### ISSUE TITLE
Incorrect memory usage for VMware instances in the metrics

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#10020]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API,UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.1, 4.19.1 
~~~

##### CONFIGURATION

Vmware vSphere

##### SUMMARY

The 'memoryintfreekbs' returned by CloudStack API listVirtualMachinesMetrics is not the 'Free' memory instead it is the memory used in the vSphere. This value is taken from MOB property of VM 'summary.quickStats.guestMemoryUsage' and used as is. 
        final String guestMemUseStr = "summary.quickStats.guestMemoryUsage";
https://github.com/apache/cloudstack/blob/546ef31aedb7c30a52f9fef0c505fa9e6968dd21/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L6513

This results in the Memory used being displayed as Memory Free. 

##### STEPS TO REPRODUCE

~~~
Compare the Memory Free/Used in VM metrics in CloudStack with vCenter/MOB. 
~~~

##### EXPECTED RESULTS

~~~
Instance metrics should list accurate memory usage. 
~~~

##### ACTUAL RESULTS

~~~
Instance metrics list incorrect memory usage. 
~~~

**Comment by DaanHoogland** [comment]
fixed in #6414
