### ISSUE TITLE
Cannot add new host in ACS

### ISSUE THREAD

**Issue by tdtmusic2** [apache/cloudstack#10094]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.2
~~~

##### CONFIGURATION

KVM hosts, CEPH RBD pool storage

##### OS / ENVIRONMENT

Almalinux 9.5

##### SUMMARY

I am trying to add a new host in ACS, there are already several hosts added and working properly. This host was configured the same way as others, same agent version. When trying to add the host I get this in the agent log:

```
ERROR [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-1:null) (logid:883a1e4a) Failed to create RBD storage pool: org.libvirt.LibvirtException: Unable to list RBD images: No such file or directory
2024-12-12 13:04:23,167 ERROR [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-1:null) (logid:883a1e4a) Failed to create the RBD storage pool, cleaning up the libvirt secret
2024-12-12 13:04:23,167 WARN  [cloud.agent.Agent] (agentRequest-Handler-1:null) (logid:883a1e4a) Caught:
com.cloud.utils.exception.CloudRuntimeException: Failed to create storage pool: c56c2378-288e-37ef-8549-ac569f7ab3b8
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.createStoragePool(LibvirtStorageAdaptor.java:743)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:364)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:358)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:42)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:35)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1929)
        at com.cloud.agent.Agent.processRequest(Agent.java:683)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1106)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

```
There's also this error but I don't think it's relevant to the main issue:

```
ERROR [utils.linux.KVMHostInfo] (Agent-Handler-1:null) (logid:) Unable to retrieve the CPU speed from file [/sys/devices/system/cpu/cpu0/cpufreq/base_frequency]
java.io.FileNotFoundException: /sys/devices/system/cpu/cpu0/cpufreq/base_frequency (No such file or directory)
```
The libvirt log has this:

```
libvirtd[3101]: 2024-12-12T12:30:05.784+0200 7f67e2003640 -1 auth: unable to find a keyring on /etc/ceph/..keyring,/etc/ceph/.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No >
libvirtd[3101]: 2024-12-12T12:30:05.785+0200 7f67e2003640 -1 auth: unable to find a keyring on /etc/ceph/..keyring,/etc/ceph/.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No >
libvirtd[3101]: 2024-12-12T12:30:05.785+0200 7f67e2003640 -1 auth: unable to find a keyring on /etc/ceph/..keyring,/etc/ceph/.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No >
libvirtd[3101]: Unable to list RBD images: No such file or directory
```

##### STEPS TO REPRODUCE

~~~
Try to add a new host in ACS.
~~~

##### EXPECTED RESULTS

~~~
Host should be added without issues.
~~~

##### ACTUAL RESULTS

~~~
Errors above.
~~~

**Comment by DaanHoogland** [comment]
@tdtmusic2 is this a libvirt version issue?

**Comment by tdtmusic2** [comment]
> @tdtmusic2 is this a libvirt version issue?

No idea, this comes with the cloudstack-agent package, I didn't install anything else on that host.

**Comment by tdtmusic2** [comment]
> is package `libvirt-daemon-driver-storage-rbd` installed ?

Hi Wei. Yes it is.

**Comment by DaanHoogland** [comment]
> > is package `libvirt-daemon-driver-storage-rbd` installed ?

@tdtmusic2 , what @weizhouapache means is check the OS package manager ; i.e. `dnf list --installed | grep libvirt-daemon-driver-storage-rbd` or `apt list --installed | grep libvirt-daemon-driver-storage-rbd`

**Comment by tdtmusic2** [comment]
> > > is package `libvirt-daemon-driver-storage-rbd` installed ?
> 
> @tdtmusic2 , what @weizhouapache means is check the OS package manager ; i.e. `dnf list --installed | grep libvirt-daemon-driver-storage-rbd` or `apt list --installed | grep libvirt-daemon-driver-storage-rbd`

I know, it is installed.
![image](https://github.com/user-attachments/assets/52e53458-3a32-4295-96ae-d2e5bf5d8dc2)

**Comment by DaanHoogland** [comment]
> > is package `libvirt-daemon-driver-storage-rbd` installed ?
> 
> This is what I could find on the manager's log:
> 
> ```
> 2024-12-12 16:22:20,356 DEBUG [c.c.s.l.StoragePoolMonitor] (AgentConnectTaskPool-30:ctx-d5cbf4cb) (logid:4690904e) Host 146 connected, connecting host to shared pool id 33 and sending storage pool information ...
> 2024-12-12 16:22:20,357 DEBUG [c.c.s.StorageManagerImpl] (AgentConnectTaskPool-30:ctx-d5cbf4cb) (logid:4690904e) Adding pool Ceph Storage to  host 146
> 2024-12-12 16:22:20,359 DEBUG [o.a.c.s.d.p.DefaultHostListener] (AgentConnectTaskPool-30:ctx-d5cbf4cb) (logid:4690904e) Sending modify storage pool command to agent: 146 for storage pool: 33 with timeout 300 seconds
> 2024-12-12 16:22:20,364 DEBUG [c.c.a.t.Request] (AgentConnectTaskPool-30:ctx-d5cbf4cb) (logid:4690904e) Seq 146-2554666888625913858: Sending  { Cmd , MgmtId: 73209801370656, via: 146(NODExx), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.ModifyStoragePoolCommand":{"add":"true","pool":{"id":"33","uuid":"c56c2378-288e-37ef-8549-ac569f7ab3b8","host":"172.xx.xx.xx,172.xx.xx.xx,172.xx.xx.xx","path":"cloudstack_RO","port":"0","type":"RBD"},"localPath":"/mnt//61b0126b-2e47-3ad5-b9c4-af4a8f0c199f","wait":"300","bypassHostMaintenance":"false"}}] }
> 2024-12-12 16:22:20,457 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-12:null) (logid:) Ping from Routing host 146(NODExx)
> 2024-12-12 16:22:20,458 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:null) (logid:) Process host VM state report from ping process. host: 146
> 2024-12-12 16:22:20,458 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:null) (logid:) Process VM state report. host: 146, number of records in report: 0
> 2024-12-12 16:22:20,458 DEBUG [c.c.a.t.Request] (AgentManager-Handler-11:null) (logid:) Seq 146-2554666888625913857: Processing:  { Ans: , MgmtId: 73209801370656, via: 146, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
> 2024-12-12 16:22:20,463 DEBUG [c.c.v.VirtualMachinePowerStateSyncImpl] (AgentManager-Handler-12:null) (logid:) Done with process of VM state report. host: 146
> 2024-12-12 16:22:20,472 INFO  [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-12:null) (logid:) PingMap for agent: 146 will not be updated because agent is no longer in the PingMap
> 2024-12-12 16:22:20,476 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-12:null) (logid:) Not processing PingRoutingCommand for agent id=0; can't find the host in the DB
> 2024-12-12 16:22:20,584 DEBUG [c.c.a.t.Request] (AgentManager-Handler-15:null) (logid:) Seq 146-2554666888625913857: Processing:  { Ans: , MgmtId: 73209801370656, via: 146, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"true","details":"","wait":"0","bypassHostMaintenance":"false"}}] }
> ```

these entries seem to be consequential, as the host is already removed from the DB. Can you try adding the host again and keep the log from the start of the API call till the end?
In addition can you add the log /var/log/cloudstack/agent/agent.log from the KVM host?

**Comment by tdtmusic2** [comment]
> 
> these entries seem to be consequential, as the host is already removed from the DB. Can you try adding the host again and keep the log from the start of the API call till the end? In addition can you add the log /var/log/cloudstack/agent/agent.log from the KVM host?
>
It will be a little tricky since there's a lot of activity in the management server logs from other hosts & stuff but I'll try to isolate anything that is related to this new host and attach it here, along with the agent log. I don't know if it matters but the only differences between this new host and the others that are already joined and working are the cpu (this one's an AMD, all others are Intel) and the fact that there's a gpu installed on it.

**Comment by weizhouapache** [comment]
@tdtmusic2 
you mentioned that the rbd storage pool is used by several hosts, is the new host same as the other hosts ? (same hardware, same OS, in the same subnet )

**Comment by tdtmusic2** [comment]
> @tdtmusic2 you mentioned that the rbd storage pool is used by several hosts, is the new host same as the other hosts ? (same hardware, same OS, in the same subnet )

The new host is on the same subnet as the others. Hardware is different, this is a Dell server with amd epyc cpu, others are hp with Intel cpus. Also this one has a gpu. The os is Almalinux on all, 9.5 and 9.4.

**Comment by tdtmusic2** [comment]
This is resolved. The issue was that the new host was not communicating with the ceph storage subnet.
