### ISSUE TITLE
GPU in passthrough mode on Xen

### ISSUE THREAD

**Issue by tdtmusic2** [apache/cloudstack#10119]
### Discussed in https://github.com/apache/cloudstack/discussions/10112

<div type='discussions-op-text'>

<sup>Originally posted by **tdtmusic2** December 16, 2024</sup>
I removed the KVM passthrough part since it seems it's a long way before it will work properly in ACS, but in Xen it should work and I do think there's a bug here. 

I tried via xcp-ng 8.2. Here the gpu is detected and after adding the host to ACS I can see that the host_gpu_groups has now a row with "Group of NVIDIA Corporation TU104GL [Tesla T4] GPUs" for that host (also the integrated gpu but that doesn't matter). vgpu_types table is also populated, with availability 1 and type passthrough. However when trying to deploy a vm with a gpu-enabled offering, I get the sql query error in ACS.

I think the sql query that ACS is trying to run is wrong. The query in the manager logs error is this:

```
SELECT host_gpu_groups.id, host_gpu_groups.group_name, host_gpu_groups.host_id FROM host_gpu_groups INNER
JOIN vgpu_types groupId ON host_gpu_groups.id=groupId.gpu_group_id WHERE host_gpu_groups.host_id = 185 
AND host_gpu_groups.group_name =x'47726f7570206f66204e766964696120436f72706f726174696f6e205455313034474c205b5465736c612054345d2047505573' AND (groupId.vgpu_type = x'706173737468726f756768' AND groupId.remaining_capacity > 0 )
ORDER BY vgpu_types.remaining_capacity DESC;
```
But if I'm running it directly in workbench I get this error: `Error Code: 1054. Unknown column 'vgpu_types.remaining_capacity' in 'order clause'`
The query should look like this (and it returns what it should, the available gpu):

```
SELECT host_gpu_groups.id, host_gpu_groups.group_name, host_gpu_groups.host_id 
FROM host_gpu_groups 
INNER JOIN vgpu_types groupId ON host_gpu_groups.id = groupId.gpu_group_id 
WHERE host_gpu_groups.host_id = 185 
  AND host_gpu_groups.group_name = x'47726f7570206f66204e766964696120436f72706f726174696f6e205455313034474c205b5465736c612054345d2047505573' 
  AND (groupId.vgpu_type = x'706173737468726f756768' 
       AND groupId.remaining_capacity > 0) 
ORDER BY groupId.remaining_capacity DESC;
```

_Originally posted by @tdtmusic2 in https://github.com/apache/cloudstack/discussions/10112#discussioncomment-11597542_
```

**Comment by rajujith** [comment]
https://github.com/apache/cloudstack/pull/9573 seems to have fixed it.

**Comment by DaanHoogland** [comment]
@tdtmusic2 , this means you can try head of the 4.19 branch or wait for 4.19.2 (which we are planning for end of Januari)
