### ISSUE TITLE
listResourceDetails: ID is not UUID, but DB ID

### ISSUE THREAD

**Issue by resmo** [apache/cloudstack#2527]
##### ISSUE TYPE

* Enhancement
* Bug 

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The respone of `listResourceDetails` includes an ID of the primary field not the UUID

##### STEPS TO REPRODUCE

~~~
 $ cs listResourceDetails resourcetype=uservm resourceid=d949e443-9bc8-4399-9e09-842bbb395cae --region=simulator     
~~~

##### EXPECTED RESULTS

~~~
{
  "count": 3, 
  "resourcedetail": [
    {
      "fordisplay": true, 
      "key": "foo", 
      "resourceid": "d949e443-9bc8-4399-9e09-842bbb395cae", 
      "resourcetype": "UserVm", 
      "value": "bar"
    }, 
~~~

##### ACTUAL RESULTS

~~~
{
  "count": 3, 
  "resourcedetail": [
    {
      "fordisplay": true, 
      "key": "foo", 
      "resourceid": "5", 
      "resourcetype": "UserVm", 
      "value": "bar"
    }, 
~~~

**Comment by DaanHoogland** [comment]
is there a PR planned for this? if not i'll mark it 4.12

**Comment by dhlaluku** [comment]
@resmo I can confirm this behavior.

@DaanHoogland @rhtyd I will work on a fix for this and create a PR.

**Comment by anuragaw** [comment]
@resmo , @rhtyd , @DaanHoogland , @dhlaluku - I've pushed a fix for this and a pull request is open for review. Thanks!
