### ISSUE TITLE
listVirtualMachines response ostypeid is foreign DB ID, not UUID

### ISSUE THREAD

**Issue by resmo** [apache/cloudstack#2528]
##### ISSUE TYPE

 * Bug Report
 * Enhancement

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

N/A 

##### OS / ENVIRONMENT

N/A 

##### SUMMARY

The response of `listVirtualMachines` contains the ostypeid returned as foreignkey ID of the DB, instead of UUID

##### STEPS TO REPRODUCE

~~~
cs listVirtualMachines id=d949e443-9bc8-4399-9e09-842bbb395cae --region simulator | jq '.virtualmachine[].ostypeid'
~~~

##### EXPECTED RESULTS

~~~
...
"ostypeid": "1ef04fab-4b9a-11e7-8fea-0242ac110003",
...
~~~

##### ACTUAL RESULTS

~~~
...
"ostypeid": 142, 
...
~~~

**Comment by rhtyd** [comment]
For reference, the fix broke packer for 4.11.3+, 4.12.0+ etc: https://github.com/xanzy/go-cloudstack/issues/117
