### ISSUE TITLE
registered windows10 ISO

### ISSUE THREAD

**Issue by LYXmoonstars** [apache/cloudstack#2531]
I registered windows10 ISO
, creating an instance, unable to create, indicating that Windows system error has been restarted and unable to enter the system. I think it is not compatible with windows10.
![qq 20180404121647](https://user-images.githubusercontent.com/20179689/38302102-1aeffda6-3834-11e8-8039-1b724d6cbdb5.png)

**Comment by resmo** [comment]
Also important is to select the right disk driver and it only works since > 4.6 AFAIR. Please head to mailing list. 

Closing this issue due to more like a question how to run windows VMs in cloudstack/hypervisor.
