### ISSUE TITLE
Fix Jetty configuration file bugs during Upgrade from 4.x to 4.11

### ISSUE THREAD

**Issue by ernjvr** [apache/cloudstack#2537]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
packaging
~~~

##### CLOUDSTACK VERSION

~~~
4.11
master
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The `packaging/centos7/cloud.spec` file line 400 moves the `%{_sysconfdir}/sysconfig/%{name}-management` file to `%{_sysconfdir}/default/%{name}-management`.
This is unnecessary because  the file contains the deprecated tomcat configurations. Moving it prevents the 4.11 upgrade from overwriting the old file with the new jetty configurations file. 

Also `systemctl daemon-reload` command needs to be added to the end of the `%post` management step in order to refresh daemon services so that management server can start up seamlessly after the upgrade.

##### STEPS TO REPRODUCE

To Reproduce: install version 4.6 of cloudstack. 
Update Systemvm templates. http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.11.0.0/upgrade/upgrade-4.5.html#update-system-vm-templates
Stop management server and usage server.
Do database backup.
Change the /etc/yum.repos.d/cloudstack.repo file to upgrade to 4.11.
Do sudo yum upgrade cloudstack-management.
After upgrade it fails to start the management server because:
1) the less /etc/default/cloudstack-management file still contains the old tomcat configurations and not the new 4.11 Jetty server configurations.
2) the systemctl daemon-reload needs to be executed to relaod the daemon services

~~~
systemctl stop cloudstack-management
systemctl stop cloudstack-usage
mysqldump -u root -p cloud > cloud-backup_`date '+%Y-%m-%d'`.sql
mysqldump -u root -p cloud_usage > cloud_usage-backup_`date '+%Y-%m-%d'`.sql
vi /etc/yum.repos.d/cloudstack.repo
sudo yum upgrade cloudstack-management
sudo yum upgrade cloudstack-usage
systemctl start cloudstack-management
systemctl start cloudstack-usage
~~~

##### EXPECTED RESULTS

~~~
after upgrade:
less /etc/default/cloudstack-management should show the new jetty server environment variables
management server should start up successfully without manually executing systemctl daemon-reload
able to log in to the UI  
~~~

##### ACTUAL RESULTS

management server failed to start and returned an error message "Job for cloudstack-management.service failed because the control process exited with error code. ..."

~~~
systemctl start cloudstack-management produced the above error output
~~~

**Comment by rhtyd** [comment]
@ernjvr please use something like 'This fixes \#id' to link an issue with a PR. Also, if you already have a fix, you don't need to create an issue for that. Simply open a PR with details like you've posted here. And while opening either a PR or an issue, please fill in the milestone and label details.
