### ISSUE TITLE
CloudStack-Usage Broken after Upgrade from 4.9 to 4.11

### ISSUE THREAD

**Issue by mdesaive** [apache/cloudstack#2542]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloudstack-Usage
~~~

##### CLOUDSTACK VERSION

~~~
4.11
4.9
~~~

##### OS / ENVIRONMENT

Management Server Ubuntu 14.04 with repo:
deb http://packages.shapeblue.com/cloudstack/upstream/debian/4.11 /

##### SUMMARY

After upgrading from CloudStack 4.9 to 4.11 as described in 
http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.11.0.0/upgrade/upgrade-4.9.html
cloudstack-usage does no longer startup.

##### STEPS TO REPRODUCE

~~~
Do upgrade as in http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.11.0.0/upgrade/upgrade-4.9.html
service cloudstack-usage start
~~~

##### EXPECTED RESULTS

~~~
"service cloudstack-usage status" should show a correctly running service.
~~~

##### ACTUAL RESULTS

~~~
"service cloudstack-usage status" indicates that cloudstack-usage is not running.
~~~

**Comment by mdesaive** [comment]
Stephan found out, that the update didn't clean old libs from /usr/share/cloudstack-usage/libs. For us cleanup and reinstall fixed that.

**Comment by s-seitz** [comment]
Attached is a diff from a working and a non-working (updated) setup. It shows in the non-working setup a lot of jar's from the pre-update are getting loaded.

root@acs-management-1:~# diff -u cloudstack-usage-process-libs-not-working cloudstack-usage-process-libs-working
--- cloudstack-usage-process-libs-not-working	2018-04-04 09:54:15.901380256 +0200
+++ cloudstack-usage-process-libs-working	2018-04-04 09:54:06.805281679 +0200
@@ -6,247 +6,119 @@
 /usr/share/java/mysql-connector-java.jar
 /usr/share/cloudstack-usage/lib/activation-1.1.jar
 /usr/share/cloudstack-usage/lib/animal-sniffer-annotations-1.14.jar
-/usr/share/cloudstack-usage/lib/antisamy-1.4.3.jar
 /usr/share/cloudstack-usage/lib/antisamy-1.5.3.jar
 /usr/share/cloudstack-usage/lib/apache-log4j-extras-1.2.17.jar
 /usr/share/cloudstack-usage/lib/aspectjweaver-1.8.13.jar
-/usr/share/cloudstack-usage/lib/aspectjweaver-1.8.4.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-api-gateway-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-autoscaling-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudformation-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudfront-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudhsm-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudsearch-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudtrail-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudwatch-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cloudwatchmetrics-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-codecommit-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-codedeploy-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-codepipeline-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cognitoidentity-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-cognitosync-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-config-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-core-1.10.34.jar
 /usr/share/cloudstack-usage/lib/aws-java-sdk-core-1.11.213.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-datapipeline-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-devicefarm-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-directconnect-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-directory-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-dynamodb-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-ec2-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-ecs-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-efs-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-elasticache-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-elasticbeanstalk-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-elasticloadbalancing-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-elasticsearch-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-elastictranscoder-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-emr-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-glacier-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-iam-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-importexport-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-inspector-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-iot-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-kinesis-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-kms-1.10.34.jar
 /usr/share/cloudstack-usage/lib/aws-java-sdk-kms-1.11.213.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-lambda-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-logs-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-machinelearning-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-marketplacecommerceanalytics-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-opsworks-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-rds-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-redshift-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-route53-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-s3-1.10.34.jar
 /usr/share/cloudstack-usage/lib/aws-java-sdk-s3-1.11.213.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-ses-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-simpledb-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-simpleworkflow-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-sns-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-sqs-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-ssm-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-storagegateway-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-sts-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-support-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-swf-libraries-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-waf-1.10.34.jar
-/usr/share/cloudstack-usage/lib/aws-java-sdk-workspaces-1.10.34.jar
 /usr/share/cloudstack-usage/lib/batik-constants-1.9.1.jar
-/usr/share/cloudstack-usage/lib/batik-css-1.7.jar
 /usr/share/cloudstack-usage/lib/batik-css-1.9.1.jar
-/usr/share/cloudstack-usage/lib/batik-ext-1.7.jar
 /usr/share/cloudstack-usage/lib/batik-i18n-1.9.1.jar
-/usr/share/cloudstack-usage/lib/batik-util-1.7.jar
 /usr/share/cloudstack-usage/lib/batik-util-1.9.1.jar
 /usr/share/cloudstack-usage/lib/bcpkix-jdk15on-1.59.jar
-/usr/share/cloudstack-usage/lib/bcprov-jdk15-1.46.jar
 /usr/share/cloudstack-usage/lib/bcprov-jdk15on-1.59.jar
-/usr/share/cloudstack-usage/lib/bcprov-jdk16-1.46.jar
 /usr/share/cloudstack-usage/lib/bsh-core-2.0b4.jar
-/usr/share/cloudstack-usage/lib/cglib-nodep-3.1.jar
 /usr/share/cloudstack-usage/lib/cglib-nodep-3.2.5.jar
 /usr/share/cloudstack-usage/lib/checker-compat-qual-2.0.0.jar
 /usr/share/cloudstack-usage/lib/cloud-api-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-api-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-core-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-core-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-engine-api-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-engine-api-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-engine-components-api-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-engine-components-api-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-engine-schema-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-engine-schema-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-ca-4.11.0.0.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-cluster-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-cluster-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-config-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-config-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-db-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-db-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-direct-download-4.11.0.0.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-events-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-events-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-ipc-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-ipc-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-jobs-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-jobs-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-managed-context-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-managed-context-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-quota-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-quota-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-rest-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-rest-4.8.0.1.jar
 /usr/share/cloudstack-usage/lib/cloud-framework-security-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-framework-security-4.8.0.1.jar
-/usr/share/cloudstack-usage/lib/cloudstack-usage.jar
 /usr/share/cloudstack-usage/lib/cloud-utils-4.11.0.0.jar
-/usr/share/cloudstack-usage/lib/cloud-utils-4.8.0.1.jar
-/usr/share/cloudstack-usage/lib/commons-beanutils-1.8.3.jar
+/usr/share/cloudstack-usage/lib/cloudstack-usage.jar
 /usr/share/cloudstack-usage/lib/commons-beanutils-1.9.2.jar
-/usr/share/cloudstack-usage/lib/commons-beanutils-core-1.7.0.jar
 /usr/share/cloudstack-usage/lib/commons-codec-1.11.jar
-/usr/share/cloudstack-usage/lib/commons-collections-3.2.1.jar
 /usr/share/cloudstack-usage/lib/commons-collections-3.2.2.jar
 /usr/share/cloudstack-usage/lib/commons-compress-1.15.jar
 /usr/share/cloudstack-usage/lib/commons-configuration-1.10.jar
 /usr/share/cloudstack-usage/lib/commons-daemon-1.1.0.jar
 /usr/share/cloudstack-usage/lib/commons-dbcp-1.4.jar
 /usr/share/cloudstack-usage/lib/commons-digester-1.8.1.jar
-/usr/share/cloudstack-usage/lib/commons-digester-1.8.jar
-/usr/share/cloudstack-usage/lib/commons-fileupload-1.2.jar
 /usr/share/cloudstack-usage/lib/commons-fileupload-1.3.3.jar
 /usr/share/cloudstack-usage/lib/commons-httpclient-3.1.jar
 /usr/share/cloudstack-usage/lib/commons-io-2.6.jar
 /usr/share/cloudstack-usage/lib/commons-lang-2.6.jar
 /usr/share/cloudstack-usage/lib/commons-lang3-3.6.jar
 /usr/share/cloudstack-usage/lib/commons-logging-1.2.jar
-/usr/share/cloudstack-usage/lib/commons-net-3.3.jar
 /usr/share/cloudstack-usage/lib/commons-net-3.6.jar
 /usr/share/cloudstack-usage/lib/commons-pool-1.6.jar
-/usr/share/cloudstack-usage/lib/commons-validator-1.4.0.jar
 /usr/share/cloudstack-usage/lib/commons-validator-1.6.jar
-/usr/share/cloudstack-usage/lib/cxf-bundle-jaxrs-2.7.13.jar
 /usr/share/cloudstack-usage/lib/cxf-core-3.2.0.jar
 /usr/share/cloudstack-usage/lib/cxf-rt-frontend-jaxrs-3.2.0.jar
 /usr/share/cloudstack-usage/lib/cxf-rt-transports-http-3.2.0.jar
 /usr/share/cloudstack-usage/lib/ehcache-core-2.6.11.jar
-/usr/share/cloudstack-usage/lib/ehcache-core-2.6.9.jar
 /usr/share/cloudstack-usage/lib/error_prone_annotations-2.1.3.jar
 /usr/share/cloudstack-usage/lib/esapi-2.1.0.1.jar
-/usr/share/cloudstack-usage/lib/esapi-2.1.0.jar
 /usr/share/cloudstack-usage/lib/gson-1.7.2.jar
-/usr/share/cloudstack-usage/lib/guava-18.0.jar
 /usr/share/cloudstack-usage/lib/guava-23.6-jre.jar
 /usr/share/cloudstack-usage/lib/guava-testlib-18.0.jar
 /usr/share/cloudstack-usage/lib/httpclient-4.5.4.jar
-/usr/share/cloudstack-usage/lib/httpclient-4.5.jar
 /usr/share/cloudstack-usage/lib/httpcore-4.4.8.jar
-/usr/share/cloudstack-usage/lib/httpcore-4.4.jar
 /usr/share/cloudstack-usage/lib/ion-java-1.0.2.jar
 /usr/share/cloudstack-usage/lib/j2objc-annotations-1.1.jar
-/usr/share/cloudstack-usage/lib/jackson-annotations-2.6.0.jar
 /usr/share/cloudstack-usage/lib/jackson-annotations-2.9.0.jar
-/usr/share/cloudstack-usage/lib/jackson-core-2.6.3.jar
 /usr/share/cloudstack-usage/lib/jackson-core-2.9.2.jar
-/usr/share/cloudstack-usage/lib/jackson-databind-2.6.3.jar
 /usr/share/cloudstack-usage/lib/jackson-databind-2.9.2.jar
 /usr/share/cloudstack-usage/lib/jackson-dataformat-cbor-2.6.7.jar
-/usr/share/cloudstack-usage/lib/jackson-jaxrs-base-2.6.3.jar
 /usr/share/cloudstack-usage/lib/jackson-jaxrs-base-2.9.2.jar
-/usr/share/cloudstack-usage/lib/jackson-jaxrs-json-provider-2.6.3.jar
 /usr/share/cloudstack-usage/lib/jackson-jaxrs-json-provider-2.9.2.jar
-/usr/share/cloudstack-usage/lib/jackson-module-jaxb-annotations-2.6.3.jar
 /usr/share/cloudstack-usage/lib/jackson-module-jaxb-annotations-2.9.2.jar
 /usr/share/cloudstack-usage/lib/jasypt-1.9.2.jar
-/usr/share/cloudstack-usage/lib/java-ipv6-0.15.jar
 /usr/share/cloudstack-usage/lib/java-ipv6-0.16.jar
 /usr/share/cloudstack-usage/lib/javassist-3.22.0-GA.jar
 /usr/share/cloudstack-usage/lib/javax.annotation-api-1.3.jar
 /usr/share/cloudstack-usage/lib/javax.inject-1.jar
-/usr/share/cloudstack-usage/lib/javax.persistence-2.1.0.jar
 /usr/share/cloudstack-usage/lib/javax.persistence-2.2.0.jar
 /usr/share/cloudstack-usage/lib/javax.servlet-api-4.0.0.jar
 /usr/share/cloudstack-usage/lib/javax.ws.rs-api-2.1.jar
 /usr/share/cloudstack-usage/lib/jmespath-java-1.11.213.jar
 /usr/share/cloudstack-usage/lib/joda-time-2.8.1.jar
-/usr/share/cloudstack-usage/lib/jsch-0.1.51.jar
 /usr/share/cloudstack-usage/lib/jsch-0.1.54.jar
 /usr/share/cloudstack-usage/lib/jsr305-1.3.9.jar
 /usr/share/cloudstack-usage/lib/log4j-1.2.17.jar
-/usr/share/cloudstack-usage/lib/mail-1.4.7.jar
 /usr/share/cloudstack-usage/lib/mail-1.5.0-b01.jar
-/usr/share/cloudstack-usage/lib/nekohtml-1.9.12.jar
 /usr/share/cloudstack-usage/lib/nekohtml-1.9.16.jar
 /usr/share/cloudstack-usage/lib/not-yet-commons-ssl-0.3.9.jar
 /usr/share/cloudstack-usage/lib/objenesis-2.1.jar
-/usr/share/cloudstack-usage/lib/opensaml-2.6.1.jar
 /usr/share/cloudstack-usage/lib/opensaml-2.6.4.jar
-/usr/share/cloudstack-usage/lib/openws-1.5.1.jar
 /usr/share/cloudstack-usage/lib/openws-1.5.4.jar
-/usr/share/cloudstack-usage/lib/powermock-core-1.5.3.jar
 /usr/share/cloudstack-usage/lib/powermock-core-1.6.4.jar
-/usr/share/cloudstack-usage/lib/powermock-module-junit4-1.5.3.jar
 /usr/share/cloudstack-usage/lib/powermock-module-junit4-1.6.4.jar
-/usr/share/cloudstack-usage/lib/powermock-module-junit4-common-1.5.3.jar
 /usr/share/cloudstack-usage/lib/powermock-module-junit4-common-1.6.4.jar
-/usr/share/cloudstack-usage/lib/powermock-reflect-1.5.3.jar
 /usr/share/cloudstack-usage/lib/powermock-reflect-1.6.4.jar
 /usr/share/cloudstack-usage/lib/reflections-0.9.11.jar
-/usr/share/cloudstack-usage/lib/reflections-0.9.9.jar
-/usr/share/cloudstack-usage/lib/serializer-2.7.1.jar
 /usr/share/cloudstack-usage/lib/slf4j-api-1.7.22.jar
-/usr/share/cloudstack-usage/lib/slf4j-api-1.7.7.jar
 /usr/share/cloudstack-usage/lib/slf4j-log4j12-1.7.22.jar
-/usr/share/cloudstack-usage/lib/slf4j-log4j12-1.7.7.jar
-/usr/share/cloudstack-usage/lib/spring-aop-3.2.12.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-aop-5.0.2.RELEASE.jar
-/usr/share/cloudstack-usage/lib/spring-beans-3.2.12.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-beans-5.0.2.RELEASE.jar
-/usr/share/cloudstack-usage/lib/spring-context-3.2.12.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-context-5.0.2.RELEASE.jar
-/usr/share/cloudstack-usage/lib/spring-core-3.2.12.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-core-5.0.2.RELEASE.jar
-/usr/share/cloudstack-usage/lib/spring-expression-3.2.12.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-expression-5.0.2.RELEASE.jar
 /usr/share/cloudstack-usage/lib/spring-jcl-5.0.2.RELEASE.jar
 /usr/share/cloudstack-usage/lib/stax2-api-3.1.4.jar
-/usr/share/cloudstack-usage/lib/trilead-ssh2-1.0.0-build217.jar
 /usr/share/cloudstack-usage/lib/trilead-ssh2-1.0.0-build221.jar
 /usr/share/cloudstack-usage/lib/truth-0.23.jar
 /usr/share/cloudstack-usage/lib/velocity-1.7.jar
 /usr/share/cloudstack-usage/lib/woodstox-core-5.0.3.jar
 /usr/share/cloudstack-usage/lib/xalan-2.7.0.jar
-/usr/share/cloudstack-usage/lib/xalan-2.7.1.jar
-/usr/share/cloudstack-usage/lib/xercesImpl-2.10.0.jar
 /usr/share/cloudstack-usage/lib/xercesImpl-2.8.0.jar
 /usr/share/cloudstack-usage/lib/xmlgraphics-commons-2.2.jar
-/usr/share/cloudstack-usage/lib/xml-resolver-1.2.jar
 /usr/share/cloudstack-usage/lib/xmlschema-core-2.2.2.jar
-/usr/share/cloudstack-usage/lib/xmlsec-1.5.6.jar
 /usr/share/cloudstack-usage/lib/xmlsec-1.5.7.jar
-/usr/share/cloudstack-usage/lib/xmltooling-1.4.1.jar
 /usr/share/cloudstack-usage/lib/xmltooling-1.4.4.jar
 /usr/share/cloudstack-usage/lib/xom-1.2.5.jar

**Comment by rhtyd** [comment]
@s-seitz I'm not sure why upgrade did not remove old files, I'll send a fix that removes old jars as part of the upgrade. On CentOS, old jars are erased before new files are installed.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/2552
