### ISSUE TITLE
Textbox "Account and projectId can't be specified together"

### ISSUE THREAD

**Issue by mdesaive** [apache/cloudstack#2543]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

When I view the "Networks" view after selecting a project in the web-UI a textbox with the message "Account and projectId can't be specified together" has to be confirmed.

##### STEPS TO REPRODUCE

~~~
Log in to the web-UI.
Select a project.
Select the "Network" view
~~~

##### EXPECTED RESULTS

~~~
No textbox. ;)
~~~

##### ACTUAL RESULTS

~~~
A textbox with the message "Account and projectId can't be specified together" has to be confirmed.
~~~

**Comment by mdesaive** [comment]
A screenshot of the textbox:
![textbox-web-ui](https://user-images.githubusercontent.com/17803067/38418136-720ac64e-399b-11e8-9ab8-71a28e40d420.png)

**Comment by rhtyd** [comment]
FYI - we had a similar fix for projects view - https://github.com/apache/cloudstack/pull/2464 /cc @DaanHoogland @PaulAngus

**Comment by rhtyd** [comment]
Checked, fixed in https://github.com/apache/cloudstack/pull/2464 @mdesaive you may test the fix using diff from the PR (https://github.com/apache/cloudstack/pull/2464/files)
