### ISSUE TITLE
Password Reset does not work with Isolated Networks with redundant routers

### ISSUE THREAD

**Issue by s-seitz** [apache/cloudstack#2544]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

Advanced Network, Isolated Network with Redundant Router and DNS, DHCP, Passwort, etc. Feateres all on

##### SUMMARY

When using the cloudstack-set-guest-password skript, the query is done against http://IP-OF-THE-DHCP-SERVER-THAT-SERVED-THE-LEASE:8080

A quick peek inside the MASTER of a redundant router setup shows, that the service (python) is only listening to the service-IP (the default gateway)

Firewall instead shows that port 8080 is open for both host- and service-IP.

##### STEPS TO REPRODUCE

Deploy a VM connected to an Isolated Network with redundant routers and use /etc/init.d/cloudstack-set-guest-password inside the VM 

wget just silently quits, telnet shows a "connection refused"

SSH keys are not affected since the pubkeys are deliverd by another service.

~~~

~~~

##### EXPECTED RESULTS

~~~
Getting the password via DHCP-SERVER-HOST-IP:8080
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@s-seitz can you share the `cloudstack-set-guest-password` password that you've used?

**Comment by rhtyd** [comment]
@s-seitz ignore if this is same as: https://github.com/apache/cloudstack/blob/4.11/setup/bindir/cloud-set-guest-password.in

**Comment by rhtyd** [comment]
Addressed fix in https://github.com/apache/cloudstack/pull/2635, closing now. @s-seitz you can test the PR, thanks.

**Comment by s-seitz** [comment]
@rhtyd i've cherrypicked #2635 and tested the password reset successfully. Thank You!
