### ISSUE TITLE
dedicatePublicIpRange to domain doesn't work

### ISSUE THREAD

**Issue by se-bre** [apache/cloudstack#2545]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Network (Public)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
Ubuntu 16.04 (Management/Hypervisor)
KVM

##### SUMMARY
dedicate a public IP range to a domain doesn't work

##### STEPS TO REPRODUCE

~~~
create a new (should not be the first) public IP range  
dedicate this range to a domain
acquire a new public IP in a project which is located in the specified domain
~~~

##### EXPECTED RESULTS

~~~
get a IP which is located in the specified IP range for this domain
~~~

##### ACTUAL RESULTS

~~~
ip is acquired from an other public pool (first created public IP range - with no assignment for domain)
~~~

**Comment by rhtyd** [comment]
Since a project can tie users/accounts from different domains, IP range dedicated to an account/domain cannot be used by a project. Can you advise exactly how you were testing this? /cc @PaulAngus

**Comment by rhtyd** [comment]
I've removed this from 4.11.1.0 until we can conclude that this is a valid bug.

**Comment by se-bre** [comment]
hi rohit, hi paul,
we create a domain for each customer.
some customers come with their own public ip range.
so we dedicate those ip ranges to their domain.
the result is, that they build up their own projects and they can use their own public ip range in all their projects in their domain
this was working up to 4.9 (4.10 untested from our side)

when we dedicate a public ip range to a domain now, this isn't working any more - they will  get a ip from an other range. 

br, sebastian

@rhtyd @PaulAngus

**Comment by se-bre** [comment]
we are not 100% sure, but we may found the commit where the relavant code was removed:

https://github.com/apache/cloudstack/commit/b2f7f9abb6f710e1ec0ba9b03a645023abd0d649#diff-0f5b97d5dceac89ff4509fbcf07d2330

File: server/src/com/cloud/network/IpAddressManagerImpl.java
Lines: 712 - 716

don't know if there was a reason for this @priyankparihar

**Comment by IngoJochim** [comment]
Da bin ich ja mal auf die Antwort gespannt.
VG
Ingo

Am 16.05.2018 um 10:33 schrieb S. Bretschneider <notifications@github.com<mailto:notifications@github.com>>:


we are not 100% sure, but we may found the commit where the relavant code was removed:

b2f7f9a#diff-0f5b97d5dceac89ff4509fbcf07d2330<https://github.com/apache/cloudstack/commit/b2f7f9abb6f710e1ec0ba9b03a645023abd0d649#diff-0f5b97d5dceac89ff4509fbcf07d2330>

File: server/src/com/cloud/network/IpAddressManagerImpl.java
Lines: 712 - 716

don't know if there was a reason for this @priyankparihar<https://github.com/priyankparihar>

**Comment by PaulAngus** [comment]
I've confirmed that this behaviour used to work in 4.9.3 (projects would use IP dedicated to the domain that the project was in) and no longer works in 4.11.0  cc @DaanHoogland

**Comment by DaanHoogland** [comment]
@se-bre can you code your steps to reproduce in a marvin test (or otherwise a small script)?
