### ISSUE TITLE
API uploadSslCert does not work

### ISSUE THREAD

**Issue by s-seitz** [apache/cloudstack#2558]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

Advanced Networking, Cloudstack 4.11.0.0 on Ubuntu 14.04 LTS, MySQL 5.5.59-0ubuntu0.14.04.1

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS
##### SUMMARY

Uploading sslcertificates ( https://cloudstack.apache.org/api/apidocs-4.11/apis/uploadSslCert.html ) fails for two reasons.
a) Including the CertChain, it's very likely that the Request Header Size grows > 8k and results in HTTP Error 414.
b) Leaving the CertChain empty to get a shorter GET Request, the Cloudstack API responds with Error 530: DB Exception on: com.mysql.jdbc.JDBC4PreparedStatement@7ba59657

##### STEPS TO REPRODUCE

~~~

Here 's the sample output of a response. For obvious reasons the certificate, key and fingerprint  as well as the name are redacted.

Error 530: DB Exception on: com.mysql.jdbc.JDBC4PreparedStatement@7ba59657: INSERT INTO sslcerts (sslcerts.id, sslcerts.uuid, sslcerts.certificate, sslcerts.chain, sslcerts.key, sslcerts.password, sslcerts.account_id, sslcerts.domain_id, sslcerts.fingerprint, sslcerts.name) VALUES (null, _binary'4ed417b3-77b6-42bf-9a82-81ed25aaedc2', _binary'-----BEGIN CERTIFICATE-----\n R E D A C T E D \n-----END CERTIFICATE-----', null, _binary'K E Y R E D A C T E D==', null, 160, 2, _binary'00:11:22:33:44:55:66:77:88:F7:AE:73:81:BA:D9:B7:AF:46:D8:E2:F8:EA:7C:FF:00:B7:DE:F7:D7:CF:9B:C9', _binary'STAR.some.tld')
errorcode,uuidList,cserrorcode,errortext



~~~

##### EXPECTED RESULTS

~~~

One would expect a certificate available to select after uploading it.

~~~

##### ACTUAL RESULTS

~~~


~~~

**Comment by rhtyd** [comment]
@GabrielBrascher can you pick this up as well? Thanks.

**Comment by GabrielBrascher** [comment]
Yes @rhtyd, I will take a look at it.

**Comment by rhtyd** [comment]
@GabrielBrascher any update on this, thanks.

**Comment by PaulAngus** [comment]
@GabrielBrascher  - we're looking to cut an RC soonish, do you have an eta for a fix please?

**Comment by GabrielBrascher** [comment]
@rhtyd  @PaulAngus sorry for the delay but I am still working on this one. Do you think we should push this to 4.11.2? How much time do I have to finish it for 4.11.1?

**Comment by DaanHoogland** [comment]
:) -(a weekend)
The question is not how much time you have but how much we need this in, @GabrielBrascher

**Comment by rhtyd** [comment]
@GabrielBrascher can you at least help test this against a normal certificate of size less than 8k? Usually certificates are 2k-4k in size. If there are no blockers around using custom certificates, then yes we can discuss pushing it for 4.11.2.0 milestone.

**Comment by GabrielBrascher** [comment]
We are making a GET request, not a POST. I created PR [2661](https://github.com/apache/cloudstack/pull/2661) to fix it.
