### ISSUE TITLE
Web UI is not responsive

### ISSUE THREAD

**Issue by jorgesumle** [apache/cloudstack#2565]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
Latest
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Web browser

##### SUMMARY

The web UI is not responsive.

##### STEPS TO REPRODUCE

~~~
Open the website UI in a small monitor. I tried in a 1024x768 screen. In smaller screens will be even worse.
~~~

##### EXPECTED RESULTS

~~~
A responsive website
~~~

##### ACTUAL RESULTS

~~~
It wasn't responsive, and I had to scroll. 
~~~

**Comment by rhtyd** [comment]
The UI assumes 1920x1080 (modern screens). The entire UI include CSS and widgets would need to be re-written in order to support responsiveness, which we'll ensure for the next-gen UI.
