### ISSUE TITLE
Errors in Spanish translation

### ISSUE THREAD

**Issue by jorgesumle** [apache/cloudstack#2569]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
latest
~~~

##### OS / ENVIRONMENT

N/A

##### SUMMARY

There are some errors in the Spanish translation: "esta" when used as a verb should be written "está", text have two spaces between words, "mio" is incorrect (it should be "mío").

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
I expected a good translation
~~~

##### ACTUAL RESULTS

~~~
It had some errors.
~~~

**Comment by DagSonsteboSB** [comment]
Jorge - this is an open source project and we rely on native speakers in the CloudStack community to update and correct translations. 

If there are errors can you fix them and raise a pull request so this can be improved going forward. The Spanish translation file can be found in:

https://github.com/apache/cloudstack/blob/master/ui/l10n/es.js

**Comment by rhtyd** [comment]
@jorgesumle thanks for the issue and the PR. As requested on the PR you sent, we use transifex to do the translations, please use that for changing/fixing translation used in CloudStack. The updated translations are committed to CloudStack and open, even though transifex maybe a private service.
You can look at the following on how you can participate.
https://github.com/apache/cloudstack/blob/master/tools/transifex/README-transifex.txt
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Update+L10N+files+from+Transifex+to+git+repo
I'll close this issue as this is something that should be solved via transifex.
