### ISSUE TITLE
Latest Docker container is broken

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#2581]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Docker
~~~

##### CLOUDSTACK VERSION

~~~
Master branch (15afc35)
~~~

##### CONFIGURATION

No configuration at all, just ran the docker container with the command specified on:

https://hub.docker.com/r/cloudstack/simulator/

##### OS / ENVIRONMENT

Docker 17.12.0-ce running on Ubuntu 16.04.3 LTS

##### SUMMARY

The container stops doing anything after setting up mysqld (and restarting it around 8 times) and the web server on port 8080 returns error 503 Service Unavailable.

##### STEPS TO REPRODUCE

~~~
docker pull cloudstack/simulator
docker run --name cloudstack -d -p 8080:8080 cloudstack/simulator
<open browser at http://localhost:8080/client/>
~~~

##### EXPECTED RESULTS

~~~
A functional Cloudstack dashboard
~~~

##### ACTUAL RESULTS

~~~
503 Service Unavailable

Powered by Jetty
~~~

**Comment by rhtyd** [comment]
@pdion891 @swill any ideas who maintains the docker image? Can you help?

**Comment by khos2ow** [comment]
I'll take a look.

**Comment by rhtyd** [comment]
The https://hub.docker.com/r/cloudstack/simulator/tags/ is not officially supported/maintained. @Overv kindly have a look at `tools/docker` and build your own image. It's possible it's not maintained and may need bugfixing in which case you can send a PR. Closing on this remark.
