### ISSUE TITLE
No volume name and virtualmachine ID in volume usagerecord

### ISSUE THREAD

**Issue by AlexanderStock** [apache/cloudstack#2604]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

~~~
Usage (Usagerecords)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

~~~
advanced networking
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu 16.04 
~~~

##### SUMMARY
If the usagerecords of a volume are queried, the result does not contain the name of the volume or the virtualmachineid of the VM the volume is attached to.
It just contains a description with the internal volumeid.

For processing this data in some 3rd party tools, it would be helpfull to know how the volume is called and on which VM it was attached in the timeframe of the usagerecord.

##### STEPS TO REPRODUCE

~~~
http://<cloudstack>/client/api/?command=listUsageRecords&startdate=<startdate>&enddate=<enddate>&type=6
~~~

##### EXPECTED RESULTS

~~~
The data should contain the volume name and the virtualmachine id if the volume is attached to a VM.
~~~

##### ACTUAL RESULTS

~~~
No volume name or virtualmachine id is delivered.
~~~

**Comment by rhtyd** [comment]
@AlexanderStock can you advise if this used to work in previous versions? It is possible that granular usage data may not be available for a resource within an account.

**Comment by rhtyd** [comment]
This is now fixed under https://github.com/apache/cloudstack/pull/3344 which will export both vm and volume name and UUIDs wherever applicable.
