### ISSUE TITLE
Using the simulator to run tests

### ISSUE THREAD

**Issue by marcaurele** [apache/cloudstack#2609]
##### ISSUE TYPE
 * Bug Report
 * Documentation Report

##### COMPONENT NAME

~~~
simulator, test, marvin
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY
Trying to run the simulator and to perform the integration tests, the maven command to call Marvin to deploy the DC and run the test is failing: http://docs.cloudstack.apache.org/en/latest/developer_guide.html#using-the-simulator

##### STEPS TO REPRODUCE

Perform the steps in the [simulator documentation](http://docs.cloudstack.apache.org/en/latest/developer_guide.html#using-the-simulator) and the step to perform the integration tests is failing.

~~~
mvn -Pdeveloper,marvin.setup -Dmarvin.config=setup/dev/basic.cfg -pl :cloud-marvin integration-test
~~~

##### EXPECTED RESULTS

~~~
Tests running successfully
~~~

##### ACTUAL RESULTS

~~~
[DEBUG] Executing command line: python deployAndRun.py -c /home/marco/code/cloudstack-public/setup/dev/basic.cfg -d /home/marco/code/cloudstack-public/tools/marvin/marvin/testSetupSuccess.py
Usage: deployAndRun.py [options]

deployAndRun.py: error: no such option: -c
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.641 s
[INFO] Finished at: 2018-04-27T15:00:31+02:00
[INFO] Final Memory: 62M/449M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pre-integration-test) on project cloud-marvin: Command execution failed.: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
~~~

Related to this PR I'm trying to test locally https://github.com/apache/cloudstack/pull/2428

**Comment by rhtyd** [comment]
@marcaurele see Travis related scripts, Travis uses simulator to run test (the wiki/docs may be old and needs to be updated):
https://github.com/apache/cloudstack/tree/master/tools/travis
You can also use a KVM based box (on Linux) to run a local env, run tests etc: https://github.com/rhtyd/monkeybox

**Comment by marcaurele** [comment]
Thanks @rhtyd , I'll update the documentation/pom with the correct command too

**Comment by skattoju3** [comment]
Seem to have missed it .. What is the correct command ?

**Comment by rhtyd** [comment]
The entire developer guide needs fixing, I'll take this as a background task. Closing this as the commands could be found.

**Comment by skattoju3** [comment]
Hey Rohit,

Just ran / running through it.. anyway I can contribute ?  ( not sure how to )

BR/Sid

**Comment by rhtyd** [comment]
@skattoju3 fork https://github.com/apache/cloudstack-documentation, create a bugfix branch, make changes and send a pull request.
