### ISSUE TITLE
Autogenerate marvin wrapper files for external plugins

### ISSUE THREAD

**Issue by dhlaluku** [apache/cloudstack#2610]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API, plugin, marvin
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY

The Marvin wrapper files are currently only generated for APIs and internal plugins within CloudStack. We wish to have an automated generic way of generating this wrapper files for external plugins that are not part of CloudStack code. 

##### STEPS TO REPRODUCE

~~~
Automation for an external plugin
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
It's currently possible to use marvin's codegenerator against a live running mgmt server's unauthenticated port to generate code. This is from tools/marvin/marvin:
```
python codegenerator.py -h
Usage: codegenerator.py [options]

Options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output=OUTPUT
                        The path to the generated code entities, default is .
  -s SPEC, --specfile=SPEC
                        The path and name of the api spec xml file, default is
                        /etc/cloud/cli/commands.xml
  -e ENDPOINT, --endpoint=ENDPOINT
                        The endpoint mgmt server (with open 8096) where apis
                        are discovered, default is localhost

```
Closing this one as the current way of code generation is shared. If you've a specific use-case or need, please re-submit a ticket or reopen this one with more details. Thanks.
