### ISSUE TITLE
Infra->Pods does not show which pod from which zone is, admin needs to name them with the zone name to have this info

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2618]
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request
 * Feature Idea

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
Reported in 4.11, but also seen in previous 
~~~

##### CONFIGURATION

Have more than one zone with multiple pods 

##### OS / ENVIRONMENT

NA

##### SUMMARY

When opening the Pods in the UI, Cloudstack admin is not able to see which zone a pod is part of, if it's using same naming it could be confusing. It'll be good if we have a fields here to display the zone.

##### STEPS TO REPRODUCE

~~~
Just open Infra->Pods
~~~

##### EXPECTED RESULTS

~~~
Pods to have zone displayed 
~~~

##### ACTUAL RESULTS

~~~
They dont
~~~

**Comment by rhtyd** [comment]
Not a problem with 4.11.1, see:
![screenshot from 2018-05-08 21-11-05](https://user-images.githubusercontent.com/95203/39767432-636aa01e-5304-11e8-95aa-861f9da74d32.png)
