### ISSUE TITLE
UI LDAP settings

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2644]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Management server
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

Don't no if it's issue or not.. In CS UI when configuring LDAP settings instead of values, which were entered I see this:

![screen shot 2018-05-15 at 17 36 02](https://user-images.githubusercontent.com/6417697/40063639-779969d2-5866-11e8-8d4b-8c885b95fb08.png)

New values (if I, for example, edit default value) entered are showing normally until I reboot management server (to apply configuration). After, all values regarding LDAP are showed like on screen

**Comment by DaanHoogland** [comment]
that is a strange inconvenience, for some it makes sense (bind password) for this one it doesn't, i think. I also don't know what should be the right behaviour.

**Comment by izenk** [comment]
Found way to watch them with
~~~
java -classpath /usr/share/cloudstack-common/lib/jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringDecryptionCLI decrypt.sh
~~~
So, UI values for some reason are not decrypted...

**Comment by DaanHoogland** [comment]
@izenk I think this issue is in since 4.9 at least. Are you using the global mapping or the per domain mapping?

**Comment by izenk** [comment]
Global mapping

**Comment by DaanHoogland** [comment]
@izenk can you check this in the rc3 for 4.11.1? it should have been solved with #2699

**Comment by izenk** [comment]
Sorry, can't.
Just use as private cloud.

**Comment by DaanHoogland** [comment]
ok, than you'll have to trust me ;)
