### ISSUE TITLE
Templates created under project are not visible

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2648]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management server
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

CEPH storage, Advanced networking

##### OS / ENVIRONMENT

Centos 7.4.1708

##### SUMMARY

Trying to create a template from VM.
VM was  created, prepared and stopped under the **project**.
Template creation task was completed successfully in terms that I can see notification about successful template creation. I can see job status in logs that everything is ok.
At the same time created template are shown nowhere in UI, also I can't get it through cloudmonkey
~~~
list templates templatefilter=all listall=true isrecursive=true
~~~

but if I specify template uuid directly
~~~
list templates listall=true templatefilter=all id=c350641c-26e6-484d-b0df-058b96ac3911
~~~

template is shown

At the same time I **can** see it in cs db in vm_template table for example.
I tried to investigate a little, what went wrong.. I don't now internals of cs and there are no docs, but what looks strange for me:
account_id is set to value, that belongs to account which was never created by me (manually or automatically).
This account is not showing in UI, but is presented in cs db table account
~~~
id: 7
account_name: PrjAcct-spg-infra_srv-3
uuid: 4e3ad0e6-919e-4066-b81a-9ea555f84e4e
type: 5
role_id: NULL
domain_id: 3
state: enabled
removed: NULL
cleanup_needed: 0
network_domain: NULL
default_zone_id: NULL
default: 0
~~~

Why role_id is null?
After some testing, I found that for every project account of type 5 is created.
Type 5 is defined, but can't find its role in cs ([Account](https://github.com/apache/cloudstack/blob/893a88d225276e45f12f9490e6af2c94a81c2965/api/src/main/java/com/cloud/user/Account.java)).

So may be the reason, that created template is owned by this special account

##### STEPS TO REPRODUCE

* Create vm under project
* Stop vm
* Create template from ROOT disk

##### EXPECTED RESULTS

Template is shown in "Templates" area

##### ACTUAL RESULTS
Template is not shown anywhere in UI and partly visible through API

**Comment by rhtyd** [comment]
Closing as this is similar to https://github.com/apache/cloudstack/issues/2871, we'll address issues against https://github.com/apache/cloudstack/issues/2871
