### ISSUE TITLE
configdrive testing needs refactorring

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#2671]
Config drive refactoring has led to an external utility being used in a unittest for it (genisoimage). This test must be done, however but in an integration test.
#2665 deletes the original test
#2651 introduced the change and has validity so we should keep the new way of creating the configdrive and only change the way of testing it.
 
##### ISSUE TYPE

 * Other (test improvement)

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
as #2665 now mocks the tool, I am wondering if we need an integration style test still. @rafaelweingartner @wido @fmaximus @mike-tutkowski can any of you comment? /cc @rhtyd

**Comment by wido** [comment]
If we have a proper Mock we do not need a integration test I think

**Comment by rafaelweingartner** [comment]
@wido that is the idea. It might be a good idea to have an "integration"/API test (those written in python) that calls the API that in turn uses the execution flow, which uses this configDriver block of code

**Comment by DaanHoogland** [comment]
So, what do we dicide? I think @rafaelweingartner 's tests are fine. I didn't check if we can skip the tests in #2673 but the macos fix I still want in.
comments, @wido @rhtyd @PaulAngus

**Comment by rafaelweingartner** [comment]
+1 to merge it if we are going to cut another RC. Not sure what to do if we are going to close release with the current RC.

**Comment by DaanHoogland** [comment]
merge and merge forward, but then still, do we merge #2673 as well?

**Comment by rafaelweingartner** [comment]
There seems to be some questions there, but I guess we should merge #2673 as well. It is fixing some integration tests.

**Comment by DaanHoogland** [comment]
sorry, no I've been confusing stuff. I mean #2665

**Comment by rafaelweingartner** [comment]
#2665 is deprecated by my PR

**Comment by DaanHoogland** [comment]
not entirely, but i'll create a separate PR for the macos bit, after verifying it actually does creates configdrives

**Comment by rafaelweingartner** [comment]
You mean, using the path to the program that is expected in the MacOS?

**Comment by DaanHoogland** [comment]
never mind @rafaelweingartner , I found the code in your PR
