### ISSUE TITLE
Build on Ubuntu 18.04 fails - "FAILURE! - in com.cloud.utils.ssh.SshHelperTest initializationError(com.cloud.utils.ssh.SshHelperTest)"

### ISSUE THREAD

**Issue by schadom** [apache/cloudstack#2678]
##### ISSUE TYPE
~~~
 * Bug Report
~~~

##### COMPONENT NAME
~~~
* Building cloud-utils on Ubuntu 18.04 LTS fails
~~~

##### CLOUDSTACK VERSION
~~~
* Cloudstack 4.11.0.0 stable
* Ubuntu 18.04 LTS
~~~

##### CONFIGURATION
~~~
* Fresh Ubuntu 18.04 LTS installation
* Cloudstack 4.11.0.0 source
~~~

##### OS / ENVIRONMENT
~~~
N/A
~~~

##### SUMMARY
~~~
Building cloud-utils form cloudstack 4.11.0.0 on Ubuntu 18.04 LTS fails during tests.
~~~

##### STEPS TO REPRODUCE
~~~
rob@cloudstack:~$ wget http://www.apache.org/dyn/closer.lua/cloudstack/releases/4.11.0.0/apache-cloudstack-4.11.0.0-src.tar.bz2
rob@cloudstack:~$ tar -jxvf apache-cloudstack-4.11.0.0-src.tar.bz2
rob@cloudstack:~$ cd ./apache-cloudstack-4.11.0.0-src
rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ sudo apt update && sudo apt install mysql-connector-python python-software-properties debhelper openjdk-8-jdk libws-commons-util-java genisoimage libcommons-codec-java libcommons-httpclient-java liblog4j1.2-java maven
rob@cloudstack:~$ mvn -P deps
~~~

Output: https://gist.github.com/schadom/ade6addc97bb00e8f7d46a39d56d06cf

##### EXPECTED RESULTS
~~~
maven should run through without failures. 
~~~

##### ACTUAL RESULTS
~~~
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in com.cloud.utils.ssh.SshHelperTest
initializationError(com.cloud.utils.ssh.SshHelperTest) Time elapsed: 0 sec <<< ERROR!
~~~

**Comment by khos2ow** [comment]
Can you check your java version? is it JDK 9?

**Comment by schadom** [comment]
> Can you check your java version? is it JDK 9?

It's `openjdk-8-jdk` like stated in the [docs](http://docs.cloudstack.apache.org/projects/cloudstack-installation/en/4.11/building_from_source.html#prerequisites-for-building-apache-cloudstack). Is this info not actual anymore?

	rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ apt list --installed | grep jdk
	openjdk-11-jre-headless/bionic,now 10.0.1+10-3ubuntu1 amd64
	openjdk-8-jdk/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64
	openjdk-8-jdk-headless/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64
	openjdk-8-jre/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64
	openjdk-8-jre-headless/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64

	rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ java --version
	openjdk 10.0.1 2018-04-17
	OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
	OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

**Comment by khos2ow** [comment]
> rob@cloudstack:~/apache-cloudstack-4.11.0.0-src$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

You actually have both Java 10 and 8 installed, and the *active* one is Java 10. And apparently one of the test framework we use has a known issues with java 9+.

In the meantime you can switch to java 8 and try again, execute below command and follow the on screen instructions:

```
update-alternatives --config java
```

**Comment by schadom** [comment]
Sorry my fault. Worked out fine with java 8 now. Thanks very much!
