### ISSUE TITLE
with basic network mode, router vm is not up

### ISSUE THREAD

**Issue by Jamlee** [apache/cloudstack#2687]
when i use the basic network mode,  the **default ip is assign to eth0** and **eth1 have no ip**.  but the port **3922** iptable rule is on eth1. So **cloustack master** can not ssh to **router**.

As blew code:
https://github.com/apache/cloudstack/blob/ca17b6a126d8842adb750146a3f843e6acbadd04/systemvm/debian/opt/cloud/bin/cs/CsAddress.py#L356

i **changed eth1 to eth0** , then rebuild cloudstack.  router vm started  and status is **up**.

```
 ["filter", "", "-A INPUT -i eth0 -p tcp -m tcp --dport 3922 -m state --state NEW,ESTABLISHED -j ACCEPT"]) 
```

**Comment by DaanHoogland** [comment]
@wido Can you judge this one for its merits? Has there been a change in basic mode VRs?

**Comment by Jamlee** [comment]
Sorry.  the wrong thing i do is that i use the latest 4.12 with systemvm-4.11.
