### ISSUE TITLE
Existing templates not downloaded when adding new secondary storage

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#2689]
Adding a new secondary storage does not kick downloading of existing templates on the new secondary storage. However, if we restart the cloud service in ssvm it attempts to download those existing templates.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM, Secondary Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.9, 4.10, 4.11
~~~

##### STEPS TO REPRODUCE

~~~
- Add new secondary storage
- Keep watching the new secondary storage directory/mount point for new files/folders, and tail ssvm logs
- Existing templates not downloaded 
~~~

##### EXPECTED RESULTS

~~~
Existing/registered templates should be downloaded
~~~

**Comment by ernjvr** [comment]
yes
