### ISSUE TITLE
Host State different between 'Hosts' and 'host' perspective

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#2702]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~
##### SUMMARY
The host has different State, as shown in the following picture:

![kvmhoststate](https://user-images.githubusercontent.com/5025148/41109410-5446fc76-6a4d-11e8-9cf6-4d2889514b60.jpg)

However, both perspectives return State as 'Up' from the `listHost` command.

```
listhostsresponse	{…}
	count	1
	host	[…]
	0	{…}
	id	642415ff-6e31-45fb-8a25-e20a43ee5a21
	name	kvm
	state	Up
	type	Routing
	(...)
```

##### CLOUDSTACK VERSION

~~~
4.11.1.0 release (RC1)
~~~

##### STEPS TO REPRODUCE

View perspectives `Home > Infrastructure > Hosts` and `Home > Infrastructure > Hosts > hostname`
For new features, show how the feature would be used.

##### EXPECTED RESULTS

~~~
Both perspectives with the same state.
~~~

##### ACTUAL RESULTS

~~~
State is Up and Unsecure at the same time.
~~~

**Comment by rafaelweingartner** [comment]
Where does the "unsecure" state come from?

**Comment by GabrielBrascher** [comment]
I'm am not sure if this is a bug or a desired behavior, but I got confused when saw different states.

In system.js we have:
```
if (host && host.hypervisor == "KVM" && host.state == 'Up' && host.details && host.details["secured"] != 'true') {
	items[idx].state = 'Unsecure';
}
```

**Comment by rhtyd** [comment]
This is intentional to show that a connection is Up but not secured by CA cert subsystem. There is a new button for kvm hosts to provision certificate i.e secure that host. If you want we can show Up in parenthesis.

**Comment by GabrielBrascher** [comment]
@rhtyd got it, thanks. I am ok with the way it is, but it would be nice to have it documented (I would gladly help on the 4.11.1 documentation as well)

**Comment by rafaelweingartner** [comment]
I think that @rhtyd's suggestion might help. We could use `Up (unsecured)` instead.

**Comment by GabrielBrascher** [comment]
`Up (unsecured)` would be perfect!
