### ISSUE TITLE
Restarting of non-redundant VPC with private gateway fails sometimes

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#2719]
See this for reference:
https://github.com/apache/cloudstack/pull/2712
https://github.com/apache/cloudstack/pull/2128

The issue is that a non-redundant VPC VR with private gateway after restart (with cleanup=true) sometimes screws up the nic sequence and the private/guest network nics and private gateway (static routes) ips end on the same interfaces (such as eth2) with eth3 without any nic configured. The workaround in such a case is to destroy the VPC VR manually, and restart the VPC without cleanup selected.

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
VR, VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.9, 4.10, 4.11
~~~

**Comment by PaulAngus** [comment]
Reference PR #2128 is not fully implemented and causes issues when deploying VRs with private gateways on VMware.

**Comment by PaulAngus** [comment]
LGTM based on specific functionality fix - 'just' need full test suite

test_01_vpc_privategw_acl (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_01_vpc_privategw_acl | Status : SUCCESS ===
ok
test_02_vpc_privategw_static_routes (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_02_vpc_privategw_static_routes | Status : SUCCESS ===
ok
test_03_vpc_privategw_restart_vpc_cleanup (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_03_vpc_privategw_restart_vpc_cleanup | Status : SUCCESS ===
ok
test_04_rvpc_privategw_static_routes (tests.smoke.test_privategw_acl.TestPrivateGwACL) ... === TestName: test_04_rvpc_privategw_static_routes | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 4 tests in 687.214s

OK

**Comment by rhtyd** [comment]
PR merged, closing.
