### ISSUE TITLE
Service Offering Sorting is broken in UI

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#2724]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
4.11.1

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Trying to order Compute service offerings in UI, but the result is the same as before sorting. UI controls allow moving offerings against each other, including drag and drop way, but after page reload they are still in the same order as before.

##### STEPS TO REPRODUCE
Create several service offerings, try to reorder them in UI. 

##### EXPECTED RESULTS
Items reordered

##### ACTUAL RESULTS
Items in the same order

**Comment by bwsw** [comment]
Later investigation has shown that it also broke in Templates/ISO sorting order.

**Comment by rhtyd** [comment]
@anuragaw can you verify fix this, since I think you've fixed sorting for couple of resources in the UI.

**Comment by anuragaw** [comment]
Copy @rhtyd

**Comment by anuragaw** [comment]
DB support for service offerings was existing but I discovered another bug while testing and fixed it in the above PR.

**Comment by rhtyd** [comment]
As per remarks on https://github.com/apache/cloudstack/pull/3445, this is fixed. Closing.
