### ISSUE TITLE
Cloudstack development source code repo not found

### ISSUE THREAD

**Issue by NaingThuraKyaw** [apache/cloudstack#2729]
##### ISSUE TYPE

 * Other

##### SUMMARY

Git repo not found

##### STEPS TO REPRODUCE

1. Go to https://github.com/apache/cloudstack/blob/master/INSTALL.md
2. There is a link namely "[Setting up development environment](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Setting+up+CloudStack+Development+Environment)" 
3. There is another link namely "[Using Eclipse With CloudStack](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Using+Eclipse+With+CloudStack)" 
4. CLone the git repo  written there.
 https://git-wip-us.apache.org/repos/asf/cloudstack.git

##### EXPECTED RESULTS

Should be able to clone the repo.

##### ACTUAL RESULTS

Repo not found.

**Comment by DaanHoogland** [comment]
the actual upstream is https://gitbox.apache.org/repos/asf/cloudstack.git but either should work. As for a PR i suggest you use the apache site and not this repo if you create one (they have found this one anyway)

**Comment by DaanHoogland** [comment]
just checked the INSTALL.md and it contains the right link (https://gitbox.apache.org/repos/asf/cloudstack.git). Where did you encounter that old link?

**Comment by DaanHoogland** [comment]
ok @NaingThuraKyaw , I found the link and updated it, thanks. closing this ticket now.
