### ISSUE TITLE
If a VM resource is requested to transition in a state where it's already in, it returns success, instead it should return 'the resource is in the same state' 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2736]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM handler 

~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

If a VM is already running on HostA and the Admin requests a Start on HostB, it will return a success with the VM being started on HostA. Instead it should return an error to the administrator that the resource is already in running state.

##### STEPS TO REPRODUCE

1. Start a VM on HostA
2. With cloudmonkey, start the same VM on HostB
3. Observe the result

##### EXPECTED RESULTS

~~~
Response should fail the job and say VM is already in the same state. 
~~~

##### ACTUAL RESULTS

~~~
Job succeeds with VM not being the requested host 
~~~

**Comment by DaanHoogland** [comment]
I would argue that the expected behaviour is a migration to host B but agree that the endstate does not qualify as a success. Do you request that this is implemented as failure result, @borisstoyanov ?

**Comment by borisstoyanov** [comment]
Yes @DaanHoogland, I do believe that it should return a failure if cloudstack is not able to execute the request with all required parameters.
