### ISSUE TITLE
VPC offerings not sortable

### ISSUE THREAD

**Issue by resmo** [apache/cloudstack#2742]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
API, VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

VPC offerings UI offers to sort the VPC offerings. VPC offerings order is not stored anyware. The api does not support ordering due missing sortkey param (https://cloudstack.apache.org/api/apidocs-4.11/apis/updateVPCOffering.html) 

##### STEPS TO REPRODUCE
In the UI:
Change order of VPC offerings than hit refresh (clicking on magnifier icon) 

##### EXPECTED RESULTS

VPC offerings are ordered as desired 

##### ACTUAL RESULTS
VPC offerings remain in the same order.

**Comment by anuragaw** [comment]
I'm working on this issue as I had worked on something similar sometime back.
