### ISSUE TITLE
Could i set fixed mgmt_server_id ?

### ISSUE THREAD

**Issue by Jamlee** [apache/cloudstack#2744]
##### ISSUE TYPE
 Bug Report

##### COMPONENT NAME
management server 

##### CLOUDSTACK VERSION
4.11

##### OS / ENVIRONMENT
`ubuntu + docker + cloudstack`

##### SUMMARY
when i install cloudstack and  docker on same virtual machine, it grab the `docker0 bridge mac address` as a mgmt_server_id. but the **docker0 mac address changed  sometimes**. So Could i set a fixed interface for cloudstack to grab mac address.

**Comment by resmo** [comment]
This is not a bug, please head over to the mailing lists for questions: http://cloudstack.apache.org/mailing-lists.html

Thanks
