### ISSUE TITLE
missing items in instance list

### ISSUE THREAD

**Issue by tfbb** [apache/cloudstack#2746]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~
##### CLOUDSTACK VERSION
~~~
4.11.0.0
~~~

##### CONFIGURATION
~~~
N/A 
~~~

##### OS / ENVIRONMENT
~~~
N/A
~~~

##### SUMMARY

sorting the instance list in the web gui makes instances disappear, scrolling the list down & up again brings them back

##### STEPS TO REPRODUCE
in the web gui:
1. click on instances and have a list with instances that won't fit on one page, ie. there should be a scrollbar on the right ![](https://thoralf-spielwiese.cloud.heinlein-hosting.de/acs-foo/001.png?)
2. sort this unsorted list by clicking on any of the row headers - in the example pics, the list is being sorted ascending by name. note that "bas…" is the first item in the list ![](https://thoralf-spielwiese.cloud.heinlein-hosting.de/acs-foo/002.png?)
3. scroll down until the list gets reloaded
4. scroll up again to the very top. note that "apt…" is now the first item in the list ![](https://thoralf-spielwiese.cloud.heinlein-hosting.de/acs-foo/003.png?)

##### EXPECTED RESULTS
~~~
"apt…" should be the first list item from the start
~~~

##### ACTUAL RESULTS
~~~
"bas…" was the first list item. only after reloading the list will  "apt…" be the first item
~~~

**Comment by rhtyd** [comment]
Unable to reproduce. Please test latest 4.11.3.0 or master and reopen if you're able to reproduce.
