### ISSUE TITLE
SystemVMs running in Xen HVM mode are not configured

### ISSUE THREAD

**Issue by dpassante** [apache/cloudstack#2760]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
systemVM image 4.11 for XenServer
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

* Cloudstack 4.11.1
* XenServer 7.1.1
* SystemVM 4.11.1 Fri Jun 22 07:52:17 UTC 2018 running in HVM mode

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Newly created system VMs are not configured.

Related to #2561 

virt-what cpuid helper detects Xen HVM guests with viridian extension enabled as hyperV guests.

~~~bash
root@v-2158-VM:~# /usr/lib/x86_64-linux-gnu/virt-what-cpuid-helper
Microsoft Hv
~~~

So, virt-what returns the following on Xen HVM SystemVMs:

~~~bash
root@v-2158-VM:~# virt-what
hyperv
xen
xen-domU
~~~

In this case, the ```/opt/cloud/bin/setup/cloud-early-config``` script assumes that we're running on a paravirtualized guest and fails to get boot args.

##### EXPECTED RESULTS

hypervisor: xen-hvm
systemvm type: should be detected.

~~~
Sun Jul 22 03:18:28 UTC 2018 Executing cloud-early-config
Sun Jul 22 03:18:28 UTC 2018 Detected that we are running inside xen-hvm
Sun Jul 22 03:18:28 UTC 2018 Scripts checksum detected: oldmd5=76c6bbddfc1d55d1b212ad8ca07190d4 newmd5=76c6bbddfc1d55d1b212ad8ca07190d4
Sun Jul 22 03:18:28 UTC 2018 Configuring systemvm type=consoleproxy
Sun Jul 22 03:18:29 UTC 2018 Setting up console proxy system vm
...
~~~

##### ACTUAL RESULTS

hypervisor: xen-domU
systemvm type : empty

~~~
root@systemvm:~# cat /var/log/cloud.log
Fri Jul 20 12:55:19 UTC 2018 Executing cloud-early-config
Fri Jul 20 12:55:19 UTC 2018 Detected that we are running inside xen-domU
Fri Jul 20 12:55:19 UTC 2018 Scripts checksum detected: oldmd5=76c6bbddfc1d55d1b212ad8ca07190d4 newmd5=76c6bbddfc1d55d1b212ad8ca07190d4
Fri Jul 20 12:55:19 UTC 2018 Configuring systemvm type=
Fri Jul 20 12:55:19 UTC 2018 Finished setting up systemvm
~~~

**Comment by rhtyd** [comment]
@dpassante the only difference between how xen-domU and xen are used by the systemvm is wrt the way of getting an initial cmdline. Otherwise, there is no difference. Are you able to see systemvms come up or are they failing?

**Comment by rhtyd** [comment]
ping @dpassante based on the comment above I'll remove this from 4.11.2.0 milestone, if you can reply and share any suggestive fix we can help with reviewing and testing of a fix.

**Comment by dpassante** [comment]
@rhtyd the systemvms are booting but not configured as the PV-ARGs are not present in /proc/cmdline.

The easy way to fix is to do not rely on virt-what for Xen guests and move lines 44-52 to the beginning of the ```hypervisior()``` function.

I'll also share the fix that is currently running on my environments.
