### ISSUE TITLE
Followup 2613: Re-enable PMD in enablefindbugs profile

### ISSUE THREAD

**Issue by khos2ow** [apache/cloudstack#2770]
Following up after #2613 we need to assess how to re-enable PMD plugin in `enablefindbugs` profile. We had some issue with Jenkins's agent going offline because of the huge number of problem the plugins was finding. [reference](https://issues.jenkins-ci.org/browse/JENKINS-46641)

**Comment by DaanHoogland** [comment]
@khos2ow still involved? thoughts?

**Comment by khos2ow** [comment]
Unfortunately I've not been involved lately, but for this I don't think there is an easy and straightforward way of enabling PMD again due to the stagering number of problems. It requires a lot of collective effort to fix them which might not make sense.

**Comment by DaanHoogland** [comment]
not sure butif i get the time and energy i'll look again at flogging this dead horse

**Comment by DaanHoogland** [comment]
not on any priority list at the moment, reopen or recreate later
