### ISSUE TITLE
nw_rate from system offering is not honoured

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#2780]
ACS 4.11.1 no longer honours nw_rate from system offering when creating VRs. In 4.9(.2) one could create a system offering with a different network rate to differentiate between types of networks. In 4.11.1 one needs to create a network offering and thus a separate VPC offering for instance to control network rate.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

this is standard networking based on vlans in advanded zone. It affects VPCs mostly but seems to matter for regular isolated networks as well

##### STEPS TO REPRODUCE

~~~
create a system offering with obviously different nwrate (7 or 11 or 13;)
choose this offering for a router in a network and restat the network.
~~~

##### EXPECTED RESULTS

~~~
the nwrate from the system offering is used (i.e. 7 Mb/s)
~~~

##### ACTUAL RESULTS

~~~
the default from the global setting is still used
~~~

**Comment by rhtyd** [comment]
Per the docs, this is not an issue: http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/service_offerings.html#network-throttling
I'll close this based on the behaviour from above documentation, please re-open if we don't agree.
