### ISSUE TITLE
Make allowed ports for registerTemplate api configurable

### ISSUE THREAD

**Issue by csquire** [apache/cloudstack#2802]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

Currently, Cloudstack restricts urls for registerTemplate to a small set of ports.  Would be nice to make this configurable to allow an admin to configure the allowed ports.  In my case, I have a server listening on 8081 which I do not have control over. I'd like to be able to configure Cloudstack to allow this port.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rafaelweingartner** [comment]
@csquire can you post here the screenshot of the error? Or, maybe the log entries with the exception? Or the error message  you received in the client side?

**Comment by csquire** [comment]
@rafaelweingartner Yeah, it returns a 403 and shows `Forbidden` in a browser. The behavior is intentional, it's not a bug per se.

Offending code is here: 
https://github.com/apache/cloudstack/blob/master/plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java#L51-L59

**Comment by rafaelweingartner** [comment]
I am confused now. Are you talking about the code that register templates or the code that handles Prometheus integration?

**Comment by csquire** [comment]
Sorry, last comment was posted in the wrong issue, I deleted it.

You just get an error back that your port is not allowed `Only ports 80, 8080 and 443 are allowed`

https://github.com/apache/cloudstack/blob/master/utils/src/main/java/com/cloud/utils/UriUtils.java#L267-L270

**Comment by shwstppr** [comment]
@csquire Will removing port checking be an appropriate solution for this or should there be some global settings where admin can set a list of allowed ports?
cc @rhtyd @nvazquez

**Comment by rhtyd** [comment]
It should be any port @shwstppr
