### ISSUE TITLE
Start timeout - Virtual router

### ISSUE THREAD

**Issue by lhmachado** [apache/cloudstack#2805]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

~~~
N/A
~~~

##### OS / ENVIRONMENT

~~~
N/A
~~~

##### SUMMARY

When the virtual router has many machines on its network, in the order of magnitude of 20 or 30, it does not rise due to a command that takes too long in its scripts.
 

##### STEPS TO REPRODUCE

~~~
Start 20 instances on the same network.
'UI' in menu Infrastructure -> Virtual Routers, choose your network VR.
Destroy your VR.
'UI' Networks, Choose your network and restart it.
~~~

##### EXPECTED RESULTS

~~~
Router must start it. 
~~~

##### ACTUAL RESULTS

~~~
Router will stay in starting and will not change it
~~~

**Comment by PaulAngus** [comment]
@lhmachado - is this 4.11.0.0 or 4.11.1.0 ?

I've created 40 VMs on a network (4.11.1.0) and restarted it with (with cleanup) no problem.

**Comment by bwsw** [comment]
I saw that problem. Default command  timeout should be increased. It helped me to solve that.

**Comment by lhmachado** [comment]
@PaulAngus , the version with this problem was 4.11.0.0.  
But the real problem was arping command in virtual-router was called anyway on python code.
Maybe on 4.11.1.0 default command have a different timeout like @bwsw said.

on file: merge.py 
line 239, in this code : "dp['gateway'] ='None' ''

later on CsAddress.py line 303

if 'gateway' in self.address:
                self.arpPing()

This string 'None' makes if steatement  always be true
the solution on #2806 makes dp['gateway'] =''

cannot be None type because there is a string operation later on code.

**Comment by DaanHoogland** [comment]
@lhmachado 'None' and None should be two different things and unless evaluated 'None' should not be in self.address. I think you are solving the wrong bug. Am I making any sense?

**Comment by lhmachado** [comment]
@DaanHoogland I agree with you.

the code with 'None'  (String with value None), is wrong, beacause makes arping called in any situation on if steatment with value 'None'. 
The result in bash is : 
 $ "arping .... None" 
this command takes at least 1 minute to run (peer VM configured on router), so in a cenario then we have a lot of VM's in the same network, eventually we receive a failure on router start up.

But when the value is '' (empty string)
the if steatement is correct evaluated and router can start up.

So, the real problem is:
An invalid command ($ "arping .... None") has been called every VM on router startup.
