### ISSUE TITLE
UI: Overlay issue in snapshot view on master with new jquery and other changes

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#2830]
Go to volumes -> select a volume -> click on the recurring snapshot button -> it shows up like this:
![screenshot from 2018-08-30 15-36-48](https://user-images.githubusercontent.com/95203/44845337-e4352880-ac6a-11e8-97ae-a65c4b05459e.png)

The env is based on master, no sure if it's already fixed. /cc @rafaelweingartner 

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### EXPECTED RESULTS

~~~
UI should allow configuration of snapshot schedule
~~~

##### ACTUAL RESULTS

~~~
Overlay stops user from using the snapshot scheduler widget
~~~

**Comment by rafaelweingartner** [comment]
Thanks for spotting that. I have just create the PR to fix it.
