### ISSUE TITLE
Volume snapshot recurring schedule not showing once added 

### ISSUE THREAD

**Issue by glennwagner** [apache/cloudstack#2831]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1 LTS
~~~

##### CONFIGURATION

Advanced Networking
Two Zones
Primary Storage: VMFS Datastores 
Secondary Storage: NFS Servers 
16 Vmware ESXi Hosts 
2 XenServer Hosts

##### OS / ENVIRONMENT

Management Servers: CentOS Linux release 7.5.1804 (Core)
Hypervisor: VMware vSphere 6.5
XenServer 6.2 SP1

##### SUMMARY

When adding a volume recurring snapshot the entree shows as add but nothing is displayed under the heading,

##### STEPS TO REPRODUCE

~~~
1. Go to a Volume of an existing VM.
2. Create a Volume recurring snapshot 
* Select timezone 
* Time to run 
* Keep how many copies
* click add.
 

~~~

![image](https://user-images.githubusercontent.com/10772436/44846807-cad3b280-ac51-11e8-8763-dfe2dbacd926.png)

##### EXPECTED RESULTS

~~~
Volume recurring snapshot schedule to show after added
~~~

##### ACTUAL RESULTS

~~~
Blank schedule 
~~~

**Comment by ernjvr** [comment]
fix https://github.com/apache/cloudstack/pull/2836
