### ISSUE TITLE
Add XCP-NG 7.5 support for 4.11.2

### ISSUE THREAD

**Issue by cocoon** [apache/cloudstack#2834]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Hypervisor Support
~~~

##### CLOUDSTACK VERSION
~~~
4.11.2
~~~

##### SUMMARY
Add support for released XCP-NG 7.5
https://xcp-ng.org/download/

##### STEPS TO REPRODUCE

Here is already prepared to add XenServer 7.5:
[systemvmtemplate: new 4.11.2 template and fixes #2799](https://github.com/apache/cloudstack/pull/2799/files#diff-8e19845d82b0e68ea9a2dcaf58d70aea)

So I think it would be the correct place to add XCP-NG 7.5 with that commit, too?
XCP-NG 7.4 was introduced here:
https://github.com/apache/cloudstack/blob/5a1f25ae4507693abf52ef1db528677590f38548/engine/schema/resources/META-INF/db/schema-41100to41110.sql#L91

**Comment by rhtyd** [comment]
Added upgrade path here for 4.11.2.0 to add support for XS 7.5 which also adds supports for XCP-NG 7.5: https://github.com/apache/cloudstack/pull/2799/commits/5746d3d0501e65df68874dfad1df10362a445cd6
