### ISSUE TITLE
When KVM hypervisor is selected in template registration don't show XS tools version option

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#2844]
When KVM hypervisor is selected in template registration don't show XS tools version option:

![pastedgraphic-1](https://user-images.githubusercontent.com/95203/45541086-b1269380-b82b-11e8-9fee-28da58a9dfc4.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1.0
~~~

##### STEPS TO REPRODUCE

~~~
Register template for a KVM env
Select KVM hypervisor, the option still shows up
~~~

##### EXPECTED RESULTS

~~~
XS related option should not to displayed
~~~

##### ACTUAL RESULTS

~~~
See screenshot
~~~

**Comment by rhtyd** [comment]
Looks like already fixed - https://github.com/apache/cloudstack/pull/2757 @ernjvr @PaulAngus to comment/verify

**Comment by ernjvr** [comment]
Yes, 'Origin XS version is 6.1+' no longer shows for KVM option

**Comment by rhtyd** [comment]
Thanks @ernjvr closing on your remark.
