### ISSUE TITLE
migrateNetwork API doesn't declare networkofferingid as required

### ISSUE THREAD

**Issue by krissterckx** [apache/cloudstack#2851]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

API

##### CLOUDSTACK VERSION

4.11

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

ALL

##### SUMMARY

networkofferingid as declared in migrateNetwork API must be required

##### STEPS TO REPRODUCE

check https://cloudstack.apache.org/api/apidocs-4.11/apis/migrateNetwork.html

##### EXPECTED RESULTS

networkofferingid to be required

##### ACTUAL RESULTS

networkofferingid is not required

**Comment by rhtyd** [comment]
PR merged, this may likely get into 4.11.2.0 RC2.
