### ISSUE TITLE
SSVM NFS4 does not support minor version setting e.g. 4.1

### ISSUE THREAD

**Issue by resmo** [apache/cloudstack#2861]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
SecondaryStorage VM
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Debian 9 system VM default NFS version is 4.2. If your NFS server does not support 4.2, the mount may fail (is does in our case).

There is a global config `secstorage.nfs.version` to specify the version, but it does only support int values. If you set it to `4` the NFS4 version used is `4.0`. 

There is currently no way to set a minor version. e.g. `4.1`.

:warning: Note that version 3 has no "minor versions". 

Probably worth considering is to add new configuration field for nfs4 minor versions. e.g. `secstorage.nfs4.minorversion` defaulted to null.  NFS4 version shoulld be a combination of 
`secstorage.nfs.version + '.' + secstorage.nfs4.minorversion`. NFS3 only `secstorage.nfs.version`

**Comment by rhtyd** [comment]
Looks like a bug, if it was previously supported/working. However, not a major blocker, I'll try and fix it before RC2.

**Comment by resmo** [comment]
not a big issue, could be in 4.11.3.

**Comment by PaulAngus** [comment]
looks like it would be a simple enhancement to add to nfs mount commands:

mount -t nfs4 -o rw,nolock,nfsvers=4,minorversion=1 nfsserver:/path /mnt/path

But this needn't hold up 4.11.2

**Comment by rhtyd** [comment]
cc @Spaceman1984

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4180
