### ISSUE TITLE
Cloudstack 4.11.1.0 - Unable to create shared network in advanced zone

### ISSUE THREAD

**Issue by bdonnahue** [apache/cloudstack#2863]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
UI / API

##### CLOUDSTACK VERSION
4.11.1.0

##### CONFIGURATION
Advanced Network
GRE Isolation
XenServer 7.2
1 physical network hosting all network traffic types

##### SUMMARY
I cannot create a shared network through the GUI. I see the following error message in my logs:

2018-09-24 22:19:07,803 ERROR [c.c.a.ApiServer] (qtp788117692-144094:ctx-75aeff02 ctx-93156a36) (logid:3b14107d) unhandled exception executing api command: [Ljava.lang.String;@11e8bdf4 com.cloud.utils.exception.CloudRuntimeException: Unable to convert network offering with specified id to network profile

##### STEPS TO REPRODUCE
Create an advanced network and try to create shared network

##### EXPECTED RESULTS
Shared network screated

##### ACTUAL RESULTS
Error message displayed

**Comment by rhtyd** [comment]
@bdonnahue can you share more details about your zone/infra setup? How you have setup and deployed your zone with XenServer 7.x and openvswitch?

**Comment by rhtyd** [comment]
@bdonnahue according to the list https://www.mail-archive.com/dev@cloudstack.apache.org/msg17396.html the feature may have been broken since 4.2.

**Comment by fmaximus** [comment]
The error means it can't find a NetworkGuru who wants to design the network.
I also took a look at the NetworkGurus:
Neither ExternalGuestNetworkGuru nor OvsGuestNetworkGuru have Shared Network support.
DirectNetworkGuru has Shared support, but doesn't support GRE.

**Comment by bdonnahue** [comment]
@rhtyd what information would you like specifically (sorry just new to CS and not sure what might be common knowledge)

I am not sure how to reconcile the comments maid in the mail archive that @rhtyd linked to and the comments that @fmaximus made. It sounds like the bug was fixed by removing the components to setup GRE tunnels (formerly implemented by the OVS plugin in 4.1)? Is that an accurate statement?

**Comment by PaulAngus** [comment]
@bdonnahue - the combination is saying that OVS is a prerequisite of using GRE tunnels, and that OVS does not support shared networks.
So I'm afraid that you've found a limitation rather than a bug.

**Comment by bdonnahue** [comment]
@PaulAngus can you add some more detail about what you mean when you say that OVS does not support shared networks? I thought a shared network was a network that can be used by VMs provisioned by different accounts. If that is true, why would this be a limitation of OVS and not the OVS plugin/Cloudstack?

**Comment by PaulAngus** [comment]
Sorry, that was my shorthand, by OVS i meant OVS in CloudStack. it is a limitation of the OVS plugin.  Excluding shared networks seems a strange omission, but i guess whoever implemented it had a specific use case in mind.

**Comment by bdonnahue** [comment]
@PaulAngus ah ok thanks for clearing that up. Whats the best way to make a feature request? Is there a way this could be added to the 4.11.2.0 milestone?

**Comment by rhtyd** [comment]
@bdonnahue since we're already in between testing/reviewing 4.11.2.0 RCs, we should avoid major/new enhancement/fixes towards 4.11.2.0, the best way forward would be to aim towards 4.11.3.0 or 4.12.0.0.

**Comment by bdonnahue** [comment]
@rhtyd waiting for a future release makes sense. What is the best way to make the feature request? Do we just use this ticket and attach some tags to it?

**Comment by rhtyd** [comment]
Create a new issue request in github, you may provide links to related resources, prs etc in your issue description @bdonnahue

**Comment by rhtyd** [comment]
Relevant issue opened, closing this one as https://github.com/apache/cloudstack/issues/2885
