### ISSUE TITLE
Ceph - resize volume doesn't work

### ISSUE THREAD

**Issue by se-bre** [apache/cloudstack#2868]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Ceph / primary storage
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0 / 4.9
~~~

##### CONFIGURATION

Ceph as primary storage

##### OS / ENVIRONMENT

Ubuntu 16.04
libvirt 1.3.1

##### SUMMARY

Volume resize does not work for running VM.
Cloudstack resizes the ceph rbd but running vm doesn't recognise

##### STEPS TO REPRODUCE

resize volume (attached to a running vm)

##### EXPECTED RESULTS

lsblk should show new size

##### ACTUAL RESULTS

lsblk shows old size

workaround:

- detach - reattach volume

- stop - start vm

- virsh command on hypervisor

get volume on hypervisor:
~~~
    virsh qemu-monitor-command <vm_name or domain_id> info block --hmp
    
    drive-virtio-disk0 (#block155): rbd:pool/xyz:id=cloudstack:key=xyz==:auth_supported=cephx\;none:mon_host=ceph.mon\:6789 (raw)
        [...]
        
~~~
disk name `drive-virtio-disk0`

update blockdevice size information for vm
~~~
virsh qemu-monitor-command <vm_name or domain_id> 'block_resize <disk_name> <new_size>G'
~~~

log entries `/var/log/cloudstack/agent/resizevolume.log`:
~~~
Mon Oct  1 11:42:31 CEST 2018 - failed to live resize pool/xyz to size of 10485760 kb
~~~

**Comment by kiwiflyer** [comment]
I'm going to take a look at this and propose a PR.

**Comment by kiwiflyer** [comment]
I've created a test PR for our branch on 4.8. Feel free to try this and see if it fixes your problem. If it does, I'll push a PR up to 4.11.x and master.

https://github.com/myENA/cloudstack/pull/38/commits/c68b84cd82b4fe7105cd5125ef41cef64e3157ae

You can take those two lines and change /usr/share/cloudstack-common/scripts/storage/qcow2/resizevolume.sh on a test host, then try a resize.

**Comment by kiwiflyer** [comment]
@se-bre Do you have an environment where you may be able to test the above patch?

**Comment by kiwiflyer** [comment]
I spun up a Ubuntu 16.04 server using virtio-blk.

I started with a 106GB block device on ceph:

![before_106gb](https://user-images.githubusercontent.com/17278194/46501501-527d8580-c7eb-11e8-9eb0-ddd9ed1b86b0.png)

I then used the ACS GUI to resize it to 150GB:

![after_150gb](https://user-images.githubusercontent.com/17278194/46501517-60330b00-c7eb-11e8-92aa-6819ecf367c9.png)

Live resize on ceph seems to be working as expected with the above patch.
