### ISSUE TITLE
Public templates not displayed

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2871]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

Advanced networking, KVM, CEPH

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

In project view public templates are not shown, but when try to create vm - they are.

##### STEPS TO REPRODUCE
Create template under admin account and mark it as 'public'.
Switch to another account and create project.
Switch to created project (Project view in UI).
Switch to 'Templates' section and choose 'Community' from list (or any section, just to find created public template).

##### EXPECTED RESULTS

~~~
Public templates are shown in 'Templates/Community' section
~~~

##### ACTUAL RESULTS

~~~
Nothing is shown in 'Templates/Community or any other' section
~~~
[Screen1](https://postimg.cc/KRbJqP1x)

but template is shown during vm creation

[Screen2](https://postimg.cc/qgy1xbM1)

**Comment by izenk** [comment]
Any Public template created under Project is not visible in "Default View" even it was marked as "Public". So VM under "Default View" can't be created using this template

**Comment by izenk** [comment]
Any updates on this?

**Comment by rhtyd** [comment]
Similar to: https://github.com/apache/cloudstack/issues/3059 (same logic of access restriction likely)

**Comment by rhtyd** [comment]
@anuragaw can you take this one as well. We need to do the following:
- Reproduce the issue mentioned in this ticket
- Create templates from a snapshot, and also register a template under a project; for both cases confirm that it shows up in the UI in the template
- Fix any access checks if necessary

**Comment by anuragaw** [comment]
Sounds good @rhtyd

**Comment by anuragaw** [comment]
I have tried some combinations but the bug is not reproducible on master.
@izenk - can you verify if you can reproduce it on master?
CC/ @rhtyd, @shwstppr

**Comment by rhtyd** [comment]
Closing on your remark @anuragaw 
@izenk please reopen if you could reproduce the issue with latest master/4.13
