### ISSUE TITLE
Improve ConfigDrive to store network information

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#2872]
ConfigDrive / cloud-init supports a *network_data.json* file which can contain network information for a VM.

By providing  the network information using ConfigDrive to a VM we can eliminate the need for DHCP and thus the Virtual Router in some use-cases.

An example JSON file:

<pre>
{
    "links": [
        {
            "ethernet_mac_address": "52:54:00:0d:bf:93",
            "id": "eth0",
            "mtu": 1500,
            "type": "phy"
        }
    ],
    "networks": [
        {
            "id": "eth0",
            "ip_address": "192.168.200.200",
            "link": "eth0",
            "netmask": "255.255.255.0",
            "network_id": "dacd568d-5be6-4786-91fe-750c374b78b4",
            "routes": [
                {
                    "gateway": "192.168.200.1",
                    "netmask": "0.0.0.0",
                    "network": "0.0.0.0"
                }
            ],
            "type": "ipv4"
        },
        {
            "id": "eth0",
            "ip_address": "2001:db8:100::1337",
            "link": "eth0",
            "netmask": "64",
            "network_id": "dacd568d-5be6-4786-91fe-750c374b78b4",
            "routes": [
                {
                    "gateway": "2001:db8:100::1",
                    "netmask": "0",
                    "network": "::"
                }
            ],
            "type": "ipv6"
        }
    ],
    "services": [
        {
            "address": "8.8.8.8",
            "type": "dns"
        }
    ]
}
</pre>

In Basic Networking and Advanced Networking zones which are using a shared network you wouldn't require a VR anymore.

**Comment by wido** [comment]
More information:

- https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html
- https://cloudinit.readthedocs.io/en/latest/topics/network-config.html

I tested this with this cloud-init configuration under Ubuntu 18.04

<pre>
root@ubuntu-test:~# cat /etc/cloud/cloud.cfg.d/99_cloudstack.cfg 
system_info:
  default_user:
    name: root
  package_mirrors:
    - arches: [i386, amd64]
      failsafe:
        primary: http://ubuntu.apt-get.eu/ubuntu
        security: http://security.ubuntu.apt-get.eu/ubuntu

disable_root: false

cloud_config_modules:
 - emit_upstart
 - snap_config
 - ssh-import-id
 - locale
 - [ set-passwords, always ]
 - grub-dpkg
 - apt-pipelining
 - apt-configure
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd
 - byobu

datasource:
  None: {}
datasource_list:
  - ConfigDrive
root@ubuntu-test:~#
</pre>

Files on the CD-Rom:

<pre>
root@ubuntu-test:~# find /mnt/cdrom/
/mnt/cdrom/
/mnt/cdrom/openstack
/mnt/cdrom/openstack/latest
/mnt/cdrom/openstack/latest/meta_data.json
/mnt/cdrom/openstack/latest/network_data.json
root@ubuntu-test:~#
</pre>

I generated this ISO manually on a non-CloudStack environment to test it, but we could store all the network information we have from a VM inside the ConfigDrive.

**Comment by rhtyd** [comment]
@wido yes ideally that's the use of config drive feature. I would see this as a bug, if currently it's not possible to share/send the network (ip and dns) currently. If you do decide to implement the fix, please open PR for 4.11 branch.

**Comment by wido** [comment]
@rhtyd Yes, it would be great! It would allow for much larger scaling without the need of DHCP. That removes the VR in many use-cases.

I haven't got ConfigDrive to work yet (offerings which wouldn't work...), but from the code I saw it only generates a empty network_data.json file.

Happy to work on this and write against 4.11

**Comment by DaanHoogland** [comment]
no milestones and no related PRs is this resolved or being worked on?

**Comment by NuxRo** [comment]
Hi, I'd be interested as well.

**Comment by wido** [comment]
This is still interesting. But @GabrielBrascher and me have been working on other things and haven't been able to give this more attention.

With this (as mentioned) there would be no need for a Virtual Router in many cases.

**Comment by DaanHoogland** [comment]
but no milestone to put to it still, @wido ?

**Comment by wido** [comment]
Not yet @DaanHoogland. I'd like to keep this open for future reference. Might be that somebody else wants to pick this up before we have time.

**Comment by svenvogel** [comment]
@wido is there any idea how you plan to implement this without a virtual router. this will be interesting for us because of the future use of TF we will lost the VR.

**Comment by NuxRo** [comment]
@svenvogel Not sure if this is what you are asking, but the DHCP server would not longer be needed as the IP addressing details will be supplied to the VM via the configdrive ISO, cloud-init/scripts will read them and do the rest of the config.

**Comment by wido** [comment]
@svenvogel and @NuxRo Indeed. With ConfigDrive and network information there is no more need for a DHCP server (thus Virtual Router) in a network.

From the local drive cloud-init can fetch all the required network information and configure the network interface accordingly.

**Comment by weizhouapache** [comment]
this issue is not implemented yet in 4.18.0

**Comment by alexandremattioli** [comment]
Especially relevant to Edge Zones.

**Comment by rohityadavcloud** [comment]
In progress by @vishesh92 at https://github.com/apache/cloudstack/pull/9329
