### ISSUE TITLE
incorrect number of public lb ip in UI

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2874]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

KVM, advanced networking

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

In UI, in VPC view, number of "public lb ip" per tier is displayed incorrectly. Instead number of forwarding rules is displayed [screen](https://postimg.cc/FYm0BNZY)

**Comment by anuragaw** [comment]
Close to finalizing this. Discovered an unrelated change with this investigation in GenericDaoBase#searchAndCount
