### ISSUE TITLE
[4.11.2] VR: ip_tables tcp match: ony valid for protocol 6

### ISSUE THREAD

**Issue by resmo** [apache/cloudstack#2882]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2, 4.11.1
~~~

##### SUMMARY

seeing errors in VR console 

![selection_200](https://user-images.githubusercontent.com/23809/46535253-13166e00-c8ab-11e8-86e9-a8aafea085fe.png)

##### STEPS TO REPRODUCE

~~~
see console log of VR
~~~

##### EXPECTED RESULTS

~~~
no errors
~~~

##### ACTUAL RESULTS

~~~
 ip_tables tcp match: ony valid for protocol 6
~~~

**Comment by rhtyd** [comment]
This is largely an ignorable warning, it means iptables match rules were matched against something other than an IP packet. A lot of legacy VR programming code (old style of rules etc) require a proper cleanup.

**Comment by resmo** [comment]
haven't seen this in 4.11.1

**Comment by resmo** [comment]
also saw this in 4.11.1

**Comment by rhtyd** [comment]
Unable to reproduce, kindly reopen if reproducible.
