### ISSUE TITLE
Feature Request - Create shared network in advanced zone using GRE tunnels / OVS Plugin

### ISSUE THREAD

**Issue by bdonnahue** [apache/cloudstack#2885]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
OVS Plugin

##### CLOUDSTACK VERSION
4.11.1.0

##### CONFIGURATION
Advanced Network
GRE Isolation
XenServer 7.2
1 physical network hosting all network traffic types

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I cannot create a shared network through the GUI. I see the following error message in my logs:

2018-09-24 22:19:07,803 ERROR [c.c.a.ApiServer] (qtp788117692-144094:ctx-75aeff02 ctx-93156a36) (logid:3b14107d) unhandled exception executing api command: [Ljava.lang.String;@11e8bdf4 com.cloud.utils.exception.CloudRuntimeException: Unable to convert network offering with specified id to network profile

The issue was discussed here: https://github.com/apache/cloudstack/issues/2863

##### STEPS TO REPRODUCE
Create an advanced network and try to create shared network

##### EXPECTED RESULTS
Shared network screated

##### ACTUAL RESULTS
Error message displayed

**Comment by bdonnahue** [comment]
@rhtyd is there any way to get this prioritized for an upcoming release?

**Comment by rhtyd** [comment]
@bdonnahue we couldn't find any contributor who has an interest around OVS to work on it in this milestone, we can push to the next milestone. In case a PR makes towards master in next week, we can include it towards 4.13 milestone.

**Comment by bdonnahue** [comment]
@rhtyd I would be interested in fixing / rearchitecting the current solution but I am lacking some understanding of the cloudstack datamodel and codebase. What would be the best way to arrange a knowledge transfer with a seasoned developer? Mailing list?

**Comment by rhtyd** [comment]
@bdonnahue yes join the dev mailing list and to get started on kvm based development you can try https://github.com/rhtyd/monkeybox

**Comment by DaanHoogland** [comment]
@bdonnahue are you addressing this? or shall i close the issue?

**Comment by DaanHoogland** [comment]
@bdonnahue are you addressing this? or shall i close the issue? or mark it for milestone 5.0?
