### ISSUE TITLE
Cloudstack 4.11.1.0 - Static NAT not functioning in Advanced Zone with GRE Isolation

### ISSUE THREAD

**Issue by bdonnahue** [apache/cloudstack#2886]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
VPC / Router VM

##### CLOUDSTACK VERSION
4.11.1.0

##### CONFIGURATION
Advanced Network
GRE Isolation
XenServer 7.2
1 physical network hosting all network traffic types

##### SUMMARY
I am able to provision a Static NAT for a VPC defined in an Advanced Zone using GRE Isolation. The Static NAT does not behave as expected.

From the router VM I am able to SSH to the public IP allocated for the Static NAT; It redirects to the instance. Looking at the Iptables and routing table it looks like the router VM is not prepared to forward traffic as desired.

##### STEPS TO REPRODUCE
Create an Static NAT
Try to SSH / Ping the Public IP

##### EXPECTED RESULTS
Connection established / ping reply

##### ACTUAL RESULTS
Connection timeout / ping timeout

**Comment by bdonnahue** [comment]
I tried troubleshooting this. I added an ACL with an ingress/egress rules to allow all traffic. I was not able to ping / ssh the instance behind the public ip. I had a look at the iptables and routing table and I do not see how the packet would be forwarded.

**Comment by bdonnahue** [comment]
I have been digging into this further. I ran iptables-save on the router before and after adding a new ACL to the VPC. The ACL had two rules (ingress/egress) to allow all traffic form all protocols (0.0.0.0/0 CIDR). The iptables showed no difference at all.

**Comment by bdonnahue** [comment]
I also tried adding an ACL to use the 15.0.0.0/8 subnet (which is the VPC WAN) and saw no changes to the router.

**Comment by rafaelweingartner** [comment]
As we discussed, this is not a problem. It was a misunderstanding when using ACLs.

**Comment by bdonnahue** [comment]
Thanks @rafaelweingartner. Yes, user error on my part.
