### ISSUE TITLE
ssh-keys instances ERROR

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2895]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

KVM, Advanced Networking

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

When click to "View Instances" link in project View for ssh-keys - error is displayed instead of instances list 

##### STEPS TO REPRODUCE

Login to UI -> switch to project view -> click to "Accounts" -> choose "SSH keys" -> choose any ssh key -> click "View instances" [Screen](https://postimg.cc/DJ05Gwdz)

**Comment by resmo** [comment]
similar problem fixed with network.js in bff7c01f19264e85c0da4a79c45f619761cfcc86

**Comment by anuragaw** [comment]
Pushed a PR for fixing the bug @izenk
