### ISSUE TITLE
Shared Networks documentation

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2906]
##### ISSUE TYPE

 * Documentation Report
 

##### COMPONENT NAME

~~~
Documentation
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### SUMMARY

[Shared Network](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/networking.html#shared-networks) section contains link to "Configuring a Shared Guest Network" - which is:
![screen shot 2018-10-18 at 12 38 07](https://user-images.githubusercontent.com/6417697/47145566-b36c8980-d2d2-11e8-872d-11751543777b.png)

So, there is no info how Shared Network works..

Also, many links on this section [docs](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/networking.html#creating-a-new-network-offering) are broken..
e.g: [remote-access-vpn](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/networking2.html#remote-access-vpn)

**Comment by izenk** [comment]
Also documentation for Network Services needed, like: what is Gateway service in Service offering

**Comment by rhtyd** [comment]
The doc link is incorrect, we've also consolidated all the docs at docs.cloudstack.apache.org. The article you're looking for is here; http://docs.cloudstack.apache.org/en/latest/adminguide/networking/advanced_zone_config.html#configuring-a-shared-guest-network

**Comment by izenk** [comment]
@rhtyd thanks,
There is no any info about "Supported services" in shared netwoks (dns, dhcp and so on). Who will be responsible to these services, some kind of VR or somebody external?
I mean, that's no clear how it's organized in Shared Networks?

**Comment by rhtyd** [comment]
It depends but yes @izenk supported services could be external, by default these supported services (dhcp and dns) are provided by the VR.

**Comment by izenk** [comment]
@rhtyd is documented(I mean dhcp/dns in shared network) anywhere?
Here: [docs](http://docs.cloudstack.apache.org/en/latest/adminguide/networking/advanced_zone_config.html#configuring-a-shared-guest-network) - no. Just mentioned how to create shared network. But my question is how dhcp/dns will be configured and what is the difference with isolated guest network and etc.

**Comment by rhtyd** [comment]
Please discuss on the dev/user list @izenk please only use Github issues for reporting issues. For any doc bugs, please report on the https://github.com/apache/cloudstack-documentation repo. Closing on this remark.
