### ISSUE TITLE
Private gateway can't be deleted

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#2908]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Node
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

~~~
Advanced Network, KVM bridged
~~~

##### OS / ENVIRONMENT

~~~
CentOS 4.11.1
~~~

##### SUMMARY

Its possible to create VPC offering without services, then add VPC based on this offering, then add Private Gateway for this VPC, then add route for this Private Gateway.
During route creation error is displayed:
![screen shot 2018-10-18 at 18 39 45](https://user-images.githubusercontent.com/6417697/47166617-44f4ef00-d305-11e8-9a5a-3ad9fc468b1e.png)

**But** route still being created. Then if I try to delete route - I can't, because of the same error.
So created route can't be deleted and as a result Private Gateway can't be deleted also and VPC can't be deleted too.

**Comment by rhtyd** [comment]
Can you test with 4.11.2.0-rc3?

**Comment by andrijapanic** [comment]
Issue still present - with identical messages as described above (simple workarroun - go to DB, and delete problematic route from cloud.static_route table) after which you can delete the Private Gateway.

**Comment by anuragaw** [comment]
Looking into this.
