### ISSUE TITLE
mvn needs -B switch

### ISSUE THREAD

**Issue by querplis** [apache/cloudstack#2910]
https://github.com/apache/cloudstack/blob/233f46c94b0b792d3f674cda120066a97e04c8ea/tools/build/setnextversion.sh#L127

without -B ( batch mode ), if maven has to download anything it will end in variable.

worth to change here too, not critical tho
https://github.com/apache/cloudstack/blob/233f46c94b0b792d3f674cda120066a97e04c8ea/tools/build/setnextversion.sh#L131

**Comment by rhtyd** [comment]
LGTM, @querplis can you send a pull request to master?

**Comment by rhtyd** [comment]
Fixed in PR. Closing.
