### ISSUE TITLE
SSH key pairs are not searchable

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#2920]
The `keyword` argument in [`listSSHKeyPairs`](https://cloudstack.apache.org/api/apidocs-4.11/apis/listSSHKeyPairs.html) is ignored, causing the search in the UI not to work.

* The command doesn't specify it as parameter despite it being documented: https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/api/src/main/java/org/apache/cloudstack/api/command/user/ssh/ListSSHKeyPairsCmd.java#L36
* Seems like it should be added as criteria here: https://github.com/apache/cloudstack/blob/1fa4f10a9ea65f156464da1671a4dbf62cc88e06/server/src/main/java/com/cloud/server/ManagementServerImpl.java#L3665
* Just like: https://github.com/apache/cloudstack/blob/1fa4f10a9ea65f156464da1671a4dbf62cc88e06/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L1194

**Comment by dhlaluku** [comment]
@anuragaw operations such as adding labels and reviewers on the PR are only allowed for committers. We contributors can only request reviewers via comments as you did.
