### ISSUE TITLE
add public IP range to domain fails in the inital setup (UI Problem)

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#2929]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloudstack UI
~~~

##### CLOUDSTACK VERSION

~~~
we use the master branch. -> 4.12.0
~~~

##### CONFIGURATION

advanced network, CentOS, KVM

##### SUMMARY

If you create a public network in the infrastructure->zone->physical bridge->ip ranges and you add a ip range with initial "set reservation" the reservation will be set to "[ROOT] System"

after its created you can change it again and its working BUT i think it should be initially set correctly to the account/domain.

##### STEPS TO REPRODUCE

~~~
1. add the public network data
~~~
![image](https://user-images.githubusercontent.com/5433844/47563462-2eaceb80-d922-11e8-8d7b-f4c3c6fcbaff.png)
~~~
2. set in the initial configuration a other domain e.g. dummy
~~~
![image](https://user-images.githubusercontent.com/5433844/47563683-e215e000-d922-11e8-9e6b-a77c5f560287.png)
~~~
3. you will see it will not set the "dummy" domain but [ROOT] System... 
~~~
![image](https://user-images.githubusercontent.com/5433844/47563694-e80bc100-d922-11e8-9f55-7caf159538e3.png)
![image](https://user-images.githubusercontent.com/5433844/47563717-fb1e9100-d922-11e8-81a2-1eaaeaf5f065.png)
~~~
4. after that it i add it again it works
~~~
![image](https://user-images.githubusercontent.com/5433844/47563726-070a5300-d923-11e8-84a7-756bfde6f477.png)
![image](https://user-images.githubusercontent.com/5433844/47563730-0a054380-d923-11e8-8f85-2e9869143ce9.png)

##### EXPECTED RESULTS

~~~
it should be set "initial" the correct account and/or domain!
~~~

**Comment by rhtyd** [comment]
@nvazquez can you triage this?

**Comment by svenvogel** [comment]
@nvazquez Can you check this?

**Comment by nvazquez** [comment]
@svenvogel @rhtyd sure, I'll be working on this one and will update you soon
