### ISSUE TITLE
set affinity for user (ui problem)

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#2986]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11 -> 4.12
~~~

##### CONFIGURATION

anvanced network

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

If a user want to set a affinity below the instance setting he will get a layered windows.

##### STEPS TO REPRODUCE

<img width="470" alt="bildschirmfoto 2018-10-30 um 17 32 43" src="https://user-images.githubusercontent.com/5433844/47734141-131b4b00-dc6a-11e8-9027-a7714c645b4c.png">
<img width="1429" alt="bildschirmfoto 2018-10-30 um 17 21 00" src="https://user-images.githubusercontent.com/5433844/47734189-2dedbf80-dc6a-11e8-8a69-177f05751ca9.png">
<img width="1309" alt="bildschirmfoto 2018-10-30 um 17 20 36" src="https://user-images.githubusercontent.com/5433844/47734195-3219dd00-dc6a-11e8-8da4-1c3d8eb29f74.png">

##### EXPECTED RESULTS

~~~
the affinity window, not a layered window
~~~

**Comment by svenvogel** [comment]
@nvazquez another ui problem, maybe you can have a look :)

**Comment by rafaelweingartner** [comment]
@svenvogel can you take a look at #2987?

**Comment by svenvogel** [comment]
@rafaelweingartner we tested it. it works! great work from you! LGTM!

**Comment by rafaelweingartner** [comment]
can you go to https://github.com/apache/cloudstack/pull/2987 and approve the PR?

**Comment by svenvogel** [comment]
yes. we approved your pull request #2987 . it works fine.
