### ISSUE TITLE
Unable to create network post upgrade to 4.11

### ISSUE THREAD

**Issue by somejfn** [apache/cloudstack#2989]
##### ISSUE TYPE
 * Bug Report
##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2rc3
~~~

##### CONFIGURATION
CentOS 7 on KVM.  Upgraded from 4.9.3. 

Using shared networks with no services since physical network provide DHCP/DNS.

The network offering:

{
  "count": 1, 
  "networkoffering": [
    {
      "availability": "Optional", 
      "conservemode": true, 
      "displaytext": "ExternalTenantNetwork", 
      "egressdefaultpolicy": true, 
      "forvpc": false, 
      "guestiptype": "Shared", 
      "id": "3b1e09fe-2350-4d88-87f3-8c6ba656f6ec", 
      "isdefault": false, 
      "ispersistent": false, 
      "name": "ExternalTenantNetwork", 
      "networkrate": -1, 
      "service": [], 
      "serviceofferingid": "ef26069f-8183-4c27-bc68-1f405597553d", 
      "specifyipranges": true, 
      "specifyvlan": true, 
      "state": "Enabled", 
      "supportspublicaccess": false, 
      "supportsstrechedl2subnet": false, 
      "traffictype": "Guest"
    }
  ]
}

##### OS / ENVIRONMENT
CentOS 7.4/KVM

##### SUMMARY
Creating a new network the same way as on 4.9.3 fails with error:

cs createNetwork name="10.73.220.0/24" displaytext="10.73.220.0/24" vlan=531 networkofferingid=3b1e09fe-2350-4d88-87f3-8c6ba656f6ec zoneid=9f800143-d7a0-4989-a1f4-d6b6b66198ee projectid=ee24f6f0-56b7-4288-b23b-9a56190c2960 StartIP=10.73.220.20 endIp=10.73.220.200 gateway=10.73.220.1 netmask=255.255.255.0
Cloudstack error: HTTP response 530
{
  "createnetworkresponse": {
    "cserrorcode": 4250, 
    "errorcode": 530, 
    "errortext": "Unable to convert network offering with specified id to network profile", 
    "uuidList": [
      {
        "description": "offeringId", 
        "serialVersionUID": -7514266713085362352, 
        "uuid": "3b1e09fe-2350-4d88-87f3-8c6ba656f6ec"
      }
    ]
  }
}

##### STEPS TO REPRODUCE

Create network offering as above on 4.9.3,  upgrade to 4.11.2 and attempt creating the network above

~~~

~~~

##### EXPECTED RESULTS
~~~
Network gets created as before
~~~

##### ACTUAL RESULTS
~~~
In the MS logs:


2018-10-30 20:01:26,311 DEBUG [c.c.a.ApiServlet] (qtp895947612-417:ctx-3dbb5c36) (logid:9755ae2f) ===START===  10.99.97.88 -- GET  endIp=10.73.220.30&acltype=account&name=10.73.220.0%2F24&networkofferingid=3b1e09fe-2350-4d88-87f3-8c6ba656f6ec&StartIP=10.73.220.20&projectid=ee24f6f0-56b7-4288-b23b-9a56190c2960&vlan=531&zoneid=9f800143-d7a0-4989-a1f4-d6b6b66198ee&netmask=255.255.255.0&apiKey=c_56pI8PmZeTaBeBnl7_zE8bEhzWsSzGqOcH6VYEL7SU1fNz7G5888a2Gm7NzNE_8vHwBMqWAEOvD96rg6fcyA&displaytext=10.73.220.0%2F24&signature=fx1mEDV%2ButfOo5ES5mzAFmtqPPU%3D&command=createNetwork&response=json&gateway=10.73.220.1
2018-10-30 20:01:26,359 DEBUG [c.c.n.g.BigSwitchBcfGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network, the physical isolation type is not BCF_SEGMENT
2018-10-30 20:01:26,362 DEBUG [o.a.c.n.c.m.ContrailGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network
2018-10-30 20:01:26,364 DEBUG [c.c.n.g.NiciraNvpGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network
2018-10-30 20:01:26,366 DEBUG [o.a.c.n.o.OpendaylightGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network
2018-10-30 20:01:26,369 DEBUG [c.c.n.g.OvsGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network
2018-10-30 20:01:26,377 DEBUG [o.a.c.n.g.SspGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) SSP not configured to be active
2018-10-30 20:01:26,379 DEBUG [c.c.n.g.BrocadeVcsGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design this network
2018-10-30 20:01:26,382 DEBUG [c.c.n.g.NuageVspGuestNetworkGuru] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Refusing to design network using network offering 16 on physical network 200
2018-10-30 20:01:26,384 DEBUG [o.a.c.e.o.NetworkOrchestrator] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Releasing lock for Acct[fc93ac67-21fc-47db-9611-760b48c6668f-PrjAcct-tenant-531-1]
2018-10-30 20:01:26,388 DEBUG [c.c.u.d.T.Transaction] (qtp895947612-417:ctx-3dbb5c36 ctx-45e3659a ctx-d6368d16) (logid:9755ae2f) Rolling back the transaction: Time = 39 Name =  qtp895947612-417; called by -TransactionLegacy.rollback:890-TransactionLegacy.removeUpTo:833-TransactionLegacy.close:657-Transaction.execute:43-Transaction.execute:47-NetworOrchestrator.createGuestNetwork:2308-NetworkServiceImpl$4.doInTransaction:1383-NetworkServiceImpl$4.doInTransaction:1331-Transaction.execute:40-NetworkServiceImpl.commitNetwork:1331-NetworkServiceImpl.createGuestNetwork:1294-NativeMethodAccessorImpl.invoke0:-2
com.cloud.utils.exception.CloudRuntimeException: Unable to convert network offering with specified id to network profile
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.setupNetwork(NetworkOrchestrator.java:715)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$10.doInTransaction(NetworkOrchestrator.java:2357)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator$10.doInTransaction(NetworkOrchestrator.java:2308)
	at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.createGuestNetwork(NetworkOrchestrator.java:2308)
	at com.cloud.network.NetworkServiceImpl$4.doInTransaction(NetworkServiceImpl.java:1383)
	at com.cloud.network.NetworkServiceImpl$4.doInTransaction(NetworkServiceImpl.java:1331)
	at com.cloud.network.NetworkServiceImpl.commitNetwork(NetworkServiceImpl.java:1331)
	at com.cloud.network.NetworkServiceImpl.createGuestNetwork(NetworkServiceImpl.java:1294)
	at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
	at com.sun.proxy.$Proxy231.createGuestNetwork(Unknown Source)

I know since 4.10, L2 networks should provide equivalent functionality but still the other way should still work. 

~~~

**Comment by borisstoyanov** [comment]
Hi @somejfn, shouldn't the guest type of the network offering be L2, instead of Shared?

**Comment by somejfn** [comment]
L2 did not exist in 4.9.3 and unless we have a way to convert them to L2
live on 4.11.2 (I'd like that)....  well the existing network offering
remain a shared one.

We built our provisioning process (our own API extensions) on those shared
networks with no services.  So we will change our code to support the new
L2 networks somehow but at the same time not being retro compatible here is
kind of a regression no ? I would also like to understand the reasoning
behind this error which is everything but comprehensive for the admin.

**Comment by borisstoyanov** [comment]
Hi @somejfn, I've tried reproducing this on an upgraded env from LTS 4.9.3 to 4.11.2 RC4
Using this offering: 
a91d1c0e-49cb-4d49-9537-3399d653f2b5
```
{
  "count": 1,
  "networkoffering": [
    {
      "availability": "Optional",
      "conservemode": true,
      "displaytext": "test",
      "egressdefaultpolicy": true,
      "forvpc": false,
      "guestiptype": "Shared",
      "id": "a91d1c0e-49cb-4d49-9537-3399d653f2b5",
      "isdefault": false,
      "ispersistent": false,
      "name": "test",
      "networkrate": 200,
      "service": [],
      "serviceofferingid": "0295faf4-bdc3-41de-b784-5367ed328baf",
      "specifyipranges": true,
      "specifyvlan": true,
      "state": "Enabled",
      "supportspublicaccess": false,
      "supportsstrechedl2subnet": false,
      "traffictype": "Guest"
    }
  ]
}
```

I was able to create a network: 
```
(local) SBCM5> create network name=test displaytext=test vlan=531 networkofferingid=a91d1c0e-49cb-4d49-9537-3399d653f2b5  zoneid=e42cabe7-1557-4532-9480-2a2d818988dc startIP=10.1.1.1 endIp=10.1.1.10 gateway=10.1.1.50 netmask=255.255.255.0 projectid=5277b062-e752-4b0d-b5b9-f3c0c40a1e37
{
  "network": {
    "acltype": "Domain",
    "broadcastdomaintype": "Vlan",
    "broadcasturi": "vlan://531",
    "canusefordeploy": true,
    "cidr": "10.1.1.0/24",
    "displaynetwork": true,
    "displaytext": "test",
    "dns1": "8.8.8.8",
    "dns2": "8.8.4.4",
    "domain": "ROOT",
    "domainid": "559d27ed-e0da-11e8-99de-062a88010832",
    "gateway": "10.1.1.50",
    "id": "9e74caa2-4cb4-4ddd-a724-33bc2385c34e",
    "ispersistent": false,
    "issystem": false,
    "name": "test",
    "netmask": "255.255.255.0",
    "networkofferingavailability": "Optional",
    "networkofferingconservemode": true,
    "networkofferingdisplaytext": "test",
    "networkofferingid": "a91d1c0e-49cb-4d49-9537-3399d653f2b5",
    "networkofferingname": "test",
    "physicalnetworkid": "92f0d57d-e1ee-4e8d-b2dc-151370ad2243",
    "redundantrouter": false,
    "related": "9e74caa2-4cb4-4ddd-a724-33bc2385c34e",
    "restartrequired": false,
    "service": [],
    "specifyipranges": true,
    "state": "Setup",
    "strechedl2subnet": false,
    "subdomainaccess": true,
    "tags": [],
    "traffictype": "Guest",
    "type": "Shared",
    "vlan": "531",
    "zoneid": "e42cabe7-1557-4532-9480-2a2d818988dc",
    "zonename": "trl-1711-v-M7-bstoyanov"
  }
}
```

Can you share any other details that could be affecting this? 

Otherwise, I think if you're not using any CS network services and all of them are managed externally L2 network is the way forward, but can't think of a way to swiftly migrate to it without having to recreate them all.. :(

**Comment by PaulAngus** [comment]
I have also tried a clean install and an upgrade from 4.9.3, i can't reproduce this issue. 
Have you retried on **RC4** ?

**Comment by somejfn** [comment]
Hmm I don't see the difference by the look of it.   The network offering on
4.9.3 was created this way:

    cs createNetworkOffering displaytext="{{ netoffer_name }}"
supportedservices=""
    guestiptype=Shared name="{{ netoffer_name }}" traffictype=GUEST
    SpecifyVlan=true SpecifyIpRanges=true networkrate=-1

Could the network service providers being enabled come into play ?

In my setup I only have these enabled:

> list networkserviceproviders filter=name state=Enabled
{
  "count": 2,
  "networkserviceprovider": [
    {
      "name": "ConfigDrive"
    },
    {
      "name": "BaremetalPxeProvider"
    }
  ]
}

**Comment by somejfn** [comment]
I'll upgrade to RC4 right now and see

**Comment by somejfn** [comment]
Same error on RC4

If that matters,  I created a new network offering on 4.11.2 similarly to
the 4.9.3 one with the only difference I enabled user-data via configdrive:

list networkofferings id=5955e06f-ab78-4a03-b2fa-9856f38a6ed8
{
  "count": 1,
  "networkoffering": [
    {
      "availability": "Optional",
      "conservemode": true,
      "details": {
        "ForgedTransmits": "true",
        "MacAddressChanges": "true",
        "PromiscuousMode": "true"
      },
      "displaytext": "ExternalTenantNetworkWithCloudInit",
      "egressdefaultpolicy": true,
      "forvpc": false,
      "guestiptype": "Shared",
      "id": "5955e06f-ab78-4a03-b2fa-9856f38a6ed8",
      "isdefault": false,
      "ispersistent": false,
      "name": "ExternalTenantNetworkWithCloudInit",
      "networkrate": -1,
      "service": [
        {
          "name": "UserData",
          "provider": [
            {
              "name": "ConfigDrive"
            }
          ]
        }
      ],
      "serviceofferingid": "ef26069f-8183-4c27-bc68-1f405597553d",
      "specifyipranges": true,
      "specifyvlan": true,
      "state": "Enabled",
      "supportspublicaccess": false,
      "supportsstrechedl2subnet": false,
      "traffictype": "Guest"
    }
  ]
}

But same error trying to use it:

> create network name=test displaytext=test vlan=531
networkofferingid=5955e06f-ab78-4a03-b2fa-9856f38a6ed8
 zoneid=9f800143-d7a0-4989-a1f4-d6b6b66198ee  startIP=10.1.1.1
endIp=10.1.1.10 gateway=10.1.1.50 netmask=255.255.255.0
projectid=b742de07-d8e0-417b-88dd-99779c0551a1
Error 530: Unable to convert network offering with specified id to network
profile
{
  "cserrorcode": 4250,
  "errorcode": 530,
  "errortext": "Unable to convert network offering with specified id to
network profile",
  "uuidList": [
    {
      "description": "offeringId",
      "serialVersionUID": -7514266713085362352,
      "uuid": "5955e06f-ab78-4a03-b2fa-9856f38a6ed8"
    }
  ]
}

**Comment by PaulAngus** [comment]
@somejfn i'm not sure how well config drive is supported in shared networks, can you check that it is enabled for the guest networks - infrastructure -> zones -> <ZONE> -> Physical Network Guest -> Network Service Providers

**Comment by somejfn** [comment]
Yep I did had to enable it there to get it working while testing with new
L2 networks.

**Comment by PaulAngus** [comment]
so to clarify - does the shared network with no-services deploy in 4.11.2rc4 if you don't use config drive ?
(the 'details' should be blank for KVM - they only apply to vSphere vSwitches).

how exactly did you 'enable' config drive after upgrading?

**Comment by somejfn** [comment]
Hi Paul,

I have 2 custom neworkofferings created as shared networks,  one with
config drive (post 4.11.2 upgrade) enabled and the other without (created
under 4.9.3).  Under both cases the network creation fails with that same
error.

**Comment by PaulAngus** [comment]
@somejfn - could you try something for me.  Could you create your network (without config drive) but **ADD** the Source NAT service,  And then try.  thanks.

**Comment by somejfn** [comment]
Hi Paul,

I created that offering (Source Nat via Virtual Router) but it's not
available/listed when I attempt to create a network.  I guess because the
zone/physical network do not have the virtual router provider enabled ?

**Comment by borisstoyanov** [comment]
@somejfn quick question, have you enabled the offering once you've created it?

**Comment by somejfn** [comment]
Yep:

{
  "count": 1,
  "networkoffering": [
    {
      "availability": "Optional",
      "conservemode": true,
      "displaytext": "ExternalTenantTest",
      "egressdefaultpolicy": true,
      "forvpc": false,
      "guestiptype": "Shared",
      "id": "469a1565-b78d-430c-a123-e9c0a72c6fad",
      "isdefault": false,
      "ispersistent": false,
      "name": "ExternalTenantTest",
      "networkrate": -1,
      "service": [
        {
          "capability": [
            {
              "canchooseservicecapability": false,
              "name": "SupportedSourceNatTypes",
              "value": "peraccount"
            },
            {
              "canchooseservicecapability": false,
              "name": "RedundantRouter",
              "value": "false"
            }
          ],
          "name": "SourceNat",
          "provider": [
            {
              "name": "VirtualRouter"
            }
          ]
        }
      ],
      "serviceofferingid": "ef26069f-8183-4c27-bc68-1f405597553d",
      "specifyipranges": true,
      "specifyvlan": true,
      "state": "Enabled",
      "supportspublicaccess": false,
      "supportsstrechedl2subnet": false,
      "traffictype": "Guest"
    }
  ]
}

**Comment by somejfn** [comment]
Also unable to make that provider enabled... not sure how to "configure it":

Provider is not ready, cannot Enable the provider, please configure the
provider first

**Comment by borisstoyanov** [comment]
yes, I've disabled it and got: 
`  "errortext": "Provider VirtualRouter is either not enabled or doesn't support service SourceNat in physical network id=201",`

You can go to Zone-> physical networks -> select the guest public network -> scroll down and select 'Configure' on Network Service Providers -> click on VR and enable it. 

There should be api call through cloudmonkey also...

**Comment by somejfn** [comment]
This is where I get the error:  Provider is not ready, cannot Enable the
provider, please configure the provider first

**Comment by somejfn** [comment]
I'd be happy to share screen with you on a Zoom if you want.  DM me on
slack if you can

**Comment by nvazquez** [comment]
Hi @somejfn,

I've been debugging the issue and could find the root cause of the failure. The DirectNetworkGuru could not implement the network as the it compares the expected isolation methods with the ones expected and if they differ it does not implement it. In this case the guru expected "VLAN" as isolation method on the physical network but found "vlan".

The workaround is to update your entries on table `physical_network_isolation_methods` by changing column `isolation_method` from "vlan" to "VLAN" and retry.

I'll open a PR with this fix and then will ask you to revert the changes on your database, get the PR code and retry if you don't mind.

Thanks,
Nicolas Vazquez

**Comment by somejfn** [comment]
Fix is confirmed. I can create a new network now based on the shared network offering.
thanks for the great support @borisstoyanov @PaulAngus

**Comment by Luskan777** [comment]
@somejfn , the same problem, how did you manage to solve it?
