### ISSUE TITLE
[Bug Report] - GRE Isolation Broken in VPC Tier

### ISSUE THREAD

**Issue by bdonnahue** [apache/cloudstack#2996]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
GRE Isolation / VPC Tier

##### CLOUDSTACK VERSION
4.11.2.0

##### CONFIGURATION
I have a VPC and a VPC Tier
I have an advanced zone which uses GRE Isolation
The zone hosts one pod and two clusters.
Each cluster has its own XenServer hypervisor

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I created wto VMs on two different hosts and attached them to the same vpc tier. The vms cannot communicate with eachother.

##### STEPS TO REPRODUCE
Create the advanced zone with GRE Tunnel Isolation
Create two clusters
Attach a host to each of the clusters
Create VMs on each host which are conected to same vpc tier
Ping host A from host B

##### EXPECTED RESULTS
DHCP lease assigned to both vms
Both vms can ping internet and eachother

##### ACTUAL RESULTS
No lease assigned to one of the VMs (the one not on the same machine as the router vm)
VMs cannot ping across hosts

**Comment by bdonnahue** [comment]
When I move the router from host A to host B, all the vms on host A loose connectivity to the tier network and the internet. All the vms on host B then get connectivity to the tier network and the internet

**Comment by bdonnahue** [comment]
Making the network redundant does not create any more router vms

**Comment by bdonnahue** [comment]
Hey can anyone confirm this is a bug? I have tried multiple installs but I would like to have a sanity check from someone else

**Comment by bdonnahue** [comment]
@DaanHoogland will to. I was able to track down who I think is the author who i believe is @frank-zhang with commit https://github.com/apache/cloudstack/commit/276e37115b58fde14602aa7d017cc1aded276ace
I will also see if I can reach out to him

**Comment by andrijapanicsb** [comment]
@bdonnahue is this something you can pick up (havae you pinged folds on the mailin lists) - or should we move it to 4.15 milestone, or perhaps close completely (although it seems like a bug, I'm not sure if anyone uses GRE these days)?

**Comment by bdonnahue** [comment]
@andrijapanicsb IIRC no one on the list was familiar with the GRE component. I don't think the issue should be closed. Either the feature needs to be fixed or removed with documentation being updated. I don't think moving the milestone makes sense if no one plans to work on it. I have not yet had time to pick this up and do the research.

**Comment by andrijapanicsb** [comment]
Are you saying to let it go, if it doesn't make into 4.14 @bdonnahue?

**Comment by bdonnahue** [comment]
@andrijapanicsb I do not think this should be part of the 4.14 milestone. I also do not think the issue should be closed.

**Comment by shoaibjdev** [comment]
> @bdonnahue is this something you can pick up (have you pinged folds on the mailing lists) - or should we move it to 4.15 milestone, or perhaps close completely (although it seems like a bug, I'm not sure if anyone uses GRE these days)?

**@andrijapanicsb** If GRE is not used widely, please advise what's the recommended SDN tunnel to be used with Open vSwitch for Advanced network on ACS. We managed to setup ACS 4.12 completely and VPCs are up, KVM VMs are also added and running but they are not assigned any IPs through OVS DHCP and appears like the tunnels are not being generated for the vm ports when using GRE. 
We came across this issue and several others reported on mailing list and realized GRE seems broken on ACS latest releases. So we need recommendation here for Advanced networks with Open vSwitch on KVM hosts.

**Comment by DaanHoogland** [comment]
moving it back to the milestone @rhtyd @PaulAngus @andrijapanicsb 

> @andrijapanicsb IIRC no one on the list was familiar with the GRE component. I don't think the issue should be closed. Either the feature needs to be fixed or removed with documentation being updated. I don't think moving the milestone makes sense if no one plans to work on it. I have not yet had time to pick this up and do the research.

what I read here is that we should remove the documentation part for GRE. (cc @bdonnahue)

**Comment by weizhouapache** [comment]
@DaanHoogland 
OVS/GRE is the native SDN solution in cloudstack, although it is not maintained and maybe nobody is using it, I think it is not good to remove it from cloudstack.
If nobody objects, I can work on some issues with GRE, eg #2996, #2885, #3802, #2863, #2886
cc @nvazquez @davidjumani @rhtyd

**Comment by nvazquez** [comment]
@weizhouapache I think the intention was to update the documentation for configuring OVS as it is outdated as it mentions it must use GRE isolation, but agree on not removing it from CloudStack - simply update the OVS documentation section

**Comment by weizhouapache** [comment]
> @weizhouapache I think the intention was to update the documentation for configuring OVS as it is outdated as it mentions it must use GRE isolation, but agree on not removing it from CloudStack - simply update the OVS documentation section

@nvazquez it also makes sense.

I will have a quick look at the issues. from my experience, it is not difficult to fix them.

**Comment by davidjumani** [comment]
@nvazquez @weizhouapache Have already added a note in the documentation about ovs https://github.com/apache/cloudstack-documentation/pull/133/files
