### ISSUE TITLE
storage upload -> "custom disk offerings" not displayed correctly (ui bug)

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#3001]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11->4.12 Master
~~~

##### OS / ENVIRONMENT

CentOS7

##### SUMMARY

When you try to upload a disk file in "storage->upload" e.g. a qcow2 the ui displays one description in the "custom disk offering" field. it will not display the disk offerings but instead "one" description of that?

##### STEPS TO REPRODUCE

1. goto Storage->Upload, put URL and Description into the fields and select "Custom Disk Offerings"
<img width="990" alt="bildschirmfoto 2018-11-05 um 12 08 55" src="https://user-images.githubusercontent.com/5433844/47995108-97e7e800-e0f4-11e8-94f1-834694a13b00.png">
<img width="430" alt="bildschirmfoto 2018-11-05 um 11 35 10" src="https://user-images.githubusercontent.com/5433844/47995144-aafab800-e0f4-11e8-980c-5ffe70d5906d.png">
2. thats our "Custom Disk Offerings"
<img width="988" alt="bildschirmfoto 2018-11-05 um 12 09 26" src="https://user-images.githubusercontent.com/5433844/47995171-c06fe200-e0f4-11e8-9e63-ee968618b3ae.png">
3. if this bug is fixed we run in the next #2820 

##### EXPECTED RESULTS

~~~
Normally there should be displayed all custom disk offerings
~~~

**Comment by svenvogel** [comment]
@mike-tutkowski what do you think?

**Comment by DennisKonrad** [comment]
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/ui/scripts/storage.js#L509-L552

This should be the relevant section.

**Comment by rhtyd** [comment]
Is this bug fixed or are you working on it - @svenvogel @DennisKonrad ?

**Comment by rhtyd** [comment]
Confirmed fixed by https://github.com/apache/cloudstack/pull/3479 which should be merged after a manual UI test.

**Comment by borisstoyanov** [comment]
I've just confirmed the fix it LGTM
