### ISSUE TITLE
Secondary Storage server fails if multiple Management servers are defined

### ISSUE THREAD

**Issue by ccheline** [apache/cloudstack#3006]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
systemvm agent (secondary storage vm)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1.0
~~~

##### CONFIGURATION

Global Setting
Key: host
Value: IP_ADDR1,IP_ADDR2 (eg: 10.0.0.20,10.0.0.21)

##### SUMMARY

When setting the host global setting to multiple addresses (separated by a comma), the secondary storage systemvm alerts and fails to further operate.

##### STEPS TO REPRODUCE

Change the global settings option "host" to multiple addresses as defined in the description field.
Restart the Secondary Storage systemvm.

~~~

~~~

##### EXPECTED RESULTS

~~~
Secondary Storage systemvm comes online and proceeds with standard operation (template management, etc)
~~~

##### ACTUAL RESULTS

Agent went to alert state and never performed secondary storage operations.

From cloud.log:
~~~
2018-11-05 22:07:04,813 WARN  [storage.resource.NfsSecondaryStorageResource] (maa
in:null)  destIp is not a valid ip address or cidr destIp=10.0.0.20,10.0.0.21
2018-11-05 22:07:04,854 ERROR [storage.resource.NfsSecondaryStorageResource] (maa
in:null) Couldn't cast null to integer
2018-11-05 22:07:04,860 INFO  [storage.template.DownloadManagerImpl] (main:null))
 DownloadManager: starting additional services since we are inside system vm
2018-11-05 22:07:04,866 ERROR [storage.resource.NfsSecondaryStorageResource] (maa
in:null) Couldn't cast null to integer
~~~

**Comment by borisstoyanov** [comment]
@ccheline couple of questions, 

- have you seen this with just the SSVM? 
- is the management server running and properly configured to work as a management cluster on all the IPs in the list
- is this a clean install or upgrade?

**Comment by rhtyd** [comment]
Can you test with 4.11.2.0 or latest? I'm unable to reproduce this @ccheline
