### ISSUE TITLE
BUG: Account Resource Count is incorred when removed Service Offerings used

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3009]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

Basic Networking, Domain ROOT/users, user: user

##### OS / ENVIRONMENT

Ubuntu 16.04 Server

##### SUMMARY

When you use in the account VM with SO removed, its resources are not accounted. Maybe specific only for accounts inside domains, but unsure. Bug found for env with domains. The bug was found when our engineer developed the feature for CSUI.

Maybe DOs also affected somehow.

##### STEPS TO REPRODUCE

1. admin: create an account.
2. admin: create SO which the account may use.
3. user: create VM with the SO.
4. admin: request account resource counters (correct).
4. admin: remove SO.
5. admin: request account resource counters (incorrect).

~~~

~~~

##### EXPECTED RESULTS

~~~
Resource calculation must be correct even when VMs with removed SOs are used.
~~~

##### ACTUAL RESULTS

~~~
Resources are calculated incorrectly. VM is accounted in VM count, but RAM and CPU is not accounted.
~~~

**Comment by rhtyd** [comment]
PR merged, closing.
