### ISSUE TITLE
Hypervisor max guest limit

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#3015]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Hypervisor / Management Server
~~~

##### CLOUDSTACK VERSION
~~~
master
~~~

##### CONFIGURATION
Max Guest Limit

##### SUMMARY
We currently enforce the number of Guests / Instances which can be run on a hypervisor. This is a fixed number not tied to RAM or CPU.

This limit should be removed. If the hypervisor has enough RAM and CPU we should think the HV is capable.

There should be no limit on the amount of Instances on a hypervisor

**Comment by rafaelweingartner** [comment]
I think that for XenServer it might still be needed. However, if a user tries to deploy in XenServer, more VMs than it allows to, an exception is thrown, and the exception handling in ACS would catch it. So, it might also not be needed, because the host would be then put in avoid state, and the VM deployment would be retried somewhere else.

**Comment by DaanHoogland** [comment]
tnx @rafaelweingartner , if you say the error handling is good enough to deal with it, we should go for it, it is not for ACS to decide what a hypervisor can, just to deal with it.

**Comment by DaanHoogland** [comment]
@wido any work related to this that youknow of?

**Comment by DaanHoogland** [comment]
one more remark in hindsight, @wido @rafaelweingartner . trying and failing is a big roundtrip from the deployment planner to the hypervisor. In the case of xen one might still want the ability to set a max if it is known anyway.

**Comment by nvazquez** [comment]
Hi @wido is there any work on this issue?

**Comment by wido** [comment]
> Hi @wido is there any work on this issue?

There has not been any work on this issue

**Comment by rhtyd** [comment]
We need the docs to be updated on per hypervisor basis for example;
VMware and XenServer - specifies in the docs no. of max hosts in a cluster in release notes (version-specific)
KVM - likely no concept of pool or cluster, so pratically as many no. of processes you can run on Linux

cc @nvazquez

**Comment by shwstppr** [comment]
@wido @rhtyd @nvazquez I've created a PR to skip guest limit check for KVM in code.
Do you guys suggest we also skip check for Xenserver?
We also have a default limit for maximum data volumes for a VM (used 6), should we make any changes there as well?
https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L3446-L3450

**Comment by wido** [comment]
> @wido @rhtyd @nvazquez I've created a PR to skip guest limit check for KVM in code.
> Do you guys suggest we also skip check for Xenserver?

I don't work with Xenserver, so I can't comment on that.

> We also have a default limit for maximum data volumes for a VM (used 6), should we make any changes there as well?
> https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L3446-L3450

I don't see any reason why 6 should be the limit. I always thought the limit was 10.

https://rwmj.wordpress.com/2017/04/25/how-many-disks-can-you-add-to-a-virtual-linux-machine/

That seems to imply that with KVM you can add 256 disks if you want.

**Comment by shwstppr** [comment]
For KVM, it may always end up 32 as the default version for KVM in hypervisor_capabilities table is set to 32,
```
MariaDB [cloud]> select * from hypervisor_capabilities where hypervisor_Type='KVM';
+----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
| id | uuid | hypervisor_type | hypervisor_version | max_guests_limit | security_group_enabled | max_data_volumes_limit | max_hosts_per_cluster | storage_motion_supported | vm_snapshot_enabled |
+----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
| 13 | 13   | KVM             | default            |               50 |                      1 |                     32 |                  NULL |                        1 |                   1 |
+----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
```

**Comment by wido** [comment]
> For KVM, it may always end up 32 as the default version for KVM in hypervisor_capabilities table is set to 32,
> 
> ```
> MariaDB [cloud]> select * from hypervisor_capabilities where hypervisor_Type='KVM';
> +----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
> | id | uuid | hypervisor_type | hypervisor_version | max_guests_limit | security_group_enabled | max_data_volumes_limit | max_hosts_per_cluster | storage_motion_supported | vm_snapshot_enabled |
> +----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
> | 13 | 13   | KVM             | default            |               50 |                      1 |                     32 |                  NULL |                        1 |                   1 |
> +----+------+-----------------+--------------------+------------------+------------------------+------------------------+-----------------------+--------------------------+---------------------+
> ```

I personally don't see any reason why somebody would go over 32 disks attached to a single VM. For now I think we can maintain that limit.
