### ISSUE TITLE
Cannot input backslashes on Console Proxy's french keyboard

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#3017]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
ConsoleProxy
~~~

##### CLOUDSTACK VERSION
~~~
4.11.1, 4.12
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Selecting French AZERTY keyboard on console proxy does not allow input backslashes (ALTGR+8)

##### STEPS TO REPRODUCE

~~~
Open ConsoleProxy on VM
Select Keyboard -> French AZERTY keyboard
Try to input backslashes using ALTGT + 8 keys
~~~

##### EXPECTED RESULTS
~~~
'\' characters
~~~

##### ACTUAL RESULTS

~~~
'*' or nothing (output may vary but not '\' character)
~~~

**Comment by rhtyd** [comment]
Can you advise how to check/test/fix this?

**Comment by nvazquez** [comment]
@rhtyd to test this we need to open a console proxy on any guest VM and select the French AZERTY keyboard. Then try to type a backslash using this combination of keys: 'ALTGR' + '8'. The output character won't be a backslash. Have tested this on 4.11 and 4.12 but not on current master

**Comment by DaanHoogland** [comment]
@nvazquez I just turned on french on my keyboard but in github it does not give me a '\' under ALT-8. instead it gives '¡', '8' or 'Û' depending on other modifiers. In fact the '\' is not found anywhere on that keyboard layout. When using the ABC-AWERTY layout the '\' is found under right-ALT-shift-'.'.
However when choosing french-PC as keyboard I do get '\' (using the right alt modifier). I think it is not a console, but a keyboard layout issue.

**Comment by rhtyd** [comment]
@nvazquez is this still an issue, in old console proxy or  new novnc?

**Comment by rhtyd** [comment]
ping @nvazquez is this applicable for old console proxy or the new novnc?

**Comment by DaanHoogland** [comment]
@rhtyd this tickets dates pre-novnc merge (june 2019)

**Comment by davidjumani** [comment]
@nvazquez Able to enter '/' while my local keyboard as well as the console keyboard is set to FR
![Screenshot from 2020-11-18 15-12-55](https://user-images.githubusercontent.com/8244774/99513451-aa1de180-29b0-11eb-8fe1-f818d8e939ba.png)

**Comment by nvazquez** [comment]
This was applicable for the old console proxy. Thanks @davidjumani, looks like we can close this issue
