### ISSUE TITLE
project - infrastructure - "Select View: Group by Account" (ui problem)

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#3029]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

 advanced networking

##### OS / ENVIRONMENT

CentOS7

##### SUMMARY

If you are a "admin" user (Role Type: admin) select a created project goto infrastructur -> virtual routers -> select view -> group by account then you get an "account and project id can't be specified together"

##### STEPS TO REPRODUCE

1. create a dummy / example project and select it
![image](https://user-images.githubusercontent.com/5433844/48506406-a9926380-e849-11e8-90e2-218f37dcde1c.png)
2. select "Infrastructure"
![image](https://user-images.githubusercontent.com/5433844/48506526-e3fc0080-e849-11e8-9122-73fc96da7ea8.png)
3. go to "Virtual Router"
![image](https://user-images.githubusercontent.com/5433844/48506575-07bf4680-e84a-11e8-8855-139ac7847c95.png)
4. you will see some router like the picture below
![image](https://user-images.githubusercontent.com/5433844/48506674-3d642f80-e84a-11e8-89a0-23bd6c0c71ca.png)
5. "select view" -> "group by account"
![image](https://user-images.githubusercontent.com/5433844/48506723-68e71a00-e84a-11e8-95e9-1e20ee0496af.png)
6. you get after some time (bubble of the ring) the following error or message "Account and projectId can't be specified together"
![image](https://user-images.githubusercontent.com/5433844/48506818-9cc23f80-e84a-11e8-9b42-d5b95795d747.png)
7. after the window popup you can click on close and see the account view and the message will not go away...
![image](https://user-images.githubusercontent.com/5433844/48507011-0d695c00-e84b-11e8-9cab-be86137456fb.png)

##### EXPECTED RESULTS

~~~
Normally there should not come this error or message i think. it should be only group the objects!
~~~

**Comment by rhtyd** [comment]
@pbankonier @svenvogel I think this feature could be (a) removed as it does not work, or (b) display list of routers/account this way -> routers belong to networks of project -> find accounts that belong with the project, group accounts by project and group networks to the project -> then group of routers ... (this is complicated), or (c) Alternatively, when project is selected don't pass project id (fixes the issue).

**Comment by DaanHoogland** [comment]
@svenvogel @pbankonier @rhtyd @bwsw I'm moving this to 4.15 as there is no clear consent on how it should work in the ticket. please amend/escalate/push back

**Comment by rhtyd** [comment]
@svenvogel this is not supported in Primate; instead in Primate we list all kinds of routers now including project ones. Since this is related to old UI where any new enhancements can be avoided, I'll close this but request if there's a use-case you're welcome to contribute changes to Primate instead. Thanks.
