### ISSUE TITLE
Impossible to edit domain specific settings in GUI (Safari and Chrome)

### ISSUE THREAD

**Issue by DagSonsteboSB** [apache/cloudstack#3032]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
* CloudStack GUI

##### CLOUDSTACK VERSION
* 4.11.2

##### CONFIGURATION
* LDAP configuration on subdomain

##### OS / ENVIRONMENT
* OS independent
* Fails in: Safari and Chrome
* Does not fail in Firefox

##### SUMMARY
![canteditdomain](https://user-images.githubusercontent.com/12859582/48559825-4dc8e880-e8e4-11e8-9f25-b0ec95f03c6a.png)
* On the domain specific settings screen it is impossible to get to the rightmost actions column with edit button. You can not scroll to it, you can not resize the screen to get to it, you can not use arrow keys to scroll to it.
* Page source shows the column being there.
* In addition resizing columns does not work at all. You can grab the column anchor and try to drag them out but you have no control over the resize. Even after releasing the mouse button the columns will randomly resize back and forth. Please note at no point will the random resize show the actions column.

##### STEPS TO REPRODUCE
* Create domain
* Click the settings column and try to access the actions column.

##### EXPECTED RESULTS
* Ability to edit domain settings.

##### ACTUAL RESULTS
* Domain settings have to be updated through the API
* Impossible to edit the settings through GUI

**Comment by izenk** [comment]
Can edit in 4.11.1
![screen shot 2018-11-15 at 18 09 36](https://user-images.githubusercontent.com/6417697/48561723-a5298180-e901-11e8-9dee-c8970f79a81d.png)

**Comment by DagSonsteboSB** [comment]
Thanks @izenk - have updated this to 4.11.2.

**Comment by rhtyd** [comment]
@DaanHoogland can you comment?

**Comment by DaanHoogland** [comment]
have to install chrome, in safari the edit box appears after tinkering with the clumn widths. it doesn't feel natural.prbably some css wizardry to do?!

**Comment by DaanHoogland** [comment]
chrome is worse, when tinkering with the column widths the edit button doesn't appear and the value almost disappears as well.

**Comment by rhtyd** [comment]
Fixed in Primate, btw.
