### ISSUE TITLE
ERROR when edit Project

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#3033]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### SUMMARY

Error appears when trying to edit Project's "Display Name"

##### STEPS TO REPRODUCE

1) Choose any project and click "Edit"
2) Edit "Display Name" field
3) Click "Apply"

Error appears:
~~~
Unable to decode parameter tags[0][key]; if specifying an object array, please use parameter[index].field=XXX, e.g. userGroupList[0].group=httpGroup
~~~

**Comment by izenk** [comment]
Error is reproducible if editing is doing under "Project View", if under "Default View" everything is ok.

**Comment by izenk** [comment]
Error is reproducible if editing is doing under "Project View", if under "Default View" everything is ok.

**Comment by DaanHoogland** [comment]
Ilia, for UI issues can you add screenshots, please?

**Comment by izenk** [comment]
@DaanHoogland sure
![screen shot 2018-11-19 at 11 47 38](https://user-images.githubusercontent.com/6417697/48695728-f763ee80-ebf0-11e8-9fa9-86082da6e69e.png)

**Comment by DaanHoogland** [comment]
may have been fixed (accidentally?) in another PR. I tried a 4.13 environment and editting the display name of a project work as expected.
