### ISSUE TITLE
Decision making logic of which Secondary storage to be used

### ISSUE THREAD

**Issue by dhlaluku** [apache/cloudstack#3041]
Related to this unresolved issue https://issues.apache.org/jira/browse/CLOUDSTACK-2919
Add proper check for disk space on secondary storage to be used for volume migration across clusters. The current logic does not validate if volume will fit in the destination storage pool, but only checks if whether secondary storage disk utilization has not reached 90%. 

##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.9+
~~~

##### CONFIGURATION

2+ Secondary Storage (ImageStore) pools with Zone scope
2+ Clusters 

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When performing cross-cluster volume migration in multi ImageStore environments within the same Zone. The volume is first copied the secondary storage, attached to a worker VM and then migrated to the destination storage pool. This is procedure is only successful when the following 2 conditions are satisfied
1. The ImageStore disk usage should not exceed a hardcoded value of 0.9 (90 %)
2. The size of the volume the volume to be migrated should exist the amount of free space available in the ImageStore.
![image](https://user-images.githubusercontent.com/19572501/48846435-d09be880-eda7-11e8-8c5d-f30bb558d38b.png)

##### STEPS TO REPRODUCE

~~~
- Fill up secondary storage disk up to 90%
- Perform cross-cluster volume migration through UI or API
~~~

##### EXPECTED RESULTS

~~~
An exception should be thrown explaining that no suitable secondary storage pool was found for volume migration.
~~~

##### ACTUAL RESULTS

~~~
CloudStack selects a random secondary storage pool and attempts to migrate the volume anyways and fails when the size of the volume exceeds the amount of free space within that particular secondary storage.
~~~

**Comment by dhlaluku** [comment]
Throw 'InsufficientCapacityException' when migration fails due to insufficient space in secondary storage

**Comment by rafaelweingartner** [comment]
Any chance on getting this into 4.12.0? Otherwise, I would move it to 5.0.0

**Comment by GabrielBrascher** [comment]
@dhlaluku any update on this one?

**Comment by dhlaluku** [comment]
@GabrielBrascher @rafaelweingartner I will pick this up some time next week.

**Comment by kioie** [comment]
@dhlaluku this one?

**Comment by dhlaluku** [comment]
@kioe yes

**Comment by rhtyd** [comment]
Ping @anuragaw

**Comment by rhtyd** [comment]
Refer for duplicate and related case of uploading template/iso/volume: https://github.com/apache/cloudstack/issues/3287 where secondary storage usage exceeds the threshold

**Comment by anuragaw** [comment]
what's the next steps on this issue @rhtyd ? Should I investigate and create a fresh PR as needed?

**Comment by rhtyd** [comment]
The selection of secondary storage should be refactored (the method) based on usage and throw exception when no available image store is found with enough capacity.
@shwstppr can you continue over this, there is an existing PR you can review or extend over.

**Comment by rhtyd** [comment]
Related:
https://github.com/apache/cloudstack/issues/3041
https://github.com/apache/cloudstack/issues/3287
https://github.com/apache/cloudstack/issues/3478

**Comment by rhtyd** [comment]
Related/dupes https://github.com/apache/cloudstack/issues/3478 closing this one.
