### ISSUE TITLE
User can see the setting tab of vms, and change the value of settings

### ISSUE THREAD

**Issue by ustcweizhou** [apache/cloudstack#3043]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
API/UI

##### CLOUDSTACK VERSION
4.11.2.0-RC6

##### CONFIGURATION
Advanced zone with security groups

##### OS / ENVIRONMENT
Management server and nodes are all Ubuntu 16.04

##### SUMMARY
The setting tab for vms is visible for all users. 
Users can change the value of all settings as well

##### STEPS TO REPRODUCE
go to instances -> Setting tab

##### EXPECTED RESULTS
Settings should be hidden for users
We do not allow users to change the settings.

##### ACTUAL RESULTS

users can change the settings

**Comment by rhtyd** [comment]
Ideally the tab should be always show, but when users try to edit settings and if VM is not stopped it should show an error like it does for reset password button etc

**Comment by anuragaw** [comment]
@ustcweizhou can you also please include some snapshot of the UI?

**Comment by rafaelweingartner** [comment]
@rhtyd this control should be done in the server side right? It is not just a UI problem, because if the USER uses the configurations API parameter, it seems that right now he/she would be able to change/override the overprovisioning configurations for his/her VMs.

**Comment by rhtyd** [comment]
@rafaelweingartner The backend need to honour the `display` field of a detail and perhaps we can add a global setting to say which details (by key/name) are blacklisted.
@anuragaw deploy a latest 4.11 based env, deploy a VM and then stop it, you should see a setting tab in the VM details view.

**Comment by rafaelweingartner** [comment]
@rhtyd that works. I also thought about adding a new parameter to that enum you created to indicate if the configuration can be changed/customized/overridden by the final user.

**Comment by rhtyd** [comment]
With https://github.com/apache/cloudstack/pull/3244 the settings tab editing is not allowed when VM is running in the UI. However I don't think we should restrict users to not change the values, as it is allowed via API anyway.
With https://github.com/apache/cloudstack/pull/3240 feature, users will know possible options they can pass. Wrt KVM, the number of allowed options/details are minimal.
