### ISSUE TITLE
Support multiple networks on vm in advanced zone with security groups

### ISSUE THREAD

**Issue by ustcweizhou** [apache/cloudstack#3045]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.12.0
~~~

##### CONFIGURATION

~~~
advanced zone with security groups
~~~
##### OS / ENVIRONMENT

~~~
Ubuntu/KVM
~~~
##### SUMMARY

~~~
We have the requirement that vm needs multiple IPs in different networks.
It is currently not supported by cloudstack
~~~
##### STEPS TO REPRODUCE
While create vm using instance wizard, if multiple shared networks are checked, an error message is displayed: "Can't create a vm with multiple networks one of which is Security Group enabled"

If create a vm with one network, and add vm to other networks. the nics will not work except the first nic.

iptables rules are only applied on first nic

##### EXPECTED RESULTS
~~~
Operations should succeed
iptables/ebtables rules should be applied on all nics
~~~

**Comment by ustcweizhou** [comment]
I will create a PR for this

**Comment by rhtyd** [comment]
Ping @ustcweizhou any update?

**Comment by ustcweizhou** [comment]
@rhtyd 
we have ported our changes to 4.11.3 and tested ok. it supports only KVM now.
We will present it in  our presentation in CCC NA 2019.
no ETA to master.

**Comment by rhtyd** [comment]
Okay, I'll remove the milestone then @ustcweizhou - looking forward to your PR whenever you send it and presentation in CCCNA19.
