### ISSUE TITLE
VM Details shows parameters which should not be shown to the end user

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3046]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.10 to 4.11.2.0
~~~

##### CONFIGURATION

Any

##### OS / ENVIRONMENT

All

##### SUMMARY

The settings tab for VMs displays VM related settings which should not be exposed to the end user.
These include:

• memoryOvercommitRatio
• cpuOvercommitRatio
• rootdisksize 

##### STEPS TO REPRODUCE

~~~
Create VM and navigate to the VM's settings tab
~~~

##### EXPECTED RESULTS

~~~
Only 'safe' settings should be displayed to the end user.
'safe' settings should be determined by an admin controlled blacklist or whitelist
~~~

##### ACTUAL RESULTS

~~~
The settings tab for VMs displays VM related settings which should not be exposed to the end user.
These include:
~~~

**Comment by DaanHoogland** [comment]
@PaulAngus I am removing UI as tag from this issue as it would be handled in the API

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack/pull/3213

**Comment by rhtyd** [comment]
Closed because https://github.com/apache/cloudstack/pull/3213 is merged.
