### ISSUE TITLE
Sort list of templates in the deploy VM wizard

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3050]
The list of templates in the deploy VM wizard is not sorted and comes randomly every time. Fix the list to be sorted (alphabetically)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11, all past versions
~~~

**Comment by smlshn** [comment]
I write function to sort any array by given key and 
I made required changes to sort the data available on each step by their suitable fields i.e
templates by name
serviceOfferings by cpuspeed
diskOfferings by disksize
affinityGroups by name
sshkeyPairs by name
network:
   - vpcs by name
   - networkOfferings by name

**Comment by rhtyd** [comment]
Closing the issue, will carry discussion and testing over the PR.

**Comment by anuragaw** [comment]
Templates now support a sortkey in master and this issue is no longer needed.
