### ISSUE TITLE
destroyVirtualMachine support force shutdown of VM

### ISSUE THREAD

**Issue by pdion891** [apache/cloudstack#3054]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
API

##### CONFIGURATION
Using detroyVirtualMachine, we should be able to force shutdown VM when needed. Something a VM is crashed on the hypervisor and required a force stop, the destroyVirtualMachine will fail due to stop command timeout.

command example could be:

```
detroy virtualmachine id=<...> forcestop=true
```

**Comment by rhtyd** [comment]
@pdion891 there is a global setting to force shutdown VMs on destroy you can use that.

**Comment by pdion891** [comment]
That would make sense,  gona have to test `vm.destroy.forcestop = true`

Thanks @rhtyd !

**Comment by rhtyd** [comment]
This was fixed in https://github.com/apache/cloudstack/pull/2108, closing based on this. @pdion891 kindly re-open if the global setting workaround is not acceptable.
