### ISSUE TITLE
Niche feature configuration is always prominent in UI (SSL Offload)

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3056]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

##### SUMMARY

When adding a load balancing rule a SSL Certificate column is presented to the user, regardless of whether the network offering supports SSL offload,
This feature is only available when using a NetScaler.

![image](https://user-images.githubusercontent.com/4810220/49027233-a5ded500-f197-11e8-8db1-cf38a24dceac.png)

##### STEPS TO REPRODUCE

~~~
Navigate to the load balancing tab in the UI when the environment does not have the NetScaler load-balancing feature enabled
~~~

##### EXPECTED RESULTS

~~~
Should not see option to upload an SSL certificate
~~~

##### ACTUAL RESULTS

~~~
see option to upload an SSL certificate
~~~

**Comment by onitake** [comment]
Wouldn't it be better to support SSL offloading for the built-in load balancer instead?
HAProxy can do SSL termination, though some work to prepare the configuration and combine certificate and key into one blob may be needed.

**Comment by PaulAngus** [comment]
It would certainly be nice.  I'm sure that the community would very much welcome the feature.  But for now the UI promises something that can't be provided most of the time.  And that's not ok...

**Comment by rhtyd** [comment]
Instead of removing the feature - we could allow admins/users to setup SSL termination via HAProxy that makes this an enhancement.

**Comment by rhtyd** [comment]
cc @weizhouapache do you have plans (or maybe via #4141 ) to support SSL offloading via nginx/haproxy?

**Comment by weizhouapache** [comment]
> cc @weizhouapache do you have plans (or maybe via #4141 ) to support SSL offloading via nginx/haproxy?

@rhtyd  SSL offloading is supported in PR #4141

**Comment by nvazquez** [comment]
@PaulAngus @weizhouapache is this issue still valid in the new UI?

**Comment by weizhouapache** [comment]
> @PaulAngus @weizhouapache is this issue still valid in the new UI?

@nvazquez seems not.

![image](https://user-images.githubusercontent.com/57355700/125596771-92a2dc97-f187-4e6f-af67-3a6b1fe3e1d6.png)

**Comment by nvazquez** [comment]
Thanks @weizhouapache, closing it
