### ISSUE TITLE
Some UI additions to #2919

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3068]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### SUMMARY

Enhancement of #2919 
From the internal review, some additions were raised to the UI of this feature: 

1. Upon submission add a warning message that the changes will take place after management restart

2. Pre-fill the UI form with the data user is about to change. This would make it far more easier for the end user to figure out what needs changing if anything. 
- one thing to keep an eye here is the masked password, if not changed we need to make sure we send the same (current one) as update instead of bunch of asterisks. 

##### STEPS TO REPRODUCE

Go to Infra -> select a zone -> select 'Update VMware Datacenter details'

**Comment by rhtyd** [comment]
the PR was for master, setting milestone to 4.12.0.0

**Comment by GabrielBrascher** [comment]
@borisstoyanov and @rhtyd what is the status of this issue? Should we keep it to 4.12.0.0?

**Comment by DaanHoogland** [comment]
looks like a feature so 4.14 and not 4.13.1,  @borisstoyanov @andrijapanicsb Can you have a slavic mob meeting about this one?

**Comment by andrijapanicsb** [comment]
Not sure if we'll have the time for this one, moving to 4.15, unless @shwstppr or someone can pick it up

**Comment by rhtyd** [comment]
I think these are largely addressed (pre-filling UI form and masked password) in Primate.

**Comment by rhtyd** [comment]
We don't do this yet though `Upon submission add a warning message that the changes will take place after management restart` cc @davidjumani

**Comment by rhtyd** [comment]
Moved here https://github.com/apache/cloudstack-primate/issues/577
