### ISSUE TITLE
Console proxy SSL fails in 4.11.2.0

### ISSUE THREAD

**Issue by msinhore** [apache/cloudstack#3072]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
Console Proxy
~~~

##### CLOUDSTACK VERSION
~~~
4.11.2.0
~~~

##### CONFIGURATION
Console Proxy SSL configuration performed in  4.9.3

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When I click to open the console of any VM, it shows in the left browser address bar the message "Connection is not secure". If I disable the protection, it works but without secure https connection. 
The ACS has been upgraded from 4.9.3.0 and it was working well before. 

##### STEPS TO REPRODUCE

Go to Instances > VM > Console.

~~~
Go to Instances > VM > Console
~~~

##### EXPECTED RESULTS

~~~
Open a console with SSL enabled. 
~~~

##### ACTUAL RESULTS

~~~
Console proxy have no secure layer.
~~~

**Comment by rhtyd** [comment]
Did you setup ssl certificate and configure global settings for consoleproxy suitably @msinhore ?

**Comment by andrijapanicsb** [comment]
I believe this might be a mis-configuration @msinhore - can you follow up please - or do you feel OK to close it ?

**Comment by msinhore** [comment]
Thanks guys. It was solved.
