### ISSUE TITLE
Install version 4.11.2.0 on CentoOS 7.5 with a dependency error

### ISSUE THREAD

**Issue by saliven1970** [apache/cloudstack#3074]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Packaging

##### CLOUDSTACK VERSION

4.11.1.0
4.11.2.0

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS7.5

##### SUMMARY

Install version 4.11.2.0 on CentoOS 7.5 with a dependency error: 
Error: Dependency detection failed: 
Libc.so.6 is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64 
Libc.so.6 (glibc_2.0) is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64 
Libc.so.6 (glibc_2.1) is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64 
Libc.so.6 (glibc_2.2) is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64 
Libc.so.6 (glibc_2.2.3) is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64 
Libc.so.6 (glibc_2.3) is needed by cloudstack-common-4.11.2.0-1.el7.centos.x86_64

##### STEPS TO REPRODUCE

1.Install  the cloudstack-common-4.11.2.0-1.el7.centos.x86_64.rpm

##### EXPECTED RESULTS

Installation succeeded

##### ACTUAL RESULTS

Install version 4.11.2.0 on CentoOS 7.5 with a dependency error

**Comment by saliven1970** [comment]
I downloaded the code 4.11.3-SNAPSHOT from Github and compiled it myself. There will be no dependency errors during the installation,Is it a compiled host environment problem?

**Comment by saliven1970** [comment]
In the same environment, 4.11.0.0 will not have this problem when it is installed

**Comment by saliven1970** [comment]
In the same environment, this dependency problem will also occur when testing the installation of 4.11.1.0.

**Comment by saliven1970** [comment]
After confirmation again, this problem appeared on CentOS 7.5, not CentOS 7.4. My system has been upgraded by yum and is already CentOS7.5.

**Comment by rhtyd** [comment]
@saliven1970 alright so you got the problem on centos 7.5 and not on 7.4 - please update the issue description. Thanks.

**Comment by rhtyd** [comment]
Could not reproduce the error, please try with latest CentOS 7.6 x86_64. Note: we only support x86_64 arch, and I'm not sure if installation was attempted on a non-x86_64 system.
Kindly re-open with more details about the system, version etc. if you can reproduce the error.
