### ISSUE TITLE
What about the old VPC after the VPC template is updated

### ISSUE THREAD

**Issue by Danny-jackshen** [apache/cloudstack#3079]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@Danny-jackshen invalid issue due to missing information, please re-submit a new one with more details and description. I'll close this one.
