### ISSUE TITLE
Provide recent standalone test instances 4.7 and 4.9 as Docker containers on DockerHub

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#3083]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.7
4.9
4.10
~~~

##### OS / ENVIRONMENT
CentOS

##### SUMMARY
Just to test the API, I need an easy way to have it, also in different versions without going through installation processes.
This request is not meant to support Docker as operational environment!

##### STEPS TO REPRODUCE
Go to DockerHub 
Search for CloudStack docker images

##### EXPECTED RESULTS

~~~
For a CloudStack version, there is a standalone Docker image
~~~
##### ACTUAL RESULTS

~~~
* No resent simulator images for CS versions 4.7 and 4.9

```
latest 1 GB  5 hours ago
4.5 2 GB 3 years ago 
4.6.0 2 GB 3 years ago
4.6rc1 2 GB 3 years ago

```
~~~
Apart from that, I could build the CentOS Docker image for 4.10 but not 4.7. Maybe it makes sense to setup Travis CI jobs.

**Comment by rhtyd** [comment]
I'm not sure who is owner/manager of the cloudstack dockerhub account and if it's possible for the project or community to manage that. You may use the dockerfile from the codebase to build your own.

@pdion891 @swill @resmo @wido @khos2ow @rafaelweingartner  anybody know?

**Comment by 1605200517** [comment]
I have tried to build 4.7 but get:

`docker build -f Dockerfile.centos6 -t cloudstack/management_centos6 .`

```
/bin/sh: line 0: cd: /etc/cloudstack/management: No such file or directory
/usr/share/cloudstack-common/scripts/vm/hypervisor/xenserver/vhd-util: No such file or directory
The command '/bin/sh -c cd /etc/cloudstack/management;     ln -s tomcat6-nonssl.conf tomcat6.conf;     ln -s server-nonssl.xml server.xml;     ln -s log4j-cloud.xml log4j.xml;     wget -O /usr/share/cloudstack-common/scripts/vm/hypervisor/xenserver/vhd-util     http://download.cloud.com.s3.amazonaws.com/tools/vhd-util' returned a non-zero code: 1

```

**Comment by rafaelweingartner** [comment]
I have no idea who owns it. It seems that somebody registered the namespace “cloudstack”. If the PMC has no clues on who owns the namespace there, we can reach Docker hub guys to reset the password and provide access to us.

Still, as far as I know, CloudStack as a community is not providing Docker images. It does not mean that I do not find the idea of providing such images interesting; quite the opposite, I find this is a great idea.

**Comment by 1605200517** [comment]
@rafaelweingartner who is PMC?

**Comment by rafaelweingartner** [comment]
It is not a person.

PMC=Project Management Comitee. 
https://cloudstack.apache.org/who.html

**Comment by khos2ow** [comment]
I'm a big +1 on making use of Docker in ACS development or even deployment.

The fact that @wido mentioned in ML a while back that [cloudstack/package-docker-deb](https://hub.docker.com/r/cloudstack/package-docker-deb/) belongs (maintained) to him, I would think he has some sort of control or at least can shed some light who has.

**Comment by khos2ow** [comment]
and when ownership is resolved I can even donate [khos2ow/cloudstack-rpm-builder](https://hub.docker.com/r/khos2ow/cloudstack-rpm-builder/) and [khos2ow/cloudstack-deb-builder](https://hub.docker.com/r/khos2ow/cloudstack-deb-builder/) to be part of the _official_ images as well.

**Comment by rhtyd** [comment]
I think we'll need somebody to maintain official docker images. Just to be clear, a community maintained package needs to be voted and passed in order to be considered an *official* release/artifact. Otherwise, it's just community maintained *stuff* which everybody could use but not officially endorsed by the project.

**Comment by khos2ow** [comment]
Exactly, that's why I proposed to move those two github repos and eventually dockerhub repos from `khos2ow` to `apache`/`cloudstack`.

**Comment by 1605200517** [comment]
@rhtyd  here is some evidence for the Docker images ownership from Apache Cloudstack Wiki.
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Dockerfiles
seems like @pdion891 might know more :-)

**Comment by DaanHoogland** [comment]
not much involvement here. Are there any people that feel responsible for the docker containers?

**Comment by resmo** [comment]
there are test container images for the ansible integration https://quay.io/repository/ansible/cloudstack-test-container?tab=tags https://github.com/ansible/cloudstack-test-container

note that the container will report 503 until it is fully deployed, the api keys to use are served on port `8080/admin.json`

**Comment by DaanHoogland** [comment]
tnx @resmo closing
