### ISSUE TITLE
Propose official CS Docker images for Docker Hub

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#3092]
To get into the Docker Hub library, a pull request needs to be done for this repo:

https://github.com/docker-library/official-images/tree/master/library

More information:
https://docs.docker.com/docker-hub/official_repos/#how-do-i-know-the-official-repositories-are-secure

**Comment by rhtyd** [comment]
We do have official org account here: https://hub.docker.com/u/apache
This dupes https://github.com/apache/cloudstack/issues/3083
