### ISSUE TITLE
KVM Agent with Local Storage requests other local storage pools from LibVirt

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3093]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Basic Zone, KVM, Local Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

When KVM CloudStack Agent is deployed in cluster which uses local storages only, it tries to fetch from libvirt all known storage pools, not only a local one. This causes exceptions in agent.

##### STEPS TO REPRODUCE

~~~
Deploy cluster with hosts which uses local storages. Find exceptions in agent log.
~~~

##### EXPECTED RESULTS

~~~
Agent only fetches from libvirt the storage pool which is local.
~~~

##### ACTUAL RESULTS

~~~
Agent fetches all storage pools, even which are not local.
~~~

**Comment by DaanHoogland** [comment]
most likely related to #3596 ,which says a similar thing about zone-wide storage.
