### ISSUE TITLE
Cloudstack API: concurrent virtual machine requests lead to variety of problems

### ISSUE THREAD

**Issue by dubauski** [apache/cloudstack#3103]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
API

##### CLOUDSTACK VERSION
4.9.2.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When requesting multiple virtual machines (via deployVirtualMachine REST method) using CloudStack API leads to various failures:
- 431 server response 
- duplicate private addresses assigned (intermittently)

##### STEPS TO REPRODUCE
1. Create VPC 
2. Create guest network
3. using deployVirtualMachine REST method request a virtual machine to be created in the guest network
4. without waiting for completion repeat step 3 for 20 other virtual machines. This step is performed in a parallel fashion: i.e. requests for new vms are issues from parallel threads (not sequentially)

##### EXPECTED RESULTS
All of the requested virtual machines created successfully

##### ACTUAL RESULTS
Error: Server returned HTTP response code: 431 for URL: http://<cs host>:8080/client/api/?apikey=xxxx&command=deployVirtualMachine&name=st2e03-oooodb01&networkids=<networkIdvalue>&response=json&serviceofferingid=<offeringid>&templateid=<templateid>&zoneid=<zoneId>&signature=<myapisignature>

**Comment by rhtyd** [comment]
Can you try using 4.11.2.0?

**Comment by dubauski** [comment]
@rhtyd 
http://docs.cloudstack.apache.org/projects/cloudstack-release-notes/en/4.11.2.0/ link is broken. Did concurrency bugs specifically get addressed in this release?

Is concurrent virtual machine creation supported by CloudStack?

**Comment by rhtyd** [comment]
Dupes: https://github.com/apache/cloudstack/issues/3025
Will try to fix towards 3025

**Comment by rhtyd** [comment]
@dubauski release notes are here: http://docs.cloudstack.apache.org/en/4.11.2.0/releasenotes/index.html
