### ISSUE TITLE
Account removal triggers event of unrelated user (from the different account) removal which has the same ID as account which is being deleted

### ISSUE THREAD

**Issue by brankomijuskovic** [apache/cloudstack#3109]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

##### CONFIGURATION

Advanced networking, KVM

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When account is deleted, an event is generated which prints attempt of deletion of user which has the same database ID as the account which is being deleted, although the user can be from completelly different account/domain.  

##### STEPS TO REPRODUCE

* Create an account under one domain e.g. account 'account2' under 'TEST' domain.
* Then create additional user (e.g. 'account2-user2') under the same 'account2' account and note the new user ID in the DB e.g 21
* Then create several more accounts under some other domain (e.g. 'domain-test') and check in the DB that ID of one of those new accounts (e.g. 'account5') is the same as the second user ('account2-user2') ID from the previous account
* Delete the 'account5'
* Now check Events and find the attempt to delete unrelated user (account2-user2) and account (account2) while deleting 'account5'

![account-accounts](https://user-images.githubusercontent.com/6506779/50399020-7910e400-077c-11e9-8e83-80ab07f54681.png)

User table:
![account-table-user](https://user-images.githubusercontent.com/6506779/50399305-d017b880-077e-11e9-8b89-4d87989d34ef.png)

Account table:
![account-table-account](https://user-images.githubusercontent.com/6506779/50399297-bbd3bb80-077e-11e9-9b4a-4dac19aa4395.png)

Events:
![account-delete-events2](https://user-images.githubusercontent.com/6506779/50399071-ef154b00-077c-11e9-969d-99c6dd33e565.png)

~~~

~~~

##### EXPECTED RESULTS

~~~
It was expected to generate an event to only delete account which is mented to be deleted (account5)
~~~

##### ACTUAL RESULTS

~~~
Additional event is generated saying that unrelated user and account will be deleted (account2-user2, account2)
As can be seen in the DB, the unrelated user/account are not deleted, but the event is there.


~~~
Account table:
![account-account-table](https://user-images.githubusercontent.com/6506779/50399208-128cc580-077e-11e9-82af-112716c4538e.png)
User table:
![account-user-table](https://user-images.githubusercontent.com/6506779/50399245-4962db80-077e-11e9-9857-2d62a9b4f51c.png)

Events:
![account-delete-events2](https://user-images.githubusercontent.com/6506779/50399105-461b2000-077d-11e9-8468-d28b286aefc2.png)

**Comment by rhtyd** [comment]
cc @shwstppr can you check this? Thanks.

**Comment by shwstppr** [comment]
Looking into it
