### ISSUE TITLE
Allow extending and shrinking of public IP address range

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3111]
Currently, there is not API to update or shrink/expand the public IP range for an advanced zone. Add an API to allow that.

##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
API, public ip address
~~~

##### CLOUDSTACK VERSION

~~~
4.9, 4.11, master
~~~

**Comment by Spaceman1984** [comment]
A good addition. +1

**Comment by DaanHoogland** [comment]
> A good addition. +1

is that you volunteering, @Spaceman1984 ?

**Comment by rhtyd** [comment]
@nvazquez maybe someone can be assigned to continue PR3997 to completion?

**Comment by nvazquez** [comment]
PR #5411 continuing work from PR 3997
