### ISSUE TITLE
One can no longer add multiple Public IP ranges, which share the same subnet.

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3114]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Networking
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

N/A

##### SUMMARY

One can no longer add multiple Public IP ranges, which share the same subnet.
Previously one could take a subnet, and split it into multiple ranges and dedicate them to different accounts.
Now each range must be on a unique subnet.

##### STEPS TO REPRODUCE

~~~
```create vlaniprange zoneId="4549cc45-bc59-421c-bda7-ce097c70de79" vlan=untagged gateway=10.99.0.254 netmask=255.255.255.0 startip=10.99.0.1 endip=10.99.0.100 forsystemvms=false forVirtualNetwork=true
create vlaniprange zoneId="4549cc45-bc59-421c-bda7-ce097c70de79" vlan=untagged gateway=10.99.0.254 netmask=255.255.255.0 startip=10.99.0.101 endip=10.99.0.200 forsystemvms=false forVirtualNetwork=true```
~~~

##### EXPECTED RESULTS

~~~
2nd range added without issue
~~~

##### ACTUAL RESULTS

~~~
Error message returned:

Error: (HTTP 431, error code 4350) The IP range with tag: vlan://untagged in zone ref-trl-868-k-M7-pangus has overlapped with the subnet. Please specify a different gateway/netmask.

~~~

**Comment by rhtyd** [comment]
cc @anuragaw can you take this one?

**Comment by anuragaw** [comment]
Sure @rhtyd . Looking at it starting today.

**Comment by anuragaw** [comment]
Traced back the bug introduction to https://github.com/apache/cloudstack/commit/41fdb88970d1a33d57ff08a3ecc239ec898956dc#diff-6e2b61984e8fa2823bb47da3caafa4eeR3174
