### ISSUE TITLE
Hot public NIC add fails on VMware 4.11 VR

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3116]
In 4.11, public nic hot-plugging fails with VR when the router.extra.public.nics is configured to a lower value and the number of public nics that need to be added to a VR exceed the global setting. The 4.11 systemvmtemplate installs and uses open-vm-tools which is same as 4.6-4.9 systemvmtemplate. This issue needs reproducing, triaging and fixing if necessary.

The ideal solution would be to get rid of this global setting and ensure that on VMware VR is able to hot-plug (public) nic.

/cc @PaulAngus 

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION
~~~
4.11.1/4.11.2
~~~

##### CONFIGURATION

Advanced zone networking, isolated network with multiple public IP ranges and VMware as hypervisor.

##### OS / ENVIRONMENT

CentOS7

**Comment by DagSonsteboSB** [comment]
Further information provided, issue found with VM configured with:
* Single guest NIC
* Single private NIC
* 5 x public NIC (all on different VLANs)
* VMware virtual hardware version vmx-10

**Comment by andrijapanicsb** [comment]
Sounds like a quite bit of work, moving to 4.15 milestone

**Comment by andrijapanicsb** [comment]
+1

**Comment by rhtyd** [comment]
Related: https://github.com/apache/cloudstack/issues/5716, closing this.
