### ISSUE TITLE
SystemVM template installation script does not check if file command exists

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#3117]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management script
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS minimal

##### SUMMARY

If the `file` utility is not installed then the `cloud-install-sys-tmplt` script does print an error, but does not fail with a non-zero exit code and instead installs a bz2 file as if it were a qcow2 file.

##### STEPS TO REPRODUCE

~~~
$ /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /export/secondary -u http://download.cloudstack.org/systemvm/4.11/systemvmtemplate-4.11.2-kvm.qcow2.bz2 -h kvm -F
~~~

##### EXPECTED RESULTS

The script to fail outright.

##### ACTUAL RESULTS

~~~
...
/usr/share/cloudstack-common/scripts/storage/secondary/createtmplt.sh: line 57: file: command not found
File /usr/share/cloudstack-common/scripts/storage/secondary/28966bfc-6205-4689-b6f7-dfac05e48ce8.qcow2 does not appear to be compressed
...
~~~

**Comment by DaanHoogland** [comment]
really ? a unix system without `file`!?!.

**Comment by Overv** [comment]
@dahn I was as surprised as you are, but I guess it's considered a non-essential utility for minimal images.

**Comment by rhtyd** [comment]
That's surprising so I guess the cloudstack-common package should install file on debian/ubuntu systems?
