### ISSUE TITLE
Installing template from URL is not possible unless it contains a predefined extension in the URL

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#3118]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

It is not possible to install a template from a URL unless it matches some predefined postfix.

##### STEPS TO REPRODUCE

Try to install a template from the URL https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img.

##### EXPECTED RESULTS

I expected CloudStack to just download the image and install it as the QCOW2 image that it is.

##### ACTUAL RESULTS

CloudStack will return an error stating that the URL does not end on `.qcow2`. This seems like an unnecessary limitation, because now I need to rehost this image with a different name just because CloudStack refuses to download it otherwise.

**Comment by DaanHoogland** [comment]
@Overv this limitation is due to some decision in the past making a check on the target for a template based on the extension. A call to the file command would be more correct but would require a pre-download to implement. I wonder if a magic number check can be performed on a stream to abandon download if it fails.

**Comment by Overv** [comment]
@DaanHoogland An extra parameter that disables the check would also be a solution. The UI could optionally implement this by showing a warning and asking if the user would like to skip/postpone the check.

**Comment by rhtyd** [comment]
Here's a hack you can try with your url... Pass url?file=.qcow2

**Comment by DaanHoogland** [comment]
new features go on .0s

**Comment by andrijapanicsb** [comment]
Moving to 4.15 milestone, since not critical and there is a workaround for edge case usage.

**Comment by rhtyd** [comment]
I think in latest master, .img is associated with KVM/qcow2 but needs testing.

**Comment by davidjumani** [comment]
Tested, able to download .img on latest main and boot a VM from it

**Comment by weizhouapache** [comment]
@davidjumani yeah. img is supported since #4013
shall we support other suffix or no suffix ? it will be a bit complicated @nvazquez @davidjumani

**Comment by andrijapanicsb** [comment]
no, for XXX sake, no - unless we parse few first bit (which I believe we do?) and can surely know which file type it is and throw and early error (if, say .IMG (qcow2 really) is used for i.e. VMware)

K.I.S.S. if possible.

**Comment by nvazquez** [comment]
Thanks @davidjumani @weizhouapache @andrijapanicsb, closing this after your remarks
