### ISSUE TITLE
Integrating Ceph Status into CloudStack Dashboard

### ISSUE THREAD

**Issue by falcon78921** [apache/cloudstack#3137]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
CloudStack UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1+
~~~

##### CONFIGURATION

I have an idea for a new CloudStack feature. Being someone who utilizes Ceph greatly in their environment, I thought it would be pretty cool if CloudStack fetched the health status of a Ceph cluster and displayed it in the ACS dashboard (under each instance of Primary Storage (RBD)). I wrote a Python script that opens a SSH connection to a Ceph node and runs the ``ceph health`` command. I'm not too familiar with the "under-the-hood" functions of CloudStack. That's why I would love some advice on how to go about doing this. Some things I brainstormed:

- Where would I put this script, in accordance with the CloudStack code structure? (e.g. ``cloudstack/scripts/storage``)
- Where would I reference the SSH authentication for the Ceph storage node? Could we add a passwordless SSH auth to the storage node (via CloudStack)? Is there another way to fetch ``ceph health`` without SSH? (maybe via API). 
- I'm guessing a new column would be created under the ``storage_pool`` table. You could call it ``ceph_health`` and insert the health status within this column, for each row of RBD storage specified. If the storage type is not RBD, the value would be ``null``.
- For scheduling execution, I'm thinking you could add a reference within the management server to run the script. The script would open a connection to the ``cloud`` database, query all storage types that are RBD, authenticate to the RADOS monitor IP specified, run the ``ceph health`` command, report the result back to the CloudStack management server, and store the result in ``ceph_health`` (for each instance). 

The Ceph health status would be placed under the storage state. For example,

State:     **Up**

Ceph Health:   **HEALTH_OK**

Again, I just thought of this idea and it seemed like a pretty good one. I know there are many different Ceph dashboards available, including the dashboard that comes with Ceph (starting in the Luminous release). I thought this feature would be useful and it wouldn't take too much time to implement. If there are any errors in my idea or if I'm misinterpreting something, please let me know. Thanks! :)

**Comment by falcon78921** [comment]
@kiwiflyer That would be cool! :)

I found the Mimic documentation for the RESTful API plugin: http://docs.ceph.com/docs/mimic/mgr/restful/

From what I see, you can get pretty creative with the endpoints (e.g. checking cluster health, setting OSD states, removing OSDs, etc.) I'll start playing around with this.

**Comment by falcon78921** [comment]
@kiwiflyer The API is pretty easy to work with. All you need to do is enable the RESTful plugin on the ``ceph-mgr``.

``ceph mgr module enable restful``

All API requests are sent over SSL (mandatory). You can generate a self-signed certificate or use your own. In my case, I just generated a self-signed cert with the following command:

``ceph restful create-self-signed-cert``

Then, to generate an API user, run the following:

``ceph restful create-key <username>``

The username, in my case, is ``tester``.

This generates an UUID, which acts as the secret. Then, all you need to do is send the request with HTTP Basic Auth. 

``curl -k https://tester:5722f20a-6a3c-48f0-b81b-03cadfc21e8b@192.168.5.10:8003/server -v``

To see all users with API access, use this command:

``ceph restful list-keys``

This outputs the info in JSON:
~~~
{
  "tester": "5722f20a-6a3c-48f0-b81b-03cadfc21e8b"
}
~~~

Here's an example of fetching server info, via API:

~~~

curl -k https://tester:5722f20a-6a3c-48f0-b81b-03cadfc21e8b@192.168.5.10:8003/server -v

  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: O=IT; CN=ceph-restful
* 	 start date: 2019-01-17 13:05:33 GMT
* 	 expire date: 2029-01-14 13:05:33 GMT
* 	 issuer: O=IT; CN=ceph-restful
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
* Server auth using Basic with user 'tester'
> GET /server HTTP/1.1
> Authorization: Basic SECRETHERE
> User-Agent: curl/7.35.0
> Host: 192.168.5.10:8003
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 1964
< Content-Type: application/json; charset=UTF-8
< Server: Werkzeug/0.10.4 Python/2.7.12
< Date: Thu, 17 Jan 2019 14:16:36 GMT
< 
[
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-1",
        "services": [
            {
                "id": "DEVNODE-1",
                "type": "mon"
            }
        ]
    },
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-2",
        "services": [
            {
                "id": "DEVNODE-2",
                "type": "mon"
            },
            {
                "id": "1",
                "type": "osd"
            },
            {
                "id": "DEVNODE-2",
                "type": "rgw"
            }
        ]
    },
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-3",
        "services": [
            {
                "id": "DEVNODE-3",
                "type": "mon"
            },
            {
                "id": "2",
                "type": "osd"
            }
        ]
    },
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-4",
        "services": [
            {
                "id": "3",
                "type": "osd"
            }
        ]
    },
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-5",
        "services": [
            {
                "id": "5",
                "type": "osd"
            }
        ]
    },
    {
        "ceph_version": "ceph version 12.2.10 (177915764b752804194937482a39e95e0ca3de94) luminous (stable)",
        "hostname": "DEVNODE-6",
        "services": [
            {
                "id": "4",
                "type": "osd"
            }
        ]
    }

~~~

It's strange, because you have the RESTful API in the ``ceph-mgr``, but you also have the ceph-rest-api, as described here: https://ceph.com/geen-categorie/experimenting-with-the-ceph-rest-api/

Both are built into Ceph. I can't vouch for Mimic, but they're both in Luminous. The ``ceph-mgr`` RESTful plugin seems to be better for security because the requests are sent over HTTPS. Maybe the ceph-rest-api has SSL options? I didn't look much into it.

**Comment by wido** [comment]
The restful API is actually pretty broken in Ceph.

The dashboard in Ceph is already pretty good and keeps getting better and better. Wouldn't it be better that you can configure a URL to the dashboard and from the CloudStack UI you have a link to the Ceph dashboard.

It would be a lot of work to build this into CloudStack and I'm doubting the benefit.

**Comment by falcon78921** [comment]
@wido I agree that the Ceph dashboard is pretty good. I use it with my Luminous cluster. There's also another great Ceph dashboard here: https://github.com/Crapworks/ceph-dash

The only downside to the dashboard in Luminous is the fact that it's simply a "read-only" page, same for the ceph-dash project. With Mimic, however, I'm seeing more maturity with the dashboard: https://ceph.com/community/mimic-new-ceph-manager-dashboard/. 

Personally, I've utilized both dashboards. I guess my thought on this is to consolidate monitoring/management tools and bring Ceph more into the "CloudStack-picture". Having to bounce between different management components can get pretty frustrating. IMO, the benefits could be great. Instead of adding another component, say openATTIC, an user can manage Ceph through CloudStack. Creating pools, monitoring OSDs, managing RBD images, etc. could be possible. The more functions that are built in, the more work, I agree. Again, I'm more than willing to assist with this in any way! :)

@wido, out of curiosity, you say the RESTful API is broken. What do you mean by broken? Are you talking about the ``ceph-mgr`` RESTful plugin or the ``ceph-rest-api``?

**Comment by falcon78921** [comment]
Yeah, you could see this as "re-inventing the wheel". However, if users use both CloudStack and Ceph, you're giving them a more centralized management system versus several third-party integrations. I,  myself, see the value in this. I think this could also attract more users to CloudStack if CloudStack had this packaged in. 

If the API is broken, is there another way that CloudStack could talk to a Ceph node? Could you send the commands over SSH? When adding compute servers in CloudStack, the user is prompted for ``sudo`` credentials on the system. Could we do something like that for Ceph? We could exchange SSH keys for remote control. I'm not familiar with Java, however, I've worked with Python's ``paramiko`` module. You can do some pretty cool automation with it. Just a suggestion :)

**Comment by wido** [comment]
I personally just do not think it's a very good thing to do. It will probably be maintained poorly and lacking features which are available in the Ceph dashboard.

I would also not advise to use SSH, you should need to fix a few things in the restful API first.

Overall I don't think it's worth the effort.
