### ISSUE TITLE
CentOS 6 Repo not updated for 4.11.2 GA

### ISSUE THREAD

**Issue by richardlawley** [apache/cloudstack#3157]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CentOS 6 Yum Repo
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

CentOS 6

##### SUMMARY

The version of CloudStack available from http://download.cloudstack.org/centos/6/4.11/ is 4.11.2-rc5, not the GA version.

##### STEPS TO REPRODUCE

~~~
cat <<EOF > /etc/yum.repos.d/cloudstack.repo
[apache-cloudstack]
name=Apache CloudStack
baseurl=http://download.cloudstack.org/centos/$releasever/4.11/
enabled=1
gpgcheck=0
EOF
yum info cloudstack-management
~~~

##### EXPECTED RESULTS

Release should be 1.el6
##### ACTUAL RESULTS

~~~
# yum info cloudstack-management
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.vooservers.com
 * extras: mirror.bytemark.co.uk
 * updates: mirrors.vooservers.com
Installed Packages
Name        : cloudstack-management
Arch        : x86_64
Version     : 4.11.2.0
Release     : rc5.el6
Size        : 100 M
Repo        : installed
From repo   : cloudstack
Summary     : CloudStack management server UI
License     : ASL 2.0
Description : The CloudStack management server is the central point of coordination,
            : management, and intelligence in CloudStack.

~~~

**Comment by rhtyd** [comment]
@richardlawley thanks for reporting. You can consume the rpms from here: http://packages.shapeblue.com/cloudstack/upstream/centos/4.11/
@wido can you fix that, thanks.

**Comment by rhtyd** [comment]
cc @PaulAngus - do you have any idea?

**Comment by rhtyd** [comment]
Thanks @wido we'll try to sort that out soon.

**Comment by PaulAngus** [comment]
i don't know what happened there. we'll get it sorted,

**Comment by rhtyd** [comment]
I do see 4.11.2.0 packages now, http://download.cloudstack.org/centos/6/4.11/
Closing

**Comment by richardlawley** [comment]
There is indeed a package with the filename 4.11.2, but it does not contain the GA version of 4.11.2, it is RC5 instead.

```
$ wget -q http://download.cloudstack.org/centos/6/4.11/cloudstack-management-4.11.2.0.el6.x86_64.rpm
$ rpm  -qp cloudstack-management-4.11.2.0.el6.x86_64.rpm 
warning: cloudstack-management-4.11.2.0.el6.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 584df93f: NOKEY
cloudstack-management-4.11.2.0-rc5.el6.x86_64
```

**Comment by rhtyd** [comment]
Thanks for confirming @richardlawley - repositories are community/3rd party hosted and officially hosted by the project. This means you'll have to reach out to the repository maintainer to get it fixed. cc @wido - can you help fix the issue, thanks.
