### ISSUE TITLE
Not possible to edit/change a VMware VM immediately after it's stopped

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3159]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

VMWARE / vShpere code

##### CLOUDSTACK VERSION

4.11.2 (didn't test all previous releases, except I know thing worked differently in 4.6)

##### CONFIGURATION

vSphere hypervisor used.

##### OS / ENVIRONMENT
NA

##### SUMMARY
After VM is stopped via API/GUI, it's not possible to immediately change VM (resize disk, change Service Offering, etc. - these 2 were tested) since they require the VM to be stopped (and VM is actually stopped), but due to VMware code using "ping.interval" global setting value, it can take up to 2 x ping.interval for VM power state to be fully synced from vCenter to Management Server. ( by default, this becomes up to 2 minutes)

##### STEPS TO REPRODUCE

Spin new VM, stop VM, and immediately try to change Service/Compute Offering for the VM.

##### EXPECTED RESULTS

It should be possible to change/edit a VM immediately after stopping it (i.e. this was possible in ACS 4.6)

##### ACTUAL RESULTS
Can't change Service/Compute offering or resize ROOT disk of a VM -  you will get error that it's impossible since VM is not stopped.

~~~

**Comment by DaanHoogland** [comment]
don't think this is being addressed so moving to 4.15

**Comment by Spaceman1984** [comment]
I'll take a look

**Comment by rhtyd** [comment]
cc @Spaceman1984
