### ISSUE TITLE
java download client - unable to download/register when there's a trusted ssl connection 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3172]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

Setup a valid/trusted ssl certificate for the ssvm 

##### STEPS TO REPRODUCE

~~~
test_templates:test_04_extract_template
~~~

##### EXPECTED RESULTS

~~~
Test would pass
~~~

##### ACTUAL RESULTS

~~~
Fails with the following: 
`2019-02-11 10:57:22,658 - CRITICAL - FAILED: test_04_extract_template: ['Traceback (most recent call last):\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run\n    testMethod()\n', '  File "/marvin/tests/smoke/test_templates.py", line 778, in test_04_extract_template\n    % (formatted_url, self.template_2.id)\n', '  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail\n    raise self.failureException(msg)\n', 'AssertionError: Extract Template Failed with invalid URL https://10-1-35-4.sbcloud.uk/userdata/e60c42e1-43b3-422d-936d-1dbe4c7b2c61.qcow2 (template id: 9fc2d490-bec5-4f3d-b9ff-046be227f037)\n']`
~~~

**Comment by rhtyd** [comment]
Per the docs, upload should work over http https://github.com/apache/cloudstack-documentation/pull/37/files
The failure could be env related and needs investigation.

**Comment by rhtyd** [comment]
The current Marvin tests perhaps don't test well for SSL enabled end-points, so likely the marvin test needs to ignore any SSL errors while trying to extract/download the URL. cc @borisstoyanov

**Comment by borisstoyanov** [comment]
current marvin tests are having a different issue with downloading ssl enabled urls, they prompt the download through ssl method is not callable, which means afaik the python was not compiled with ssl capability. 
As far as this error I don't think we see it by now, think we can close this..

**Comment by rhtyd** [comment]
Okay @borisstoyanov closing on your remark. Please reopen if you can reproduce it again.
