### ISSUE TITLE
How to determine the proper sizing of RAM vor VR?

### ISSUE THREAD

**Issue by 1605200517** [apache/cloudstack#3175]
On CloudStack 4.7, we observe that large CIDR lists (say. several hundreds entries) for VPC access lists used for many ports lead to timeouts during creation of the iptables on the VR.

We observed that this can be tackled through increasing the RAM of the virtual private router.

Before we provide a detailed report if this should a bug, first a question what is the background of this dependency (more CIDRs - more runtime for setting the iptables) and how to determine RAM required for the VPR.

**Comment by rhtyd** [comment]
It depends on your network requirements, not just the RAM you may need to increase the vCPUs for the router offering as well. Kindly discuss this over users ML http://cloudstack.apache.org/mailing-lists.html
