### ISSUE TITLE
qcow2 images are being corrupted

### ISSUE THREAD

**Issue by melnik13** [apache/cloudstack#3193]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Management Server
~~~

##### CLOUDSTACK VERSION
~~~
4.x
~~~

##### CONFIGURATION
Apache CloudStack with KVM-powered hosts

##### OS / ENVIRONMENT
Hypervisor: KVM (CentOS 7)

##### SUMMARY
Sometimes a qcow2 image could be corrupted by the snapshot deletion procedure. This issue was discussed in the cloudstack-users@ mailing list:
https://mail-archives.apache.org/mod_mbox/cloudstack-users/201901.mbox/%3Ccb737633a9134ae48e816ba183c97d11%40IPPEXCH13MB1.ipp.corp%3E
https://mail-archives.apache.org/mod_mbox/cloudstack-users/201902.mbox/%3C71795593db0b45d5846132d8bb2eb174%40IPPEXCH13MB1.ipp.corp%3E
https://mail-archives.apache.org/mod_mbox/cloudstack-users/201807.mbox/%3CnRAxfbfpv8T35h3ylbiWeOPF2zYHmZ2YRf6QjYc2pyHTuj-qtTSw8_wK4YlAiV9_EsPmrBatTl3i2nRhPhK4cbBl9nIzPQ0hhHJIrvgV6-A%3D%40protonmail.com%3E

##### STEPS TO REPRODUCE
Alas, there are no 100%-working ways to reproduce that. It just happens in the most inappropriate moment.

##### EXPECTED RESULTS
Everyone expects their data is safe. :-)

##### ACTUAL RESULTS
Sometimes data is being lost. :-(

**Comment by rhtyd** [comment]
Merged in https://github.com/apache/cloudstack/pull/3194

**Comment by Slair1** [comment]
@melnik13 we've been doing some additional testing.  This seems to work well with the VM being suspended when the snapshot is deleted.  However, when a "VM Snapshot" is deleted, the VM is not suspended.  Perhaps we need to add code for when VM Snapshots are deleted also?  Thoughts?

**Comment by Slair1** [comment]
> @melnik13 we've been doing some additional testing. This seems to work well with the VM being suspended when the snapshot is deleted. However, when a "VM Snapshot" is deleted, the VM is not suspended. Perhaps we need to add code for when VM Snapshots are deleted also? Thoughts?

@melnik13 or may @rhtyd  ?
