### ISSUE TITLE
after changing the Instance default nic, no new gateway can be obtained

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3201]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
4.11.2
~~~

##### CONFIGURATION

isolation network
l3 share network

##### SUMMARY

Instance has two NICs. After changing the default nic, the instance cannot get the new gateway address (the instance always gets the old one).

Must be restarted by CLOUDSTACK or shut down and restart, in order to get the new gateway address.
##### STEPS TO REPRODUCE

~~~
1.Add two networks to instance
2.Set nic2 to a defualt network.
3.Retrieve Ip (dhclient) in instance OS

~~~

##### EXPECTED RESULTS

~~~
os get the gateway address of nic2
~~~

##### ACTUAL RESULTS

~~~
os get the gateway address of nic1

~~~

**Comment by ustcweizhou** [comment]
@div8cn thanks for report. I will create a PR for this issue.

**Comment by luhaijiao** [comment]
Thanks weizhou,  you rock !






在2019年03月06 15时45分, "ustcweizhou"<notifications@github.com>写道:



@div8cn thanks for report. I will create a PR for this issue.
