### ISSUE TITLE
Error while searching through VM snapshots

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3208]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
API listVMSnapshot
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2+ (didn't test on older ones)
~~~

##### CONFIGURATION

No special config needed

##### OS / ENVIRONMENT

Not relevant

##### SUMMARY

Can't search through VM snapshots

##### STEPS TO REPRODUCE

"cmk list vmsnapshot listall=true keyword=ldap" or  simply searching through VM snapshots with just a keyword typed in the search field gives errors 530 with SQL error (check below for output)

##### EXPECTED RESULTS

~~~
Can search successfully through VM snapshots
~~~

##### ACTUAL RESULTS

SQL error displayed in the GUI as following (keyword used was "ldap"):

Caught: com.mysql.jdbc.JDBC4PreparedStatement@339fb43b: SELECT vm_snapshots.id, vm_snapshots.uuid, vm_snapshots.name, vm_snapshots.display_name, vm_snapshots.description, vm_snapshots.vm_id, vm_snapshots.account_id, vm_snapshots.domain_id, vm_snapshots.service_offering_id, vm_snapshots.vm_snapshot_type, vm_snapshots.state, vm_snapshots.created, vm_snapshots.removed, vm_snapshots.current, vm_snapshots.parent, vm_snapshots.updated, vm_snapshots.update_count FROM vm_snapshots INNER JOIN account ON vm_snapshots.account_id=account.id WHERE vm_snapshots.state IN ('Ready','Creating','Allocated','Error','Expunging','Reverting') AND (vm_snapshots.name LIKE _binary'%ldap%' OR OR vm_snapshots.description LIKE ** NOT SPECIFIED ** ) AND vm_snapshots.removed IS NULL AND (account.type != ** NOT SPECIFIED ** ) ORDER BY vm_snapshots.created DESC LIMIT 0, 20

**Comment by andrijapanicsb** [comment]
Additionally, per documentation, no parameter is REQUIRED, all are optional, which seems to not be the case.

Additionally, when searching for VM snap via GUI, the "listall=true" is sent two times  - this is also to be fixed.

**Comment by shwstppr** [comment]
> Additionally, per documentation, no parameter is REQUIRED, all are optional, which seems to not be the case.

@andrijapanic Not able get the above part, rest should be fixed with my PR https://github.com/apache/cloudstack/pull/3257

**Comment by andrijapanicsb** [comment]
Ignore that, my bad!
