### ISSUE TITLE
Cannot create (add) template for KVM (QCOW2)

### ISSUE THREAD

**Issue by 3guboff** [apache/cloudstack#3224]
##### ISSUE TYPE
 * Bug Report
##### COMPONENT NAME
~~~
Templates
~~~
##### CLOUDSTACK VERSION
~~~
4.11.2.0
~~~
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
~~~
CentOS Linux release 7.6.1810
~~~

##### SUMMARY
Cannot upload image for template when:
~~~
  format     = "QCOW2"
  hypervisor = "KVM"
  url        = "https://cloud-images.ubuntu.com/xenial/20190308/xenial-server-cloudimg-amd64-disk1.img"
~~~
##### STEPS TO REPRODUCE
~~~
Go to:
Templates => Add
Set:
URL = https://cloud-images.ubuntu.com/xenial/20190308/xenial-server-cloudimg-amd64-disk1.img
Hypervisor = KVM
Format = QCOW2
~~~
##### EXPECTED RESULTS
Template uploaded successfully

##### ACTUAL RESULTS
![Screenshot from 2019-03-13 12-26-39](https://user-images.githubusercontent.com/1561986/54267977-50360900-458b-11e9-830c-f2ca33366123.png)

**Comment by ustcweizhou** [comment]
cloudstack does not support qcow2 image files with suffix .img
the suffix must be .qcow2

**Comment by 3guboff** [comment]
> cloudstack does not support qcow2 image files with suffix .img
> the suffix must be .qcow2

It's some kind of joke? Why so stupid restriction exist in this project?
Example for better understanding stupidity of the situation: I have text file without extension, so I can't open him on my laptop, seriously?

**Comment by ustcweizhou** [comment]
> > cloudstack does not support qcow2 image files with suffix .img
> > the suffix must be .qcow2
> 
> It's some kind of joke? Why so stupid restriction exist in this project?
> Example for better understanding stupidity of the situation: I have text file without extension, so I can't open this file on my laptop, seriously!?

@3guboff  You may try to register template with format=RAW instead of QCOW2
It works for me.

**Comment by 3guboff** [comment]
@ustcweizhou Not working for me

**Comment by PaulAngus** [comment]
@3guboff  I doubled checked, and the  .img extension should be used for raw images not qcow2 images.

I would suggest that you go to creator of the images and ask them to use the appropriate file extension for their qcow2 images.

I would also counsel that you refrain from hurling insults at them if they try to help you, as it is unlikely to further your cause.

**Comment by PaulAngus** [comment]
.img extension is generally used for raw images
CloudStack's expectation of a .qcow2 extension for a QCOW2 disk image is correct and sensible.
