### ISSUE TITLE
Console Proxy sends redundant CTRL and ALT keys to VMware

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3229]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
Console Proxy (or possibly VMware SDK...)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.X
~~~

##### CONFIGURATION

VMware zone

##### OS / ENVIRONMENT

VMware zone

##### SUMMARY

on VMware Zone, hitting CTRL over Console Proxy will send CTRL+ALT + CTRL keys or possible CTRL + ALT + right CTRL + right ALT (as can be seen on Windows with on-screen keyboard)

##### STEPS TO REPRODUCE

use "showkey" tool on Linux - and hit just CTRL key - you will see keycode 29,56,29 pressed and then keycode 29,56 released ?!) 
On Windows guest VM, start on-screen keyboard, and again press CTRL  - it will show both CTRL and both ALT keys being pressed - ctrl + c doesn't work and will produce copyright sign instead of copying text, etc.

##### EXPECTED RESULTS

~~~
When pressing CTRL, send only "CTRL" to VM console.
~~~

##### ACTUAL RESULTS

~~~
Read above from "steps to reproduce" section please
~~~

**Comment by andrijapanicsb** [comment]
Seems to be working fine on XenServer (7.0 tested) - I can see with "showkey" only one keycode reported to be pressed/released. Didn't try KVM.

**Comment by rhtyd** [comment]
Investigation: Based on showkey output on linux (debian and centos guests) with ACS 4.11.2.0, the console proxy indeed sends those keys as pressed, but with an additional ESC key.

In the screenshot, the first set of Ctrl+keys were typed on a virt-manager VNC ( KVM), and next sets were typed via browser based console (cloudstack). This shows that some additional key is being sent as part of the key press event:
![Screenshot from 2019-04-01 13-13-02](https://user-images.githubusercontent.com/95203/55313103-a01a3880-5484-11e9-9eaf-652af1e5ba56.png)

Based on debugging a local 4.11.2.0 env, I found that Ctrl+D/E/A were accepted when metaKey was ignored in ajaxviewer.js however I'm not sure what possible regression this may introduce:

                //if(e.metaKey)
                //      modifiers |= AjaxViewer.META_KEY_MASK;

Reference:
https://css-tricks.com/snippets/javascript/javascript-keycodes/

**Comment by anuragaw** [comment]
Upon investigation it seems to be broken just for VMWare

> Seems to be working fine on XenServer (7.0 tested) - I can see with "showkey" only one keycode reported to be pressed/released. Didn't try KVM.

Seems to be working fine on KVM on latest Master. Investigating further.

**Comment by anuragaw** [comment]
Also observed that `Cmd` (meta key on Macs) has no effect on VMWare and KVM when CPVM console is launched on MacBook Pro in Chrome.

**Comment by rhtyd** [comment]
Handled here: https://github.com/apache/cloudstack/pull/3308

**Comment by PaulAngus** [comment]
LGTM - Tested using vmware 65u2, a windows 2008r2 VM and Centos53 VM  
Windows 10 with Chrome, Firefox and Edge
CRTL A, V, C   etc work as expect
