### ISSUE TITLE
CloudStack system vm Hyper-V error

### ISSUE THREAD

**Issue by hex-dec** [apache/cloudstack#3262]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

on new system vm template on debian 9.6 and Hyper-v 2012 r2+ 
1. path /var/opt/hyperv/ does not exist
hv_kvp_daemon write file to /var/lib/hyperv/.kvp_pool_0
2. .kvp_pool_0 is binary format and (grep -Po 'type=\K[a-zA-Z]*') does not work

For 1. may create symlink or change script in "cloud-early-config"

For 2. may use
 echo $(cat /var/opt/hyperv/.kvp_pool_0) > $CMDLINE
instead of 
cp -f /var/opt/hyperv/.kvp_pool_0 $CMDLINE
in "cloud-early-config"

**Comment by rhtyd** [comment]
@hex-dec can you describe how you tested your env and which version of CloudStack was used?

**Comment by andrijapanicsb** [comment]
ping @hex-dec - any update on this one?

**Comment by DaanHoogland** [comment]
@hex-dec is this something you are still working on?

**Comment by rohityadavcloud** [comment]
Stale - thanks for the report, closing this. Pl re-open if you've further updates on latest release.
