### ISSUE TITLE
SSVM uses the guest network to mount NFS SS instead of the management network

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#3263]
Hi,

4.11.2 + KVM, ADV +SG zone. 
One management network + one guest network  - no dedicated sstorage network, public IPv4 everywhere.
I am having a hard time mounting the FreeNAS NFS share, turns out the SSVM uses the guest network to access the NFS server (as shown by "ip ro get").
Obviously, I can't add the guest network to the NFS ACL, any client VM would be able to mount the share.

Ideas?

**Comment by andrijapanicsb** [comment]
I saw same thing in 4.11.2 when I used Basic Zone/SG also withOUT defining Storage Network (also using Guest/Public network to access NFS).
Workarround was to define Storage Network (even though in the same IP range as MGMT)...

**Comment by NuxRo** [comment]
Thanks for confirming; as a workaround I have moved SS on to an IP in the mgmt network, but.. it is a workaround, it'd be nice to see a fix.

**Comment by nvazquez** [comment]
Hi @Pearl1594 can you pleas explore this issue?

**Comment by nvazquez** [comment]
As @Pearl1594's investigation this is no longer an issue
