### ISSUE TITLE
System VM health monitoring

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack#3270]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
VR, API
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In CloudStack 4.11, there seems to be no effective way to monitor the health of virtual routers and other system VMs.
CloudStack does some internal health monitoring, but the result of these health checks is not exposed via the API.
It would be very useful if system VMs (especially the VRs) or the API offered a built-in way to monitor their performance and health.

##### STEPS TO REPRODUCE

An existing monitoring system, such as Icinga or Prometheus would automatically query CloudStack about its networks and/or system VMs, then record performance data from each system VM.

This would allow performance monitoring (such as CPU, memory and network load) and health checks to react to extraordinary conditions.

Some of these measurements could be implemented on the hypervisor level, but others are inherent to the system VM and thus not easily monitorable in a hypervisor-agnostic way.

##### EXPECTED RESULTS

Aside from offering simple monitors such as those offered for regular VMs, where CloudStack queries the hypervisor and exposes them via the API, additional data from the system VM services should be available.
Alternatively, the system VMs could expose a monitoring service (SNMP, Prometheus, NRPE, ...) that can be queried from a monitoring service running on the backend network.

Here's a non-exhaustive list of monitors that would be interesting:
- CPU load
- System load
- Memory / cache / swap usage
- Disk read / write / bit/s / IOPS
- Per-network in / out / bit/s / packet/s
- Number of NAT table (conntrack) entries
- System health / disk usage % / swap usage % / rootfs mounted readonly

##### ACTUAL RESULTS

Neither simple hypervisor-based metrics nor advanced metrics from the service are exposed.

In the past, we manually installed additional monitoring services into each newly deployed VR, which would then queried from our central monitoring platform. But such a setup can be brittle, lead to incompatibilities and performance problems and needs manual attention to stay up to date.

**Comment by onitake** [comment]
I briefly discussed the feature on the [cloudstack-users mailing list](https://lists.apache.org/thread.html/5eb1ef3ce0bd75c9a5dbf1080b3f13b844758415e71afe669a180b15@%3Cusers.cloudstack.apache.org%3E), but the offered suggestions were too hypervisor-specific and did not meet my expectations on what I want to monitor.

**Comment by DaanHoogland** [comment]
@onitake are you familiar with the health check feature being implemented? #3575 it seems it implements yourrequirement, correct?

**Comment by onitake** [comment]
@DaanHoogland That implementation looks pretty cool. Let me comment there.

**Comment by rhtyd** [comment]
@onitake can you review and close this issue? Thanks.

**Comment by DaanHoogland** [comment]
@onitake closing this, please reopen or create a new issue if you dissagree

**Comment by onitake** [comment]
Sorry, yes. This issue can be closed.
