### ISSUE TITLE
Service offerings too small

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#3274]
Env: 4.11.2, Xenserver, Ubuntu template from openvm.eu

I just wasted a silly amount of time trying to debug over a high latency connection why passwords (and other cloud-init features) did not work. Turns out the tests were done with the Small service offering which has 512 RAM; the template would run out of memory, thus impeding cloud-init.
Everything worked with the Medium offering.

It's 2019, can we upgrade the Small one to 1 GB RAM? 
We should offer sane, working defaults.

While at it, we need to nuke the CentOS 5.5 built-in template ...

**Comment by rhtyd** [comment]
Or you can use the Medium offering (1GiB RAM).

We may also introduce a new one such that:
Small: 512MiB
Medium: 1024MiB
Large: 2048MiB

**Comment by NuxRo** [comment]
Can we make the small one 1GB, pretty please?
People expect viable offerings, I was also surprised and disappointed that cloud-init fails so badly with low RAM .. but it is what it is..

**Comment by rhtyd** [comment]
Due to backward compatibility issues, we cannot change the default setting for the Small offering. However, we can introduced a Large (L) and Extra Large (XL) offering.

**Comment by DaanHoogland** [comment]
@NuxRo @rhtyd is this still an issue?

**Comment by NuxRo** [comment]
Since we mess up backwards compatibility, I guess this is not an "issue" and will need to be worked around some other way.
