### ISSUE TITLE
Marvin can't read config file

### ISSUE THREAD

**Issue by pmury** [apache/cloudstack#3277]
##### ISSUE TYPE

 * Bug Report
 * Documentation Report
 
##### COMPONENT NAME
~~~
Marvin, testing
~~~

##### CLOUDSTACK VERSION
~~~
master branch
~~~

##### CONFIGURATION

https://github.com/pmury/cloudstack/blob/marvin-101/test/integration/Dockerfile.python27

and setup.cfg both adopted, either 1:1 copied from the installation
instructions following the example from 
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Marvin+-+Testing+with+Python#Marvin-TestingwithPython-Installation.1

##### OS / ENVIRONMENT

as per Dockerfile

##### SUMMARY
Can't initialize Marvin

##### STEPS TO REPRODUCE
~~~
Run build for Dockerfile
~~~

##### EXPECTED RESULTS
Marvin starts testing

##### ACTUAL RESULTS

Error

```
Usage: nosetests [options]
nosetests: error: Error reading config file 'setup.cfg': File contains no
section headers. file: 'setup.cfg', line: 1
'{\n'
The command '/bin/sh -c nosetests --with-marvin
 --marvin-config=./setup.cfg --hypervisor=vmware -s -a tags=advanced
 /opt/cs/test/integration/component/' returned a non-zero code: 2

```
How can JSON miss section headers? Maybe this should be .ini format?

**Comment by ustcweizhou** [comment]
I run the commands below and it succeed
```
wget -N https://builds.apache.org/job/cloudstack-marvin/lastSuccessfulBuild/artifact/tools/marvin/dist/Marvin-0.1.0-2626.tar.gz

pip install Marvin-0.1.0-2626.tar.gz

/bin/bash -c nosetests --with-marvin --marvin-config=setup.cfg --hypervisor=kvm -a tags=advancedsg /root/
```

# nosetests --version
nosetests version 1.3.7

**Comment by rhtyd** [comment]
Here's a VM based dev-test env toolkit you can try: https://github.com/rhtyd/monkeybox

I'm able to install marvin, the issue is env related.
