### ISSUE TITLE
SystemVM template build does not work with latest packer v1.4.0

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3284]
I recently found that our systemvmtemplate build system does not work with packer v1.4.0 however, it does work fine with packer v1.2.5.

Till the time we fix that, users/devs - kindly use packer v1.2.5 for building systemvmtemplate.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SystemVM template
~~~

##### CLOUDSTACK VERSION

~~~
N/A
~~~

**Comment by DaanHoogland** [comment]
@rhtyd you have an update?

**Comment by rhtyd** [comment]
I had created this PR https://github.com/apache/cloudstack/pull/3797 against packer 1.4.5, so this can be closed.
