### ISSUE TITLE
S2S VPN check does not different between VRs by their roles

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3286]
The S2S VPN connection checking code does not differentiate between routers based on the roles, due to which with a VPC with an internal LB VM, the query to check VPN connection may also reach the internal LB VM instead of just the VPC VR:

https://github.com/apache/cloudstack/blob/4.11.2.0/server/src/com/cloud/network/router/VirtualNetworkApplianceManagerImpl.java#841

The issue seen would be frequently toggling of VPN connection state going from connected/disconnected etc.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2.0
~~~

**Comment by rhtyd** [comment]
I think @weizhouapache or @ravening fixed this, will close.

**Comment by ravening** [comment]
Yes this is fixed
