### ISSUE TITLE
Issues when multiple management IP addresses are set in the KVM hypervisor (with fix)

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#3311]
##### ISSUE 
 * Bug Report

(fix by Wei down below)

##### COMPONENT NAME
Management
~~~

~~~

##### CLOUDSTACK VERSION
~~~

~~~

##### CONFIGURATION
Advanced zone with SG

##### OS / ENVIRONMENT
KVM, CentOS7, 

##### SUMMARY
When multiple IPs are set on the bridge used for management traffic, the management server/UI can report the "wrong" IP - not the one used when the hypervisor was added - and it can cause all sorts of issue, like "Alert" status etc.

##### STEPS TO REPRODUCE
Add another IP to the bridge in question, restart agent, refresh hypervisors in the UI.

##### EXPECTED RESULTS
The management server and UI should only report and address the hypervisor with the actual address used when adding it to Cloudstack.

~~~

~~~

##### ACTUAL RESULTS
Hypervisor stuck in "Alert" status and other issues, please see this mailing list thread which also contains a fix by Wei Zhou.

https://lists.apache.org/thread.html/1dec4d735add244be77da261cf8d553117b40e8ab1dd8146908abf12@%3Cdev.cloudstack.apache.org%3E

**Comment by rhtyd** [comment]
I checked the jdk docs, the order of the list of interfaces and addresses returned by `getInterfaceAddresses` is implementation and platform dependent so I'm not sure if the list need to be reversed. I think the workaround you've used @NuxRo is good enough.
@ustcweizhou can you comment if reversing the order would make sense wrt Linux?

For most users they can now use the software lb, by passing multiple mgmt server IPs to the host global setting.

**Comment by ustcweizhou** [comment]
@rhtyd 

I tested the following java code in centos6, centos7, ubuntu12 and ubuntu16. 
It lists all devices and ips in reverse order as "ip a".
So I think it is better to reverse the ip addresses as usually we use the first ip of nics for communication.

ListNetworkAddresses.java
```
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

public class ListNetworkAddresses {
    public static void main(String[] args) throws Exception {
        final List<NetworkInterface> nics = Collections.list(NetworkInterface.getNetworkInterfaces());
        for (final NetworkInterface nic : nics) {
            final List<InterfaceAddress> addrs = nic.getInterfaceAddresses();
            if (addrs != null) {
                for (final InterfaceAddress addr : addrs) {
                    System.out.println("network device name is " + nic.getName() + ", ip is " + addr.getAddress().getHostAddress());
                }
            }
        }
    }
}
```

command
```
javac ListNetworkAddresses.java && java ListNetworkAddresses
```

**Comment by rhtyd** [comment]
Thanks @ustcweizhou in that case can you send a PR?

**Comment by ustcweizhou** [comment]
@rhtyd will do

**Comment by ustcweizhou** [comment]
@rhtyd 
can you test the following code to see if you can get same result ?
https://docs.oracle.com/javase/tutorial/networking/nifs/listing.html

save as ListNets.java and run "javac ListNets.java && java ListNets"

I got reverse order as it shows in my testing.

**Comment by rhtyd** [comment]
Thanks for sharing @ustcweizhou, I'll help review/test when you submit the PR. Thanks.
