### ISSUE TITLE
Volume name for failed and successful snapshots

### ISSUE THREAD

**Issue by glennwagner** [apache/cloudstack#3327]
##### ISSUE TYPE

 * Feature Idea
 

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### SUMMARY

We would like to see additional information such as Volume name, supplied for events related to failed/successful snapshots so that these messages are distinguishable.

e.g. the customer would like to see the Volume name for failed and successful snapshots:

+--------------------------------------------------------------------+

|     description                                                        |

+--------------------------------------------------------------------+

| Successfully completed taking snapshot                             |

| Error while taking snapshot                                        |

| creating snapshot for volume: fcc93103-605f-493a-882b-2d0fbd239a11 |

+--------------------------------------------------------------------+

##### STEPS TO REPRODUCE

~~~
Create a Volume Snapshot in the UI or API 
~~~

##### EXPECTED RESULTS

~~~
e.g. the customer would like to see the Volume name for failed and successful snapshots:

+--------------------------------------------------------------------+

|     description                                                        |

+--------------------------------------------------------------------+

| Successfully completed taking snapshot                             |

| Error while taking snapshot                                        |

| creating snapshot for volume: fcc93103-605f-493a-882b-2d0fbd239a11 |

+--------------------------------------------------------------------+
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by anuragaw** [comment]
I will take a look @glennwagner

**Comment by rhtyd** [comment]
@shwstppr can you pick this up?
