### ISSUE TITLE
ACS tries to delete a root disk in zone wide primary storage

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3340]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
vSphere - Zone wide storage
~~~

##### CLOUDSTACK VERSION

~~~
4.9, 4.11, 4.12, master
~~~

##### CONFIGURATION

vSphere with zone-wide storage
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Transferred from Jira :
https://issues.apache.org/jira/browse/CLOUDSTACK-9991

A VM is running and the disk is migrated from cluster to zone wide primary storage. The root disk for that VM is now seen in all clusters and ACS tries to delete it. This fails, fortunately but only because it is in use. ACS should not try to delete the disk.

##### STEPS TO REPRODUCE

~~~


~~~

##### EXPECTED RESULTS

~~~
Migrate the root disk of a running VM from cluster-wide to zone wide storage.
~~~

##### ACTUAL RESULTS

message seen:
Cannot delete file [Perf06_ix_stor_003] i-93-8549-VM/ROOT-8549-delta.vmdk

It looks like this message
private void deleteUnregisteredVmFiles(VirtualMachineFileLayoutEx vmFileLayout, DatacenterMO dcMo, boolean deleteDisks) throws Exception { s_logger.debug("Deleting files associated with an existing VM that was unregistered");

from here: https://github.com/apache/cloudstack/blob/a25b54cf05704bcf074e67d5500d5d221235cc86/plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L2712-L2713

because the start is reading this: https://github.com/apache/cloudstack/blob/a25b54cf05704bcf074e67d5500d5d221235cc86/plugins/hypervisors/vmware/src/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L2073-L2076

// Since VM was successfully powered-on, if there was an existing VM in a different cluster that was unregistered, delete all the files associated with it.
if (existingVmName != null && existingVmFileLayout != null)

{ deleteUnregisteredVmFiles(existingVmFileLayout, dcMo, true); }

~~~

~~~

**Comment by shwstppr** [comment]
Code on master checks for files on zone-wide datastores. This should cover the case mentioned, https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java#L2277-L2283
Need to test this with master
@PaulAngus @rhtyd

**Comment by rhtyd** [comment]
cc @borisstoyanov

**Comment by borisstoyanov** [comment]
having a look

**Comment by borisstoyanov** [comment]
Cannot reproduce this, I'm running 2 storage pools (cluster and zone scoped) when migrating the volume to the zone one I cannot see in the its logs trying to delete it.

**Comment by borisstoyanov** [comment]
@PaulAngus is there any time period for this job to kick in, since I've been trying to do this on 4.11.3 4.9.3 and master and could not reproduce, I've replicated the exact storage circumstances and simply could not see such message in the logs. Env are running with root volume on zonewide storage pool for more than hour?
