### ISSUE TITLE
4.11.2 HA VRs with Second Public NIC do not get constant MAC

### ISSUE THREAD

**Issue by richardlawley** [apache/cloudstack#3352]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VRs
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

XenServer 6.5, Advanced Networking

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When an advanced network has multiple public interfaces, the second (and subsequent) interfaces do not have the same MAC address on both VRs.  This means that after a failover, connectivity with the IPs on the second+ ranges is interrupted until the ARP entry times out.

##### STEPS TO REPRODUCE

1.  Create zone with 2 or more public IP ranges
2.  Create an advanced network, allocate IPs until you get IPs from both networks (or use the database to assign a specific IP)
3.  Create a VM and assign a Static NAT IP to the IP from the second range
4.  Log into both VRs, compare the MAC addresses of eth2 and eth3 on both VRs

##### EXPECTED RESULTS

~~~
MAC addresses for eth3 should be the same on both VRs
~~~

##### ACTUAL RESULTS

~~~
MAC addresses for eth3 are different.
~~~

**Comment by richardlawley** [comment]
The additional public NICs do not seem to have a database entry - I was hoping to be able to adjust it as a short-term fix.

**Comment by richardlawley** [comment]
My workaround for now is to send garp messages when transitioning to master (037b1e9) but it would be better if the MAC address was constant, like for eth2.

**Comment by rhtyd** [comment]
Future note: explore a way to make the mac address constant.
