### ISSUE TITLE
Upon VM removal, VM records not removed from /etc/hosts

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3354]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.x
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

When VM is deleted and expunged, VM's record is not removed from /etc/hosts file and thus DNSmasq will continue to do DNS resolution for this VM's

##### STEPS TO REPRODUCE

Destroy and expunge the VM, observe /etc/hosts of the related VR - VM's name and IP address are present.

~~~

~~~

##### EXPECTED RESULTS

After VM is expunged/deleted, it's records/entries should be properly removed from /etc/hosts (and similar, not part of this issues, from DHCP related files)
~~~

~~~

##### ACTUAL RESULTS

VM records not deleted from /etc/hosts
~~~

~~~

**Comment by gildegoma** [comment]
FYI: I did some validation tests against CloudStack 4.11.3.0-RC1, and can confirm that this issue is now elegantly resolved :+1:

 :heart: :heart: :heart:
