### ISSUE TITLE
MTU for storage interface on SSVM is not honored

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3369]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

The global setting  **secstorage.vm.mtu.size**  does not get applied to the SSVM

##### STEPS TO REPRODUCE

~~~
Set the global setting  **secstorage.vm.mtu.size** to a jumbo frames value ie 4500 or 9000, then destroy the existing SSVM(s),


~~~

##### EXPECTED RESULTS

~~~
New SSVM should have the new MTU allied to the storage interface

~~~

##### ACTUAL RESULTS

~~~
No change in the MTU of the SSVM.
~~~

**Comment by rhtyd** [comment]
@PaulAngus  please test and review https://github.com/apache/cloudstack/pull/3370

**Comment by rhtyd** [comment]
Fixed and merged in https://github.com/apache/cloudstack/pull/3370
