### ISSUE TITLE
listProjects API command returns same tags as many times as there are accounts in the Project

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3375]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

listProjects API command returns same tags as many times as there are accounts in the Project

##### STEPS TO REPRODUCE

~~~
Create a project with n accounts in it (where n is more than 1)
Add some tags with any values
View the project's tags via UI or listProjects API (as an account in that project)
~~~

##### EXPECTED RESULTS

~~~
The user/admin should see each tag/value combination once
~~~

##### ACTUAL RESULTS

~~~
Each tag/value combination is returned n times (where n is the number of accounts in the project).
~~~

**Comment by ustcweizhou** [comment]
@PaulAngus 
can this be fixed by #3306  ?

**Comment by shwstppr** [comment]
Tested this locally with changes from #3306, fixed now. Can be closed.

**Comment by rhtyd** [comment]
Closing on @shwstppr 's remark.
