### ISSUE TITLE
User timezone is forced to UTC when user.timezone is undefined

### ISSUE THREAD

**Issue by gildegoma** [apache/cloudstack#3388]
##### ISSUE TYPE

 * Bug Report (regression apparently introduced by 0102e8593db435d5fa10d116470a37b220a0a257)

##### COMPONENT NAME

~~~
API
(UI)
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0+
4.12.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

###### Before CloudStack 4.11.0.0:
If the user.timezone is NULL, the API login response doesn't contain any timezoneoffset (nor timezone) attribute. In such situation the Admin Web UI gracefully applies the Web Browser timezone.

###### Since CloudStack 4.11.0.0:
If the user.timezone is NULL, the API login response contains timezone and timezoneoffset values by default. For this reason, the Admin Web UI no longer uses the Web Browser timezone, but display date/time values in UTC timezone.

##### STEPS TO REPRODUCE

* Have a CloudStack user with no timezone setting specified (i.e. `user.timezone` database field must be **NULL**)
* Use this user account to log into CloudStack Web UI with a Browser which timezone is different from UTC
* Optionally inspect the JSON loginresponse payload, and verify that `timezone == "UTC"` and `timezoneoffset == "0.0"` (see screenshot below)
* Go to the **Events** or **Alerts** view and check the *Date* colum. The displayed timezone is UTC.

![image](https://user-images.githubusercontent.com/434654/59108067-5e9d8200-893a-11e9-9705-4b20a4a847b6.png)

##### EXPECTED RESULTS

In cases where a CloudStack user profile has no explicit timezone defined, it is expected from the CloudStack Web UI to dynamically fetch and apply the user Web Browser timezone(offset).
The [Client-Side JavaScript code still exists](https://github.com/apache/cloudstack/blob/4.11.2.0/ui/scripts/sharedFunctions.js#L1291-L1298), but is only applied when no timezone data is returned by the CloudStack API (see loginresponse JSON payload).

In the debugging screenshot below, the code branch starting at line 1291 is expected to be executed, but it is the line 1289 which is executed instead.

![image](https://user-images.githubusercontent.com/434654/59107398-d4a0e980-8938-11e9-93e8-23277a30f81c.png)

##### ACTUAL RESULTS

Since CloudStack 4.11.0.0 (see 0102e8593db435d5fa10d116470a37b220a0a257), the [UserVO implementation has been changed](https://github.com/apache/cloudstack/blob/0102e8593db435d5fa10d116470a37b220a0a257/engine/schema/src/com/cloud/user/UserVO.java#L237-L239) to fallback to `"UTC"` when user.timezone is NULL.

This change [affects the API response](https://github.com/apache/cloudstack/blob/b363fd49f70ac2092ebe6226a72a3d911dc99e1f/server/src/main/java/com/cloud/api/ApiServer.java#L1113-L1116) on user authentication, leading the JavaScript UI code to **not fetch the browser timezoneoffset**, but to systematically use UTC timezone.

##### WORKAROUND

Explicitely set the user.timezone for each user (who doesn't want to see date/times in UTC timezone)

**Comment by DaanHoogland** [comment]
@gildegoma I wonder if using the browser time offset is really what you want as a lot of multitimezone implementations exist. What would you do to mitigate no timezone  vs UTC?
/cc @rhtyd

**Comment by gildegoma** [comment]
@DaanHoogland I have no preference for one solution over the other one, but I wanted to report and address the following points:

1. This new behaviour was _silently_ introduced in 4.11.0.0. (This change was not part of CLOUDSTACK-10129 [initial] goals, as far as I understood)
1. What are the exact benefits of this new behaviour? 
1. If this new behaviour is kept in the future, I'd propose to consider following anti-"technical debt" actions:
   - [ ] Make the `user.timezone` database field explicitly mandatory (i.e. NOT NULL constraint + default value) instead of the current `UserAccountVO::getTimezone()` override hack
   - [ ] Remove the obsolete/unused Client-Side code (fetching browser timezone offset, etc.)
   - [ ] Add spec/test coverage

**Comment by DaanHoogland** [comment]
@davidjumani I think the new UI handles this differently. can you check? (I do feel that the non-null default value makes sense btw. )

**Comment by davidjumani** [comment]
From what I've tested on the new UI, timezone conversion doesn't happen and everything is in UTC. Will require creating a fix for it

**Comment by davidjumani** [comment]
Created a button in the new UI to toggle between browser timezone and configured one. This way users can choose the timezone they'd like to use. @gildegoma Guess this should make everyone happy!
https://github.com/apache/cloudstack-primate/pull/903

**Comment by gildegoma** [comment]
@davidjumani thank you very much ❤️ The Primate enhancement looks pretty nice 👌🏿

**Comment by davidjumani** [comment]
@gildegoma @DaanHoogland The Primate PR has been merged, so users can choose between configured & local timezone. So can we close this issue ?

**Comment by gildegoma** [comment]
> So can this issue be closed ?

@davidjumani Yes, for sure! Thank you again for your work on this issue :)
