### ISSUE TITLE
Dedicate VMware hosts are still used for template seeding

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3392]
When a VMware host is dedicated to an account, the host may still be used for preparing templates. A dedicated host owner/account may not prefer that their host is used for template preparations.

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

##### COMPONENT NAME

~~~
VMware, Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.9.x, 4.11.x
~~~

**Comment by rhtyd** [comment]
cc @Spaceman1984 - good to have

**Comment by Spaceman1984** [comment]
@rhtyd what do you mean by "preparing templates"? Is this the process of adding an image template to Cloudstack and then the secondary storage agent does the download?

Would that then mean that a dedicated host should not have the system VMs running on it?

**Comment by rhtyd** [comment]
refer prepareTemplate API
