### ISSUE TITLE
Improve volume migration without using secondary storage if possible

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3404]
Currently, a volume migration from one primary storage to another primary storage pool happens via the secondary storage (or a caching storage pool if available). It's possible that both the primary storages are reachable from one-another and in which case the migration can happen directly. In case of VMware, (did not test but per tribal knowledge) a snapshot is taken then it is copied to secondary storage then copied the OVA down to new storage, then a volume is deployed from that template. The aim of the issue is to ask if future versions can have the volume migration improved. 

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Volumes, migration
~~~

##### CLOUDSTACK VERSION

~~~
4.9.x, 4.11.x, 4.13.x
~~~

**Comment by DaanHoogland** [comment]
@rhtyd, i think this was implemented for vmware (i worked on it) is there a more generic solution envisioned?
if not this should go to a future milestone.

**Comment by rhtyd** [comment]
I think @shwstppr explored this recently, we may propose enhancement/feature after 4.15

**Comment by nvazquez** [comment]
@shwstppr any update on this?

**Comment by shwstppr** [comment]
@nvazquez this has been addressed with #4385. Can be closed unless reported otherwise
