### ISSUE TITLE
VMware Worker VM doesn't get recycled after a configured timeout

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3408]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2 (didn't test previous ones)
~~~

##### CONFIGURATION

VMware 6.5u2 (should be irelevant)

##### OS / ENVIRONMENT

mgmt = CentOS 7 (irelevant)

##### SUMMARY

Temp VMware worker VM used to export volume snapshot is not being recycled (i.e. removed) after the timeout is reached (and when configured to be removed). Root cause seems to be the fact that we are not stopping the running OVF task, which cause the attempt to remove worker VM to fail (i.e. it is stuck in pending state).

##### STEPS TO REPRODUCE
Set following global settings:
- job.expire.minutes : 1
- job.cancel.threshold.minutes : 1
vmware.clean.old.worker.vms : true

Create a volume snapshot.
After 2 x ( job.expire.minutes + job.cancel.threshold.minutes) = 240 sec, the job will time out / fail with the following message in logs:

2019-06-17 11:35:26,459 INFO  [c.c.h.v.m.VmwareManagerImpl] (DirectAgentCronJob-40:ctx-dbfaf1a2) (logid:bff5a57c) *Worker VM expired, seconds elapsed: 252*
2019-06-17 11:35:26,463 INFO  [c.c.h.v.r.VmwareResource] (DirectAgentCronJob-40:ctx-dbfaf1a2) (logid:bff5a57c) *Recycle pending worker VM: 935686f0ee0b4b518ca2b50597650c75*

but tasks remain on the vCenter side:

![worker-vm-tasks-not-removed](https://user-images.githubusercontent.com/45762285/59602942-58f92680-9108-11e9-9b0a-624de4020cf4.JPG)

The way to "clean it manually" is to stop/kill the OVF export task in vCenter, after which the VM reconfiguration task and finally removal task (not visible on the image) will be executed and worker VM will be removed as per the expected behavior.

Issues seems, that we are NOT killing to OVF export task once the timeouts are reached in ACS, which is the required step.

~~~

##### EXPECTED RESULTS

~~~
OVF task is stopped/killed and worker VM get's removed.
~~~

##### ACTUAL RESULTS
~~~
Worker VM keeps running, as well as the OVF export task.
~~~

**Comment by andrijapanicsb** [comment]
FYI @nvazquez @rhtyd

**Comment by DaanHoogland** [comment]
@andrijapanicsb would this be part of the garbage collection epic?

**Comment by andrijapanicsb** [comment]
not related afaik... but a valid one.

**Comment by rhtyd** [comment]
Is this still an issue requiring a fix for 4.13/4.14 @andrijapanicsb @DaanHoogland ?

**Comment by DaanHoogland** [comment]
haven't had an eye on vmware @rhtyd and haven't tested this, but there are some issues open now:
- garbage collection
- basic zones
- migration
so tlc needed.

**Comment by rhtyd** [comment]
@harikrishna-patnala @Pearl1594 can you comment on this?

**Comment by rhtyd** [comment]
Moving out of 4.15 milestone, as this may require some vmware resource-wide refactoring changes

**Comment by Pearl1594** [comment]
This issue will still exist, as during the vm export operation, the we do not consider the expiry time while exporting a VM. Hence, deletion of worker VM in case of job expiry will still be hindered.

**Comment by rhtyd** [comment]
Closing as the linked PR has been merged.
