### ISSUE TITLE
VMware: volume statistics show wrong values

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3416]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
GetVolumeStatsCommand
~~~

##### CLOUDSTACK VERSION

~~~
4.11+ (tested 4.11.2 and Master)
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

physical volume size reported is wrong, and doesn't change after you write a lot of data to the VM's root disk (be it linked clone or full clone)

##### STEPS TO REPRODUCE

configure "volume.stats.interval" to 60000 (these are milliseconds, not seconds as stated atm - I raised a separate PR for this).

1. Grep management-server.log for "GetVolumeStatsCommand" and observe it's running each minute

2. Inside the VM, write i.e. 50MB to disk  -  "dd=/dev/urandom of=ddfile bs=1M count=50; sync"

3. Wait for next run of GetVolumeStatsCommand from the mgmt logs - check the size reported in the text output and also on the GUI

##### EXPECTED RESULTS

Correct physical size is reported

##### ACTUAL RESULTS

0.53KB reported instead of the real size (linked clone - from image bellow is ~ 220MB)

![image](https://user-images.githubusercontent.com/45762285/59966004-09ef2f00-9516-11e9-93d0-397d5db15802.png)

**Comment by andrijapanicsb** [comment]
Initial support seems implemented in 4.11 https://github.com/apache/cloudstack/commit/4627fb2cd7556173bd7e58bf1bec22c93a78f31d

But 4.11.2 is not working - so not sure if it was ever working properly.

Works fine for KVM.

**Comment by rhtyd** [comment]
Will investigate this tomorrow @andrijapanic cc @PaulAngus @borisstoyanov

**Comment by rhtyd** [comment]
Reopened due to this case where flat files are not part of the chain/info and are ignored in stats calculations: https://github.com/apache/cloudstack/pull/3473#issuecomment-512731291

**Comment by rhtyd** [comment]
Fixed recently https://github.com/apache/cloudstack/pull/4225
