### ISSUE TITLE
Build a new Debian 10 systemvmtemplate for 4.14+

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3426]
Outstanding items for the new feature/infra:

- Build systemvmtemplate based on Debian 10 without JRE11, but have systemvms's agent.zip have JRE embedded using jlink
- Start only services on setup/boot, don't enable by default
- Have a one-shot ACS services, that terminate after running
- Evaluate if number of processes could be reduced, as well the image size
- Implement a livepatch upgrade process/mechanism that is systemvm.iso+mount based

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
VR
~~~

**Comment by andrijapanicsb** [comment]
related to #3601

**Comment by andrijapanicsb** [comment]
We are aiming to do debian 10 systemvm in 4.15

**Comment by rhtyd** [comment]
Yes, let's aim to do this after 4.14 RC1 is cut.

**Comment by DaanHoogland** [comment]
what is the reason for closing this @rhtyd ?
