### ISSUE TITLE
extract/download marvin tests failing in Trillian

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3440]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Marvin
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

test_04_extract_Iso | `Failure` | 1.08 | test_iso.py
test_04_extract_template | `Failure` | 1.06 | test_templates.py
test_06_download_detached_volume | `Failure` | 10.34 | test_volumes.py
are failing in trillian

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~
[Matrix-kC7Adv-Smk-RC2Testing-2.zip](https://github.com/apache/cloudstack/files/3338233/Matrix-kC7Adv-Smk-RC2Testing-2.zip)

**Comment by borisstoyanov** [comment]
the following exception appears when calling urllib.urlopen(formatted_url) from the test. 
'\\'SSLContext\\' object is not callable'

So the current marvin test needs to be revised to check properly download when ssl is enabled

**Comment by rhtyd** [comment]
@borisstoyanov can you try to install `pip install requests[security]` (ensure both pip and python are 2.x, not 3.x) on the marvin/box where you're trying to run the test. It's possibly it's not the test issue, but issue with the python/env. If with this, test passes then we can fix it in Trillian. cc @PaulAngus @andrijapanic

**Comment by borisstoyanov** [comment]
@rhtyd pip says 'Requirement already satisfied'

**Comment by rhtyd** [comment]
okay let me pick this up as part of stabilisation effort on master I plan to do next week @borisstoyanov

**Comment by borisstoyanov** [comment]
@rhtyd I'll be picking this up today

**Comment by borisstoyanov** [comment]
I've spend some time investigating and it looks like it's more of an env related issue, the python libraries we're using to test the https download are not compiled with ssl support. 
` 
HTTPS support is only available if the socket module was compiled with SSL support.`
