### ISSUE TITLE
UserDispersingPlanner only counts Running vms on hosts.

### ISSUE THREAD

**Issue by cl-k-takahashi** [apache/cloudstack#3442]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UserDispersingPlanner.java
~~~

##### CLOUDSTACK VERSION

~~~
Current version
~~~

##### SUMMARY

When you try to deploy multiple vms in a short time, their state will go to 'Starting' state.
According to UserDispersingPlanner.java, it counts only Running vms on hosts to calculate priority of destination hosts to deploy vm. As a result, these vms can concentrate to one host if we try to deploy vms in a short time.
To avoid this, I think we should count not only Running vms but also Starting vms.
```
        Long totalVmsOfAccount = vmInstanceDao.countRunningByAccount(accountId);
        if (s_logger.isDebugEnabled()) {
            s_logger.debug("Total VMs for account: " + totalVmsOfAccount);
        }
```
quoted from UserDispersingPlanner.java (master)

**Comment by rhtyd** [comment]
UserDispersingPlanner can consider both VMs in running and starting states.

**Comment by anuragaw** [comment]
Working on this.

**Comment by anuragaw** [comment]
Testing was little tricky locally but the PR would be out later today. Verified that counting stating VMs makes sense does not break anything.
