### ISSUE TITLE
Quota calculation is incorrect

### ISSUE THREAD

**Issue by huadream** [apache/cloudstack#3448]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Quota
~~~

##### CLOUDSTACK VERSION

~~~
master branch
~~~

##### SUMMARY

https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L101
The default value of `usage.stats.job.aggregation.range` is 1440.
_aggregationDuration = Integer.parseInt(aggregationRange);
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L142
The value of `aggregationRatio` calculated is `1440/(30 * 24 * 60)`.

All updateQuota* functions have the bug below.
https://github.com/apache/cloudstack/blob/1d05fead49f5c856257a741b07122f5633d2e359/framework/quota/src/main/java/org/apache/cloudstack/quota/QuotaManagerImpl.java#L436
This line would be one-day-cost not one-hour-cost.
So the `aggregationRatio` should be fixed with `1/(30 * 24)`.

**Comment by rhtyd** [comment]
Ping @msinhore can be comment ^^

**Comment by msinhore** [comment]
@rhtyd need to be tested. We have it running in production and no one reported any kind of calculation issue.

**Comment by DaanHoogland** [comment]
@huadream have you issues with this and a workaround? nobody else complains about this, so either no one uses quota or it is failing only for you. As you have pinpointed the issue in code, can you submit a PR for fixing it? or alternatively do you think we can close this issue?
