### ISSUE TITLE
Memory Used is incorrect

### ISSUE THREAD

**Issue by kioie** [apache/cloudstack#3456]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11+
~~~

##### SUMMARY

Memory metrics for VMs seems to be reporting incorrect info.
When you run the `list virtualmachines` command, the results return values that are not correct
![Screen Shot 2019-07-02 at 12 03 29 PM](https://user-images.githubusercontent.com/20902920/60500584-457ebb80-9cc3-11e9-8f16-afb389e8845c.png)

According to the [listVirtualMachines](https://cloudstack.apache.org/api/apidocs-4.12/apis/listVirtualMachines.html) api doc, the `memorykbs` should report `the memory used by the vm` and the `memorytargetkbs` should report `the target memory in vm` . Both values cannot be the same

##### STEPS TO REPRODUCE

~~~
list virtualmachines
~~~

##### EXPECTED RESULTS

~~~
memorykbs should report `the memory used by the vm`
`memorytargetkbs` should report `the target memory in vm`
~~~

##### ACTUAL RESULTS

~~~
 Both produce the same results

"memorykbs": 1048576,
"memorytargetkbs": 1048576,
~~~

**Comment by rhtyd** [comment]
On which hypervisor are you seeing this @kioie, if it's simulator - note that values are mocked by simulator and are not representative of real-world-hypervisor.

**Comment by kioie** [comment]
@rhtyd Hypervisor is KVM ....actually the simulator for some interesting reason doesn't mock any values for memory

**Comment by kioie** [comment]
I'm thinking the issue could be because of the below

 ```
public VmStatsEntry getVmStat(final Connect conn, final String vmName) throws LibvirtException {
        Domain dm = null;
        try {
            dm = getDomain(conn, vmName);
            if (dm == null) {
                return null;
            `}`
            DomainInfo info = dm.getInfo();
            final VmStatsEntry stats = new VmStatsEntry();

            stats.setNumCPUs(info.nrVirtCpu);
            stats.setEntityType("vm");

            stats.setMemoryKBs(info.maxMem);
            stats.setTargetMemoryKBs(info.memory);
            stats.setIntFreeMemoryKBs(getMemoryFreeInKBs(dm));
```

stats.setMemoryKBs(info.maxMem);
stats.setTargetMemoryKBs(info.memory);

I believe `maxMem` and `memory` would most likely return similar values

**Comment by rhtyd** [comment]
@kioie are you able to reproduce using latest master?

**Comment by kioie** [comment]
The above is on 4.12, but looking at the code base on latest master, doesn't look like much anything has changed on this endpoint

**Comment by shwstppr** [comment]
Checked with VMware and it is same,
```
list virtualmachines id=f834f6d2-aef3-4b71-bc19-a59bb4e4f7a7 
{
  "count": 1,
  "virtualmachine": [
    {
      "account": "admin",
      "affinitygroup": [],
      "cpunumber": 1,
      "cpuspeed": 500,
      "cpuused": "52%",
      "created": "2019-07-04T12:06:30+0000",
      "details": {
        "cpuOvercommitRatio": "2.0",
        "dataDiskController": "osdefault",
        "memoryOvercommitRatio": "1.0",
        "rootDiskController": "ide"
      },
      "diskioread": 43,
      "diskiowrite": 34,
      "diskkbsread": 1792,
      "diskkbswrite": 266,
      "displayname": "VM-f834f6d2-aef3-4b71-bc19-a59bb4e4f7a7",
      "displayvm": true,
      "domain": "ROOT",
      "domainid": "aaa52283-9986-11e9-aa0e-1e007b01075d",
      "guestosid": "aaae020e-9986-11e9-aa0e-1e007b01075d",
      "haenable": false,
      "hostid": "2c998985-2ef6-419c-82f2-894f9c3c12e2",
      "hypervisor": "VMware",
      "id": "f834f6d2-aef3-4b71-bc19-a59bb4e4f7a7",
      "instancename": "i-2-3-VM",
      "isdynamicallyscalable": false,
      "memory": 512,
      "memoryintfreekbs": 393216,
      "memorykbs": 524288,
      "memorytargetkbs": 524288,
      "name": "VM-f834f6d2-aef3-4b71-bc19-a59bb4e4f7a7",
      "networkkbsread": 0,
      "networkkbswrite": 0,
```

`memorykbs` is surely not the memory currently in use. Not sure if it is an ambiguity with docs or issue with code.

**Comment by DaanHoogland** [comment]
@kioie can you recheck with the current master branch, please. Metrics have been somewhat adjusted.

**Comment by DaanHoogland** [comment]
@kioie closing this as well, please check with 4.15 and reopen if I shouldn't have.
