### ISSUE TITLE
When system vm is deployed from a new secondary pool it may fail to live migrate because the new secondary storage pool is not mounted in target host.

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3478]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.9
~~~

##### SUMMARY

With VMware, when a new secondary storage pool is added, and a system-vm is being deployed from that mount, cloudstack operator cannot live migrate the VM to a new host because the secondary storage pool is not mounted on the host. 

2019-07-02 17:18:20,490 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-10:ctx-e0ee2e04 job-496401) (logid:4365c38d) Complete async job-496401, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":530,"errortext":"MigrationCommand failed due to Exception: java.lang.RuntimeException\nMessage: 現在接続しているデバイス「CD/DVD drive 1」が、アクセスできないバッキング「[acb61221d4cc3273852f15dea25b9c57] systemvm/systemvm-4.9.1.0.iso」を使用しています。\n"}

The message written in Japanese means "Device 'CD/DVD drive 1' uses backing '[acb61221d4cc3273852f15dea25b9c57] systemvm/systemvm-4.9.1.0.iso', which is not accessible.".

##### EXPECTED RESULTS

~~~
Migration should be successful 
~~~

##### ACTUAL RESULTS

~~~
Migration fails since the secondary storage pool is not mounted on the target host.
~~~

**Comment by rhtyd** [comment]
I checked both 4.9, 4.11, master codebases prior to VM migration it does check that the secondary storage is mounted. However, the root cause is that when there are multiple secondary storages it picks one randomly which is mounted instead of the specific secondary storage.

Here it picks one datastore instead of a list for that zone:
https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/manager/VmwareManagerImpl.java#L495

**Comment by rhtyd** [comment]
Related issue on secondary storage selection: https://github.com/apache/cloudstack/issues/3041

**Comment by shwstppr** [comment]
@rhtyd Do we need to call the prepareSecondaryStorageStore method for all secondary stores of a datacenter to be fail safe?
Already refactored image store selection for a datacenter for writing wrt their free capacity #3480 

In that case HyperV will need similar changes

**Comment by rhtyd** [comment]
Yes Abhishek, loop through and ensure all sec storages are mounted for a zone.
