### ISSUE TITLE
Can't share a template that is in a project

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3481]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Templates
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY

If a template is created in a project, an error is returned if a user in that project tries to share the template from within the project

##### STEPS TO REPRODUCE

Create a project and register a template while in the project, try to share the template with an account

##### EXPECTED RESULTS

~~~
Template is shared
~~~

##### ACTUAL RESULTS

![319888e8-a92e-42a1-b060-f8657bb7730d](https://user-images.githubusercontent.com/13551960/60971545-199baf80-a32d-11e9-9929-fe76bf6b7dc1.png)

**Comment by kioie** [comment]
Looks to me like this logic works as expected...I am thinking, only owner or admin should be allowed to share templates

**Comment by borisstoyanov** [comment]
![Screenshot 2019-07-17 at 16 11 49](https://user-images.githubusercontent.com/13551960/61378294-c76b0900-a8ad-11e9-888b-d16820e2412a.png)
with latest #3241

**Comment by DaanHoogland** [comment]
@borisstoyanov can you confirm that #3241 solved thois issue? does it need backporting?

**Comment by borisstoyanov** [comment]
Looks like it was merged in 4.13.1 and it was a new feature of 4.13 as far as I remember.

**Comment by DaanHoogland** [comment]
looks like all code is on 4.13 head as well, @borisstoyanov . can you confirm we can close this?

**Comment by borisstoyanov** [comment]
thanks @DaanHoogland
