### ISSUE TITLE
Allow ISO Upload from Local Machine

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack#3496]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In CloudStack 4.11, it's possible to upload VM templates directly from the web interface, without requiring an upload to an intermediate web server first.

This should also be implemented for ISO uploads.

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
N/A
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~

**Comment by ustcweizhou** [comment]
this has been fixed by #3251

**Comment by onitake** [comment]
Woops I think I even saw that PR, but didn't realise what it did. Mea culpa.
