### ISSUE TITLE
Add support to revert (rollback) a RBD image snapshot

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#3498]
Currently, it is not possible to revert/rollback an RBD image snapshot.

I will be soon opening a PR adding support to reverting RBD snapshot volumes. Hope that this one makes in time for 4.13. What is the status of 4.13 @PaulAngus @rhtyd?

##### COMPONENT NAME

~~~
KVM & Ceph/RBD
~~~

**Comment by rhtyd** [comment]
@GabrielBrascher We would ideally want to freeze, stabilise master and cut RC1 by end of this month, likely the week of 29th July. cc @PaulAngus

**Comment by GabrielBrascher** [comment]
Thanks for the update @rhtyd!

**Comment by rhtyd** [comment]
Merged https://github.com/apache/cloudstack/pull/3502
