### ISSUE TITLE
Physical networking with pfsense

### ISSUE THREAD

**Issue by imacks** [apache/cloudstack#3499]
I'm trying out cloudstack for the first time, so pls be patient. My current physical setup:
```
---wan---( pfsense )---lan---( pc1 )
            +----------------( pc2 )--------( l2 dumb switch )
```
Pfsense works as DHCP server, assigning 172.18.1.x to pc1 and 172.18.1.y to pc2. Pfsense itself isn't relevant, as it works mostly as a generic router in this setup.

PC1 is hyper-v server with 1 physical nic, bound to a virtual switch. It runs 1 VM instance of MySQL, NFS server, and cloudstack management each. Cloudstack management VM virtual nic vlan is configured in trunk mode (0, 10-1000); the other VMS are untagged.

I can see on pfsense 5 DHCP leases, all on 172.18.1.1/24.

Pc2 is kvm host on Ubuntu server, with 2 physical nics. Nic 1 (eth0)  is attached to pfsense with up by DHCP 172.18.1.y as said. Nic 2 (eth1) is plugged to a l2 switch.

Pc2 eth1 is configured `iface inet manual`. Then I have cloudbr1 bridge interface that has eth1 as it's port. All are following cloudstack doc on hypervisor installation re. guest Network.

I am now totally lost on advanced zone setup. What's:
- guest cidr
- internal DNS 1
- the physical network page setup
- public traffic ips
- pod reserved system gateway, netmask, reserved ip range
- guest vlan range

**Comment by kioie** [comment]
Hey @imacks 

For starters, I'm assuming this is not a prod environment, possibly test/dev in which case please note this as mentioned in the documentation

> A /24 network with the gateway being at xxx.xxx.xxx.1, no DHCP should be on this network and none of the computers running CloudStack will have a dynamic address. Again this is done for the sake of simplicity.

So you might want to give a static IP to all machines and possibly disable DHCP. You will also realize, that Advanced networking may not work with a single subnet, you will need additional subnets/vlans to isolate traffic

**Guest cidr** - the default `10.1.1.0/24` should work fine

**Internal DNS 1 and Internal DNS 2**- These are DNS servers for use by system VMs in the zone(these are VMs used by CloudStack itself, such as virtual routers, console proxies,and Secondary Storage VMs.) These DNS servers will be accessed via the management traffic network interface of the System VMs. If unsure about what to use here, you can use `8.8.8.8` and `8.8.4.4`, as long as management traffic has access to the internet.

**physical network page setup** - 

> The traffic types are management, public, guest, and storage traffic. For more information about the types, roll over the icons to display their tool tips, or see “Advanced Zone Network Traffic Types”. This screenstarts out with one network already configured. If you have multiple physical networks, you need to add more. Drag and drop traffic types onto a greyed-out network and it will become active. You can move the traffic icons from one network to another; for example, if the default traffic types shown for Network 1 do not match your actual setup, you can move them down. You can also change the network names if desired.
> 
> (Introduced in version 3.0.1) Assign a network traffic label to each traffic type on each physical network. These labels must match the labels you have already defined on the hypervisor host. To assign each label, click the Edit button under the traffic type icon within each physical network. A popup dialog appears where you can type the label, then click OK.
> 
> These traffic labels will be defined only for the hypervisor selected for the first cluster. For all other hypervisors, the labels can be configured after the zone is created.

In your case, you may need additional bridges if you are setting up an advanced network. See **[here](https://www.shapeblue.com/networking-kvm-for-cloudstack-2018-revisit-for-centos7-and-ubuntu-18-04/)** for a detailed account on what bridges you might require.

**Pod Configuration/guest vlan range/public traffic ips** - Alot of this will depend on how you setup your bridges

Also, considering this is not a dev issue, you might want to close this and move this conversation to the mailing list where you might get better support.

**Comment by imacks** [comment]
tks for clarifying. I have looked at the linked articles before. 

i'm just really having a hard time finding an example physical network routing topology that is for production use. Perhaps the documentation can benefit from some walkthroughs? But no this is not code related issues, so I'll bring it to the mailing list.
