### ISSUE TITLE
create snapshot fail with error domain not found

### ISSUE THREAD

**Issue by velinbudinov** [apache/cloudstack#3503]
##### ISSUE TYPE
 * Bug Report

##### CLOUDSTACK VERSION
CS: 4.11.2
Hypervisors: KVM
CS agents: 4.11.2

##### CONFIGURATION
basic networking

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
On stopped VM, can't create snapshot
[snapshot.log](https://github.com/apache/cloudstack/files/3406891/snapshot.log)

**Comment by rhtyd** [comment]
This is not a problem, stopped VMs cannot have VM snapshot but only volume snapshot.
