### ISSUE TITLE
Incorrect isolated network creation

### ISSUE THREAD

**Issue by DmB991** [apache/cloudstack#3513]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
agent
isolated networks
L2 networks
~~~

##### CLOUDSTACK VERSION
~~~
4.11.3.0
4.11.2.0
~~~

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
- Centos 7
- kernel 5.1.14-1.el7.elrepo.x86_64
- qemu-kvm-ev 2.12.0
- libvirt 4.5.0
- separate storage with nfsv3/v4 and zfs
- MariaDB 10.4.6

##### SUMMARY
Incorrect isolated network creation when huge amount of VMs and networks already created async.

##### STEPS TO REPRODUCE
1. Create guest network.
2. Create network offering for isolated network with default settings and without any supported services.
3. Create isolated network with network offering above.
4. Create and destroy(after few minutes) 2 VMs(with 1core x 512Mhz and 512Mb ram) async with networks above.
5. Perform 3-4 points async huge amount(from 500 to 2000) times.

##### ACTUAL RESULTS
After STEPS TO REPRODUCE we see two machines with names 'redistr-200-28424-smoke-gre-425-20e8ff03'(i-2-322138-VM) and 'redistr-200-28424-smoke-gre-425-7fcc1e3a'(i-2-322566-VM).
Each machine has guest(shared4) and isolated network(redistr-200-28424-smoke-gre-425-0)  .
![net](https://user-images.githubusercontent.com/3996198/61744175-517c0b80-ad9f-11e9-9de6-27d44aae4cf6.png)
![vms_of_net](https://user-images.githubusercontent.com/3996198/61744176-5214a200-ad9f-11e9-80cf-a518826f8b7f.png)

We can ping from one VM to another VM throught eth0, but we can't ping throught eth1.
On the first cloudstack host we see that vnet301(eth1) of i-2-322566-VM in the brenp8s0f0-1016 and we see request in modifyvlan.sh for create bridge and add vlan to it.
On the second cloudstack host we don't see any bridge or vlan with 1016 in the name of interfaces and we don't see any requst for creation it in the modifyvlan.sh.
We see that vnet126 in another bridge brenp1s0-2889.
[first-host-request-create-vm.log](https://github.com/apache/cloudstack/files/3423905/from-first-host-agent.log)
[second-host-request-create-vm.log](https://github.com/apache/cloudstack/files/3423906/from-second-host-agent.log)

* modifyvlan.sh = /usr/share/cloudstack-common/scripts/vm/network/vnet/modifyvlan.sh (or https://github.com/apache/cloudstack/blob/master/scripts/vm/network/vnet/modifyvlan.sh)

##### EXPECTED RESULTS
~~~
On the second cloudstack host brNAME-1016 are created with vnet126 included for i-2-322138-VM.
~~~

##### LOGS
management-server.log(reproduced on 4.11.3.0) https://yadi.sk/d/CxLKq293WF9Psg
network redistr-200-68979-smoke-gre-284-0 with vlan 2958
VM redistr-200-68979-smoke-gre-284-cbb50e02 with eth1 network redistr-200-68979-smoke-gre-284-0 (vlan 2958)
VM redistr-200-68979-smoke-gre-284-4e22a7ea with eth1 network redistr-200-68979-smoke-gre-284-0 (vlan 3330, should be 2958)

**Comment by DmB991** [comment]
The same problem with L2 networks

**Comment by DaanHoogland** [comment]
@DmB991 did you test on latest master?

**Comment by weizhouapache** [comment]
this is related to #3807
you can set allow.duplicate.networkname to false (it is true by default) in global setting.

**Comment by DaanHoogland** [comment]
@DmB991 can you confirm with 4.14 or later and close this issue?

**Comment by DaanHoogland** [comment]
assuming this is resolved in latest releases, please reopen if it persists.
