### ISSUE TITLE
add size to usage type 27

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3530]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
usage
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY

size is missing from usage type 27, but available in related type 25. For consistency it's good to have

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
size should be available 
~~~

##### ACTUAL RESULTS

~~~
it's missing
~~~

**Comment by borisstoyanov** [comment]
fixed by #3529

**Comment by rhtyd** [comment]
Fixed in **https://github.com/apache/cloudstack/pull/3529**
