### ISSUE TITLE
# of CPU_CORE capacity has been shown wrongly

### ISSUE THREAD

**Issue by msinhore** [apache/cloudstack#3542]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
capacity calculation
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

The # of CPU_CORE capacity has been shown wrongly when, even considering the operprovisioning factor, the value presented should be for maximum capacity = 100% and no more than this. 
Example in CloudMonkey command: 
cloudmonkey list capacity filter=name,percentused, | grep CPU_CORE
CPU_CORE,195.72

In the UI, the CPU_CORE value, shown out of margin in "Infrastructure > Zones > select zone > Resources"

![Captura de Tela 2019-08-05 às 14 22 08](https://user-images.githubusercontent.com/108022/62482762-73589380-b78c-11e9-8b6c-f95d19778053.png)
![Captura de Tela 2019-08-05 às 14 21 56](https://user-images.githubusercontent.com/108022/62482766-75baed80-b78c-11e9-9c2b-d0ceb9569cb1.png)

**Comment by rhtyd** [comment]
It's because it adds all the CPU cores from all the VM instances, while the total cores is from the hosts.

**Comment by msinhore** [comment]
Thanks @rhtyd for the explanation. 

Maybe the better way to display these information is use the overprovisioning algorithm, considering it as the maximum resources available to be used. As it is, isn't a polished UX.
