### ISSUE TITLE
Live Volume Resize when fails returns as success on KVM

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3543]
While live resizing a volume on KVM (CentOS 6.x), when the resize script fails it outputs `failed to live resize...` but as part of the resize volume answer it returns the correct/current new size as the old size and returns the success as `true`, the requested resize value is then set in the `volumes.size`.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM, volumes
~~~

##### CLOUDSTACK VERSION

~~~
4.9, 4.11
~~~

##### CONFIGURATION

CentOS/EL6.x

**Comment by shwstppr** [comment]
I'll look into this

**Comment by DaanHoogland** [comment]
ping @shwstppr is this active?

**Comment by shwstppr** [comment]
@DaanHoogland will check and update today

**Comment by rhtyd** [comment]
Not applicable anymore as CentOS6 is no longer supported
