### ISSUE TITLE
When scrolling down the VM settings, they keep on loading again and again endlessly

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3544]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
Master
~~~

##### SUMMARY

Observed in vm settings and template settings. When settings are a lot, it loads them over and over endlessly when scrolling down

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
#3690 and #3691 relate to this

**Comment by MNettesheim** [comment]
Hi Boris, 
Isn't this about the OVF properties page, rather than the settings page.

**Comment by borisstoyanov** [comment]
Hi @MNettesheim, 
It's about the settings at template and vm, but we're considering the ovf settings at #3690

**Comment by DaanHoogland** [comment]
merged in 4.13 and master
