### ISSUE TITLE
When adding a new KVM zone, the template_store_ref may get wrong install_path for systemvmtemplate

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3548]
With an existing zone with a new system template (that would be registered with root admin's accoutn ID):
- Add a new zone and scp/copy the system template directory to the new zone's secondary storage
- Check the `install_path` template_store_ref for the reference for the systemvmtemplate in the new zone, does it use the account ID 1 in the folder path?

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SystemVM Template
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

**Comment by rhtyd** [comment]
Looks like the systemvm install script by default hard codes the account folder to `1`:
https://github.com/apache/cloudstack/blob/master/scripts/storage/secondary/cloud-install-sys-tmplt#L205

**Comment by rhtyd** [comment]
Another issue discovered is that the script renames the uuid for the template which is not necessary.

**Comment by rhtyd** [comment]
@Pearl1594 is this still an issue with new secondary storage changes? cc @Spaceman1984

**Comment by Pearl1594** [comment]
@rhtyd I haven't noticed anything odd wrt the install path of sytemvm templates, the install_path in template_store_ref table seemed to be correct.
I think when the systemvm template is registered as root admin - the path is template/tmpl/2/<template_id>/...

**Comment by nvazquez** [comment]
@Pearl1594 does your work on the system VM template improvements fix this issue?

**Comment by Pearl1594** [comment]
@nvazquez I haven't really testing in a multi-zone env - at this point, it hasn't been addressed. However, I can test/verify if this is still persistent and try to fix it.

**Comment by rhtyd** [comment]
Thanks @Pearl1594 looking forward to that.

**Comment by nvazquez** [comment]
Thanks @Pearl1594 please advise after your tests

**Comment by Pearl1594** [comment]
@rhtyd @nvazquez I don't think this is an issue as when the` cloud-install-sysvm-tmplt `script is used for seeding the template, it assumes that the template is owned by system account (account_id = 1) therefore on addition of the new zone, the path is properly updated.

Following is the observation made:

#### Seeded template :
```
# ls /export/testing/qa2-testzone415-b9ca73e3-kvm/secondary2/template/tmpl/1/3/   <--- zone1
deeeb1c5-5e26-4ab0-b72e-86e3ef0a6c47.qcow2  template.properties
# ls /export/testing/qa2-testzone415-b9ca73e3-kvm/secondary1/template/tmpl/1/3/ <--- zone2
f1b14109-1ea3-4c8f-8643-02d3006c68f3.qcow2  template.properties
```

#### Image store:
```
MariaDB [cloud]> select * from image_store\G
*************************** 1. row ***************************
                 id: 1
               name: nfs://172.20.0.1/export/testing/qa2-testzone415-b9ca73e3-kvm/secondary1
image_provider_name: NFS
           protocol: nfs
                url: nfs://172.20.0.1/export/testing/qa2-testzone415-b9ca73e3-kvm/secondary1
     data_center_id: 1
              scope: ZONE
               role: Image
               uuid: 1a5ee1f0-4191-458b-bd7c-18048f963b6a
             parent: 74432ad6-abcd-3ca4-a8d9-a20f91fcd339
            created: 2021-08-24 04:12:06
            removed: NULL
         total_size: NULL
         used_bytes: NULL
           readonly: 0
*************************** 2. row ***************************
                 id: 2
               name: nfs://172.20.0.1/export/testing/qa2-testzone415-b9ca73e3-kvm/secondary2
image_provider_name: NFS
           protocol: nfs
                url: nfs://172.20.0.1/export/testing/qa2-testzone415-b9ca73e3-kvm/secondary2
     data_center_id: 2
              scope: ZONE
               role: Image
               uuid: 7ada2348-e31f-4c53-994f-6c047afe9373
             parent: 25f12d68-e6b0-3610-9519-93d15de72bba
            created: 2021-08-24 04:21:47
            removed: NULL
         total_size: NULL
         used_bytes: NULL
           readonly: 0
2 rows in set (0.00 sec)
```

#### template_store_ref details corresponding to the systemvm template
```
MariaDB [cloud]> select id, store_id, template_id, download_pct, store_role, download_state, install_path, url, state, destroyed from template_store_ref where template_id = 3\G
*************************** 1. row ***************************
            id: 5
      store_id: 1
   template_id: 3
  download_pct: 100
    store_role: Image
download_state: DOWNLOADED
  install_path: template/tmpl/1/3/f1b14109-1ea3-4c8f-8643-02d3006c68f3.qcow2
           url: https://download.cloudstack.org/systemvm/4.15/systemvmtemplate-4.15.1-kvm.qcow2.bz2
         state: Ready
     destroyed: 0
*************************** 2. row ***************************
            id: 13
      store_id: 2
   template_id: 3
  download_pct: 100
    store_role: Image
download_state: DOWNLOADED
  install_path: template/tmpl/1/3/deeeb1c5-5e26-4ab0-b72e-86e3ef0a6c47.qcow2
           url: https://download.cloudstack.org/systemvm/4.15/systemvmtemplate-4.15.1-kvm.qcow2.bz2
         state: Ready
     destroyed: 0
2 rows in set (0.00 sec)

```
As for the name being different, though that is not necessary - it doesn't cause any issue

**Comment by nvazquez** [comment]
Thanks @Pearl1594, closing after your remarks
