### ISSUE TITLE
Upload ISO fails if the ISO name contains space

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3552]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, Upload from Local
~~~

##### CLOUDSTACK VERSION

~~~
Master
~~~

##### STEPS TO REPRODUCE

~~~
1. CReate and iso with a space in the name, for example "test_iso (1).iso"
2. Upload it from local
~~~

##### EXPECTED RESULTS

~~~
Upload successful
~~~

##### ACTUAL RESULTS

~~~
![Screenshot 2019-08-12 at 15 07 53](https://user-images.githubusercontent.com/13551960/62944484-7afbe600-bde5-11e9-8772-ae108aa1b622.png)
![Uploading Screenshot 2019-08-12 at 15.07.31.png…]()

~~~

**Comment by borisstoyanov** [comment]
![Screenshot 2019-08-12 at 15 07 53](https://user-images.githubusercontent.com/13551960/62944517-864f1180-bde5-11e9-9dfe-229c78e9fc32.png)
![Screenshot 2019-08-12 at 15 07 31](https://user-images.githubusercontent.com/13551960/62944519-864f1180-bde5-11e9-819f-da0e1e3824eb.png)

**Comment by rhtyd** [comment]
Oh so, this was the bug. Thanks for reporting. Likely some space issue somewhere, though we only check by suffix/extension.

**Comment by DaanHoogland** [comment]
@borisstoyanov has this slipped between the cracks, or is it no longer an issue? (cc @rhtyd )

**Comment by DaanHoogland** [comment]
either in the (old) ui or in the API. should be not to hard to find.

**Comment by nvazquez** [comment]
@borisstoyanov is this still an issue with the new UI?

**Comment by borisstoyanov** [comment]
@nvazquez just checked it, not a valid issue anymore with the new ui, closing.
