### ISSUE TITLE
Guest OS preference isn't working to define physical hosts to deploy os types

### ISSUE THREAD

**Issue by msinhore** [apache/cloudstack#3554]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.x
~~~

##### CONFIGURATION

Define the OS preference as Windows in one host to take advantage of hardware and OS licensing models.

##### OS / ENVIRONMENT

Hypervisor: VMware 6.5
Template: Windows Server Datacenter 2016 

##### SUMMARY

If a host is defined to be preferred OS for windows for example, it isn't working. The Windows OS is deployed on any hosts. 
This issue occurred with  "Windows Server 2019 Datacenter" using os_type "Windows Server 2016 (64-bit)"  running on top VMware 6.5.
##### STEPS TO REPRODUCE

~~~

- Setup the OS preference for Windows in one host.
- Deploy a Windows VM.
~~~

##### EXPECTED RESULTS

~~~
Windows VM running in target host where Os preference is Windows.
 ~~~

##### ACTUAL RESULTS

~~~
The Instance VM is being deployed in a random host.
~~~

**Comment by msinhore** [comment]
Thank you @rhtyd for you explanation.

**Comment by andrijapanicsb** [comment]
Why closing this one @msinhore - this is, in my opinion, a bug - or at leasts an undocumented behaviour.

**Comment by weizhouapache** [comment]
thanks @rhtyd .
what @rhtyd missed is that, if vm has last host_id specified, cloudstack will try to start vm on it at first.
for new vm, it will be deployed to the host as we expect.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4338
