### ISSUE TITLE
Hide UpdateTemplatePermissions button when the template is owned by a project.

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3555]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### SUMMARY

If a template is owned by a project it cannot be shared. User gets the following error: 

Update template permissions is an invalid operation on template project1tmpl. Project owned templates cannot be shared outside template.

It makes sense to hide the button. 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Action should be hidden
~~~

##### ACTUAL RESULTS

~~~
Action is available
~~~

**Comment by borisstoyanov** [comment]
ping @anuragaw

**Comment by rhtyd** [comment]
This has been fixed in Primate
