### ISSUE TITLE
Snapshots that have timed out have been left on the secondary storage

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3559]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Snapshots, vmware
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### CONFIGURATION

VMware, NFS

##### SUMMARY

When a snapshot has timed out the job fails but the file itself is left on the secondary storage pool. This may cause the storage pool to be filled with unusable data. 
There's also no records in the DB about the snapshots

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
files to be properly cleaned 
~~~

##### ACTUAL RESULTS

~~~
There's files on the secondary storage drive and no DB records for them
~~~

**Comment by server24** [comment]
This seems to be the case for KVM, also.

**Comment by tsvetanakostova** [comment]
Same issue here, again with VMware.

**Comment by rhtyd** [comment]
@nvazquez cc @andrijapanicsb  @DaanHoogland was this issue fixed recently?

**Comment by rhtyd** [comment]
cc @Spaceman1984 can you discuss with any of @borisstoyanov @andrijapanicsb @DaanHoogland and @nvazquez

**Comment by Spaceman1984** [comment]
Creating a snapshot is an asynchronous process, 

The expected result is that the files should be cleaned when the process times out. I'm not sure if this is the safest solution.

At the point that the timeout occurs, Cloudstack doesn't make any assumptions that the process will eventually complete. It simply cleans up the DB. A timeout is there to prevent waiting for a process forever. 

I think the question here should be, why is the process timing out? Wouldn't it make sense to just raise the timeout value then?

I tested with the built-in template and the process didn't time out - So this would seem like some kind of edge case.

**Comment by andrijapanicsb** [comment]
We should clean our junk on any failures - simple as that - no excuses... 
(i.e. we do cleanup VM if the live migration/storage migration doesn't happen within the timeouts period)
