### ISSUE TITLE
vmware dvSwitches - promiscuous mode gets 'reject' when another network is attached to a VM

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3565]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
dvSwitch
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### SUMMARY

When a new network is joined to a VM the promiscuous mode gets to 'reject' of the original network. 

##### STEPS TO REPRODUCE

~~~
1. Create a network with promiscuous mode accept. 
2. Deploy a VM on it
3. On a separate VM, add a new nic to with the created network
~~~

##### EXPECTED RESULTS

~~~
Prom mode to remain Accept
~~~

##### ACTUAL RESULTS

~~~
It changes to Reject 
~~~

**Comment by DaanHoogland** [comment]
fixed by merge of 4.13 in master (#3781 )
