### ISSUE TITLE
IPv6 code cleanup

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#3569]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
IPv6
Basic Networking
Advanced Networking
~~~

##### CLOUDSTACK VERSION
~~~
master
~~~

##### CONFIGURATION
IPv6

##### SUMMARY
A lot of the current IPv6 code dates back to 2013 and is poorly implemented.

This code copied IPv4 logic like allocating addresses in a table and then handing them out through DHCP to an Instance to IPv6 and that is not how it works with IPv6.

In Basic Networking and Advanced Networking with Shared Networks IPv6 already works and Security Grouping also supports IPv6.

A lot of the code around IPv6 in CloudStack however still applies logic like "startip" and "endip" for IPv6 while this isn't needed as just the "cidr" is sufficient.

Cleaning up this code will not break existing functionality, but it will remove a lot of dead code and make it more clear for other developers on how the flow works.

This issue is here so that future PRs (which me and @GabrielBrascher will open) can refer to this issue.

**Comment by DaanHoogland** [comment]
@wido @GabrielBrascher as I understand this is ongoing but partly done  i'm marking this for 4.16 Hope you agree

**Comment by rhtyd** [comment]
@wido @GabrielBrascher anybody working on this?

**Comment by GabrielBrascher** [comment]
@rhtyd right now there are no PRs on the way.

PRs #3571 and #4177 worked in some parts to tackle the problem raised in this issue; however, there is still room for some code cleanup and enhancements in the IPv6 codebase.

This is not a top priority issue (bug fix nor enhancements) but still would be nice to have it tackled in the future.
For now, I think that we can postpone and remove the 4.16 milestone.

**Comment by DaanHoogland** [comment]
those two issues are closed @GabrielBrascher @rhtyd let's close this? (cleanup should be a focus on any PR, safe maybe urgent fixes)

feel free to reopen if you disagree.
