### ISSUE TITLE
secondary-storage-vm-console-proxy-creation-failure

### ISSUE THREAD

**Issue by prashant2594** [apache/cloudstack#3573]
@rhtyd

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other
Other
##### COMPONENT NAME

~~~
UI,etc
~~~

##### CLOUDSTACK VERSION

ACS 4.11
~~~

~~~

##### CONFIGURATION

ACS 4.11 , KVM , NFS

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

I'm a newbie, and I've been trying to setup cloudstack with NFS and using KVM by following the official documents , everything goes smoothly, but when I get Dashboard , secondary storage is missing , i cant figure out where I'm going wrong.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
SSVM missing and even console proxy fails to start
~~~

**Comment by rhtyd** [comment]
@prashant2594 please share the logs, add a secondary storage and seed the correct version specific template.  Here's a quick tutorial on ubuntu/kvm: https://rohityadav.cloud/blog/cloudstack-kvm and you can also refer to http://docs.cloudstack.apache.org/en/4.11.3.0/

Kindly join the users ML and ask such questions there. What you're experiencing is a setup/install issue and not a bug or issue: http://cloudstack.apache.org/mailing-lists.html
