### ISSUE TITLE
Agent LB not working with disabled hosts

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#3581]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
KVM, Agent LB
~~~

##### CLOUDSTACK VERSION
~~~
4.11.2
~~~

##### CONFIGURATION
Enable agent LB, set up algorithm and host global setting

##### OS / ENVIRONMENT
Multiple management servers, multiple KVM hosts

##### SUMMARY
- Disabled KVM hosts do not get the 'host' configuration updated value.
- Disabled KVM hosts do not connect on agent restart

##### STEPS TO REPRODUCE
~~~
1)
- Disable a host
- Change the host global configuration value
- Verify the hosts list is not received by the host agent

2)
- Disable a host
- Restart host agent
~~~

##### EXPECTED RESULTS

~~~
1)
Host receives the updated hosts list

2)
Host is connected
~~~

##### ACTUAL RESULTS
~~~
1)
List is not sent to the host

2)
Host cannot connect to management server
~~~

**Comment by DaanHoogland** [comment]
@nvazquez Is this true if the agent happened to have been connected to the disabled MS or is this a generic fault, i.e. it never gets an update?

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/3617
