### ISSUE TITLE
[Improvement] Enter BIOS directly after VM restart

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#3583]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
VM lifeccle
~~~

##### CLOUDSTACK VERSION
~~~
4.14, 4.15
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It would be nice to have a mechanism to enter BOS directly without user intervention after a VM restarts. Currently, users can access BIOS hitting F2.

##### STEPS TO REPRODUCE

~~~
- Restart VM, selecting a new option to enter BIOS
~~~

##### EXPECTED RESULTS

~~~
BIOS displayed on console proxy
~~~

##### ACTUAL RESULTS

~~~
Hit F2 to enter BIOS on boot
~~~

**Comment by onitake** [comment]
Is something like this even feasible?
I'm sure it would at least be hypervisor dependent...

**Comment by nvazquez** [comment]
Hi @onitake, my intention was bringing up this idea as a nice to have, but honestly, I haven't gone into thinking how to do it rather than imagining use cases. I think the initial effort with this ticket will be evaluating if it is possible and how it can be achieved for different hypervisors.

**Comment by onitake** [comment]
Ah, I see.
I guess it might be useful, as there is often very little time to react at startup.

It seems like VMware does have an API for this: http://vmware.github.io/vsphere-automation-sdk-rest/6.5/operations/com/vmware/vcenter/vm/hardware/boot.get-operation.html
`value.enter_setup_mode`

**Comment by andrijapanicsb** [comment]
@nvazquez did we do some in-house work on this one - what's the idea, going to be in 4.14 or shall I move this to 4.15 milestone?

**Comment by rhtyd** [comment]
@nvazquez we've a boot into bios mode feature now, closing based on that.
