### ISSUE TITLE
Unexpected Error when creating VM Snapshot on Stopped VM

### ISSUE THREAD

**Issue by mihle** [apache/cloudstack#3584]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2 (from Shape Blue Repo)
~~~

##### OS / ENVIRONMENT

Xenserver 7.1 

##### SUMMARY

Cannot create VM Snapshot on stopped VM. Once the VM starts, the VM snapshot works.

This is occurring with Xen Hypervisor.  Unexpected error in the UI caused by an NPE from this line:

VMSnapshotManagerImpl.orchestrateCreateVMSnapshot
_jobMgr.marshallResultObject(new Long(snapshot.getId()))); <==NPE

From the Logs:
2019-09-05 17:58:01,652 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-79:ctx-e46e6eeb job-2563) (logid:e230b770) Unexpected exception while executing org.apache.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd
java.lang.RuntimeException: Unexpected exception
at com.cloud.vm.snapshot.VMSnapshotManagerImpl.createVMSnapshot(VMSnapshotManagerImpl.java:482)

...
Caused by: java.lang.NullPointerException
at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(VMSnapshotManagerImpl.java:1199)
at sun.reflect.GeneratedMethodAccessor772.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

##### STEPS TO REPRODUCE

~~~
Create default centos VM.  Stop VM.  Create VM Snapshot yields an Unexpected Error.  Starting the VM, you are able to create a VM Snapshot. 
~~~

##### EXPECTED RESULTS

~~~
VM Snapshot will be created.
~~~

##### ACTUAL RESULTS

Unexpected Error in the UI.

~~~

~~~

**Comment by luhaijiao** [comment]
Yes, we confirm this issue in our XenServer environment. 
And also noted the VM with snapshots is not allowed to resize volume or add disk.  And these are ACS's constraint but not XenServer.   Unlesss there's some special concern,  I think these constraints should be removed too.

**Comment by DaanHoogland** [comment]
@mihle @luhaijiao What is the use of a VM snapshot when a VM is stopped? The only tangible thing is the disk image as a stopped VM does not have memory state.
Isn't it completely appropriate to be not be able to take a VM snapshot (irrespective of the unclear error output)?

**Comment by mihle** [comment]
@DaanHoogland Thanks for your reply.  I disagree about the utility of creating VM snapshots from stopped VMs.  The customer wants to freeze a VM prior to running a windows update. 
 Being able to stop the VM ensures the disk state prior to snapshotting.  

At the least, the UI/Java code should handle the logic/error gracefully.  Also, I feel like this issue was introduced with refactoring done for 4.11.  I did not notice this issue in the 4.9 release.

**Comment by ustcweizhou** [comment]
this seems to be a critical issue.

**Comment by DaanHoogland** [comment]
I don't agree (obviously) with @weizhouapache (not sure if @ustcweizhou is still prefered in use?) but lets give researching it a place in next cycle.
In my personal opinion a stopped VM is nothing more than a set of volumes, and a machine difinition, there is no state to snapshot, but saving the machine definition might make sense.
At least the failure should be graceful with a sensible error or warning message.

**Comment by weizhouapache** [comment]
> I don't agree (obviously) with @weizhouapache (not sure if @ustcweizhou is still prefered in use?) but lets give researching it a place in next cycle.
> In my personal opinion a stopped VM is nothing more than a set of volumes, and a machine difinition, there is no state to snapshot, but saving the machine definition might make sense.
> At least the failure should be graceful with a sensible error or warning message.

@DaanHoogland the actions are different on kvm/xenserver/vmware.
for kvm, it is not possible to create vm snapshot on stopped vm so it is not an issue.

**Comment by nvazquez** [comment]
@DaanHoogland @weizhouapache @mihle is there any update on this?

**Comment by weizhouapache** [comment]
@nvazquez no update from me. it would be better to ask a xenserver expert to look into it.

**Comment by davidjumani** [comment]
Just tested it on the latest 4.15 on Xen 7.1
- Created a VM
- Stopped it
- Create VM snapshot
- Success !!
