### ISSUE TITLE
agent.log should not be rotated by logrotate

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#3585]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
cloudstack-agent
logrotate
~~~

##### CLOUDSTACK VERSION
~~~
4.12
~~~

##### OS / ENVIRONMENT
Ubuntu 16.04 / 18.04 hypervisor

##### SUMMARY
The /var/log/cloudstack/agent/agent.log is rotated by both log4j and logrotate and this causes the agent.log to be filled with binary (gzipped) data.

##### STEPS TO REPRODUCE
Try to 'grep' for some text in /var/log/cloudstack/agent/agent.log

**Comment by onitake** [comment]
Potentially related: #3443

There are still log files that are not generated by log4j.
If these are all migrated, external logrotate will no longer be necessary.

**Comment by DaanHoogland** [comment]
cherry-picked as 7e64945b8846d00c1d938084a83af3979b826cf1
