### ISSUE TITLE
Revert Ceph/RBD Snapshot issue

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#3590]
#### DESCRIPTION

The following exception shows that the parameter "path" had different data from what it was expected to have. I assume that it got the account id "2" instead of the image id:
```
2019-09-06 21:27:16,094 ERROR [resource.wrapper.LibvirtRevertSnapshotCommandWrapper](agentRequest-Handler-3:null)
(logid:9593f65a) Failed to connect to revert snapshot due to RBD exception:
com.ceph.rbd.RbdException: Failed to open image 2
        at com.ceph.rbd.Rbd.open(Rbd.java:243)
        at com.ceph.rbd.Rbd.open(Rbd.java:226)
        at
com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRevertSnapshotCommandWrapper.execute(LibvirtRevertSnapshotCommandWrapper.java:92)
        at
com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRevertSnapshotCommandWrapper.execute(LibvirtRevertSnapshotCommandWrapper.java:49)
        at
com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at
com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1476)
        at com.cloud.agent.Agent.processRequest(Agent.java:640)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1053)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The parameter [snapshotRelPath = snapshot.getPath()](https://github.com/apache/cloudstack/blob/61b8b779137739bb5b890f48c5164085075d0286/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/wrapper/LibvirtRevertSnapshotCommandWrapper.java#L75) is a critical piece of code that can definitely break the rollback execution flow if its content is not the expected. My tests had pointed for a pattern but the reported issue points to other possibilities that were not the expected.

I will be working to reproduce this error. Should be soon proposing a fix that will ensure a stable Ceph rollback/revert execution. The fix will aim **CloudStack 4.13.1.0**.

##### ISSUE TYPE

 * Bug Report

**Comment by DaanHoogland** [comment]
merged on 4.13 branch. @GabrielBrascher @rhtyd please reopen if the fixes/reverts aren't good enough.
