### ISSUE TITLE
Ensure VM deletion when default nic is removed does not cause stale entries in DB and router

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3592]
When a VM is destroyed with its default nic deleted first, a NPE fix was added to simply ignore reprocessing of the dhcp/dns rule. Check and fix in case the VM deletion with the default nic removed causes stale entries in the DB or the router. Also explore if removal of the default nic at the end is the safest option.

(Reference, default NIC NPE was fixed in #3547)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3.0, 4.11.2.0, 4.13.0.0
~~~

**Comment by Doni7722** [comment]
@rhtyd We have CloudStack 4.11.3 running and we can't expunge VM's which have more than 1 NIC and the default NIC is the first one. What I saw is, that CS will delete the default NIC first and then can't continue as he is looking for the default NIC (which was just deleted). Does this Issue handel this issue or should I open a new one?

**Comment by DaanHoogland** [comment]
@Spaceman1984 can you verify this is an issue in latest master?

**Comment by Spaceman1984** [comment]
Not at the moment @DaanHoogland, I will only be available from the 7th of December.

**Comment by Spaceman1984** [comment]
I have tested 4.13 and master, 

I created a few networks and instances. 
I attached the instances to multiple networks.
For some instances, I changed the default nic and others I left the default nic as is.
I destroyed and expunged all the instances and in all cases, the DB entries in the nics table were updated and the /var/lib/misc/dnsmasq.leases and hosts files in the router were updated successfully, 

There doesn't seem to be an issue here.

I did observe that the dnsmasq.leases file doesn't get populated every time an instance is created, not sure if that is a bug.

**Comment by DaanHoogland** [comment]
@Spaceman1984 (cc @rhtyd) I think it is a bug, if the leases file is not updated for new VMs, but not the one reported here. Did you see that behaviour on both 4.13 and master?

**Comment by Spaceman1984** [comment]
The behaviour is the same for master and 4.13, but I did some more testing and I suspect it is down to config outside of Cloudstack. I have 3 virtual ESXI hosts and the VMs running on the same host as the VR are getting leases, but the ones running on other hosts are not getting leases.

I would have to test using a DVswtich to be sure, but this is what I am suspecting.

**Comment by rhtyd** [comment]
The leases file is now fully generated on VR cleanup+restart. Closing on Darrin's remark.
