### ISSUE TITLE
Not able to call scripts with get diagnostics

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3593]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, get diagnostics 
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### SUMMARY

get diagnostics fails to execute a script when called. I've setup a script that would create some files locally on the VR in the /opt/cloud/bin dir, but when calling it via the api and UI with [script]
it does not run. 
related to #3350

**Comment by borisstoyanov** [comment]
ping @anuragaw

**Comment by anuragaw** [comment]
Can you see if the router was patched with the scripts that is expected to run @borisstoyanov ? I mean if the VR was created and then you upgraded to this feature, the older VRs could be missing that script.

**Comment by borisstoyanov** [comment]
Yes, the env is fresh installed and router should have these changes in it @anuragaw

**Comment by anuragaw** [comment]
Looked at it today but doesn't repro. I'll sync later to get exact steps.

**Comment by andrijapanicsb** [comment]
is this one still valid @borisstoyanov @anuragaw ?

**Comment by borisstoyanov** [comment]
seems to be fixed but will close when PR is merged #3350

**Comment by anuragaw** [comment]
I've fixed this as part of the PR #3350 and @borisstoyanov has verified. We can close this issue as the PR is open.

**Comment by DaanHoogland** [comment]
@anuragaw I'll add a "Fixes" tag in the PR so this will auto close. but let's not close issues untill they are merged, because an abandoned/closed PR will hide the fact that the issue was there at all.
