### ISSUE TITLE
Support for KVM dynamic scaling

### ISSUE THREAD

**Issue by kiwiflyer** [apache/cloudstack#3594]
Support the ability to dynamically scale or change multiple config components in a libvirt configuration.

Initial support for vCPU, Memory, bandwidth limits, IOP min,max and burt limits.

@rhtyd @skattoju4 @ustcweizhou @PaulAngus @rafaelweingartner  @nathanejohnson

**Comment by svenvogel** [comment]
@kiwiflyer is that call for a feature request?

**Comment by skattoju4** [comment]
> @kiwiflyer is that call for a feature request?

@svenvogel we talked about at CCC and did a quick test using virsh to see whats possible. wondering if anyone else in the community has looked at this.. looking for contributions.

**Comment by nvazquez** [comment]
Hi @skattoju4, the PR I submitted is work in progress, doing it incrementally while testing possible approaches. Feel free to propose/refactor the approach in the PR

**Comment by sureshanaparti** [comment]
ping @nvazquez @kiwiflyer can you confirm whether this issue is fixed with #4878 or not.
