### ISSUE TITLE
Using custom protocol in ACL rule, breaks ACL

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3602]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
mgmt, ACL rules handling
~~~

##### CLOUDSTACK VERSION

~~~
tested 4.11.2.0, 4.13.0.0
~~~

##### CONFIGURATION

VPC, custom ACL with a few (ingress) rules applied to a network

##### OS / ENVIRONMENT

NA

##### SUMMARY

Adding an ACL rule with a custom **protocol number** (i.e. protocol 50, 51 or any other) - will break ACL/iptables chain inside the VR in following way
- all the rules BEFORE this one (rule number lower than the custom protocol rule number) will get properly applied
- this specific rule (custom protocol number) will NOT be injected at all inside the VR (seems it is not sent by mgmt server to the VR ) 
- all the rules that come AFTER this one, will be injected only AFTER the default DENY rule is injected

##### STEPS TO REPRODUCE

Create a VPC with custom ACL on the network i.e.:
![image](https://user-images.githubusercontent.com/45762285/65315803-06ad2300-db99-11e9-980b-184eab9468e0.png)

Confirm rules are properly applied inside the VR:
```
root@r-47-VM:~# iptables-save | grep INBOUND_eth2
:ACL_INBOUND_eth2 - [0:0]
-A FORWARD -d 10.10.10.0/24 -o eth2 -j ACL_INBOUND_eth2
-A ACL_INBOUND_eth2 -d 225.0.0.50/32 -j ACCEPT
-A ACL_INBOUND_eth2 -d 224.0.0.18/32 -j ACCEPT
-A ACL_INBOUND_eth2 -s 6.6.6.6/32 -p tcp -m tcp --dport 666 -j ACCEPT
-A ACL_INBOUND_eth2 -s 2.2.2.2/32 -p tcp -m tcp --dport 222 -j ACCEPT
-A ACL_INBOUND_eth2 -s 3.3.3.3/32 -p tcp -m tcp --dport 333 -j ACCEPT
-A ACL_INBOUND_eth2 -j DROP
```

Now, add a custom rule in the middle of the rules list (rule number 31 in the example below), as follows:

![image](https://user-images.githubusercontent.com/45762285/65315955-4d9b1880-db99-11e9-8f51-56b12b6fb087.png)

Again examine the rules in the VR:

```
root@r-47-VM:~# iptables-save | grep INBOUND_eth2
:ACL_INBOUND_eth2 - [0:0]
-A FORWARD -d 10.10.10.0/24 -o eth2 -j ACL_INBOUND_eth2
-A ACL_INBOUND_eth2 -d 225.0.0.50/32 -j ACCEPT
-A ACL_INBOUND_eth2 -d 224.0.0.18/32 -j ACCEPT
-A ACL_INBOUND_eth2 -s 6.6.6.6/32 -p tcp -m tcp --dport 666 -j ACCEPT
-A ACL_INBOUND_eth2 -s 2.2.2.2/32 -p tcp -m tcp --dport 222 -j ACCEPT
-A ACL_INBOUND_eth2 -j DROP
-A ACL_INBOUND_eth2 -s 3.3.3.3/32 -p tcp -m tcp --dport 333 -j ACCEPT
```

Notice that:
- the rule for protocol 50 is missing (not even mentioned in the /var/log/cloud.log, while inside the management.log there is simply a "success" adding a rule - i.e. no exceptions)
- the default DENY rule is applied in the middle of the chain
- other rules (the ones that should come after the custom protocol number rule) are added later, below the DENY rule (so they never get evaluated)

##### EXPECTED RESULTS

~~~
A working ACL.
~~~

##### ACTUAL RESULTS

~~~
Read the "STEPS TO REPRODUCE" section.
~~~

**Comment by onitake** [comment]
For reference: IP protocol numbers 50 and 51 are for IPsec in transport mode. They are useful if IPsec endpoints are operated behind the router and tunnel mode (UDP port 500) cannot be used.

**Comment by andrijapanicsb** [comment]
_(I tested with protocol number 6 (TCP) and saw the same behaviour)_

**Comment by weizhouapache** [comment]
@andrijapanicsb 
have you fixed this issue? If not, I will take it. we have a fix for it.

**Comment by andrijapanicsb** [comment]
not yet @weizhouapache, thx in advance!

**Comment by ustcweizhou** [comment]
@andrijapanicsb I have created a PR #3678 for this issue.
Please review/test it, thanks !
