### ISSUE TITLE
[Improvement] force VM shutdown when destroying VM

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3626]
* Improvement Request

When VM destroy is called (or at least whe the "expunge=true"), make sure to ask hypervisor for the forcefull stop of VM (quick!) and not regular guest OS shutdown (which can take time...)

Makes destroying VM faster.

**Comment by cl-k-takahashi** [comment]
Setting `vm.destroy.forcestop` to `true` in Global Settings may do.

**Comment by andrijapanicsb** [comment]
Well, that works as well :) Closing this one.
