### ISSUE TITLE
Unable to add host to cloudstack UI

### ISSUE THREAD

**Issue by gngusen** [apache/cloudstack#3629]
Its great that I found experts in cloudstack. May you please help me I am unable to add the host to the management server
The management server and the host are separate machines in the same network with a private Ip address. The management server also serves as the storage, is installed correctly and can be obtained in the UI but unable to add host
Agent and libvirtd are running properly
Management and mariadb are also running actively
But the storage and host can not be added to the management server?

Help please? @digitalgust @rhtyd

These are the logs
![image](https://user-images.githubusercontent.com/49669122/66487684-738b4d00-eab5-11e9-9cd3-25454d0b0dfc.png)
![image](https://user-images.githubusercontent.com/49669122/66487782-9289df00-eab5-11e9-9d03-2c9ac4f43d34.png)
![image](https://user-images.githubusercontent.com/49669122/66487886-c49b4100-eab5-11e9-8346-2333215f7776.png)

_Originally posted by @gngusen in https://github.com/apache/cloudstack/issues/3509#issuecomment-539911230_

**Comment by ustcweizhou** [comment]
@gngusen could you post the logs in /var/log/cloudstack/agent/setup.log on host ? and your cloudstack version, os /version, etc

**Comment by rhtyd** [comment]
@gngusen sorry I missed this issue, can you test against latest 4.14 release or master?

**Comment by DaanHoogland** [comment]
@gngusen , as this is really old and standard functionality I am closing this. Can you seek help at users@cloudstack.apache.org if this is still an issue for you, please?
