### ISSUE TITLE
GUI doesn't show "default" label next to networks in Add Instance wizard

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3633]
* Bug Report

- Master branch

Word "Default" in front of the radio buttons is missing.

Tested on Chrome/Firefox (cleared cache)
 
![image](https://user-images.githubusercontent.com/45762285/66570286-9842fb80-eb6d-11e9-8163-8905b458dbfc.png)

**Comment by andrijapanicsb** [comment]
@anuragaw if you could have a look, some time please?

Should be like this below:

![image](https://user-images.githubusercontent.com/45762285/66570467-eeb03a00-eb6d-11e9-9928-7e405c3e57b5.png)

**Comment by anuragaw** [comment]
Sure @andrijapanicsb

**Comment by andrijapanicsb** [comment]
ping @anuragaw @DaanHoogland - hopefully, a quick one - still present in current master

**Comment by Spaceman1984** [comment]
I'll take a look
