### ISSUE TITLE
fresh install 4.11.3 systemvm template fails to be recognized during upgrade

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3647]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Upgrade
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3
~~~

##### SUMMARY

system vm template fails to get recognized as valid and we get an upgrade failure due to that, if the user registers a 4.11.3 template with the name as per instruction it works, but that's not needed since it's the same template. 

##### STEPS TO REPRODUCE

~~~
Clean install 4.11.3
Upgrade to 4.13 without registering a systemvm template
~~~

##### EXPECTED RESULTS

~~~
default systemvm to be user 
~~~

##### ACTUAL RESULTS

~~~
Upgrade error of missing template
~~~

**Comment by DaanHoogland** [comment]
@borisstoyanov as no one else reported this, is this an incident or a consistent error?

Note: i saw no/missing schema-xxxtoyyy.sql files for the upgrade in any version branch

**Comment by borisstoyanov** [comment]
Since it does not have the proper name of systemvm-temaplate-[hypervisor]-4.11.3 in it, but just SystemVMTemplate-[hypervisor]. Cloudstack DB upgrade from 4.11.3 to 4.13 fails as it cannot find the 4.11.3 name. It's consistent

**Comment by rhtyd** [comment]
@borisstoyanov can you check https://github.com/apache/cloudstack-documentation/pull/87, and advise what else needs to be done. I think the issue can be closed now.

**Comment by borisstoyanov** [comment]
I think this one was fixed right away by @andrijapanicsb he updated documentation.

**Comment by andrijapanicsb** [comment]
Correct, there is explicit note in upgrade doc with warning to register 4.11.3 template even if user is having one from before.

closing this one.
