### ISSUE TITLE
improve logging in vmware storage processor

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3652]
VolumeOrchestrator gives a cryptic message when copy from primary to secondary failes on Vmware during migrate volume.

```
Failed to migrate volumecom.cloud.exception.StorageUnavailableException: Resource [StoragePool:1446] is unreachable: Migrate volume failed: copy volume from primary to secondary failed due to exception: Exception: java.lang.NullPointerExceptionMessage: null
```
there is a lot of information in the message about where things went wrong but not about what is wrong. The NPE is not locatable from the message or the accompanyting stacktrace.

in ```com.cloud.storage.resource.VmwareStorageProcessor#copyVolumeFromPrimaryToSecondary``` , diagnostic output should be improved.

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Vmware Storage
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@nvazquez @harikrishna-patnala you did a lot of refactoring on vmware lately, Did you encounter this as well and do you have any opinion on how to improve?

**Comment by DaanHoogland** [comment]
marking this as minor as no-one really complains about it, or is giving it any attention.

**Comment by nvazquez** [comment]
@DaanHoogland PR #5353 improves that specific class, think it is good or needs further logging improvement?

**Comment by DaanHoogland** [comment]
@nvazquez do you dare to merge 5353 in before 4.16?

**Comment by nvazquez** [comment]
No @DaanHoogland, the PR has been recently fixed as there were many smoke tests failures so will need further review and tests
