### ISSUE TITLE
Instances status out of sync with hypervisor VM's

### ISSUE THREAD

**Issue by AndreaGHG** [apache/cloudstack#3664]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloudstack Manager
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.11.3.0, VMWare 6.5 as hypervisor.
~~~

##### CONFIGURATION

1 Cloudstack management server, 1 dedicated DB server with MariaDB 5.5, 3 node VMWare VSphere 6.5 cluster. Cloudstack advanced networking setup.

##### OS / ENVIRONMENT

Management server installed on CentOS 7.

##### SUMMARY

Often it happens that Instances status goes out of sync with VMWare virtual machines status.

I startup one instance, it boots up correctly and goes to the "Running" state. After some time (hours, days, months, there is not a defined amount of time) it appears in the "Stopped" status on the manager web interface (in the "instances" section) without any user interaction, but if I look in the VSphere interface the virtual machine is still running fine and I can connect to its console.

This happens with randomly on instances, both with Windows and Linux VMs.

VSphere cluster has DRS enabled, I have tried to turn DRS off but this behavior doesn't change.

##### STEPS TO REPRODUCE

Setup many instances, turn them on and wait. After an undefined amount of time one or more instances could appears stopped in Cloudstack management web interface but they are still powered on and running for VMWare VSphere.

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by PaulAngus** [comment]
Hi Andrea,

You mention that you had turned DRS off, had you still performed migrations on the effected VMs via vCenter, rather than via CloudStack?

thanks

**Comment by AndreaGHG** [comment]
Hi Paul,

I had not performed any migrations via vCenter, every operation was made via CloudStack.

Thanks!

**Comment by DaanHoogland** [comment]
@AndreaGHG there are some improvements with respect to status processing in the newer versions. Can you check if your issue is still happening in newer versions? (btw The fixes pertain to DRS out of bounds migrations so I wonder what could happen with DRS turned off)

**Comment by DaanHoogland** [comment]
@AndreaGHG as 4.15 is out and you didn't reply I'm assuming this can be closed, please re-open if i'm in err
