### ISSUE TITLE
Update SystemVM Template for 4.14+

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3667]
Create a new sytemvmtemplate towards the next release (4.14 or above) with latest strongswan (https://github.com/apache/cloudstack/issues/3138) and other packages, including java11 JRE.

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
VR/systemvmtemplate
~~~

**Comment by andrijapanicsb** [comment]
Check also #3654 - Marco specified with which StrongSwan versions (from Debian10 repo) there are no problems.

**Comment by GabrielBrascher** [comment]
@rhtyd considering that Python 2.7 will not be maintained past 2020 (will be retired on 1st January, 2020) next template should also have python3 installed to support python3 scripts.

**Comment by rhtyd** [comment]
Sure @GabrielBrascher, we can install both python2 and python3 in the next systemvmtemplates (with python2 as default) so scripts can specify which python version they want.

**Comment by weizhouapache** [comment]
@rhtyd 
can we upgrade haproxy from 1.7.5 (in 4.11/4.13) to 1.8.X in new systemvm template ?
it supports http2

**Comment by rhtyd** [comment]
@ustcweizhou yes, as long as the distribution (Debian 10) supports that version and moving to that version won't add regression or massive code changes.
