### ISSUE TITLE
Adding ACL rules for one subnet in a VPC stops traffic to a VM with a Public IP in a second subnet

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3670]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.9
~~~

##### SUMMARY

Whenever adding ACL rules for subnet 1 in a VPC, the VM that has Public IP in the Subnet 2 becomes unreachable. To solve the problem we need to restart the subnet 2 with clean up option.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@PaulAngus cc @andrijapanicsb - have we tested if this affects 4.11, 4.13? If not I can run a test.

**Comment by weizhouapache** [comment]
There are many commits in master to fix issues with multiple public subnets for isolated network/vpc.
it would be better to upgrade to 4.13

**Comment by andrijapanicsb** [comment]
I believe this problem was local to 4.9 and @PaulAngus had the idea to close it (there's no internal ticket), so I say this can be closed
