### ISSUE TITLE
Stop "mgmt server needs restart" message on global setting that doesn't require it

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3683]
Currently, when we change ANY global setting, there is a popup window saying "Please restart your management server(s) for your new settings to take effect"

But on i.e. 4.11 release, Out of  589 different settings, 188 of those do not require mgmt server restart. (SELECT * FROM cloud.configuration WHERE is_dynamic=1;)

Would be nice to stop that false popup for those global settings that do not require mgmt server restart.

**Comment by weizhouapache** [comment]
@andrijapanicsb we have a fix for this issue
I will port it to 4.13 and create a pull request.

**Comment by andrijapanicsb** [comment]
thanks (as usual) @weizhouapache !

**Comment by weizhouapache** [comment]
@andrijapanicsb 
I have created the pull request #3729 
could you please test it when you have time ? thanks !
