### ISSUE TITLE
With Chrome you cannot edit domain level settings 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3684]
Chrome version:
Version 78.0.3904.97 (Official Build) (64-bit)
Automatically update Chrome for all users Learn more

![Screenshot 2019-11-14 at 10 32 45](https://user-images.githubusercontent.com/13551960/68839797-1b55f500-06ca-11ea-97d4-e10fa64ecddf.png)

Probably a scroller is needed

**Comment by rhtyd** [comment]
This is allowed in Primate, I'm not for old UI. Closing on this remark and request that we should we Primate from hereon. Thanks.
