### ISSUE TITLE
Domain level ldap server configuration is not displayed

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3686]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### SUMMARY

Configure LDAP at a domain level and you won't be able to see this configuration anywhere in the UI, at Global Setting -> LDAP it's being displayed only root domain level configurations

Looks like list api is dependent on the domainid, and if no domain id is passed it ignores the results.

```
(localcloud) SBCM5> > add ldapconfiguration hostname=10.1.2.5 port=389 domainid=7cc39a93-a6a7-423c-b150-50f63b8765d6
{
  "LdapAddConfiguration": {
    "domainid": "7cc39a93-a6a7-423c-b150-50f63b8765d6",
    "hostname": "10.1.2.5",
    "port": 389
  }
}
(localcloud) SBCM5> > list ldapconfigurations
(localcloud) SBCM5> > list ldapconfigurations domainid=7cc39a93-a6a7-423c-b150-50f63b8765d6
{
  "LdapConfiguration": [
    {
      "domainid": "7cc39a93-a6a7-423c-b150-50f63b8765d6",
      "hostname": "10.1.2.5",
      "port": 389
    }
  ],
  "count": 1
}

```

![Uploading Screenshot 2019-11-14 at 12.52.50.png…]()

##### EXPECTED RESULTS

~~~
As an admin I would like to see all level of configurations
~~~

##### ACTUAL RESULTS

~~~
Not being listed
~~~

**Comment by weizhouapache** [comment]
@borisstoyanov listall=true ?

**Comment by borisstoyanov** [comment]
I believe there's not such option: 

```
(localcloud) SBCM5> > list ldapusers listtype=
(localcloud) SBCM5> > list ldapusers listtype=all
(localcloud) SBCM5> > list ldapusers
domainid=   filter=     keyword=    listtype=   page=       pagesize=   userfilter=
```

**Comment by DaanHoogland** [comment]
Indeed @weizhouapache This is an ommision in the UI. Not my prio now, but I will look when I have time.

**Comment by rhtyd** [comment]
@davidjumani @DaanHoogland can you check against latest master/primate?

**Comment by davidjumani** [comment]
This has been added in primate
![Screenshot from 2020-08-12 16-53-33](https://user-images.githubusercontent.com/8244774/90009811-62eec900-dcbc-11ea-8a4e-f0b9eea3110a.png)

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4164
