### ISSUE TITLE
When importing a multi-disk OVA some options are missing in appliances created from it

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3690]
There missing "options" in appliances in Vmware - a direct import in vcenter displays more options than the CS instance wizard.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMWARE
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@DaanHoogland can you review and close this as things are addressed in depth in #4250

**Comment by DaanHoogland** [comment]
mostly done, will open a new issue if anything remains
