### ISSUE TITLE
Name and Description fields of Projects in UI is too short

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#3697]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA

##### STEPS TO REPRODUCE

Text field is unnecessarily short causing truncation at worst
PC
![image](https://user-images.githubusercontent.com/4810220/69263316-f88d7a00-0bbc-11ea-8b3d-9c01132b7aa6.png)

MAC
![image](https://user-images.githubusercontent.com/4810220/69263333-017e4b80-0bbd-11ea-88f5-5cccae35d09c.png)

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/3703
