### ISSUE TITLE
update default user vm template to later version

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3700]
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
Templates
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### SUMMARY

Currently cloudstack uses CentOS 5.5 as default user VM template, can we update that to latest CentOS 7 or even 8 versions if possible?

**Comment by andrijapanicsb** [comment]
Not sure we have CentOS8 mapping/guest OS for all hypervisors - but sounds like a very valid proposition (that I had in my head last few days as well). Let me see if I have time to do something around that.

**Comment by borisstoyanov** [comment]
is this being fixed in #3712 right?

**Comment by andrijapanicsb** [comment]
yep

**Comment by andrijapanicsb** [comment]
@borisstoyanov is using CentOS8 going to break any Marvin tests (Inside CentOS8 - ssh still works, and all  basic network utils available inside, including "old" ifconfig/route etc - I'm talking about #3712 ) -

**Comment by DaanHoogland** [comment]
@borisroman @andrijapanicsb does it make sense to let the operator/user decide on the default usertemplate by prioviding a url and guestos type at install time? or through an API?

**Comment by andrijapanicsb** [comment]
I don't think so @DaanHoogland  - the more "freedom" you give to the user, the more issues you might face.
We need to see what is the "newest" guest OS, supported by the OLDEST hypervisor we officially support in ACS - we can't use a newer OS than that (and we should not be using older, like the current one).
Remeber - this template is barely to validate/test basic ACS functionality and if the deployment is successful (can deploy a VM in a clean/new ACS installation)

One thing to notice is that we also run Marvin tests using this default template, so.... need to take care on steps forward.

**Comment by rohityadavcloud** [comment]
We should bring this discussion on dev@, which I see has been tried before. The purpose of the default template is just to cloudstack in a new installation it works. With EL9 around, it may make sense to discuss it again on dev@. I'll start that discussion but close this 2yr+ old ticket.
