### ISSUE TITLE
Remove dhcp/dns configuration from VR, when VM is being DETACHED from a network

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3706]
As part of the additional cleanup discussed in https://github.com/apache/cloudstack/pull/3627,
we also need to remove all  DHCP/DNS config data (and the active lease) from VR when VM is being DETACHED from a network (any network)

Reason: we need to do the same dhcp/dns config cleanup (that we otherwise do only when VM is being expunged) when we detach network from a VM - since after VM is detached, its reference(s) to its previous network(s) is lost and will never be later cleaned up (dhcp/dns config) when VM is destroyed/expunged later.

Multiple consequences (with multihomed VMs) can be seen if this is not fixed.

@weizhouapache @rhtyd

**Comment by DaanHoogland** [comment]
merged in 4.13 and fwd-merged
