### ISSUE TITLE
Issue in GUI when adding instances

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3709]
##### ISSUE TYPE

 * Bug Report

When adding an instance via GUI, one of the screens is empty, issues in some JS (visible via browser developer tools)

Video here: https://screencast-o-matic.com/watch/cqX0lwUyZC

![image](https://user-images.githubusercontent.com/45762285/69478730-0d088700-0df6-11ea-923d-bfec2c188744.png)

**Comment by DaanHoogland** [comment]
@andrijapanicsb is this broken on master?

**Comment by andrijapanicsb** [comment]
Good question... I could NOT briefly reproduce it - will update here, since I'm doing lots of testing these days...

**Comment by andrijapanicsb** [comment]
Seems not present on master (any more) - closing.
