### ISSUE TITLE
GUI show job never completing due to JS issues

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3711]
##### ISSUE TYPE

 * Bug Report

CloudStack 4.13 (probably also master?)

When i.e. creating a template from a root volume, the job completes fine, but the job results are not parsed properly in the GUI - and the circle is spinning indefinitely

![image](https://user-images.githubusercontent.com/45762285/69501301-08ca8f80-0f04-11ea-89db-2cb435ca566a.png)

**Comment by rhtyd** [comment]
Per https://github.com/apache/cloudstack/pull/4005 fixed it
