### ISSUE TITLE
creating template from snapshot does not work from snapshot list 

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3716]
If you go to STORAGE (main section menu on the left), then select VOLUMES from the dropdown list, select a particular volume, than see snapshots, then select a snaphost - then clicking on button WILL work fine and popup window is show as follows:
![image](https://user-images.githubusercontent.com/2486961/69534212-9dbba000-0f79-11ea-9650-647a76efae49.png)

But if you go to STORAGE (main section menu on the left), then select SNAPSHOTS from the dropdown list and find one and click the button - then an exception happens in the javascript code: 
![image](https://user-images.githubusercontent.com/2486961/69534149-811f6800-0f79-11ea-82cd-fa9016e72cfa.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
during the latest update of jquery the createTemplate functions for volumes and snapshots were unified into a shared function without fully abstracting out the entities 'volumes' and 'snapshots'
We can duplicate the function as a quick-fix or put effort into the abstraction. I am choosing the first as the current UI is to be phased out.
@andrijapanicsb @rhtyd @rafaelweingartner

**Comment by andrijapanicsb** [comment]
sounds good @DaanHoogland 

I've also seen (probably NOT related, but to mention...) that when you register the template from URL, previously there was a spinning circle just until the template was added to the DB - then you can actually click on it and see it being downloaded etc. In current master when you register the template, the circle is spinning all the time, until the template is actually completely downloaded, which is insane. - not sure if that's also a quick fix...

**Comment by DaanHoogland** [comment]
actually @andrijapanicsb half an hour extra search gave me a location to add a conditional, testing is probably going to be more effort.
What you are saying seems a different location in the code. i'll keep it in mind. Did you create an issue for that already?

**Comment by andrijapanicsb** [comment]
No @DaanHoogland, I was lazy...
