### ISSUE TITLE
Host HA is configre fail

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3717]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Host Ha 
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
4.11.3
4.12
4.13
~~~

##### SUMMARY

When the ha.tag tag in the global configuration is not the first tag in the host tag, the host will display HA Enabled=No

HOST HA will fail

##### STEPS TO REPRODUCE

~~~
1.configure Global Settings the host.ha=ha
2.Restart cloudstack management service
3.Log in to ACS UI and set tag "test, ha" of host
4.View host ha status




~~~

##### EXPECTED RESULTS

~~~
Host HA Enable =Yes
~~~

##### ACTUAL RESULTS

~~~
Host HA Enable =No

ps: After configure host ha to "ha, test", host ha will display yes. And ha function test is normal
~~~

**Comment by DaanHoogland** [comment]
seems related to a multi-tag issue with had. Can you test this with a recent (pre)release version, @div8cn ?

**Comment by DaanHoogland** [comment]
@div8cn is this still an issue in 4.15?

**Comment by DaanHoogland** [comment]
ping @div8cn

**Comment by div8cn** [comment]
I reproduced this bug in 4.15.0.0 + Ubuntu + KVM + CEPH


global.ha.tag=HCMHA
hosttags="aabb,ccdd,HCMHA"

the listhostsresponse:


{
listhostsresponse: {
count: 1,
host: [
{
id: "ebbdfa50-0d36-4155-9561-ec02e337b807",
name: "nodeb",
state: "Up",
disconnected: "2021-02-03T23:00:13+0800",
type: "Routing",
ipaddress: "10.228.18.129",
zoneid: "0dfcc491-25c0-4527-ab99-bf9c5916ad50",
zonename: "DEV2.4",
podid: "302d1e52-464d-4a6c-b0d4-48d0f86b73eb",
podname: "SP01",
version: "4.15.0.0",
hypervisor: "KVM",
cpusockets: 2,
cpunumber: 32,
cpuspeed: 3000,
cpuallocated: "0%",
cpuallocatedvalue: 0,
cpuallocatedpercentage: "0%",
cpuallocatedwithoverprovisioning: "0%",
cpuused: "0.31%",
cpuwithoverprovisioning: "96000",
cpuloadaverage: 0.06,
networkkbsread: 1019,
networkkbswrite: 49,
memorytotal: 133757448192,
memorywithoverprovisioning: "133757452288",
memoryallocated: 0,
memoryallocatedpercentage: "0%",
memoryallocatedbytes: 0,
memoryused: 1489330176,
capabilities: "hvm,snapshot",
lastpinged: "1970-01-19T13:30:27+0800",
managementserverid: "5ee3964d-af8b-4732-be1f-edff9e4049e6",
clusterid: "f1775574-97de-4d03-a038-fd9a0f632efb",
clustername: "CL01",
clustertype: "CloudManaged",
islocalstorageactive: false,
created: "2021-02-01T21:04:11+0800",
events: "AgentDisconnected; ManagementServerDown; StartAgentRebalance; Ping; Remove; AgentConnected; HostDown; ShutdownRequested; PingTimeout",
hosttags: "aabb,ccdd,HCMHA",
hostha: {
haenable: false,
hastate: "Disabled"
},
outofbandmanagement: {
powerstate: "Disabled",
enabled: false
},
resourcestate: "Enabled",
hahost: false,
details: {
Host.OS.Version: "20.04",
Host.CPU.ModelName: "Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz",
Host.System.PhysicalMemory: "131072",
Host.OS.Kernel.Version: "5.4.0-65-generic",
com.cloud.network.Networks.RouterPrivateIpStrategy: "HostLocal",
Host.System.ProductName: "SYS-6029TP-HTR",
secured: "true",
Host.OS: "Ubuntu",
Host.System.Manufacturer: "Supermicro"
},
ueficapability: false
}
]
}
}

**Comment by shwstppr** [comment]
@div8cn @weizhouapache I checked the behaviour in the code and currently we set only `hahost` parameter in the API response to `true` when a matching tag is specified in global config `ha.tag`.
Currently, API was failing to report the correct value when multiple tags are being set for a host. I've raised a PR to fix that. https://github.com/apache/cloudstack/pull/4789

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4789
