### ISSUE TITLE
VMware: SystemVMs not cleared after forcing them to stop

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3719]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Occupy a host with a few VMs and make sure both system vms are there as well

```
MariaDB [cloud]> select name,state,removed from vm_instance where type = 'SecondaryStorageVm' or type ='ConsoleProxy';
+---------+-----------+---------------------+
| name    | state     | removed             |
+---------+-----------+---------------------+
| s-1-VM  | Destroyed | 2019-11-21 09:37:59 |
| v-2-VM  | Destroyed | 2019-11-21 09:48:16 |
| s-28-VM | Destroyed | 2019-11-21 09:38:58 |
| s-29-VM | Destroyed | 2019-11-21 09:45:29 |
| s-30-VM | Destroyed | 2019-11-21 09:46:29 |
| s-31-VM | Destroyed | 2019-11-21 09:47:29 |
| s-32-VM | Destroyed | 2019-11-21 11:50:29 |
| v-33-VM | Destroyed | 2019-11-21 11:44:56 |
| v-39-VM | Destroyed | 2019-11-21 11:45:59 |
| v-40-VM | Destroyed | 2019-11-21 11:50:29 |
| v-41-VM | Running   | NULL                |
| s-42-VM | Destroyed | 2019-11-21 11:51:29 |
| s-43-VM | Destroyed | 2019-11-21 11:52:29 |
| s-44-VM | Destroyed | 2019-11-21 11:53:29 |
| s-45-VM | Destroyed | 2019-11-21 11:54:29 |
| s-46-VM | Destroyed | 2019-11-21 11:55:29 |
| s-47-VM | Destroyed | 2019-11-21 11:56:29 |
| s-48-VM | Running   | NULL                |
+---------+-----------+---------------------+
18 rows in set (0.00 sec)
```

![Screenshot 2019-11-21 at 13 41 26](https://user-images.githubusercontent.com/13551960/69634706-75a46d80-105b-11ea-963a-3d371a5df3e7.png)

notice how s-29, s-32, 40 are still part of the list but according to cloudstack DB they are removed

##### STEPS TO REPRODUCE

~~~
Make sure the host is the last one in the cluster and set it to maintenance

Observe that all VMs are shut down

Cancel maintenance and observe new system vms will be created

Login to vCenter and see that old system vms are not destroyed
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@borisstoyanov do still see this with latest master?

**Comment by DaanHoogland** [comment]
I can confirm this still happens in 4.15. I wonder if it is on purpose as we are talking about the last host in the zone, might it be thought to be usefull to keep the images of the svms around?
i think we can call this valid and setting it to 4.14.1 for now (we might need to postpone ...

**Comment by rhtyd** [comment]
Edge case, not critical issue moved to next milestone.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4644
