### ISSUE TITLE
Log output improvement when cluster resources are insufficient

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3734]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
LOG
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
4.11.3
4.12
4.13
~~~

##### SUMMARY

During deploy instance, if the CPU utilization rate of the cluster exceeds that of cluster.cpu.allocated.capacity.disabledthhreshold or cluster.memory.allocated.capacity.disabledthhreshold. Output in log

Cannot allocate cluster list [4] for vm creation since their allocated percentage crosses the disable capacity threshold defined at each cluster/ at global value for capacity Type : 0, skipping these clusters

Change capacity type: 0 to capacity type: CPU, or capacity type: ram;

https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/deploy/FirstFitPlanner.java#L355

**Comment by DaanHoogland** [comment]
@div8cn can you check if PR #5762 met your requirements and prozaically describe remaining issues, please?

**Comment by sureshanaparti** [comment]
> @div8cn can you check if PR #5762 met your requirements and prozaically describe remaining issues, please?

Hi @div8cn please confirm, thanks.

**Comment by DaanHoogland** [comment]
closing this @div8cn , please reopen or create a new one, would you desire more improvements.
