### ISSUE TITLE
deleteTemplate performs forced deletion by default

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3735]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
ALL VERSION
~~~

##### SUMMARY

When calling deleteTemplate via API, if no forced parameter is passed, forced=true or forced=false deletion is performed by default. This is inconsistent with the API DOCS display

http://cloudstack.apache.org/api/apidocs-4.13/apis/deleteTemplate.html

**Comment by kioie** [comment]
Hi @div8cn the apidocs just suggests that the parameter is not really required for the command to run. 
Default action is forced=true.

**Comment by DaanHoogland** [comment]
I see a miscommunication in here and am not sure where it lies, @div8cn @kioie . The parameter is not required and if not given it is set to forced=false, but that does not mean the delete is not attempted. the delete is attempted but if impediments are in the way it is not forcefully pursued, is what the APIdoc suggests. One could think of still be in use or some (other) db constraint or disk permissions.
Can you reconsider @div8cn and if agreeing close this ticket?
