### ISSUE TITLE
migratewait does not seem to be honored in KVM

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3742]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14 and less
~~~

##### SUMMARY

While observing the logs and running migrations noticed:
job: job-1843/job-1915 initiate migrate command at 2019-12-03 13:14:29,833

later on at 2019-12-03 13:14:54,097 it is being reported that the job is completed this is about 30 seconds. 

meanwhile the migratewait setting is being set to 1, and seems to be honored at Xen 

with VMware we have the same failure: 

migrte command started at: 2019-12-03 13:21:14,585

and reported success at:  2019-12-03 13:21:24,044

About 10 seconds. 

##### STEPS TO REPRODUCE

~~~
Set the migratewait setting to 1 and initiate a livemigration
~~~

##### EXPECTED RESULTS

~~~
migratewait to be honored 
~~~

##### ACTUAL RESULTS

~~~
It's not
~~~

**Comment by weizhouapache** [comment]
@borisstoyanov 
I do not know how xenserver plugin handle the migration if times out.
in kvm,there are some other settings which can speed up the migration. see below

```
        value = (String) params.get("vm.migrate.downtime");
        _migrateDowntime = NumbersUtil.parseInt(value, -1);

        value = (String) params.get("vm.migrate.pauseafter");
        _migratePauseAfter = NumbersUtil.parseInt(value, -1);

        value = (String)params.get("vm.migrate.speed");
        _migrateSpeed = NumbersUtil.parseInt(value, -1);
```

**Comment by borisstoyanov** [comment]
@weizhouapache it's not about speeding up or slowing down a migration, it's about setting up a timeout period, after which the migration needs to be gracefully put down.

**Comment by weizhouapache** [comment]
@borisstoyanov  I understand
on xenserver, a migration task can be cancelled.
on kvm, it seems difficult (stopping vm on destination host is the only way but not good idea).

**Comment by DaanHoogland** [comment]
@weizhouapache are you saying we connot solve this because of the lack of an API on KVM for stopping an ongoing job?

**Comment by weizhouapache** [comment]
> are you saying we connot solve this because of the lack of an API on KVM for stopping an ongoing job?

@DaanHoogland  
I checked this again.
actually there is a method in libvirt-java to abort domain job.
https://libvirt.org/sources/java/javadoc/org/libvirt/Domain.html#abortJob()

**Comment by DaanHoogland** [comment]
ok, so we can plan this for coming versions. I'll put it to 4.16 for now, let's change if needed.

**Comment by nvazquez** [comment]
@weizhouapache can you check if this is still valid and work around the abort job method you mentioned?
