### ISSUE TITLE
UI: JOB does not complete when you create a template from snapshot

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3770]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.13+
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

When creating a template from volume snapshot, the UI displays the job as still running but you can see that the template is in ready state. 

##### STEPS TO REPRODUCE

~~~
1. create a snapshot of a volume
2. create a template from the snapshot
~~~

##### EXPECTED RESULTS

~~~
Job of the create template action should be marked as successful in the UI when complete. 
~~~

##### ACTUAL RESULTS

~~~
It's running indefinitely 
~~~

**Comment by DaanHoogland** [comment]
I think this is a more generic issue where jobs finish but the notification drop-down still shows them as running. The completion event or message does not reliably come through, it seems. I have reproduced it with 4.1 and master, in the scenario of creating template from snapshot but not reliably, and i remember it happening on other longer going jobs as well, like starting or stopping networks and VMs.

**Comment by andrijapanicsb** [comment]
This was fixed by some commit, not sure which.

**Comment by rhtyd** [comment]
I've tested this case with Primate and 4.14+master recently, did not reproduce this. Closing on the remark that it was not reproducible with Primate, pl log issue here https://github.com/apache/cloudstack-primate if reproducible. Thanks.
