### ISSUE TITLE
systemVM stuck in starting state

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3784]
When a host running system VM's ( SSVM/ Console Proxy / VR ) undergoes a planned or un-planned reboot, after the reboot, the system VM's get stuck in "Starting" state and do not start up properly causing new VM deployment issues.
The behaviour was tested on version 4.13.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
HA systemVMs
~~~

##### CLOUDSTACK VERSION

~~~
4.13.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by andrijapanicsb** [comment]
@DaanHoogland is this related to local storage, or in general?

**Comment by DaanHoogland** [comment]
@andrijapanicsb I'd have to test, i don't know.

**Comment by Spaceman1984** [comment]
Tested with NFS, no error - Will test with local storage.

**Comment by rhtyd** [comment]
Not seen recently.

**Comment by Spaceman1984** [comment]
Tested with local storage, unable to reproduce.

**Comment by andrijapanicsb** [comment]
Did you try/test this by powering off (in parent lab) the hypervisor where the SSVM/CPVM are running (KVM, local storage)?

**Comment by Spaceman1984** [comment]
I tested with restarting my Centos 7 KVM Hypervisor, 2 Different zones, 1 with local storage, one with NFS.

**Comment by rhtyd** [comment]
@DaanHoogland are you able to reproduce it still on master?

**Comment by DaanHoogland** [comment]
tried on a 2 kvm nested test env with centos7 hosts:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/2486961/95564177-b8c2c180-0a1e-11eb-9aff-f03fbdf8b1de.png">
the host and systemVM show as up and connected but the console is not reachable and on the host `virsh list` does not show any VMs.

**Comment by DaanHoogland** [comment]
retsting again as it finds no traction, will close and open a new one if it costs any effort to reproduce.

**Comment by DaanHoogland** [comment]
tested on latest healthcheck build, stopped and started the host that contained cpvm out of bound. no problem found
