### ISSUE TITLE
Public/Guest IP address of Shared Network VR is not persistent when VR is destroyed/recreated

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3787]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
Tested in 4.11.3 (to be confirmed in 4.13, but I expect the identical behaviour) 
~~~

##### CONFIGURATION

Shared network with a running VR.

##### OS / ENVIRONMENT

NA

##### SUMMARY

When a Shared Network VR is manually destroyed and then created automatically again (when starting an existing/new VM) - the public IP of the VR will NOT be the one from the “placeholder” DB records but a new random Public IP.

##### EXPECTED RESULTS

When a new VR for Shared network is created, it's "public/guest" interface is given some IP and this one should persist for the lifetime of the network - i.e. when network is restarted with cleanup, a new VR will be created, but with the same public/guest IP - so that the existing user VMs can continue to use it as DHCP/DNS server.

i.e

![image](https://user-images.githubusercontent.com/45762285/71478410-bf65ac80-27ef-11ea-930d-b3f264008e0c.png)

When this shared network is restarted with cleanup, the IP for the new NIC for the new VR stays the same as the "placeholder" IP (see image above)

But when VR is **deleted**, and then a new VM is created/existing VM is started, a new VR will be created, but it will not inherit the "placeholder" IP, and will instead get the new IP address - this needs fixing.

**Comment by DaanHoogland** [comment]
merged 4.13 and master
