### ISSUE TITLE
dnsmasq.leases file is missing on the new VR after network restart

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3788]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR / DHCP
~~~

##### CLOUDSTACK VERSION

~~~
4.11+
~~~

**PROBLEM:**
After the new VR is created as part of the network restart with cleanup, the new VR will have missing or empty "/var/lib/misc/dnsmasq.leases" file

This will cause that the VM after 15 days of running (50% from the currently hardcoded 30d lease duration) will try to renew it's DHCP lease by sending DHCPREQUEST, but VR/dnsmasq is not aware of that lease (dnsmasq.leases missing/empty), so it will send DHCPNAK, so eventually DHPC client will fail back to the initialization process and start from scratch with DHCPDISCOVER and get its IP again.

This doesn't mean network downtime, but on some older RHEL 6.x systems (that assumes CentOS 6.x as well), **the "initialization" process will remove any static routes added**, thus causing issues.

We need to ensure that the content of the "/var/lib/misc/dnsmasq.leases" file is regenerated/populated with all the needed records on the new VR when restarting a network with cleanup.  Alos, rebootRouter / startRouter API while "recreate.systemvm.enabled”=”true” also need to produce the same results

**Comment by andrijapanicsb** [comment]
The problem of VMs not being able to renew it’s IP address (that his issues casuses) is solved (in 4.13.1 / 4.14) by increasing the dhcp lease time to ~infinity (~98 years) - so currently running VMs will not try to renew the lease for < 50 years. This PR #3662

**Comment by PaulAngus** [comment]
The required fix (repopulating of the leases file) has not yet been implemented, the stated issue has not been resolved.

**Comment by andrijapanicsb** [comment]
Fixed now by #4529  - looks fine
