### ISSUE TITLE
Provided IP during VM deployment may not work in UI

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3810]
When a VM is deployed by the UI wizard with a provided IP address, it seems to be not honoured and assigned to the VM. However, the same is honoured when explicitly passed to the API using cloudmonkey. The issue could be UI related.

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.12, 4.13
~~~

**Comment by andrijapanicsb** [comment]
Not an issue:

![image](https://user-images.githubusercontent.com/45762285/72327409-53b98580-36b1-11ea-8ffc-84e455f83f64.png)

**Comment by andrijapanicsb** [comment]
Same on 4.13:

![image](https://user-images.githubusercontent.com/45762285/72328296-f8889280-36b2-11ea-8df8-67febca4c5f4.png)
