### ISSUE TITLE
Rolling restart doesn't work for a single network of a VPC

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3815]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### CONFIGURATION

NA, single Isolated net, Shared net, and single VPC with at least 1 network in the VPC

##### OS / ENVIRONMENT

NA

##### SUMMARY

When "network.rolling.restart" is set to "true - when restarting a Shared or a single (non-VPC) Isolated network (or a whole VPC) with "cleanup" - the behaviour is as expected -  a new VR is being created first, and only later old one is destroyed.

But when restart a single Isolated network that is part of VPC - this doesn't apply - and VPC VR is being destroyed first, while new one created later.

##### STEPS TO REPRODUCE

~~~
Read the Summary
~~~

##### EXPECTED RESULTS

~~~
rolling restat is done, as for the other network types
~~~

##### ACTUAL RESULTS

~~~
Read the summary
~~~

**Comment by weizhouapache** [comment]
restart a vpc tier will not recreate vpc vrs, but remove the guest nics on VRs and re-add guest nic.

I do not think it is a good idea to restart a single vpc tier. we should disable it.

**Comment by rhtyd** [comment]
Was this recently fixed @andrijapanicsb @DaanHoogland @Spaceman1984 ? Thanks.

**Comment by rhtyd** [comment]
cc @Spaceman1984

**Comment by Spaceman1984** [comment]
I'll take a look @rhtyd
