### ISSUE TITLE
"restart required : yes" is never set to "no" after network/VPC restart

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3816]
##### ISSUE TYPE

 * Improvement request
(perhaps a bug?)

##### COMPONENT NAME

~~~

https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/network/vpc/VpcManagerImpl.java#L1719-L1764


~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### CONFIGURATION/SUMMARY/ETC

When a network is showing as "Restart required: yes" in the GUI (field "restart_required"="1" in cloud.networks table) - there is no way to "fix" this (set it back to "no")

Confirmed by manually setting "1" in the DB for multiple Shared, non-VPC Isolated networks and VPC Isolated networks.
Restart (no cleanup) doesn't work
Restart (with cleanup) doesn't work
The only way seems to be to hack the DB to set 

The code provided above does set this for the VPC itself, not for it's networks.

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack/pull/3803

**Comment by andrijapanicsb** [comment]
Not completely addressed - when you restart VPC with cleanup, it does NOT mark the field as 0 in DB, thus all VPC networks still show as requiring a restart. Thus reopening the issue.

**Comment by Spaceman1984** [comment]
@andrijapanicsb, I tested networks and VPC with and without cleanup. I was not able to reproduce the error. Seems like this is no longer an issue and can be closed.

**Comment by Spaceman1984** [comment]
I have tested on 4.13.1 with isolated, shared and L2 networks and a VPC network. In all instances, the restart required flag was reset with and without cleanup. @andrijapanicsb this doesn't seem like an issue anymore.

**Comment by andrijapanicsb** [comment]
It can't be gone by its own? See this comment from Wei https://github.com/apache/cloudstack/pull/3803#issuecomment-581936011

Can you trace any commit that would have fixed the thing?

**Comment by Spaceman1984** [comment]
Ok, I didn't test restarting the VPC. My test only included restarting the network in the VPC. I'll look into it.

**Comment by Spaceman1984** [comment]
Restarting the VPC did not restart the network. I'll work on a fix.
