### ISSUE TITLE
New Feature: KVM Agent Hooks

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3823]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
CloudStack KVM Agent
~~~

##### CLOUDSTACK VERSION

~~~
Master
~~~

##### SUMMARY

Allow Agent to launch external program to mangle XML before VM launch. Workflow like

1. agent builds initial XML
2. if external transformer script is provided, agent passes XML to transform it.
3. agent receives back transformed XML
4. agent launches XML

Purpose:
- pass raw devices like USB keys, Movidius accelerators, etc.
- GPU pass-thru
- RAW drives
- additional unmanaged nics, VXLANS (we already have a usecase for that, but use it thru security groups script hacking (hotplug) which is not good)
- alter and provide additional CPU flags unsupported by CS

Let me know what do you think about it. Design considerations? Maybe already implemented?

@rhtyd @PaulAngus @andrijapanicsb @DaanHoogland @wido @rafaelweingartner @svenvogel 

We (Bitworks) would like to implement it. If it has chances to be added to mainstream, it's great to discuss the design.

**Comment by PaulAngus** [comment]
Hi @bwsw  - I believe this is what you're looking for:
https://github.com/apache/cloudstack/pull/3510

**Comment by bwsw** [comment]
@PaulAngus thanks for reply, but it's not what I mean. I really cry about this PR - it's huge pain for cloud admins of public cloud... It introduces user-driven VM alternations and very bad for troubleshooting. 

I'm speaking about provider-driven XML alternation based on some kind of dynamic logic when VM is launched. E.g. when VM of SO_X is launched it searches for a spare GPU on host and it's ingested into XML pass-thru, or it cuts , say 32GB of optane device LVM and passes it into VM as a cache device. It's provider driven and user cannot change it.

Real-world example, for every domain/account we have VXLANID in MySQL table. When VM is launched, we create private VM VXLAN network and add it as an unmanaged NIC to VM. CloudStack knows nothing about it. User gets it as is. Now we use hotplug KVM feature for it, but better to change XML and launch VM with such NIC defined.

**Comment by bwsw** [comment]
@svenvogel @DaanHoogland As this PR is merged It would be great if you guys guide me to the documentation area where I can fill in initial documentation for KVM agent hooks. I'm planning to point the design, behavior and hooks example for every hook.

**Comment by DaanHoogland** [comment]
https://github.com/apache/cloudstack-documentation is the repo, I have no idea where we should add your documentation. The design can be added to cwiki: https://cwiki.apache.org/confluence/display/CLOUDSTACK/4.14+Design+Documents

**Comment by DaanHoogland** [comment]
@bwsw, can you close this issue, if you a satisfied?

**Comment by bwsw** [comment]
@DaanHoogland sure
