### ISSUE TITLE
clarify the usage of vlanipranges

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#3824]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
list vlanipranges
~~~

##### CLOUDSTACK VERSION

~~~
acutally master
~~~

##### SUMMARY

i dont know if its a bug but we encounter the following problem.

if you create a physical network and and add 2 vlanipranges aka public addresses. 

e.g.

first network (ROOT)
we have one network range "forsystemvms: true" and its assigned to the root domain
```
   {
      "account": "system",
      "domain": "ROOT",
      "domainid": "23462d06-b5a4-11e8-905f-525400ce8b0c",
      "endip": "192.168.1.238",
      "forsystemvms": true,
      "forvirtualnetwork": true,
      "gateway": "192.168.1.233",
      "id": "8aab7a4e-b20c-4f0e-b6a1-e0f6dbe6471c",
      "netmask": "255.255.255.248",
      "networkid": "0f0d66cb-f8f1-4e33-ad3a-ee2889bb0a09",
      "physicalnetworkid": "6ae13495-fad8-479e-b3f8-b2014fb8de63",
      "startip": "192.168.1.236",
      "vlan": "vlan://100",
...
```

a second network (DOMAINX) assigned to other domain,  "forsystemvms: false"
```
  {
      "domain": "DOMAINX",
      "domainid": "9d77af79-5c87-4b73-b094-a106525803b6",
      "endip": "192.168.2.126",
      "forsystemvms": false,
      "forvirtualnetwork": true,
      "gateway": "192.168.2.65",
      "id": "a9db9833-4deb-4591-a860-e9d5f1d85ed5",
      "netmask": "255.255.255.192",
      "networkid": "0f0d66cb-f8f1-4e33-ad3a-ee2889bb0a09",
      "physicalnetworkid": "6ae13495-fad8-479e-b3f8-b2014fb8de63",
      "startip": "192.168.2.67",
      "vlan": "vlan://101",
...
```

the problem which we encounter is that if there no addresses more left in "DOMAINX" network we encounter that the "ROOT" network is used. 

is this a normal behaviour?

##### STEPS TO REPRODUCE

1. create a ROOT network (set systemvm usage)
2. create a DOMAINX network
3. acquire additional addresses if there is no one more left in the DOMAINX domain and you get one from ROOT
 

~~~

~~~

##### EXPECTED RESULTS

~~~
normally only the assigned network should be used in the domain
~~~

##### ACTUAL RESULTS

~~~
if network from "DOMAINX" has no more addresses it will use the "ROOT" domain
~~~

**Comment by svenvogel** [comment]
@andrijapanicsb do you have an idea?

**Comment by andrijapanicsb** [comment]
Sounds like a bug to me (haven't reproduced). If you had another range for general usage (i.e. not assigned to any specific domain), then I would expect to start using those IPs,  but definitely not the ones which is reserved for system VMs.

**Comment by svenvogel** [comment]
@andrijapanicsb ok. hmm bad.

@weizhouapache do you know about the problem, maybe in your environment?

**Comment by weizhouapache** [comment]
@svenvogel do you mean the ip ranges for systemvms should not be used by other domain/account ?

We do not dedicate vlan and ip ranges for systemvms.

In old versions, if other account has used all dedicated ips (to domain or account) , and use.system.public.ips is true in account setting, IPs in public pool will be fetched when he acquires more IPs.

**Comment by svenvogel** [comment]
@weizhouapache yes i think so. for my understanding it should not use the systemvm ips in the other domain public ip assignment. i detected if DOMAINX is out of addresses it uses the ROOT ips which are only for systemvm. i think this should not happen.

**Comment by weizhouapache** [comment]
@svenvogel agrees. so what you said should be a bug

**Comment by DaanHoogland** [comment]
> @weizhouapache yes i think so. for my understanding it should not use the systemvm ips in the other domain public ip assignment. i detected if DOMAINX is out of addresses it uses the ROOT ips which are only for systemvm. i think this should not happen.

@svenvogel i see `"forvirtualnetwork": true` in your range for ROOT domain. It seems to me that you would expevt them to be used. of course this may be a bad choice for flag names. Are you clear yet on how it should have worked?

**Comment by weizhouapache** [comment]
@DaanHoogland   it should be fixed if system.vm.public.ip.reservation.mode.strictness is set to true.
