### ISSUE TITLE
UI: cannot assign VMs in Internal LB in VPC

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#3827]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
4.14

##### CONFIGURATION

Advanced zone

##### SUMMARY

cannot assign VMs in Internal LB in VPC
##### STEPS TO REPRODUCE
create a VPC 
create a VPC tier with Internal LB
create a vm in the VPC tier
create a internal lb in the vpc tier
click the "Assign VMs" tab in detail page of internal lb
choose a vm, and click "Apply"

##### EXPECTED RESULTS
vm is added to internal LB.

##### ACTUAL RESULTS
No response on UI.
Errors in console log, see below

![image](https://user-images.githubusercontent.com/57355700/72845465-f91abd80-3c9e-11ea-9063-1920e0442280.png)

**Comment by DaanHoogland** [comment]
did you confirm this against 4.13,yet @weizhouapache ?

**Comment by weizhouapache** [comment]
@DaanHoogland I will double check

**Comment by weizhouapache** [comment]
@DaanHoogland I tested on 4.14

If I revert commit 2e2b6700a5a17aed2a97577c8bcec9941c30112d (#3161), it works.

**Comment by weizhouapache** [comment]
@DaanHoogland @pbankonier 
I have created a PR #3832 for this issue. Please review.
