### ISSUE TITLE
Cloudstack 4.13 HA Issue 

### ISSUE THREAD

**Issue by prashant2594** [apache/cloudstack#3830]
@rhtyd 
@wido 
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
KVM, HA,  ceph version 14.2.6 nautilus
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.13
~~~

##### OS / ENVIRONMENT

Centos 7

##### SUMMARY

- I've installed coludstack 4.13 on ceph OSD nodes, and also added ceph as primary storage in cloudstack as RBD pool. Till here it works smoothly. 

- Problem starts in HA phase, when I test HA, it fails.

- VM doesn't migrate to other available management server.

##### STEPS TO REPRODUCE

1. Install ceph,
2. Install cloudstack on ceph osd nodes, 
3. Add ceph OSD's as RBD storage pool to cloudstack as primary storage,
4. Test HA.

~~~
<img width="1557" alt="Screenshot 2020-01-21 at 2 24 09 AM" src="https://user-images.githubusercontent.com/44703864/72960869-426d2900-3dd5-11ea-8418-c79adf396e95.png">

~~~

##### EXPECTED RESULTS

~~~
VM should migrate to available management server.
~~~

##### ACTUAL RESULTS

~~~
It is stuck and doesn't move to other server.

<img width="1557" alt="Screenshot 2020-01-21 at 2 24 09 AM" src="https://user-images.githubusercontent.com/44703864/72960913-76484e80-3dd5-11ea-9ea8-95bab4924e93.png">

~~~

**Comment by wido** [comment]
This is expected and you need to configure Host Out of Band through IPMI to make this work.

Without IPMI there is no way a Hypervisor can be fenced of safely and thus allowing for a safe start of the VMs somewhere else.

**Comment by prashant2594** [comment]
I've configured Out of Band Management as well, pardon me as i forgot to mention about Out of Band Management. @wido 
But HA works fine with NFS storage, 
![Screenshot from 2020-01-23 13-50-48](https://user-images.githubusercontent.com/44703864/72967518-8701c000-3de7-11ea-8cb1-da7a65397c8c.png)

**Comment by div8cn** [comment]
During HA detection, heartbeat detection of the primary storage is required.

Currently ACS + KVM only supports HA for NFS primary storage.

So, HA does not support RBD primary storage
