### ISSUE TITLE
Cloudstack 4.13v unable to 2nd Zone

### ISSUE THREAD

**Issue by prashant2594** [apache/cloudstack#3852]
@wido 
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
cloudstack-agent.service
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.13
~~~

##### OS / ENVIRONMENT

Centos7, KVM, NFS

##### SUMMARY

I've two cloudstack setups, when I try to add 2nd zone, going with Advance zone setup, 
Everything goes in flow till adding host, when it reaches adding host, it starts failing, simultaneously cloudstack-agent.service fails and doesn't start or restarts again. 

[root@acs4 ~]# service cloudstack-agent status -l
Redirecting to /bin/systemctl status  -l cloudstack-agent.service
● cloudstack-agent.service - CloudStack Agent
   Loaded: loaded (/usr/lib/systemd/system/cloudstack-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-01-29 15:43:22 IST; 8s ago
     Docs: http://www.cloudstack.org/
  Process: 17938 ExecStart=/usr/bin/java $JAVA_OPTS $JAVA_DEBUG -cp $CLASSPATH $JAVA_CLASS (code=exited, status=66)
 Main PID: 17938 (code=exited, status=66)

Jan 29 15:43:22 acs4.omnion.in systemd[1]: Unit cloudstack-agent.service entered failed state.
Jan 29 15:43:22 acs4.omnion.in systemd[1]: cloudstack-agent.service failed.
[root@acs4 ~]#

##### STEPS TO REPRODUCE

~~~
Goto->Infrastructure -> Zones -> Add New Zone
Give the IP address and all other required info. 
~~~

##### EXPECTED RESULTS

~~~
Successfully add zone and create VM's
~~~

##### ACTUAL RESULTS

~~~
fails while adding host, cloudstack-agent.service also enter fail state


~~~

**Comment by Slair1** [comment]
@prashant2594 we have the same issue - did you find a fix?

**Comment by alamintech** [comment]
Please help me same error form my. this is my kvm centos 7.7. cloudstack agent not start.
![image](https://user-images.githubusercontent.com/68062764/91588484-0ce77a00-e97a-11ea-8f8d-cb8944cbbdd6.png)

**Thanks.**

**Comment by rhtyd** [comment]
@alamintech try to remove and add the host agains, check in the agent.properties file is there any public nic defined. For example, in my local setup I see:
```
# cat /etc/cloudstack/agent/agent.properties | grep network
private.network.device=cloudbr0
domr.scripts.dir=scripts/network/domr/kvm
guest.network.device=cloudbr0
public.network.device=cloudbr0
```

**Comment by alamintech** [comment]
@rhtyd  Thanks for your reply! 
Now fix, I am using MS version is 4.14 and kvm agent is 4.13. so kvm agent and libvirt is ok, now. 
If I am use this any problem ? 

when I am create instance so I am arise new problem Error "unable to start a vm due to insufficient capacity cloudstack" 

Please help me..
Thanks again.

**Comment by rhtyd** [comment]
You're using 4.13 agent with 4.14 mgmt server. Your setup is incorrect, you must use the same software version for all components.

**Comment by alamintech** [comment]
ok I am trying again.

**Comment by alamintech** [comment]
@rhtyd **Many many thanks.** 

version 4.14 all is ok using ceph storage primary and secondary is nfs. 

Now two question for you. 
1. How can I use open vm console using LAN ip without WAN interface?
2. How can I use secondary storage as ceph pool? 

**Thanks.**

**Comment by wido** [comment]
@alamintech Ceph can not be used as Secondary Storage.

**Comment by alamintech** [comment]
ok, you know Q. 1 ans. Please help me.
Thanks.

**Comment by alamintech** [comment]
all working is fine.
I see primary storage is two think one is my ceph storage and one is my host kvm location is 
**/var/lib/libvirt/images** 
![image](https://user-images.githubusercontent.com/68062764/93348945-aeb30600-f858-11ea-81fd-92833d65a055.png)

And another question.. I see all time local storage is double. It is my problem or not. I am not understand. 
Please help me.
Thanks.
