### ISSUE TITLE
Unable to upgrade the database

### ISSUE THREAD

**Issue by bluesnail95** [apache/cloudstack#3856]
I install cloudstack according to offical quick installation guide.

http://docs.cloudstack.apache.org/en/latest/quickinstallationguide/qig.html#mysql-connector-installation

but I meet this error: 

com.cloud.utils.exception.CloudRuntimeException:Unbale to upgrade the database

com.cloud.utils.exception.CloudRuntimeException:Problem with getting the ec attribute

java.lang.IllegalArgumentException:Can not set long field com cloud upgrade.dao.VersionV0.id to java.math.BigInteger.

**Comment by weizhouapache** [comment]
@bluesnail95 you need to downgrade mysql-connector-java from 8.0.19 to 5.X
This duplicates #3826
