### ISSUE TITLE
test_privategw_acl.py failed in some Trillian tests

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#3859]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
VPC private gateway
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

Advanced zone 

##### SUMMARY

~~~
Smoke test  test_privategw_acl.py failed in some Trillian tests.
~~~

##### STEPS TO REPRODUCE

~~~
see more details in https://github.com/apache/cloudstack/blob/master/test/integration/smoke/test_privategw_acl.py#L317-L381
~~~

##### EXPECTED RESULTS

~~~
No errors/failures
~~~

##### ACTUAL RESULTS

~~~
Some tests failed. For example

https://github.com/apache/cloudstack/pull/3477#issuecomment-571288662
https://github.com/apache/cloudstack/pull/3836#issuecomment-579981259
https://github.com/apache/cloudstack/pull/3851#issuecomment-580891071

~~~

**Comment by weizhouapache** [comment]
https://github.com/apache/cloudstack/pull/3871#issuecomment-583599818

**Comment by weizhouapache** [comment]
https://github.com/apache/cloudstack/pull/3601#issuecomment-584493660

**Comment by rhtyd** [comment]
Failure seen in latest master smoketests - https://github.com/apache/cloudstack/pull/3850#issuecomment-585511968

@weizhouapache I see this issue, are you working on it?

**Comment by weizhouapache** [comment]
@rhtyd yes
found the root cause: https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/network/NetworkServiceImpl.java#L4472

private gateway in two VPCs use the same isolated network, if they have same vlan and cidr.

**Comment by rhtyd** [comment]
Okay @weizhouapache do we need to fix that in the test data config, test or in CloudStack java code?

**Comment by rhtyd** [comment]
@weizhouapache are you send a fix? Thanks.

**Comment by weizhouapache** [comment]
@rhtyd we need to fix it in java code. it is not simple.

**Comment by rhtyd** [comment]
I think it is expected that vlan shouldn't be same? @weizhouapache  - should we fix this in the test or test's config instead?

**Comment by weizhouapache** [comment]
> I think it is expected that vlan shouldn't be same? 
@rhtyd exactly. however in smoke test it creates two VPCs  and private gateway with same vlan for each VPC, then test the connectivity between them. hence we have to add a new parameter bypassvlanoverlapcheck to private gateway so that the test can still go on.
> @weizhouapache - should we fix this in the test or test's config instead?

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland ^^ let's triage/assign this, could @Spaceman1984 pick this up?

**Comment by Spaceman1984** [comment]
I can take a look.

**Comment by weizhouapache** [comment]
@rhtyd @Spaceman1984 I will create a PR today

**Comment by Spaceman1984** [comment]
ok, Thanks @weizhouapache

**Comment by rhtyd** [comment]
Great, thanks @weizhouapache
