### ISSUE TITLE
UI: Resize ROOT volume does not invoke resizeVolume API

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#3860]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.13.0
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The API invokation to resizeVolume API does not happen as the UI breaks due to an error (seen with developer tools enabled):

![image](https://user-images.githubusercontent.com/5295080/73660153-656dc780-4676-11ea-9c73-e1e1366a7175.png)

##### STEPS TO REPRODUCE
~~~
Create a VM
Select ROOT disk
Resize disk to a new size
~~~

##### EXPECTED RESULTS
~~~
Resize API is invoked
~~~

##### ACTUAL RESULTS
~~~
API is not invoked
~~~

**Comment by rhtyd** [comment]
@Spaceman1984 can you have a look at this as well?

**Comment by Spaceman1984** [comment]
Sure @rhtyd
