### ISSUE TITLE
New installation of v 4.13 on Centos 7 completes successfully, but the svms end up in a non-healthy state.

### ISSUE THREAD

**Issue by hextht** [apache/cloudstack#3866]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
svm deployment
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

Basic networking. I am configuring cloudstack with the configuration wizard.

##### OS / ENVIRONMENT

Centos 7
I am using mysql-connector-java-5.1.25-3.el7  instead of the last version, because the installation fails with mysql-java-connector v.8.0.19-1.

##### SUMMARY

I am following the instructions for quick installation of v 4.13 on Centos 7 (http://docs.cloudstack.apache.org/en/latest/quickinstallationguide/qig.html) 

The installation completes successfully, the configuration wizard also completes with no error, but then both svms - console and secondary storage seems to be incomplete. 
Here are the symptoms that i noticed:

- They do not have IP addresses assigned, altough the in the control panel there are IPs listed. 

-  Inside the VMs i looked for the check-health script, but the /usr/local/cloud directory is empty.

- The cloud agent inside the svms is not running and when i try to start it, it fails.

- In the /var/log/cloud.log there are such entries:
    No suitable VirtIO port was found in /dev/virtio-ports

- The templates listed in the UI are actually not present - they do not appear when i try to create a VM, but considering that the svms are not accessible i guess it is to be expected

- After  manually restarting the VMs, they do restart, but the control panel sees tham in "starting" 
   state and remains like that forever.
   alert: Console proxy creation failure. zone: B5, error details: We cannot stop VM[ConsoleProxy\|v- 
     1-VM] when it is in state Starting
--

- There are alerts related to both svms : 
     - Console proxy creation failure. zone: B5, error details: null
     - Secondary Storage Vm creation failure. zone: B5, error details: null
--

I have repeated the installation several times on different server, and every time the installations 

##### STEPS TO REPRODUCE

~~~
Install Centos 7.5 minimal with one NIC and follow the instructions for quick installation:
http://docs.cloudstack.apache.org/en/latest/quickinstallationguide/qig.html

~~~

##### EXPECTED RESULTS

~~~
After the initial configuration wizard completes successfully, the svms should be in a healthy state.
~~~

##### ACTUAL RESULTS

~~~
The configuration wizard completes with no error, but the svms are not complete or not in a healthy state - resulting in an overall non-functional Cloudstack installation
~~~

**Comment by tobin-landricombe** [comment]
Same problem. Not a great introduction to the project.

@hextht Did you get past this?

**Comment by Spaceman1984** [comment]
@hextht the guide is for 4.11, did you change 4.11 to 4.13 when following?

**Comment by Spaceman1984** [comment]
Seems like the System template is also old, should be 
`http://download.cloudstack.org/systemvm/4.11/systemvmtemplate-4.11.3-kvm.qcow2.bz2`

**Comment by tobin-landricombe** [comment]
With these two fixes plus hacking the correct mysql connectors in, my latest attempt is showing System VMs Agent State as "Up".

Still no templates listed so I haven't actually started a VM yet but that can wait until tomorrow.

Thanks, @Spaceman1984

**Comment by Spaceman1984** [comment]
My pleasure @tobin-landricombe . You should be able to start instances as soon as the default template is done downloading. Templates -> CentOS 5.5(64-bit) no GUI (KVM) -> Zones. 

I was able to use mysql-connector-python-8.0.19-1.el7  after running:

```
yum -y install epel-release
yum -y install python-dns
```

@hextht I think we can close this issue as soon as the documentation is updated for the quick install guide.

**Comment by coreymr** [comment]
@tobin-landricombe do you mind detailing your fully functioning build and how you got to it?  
OS=
MySQL =
Java Connector = 
etc...
I'm a newb to CS and trying to get a fresh installation of CS 4.13 going, but have failed numerous attempts.  I see all these references to using an old version of MySQL, old version of Java Connector, tweak this, change that...I wish the installation and documentation and caveats were all clearly available for us non-developers to follow.

Thanks!

**Comment by tobin-landricombe** [comment]
CentOS7. Just the minimal.

I'm using qemu/kvm so: `yum install -y qemu-kvm qemu-img libvirt libvirt-python bridge-utils`

Stop firewalld and NetworkManager:
```
systemctl stop firewalld
systemctl disable firewalld
systemctl mask firewalld
systemctl stop NetworkManager
systemctl disable NetworkManager
systemctl mask NetworkManager
```

Update the instructions with Spaceman1984's comments and follow them apart from the mysql bits:
. Install `mysql` as the instructions said.
. Ignore the MySQL connector Installation bit. I think I also edited `/etc/yum.repos.d/mysql-community.repo` and set `enabled=0` on the `mysql-connectors-community` repo. Instead:
```
yum install epel-release
yum install mysql-connector-python
yum install mysql-connector-java
```

Various bits take a long time to start. Be patient.

Since then other work has got in the way, but I have the SSVM's up, I can `virsh console` them and ping the outside world from them.

**Comment by DaanHoogland** [comment]
seems resolved as per the comments above, please re-open if i'm in err.
