### ISSUE TITLE
Nested Virtualisation for hyper-v on kvm

### ISSUE THREAD

**Issue by svouland** [apache/cloudstack#3868]
##### ISSUE TYPE

 Bug Report

##### COMPONENT NAME

Nested Virtualisation

##### CLOUDSTACK VERSION

4.13

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

4 nodes, CentOs 7, KVM

##### SUMMARY

I looking for activate the nested virtualisation for VM on Windows with Hyper-V
I find in the cloudstack documentation how to activate the nested. It's working when i try with a VM on linux with kvm. I can create and execute VMs

But on windows, when try to install hyper-v, i have an alerte : virtualisation is not activate on the bios. (i dont know how to go enter in the bios with the cloudstack console). Before the nested activation, i had an alerte who said, the virtualization is not activate on the proc.
If lauch systeminfo on command, it said, one hypervisor was detected....

How can i enter in the bios ? press F2 (dont work) ?
Or i missed a step to activate the nestde virtualization for windows ?

thanks, seb.

**Comment by DaanHoogland** [comment]
@svouland in 4.15 there is an option to enter bios on boot for vmware. in older pressing f2 should work but you must reach the console in time to do that. Directly from the kvm console might be an option. I am not sure if there is functional possibility for kvm to do this programmatically.

**Comment by DaanHoogland** [comment]
@svouland is this still an issue for you with the latest version?

**Comment by DaanHoogland** [comment]
@svouland closing, please reopen if it is still an issue
