### ISSUE TITLE
systemvm: Agent state is always Up

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#3875]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Systemvm
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### SUMMARY

This is regression issue of #3870 

the agent state of systemvm should NOT be the state of host, but the state of cloud service in systemvms.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@DaanHoogland @rhtyd 
here is a bug report.
Unfortunately I cannot find the systemvm information in `host` table. 
Must be something wrong in 4.14.

**Comment by rhtyd** [comment]
Probably I used the hostvo the systemvm was on, instead of hostvo of the ssvm/cpvm.

**Comment by weizhouapache** [comment]
> Probably I used the hostvo the systemvm was on, instead of hostvo of the ssvm/cpvm.

should be caused by it.

update: when cloud service is running well, I can see the records in `host` table for systemvms.

**Comment by rhtyd** [comment]
Submitted PR #3876 please review Wei.

**Comment by rhtyd** [comment]
PR merged to 4.13 and fwd-merged to master https://github.com/apache/cloudstack/pull/3876
