### ISSUE TITLE
4.13 Fresh Install fails: Cannot Upgrade Database

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#3883]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Cloudstack Manager / Database
~~~

##### CLOUDSTACK VERSION

~~~
4.13 distribution
~~~

##### OS / ENVIRONMENT

Centos 7, KVM, following Quick Installation Guide

##### SUMMARY

Everything installs OK, on first run CloudStack Manager fails. 

##### STEPS TO REPRODUCE

~~~
follow the quick instllation guide.  
~~~
The latest guide is [here](http://docs.cloudstack.apache.org/en/4.13.0.0/quickinstallationguide/qig.html)

##### EXPECTED RESULTS

~~~
The CloudStack Management web UI should work 
~~~

##### ACTUAL RESULTS

~~~
503 error on web
Exception during database migration for version 4.0.0 to 4.13.0.0
ERROR Unable to upgrade the database
~~~
Check [management-server.log](https://pastebin.com/zhyfjtC6)

**Comment by rvalle** [comment]
I have googled around and found old threads that point to the java mysql connector version. 
For reference the one installed on my centos-7 is:
```
Name        : mysql-connector-java
Arch        : noarch
Epoch       : 1
Version     : 8.0.19
Release     : 1.el7
```
In the Mysql repostories installed pas per quick guide there is no other alternative present.

**Comment by rhtyd** [comment]
@rvalle the workaround is to remove this and replace it with a version 5.x connector. This is fixed in #3601 towards master/4.14.

**Comment by rvalle** [comment]
@rhtyd and were can one get the connector from? it is not in the repo any idea?

**Comment by rhtyd** [comment]
@rvalle you can search alternate repo, epel, or install manually from https://centos.pkgs.org/7/centos-x86_64/mysql-connector-java-5.1.25-3.el7.noarch.rpm.html or rpmfind

**Comment by rvalle** [comment]
@rhtyd thanks

**Comment by coreymr** [comment]
@rhtyd I'm new to CS and am unsure how to do the suggested fix.  I'm receiving a similar error on a fresh installation of CS 4.13 with MySQL 5.7.  I wish the documentation and caveats were more clear.

**Comment by rvalle** [comment]
@rhtyd you have more information in the bug report: #3954 hope that helps.
