### ISSUE TITLE
Programatic Credential Configuration for Admin

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#3885]
##### ISSUE TYPE

 * Feature Idea
 * Documentation Report

This might be either a feature idea or an existing feature not documented.

##### COMPONENT NAME

~~~
Cloudstack Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### OS / ENVIRONMENT

Centos 7 / KVM / Quick Installation Setup

##### SUMMARY

I have automated the deployment of Cloudstack with Ansible following the Quick Installation Guide. Now I want to continue configuring it with Ansible. There is no documented way to configure programatically the admin credentials: password and API keys so that a full automated deployment is feasible.

##### STEPS TO REPRODUCE

~~~
Follow the Quick Installation Guide.
There is no way to configure the root password or create API keys without using the interactive UI.
~~~

##### EXPECTED RESULTS

Should be possible to setup the admin password on initial management server configuration, for example:

~~~
cloudstack-setup-management --admin-password XXXXX --generate-admin-keys
cat /etc/cloudstack/management/admin.properties
~~~

##### ACTUAL RESULTS

~~~
I can only setup admin credentials via UI on initial configuration
~~~

**Comment by rvalle** [comment]
Is there something I missed in the documentation?
Is there any workaround for setting the admin credentials in an non-interactive way?

**Comment by weizhouapache** [comment]
@rvalle you can use cloudmonkey CLI

**Comment by rvalle** [comment]
thanks @weizhouapache, I wonder how it works 

I have reviewed the cloudmonkey documentation and it seems possible to use username/password to configure it. 

Does it mean that it is possible to use cloudstack api with username/password as an alternative to authentication keys? 

Is that using basic auth headers instead of adding api keys and signature? Or using credentials in the place of API keys? perhaps this could even work on Ansible modules directly...

On the other hand, I have installed the cloudstack-cli, is there a particular reason to use this other cli?

**Comment by rvalle** [comment]
I have reviewed the cloudmonkey code, and it seems to log in in order to gain a session key.
It looks to me like there is not an easy shortcut to have username/password authentication on the api, and will go with this suggestion.
I also found a now disabled by default functionality that created an un-autenticated endpoing.

For now, I will just go with @weizhouapache recomendation and use this cli to setup the admin credentials.

**Comment by weizhouapache** [comment]
@rvalle 
if apikey and secretkey is set in cloudmonkey config, they will be used.
if they are not set, username/password/domain will be used.

some useful api

get user keys:  `cloudmonkey get userkeys id=<user id>`
reset user apikey/secretkey: `cloudmonkey register userkeys id=<user id>`
reset user password: `cloudmonkey update user id=<user id> password=<new password>`

**Comment by rvalle** [comment]
@weizhouapache thanks a lot!
I also found out that cloudmonkey is an apache project too.

For a minute I thought it was a third party tool.
Since this tool clearly fills the gap I will close this feature Idea.
