### ISSUE TITLE
With pagesize=10 the count returned in the API response is wrong

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3890]
Deploy 11 VMs, keep pagesize as 10; the `count` returned in the API is not 11 but 10.

APIs affected:
``` 
(check all metrics APIs):
listVirtualMachinesMetrics
listVolumesMetrics
listHostsMetrics
listStoragePoolsMetrics
listZonesMetrics
listClustersMetrics
listClusters

listAffinityGroups
findHostsForMigration
listServiceOfferings
listDiskOfferings

Misc:
listInfrastructure does not return alert and ilbvms count
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.13.x/4.14.x
~~~

**Comment by rhtyd** [comment]
This will affect pagination on Primate.

**Comment by rhtyd** [comment]
@Pearl1594 @davidjumani let's triage, do you think these are quick fixes?

**Comment by DaanHoogland** [comment]
@rhtyd I do not really agree with this being a blocker. It is a blocket to primate only. It has been in for ever since we are an apache project, and probably longer. I understand the urge but it shouldn't block any release. Any reason it should?

**Comment by rhtyd** [comment]
Yes because while it only blocks Primate not the release, but most users would use UI and if we're saying there is a new UI we want to ship to users, any blockers for the new UI should be blocker for the release(s). We already have a PR on this and changes are limited to API layer.

Let's at least try to keep it in, until branch is frozen; we can discuss at that stage if its blocker status needs to be changed.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/3894
