### ISSUE TITLE
Algorithm not set in agent.properties, when adding a new KVM hosts

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3895]
CloudStack agent, software load balancing logic

### how it works / supposed to work
When having the global setting as follows (IP values are an example, to show 2 IP addresses for 2 mgmt hosts)... :
- host=10.2.2.144,10.2.2.118
- indirect.agent.lb.algorithm=roundrobin (or static)
- indirect.agent.lb.check.interval = xxx (different then zero)

... the behaviour we are achieving here is that the list of mgmt servers is randomised due to using "roundrobin" (or set always in the same order as it appears in the "host" value if we set "static) - before getting sent to all connected agents (so some agents will have "x.x.x..144,x.x.x.118@roundrobin" while some will have "x.x.x.118,x.x.x.144@roundrobin" in their agent.properties file)

The presence of  "@roundrobin" or "@static" in the agent.properties is needed for the agent background task to run - a task which says "ok, this is "@static" or "@roundrobin", i.e. NOT "@shuffle" - so I'm going to read the value of the  _indirect.agent.lb.check.interval_ and then check each _indirect.agent.lb.check.interval_ seconds whether some of the prefered mshost (which died previously) is up again and will failback (reconnect again) to the first mshost from the list of mshosts in the agent.properties.
If the algorithm is "shuffle" or if it's missing from the agent.properties, then the task will assume "shuffle" and this means it will internally set indirect.agent.lb.check.interval=0, and thus will NEVER try to reconnect to the first mshost from the list of mshosts in the agent.properties - so if the first mshost dies, agent will always connect to the next one, but when the first mshost is back again, the agent will NOT reconnect to the first one, since the algorithm is "shuffle" or **missing** inside the agent.properties.

### BUG
When adding a new KVM hosts, while having the global setting as described above, the new host will only have a list of mshosts, withOUT the algorithm, in its agent.properties. This means if the first mshost is down, agent will reconnect (fail-over) to the second mshost from the list, but when the first server is back online, it will NOT reconnect (fail-back) to the first mshost, even though the global settings (indirect.agent.lb.check.interval = xxx) says it should do so.

Not a critical bug, but creates inconsistency in agent "fail-back" behaviour between the existing and freshly added KVM hosts.

Workaround: change the host list once, change it back to what it was before ("host" setting) and everything will be properly propagated to all connected agents (including those freshly added KVM hosts)

### Solution
"simply" send the algorithm together with the host list when configuring cloudstack-agent on the KVM side

**Comment by weizhouapache** [comment]
@andrijapanicsb I notice #3491 has been merged into 4.14 by Daan.
Could you please test with latest master ?

**Comment by andrijapanicsb** [comment]
will do, but don't think we touched the issue due to specific of how it works. thx

**Comment by rhtyd** [comment]
@andrijapanicsb cc @DaanHoogland is this still a bug on 4.14/master?

**Comment by DaanHoogland** [comment]
ping @andrijapanicsb , can we close on comment, or do we need to test again?

**Comment by weizhouapache** [comment]
I tested with 4.14.1.0-SNAPSHOT. this issue still exist
(1) indirect.agent.lb.algorithm to roundrobin, in agent.properties
host=10.135.122.60,10.135.122.68,10.135.122.69@roundrobin
(2) put host to maintenance
(3 remove the host and re-add it
host=10.135.122.60,10.135.122.68,10.135.122.69

**Comment by rhtyd** [comment]
cc @nvazquez can you comment?
@Spaceman1984 can you look into this next? Thnx

**Comment by weizhouapache** [comment]
@rhtyd @Spaceman1984 create a pr for this issue #4335

**Comment by nvazquez** [comment]
Thanks @weizhouapache, I have reviewed your PR and looks good
