### ISSUE TITLE
merge propagation code of host parameters to the agents

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3896]
propagating agent.properties from MS to agents from the MS has some boiler plate as commented by @nvazquez . we can put some effort in to unify the code used as  specified in https://github.com/apache/cloudstack/pull/3491#pullrequestreview-361091060

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@DaanHoogland was this addressed, can this be closed then? Thanks
