### ISSUE TITLE
Review all list APIs and make then honour listall parameter

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#3897]
There are many list APIs that should ideally honour the `listall` parameter and when set to true should return all the items a caller/account is authorised to see. Due to a historic use of projectid=-1, most APIs do return all project only resources.

With PR https://github.com/apache/cloudstack/pull/3894 the behaviour has been addressed for some APIs such as listRouters etc where all resources are returned for root admin when both listall=true and projectid=-1 is passed. A review of all list APIs and fix to make the behaviour consistent is asked.

##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.13, 4.14+
~~~

**Comment by weizhouapache** [comment]
@rhtyd Should this be fixed before 4.14.0.0 release ?

**Comment by rhtyd** [comment]
@weizhouapache I'll need to check if others APIs need to be supported, the changes were done solely to support infrastructure (VR etc) list views in Primate.

**Comment by weizhouapache** [comment]
@rhtyd will you plan to work on this issue ?

**Comment by rhtyd** [comment]
@weizhouapache I'm not sure - it would depend on requirement coming from Primate issues/tasks

**Comment by wido** [comment]
Ping @GabrielBrascher 

This is what we ran into as well

**Comment by DaanHoogland** [comment]
in view of the changes in #3894 it would seem that no further work needs to be done, @rhtyd can you comment?
@wido @weizhouapache did you have anymore issues as a result of this?

**Comment by GabrielBrascher** [comment]
@rhtyd @DaanHoogland do you think that PR #4276 should extend its goals to more APIs?

Or is it ok to do it "progressively" with different PRs addressing this issue?

**Comment by DaanHoogland** [comment]
@GabrielBrascher I don't mind progressively solving this but I have two worries:
1. this issue drags on for the longest while
2. consistant implementation is going to suffer from scattered work, and we and up with a new discussion on how `list`APIs and the `listall` parameter should work

**Comment by rohityadavcloud** [comment]
cc @davidjumani does your related PR address this?

**Comment by davidjumani** [comment]
@rohityadavcloud  Nope but I can look into this if its priority for 4.17

**Comment by rohityadavcloud** [comment]
cc @shwstppr

**Comment by rohityadavcloud** [comment]
Closing this as several list APIs were improved to support listall or project=-1 param. It could risks the issue of API backward compatibility. I'm not going to work on this, abandoning this one. Others are welcome to raise PRs around this as/when needed.
