### ISSUE TITLE
scale_vm test fails on xen

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#3906]
this report is consistant on xen and doesn't occur on other hypervisors:
test_01_scale_vm | Failure | 26.81 | test_scale_vm.py

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
smoke test
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
It's because this feature requires licensed version of xenserver7+, on xcp-ng the test passes.

**Comment by DaanHoogland** [comment]
ok, so the fix is not to run it on xenserver but on xcp-ng, thanks.
