### ISSUE TITLE
VRs listed twice in GUI

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3926]
Picture worth a thousand words...Current Master version:

![image](https://user-images.githubusercontent.com/45762285/75804819-f07ad400-5d80-11ea-9205-e1b42dde4a78.png)

**Comment by rhtyd** [comment]
@andrijapanicsb can you clear browser cache and try again?

**Comment by rhtyd** [comment]
I'll check tomorrow nonetheless
