### ISSUE TITLE
VRs are being displayed twice 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3931]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

![Screenshot 2020-03-04 at 15 57 56](https://user-images.githubusercontent.com/13551960/75889113-1497ed00-5e35-11ea-8c80-5f0c61f553f7.png)
![Screenshot 2020-03-04 at 15 57 52](https://user-images.githubusercontent.com/13551960/75889117-15c91a00-5e35-11ea-9f44-97fdadb8b18b.png)

##### SUMMARY

VRs are being displayed 2 times

**Comment by borisstoyanov** [comment]
It'll be good if we can get this in 4.14

**Comment by rhtyd** [comment]
Can test against latest master @borisstoyanov, a fix was merged today cc @DaanHoogland @andrijapanicsb

**Comment by borisstoyanov** [comment]
nice

**Comment by DaanHoogland** [comment]
#3927
