### ISSUE TITLE
Root disk size reverts to its template size after rebuild

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#3957]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### CONFIGURATION

CloudStack 4.13
vSphere 6.5

##### STEPS TO REPRODUCE

- resize root disk to larger size
- rebuild vm

##### EXPECTED RESULTS

CloudStack resize root disk to larger size after rebuild

##### ACTUAL RESULTS

- root disk size reverts to its original template size
- CloudStack reports root disk size has not been reverted

**Comment by DaanHoogland** [comment]
@aleskxyz what diskoffering did the VM have to begin with?

**Comment by aleskxyz** [comment]
> @aleskxyz what diskoffering did the VM have to begin with?
 I have create VM from a template which its root disk is created from a dynamic disk offering.

**Comment by aleskxyz** [comment]
More investigation results:

**Scenario 1:**
1. Create a VM with root disk same as template
2. Upgrade root disk
3. Rebuild VM
Result: root disk size reverts to template size

**Scenario 2:**
1. Create a VM with increased root disk size
2. Rebuild VM
Result: root disk size is ok

**Scenario 3:**
1. Create a VM with increased root disk size
2. Upgrade root disk
3. Rebuild VM
Result: root disk size is ok

**Comment by aleskxyz** [comment]
**Workaround:**
It seems that when you increase root disk size at deployment, CloudStack initializes "rootdisksize" as a variable in "details" list with the size of root disk.
When you request for rebuild, CloudStack looks for "rootdisksize" _regardless of its value_, and recreates root disk according to its latest size.
So this scenario is a workaround to this bug:

1. Create a VM with root disk same as template
2. Upgrade root disk
3. Call "updateVirtualMachine" by adding "rootdisksize=0" to "details" list.
4. Rebuild VM
Result: root disk size is ok

**Comment by DaanHoogland** [comment]
Sounds like this can be done by :

1. Create a VM with root disk same as template
2. (under the hood) Call "updateVirtualMachine" by adding "rootdisksize=0" to "details" list.
3. Upgrade root disk
4. Rebuild VM
   Result: root disk size should be ok

are you planning to fix this @aleskxyz ?

**Comment by aleskxyz** [comment]
> Sounds like this can be done by :
> 
> 1. Create a VM with root disk same as template
> 2. (under the hood) Call "updateVirtualMachine" by adding "rootdisksize=0" to "details" list.
> 3. Upgrade root disk
> 4. Rebuild VM
>    Result: root disk size should be ok
> 
> are you planning to fix this @aleskxyz ?

@DaanHoogland 
I really want to contribute on CS code but unfortunately I'm not a developer :(

**Comment by DaanHoogland** [comment]
ok @aleskxyz , unfortunately that means there is no guarantee it will actually be implemented. I will if i find the time but make no promises

**Comment by aleskxyz** [comment]
**Better workaround:**
Based on [this line of code](https://github.com/apache/cloudstack/blob/4.13.0.0/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L3841) we can abuse (?!) template details and inject "rootdisksize" in vm details:

![image](https://user-images.githubusercontent.com/39186039/76369575-eaaa6300-632b-11ea-9760-dd115cc2b082.png)

By this workaround everything goes as expected.

**Comment by DaanHoogland** [comment]
@aleskxyz glad it works for you, but now you are tying the rootDiskSize to the template instead of the diskOffering. If this template is never used with a fixed diskOffering 👍 , is it?

**Comment by DaanHoogland** [comment]
I'm having second thoughts on this @aleskxyz , if you revert, you want to revert, so yuou expect the original configuration. Why else would you?
cc @andrijapanicsb @PaulAngus @alexmattioli

**Comment by PaulAngus** [comment]
I'd agree with your last summary.  Revert to original deployment should do exactly that. Revert to the original 'configuration'

Obviously the DB and billing should reflect that..

**Comment by aleskxyz** [comment]
> I'm having second thoughts on this @aleskxyz , if you revert, you want to revert, so yuou expect the original configuration. Why else would you?
@DaanHoogland
Reverting to template size or keeping the existing root disk size is not the problem.
As I have mentioned in bug report, we see a inconsistency here. In VMware I see that the disk size is reverted but CS reports that the disk size is not changed.
@PaulAngus

**Comment by DaanHoogland** [comment]
> > I'm having second thoughts on this @aleskxyz , if you revert, you want to revert, so yuou expect the original configuration. Why else would you?
> 
> @DaanHoogland
> Reverting to template size or keeping the existing root disk size is not the problem.
> As I have mentioned in bug report, we see a inconsistency here. In VMware I see that the disk size is reverted but CS reports that the disk size is not changed.
> @PaulAngus

Ok @aleskxyz , that I agree to. the original size should be restored and set in the DB.
So I dissagree with the "EXPECTED RESULT" form your original description; "CloudStack resize root disk to larger size after rebuild", this should read "CloudStack resizes root disk to original size after rebuild".
Being pragmatic we might let the behaviour be hypervisor specific to ease implementation, but in principle rebuild is rebuild imnsho.

**Comment by rhtyd** [comment]
On reset, I would expect the VM to return to the originally deployed state, which in case the root disk size was different than template size (originally resized while deployment) then the reset VM root disk size should be resized.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4638
