### ISSUE TITLE
Cannot build packages with latest master on Ubuntu 18.04

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#3981]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Packaging
~~~

##### CLOUDSTACK VERSION

~~~
master/4.14
~~~

##### CONFIGURATION

-

##### OS / ENVIRONMENT

Ubuntu 18.04

##### SUMMARY

We are not able to build packages with latest master on Ubuntu 18.04
It might be caused by #3610

##### STEPS TO REPRODUCE

~~~
cd packaging
./build-deb.sh
~~~

##### EXPECTED RESULTS

~~~

packages are built successfully.
~~~

##### ACTUAL RESULTS

~~~
make[1]: Leaving directory '/root/cloudstack.414-leaseweb'
   dh_installchangelogs
   dh_python2
   debian/rules override_dh_systemd_enable
make[1]: Entering directory '/root/cloudstack.414-leaseweb'
dh_systemd_enable -pcloudstack-management -pcloudstack-agent -pcloudstack-usage -pcloudstack-rolling-maintenance@
debian/rules:144: recipe for target 'override_dh_systemd_enable' failed
make[1]: Leaving directory '/root/cloudstack.414-leaseweb'
debian/rules:9: recipe for target 'binary' failed
~~~

**Comment by DaanHoogland** [comment]
@weizhouapache what points you to that PR you mention? I had a look and it has packages build for debian before merge: https://github.com/apache/cloudstack/pull/3610#issuecomment-597642443 
anything we missed?

**Comment by weizhouapache** [comment]
@DaanHoogland it is not because of something missed, but the line below


https://github.com/apache/cloudstack/pull/3610/files#diff-d2b2229a977ef7e99780f2207c29b503R144


build succeed if revert this line.

**Comment by DaanHoogland** [comment]
@weizhouapache , your link does not point to a line but to the whole diff.

**Comment by weizhouapache** [comment]
@DaanHoogland it might because the PR is huge.

https://github.com/shapeblue/cloudstack/blob/f753d030033e9b598b179f4c7a1945cfef73b6c3/debian/rules#L144

**Comment by DaanHoogland** [comment]
tnx @weizhouapache , can you try with only the last @ removed from that line?
again, it is strange that the package build would work in the lab but not on your env. It might be as simple as that though ;)

**Comment by DaanHoogland** [comment]
ping @nvazquez , please have a look?

**Comment by weizhouapache** [comment]
@DaanHoogland I have tried with removing "@" yesterday, did not work
hence I remove whole "-pcloudstack-rolling-maintenance@", it works

**Comment by nvazquez** [comment]
@weizhouapache @DaanHoogland taking a look at it, spinning up an ubuntu 18 env to try replicating, let me update you soon

**Comment by andrijapanicsb** [comment]
@nvazquez what's the update here?

**Comment by nvazquez** [comment]
@andrijapanicsb PR 3984 tested and working as expeected, waiting for review and approval
