### ISSUE TITLE
Allow .img extension for qcow2 type of template

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4011]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

KVM ".img" extension is used for both qcow2 and raw image types (for reasons to confuse you and nothing else!) and since Canonical (and others, i.e. OpenStack) distributes some linux/cloud qcow2 images with .img extension, it makes sense to allow .img extension for qcow2 as well

Currently, this extension is allowed for RAW image type only.
Change is simple but requires careful unit test change.

**Comment by rhtyd** [comment]
Was this fixed @nvazquez ?

**Comment by DaanHoogland** [comment]
ping @nvazquez , can you comment?

**Comment by rhtyd** [comment]
Checked UriUtils.java, img is supported for qcow2 format
