### ISSUE TITLE
There is no secondary storage VM for secondary storage host

### ISSUE THREAD

**Issue by gnanasankar** [apache/cloudstack#4028]
There is no secondary storage VM for secondary storage host

**Comment by DaanHoogland** [comment]
this does not tell is anything about your issue, @gnanasankar . Please be as verbose as possible. describe OSses used, version of cloudstack, hypervisor type and - version. include any error you observe in the logs...

**Comment by DaanHoogland** [comment]
closing due to lack of info, please re-open with more details if needed.
