### ISSUE TITLE
Template on different domain permissions 

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#4031]
Users from different domain than the template's domain should be excluded. Example; Admin can see ROOT domain users but not add template permission if the template belongs to a subdomain

##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.13.1, master
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Not relevant

##### SUMMARY
Users from different domain than the template's domain should be excluded

##### STEPS TO REPRODUCE
~~~
Create subdomain
Create user
User registers template
Admin updates template permission
~~~

##### EXPECTED RESULTS

~~~
Users in ROOT domain not displayed
~~~

##### ACTUAL RESULTS

~~~
Users in ROOT domain displayed and selectable (fail when selected)
~~~

**Comment by DaanHoogland** [comment]
@nvazquez is this still a valid issue?
(seems minor/simple to me and could go towards 4.16)

**Comment by nvazquez** [comment]
@DaanHoogland I've tested this on 4.15 with the Primate UI and the issue is still present

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4744 tested by David and Pearl
