### ISSUE TITLE
At last step of zone deployment wizard, the enable button is not shown 

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4044]
At the last step of the zone deployment wizard on latest master, the enable zone button is not shown but errors are seen in console:

![Screenshot from 2020-04-27 14-12-06](https://user-images.githubusercontent.com/95203/80359887-2083b680-889c-11ea-8ca4-038b913d5f55.png)

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0-SNAPSHOT/master
~~~

**Comment by andrijapanicsb** [comment]
@rhtyd is this issue still present, i.e. I don't recall anyone tested/confirmed/etc?

**Comment by andrijapanicsb** [comment]
@borisstoyanov do we have bandwidth to test this? This would be a blocker (if it's a valid bug).

**Comment by borisstoyanov** [comment]
Sorry I came back to you late, I've tested that way back with RC1 and it didn't happen, was able to add zone with chrome browser. Please let me know if you think it could be browser related and I can retest

**Comment by rhtyd** [comment]
Yes, it could be browser/env related. I'll close this on your remark @borisstoyanov
