### ISSUE TITLE
Quick Guide Install: Cannot Add host

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4050]
##### ISSUE TYPE

 * Bug Report
 * Documentation Report

##### COMPONENT NAME

~~~
KVM Agent/Host
~~~

##### CLOUDSTACK VERSION

~~~
4.13 / Latest
~~~

##### OS / ENVIRONMENT

CentOS Linux release 7.8.2003 (Core)

##### STEPS TO REPRODUCE

~~~
Follow the quick install guide, add a kvm host as explained:
~~~

Quick install [guide](http://docs.cloudstack.apache.org/projects/archived-cloudstack-installation/en/4.11/qig.html)

##### EXPECTED RESULTS

~~~
Host should be added to the UI
~~~

##### ACTUAL RESULTS

~~~
The host addition process is failing. Looks like the Agent and Libvirtd cannot talk as per exception:

2020-04-29 12:25:32,753 ERROR [kvm.resource.LibvirtConnection] (AgentShutdownThread:null) (logid:) Connection with libvirtd is broken: invalid connection pointer in virConnectGetVersion

It also looks like my changes to /etc/libvirt/libvirt.conf are been wiped out each time I try to add the host.

I wonder if the quick install guide is up-to-date or the Agent is now trying to do the libvirt configuration itself. 

~~~

**Comment by rvalle** [comment]
Ok, I just noticed issue #3509

This seems to be the same thing I am experimenting. And there is a bunch of other users there.

I still have not worked out my problem but the consensus there seems to be that the error message "invalid connection pointer in virConnectGetVersion"... can be discarded

**Comment by rvalle** [comment]
I can see that the agent is not capable to connect to libvirt
I can also see that the Agent confiruration has modified my network setup in ways that I did not expect or anticipate, has created a bridge on eth0 despite me having a dedicated interface for the cloud... that does not seem to be in use.

I guess my setup is not just like in the quick install guide, and also cloudstack is fairly intrusive in the network configuraiton. I need to better understand how it owrks. I leave this log in case anybody else finds the same situation.

**Comment by lizeyun** [comment]
Have you solve this problem

**Comment by rvalle** [comment]
Yes it is now working.

I think my problem was related to firewall. My firewall policy was to close all, and only add the rules specified in the documentation, but it was not enough, or there was conflict between my firewall rules and rules managed by the agent.

are you having this problem too?
