### ISSUE TITLE
Unable to add host: uncapable to identify cause/missing ERROR logs

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4054]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
Advanced Networking Zone installation
~~~

##### CLOUDSTACK VERSION

~~~
Latest: 4.13.1
~~~

##### CONFIGURATION

Advanced Networking new zone,pod, cluster and host.

##### OS / ENVIRONMENT

Centos 7.

##### SUMMARY

I am creating an KVM, network advanced zone. The UI reports that the host could not be added, however, by looking at the logs everything seems to be just fine.
The main issue here is that it is NOT possible to identify what is failing.

##### STEPS TO REPRODUCE

~~~
Attempt to Create a new Advanced zone, pod, cluster and host. 
Provide a parameter that is invalid or wrong. 
~~~

##### EXPECTED RESULTS

~~~
Logs should include ERROR messages that help identify the cause.
~~~

##### ACTUAL RESULTS

~~~
UI Reports unable to add host
Logs include no relevant ERROR mensage (other that the host could not be added)
Logs include several SUCCESS messages that signal that everything is OK.
~~~

**Comment by rvalle** [comment]
The relevant logs that I see are:

Confirmation the agent was created OK, manager logs:
```
2020-05-03 16:22:27,115 DEBUG [c.c.u.s.SSHCmdHelper] (qtp540585569-13:ctx-a9e3d331 ctx-07912f60) (logid:361428b2) SSH command: sudo cloudstack-setup-agent  -m 10.71.0.254 -z 1 -p 1 -c 1 -g ef861baa-8f7c-38fe-9b6a-981df48ac7ac -a -s  --pubNic=host_netbr --prvNic=host_netbr --guestNic=guest_netbr --hypervisor=kvm
SSH command output:Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [OK]
Configure Firewall ...        [OK]
Configure Nfs ...             [OK]
Configure cloudAgent ...      [OK]
CloudStack Agent setup is done!
```

Confirmation the agents connects back with the manager, that logs:
```
2020-05-03 16:22:30,330 DEBUG [o.a.c.c.p.RootCACustomTrustManager] (pool-9-thread-1:null) (logid:) A client/agent attempting connection from address=10.71.0.1 has presented these certificate(s):
Certificate [1] :
 Serial: 18f633061a199417
  Not Before:Sun May 03 04:21:51 UTC 2020
  Not After:Mon May 03 16:21:51 UTC 2021
  Signature Algorithm:SHA256withRSA
  Version:3
  Subject DN:C=cloudstack, O=cloudstack, OU=cloudstack, CN=compute1.host_net
  Issuer DN:CN=ca.cloudstack.apache.org
```
Similar success logs can be found on the agent, that reports connection to the manager:
```
2020-05-03 16:22:29,478 INFO  [utils.nio.NioClient] (main:null) (logid:) Connecting to 10.71.0.254:8250
2020-05-03 16:22:29,484 INFO  [utils.nio.Link] (main:null) (logid:) Conf file found: /etc/cloudstack/agent/agent.properties
2020-05-03 16:22:30,733 INFO  [utils.nio.NioClient] (main:null) (logid:) SSL: Handshake done
2020-05-03 16:22:30,733 INFO  [utils.nio.NioClient] (main:null) (logid:) Connected to 10.71.0.254:8250
```

Confirmation the agent can talk to libvirt, agent logs manipulation of libvirt objects:
```
2020-05-03 16:31:31,963 INFO  [kvm.storage.LibvirtStorageAdaptor] (Agent-Handler-1:null) (logid:) Found existing defined storage pool c3ae71d6-74a8-4252-bd7c-f886a821dac7, using it.
```
A further check on virsh finds that object:
```
virsh # pool-list 
 Name                 State      Autostart 
-------------------------------------------
 c3ae71d6-74a8-4252-bd7c-f886a821dac7 active     no 
```

At this point I assume that all the bits and pieces are working. However, after a long wait, the manager reports:
```
2020-05-03 16:51:11,793 WARN  [c.c.r.ResourceManagerImpl] (qtp540585569-14:ctx-098be29b ctx-c1b8d4c3) (logid:d82ea0e4) Unable to find the server resources at http://10.71.0.1
2020-05-03 16:51:11,797 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp540585569-14:ctx-098be29b ctx-c1b8d4c3) (logid:d82ea0e4) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2020-05-03 16:51:11,797 WARN  [o.a.c.a.c.a.h.AddHostCmd] (qtp540585569-14:ctx-098be29b ctx-c1b8d4c3) (logid:d82ea0e4) Exception: 
com.cloud.exception.DiscoveryException: Unable to add the host
	at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:825)
	at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by rvalle** [comment]
I suspect a networking issue, due to the long wait, however, without exception or ERROR message I have been already 3 days trying to find out what is wrong. 

I attach complete logs files.

[management-server.log.2020-05-03.gz](https://github.com/apache/cloudstack/files/4573299/management-server.log.2020-05-03.gz)
[agent.log.2020-05-03.gz](https://github.com/apache/cloudstack/files/4573301/agent.log.2020-05-03.gz)

**Comment by DaanHoogland** [comment]
that does not sound nice @rvalle . The automated tests we run internally install advanced zone mostly (blueorangutan outputs you see all around), So yes it is probably environmental, but that doesn't mean we shouldn't improve the diagnostics you are getting.
according to your agent log it is connected to your server: `2020-05-03 16:37:31,616 INFO  [utils.nio.NioClient] (Agent Timer:null) (logid:) Connected to 10.71.0.254:8250`, however in the agent itself `2020-05-03 16:22:30,832 ERROR [kvm.resource.LibvirtConnection] (Agent-Handler-1:null) (logid:) Connection with libvirtd is broken: invalid connection pointer in virConnectGetVersion`. Can you check if your host is a fully functional hypervisor?

**Comment by rvalle** [comment]
@DaanHoogland I researched that message and found  issue #3509 here where the team implied that the exception could be ignored. 
 
I quote @andrijapanicsb : 

> that message you shared "invalid connection pointer in virConnectGetVersion" I've seen as well, but my agents were working fine (can't advise why it's there)

I still think that the message (or its persistent occurrence) might be somehow related.

**Comment by DaanHoogland** [comment]
ok @rvalle reading that ticket my next try, after validating the network setup, would be to look at the qemu version.

**Comment by rvalle** [comment]
@DaanHoogland  I did not install any particular version, just the default en Centos 7.
Is the distribution tested against a particular Qemu version? 

Is there a spec of which qemu version is required?

The QuickInstall guide does not warn about it.

Thanks for the tip, I will review.

**Comment by rvalle** [comment]
@DaanHoogland I just reviewed the integration testing infrastructure, 
Could we say that systemvm is the "reference" OS setup for both Manager and Hosts?
This VM seems to be base on debian 9, while the quickinstall guide refers to Centos...

**Comment by rvalle** [comment]
@DaanHoogland  I can see the following strange connections:

```
tcp6       0      0 192.168.121.48:8080     192.168.121.1:58612     TIME_WAIT  
tcp6       0      0 192.168.121.48:8080     192.168.121.1:58622     TIME_WAIT  
tcp6       0      0 192.168.121.48:8080     192.168.121.1:58620     TIME_WAIT  
```
here the .48 is the manager and .1 is the DNS server. I wonder what is trying to access. Aren't those ports meant to be NFS?

**Comment by rvalle** [comment]
I can now create host. One of the following 3 things unlocked the problem:

- /secondary was nfs-mounted on the host before adding them
- The hosts did not meet the minimum RAM requirement (according to google) of 4GB
- I have disabled the firewall until I get this back working.

**Comment by DaanHoogland** [comment]
It is probably the middle - or last bullet point @rvalle. The secondary storage should not have to be mounted in one go, but instead the specific store share and this will be done by the system. Maybe I misinterpreted your first bullet?

**Comment by rvalle** [comment]
@DaanHoogland you are right.

The exception was all alone there, but fairly cryptic:

```
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'ram' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4185)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4119)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
	... 47 more
```
The agent seems to calculate its RAM by subtracting a given amount form the physical RAM , as it is common practice when sizing an hypervisor. In my case the reported RAM would become negative. 

A good improvement would be that the setup script checked for minimum requirements here: 
```
SSH command output:Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [OK]
Configure Firewall ...        [OK]
Configure Nfs ...             [OK]
Configure cloudAgent ...      [OK]
CloudStack Agent setup is done!
```

**Comment by DaanHoogland** [comment]
I love to hear about a "good improvement", but don't see a relation between minimum requirements and that output. Can you create an issue stating the exact 'requirement'?
tnx @rvalle

**Comment by rvalle** [comment]
@DaanHoogland I have created the issue. No everything is working very nicely, and my perception of ACS has greatly improved since. 
I am going to re-run my scripts with the NFS secondary volume mounted, to see up to which point that was an issue too or not.

**Comment by bragonznx** [comment]
Hello
Any news on this ?
I still have the same issue and the agent doesn't want to start .... :(
I saw many issue like this one not resolve, does anybody got a clear answer of what could be the issue with :
"Connection with libvirtd is broken: invalid connection pointer in virConnectGetVersion"

**Comment by bragonznx** [comment]
I double check all of this
And we have 128Go of memory so no issue on that
We have as well no firewall, so no issue with that !

**Comment by DaanHoogland** [comment]
@bragonznx As @rvalle closed the issue yours is probably not the same. Can you open a new ticket and describe the issue in detail, please? (I.E. versions of OSses and ACS components, logs from MS and agent, etc)

**Comment by bragonznx** [comment]
I already open a new issue : thanks for the reminder

**Comment by bagayatkarashish** [comment]
Hi Team,

I am unable to add the host to the management server. I have tried all above suggestion but no luck
