### ISSUE TITLE
The listKubernetesSupportedVersions API does not honour searching

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4056]
The kubernetes ISOs or the listKubernetesSupportedVersions API does not support searching as the keyword parameter is not honoured. Fixing this would enable searching both in UI and API.

Originally opened as Primate bug - https://github.com/apache/cloudstack-primate/issues/280

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack-primate/issues/280 closed in favour of this cc @borisstoyanov

**Comment by rhtyd** [comment]
ping - @shwstppr another CKS improvement

**Comment by shwstppr** [comment]
@rhtyd added fix in #4134
