### ISSUE TITLE
Improved Error message: Installing on Hosts that don't meet requirements.

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4063]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Host Agent 
~~~

##### CLOUDSTACK VERSION

~~~
4.13.1
~~~

##### CONFIGURATION

Typical testing environment / 3 node minimal cluster.

##### OS / ENVIRONMENT

Centos 7 / KVM

##### SUMMARY

I have been lost for days trying to setup a ACS test cluster. One of my mistakes was to try to add a host that did not meet the RAM requirement. See #4054 for details.

This improvement is about providing better error messages, and facilitate ACS adoption.

##### STEPS TO REPRODUCE

~~~
Install an ACS on a test cluster, 3 nodes 1GB ram each. 
use KVM with nested virtualization enabled.
Follow the quick guide or use Ansible to install the compontents.
~~~

##### EXPECTED RESULTS

A clear ERROR or WARNING should be received stating that the Hosts do not meet the requirements. Something like:

~~~

SSH command output:Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [OK]
Configure Firewall ...        [OK]
Configure Nfs ...             [OK]
Configure cloudAgent ...      [OK]
Host meets Requirements... [ERROR]
CloudStack Agent setup finalized with ERROR.

~~~

##### ACTUAL RESULTS

The logs suggests that everything is OK, but system is not functional: 

~~~

SSH command output:Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [OK]
Configure Firewall ...        [OK]
Configure Nfs ...             [OK]
Configure cloudAgent ...      [OK]
CloudStack Agent setup is done!
~~~

**Comment by davidjumani** [comment]
Can add a check for the min ram requirements
