### ISSUE TITLE
System VMs stuck at Starting when adding a host

### ISSUE THREAD

**Issue by jl0x61** [apache/cloudstack#4072]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
System VM Creation
~~~

##### CLOUDSTACK VERSION

~~~
4.13.1.0
~~~

##### CONFIGURATION

I use basic network. The gateway and management server ip are both 11.11.11.21. 
The management network ip range is between 11.11.11.53 and 11.11.11.59.
The NFS server ip is 11.11.11.50.
The guest network ip range is between 11.11.11.60 to 11.11.11.200.
The netmask is 255.255.255.0. 

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### SUMMARY

I installed CloudStack in a two node cluster.  The management server is running on 11.11.11.21 and the agent is running on 11.11.11.22.  The gateway is also 11.11.11.21. 

The management server created two system VMs in agent. When I type `virsh list` on 11.11.11.22, the statuses of secondary storage VM and console proxy VM are both "running".  But on the management server UI, the two system VMs are stuck at "Starting" state.  ` There is no secondary storage VM for secondary storage host nfs://11.11.11.50/export/secondary` appear in management server logs every one minute.

It seems that the management server cannot detect the liveliness of system VMs.

I think the problem is that the system VMs cannot access the network 11.11.11.0/24. Because I cannot ping or ssh VMs' public/private/link local ip address listed on cloudstack management server UI. But when I type `virsh console [VMName]`, there is a prompt for username and password.

The creating VM job log: https://paste.ubuntu.com/p/tkNHM9r8yf/
The ifconfig output of agent host: https://paste.ubuntu.com/p/6BHmS995Fh/
The ifconfig output of management server host: https://paste.ubuntu.com/p/BY5xtd62k4/
Could anyone help me? Any help will be appreciated.

##### STEPS TO REPRODUCE

~~~
Installation steps is the same as [this link](https://rohityadav.cloud/blog/cloudstack-kvm/)
expect that the CloudStack binary is built from source.
~~~

##### EXPECTED RESULTS

~~~
The two system VMs running correctly.
~~~

##### ACTUAL RESULTS

~~~
The state of the two system VMs are stuck at "Starting".
~~~

**Comment by weizhouapache** [comment]
is the systemvm template correct ?

**Comment by jl0x61** [comment]
@weizhouapache I use the systemvm template downloaded from http://download.cloudstack.org/systemvm/4.11/systemvmtemplate-4.11.2-kvm.qcow2.bz2. Is it correct? Does the system VM template for 4.13.1 exist?
Besides, I see argument `-drive file=/usr/share/cloudstack-common/vms/systemvm.iso` in system VMs' qemu argument. Is `systemvm.iso` also a system VM template?

**Comment by jl0x61** [comment]
I find the bridge cloudbr0 didn't connect to network interface enp95s0f1 correctly because the network interface connected to k8s's network. So I used a new unused network interface `eno1` and set its ip address to `33.33.33.x`. But the above problem is till there.
current `brctl show` output of agent host: https://paste.ubuntu.com/p/D6w94qDRhR/
current `ifconfig` output of agent host: https://paste.ubuntu.com/p/WWJwvPjGpf/

**Comment by jl0x61** [comment]
I resolve this problem by switch to version 4.11.

**Comment by weizhouapache** [comment]
@jl0x61 
cloudstack 4.13.1 uses the same systemvm template as 4.11.3 (NOT 4.11.2 !!! )
you can find the template at http://download.cloudstack.org/systemvm/4.11/

please register 4.11.3 systemvm template, and try upgrade again.

**Comment by jl0x61** [comment]
@weizhouapache I tried your advice and it works. I think the [quickstart documentation](https://github.com/apache/cloudstack-documentation/blob/4.13.1.0/source/quickinstallationguide/qig.rst#system-template-setup) should be updated...

**Comment by weizhouapache** [comment]
> systemvm.iso

@EHerzog76 
systemvm.iso is not required any more since 4.17.0

In previous versions (prior to 4.17.0), systemvm.iso was a tarball which includes the systemvm scripts,configurations,etc, not the Debian ISO.

**Comment by EHerzog76** [comment]
Hello Wei,

Thank you for yor response.
Here you forgot to remove the old Code lines:
https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/manager/HypervManagerImpl.java

See Line Nr.: 168
      File srcIso = getSystemVMPatchIsoFile();

best regards
Erwin

**Comment by weizhouapache** [comment]
> Hello Wei,
> 
> Thank you for yor response. Here you forgot to remove the old Code lines: https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/hyperv/src/main/java/com/cloud/hypervisor/hyperv/manager/HypervManagerImpl.java
> 
> See Line Nr.: 168 File srcIso = getSystemVMPatchIsoFile();
> 
> best regards Erwin

@EHerzog76 
Hi Edwin, thanks for the reply.
Are you using hyperv ?

**Comment by EHerzog76** [comment]
Yes,

Because for one use case we need to run virtual Windows 10 and Windows 11 clients.
And it makes sense to run this systems on Windows Hyper-V Servers.

**Comment by weizhouapache** [comment]
> Yes,
> 
> Because for one use case we need to run virtual Windows 10 and Windows 11 clients. And it makes sense to run this systems on Windows Hyper-V Servers.

@EHerzog76 
does it work ? have you faced any other issues  ?

**Comment by EHerzog76** [comment]
No, it dose not work.

The problem is here:
    https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/hyperv/DotNet/ServerResource/HypervResource/WmiCallsV2.cs
     =>  public ComputerSystem AddUserData(ComputerSystem vm, string userData)
   Line-nr.: 93
   vmMgmtSvc.AddKvpItems  => WmiWrappers\ROOT.virtualization.v2.Msvm_VirtualSystemManagementService.cs
                 public uint AddKvpItems(string[] DataItems, System.Management.ManagementPath TargetSystem, out System.Management.ManagementPath Job)
                 => System.Management.ManagementBaseObject outParams = PrivateLateBoundObject.InvokeMethod("AddKvpItems", inParams, null);
                 The current Hyper-V version come back with the error code:  Invalid parameter (32773)
                 (Documentations of this function is here:   https://learn.microsoft.com/en-us/windows/win32/hyperv_v2/addkvpitems-msvm-virtualsystemmanagementservice )
               
Currently I found no work-a-round for this error !
I will fork your project and rewrite the function:
   public ComputerSystem AddUserData(ComputerSystem vm, string userData)
   
in this way:   Create a config.iso  disk with the needed data for cloud-init.
See here for more details:
  => https://cloudinit.readthedocs.io/en/19.3/topics/datasources/nocloud.html
  => https://cloudinit.readthedocs.io/en/19.3/topics/examples.html
  => https://cloudinit.readthedocs.io/en/19.3/topics/network-config-format-v2.html#network-config-v2

(The Openstack implementation is working. See here for the implementation details:  https://github.com/openstack/nova/blob/master/nova/virt/configdrive.py )

**Comment by weizhouapache** [comment]
> 

@EHerzog76 
thank you for the details !

It looks the cloudstack hyperv plugin is not well-maintained.
