### ISSUE TITLE
Many "Unknown API command" errors in version 4.11.3

### ISSUE THREAD

**Issue by jl0x61** [apache/cloudstack#4080]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3
~~~

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### SUMMARY

I installed Cloudstack 4.13.1 yesterday but the system VMs were stuck at "starting". 
So I switch to version 4.11.3 today. The system VMs is running correctly.
But there are many "Unknown API command" error when I click the management web UI. For example: 
+ When I click `Infrasturcture->Management Servers`, the error "Unkown API command: listManagementServers" occurs.
+ When I click `Templates->CentOS 5.5(64 bits) no GUI(KVM)`, the error "Unkown API command: listTemplateOvfProperties" occurs.

When I look up [API Reference of version 4.11.X](http://cloudstack.apache.org/api/apidocs-4.11/), thoes APIs doesn't exist actually. But why the web UI of 4.11.X invoke them?
##### STEPS TO REPRODUCE

~~~

Install CloudStack downloaded from http://download.cloudstack.org/ubuntu/dists/xenial/4.11/pool/
~~~

##### EXPECTED RESULTS

~~~
No "Unknown API command" error.
~~~

##### ACTUAL RESULTS

~~~
Many "Unknown API command" errors.
~~~

**Comment by rhtyd** [comment]
How did you switch back to 4.11.3? It appears the 4.13.1 UI was not removed, can you try reinstalling the 4.11.3 management server package?

**Comment by jl0x61** [comment]
@rhtyd I use `dpkg -P` to remove all the packages of 4.13.1 and install 4.11.3. 
I don't know the reson, so I go back to version 4.13.1 and it is running correctly now...
