### ISSUE TITLE
[4.15] Support of next versions

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4081]
There are some works in progress to support next software versions in 4.15

Here lists all tasks for better collaboration.

1. python2 -> python3 upgrade.
see #4068 Adding CentOS 8 Support

2. CentOS 8 as hypervisor
see #4068 Adding CentOS 8 Support

3. Ubuntu 20.04 as hypervisor and management server
see #4069 Ubuntu 20.04 support (as hypervisor)

4. MySQL 8 support
see #4051 db: add support for MySQL 8

5. Add guest os "CentOS 8"

6. Add guest os "Ubuntu 20.04"

7. support Ubuntu 20.04 as vm
an issue is fixed in #4070 Update cloud-set-guest-password.in
similar issue still exists in cloud-set-guest-sshkey.in

8. upgrade systemvm template to debian10
See #3797 appliance: upgrade to Debian 10 systemvmtemplate

9. upgrade python to python3 in VRs
See #3730 Update VR's scripts from python2 to python3

##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME
~~~
scripts, KVM, packaging
~~~

##### CLOUDSTACK VERSION
~~~
4.15
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@weizhouapache thanks but we already have the 4.15.0.0 milestone to track the PRs.
