### ISSUE TITLE
UEFI boot in Legacy mode corrupts VSphere connection.

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#4088]
When deplying a Virtual Box OVA to vmware and choosing Boot Type `Uefi` and Boot Mode `LEGACY`, the connection between cloudstack and VSphere is broken and won't recuperate untill a reboot of the VSphere machine

[vote thread report](https://lists.apache.org/thread.html/r82d49a9a013efa7eba2a8995f9d5208b7b5610c3d34338d7afbc2fe9%40%3Cdev.cloudstack.apache.org%3E)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Vmware
~~~

##### CLOUDSTACK VERSION

~~~
4.14 RC3
~~~

##### OS / ENVIRONMENT

ACS 4.14 rc
VMware 6.7u3

##### SUMMARY

connection from cloudstack to vsphere can be corrupted and the vsphere 443 made unavailable by submitting a wrong template in a certain way.

##### STEPS TO REPRODUCE

register a faulty template meant for virtualbox as a vmware OVA.
deploy using boot type `UEFI` and boot mode `LEGACY`.

~~~

~~~

##### EXPECTED RESULTS

~~~
`Unable to start a VM due to insufficient capacity` or an even more descriptive message after which one would be able to continue and deploy a suitable template
~~~

##### ACTUAL RESULTS

~~~
`Unable to create a deployment for VM[User|i-xx-yy-VM]` after which this message appears for all subsequent deployments.
~~~

**Comment by GabrielBrascher** [comment]
@DaanHoogland I assume that this issue happens only with VMware.

The UEFI implementation #3638 addressed VMware and KVM. Do you know if it has been tested and confirmed that this does not affect KVM as well?

**Comment by GabrielBrascher** [comment]
Not related with UEFI "only".
> register a faulty template meant for virtualbox as a vmware OVA.
> deploy using boot type UEFI and boot mode LEGACY.

Please, ignore my comment above.

**Comment by DaanHoogland** [comment]
This issue does not describe the issue correctly but as PRs and other references are based on it I will create a new one.
