### ISSUE TITLE
updateDiskOffering can't add/edit tag on existent disk Offering

### ISSUE THREAD

**Issue by RodrigoDLopez** [apache/cloudstack#4095]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
DiskOffering
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### SUMMARY

- Edit tag on diskOffering with `updateDiskOffering` command

##### STEPS TO REPRODUCE

~~~
Try to add or edit tags on existent diskOffering
~~~

##### EXPECTED RESULTS

~~~
ACS update tags on diskOffering
~~~

##### ACTUAL RESULTS

~~~
ACS is unable to edit tag due updateDiskOffering does not accept tag as parameter
~~~

**Comment by PranaliM** [comment]
Hi @RodrigoDLopez,
Can you pls. let know that is there any plan to fix this?

**Comment by RodrigoDLopez** [comment]
Hello, @PranaliM   
We have a fix for this issue, it was merged with this PR #4194 in version 4.15
I believe that users of cloud primate still cannot use this feature because we need to make changes to that project as well. However, my correction includes the standard graphical interface of the ACS.
Any other questions I am available.

**Comment by PranaliM** [comment]
Thanks @RodrigoDLopez, this helps.
Do we have a similar option for editing host tags in service offerings ? If not, could we consider adding that?

**Comment by RodrigoDLopez** [comment]
Hi @PranaliM 
I will make this... but we will need help to merge this enchantment.
maybe if you could review and run some tests when I finish my work

**Comment by PranaliM** [comment]
sure, @RodrigoDLopez. Thanks.
