### ISSUE TITLE
KVM: Change SystemVM patching to Qemu Fw Cfg

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#4112]
The systemvms are patching on KVM are currently performed patch.sh that uses qemu-agent-command (a serial-device mechanism) and consumed in the systemvms via qemu-guest-agent. Newer qemu versions (at least 2.2+) can make use of the qemu fw cfg device to pass key/value strings for the `cmdline` without using a more brittle/low-level approach much like XenServer and  VMware, and inside the systemvm they can consume the value for the `cmdline` at `/sys/firmware/qemu_fw_cfg/by_name/...` path which is available in newer kernels.

Refs:
https://github.com/qemu/qemu/blob/master/docs/specs/fw_cfg.txt
https://github.com/torvalds/linux/blob/master/drivers/firmware/qemu_fw_cfg.c

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
VR, SSVM, CPVM
~~~

**Comment by DaanHoogland** [comment]
@rhtyd are you talking of just the install time patching or live updates of the systemvm here?
and do you think we need to implement this before the next systemvm update?
