### ISSUE TITLE
CKS: Consider the UEFI for the VMs used as nodes

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4120]
##### ISSUE TYPE

 * Improvement Request

Purely as an enhancement, consider having the option to choose whether the master/worker nodes should use UEFI or BIOS on hypervisor side - if (and only if) it makes sense for the next-to-be-chosen OS for CKS (instead of CoreOS).

**Comment by DaanHoogland** [comment]
@shwstppr can you comment on this? And is general (cc @andrijapanicsb (-dont-use-this-one)) is it possible to auto discover whether a vm/template is uefi based?

**Comment by shwstppr** [comment]
@andrijapanicsb @DaanHoogland we can have look at this once #4329 is merged

**Comment by sureshanaparti** [comment]
> @andrijapanicsb @DaanHoogland we can have look at this once #4329 is merged

@shwstppr Any comments on this issue?

**Comment by shwstppr** [comment]
@sureshanaparti will try to explore this later in the week

**Comment by sureshanaparti** [comment]
> @sureshanaparti will try to explore this later in the week

thank you @shwstppr

**Comment by davidjumani** [comment]
Not sure if this issue is still valid. As of 416, the systemvm template is used for CKS nodes, and should be let to boot as is without any user intervention / requirement. The aim of CKS is to provide Kubernetes as a Service and not let the user worry about things like this
