### ISSUE TITLE
The internal instance name is returned for non-root admin in listVirtualMachineMetrics API

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4143]
The internal instance name is returned for non-root admin in listVirtualMachineMetrics API response but not in the listVirtualMachines API response.

We need to check and fix to ensure we only return the internal instance-name for root-admins only.

Tested on the Primate QA server against 4.14.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14 (tested), 4.13 (possibly)
~~~

**Comment by rhtyd** [comment]
cc @davidjumani please pick this one as well, thanks.

**Comment by onitake** [comment]
I'm not sure if making the API asymmetric is the best idea. IMHO, the returned values should be the same for everybody. Why is the internal name returned in the first place?

**Comment by rhtyd** [comment]
@onitake you're repeating the bug-report, sorry I didn't get your point?

**Comment by onitake** [comment]
Sorry @rhtyd , I didn't see that you were talking about two different API calls. My point wasn't about the asymmetry between listVirtualMachineMetrics and listVirtualMachines, but between root and non-root.
Wouldn't it be cleaner to return the same set of values for all types of users?

**Comment by rhtyd** [comment]
Np @onitake - not really because root admin should be able to know more infrastructure specific information, for example the host where the VM is running on but not to the normal user. Because of this, we need to return information for root admin for many APIs, but not for users.
