### ISSUE TITLE
The instance still stays in runing status after I shutdown the VMs.

### ISSUE THREAD

**Issue by fuchanghao** [apache/cloudstack#4151]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
Instance

##### CLOUDSTACK VERSION
4.14,0

##### CONFIGURATION
Simple test with this doc: https://docs.cloudstack.apache.org/en/4.14.0.0/quickinstallationguide/qig.html

##### OS / ENVIRONMENT
CentOS 7.8 (2003)

##### SUMMARY
When I type "sudo poweroff" in the VMs (KVM) , the instance still stays in runing status.

I tested CentOS 7 / Ubuntu 18.04.

##### EXPECTED RESULTS
Is that a bug or It's designed like this?

**Comment by rhtyd** [comment]
@fuchanghao the VM state usually syncs for out of band changes (such as a guest poweroff/shutdown or crash) within seconds/minutes. Can you check if your KVM host was in connected/Up state and did you wait for few seconds/minutes?
