### ISSUE TITLE
Remote Access VPN does not work

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4153]
Remote access vpn to a vpc public ip does not connect. it works for isolated networks. 

Error 789 on a windows machine.

**Comment by gaaray2k** [comment]
Jun 17 17:52:23 r-20-VM ipsec[915]: 13[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
Jun 17 17:52:23 r-20-VM ipsec[915]: 13[IKE] received FRAGMENTATION vendor ID
Jun 17 17:52:23 r-20-VM ipsec[915]: 13[ENC] received unknown vendor ID: fb:1d:e3:cd:f3:41:b7:ea:16:b7:e5:be:08:55:f1:20
Jun 17 17:52:23 r-20-VM charon: 13[IKE] received NAT-T (RFC 3947) vendor ID
Jun 17 17:52:23 r-20-VM ipsec[915]: 13[ENC] received unknown vendor ID: 26:24:4d:38:ed:db:61:b3:17:2a:36:e3:d0:cf:b8:19
Jun 17 17:52:23 r-20-VM charon: 13[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
Jun 17 17:52:23 r-20-VM charon: 13[IKE] received FRAGMENTATION vendor ID
Jun 17 17:52:23 r-20-VM charon: 13[ENC] received unknown vendor ID: fb:1d:e3:cd:f3:41:b7:ea:16:b7:e5:be:08:55:f1:20
Jun 17 17:52:23 r-20-VM charon: 13[ENC] received unknown vendor ID: 26:24:4d:38:ed:db:61:b3:17:2a:36:e3:d0:cf:b8:19
Jun 17 17:52:23 r-20-VM charon: 13[ENC] received unknown vendor ID: e3:a5:96:6a:76:37:9f:e7:07:22:82:31:e5:ce:86:52
Jun 17 17:52:23 r-20-VM charon: 13[IKE] 10.0.0.71 is initiating a Main Mode IKE_SA
Jun 17 17:52:23 r-20-VM charon: 13[ENC] generating ID_PROT response 0 [ SA V V V V ]
Jun 17 17:52:23 r-20-VM charon: 13[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (160 bytes)
Jun 17 17:52:23 r-20-VM charon: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (388 bytes)
Jun 17 17:52:23 r-20-VM charon: 16[ENC] parsed ID_PROT request 0 [ KE No NAT-D NAT-D ]
Jun 17 17:52:23 r-20-VM charon: 16[ENC] generating ID_PROT response 0 [ KE No NAT-D NAT-D ]
Jun 17 17:52:23 r-20-VM charon: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (372 bytes)
Jun 17 17:52:23 r-20-VM charon: 14[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:23 r-20-VM charon: 14[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:23 r-20-VM charon: 14[ENC] could not decrypt payloads
Jun 17 17:52:23 r-20-VM charon: 14[IKE] message parsing failed
Jun 17 17:52:23 r-20-VM charon: 14[ENC] generating INFORMATIONAL_V1 request 180943984 [ HASH N(PLD_MAL) ]
Jun 17 17:52:23 r-20-VM charon: 14[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:23 r-20-VM charon: 14[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:24 r-20-VM charon: 10[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:24 r-20-VM charon: 10[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:24 r-20-VM charon: 10[ENC] could not decrypt payloads
Jun 17 17:52:24 r-20-VM charon: 10[IKE] message parsing failed
Jun 17 17:52:24 r-20-VM charon: 10[ENC] generating INFORMATIONAL_V1 request 2197698318 [ HASH N(PLD_MAL) ]
Jun 17 17:52:24 r-20-VM charon: 10[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:24 r-20-VM charon: 10[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:25 r-20-VM charon: 08[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:25 r-20-VM charon: 08[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:25 r-20-VM charon: 08[ENC] could not decrypt payloads
Jun 17 17:52:25 r-20-VM charon: 08[IKE] message parsing failed
Jun 17 17:52:25 r-20-VM charon: 08[ENC] generating INFORMATIONAL_V1 request 3584470661 [ HASH N(PLD_MAL) ]
Jun 17 17:52:25 r-20-VM charon: 08[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:25 r-20-VM charon: 08[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:28 r-20-VM charon: 09[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:28 r-20-VM charon: 09[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:28 r-20-VM charon: 09[ENC] could not decrypt payloads
Jun 17 17:52:28 r-20-VM charon: 09[IKE] message parsing failed
Jun 17 17:52:28 r-20-VM charon: 09[ENC] generating INFORMATIONAL_V1 request 2647948745 [ HASH N(PLD_MAL) ]
Jun 17 17:52:28 r-20-VM charon: 09[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:28 r-20-VM charon: 09[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:35 r-20-VM charon: 07[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:35 r-20-VM charon: 07[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:35 r-20-VM charon: 07[ENC] could not decrypt payloads
Jun 17 17:52:35 r-20-VM charon: 07[IKE] message parsing failed
Jun 17 17:52:35 r-20-VM charon: 07[ENC] generating INFORMATIONAL_V1 request 1786459906 [ HASH N(PLD_MAL) ]
Jun 17 17:52:35 r-20-VM charon: 07[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:35 r-20-VM charon: 07[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:37 r-20-VM systemd[1]: Started Session 76 of user root.
Jun 17 17:52:50 r-20-VM charon: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:52:50 r-20-VM charon: 16[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:52:50 r-20-VM charon: 16[ENC] could not decrypt payloads
Jun 17 17:52:50 r-20-VM charon: 16[IKE] message parsing failed
Jun 17 17:52:50 r-20-VM charon: 16[ENC] generating INFORMATIONAL_V1 request 3997853721 [ HASH N(PLD_MAL) ]
Jun 17 17:52:50 r-20-VM charon: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:52:50 r-20-VM charon: 16[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:52:53 r-20-VM charon: 10[JOB] deleting half open IKE_SA after timeout
Jun 17 17:53:07 r-20-VM systemd[1]: Started Session 77 of user root.
Jun 17 17:53:37 r-20-VM systemd[1]: Started Session 78 of user root.
Jun 17 17:53:37 r-20-VM systemd[1]: Started Session 79 of user root.
Jun 17 17:54:07 r-20-VM systemd[1]: Started Session 81 of user root.
Jun 17 17:54:37 r-20-VM systemd[1]: Started Session 82 of user root.
Jun 17 17:54:44 r-20-VM charon: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (408 bytes)
Jun 17 17:54:44 r-20-VM charon: 16[ENC] parsed ID_PROT request 0 [ SA V V V V V V V V ]
Jun 17 17:54:44 r-20-VM charon: 16[ENC] received unknown vendor ID: 01:52:8b:bb:c0:06:96:12:18:49:ab:9a:1c:5b:2a:51:00:00:00:01
Jun 17 17:54:44 r-20-VM charon: 16[IKE] received MS NT5 ISAKMPOAKLEY vendor ID
Jun 17 17:54:44 r-20-VM charon: 16[IKE] received NAT-T (RFC 3947) vendor ID
Jun 17 17:54:44 r-20-VM charon: 16[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
Jun 17 17:54:44 r-20-VM charon: 16[IKE] received FRAGMENTATION vendor ID
Jun 17 17:54:44 r-20-VM charon: 16[ENC] received unknown vendor ID: fb:1d:e3:cd:f3:41:b7:ea:16:b7:e5:be:08:55:f1:20
Jun 17 17:54:44 r-20-VM charon: 16[ENC] received unknown vendor ID: 26:24:4d:38:ed:db:61:b3:17:2a:36:e3:d0:cf:b8:19
Jun 17 17:54:44 r-20-VM charon: 16[ENC] received unknown vendor ID: e3:a5:96:6a:76:37:9f:e7:07:22:82:31:e5:ce:86:52
Jun 17 17:54:44 r-20-VM charon: 16[IKE] 10.0.0.71 is initiating a Main Mode IKE_SA
Jun 17 17:54:44 r-20-VM charon: 16[ENC] generating ID_PROT response 0 [ SA V V V V ]
Jun 17 17:54:44 r-20-VM charon: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (160 bytes)
Jun 17 17:54:44 r-20-VM charon: 14[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (388 bytes)
Jun 17 17:54:44 r-20-VM charon: 14[ENC] parsed ID_PROT request 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:44 r-20-VM charon: 14[ENC] generating ID_PROT response 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:44 r-20-VM charon: 14[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (372 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 13[ENC] received unknown vendor ID: e3:a5:96:6a:76:37:9f:e7:07:22:82:31:e5:ce:86:52
Jun 17 17:54:44 r-20-VM ipsec[915]: 13[IKE] 10.0.0.71 is initiating a Main Mode IKE_SA
Jun 17 17:54:44 r-20-VM ipsec[915]: 13[ENC] generating ID_PROT response 0 [ SA V V V V ]
Jun 17 17:54:44 r-20-VM ipsec[915]: 13[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (160 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (388 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 16[ENC] parsed ID_PROT request 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:44 r-20-VM ipsec[915]: 16[ENC] generating ID_PROT response 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:44 r-20-VM ipsec[915]: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (372 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[ENC] could not decrypt payloads
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[IKE] message parsing failed
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[ENC] generating INFORMATIONAL_V1 request 180943984 [ HASH N(PLD_MAL) ]
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 14[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[ENC] could not decrypt payloads
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[IKE] message parsing failed
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[ENC] generating INFORMATIONAL_V1 request 2197698318 [ HASH N(PLD_MAL) ]
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:44 r-20-VM ipsec[915]: 10[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[ENC] generating INFORMATIONAL_V1 request 3584470661 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 08[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[ENC] generating INFORMATIONAL_V1 request 2647948745 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM charon: 08[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 09[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[ENC] generating INFORMATIONAL_V1 request 1786459906 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 07[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] generating INFORMATIONAL_V1 request 3997853721 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM ipsec[915]: 10[JOB] deleting half open IKE_SA after timeout
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (408 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] parsed ID_PROT request 0 [ SA V V V V V V V V ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] received unknown vendor ID: 01:52:8b:bb:c0:06:96:12:18:49:ab:9a:1c:5b:2a:51:00:00:00:01
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] received MS NT5 ISAKMPOAKLEY vendor ID
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] received NAT-T (RFC 3947) vendor ID
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] received FRAGMENTATION vendor ID
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] received unknown vendor ID: fb:1d:e3:cd:f3:41:b7:ea:16:b7:e5:be:08:55:f1:20
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] received unknown vendor ID: 26:24:4d:38:ed:db:61:b3:17:2a:36:e3:d0:cf:b8:19
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] received unknown vendor ID: e3:a5:96:6a:76:37:9f:e7:07:22:82:31:e5:ce:86:52
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[IKE] 10.0.0.71 is initiating a Main Mode IKE_SA
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[ENC] generating ID_PROT response 0 [ SA V V V V ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 16[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (160 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 14[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (388 bytes)
Jun 17 17:54:45 r-20-VM ipsec[915]: 14[ENC] parsed ID_PROT request 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:45 r-20-VM ipsec[915]: 14[ENC] generating ID_PROT response 0 [ KE No NAT-D NAT-D ]
Jun 17 17:54:45 r-20-VM charon: 08[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM ipsec[915]: 14[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (372 bytes)
Jun 17 17:54:45 r-20-VM charon: 08[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM charon: 08[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM charon: 08[ENC] generating INFORMATIONAL_V1 request 1195808344 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM charon: 08[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM charon: 08[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:45 r-20-VM charon: 10[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:45 r-20-VM charon: 10[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:45 r-20-VM charon: 10[ENC] could not decrypt payloads
Jun 17 17:54:45 r-20-VM charon: 10[IKE] message parsing failed
Jun 17 17:54:45 r-20-VM charon: 10[ENC] generating INFORMATIONAL_V1 request 1025308458 [ HASH N(PLD_MAL) ]
Jun 17 17:54:45 r-20-VM charon: 10[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:45 r-20-VM charon: 10[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:46 r-20-VM charon: 11[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:46 r-20-VM charon: 11[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:46 r-20-VM charon: 11[ENC] could not decrypt payloads
Jun 17 17:54:46 r-20-VM charon: 11[IKE] message parsing failed
Jun 17 17:54:46 r-20-VM charon: 11[ENC] generating INFORMATIONAL_V1 request 95893030 [ HASH N(PLD_MAL) ]
Jun 17 17:54:46 r-20-VM charon: 11[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:46 r-20-VM charon: 11[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:49 r-20-VM charon: 05[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:49 r-20-VM charon: 05[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:49 r-20-VM charon: 05[ENC] could not decrypt payloads
Jun 17 17:54:49 r-20-VM charon: 05[IKE] message parsing failed
Jun 17 17:54:49 r-20-VM charon: 05[ENC] generating INFORMATIONAL_V1 request 538623411 [ HASH N(PLD_MAL) ]
Jun 17 17:54:49 r-20-VM charon: 05[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:49 r-20-VM charon: 05[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:54:56 r-20-VM charon: 12[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:54:56 r-20-VM charon: 12[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:54:56 r-20-VM charon: 12[ENC] could not decrypt payloads
Jun 17 17:54:56 r-20-VM charon: 12[IKE] message parsing failed
Jun 17 17:54:56 r-20-VM charon: 12[ENC] generating INFORMATIONAL_V1 request 1771938155 [ HASH N(PLD_MAL) ]
Jun 17 17:54:56 r-20-VM charon: 12[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:54:56 r-20-VM charon: 12[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:55:07 r-20-VM systemd[1]: Started Session 84 of user root.
Jun 17 17:55:11 r-20-VM charon: 15[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:55:11 r-20-VM charon: 15[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:55:11 r-20-VM charon: 15[ENC] could not decrypt payloads
Jun 17 17:55:11 r-20-VM charon: 15[IKE] message parsing failed
Jun 17 17:55:11 r-20-VM charon: 15[ENC] generating INFORMATIONAL_V1 request 2979378132 [ HASH N(PLD_MAL) ]
Jun 17 17:55:11 r-20-VM charon: 15[NET] sending packet: from 10.0.0.247[500] to 10.0.0.71[500] (76 bytes)
Jun 17 17:55:11 r-20-VM charon: 15[IKE] ID_PROT request with message ID 0 processing failed
Jun 17 17:55:14 r-20-VM charon: 10[JOB] deleting half open IKE_SA after timeout
Jun 17 17:55:37 r-20-VM systemd[1]: Started Session 85 of user root.
Jun 17 17:56:07 r-20-VM systemd[1]: Started Session 86 of user root.

**Comment by gaaray2k** [comment]
I keep getting this

Jun 17 17:55:11 r-20-VM charon: 15[NET] received packet: from 10.0.0.71[500] to 10.0.0.247[500] (76 bytes)
Jun 17 17:55:11 r-20-VM charon: 15[ENC] invalid ID_V1 payload length, decryption failed?
Jun 17 17:55:11 r-20-VM charon: 15[ENC] could not decrypt payloads
Jun 17 17:55:11 r-20-VM charon: 15[IKE] message parsing failed

**Comment by andrijapanicsb** [comment]
These kinds of tickets with zero information about the env setup, version of ACS, VPC setup (do you have s-2-s VPN as well - there is a known bug in 4.11+, will be fixed in 4.15), etc - will just get ignored by people... Consider updating it.

**Comment by gaaray2k** [comment]
yes, I think i hit the bug. it works when I remove the s-2s vpn tunnel. ACS 4.14 one controller and two compute nodes. I am just testing in my home lab for now.

**Comment by andrijapanicsb** [comment]
Great – that is a known bug, already logged – and will be fixed in 4.15 (summer LTS release).

**Comment by gaaray2k** [comment]
I am checking it out because I want to advertize it to my customers, but I need to make sure everything works as expected before I do so. I guess I am going to have to wait.

**Comment by gaaray2k** [comment]
it looks like it was fixed in 4.15 but there is another issue. when connecting to the vpn, the v-router is setting a default route pointing to the vpn. this is causing all the traffic to go over the vpn, breaking internet access. it would be best to make so only the 10.1.2.0/24 route is being routed over the tunnel.

**Comment by andrijapanicsb** [comment]
@gaaray2k you've already tested this, right? I assume this is different behaviour to how it worked before (the routing thing/issue)?

/cc @DaanHoogland @rhtyd

**Comment by gaaray2k** [comment]
I tested it. I can connect to the vpn while I have the vpn site to site connected. so the original issue has been solved. the problem is now that while connected to a remote access vpn all the traffic is pointing to the vpn tunnel so desktops lose internet connectivity. I think it should just be the the cloudstack network subnet pointing to the vpn. I think the config below would fix it.
root@r-201-VM:~# vi /etc/ipsec.d/l2tp.conf 

#ipsec remote access vpn configuration
conn L2TP-PSK
        authby=secret
        rekey=no
        keyingtries=3
        leftfirewall=yes
        type=transport
        #
        # ----------------------------------------------------------
        # The VPN server.
        #
        # Allow incoming connections on the external network interface.
        # If you want to use a different interface or if there is no
        # defaultroute, you can use:   left=your.ip.addr.ess
        #
 left=192.168.11.248
        #
        leftprotoport=udp/l2tp
        # If you insist on supporting non-updated Windows clients,
        # you can use:    leftprotoport=17/%any
        #
        # ----------------------------------------------------------
        # The remote user(s).
        #
        # Allow incoming connections only from this IP address.
        right=%any
        # If you want to allow multiple connections from any IP address,
        # you can use:    right=%any
        #
        rightprotoport=udp/%any
        #
        # ----------------------------------------------------------
        # Change 'ignore' to 'add' to enable this configuration.
        #
        rightsubnetwithin=0.0.0.0/0
        rightsubnetwithin=THIS SHOULD BE the NETWORK SUBNET NOT 0.0.0.0/0
        auto=route

**Comment by andrijapanicsb** [comment]
@gaaray2k your are saying that all of your desktop (client's) internet traffic is now going over VPN?
If not mistaken, that depends on how you configure your route on the Windows client  - i.e. in order to reach the VPC networks (the whole VPC CIDR range) - you have 2 options (from what I can remember when I was actively using this as a "client")
- Tick the "Send/Route all traffic over the remote gateway" in the properties of the VPN connection on Windows/client
- Untick that box, but then you need to add routes to VPC CIDR to go over the Remote VPN tunnel

I don't see this being different now - or do I miss something from your report?

thx

**Comment by gaaray2k** [comment]
shoot. I forgot about that. it works now. my bad.

**Comment by gaaray2k** [comment]
how can I disable the make redundant option when restarting a network or vpc?

**Comment by andrijapanicsb** [comment]
Phew, good...

That one is a question for the ML not here :) but - you can't via UI.

Go to table "vpc" or "network" and replace 1 with 0 in the  "redundant" field - then destroy both VRs of the network/VPC - and then restart the network with cleanup (but don't tick the Make redundant checkbox)

Cheers,

**Comment by gaaray2k** [comment]
ok. thats a hack. but it would be nice to do it via the UI. also I wanted to disabled all together. I was looking into the webapp to see if I could just remove the form item from the code, but I guest I am not that good.

**Comment by andrijapanicsb** [comment]
Ah the "option" to make it redundant? No way, for now.
