### ISSUE TITLE
health check gateways_check.py for redundant VR will fail for BACKUP router

### ISSUE THREAD

**Issue by Doni7722** [apache/cloudstack#4163]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Health Checks on VR
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0 LTS
~~~

##### CONFIGURATION

advanced networking with public link on VR

##### OS / ENVIRONMENT

VMWare Hypervisor (may happens on other hypervisor as well)

##### SUMMARY

If you deploy redundant VRs the Backup VR will set the public interface to DOWN until it gets MASTER. As long as he is BACKUP the gateways_check.py will fail as the link is DOWN.

##### STEPS TO REPRODUCE

~~~
deploy redundant VR and execute the health checks. gateways_check.py will never pass on the BACKUP VR.
~~~

##### EXPECTED RESULTS

~~~
As this is an expected behavior the health checks should check the state the VR and in case of BACKUP exclude this check.
~~~

##### ACTUAL RESULTS

~~~
Health Checks will fail and fill up the alerts with error messages.
~~~

**Comment by rhtyd** [comment]
@shwstppr can you have a look at this issue; we also might want to reduce the INFO logging on VR checks
