### ISSUE TITLE
local iso upload failed

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#4169]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.13
4.14
~~~

##### SUMMARY

After the default installation, users cannot upload ISO to cloudstack from the UI.
Error ：
Failed to upload file due to system misconfiguration. Please contact admin.

I learned from the documentation (https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=39620237) that for ISO local upload, HTTPS must be used.

By default (users do not enable cloudstack ssl), ssvm will use the *.realhostip.com certificate (this certificate has expired in 2017)
Due to a certificate error, chrome(ie) will issue a warning and must be confirmed by the user before accessing the corresponding page.
So if you want to implement local iso upload without configuring SSL, you must first use the browser to request the public IP of SSVM,
For example: https://10.228.18.64
Click Continue when the browser issues a warning.
Then you can upload ISO on cloudstack ui.

Can we remove this restriction on https? (For example, HTTPS is optional)
I think many users will encounter this problem when they first deploy.
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Probably display a more meaningful message in the form when upload fails

**Comment by rhtyd** [comment]
@div8cn turns out we cannot check if the URL/server has a valid SSL certificate from javascript without using any external tool/service; it's therefore advised to use this feature use SSL enabled env. Alternatively, we can explore a fix in future that allows uploading on http:// URL for envs where SSL is not enabled by default.

**Comment by andrijapanicsb** [comment]
I would not trade security for convenience - thus I wild propose this stays as it is - requiring HTTPS end point on SSVM.

**Comment by rohityadavcloud** [comment]
Closing as we require proper SSL/TLS certificate to be configured to use this feature.
