### ISSUE TITLE
Centos7 RPM packages are x86_64 should be noarch

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4170]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
Centos Packaging
~~~

##### CLOUDSTACK VERSION

~~~
4.13 / 4.14
~~~

##### OS / ENVIRONMENT

Centos 7 / ARM / Raspberry pi

##### SUMMARY

Raspberry PIs computing capabilities are growing exponentially. I was planning on using a Raspbery Pi 8GB as cloudstack-manager for a small/lab cloudstack deployment (around 10 hosts).  

Platforms supported by Apache CS, such as Centos and Ubuntu are also becoming mature on these ARM devices.

I notice that Centos 7 RPM packages are labelled x86_64, but I am not sure that is correct, at least the main java component could be platform independent: noarch. 

##### STEPS TO REPRODUCE

~~~
Install Centos 7 on RPI4
Add Apache CS repo
yum install cloudstack-management
~~~

##### EXPECTED RESULTS

~~~
cloustack-management installation starts.
~~~

##### ACTUAL RESULTS

~~~
No package cloudstack-management available.
~~~

**Comment by rhtyd** [comment]
@rvalle qemu, kvm and kernel on centos7 are very old to support VMs on aarch64. You probably want to try Ubuntu 20.04 instead, try this instead https://rohityadav.cloud/blog/cloudstack-rpi4-kvm/

**Comment by rvalle** [comment]
@rhtyd thanks, will test with ubuntu. 

I was not really looking to virtualize but just to run the management from RPI.

**Comment by rhtyd** [comment]
Closing this, official packages are x86_64 only
