### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4179]
Simple question. what is the purpose of regions? I added a second CS instance to my setup, mgmt,compute and db. I followed the documentation to add my two CS environments as region to each other. I can see that region A has been added to region B and vice versa, but I dont see resources from region A on region B or from region B on region A. if I log into region A mgmt UI and try to create an instance, am I supposed to get an option to choose a zone from region B if I want to create an instance there?

I assumed it was similar to a public cloud like AWS where you can choose different datacenters from a single web UI. am I wrong?

**Comment by rhtyd** [comment]
This is largely an unsupported feature, right now it's serves as a bookmark to other mgmt server. Please ask questions or discuss them on the users ML list instead: http://cloudstack.apache.org/mailing-lists.html

Thanks.
