### ISSUE TITLE
Quota API don't honour pagination and searching

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4181]
quotaSummary and quotaTariffList don't honour pagination and keyword/searching

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Quota Plugin
~~~

**Comment by rhtyd** [comment]
Minor issue please see @davidjumani

**Comment by davidjumani** [comment]
Would this also need to add search functionality in quotaTariffList? Since it only has a fixed list of 25 tariff types
