### ISSUE TITLE
python3-mysql.connector package needed for running on Ubuntu20.04

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack#4185]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Management server
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0
~~~

##### OS / ENVIRONMENT

Ubuntu 20.04

##### SUMMARY

Unable to install Cloudstack managment server on Ubuntu20.04 as it depends on `python-mysql.connector` but this cant be installed on Ubuntu20.04. So should we upgrade the package to `python3-mysql.connector` ?
This worked fine for me in my test setup. I was not able to install `python-mysql.connector` even after adding necessary repos.

@weizhouapache @rhtyd @wido @DaanHoogland any suggestions?

##### STEPS TO REPRODUCE

~~~
1. Create a vm on Ubuntu20.04
2. Try to install 4.14 or onward version of cloudstack-management package
3. It fails as it depends on `python-mysql.connector` which cant be installed.
~~~

##### EXPECTED RESULTS

~~~
Expected management package to be installed
~~~

##### ACTUAL RESULTS

~~~
Installation failed as it depends on `python-mysql.connector`
~~~

**Comment by weizhouapache** [comment]
@ravening ubuntu 20.04 is not supported by cloudstack 4.14

I have a draft PR for ubuntu 20.04 support in cloudstack 4.14 https://github.com/apache/cloudstack/pull/4069
Shapeblue guys are working a huge improvement which contains ubuntu 20.04 support for cloudstack 4.15/master https://github.com/apache/cloudstack/pull/4068

**Comment by rhtyd** [comment]
@ravening as Wei advised; we've merged Wei's commits from #4069 to consolidate our testing across various permutations/combinations in #4068 that adds support for newer distros (centos8, ubuntu 20.04) to be used both as mgmt/usage server host and KVM hosts.

**Comment by ravening** [comment]
closing the issue

**Comment by wido** [comment]
> Is there a way to depend on `python3-mysqldb` and not on `python-mysql.connector`? It would be great to install Management Server on Debian.

No, as they are really different MySQL connectors for Python. So that will not work.
