### ISSUE TITLE
Migration not working in ACS 4.14 with Basic Network - VMware Local storage

### ISSUE THREAD

**Issue by ccycv** [apache/cloudstack#4187]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management - unfinished process
~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.14 Upgraded from 4.11.
~~~

##### CONFIGURATION

ACS 4.14 Basic Networking with VMware 6.0, 6.5 ( tested with different VMware version)

##### OS / ENVIRONMENT

CentOS Linux release 7.8.2003 (Core)

##### SUMMARY

Migrating VM with local storage it is not working, getting successfully feedback notification in UI but it is unfinished.

##### STEPS TO REPRODUCE

~~~
1. Stop VM
2. Migrate instance to another primary storage
2. Start VM
3. Fail
~~~

##### EXPECTED RESULTS

~~~
No issue
~~~

##### ACTUAL RESULTS

~~~
Screenshot : https://imgur.com/a/t50qL0z
Log part  (2. Migrate instance to another primary storage) : https://gist.github.com/ccycv/0a7f75a5ae9c4782ba9a5d4568605ba2

I have also found a temporary workaround:

    1. Stop VM
    2. Migrate to the destination storage 
    3. Start VM from UI and select destination host, at this point I get this error : File []/vmfs/volumes/5ef5902c-83b77eaa-5143-b4a9fc1bb3ae/i-2-1497-VM/ROOT-1497.vmdk was not found
    4. If i check the destination is see the VM folder and vmx, vmsd, hlog files but no .vmdk file.
    5. I do a manually copy for this file : ROOT-1497.vmdk, from initial source to : vmfs/volumes/5ef5902c-83b77eaa-5143-b4a9fc1bb3ae/i-2-1497-VM/
   6. Start VM, everything works.

Here we can see the error  which I get when I start the VM I get before migrating manually the vmdk file : https://pastebin.com/VcEtV7R3
~~~

**Comment by DaanHoogland** [comment]
@ccycv can youtest this with 4.15 please?

**Comment by ccycv** [comment]
> @ccycv can youtest this with 4.15 please?

After the upgrade I will test asap and let you know.

**Comment by ccycv** [comment]
> @ccycv can youtest this with 4.15 please?

I still have the same issue, "failed to get message for exception: File []/vmfs/volumes/5ef5902c-83b77eaa-5143-b4a9fc1bb3ae/i-2-1583-VM/ROOT-1583.vmdk was not found"

1. Stop the VM
2.  Migrate storage
3.  Start VM - here I get the error, vmdk was not found.

**Comment by ccycv** [comment]
> @ccycv can youtest this with 4.15 please?

I still have the same issue, "failed to get message for exception: File []/vmfs/volumes/5ef5902c-83b77eaa-5143-b4a9fc1bb3ae/i-2-1583-VM/ROOT-1583.vmdk was not found"

1. Stop the VM
2. Migrate storage
3. Start VM - here I get the error, vmdk was not found.

**Comment by DaanHoogland** [comment]
@harikrishna-patnala @nvazquez can you comment?

**Comment by nvazquez** [comment]
@weizhouapache can you please check this issue?

**Comment by weizhouapache** [comment]
@nvazquez I was not able to create a vmware basic zone with local storage for testing. for vmware basic zone with shared storage, it works in my testing.

@shwstppr I noticed that you have made some improvement for vm migration on vmware in #4385, could you please have a look at this issue ? might it be fixed already?

**Comment by shwstppr** [comment]
@weizhouapache will try to have a look.
@ccycv is it possible to test 4.15.1 to reproduce it? Other  than #4385 , VMware migration improvements were also made with #4895 & #4758

**Comment by weizhouapache** [comment]
> @weizhouapache will try to have a look.
thanks @shwstppr .
> @ccycv is it possible to test 4.15.1 to reproduce it? Other than #4385 , VMware migration improvements were also made with #4895 & #4758

@ccycv could you please test cloudstack 4.15.1 ?

**Comment by ccycv** [comment]
> > @weizhouapache will try to have a look.
> 
> thanks @shwstppr .
> 
> > @ccycv is it possible to test 4.15.1 to reproduce it? Other than #4385 , VMware migration improvements were also made with #4895 & #4758
> 
> @ccycv could you please test cloudstack 4.15.1 ?

I just upgraded to 4.15.1 and tested the upgrade, works as expected! great job guys!
