### ISSUE TITLE
NioTest fails on fresh install of Fedora due to RSA key size < 2048

### ISSUE THREAD

**Issue by Spaceman1984** [apache/cloudstack#4189]
On a fresh installation of Fedora 31, running the NioTest will fail. This is due to Fedora using 2048 as the minimum allowed size for a RSA key and cloudstack generates a 1024 size key.

An upgrade has to be made to the certificate key size Cloudstack uses for the test as 2048 is the recommended size for RSA keys at the moment and other operating systems will likely make this a requirement as well.

I have verified the key size requirement in the following files: 
/usr/share/crypto-policies/DEFAULT/java.txt
/usr/share/crypto-policies/FIPS/java.txt
/usr/share/crypto-policies/NEXT/java.txt

The NioTest passes when changing the RSA keySize to < 1024, but this doesn't address the issue of Cloudstack generating a less secure certificate.
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
NioTest
~~~

##### CLOUDSTACK VERSION

~~~
Tested on 4.13.0.2
~~~

##### OS / ENVIRONMENT

Fedora 31
Cloudstack 4.13 branch
Java 1.8
Python 2.7

##### STEPS TO REPRODUCE

 

~~~
Do a fresh install of Fedora, 
Install Java 8
Install python2.7
Install git
Install maven

Clone Cloudstack 4.13 branch

Run mvn install -Pdeveloper,systemvm
~~~

##### EXPECTED RESULTS

~~~
Tests pass
~~~

##### ACTUAL RESULTS

~~~
Tests fail
~~~

**Comment by rhtyd** [comment]
I think @shwstppr has addressed this in his PR #4068 ?

**Comment by shwstppr** [comment]
@Spaceman1984 here https://github.com/apache/cloudstack/pull/4068/files#diff-a24703d95ef24543c23939815013558a cc @rhtyd 

I used a 2048-bit key. Do we need to use even higher for future-proofing?

**Comment by Spaceman1984** [comment]
@shwstppr I think 2048 is fine for now, I don't think the recommended size will change very soon. This issue may be closed once your PR is merged.

**Comment by rhtyd** [comment]
Addressed in https://github.com/apache/cloudstack/pull/4068/files#diff-a24703d95ef24543c23939815013558a
