### ISSUE TITLE
Tests fail with XenServer/XCP-ng later than 7.1 (maybe they are fine iw

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4192]
Automated regression test that we run for each PR with  @ blueorangutan, etc, fails miserably for (as it seems) any XS/XPC-ng version newer than 7.1 - at least for 7.6 and onwards.

Please take this PR as the reference - I've started a few XS/XCP-ng combinations there (xs74, xpcng7.6/8.0/8.1): https://github.com/apache/cloudstack/pull/4114  (it's a closed PR though, but relevant enough)

As it seems, we have never really tested and got clean results with anything newer than XenServer 7.1 (and tests for XS 7.1 still works fine, with a single known failure due to licencing) - that is my conclusion after reviewing the PRs where we added support for XS 7.1/7.2, XS/XCPng 7.4/7.5/7.6

**Comment by andrijapanicsb** [comment]
@shwstppr @rhtyd @sureshanaparti @Pearl1594 @nvazquez @PaulAngus /CC @borisstoyanov

**Comment by rhtyd** [comment]
@andrijapanicsb is this still a blocker?

**Comment by andrijapanicsb** [comment]
Nope @rhtyd this one can be closed - I've opened 1 or 2 new ones, more minor, as the redudant_vpc test is consistently failing on XCP 7.6 and 8.0 (sometimes works fine/no errors when run manually from the Marvin box) - but the same doesn't fail (haven't seen it fail) with XS 7,1
