### ISSUE TITLE
Count mismatch for list diskofferings api

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack#4195]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, Server
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0
~~~

##### OS / ENVIRONMENT

Ubuntu16

##### SUMMARY

The count value returned by listDiskofferings api is different from total number of actual returned elements.

##### STEPS TO REPRODUCE

~~~
1. Create a domain under ROOT called "test1"
2. Create a child domain for "test1" called "test1-child"
3. Create disk offerings ONLY for the domain "test1-child"
4. Login as "test1" domain in cloudmonkey using cloudmonkey -p test1
5. Run the list diskofferings command with and without isrecursive flag
~~~

##### EXPECTED RESULTS

~~~
Without isrecursive flag I should see a total of 9 items returned as the count says 9
With isrecursive flag set to true, I should see a total of 9 elements returned as the count says 9
~~~

##### ACTUAL RESULTS

~~~
Without isrecursive flag I see only 6 elements returned

(test1) 🐵 > list diskofferings filter=name
{
  "count": 9, <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  "diskoffering": [
    {
      "name": "Small"
    },
    {
      "name": "Medium"
    },
    {
      "name": "Large"
    },
    {
      "name": "Custom"
    },
    {
      "name": "root-offering"
    },
    {
      "name": "test1"
    }
  ]
}



With isrecursive=true, I see 8 items returned

(test1) 🐵 > list diskofferings filter=name isrecursive=true
{
  "count": 9,  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  "diskoffering": [
    {
      "name": "Small"
    },
    {
      "name": "Medium"
    },
    {
      "name": "Large"
    },
    {
      "name": "Custom"
    },
    {
      "name": "test-11"
    },
    {
      "name": "test1"
    },
    {
      "name": "test-11-only"
    },
    {
      "name": "child-domain-test-11"
    }
  ]
}
~~~

@rhtyd @shwstppr 

what should the `count` variable contain here?

In the code `server/src/main/java/com/cloud/api/query/QueryManagerImpl.java` function `searchForDiskOfferingsInternal`, I see that if `isrecursive=true` is passed, it is doing some filtering on the list but it does not return the final size of the list instead it returns the initial size of the list

```
 return new Pair<>(result.first(), result.second());
```

Instead, it should return 
```
return new Pair<>(result.first(), result.first().size());
```

**Comment by shwstppr** [comment]
@ravening as per my understanding it cannot always return `result.first.size()`. Second parameter is total count while count of first will be pageSize.

Though your issue seems a real bug. It should return correct size for `isrecursive=true`. It seems to be including parent domains in count.

**Comment by DaanHoogland** [comment]
@ravening , @davidjumani did some improvcements in this respect fr 4.15 (I'll link the pull if i get time to find it) can you try with 4.15 please?

**Comment by DaanHoogland** [comment]
@ravening can you look if #4374 solves your problem? closing for now, but please reopen if you feel it is still an issue.

**Comment by ravening** [comment]
> @ravening can you look if #4374 solves your problem? closing for now, but please reopen if you feel it is still an issue.

@DaanHoogland that fix doesnt solve the issue. Can you please reopen the issue again as its being tracked by another pr?

**Comment by DaanHoogland** [comment]
>  I dont have permission to reopen this issue

strange, it is yours. but here you go.

**Comment by DaanHoogland** [comment]
@ravening , can you link the PR with the "Linked pull requests" item on the right, please?

**Comment by ravening** [comment]
> @ravening , can you link the PR with the "Linked pull requests" item on the right, please?

@DaanHoogland since you closed it, I wont have permission to reopen it. I dont have the permission to link the pr also but here is the pr https://github.com/apache/cloudstack/pull/5307

**Comment by rohityadavcloud** [comment]
Looks like this https://github.com/apache/cloudstack/pull/5307 fixed it? Pl re-open or ping if that's not the case.
