### ISSUE TITLE
Kubernetes container service: coreos is EOL

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4198]
On May 26, 2020, CoreOS Container Linux will reach its end of life and will no longer receive updates. We strongly recommend that users begin migrating their workloads to another operating system as soon as possible.

https://coreos.com/os/eol/

##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

~~~
Kubernetes container service
~~~

##### CLOUDSTACK VERSION

~~~
4.14/4.15
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
following @Pearl1594 @shwstppr

**Comment by rhtyd** [comment]
We're exploring alternative with https://www.flatcar-linux.org/releases/

**Comment by rhtyd** [comment]
@Pearl1594 may update her findings, we compared FlatCar vs Alpine vs Debian and it may make sense to reuse a Debian based template that's common for systemvm, and CKS host.

**Comment by rhtyd** [comment]
Closing this, we've the PR https://github.com/apache/cloudstack/pull/4329
