### ISSUE TITLE
VM pass not getting reset

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4203]
When I request a password reset for a virtual machine, the password isnt getting reset. vm logs show that it cant get the password from the VR. is this a known issue?

 I downloaded the password script an placed it in /bin and applied the correct permissions. it looks like the password is being saved in the VR but not being sent to the vm. Please see attached screenshots. please let me know if there is more info you need me to provide.

![VM](https://user-images.githubusercontent.com/67025242/86544997-6f337980-bef9-11ea-9ca7-ddccfd399c40.PNG)
![vr](https://user-images.githubusercontent.com/67025242/86545000-722e6a00-bef9-11ea-99c4-a9542ea56359.PNG)

CS version: 4.14
VM OS: centos 7

**Comment by ravening** [comment]
I encountered same issue with centos5 but didnt face this issue with ubuntu

**Comment by DaanHoogland** [comment]
@gaaray2k is the VM based on a tamplate that contains (the right version of) cloud_init?
This is not a known issue but please add some explanation of the screenshots in your description. also please recheck with the latest versions to see if it still a problem.

**Comment by DaanHoogland** [comment]
@gaaray2k closing now, please feel free to re-open or re-submit
