### ISSUE TITLE
Test issue: ipmisim/pyghmi does not work with CentOS8 patched ipmitool

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4204]
During marvin testing it was found that the ipmitool on CentOS8 has patches that no longer works with `ipmisim` test utility. This does not mean that OOBM may not work with CentOS8 management servers, which may need further testing with an actual BMC. The `ipmisim` utility uses `pyghmi` from OpenStack and may need bugfixes/refactoring that is out of scope of CloudStack project.

The difference seems to be some patches on CentOS8 build, while the version on both CentOS8, CentOS7, Ubuntu 20.04 are `ipmitool version 1.8.18`, on CentOS7, Ubuntu 20.04 it works.

Until this is fixed oobm related simulator tests (using ipmisim) can be skipped in Marvin. 

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Testing/library
~~~

**Comment by rhtyd** [comment]
Workaround - install the CentOS 8.1.1911 1.8.18-12 rpm: (the 1.8.18-14 rpm does not work with latest)
https://rpmfind.net/linux/centos/8.1.1911/AppStream/x86_64/os/Packages/ipmitool-1.8.18-12.el8_1.x86_64.rpm

**Comment by rhtyd** [comment]
@shwstppr I think the best way would be to document this, send a doc PR and for Trillian just install the 1.8.18-12 rpm (instead of 1.8.18-14 rpm)

**Comment by rhtyd** [comment]
With @shwstppr

**Comment by rhtyd** [comment]
@shwstppr pl send a doc PR on this to cloudstack-documentation website

**Comment by rhtyd** [comment]
Doc PR merged - https://github.com/apache/cloudstack-documentation/pull/165

**Comment by DaanHoogland** [comment]
@rhtyd I saw a deployment failing based on this. I than tried 1.8.18-17 but this also failed. Next I removed all explicit setting of IPMiTools and it is running now, will update this comment with results.

**Comment by rhtyd** [comment]
cc @shwstppr ^^

**Comment by DaanHoogland** [comment]
update: @Pearl1594 created an setup with ipmitool-1.8.18-12.el8_1.x86_64.rpm
 and I tried with the explicit update of ipmitool removed. Both seem to start.
