### ISSUE TITLE
Behavior of vm.instancename.flag not as expected/documented

### ISSUE THREAD

**Issue by mib1185** [apache/cloudstack#4206]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware plugin
~~~

##### CLOUDSTACK VERSION

~~~
4.13.0
~~~

##### CONFIGURATION

~~~
vCenter-Version: 6.7.0, 15976728
vSphere-Version: ESXi, 6.7.0, 10302608

`vm.instancename.flag` = `true`
~~~

##### SUMMARY

Behavior of global parameter `vm.instancename.flag` has been changed with 51ee90074d5b53be261dcc746e4bd8a1058dfb6a and therefore does not work as expected by documentation http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html#id2

##### STEPS TO REPRODUCE

~~~
- set `vm.instancename.flag` to `true`
- reboot management instance
- create new instance via WebUI on VMware powered zone with provided "Name (Optional) = dummy-03"
~~~

##### EXPECTED RESULTS

~~~
Name on vCenter = i-<user_id>-<vm_id>-displayName
Internal Name = i-<user_id>-<vm_id>-displayName
~~~

##### ACTUAL RESULTS

~~~
Name on vCenter = dummy-03
Internal Name = i-9-140-VM
~~~

**Comment by rhtyd** [comment]
@mib1185 thanks for reporting, changing the behaviour again may break some environments and given the change was done many years ago (circa 4.6)  I think we'll address this in docs instead.

**Comment by PaulAngus** [comment]
Change of behaviour only occurs if default is changed. If the setting is changed that is because the wants different behaviour.

**Comment by rhtyd** [comment]
This will require a bit of work to see what can be supported (in code) and what can be improved/fixed in docs without causing backward compatibility issues. Given the code freeze, I'm it moving to 4.16 milestone.
