### ISSUE TITLE
use X-forward-for address instead of the load balancer ip.

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4209]
When I log into primate an event is recorded saying "user USER logged in from IPADDRESS". this is a problem for users that use a proxy or load balancer because the ip will always be the the ip of the load balancer or proxy. can a system config option be added to use the IP address of the x-forward header so the real ip of the user is shown instead when using a proxy or load balancer?.

**Comment by ravening** [comment]
we are using haproxy as a loadbalancer and when transparent mode is enabled, it uses XFF address instead of loadbalancer ip. This will be fixed in https://github.com/apache/cloudstack/pull/4141

**Comment by gaaray2k** [comment]
Sorry I don't think I was clear enough. In primate, when a user logs in, an event is log that has the IP of the user in it. The problem is that placing a load balancer in front of the management server, the IP is the load balancer is in the vent instead of the client IP. I asked in the primate project about this and they said that they just take whatever up th backend sends primate. So my question is, is there a way to make the backend log the IP in the x- forward header?

**Comment by DaanHoogland** [comment]
@gaaray2k did you get any progres on this or is it still an issue/feature request?

**Comment by DaanHoogland** [comment]
@gaaray2k closing, hope you don't mind.
