### ISSUE TITLE
How can I use LVM volume storage for my private CloudStack

### ISSUE THREAD

**Issue by alamintech** [apache/cloudstack#4217]
How can I use LVM volume storage for my private CloudStack.

Please see my image below
Also please give me any mail address so I have some query for my private server.
many time I got below details for collect mail address, but I am not find out which exact mail address.

![lvm](https://user-images.githubusercontent.com/68062764/87840664-ab37e880-c8c2-11ea-8f68-a6b5d04d256c.JPG)

Thanks.

**Comment by DaanHoogland** [comment]
there is [the users list](mailto:users@cloudstack.apache.org>) for these questions. hope that helps.

**Comment by rhtyd** [comment]
Closing as this is a not a bug report but question that must be asked on the users ML. Thanks.
