### ISSUE TITLE
Removed kvm host is added back to cloudstack when restart cloudstack-agent on it

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4218]
When we remove a KVM host from cloudstack, and restart cloudstack-agent on it, the host is added back to cloudstack.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM agent
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

basic/advanced networking

##### OS / ENVIRONMENT

KVM

##### STEPS TO REPRODUCE

~~~
1. add a kvm host  to clodustack
2. put host to maintenance in cloudstack
3. remove host from cloudstack
4. restart cloudstack-agent on the host

~~~

##### EXPECTED RESULTS

~~~

5. host is not added back to cloudstack
~~~

##### ACTUAL RESULTS

~~~
5. host is added back to cloudstack
~~~

**Comment by rhtyd** [comment]
@weizhouapache should the remote host purge the agent.properties?
