### ISSUE TITLE
wrong bridge interfaces

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4223]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

KVM

##### OS / ENVIRONMENT

Ubuntu 18

##### SUMMARY

Our systems are configured with descriptive names for bridges, we have configured the agent accordingly. (private, public,guest).network.device are pointing to the right devices in agent.properties.

However a "cloud0" bridge is created. If we delete the device it is re-created on agent startup.

##### STEPS TO REPRODUCE

~~~
- create your bridges following the install guide, use descriptive names such as privatebr, guestbr, etc.
- install cloud agent, and configure agent.proporties with the bridges you just created.
- start cloudstack agent

~~~

##### EXPECTED RESULTS

~~~
no cloud0 bridge exists
~~~

##### ACTUAL RESULTS

~~~
cloud0 bridge has been created.
~~~

**Comment by GabrielBrascher** [comment]
By default, CloudStack configures `cloud0` as the host-only bridge, created when the host is added to a CloudStack zone. This bridge is used internally for SSH access into System VMs. As far as I remember the documentation mentions the process of editing bridges for _management_, _public/guest_, and _storage_ networks (examples on documentation being _cloudbr0_, _cloudbr1_, and _cloudbr2_).

If you edited parameter `private.bridge.name` inside `agent.properties` before adding the host into CloudStack and it still had set as `cloud0` then we need to look into a possible bug indeed.

For reference, this is the line that configures cloud0: [LibvirtComputingResource.java#L858](https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java#L858)

Note that private bridge (`private.bridge.name`) is different from `private.network.device`, which by default is set to `cloudbr1`. More details at: [LibvirtComputingResource.java#L872](https://github.com/apache/cloudstack/blob/master/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/resource/LibvirtComputingResource.java#L872).

**Comment by GabrielBrascher** [comment]
@rvalle did you configure `private.bridge.name`?
Could you please share agent.proporties bridge/network parameters?

**Comment by rvalle** [comment]
ok @GabrielBrascher  let me check...
I have configured
- guest.network.device
- public.network.device
- private.network.device

I have not configured private.bridge.name, you are right, I do remember the documentation mentioning it.

here is my agent.properties
```
#Storage
#Thu Jul 23 17:49:58 CEST 2020
guest.network.device=guest_netbr
workers=5
private.network.device=host_netbr
port=8250
resource=com.cloud.hypervisor.kvm.resource.LibvirtComputingResource
pod=1
zone=1
hypervisor.type=kvm
guid=ef861baa-8f7c-38fe-9b6a-981df48ac7ac
public.network.device=host_netbr
cluster=1
local.storage.uuid=**************************'
keystore.passphrase=*******************
domr.scripts.dir=scripts/network/domr/kvm
LibvirtComputingResource.id=1
host=10.71.0.254
router.aggregation.command.each.timeout=600

```

I have confused cloud0 bridge with cloud0br bridge

**Comment by GabrielBrascher** [comment]
I thought that this was the case. All looking good then :-)
