### ISSUE TITLE
confused about User Permission 

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4227]
I am a little confused as to how user accounts work on CS. right now I have an account called A which is domain admin in domain lab.com . if I add another user in account A, it gets the same "domain admin" permission. if I want to create another user with the "user" role, I would have to create another account with the "user" role under the same domain, but the new account would get different resource count. 

how do I setup a domain as follow?
if I have a customer call acme.com buying resources, I would create a domain called acme.com, then I would create an account called peter which is going to be an admin on that domain. then peter can create users that would get the "user" role under the same domain.  resources consumed by a regular user need to counted from the sources available in the whole "account".

please dont bother sending me the link to CS docs. I already read it a 1000x and still dont get it.

apologized if I am not being clear as to what I am looking for. the way CS implemented the user permission model is very confusing in my opinion.

**Comment by DaanHoogland** [comment]
@gaaray2k I think your question makes sense, even when not understanding it completely; you want the resource count to be on domain level, or shared over the domain admin and the regular user account, do you?

**Comment by andrijapanicsb** [comment]
@gaaray2k the correct place for QUESTIONS is the mailing list - you'll get better help there.

- USER = just username/password (or API/SECRET key) combination to become an ACCOUNT - i.e. once you log in with your credentials, you "become" an ACCOUNT - and everything you do / all resources created belong to this ACCOUNT.
- 
- ACCOUNT = owner of all resources, with optionally limits on a per-account basis.
- DOMAIN ADMIN ACCOUNT = same as regular user-role ACCOUNT, but can see/manage all resources (including those of other ACCOUNTS) in his own domain. Resources can also be limited on a per-domain basis (but keep in mind that sum of all resources for all accounts in a domain, can not be more than the limits set on a domain level)....
- USER ACCOUNT - well, same as the domain account. but it has the user role - so can only create/manage his own resoruces (VMs, volumes, networks etc)

Does that gives you enough info?

In your case, inside your acme.com domain, you would create a DOMAIN ADMIN ACCOUNT called  "peter"  (i.e. an account with a "domain admin" role, not "user" role). Here, also a "user" (user/password) called "peter" will be automatically created for you DOMAIN ADMIN ACCOUNT named 'peter"... this is perhaps what confuses you (so there is account peter and automatically created user peter for that account)

Your DOMAIN ADMIN "peter" would then usually create ACCOUNTS of the "user" role (that will automatically create a "user" (user/password) for that account 

Hope that makes sense.

**Comment by gaaray2k** [comment]
The confirmation comes in the account creation. I would have to rename the account after is being created the. Otherwise I will have an account called and a user called acme.

**Comment by gaaray2k** [comment]
> @gaaray2k I think your question makes sense, even when not understanding it completely; you want the resource count to be on domain level, or shared over the domain admin and the regular user account, do you?

Correct. Or even if a domain is just for auth, the account creation should be separated from a user creation. It should be I create an account and assign resources to it then I create users to consume those resources and assign roles to those users. right now if I create an account all users under that account would have the same permissions. The whole thing is just confusing in my opinion. it is a great product regardless though.

**Comment by gaaray2k** [comment]
This is what I mean. There is no role option when creating a user. The role option is just for accounts. Every user under the same account will have the same roles. 

![Screenshot_20200729-205200](https://user-images.githubusercontent.com/67025242/88868202-835b5580-d1dd-11ea-88e4-fe5b6adbdcb3.png)

**Comment by gaaray2k** [comment]
![Screenshot_20200729-205551](https://user-images.githubusercontent.com/67025242/88868397-15635e00-d1de-11ea-86ea-50a7e6113694.png)

**Comment by andrijapanicsb** [comment]
user doesn't have a role.
Account does.

As I said - observe user as just a username/password (login credentials) for the same account - multiple users in the same account, when they log in, they all "become" this single account

**Comment by gaaray2k** [comment]
Then there is no way to have many users with different roles under the same account sharing resources.

**Comment by andrijapanicsb** [comment]
Correct. For resource sharing – you would probably want to use Projects – each resource created IN the Project (by any account joined to the project) will belong to the project (not the account) – and here you can share resources by simply adding more accounts (participants) to the project.

**Comment by gaaray2k** [comment]
here is another situation.

from the root domain, I created a domain called lab.com which have user walvarez (domain admin). I logged in as walvarez and created another domain called test.com. my userstanding is that lab.com would be a reseller and test.com would be a customer of lab.com. the problem is that when I try to create an account for test.com, the domain test.com doesnt show up in the list  and it doesnt even let me pick a domain at all. it seems like a bug to me. it does this on both the lagacy UI and primate.

![Capture](https://user-images.githubusercontent.com/67025242/88959714-6f146880-d270-11ea-8dd2-b790c8209e62.PNG)

**Comment by andrijapanicsb** [comment]
You can’t add a user-role in an empty domain, until you add the domain-admin , afaik.

Further more, for the reseller model, I would suggest one domain/domain-admin account should be one reseller, then regular user-role accounts inside this same domain would be it’s customers. This way reseler (domain admin account) can manage its customer resoruces (user-role account create resoruces).

For another reseller, create another domain and domain-admin role account etc.

**Comment by gaaray2k** [comment]
How can I add a domain admin if the domain doesn't show up in the list?

**Comment by DaanHoogland** [comment]
@gaaray2k this question is stale as well, Are you still on it?

**Comment by DaanHoogland** [comment]
> How can I add a domain admin if the domain doesn't show up in the list?

@gaaray2k above I read that you added a user walvarez as domain admin so I am assuming some messages got crossed and this is answerred.
