### ISSUE TITLE
uefi vm creation fail

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4238]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
VM creation fails when creting a vm with uefi bios

##### STEPS TO REPRODUCE
create an instance with a uefi bios

##### EXPECTED RESULTS
vm is created sucessfully

##### ACTUAL RESULTS
2020-06-23 11:44:19,025 ERROR [kvm.resource.LibvirtComputingResource] (main:null) (logid:) uefi properties file not found due to: Unable to find file uefi.properties.

**Comment by gaaray2k** [comment]
from https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+UEFI+booting+for+Instance it says:

In case of newly configuring KVM Host , Cloud Admin [Customer admin] will have to prepare and add uefi.properties after successful completion of agent.

is this a file I need to create manually?

**Comment by DaanHoogland** [comment]
@gaaray2k I have never tested UEFI with any thing but vmware and I thought on KVM firmware emulation does not apply as all properties are set in the spec xml that qemu uses. However reading that page it says an extra package needs to be installed on KVM to support UEFI.
>  { eg: KVM host additional OVMF package is required to  boot Guest VM in UEFI mode}
Did you do that?
As i don't know of any other users atm I think you are on your own. Try addressing the author of the feature.

**Comment by DaanHoogland** [comment]
@gaaray2k can you test this with 4.15, please?

**Comment by DaanHoogland** [comment]
@gaaray2k did you find an answer and can you share it?

**Comment by slavkap** [comment]
I'm not @gaaray2k but I could tell how I did the setup on one of my hosts. My configuration is according to the steps from PR [#3638 ](https://github.com/apache/cloudstack/pull/3638)



I have installed OVMF and have created uefi.properties with those details
![image](https://user-images.githubusercontent.com/51903378/107012932-5dbd9300-67a2-11eb-94ba-35831b38828d.png)

and in /etc/libvirt/qemu.conf file I have added 
`nvram = ["/usr/share/OVMF/OVMF_CODE.secboot.fd:/usr/share/OVMF/OVMF_VARS.fd"]
`

Because my host wasn't newly created I have changed in `host_details `table the value for `"host.uefi.enable"` of the respective host to `true`. I have tested it also by adding a new host.

I couldn't find a qcow2 image with EFI to test deploying a VM from a template, but deploying a VM with ISO works, but at runtime, I've replaced the bus  from `'ide'` to `'sata'`

**Comment by DaanHoogland** [comment]
@slavkap , that sounds like the adding of uefi.properties should be part of the agent setup/host connect procedure, should it?
cc @weizhouapache @wido @pavanaravapalli ?

**Comment by slavkap** [comment]
@DaanHoogland , I think that for the end-user it will be ok the uefi.properties file to be included. But I don't have experience in this, because for the last three days I'm "playing" with this feature :) So somebody else has to say which option is better

**Comment by Hudratronium** [comment]
> 
> 
> @slavkap , that sounds like the adding of uefi.properties should be part of the agent setup/host connect procedure, should it? cc @weizhouapache @wido @pavanaravapalli ?

+1

I would really appreciate this, as the managementserver GUI will show this option even if no uefi-capable hosts for instance deployment are availeable.
So from a users point of view, uefi-boot is availeable all of the  time.
Another topic might be to dispaly some more informations in the advanced  - mode menue as, according to [https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+UEFI+booting+for+Instance](url) there are some limitations. 
"Guest VM which is deployed in UEFI mode , restricted to migrate another Host[with UEFI capability]"

@slavkap 
Did you have issues migrating uefi-secureboot instances between different hosts?

**Comment by slavkap** [comment]
@Hudratronium, I don't remember. I will test and let you know

**Comment by Hudratronium** [comment]
That would be really appreaciated.
Currently the docs as well as the wiki are quiet ... empty regarding this whole topic.

**Comment by slavkap** [comment]
@Hudratronium, I just tested and live migration without migrating to the different storage pool.
zone-wide NFS storage the migrating is successful
zone-wide StorPool storage the migration is successful

But found that during migration with both cases - `migrateVirtualMachineWithVolume` and `migrateVirtualMachine` the `/var/lib/libvirt/qemu/nvram/[VM-UUID].fd` file is copied to the new host, but still exists and on the old one. Which I think has to be deleted

**Comment by Hudratronium** [comment]
So then as an update:
migrating UEFI secureboot enabled instances on kvm works:
with NFS:
 -   in stopped state
 -   in running state
 --> Basically fully functional in regards of migration
 
with StorePool
 --> Basically fully functional in regards of migration

Sadly i am not as much of an developer if i would like, so i currently can't take deep look into the topic with the nvram file.
Maybe there is a small bug cause you can give the host a custome path for the location of the vram folder in the additonal conf.file (see your post https://github.com/apache/cloudstack/issues/4238#issuecomment-773908266 ).

Maybe @DaanHoogland has an idea regarding this?

**Comment by DaanHoogland** [comment]
sounds like a bug to me. @nvazquez @GabrielBrascher @GutoVeronezi ?

**Comment by rohityadavcloud** [comment]
I think the creation depends on whether the hypervisor supports it; for ex. if the platform is arm64, all VMs are UEFI based only; is this still a bug @gaaray2k ?

**Comment by pavanaravapalli** [comment]
In case of KVM+ OVMF combination, we need to consider machine profile 'Q35' supported on host  for VM secure booting.

**Comment by Hudratronium** [comment]
> I think the creation depends on whether the hypervisor supports it; for ex. if the platform is arm64, all VMs are UEFI based only; is this still a bug @gaaray2k ?

Would this work for CS in a mixed environment (meaning UEFI capable and not capable hosts )?
Up till now my understanding of the design reference ( https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+UEFI+booting+for+Instance ) is that UEFI is optional. Meaning even if a plattform (host) supports UEFI, the current standard for deployments still is BIOS (especially regarding the SystemVMs).

@slavkap 
> But found that during migration with both cases - `migrateVirtualMachineWithVolume` and `migrateVirtualMachine` the `/var/lib/libvirt/qemu/nvram/[VM-UUID].fd` file is copied to the new host, but still exists and on the old one. Which I think has to be deleted

I've seen that for the last releases (4.17) there have been some changes regarding the UEFI capabilies out of the box - do you know if this was "fixed" ?
Also you wrote the link to the source for the content of the "uefi.properties"-file. Do you know if there have been some changes regarding the contents as well as of the deployment (kind of "inital" configuration) which might be deployed with 4.17?

**Comment by DaanHoogland** [comment]
> It seems not be a bug should we close this ? @DaanHoogland @rohityadavcloud

I would leave it to @gaaray2k (and @Hudratronium ) to close or specify further. If they had problems they are best to judge if this is due to unwanted behaviour, lack of documentation, or what else.

@gaaray2k @Hudratronium can you open a new issue and close this discussion one if there is anything to do on this?

**Comment by Hudratronium** [comment]
Regarding the 'uefi.properties' file i guess everything is said and done.
As always it would be nice to see some more information in the docs for this as the only offical source of information is the above mentioned wiki entry. As far as i have seen, there have been some changes and fixes regarding that feature during the last versions of CS. So i can't say that the infos given in the wiki are still up to date as it has been modified at 10/2019.
With Windows Server 2022 we have a major OS which is actively checking secure boot / needing it to match some security baselines. 
The same goes for several certifications and stuff when you are using CS in more security sensitive environments.If the project wants to give the opertunity to use Cloudstack with KVM hosts in such environments, it might be nice thinking about updateing the docs wiki and maybe publish some more infos regarding the whole depolyment / usage of the feature.

**Comment by DaanHoogland** [comment]
@Hudratronium please open a [documentation pr](https://github.com/apache/cloudstack-documentation/compare) or a [new issue](https://github.com/apache/cloudstack/issues/new/choose) describing it seperately. I am afraid it will get drowned in this ticket.

**Comment by Hudratronium** [comment]
@DaanHoogland 
I opened a new Issue for that topic - I hope it was the right format
https://github.com/apache/cloudstack/issues/7126

**Comment by DaanHoogland** [comment]
looks good. Now an experienced user will have to write it ;)

**Comment by rohityadavcloud** [comment]
Closing as https://github.com/apache/cloudstack/issues/7126 was opened.
