### ISSUE TITLE
Agents failover

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4240]
is there a setting I need to enable for the agents to failover to a new mgmt server in case of a failure? right now this isnt happening. I shutdown the mgmt server where the agents were connected and they all went to disconnected state. I waited about 10 mins but they didnt reconnect to another server.

The only fix is to restart the agent.

**Comment by rhtyd** [comment]
@gaaray2k see http://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#server-address-usage 
Which were your env/versions of CloudStack/KVM?

**Comment by gaaray2k** [comment]
I am using 4.14 with kvm.

**Comment by rhtyd** [comment]
@gaaray2k have you tried specifying comma separate list of hosts in the `host` global setting and then restart the agents, repeat the failure case?

**Comment by gaaray2k** [comment]
I did

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ravening** [comment]
@gaaray2k if the `host` field in `/etc/cloudstack/agent/agent.properties` contains a command separated list of mgt server IP then if one mgt server goes down then all agents will connect to next mgt server depending on algorithm. We have this is production and no issues so far

**Comment by DaanHoogland** [comment]
@gaaray2k can you confirm and close this or provide more details please?

**Comment by gaaray2k** [comment]
You can close it

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
