### ISSUE TITLE
Unable to login with latest master 2020/08/04

### ISSUE THREAD

**Issue by Spaceman1984** [apache/cloudstack#4242]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI/API
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### OS / ENVIRONMENT

Using Google Chrome Browser: Version 84.0.4147.105 (Official Build) (64-bit)

##### SUMMARY

Unable to log in

##### STEPS TO REPRODUCE

~~~
Start up management server
Go to login page
Try to log in using credentials:
admin
password
~~~

##### EXPECTED RESULTS

~~~
Redirect to dashboard
~~~

##### ACTUAL RESULTS

~~~
No redirect

Json response from API call:
listcapabilitiesresponse: {uuidList: [], errorcode: 401, errortext: "unable to verify user credentials"}
errorcode: 401
errortext: "unable to verify user credentials"
uuidList: []
~~~

**Comment by Pearl1594** [comment]
@Spaceman1984 I am unable to reproduce the issue. This issue may however crop up if you have cookies of another session. There was a PR merged into master that handles purging of (multiple session key) cookies (https://github.com/apache/cloudstack/pull/4176). In case there exists session Key cookies of another session - try clearing out your cache once, and then test if this issue crops up again.
Also, could you  please share the sessionkey and path details. Thanks

**Comment by Spaceman1984** [comment]
Hi @Pearl1594 , seems like this is an issue that occurs when running an older version before going to latest master, I was able to log in using a guest session on chrome. Where do I find the sessionkey and path?

**Comment by Pearl1594** [comment]
@Spaceman1984 In your browser's dev tools, goto storage -> cookies. There you'd see the sessionkey; clicking on it, will fetch you details of the respective cookie.

**Comment by Spaceman1984** [comment]
![Cookies](https://user-images.githubusercontent.com/49917670/89383278-82a25200-d6fc-11ea-9e1d-c263c0ce36d8.png)

**Comment by Spaceman1984** [comment]
@Pearl1594 seems like these cookies will expire tomorrow

**Comment by Spaceman1984** [comment]
![Cookies-Guest](https://user-images.githubusercontent.com/49917670/89383838-7e2a6900-d6fd-11ea-8f88-67c32902990e.png)
 
The cookies from the guest session doesn't include a sessionkey for /client, maybe the different path on the new version is causing the issue.

**Comment by rhtyd** [comment]
@Spaceman1984 on latest branch/master what you're working on if you clear application cache (see clear storage on the Application tab) - are you able to log in? Are you using old UI or Primate for testing UI?

**Comment by Spaceman1984** [comment]
@rhtyd  I'm using the old UI. If I clear the cache, the immediate problem is gone. but that is a workaround that doesn't address the issue. 

Just by looking at the pictures I uploaded, I can see an extra sessionkey with a different path. Possibly the problem here is that a new session key is added but the old incorrect sessionkey is being checked for authentication?

**Comment by Spaceman1984** [comment]
@rhtyd This is an edge case with a workaround, maybe we can close this one?

**Comment by Pearl1594** [comment]
@Spaceman1984  If we are moving from an old to the newer code base with the fix in place, there would be a need to clear any session keys left behind that was not cleaned earlier during the logout process. Further on, you will not see the issue as the PR mentioned earlier will handle purging them.

**Comment by Spaceman1984** [comment]
Ok @Pearl1594,  sounds like this is a duplicate issue then, closing.
