### ISSUE TITLE
Fix failing smoke tests for VMware

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4261]
Please review and check if we've valid regressions on master, we're seeing new intermittent test failures:

test_07_reboot_ssvm | Failure | 25.34 | test_ssvm.py
test_02_enableHumanReadableLogs | Failure | 65.72 | test_human_readable_logs.py

Both are intermittent minor issues

`reboot_ssvm fails` with error that NFS storage is not mounted
`enableHumanReadableLogs` fails due to config. mismatch could be timeout/run related

**Comment by rhtyd** [comment]
With @Pearl1594 cc @Spaceman1984

**Comment by Spaceman1984** [comment]
@rhtyd I'll take a look

**Comment by Spaceman1984** [comment]
Seems like an environment issue for test_vm_life_cycle.py.
`MigrationCommand failed due to Exception: java.lang.RuntimeException\\nMessage: The target host does not support the virtual machine\'s current hardware requirements.`
@rhtyd Should I proceed with manual testing?

**Comment by rhtyd** [comment]
@Spaceman1984 good idea, I think you can setup a Vmware 6.5 or 6.7 env with two host and try to excute the two failing tests manually (manually execute marvin tests or manually perform the migrate VM and reboot SSVM operations). Please also check if  the ESXi hosts are on two different underlying hosts with different processors (i.e. one on Intel and another on AMD which could be an issue).

**Comment by Spaceman1984** [comment]
I have tested manually
Intel to AMD = Fail
Intel to Intel = Pass
Definitely an env issue.

**Comment by rhtyd** [comment]
Thanks @Spaceman1984 verified. The same issue is causing xenserver-71 deployment/test issues.

**Comment by rhtyd** [comment]
@Spaceman1984 @Pearl1594 
`reboot_ssvm fails` with error that NFS storage is not mounted
`enableHumanReadableLogs` fails due to config. mismatch could be timeout/run related

**Comment by Spaceman1984** [comment]
> `enableHumanReadableLogs` fails due to config. mismatch could be timeout/run related
Possibly, the test waits 1 minute for a capacity log, not sure if the same happens with vmware, I have to test.

**Comment by rhtyd** [comment]
Closing both issues env related, handled.
