### ISSUE TITLE
List VMs in Projects when listing all VMs

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#4267]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
API
~~~

##### SUMMARY
CloudStack does not list VMs that are in a project unless the `listVirtualMachines` API request has the specific project ID set on `projectid` parameter. I don`t see why we do not provide any way of listing **all** VMs.

Looking at the documentation of [listVirtualMachines](https://cloudstack.apache.org/api/apidocs-4.14/apis/listVirtualMachines.html), when `listall=true` it lists all VMs that the caller is authorized to see; if set to false, it lists just the resources owned by the caller.

With that said, I think that the admin should be allowed to list VMs on projects when the request contains`listall=true`. Does anyone (dis)agree with that?

I would like to take the liberty and propose/discuss two approaches to fix/enhance it:
1. Add support for Admins to list VMs on all projects when listall=true; or,
2. add a new parameter that will allow the Admin to list all VMs, including those in projects.

Considering the [API's documentation](https://cloudstack.apache.org/api/apidocs-4.14/apis/listVirtualMachines.html), the first approach fits well as Admin is indeed authorized to see all VMs; however, the second option avoids any possible backward compatibility and adds finer granularity to Admin's requests.

**Comment by rhtyd** [comment]
@GabrielBrascher there is a way by calling listall=true and projectid=-1 can you try that?

**Comment by GabrielBrascher** [comment]
I had no idea of this trick. It works indeed!
@rhtyd thanks for the hint :slightly_smiling_face: :+1:

Do you know if this is documented somewhere? It would be nice to have this documented somewhere.
