### ISSUE TITLE
Multiple L2 networks with same VLAN cannot be created even with Bypass VLAN id/range overlap checked

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#4273]
Till 4.13 ACS allowed creating multiple L2 networks with the same VLAN ID when Bypass VLAN id/range overlap is checked in the UI. But this behaviour is changed with 4.14 which throws an error,
![Screenshot from 2020-08-19 12-47-02](https://user-images.githubusercontent.com/153340/90604233-28d07a80-e21a-11ea-9e53-c10d7750186f.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
L2 networks
~~~

##### CLOUDSTACK VERSION

~~~
4.14 and above
~~~

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

KVM, CentOS7 but doesn't seem to be hypervisor, OS specific

##### STEPS TO REPRODUCE

~~~
1. Create a L2 network with some VLAN ID, say 100, while Bypass VLAN id/range overlap option checked. Network will be created successfully
2. Create another L2 network with same VLAN ID with Bypass VLAN id/range overlap option checked. Network will fail to create with error.
~~~

##### EXPECTED RESULTS

~~~
Second network succesfully created with same VLAN ID as Bypass VLAN id/range overlap option was checked
~~~

##### ACTUAL RESULTS

~~~
Server returns error with message - Network with vlan 100 already exists or overlaps with other network vlans in zone 1
~~~

Issue is seen with both UI and cmk

**Comment by rhtyd** [comment]
cc @Spaceman1984 can you look at this next, thanks

**Comment by shwstppr** [comment]
Some issue here,
https://github.com/apache/cloudstack/blob/4.14/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java#L2531-L2533

https://github.com/apache/cloudstack/blob/4.13/engine/orchestration/src/main/java/org/apache/cloudstack/engine/orchestration/NetworkOrchestrator.java#L2483-L2485

**Comment by rhtyd** [comment]
Thanks I'll raise a PR I know what happened there @shwstppr

**Comment by rhtyd** [comment]
Fixed in PR https://github.com/apache/cloudstack/pull/4274, tested by @Spaceman1984 and I
