### ISSUE TITLE
Use database name other than "cloud"

### ISSUE THREAD

**Issue by alitheg** [apache/cloudstack#4277]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Installation scripts
~~~

##### CLOUDSTACK VERSION
~~~
4.14.0
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I'd love to have control over the name of the DB, as I'm using a database hosted in another cloud provider and I'm unable to allow a newly-created user access to the "mysql" database.

It's possible to bypass the creation SQL and run it manually to get this far, but the other scripts fail.

##### STEPS TO REPRODUCE
~~~
db.properties supports a db.cloud.name property, ostensibly to change the name of the database (instead of "cloud"). However, all the setup SQL scripts, and the cloud-install-sys-tmplt scripts, have the database name hard-coded instead of pulling from configuration. 
~~~

##### EXPECTED RESULTS
~~~
Scripts successfully connect and interact with my database.
~~~

##### ACTUAL RESULTS
~~~
Access denied for user xxxxxx to database `cloud`
~~~

**Comment by alitheg** [comment]
In fact, the whole system fails when the database isn't called "cloud". Serves me right for raising an issue before I'd finished.

**Comment by DaanHoogland** [comment]
@alitheg if you are planning to do more investigation we can keep this issue open, otherwise we'd close it. care to comment?

**Comment by alitheg** [comment]
That's fine - I was only testing the waters of cloudstack and haven't the time to dig into it further. Closing the issue.
