### ISSUE TITLE
cloudstack-common no longer installed with cloudstack-agent and cloudstack-management

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#4280]
##### ISSUE TYPE

 * Bug Report
 ##### COMPONENT NAME

~~~
CloudStack - Install
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

Ubuntu
CentOS

##### SUMMARY

Previously cloudstack-common was automatically installed with the main packages.
Requiring extra steps is a blocker to 'easy' install.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Ping @davidjumani - any comments?

**Comment by davidjumani** [comment]
@rhtyd I checked and it is listed as a dependency. Installed cloudstack-management & cloudstack-agent on a local VM on ubuntu and centos and cloudstack-common was installed too!

**Comment by rhtyd** [comment]
@davidjumani did you try Ubuntu 16.04 and 18.04? I think it works OK on 20.04.

**Comment by davidjumani** [comment]
@rhtyd It worked with 18.04 as well as 20.04, but failed on 16.04 as `python3-distutils` was not found. Can decide whether to support 16.04 based on the discussion going on in the mailing list

**Comment by rhtyd** [comment]
@davidjumani can you kick a test against latest master with Ubuntu 16.04 as mgmt server and kvm host and identify what fails, and what workaround we can establish (with trillian, i.e. installation of workaround pkgs etc)

**Comment by davidjumani** [comment]
@rhtyd Trying a workaround by using `python3-distutils-extra` instead via #4305 
Builds and installs in 16.04, Going to run tests and check whether it's all good

**Comment by rhtyd** [comment]
@davidjumani have you tested your workaround?

**Comment by davidjumani** [comment]
@rhtyd Tested locally with a few smoke tests since the lab had issues. Will try again

**Comment by rhtyd** [comment]
With @davidjumani cc @Spaceman1984

**Comment by DaanHoogland** [comment]
@Spaceman1984 I can't seem to assign to you, but consider yourself assigned please

**Comment by davidjumani** [comment]
@PaulAngus @shwstppr No issues while installing on u16, but created https://github.com/apache/cloudstack/pull/4305 to ensure that the dependencies are met (Smoke tests ran on u16 u18 u20)

**Comment by rhtyd** [comment]
Copy @davidjumani I see cloudstack-agent/cloudstack-common installs OK with PR #4305 closing on this  remark
