### ISSUE TITLE
Problem with L2TP remote VPN

### ISSUE THREAD

**Issue by humito36** [apache/cloudstack#4281]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
L2TP VPN

##### CLOUDSTACK VERSION

4.14

##### CONFIGURATION
VPC network system vm version: 4.14.0

##### OS / ENVIRONMENT
Mac OS, Windows 10.

##### SUMMARY
I have got problem with remote VPN feature in VPC. Probably script generate bad config file at VPC VM:
/etc/ipsec.d/ipsec.any.secrets 

PUBLIC IP %any : PSK "PRESHAREDKEY"
When i edit it to:
 : PSK "PRESHAREDKEY and do ipsec rereadsecrets via shell at vac it starts to work.

**Comment by rhtyd** [comment]
@humito36 are you able to reproduce it if you restart VPC with cleanup?

**Comment by humito36** [comment]
Yes The problem persists i tried few times

Pozdrawiam,

Tomasz Humiczewski
Członek Zarządu

tomasz.humiczewski@blackice.com.pl
kom: +48 533 599 910
tel. +48 12 634 99 90

BlackIce Networks Sp. z o. o., ul. Marcika 2, 30-443, Kraków
NIP: 676 245 98 98, REGON: 122709468 KRS: 0000439317 Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie Wydział XI Gospodarczy
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses.
Anyone who communicates with us by e-mail is deemed to have accepted these risks.
BlackIce Networks is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those

________________________________
Od: Rohit Yadav <notifications@github.com>
Wysłane: Friday, August 28, 2020 11:34:07 AM
Do: apache/cloudstack <cloudstack@noreply.github.com>
DW: Tomasz Humiczewski <tomasz.humiczewski@blackice.com.pl>; Mention <mention@noreply.github.com>
Temat: Re: [apache/cloudstack] Problem with L2TP remote VPN (#4281)


@humito36<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhumito36&data=01%7C01%7Ctomasz.humiczewski%40blackice.com.pl%7C1645d97a1f394f190b6a08d84b358365%7Ccbcade97b55645da892b99f84316d12a%7C0&sdata=ogj8lED6X9iy8NABFKJCk8GT%2FuDnEngC%2B%2FQL7wmgoxE%3D&reserved=0> are you able to reproduce it if you restart VPC with cleanup?

**Comment by rhtyd** [comment]
@humito36 can you test latest 4.15.1?

**Comment by rhtyd** [comment]
Fixed by referenced PR.
