### ISSUE TITLE
Encrypt keystore password in cloudstack properties file

### ISSUE THREAD

**Issue by Dajeong-Park** [apache/cloudstack#4293]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

Encrypt keystore password in cloudstack properties file

##### CLOUDSTACK VERSION

4.13
4.14

##### SUMMARY

If you enter the "https.keystore.password" value in the server.properties file as an encrypted value through the jasypt-1.9.2.jar file of the cloudstack-common library, as in how to encrypt the password in db.properties file.
the service will not run normally on port 8443. I hope that the keystore password can be encrypted and applied.

##### EXPECTED RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@Dajeong-Park marking it for future now, if you have a PR you are welcome to submit it.
