### ISSUE TITLE
Api Authentication Error 

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4295]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API / Manager
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

KVM

##### OS / ENVIRONMENT

Ubuntu 18.04

##### SUMMARY

The API is rejecting calls made from CloudMonkey when they include a particular value/parameter.

The particular case found is using cloudmonkey to upload certificates. The API will return Autentication Error when the parameter domainsuffix starts by "*", removing the offending character  makes the call work as expected. 

The generated URL call seems to be properly formed, according to parsers, with special characters properly escaped. 

It looks as if the API server authentication functionality was not working for some poisoned requests. 

##### STEPS TO REPRODUCE

Follow the instructions to secure cloudstack as stated: https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/
Use the CloudMonkey configuration process
Or submit the following CloudMonkey request

~~~

cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test"
~~~

##### EXPECTED RESULTS

~~~
It should be possible to upload certificates using cloudmonkey, that include * as domainsuffix

~~~

##### ACTUAL RESULTS

~~~
when the domainsuffix starts by * the call will return authentication error.
~~~

**Comment by rvalle** [comment]
as a workaround for my particular call I just realized that for uploading the certificates the * can be removed from the domainsuffix and uploaded as ".svm.vdc.test" and they will work as expected, even for securing the console with consoleproxy.url.domain = *.svm.vdc.test.

**Comment by rhtyd** [comment]
@rvalle does it work for you if you use the GUI? In cmk, could it be the quote issue - in your example I see `domainsuffix='*.svm.vdc.test"` which must be written as `domainsuffix="*.svm.vdc.test"` or `domainsuffix=*.svm.vdc.test`. You may debug what is sent to the management server by running `set debug true` in cmk and then run the API.

**Comment by rvalle** [comment]
@rhtyd  
It does work on the GUI.
It is not a quote issue.

You can literally try this command: 

```
cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test"
```
do not worry about the fact that the certificate is not complete. The call will work, but only after you delete the * form the domainsuffix.

Can you reproduce it?

**Comment by DaanHoogland** [comment]
`cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test"`

should be

`cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test'`

Note the final quote. I think that is what @rhtyd pointed out. Did you check that?

**Comment by rvalle** [comment]
Sorry, I copied the example badly, have a look:

First attment, with asterisk:

```
root@manager:~# cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test'
🙈 Error: failed to authenticate, please check the credentials
```

Second without:

```
root@manager:~# cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='.svm.vdc.test'
{
  "customcertificate": {
    "message": "Certificate has been successfully updated, if its the server certificate we would reboot all running console proxy VMs and secondary storage VMs to propagate the new certificate, please give a few minutes for console access and storage services service to be up and working again"
  }
}
root@manager:~# 
```

did you reproduce it?

**Comment by rvalle** [comment]
I don't know if related or not, but i am seeing other strange authentication errors:

```

TASK [Create Service Instances] ***************************************************
ok: [localhost] => (item=sv1)

TASK [Create Management Instances] ************************************************
failed: [localhost] (item=mg1) => {"ansible_loop_var": "item", "api_http_method": "get", "api_key": "xxxxxxxxxxxx", "api_region": "cloudstack", "api_timeout": 10, "api_url": "https://manager/client/api", "api_verify_ssl_cert": "./.ca.crt", "changed": true, "item": "mg1", "msg": "CloudStackException: HTTP 401 response from CloudStack, error: {'uuidList': [], 'errorcode': 401, 'errortext': 'unable to verify user credentials and/or request signature'}", "zone": "z1"}
```

Note how in the same play previous task is authenticated OK and next tasks does not. I did re-run and both passed OK.

**Comment by DaanHoogland** [comment]
@rvalle , I think i can't reproduce3:
```
# cmk upload customcertificate id=1 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test'
{
  "customcertificate": {
    "message": "Certificate has been successfully updated, if its the server certificate we would reboot all running console proxy VMs and secondary storage VMs to propagate the new certificate, please give a few minutes for console access and storage services service to be up and working again"
  }
}
```

**Comment by rvalle** [comment]
@DaanHoogland what!!???

how is that possible? Which version of ACS are you using? I am on 4.14.0

**Comment by DaanHoogland** [comment]
@rvalle let me double check. it might have been a 4.15 prequel I tested it on, in which case it is solved in master.

**Comment by DaanHoogland** [comment]
@rvalle sorry it took so long. I checked but it works in 4.14 for me. I did a c&p of my text again and it worked again.

**Comment by rvalle** [comment]
@DaanHoogland I will rebuild my environment again and retest. 

Big mystery to me. 

I can reproduce this bug each time. I am on Ubuntu 18.04, perhaps the issue is related to JVM patch level? 

I will investigate further and see what I can find out.

**Comment by DaanHoogland** [comment]
Any update @rvalle . is this a bug? is there a milestone to add, or a severity label?
tnx

**Comment by rvalle** [comment]
Hi @DaanHoogland 

I am sure it is a bug, I can reproduce it on each installation of my test cloud.
Severity is very low, because it can easily be workarounded.
I still have not looked into tracing the code and trying to understand why it is only happening to me and others cannot reproduce it.
I was thinking on testing it on 4.15, but my environment is not yet there.

I would keep this open because if url signature is failing under some strange circumstances, I think we want to know.

**Comment by DaanHoogland** [comment]
tnx @rvalle marking it for 4.16 . if we find a quick fix for you we can move it back to older versions.

**Comment by rvalle** [comment]
Revisiting this issue, I just installed 4.15 for first time. Very impressed by the new UI. 

Testing this issue on fresh install:

```
Apache CloudStack 🐵 CloudMonkey 6.1.0
Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues
(localcloud) 🐱 > sync
Discovered 613 APIs
(localcloud) 🐱 > exit
root@manager:~# cmk upload customcertificate id=19 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test'
🙈 Error: failed to authenticate, please check the credentials
root@manager:~# cmk upload customcertificate id=19 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='.svm.vdc.test'
{
  "customcertificate": {
    "message": "Certificate has been successfully updated, if its the server certificate we would reboot all running console proxy VMs and secondary storage VMs to propagate the new certificate, please give a few minutes for console access and storage services service to be up and working again"
  }
}
``` 

@DaanHoogland , looks like unfortunately is still there. And looks like it is still just me.

Quick question: Is it possible to use the remote JVM debugger if I installed from the packages? Perhaps setting JVM options on the service unit?

**Comment by DaanHoogland** [comment]
Yes, @rvalle we do that a lot, there even is a debug line for the options replacing the default. just comment out one and uncomment the other and restart.

**Comment by weizhouapache** [comment]
> Revisiting this issue, I just installed 4.15 for first time. Very impressed by the new UI.
> 
> Testing this issue on fresh install:
> 
> ```
> Apache CloudStack 🐵 CloudMonkey 6.1.0
> Report issues: https://github.com/apache/cloudstack-cloudmonkey/issues
> (localcloud) 🐱 > sync
> Discovered 613 APIs
> (localcloud) 🐱 > exit
> root@manager:~# cmk upload customcertificate id=19 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='*.svm.vdc.test'
> 🙈 Error: failed to authenticate, please check the credentials
> root@manager:~# cmk upload customcertificate id=19 name='RootCertificate' certificate='-----BEGIN CERTIFICATE-----' domainsuffix='.svm.vdc.test'
> {
>   "customcertificate": {
>     "message": "Certificate has been successfully updated, if its the server certificate we would reboot all running console proxy VMs and secondary storage VMs to propagate the new certificate, please give a few minutes for console access and storage services service to be up and working again"
>   }
> }
> ```
> 
> @DaanHoogland , looks like unfortunately is still there. And looks like it is still just me.
> 
> Quick question: Is it possible to use the remote JVM debugger if I installed from the packages? Perhaps setting JVM options on the service unit?

@rvalle 
the following commands work for me.
```
cmk upload customcertificate certificate="$(cat $CERT_ROOT_CERT)" domainsuffix=$(cat $CERT_DOMAIN)  name=root id=1 
cmk upload customcertificate certificate="$(cat $CERT_FILE)" domainsuffix=$(cat $CERT_DOMAIN) privatekey="$(cat $CERT_PRIVATE_KEY)" id=2
```

please pay attention to the id (1 -> root certificate, 2 -> certificate)

**Comment by rvalle** [comment]
this seems to be only me, and I have a workaround too. so, will close for now.
