### ISSUE TITLE
"Data-server." is not resolved by the VR - Cloud-init cannot get user-data on RHEL8-Like

### ISSUE THREAD

**Issue by Lucasgranet** [apache/cloudstack#4308]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
VR
~~~

##### CLOUDSTACK VERSION
~~~
4.14
~~~

##### CONFIGURATION
VSphere and Xcp-Ng templates

##### OS / ENVIRONMENT
Impact RHEL8/C8

##### SUMMARY

- When a VM tries to resolve "data-server." (DNS entry that must point to the VR IP), it failed.
On RHEL-8-like, cloud-init cannot get anymore the VR IP from the DHCP lease (via the attribute "dhcp-server-identifier") since they now used NetworkManager. So, cloud-init cannot get the user-data from the VR. 

- Now, the only way for a C8/RHEL8 to access to their user-data is from the DNS resolution "data-server" (in order to get access to the VR).

- I try to add the static entry in the /etc/hosts of the VR, but the file is rewritten after each new VM deployment.
The entry should be added by this script : _/opt/cloud/bin/setup/common.sh_ but I think something else erase the entry.

##### STEPS TO REPRODUCE
* Log into a random VM, try to resolve "data-server." or "data-server".
```shell
[root@test8 ~]# nslookup
> server
Default server: 10.2.111.18 <---- VR IP ---->
Address: 10.2.111.18#53
Default server: 10.2.254.254
Address: 10.2.254.254#53
> data-server.
Server:         10.2.111.18
Address:        10.2.111.18#53

Non-authoritative answer:
*** Can't find data-server: No answer
```

##### EXPECTED RESULTS

* Log into the VR, try to get "data-server" from the /etc/hosts - perform a DNS resolution - **after a new deployment**
```shell
root@r-8-VM:/etc# cat /etc/hosts |grep data-server
10.2.111.18     data-server
root@r-8-VM:/etc# echo $?
0
root@r-8-VM:/# nslookup data-server localhost
Server:         localhost
Address:        127.0.0.1#53

Name:   data-server
Address: 10.2.111.18
```

* Into a random VM
```shell
[root@test8 ~]# nslookup
> data-server
Server:         10.2.111.18
Address:        10.2.111.18#53

Name:   data-server.iaas.lgr.fr
Address: 10.2.111.18
```

##### ACTUAL RESULTS
* Log into the VR, try to get "data-server" from the /etc/hosts - perform a DNS resolution - **after a new deployment**
```shell
root@r-8-VM:~# cat /etc/hosts |grep data-server
root@r-8-VM:~# echo $?
1
root@r-8-VM:/# nslookup data-server localhost
Server:         localhost
Address:        127.0.0.1#53

Non-authoritative answer:
*** Can't find data-server: No answer

```

**Comment by andrijapanicsb** [comment]
Shouldn't this be a bug for cloud-init project?

**Comment by Lucasgranet** [comment]
Hello,

Pull request #4319
