### ISSUE TITLE
SystemVMs Publics IPs offered to accounts despite global settings

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4310]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

KVM, Local Storage, Advanced Networking

##### OS / ENVIRONMENT

Ubuntu 18.04

##### SUMMARY

We want to configure ACS so that Accounts are assigned certain Public IPs that they can manage themselves. 
On the other hand we have reserved special Public IPs "for system vms"

With the following Global settings:
system.vm.public.ip.reservation.mode.strictness = true
use.system.public.ips = false

When trying to acquire a public IP form an Account in web UI:
- Public IP rages for their domain are offered, as expected.
- Public IP ranges not assigned explicitly to them are not offered, as expected.
- Public IP ranges not assigned explicitly marked for System VMs  are offered, which seems to be a bug.

##### STEPS TO REPRODUCE

~~~
- configure global settings 
- restart manager
- create account
- configure IP ranges for account
- log in as account
- try to acquire a new public IP to an isolated network, review the list of offered IPs.

~~~

##### EXPECTED RESULTS

~~~
With this settings Accounts should not be offered forSystemVMs Public IPs. 
~~~

##### ACTUAL RESULTS

~~~
Accounts are offered public IPs reserved for System VMs.
~~~

**Comment by rhtyd** [comment]
@rvalle in your env did you run out of public IPs for users/networks?

**Comment by rhtyd** [comment]
cc @nvazquez

**Comment by rvalle** [comment]
@rhtyd the Public IPs marked as for System VMs are offered for user consumption (web UI) from the beginning.

I mean, after a fresh installation when non of the public IPs have been consumed. 

I am assuming that it has been implemented that System VMs will use (optionally strictly)  vlan_ip_ranges flagged for SystemVMs, but it has not been implemented that those IPs are not to be used other accounts.

**Comment by ravening** [comment]
@rvalle I remember encountering same issue. We had domain setting as -1 for public ip field. Can you set it to 0 and try again?

**Comment by rvalle** [comment]
@ravening you mean the public ip limits?

```Public IP Limits -1```

But this domain has IPs assigned to it, perhaps I can just use the actual amount as limit? ... that did not work.

But if I set the limit for the domain as 0, can I acquire IPs from this domain?

**Comment by rvalle** [comment]
Perhaps a workaround would be to modify the system IPs with this call:
```
UpdateIPAdddress.fordisplay=false
```

But that would be a workaround, wouldn't it? as these IPs should not be offered to Accounts...

**Comment by DaanHoogland** [comment]
@nvazquez do you recognise this? can we fix this (in 4.14)?

**Comment by Spaceman1984** [comment]
Seems like IP addresses are presented but you cannot actually select it. 

I have set up a few ranges and dedicated 2 ranges to system VMs and 1 range to an account.

![IpRanges](https://user-images.githubusercontent.com/49917670/95953894-cef3c780-0dfa-11eb-8d6e-c996a20eb581.png)

When I acquire new IP addresses, the ones dedicated to system VMs are in the list, but it throws an error if I select it

![aquire ip](https://user-images.githubusercontent.com/49917670/95954109-1aa67100-0dfb-11eb-9696-6622a97411b8.png)

![Insufficient](https://user-images.githubusercontent.com/49917670/95954173-2e51d780-0dfb-11eb-9c00-75d1ae2dffed.png)

Looks like the bug is just the list being returned

**Comment by rvalle** [comment]
@Spaceman1984 aha! I actually never tried to pick them... they just fill up my list of actual public IP addresses.

**Comment by Spaceman1984** [comment]
alright @rvalle, I'll work on a fix.

**Comment by DaanHoogland** [comment]
@Spaceman1984 will you fix primate (old UI is being phased out)

**Comment by Spaceman1984** [comment]
I'll take a look @DaanHoogland, but I'm not sure if the bug is in the UI at this point, I suspect API.

**Comment by rvalle** [comment]
many thanks @Spaceman1984

**Comment by Spaceman1984** [comment]
It's a pleasure to help @rvalle
