### ISSUE TITLE
Can't set the "allow.user.create.projects" to false - backend error

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4318]
Current master:

![image](https://user-images.githubusercontent.com/45762285/92732159-579fc380-f376-11ea-89f8-b66a46240d97.png)

**Comment by andrijapanicsb** [comment]
ping @Spaceman1984 if you have time/will - please take a look. thx

**Comment by rhtyd** [comment]
Fixed in PR https://github.com/apache/cloudstack/pull/4320
