### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project cloud-plugin-ca-rootca

### ISSUE THREAD

**Issue by Yann-Kaelig** [apache/cloudstack#4322]
#### ISSUE TYPE
 * Other

##### COMPONENT NAME
BUILD FAILURE

##### CLOUDSTACK VERSION
4.14.0.0

##### OS / ENVIRONMENT
Debian 10:

maven  3.6.0-1
libmaven-parent-java 31-2
libmaven-resolver-java 1.3.1-1
libmaven-shared-utils-java 3.6.0-1
libmaven3-core-java 3.6.0-1

openjdk-11-jdk:amd64 11.0.8+10-1
openjdk-11-jdk-headless:amd64 11.0.8+10-1
openjdk-11-jre:amd64 11.0.8+10-1
openjdk-11-jre-headless:amd64 11.0.8+10-1

mysql-apt-config_0.8.15-1_all.deb

##### SUMMARY
BUILD FAILURE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project cloud-plugin-ca-rootca: There are test failures.

##### STEPS TO REPRODUCE
Install/Configure a Debian 10 environment for an Openstack build from source. 
Run mvn 

##### EXPECTED RESULTS
test doesnt' failed

##### ACTUAL RESULTS
There are test failures

[surefire-reports.zip](https://github.com/apache/cloudstack/files/5211062/surefire-reports.zip)
[Cloudstack-build-debug-info.zip](https://github.com/apache/cloudstack/files/5211110/Cloudstack-build-debug-info.zip)

##### OTHER INFO
It's a first time with Cloudstack and Java. If you need anything else that can help for the debugging, please tell me.
[Cloudstack documentation](http://docs.cloudstack.apache.org/en/4.14.0.0/installguide/building_from_source.html) seems to be out of date, it could be that I made a mistake or forgot an important package.

Thx

**Comment by Yann-Kaelig** [comment]
Hi.

I finally found the fix here: https://github.com/apache/cloudstack/pull/4226

Thx

**Comment by rhtyd** [comment]
Thanks @Yann-Kaelig can you close the issue then. This was an issue with change in the openjdk release.
