### ISSUE TITLE
Missing package uuid-runtime

### ISSUE THREAD

**Issue by Yann-Kaelig** [apache/cloudstack#4325]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
 * PACKAGING

##### CLOUDSTACK VERSION
 * 4.15.0.0-SNAPSHOT

##### OS / ENVIRONMENT
 * Debian 10 ( minimal installation )

##### SUMMARY
By following the ['Quick Installation Guide: System Template Setup'](http://docs.cloudstack.apache.org/en/latest/quickinstallationguide/qig.html#system-template-setup),  the result is incorrect.

##### STEPS TO REPRODUCE
Run:
`/usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /export/secondary -u http://download.cloudstack.org/systemvm/4.15/systemvmtemplate-4.15.0-kvm.qcow2.bz2 -h kvm -F`

##### EXPECTED RESULTS

> Uncompressing to /usr/share/cloudstack-common/scripts/storage/secondary/eda14a4d-be87-44d6-8d91-6117b37c564c.qcow2.tmp (type bz2)...could take a long time
> Moving to /export/secondary/template/tmpl/1/3///eda14a4d-be87-44d6-8d91-6117b37c564c.qcow2...could take a while

`ls /export/secondary/template/tmpl/1/3/`
eda14a4d-be87-44d6-8d91-6117b37c564c.qcow2

##### ACTUAL RESULTS

> cloud-install-sys-tmplt: line 193: uuidgen: command not found
> Uncompressing to /usr/share/cloudstack-common/scripts/storage/secondary/.qcow2.tmp (type bz2)...could take a long time
> Moving to /export/secondary/template/tmpl/1/3///.qcow2...could take a while

`ls /export/secondary/template/tmpl/1/3/`
.qcow2

**Comment by Yann-Kaelig** [comment]
Unless I'm mistaken or the Quick Installation guide is only valid for CentOS. I found that 'uuid-runtime' is part of **cloudstack-agent_4.15.0.0-SNAPSHOT_all.deb**

However at no time is it said during the **setup of the management server** that the installation of this package is necessary.
Would it be possible to clarify this?

Thx

**Comment by rhtyd** [comment]
@Yann-Kaelig the packaging is only supported for CentOS and Ubuntu, and not explicitly tested on Debian. Please refer to http://docs.cloudstack.apache.org/en/latest/releasenotes/compat.html for compatibility

**Comment by Yann-Kaelig** [comment]
Hi rhtyd.

Thanks for this clarification. In this case, is there any documentation specific to Ubuntu? 
I don't see any reference to this operating system in the quick installation guide documentation.

Thx

**Comment by rhtyd** [comment]
@Yann-Kaelig please see my reply again. There's no QIG for Ubuntu as far as I know in the official docs.

**Comment by weizhouapache** [comment]
it would be to better to add uuid-runtime to dependencies of cloudstack management in debian/control
