### ISSUE TITLE
Changing disk controller type is not working for root disk or data disk

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#4344]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
Cloudstack 4.14.0.0, master 
~~~

##### SUMMARY

Changed the controller from IDE to SCSI from VM settings tab on stopped VM and then started the VM. 
Now cloudstack shows scsi but vmware shows IDE.
CloudStack deliberately fetching the controller details from already existing disks and sets the same irrespective of the VM settings or template settings.

![image](https://user-images.githubusercontent.com/3348673/94136813-197cc680-fe83-11ea-9ced-09c9f47682cf.png)
![image](https://user-images.githubusercontent.com/3348673/94136833-239ec500-fe83-11ea-8179-3e984f8b2f4e.png)

##### STEPS TO REPRODUCE

1. Create VM (on VMware)
2. Stop VM
3. Go to VM settings
4. Change root.disk.controller from IDE to SCSI
5. Start the VM

~~~

~~~

##### EXPECTED RESULTS

~~~
Controller at vCenter should change to SCSI on the corresponding hard disk of VM
~~~

##### ACTUAL RESULTS

~~~
Controller at vCenter still shows IDE on the corresponding hard disk of VM
~~~

**Comment by rhtyd** [comment]
cc @PaulAngus @harikrishna-patnala can you revisit this and close this if we're going to not support this. We may also like to remove support for disk controller in VM/template details in UI/API.

**Comment by nvazquez** [comment]
@harikrishna-patnala @rhtyd this affects 4.14 and starting from 4.15 only to VMs deployed from older templates (not using the deploy-as-is logic)

**Comment by rhtyd** [comment]
ping @Spaceman1984 cc @harikrishna-patnala

**Comment by rhtyd** [comment]
cc @Spaceman1984 w/ @nvazquez @harikrishna-patnala
