### ISSUE TITLE
Revert snapshot only if volume is not attached to a running VM

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#4356]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
Ceph/KVM
~~~

##### CLOUDSTACK VERSION

~~~
4.13
4.14
master
~~~

##### SUMMARY

Snapshotting and reverting snapshots on KVM + Ceph work fine; however, it is allowed to revert to the snapshot while the VM is running. To avoid issues during the revert of a snapshot we need to make sure the VM is stopped.

If the Volume is attached to a VM and that VM is running, snapshot revert should not be allowed.

**Comment by wido** [comment]
I tested and verified this with:

- CloudStack 4.13.1
- Ceph Octopus (15)

The revert worked, but as the VM was running it didn't have any effect.

After stopping and reverting again it worked as expected.

**Comment by DaanHoogland** [comment]
Atre you saying "not a bug", @wido ?

**Comment by wido** [comment]
Well, technically you can do this revert, but it won't have any effect. In order to guarantee data consistency you would need to Stop the VM before doing so.

**Comment by DaanHoogland** [comment]
so still the question remains, do we silently failing consider a bug or well behaved handling of an exception? i.e. how should this be handled?
1. including the stop when a revert is requested
2. throw an error when the vm is running
3. silently ignore the request

**Comment by DaanHoogland** [comment]
3. meaning this issue being closed as "not a bug"

**Comment by wido** [comment]
I would say Option 2: Throw an error when the VM is running

**Comment by DaanHoogland** [comment]
as you guys can test this will you implement a PR @GabrielBrascher @wido ?

**Comment by wido** [comment]
Yes. @GabrielBrascher is working on a PR. This issue is here to track it and close once the PR is merged.

**Comment by GabrielBrascher** [comment]
I tried to revert a VM snapshot either via UI or API and I could not reproduce this issue on 4.15. it works as expected and the user will get an exception with the following message _"The VM the specified disk is attached to is not in the shutdown state."_
