### ISSUE TITLE
ACS unable to set VLAN to Trunk on Distributed Virtual Switches

### ISSUE THREAD

**Issue by alexandremattioli** [apache/cloudstack#4358]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Networking

##### CLOUDSTACK VERSION
4.14

##### CONFIGURATION
Advanced networking, Distributed Virtual Switches on VMWare 6.7

##### SUMMARY
ACS unable to set VLAN to Trunk on Distributed Virtual Switches

##### STEPS TO REPRODUCE

1- Create physical network with Distributed Virtual Switches
2- Create guest network on the physical switch with DVS
3- Set VLAN/VNI id to 4095 
4 - Deploy VM in new network

Error shows up on vCenter
![4095](https://user-images.githubusercontent.com/60507727/94693495-b62fe000-032b-11eb-934f-dcdf7e862c1a.JPG)

**Comment by PaulAngus** [comment]
Can you add some detail please.

**Comment by alexandremattioli** [comment]
Details were there but not showing, some issue with formatting, fixed now.

**Comment by rhtyd** [comment]
@alexandremattioli can you check and close the bug if it was env issue, or provide details/steps on how to reproduce it? Thanks

**Comment by Spaceman1984** [comment]
Seems like that ID is out of range @alexandremattioli according to https://kb.vmware.com/s/article/2075351

**Comment by Spaceman1984** [comment]
I tested according to your steps and I get the error, but I believe this is a limitation not on Cloudstack.

**Comment by rhtyd** [comment]
@Spaceman1984 can you discuss with @alexandremattioli and @PaulAngus and change the tags to new-feature if this is a CloudStack limitations (known/unknown?).

**Comment by Spaceman1984** [comment]
I propose we move this to 4.16 and to make this a small new feature. 

If you are using a dvSwitch and want to do VLAN trunking, a second range parameter is required. In the UI we will need a checkbox and a start and end ID.

Otherwise, a temporary and imperfect fix would be to just trunk all ids if 4095 is sent.

Would you guys agree? @alexandremattioli @PaulAngus

**Comment by rhtyd** [comment]
Let's move to 4.16, this is not blocker/critical unless we hear from reporters

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4557, this will make into future 4.14.1.0, 4.15.1.0, 4.16.0.0
