### ISSUE TITLE
Raw root volumes being identified as qcow2 & fail to start

### ISSUE THREAD

**Issue by RomanGz** [apache/cloudstack#4368]
##### ISSUE TYPE

 * Other
##### COMPONENT NAME
KVM
~~~

~~~

##### CLOUDSTACK VERSION
4.14
~~~

~~~

##### OS / ENVIRONMENT
18.04

##### SUMMARY
Upgraded from 4.9
Have various instances with raw root images that fail to start
Restarting these instances, CS passes the `format=qcow2` to qemu, when it should be `format=raw`.
qemu returns: `Image is not in qcow2 format`
If I manually edit the DB and change the path field to `imange-id.raw` and rename the image to match, then it starts up as expected and passes `format=raw`
They're all marked as QCOW2 type in the db, even though they're raw, but changing that field has no effect.
None of my images currently have extensions.

**Comment by DaanHoogland** [comment]
@RomanGz have you had this working with older versions?

**Comment by andrijapanicsb** [comment]
there was a lot of mess in 4.5-->4.8 when it comes to the type/extension as in the DB
CloudStack always creates QCOW2 (AFAIK) on NFS/filesystem storage, so TBH I'm not sure how you ended up with RAW images on your storage? Can you advise please?
Anyway, whatever is your format on storage, that should be reflected in the DB (volumes table) - but keep in mind that having RAW (instead of the QCOW2) might (most probably will) cause various issues working with those volumes

**Comment by RomanGz** [comment]
Yes. It worked before through versions 4.2, 4.4, 4.9. 

We only use local storage pools. 
I’m not entirely sure how we ended up with raw images, but I’m sure some of them have been running as far back as 4.2, or even older perhaps. 

We have another 4.9 install running. I’m going to go through it to see if I can make sense of the raw situation.

**Comment by RomanGz** [comment]
So looks like everything created under 4.4 and earlier is raw. DB format says it's QCOW2, but as I mentioned, changing that field has no effect on actually running the instance - it still launches it with format=qcow2. Should the volumes.format field not determine how the VM is launched?

**Comment by andrijapanicsb** [comment]
Once the volume is created, there is no more changes to it. The type will, however, be used in some code to determine how to do some actions (say, snapshot or similar volume-managing-actions).

My advice would be to se if you are having any issues with the current state - if not, great.

If you do have issues with RAW, then, you can test converting RAW to QCOW2 - both inside DB and the actual volume itself (qemu-img convert...) - make sure the converted volume has the same name as before - and needles to say, test on some test VMs/volumes, and ensure VMs are stopped, i.e. the volume is not in use.

**Comment by RomanGz** [comment]
The first thing I tried was converting it to qcow as a test, and that of course works - But I would have to convert over 200 instances.

The only issue with RAW is that CS configures it with format=qcow2 when generating the instance config. I'm guessing it assumes KVM=qcow2. We don't care about the loss of features with raw as we don't utilize any of them. 

Is the final qemu config/arguments generated on the manager, or agent side?

**Comment by RomanGz** [comment]
Mystery solved. Apparently, we had a custom build floating around that forced the build to raw format, as well as change the format in LibvirtVMDef.java to raw if the image format was raw.
Still seems like that's something CS could manage to check on its own. Not a fan of running custom builds - because of this exact situation.
