### ISSUE TITLE
Incorrect count returned by findHostsForMigration

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#4371]
findHostsForMigration returns wrong count

##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION
master

##### STEPS TO REPRODUCE
~~~
(localcloud) SBCM5> > find hostsformigration virtualmachineid=3a2e2d93-2105-4b77-a5df-c2c07caab43c filter=
{
  "count": 6,
  "host": [
    {},
    {}
  ]
}

~~~

##### EXPECTED RESULTS
The right count

**Comment by DaanHoogland** [comment]
#relates to #4372
