### ISSUE TITLE
Cpu and Memory Overprovisioning calculation

### ISSUE THREAD

**Issue by meysamfarazmand** [apache/cloudstack#4390]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.13.0.0
~~~

##### CONFIGURATION

cpu.overprovisioning.factor=6
mem.overprovisioning.factor=1.1
VMware Tools on All VMs

##### OS / ENVIRONMENT

CentOS 6

##### SUMMARY

My cloudstack deployment has 1000 VMs. i had configured cpu.overprovisioning.factor=3.5 until i faced 95% of cpu allocation and decided to change cpu.overprovisioning.factor=6 in cluster settings. 
i expected new settings being applied and "Allocable" cpu goes higher than "Allocated" ,but "Allocable" and "Allocated" cpus go up together and no matter which number has been set in "cpu.overprovisioning.factor". 
As i have read in cloudstack documentations, it seems i MUST stop and start all VMs for new "cpu.overprovisioning.factor" settings to be applied. is this true or there is another way to reach my goal?
http://docs.cloudstack.apache.org/projects/archived-cloudstack-administration/en/latest/hosts.html#requirements-for-over-provisioning

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@meysamfarazmand I think your are interpreting the docs correctly. I don't know of a workaround.

**Comment by andrijapanicsb** [comment]
not an issue, closing - please read the docs.
