### ISSUE TITLE
Find suitable storage for migration regression

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4400]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware migration, API
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### CONFIGURATION

VMware

##### SUMMARY

When executing the api agains attached volume we observe that none of the pools is marked suitable, a little investigation was done suspecting the following change: 
https://github.com/shapeblue/cloudstack/blob/ovfprops-and-vsphere-adv-together/server/src/main/java/com/cloud/server/ManagementServerImpl.java#L156

```
        //This is an override mechanism so we can list the possible local storage pools that a volume in a shared pool might be able to be migrated to
diskProfile.setUseLocalStorage(true);

```
Before searching for the suitable storage pools,  volume is marked as using local storage just to also find any local storage pools to which volume can be migrated along with the shared storage pools. 

But this is causing regression for zone wide storage pools, while zone wide storage pool allocator searches for any zone wide storage pools the entrance check is 

`if (dskCh.useLocalStorage()) {    return null;}
`which causing zone wide storage pool allocator returning nothing and at the end findStoragePoolsForMigration API shows all zone wide storage pools are “not suitable“.

Below is the screenshot of a volume which is not associated with any storage policy but still showing “vvol5-zone“ as “not suitable“.
![image-20201011-195301](https://user-images.githubusercontent.com/13551960/95826137-8d034c80-0d3a-11eb-9ef9-06b2f0c83b3b.png)

**Comment by sureshanaparti** [comment]
@borisstoyanov the check in the Zone wide pool allocator `if (dskCh.useLocalStorage()) { return null;}` should be ok, as the local storage can never be a zone wide pool and the disk profile want to find suitable local storage pools only, as the flag useLocalStorage is set. "useLocalStorage" is appropriately set to find the local pools, for zone / cluster-wide pool, this is set to false.

**Comment by sureshanaparti** [comment]
The override mechanism to list the possible local storage pools is skipping the zone wide pools, and so when migrating a volume attached to a running VM doesn't list zone wide pool as a suitable pool in UI, with _findStoragePoolsForMigration_ API.

To fix this and consider zone wide pools for migration, the condition` if (dskCh.useLocalStorage()) { return null;}` has to be removed from ZoneWideStoragePoolAllocator. This is already addressed in PR https://github.com/apache/cloudstack/pull/4304

**Comment by harikrishna-patnala** [comment]
@sureshanaparti if we remove the local storage condition from ZoneWideStoragePoolAllocator then it implies that any volume on local or cluster scoped or zone wide storage can be migrated to zone wide storage. If those operations are functionally allowed then the fix that you mentioned is fine. 

Can you please confirm if volumes on any storage(local, cluster, zone) can be migrated to zone wide storage.

**Comment by sureshanaparti** [comment]
@harikrishna-patnala the intention is to list all the storage pools and mark as suitable / unsuitable. If unsuitable pool is selected for migration, the appropriate cmd is sent to hypervisor resource for migration. If succeeds, the offering, etc. applicable details are updated, else keeps the same.

Please take a look at the actual implementation in the PRs: https://github.com/apache/cloudstack/pull/2425 and https://github.com/apache/cloudstack/pull/2486.

The override mechanism in these changes is skipping the zone wide pools, which are also has to be considered.

**Comment by rafaelweingartner** [comment]
@harikrishna-patnala and @sureshanaparti exactly that.

**Comment by DaanHoogland** [comment]
@borisstoyanov can you check in 4.15?
also the link in the summary gives me a 404, can you update the description, please?

**Comment by DaanHoogland** [comment]
marking 4.16 as #4304 is as well
