### ISSUE TITLE
Retry logic - ignores tags

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4406]
NOT burning issue, as it's hardly reproducible - but a proper code analysis might prove bug (non) existance.

I've seen this in master/PR #4307 (VMware , but probably a general issue) - an issue with storage tags not being honored during VM deployment retry.

By using tags, I've made sure a VM will be deployed on a specific storage pool.

Due to VM failing to start on host X on storage X _(whatever the root cause - i.e vApp properties missing in the VM deployment API call and no default value set - so VM fails to start on VMware side)_ - **ACS will retry the action for a few times, and eventually will try to deploy a VM on different datastore than the one choosen by usage of storage tags** - I've seen a constant VM "reallocate" task to other hosts until many hosts were tried and failed to start a VM - then we cleaned-up that VM, and deployed VM from scratch on a different datastore.

i.e. storage tags are NOT doing the work during retry logic - as it seems (or does it...)

Perhaps also @alexandremattioli saw similar issue with host tags in 4.14 or so (please update here if that's the case...)

The way to reproduce this is a bit problematic - I can only think about the edge case that I saw (which btw, will be stated as a limitation in 4.15 Release notes):

- can be reproduced by clean ACS 4.14 install, registering a template that has some vApp properties (I can provide some) with no default value set for at least 1 vApp property. Then upgrade to master (PR 4307) and try to deploy VM from that template (some vApp property has NO default value) - on **VVols** storage (new in ACS 415/PR #4307), while still having an old fashioned NFS pool as well (not targeted by the storage tag).
- I'm not sure what other way would be a good way to cause some failure on VMware side (when starting a VM)

Worth testing also with 2 storage pools, but where the targetd one (by storage tags) is over the allocated threashold and can't be used - see then if other pools will be used (despite NOT having the required storage tag)

**Comment by andrijapanicsb** [comment]
Might be also a false alarm - but I thought it's worth documenting it, in case someone would like to validate the retry logic in ACS.

**Comment by rhtyd** [comment]
@nvazquez @sureshanaparti @davidjumani @shwstppr @Pearl1594 @DaanHoogland @weizhouapache - any update on this, who's assigned/working on this? Thanks.

**Comment by nvazquez** [comment]
@weizhouapache please advise if this needs fixing after your checks
