### ISSUE TITLE
Sensitive info when failure on attaching a deleted/recovered volume

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4419]
VMware, master

WHen a volume is deleted, then recovered - there is an issue attaching a volume (@weizhouapache didn't you work on a PR for allowing delete/expunge vs. just deletting a volume? perhaps you can advise here?) - sensitive info is sent by the backend and displayed in UI:

![image](https://user-images.githubusercontent.com/45762285/96840368-a39c5880-144a-11eb-9d1e-3f4683cbedd3.png)

The simple fix might be to remove the vSphere volume location from the message - just keep the first sentence of the error response, but ensure that the full info is logged in debug/elsewhere in the mgmt log.

**Comment by andrijapanicsb** [comment]
cc @DaanHoogland - FYI

**Comment by rhtyd** [comment]
cc @Spaceman1984

**Comment by DaanHoogland** [comment]
@andrijapanicsb why is the path sensitive? to my knowledge authorisation of the user had already been done when this error occurs? is the user not allowed to know where their disks reside?

**Comment by andrijapanicsb** [comment]
@DaanHoogland I'm sure you are not saying that an average joe ("user" role) is allowed to learn your internal IPs (and internal VM name?)

**Comment by DaanHoogland** [comment]
ah, the ip i missed, sure . just don't see harm in the internal name
