### ISSUE TITLE
Adding a cluster

### ISSUE THREAD

**Issue by RRadziejewski** [apache/cloudstack#4423]
Hello,

I am trying to add a cluster into my apache cloudstack 4.14
I have v center vSphere Client version 7.0.1.00000

When adding i have following error:

This cluster null belongs to vCenter https. But this zone is associated with VMware DC from vCenter vcenter.cloud.xxx.com Make sure the cluster being added belongs to vCenter vcenter.cloud.xxx.com and VMware DC XXX XXX

**Comment by mkriegs** [comment]
AS far i know its not Supported in this version of cs. 
There is PR for 4.16. allready. https://github.com/apache/cloudstack/pull/4300
The SDK is Missing in your version and lots of Things chanced in 7.0 agains 6.7.

**Comment by rhtyd** [comment]
That's correct, vSphere7 support will be added in future version.

**Comment by ManuDIY** [comment]
Hello everyone.
Can someone help me with the following problem?
I have installed successfully the cloudstack management server v4.14, the pre-compiled version and i cannot add a vsphere 6.7 cluster within cloudstack.
It gives me this error.
![image](https://user-images.githubusercontent.com/37869585/104076726-9f006880-521f-11eb-96ba-ab90b9708947.png)

Thanks in advance for any idea / help,
Regards

**Comment by rhtyd** [comment]
@ManuDIY are you using Ubuntu packages from download.cloudstack.org? To use 4.14 with Vmware you'll need noredist packages that you can get from http://shapeblue.com/packages

**Comment by DaanHoogland** [comment]
@ManuDIY is this still an issue for you?

**Comment by manusysadmin** [comment]
> @ManuDIY are you using Ubuntu packages from download.cloudstack.org? To use 4.14 with Vmware you'll need noredist packages that you can get from http://shapeblue.com/packages

Hi @rhtyd, thanks for the tip. i will give it a try.

**Comment by manusysadmin** [comment]
> @ManuDIY is this still an issue for you?

yes, it is but i will try to do what @rhtyd just suggested to me.

**Comment by manusysadmin** [comment]
> @ManuDIY is this still an issue for you?

yes, it is but i will try to do what @rhtyd just suggested to me.
