### ISSUE TITLE
Maven noredist build option broken

### ISSUE THREAD

**Issue by DennisKonrad** [apache/cloudstack#4431]
Hi,

the following build option used to work but doesn't right now:

mvn install -Dnoredist -P developer,systemvm

Removing the noredist build option makes it work again but I think it should also work with noredist.
I'm suspecting a recent merge for breaking the option:
https://github.com/apache/cloudstack/pull/4307

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
maven build infrastructure

##### CLOUDSTACK VERSION
recent github master

##### STEPS TO REPRODUCE
git clone https://github.com/apache/cloudstack
cd directory
 mvn install -Dnoredist -P developer,systemvm

**Comment by DaanHoogland** [comment]
@DennisKonrad did you install the non-redistributable requisites? there was (at least) one from vmware added

**Comment by DennisKonrad** [comment]
Yes I did, it complains about about not beeing able to resolve dependency for vmware-pbm and vmware-vim25 version 6.7. But installing those like shown below doesn't work.

mvn install:install-file -Dfile=pbm_67.jar    -DgroupId=com.cloud.com.vmware -DartifactId=vmware-pbm     -Dversion=6.7   -Dpackaging=jar
mvn install:install-file -Dfile=vim25_67.jar  -DgroupId=com.cloud.com.vmware -DartifactId=vmware-vim25   -Dversion=6.7   -Dpackaging=jar

**Comment by DaanHoogland** [comment]
ok, that is not good, however I have seen al lot of colleagues use it and the integration tests work as well, so I still kind of think it is an environmental issue. can you check your ~/.m2/repository/com/cloud dir for the contents?

**Comment by DennisKonrad** [comment]
Both folders are there and contain their files. I'll double check for problems in the environment as you state integration tests are working.

**Comment by DennisKonrad** [comment]
Maybe you can give me a hint were to look. Even when installing all of the non oss packages I'm getting this error message:


[ERROR] Failed to execute goal on project cloud-vmware-base: Could not resolve dependencies for project org.apache.cloudstack:cloud-vmware-base:jar:4.15.0.0-SNAPSHOT: The following artifacts could not be resolved: com.cloud.com.vmware:vmware-vim25:jar:6.7, com.cloud.com.vmware:vmware-pbm:jar:6.7: Failure to find com.cloud.com.vmware:vmware-vim25:jar:6.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cloud-vmware-base

**Comment by DaanHoogland** [comment]
@DennisKonrad that message means that there is no local copy and maven is trying to download it. It shouldn't if it finds it in your cache. Can you double check the jar for validity? (and the pom as well, btw)

**Comment by DennisKonrad** [comment]
@DennisKonrad As I'm installing the dependencies manually before trying to compile there should be a local copy.

I checked and it does install the jar but append ".lastUpdated". I tried different things to counter this but until now to no effect.
Do you now how to fix this?

**Comment by DaanHoogland** [comment]
not sure @DaanHoogland ;)
i think you need to clear the `com.cloud` package dir and reinstall all, or at least dirs for the ones with the `.lastUpdated` extensions

**Comment by DaanHoogland** [comment]
any resolution yet @DennisKonrad ?

**Comment by DennisKonrad** [comment]
It needed a weird combination of removing the `.lastUpdated` jars and doing an offline build (`-o`) and the `-U` flag to get everything in order again. But now it's working.

Oddly the build just broke without someone touching it. Seems the new dependencies were to much for the installation. 
I'll go ahead and close this
