### ISSUE TITLE
Adding kubernetes version failed

### ISSUE THREAD

**Issue by RRadziejewski** [apache/cloudstack#4434]
Hello i am running cloudstack 4.14 and trying to create kubernetes version however this is not working

When running command: 
/usr/share/cloudstack-common/scripts/util/create-kubernetes-binaries-iso.sh k8s/ 1.16.3 0.7.1 1.12.0 "https://cloud.weave.works/k8s/net?k8s-version=1.12.5" https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml

i get error: 
/usr/share/cloudstack-common/scripts/util/create-kubernetes-binaries-iso.sh: line 99: [: : integer expression expected
I: -input-charset not specified, using utf-8 (detected in locale settings)
genisoimage: No such file or directory. Unable to open disc image file 'k8s//setup-v1.16.3.iso'.

any idea ?

When doing this via ui with http://download.cloudstack.org/cks/setup-1.16.3.iso this link as a url
I can see lthat version is added but it's not existing when trying to add cluster.
After checking the iso and the zone it says message Connection refused.

**Comment by shwstppr** [comment]
@RRadziejewski script is not being able to create iso at given location `k8s/`. Please use complete path for the output directory or use `./k8s` if you are running script from parent directory.
For download.cloudstack.org links, it seems you have restricted Internet access in your environment as above link seems to be working fine.

**Comment by RRadziejewski** [comment]
Any idea how to allow internec access? i don't know how to do it because i am unable to wget this iso via wget from server terminal.

**Comment by RRadziejewski** [comment]
Okey i finally created version but how to add it via api ?  There should be something like add kubernetessupportedversion
but how to use it

**Comment by RRadziejewski** [comment]
<img width="605" alt="chrome_2020-10-29_09-16-33" src="https://user-images.githubusercontent.com/32438378/97542708-85dd6f00-19c7-11eb-9bc4-d73e436b0439.png">

**Comment by RRadziejewski** [comment]
If i have it locally on my server under /root/k8s/setups.iso how do i add it ?

**Comment by RRadziejewski** [comment]
File:// type urls are currently unsupported

**Comment by RRadziejewski** [comment]
How to use cloudmonkey behind a proxy ??

**Comment by shwstppr** [comment]
@RRadziejewski For adding k8s version ISO, you will need to provide http url for your ISO file. If your environment is deployed is a way to prevent access to Internet. You can run Apache webserver locally to register templates and ISOs.

For cloudmonkey proxy support, check https://github.com/apache/cloudstack-cloudmonkey/commit/98fa4934c20a2de8d57d206e8cebe12a9eb338ba

Since the questions and issues you have related to different operations, it will be better to use CloudStack mailing lists to ask your queries, https://cloudstack.apache.org/mailing-lists.html

**Comment by RRadziejewski** [comment]
I've read about running HTTP_PROXY="x" HTTPS_PROXY="x" ./cmk But still templates iso states connection refused

**Comment by shwstppr** [comment]
@RRadziejewski Problem is not with cloudmonkey. You should check your SSVM. See if it can ping any external IP. You can get the option for running diagnostic tools in VM view for system VMs (Infrastructure -> System VMs -> SSVM -> Run diagnostics).
http://docs.cloudstack.apache.org/en/latest/adminguide/systemvm.html#secondary-storage-vm

**Comment by RRadziejewski** [comment]
Okay i cannot ping anything external how can i fix it ? What are default credentials to ssvm ?

**Comment by RRadziejewski** [comment]
Thank you by the way for help you are really helpfull with getting me into cloudstack

**Comment by RRadziejewski** [comment]
So i have logged in to ssvm exported http_proxy and https_proxy i am able to curl http://download.cloudstack.org/cks/setup-1.16.3.iso  but still connection refused on zone

**Comment by RRadziejewski** [comment]
(localcloud) 🐱 > add kubernetessupportedversion name=k8s1.16 semanticversion=1.16.3 url=http://download.cloudstack.org/cks/setup-1.16.3.iso mincpunumber=2 minmemory=2048
{
  "kubernetessupportedversion": {
    "id": "c2e39b52-de54-4c61-ae67-3455b7f612bf",
    "isoid": "7530c677-0499-4558-91e7-9cf59ba3227b",
    "isoname": "k8s1.16-Kubernetes-Binaries-ISO",
    "isostate": "Creating",
    "mincpunumber": 2,
    "minmemory": 2048,
    "name": "k8s1.16",
    "semanticversion": "1.16.3",
    "state": "Enabled",
    "supportsha": true
  }
}

But still zone claims that connection is refused any idea ?

**Comment by RRadziejewski** [comment]
How to configure http_proxy for ssvm or management server ? Maybe zone needs some update or network configuration inside zone let's say storage network ? Plesae help

**Comment by RRadziejewski** [comment]
i can curl google.com fro mgmt and from ssvm but still connection refused when adding kubernetes version

**Comment by DaanHoogland** [comment]
@RRadziejewski I see no cloudstack bug here but only network issues. can you add more details or close this issue? cc @shwstppr

**Comment by RRadziejewski** [comment]
You can close this issue however if you would like to install cloudstack behind a proxy i didn't proceed with it :( We've had to turn proxy off, thank you for attention.
