### ISSUE TITLE
cpvm not support VMware 7.0 console

### ISSUE THREAD

**Issue by dukeware** [apache/cloudstack#4441]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
CPVM
~~~

##### CLOUDSTACK VERSION
~~~
14.1
~~~

**Comment by DaanHoogland** [comment]
@dukeware I suppose you mean cloudstack version 4.14.1? it is not released so did you test this with a build of the 4.14 branch?

**Comment by DaanHoogland** [comment]
@dukeware just realised that vmware 7 is not supported by cloudstack yet

**Comment by rhtyd** [comment]
Vmware 7.0 is not supported yet

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4300
