### ISSUE TITLE
[Investigation] Templates/ISOs are not removed but marked as Inactive

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#4470]
Probably not an issue, but worth investigating the reason why templates/ISOs are not deleted in database (the removed column stays NULL) after deleting a template/ISO. The ticket is raised after some doubts on the reviews of PR #4047 

##### ISSUE TYPE
 * Other

##### COMPONENT NAME
~~~
API, templates, ISOs
~~~

##### CLOUDSTACK VERSION
~~~
All versions
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Deleting a template/ISO does not actually remove it, but set it to Inactive and hidden

##### STEPS TO REPRODUCE
~~~
Remove a template/ISO
~~~

##### EXPECTED RESULTS

~~~
Template/ISO removed in database
~~~

##### ACTUAL RESULTS

~~~
Template/ISO state = 'Inactive' but removed column not changed
~~~

**Comment by rhtyd** [comment]
Cc @Spaceman1984 looks like GC issue, have you seen this or can you discuss with @nvazquez and investigate/fix?

**Comment by Spaceman1984** [comment]
I'll take a look @rhtyd

**Comment by Spaceman1984** [comment]
I'm not sure what the original problem was, I have traced the active/inactive fields to a commit in 2013. In the git log there is speak of some kind of problem that was solved from version 2.1.x to do with the removed column not being correctly used.
```
Fixed the problem with offerings and templates.  These two items due to a previous patch all the way back in 2.1.x versions uses the removed column incorrectly.  No one fixed since then.  Hence, there's a bunch of findbyidincludingremoved calls in the cloudstack code around these two items.

abbae2aa Alex Huang <alex.huang@citrix.com> on 2013/08/27 at 02:30
```

**Comment by Spaceman1984** [comment]
@rhtyd Like @nvazquez said, there is no issue here, just a question about design choices.

**Comment by DaanHoogland** [comment]
ok, this means we'll have to look for those find including removed calls and try to make sure the removed column is correctly filled at the correct moment. (future version for now)

**Comment by rhtyd** [comment]
Looks liked fixed in https://github.com/apache/cloudstack/pull/4748
@nvazquez can you check?

**Comment by nvazquez** [comment]
Tested - fixed confirmed. Thanks @Pearl1594 @rhtyd
