### ISSUE TITLE
Cloudstack Agent SetMonitorServiceCommand 

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack#4474]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cloudstack-Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.14 , running on Ubuntu 18.04
~~~

##### CONFIGURATION

Advance Network, with SG

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

~~~
Create VM , and In Cloudstack log show:

2020-11-17 03:50:54,123 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:d557e0de) Expected 1 answers while executing SetMonitorServiceCommand but received 3



Cloudstack Usage for Network Byte send and Received is not calculated ,  Suspect is this SetMonitorServiceCommand warning and not populate the data correctly

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~




~~~

**Comment by DaanHoogland** [comment]
@hstan77 can you reproduce this on other hypervisor and cloudstack versions?
can you add your libvirt / qemu versions here?

@weizhouapache @andrijapanicsb sounds familiar?

**Comment by hstan77** [comment]
HI

I am running on Ubuntu 18.04, Cloudstack 4.14 , 
libvirt version: 4.0.0, package: 1ubuntu8.17 (Marc Deslauriers

Yes, Hypervisor is KVM.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4489
