### ISSUE TITLE
add cpu percentage and value

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#4488]
cpu percentage and value as for memory #4478 

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
API, metrics
~~~

##### CLOUDSTACK VERSION

~~~
all
~~~

##### SUMMARY

as in #4478 (for memory), cpu could have percentage and value output for use in UI or scripts

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS	

~~~

~~~

**Comment by davidjumani** [comment]
@DaanHoogland This would mean reverting `cpuallocated` to the original allocated value and adding a new field `cpuallocatedwithoverprovisioning` ?

**Comment by DaanHoogland** [comment]
no, it would mean adding two new response parameters as done for memory and leaving the existing as is but deprecated. cc @weizhouapache @rhtyd

**Comment by davidjumani** [comment]
@DaanHoogland It's always been a percentage, just that it was changed to consider overprovisioning in https://github.com/apache/cloudstack/commit/09de5e0b51d1cd0e1d84eef120ae48358300fdcd So would it make sense to revert it and add a new field `cpuallocatediwthoverprovisioning` for naming consistency ?

**Comment by DaanHoogland** [comment]
so what would the resulting field(-names) be, @davidjumani ?
and which ones will in the endd be deprecated?

**Comment by davidjumani** [comment]
I'd suggest reverting `cpuallocated` to not consider overcommit and introducing `cpuallocatediwthoverprovisioning` to follow the naming convention here 
https://github.com/apache/cloudstack/blob/4.14/api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java#L106
https://github.com/apache/cloudstack/blob/4.14/api/src/main/java/org/apache/cloudstack/api/response/HostForMigrationResponse.java#L115

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4499
