### ISSUE TITLE
User vm details is readonly on UI but still can be changed via api or cloudmonkey/cmk

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4514]
#3244 introduced a global setting to make some details read-only on UI.
however, these details can still be changed by cloudmonkey.

it would be better to improve it.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM
~~~

##### CLOUDSTACK VERSION

~~~
4.14/4.15
~~~

##### STEPS TO REPRODUCE

login as domain admin or regular user
create a dynamic offering
deploy a vm  with the offering, and stop it
cpuNumber, cpuSpeed and memory are visible and editable in vm Settings page
change global setting user.vm.readonly.ui.details to "dataDiskController, rootDiskController,cpuSpeed,memory,cpuNumber"
cpuNumber, cpuSpeed and memory are visible but not editable in vm Settings page

use cmk to update vm with details[0].cpuNumber=X

~~~

~~~

##### EXPECTED RESULTS

~~~
Fail with error similar as
```
You're not allowed to add or edit the restricted setting: cpuNumber
```
~~~

##### ACTUAL RESULTS

~~~
cmk command is successful. vm cpunumber is changed
~~~

**Comment by rhtyd** [comment]
Fixed in #4629
