### ISSUE TITLE
UI allows ISO images, uploaded/registered as not extractable to be downloaded

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#4535]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14
4.15 RC1
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The Images > ISOs page ignores the backend flag 'isextractable' and allows user to download an ISO even when it was uploaded with this setting unchecked.

##### STEPS TO REPRODUCE
~~~
1. Register (or upload) ISO image, leaving the 'Extractable' option unchecked.
~~~
![image](https://user-images.githubusercontent.com/12384665/101922632-01415b80-3bd7-11eb-9629-683cba50a0b6.png)
~~~
2. Go to Images > ISOs > new ISO, wait until it's successfully installed and try to download it:
~~~
![image](https://user-images.githubusercontent.com/12384665/101922805-3e0d5280-3bd7-11eb-9380-c9b416a738fc.png)

##### EXPECTED RESULTS
~~~
The download icon should be missing and this operation must be forbidden.
~~~

##### ACTUAL RESULTS
~~~
The UI ignores this flag, allowing user to download ISO images marked as non-extractable.
~~~

##### ADDITIONAL INFORMATION

Here is the request when registering a new ISO image - the isextractable flag is properly sent:

http ://10.10.2.113:8080/client/api/?url=http:%2F%2F10.5.1.128%2Fopenvm%2Fcloudstack%2Fiso%2FTinyCore-8.0.iso&name=Tiny+Core&displaytext=Tiny+Core&zoneid=-1&bootable=true&ostypeid=0b9e0c15-3bad-11eb-9ec8-1e00830138c0&**isextractable=false**&ispublic=false&isfeatured=false&command=registerIso&response=json

And this is the server response when preparing the details page - the same flag is properly sent from the server:

account: "admin"
bits: 64
bootable: true
checksum: "18a24183958339cb0508a9e27abd81494514469529bf1a4dd0cbc8a3c4d502a94400e6c58b6d54d5043eb2100946f6e85dd7032bc12642e4ab2e8907ed88dbcb"
created: "2020-12-11T15:23:18+0000"
crossZones: true
directdownload: false
displaytext: "Tiny Core"
domain: "ROOT"
domainid: "0b746f3a-3bad-11eb-9ec8-1e00830138c0"
id: "7c51f019-fbed-485d-a2f4-d2ca9e235e78"
isdynamicallyscalable: false
**isextractable: false**
isfeatured: false
ispublic: false
isready: true
name: "Tiny Core"
ostypeid: "0b9e0c15-3bad-11eb-9ec8-1e00830138c0"
ostypename: "Other Linux (64-bit)"
passwordenabled: false
size: 16777216
status: "Successfully Installed"
tags: []
url: "http://10.5.1.128/openvm/cloudstack/iso/TinyCore-8.0.iso"
zoneid: "b321c664-734a-4c98-9c4d-9a692d99f08e"
zonename: "ref-trl-2078-k-M7-rohit-yadav"

**Comment by DaanHoogland** [comment]
@vladimirpetrov this seems a primate bug, as we have not merged it in the main tree yet can you submit it there?

**Comment by vladimirpetrov** [comment]
@DaanHoogland I'm not really sure if it's only about the UI - perhaps the backend also should not allow extracting of an image even when UI allows it. It's always a good practice to have checks on both places.

**Comment by vladimirpetrov** [comment]
I just tested this on 4.14 and we have the same behavior there - using the legacy UI.

**Comment by rhtyd** [comment]
Thanks @vladimirpetrov - since this is a known historic issue, let's fix in the next minor release or 4.16.0.0

**Comment by andrijapanicsb** [comment]
@vladimirpetrov Did you test with a regular user account?
Admins can always download even the non-extractable templates....

If you register a public templat/ISO as root admin (non-extractable) - and then if the regular user fails to download it - then there is no bug. If the regular user can still download it - it's a bug.

**Comment by andrijapanicsb** [comment]
Again, my 2 cents after testing with 4.14;
- root admin account can download all templates/ISOs, irrelevant if it's marked as Extractable or not
- If a template is not extractable, regular user accounts can not download it - see images below:

![image](https://user-images.githubusercontent.com/45762285/102255825-e63e5680-3f0a-11eb-9cf9-fcaffd460e8c.png)

(Even more, when the template is marked as public and extractable (ISO uploaded by the root admin) - _the regular user can not download it (this looks like a bug, indeed),_ while the user can download it's own uploaded ISO)

So, I don't think the reported issues is a bug, but a design behaviour.

**Comment by DaanHoogland** [comment]
@vladimirpetrov can you test the user vs admin behaviour and revisit please?

**Comment by Spaceman1984** [comment]
I tested the UI  with master and the behavior is different, an admin does not have the download icon for an iso that is not marked as extractable. The question now is - is master or 4.13/4.14 broken?

**Comment by rhtyd** [comment]
@Spaceman1984 can you test against 4.15 RC2? Thanks.

**Comment by vladimirpetrov** [comment]
I did, @rhtyd , the issue is there:

![image](https://user-images.githubusercontent.com/12384665/102465013-cc5d5a80-4055-11eb-93b0-3da46284864e.png)

**Comment by DaanHoogland** [comment]
why did you close this @andrijapanicsb , i see no comments indicating it isn't a problem anymore

**Comment by andrijapanicsb** [comment]
um... I don't recall doing it (probably accidental click)

**Comment by rhtyd** [comment]
@vladimirpetrov can you check if in the modern UI we don't show the button to download now?
