### ISSUE TITLE
ISO image uploaded with 'Featured' attribute does not show in the 

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#4541]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.14
4.15 RC1
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Even when uploading/registering an ISO image with the 'Featured' option checked, it doesn't show in the 'Featured' tab when adding a new instance.

##### STEPS TO REPRODUCE
~~~
1. Register (or upload) an ISO image, making sure the 'Featured' option is checked.
~~~
![image](https://user-images.githubusercontent.com/12384665/102060798-4fcf3f80-3dfb-11eb-8b18-33b30baa5d79.png)

~~~
2. Start adding a new instance 
~~~
![image](https://user-images.githubusercontent.com/12384665/102061364-0f23f600-3dfc-11eb-99f0-faa491d8d42c.png)

##### EXPECTED RESULTS
~~~
The uploaded/registered ISOs, marked as 'Featured' must be shown in the 'Featured' tab when adding a new instance from ISO.
~~~

##### ACTUAL RESULTS
~~~
The API command invoked by the UI does not return any featured ISOs even when there are such objects in the database:

(localcloud) SBCM5> > list isos filter=featured zoneid=34b429e8-b265-4fcc-a7ce-08517f8c1e77 bootable=true
{
  "count": 1,
  "iso": [
    {}
  ]
}

And here is what we have in the database:

MariaDB [cloud]> select name, featured from vm_template where format='ISO';
+------------------+----------+
| name             | featured |
+------------------+----------+
| vmware-tools.iso |        1 |
| xs-tools.iso     |        1 |
| dCore featured   |        1 |
+------------------+----------+
3 rows in set (0.00 sec)

~~~

**Comment by rhtyd** [comment]
@vladimirpetrov was the test performed as a root admin or normal account?

**Comment by vladimirpetrov** [comment]
I was testing as root admin.

**Comment by andrijapanicsb** [comment]
My 2 cents (after testing on 4.14):

- If the template/iso is not marked as public, it will also not appear in the Featured (despite being marked as "Featured) - it seems this is how it works for a long time now
- Registering (upload from local) ISO as "admin" and marking it as "public" and "featured" - then trying to deploy a VM as a regular user account - works fine - i.e. the ISO is shown in the Featured section of the VM deployment form (also when listing ISOs in UI as a regular user account, and choosing Featured)

IMO, this is not a bug, but a design behaviour.

**Comment by DaanHoogland** [comment]
@vladimirpetrov can you reconsider and close if it ^^ makes sense?

**Comment by vladimirpetrov** [comment]
Agree with Andrija here, closing the issue.
