### ISSUE TITLE
Unnecessarily VM power status check when resizing ROOT disk volume

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#4552]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
API
Management
Volume
~~~

##### CLOUDSTACK VERSION

~~~
4.14
4.15
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

VMware 6.5
CloudStack 4.14

##### SUMMARY

When trying to resize ROOT volume of a VM in VMware, CloudStack checks for VM status and force user to power it off before ROOT disk resize.
But I can expand ROOT disk without need to power off the VM from vSphere 6.5 UI.
It seems this constrain is not necessary.

The line of code which causes this result:
https://github.com/apache/cloudstack/blob/58a0a7b1a3408240757279a95543ce6304cd2a62/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L1095

##### STEPS TO REPRODUCE

~~~
Create a new VM
Check VM is powered on
Resize ROOT disk
~~~

##### EXPECTED RESULTS

~~~
ROOT disk resize successfully.
~~~

##### ACTUAL RESULTS

~~~
Error message that ask to power off the VM before resize.
~~~

**Comment by nvazquez** [comment]
@aleskxyz PR #5186 seems to fix this issue

**Comment by nvazquez** [comment]
Closing as PR is merged
