### ISSUE TITLE
Upgrade from 4.14 to 4.15 and new UI does not load

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#4578]
Upgrade from 4.14 to 4.15 and new UI does not load
I have this screen with the message

![image](https://user-images.githubusercontent.com/25532758/104233585-cb53f900-545a-11eb-888a-fa1bda89dfe6.png)

**Comment by rhtyd** [comment]
Thanks for reporting @AlexanderKgr can you share which repository you used?

**Comment by rhtyd** [comment]
(it could be failure to bundle the primate UI archive build)

**Comment by AlexanderKgr** [comment]
> Thanks for reporting @AlexanderKgr can you share which repository you used?

thanks for answering
i used this repository

deb http://download.cloudstack.org/ubuntu bionic 4.15

**Comment by rhtyd** [comment]
Can you use http://packages.shapeblue.com/cloudstack/upstream/debian/4.15/

@GabrielBrascher can you rebuild the mgmt server deb pkg by including a build of Primate under the ui directory of src? Ping me if you need any help or assistance.

**Comment by AlexanderKgr** [comment]
remove previous cloudstack management and tried to install the file from shapeblue and i have this error

![image](https://user-images.githubusercontent.com/25532758/104241215-fee85080-5465-11eb-8196-a83733eae45a.png)

**Comment by AlexanderKgr** [comment]
installed both 
cloudstack-common_4.15.0.0_all.deb
cloudstack-management_4.15.0.0_all.deb

and everything works. 
i suppose something is wrong with bionic repo. thanks for the help

**Comment by rhtyd** [comment]
@AlexanderKgr can you close the issue, I'll advise @GabrielBrascher steps to rebuild the ubuntu pkgs.

**Comment by efansoftware** [comment]
> Can you use http://packages.shapeblue.com/cloudstack/upstream/debian/4.15/
> 
> @GabrielBrascher can you rebuild the mgmt server deb pkg by including a build of Primate under the ui directory of src? Ping me if you need any help or assistance.

Same issue exists in packaging from source for CentOS7
[cd packaging; ./package.sh -d centos7]
After upgraded to 4.15 (from 4.13) by using these rpms, same first ui as Alexander posted screenshot.
The new UI does not load.

@rhtyd , could you please share the build steps to include the Primate? It will help much even it is draft. Thanks! [I searched through 4.15 documentation but did not get a clue]

**Comment by rhtyd** [comment]
@efansoftware yes, read the readme (install the dependencies first) and then see https://github.com/apache/cloudstack/tree/master/ui#production
