### ISSUE TITLE
Register template from URL does not work with HTTPS and SNI

### ISSUE THREAD

**Issue by olivierlemasle** [apache/cloudstack#4587]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
The http(s) client used by the SSVM to download templates does not support SNI (Server Name Indication).

Templates available on webservers using https and SNI (e.g. behind Cloudfront) cannot be downloaded.

##### STEPS TO REPRODUCE

Register template from URL, with e.g.:
- URL: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/33.20201214.3.1/x86_64/fedora-coreos-33.20201214.3.1-vmware.x86_64.ova (for OVA) or https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/33.20201214.3.1/x86_64/fedora-coreos-33.20201214.3.1-digitalocean.x86_64.qcow2.gz (for qcow2)
- direct download: false

##### EXPECTED RESULTS

Template is expected to be downloaded in the zone.

##### ACTUAL RESULTS

Template download fails in the zone, with message:
~~~
Received fatal alert: handshake_failure
~~~

##### Temporary fix

1. Log in the SSVM using SSH
2. Edit `/usr/local/cloud/systemvm/_run.sh` to replace `-Djsse.enableSNIExtension=false` by `-Djsse.enableSNIExtension=true`
3. Restart the SSVM

**Comment by DaanHoogland** [comment]
seems like a trivial change, I wonder if the `enableSNIExtension=false` was set on purpose.
cc @nvazquez (and maybe @sureshanaparti)?

**Comment by olivierlemasle** [comment]
> I wonder if the enableSNIExtension=false was set on purpose.

I wonder, too...

As I wrote in PR #4588, `enableSNIExtension=false` was added in commit 1d45b75298e; the commit message includes:

> Java 1.7 - disable using SNI since copyTemplate doesnt work for SSL.

**Comment by rhtyd** [comment]
Ping @olivierlemasle are you working on the PR #4588 ?

**Comment by nvazquez** [comment]
Hi @olivierlemasle is there any work after PR #4588 is closed to address this issue?

**Comment by rhtyd** [comment]
Ping @olivierlemasle - any update on this? Should we close this, or attempt to introduce a global setting on top of your previous PR to toggle behaviour?

**Comment by sureshanaparti** [comment]
ping @olivierlemasle any update on this issue (any work done after PR #4588)?

**Comment by nvazquez** [comment]
Ping @olivierlemasle

**Comment by rohityadavcloud** [comment]
Ping @olivierlemasle can you test this with latest 4.17.0.0?
