### ISSUE TITLE
Cannot create virtual router when restarting network

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#4589]
Trying to restart network and vr is deleted after 4.15 installation.
System cannot recreate vr 

![image](https://user-images.githubusercontent.com/25532758/104810612-7ae3ef00-57fe-11eb-8ee8-21d1e236da1f.png)

and the logs

![image](https://user-images.githubusercontent.com/25532758/104811128-19be1a80-5802-11eb-82e5-893145ba94c5.png)

any help will be highly appreciated

**Comment by sledzikowy** [comment]
Hi, I'm having same issue here. I guess that's configuration problem, how did you solve it?
