### ISSUE TITLE
The network documentation contains dangling hyperlinks.

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#4594]
##### ISSUE TYPE
 * Documentation Report

##### COMPONENT NAME
~~~
Documentation
~~~

##### CLOUDSTACK VERSION
~~~
4.15, 4.14, 4.13.x, 4.12, 4.11.x
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The missing file network2.html is linked from the documentation where subject pages should be pointed to.

##### STEPS TO REPRODUCE

The documentation sections about “Configure Guest Traffic in an Advanced Zone”, “Configuring a Shared Guest Network”, “Persistent Networks”, “About Virtual Private Clouds”, “DNS and DHCP”, “Remote Access VPN”, “Configuring Network Access Control List”, “Adding a Security Group” and “About Elastic IP” are missing.

Go to the following page and try ro reach some of the sections from above:
[http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking.html#isolated-networks](http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking.html#isolated-networks)

##### EXPECTED RESULTS
~~~
All documentation links must be working.
~~~

##### ACTUAL RESULTS
The "not found" page is shown instead:
![image](https://user-images.githubusercontent.com/12384665/104938049-32bbfc80-59b7-11eb-8fd4-391bb4924272.png)

**Comment by DaanHoogland** [comment]
@vladimirpetrov http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking/elastic_ips.html is there, but I got there through a search, maybe the page is orphaned? What path would you expect to lead there?

**Comment by vladimirpetrov** [comment]
@DaanHoogland I tried to reach it through the aforementioned page:

![image](https://user-images.githubusercontent.com/12384665/105018966-41092780-5a4e-11eb-876e-533987b6a94f.png)

and the link is broken:
[http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking2.html#about-elastic-ip](http://docs.cloudstack.apache.org/en/4.15.0.0/adminguide/networking2.html#about-elastic-ip)

**Comment by DaanHoogland** [comment]
ok, so that link is broken, `networking2.html#about-elastic-ip` should be `networking/elastic-ips.html`. I'm changing the titel of this issue.

**Comment by vladimirpetrov** [comment]
What about other links? Are they on a different place or just missing?

**Comment by DaanHoogland** [comment]
Need to look, i *think* there is a file per feature, @vladimirpetrov

**Comment by shwstppr** [comment]
@vladimirpetrov Opened this PR https://github.com/apache/cloudstack-documentation/pull/184, can you please have a look

**Comment by DaanHoogland** [comment]
@shwstppr I see uyou don't use `networking/elastic-ips.html` is there a double implementation somehow? i think that should be clean up, then.

**Comment by rhtyd** [comment]
Closing based on https://github.com/apache/cloudstack-documentation/pull/184 @vladimirpetrov pl check, re-open if you see something we've missed.

**Comment by vladimirpetrov** [comment]
The last link - "'About Elastic IP” on the page:

[https://acs-www.shapeblue.com/docs/WIP-PROOFING/pr184//adminguide/networking.html#isolated-networks](https://acs-www.shapeblue.com/docs/WIP-PROOFING/pr184//adminguide/networking.html#isolated-networks)

![image](https://user-images.githubusercontent.com/12384665/106921704-edb4fb80-6714-11eb-93e5-4e25088485a1.png)

is still broken, it links to the following url:

[https://acs-www.shapeblue.com/docs/WIP-PROOFING/pr184//adminguide/advanced_zone_config.html#about-elastic-ip](https://acs-www.shapeblue.com/docs/WIP-PROOFING/pr184//adminguide/advanced_zone_config.html#about-elastic-ip)

which is unavailable:

![image](https://user-images.githubusercontent.com/12384665/106921915-2654d500-6715-11eb-93da-2522c31d0487.png)

**Comment by shwstppr** [comment]
@vladimirpetrov please test https://github.com/apache/cloudstack-documentation/pull/185

**Comment by vladimirpetrov** [comment]
@shwstppr Reviewed - LGTM now!

**Comment by shwstppr** [comment]
Closing based on ^^, fixed with https://github.com/apache/cloudstack-documentation/pull/185
