### ISSUE TITLE
uuids instead of display names are shown in detail view of VM snapshot

### ISSUE THREAD

**Issue by mib1185** [apache/cloudstack#4603]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Primate UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### SUMMARY

On details view of an VM snapshot uuids instead of display names for "VM name" and "Zone" are shown

##### STEPS TO REPRODUCE

- create VM snapshot
- open detail view for created snapshot

##### EXPECTED RESULTS

real displayname for "VM name" and "Zone" is shown

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/35783820/105168065-de7d5d80-5b19-11eb-9023-cf4f0daf67e3.png)

**Comment by shwstppr** [comment]
@mib1185 listVmSnapshot API was not havin name parameters, I've created a PR to add them

**Comment by shwstppr** [comment]
Closed with #4604 
@mib1185 please re-open if the issue still persists
