### ISSUE TITLE
List of templates - 500 server error

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#4606]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15
~~~

##### SUMMARY
Until yesterday was working perfectly

##### STEPS TO REPRODUCE
~~~
Select images - Templates and i have the issue
~~~

##### EXPECTED RESULTS
~~~
Until yesterday it was displaying templates
~~~

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/25532758/105349249-1b1c8800-5bf2-11eb-914f-626771a6f25a.png)

And the logs from cloudstack server
![image](https://user-images.githubusercontent.com/25532758/105349332-38515680-5bf2-11eb-88fd-9281c8932de2.png)

![image](https://user-images.githubusercontent.com/25532758/105349361-44d5af00-5bf2-11eb-9699-8cb6aa041a05.png)

**Comment by DaanHoogland** [comment]
@AlexanderKgr these images are not very helpful. Can you add the text version?

You say it stopped working, was this after an upgrade or with the same version?

**Comment by shwstppr** [comment]
@AlexanderKgr have you removed any secondary store?

**Comment by rhtyd** [comment]
NPE possibly due to null value returned at https://github.com/apache/cloudstack/blob/4.15/server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java#L164
cc @nvazquez @harikrishna-patnala - does this seems like vsphere/deploy-as-is changes?

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr these images are not very helpful. Can you add the text version?
> 
> You say it stopped working, was this after an upgrade or with the same version?

it was working perfectly for 3-4 days without any issue

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr have you removed any secondary store?

no nothing

**Comment by DaanHoogland** [comment]
> > @AlexanderKgr these images are not very helpful. Can you add the text version?
> > You say it stopped working, was this after an upgrade or with the same version?
> 
> it was working perfectly for 3-4 days without any issue

so no upgrade, same install, same templates?

**Comment by AlexanderKgr** [comment]
> > > @AlexanderKgr these images are not very helpful. Can you add the text version?
> > > You say it stopped working, was this after an upgrade or with the same version?
> > 
> > 
> > it was working perfectly for 3-4 days without any issue
> 
> so no upgrade, same install, same templates?

Updated to 4.15 before 3 - 4 days. Hadn't any issue those days. But today this 500 error

**Comment by weizhouapache** [comment]
> > > > @AlexanderKgr these images are not very helpful. Can you add the text version?
> > > > You say it stopped working, was this after an upgrade or with the same version?
> > > 
> > > 
> > > it was working perfectly for 3-4 days without any issue
> > 
> > 
> > so no upgrade, same install, same templates?
> 
> Updated to 4.15 before 3 - 4 days. Hadn't any issue those days. But today this 500 error.
> Of course there have been changes concerning templates. But no change concerning secondary storage and hosts. Anything that can help me fix this issue?

@AlexanderKgr 
could you please share the tables below ?
(1) vm_template 
(2) template_store_ref
(3) image_store

**Comment by harikrishna-patnala** [comment]
> NPE possibly due to null value returned at https://github.com/apache/cloudstack/blob/4.15/server/src/main/java/com/cloud/api/query/dao/TemplateJoinDaoImpl.java#L164
> cc @nvazquez @harikrishna-patnala - does this seems like vsphere/deploy-as-is changes?

Not related to those changes @rhtyd . We can investigate based on the tables requested by @weizhouapache

**Comment by AlexanderKgr** [comment]
> > > > > @AlexanderKgr these images are not very helpful. Can you add the text version?
> > > > > You say it stopped working, was this after an upgrade or with the same version?
> > > > 
> > > > 
> > > > it was working perfectly for 3-4 days without any issue
> > > 
> > > 
> > > so no upgrade, same install, same templates?
> > 
> > 
> > Updated to 4.15 before 3 - 4 days. Hadn't any issue those days. But today this 500 error.
> > Of course there have been changes concerning templates. But no change concerning secondary storage and hosts. Anything that can help me fix this issue?
> 
> @AlexanderKgr
> could you please share the tables below ?
> (1) vm_template
> (2) template_store_ref
> (3) image_store

sorry for the delay
the tables

[tables.zip](https://github.com/apache/cloudstack/files/5853916/tables.zip)

thanks for helping

**Comment by Pearl1594** [comment]
@AlexanderKgr going over the tables shared, it seems like there are some active templates on stores with id's 15 and 16 but these stores have been deleted. Ideally, if there are active templates on a store, removal of the image stores will be prevented. It's because of the presence of these templates that the API fails

**Comment by harikrishna-patnala** [comment]
yes I checked the same what @Pearl1594 mentioned. 
@AlexanderKgr please check if you have removed those secondary storages manually by some DB changes. If the secondary storage still available revert the DB changes or mark the active templates on those secondary storages as removed. Hope this will fix the your problem

**Comment by weizhouapache** [comment]
> yes I checked the same what @Pearl1594 mentioned.
> @AlexanderKgr please check if you have removed those secondary storages manually by some DB changes. If the secondary storage still available revert the DB changes or mark the active templates on those secondary storages as removed. Hope this will fix the your problem

@harikrishna-patnala agrees. it seems @AlexanderKgr removed db entries manually.
it is not a bug.

**Comment by AlexanderKgr** [comment]
ok found the issue and fixed it. thank you very much. 
tried migrating these secondary storages and something might happen with the migration
by the way...is there anywhere a description of the tables or a diagram of the db?
