### ISSUE TITLE
[UI] Cannot remove tags on host and primary storage

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#4610]
If there is only one tag for host/primary storage it's not possible to remove it. The workaround is to replace the tag with a comma ",". In the old UI, this functionality works correctly

API call from old UI is:

> /client/api?command=updateStoragePool&id=c9b09777-7340-3752-8a96-f3835f9f5c53&tags=&capacitybytes=273804165120&name=test2&response=json&_=1611312734947

API call from new UI the tag value with an empty string was not get:

> /client/api/?id=c9b09777-7340-3752-8a96-f3835f9f5c53&name=test2&command=updateStoragePool&response=json 

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### EXPECTED RESULTS

~~~
The tag should be removed
~~~

##### ACTUAL RESULTS

~~~
The tag is still set on host/primary storage
~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4611, can you test latest 4.15 and close @slavkap

**Comment by slavkap** [comment]
thanks, @rhtyd, it works correctly
