### ISSUE TITLE
Cannot remove Secondary storage after using new feature "migration of secondary storage"

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#4613]
##### ISSUE TYPE
 * Bug Report
##### COMPONENT NAME

API

##### CLOUDSTACK VERSION
~~~
4.15
~~~

##### SUMMARY

After migration finishes cannot delete secondary storage

##### STEPS TO REPRODUCE

1. Migrate data from image store choosing complete migration policy
![image](https://user-images.githubusercontent.com/25532758/105623414-3d94e800-5e22-11eb-9577-fbddf576bddb.png)

After a couple of minutes

![image](https://user-images.githubusercontent.com/25532758/105623477-aaa87d80-5e22-11eb-8536-1a8c98dfcb99.png)

2. After i tried to delete secondary storage and i have the following message
![image](https://user-images.githubusercontent.com/25532758/105623497-cf9cf080-5e22-11eb-9a75-36df3e988454.png)

##### EXPECTED RESULTS

~~~
After running migration successfully i thought that i could delete the secondary storage without problem.
The same procedure for primary storage works perfectly so i thought it would be the same.
There is no info for deleting secondary storage at documentation

~~~

##### ACTUAL RESULTS
~~~
Cannot delete secondary storage after migration
~~~

**Comment by DaanHoogland** [comment]
@AlexanderKgr are there system templates still on that secstor?

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr are there system templates still on that secstor?

yes there are system templates because there are other image stores - secondary storages. 
Also there is the secondary storage that i migrated from this that i want to delete

**Comment by DaanHoogland** [comment]
@AlexanderKgr can you test @Pearl1594 's fix in #4615? it is allowing for deleting a secstor if no private templates are on it, ignoring public (builtin) templates.

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr can you test @Pearl1594 's fix in #4615? it is allowing for deleting a secstor if no private templates are on it, ignoring public (builtin) templates.

will check and report

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr can you test @Pearl1594 's fix in #4615? it is allowing for deleting a secstor if no private templates are on it, ignoring public (builtin) templates.

i am quite new to debug of cloudstack. can you help how to implement the fix? searching for the 2 files that have been changed but i cannot find them

**Comment by DaanHoogland** [comment]
@AlexanderKgr You'll need to build the PR version and upgrade a test environment to that version to be able to test it.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4615

**Comment by AlexanderKgr** [comment]
@rohityadavcloud @Pearl1594 
tried to delete secondary storage at 4.18.0 and faced the same issue.

Migrated all data - complete migrate.
 and then

![image](https://github.com/apache/cloudstack/assets/25532758/2ccb4081-5e3d-4b8e-a969-f3bd14b79b78)


should i report it again?

**Comment by Pearl1594** [comment]
@AlexanderKgr Would it be possible for you to confirm if there are any private templates still present on the secondary storage from where resources were migrated.Also, on re-attempting migration, do you see any errors reported. It could so happen that when attempting to migrate the resource(s) it encountered some failure. These left over templates/snaps/volumes would prevent deletion of the secondary storage

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr Would it be possible for you to confirm if there are any private templates still present on the secondary storage from where resources were migrated.Also, on re-attempting migration, do you see any errors reported. It could so happen that when attempting to migrate the resource(s) it encountered some failure. These left over templates/snaps/volumes would prevent deletion of the secondary storage

when doing a complete migration of a secondary storage as admin, why  should I check for private templates? complete migration should migrate everything. I wanted to delete the 2nd secondary storage because there have been an issue with the array of disks and i couldn't. I have deleted the entry of secondary storage from the database. 
I think that, when the admin decides to do a complete migration it should migrate everything. Volumes templates etc... I haven't any errors from the migrations. And after the migration it should be possible to remove the secondary storage.

**Comment by Jayd603** [comment]
I just did a new cloudstack install, set up first zone, I accidentally used the wrong secondary storage path, the set-up process gave no errors.   Now, after creating new and correct secondary storage, I cannot migrate and cannot delete the old one.   Zone set-up script should test connection and write ability of the secondary storage I'm thinking.
