### ISSUE TITLE
Problem on selecting "Tier" dropdown and pagination error in "Port forward" UI

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#4632]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Problem 1: empty VPC network list
Problem 2: pagination request error.
 
##### STEPS TO REPRODUCE

~~~
1. Under Project View
2. Create a VPC network with "Default VPC offering"
3. Navigate into the newly created VPC->network
4. Add two Network with DefaultIsolatedNetworkOfferingForVpcNeworksWithInternalLB setting
5. Add a new Public IP address
6. Click on the newly assigned IP address, move to Port Forwarding, it shown "Request Failed"
7. Enter port 80 and click Add VM
8. Add VM screen popup, network tier drop down shown empty, click on page 2, show "Request Failed"
~~~
![requesterror](https://user-images.githubusercontent.com/36956864/106349183-e5208780-6306-11eb-9f67-4f0d62398ac9.png)

![portforward](https://user-images.githubusercontent.com/36956864/106349179-e2259700-6306-11eb-84d1-5d6bdbf19f7c.png)

##### EXPECTED RESULTS

~~~
- Network list out properly
- No error shown during navigation.
~~~

##### ACTUAL RESULTS

~~~
See screen capture.
~~~

**Comment by DaanHoogland** [comment]
@levindecaro did you look in the logs to see what happened?
Did you allow time for the creation of the networks in the VPC virtual router?

If there are any ERRORs in the log of exception traces, can you share these please?

**Comment by utchoang** [comment]
@DaanHoogland @rhtyd @shwstppr According to the old UI, if the VPC network does not have Internal LB, is the PortForwarding tab displayed? As you can see, if the VPC network does not have an Internal LB then when adding the VM in PortForwading the tab list tier will be empty.

**Comment by utchoang** [comment]
According to the old UI, if the VPC network does not contain the `DefaultIsolatedNetworkOfferingForVpcNetworks` and the `DefaultIsolatedNetworkOfferingForVpcNetworksNoLB` settings, is the PortForwading tab displayed? As I see the Tier list it will be empty.
![image](https://user-images.githubusercontent.com/13766648/109762746-afcbca00-7c23-11eb-8dee-8edcfc87e42b.png)
![image](https://user-images.githubusercontent.com/13766648/109762834-d427a680-7c23-11eb-9530-4f4b16fbd0d0.png)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4746
