### ISSUE TITLE
VM's name and display name in UI

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#4654]
In new UI, for the VM detail view shows VM's display name while VM's name is shown in the list view. It is fine when VM is deployed from the UI itself but name and display name can have different values when deployed from cmk.

Old UI used to show `name` of the VM in the list view and there was no info tab in detail view,
![Screenshot from 2021-02-05 11-31-12](https://user-images.githubusercontent.com/153340/106996466-11c11d00-67a7-11eb-84bb-0734d83df386.png)
![Screenshot from 2021-02-05 11-31-26](https://user-images.githubusercontent.com/153340/106996481-15ed3a80-67a7-11eb-9352-6b236bf533bc.png)

New UI
![Screenshot from 2021-02-05 11-40-24](https://user-images.githubusercontent.com/153340/106996490-1be31b80-67a7-11eb-9cda-4de4c02ec7ba.png)
![Screenshot from 2021-02-05 11-40-43](https://user-images.githubusercontent.com/153340/106996526-2d2c2800-67a7-11eb-8690-8cf809d7f684.png)

Few queries here,
- Is this behaviour okay from the user perspective?
- Should UI display VM's `displayname` in the list view?
- Should new UI show VM's `name` in the info tab in detail view?

##### ISSUE TYPE

 * Other

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15.0
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
~~~
Deploy a VM using cmk while providing different name and displayname value
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@harikrishna-patnala @vladimirpetrov @PaulAngus @weizhouapache @ravening @rhtyd @davidjumani @andrijapanicsb opinion on this?

**Comment by harikrishna-patnala** [comment]
@shwstppr In my opinion list view should show "Display Name" of the VM because the displayname itself is meant for that.
so I would like to see display name instead of name. Details tab anyways shows both Display Name and Name

**Comment by vladimirpetrov** [comment]
I agree with @harikrishna-patnala!

**Comment by PaulAngus** [comment]
I think that the `display name` is the most obvious thing to show as Hari and Vladi say. 

Our problem is that its a UI bug not to show both when creating an instance* so everyone knows what was going on, then the documentation mistakes might not have happened.

_Someone_ will probably get upset if we change it, even though it makes much more sense.

* @shwstppr - We should update the Add Instance wizard in the UI to show both 'name' and 'display name'.

+ While we're at it...  Who, _ever_, sets the name of something that they're creating at the END!  (how on earth is the name of the instance just a 'detail').   Can we move the 'name' and 'display name' input fields to the start?

**Comment by davidjumani** [comment]
@shwstppr I don't have any preferences but can tweak the UI to show both the name and display name on the info card so everyone is happy

**Comment by rhtyd** [comment]
+1

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4787 for 4.15

**Comment by suppersam** [comment]
Was this disabled in CloudStack 4.18.1.0? Or how can i enable it?

**Comment by DaanHoogland** [comment]
both name and display names are shown in details. In the list view only the name shows @suppersam : 
![image](https://github.com/apache/cloudstack/assets/2486961/0477cacc-9784-4e63-896a-32e5d6f60be7)

![image](https://github.com/apache/cloudstack/assets/2486961/448e8e9e-ab6a-4acf-a3b9-6010acd216f3)

you can submit a new [issue](https://github.com/apache/cloudstack/issues/new) if you feel that should be changed.

**Comment by DaanHoogland** [comment]
btw @suppersam it was explicitely removed in https://github.com/apache/cloudstack/pull/7833/files#diff-93b52572e13887859e26011826bd9744351c29e7a0de514ea308d503113a13e3L49 which might have been by accident. (cc @rohityadavcloud ?)

**Comment by rohityadavcloud** [comment]
@DaanHoogland in most cases display and name are the same, having two redundant columns - so one of the two were removed as part of polish idea: `Standardise most resources to show state/status columns right after resource name (wherever applicable)` and `Remove displayname column in VM list view, add cpu number and memory by default`
