### ISSUE TITLE
Question: How to Import existing VM to Cloudstack Managed instance? 

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#4658]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI or API
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

XCP-NG 8.0, Cloudstack 4.15

##### OS / ENVIRONMENT

N/A

##### SUMMARY

QUESTION: 
How do I Import an Existing VM (which runs in same cluster that cloudstack manages) but not currently managed by Cloudstack - into Cloudstack managed instance? 

I have several VMs that existed in our Xen/XCP environment, prior to CLoudstack installation. I would like to bring those into Cloudstack for ease of management. 

One way I have found is copy the vhd file for the current VM and upload it to cloudstack as a Template, and then create a VM using that template. But that seems a bit not right way to do things. 

Is there a better way/best practices way to do this? 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@nxsbi this is currently only implemented on vmware. Your workaraound (to create a template from the external VM, register it as a template and deploy from there) is the only way at the moment as far as i know.

**Comment by DaanHoogland** [comment]
@nxsbi do you want to turn this into a feature request? and do you want to be involved in the work around it?

**Comment by nxsbi** [comment]
> @nxsbi do you want to turn this into a feature request? and do you want to be involved in the work around it?

I am not a developer, so I cannot help with coding, but I can definitely help with testing if that helps. 
It would be a nice feature to have incase someone who is currently on XCP/Xen wants to move to managed Cloudstack instance. 

How can I help?

**Comment by DaanHoogland** [comment]
> I am not a developer, so I cannot help with coding, but I can definitely help with testing if that helps.

...

> How can I help?

Testing will help in the end, and how about making a more extensive functional description? investigate the vmware version [design](https://cwiki.apache.org/confluence/display/CLOUDSTACK/VM+Ingestion) or [documents](http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines/unmanage_vms.html) of this functionality and describe how this is the same and where it differs. You can do this in a ticket here or on the [wiki](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Design)

tnx

**Comment by rohityadavcloud** [comment]
@nxsbi we've the new ingestion feature you can try for VMware;
https://www.shapeblue.com/new-feature-first-look-vm-ingestion/
https://www.youtube.com/watch?v=EfAXyAF1wwM

Further there's the unmanage instance feature:
https://www.shapeblue.com/cloudstack-feature-first-look-enable-unmanaging-of-guest-instances/

For other hypervisors, the only way is to do a cold import, shortly - shutdown the VM, import the VM disk(s) as template and deploy VMs using that.

Thanks for the issue. Since this is largely a question I'm closing this.

**Comment by alsko-icom** [comment]
Hey everyone. Is there a change in this feature of existing XCP hosted VMs since last post in 2022?
