### ISSUE TITLE
Unable to create shared networks in master

### ISSUE THREAD

**Issue by ravening** [apache/cloudstack#4664]
I am unable to create shared networks in the latest master branch

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Networks
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0
~~~

##### STEPS TO REPRODUCE

~~~
Login to UI
Navigate to Networks and click on Create network
Select type as shared. Fill in the details and click on
~~~

##### EXPECTED RESULTS

~~~
Shared network should be created
~~~

##### ACTUAL RESULTS

~~~
The network didnt get created. I dont see any api call being made to backend
I see some warn in the console but Im not sure if thats related.

~~~
![Screenshot 2021-02-08 at 13 58 41](https://user-images.githubusercontent.com/10645273/107223126-18090080-6a16-11eb-98b0-5efde73b825d.png)

![Screenshot 2021-02-08 at 14 01 21](https://user-images.githubusercontent.com/10645273/107223176-26571c80-6a16-11eb-9882-74eba635f8dc.png)

I am able to create it sometimes but most of the time, its just stuck.

@ustcweizhou you were also facing this issue right?

@rhtyd @DaanHoogland @shwstppr

**Comment by weizhouapache** [comment]
@ravening yes, I confirmed it.
it does not work most of times.

**Comment by ravening** [comment]
after some debugging, found out that `this.formSelectedPhysicalNetwork` was null and NPE happens there. Hence the code flow wont go further

**Comment by weizhouapache** [comment]
> after some debugging, found out that `this.formSelectedPhysicalNetwork` was null and NPE happens there. Hence the code flow wont go further

@ravening good. should it be a required field ?

**Comment by ravening** [comment]
No.. for some reason this field is null. we just need to call the api to fetch the data again if its null. i have made the change and it works fine. will create a pr

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4666
