### ISSUE TITLE
removing a linking ldap account leaves an ldap-trustmap

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#4673]
This is an issue bacause remove account does not interact with the ldap plugin. when creating a linked account this trustmap is created en when linking against the same ldap group again it is deleted and re-created. But when creating a lot of new test groups these remain in place as they are never re-used.
 
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
LDAP
Authentication
~~~

##### CLOUDSTACK VERSION

~~~
4.14
4.15
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
@DaanHoogland changing milestone to 4.15.1 as the PR is here for the bugfix

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4899
