### ISSUE TITLE
Question: Nested Virtualization 

### ISSUE THREAD

**Issue by ThyLAW** [apache/cloudstack#4677]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

4.15
~~~
4.15
~~~

##### CONFIGURATION

Followed the quick installation guide
##### OS / ENVIRONMENT

CentOS 7.9, installed as VM on hyper-v Windows Server 2016. Followed the quick installation guide on the documentation

##### SUMMARY

I created this ApacheCS installation on a virtual machine. I have it working and other hosts can connect to it. I realize now that ApacheCS instances virtual machines which would, in my case, cause nested virtualization of hosts. I have read that this does not work. Is ApacheCS able to work in this environment? I have not been able to find a real answer anywhere online, so I apologize for asking. I am not a Systems Administrator, only a student doing this as a project for my class.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@ThyLAW if you use a virtual machine as cloudstack kvm host, nested virtualization must be enabled.
however, it seems not supported by hyperv.
https://docs.microsoft.com/en-us/system-center/vmm/vm-nested-virtualization?view=sc-vmm-2019
