### ISSUE TITLE
[UI] while creating any system offering, API always called with System VM Type as domain router

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#4682]
While creating any system offering of type SSVM or CPVM or domain router from UI, the underlying API called is always with 
"systemvmtype" as domainrotuer.
Following is the screenshot of system offering creation with System VM type "Secondary Storage VM"
![image](https://user-images.githubusercontent.com/3348673/107620510-ce6d1f80-6c7a-11eb-903d-6bfeaf1deda8.png)

Here is the system offering created with type domainrouter.
![image](https://user-images.githubusercontent.com/3348673/107620639-070cf900-6c7b-11eb-953c-86b316e10a40.png)

API captured for this operation.
{"createserviceofferingresponse":{"serviceoffering":{"id":"b761ad41-1b66-4475-b261-38ab3c697f47","name":"testSSVMoffering","displaytext":"testSSVMoffering","cpunumber":1,"cpuspeed":1000,"memory":1024,"created":"2021-02-11T09:37:50+0000","storagetype":"shared","provisioningtype":"thin","offerha":false,"limitcpuuse":false,"isvolatile":false,"issystem":true,"defaultuse":false,"systemvmtype":"domainrouter","iscustomizediops":false,"miniops":0,"maxiops":0,"iscustomized":false,"cacheMode":"none","rootdisksize":0,"dynamicscalingenabled":true}}}

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
4.15 or master

##### EXPECTED RESULTS
Creating System offering from UI should create with provided system vm type

##### ACTUAL RESULTS
Creating System offering from UI always creates with domainrouter type irrespective of provided type

**Comment by shwstppr** [comment]
@harikrishna-patnala please check if PR #4683 fixes the problem
