### ISSUE TITLE
When on Zone level storage, Cluster level pool are not being offered to a volume with find suitable pools api

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4692]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.15 
~~~

##### SUMMARY

When a volume is sitting on Zone level, it’s not being offered pools to migrate to with find storagepoolsformigration api.

##### STEPS TO REPRODUCE

~~~
1. Get a volume on zone level storage pool
2. Execute find storage pools api
3. Observe cluster level storage pools are not offered
~~~

##### EXPECTED RESULTS

~~~
Cluster level pools a eligible for migration and should be part of the response
~~~

##### ACTUAL RESULTS

~~~
Only zone level pools are there
~~~

**Comment by shwstppr** [comment]
Looking into this
