### ISSUE TITLE
GSoC 2021 Idea: Add virt-v2v support in CloudStack for VM import to KVM

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#4696]
## Background

There are many existing users who have deployed their infrastructure on XenServer or VMware but the migration to an IaaS platform such as CloudStack requires a lot of work.

Such a feature will allow the Apache CloudStack project to onboard and facilitate users who have an existing VM based infra on VMware/XenServer by using tools such as virt-v2v which can help automate shutdown (cold) VMs to KVM/CloudStack.

## Proposed Tasks

- Get started on basic CloudStack codebase and development (building and running CloudStack)
- Setup KVM based CloudStack dev/test environment
- Setup a test environment (XenServer and/or VMware) with test VMs
- R&D - virt-v2v tool and usage; define the overall workflow (steps) for import/migration
- Re-define scope/requirements of this feature (KVM distro, libvirt version; support source hypervisor versions XenServer/VMware)
- Integrate API that in-turn uses virt-v2v
- Deliverables: documentation and community pull request, end-to-end demo of feature

### Relevant Skills
- Java and Python
- Basic libvirt domain knowledge and usage
- virt-v2v

## Proposed Mentor

Rohit Yadav (rohit (at) apache.org), PMC/commiter Apache CloudStack

## Difficulty

Major

## Potential Mentors

Rohit Yadav (rohit (at) apache.org), PMC/commiter Apache CloudStack

### Example and references
https://libguestfs.org/virt-v2v.1.html
https://github.com/libguestfs/virt-v2v
https://www.ovirt.org/develop/release-management/features/virt/virt-v2v-integration.html
https://blogs.oracle.com/scoter/virt-v2v-automated-migration-from-oracle-vm-to-oracle-linux-kvm
https://access.redhat.com/articles/1351473

##### ISSUE TYPE

 * Feature Idea

**Comment by DaanHoogland** [comment]
@rhtyd this would be for milestone 4.17, right?

**Comment by rhtyd** [comment]
@DaanHoogland leave blank for now

**Comment by weizhouapache** [comment]
@rhtyd 
fyi, we used libguestfs/guestfish and rsync to convert openvz containers to kvm vm in the past.
https://www.youtube.com/watch?v=mmWs9H7dnNA
