### ISSUE TITLE
Guest IPs range not visible in UI

### ISSUE THREAD

**Issue by ccycv** [apache/cloudstack#4697]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### OS / ENVIRONMENT

~~~
N/A
~~~

##### SUMMARY

Guest IPs are not visible in UI 4.15, with no possibility to delete, add.

Select Zone> Physical Network > Guest  

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Add, Delete, View.
~~~

##### ACTUAL RESULTS

~~~
Not visible.
~~~

**Comment by DaanHoogland** [comment]
see [primate issue 909](https://github.com/apache/cloudstack-primate/issues/909)

**Comment by DaanHoogland** [comment]
@utchoang can you comment on this? (was it planned? Is there a reason for leaving it out? is it complex?)

**Comment by utchoang** [comment]
@DaanHoogland I see @davidjumani fixed it in PR but it seems to be frozen. I will use @davidjumani's fix and switch to Cloudstack.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4716
