### ISSUE TITLE
Cloudstack management asks for rpm command on debian distribution

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#4715]
- Fresh reinstall on 18.04.5 LTS (Bionic Beaver),
- Cloudstack 4.15
- Cloudstack repo : deb http://packages.shapeblue.com/cloudstack/upstream/debian/4.15 /
- My first initialization
- Step : Adding host
```
2021-02-20 00:39:23,074 DEBUG [c.c.u.s.SSHCmdHelper] (qtp182531396-13:ctx-85c1f557 ctx-cee8d01f) (logid:7b5f2cd9) Executing cmd: rpm -qa | grep -i ovmf
2021-02-20 00:39:24,138 DEBUG [c.c.u.s.SSHCmdHelper] (qtp182531396-13:ctx-85c1f557 ctx-cee8d01f) (logid:7b5f2cd9) SSH command: rpm -qa | grep -i ovmf
SSH command output:
bash: rpm: command not found
```

**Comment by rhtyd** [comment]
@abdelouahabb is your KVM host centos7 based?

**Comment by abdelouahabb** [comment]
> @abdelouahabb is your KVM host centos7 based?

@rhtyd no, this is Ubuntu 18.04.5 ontop of VirtualBox under Windows 7 (as the paravirtualization enabled)

**Comment by abdelouahabb** [comment]
```
abdelouahab@alien:~
$ sudo lshw -class system
alien.akham.local           
    description: Computer
    product: VirtualBox
    vendor: innotek GmbH
    version: 1.2
    serial: 0
    width: 64 bits
    capabilities: smbios-2.5 dmi-2.5 smp vsyscall32
    configuration: family=Virtual Machine uuid=E7584F9E-5753-2E49-9099-BA34C6073FA3
abdelouahab@alien:~
$ hostnamectl status
   Static hostname: alien.akham.local
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec31ec7e3e384682b6a396c151c030ac
           Boot ID: 4f3d9a5b14734ad7afcd55b2b456d2cc
    Virtualization: oracle
  Operating System: Ubuntu 18.04.5 LTS
            Kernel: Linux 4.15.0-135-generic
      Architecture: x86-64
```

**Comment by rhtyd** [comment]
@abdelouahabb what you report may look like an error but it isn't a failure [1], it checks if the KVM machine is UEFI enabled and looks like whoever added that didn't add a suitable support for Ubuntu. If host addition is failing due to keystore setup, chances are the host does not have kvm or hardware acceleration. I'm not sure if VirtualBox now supported nested VMs with hardware acceleration (vmx or svm supported). Easy way to check is to run `kvm-ok` or `ls /dev/kvm`. The other issue with keystore setup could be lack of entroy in the nested KVM (your Ubuntu VM on VirtualBox), which may be fixed by installed haveged (https://packages.ubuntu.com/bionic/haveged) and try to add host again.

[1] https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java#L262

**Comment by abdelouahabb** [comment]
> @abdelouahabb what you report may look like an error but it isn't a failure [1], it checks if the KVM machine is UEFI enabled and looks like whoever added that didn't add a suitable support for Ubuntu. If host addition is failing due to keystore setup, chances are the host does not have kvm or hardware acceleration. I'm not sure if VirtualBox now supported nested VMs with hardware acceleration (vmx or svm supported). Easy way to check is to run `kvm-ok` or `ls /dev/kvm`. The other issue with keystore setup could be lack of entroy in the nested KVM (your Ubuntu VM on VirtualBox), which may be fixed by installed haveged (https://packages.ubuntu.com/bionic/haveged) and try to add host again.
> 
> [1] https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/hypervisor/kvm/discoverer/LibvirtServerDiscoverer.java#L262

- For `haveged` isent useful if it will be added to the docs ? 
- For Virtualbox, on Windows the GUI dont give access to enable it, I have to use the commandline :+1: 
```
VBoxManage modifyvm CloudStack --nested-hw-virt on 
```
Where `CloudStack` is the name of the Virtual Machine, once enabled : 

```
$ ls -l /dev/kvm 
crw-rw---- 1 root kvm 10, 232 févr. 23 18:18 /dev/kvm
abdelouahab@alien:~
$ kvm-ok 
INFO: /dev/kvm exists
KVM acceleration can be used
abdelouahab@alien:~
$ lsmod | grep kvm
kvm_intel             217088  0
kvm                   614400  1 kvm_intel
irqbypass              16384  1 kvm
abdelouahab@alien:~
$ cat /proc/cpuinfo | grep -E 'vmx|svm'
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm pti tpr_shadow flexpriority
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm pti tpr_shadow flexpriority
```

**Comment by rhtyd** [comment]
@abdelouahabb `haveged` is not necessary generally unless you're using an unsupported deployment or slow servers (VirtualBox env are generally slow compared to real hardware) where you want entropy.

We've established that the rpm command not found is not an error, you can ignore that log and won't cause the host to be not added, do you actually get an exception in the logs (the debug level would be ERROR)?

**Comment by rhtyd** [comment]
Given the original issue doesn't cause the command failure (the log is debug, the exception/error is ignored by CloudStack). I'm closing this.
