### ISSUE TITLE
[UI] Need separate configurations for setting URL for general help and context sensitive help 

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#4720]
Currently CloudStack has "docBase" in config.json file where one can change the base URL for all sections. Changing the "docBase" to a new URL will effect all sections which may not be a convenient setting.  

For example, changing the "docBase" URL from "http://docs.cloudstack.apache.org/en/latest/" to "http://dochelp.custom.url/" this change effect the general help section here (below image) which is good
![image](https://user-images.githubusercontent.com/3348673/108704609-41577f80-7532-11eb-9839-7cd655a1883e.png)

But it also changes the base URL for other sections like context sensitive help (below image) for example on a specific virtual machine page the help URL is updated to "http://dochelp.custom.url//adminguide/virtualmachine.html"
![image](https://user-images.githubusercontent.com/3348673/108704813-87144800-7532-11eb-97a2-cff0d8284270.png)

It is good to have two different settings for URLs, one for general help and another for all context sensitive help sections.

Also if feasible, a single place like a json file where one can update the bookmarks/URLS to the general help and individual context sensitive help sections (eg: VM, template, snapshot, volume, etc.)

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME
UI
~~~

~~~

##### CLOUDSTACK VERSION
4.15

**Comment by rhtyd** [comment]
Replaced by - https://github.com/apache/cloudstack/issues/4731 (a mapping proposed)
