### ISSUE TITLE
listPublicIpAddresses API lists the (unallocated) reserved public IPs of other account, and resulting in UI to show other account's public IPs while acquire new IPs in the network

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#4723]
listPublicIpAddresses API lists the (unallocated ) reserved public IPs of other account (when allocatedonly=false and account is passed in the API), and it is resulting in UI to show other account's public IPs while acquire new IPs in the network.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Network
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0   4.15.0.0
~~~

##### SUMMARY

UI show the list of reserved public IPs of other account while acquire new IPs in the network

##### STEPS TO REPRODUCE

1) Create a zone with advanced network
2) Add two different public IP ranges in the Public Network and reserve them to two different accounts, say account01 and account02.
3) Login with account01, and create a network, say network01
4) Try to acquire new IP in the network01, which lists the reserved IPs for account02.
(or) Call listPublicIpAddresses API with account=account01 and allocatedonly=false.

~~~

~~~

##### EXPECTED RESULTS

~~~
The reserved public IPs of other account shouldn't be listed while acquiring new IP.
~~~

##### ACTUAL RESULTS

~~~
The reserved public IPs of other account are listed while acquiring new IP.
~~~

**Comment by DaanHoogland** [comment]
@sureshanaparti if the UI shows that the API must return those as well, which seems the real issue, did you check that?

**Comment by sureshanaparti** [comment]
> , did you check th

yes @DaanHoogland , API is ignoring account when listing unallocated IPs (allocatedonly=false)

**Comment by sureshanaparti** [comment]
> @sureshanaparti if the UI shows that the API must return those as well, which seems the real issue, did you check that?

yes @DaanHoogland , API is ignoring account when listing unallocated IPs (allocatedonly=false)

**Comment by weizhouapache** [comment]
@sureshanaparti this might be fixed by #4675

@ravening could you confirm ?

**Comment by ravening** [comment]
> @sureshanaparti this might be fixed by #4675
> 
> 
> 
> @ravening could you confirm ?

Yes that pr fixes the issue

**Comment by sureshanaparti** [comment]
thanks for the confirmation @ravening

**Comment by rhtyd** [comment]
@shwstppr can you test if PR #4675 fixes the issue for this bug?

**Comment by shwstppr** [comment]
tested `listpublicipaddresses` API and Acquire New IP UI with #4675. IPs assigned to different account were not listed.
And not able assign ip from another account.
```
(local) 🐱 > list publicipaddresses id=1404f2a2-1c30-49a5-8aea-6da8cfa3295e
{
  "count": 1,
  "publicipaddress": [
    {
      "fordisplay": true,
      "forvirtualnetwork": true,
      "id": "1404f2a2-1c30-49a5-8aea-6da8cfa3295e",
      "ipaddress": "192.168.5.5",
      "isportable": false,
      "issourcenat": false,
      "isstaticnat": false,
      "issystem": false,
      "networkid": "c8822cbc-1fd7-4a76-b6fd-04db5c103806",
      "physicalnetworkid": "2282fc1e-02f9-4b99-bc65-9c3c606b1b40",
      "state": "Free",
      "tags": [],
      "vlanid": "eac3ddb5-4635-445f-b727-8b4eed2ace08",
      "vlanname": "vlan://53",
      "zoneid": "6d560900-b905-4f31-af04-c2e3f947e9c6",
      "zonename": "Sandbox-simulator"
    }
  ]
}

(local) 🐱 > list networks id=b0a7048b-2dfc-4dbf-bd2e-cf5bbd4e7692 filter=id,name,account
{
  "count": 1,
  "network": [
    {
      "account": "account1",
      "id": "b0a7048b-2dfc-4dbf-bd2e-cf5bbd4e7692",
      "name": "iso"
    }
  ]
}

(local) 🐱 > associate ipaddress networkid=b0a7048b-2dfc-4dbf-bd2e-cf5bbd4e7692 ipaddress=192.168.5.5
🙈 Error: (HTTP 533, error code 9999) Insufficient address capacity

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4675
