### ISSUE TITLE
Check and fix all UI issue from the archived primate repository

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4726]
Triage and address open issues from https://github.com/apache/cloudstack-primate/issues
And ask authors to port their PRs (if not done already) https://github.com/apache/cloudstack-primate/pulls

##### ISSUE TYPE

 * Task

##### COMPONENT NAME

~~~
UI
~~~

**Comment by utchoang** [comment]
1. https://github.com/apache/cloudstack-primate/issues/158
   - [x] https://github.com/apache/cloudstack/pull/4762 - When opening a dialog, the first element should be active (with the cursor ready for typing). This avoids extra clicks.
   - [x] https://github.com/apache/cloudstack/pull/4763 - Some dialogs do not have 'Cancel' buttons - for example 'Assign Instance to Another Account'. The 'x' icon on the top right corner is always an option but I think we should be consistent here.

2. https://github.com/apache/cloudstack-primate/issues/462
   - [x] https://github.com/apache/cloudstack/pull/4764 - Create zone form is not aligned in mobile view
   - [x] https://github.com/apache/cloudstack/pull/4765 - Page size changer doesn't show up on mobile mode
   - [x] https://github.com/apache/cloudstack/pull/4766 - Enter to submit a form
   - [x] https://github.com/apache/cloudstack/pull/4769 - While listing domains, on full page reload, it goes back to the root domain
   - [x] https://github.com/apache/cloudstack/pull/4767 - Account in user info card doesn't directly go to account but to the account listview

3. https://github.com/apache/cloudstack-primate/issues/465 & https://github.com/apache/cloudstack-primate/issues/615
   - [x] https://github.com/apache/cloudstack/pull/4782 - Refactor async job polling codebase-wide and show multiple async jobs

4. https://github.com/apache/cloudstack-primate/issues/719
   - [x] https://github.com/apache/cloudstack/pull/4811 - Move fetch data to created()

5. https://github.com/apache/cloudstack-primate/issues/743
   - [x] https://github.com/apache/cloudstack/pull/4820 - Edit instance - offer existing Groups

**Comment by rhtyd** [comment]
Thanks for the update @utchoang

**Comment by rhtyd** [comment]
@utchoang are all the issues fixed/raised, can this ticket be closed?

**Comment by utchoang** [comment]
Currently, there is still the PR (https://github.com/apache/cloudstack-primate/pull/898) to consider. I will update it now.

**Comment by utchoang** [comment]
[x] https://github.com/apache/cloudstack/pull/4885 - Multiple Management Server support

**Comment by rhtyd** [comment]
@utchoang thanks, the PRs that introduce new features can be raised against master; PRs fixing any bug or introducing (minor) enhanacement can be considered for 4.15 branch. If all the PRs have been raised, can I close this issue?

**Comment by utchoang** [comment]
@rhtyd Yes, it is possible to close it
