### ISSUE TITLE
UI: allow users to override CSS via a single css file

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4732]
Investigate if it's possible to create a static css (single) file that can be used to override any/all CSS changes throughout the UI. Like the config.json, this can be loaded/applied after the UI loads. The firsts step is to investigate the feasibility and next to implement with a PR.

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

**Comment by rhtyd** [comment]
Hi @utchoang since you've worked on the config.json and several UI customisation support, can you help explore this? cc @svenvogel @shwstppr

**Comment by rhtyd** [comment]
@utchoang @svenvogel - can you comment if this is even feasible?

**Comment by utchoang** [comment]
@rhtyd Hi Rohit, In my opinion, it is not possible for a user to overwrite a CSS file from the `public` folder. As you can see, before in https://github.com/apache/cloudstack-primate/issues/359 to customizing UI (color, background, text,...), it was necessary to edit the object in `src/style/ var.less`. Then rely on variables from `config.json` to change color, text,...

**Comment by rhtyd** [comment]
Thanks @utchoang I'll close this then.
