### ISSUE TITLE
Bug: incorrect link to issue tracker

### ISSUE THREAD

**Issue by sebbASF** [apache/cloudstack#4752]
It's not that easy to find a link to the issue tracker, but there is one under:

Community | Get Involved 
which leads to
http://cloudstack.apache.org/contribute.html
which has the text:
"If you just want to report a bug, that's easily done in our Jira bug tracking tool."

However I am told that the project now uses GitHub issues instead.

The Developers page
http://cloudstack.apache.org/developers.html
also mentions JIRA as the main issue handling system

**Comment by rhtyd** [comment]
Thanks for the issue @sebbASF we need to rewrite the developers and contribute pages that are outdated. cc @apache/cloudstack-committers

**Comment by DaanHoogland** [comment]
created apache/cloudstack-www#79

**Comment by sebbASF** [comment]
AFAICT the web page has not been updated

**Comment by DaanHoogland** [comment]
@sebbASF did you clear cache? I can see the changes on https://cloudstack.apache.org/downloads.html

**Comment by DaanHoogland** [comment]
sorry, looking at the wrong issue, you are right, the download verification issues were updated but the jira link wasn't. I'll look into it.

**Comment by DaanHoogland** [comment]
created apache/cloudstack-www#80

**Comment by DaanHoogland** [comment]
@sebbASF , should be good now. I didn't expect there to be intermediate files in the git repo. not sure I understand the publication proces.

**Comment by sebbASF** [comment]
Thanks, looks good now
