### ISSUE TITLE
Bug in download page verification instructions

### ISSUE THREAD

**Issue by sebbASF** [apache/cloudstack#4753]
The download page
http://cloudstack.apache.org/downloads.html
has a verification section
This gives an example for gpg verify:
```% gpg --verify apache-cloudstack-X.X.X-src.tar.bz2.asc```

Whilst this works, it is not good practice.
When using gpg verify one should specify a second param, see:
https://www.apache.org/info/verification.html#specify_both

**Comment by rhtyd** [comment]
Unrelated to release milestone, I've removed 4.15.1.0. Website http://github.com/apache/cloudstack-www needs to be fixed.
