### ISSUE TITLE
Add a host using systemd / libvirt > 5.6 will stop libvirt and cloudstack-agent

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#4754]
##### ISSUE TYPE

 * Bug Report
  * Enhancement Request

##### COMPONENT NAME

~~~
Cloudstack Agent
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

Host to add: CentOS8

##### OS / ENVIRONMENT

CentOS8 / Hypervisor KVM / libvirt 6.0.0

##### SUMMARY
When adding a Host to a cluster, during the process a "configuration" of the libvirtd takes place. 

`management server log:
2021-03-05 01:38:37,166 DEBUG [c.c.u.s.SSHCmdHelper] (qtp2012330741-326:ctx-969e2771 ctx-a592cc3c) (logid:55839319) SSH command: cloudstack-setup-agent  -m 192.168.163.139 -z 5 -p 4 -c 4 -g 902eefa4-f4bc-3c75-8a1c-c57bc3798f18 -a -s  --pubNic=cloudbr0 --prvNic=cloudbr0 --guestNic=cloudbr0 --hypervisor=kvm
SSH command output:Starting to configure your system:
Configure SElinux ...         [OK]
Configure Network ...         [OK]
Configure Libvirt ...         [Failed]
Configuration failed for service Libvirt
Try to restore your system:
Restore SElinux ...           [OK]
Restore Network ...           [OK]
Restore Libvirt ...           [Failed]`

The problem is, that during this configuration the parameter `LIBVIRTD_ARGS=-l` is written into /etc/sysconfig/libvirtd.
At least for me, this breaks the whole set-up as the libvirtd will stop after relaoding.
Also therer are several other parameter, witch aren't needed when configuring libvirt usind systemd. These seem at least having not this effect on the libvirtd.

##### STEPS TO REPRODUCE
1. Configure a CentOS 8 machine according to the guides, besides the libvirt-configuration. Theseare configured accordingly to the official libvirt docs  [https://libvirt.org/daemons.html](url)
2. Add the CentOS8 Host to a cluster

##### EXPECTED RESULTS

Host would be added to the cluster.

##### ACTUAL RESULTS

Host wasn't added to the cluster; libvirtd won't come up anymore so the cloud-stack agent is also down as long as libvirtd is repaired.

**Comment by rhtyd** [comment]
Is CentOS8 libvirtd configuration different from Ubuntu 20.04's? cc @weizhouapache @shwstppr

**Comment by shwstppr** [comment]
@rhtyd yes, masking socket was not needed at the time for CentOS8 with libvirt version 4.5

**Comment by Hudratronium** [comment]
So just for my understanding (and further contribiution for the offical docs):
Basically the cloudstack-agent takes care of the libvirtd configuration during the "onboarding" to an cluster? (Taking a look into /python/lib/cloudutils/serviceConfig.py basically the whole config for the hostst seems to be there :-) )
Would be nice to know and quiet interesting to integrate it in to the install guides, as this speeds up things from a users point of view.

**Comment by shwstppr** [comment]
@Hudratronium yes, cloudstack-agent makes required changes to libvirt config when you add a host using UI/API. On the host cloudstack-agent is called with required parameters. Similar to,
`cloudstack-setup-agent  -m 10.10.3.203 -z 1 -p 1 -c 1 -g bd24ab4a-4311-357e-8e9e-dab829448772 -a -s  --pubNic=cloudbr1 --prvNic=cloudbr0 --guestNic=cloudbr1 --hypervisor=kvm`
Python scripts in cloudutils contain code for these configuration changes

**Comment by Hudratronium** [comment]
Thanks @shwstppr !
Will see how to put this piece of information into the docs. Even if you will have some things to check / do manually afterwards it will speed things up alot.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4756 for 4.15.1
