### ISSUE TITLE
Stabilise 4.15 branch: Fix intermittent Travis+Trillian tests failures

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#4760]
Some travis tests in job 2,3 (see pattern on travis) fail intermittently making it time consuming to run them manually again for PRs. Can we survey and see why they fail intermittently (an issue with the tests themselves or in CloudStack something that is not determinsitic/thread bound). cc @DaanHoogland

**Comment by rhtyd** [comment]
See https://travis-ci.com/github/apache/cloudstack/branches

**Comment by DaanHoogland** [comment]
I don't see per job stats there, just the the overview.

**Comment by rhtyd** [comment]
Closing this, largely passes except for two cases which are intermittent or have PRs to address them.
https://github.com/apache/cloudstack/pull/4710
