### ISSUE TITLE
 listNics api response parameter type is incorrect

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#4770]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0.0,4.15.0.0
~~~

##### SUMMARY

When VM mounts two different types of networks at the same time and queries through listnics,

The following data returned is abnormal. (actually, they are totally different, one is L3 share network, the other is isolated network.)

networkname
traffictype
type

networkid: "636fd9cc-ef29-4657-abfd-2efc5d2799d2",  type=Isolated
networkid: "d19e4183-e91e-4dc4-8cdd-430b42e0b166", type=Shared

{
listnicsresponse: {
count: 2,
nic: [
{
id: "be9123e6-3b61-497b-9b01-59290430aaa6",
networkid: "636fd9cc-ef29-4657-abfd-2efc5d2799d2",
networkname: "YuXiaoDou-test",
netmask: "255.255.255.0",
gateway: "192.168.1.1",
ipaddress: "192.168.1.7",
isolationuri: "vlan://619",
broadcasturi: "vlan://619",
traffictype: "Guest",
type: "Isolated",
isdefault: false,
macaddress: "02:00:65:91:00:03",
extradhcpoption: [ ],
deviceid: "1",
virtualmachineid: "b67781fd-1be5-4302-8aca-a53e1b1b8d98"
},
{
id: "671b8570-e182-414b-aaed-0bc82ffdf922",
networkid: "d19e4183-e91e-4dc4-8cdd-430b42e0b166",
networkname: "YuXiaoDou-test",
netmask: "255.255.255.0",
gateway: "192.168.1.1",
ipaddress: "192.168.1.17",
isolationuri: "vlan://1",
broadcasturi: "vlan://1",
traffictype: "Guest",
type: "Isolated",
isdefault: true,
macaddress: "1e:00:2c:00:00:eb",
extradhcpoption: [ ],
deviceid: "0",
virtualmachineid: "b67781fd-1be5-4302-8aca-a53e1b1b8d98"
}
]
}
}
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Fixed #4772
