### ISSUE TITLE
Listhostsmetric cpuallocated >100%

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#4778]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

When listhostsmetric calculates cpualocated and cpualocatedghz, it does not set the cpu.overprovisioning.factor The coefficient is included, resulting in cpualocated > 100%

capabilities: "hvm,snapshot"
clusterid: "2c95571e-5cf9-4ff8-b09a-750a517d6dc4"
clustername: "cl01"
clustertype: "CloudManaged"
cpuallocated: "113.84%"
cpuallocateddisablethreshold: false
cpuallocatedghz: "76.50 Ghz"
cpuallocatedthreshold: false
cpudisablethreshold: false
cpuloadaverage: 3.93
cpumodelname: "Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz"
cpunumber: 32
cpusockets: 2
cpuspeed: 2100
cputhreshold: false
cputotalghz: "67.20 Ghz (x 4.0)"
cpuused: "7.66%"
cpuusedghz: "5.15 Ghz"
cpuwithoverprovisioning: "268800"
created: "2021-03-04T18:36:38+0800"

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
cc @davidjumani I think you've started some fix around host metrics change?

**Comment by shwstppr** [comment]
@div8cn In `listHosts` API response, we get two different values cpuallocated with and without operprovisioning applied.
```
(localcloud) SBCM5> > list hosts id=4937aa4f-6f27-4dc8-af70-2335279edf27 
{
  "count": 1,
  "host": [
    {
      "capabilities": "hvm,snapshot",
      "clusterid": "881c01ec-7a4b-4c55-af5c-d53de5880b5e",
      "clustername": "p1-c1",
      "clustertype": "CloudManaged",
      "cpuallocated": "7.09%",
      "cpuallocatedpercentage": "7.09%",
      "cpuallocatedvalue": 500,
      "cpuallocatedwithoverprovisioning": "3.55%",
      "cpuloadaverage": 0.09,
      "cpunumber": 3,
      "cpusockets": 3,
      "cpuspeed": 2350,
      "cpuused": "2.09%",
      "cpuwithoverprovisioning": "14100",
      "created": "2021-03-03T06:09:26+0000",
      "details": {
        "Host.OS": "CentOS",
        "Host.OS.Kernel.Version": "3.10.0-957.12.2.el7.x86_64",
        "Host.OS.Version": "7.6.1810",
        "com.cloud.network.Networks.RouterPrivateIpStrategy": "HostLocal",
        "secured": "true"
      },
      "events": "PingTimeout; AgentDisconnected; StartAgentRebalance; AgentConnected; ShutdownRequested; Ping; ManagementServerDown; HostDown; Remove",
      "hahost": false,
      "hostha": {
        "haenable": false,
        "hastate": "Disabled"
      },
      "hosttags": "test,ha",
      "hypervisor": "KVM",
      "id": "4937aa4f-6f27-4dc8-af70-2335279edf27",
      "ipaddress": "10.10.3.146",
      "islocalstorageactive": false,
      "lastpinged": "1970-01-19T06:13:21+0000",
      "managementserverid": "2bb26158-495c-472e-865f-d24205d2befc",
      "memoryallocated": 268435456,
      "memoryallocatedbytes": 268435456,
      "memoryallocatedpercentage": "3.69%",
      "memorytotal": 7277121536,
      "memoryused": 396492800,
      "memorywithoverprovisioning": "7277121536",
      "name": "pr4710-t3640-kvm-centos7-kvm1",
      "networkkbsread": 1131042,
      "networkkbswrite": 1,
      "outofbandmanagement": {
        "enabled": false,
        "powerstate": "Disabled"
      },
      "podid": "496029eb-411a-4736-954d-73d5a8d15e56",
      "podname": "Pod1",
      "resourcestate": "Enabled",
      "state": "Up",
      "type": "Routing",
      "ueficapability": false,
      "version": "4.15.1.0-SNAPSHOT",
      "zoneid": "3f4d015c-7d6b-4b5e-86b0-79552910f77b",
      "zonename": "pr4710-t3640-kvm-centos7"
    }
  ]
}
```
I've created PR #4795 to enable this in listHostsMetrics response as well. Should this be done for memory allocated as well?
@rhtyd @DaanHoogland @weizhouapache thoughts?

**Comment by davidjumani** [comment]
+1 for getting listHosts as a subset of listHostsMetrics

**Comment by DaanHoogland** [comment]
agree, just make sure you don't change the semantics or format of any key causing backwards incompatibilities (unless the current filling of a value is obviously a bug, but even than,...)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4795
