### ISSUE TITLE
Management Server GUI: "Add Zone wizard" doesn't offer "basic networking"

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#4791]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
Management Server UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### OS / ENVIRONMENT

Management-Server on CentOS8

##### SUMMARY

When creating a new zone via the inital setup after management server installation or when adding an additonal zone afterwards, the wizard won't allow choosing "basic networking". The entry is fixed set to "Advanced networking"

##### STEPS TO REPRODUCE

![grafik](https://user-images.githubusercontent.com/79725167/110701529-8a295c80-81f1-11eb-9045-dccac9579bd0.png)

The wizard won't allow to change to "basic networking"

~~~

~~~

##### EXPECTED RESULTS

~~~
Wizard should offer to change zone configuration from advanced to basic networking
~~~

##### ACTUAL RESULTS

~~~
Can't use basic networking for zones - at least via gui
~~~

**Comment by rhtyd** [comment]
@Hudratronium yes, this is expected, we want to deprecate basic zone over time. All feature you need from a basic zone are available from advanced zone. Pl create a advanced zone and create a shared network for your use-case; or you may use the legacy UI (or APIs) to deploy a basic zone.

**Comment by Hudratronium** [comment]
@rhtyd 
Thanks for this information and imho completely understandable. Will try to share this bit of information via the offical guides.

**Comment by rhtyd** [comment]
Thanks, closing on your remark.
