### ISSUE TITLE
Is it a specification that completed jobs cannot be acquired by "listAsyncjobs"?

### ISSUE THREAD

**Issue by 0maki0** [apache/cloudstack#4792]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
API（listAsyncjobs）
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.14.0.0
~~~

##### SUMMARY

I have a question about “listAsyncjobs”.

1. Is it a CloudStack specification that completed jobs cannot be acquired with the listAsyncjobs command?
　・If startdate is specified, is “listAsyncjobs” returning asynchronous jobs remaining after the specified time?
　・Is it correct to have “removed is NULL” in the SQL condition?

```
SELECT async_job_view.id, async_job_view.uuid, async_job_view.account_id, async_job_view.account_uuid, async_job_view.account_name,
 async_job_view.account_type, async_job_view.domain_id, async_job_view.domain_uuid, async_job_view.domain_name, async_job_view.domain_path, async_job_view.user_id, async_job_view.
user_uuid, async_job_view.job_cmd, async_job_view.job_status, async_job_view.job_process_status, async_job_view.job_result_code, async_job_view.job_result, async_job_view.created,
 async_job_view.removed, async_job_view.instance_type, async_job_view.instance_id, async_job_view.instance_uuid FROM async_job_view WHERE async_job_view.account_id=2 AND async_job
_view.account_type != 5  AND async_job_view.created >= '2021-03-11 01:00:00'  AND async_job_view.removed IS NULL  ORDER BY async_job_view.id ASC  LIMIT 0, 500

```

2. Is there a way to get a completed job?

**Comment by rhtyd** [comment]
Yes, we don't return resources/objects that are marked with a removed date in the DB (this is usually for all list APIs). There's no way to get completed jobs with this API, however, you can use `queryAsyncJobResult` get the result of a completed job if you know the job ID.

Pl use the users mailing list to ask questions: http://cloudstack.apache.org/mailing-lists.html

Thanks.
