### ISSUE TITLE
Snapshot removal from secondary storage with Ceph primary v4.15

### ISSUE THREAD

**Issue by edward-stpierre** [apache/cloudstack#4797]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Snapshot cleanup
~~~

~~~

##### CLOUDSTACK VERSION

4.15

~~~

~~~

##### CONFIGURATION
KVM with Ceph primary storage / NFS secondary storage
snapshot.backup.to.secondary set to true

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The snapshot clean-up job does not try and remove snapshot from secondary storage, was working on version 4.13

##### STEPS TO REPRODUCE
Configure environment with Ceph Primary and standard NFS secondary storage.
Enable snapshot.backup.to.secondary.
Setup a scheduled volume snapshot. After flagged for deletion, many days after the snapshots still exist on the secondary storage.
I believe the issue also happens if a manual snapshot is taken and deleted. 

##### EXPECTED RESULTS

Snapshot to be removed from secondary storage

~~~

~~~

##### ACTUAL RESULTS

Snapshot remains and is not removed.
~~~

~~~

**Comment by shwstppr** [comment]
ping @GabrielBrascher @wido, can you please have a look

**Comment by GabrielBrascher** [comment]
Thanks for opening this issue @edward-stpierre. I reproduced the same issue and I plan to take a deeper look at it.

**Comment by rhtyd** [comment]
Thanks @GabrielBrascher are you planning to raise a PR?

**Comment by rhtyd** [comment]
Ping @GabrielBrascher - any update on this?

**Comment by GabrielBrascher** [comment]
@rhtyd so far it still on the backlog. I hope to get some attention at this soon.

**Comment by rhtyd** [comment]
Alright @GabrielBrascher if you're unable to work on it, let's move to next milestone

**Comment by rhtyd** [comment]
Ping @GabrielBrascher

**Comment by GabrielBrascher** [comment]
@rhtyd unfortunately I have not been able to address this issue in time for next 4.15.

**Comment by DaanHoogland** [comment]
@GabrielBrascher are you planning it for milestone 4.16 (accidentally added it)

**Comment by rhtyd** [comment]
Fixed by https://github.com/apache/cloudstack/pull/5130
