### ISSUE TITLE
GSoC 2021 Idea - UX improvements in the UI

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4798]
## Background

Surely our new UI is great, but some users might find it interesting to navigate with shortcuts and kayboard only

## Proposed Tasks

This could be interesting to any UI/UX engineer, not required huge domain knowledge which usually turns down candidates.
 

1. Being able to navigate without mouse and use shortkey – for example when on the dashboard when the user presses T, he could be directly transitioned to Templates. Or I for infrastructure, G – global settings, H for hosts etc.. While in networks/instances/volumes press A – add item(network,volume etc). Same goes for all buttons inside a page like Instances (stop, start, destroy etc)
![Screenshot 2021-03-11 at 14 57 32](https://user-images.githubusercontent.com/13551960/110792281-db7e2e00-827b-11eb-8f44-776bba10c7b2.png)
![Screenshot 2021-03-11 at 14 53 19](https://user-images.githubusercontent.com/13551960/110792286-dcaf5b00-827b-11eb-9562-5ecefb8f9d4e.png)

List of suggestions of shortcuts: 
- [i] - infrastructure
- [g] - configuration->global settings
- [v] - storage->volumes
- [c] - compute->instances
- [t] - images->templates
- [n] - networks 
- [a] - accounts
- [p] - projects
- [e] - events
_Please bring up this list to community mailing lists for comments and objections. Also someone could bring up more ideas_

2. Confirm dialogues with key – This is not working consistently, some dialogue windows have it some do not. But surely it’ll be great if we can confirm by pressing Enter or Space and cancel by Esc.
 
3. Forms submission improvements – For example, when deploying instance if you simply click ok without selected network it will prompt you with error and then you’ll need to scroll back to the network place and add it. We could be more intuitive and automatically move the focus of the user back at the networks place in the form, where user can easily add or select a network.
 
4. Placement of buttons and forms – I’ve pointed this as debatable since it’s more of a UX discussion, which may end up with a decision ‘there is nothing to fix’. The idea is to think about questions as is this form intuitive enough, or is this button placed good, maybe there’s a more suitable place for it. Etc.

### Relevant Skills
- Vue.js

## Proposed Mentor

Boris Stoyanov - requirements and ideas
David Jumani - coding part
Any developer from the community - Coding issues 

## Difficulty

Easy

## Potential Mentors

Boris Stoyanov - requirements and ideas (boris.stoyanov@shapepblue.com)
David Jumani - coding part (david.jumani@shapeblue.com)
Rohit Yadav - any help/guidance (rohit@apache.org)

##### ISSUE TYPE

 * Feature Idea

**Comment by rhtyd** [comment]
@borisstoyanov can you use the structure/format as in https://github.com/apache/cloudstack/issues/4696

**Comment by borisstoyanov** [comment]
Thanks @rhtyd, updated.

**Comment by apurv-1** [comment]
Hey @borisstoyanov, I would like to work on this. I can write a GSoC proposal for this. I did some really great projects on Reactjs and a few in Vuejs too. You can check out [Resillience](https://resillience.in/) the frontend is based on Reactjs. This was the most challenging project I did recently. Made the entire project including backend.

**Comment by shwstppr** [comment]
@apurv-1To start with you can check the UI code here, https://github.com/apache/cloudstack/tree/master/ui, you can try to build the UI and play with it in a simulator env.
This might help https://github.com/shapeblue/hackerbook
If not already you may join CloudStack mailing lists to get more idea about it.

**Comment by shwstppr** [comment]
@apurv-1 ^^

**Comment by apurv-1** [comment]
Sure, Thanks @shwstppr

**Comment by borisstoyanov** [comment]
Hi @apurv-1, great to hear you have interest! I've replied your email with instructions how to proceed.

**Comment by apurv-1** [comment]
Yeah Sure, Thankyou @borisstoyanov :)

**Comment by rhtyd** [comment]
Hi @apurv-1 thanks for your interest.

I would advise that you read the community GSoC guidelines (https://community.apache.org/gsoc.html), join the dev mailing list (http://cloudstack.apache.org/mailing-lists.html) to discuss your GSoC idea/proposal/application, and start drafting your application (for example https://google.github.io/gsocguides/student/proposal-example-1). With your proposed mentor (see email above), start an early discussion with them and you can ask them to review your application draft (for example, compose your draft and share with a Google doc).

You can refer to the CloudStack course to help you draft your application and learn how to build something in CloudStack https://github.com/shapeblue/hackerbook

**Comment by apurv-1** [comment]
Hello @rhtyd, I'm on the mailing list, I'll soon start a discussion regarding UX improvements on the mailing list. 
Sorry, it's too late but I've drafted the proposal. Can you please review it?
