### ISSUE TITLE
GSoC 2021 Idea: Add SPICE console for vms on KVM

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4803]
## Background

CloudStack provides ajax vnc view and novnc console to access vm. It would be good to have spice console for vms on kvm/xenserver.

## Proposed Tasks

- Get started on basic CloudStack codebase and development (building and running CloudStack)
- Setup KVM based CloudStack dev/test environment
- Setup Xenserver based CloudStack dev/test environment
- Test websockify-based SPICE console
- Add websockify/spice-html5 source code in cloudstack
- Run websockify server with token authentication
- Implement a http server in CPVM to verify websockify token.
- Create URL with a token to access novnc/spice console

ps1: VNC password will be removed from vm xml definition as it is not supported by websockify.
ps2: websockify-based novnc console can be added as well.

### Relevant Skills
- Java
- python (few)
- networking (few)

## Proposed Mentor

Wei Zhou, PMC/commiter Apache CloudStack

## Difficulty

Major

## Potential Mentors

Wei Zhou, PMC/commiter Apache CloudStack

### Example and references
https://www.spice-space.org/spice-html5.html
https://gitlab.freedesktop.org/spice/spice-html5
https://github.com/novnc/websockify
https://docs.openstack.org/nova/pike/admin/remote-console-access.html
https://github.com/novnc/noVNC

##### ISSUE TYPE

 * Feature Idea

**Comment by hooklee2000** [comment]
I tried latest spice-html5 to connect a vm guest installing windows 7 ( on CentOS7 default qemu 1.5.3,libvirt 4.5.0)，it work well including video,audio without guest qxl driver  .
With qxl driver,  mouse cursor was misposition and some image overlap.

**Comment by weizhouapache** [comment]
> I tried latest main [spice-html5](https://gitlab.freedesktop.org/spice/spice-html5) to connect a vm guest installing windows 7 ( on CentOS7 default qemu 1.5.3,libvirt 4.5.0)，it work well including video,audio without guest qxl driver .
> But with guest qxl driver for better display effect, mouse cursor misposition and some image overlap (we also tried spice-html5 and [ spice-web-client](https://github.com/eyeos/spice-web-client) qemu5.2.0,libvirt7.2.0, the same result) .<img alt="微信图片_20210520145206" width="1157" src="https://user-images.githubusercontent.com/52850777/118932763-fd321a80-b97a-11eb-9dd4-02757c9a0230.png">
> May you give me some advice? Thanks a lot!
> By the way spice-server 0.14.3 support for WebSocket, this will allow to use spice-html5 without proxy.

@hooklee2000 
have you tried with more memory and/or video ram ?
see ram, vram, vgaram in https://libvirt.org/formatdomain.html#video-devices

spice-server is great. It looks difficult to integrate it into cloudstack.

**Comment by hooklee2000** [comment]
We tried to increase the video memory (ram, vram, vgaram) from default 16MB to 65MB, the same result.
Maybe spice-html doesn't support qxl.
 I tried spice-web-client which work well but some icon and text mirror vertical.

**Comment by rohityadavcloud** [comment]
@weizhouapache compared to our current noVNC, what are the pros/cons of this feature? (I would imagine people using rdp etc if they want sound etc support)

**Comment by weizhouapache** [comment]
@rohityadavcloud 
I thought that the SPICE has better performance than noVNC, esp on windows vms. However, as I know after I created this ticket, SPICE console does not have significant performance improvement than NoVNC console. 

Let's close this ticket, and reopen if needed.
