### ISSUE TITLE
Missing password.txt in ConfigDrive in multihomed VM

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#4809]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
ConfigDrive
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

CentOS7
ESXi 6.5

##### SUMMARY

When attach a VM to 2 networks which one of them uses VirtualRouter as userdata provider and other uses ConfigDrive, after password reset, you can't find password.txt file in ConfigDrive ISO

##### STEPS TO REPRODUCE

~~~
Create a network with VirtualRouter as userdata provider
Create a network with ConfigDrive  as userdata provider
Create a VM and attach it to both networks
~~~

##### EXPECTED RESULTS

~~~
Get password from VirtualRouter as well as ConfigDrive
~~~

##### ACTUAL RESULTS

~~~
VritualRouter gives you the password but there is no password.txt in ConfigDrive ISO
~~~

**Comment by weizhouapache** [comment]
@aleskxyz vm password is only sent to the Virtual Router of first network, not all networks.

**Comment by aleskxyz** [comment]
> @aleskxyz vm password is only sent to the Virtual Router of first network, not all networks.
> this is the expected behavior.
@weizhouapache 
Thanks for you comment.
I can confirm that when I use L2 network as the default network, I can find password.txt file in the iso.
I don't know why it should be expected behavior that only one of virtual routers provides the password. Maybe it is due to this fact that lifecycle management of password is handled by virtual router it self, not the CS management. I mean that when the VM gets the password from the virtual router, it sends a confirmation to router then router forgets the password.
But I think from VM point of view, using ConfigDrive for getting userdata is not relevant to type and order of attached networks. It is an independent datasource.
How can I figure out that attached ConfigDrive iso is a result of a default network or an additional network?!
Thanks

**Comment by weizhouapache** [comment]
@aleskxyz 
most cloudstack users use the following scripts (or similar)
https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password.in
https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password-configdrive.in

the vm password is processed like
(1) save vm password in VR
(2) when vm starts, it gets dhcp ip from dhcp server (VR), then sends request to the a password server (=dhcp server/VR from dhcp lease file)
(3) when vm gets password from password server(VR), it sends a request to remove the password in password server (VR).

the scripts get password from only 1 password server/VR (and exit). password is also saved into only 1 password server/VR.
that's the expected behavior in cloudstack.


in cloudstack , each nic has a `device_id` in `nics` table.
deviceId will be also displayed in response and UI, see #4768

**Comment by aleskxyz** [comment]
> @aleskxyz
> most cloudstack users use the following scripts (or similar)
> https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password.in
> https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password-configdrive.in
> 
> the vm password is processed like
> (1) save vm password in VR
> (2) when vm starts, it gets dhcp ip from dhcp server (VR), then sends request to the a password server (=dhcp server/VR from dhcp lease file)
> (3) when vm gets password from password server(VR), it sends a request to remove the password in password server (VR).
> 
> the scripts get password from only 1 password server/VR (and exit). password is also saved into only 1 password server/VR.
> that's the expected behavior in cloudstack.
> 
> in cloudstack , each nic has a `device_id` in `nics` table.
> deviceId will be also displayed in response and UI, see #4768

Thanks @weizhouapache 
Did you use these scripts with cloud-init?
One of the reasons that I open this issue was simplifying password management with cloud-init.
If you have any experience with it, please leave your comment in the related question in mailing-list:
https://lists.apache.org/thread.html/r57b74dcd13d656ee0351bdf93bf3ee0ca307ce972c701821d3245706%40%3Cusers.cloudstack.apache.org%3E

**Comment by weizhouapache** [comment]
> > @aleskxyz
> > most cloudstack users use the following scripts (or similar)
> > https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password.in
> > https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password-configdrive.in
> > the vm password is processed like
> > (1) save vm password in VR
> > (2) when vm starts, it gets dhcp ip from dhcp server (VR), then sends request to the a password server (=dhcp server/VR from dhcp lease file)
> > (3) when vm gets password from password server(VR), it sends a request to remove the password in password server (VR).
> > the scripts get password from only 1 password server/VR (and exit). password is also saved into only 1 password server/VR.
> > that's the expected behavior in cloudstack.
> > in cloudstack , each nic has a `device_id` in `nics` table.
> > deviceId will be also displayed in response and UI, see #4768
> 
> Thanks @weizhouapache
> Did you use these scripts with cloud-init?
> One of the reasons that I open this issue was simplifying password management with cloud-init.
> If you have any experience with it, please leave your comment in the related question in mailing-list:
> https://lists.apache.org/thread.html/r57b74dcd13d656ee0351bdf93bf3ee0ca307ce972c701821d3245706%40%3Cusers.cloudstack.apache.org%3E

@aleskxyz 
I have not subscribed to the users mailing list.  see my answer below

(1) we use cloud-init to set up cloud server, but we do not use it to manage/update password and ssh keys. we use a script similar as the scripts in my previous comment. the script will be executed when an interface is up.

(2) I guess the reason of ssh key is not applied is that, you use `- ssh`, not `- [ ssh, always ]`.

(3) for configdrive, please use script https://github.com/apache/cloudstack/blob/master/setup/bindir/cloud-set-guest-password-configdrive.in, it looks good.

**Comment by aleskxyz** [comment]
Thank you @weizhouapache
I will test it and write a document about it.
Regards
