### ISSUE TITLE
GSoC 2021 Idea: Synchronization of network devices on newly added hosts for Persistent Networks

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#4814]
##### Background

Cloudstack offers Persistent Networks which gets provisioned at the time of creation without having to deploy a VM in the network (http://docs.cloudstack.apache.org/en/latest/adminguide/networking/persistent_networks.html). However, in case new hosts are added or disabled hosts re-enabled or moved from maintenance mode to enabled state, the network devices do not get provisioned on such hosts.
To comply with the definition of Persistent Networks, we need to have a mechanism to synchronize the creation of network devices (VLANs/ bridges, etc) on hosts added post creation of the network by extending the existing framework of `HypervisorHostListener` to support creation of Persistent networks in a general manner .

This would involve:
- Scanning for hosts that have been added post creation of the network
- Scanning for hosts that have transitioned to Active state post creation of network

##### Proposed Tasks

   - Get started on basic CloudStack codebase and development (building and running CloudStack)
   - Understanding persistence in the context of CloudStack and across hypervisors
   - Define strategy to identify hosts that don't have the resources (bridges,etc) provisioned on them
   - Define strategy to provision networks across identified hosts
   - Deliverables: documentation and community pull request, end-to-end demo of feature

##### Relevant Skills
Java and Python

#### Difficulty
Moderate

##### Proposed Mentor
Pearl Dsilva - pearl.dsilva@shapeblue.com
Rohit Yadav - rohit@apache.org

##### Example and references
https://github.com/apache/cloudstack/blob/master/engine/api/src/main/java/org/apache/cloudstack/engine/subsystem/api/storage/HypervisorHostListener.java

**Comment by shatoboar** [comment]
Hi, I would really like to work on this project! Is there any further information or any tips to better understand the project?

**Comment by Pearl1594** [comment]
@shatoboar I've sent a mail with details that would be helpful to understand the project and the requirements. All the best! :) Feel free to reach out if you have any queries.

**Comment by JushwanthGV** [comment]
Hi,
I'm interested in this project, and I'm new to open source I would like to include this project for gsoc.
Can anyone help me with how to start?
I would like to know all the requirements needed for this project so that i can be ready for this project.
I would like some tips and some more insights abt this project.

**Comment by Pearl1594** [comment]
Hi @JushwanthGV , thanks for your interest!
To start off, you can work on drafting your application / project proposal and may use https://google.github.io/gsocguides/student/proposal-example-1 as a guideline. And reach out if you need further details. Please also go through the GSoC guidelines - https://community.apache.org/gsoc.html - if you haven't already.

**Comment by rohityadavcloud** [comment]
Closing this as we've a PR, and this may cause confusion for student looking for gsoc ideas.
