### ISSUE TITLE
vm created by ISO cannot resize the root disk size

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#4827]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

VM created by ISO cannot resize the root disk size.
Error:
Failed to resize Root volume. The service offering of this Volume has been configured with a root disk size; on such case a Root Volume can only be resized when changing to another Service Offering with a Root disk size. For more details please check out the Official Resizing Volumes documentation.

VM created by tempalte can resize root disk size.

https://github.com/apache/cloudstack/pull/4341 

My serviceoffering not set rootdisksize item

##### STEPS TO REPRODUCE

~~~
1. Create serviceoffering, name=iso-1c-1g, (do not set rootdisksize.)
2. Deploy the VM using ISO, name=iso-vm01, and use serviceoffering=iso-1c-1g.
3.stop vm iso-vm01.
4.resize iso-vm01 root disk size to 100G(size=120&id=ebe7be07-5276-4e38-8563-64d47ae83972&command=resizeVolume&response=json)

~~~

##### EXPECTED RESULTS

~~~
vm root disk size changed to 120G
~~~

##### ACTUAL RESULTS

~~~
Task execution failed
The root disk size has not changed.

API throws an error:
Failed to resize Root volume. The service offering of this Volume has been configured with a root disk size; on such case a Root Volume can only be resized when changing to another Service Offering with a Root disk size. For more details please check out the Official Resizing Volumes documentation.
~~~

**Comment by rhtyd** [comment]
@Pearl1594 can you check if your PR/fix addresses the case of ISO?

**Comment by Pearl1594** [comment]
@rhtyd I've added a fix to allow resizing of Root volume of a VM deployed from an ISO - https://github.com/apache/cloudstack/pull/4829/commits/1c3fc3c57621f003aaefbabae73d8f43fa0ee523.

**Comment by div8cn** [comment]
I verified the commit https://github.com/apache/cloudstack/commit/1c3fc3c57621f003aaefbabae73d8f43fa0ee523

It solved the problem.

thank @Pearl1594  @rhtyd

**Comment by rhtyd** [comment]
@Pearl1594 is that commit part of your PR or already merged?

**Comment by Pearl1594** [comment]
It's part of PR https://github.com/apache/cloudstack/pull/4829 - which hasn't yet been merged. Would you prefer me raising a separate PR to fix this? @rhtyd

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4829
