### ISSUE TITLE
Add Role and Import Role Dialog UI doesn't show info / tooltip for the parameters

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#4835]
Add Role and Import Role Dialog UI doesn't show info / tooltip for the parameters

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### SUMMARY

The following roles dialog doesn't show info / tooltip for the parameters

- Add Role

<img width="540" alt="AddRole" src="https://user-images.githubusercontent.com/12028987/111475985-ad08c300-8753-11eb-87cd-eda70876ad5e.png">

- Import Role

<img width="536" alt="ImportRole" src="https://user-images.githubusercontent.com/12028987/111476011-b5f99480-8753-11eb-9d5e-367532a3f30c.png">

##### STEPS TO REPRODUCE

- Go to Roles section in to UI
- Open "Add Role" or "Import Role" dialog

~~~

~~~

##### EXPECTED RESULTS

~~~
Add Role and Import Role Dialog UI should show info / tooltip for the parameters
~~~

##### ACTUAL RESULTS

~~~
Add Role and Import Role Dialog UI doesn't show info / tooltip for the parameters
~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4836
