### ISSUE TITLE
UI should show IPv6 addresses of Instance

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#4844]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15
master
~~~

##### SUMMARY
The new UI does not show IPv6 addresses of VMs and/or NICs.

##### ACTUAL RESULTS
I have taken a few screenshots from the new UI on a deployment which has IPv6 enabled Virtual Machines with VXLAN in a Shared Network.

<img width="2556" alt="Screenshot 2021-03-19 at 11 17 54" src="https://user-images.githubusercontent.com/326786/111765943-3d0a5200-88a5-11eb-9ed2-c99d48d6df10.png">

**Comment by abhi005** [comment]
Hey @DaanHoogland I would like to work on this issue. As this is one of the mandatory requirements for my course work, will make sure that it gets completed.

**Comment by DaanHoogland** [comment]
@abhi005 , I see @rhtyd has assigned this to @utchoang in the meanwhile so be sure to communicate the best solution amongst yourselves.

**Comment by abhi005** [comment]
Cool, So just to be sure requirement is to show only IPv6 on view page and not both. correct? @DaanHoogland @rhtyd

**Comment by wido** [comment]
> Cool, So just to be sure requirement is to show only IPv6 on view page and not both. correct? @DaanHoogland @rhtyd

I would say that we should display the IPv6 address of a NIC/Instance on any page where we also show the IPv4 address.

**Comment by abhi005** [comment]
Ok thanks for the clarification, I have started with the local setup and will start making changes asap.

**Comment by DaanHoogland** [comment]
> Cool, So just to be sure requirement is to show only IPv6 on view page and not both. correct? @DaanHoogland @rhtyd

No @abhi005 I think both should be shown if available.

**Comment by abhi005** [comment]
I think showing both of them would be confusing for user and not very asthetic from UI point of view. Otherwise we can tweak UI little bit, to accomodate both the options.

**Comment by DaanHoogland** [comment]
You could be right @abhi005, I'm not a UI expert (other than for making angry fruit salads). As an operator I want to be able to show both though.
what do you think @wido, @utchoang, @rhtyd ?

**Comment by wido** [comment]
> I think showing both of them would be confusing for user and not very asthetic from UI point of view. Otherwise we can tweak UI little bit, to accomodate both the options. @DaanHoogland

We should always display IPv6 when it's available. It's a different IP-stack and it has to be shown.

The user then chooses if he/she uses the v4 or the v6 address for it's application.

**Comment by rhtyd** [comment]
Ping @utchoang @abhi005 @GabrielBrascher are you working on this?

**Comment by utchoang** [comment]
I think @abhi005 is working with this issue? cc @rhtyd

**Comment by utchoang** [comment]
@abhi005 are you woking on this?

**Comment by abhi005** [comment]
@utchoang yes, already started.

**Comment by rhtyd** [comment]
Ping @abhi005 @utchoang - any progress on this? I'll leave with @GabrielBrascher @wido for tracking.

**Comment by rhtyd** [comment]
Ping @abhi005 @utchoang

**Comment by utchoang** [comment]
> @utchoang yes, already started.
@abhi005 Have you done it yet, If yes then can you put PR for us to consider?

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4948
