### ISSUE TITLE
Unable to establish noVNC connection to VM console

### ISSUE THREAD

**Issue by MoeRT09** [apache/cloudstack#4858]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Clean Chrome browser installation.

##### SUMMARY

There seems to be some kind of timing issue, when trying to establish a console connection to a VM using noVNC. Sometimes it does not try to connect. This behavior is really inconsistent between different devices, as trying to connect from some devices had no issue, while others never were able to connect. However we could narrow it down to some timing issue in the browser. 

There is a point, where the noVNC connect button is clicked from Javascript (you can not click the button manually, as it is hidden). Depending on the environment this succeeded or not. The most issues seem to be caused by Firefox. But a fresh installation of Chrome (or any other Chromium based browser like Chromium Edge, Brave...) shows a similar behavior. Interestingly you can somehow "fix" this issues, by installing arbitrary browser extensions (maybe they delay the page rendering just so slightly, that the connect button gets clicked).

I recorded a Video demonstrating the behavior by enabling and disabling the "Google Translator" extension. Note, that this is a completely fresh installation of Chrome, with all default extensions disabled. Other extensions do work to, especially password managers.

##### STEPS TO REPRODUCE

1. Start Firefox or a Chromium based browser with an empty profile and/or disable all browser extensions.
2. Open the console of a VM

**Videos demonstrating the issue:**

https://user-images.githubusercontent.com/8270908/112172634-2c374480-8bf5-11eb-9197-321bb8e7d42a.mp4

**Video 1: "Fixing" the bug by enabling extensions**

https://user-images.githubusercontent.com/8270908/112173035-833d1980-8bf5-11eb-9961-aca3d11065d5.mp4

**Video 2: Manually "clicking" connect via Javascript**

##### EXPECTED RESULTS

Connecting to the console actually connects to the console in every browser and environment.

##### ACTUAL RESULTS

Depending on the environment, a connection to a VM console can be established or not.

**Comment by weizhouapache** [comment]
@MoeRT09 this should be fixed by #4833

**Comment by MoeRT09** [comment]
@weizhouapache you are right. Appending the `autoconnect=true` parameter to the URL of the iframe fixes it.

**Comment by weizhouapache** [comment]
> @weizhouapache you are right. Appending the `autoconnect=true` parameter to the URL of the iframe fixes it.

good to know !

**Comment by rhtyd** [comment]
@MoeRT09 since it's fixed by #4833 - can you review and close the issue. (The fix will be in 4.15.1)

**Comment by MoeRT09** [comment]
@rhtyd Is it possible to find the updated relevant package somewhere, so i can drop it in for testing?

**Comment by rhtyd** [comment]
@MoeRT09 I think we don't have nightly(publicly hosted) packages, can you try to build the packages yourself? Or wait until we do a 4.15.1.0 RC1 (sometimes in April).

I'm closing based on the discussions that the original issue has been fixed in https://github.com/apache/cloudstack/pull/4833
