### ISSUE TITLE
Basic Networking needs to be restored - Advanced networks with security groups is not the same.

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#4863]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI and potentially networking, zone creation etc.
~~~

##### CLOUDSTACK VERSION

~~~


To simplify/consolidate the networking models (primarily to remove a lot of Cloud Operator confusion) it was 'concluded' that as 'basic networking' is the same as 'advanced networking with security groups' with only one network (VLAN); basic networking as a separate networking type could be depreciated.

However, this premise is not correct.

**'Basic networking' is NOT the same as 'advanced networking with security groups' with only one network (VLAN)**


- Guest networks in basic networking, have ONE SUBNET PER POD, and a gateway per pod for inter-pod guest traffic.  They also have on VR per pod to supply the DHCP, DNS, metadata and user data for that POD (Broadcast domain).
- Guest networking in an advanced network with security groups has ONE SUBNET PER VLAN, which spans the ENTIRE ZONE.  A zone created in this way would have one VR for the entire zone.

They may look very similar when there is only one cluster.
BUT THEY ARE COMPLETELY DIFFERENT.

I'm all for renaming the network styles (basic and advanced is just meaningless).  But an 'advanced network with security groups' with one network zone is nothing like a basic networking zone.

Basic networking cannot be removed in the way that it has.

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Users of 4.15.1 needing basic zone deployment can use the legacy UI, the blocker would make sense for 4.16.0.0 where the legacy UI has been removed. @PaulAngus can you start a discussion thread on dev@?

@utchoang can you look into if the basic zone option can be enabled in the new UI? (I remember it being working just the option is disabled) If it's only that we can include it for 4.15.1.0.

**Comment by PaulAngus** [comment]
Users would be completely unaware of the difference until it was too late; The 'knowledgeable person and knowledgeable tester(s)' who made the change were unaware of the difference.

Users would assume that THE UI would be correct for something so fundamental.  This would send all users down the wrong path for any initial or new zones and therefore needs to be fixed in 14.5.1 as well as 4.16

n.b. as I recall, the new UI's default zone creation is now the _not_-basic networking.  

This is a huge regression and needs rectifying before more users' experience of CloudStack is completely screwed up.

**Comment by utchoang** [comment]
> Người dùng 4.15.1 cần triển khai vùng cơ bản có thể sử dụng giao diện người dùng kế thừa, trình chặn sẽ có ý nghĩa đối với 4.16.0.0 khi giao diện người dùng kế thừa đã bị loại bỏ. @PaulAngus, bạn có thể bắt đầu một chuỗi thảo luận về dev @ không?
> 
> @utchoang, bạn có thể xem xét liệu tùy chọn vùng cơ bản có thể được bật trong giao diện người dùng mới không? (Tôi nhớ nó đang hoạt động chỉ là tùy chọn bị vô hiệu hóa) Nếu chỉ có điều đó, chúng tôi có thể đưa nó vào 4.15.1.0.

Hi, @rhtyd  cc @PaulAngus, I checked the Base area has been removed. I'll add it back and add options to show/hide based on config.json. Thanks.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4882
