### ISSUE TITLE
No "data-server" DNS record for VPC router

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#4865]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

N/A

##### SUMMARY

No "data-server" DNS record for VPC router

##### STEPS TO REPRODUCE

~~~
1. Create a VPC
2. Add an isolated network with UserData service with VirtualRouter as provider
3. Create a VM in this network
4. Run "nslookup data-server" command from inside of VM
~~~

##### EXPECTED RESULTS

~~~
Running "nslookup data-server" command returns IP address of router
~~~

##### ACTUAL RESULTS

~~~
Running "nslookup data-server" command returns "No answer"
~~~

**Comment by weizhouapache** [comment]
@aleskxyz 
in VR of shared/isolated network, there is a record in /etc/hosts like
`192.168.10.1    r-10-VM data-server`

however, this does not work in vpc, as there might be multiple guest nics.

**Comment by aleskxyz** [comment]
> @aleskxyz
> in VR of shared/isolated network, there is a record in /etc/hosts like
> `192.168.10.1 r-10-VM data-server`
> 
> however, this does not work in vpc, as there might be multiple guest nics.

@weizhouapache 
I think we can use the "localise-queries" feature of dnsmasq. So I have created a PR about it. (#4873 )

**Comment by DaanHoogland** [comment]
closing as #4873 is merged
