### ISSUE TITLE
isrecursive not honoured for listAccounts, maybe others as well

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#4868]
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

4.14 + (maybe even lower versions)

##### SUMMARY

isrecursive is not honoured when passed along with listall=true for listAccounts as a root admin
It is also not honoured when allow.user.view.all.domain.accounts is true

https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L2198-L2205

##### EXPECTED RESULTS
```
(qa) 🐱 > list accounts filter=name,domain domainid=e4874e10-5fdf-11ea-9a56-1e006800018c listall=true isrecursive=false 
{
  "account": [
    {
      "domain": "ROOT",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "name": "baremetal-system-account"
    },
    ................

```

##### ACTUAL RESULTS
```
(qa) 🐱 > list accounts filter=name,domain domainid=e4874e10-5fdf-11ea-9a56-1e006800018c listall=true isrecursive=false 
{
  "account": [
    {
      "domain": "ROOT",
      "name": "admin"
    },
    {
      "domain": "ROOT",
      "name": "baremetal-system-account"
    },
    {
      "domain": "small",            <- from a sub domain
      "name": "rick"
    },
```

**Comment by DaanHoogland** [comment]
so basically teh defined functionalities of `listall` and `isrecursive` overlap and `listall` prefails. iniutitively I'd say `isrecursive` should prefail, so FWIW I agree.

**Comment by ravening** [comment]
@davidjumani @DaanHoogland this issue exists for several api's if you call the api from the child domain

I have seen the same issue for listing service offering and disk offering as well. I have created a pr for it

Create the following domain relationship

ROOT -> test1 -> test11

Now login as test1 and create a service offering for test11 domain.
If you login as test11, you wont see it

**Comment by DaanHoogland** [comment]
> @davidjumani @DaanHoogland this issue exists for several api's if you call the api from the child domain
> 
> I have seen the same issue for listing service offering and disk offering as well. I have created a pr for it
> 
> Create the following domain relationship
> 
> ROOT -> test1 -> test11
> 
> Now login as test1 and create a service offering for test11 domain.
> If you login as test11, you wont see it

@ravening that sounds more like a problem with access than recursion, wouldn't you say so?

**Comment by ravening** [comment]
Not with recursion but how the code works

**Comment by DaanHoogland** [comment]
yes, well, domains have a concept of recursion but accounts do not. In the zone/pod/cluster/host there is another form of what could be called recursion. What you name above seems like a bug to me, but in general it is hard to define recursion consistently in cloudstack behaviour when it comes to these constructs.

> Not with recursion but how the code works

Do you agree with how @davidjumani proposes to implement this?
And do you have other examples where it should behave the same?

I think what you mention about creating a service offering merits an issue ticket of its own.

**Comment by davidjumani** [comment]
I think that this is a deeper issue that could be across several elements. Need to look into whether this should be fixed. I personally think so and can raise a PR for the same but would like to get a wider feedback

**Comment by nvazquez** [comment]
@davidjumani reading the description of the parameters:
- listall: If set to false, list only resources belonging to the command's caller; if set to true - list resources that the caller is authorized to see. Default value is false
- isrecursive: defaults to false, but if true, lists all resources from the parent specified by the domainId till leaves.

Seems like these definitions might need a change, have you thought about a new behaviour?

**Comment by davidjumani** [comment]
@nvazquez Not just the definitions but the implementations as well

**Comment by nvazquez** [comment]
@davidjumani sure, my question was if you could explain what's your idea on the new implementation. Maybe easier to explain the new definitions of both parameter

**Comment by davidjumani** [comment]
@nvazquez My idea is :
- listall : Returns all resources the user can access. As of now when set to true, it fetches resources recursively even if isrecursive is set to false. Change it to respect isrecursive
- isrecursive : Leave it as is

**Comment by nvazquez** [comment]
+1 for me, @DaanHoogland @rhtyd any input?

**Comment by DaanHoogland** [comment]
I agree that what @davidjumani describes is the intuitive way, but it might cause a regression like behaviour of user scripts so we need to document very well if we change this. (and possibly provide automated migration, though it seems not more than adding the `isrecursive=true` in scripts at first sight)

**Comment by Pearl1594** [comment]
If I could add a point here - as per my understanding, `isrecursive` is a parameter used in conjunction with domainid, where as when invoking a list api with `listall` it should list everything, irrespective of the value of `isrecursive`(which is what it does currently). In my opinion, the current behavior isn't actually wrong/buggy.

**Comment by davidjumani** [comment]
@Pearl1594 If that is the case, isn't passing a `domainid` along with `isrecursive` as true the same as passing `domainid` with `listall` as true ? In that case is `isrecursive` redundant ?
Also a user might want to list all accounts only in his / her domain without the need to explicitly pass the domainid. In that case it will return all users in subdomains as well.
I believe that this could be misleading. Either it should be fixed or a note added that `listall` ignores or is the same as passing `isrecursive`

**Comment by rhtyd** [comment]
Moving this to next milestone.

**Comment by rohityadavcloud** [comment]
It appears David's PR was reverted. @nvazquez pl review with 4.17 team if this is worth fixing for 4.17, or move to next milestone(s).

**Comment by nvazquez** [comment]
Thanks @rohityadavcloud we have forgotten to reopen this issue after reverting the PR, moving it to the next milestone

**Comment by davidjumani** [comment]
This is a niche case and not frequently encountered. Can reopen when required
