### ISSUE TITLE
why new ui just have advanced network and not have the basic network zone option?

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#4876]
##### ISSUE TYPE

 * Improvement Request
##### COMPONENT NAME

~~~
   UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### STEPS TO REPRODUCE

![avatar](https://user-images.githubusercontent.com/20500978/112594030-449c9e80-8e43-11eb-94c3-25906ab33dad.png)

##### EXPECTED RESULTS

~~~
 have the basic network option when i create zone like leg
~~~
![avatar](https://user-images.githubusercontent.com/20500978/112593619-b45e5980-8e42-11eb-9974-7de9eda9b950.png)

##### ACTUAL RESULTS

~~~
  just have advanced network option on the new ui
~~~

**Comment by shwstppr** [comment]
@staySober Duplicate issue https://github.com/apache/cloudstack/issues/4863?

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4882

**Comment by staySober** [comment]
thanks a lot
