### ISSUE TITLE
UI Physical Network Setup in Zone Wizzard fails

### ISSUE THREAD

**Issue by mkriegs** [apache/cloudstack#4877]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

##### CLOUDSTACK VERSION
<!--
4.15.0.0
Master
-->
~~~

##### CONFIGURATION

advanced networking setup over GUI

##### OS / ENVIRONMENT

Ubuntu 20.04
Centos 8
on KVM and Management Server

##### SUMMARY

If u do setup of our zone from gui it leads into fail config of the physical Network interfaces. U can change the settings afterwards but  people are new to Cloudstack fall into trap.

##### STEPS TO REPRODUCE
![cloudstack1](https://user-images.githubusercontent.com/23615999/112659054-5175be00-8e54-11eb-9050-45acbda9d8c6.JPG)
physical Interface 1 to bridge cloudbr01, label for management traffic (cloudbr01)
![cloudstack2JPG](https://user-images.githubusercontent.com/23615999/112659055-520e5480-8e54-11eb-877a-fde95b34b96e.JPG)
physical Interface 2 to bridge cloudbr03, label for guest traffic (cloudbr03)
same for public traffic but not displayed here
![cloudstack3](https://user-images.githubusercontent.com/23615999/112659043-50449100-8e54-11eb-8afb-095e036069a3.JPG)
physical Interface 3 to bridge cloudbr02, label for storage traffic (cloudbr02100) (fakebrigde on top of brigde for vlan tagging)
![cloudstack4](https://user-images.githubusercontent.com/23615999/112659047-50dd2780-8e54-11eb-873a-ad75622f8b1b.JPG)
![cloudstack5](https://user-images.githubusercontent.com/23615999/112659050-5175be00-8e54-11eb-81c3-1d556c71870c.JPG)
![cloudstack6](https://user-images.githubusercontent.com/23615999/112659052-5175be00-8e54-11eb-8ac2-d75e32c74cb5.JPG)

Issue is from handling /mapping values from gui to api

##### EXPECTED RESULTS

Labels on the correct interface and VLAN Ranges to correct interface. This works with API Calls for the Setup of the Zone but not from GUI!

##### ACTUAL RESULTS

Values are shuffled around and first host not added correctly with brigde names. Labels are Missing on the physical Interfaces. Some Values are lost.

![cloudstack7](https://user-images.githubusercontent.com/23615999/112659301-86821080-8e54-11eb-84bd-d344172bd226.JPG)
Guest VLAN Range ends up on the storage brigde
![cloudstack8](https://user-images.githubusercontent.com/23615999/112659306-871aa700-8e54-11eb-9de4-2a8ee90f10a8.JPG)
all kvm taffic labels are gone and not valid from the input i made
![cloudstack9](https://user-images.githubusercontent.com/23615999/112659308-871aa700-8e54-11eb-9e24-401f12b08fe4.JPG)
Outcome to the first KVM host after the deployment. all traffic types located on cloudbr01

~~~
~~~

**Comment by mhoffmann21** [comment]
I can confirm that on my setup. Furthermore, there is a possible issue with the defined VLANs. If you specify VLANs, like shown in the pictures, those VLANs are not really considered in the later configuration. I've done the whole setup with the wizard and had to specify the traffic types again and also the VLANs for guest traffic and storage. Otherwise it did not work properly.

**Comment by DaanHoogland** [comment]
@mhoffmann21  @mkriegs , I changed the title to be more precise about the issue, hope you don't mind.

**Comment by DaanHoogland** [comment]
@mkriegs can you add texts to teh steps editting traffic labels? it seems now that you are changing the same label three times.

**Comment by mkriegs** [comment]
don't worry @DaanHoogland 
I edit the post, do not hesitate if something is not clear to you.

**Comment by rhtyd** [comment]
@utchoang can you check the zone deployment wizard against this issue, thanks. cc @davidjumani

**Comment by rhtyd** [comment]
https://github.com/apache/cloudstack/pull/4892
