### ISSUE TITLE
Inclusivity: Rename default git branch name from 'master' to 'main', and replace offensive words/terms as appropriate

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#4887]
## Background

The default git branch name 'master' was replaced with 'main' on GitHub [2][3] and in the wider Git community [4]. For those that have missed the broader discussion in society, the term 'master' is offensive to some people [1]. This is widely considered insensitive if not illegal, hence the proposed change.

[1] https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
[2] https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know
[3] https://github.com/github/renaming
[4] https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/

## Proposal

It seems fitting the CloudStack would follow this example of inclusiveness. For this, the project would rename its default branch name of all the repositories to 'main'. In addition, all the applicable integration points (Eg: Travis-CI, etc) using these repositories have to replace the branch name 'master' with 'main'.

The sample steps to rename and replace the default branch to 'main' are here: https://faun.pub/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b

#### Systems/Scripts integrated with Apache CloudStack repo

- Jenkins
- Travis CI
- Trillian
- cwiki
- Jira
- Git mirrors
- Other CloudStack Git repos
- Internal Documentation (internal readme/install docs/etc)
- External Documentation
- External CI systems ?
- Any third party tools ?

#### Impacted Systems/Scripts [Update ( 'master' to 'main') status]

- Jenkins          [NO]
- Travis CI        [NO]
- Trillian            [NO]
- cwiki              [NO]
- Git mirrors     [NO]
- Other CloudStack Git repos [NO]

##### ISSUE TYPE

 * Infra / Other

**Comment by rhtyd** [comment]
+1

**Comment by sureshanaparti** [comment]
CloudStack repos and respective PRs with inclusivity changes:

- https://github.com/apache/cloudstack =>  PR: https://github.com/apache/cloudstack/pull/4922
- https://github.com/apache/cloudstack-documentation =>  PR: https://github.com/apache/cloudstack-documentation/pull/155
- https://github.com/apache/cloudstack-cloudmonkey => PR: https://github.com/apache/cloudstack-cloudmonkey/pull/76
- https://github.com/apache/cloudstack-kubernetes-provider => PR: https://github.com/apache/cloudstack-kubernetes-provider/pull/29
- https://github.com/apache/cloudstack-ec2stack => PR: https://github.com/apache/cloudstack-ec2stack/pull/2
- https://github.com/apache/cloudstack-gcestack => PR: https://github.com/apache/cloudstack-gcestack/pull/3

**Comment by sureshanaparti** [comment]
ASF infra ticket: https://issues.apache.org/jira/browse/INFRA-21978 , to rename the default git branch name from 'master' to 'main'.

**Comment by sureshanaparti** [comment]
The default branch has been renamed to 'main' (from 'master'), Created health checks PR: https://github.com/apache/cloudstack/pull/5102

**Comment by rhtyd** [comment]
@sureshanaparti I think all PRs are done, issues addressed, should we close this?

**Comment by rhtyd** [comment]
Closing this, I reviewed looks like all tasks mentioned in the issue are complete.
