### ISSUE TITLE
Issue while running the simulator docker image 

### ISSUE THREAD

**Issue by srisgajare** [apache/cloudstack#4891]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Docker image - simulator
~~~

##### CLOUDSTACK VERSION

~~~
Master branch
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

After cloning the repo, building the docker image from scratch and running it, the UI doesn't show up and throws the following error:
"You're in developer mode, please build and run UI using npm." 

##### STEPS TO REPRODUCE

~~~
cd tools/docker 
docker build -f Dockerfile -t cloudstack/simulator ../..
docker run --name simulator -p 8080:8080 -d cloudstack/simulator
docker exec -ti simulator python \
/root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/basic.cfg
~~~

##### EXPECTED RESULTS

~~~
Cloudstack UI
~~~

##### ACTUAL RESULTS

~~~
On the web browser:

"You're in developer mode, please build and run UI using npm." 
~~~

**Comment by apurv-1** [comment]
Hello @srisgajare, can share some screenshots and show where exactly you're facing the issue?

**Comment by apurv-1** [comment]
@srisgajare After running the docker container.
Open another terminal and follow the steps:
1. `git clone https://github.com/apache/cloudstack.git`.
2. `cd cloudstack\ui` (If using windows).
3. then `npm install`.
4.  and finally, `npm serve`.
and also make sure to set `CS_URL=http://localhost:8080/client` on `.env.local file on ui`.
Hopefully, you'll be able to run the management server on http://localhost:5050

**Comment by nvazquez** [comment]
Hi @srisgajare can you confirm if @apurv-1's workaround fixes the issue?

**Comment by rhtyd** [comment]
This is not an issue @srisgajare you're supposed to run the UI separately as developer. How are you building the docker image, one solution is to also build the UI using npm and copy and replace the src as Apurv mentioned above.

**Comment by rhtyd** [comment]
@nvazquez @sureshanaparti @davidjumani @shwstppr @Pearl1594 @DaanHoogland @weizhouapache - any update on this, who's assigned/working on this? This however, may not be a high-priority task - but let's discuss and conclude on a resolution, thanks.
