### ISSUE TITLE
Eliminate *_details table inconsistency

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#4897]
Different details tables in cloud database have different structure. While some (specifically) allow inserting details with NULL value others do not. This creates issues when data needs to be copied from one to another, similar to #4628 

```
mysql> describe user_vm_details;
+---------+-----------------+------+-----+---------+----------------+
| Field   | Type            | Null | Key | Default | Extra          |
+---------+-----------------+------+-----+---------+----------------+
| id      | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| vm_id   | bigint unsigned | NO   | MUL | NULL    |                |
| name    | varchar(255)    | NO   |     | NULL    |                |
| value   | varchar(5120)   | YES  |     | NULL    |                |
| display | tinyint(1)      | NO   |     | 1       |                |
+---------+-----------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

mysql> describe vm_template_details;
+-------------+-----------------+------+-----+---------+----------------+
| Field       | Type            | Null | Key | Default | Extra          |
+-------------+-----------------+------+-----+---------+----------------+
| id          | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| template_id | bigint unsigned | NO   | MUL | NULL    |                |
| name        | varchar(255)    | NO   |     | NULL    |                |
| value       | varchar(1024)   | NO   |     | NULL    |                |
| display     | tinyint(1)      | NO   |     | 1       |                |
+-------------+-----------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```
To prevent such issues structure of these details table should be consistent and shouldn't accept details with NULL values.
Discussed in #4794

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
DB
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

As above

##### STEPS TO REPRODUCE

~~~
1. Deploy a VM
2. Add a VM detail with a null value
3. Create a template from ROOT disk of the VM
~~~

##### EXPECTED RESULTS

~~~
Template created successfully
~~~

##### ACTUAL RESULTS

~~~
Template creation fails
~~~

**Comment by shwstppr** [comment]
Following details table allow NULL values,
```
cloud.account_details
cloud.cluster_details
cloud.data_center_details
cloud.domain_details
cloud.image_store_details
cloud.storage_pool_details
cloud.template_deploy_as_is_details
cloud.user_vm_deploy_as_is_details
cloud.user_vm_details
```
Should we update/fix all of them? @DaanHoogland @sureshanaparti 
cc @rhtyd @nvazquez

**Comment by DaanHoogland** [comment]
I don't know if there is any <null> requirement for a detail in the system. In cases where details might be copied we will certainly have to allign tables (i.e. template > vm_instance) and I would prefer to be consistent system wide. I could imagine a usecase for null but let's deal when we get there.

**Comment by sureshanaparti** [comment]
> Following details table allow NULL values,
> 
> ```
> cloud.account_details
> cloud.cluster_details
> cloud.data_center_details
> cloud.domain_details
> cloud.image_store_details
> cloud.storage_pool_details
> cloud.template_deploy_as_is_details
> cloud.user_vm_deploy_as_is_details
> cloud.user_vm_details
> ```
> 
> Should we update/fix all of them? @DaanHoogland @sureshanaparti
> cc @rhtyd @nvazquez

@shwstppr @DaanHoogland I think, it is better to fix these tables to take non-null values for the keys.
Persisting only key without value (NULL, may be temporarily), can help to track/monitor something (with key existence), but it is not a good thing to do (can keep some status/value to it).

**Comment by DaanHoogland** [comment]
@sureshanaparti and others, that was what I was thinking about as well, I don't think this is good programming but it is common practice. I think we should use another mechanism for this, but this is not in scope for this issue.

**Comment by nvazquez** [comment]
I think we should fix the tables to accept non-null values unless there is any known feature/use case that persists a detail key without a value. @shwstppr could you observe any pushback on fixing these tables?

**Comment by weizhouapache** [comment]
@shwstppr do you have any update on this issue ?

**Comment by shwstppr** [comment]
@nvazquez sorry for missing your ping. Will have look next week cc @weizhouapache

**Comment by nvazquez** [comment]
Thanks @shwstppr your PR looks good. I'm not aware of any case in which a detail key with a null value is added

**Comment by nvazquez** [comment]
@shwstppr @DaanHoogland @andrijapanicsb adding to my previous comment: have found a case in which the details table for deploy-as-is details NULL value was needed. Please see: https://github.com/apache/cloudstack/issues/5747 - have posted a PR to revert only that table: https://github.com/apache/cloudstack/pull/5748

**Comment by sureshanaparti** [comment]
@nvazquez may be not good idea to keep the detail NULL again and this will break the *_details table consistency. Instead consider the 'deploy-as-is' detail as null when it doesn't exist, or use empty value instead of null.
