### ISSUE TITLE
Duplicate jar packages are installed under ubuntu

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#4906]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
INSTALL
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### OS / ENVIRONMENT

OS： ubuntu 20.04
deb:  cloudstack-agent_4.15.0.0~focal_all.deb

##### SUMMARY

After installing cloudstack-agent_4.15.0.0~focal_all.deb under UBUNTU 20.04, two "same" (same as md5) jar packages are found under /usr/share/cloudstack-agent/lib.

/usr/share/cloudstack-agent/lib
8038649400beafdbf1a32193a9331c8b  cloud-agent-4.15.0.0.jar
8038649400beafdbf1a32193a9331c8b  cloudstack-agent.jar

In CentOS 7, there is only one cloud-agent-4.15.0.0.jar, no cloudstack- agent.jar

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
cc @wido @weizhouapache @GabrielBrascher

**Comment by wido** [comment]
Are we sure this isn't a symlink?

@div8cn Can you post the output of:

<pre>
ls -al /usr/share/cloudstack-agent/lib
</pre>

**Comment by div8cn** [comment]
`root@TC-APP01CE:~# ls -al /usr/share/cloudstack-agent/lib/ |grep agent
-rwxr-xr-x 1 root root   92829 Jan 12 23:16 cloud-agent-4.15.0.0.jar
-rwxr-xr-x 1 root root    6666 Jan 12 23:16 cloud-framework-agent-lb-4.15.0.0.jar
-rwxr-xr-x 1 root root   92829 Jan 12 23:16 cloudstack-agent.jar
root@TC-APP01CE:~# 
`

**Comment by rhtyd** [comment]
I tested and confirmed issue as well, thanks @div8cn 
```
root@rpi-kvm1:/usr/share/cloudstack-agent/lib# ls -lahi *agent*
147762 -rwxr-xr-x 1 root root  91K Dec 23 16:32 cloud-agent-4.15.0.0.jar
147832 -rwxr-xr-x 1 root root 6.6K Dec 23 16:32 cloud-framework-agent-lb-4.15.0.0.jar
147852 -rwxr-xr-x 1 root root  91K Dec 23 16:32 cloudstack-agent.jar
root@rpi-kvm1:/usr/share/cloudstack-agent/lib# md5sum cloudstack-agent.jar cloud-agent-4.15.0.0.jar 
735fca2772cab00862c02a5c69f21fe0  cloudstack-agent.jar
735fca2772cab00862c02a5c69f21fe0  cloud-agent-4.15.0.0.jar

```

**Comment by rhtyd** [comment]
@div8cn can you help test https://github.com/apache/cloudstack/pull/4927

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4927
