### ISSUE TITLE
login fails with certain username formats

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#4908]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### SUMMARY

when configured the same, user d.h@bla.cc *can* login, but user dh@blob.cc *cannot* login. Note the dot in the username or not.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
both can logon
~~~

##### ACTUAL RESULTS

~~~
dh@blob.cc cannot logon.
~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4910
