### ISSUE TITLE
cloudstack4.15 new UI , security group egressrule and ingressrule mistake

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#4919]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI 
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### STEPS TO REPRODUCE

~~~
when i use the new UI, the security group show the wrong egressrule and ingressrule, in order to explan this mistake, i upload there images and show it

~~~
![image](https://user-images.githubusercontent.com/20500978/114664249-01d93280-9d2e-11eb-9729-e6191dc0bd57.png)
![image](https://user-images.githubusercontent.com/20500978/114664411-3d73fc80-9d2e-11eb-90ee-dc52936ac28b.png)

~~~

~~~

##### EXPECTED RESULTS

~~~
I want to show them in their respective configurations, like legacy UI
This is shown in the screenshot below
~~~
![image](https://user-images.githubusercontent.com/20500978/114664864-e6baf280-9d2e-11eb-9adb-dd1f12c4d41a.png)
![image](https://user-images.githubusercontent.com/20500978/114664869-eae71000-9d2e-11eb-97c3-f075dab16d6a.png)

##### ACTUAL RESULTS

~~~
 but when i see api result, egressrule have five result, and ingressrule just have three result
this look like the UI show wrong result.  egressrule and ingressrule becomes the same result
~~~

![image](https://user-images.githubusercontent.com/20500978/114664441-4795fb00-9d2e-11eb-9cc2-de8341867b1a.png)

**Comment by staySober** [comment]
in addition to this , this page add egressrule and ingressrule It doesn't seem to work, however i add the ingressrule, it always add egressrule. It  look like this page is not finish development.
thanks a lot

**Comment by utchoang** [comment]
Hi @staySober, I understood the problem. It arises due to a language error, I will fix it for now. Thanks.

**Comment by staySober** [comment]
thanks @utchoang

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4920
