### ISSUE TITLE
UI should not allow root disk size customization if Service Offering has a fixed size

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#4930]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15
4.16
master
~~~

##### CONFIGURATION
Service Offering with a fixed root disk size

<pre>
(2019)  > list serviceofferings filter=rootdisksize,name,id id=4250629b-5754-495c-be84-16c2cdfe481f
{
  "count": 1,
  "serviceoffering": [
    {
      "id": "4250629b-5754-495c-be84-16c2cdfe481f",
      "name": "HA 1G (Root 30GB)",
      "rootdisksize": 32212254720
    }
  ]
}
(2019)  >  
</pre>

##### SUMMARY
The UI shows a toggle to customize the root disk size upon deployment even though if the root disk size has been set to a fixed value under the service offering.

This toggle should be hidden when a offering is selected which does not allow for customization of the root disk size.

Above is the output of the API and below a screenshot of the UI.

This offering has a fixed size of 30GB.

We probably want an if-statement like (pseudo):

<pre>
allowRootDiskResize = True

if rootdisksize > 0:
  allowRootDiskResize = False
</pre>

<img width="2560" alt="Screenshot 2021-04-16 at 16 01 10" src="https://user-images.githubusercontent.com/326786/115036992-4e5b7400-9ece-11eb-8e29-7d4a648fe347.png">

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4933
