### ISSUE TITLE
New UI does not allow entering CPU speed when creating new instance

### ISSUE THREAD

**Issue by r9host** [apache/cloudstack#4932]
In the new UI came with 4.15, when create a new instance using a custom compute offering, it does not show CPU speed field to enter. As a result, when click on Launch button, it gives an error that cpu speed value is missing.

**Comment by Pearl1594** [comment]
@r9host I created a custom Unconstrained compute offering. During deployment of a VM, on choosing the custom compute offering I do see an input field for specifying the CPU Speed
![image](https://user-images.githubusercontent.com/10495417/115208416-29f3d780-a11a-11eb-9d9a-85f1432da3c5.png)
Please let us know if there's anything different to be done to reproduce the issue

**Comment by rhtyd** [comment]
@r9host can you test latest 4.15 and close it?

**Comment by rhtyd** [comment]
Closing, confirmed/tested myself.
