### ISSUE TITLE
UI: Missing "Scale VM" on Running VM - when VM is marked as Dynamically Scalable

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4939]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
NEW UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0 tested
~~~

When template is marked as Dynamically scalable, VM deployed from this template, also inherits (by copy) this setting and is marked as Dynamically scalable (and global and zone-level setting enable.dynamic.scale.vm=true) -  but when VM is running, there is no button to scale the VM (it's there if the VM is stopped)

![image](https://user-images.githubusercontent.com/45762285/115448127-9efa0680-a219-11eb-9b25-c934c015f01a.png)

I haven't found the same issue already raised, so raising this one.

**Comment by rhtyd** [comment]
@utchoang can you investigate this against the legacy UI? (and if the button should be shown) Thanks. cc @davidjumani @shwstppr @Pearl1594 @Spaceman1984

**Comment by utchoang** [comment]
@rhtyd @andrijapanicsb I checked with legacy UI then for hypervisor KVM it is not allowed to display the Scale VM button. Does this case have to show it for Dynamically scalable?
![image](https://user-images.githubusercontent.com/13766648/115655759-22bd0b80-a35e-11eb-8f3b-efcaf64aac07.png)

**Comment by Pearl1594** [comment]
KVM doesn't seem to support scaling of a running VM. Fails when you attempt scaling via cmk:
```
scale virtualmachine id=ff9a1108-2fb2-41a1-97c7-cb14904e560a serviceofferingid=38a065d4-4d97-40d4-a09a-19315ea910ef
{
  "accountid": "a2ead456-a0f6-11eb-a9ca-1e005700024a",
  "cmd": "org.apache.cloudstack.api.command.admin.vm.ScaleVMCmdByAdmin",
  "completed": "2021-04-22T04:44:46+0000",
  "created": "2021-04-22T04:44:46+0000",
  "jobid": "dfaadc99-3ba0-4afb-a4a6-8059b7d561fb",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 431,
    "errortext": "Scaling the VM dynamically is not supported for VMs running on Hypervisor KVM"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "a2ebeb3c-a0f6-11eb-a9ca-1e005700024a"
}
```

**Comment by rhtyd** [comment]
@andrijapanicsb pl check and close

**Comment by andrijapanicsb** [comment]
OK, I'm an idiot - I did a test on KVM, my apologies - on VMware env the button is there.

Sorry for wasting everyone's time 👎
