### ISSUE TITLE
vmware: configdrive ISO not attached to VM deployed with deployasis template

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#4941]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware hypervisor
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When a VM is deployed with a **deployasis** template for L2 network with config drive, the configdrive ISO is not attached to the VM.
For VM with older/non-deployasis templates, configdrive ISO is found attached.

##### STEPS TO REPRODUCE

~~~
1. Register a new template if there is no template other than default template or templates before upgrading to 4.15.0. This will register the template with deployasis as true.
2. Deploy a VM with the template.
3. On vCenter, check if CD/DVD drive is shown connected in the VM hardware. vCenter will show disconnected.
~~~

##### EXPECTED RESULTS

~~~
ISO is shown connected in the Center as  CD/DVD drive.
~~~

##### ACTUAL RESULTS

~~~
VM hardware show no CD/DVD drive
~~~
VM with template having deployasis as `false`. CD/DVD drive shown connected
![Screenshot from 2021-04-21 15-59-41-1](https://user-images.githubusercontent.com/153340/115541728-1af95a80-a2bd-11eb-9aee-6cb2029067ca.png)

![Screenshot from 2021-04-21 15-59-41-3](https://user-images.githubusercontent.com/153340/115543295-d8388200-a2be-11eb-8cae-1db01acd0a22.png)

VM with template having deployasis as `true`. CD/DVD drive shown as disconnected
![Screenshot from 2021-04-21 15-59-41-2](https://user-images.githubusercontent.com/153340/115541810-2d739400-a2bd-11eb-82c9-953653684612.png)

**Comment by rhtyd** [comment]
@nvazquez can you have a look at this? Related to deploy-as-is/vmware.

**Comment by nvazquez** [comment]
@rhtyd we've discussed this issue with @Pearl1594 and she'll provide a fix

**Comment by rhtyd** [comment]
cc @vladimirpetrov

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4907
