### ISSUE TITLE
UI: Domain !structure! not shown when creating accounts

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4947]
UI/Primate issue when creating Accounts - usability is scarce:

Domain structure:
![image](https://user-images.githubusercontent.com/45762285/116010946-63e54200-a622-11eb-807b-14f9d411c5d2.png)

How it appears (no structure - impossible to use):

![image](https://user-images.githubusercontent.com/45762285/116010909-36989400-a622-11eb-9e62-f85529a518a3.png)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4949 @andrijapanicsb please test and close.

**Comment by andrijapanicsb** [comment]
LGTM, nice/quick fix - closing.
