### ISSUE TITLE
ui: Simplify code

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#4956]
### Optional chaining
The optional chaining `?.` is a safe way to access nested object properties, even if an intermediate property doesn’t exist.
`(error.response && error.response.headers && error.response.headers['x-description']) || error.message`
using optional chaining it reduces to 
`error.response?.headers?.['x-description'] || error.message`

Ref : https://javascript.info/optional-chaining

This can also be used to invoke methods on objects, etc
This improves readability as well as simplifies the existing code

### Nullish coalescing

Nullish coalescing is an improvement on the || operator where it only checks if an object is null or undefined.
Using the || operator returns false if the object is zero or an empty string which can cause issues in the code when the value is zero but incorrectly treated as false

```
let height = 0;

alert(height || 100); // 100
alert(height ?? 100); // 0
```

Ref: https://javascript.info/nullish-coalescing-operator

### Object shorthand

Provides a simpler way when creating an object who's keys have the same name as the variables passed-in as properties
```
let cat = 'Miaow';
let dog = 'Woof';
let bird = 'Peet peet';

let someObject = {
  cat,
  dog,
  bird
}
```

Ref https://alligator.io/js/object-property-shorthand-es6/

##### ISSUE TYPE

 * Enhancement Request

**Comment by nvazquez** [comment]
Hi @davidjumani @utchoang - can you please confirm if PR #5167 which has been merged fixes this issue?

**Comment by davidjumani** [comment]
@nvazquez This is a code wide change, the PR only fixes it in one place

**Comment by nvazquez** [comment]
Thanks @davidjumani, please advise if/when there are more PRs about this issue. Perhaps we can also track them on the issue description using a task list

**Comment by Yashikaone** [comment]
Hello, I am Yashika Sarkar and I am new to open source but since ACS projects(2021) interests me I was going through the issues and I came across title **"Optioinal chainging**", I am not sure if it's an error but shouldn't it be optional chaining?
#4956
Thank you.

**Comment by rohityadavcloud** [comment]
cc @borisstoyanov

**Comment by Yashikaone** [comment]
@utchoang  Hello, I have come across certain lines of codes where optional chaining may be used . 
Please let me know if it is okay to modify them or not 
These are the screenshots-
![Screenshot (68)](https://user-images.githubusercontent.com/65132044/151562718-a99f7aed-cc35-43df-812f-73e414385822.png) last line
![Screenshot (69)](https://user-images.githubusercontent.com/65132044/151562961-0ff6d039-4b15-4c7b-8261-380d48e8ddea.png) first and last line
![Screenshot (70)](https://user-images.githubusercontent.com/65132044/151563143-b2c73066-44f0-4173-99ca-6617f6ca9dbb.png) fourth line

**Comment by utchoang** [comment]
@Yashikaone These sections may be subject to optional code.

**Comment by rohityadavcloud** [comment]
Looks like these have been fixed, if not pl re-reopen @davidjumani
