### ISSUE TITLE
Adding Firewall rule, returns user to Details tab instead of staying on Firewall tab

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4961]
Adding a firewall rule and pressing OK, will add the rule...

![image](https://user-images.githubusercontent.com/45762285/116317247-62974f00-a7b3-11eb-9c9a-df8baf17b043.png)

... but then you will be returned to the Details tab (the first tab), instead of staying on the Firewall tab as in old UI

![image](https://user-images.githubusercontent.com/45762285/116317337-83f83b00-a7b3-11eb-888e-83f1f65a965c.png)

**Comment by andrijapanicsb** [comment]
The same happens if you add Port Forwarding rule, etc - please make sure to test all tabs - this is a simple Isolated network (single Public IP labeled "Source NAT")

**Comment by andrijapanicsb** [comment]
The same goes for the Egress rules tab - when added, UI returns to the Details tab.

**Comment by rhtyd** [comment]
@andrijapanicsb please test and close; fixed in https://github.com/apache/cloudstack/pull/4962

**Comment by andrijapanicsb** [comment]
LGTM - thx guys.
