### ISSUE TITLE
SSVM/CPVM Agent stays UP after the systemVM is FORCED STOPPED

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4972]
4.15.0.0

Had SSVM and CPVM all (green/connected/up) - forced stopped them. Started them both again - during Starting the Agent is still showing as UP, while in reality the VMs have not yet booted (started) at all:

![image](https://user-images.githubusercontent.com/45762285/116530026-d9306b80-a8dd-11eb-9496-474946a5322b.png)

EDIT 05.05.2021:
Per @davidjumani, this is a backend bug - having the option to FORCE stop SSVM/CPVM is new in recent release - and needs backedn fix to mark agents as Down or sometghing.

**Comment by rhtyd** [comment]
I think we use API to show that - @andrijapanicsb can you repeat the test against the legacy UI (4.15 has legacy UI) - what do you see in the legacy UI?
cc @utchoang @davidjumani can you investigate if there's a default option we use/show in the UI when some key in the API is returned - i.e. investigate if this is a UI bug or backend bug?

Thanks.

**Comment by davidjumani** [comment]
@andrijapanicsb @rhtyd Looks like a backend issue

![Screenshot from 2021-04-30 10-32-34](https://user-images.githubusercontent.com/8244774/116650778-87e8b080-a99f-11eb-884b-3b7710a7ab89.png)

**Comment by andrijapanicsb** [comment]
@davidjumani your latest screenshot doesn't say if this v-67-VM is a brand new one (and I don't see an issue on that screenshot)
or if you have actually reproduced the issue I reported (well, I don't see green dot):
- force stop SSVM/CPVM
- start it - and observe while status is Starting, it's still showing as UP (click refresh a few times, and the status is still Starting / Up)

I will report how it is in the old UI soon.

thx

**Comment by andrijapanicsb** [comment]
Tested 4.15.0.0 on "legacy? UI - there is NO FORCE STOP button, just the regular stop button - and this does change state to Disconnected - so there is no parallel to test in legacy UI. (short demo on legacy UI: http://somup.com/crhnlBF4hR)

i.e. we do NOT have a regression vs te legacy, but this new feature (FORCE stop systemVM) is not behaving "friendly" - or we can argue it is - as force stop is forced, there is no shutdown agent (which would send the disconnect agent command etc):

Short video on STOP vs FORCE STOP behaviour: http://somup.com/crhnl5F41j

I can live with this, as I'm sure the this is both 1) not critical and 2) the state would change to Disconnected eventually, but since ACS will start VM on it's own (unless zone is disabled) we never live to see this Disconnected take place.


@rhtyd @davidjumani  - up to you - feel free to close the ticket, as this seems like a backend improvement needed (update the DB as "Down" on FORCE stop SSVM/CPVM)

**Comment by davidjumani** [comment]
@andrijapanicsb Sounds like a backend fix. Can you change the title and I can look into creating a fix for it

**Comment by andrijapanicsb** [comment]
all yours @davidjumani 

thx

**Comment by weizhouapache** [comment]
When SSVM/CPVM are force-stopped, the agent in systemvms will not inform management server.
It would be good if agent state is changed to Status.Disconnected, Down or Unknown, when systemvms are force-stopped

**Comment by rhtyd** [comment]
Fixed in #5010
@andrijapanicsb pl reopen after testing if not fixed. Tested by @shwstppr and @weizhouapache on the PR

**Comment by andrijapanicsb** [comment]
👍
