### ISSUE TITLE
UI: ACL "reason" --> "description"    , label improvement

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4973]
Adding a new ACL on the ACL list

If others agree, can we rename "reason" which sounds interrogative (and wrong) to "description"?

![image](https://user-images.githubusercontent.com/45762285/116531776-d33b8a00-a8df-11eb-9bb6-44aeea274799.png)

**Comment by rhtyd** [comment]
cc @utchoang can you check if it's a translation/key issue - and if anything we can do.

**Comment by davidjumani** [comment]
@andrijapanicsb @rhtyd It's set as reason in the API cmd as well https://github.com/apache/cloudstack/blob/master/api/src/main/java/org/apache/cloudstack/api/command/user/network/CreateNetworkACLCmd.java#L90

I'm a +1 for updating in both backend and frontend for consistency, not just the UI

**Comment by rhtyd** [comment]
well, we cannot update the backend API key (breaks compatibility) - let's fix the translation key instead. (check if label.reason is used elsewhere)

**Comment by shwstppr** [comment]
`label.reason` is used only in `ui/src/views/network/AclListRulesTab.vue`

**Comment by davidjumani** [comment]
Will raise a PR to change it then

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4980
