### ISSUE TITLE
UI: Port Forwarding form - ports are NULL-ed after canceling chossing Tier/VM.

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4974]
When adding a Port Forwarding rule on Public IP of a VPC, enter private/public port, click ADD to chose Tier and the VM - but then click back/close the VM/Tier-choosing pop-up - the private/public ports fields are deleted.

For comparison, when doing the same on Load Balancing - the fields are not NULL-ed, the entered values for ports still stay as filled in previously.

Short video for simplicity of explanation:

http://somup.com/crfU6ZFUEZ

**Comment by rhtyd** [comment]
cc @shwstppr @davidjumani @Spaceman1984 @Pearl1594

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4981
