### ISSUE TITLE
UI: Refresh button on domains, does not refresh domain structure, just the selected domain details

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4975]
![image](https://user-images.githubusercontent.com/45762285/116553650-a5177380-a8fa-11eb-9908-7f3a4cf98d62.png)

Created domain marvel

Clicking on the Refresh button (as on the image above), does not show the domain.
I have to click on another menu item (i.e. Infrastructure), then go back to DOMAINS manu itme, expand the ROOT domain, and only then see the new domain added:

![image](https://user-images.githubusercontent.com/45762285/116553788-ca0be680-a8fa-11eb-970b-af5be301166f.png)

**Comment by rhtyd** [comment]
cc @utchoang can you please check? Thanks

**Comment by rhtyd** [comment]
cc @shwstppr @davidjumani @Spaceman1984 @Pearl1594

**Comment by rhtyd** [comment]
cc @shwstppr @davidjumani @Spaceman1984 @Pearl1594 @utchoang

**Comment by utchoang** [comment]
@andrijapanicsb cc @rhtyd I tried to reproduce the issue locally, but I didn't get the same mistake.
Could you please show me the browser console if possible?
![bandicam 2021-05-04 07-50-48-656](https://user-images.githubusercontent.com/13766648/116950062-26ca2100-acae-11eb-9ef9-fbad48a87c18.gif)

**Comment by andrijapanicsb** [comment]
@utchoang - my appologies for not completely explaining - the domain "marvel" shown in my example, was created by CloudMOnkey, not via UI - then while the ROOT is already expanded, clicking the refresh button or expand/collapse button did not show it....

I can also confirm UI addition works fine, as per your screenshare.

**Comment by rhtyd** [comment]
@andrijapanicsb can you close the ticket if it's a non-issue then?

**Comment by andrijapanicsb** [comment]
Unless I'm wrong, it is an issue? Shouldn't the domain created via Cmk appear when hitting the refresh button in UI?

**Comment by utchoang** [comment]
@andrijapanicsb It's an issue of where the domain was created from cmd, another client, database,.... I'll take care of it. cc @rhtyd

**Comment by andrijapanicsb** [comment]
fixed by #4999
