### ISSUE TITLE
UI: Compute(VR) offering field not automtically shown when creating network with VR as service provider

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4983]
4.15.0.0 UI, but same bug still present in one of the latest UI PRs:

When creating a Isolated Network offering, and choosing i.e. DHCP, DNS etc - VR is chosen as default as the Service Provider for those services - but the compute/service offering for VR is NOT automatically shown - it's only shown once you switch from VR to i.e. GloboDNS, then back to VR - see short video for explanation: 
http://somup.com/crhnXkF4fo

The compute/service offering for a VR should be automatically shown (and this seems like a regression from the old UI) when any service is selected by default that has VR providing at leat once service

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4988
