### ISSUE TITLE
UI: No notifications/confirmation shown after creating a domain

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4984]
When creating a new domain (under ROOT domain, but seems same under any other subdomain of the ROOT domain) - there is no confirmation/popup/notifications shown to confirm domain was created successfully

Short 30sec video:

http://somup.com/crhnXsF4fz

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4987
