### ISSUE TITLE
UI: VPC offering with external LB shown AGAIN when creating a second network

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4985]
A VPC can have only a single network tier using the (default) network offering with the public LB (HaProxy inside the VR).

When creating a second network in the same VPC, this offering was NOT available (the one with public LB) in the legacy UI - but it is still offered in the new UI (and it even works, but later will cause issues to users) - see the video for comparison:

http://somup.com/crhnlLF41U

**Comment by andrijapanicsb** [comment]
Here's also a screnshot (after a single network has been already created using the offering with public/external LB)

Old UI (doesn't offer the Offering, since there is 1 network already using it)

![image](https://user-images.githubusercontent.com/45762285/116813934-ac3abd80-ab56-11eb-9963-c1d190d58e48.png)


New UI (still offering the Offering, even though 1 network is already using it)

![image](https://user-images.githubusercontent.com/45762285/116813969-cd9ba980-ab56-11eb-8099-98dd21df5cd0.png)

**Comment by rhtyd** [comment]
cc @shwstppr @davidjumani @Spaceman1984 @Pearl1594 @utchoang

**Comment by Pearl1594** [comment]
looking into it @rhtyd

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/4989
