### ISSUE TITLE
Unable to create Basic Zone

### ISSUE THREAD

**Issue by cbr46** [apache/cloudstack#4992]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

UI

##### CLOUDSTACK VERSION

4.15

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 8.3

##### SUMMARY

When trying to add a new zone, only Advanced Zones can be created. 
There is no option for creating Basic Zones.
Yet the documention mentions it: http://docs.cloudstack.apache.org/en/latest/installguide/configuration.html#adding-a-zone

##### STEPS TO REPRODUCE

Login to Management Server GUI -> Infrastructure -> Zones -> Add Zone

##### EXPECTED RESULTS

Option to create a new zone with basic network configuration is visible

##### ACTUAL RESULTS

Basic option is missing
![Screenshot 2021-05-04 094852](https://user-images.githubusercontent.com/18323184/116974177-f9856f00-acbd-11eb-8b44-152c516e16e4.jpg)

**Comment by rhtyd** [comment]
@cbr46 pl use the legacy UI for 4.15.0.0 for creating zone, we've fixed this in 4.15.1.0.
