### ISSUE TITLE
Duplicate query string parameters

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#5007]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

API

##### CLOUDSTACK VERSION
4.15+ (Maybe below)

##### SUMMARY

When duplicate query parameters are passed with the same key but different values, ACS parses only the last occurrence.
Eg: keyword=rick&keyword=basic
It returns values matching basic

##### EXPECTED RESULTS

A possible error thrown for duplicate query params

##### ACTUAL RESULTS

http://primate-qa.cloudstack.cloud:8080/client/api/?listall=true&response=json&command=listVirtualMachines&details=min&keyword=rick&keyword=basic

Returns the VMs with name basic

http://primate-qa.cloudstack.cloud:8080/client/api/?listall=true&response=json&command=listVirtualMachines&details=min&keyword=basic&keyword=rick

Returns the VMs with name rick

**Comment by DaanHoogland** [comment]
The API server is not changed the last few releases so let's get this fixed in the oldest supported LTS branch. (i Think that is 4.14 atm.

**Comment by davidjumani** [comment]
@rhtyd Lists are handled differently. ACS explicitly overrides multiple values and only accepts one https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/api/ApiServer.java#L568
