### ISSUE TITLE
Invalid parameter ostypeid, not applicable for VMware

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#5031]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

VMWare

##### SUMMARY
OVA template cannot be uploaded when the 'Read VM settings from OVA' option is disabled.

##### STEPS TO REPRODUCE

~~~
Try to upload an OVA template with 'Read VM settings from OVA' disabled.
~~~

##### EXPECTED RESULTS

~~~
The template should be uploaded successfully.
~~~

##### ACTUAL RESULTS

~~~
The following error message pops when trying to upload a template without reading the VM settings from OVA:
Invalid parameter ostypeid, not applicable for VMware
~~~
![image](https://user-images.githubusercontent.com/12384665/118840298-f13d4e80-b8cf-11eb-8bf7-dcabb40342cf.png)

**Comment by vladimirpetrov** [comment]
Fixed by #5033, LGTM.

**Comment by vladimirpetrov** [comment]
Reopening the issue until the PR is merged ...

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5033
