### ISSUE TITLE
UI: Introduction to Dark mode with toggle Button on Management Server.

### ISSUE THREAD

**Issue by apurv-1** [apache/cloudstack#5042]
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1.0 (LTS)
~~~

##### SUMMARY

The current new UI looks great and looks clean, but It would be a cherry on the cake if we can add an option to toggle between the Light mode and Dark mode. 
I'm sure there are many users/developers who use Management Server UI during Night or in dark environment conditions, hence the dark UI can be helpful in order to reduce the screen strain on the eyes.

**Comment by rhtyd** [comment]
We can't support for lower/older CloudStack versions. I think latest Ant Design vue supports a real-dark mode. cc @utchoang - if you want to explore that.

**Comment by apurv-1** [comment]
I would also like to contribute and explore this after completion of the tasks via GSoC.

**Comment by rhtyd** [comment]
Thanks @apurv-1 looks like the improvement request has been handled in https://github.com/apache/cloudstack/pull/5052 please help review/test it on the PR.

**Comment by apurv-1** [comment]
> Thanks @apurv-1 looks like the improvement request has been handled in #5052 please help review/test it on the PR.

Yeah sure, will test and update you soon on this!
