### ISSUE TITLE
/etc/init.d/networking: not found

### ISSUE THREAD

**Issue by sweetdom69** [apache/cloudstack#5044]
##### SUMMARY
I try to setup a kvm host on ubuntu 20.04 but the agent gives me an error execute:/bin/sh: 1: /etc/init.d/networking: not found, its true that its missing since its 20.04

DEBUG:root:execute:uname -r
DEBUG:root:execute:uname -m
DEBUG:root:execute:hostname -f
DEBUG:root:execute:kvm-ok
DEBUG:root:execute:service apparmor status
DEBUG:root:execute:apparmor_status |grep libvirt
DEBUG:root:execute:ln -s /etc/apparmor.d/usr.sbin.libvirtd /etc/apparmor.d/disable/
DEBUG:root:execute:ln -s /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper /etc/apparmor.d/disable/
DEBUG:root:execute:apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
DEBUG:root:execute:apparmor_parser -R /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
DEBUG:root:Vlan is not a network device, is it down?
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:route -n|awk '/^0.0.0.0/ {print $2,$8}'
DEBUG:root:execute:ifconfig cloudbr0
DEBUG:root:Found default network device:cloudbr0
DEBUG:root:execute:ifconfig bond0
DEBUG:root:execute:sudo update-rc.d -f apparmor remove
DEBUG:root:execute:sudo update-rc.d -f apparmor defaults
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start
DEBUG:root:execute:sudo update-rc.d -f network-manager remove
DEBUG:root:execute:sudo update-rc.d -f network-manager defaults
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:sudo /usr/sbin/service network-manager start
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:sudo /usr/sbin/service network-manager start
DEBUG:root:execute:/etc/init.d/networking stop
DEBUG:root:Failed to execute:/bin/sh: 1: /etc/init.d/networking: not found
DEBUG:root:execute:/etc/init.d/networking start
DEBUG:root:Failed to execute:/bin/sh: 1: /etc/init.d/networking: not found
DEBUG:root:execute:uname -r
DEBUG:root:execute:uname -m
DEBUG:root:execute:hostname -f
DEBUG:root:execute:kvm-ok
DEBUG:root:execute:service apparmor status
DEBUG:root:execute:apparmor_status |grep libvirt
DEBUG:root:Failed to execute:
DEBUG:root:Vlan is not a network device, is it down?
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:route -n|awk '/^0.0.0.0/ {print $2,$8}'
DEBUG:root:execute:ifconfig cloudbr0
DEBUG:root:Found default network device:cloudbr0
DEBUG:root:execute:ifconfig bond0
DEBUG:root:execute:sudo update-rc.d -f apparmor remove
DEBUG:root:execute:sudo update-rc.d -f apparmor defaults
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start
DEBUG:root:execute:sudo update-rc.d -f network-manager remove
DEBUG:root:execute:sudo update-rc.d -f network-manager defaults
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:sudo /usr/sbin/service network-manager start
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:execute:sudo /usr/sbin/service network-manager start
DEBUG:root:execute:/etc/init.d/networking stop
DEBUG:root:Failed to execute:/bin/sh: 1: /etc/init.d/networking: not found
DEBUG:root:execute:/etc/init.d/networking start
DEBUG:root:Failed to execute:/bin/sh: 1: /etc/init.d/networking: not found

**Comment by shwstppr** [comment]
@sweetdom69 Ubuntu 20.04 support for KVM host is available only for ACS 4.15+

**Comment by sweetdom69** [comment]
I am sorry to bug you guys but you are right I must have used an older repo on the host machines
