### ISSUE TITLE
new UI 4.15 branch network/guest networks show zone incorrectly

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5065]
##### ISSUE TYPE

 * Bug Report
 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
front UI 4.15
backend 4.15.1-SNAPSHOT
~~~

##### STEPS TO REPRODUCE

![image](https://user-images.githubusercontent.com/20500978/120458639-0636d900-c3ca-11eb-9f0e-de866b326b49.png)
![image](https://user-images.githubusercontent.com/20500978/120458839-354d4a80-c3ca-11eb-96ed-3f1785ff986a.png)
![image](https://user-images.githubusercontent.com/20500978/120458881-3da58580-c3ca-11eb-96b7-4186bd1440e6.png)

##### EXPECTED RESULTS

~~~
 zone display correctly
~~~

##### ACTUAL RESULTS

~~~
the zone display incorrectly
~~~

**Comment by shwstppr** [comment]
@staySober Your zone is of basic network type, L2 network not allowed there

**Comment by staySober** [comment]
@shwstppr oh, guy, thanks. my problem.
