### ISSUE TITLE
Please add UI integration for syncStoragePool api-call

### ISSUE THREAD

**Issue by mib1185** [apache/cloudstack#5086]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1.0-rc
~~~

##### SUMMARY

For newly added api call `syncStoragePool` from #4871 (which works great 👍 ), a simple "Sync" button in UI to trigger storaepool synchronization for selected primary storage would be very desirable.

##### STEPS TO REPRODUCE

~~~
- Added datastore cluster with two child datastores as a primary storage pool into CloudStack
- Take out one child datastore from datastore cluster on vCenter
- trigger storaepool synchronization
~~~

##### EXPECTED RESULTS

~~~
storaepool synchronization can be triggered via UI
~~~

##### ACTUAL RESULTS

~~~
storaepool synchronization can only be triggered via api-call
~~~

**Comment by rhtyd** [comment]
@harikrishna-patnala can you check if it's available, any reason we shouldn't support it in the UI?

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5098
