### ISSUE TITLE
UI: 4.15.1 RC1 - deploy VM instance UI automatically scrolls down...

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5087]
* Bug Report

15sec video
http://somup.com/cr1j35qxiP

Has to be fixed for RC2

**Comment by rhtyd** [comment]
@Pearl1594 @shwstppr are you able to reproduce it?

**Comment by Pearl1594** [comment]
Yes @rhtyd it is reproducible.

**Comment by rhtyd** [comment]
Thanks @Pearl1594 if the fix is straightforward pl go ahead.

**Comment by shwstppr** [comment]
@Pearl1594 @rhtyd not sure if changes in #5089 are the best way to fix the focus problem but the issue not reproducible with them.
@utchoang can you please have a look

**Comment by rhtyd** [comment]
Fixed by https://github.com/apache/cloudstack/pull/5089 tested with a mobile and ipad/HD screen sizes.

**Comment by rhtyd** [comment]
@andrijapanicsb the issue seems to happen only on smaller screens, pl test the fix and re-open if you're not satisfied. Thanks.

**Comment by andrijapanicsb** [comment]
@blueorangutan package

**Comment by andrijapanicsb** [comment]
thx, will be testing the RPMs (btw, I'm on laptop/external display with fullHD+ of quadHD resolution, so not so small...)

**Comment by andrijapanicsb** [comment]
LGTM as well, thx.
