### ISSUE TITLE
UI: 404 after temlate deletion

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5092]
##### ISSUE TYPE
 * Bug Report

http://somup.com/cr1QXaqx8j

**Comment by Pearl1594** [comment]
@andrijapanicsb I am unable to reproduce the issue, can you please clear the cache (dev tools -> Storage) and then try the operation. Thanks

**Comment by andrijapanicsb** [comment]
nah, another package was built on top of older/not updated branch - all good in RC1, sorry

**Comment by shwstppr** [comment]
@andrijapanicsb @Pearl1594 to reproduce this you have:

1. Go to the template and copy the link
2. Logout from the server
3. Open the copied link, login with redirection
4. Now delete the template

Currently, 404 happens in UI when you log-in and delete something after redirection. I was trying to fix this but couldn't (Vue router not giving depth of routes or previous route).

Sorry if this wasn't the reported issue :-D

**Comment by andrijapanicsb** [comment]
Well, I don't get the 404 (when normally logged in) with 4.15.1 RC1 version, so I assume there is no issue. 🤷‍♂️
