### ISSUE TITLE
Upgrade to Vue3 library

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#5093]
Vue3 has been released and looks to be relatively stable, we should explore migrating the UI codebase to Vue3 (https://v3.vuejs.org/guide/migration/introduction.html) and latest AntD library.

**Comment by nvazquez** [comment]
Hi @utchoang I've noticed you are working on this issue. Do you think it can be completed in the 4.16 milestone?

**Comment by utchoang** [comment]
@nvazquez It won't complete in the 4.16 milestone because it needs to change the source code a lot. Currently, I think it's only 60-70% complete. Thanks.

**Comment by rhtyd** [comment]
Thanks @utchoang can you give us update on this issue or the PR - what is the scope of change expected? I hope you're not ending up rewriting a whole lot of UI :)

**Comment by utchoang** [comment]
@rhtyd Upon investigation and implementation, I note a few points that are worth considering:
1. The support to migrate from v2 to v3 of Vue3 is not sufficient (https://v3.vuejs.org/guide/migration/migration-build.html#upgrade-workflow)
2. The source code of ant-design-vue 2x is completely different from that of 1x although the UI still stays the same, which can be seen from form, slots, and events, etc. (https://2x.antdv.com/docs/vue/migration-v2)
3. Additionally, the unit tests also need to be re-written to match the new libraries as the old source code no longer fits.

**Comment by rohityadavcloud** [comment]
Closing this as we've have a PR.
