### ISSUE TITLE
UI: "Read settings from OVA" is shown before Format=OVA is selected.

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5107]
* Enhancement Request / Bug

Minor enhancement with VMware/OVA format - to actually make sense...

When hypervisor is chosen - the filed "format" is still NOT populated (OK, fine), but there is by default the "Read settings from OVA" slider available - this should also be hidden until the Format=OVA is selected (seems like the correct solution - because in future we might support other formats as well)
OR
If we keep the default to show "Read setting from OVA" after the hypervisor=VMware is selected, then let's also populated automatically the format=OVA when "Read settings from OVA" is checked - short video:

http://somup.com/cr12FxqgmO

**Comment by rhtyd** [comment]
@nvazquez can you explore if it's a quick UI fix?

**Comment by andrijapanicsb** [comment]
Fixed, thanks.
