### ISSUE TITLE
about provisioning type question

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5116]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
disk provisioningtype 
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### QUESTION

~~~
Excuse me, I have two question for your team.
1. I want to know the provisioning type used to create volumes. Valid values are thin, sparse, fat.
what are the differences between these three types of  provisioning. 

2. There are three types of configuration in VMware.  thick provision, thin Provision, and thick lazy Provision.
what is the relationship between disk provisioning types in CloudStack and those in VMware

thanks a lot.
~~~

**Comment by rhtyd** [comment]
@staySober we've an upcoming PR for 4.16 (https://github.com/apache/cloudstack/pull/4640) that will fix this, docs related to the PR is here - https://github.com/apache/cloudstack-documentation/pull/217/files which will make it clear.

Unless you're reporting a bug, kindly ask questions on the users or dev ML - https://cloudstack.apache.org/mailing-lists.html Thanks.

**Comment by staySober** [comment]
Thanks.  I get it
