### ISSUE TITLE
virtual machine name change does not update DNS

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5120]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

When the virtual machine host name is updated online, the VR is not updated, causing the internal resolution of the same VR VM to fail

##### STEPS TO REPRODUCE

~~~

1. Create an isolated network, name=test-network
2. Create two VMs and mount them on test-network (vm name: test-name01, test-name02)
3. Login  vm test-name02, ping test-name01 successful
4. Change the name of vm test-name01 to test-name11 for cloudstack api updatevirtualmachine


~~~

##### EXPECTED RESULTS

~~~
ping test-name11 successful
ping test-name01  failed
~~~

##### ACTUAL RESULTS

~~~
ping test-name11, failed
ping test-name01 successful
~~~

**Comment by rhtyd** [comment]
This is expected @div8cn did you stop and start the VM, and changed the name of the VM using CloudStack UI/API?

**Comment by div8cn** [comment]
@rhtyd 
I did not stop or restart the virtual machine;
I know that dns will be updated at restart or start;

**Comment by rhtyd** [comment]
Okay what you're asking is not a supported feature, so it's not a bug but maybe a new feature you're asking.

**Comment by luhaijiao** [comment]
yes, it's user experience improvement.  User would expect the new hostname can be reachable by ping  without rebooting the VM.
