### ISSUE TITLE
UI: Quick view option is not available for newly create resources

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#5126]
It's slightly annoying when a new VM or systemvm/VR is started, the quick view options may not be available:

![Screenshot from 2021-06-17 23-18-05](https://user-images.githubusercontent.com/95203/122448515-73e62600-cfc2-11eb-879a-ccabd27603ee.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

**Comment by utchoang** [comment]
@rhtyd cc @davidjumani  I tried creating a new zone and checking the system VM but the Quick view still shows up. Can you specify how to reproduce the error?

**Comment by davidjumani** [comment]
@utchoang Try to deploy a zone and open the systemvms tab, at that point when the VM is starting it'll have no quickview, and after refreshing a couple of times the vms will come up but the quickview will still not appear

**Comment by rhtyd** [comment]
Merged in https://github.com/apache/cloudstack/pull/5137
