### ISSUE TITLE
UI. Cannot display VM PASSWORD for Reinstall VM

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5127]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
4.15.1.0
~~~

##### SUMMARY

After executing the Reinstall VM operation through the UI, the new password of the VM will not be displayed

Note: 
1. The template used by the VM has enabled password
2. There is a new VM password in queryasyncjobresultresponse

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
fixed by #5129
