### ISSUE TITLE
Opening web console after enable ssl is very slow

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5134]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CPVM
noVNC
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

After ACS enables SSL, the process of opening webconsole(cpvm) is very slow.
After opening the debug mode on chrome, you see
load https://console.**********.com/client/console?cmd=access, it takes 97ms
load https://console.**********.com/resource/noVNC/vnc.html, it takes 15-20s

After disabled ssl, the whole process of opening the web console(cpvm) only takes 3-5 seconds

**The following log comes from management.log**
`2021-06-17 09:09:31,255 DEBUG [c.c.a.t.Request] (qtp18242360-2819:null) (logid:) Seq 18-5961921481708430491: Sending  { Cmd , MgmtId: 10000000001, via: 18(nodea), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.GetVncPortCommand":{"id":"564","name":"i-2-564-VM","wait":"0"}}] }`
`2021-06-17 09:09:31,260 DEBUG [c.c.a.t.Request] (AgentManager-Handler-10:null) (logid:) Seq 18-5961921481708430491: Processing:  { Ans: , MgmtId: 10000000001, via: 18, Ver: v1, Flags: 10, [{"com.cloud.agent.api.GetVncPortAnswer":{"address":"10.226.18.128","port":"5915","result":"true","wait":"0"}}] }`
`2021-06-17 09:09:31,260 DEBUG [c.c.a.t.Request] (qtp18242360-2819:null) (logid:) Seq 18-5961921481708430491: Received:  { Ans: , MgmtId: 10000000001, via: 18(nodea), Ver: v1, Flags: 10, { GetVncPortAnswer } }`
`2021-06-17 09:09:31,260 DEBUG [c.c.s.ConsoleProxyServlet] (qtp18242360-2819:null) (logid:) Port info 10.226.18.128`
`2021-06-17 09:09:31,260 INFO  [c.c.s.ConsoleProxyServlet] (qtp18242360-2819:null) (logid:) Parse host info returned from executing GetVNCPortCommand. host info: 10.226.18.128`
`2021-06-17 09:09:31,264 DEBUG [c.c.s.ConsoleProxyServlet] (qtp18242360-2819:null) (logid:) Compose console url: https://uatconsole.rynnova.com/resource/noVNC/vnc.html?port=8080&token=gHmHcv2ODYXJNTITdRW8Q4CIMwAWguW9TGrXFLtTRBIF-peI3StsbYymAhDQdYnZFo6sfhlXgMTyHq5NFTlbpzq2yQG87gxIIY06-PematanJEoO3URBUKhGJqNw_YwfTar2J21ewoPwXsvsXya28iK4KtaOJgOpJsl29dXotpmmIVyRMmzw-LI20OQQnA8JI5wVNn5LJWfvxOKT1SK_Xj9JMGSovOGD3MVTRxYNxr0f4mml29tiOkk5b8gH9-05C2oJkNiqiCP9QM8IvKBSGN9AMAEPPfc0wqmFZZ8B6ik`
`2021-06-17 09:09:31,264 DEBUG [c.c.s.ConsoleProxyServlet] (qtp18242360-2819:null) (logid:) the console url is :: <html><title>gumd-deploy-03</title><frameset><frame src="https://uatconsole.rynnova.com/resource/noVNC/vnc.html?port=8080&token=gHmHcv2ODYXJNTITdRW8Q4CIMwAWguW9TGrXFLtTRBIF-peI3StsbYymAhDQdYnZFo6sfhlXgMTyHq5NFTlbpzq2yQG87gxIIY06-PematanJEoO3URBUKhGJqNw_YwfTar2J21ewoPwXsvsXya28iK4KtaOJgOpJsl29dXotpmmIVyRMmzw-LI20OQQnA8JI5wVNn5LJWfvxOKT1SK_Xj9JMGSovOGD3MVTRxYNxr0f4mml29tiOkk5b8gH9-05C2oJkNiqiCP9QM8IvKBSGN9AMAEPPfc0wqmFZZ8B6ik"></frame></frameset></html>`
`2021-06-17 09:09:33,231 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-15:null) (logid:) SeqA 50-32489: Processing Seq 50-32489:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`
`2021-06-17 09:09:38,272 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-11:null) (logid:) SeqA 50-32490: Processing Seq 50-32490:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`
`2021-06-17 09:09:42,643 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-bf6faf78) (logid:4c43f504) Zone 1 is ready to launch console proxy`
`2021-06-17 09:09:48,232 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-2:null) (logid:) SeqA 50-32491: Processing Seq 50-32491:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`
`2021-06-17 09:09:53,233 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-11:null) (logid:) SeqA 50-32492: Processing Seq 50-32492:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`
`2021-06-17 09:10:00,421 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-14:null) (logid:) SeqA 50-32493: Processing Seq 50-32493:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleAccessAuthenticationCommand":{"_host":"10.226.18.128","_port":"5915","_vmId":"9b1c7594-87b8-40b3-9c6f-27fecf82cbf8","_sid":"_0OFFvwNq_zDbqCzAKDyYA","_ticket":"FOZNqg57cH4PKNUZ/LmDQWSI3zo=","_isReauthenticating":"false","wait":"0"}}] }`
`2021-06-17 09:10:00,421 DEBUG [c.c.c.AgentHookBase] (AgentManager-Handler-14:null) (logid:) Console authentication. Ticket in url for 10.226.18.128:5915-9b1c7594-87b8-40b3-9c6f-27fecf82cbf8 is FOZNqg57cH4PKNUZ/LmDQWSI3zo=`
`2021-06-17 09:10:00,421 DEBUG [c.c.c.AgentHookBase] (AgentManager-Handler-14:null) (logid:) Console authentication. Ticket in 1 minute boundary for 10.226.18.128:5915-9b1c7594-87b8-40b3-9c6f-27fecf82cbf8 is urstYk3iP2DPTafnCdWn92vfzrw=`
`2021-06-17 09:10:00,421 DEBUG [c.c.c.AgentHookBase] (AgentManager-Handler-14:null) (logid:) Console authentication. Ticket in 2-minute boundary for 10.226.18.128:5915-9b1c7594-87b8-40b3-9c6f-27fecf82cbf8 is FOZNqg57cH4PKNUZ/LmDQWSI3zo=`
`2021-06-17 09:10:00,425 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-14:null) (logid:) SeqA 50-32493: Sending Seq 50-32493:  { Ans: , MgmtId: 10000000001, via: 50, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.ConsoleAccessAuthenticationAnswer":{"_success":"true","_isReauthenticating":"false","_port":"0","result":"true","wait":"0"}}] }`
`2021-06-17 09:10:00,428 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-6:null) (logid:) SeqA 50-32494: Processing Seq 50-32494:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`
`2021-06-17 09:10:03,233 DEBUG [c.c.a.m.AgentManagerImpl] (AgentManager-Handler-7:null) (logid:) SeqA 50-32495: Processing Seq 50-32495:  { Cmd , MgmtId: -1, via: 50, Ver: v1, Flags: 11, [{"com.cloud.agent.api.ConsoleProxyLoadReportCommand":{"_proxyVmId":"704","_loadInfo":"{`

**The following log is from CPVM cloud.log**
`2021-06-17 01:09:56,544 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2198:null) Get resource request for /resource/noVNC/vnc.html`
`2021-06-17 01:09:56,546 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2198:null) Sent file /resource/noVNC/vnc.html with content type text/html`
`2021-06-17 01:09:57,227 INFO  [cloud.consoleproxy.ConsoleProxyNoVncClient] (Thread-2199:null) Connect to VNC server directly. host: 10.226.18.128, port: 5915`
`2021-06-17 01:09:57,228 INFO  [consoleproxy.vnc.NoVncClient] (Thread-2199:null) Connecting to VNC server 10.226.18.128:5915...`
`2021-06-17 01:09:57,279 INFO  [consoleproxy.vnc.NoVncClient] (Thread-2199:null) VNC server requires password authentication`
`2021-06-17 01:09:57,438 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2200:null) Get resource request for /resource/noVNC/app/images/handle_bg.svg`
`2021-06-17 01:09:57,438 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2200:null) file does not exist/resource/noVNC/app/images/handle_bg.svg`
`2021-06-17 01:10:25,774 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2201:null) Get resource request for /resource/noVNC/app/images/handle.svg`
`2021-06-17 01:10:25,774 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2201:null) file does not exist/resource/noVNC/app/images/handle.svg`
`2021-06-17 01:10:25,776 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2202:null) Get resource request for /resource/noVNC/app/images/info.svg`
`2021-06-17 01:10:25,776 INFO  [cloud.consoleproxy.ConsoleProxyResourceHandler] (Thread-2202:null) file does not exist/resource/noVNC/app/images/info.svg`

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by div8cn** [comment]
@rohit

**Comment by nvazquez** [comment]
@davidjumani any input/hint on this?

**Comment by davidjumani** [comment]
Noticed a similar result. However, the response is sent as soon as the CPVM receives the request, so the delay is possibly in the request reaching the CPVM

**Comment by davidjumani** [comment]
I've recreated the env, console loads just as fast as it would with SSL disabled
@div8cn Can you destroy and recreate the console proxy VM, and also check if it's a network related issue

**Comment by rhtyd** [comment]
Ping @div8cn any more updates, hints?

**Comment by nvazquez** [comment]
@div8cn I'm closing the issue now, please reopen if needed
