### ISSUE TITLE
UI: need to notify new vm password when reset vm ssh keypair (4.15)

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5152]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### SUMMARY

new vm password is not shown on UI when reset vm ssh keypair
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
similar as #5127 which has been fixed by #5129 

@Pearl1594 could you please also fix this ui bug ? thanks  :-)

**Comment by rhtyd** [comment]
Fixed in #5153
