### ISSUE TITLE
last id file is not created on usage server install

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5155]
the file `/usr/local/libexec/sanity-check-last-id` is not created, when the usage server is installed. This file is required by the sanity check and must be present when it is enabled.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~
install cloudstack-usage
~~~

##### EXPECTED RESULTS

~~~
the file `/usr/local/libexec/sanity-check-last-id` exists
~~~

##### ACTUAL RESULTS

~~~
`/usr/local/libexec/sanity-check-last-id` does not exist
~~~

**Comment by rohityadavcloud** [comment]
@nvazquez is the last-id even useful, needed?

**Comment by DaanHoogland** [comment]
@nvazquez , though @rohityadavcloud makes a valid point, this seems a simple fix (crating the id file on starting) why is this moved to `unplanned`? Is there a conflict with other functionality?

**Comment by rohityadavcloud** [comment]
Related/dupes - https://github.com/apache/cloudstack/issues/5156
