### ISSUE TITLE
/usr/local/libexec/sanity-check-last-id is not updated

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5156]
After the sanity check is run the file `/usr/local/libexec/sanity-check-last-id` should be updated to prevent the sanity checkl from always running over old records again.
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~
the nightly usage run has passed withg sanity check enabled.
~~~

##### EXPECTED RESULTS

~~~
the records from yesterday won't be checked again tommorow so the value in `/usr/local/libexec/sanity-check-last-id` is updated.
~~~

##### ACTUAL RESULTS

~~~
the value in `/usr/local/libexec/sanity-check-last-id` stays the same.
~~~

**Comment by rohityadavcloud** [comment]
Also refer to https://github.com/apache/cloudstack/issues/5155
Increase scope to creation of this on install/running the usage server.
