### ISSUE TITLE
IP Clearance for Terraform Provider and Go SDK

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#5159]
This issue tracks for the IP clearance process for accepting the Terraform Provider and Go SDK: https://incubator.apache.org/ip-clearance/ip-clearance-template.html#process

- [x] ACS PMC vote passed on Terraform provider donation/migration to ACS project on 22nd April 2021 (https://markmail.org/message/g4prb25g7wakbifa)
- [x] IP Clearance Officer: ASF member @PaulAngus or ACS VP @GabrielBrascher to volunteer or find a volunteer (Paul Angus volunteered on ACS PMC list on 21st June 2021, on no communication from Paul ACS VP Gabriel asked on the list to volunteer or find a volunteer on 8 July 2021)
- [x] Outline form commit: https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/cloudstack-terraform.xml
- [x] ICLA of @svanharmelen acknowledged by secretary@ ASF on 21st June 2021
- [x] Software Grants from @svanharmelen acknowledged by secretary@ ASF on 25th June 2021
- [x] Codebase relicensed under Apache Public License v2 (with tag/commits made) on https://github.com/xanzy/terraform-provider-cloudstack and https://github.com/xanzy/go-cloudstack (checked by @rhtyd on 25th June 2021)
- [x] IP clearance XML doc commit (XML doc is updated by @rhtyd on 8 July 2021: https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/cloudstack-terraform.xml)
- [x] IP clearance XML doc commit (XML doc is updated by @DaanHoogland on 19 July 2021: https://svn.apache.org/repos/asf/incubator/public/trunk/content/ip-clearance/cloudstack-go-sdk.xml)
- [x] Add a row to the table at incubator/public/trunk/content/ip-clearance/index.xml
- [x] Post a message to general@incubator prefixed [IP CLEARANCE] asking for clearance to be checked. Sign off is by lazy consensus so wait at least 72 hours for a -1 completed on date (to-be-filled)
- [x] Post a [RESULT] to close the thread and let the project know that the code has been cleared for import (to-be-filled)
- [x] Push codebase to new repositories at https://github.com/apache/cloudstack-terraform-provider and https://github.com/apache/cloudstack-go

Top 20 contributors tracking table for https://github.com/xanzy/terraform-provider-cloudstack/graphs/contributors:
| Contributor        | ICLA or contributor agreed over email/github? | Remarks
| ------------- |:-------------:| -----:|
| @svanharmelen      | ICLA + grants OK | sander@vanharmelen.nl Major contributor/author and repo owner |
| @grubernaut      | No objection received on PMC ML |  16 commits |
| @hany      | No objections in comments |  16 commits |
| @mcanevet      | No objection received on PMC ML |  11 commits |
| @serbaut      | ? | 8 commits |
| @cezarsa      | No objection received on PMC ML |  6 commits |
| @radeksimko      | No objection received on PMC ML | 6 commits |
| @jalemieux      | ? | 5 commits |
| @jefflaplante      | ? |  4 commits |
| @jeroendekorte      | ? | 4 commits |
| @benjvi      | No objections in comments | 4 commits |
| @ceh      | No objections in comments | 3 commits |
| @stack72      | No objections in comments | 3 commits |
| @schans      | No objections in comments, already ASF committer ICLA should be OK | 3 commits |
| @ddegoede      | ? | 2 commits |
| @greut      | No objections in comments | 2 commits |
| @av1nashs1ngh      | ? | 2 commits |
| @glenjamin      | ? | 2 commits |
| @chiradeep      | Yes, ACS PMC member | 2  commits |
| @cryptobioz      | ? | commits |

Top 20 contributor tracking table for https://github.com/xanzy/go-cloudstack/graphs/contributors:
| Contributor        | ICLA or contributor agreed over email/github? | Contact | Remarks |
| ------------- |:-------------:| -----:|  -----:|
| @svanharmelen      | ICLA + grants OK | sander@vanharmelen.nl | Major contributor/author and repo owner |
| @benjvi      | No objections in comments |9 commits |
| @cezarsa      | No objection received on PMC ML | 3 commits |
| @nettoclaudio      | ? | 3 commits |
| @jalemieux      | ? | 3 commits |
| @ustcweizhou      | Yes ACS PMC member and comment on this issue | 2 commits |
| @pdube      | ? | 1 commits |
| @ovear      | No objections in comments | 1 commits |
| @dcarbone      | No objections in comments | 1 commits |
| @glenjamin      | No objections in comments | 1 commits |
| @ryhamz      | ? | 1 commits |
| @andrestc      | ? | 1 commits |

**Comment by ustcweizhou** [comment]
@rhtyd I am OK with it.

**Comment by rhtyd** [comment]
Apologies to all the contributors tagged on this ticket. The Apache CloudStack project has voted and agreed to further lead the development, maintenance and releases of the Terraform provider the Go SDK codebases: https://markmail.org/message/g4prb25g7wakbifa

Following advice from general@ incubator I've started this issue to track IP clearance for the same. The thread can be referred here: https://markmail.org/message/uiot3qhuf7to2twz

We've been advised and we should attempt to get agreement from all contributors request them to submit ICLA (see https://www.apache.org/licenses/contributor-agreements.html) to secretary@ ASF, or have some document to demonstrate agreement was gathered from contributors. We understand that may be asking too much a simple github comment or email to ACS PMC - private@cloudstack.apache.org may also be fine.

If you agree with the initiative and codebase donation to Apache CloudStack project, you may kindly drop a comment on this issue with something like "Fine with me"; and/or you may submit ICLA (signed & scanned pdf) to secretary@apache.org. Thanks.

**Comment by glenjamin** [comment]
Could you expand on what this means in practice? What are we agreeing to exactly? What would happen if we didn't agree?

I don't expect I would have any objections, but it's extremely unclear to me from this comment what transfer of what rights would be taking place if I stated agreement.

**Comment by rhtyd** [comment]
@glenjamin we are asking if you and the other contributors agree to the Terraform codebase being re-licensed and donated to the Apache CloudStack project under the opensource APLv2 (https://www.apache.org/licenses/LICENSE-2.0). That's all.

TBH I don't know what should happen on any disagreements. In practice, I would see this as a mere formality as Sander the original author and owner of the repository has already submitted ICLA and his software grants to the ASF. I thought that was enough but folks on the mailing lists suggested we should make an attempt to ask all/major contributors to the codebases being donated.

The background of the initiative is that the Terraform provider was archived and no longer maintained/released, and the ACS project/community (who effectively are the users of the projects with CloudStack) want to go forward with this initiative for users and contributors to continue to develop, maintain and release (a) under the APLv2 license and (b) by the wider Apache CloudStack community. I'm not a legal expert but from what I understand as a layperson moving anything to Apache license would no longer require modifications to be shared. I'm not sure what conditions were/are applicable with the previous license.

Hope this helps.

**Comment by schans** [comment]
Happy to help out if I can. I'm already an Apache committer (Jackrabbit) with id "schans" and the ASF already has my ICLA.

I have no objections. Do you want me to mail that formally to the PMC ML? Or is here fine as well?

Thanks
Bart

**Comment by rhtyd** [comment]
Thanks @schans I'll leave it to you, here should be fine as an ASF contributor/committer you would have already submitted your ICLA.

**Comment by schans** [comment]
Cool. Hereby my office "No objection". Submitted my ICLA in 2011 ;-)

**Comment by glenjamin** [comment]
Ah ok. As far as I can tell `go-cloudstack` was already Apache 2 licensed, but sure - no objections from me.

**Comment by hany** [comment]
No objections from me.

**Comment by stack72** [comment]
None from me either

**Comment by grubernaut** [comment]
"Fine with me"

**Comment by greut** [comment]
Fine by meOn Fri, Jun 25, 2021 at 10:08, Rohit Yadav ***@***.***> wrote:  
Apologies to all the contributors tagged on this ticket. The Apache CloudStack project has voted and agreed to further lead the development, maintenance and releases of the Terraform provider the Go SDK codebases: https://markmail.org/message/g4prb25g7wakbifa
Following advice from general@ incubator I've started this issue to track IP clearance for the same. The thread can be referred here: https://markmail.org/message/uiot3qhuf7to2twz
We've been advised and we should attempt to get agreement from all contributors request them to submit ICLA (see https://www.apache.org/licenses/contributor-agreements.html) to secretary@ ASF, or have some document to demonstrate agreement was gathered from contributors. We understand that may be asking too much a simple github comment or email to ACS PMC - ***@***.*** may also be fine.
If you agree with the initiative and codebase donation to Apache CloudStack project, you may kindly drop a comment on this issue with something like "Fine with me"; and/or you may submit ICLA (signed & scanned pdf) to ***@***.*** Thanks.

**Comment by benjvi** [comment]
Fine by me, no objecttions

**Comment by ceh** [comment]
Fine with me.

**Comment by ovear** [comment]
That's cool, Fine with me.

**Comment by dcarbone** [comment]
fine with me.

**Comment by rhtyd** [comment]
Thanks all for your support, no one has objected to the initiative so we'll proceed with the IP clearance process this/next week cc @PaulAngus.

**Comment by rhtyd** [comment]
The repositories are imported under following passing of the IP clearance:
https://lists.apache.org/thread.html/r6600a9ea1a59b9d436a0c13d404b785c4cffd91349e0c79a0028bbc4%40%3Cgeneral.incubator.apache.org%3E
https://lists.apache.org/thread.html/rfec7740e736af0f0ebcc879a65bb66d131d4edd7cbde46daea0df9c5%40%3Cgeneral.incubator.apache.org%3E

Codebase imported at new repos:
https://github.com/apache/cloudstack-terraform-provider
https://github.com/apache/cloudstack-go

**Comment by rhtyd** [comment]
Thanks to all involved for your help, assistance, and patience.
