### ISSUE TITLE
UI [afaik]: Request header to long when adding Swift as Secondary Storage

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5168]
ACS 4.15.0

##### ISSUE TYPE

 * Bug Report

![image](https://user-images.githubusercontent.com/45762285/123946407-758af300-d99f-11eb-9f9d-a7cd52021433.png)

**Comment by andrijapanicsb** [comment]
POST should be used instead?

**Comment by utchoang** [comment]
![image](https://user-images.githubusercontent.com/13766648/124059104-be50b380-da54-11eb-90ab-9db32ae1ee89.png)
@andrijapanicsb 
This is not a problem with the method, it could be an error returned from the server-side. Maybe in my case, I received the message "You can only add new image stores from the same provider NFS already added"

**Comment by Pearl1594** [comment]
@utchoang I believe this is because you probably already have an NFS store added. You may have to remove that before adding a store of a different provider.

**Comment by utchoang** [comment]
@Pearl1594 I mean @andrijapanicsb's problem is not in GET or POST method (As you can see my image called POST method). So I don't think that's the cause of the "Request long header" message.

**Comment by andrijapanicsb** [comment]
My bad guys, yes, I also have hit that message like you @utchoang  - in my case I had Swift already added (but UI reported failure), etc.

Can be closed.
