### ISSUE TITLE
Useability to configure traffic types for VMware zone is not good

### ISSUE THREAD

**Issue by DK101010** [apache/cloudstack#5177]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
UI/Vmware
~~~

##### CLOUDSTACK VERSION
~~~
4.15.1.0
~~~

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In old UI when configuring the traffic type while creating a new zone of type VMware, the "Edit traffic type" form shows 3 defined fields to be filled out, where in background the traffic-label is build from these 3 fields.

![image](https://user-images.githubusercontent.com/57522802/124083546-467f8a80-da4e-11eb-9ed0-fe09639ef55b.png)

in new UI you need to know, how the traffic label is build for VMware zones. 

![image](https://user-images.githubusercontent.com/57522802/124083681-7464cf00-da4e-11eb-99e4-6d518b057da4.png)

The current implementation is not really handy for our admins because they need a to much information's to fill this label. Therefore we need the old form for VMware or an adequate replacement.

**Comment by shwstppr** [comment]
@DK101010 can you please review/test the PR #5178

**Comment by DK101010** [comment]
> @DK101010 can you please review/test the PR #5178

Hi, @shwstppr this is like I want. Many thanks for the hint ;)
