### ISSUE TITLE
VPC Site to  Site VPN state 

### ISSUE THREAD

**Issue by havengit** [apache/cloudstack#5179]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
 * UI
 * VPN
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.15.0.0
~~~

##### CONFIGURATION

CloudStack 4.15.0.0
advanced networking

##### SUMMARY

1.Create the VPN Customer Gateway with incorrect information
2.Create a site to site vpn  connect， vpn state is connected

##### STEPS TO REPRODUCE

~~~
1.Create the VPN Customer Gateway with incorrect information
2.Create a site to site vpn  connect in active mode ， first state is connected.


~~~

##### EXPECTED RESULTS

~~~
Create a site to site vpn  connect in active mode ， first state should be disconnected
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@havengit have you tried with entering correct information? and is the initial state disconnected then?

**Comment by DaanHoogland** [comment]
ok, so the assumption is it is correct untill a connection fails, could do with some improvement indeed.

**Comment by weizhouapache** [comment]
the initial state could be "Connecting" (does not exist now) instead of "Connected"
https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/network/vpn/Site2SiteVpnManagerImpl.java#L350

**Comment by davidjumani** [comment]
Added a nice little fix to set the initial state as connecting as @weizhouapache suggested #5327

![Screenshot from 2021-08-17 15-38-27](https://user-images.githubusercontent.com/8244774/129719822-a7e5a3e9-35d1-453f-a000-26b70174c147.png)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5327
