### ISSUE TITLE
Broken link in the 4.15.1 docs

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#5188]
Please update the main docs :

`deb http://server.url/cloudstack/repo/binary ./`
`wget -q -O - http://server.url/cloudstack/repo/binary/KEY.gpg | sudo apt-key add -`

Url : http://docs.cloudstack.apache.org/en/4.15.1.0/installguide/building_from_source.html

**Comment by davidjumani** [comment]
@abdelouahabb This is when the user builds packages from source and signs it with his / her custom key. The key is to be uploaded to a their custom webserver 
http://docs.cloudstack.apache.org/en/4.15.1.0/installguide/building_from_source.html#repository-signing

**Comment by rhtyd** [comment]
cc @wido @GabrielBrascher can you check this issue and specific docs URL? Do we need to update that wrt Ubuntu?

**Comment by DaanHoogland** [comment]
> Please update the main docs :
> 
> `deb http://server.url/cloudstack/repo/binary ./`
> `wget -q -O - http://server.url/cloudstack/repo/binary/KEY.gpg | sudo apt-key add -`
> 
> Url : http://docs.cloudstack.apache.org/en/4.15.1.0/installguide/building_from_source.html

I don't see a broken link, please specify

**Comment by abdelouahabb** [comment]
this makes a confusion, maybe it should be written `<http://server.url/>` to make it clear that this is a variable and it is used to make a custom repo

**Comment by nvazquez** [comment]
@abdelouahabb I have created a documentation PR to address this issue, please review: https://github.com/apache/cloudstack-documentation/pull/235 cc. @DaanHoogland @rhtyd

**Comment by rhtyd** [comment]
Docs PR merged https://github.com/apache/cloudstack-documentation/pull/235
