### ISSUE TITLE
Kubuntu returns Neon which causes error

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#5189]
In the file `/usr/lib/python3/dist-packages/cloudutils/syscfg.py` there is only Ubuntu, but in Kubuntu, it gives `Neon` if you run 

`/usr/bin/lsb_release -i
Distributor ID:	Neon
`

This makes `cloudstack-setup-management` fail,

Cloudstack 4.15.1
Distributor ID:	Neon
Description:	KDE neon User Edition 5.22
Release:	20.04
Codename:	focal 
(Kubuntu 20.04)

**Comment by davidjumani** [comment]
@abdelouahabb Cloudstack could still work since it reads the contents of `/etc/lsb-release` and not run any command to get the OS version

**Comment by davidjumani** [comment]
@abdelouahabb As of now, vanilla Ubuntu is supported, feel free to add support for Kubuntu if you'd like

**Comment by rhtyd** [comment]
@abdelouahabb Kubuntu is not a supported distribution, please use Ubuntu Server. Refer: http://docs.cloudstack.apache.org/en/latest/releasenotes/compat.html

**Comment by abdelouahabb** [comment]
Kubuntu is just a normal Ubuntu with the main difference is the GUI and the `pkcon update` instead of `apt update` (and yes, for servers, better use headeless tools)

I will try to make a PR to add it

**Comment by nvazquez** [comment]
Hi @abdelouahabb please advise when you have created the PR to fix this

**Comment by rhtyd** [comment]
Hi @abdelouahabb community can't commit to supporting and testing non-LTS and non-mainstream distros. But we'll be happy to accept any PRs of somebody wants to maintain support for their favourite distro. Feel free to raise a PR and discuss on dev@ML.

Closing on this remark.
