### ISSUE TITLE
Rebooting a host in a zone, doesn't re-add the persistent network's resources

### ISSUE THREAD

**Issue by shatoboar** [apache/cloudstack#5196]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
ENGINE
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### CONFIGURATION

Tested on local mbx kvm setup.

##### OS / ENVIRONMENT

Centos 7

##### SUMMARY

Issue is linked to #4814 

##### STEPS TO REPRODUCE

 

~~~
 Within zone with a persistent network, reboot an existing host. Check for the hosts persistent network's resources by ssh-ing into the host.
~~~

##### EXPECTED RESULTS

~~~
When running the steps above, the persistent network's resources should be present in the host.
~~~

##### ACTUAL RESULTS

~~~
The persistent networks resources have been removed from the host.
~~~

**Comment by rohityadavcloud** [comment]
Closing this as we've a PR, and this may cause confusion for student looking for gsoc ideas.
