### ISSUE TITLE
Addition to #5194 - update of `broadcast_uri` for all existing pvlan networks is necessary during upgrade to 4.15.x

### ISSUE THREAD

**Issue by mib1185** [apache/cloudstack#5202]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
Server
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### SUMMARY

As descripted in #5194, with #4040 changes were made, how the `broadcast_uri` for private VLAN network is build.
This new approach is the more correct one, but does only apply to newly created networks (_networks created after upgrade to 4.15_), those already existent networks keep its old `broadcast_uri` which is not correct, since it always contains `-i` (_ex. `pvlan://63-i123`_) and those is declared as an isolated pvlan, even it was configured as community pvlan.

In our case - since all pvlan are of type community - we simple updated all entries in DB with following SQL statement:
```sql
UPDATE cloud.networks
SET broadcast_uri = REPLACE(broadcast_uri, '-i', '-c')
WHERE removed is null and broadcast_uri like '%pvlan%';
```

But to be more generic, it is needed that the correct pvlan type is gathered from infrastructure (_ex. VMware portgroup_) and corresponding DB entry is proper updated.

cc @DK101010 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by nvazquez** [comment]
HI @DK101010 would you consider including this as part of your PR #5194?

**Comment by DK101010** [comment]
> HI @DK101010 would you consider including this as part of your PR #5194?

Hi @nvazquez, this issue is needed for my PR in that case of existing community networks lower 4.15.0.0. But it could be necessary to add this as soon as possible to cloudstack because all already existing community networks in cloudstack are wrong. I can not estimate which impact it has for other CS functionality beside the ingest.

**Comment by DaanHoogland** [comment]
@DK101010 

> Hi @nvazquez, this issue is needed for my PR in that case of existing community networks lower 4.15.0.0. But it could be necessary to add this as soon as possible to cloudstack because all already existing community networks in cloudstack are wrong. I can not estimate which impact it has for other CS functionality beside the ingest.

are you saying that that PR won't work without a DB upgrade for all URI fields? (bit worried here)

**Comment by DK101010** [comment]
> @DK101010
> 
> > Hi @nvazquez, this issue is needed for my PR in that case of existing community networks lower 4.15.0.0. But it could be necessary to add this as soon as possible to cloudstack because all already existing community networks in cloudstack are wrong. I can not estimate which impact it has for other CS functionality beside the ingest.
> 
> are you saying that that PR won't work without a DB upgrade for all URI fields? (bit worried here)

Hi Daan, sure. The current implementation always expects an "i" in the broadcast uri and throws errors for community networks that are created in CS 4.15.0.0 or above. My PR add an "i" or a "c" depending on the pvlan type and would throws errors for community networks that are created in 4.14. and below.

**Comment by DaanHoogland** [comment]
> Hi Daan, sure. The current implementation always expects an "i" in the broadcast uri and throws errors for community networks that are created in CS 4.15.0.0 or above. My PR add an "i" or a "c" depending on the pvlan type and would throws errors for community networks that are created in 4.14. and below.

so we need to enhance #5194 to include a DB upgrade for old community pvlans!

**Comment by nvazquez** [comment]
@DK101010 my idea is just what @DaanHoogland described. Including a DB upgrade only for older pvlans (created with the older format). New pvlans will have the new format and should work with your PR

**Comment by davidjumani** [comment]
If I'm understanding this correctly, other existing pvlans (in vmware) were created as isolated in cloudstack as that's the only one that was supported at that time. If that's right, updating the isolated pvlans to community ones in the db via an upgrade path is not a good idea. Assuming there are isolated pvlans created in VMware and correctly created as isolated pvlans in cloudstack, a db upgrade would change them to community ones which is incorrect. Imo, since full-fledged pvlans is a new feature, the user will need to manually upgrade it, or allow editing the pvlan via the update API (which is risky as KVM supports pvlans as well, and updating it will require reapplying the appropriate ovs rules on all the hosts for every vm on that network)

**Comment by nvazquez** [comment]
The logic to upgrade older pvlans should be smarter than a DB upgrade. I would propose to proceed with the PR #5194 without any DB upgrade, leaving this ticket open for future fix @davidjumani @DaanHoogland @mib1185

**Comment by DaanHoogland** [comment]
sorry, That will leave people with disfunctional environments. :-1:

**Comment by mib1185** [comment]
> sorry, That will leave people with disfunctional environments. 👎

This could be the case for every user, who has updated to 4.15.x, since approache, how `boadcast_uri` is build, was changed already with #4040 and does not depend on #5194.
Therefore, yes to keep #5194 as is, but IMHO fix/update for existing private vlan networks should be implemented asap (_to become part of 4.15.2_) 🤔

**Comment by davidjumani** [comment]
> sorry, That will leave people with disfunctional environments. -1

Two reasons why I'm against adding anything to the upgrade path :
1. It is a bad assumption that all pvlans created in vmware are community and correspondingly created as isolated in cloudstack. There could be admins who created isolated pvlans in vmware and cloudstack. Changing all isolated pvlans to community will break the correctly working functionality
2. Pvlans are also created on Xen and KVM (implemented via OVS) and altering it in the db via an upgrade path will break their functionality

That being said, any admin who feels that there is a mismatch between what is existing on vmware and cloudstack should manually update it

**Comment by nvazquez** [comment]
@mib1185 @davidjumani I agree - however, we had a different opinion from @DaanHoogland, after the latest replies are you still against moving on #5194 as it is now?

**Comment by davidjumani** [comment]
I'm for https://github.com/apache/cloudstack/pull/5194 but against any changes in a db upgrade path to fix existing pvlan uri

**Comment by DaanHoogland** [comment]
So the upgrade can check and change only pvlans specific to vmware hosts, can it @davidjumani , or would that give more issues? cc @nvazquez @DK101010

**Comment by nvazquez** [comment]
I'm also for #5194. If I understand correctly the PR is extending the importing of unmanaged instances to all the pvlan types. IMO that may not mean to upgrade the broadcast URI for previously created pvlans, as those pvlans were created with the pvlan type which was available at that time.

**Comment by DK101010** [comment]
@nvazquez when you merge this PR, The ingest will no longer work for all community networks with an older format. 

@DaanHoogland How do you want check which pvlan's are community and  which isolated? I checked the network table and I couldn't see any infos to decide it.

**Comment by DaanHoogland** [comment]
@DK101010 the important question to me is: are there any installations conceivable that would have a pvlan with a 'c' in the broadcast URI that will after upgrade be expected to have an 'i' in the URI. If so we have a backwards compatibility issue on our hand and we need to deal with that.
so
What is the functional reason for the difference?
if this is vital we'll need to deal during upgrade
If no, I'd suggest removing the 'c' *and* the 'i' altogether.

please explain, because I'm aware I am missing some knowledge here.

**Comment by DK101010** [comment]
@DaanHoogland japp, I'm also the wrong person to answer this question. 

But we are use this bugfix incl. uri update since 3 weeks in our prod VMware env. without problems. 

Perhaps it helps to estimate the impact.

**Comment by davidjumani** [comment]
@DK101010 Looking at the code history I see your point. The broadcast URI is stored incorrectly in the DB, although the network functions as a community PVLAN and can potentially cause issues for PVLANs created between 4.14 and 4.15. I'm +1 for a smart fix

**Comment by DK101010** [comment]
> @DK101010 Looking at the code history I see your point. The broadcast URI is stored incorrectly in the DB, although the network functions as a community PVLAN and can potentially cause issues for PVLANs created between 4.14 and 4.15. I'm +1 for a smart fix

Hi @davidjumani not quite sure what do you mean with smart fix. I have currently no clue to find out which pvlans are isolated in which not. Therefore I think a database upgrade is not enough.

**Comment by nvazquez** [comment]
I think the fix would include checking the pvlans on the hypervisor side and compare the pvlan type matches the type on the DB entry for broadcast_uri. In case there is a mismatch, the broadcast_uri must be updated. @rhtyd can you discuss with @davidjumani and work on a way forward for the upgrade fix?

**Comment by davidjumani** [comment]
Agree with @nvazquez

**Comment by rhtyd** [comment]
Agree with your suggestion @nvazquez, @davidjumani since you've worked in that area - please consider Nicolas's advice and work forward for the upgrade fix.

**Comment by nvazquez** [comment]
@rhtyd we have discussed some options to address this and found a potential issue on mixed environments with KVM and Vmware that can cause failures on the upgrade. Also, the discrepancy on DB can be solved by creating a new network with the correct type (previously all the pvlans contained the were isolated in DB as it was the only supported type) or may need manual update on DB only when its not intended to create a new network. Therefore, we are for adding a note in the documentation on how to proceed in this specific case. cc. @davidjumani

**Comment by davidjumani** [comment]
> @rhtyd we have discussed some options to address this and found a potential issue on mixed environments with KVM and Vmware that can cause failures on the upgrade. Also, the discrepancy on DB can be solved by creating a new network with the correct type (previously all the pvlans contained the were isolated in DB as it was the only supported type) or may need manual update on DB only when its not intended to create a new network. Therefore, we are for adding a note in the documentation on how to proceed in this specific case. cc. @davidjumani

+1

**Comment by rhtyd** [comment]
@davidjumani have we agreed that you'll work on a doc PR instead? Thanks

**Comment by davidjumani** [comment]
Yes, will create a PR soon and update
