### ISSUE TITLE
Update Template Sharing options cannot be disabled

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#5223]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1.0
~~~

##### OS / ENVIRONMENT

Ubuntu Server 18.04.5 LTS

##### SUMMARY

Options on Update Template Sharing can be activated but cannot be deactivated
On legacy ui everything is working as it should.

##### STEPS TO REPRODUCE

~~~
Check the attached video
~~~

https://user-images.githubusercontent.com/25532758/126294140-ea1d6a87-659f-4d54-b18d-18e5622221a3.mp4

##### EXPECTED RESULTS

~~~
Expected results to be possible to deactivate sharing options of templates
~~~

**Comment by shwstppr** [comment]
Verifying the behaviour

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5224
