### ISSUE TITLE
Choose between Public or VPN based IPs for KVM VMs

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5234]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
VPN, Connectivity
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### OS / ENVIRONMENT

Ubuntu 20.04.2
MySql 8.0.25
Cmk 6.1.0
KVM Hypervisor

##### SUMMARY

I wanna assign either Public or Internal (VPN based) IP addresses to my VMs.
If I choose to have a public, VM gets a public IP from a public Pool.
If I choose to have a VPN based (e.g 10.205.0.155), VM gets an internal IP from DCHP.

For Pub IPs, users should be able to connect directly. For VPN based IPs, users should establish an OpenVPN connection to a Host Public IP and use the VPN IP. 

The question is:
1. Can I do that with a single NIC and cloudbr0 now ? Or I'll need two links (NICs) with two bridges ?
2. Are there examples on how to do that either in GUI or in cmk ?

The diagram is below:

![Screenshot from 2021-07-22 12-52-40](https://user-images.githubusercontent.com/2816743/126620987-07346466-e128-4369-9adc-7b656b06a54d.png)

Here VM0 gets a Pub IP. VM1 and VM2 should get IPs from the VPN pool

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
1. Should be able to assign either a Public IP or a VPN based IP
2. Should be able to access my VMs both from internal and external networks
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@tampler 
I do not understand why you run a openvpn server on host.

for IP 10.205.x.x, you can use a shared network.
for IP 185.185.x.x, you can use either an isolated network (recommended) or a shared network.

therefore, it looks basic zone does not meet your requirements. you need to create an advanced zone (or advanced zone with security groups but it does not support isolated networks).

for your questions,
(1) I have ever created some environments with only 1 bridge (cloudbr0) for testing, it looks ok. It is not suggested to use it in production (it is ok for testing).
(2) it is much easier to create a zone on GUI than cmk.

**Comment by tampler** [comment]
Hello, @weizhouapache, thanks for your response. I digged more into CS documentation and found that it has own VPN implementation as well as a Static and Dynamic NAT bridges.

So my question boils down to the following: 
![setup](https://user-images.githubusercontent.com/2816743/127353289-1b43cc11-3e48-4e84-978b-cd4b608495b7.png)

The question is: 
Can I have such setup out-of-box in CloudStack ? I'll need two separate physical networks, where guest VMs with Public IPs reside in the `Physical Network 0` and VPN-backed guest VMs reside in the `Physical Network 1`.

In such config, if it is implementable, I'll need only two Public IPs: one for VM0 with a public IP and one for a NAT VPN bridge. 
The later will allow me to start any number of guest instances (up to 4096) and all traffic will go thru a single IP and is NATed inside CS

**Comment by weizhouapache** [comment]
@tampler sure.
you need to create an Advanced zone, and deploy vms on an isolated network in the zone. then you can create multiple physical networks or single physical network (it does not matter), which includes Public/Guest/Management traffic type (Storage is optional).
you can set different traffic label for traffic types, for example in your case, cloudbr0 for Public and cloudbr1 for Guest (they are actually the default value).

**Comment by tampler** [comment]
@weizhouapache hello

I've been following the guest traffic docs [here](http://docs.cloudstack.apache.org/en/latest/adminguide/networking_and_traffic.html#). Essentially, I wanna bring up the setup right from the top picture there
![guest-traffic](https://user-images.githubusercontent.com/2816743/127534994-0e268ff3-792c-4329-9a4b-c3baf4b49dfa.png)

I did the following

1. Added an Advanced Zone
2. Created an Isolated Network for Guest Traffic
3. Had the following setup
![guest-setup](https://user-images.githubusercontent.com/2816743/127535564-00170023-cd2b-42d1-866b-df62c4673e11.png)
4. Assigned a pool of Public IPs. Now see a one Public IP is assigned

5. What's next? I don't currently have a VPC or a VPN Customer Gateway setup. Also, my network config won't work. SystemVMs fail to obtain private IPs and fail with the following state

![Screenshot from 2021-07-29 19-26-22](https://user-images.githubusercontent.com/2816743/127536263-064b6cc0-aebd-436e-a533-886907e4fdb2.png)

Thanks for your help and advice,
Boris

**Comment by weizhouapache** [comment]
@tampler 
as I suggested before, please use private IP (eg 192.168.x.x, see RFC1918) for internal communication (management, hosts and systemvms), and add a private ip range to management network (they will be assigned to systemvms).
each systemvm has a public Ip, a private Ip and a control Ip.
please change your network topology accordingly.

when you add zone via wizard on UI, you need to specify some IPs in the "add pod" step, see below.
![image](https://user-images.githubusercontent.com/57355700/127545169-f7d43337-2145-421a-805f-623c3f0d529d.png)

cloudstack will pick up a ip from the range and assign to systemvm.
you can add private ip range on UI as well.

![image](https://user-images.githubusercontent.com/57355700/127545565-695034b6-66f0-49b2-829a-47ab83493c17.png)

**Comment by tampler** [comment]
@weizhouapache Hello Wei

This doesn't work for me. Any WORKING example available? Here's what I got for Advanced Zone CIDR: 192.168.1.1/24

![guest](https://user-images.githubusercontent.com/2816743/127669507-9cfa57f7-06bf-4870-bb83-e939822ad90f.png)
![err](https://user-images.githubusercontent.com/2816743/127669533-84b997c6-4e3f-4edb-82f3-6be4c9ead5ea.png)

**Comment by weizhouapache** [comment]
@tampler 
before you create the zone, you need to have a clear network design of your platform.
public ip range (to connect internet)
private ip range (for systemvms, communicate with management/host)
guest ip range (assign to vms, consider isolated networks and shared networks)
storage ip range (if you does not use local storage)
managemen ip (for mgt server and hosts)

apparently you does not have a good design.

**Comment by tampler** [comment]
@weizhouapache Hello Wei

1. I don't have a goal to build a platform now. I'm evaluating CloudStack and wanna see how to run the simplest example network with VPN. I don't need all those details at the moment since I'm running the whole thing on a single test server.

2. As for private IP ranges. Who should assign them? Do I need to allocate 192.168.x.x ranges from my switch or CS can do that with its own DHCP?

3. Could you please show screenshots of your example with valid configuration?

Thanks,
Boris

**Comment by weizhouapache** [comment]
@tampler 
you can find an example for advanced zone in cloudstack code.
https://github.com/apache/cloudstack/blob/main/tools/devcloud-kvm/devcloud-kvm-advanced.cfg

defauilt guest network ip and vlan
```
            "guestcidraddress": "10.1.1.0/24", 
...
                    "vlan": "3900-4000", 
```
public ip range
```
            "ipranges": [
                {
                    "startip": "192.168.100.100", 
                    "endip": "192.168.100.199", 
                    "netmask": "255.255.255.0", 
                    "vlan": "untagged", 
                    "gateway": "192.168.100.1"
                }
            ], 
```
private ip (startip to endip) and hosts
```
            "pods": [
                {
                    "endip": "172.17.10.199", 
                    "name": "testpod", 
                    "startip": "172.17.10.100", 
                    "netmask": "255.255.255.0", 
                    "clusters": [
                        {
                            "clustername": "testcluster", 
                            "hypervisor": "KVM", 
                            "hosts": [
                                {
                                    "username": "root", 
                                    "url": "http://172.17.10.10/", 
                                    "password": "password"
                                }
                            ], 
                            "clustertype": "CloudManaged"
                        }
                    ], 
                    "gateway": "172.17.10.1"
                }
            ], 
```

**Comment by tampler** [comment]
@weizhouapache Hey Wei

That actually worked for me! Thanks a lot for your help. I was able to

1. Launch an Advanced Zone
2. Add an Isolated Guest Network
3. Added a Public IP from the 192.168.x.x range
4. Enabled a Remote Access VPN on that public IP
5. Added a host
6. Launched a guest VM on that host

What is still NOT working
1. I can't access console on my guest instance, which I created from an ISO. Says that connection timed out
2. I wanna access my guest VM instance thru the OpenVPN client. Where can I find OpenVPN example setup?

Thanks again for your help and advice,
Boris

**Comment by andrijapanicsb** [comment]
in order to access the console of ANY VM, you are really accessing the "Public" IP of the CPVM - and if that communication is not possible, you won't be able to access console... (CPVM is connected to Pod/management network to proxy VNC traffic from hypervisor/VM, to  your browser - and this is exposed/proxied (with auth/token) on the "public" interface of the CPVM)

So your browser needs to be able to reach the Public interface/IP of the CPVM


2. There is no OpenVPN client - there are 2 VPN things in CloudStack
--- regular "Isolated network" provides only remote VPN (from your desktop/laptop) - it's L2TP/IPsec with pre-shared key
--- VPC provides the same, PLUS provides site-2-site VPN (industry standard ipsec tunnel - ike1/2, phase1/2 etc)

Hope that helps a bit - so for remote VPN, on your desktop/client you use builtin clients, not OpenVPN etc.

**Comment by tampler** [comment]
@weizhouapache Hello Wei
Which cmk command should I use to obtain my current networking config, similar to [this one](https://github.com/apache/cloudstack/blob/main/tools/devcloud-kvm/devcloud-kvm-advanced.cfg)

**Comment by shwstppr** [comment]
@tampler you will have to use multiple APIs to setup zone with that config. Easier would be to use UI.
For API you may refer this python script, it may give some hints https://github.com/apache/cloudstack/blob/main/tools/marvin/marvin/deployDataCenter.py

**Comment by tampler** [comment]
@shwstppr Thanks a lot ! Will take a look into that

**Comment by tampler** [comment]
Anybody knows how to set up an ext access to SystemVMs and Guest VMs? I set up an Advanced Zone and was able to ssh to my SystemVMs thru a local link (169.254.x.x) from the host. How do I do that from a remote host? Thanks
![network0](https://user-images.githubusercontent.com/2816743/128893857-744c223f-c3bd-4676-920f-b537c26feda5.png)

**Comment by rhtyd** [comment]
@tampler trying to access your user-VMs by their private IPs via OpenVPN on KVM host itself where VMs are running is breaking network isolation (assuming you're using VLANs and it is an advanced zone) and is not recommended. You may look into firewall/portforwarding, or use VPN of the isolated network or the VPC. Based on what you've described you probably want a shared network without VLAN (so even a basic zone with security groups, or adv zone with SG would do). If this is a dev-test setup you're trying to set up you can use https://github.com/shapeblue/mbx

**Comment by tampler** [comment]
Thanks everyone for the discussion. Here's the bottom line response to my initial question

1. If you use a `shared` network, all VMs will be accessible by Public IPs
2. If you use VPC or a simple `isolated` network, all VMs will be accessible thru the Virtual Router IP (its public interface). Firewall and port forwarding should be set properly
3. It's not recommended to mix Publicly and Privately accessible VMs. Better, create a separate network for each use case
