### ISSUE TITLE
Minimum required IP range for a single ZONE

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5235]
##### ISSUE TYPE

 * Documentation Request

##### COMPONENT NAME

~~~
Zone Configuration
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### OS / ENVIRONMENT

Ubuntu 20.04.2
MySql 8.0.25
cmk 6.1.0

##### SUMMARY

I've created a zone with only one spare external IP for both Management and Guest networks. 
When I launch a zone, SystemVM won't start with the following error: 
```
2021-07-22 13:16:36,962 INFO  [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-28:ctx-0fb05ec3 job-6/job-4039 ctx-44ce61e9) (logid:0d978522) Insufficient capacity       
com.cloud.exception.InsufficientAddressCapacityException: Insufficient address capacityScope=interface com.cloud.dc.Pod; id=1  
```
Questions: 

1. What's the MINIMUM IP range I need to have for both Management and Guest networks?
2. Can I use VPN range for the Guest network

This is related to #5234 

I need to buy a Public IP range from my provider, so need to know the minimum viable range

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Assign the minimal external IP range
Can choose between external and VPN IPs
~~~

##### ACTUAL RESULTS

~~~
SystemVM fails to boot due to "Insufficient address capacity ..."
~~~

**Comment by weizhouapache** [comment]
@tampler what type of zone do you use ?

**Comment by tampler** [comment]
I'm using the Basic Zone. I bought 3 ext IPs from my provider. 

IP0 - NIC, cloudbr0
IP1 - Management Range [IP1:IP1]
IP2 - Guest Range [IP2:IP2]

With such setup, I'm still unable to launch a single KVM VM due to the "Insufficient address capacity"

**Comment by weizhouapache** [comment]
> I'm using the Basic Zone. I bought 3 ext IPs from my provider.
> 
> IP0 - NIC, cloudbr0
> IP1 - Management Range [IP1:IP1]
> IP2 - Guest Range [IP2:IP2]
> 
> With such setup, I'm still unable to launch a single KVM VM due to the "Insufficient address capacity"

you need add least 2 public ips in cloudstack systemvms (1 for console proxy /cpvm, 1 for secondary storage/ssvm).
you can use internal ip as management ips.

**Comment by tampler** [comment]
Hello, @weizhouapache Thanks for your answer.

I set up a basic zone and was able to launch a KVM guest VM with NFS Primary/Secondary + LocalStorage enabled

However, I see 3 Public IPs have been consumed consumed + 2 Managent IPs when all VMs are expunged. I have  two SystemVMs running. How do I check who consumes my 3-rd Public IP? 

![dash](https://user-images.githubusercontent.com/2816743/127198704-8022b31a-515e-445b-b2a0-76e14e94b8b7.png)

**Comment by weizhouapache** [comment]
@tampler the 3rd IP is used by the virtual router of the default network which acts as the dhcp/dns/userdata server.
you can check the "Virtual Router" tab in network details page, or infrastructure -> Virtual Routers.

**Comment by tampler** [comment]
Okay, thanks a lot for your explanations. This should be updated in documentation as well.

To summarize

For a Basic Zone setup with a single server (mgmt + host + local db + local storage) and a single guest VM, the minimum required IP number is actually 7, split into two non-overlapping ranges of 5 IPs and 2 IPs

From Range 0 ( 5 IPs ) :

One - for the server NIC itself
Two - for Management Interface 
One - for Virtual Router
One - for guest VM

From Range 1:
Two - for System VMs

And I guess, adding a new host costs 2 more management IPs + the number of Public IPs for each guest VM, which is planned to deploy on that host. 

Is that correct?

**Comment by weizhouapache** [comment]
@tampler 
it is not necessary to assign public ip to hosts, you can use private ip (see RFC1918)

**Comment by tampler** [comment]
@weizhouapache Can I have a setup with a NAT VPN bridge, which consumes one Public IP + any number VPN backed IPs (e.g. 10.205.x.x) fo guest VMs? See #5234 for more info

**Comment by rhtyd** [comment]
@tampler the minimum public IP range to get CloudStack up and running depends on the type of the zone, and your use-cases/workloads. Only you can answer that. For a typical adv zone on KVM without SG, you'd need at least the following public IPs:
1xSSVM
1xCPVM
1xVR (at least one isolated network)
1xmanagment server (For management server it's optional and depends if you want public accessibility)
Or, just one public IP for the management server or your VPN server such that rest of your IP ranges are all private (RFC1918).

**Comment by tampler** [comment]
Okay thanks everyone for your comments. This will do for now
