### ISSUE TITLE
Unable to create a deployment for VM

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5240]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, VirtualMachines
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

Basic Zone, single cloudbridge0
system.vm.use.local.storage -> true
NFS backed Primary and Secondary storage

##### OS / ENVIRONMENT

Ubuntu 20.04.2
cmk 6.1.0
Hypervisor - KVM

##### SUMMARY

I was able to setup a Basic Zone, launch SystemVMs and observe host resources.

![Screenshot from 2021-07-23 19-04-38](https://user-images.githubusercontent.com/2816743/126810427-989c3349-24ee-47f6-8b08-6312d9261997.png)

SystemVMs look good as well:
```
  "count": 2,
  "systemvm": [
    {
      "id": "7ba2c0b0-97bd-40c2-a249-b12a88cdcdbc",
      "state": "Running"
    },
    {
      "id": "1fb9110e-c9c0-42ea-a698-a5382d87bcf6",
      "state": "Running"
    }
  ]
```

I also added my own ISO template with Ubuntu. However, when I try to create an instance, I'm getting the following: 
```


 "jobresult": {
    "errorcode": 533,
    "errortext": "Unable to create a deployment for VM[User|i-2-207-VM]"
  },
```
And I see the following error in log:
```
2021-07-23 18:56:18,148 INFO  [o.a.c.a.c.u.v.StartVMCmd] (API-Job-Executor-8:ctx-603edfec job-652 ctx-530e791d) (logid:020769fb) Unable to create a deployment for VM[User|i>
com.cloud.exception.InsufficientServerCapacityException: Unable to create a deployment for VM[User|i-2-207-VM]Scope=interface com.cloud.dc.DataCenter; id=1
```
The full log is [here](https://github.com/apache/cloudstack/files/6869967/out.log)

Question: Why am I getting this? I see my primary and secondary storage and do not understand what the problem is

##### STEPS TO REPRODUCE

~~~
start virtualmachine id=b434cf98-7f39-42bf-bb72-fae81d1872fc
~~~

##### EXPECTED RESULTS

~~~
Guest VM is started
~~~

##### ACTUAL RESULTS

~~~
Guest VM fails to start
~~~

**Comment by DaanHoogland** [comment]
@tampler , it looks like you don't have a cluster with suitable hosts, a few lines above the final failure:
```
2021-07-23 18:56:18,019 DEBUG [c.c.d.FirstFitPlanner] (API-Job-Executor-8:ctx-603edfec job-652 ctx-530e791d) (logid:020769fb) The clusterId list for the given offering tag: []
2021-07-23 18:56:18,019 DEBUG [c.c.d.FirstFitPlanner] (API-Job-Executor-8:ctx-603edfec job-652 ctx-530e791d) (logid:020769fb) No clusters found after removing disabled clusters and clusters in avoid list, returning.
```

**Comment by tampler** [comment]
Great! And what do I do? 

Seems like I do have a host, but CS can't use it

```
(localcloud) 🐱 > list hosts filter=id,name, state=up
{
  "count": 3,
  "host": [
    {
      "id": "d75b73ff-d290-4075-bd6a-4cff06b5e82a",
      "name": "s-203-VM"
    },
    {
      "id": "6216ee07-be7f-4c60-a0ca-1eb6114d2d20",
      "name": "v-202-VM"
    },
    {
      "id": "ee4a7525-9925-493c-99d1-b13230ea16d2",
      "name": "cloud"
    }
  ]
}
```

**Comment by slavkap** [comment]
@tampler, does the compute offering from which you're trying to deploy a VM has host tag, and no one of your hosts has that tag?

There also another thing from the logs which bothers me and you're trying to deploy a VM on Zone 1:

> 2021-07-23 18:56:14,076 DEBUG [c.c.c.ConsoleProxyManagerImpl] (consoleproxy-1:ctx-10e297e5) (logid:7f365bb4) Zone 1 is not ready to launch console proxy yet
> 2021-07-23 18:56:14,289 DEBUG [c.c.c.ClusterManagerImpl] (Cluster-Heartbeat-1:ctx-1062f9e0) (logid:43c58a71) Detected management node left, id:2, nodeIP:185.185.58.54
> 2021-07-23 18:56:14,289 INFO  [c.c.c.ClusterManagerImpl] (Cluster-Heartbeat-1:ctx-1062f9e0) (logid:43c58a71) Trying to connect to 185.185.58.54
> 2021-07-23 18:56:14,290 INFO  [c.c.c.ClusterManagerImpl] (Cluster-Heartbeat-1:ctx-1062f9e0) (logid:43c58a71) Management node 2 is detected inactive by timestamp but is pingable
> 2021-07-23 18:56:14,631 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-299168c9) (logid:0f541b40) System vm template is not ready at data center 1, wait until it is ready to launch secondary storage vm
> 2021-07-23 18:56:14,632 DEBUG [o.a.c.s.SecondaryStorageManagerImpl] (secstorage-1:ctx-299168c9) (logid:0f541b40) Zone 1 is not ready to launch secondary storage VM yet

you can check if a templete is downloaded and ready for a specific zone here:
![image](https://user-images.githubusercontent.com/51903378/126987667-6583a38e-47f2-4eaa-97b6-1da7e963916c.png)

**Comment by slavkap** [comment]
One more question ... you're trying to start a VM, but what is its status? Is it an `Error`? Can you share the log when you try to deploy a VM?

**Comment by tampler** [comment]
Hello @slavkap 

1. Yes, I'm pretty sure that I have successfully downloaded the ISO and setting up from it.
2. I tried to add the host and start the VM with and without the matching host tags. The result is the same and not starting

The latest [logs](https://github.com/apache/cloudstack/files/6879328/out.log)

Below are my setup and error screenshots

ISO template
![Screenshot from 2021-07-26 18-04-24](https://user-images.githubusercontent.com/2816743/127014430-f510cf44-be9c-4b82-a51d-42b1ba6d6dd3.png)

System VMs
![Screenshot from 2021-07-26 18-15-16](https://user-images.githubusercontent.com/2816743/127014480-de1c3657-906b-4a33-98e4-d3db9eea514a.png)

Host
![Screenshot from 2021-07-26 18-02-57](https://user-images.githubusercontent.com/2816743/127014572-bd63be5a-5ff7-40fe-aa38-346eb7a96538.png)

Error
![Screenshot from 2021-07-26 18-13-14](https://user-images.githubusercontent.com/2816743/127014650-9a5bed14-7b6b-4d05-8ebd-2f9d0aaf36d2.png)

**Comment by tampler** [comment]
And this is my agent properties:
```
cluster=1
pod=1
resource=com.cloud.hypervisor.kvm.resource.LibvirtComputingResource
private.network.device=cloudbr0
domr.scripts.dir=scripts/network/domr/kvm
router.aggregation.command.each.timeout=600
guest.network.device=cloudbr0
hypervisor.type=kvm
public.network.device=cloudbr0
port=8250
zone=1
local.storage.uuid=acfa6fdc-259f-4608-b1c1-d99d11288164
host=185.185.58.54@static
guid=76fcdbe8-1954-4888-a267-0d3c1f6c3043
LibvirtComputingResource.id=1
workers=5
iscsi.session.cleanup.enabled=false
```

**Comment by slavkap** [comment]
Thanks for the info @tampler! What is your primary storage and the storage scope - Zone/Cluster or local storage?

**Comment by slavkap** [comment]
@tampler 


> * Host is in the `Power State = disabled` and is NOT found during VM deployment and instantiation

in this configuration, that is normal

> * IP is NOT assigned to the guest VM

Yes, because the VM is not allocated yet

> * As per the log, `host = 1`, which may be incorrect, since all ids should be a UUID

This has to be the DB id, and the UUID from the UI corresponds to this ID.

Unfortunately, this error could appear in a lot of scenarios, and it's hard to debug. That's why I'm asking for more information, and if it is not a problem to share it
 - You have one NFS primary storage, and what is its scope - Zone-wide, Cluster-wide?
 - Why `system.vm.use.local.storage = true`? Do you intend to use Local primary storage? 
 - Can you share the information of the compute offering that you're using to deploy the Guest VM? Does it have storage/host tags? What is the `storagetype`?

**Comment by tampler** [comment]
@slavkap Thanks a lot for your help and bearing with me. You have spent pretty much time already helping me and I appreciate your attention and afford

Since we don't currently have an efficient communication channel, which I'm trying to solve in #5243, would that be a bad idea if I provide you a root access on my server so that you could take a look? It's a fresh test server with no sensible data and having access to it may save a lot of time for debugging

I can send credentials to my test server on your personal email, telegram or whats app

Thanks a lot again,
Boris

**Comment by slavkap** [comment]
@tampler, no problem with this! With the access to your test, I'm not sure is it right. Maybe somebody from the community has to tell. Is it possible to provide the information from these API calls?
`list storagepools`
`list serviceofferings id=(The UUID of the service offering with which you are deploying a VM)`
And - Why system.vm.use.local.storage = true? Do you intend to use Local primary storage?

Also, there is a slack channel for CloudStack, but the community prefers the mailing lists and Git issue requests

**Comment by tampler** [comment]
@slavkap here's more info

1. Turned off local storage with `system.vm.use.local.storage = false`
2. Storagepools
```
(localcloud) 🐱 > list storagepools
{
  "count": 1,
  "storagepool": [
    {
      "clusterid": "a1280df8-8e44-43d4-90b4-7fdb9509831b",
      "clustername": "cluster0",
      "created": "2021-07-26T16:44:40+0300",
      "disksizeallocated": 196648,
      "disksizetotal": 491180957696,
      "disksizeused": 21191286784,
      "id": "acfa6fdc-259f-4608-b1c1-d99d11288164",
      "ipaddress": "x.x.x.x",
      "name": "cloud-local-acfa6fdc",
      "overprovisionfactor": "2.0",
      "path": "/var/lib/libvirt/images",
      "podid": "c42f243e-2eef-4ccb-bc66-7ceaf919cbab",
      "podname": "pod0",
      "provider": "DefaultPrimary",
      "scope": "HOST",
      "state": "Up",
      "storagecapabilities": {
        "VOLUME_SNAPSHOT_QUIESCEVM": "false"
      },
      "type": "Filesystem",
      "zoneid": "eb9927c5-2c61-404c-8c94-c77c9cc407a6",
      "zonename": "zone0"
    }
  ]
}
(localcloud) 🐱 > 
```

3. Service offering
```
(localcloud) 🐱 > list serviceofferings id=5c9a9721-037c-4ddf-91a9-d38f5698d71b 
{
  "count": 1,
  "serviceoffering": [
    {
      "cacheMode": "writeback",
      "cpunumber": 2,
      "cpuspeed": 1500,
      "created": "2021-07-26T19:32:56+0300",
      "defaultuse": false,
      "displaytext": "NWS Base-0",
      "id": "5c9a9721-037c-4ddf-91a9-d38f5698d71b",
      "iscustomized": false,
      "issystem": false,
      "isvolatile": false,
      "limitcpuuse": false,
      "memory": 4096,
      "name": "NWS Base-0",
      "networkrate": 100,
      "offerha": false,
      "provisioningtype": "thin",
      "rootdisksize": 10,
      "storagetype": "shared"
    }
  ]
}
```

**Comment by slavkap** [comment]
Ok, so you're using Local primary storage, and you have to enable it again `system.vm.use.local.storage`.
Your service offering is not right for local storage. The `"storagetype": "shared"` has to be '"storagetype": "local"'

**Comment by slavkap** [comment]
I forgot to tell you that there is no option to update it with the API. You can change the value through the DB or to create a new compute offering

**Comment by tampler** [comment]
@slavkap 

Well, I was able to remove that offering and created a new one with the `Local` storage. I also had to turn on the `Local` storage in Zone settings, editing the Zone.

Now I created a modest compute offering with 2x1GHz, 4096MB RAM and 10GB Root Volume. 
I'm getting now the `Server Insufficient Capacity` error, which is ridiculous, since I have much more on my server.

Pls check the log atttached. Any new ideas? More commands to execute from `cmk` ?

[out.log](https://github.com/apache/cloudstack/files/6880087/out.log)

**Comment by slavkap** [comment]
The error msg from the log says that there isn't an IP address for the guest VM. The SQL query is:

> SELECT user_ip_address.id, user_ip_address.account_id, user_ip_address.domain_id, user_ip_address.public_ip_address, user_ip_address.data_center_id, user_ip_address.source_nat, user_ip_address.allocated, user_ip_address.vlan_db_id, user_ip_address.one_to_one_nat, user_ip_address.vm_id, user_ip_address.state, user_ip_address.mac_address, user_ip_address.source_network_id, user_ip_address.network_id, user_ip_address.uuid, user_ip_address.physical_network_id, user_ip_address.is_system, user_ip_address.vpc_id, user_ip_address.dnat_vmip, user_ip_address.is_portable, user_ip_address.display, user_ip_address.rule_state, user_ip_address.forsystemvms, user_ip_address.removed, user_ip_address.created 
FROM user_ip_address  INNER JOIN vlan 
ON user_ip_address.vlan_db_id=vlan.id  
INNER JOIN pod_vlan_map 
ON user_ip_address.vlan_db_id=pod_vlan_map.vlan_db_id 
WHERE user_ip_address.data_center_id = 2  
AND user_ip_address.allocated IS NULL  
AND user_ip_address.removed IS NULL  
AND  (vlan.vlan_type = 'DirectAttached'  AND vlan.network_id = 209 ) 
AND (pod_vlan_map.pod_id = 2 ) 
ORDER BY user_ip_address.forsystemvms ASC , user_ip_address.vlan_db_id ASC  LIMIT 0, 1 FOR UPDATE;

Can you test this with the respective values of your setup?

**Comment by tampler** [comment]
Sure, here's the select output
![Screenshot from 2021-07-26 22-44-50](https://user-images.githubusercontent.com/2816743/127049268-ff6bff3c-4a1a-45f0-833c-a199f18b0b08.png)

**Comment by tampler** [comment]
@slavkap Yes, looks like I have two zombie SystemVMs, which consumed all my  spare External IPs, allocated to Zone.
How do I remove a SystemVM? Don't see a command in `cmk` nor in GUI

**Comment by slavkap** [comment]
I'm really confused :smile:
From the log you're trying to list address on `pod = 1`
`com.cloud.exception.InsufficientAddressCapacityException: Insufficient address capacityScope=interface com.cloud.dc.Pod; id=1`
but from your screen shot you're looking in `pod_vlan_map.pod_id=2`

About the system VMs you can destroy them from the GUI or with cmk `destroy systemvm id=uuid of the sysvm`

**Comment by tampler** [comment]
@slavkap Great news! I finally made it work. After (almost) two weeks playing with CloudStack installation, settings and tuning.

Here's what I have now

![Screenshot from 2021-07-26 23-01-43](https://user-images.githubusercontent.com/2816743/127051663-eae4f7f2-5321-452d-8603-d9208865c16b.png)

Key lessons learned:

1. First make sure that two SystemVMs are up & running
2. Make sure you that have enough spare External IPs for Guest VMs
3. Make sure that your Global Settings, Zone and Compute Offering support `Local Storage`

That's pretty much it... I think now I owe you to update some CloudStack docs for Ubuntu Installation.

Thanks again for your great help, support and patience 

Boris

**Comment by slavkap** [comment]
That's great, @tampler! :)

**Comment by tampler** [comment]
Okay, I'm back to main issue from another angle. Again getting the same error as a result of the following sequence

1. Uploaded custom ISO
2. Launched an instance from that ISO
3. Made changes, stopped the instance
4. Went to Volumes -> Instance Volume -> Make a Template from Volume
5. When the template was created from that volume, I shut down the original instance
6. Then trying to create an instance for the same offering and that volume

Got the same issue - `Error - Unable to create a deployment for VM`
Here's the [log](https://github.com/apache/cloudstack/files/6888932/out.log)

**Comment by tampler** [comment]
Moved to #5250

**Comment by kalina-p** [comment]
I have a similar problem and I have run out of ideas. Version 4.16

all based on the suse distribution.

I get an error while creating the machine. There is no longer any idea what to do wrong. Please help


Attached the log
[cloudstack-log.txt](https://github.com/apache/cloudstack/files/7945284/cloudstack-log.txt)

**Comment by slavkap** [comment]
Hi @kalina-p, can you also share the log from the agent and the versions of qemu/libvirt?

**Comment by kalina-p** [comment]
Hello


Sure

that is my kvm host:

cs-kvm:~ # libvirtd --version
libvirtd (libvirt) 7.1.0

cs-kvm:~ # lscpu | egrep 'Model name|Thread|CPU\(s\)'
CPU(s):                          10
On-line CPU(s) list:             0-9
Thread(s) per core:              1
Model name:                      Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz

cs-kvm:~ # free -g
              total        used        free      shared  buff/cache   available
Mem:             39           2          35           0           1          36
Swap:             0           0           0

[cloudstack-kvm-agent.txt](https://github.com/apache/cloudstack/files/7950914/cloudstack-kvm-agent.txt)

**Comment by kalina-p** [comment]
ok, problem solved.
changed in kvm /etc/cloudstack/agent/agent.properties file lines:
from
guest.cpu.mode=custom|host-model|host-passthrough
to
guest.cpu.mode=host-passthrough
and removed 
guest.cpu.model=from /usr/share/libvirt/cpu_map.xml and
guest.cpu.features=vmx ept aes smx mmx ht

now worked well.

Many thanks for help me

**Comment by cisaacson** [comment]
Just a note. The same error about the architecture being empty happens with 7.x releases if you try to install on Ubuntu `22.x`, they work fine on `20.x`. It took some time to figure out that was the issue as the error on install was misleading. The System Requirements doc says Ubuntu `12.x` or later, so that also didn't lead to a solution. It would be good to either document Ubuntu `20.x` is required, or to fix the packaging in the later releases (ideal).
