### ISSUE TITLE
Discord Channel for CloudStack

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5243]
I'm new to CloudStack and already spent a week trying to launch a guest KVM VM with a very basic setup with no luck . 

This is very annoying, given the pitch for CloudStack and its development history since 2008.

Currently, I can only ask questions here on github and skim thru pretty complex and ambiguous docs.

I also saw that the core team and some devs communicate with `Mailing Lists`. Like Seriously? Mailing lists in the mid 2021 ??? 

How about moving to `Discord` to enable a more efficient communication between current and future users and developers?

PS:
I can create and delegate the chat server on `Discord` to the core team. However, I believe it would be better if someone from core team members or major contributors takes a lead for this.

**Comment by kiwiflyer** [comment]
@tampler We do have a slack channel available. You can signup here - https://docs.google.com/forms/d/1qewV4Ox3SR1WXvfZLi9tyP1HHhvKSqI0_zVK4V4dCvw

The old IRC channel has been retired.

**Comment by rhtyd** [comment]
@tampler you're free to start a Discord channel or any other online community. The project follows the ASF on its functioning so anything that does not happen on the mailing lists, hasn't happened. As Simon suggests you can join the Slack channel, however, you are encouraged to join the mailing lists and ask questions there as most people in the community would reply on the MLs but may not be online 24x7 on Slack and other communication platforms.

Closing on this remark and that the report is not an issue in CloudStack codebase. If you want to start a Discord etc pl discuss with the community on the dev/users ML.
