### ISSUE TITLE
Can't add a host in Advanced Zone - Unable to add the host

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5251]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Zone, management
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

KVM
Advanced Zone
Single server installation (mgmt, host, db, storage)
LocalStorage enabled

##### OS / ENVIRONMENT

Ubuntu 20.04.2

##### SUMMARY

I'm able to add a host X to the Basic Zone
However, I'm getting an error when I try to add the second (Advanced) Zone and add the same host X to it.

I've also tried removing the host X from the Basic Zone first, expunging all VMs and SystemVMs and restarting cloudstack-management and cloudstack-agent services. Still getting the same exception 

[log](https://github.com/apache/cloudstack/files/6896394/out.log)

##### STEPS TO REPRODUCE

~~~
1. Setup CloudStack on a single server (mgmt, host, db, storage)
2. Add a Basic Zone
3. Add the host X to the Basic Zone
4. Add Advanced Zone
5. Add  host X to the Advanced Zone
6. Notice the exception - Unable to add the host
7. Shut down the Basic Zone
8. Remove host X from the Basic Zone
9. Add host X to the Advanced Zone
10. Notice the exception - Unable to add the host
~~~

##### EXPECTED RESULTS

~~~
1. Add a host to the Advanced Zone
2. Add the same host X to both Basic and Advanced zones
~~~

##### ACTUAL RESULTS

~~~
1. Can add a host to the Basic Zone
2. Fail to add a host to the Advanced Zone
~~~

**Comment by weizhouapache** [comment]
@tampler was the username 'root' when you added the host ?

**Comment by weizhouapache** [comment]
@tampler you can not add same host to multiple zones. it is not an issue.

**Comment by weizhouapache** [comment]
@tampler 
by the way, could you subscribe to cloudstack users mailing list and ask question in mailing list ?
https://cloudstack.apache.org/mailing-lists.html

**Comment by tampler** [comment]
@weizhouapache 
Hello, that's not a question, that's a BUG report. Have you looked into a log attached? There's an exception adding a host in Ubuntu for an Advanced Zone, please re-open my issue

**Comment by tampler** [comment]
> @tampler
> by the way, could you subscribe to cloudstack users mailing list and ask question in mailing list ?
> https://cloudstack.apache.org/mailing-lists.html
No, sorry, I can't. Not using mailing lists

**Comment by slavkap** [comment]
@tampler, it is failing because of this
`sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper` and I guess you have to allow `sudo` to be used without a password

**Comment by tampler** [comment]
@slavkap Wow thanks a lot for your hint. You are my CloudStack Failry now :grinning: :grinning: :grinning: :innocent: 
Sure, adding my non-root user to sudoers, who don't need password made the trick

Thanks a lot for your patience and a wise help. I really appreciate
Closing the issue
