### ISSUE TITLE
Out-of-band Management visual Power state

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5255]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### SUMMARY

When Out-of-band Management is configured under infrastructure > Hosts > Power State indication circle is not turning green.

##### STEPS TO REPRODUCE

~~~
Configure Out-of-band Management
~~~

##### EXPECTED RESULTS

~~~
Old interface:
~~~
![ipmi_old](https://user-images.githubusercontent.com/30048481/127495664-708522a1-6823-4f21-8d07-bb516d25833d.png)

##### ACTUAL RESULTS

~~~
New interface:
~~~
![ipmi_new](https://user-images.githubusercontent.com/30048481/127495688-5325327d-c972-4abb-bb4b-3cc9d4e64a26.png)

**Comment by nvazquez** [comment]
Closing as this is fixed by PR #5278
