### ISSUE TITLE
Resource state insecure missing

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5256]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### OS / ENVIRONMENT

KVM

##### SUMMARY

When KVM host has expired or not provisioned host security key old interface in host summary Resource state colon is showing status Insecure new interface is showing Enabled. Only way to determinate in new interface that secure key must be provisioned is clicking on each host and searching for Secured = false.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
when secure = false show resource state as Insecure
~~~

##### ACTUAL RESULTS

~~~
when secure = false resource state is Enabled
~~~

**Comment by rhtyd** [comment]
FIxed in https://github.com/apache/cloudstack/pull/5292
