### ISSUE TITLE
cpu capacity

### ISSUE THREAD

**Issue by digitalgust** [apache/cloudstack#5261]
how to change cpu capacity?

 i have a cpu that amd r7 5700u，cloudstack detected 16 * 1.8GHz, but full of  core can boost to 16 * 3.3GHz, can i change it manually？

**Comment by nvazquez** [comment]
Hi @digitalgust, which hypervisor is your host running? The CPU capacity is obtained from the hosts and persisted on the `host` table in the database. You can set an overcommit factor for CPU under 'Configuration -> Global Settings -> cpu.overprovisioning.factor'

**Comment by digitalgust** [comment]
thank you, i changed the database and vn can migrate to the host

**Comment by nvazquez** [comment]
@digitalgust thanks, I'm closing this issue
