### ISSUE TITLE
CloudStack UI login is slow

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#5266]
The CloudStack UI in 4.15+ uses API auto-discovery to generated dynamic UI views, actions, paths etc. It uses `listApis` to find list of allowed APIs for the user/role which is generated on per user/account basis than per-role basis. Is there a way to make this faster, for example (1) reduce the size of list API response (based on what is actually used/consumed by the UI, for example in the json response, the params part is used but the response part may not be used), (2) pre-cache and host is statically the response based on Roles in the system than accounts, since every account has a role, (3) ship in-built json maps with the UI for default roles?, (4) run the API discovery after login screen/dashboard shows (change in view would make the UI load faster for the users)?

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

**Comment by weizhouapache** [comment]
some part of code to check access on commands can be optimized.

for example, it is not necessary to get Account and Role/RoleType in the checkAccess on each command.
we can load it only once and use it in all checkAccess on commands.

```java
        Account account = accountService.getAccount(user.getAccountId());
        if (account == null) {
            throw new PermissionDeniedException("The account id=" + user.getAccountId() + "for user id=" + user.getId() + "is null");
        }

        final Role accountRole = roleService.findRole(account.getRoleId());
```
https://github.com/apache/cloudstack/blob/main/plugins/acl/dynamic-role-based/src/main/java/org/apache/cloudstack/acl/DynamicRoleBasedAPIAccessChecker.java#L73-L78

and
```java
        Account account = accountService.getAccount(user.getAccountId());
        if (account == null) {
            throw new PermissionDeniedException("The account id=" + user.getAccountId() + "for user id=" + user.getId() + "is null");
        }

        RoleType roleType = accountService.getRoleType(account);
```
https://github.com/apache/cloudstack/blob/main/plugins/acl/static-role-based/src/main/java/org/apache/cloudstack/acl/StaticRoleBasedAPIAccessChecker.java#L78-L83

**Comment by DaanHoogland** [comment]
> some part of code to check access on commands can be optimized.
> 
> for example, it is not necessary to get Account and Role/RoleType in the checkAccess on each command.
> we can load it only once and use it in all checkAccess on commands.

good call @weizhouapache , we'll just have to make sure it is still functional for individual API calls as well. Not sure how much speed gain it will yield, but at least something.
