### ISSUE TITLE
v4.15.1.0 New UI - ListApis returns a gateway timeout

### ISSUE THREAD

**Issue by manuthu** [apache/cloudstack#5267]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1.0
~~~

##### OS / ENVIRONMENT

```
[root@cloudstack ~]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

##### SUMMARY

We recently upgraded our cloudstack environment from v4.13.0.0 to v4.15.1.0.  
The error we currently are experiencing is when login. An error is raised `Exception caught while discovering features`
This prevents users from accessing the portal. 

On inspecting the network, the `listApis` call made during the  Login discovery phase returns a `504 - Gateway timeout error. `

This is also reproducable while using cloudmonkey.

```
🐱 > set display text

 🐱 > list apis
[debug] ExecLine line:list apis
[debug] ExecCmd args: list, apis
[debug] NewAPIRequest API request URL:https://portal.nbo.angani.co/client/api?apiKey=xxxxxx&command=listApis&response=json&signature=xxxx
[debug] NewAPIRequest response status code:504
[debug] NewAPIRequest response body:<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>

🙈 Error: failed to decode response

```

##### STEPS TO REPRODUCE

~~~

🐱 > set display text
🐱 > list apis


~~~

##### EXPECTED RESULTS

~~~
A `HTTP 200` from the server. 

~~~

##### ACTUAL RESULTS

~~~

[debug] NewAPIRequest response body:<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>

~~~

**Comment by rhtyd** [comment]
Hi Mike, I believe this is not a CloudStack issue but issue of an intermediary nginx which is likely used as reverse proxy. You need to check and increase timeout settings for nginx. Can you try testing the mgmt server directly?

**Comment by manuthu** [comment]
Thanks for the response @rhtyd 

Looks like the request was timing out at the proxy. 
I've increased the timeout [settings](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) at the proxy and now everything is ok.

```
proxy_read_timeout 300s
```

The Api is however really slow - Takes about a min and a half to respond. I see you already raised an issue on the same [here](https://github.com/apache/cloudstack/issues/5266)

Cheers
