### ISSUE TITLE
replace import url for less.js with local lib 

### ISSUE THREAD

**Issue by DK101010** [apache/cloudstack#5277]
Our Browser they have access to Cloudstack runs in a isolated environment with restricted access to the internet . Therefore runs Cloudstack into a timeout while it tries to loading less.min.js and the result is that it takes a very long time for the login page to load.

Lib: https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js

I want to replace this lib with a local version but I have no clue how. 

This Lib will be added during the build in the index.html an I guess it comes from a node module.
Install of the less.js with version 2.7.2 via npm runs into an error during the build. 

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

~~~
N/A
~~~
##### OS / ENVIRONMENT

~~~
N/A
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by mib1185** [comment]
The `https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js` is default loaded by [`antd-theme-webpack-plugin` ](https://www.npmjs.com/package/antd-theme-webpack-plugin/v/1.3.9)
It is possible to use an url or path as option `lessUrl` (should be added in [`ui/theme.config.js`](https://github.com/apache/cloudstack/blob/379454caae76279329c52aa6ae3eea389741d935/ui/theme.config.js)).

So easiest solution would be to download `https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js` during build, place it in `<webroot>/js` and refer it as relativ path in `lessUrl` 🤔
