### ISSUE TITLE
UI: fields for IP in New Form Wizard are too narrow

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5286]
ACS 4.15.1

New zone wizard - IPs can't fit/show correctly in the IP address fields - fields are too "short"

![image](https://user-images.githubusercontent.com/45762285/128414403-7443b392-77db-441b-9f62-24146dc4f2b1.png)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5287
