### ISSUE TITLE
Compute Offering and Disk Size is not showing entries

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5290]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### SUMMARY

When creating new instance Compute Offering and Disk Size is not showing entries.

##### STEPS TO REPRODUCE

~~~
Create instance on ACS with several pages of compute and disk offerings.

Edit:
From user/admin perspective it looks that select is happening on all 340 items and then those who are not belonging 
to DOMAIN are filtered as invisible. Those who stay visible are not reordered afterwards and stay on pages where they 
initially were assigned on first filter/select. Pressing on page numbers one by one will show you all offerings assigned 
to domain but in order they were first filtered/selected and assigned to page numbers.

~~~
![Screenshot 2021-08-07 130418](https://user-images.githubusercontent.com/30048481/128596785-35498576-be07-45f3-9fdf-8a16bea4e3b0.png)
![Screenshot 2021-08-07 130505](https://user-images.githubusercontent.com/30048481/128596787-be66ff88-c35c-42b8-ab52-f4ec725908f3.png)
![Screenshot 2021-08-07 130610](https://user-images.githubusercontent.com/30048481/128596788-7c0e4c15-842e-40a8-aa84-0e96d4eed983.png)
![hdd Screenshot 2021-08-07 130757](https://user-images.githubusercontent.com/30048481/128596790-8bff5fc8-5ad1-4818-98a1-fdf14b8d0455.png)

Same problem also happens when you press on Scale VM.
![Screenshot 2021-08-07 133232](https://user-images.githubusercontent.com/30048481/128597301-74989e3a-3c32-4188-882f-190810e4ad5f.png)

##### EXPECTED RESULTS

~~~
Showing 10 Compute Offerings and Disk Size per page by default
~~~

##### ACTUAL RESULTS

~~~
Not showing 10 Compute Offerings and Disk Size per page by default
~~~

**Comment by rhtyd** [comment]
@kricud are you able to see the list in the legacy 4.15 UI?

**Comment by kricud** [comment]
@rhtyd in legacy ui it works as expected
![Screenshot 2021-08-09 132312](https://user-images.githubusercontent.com/30048481/128692609-84f62589-7354-4b08-a522-33b27c82c0a3.png)

**Comment by davidjumani** [comment]
@kricud can you check the browser console logs ?

**Comment by kricud** [comment]
@davidjumani don’t see anything suspicious in console logs.

The way how to reproduce this case can be done as following: Create 4 domains ROOT/dom1, ROOT/dom1/subdom1, ROOT/dom1/subdom2 and ROOT/dom1/subdom3. Create 11 compute offerings and assignee them to ROOT/dom1/subdom1 another 11 and assign them to ROOT/dom1/subdom2 another 11 assign them to ROOT/dom1. (order of creation is important) Create account in ROOT/dom1/subdom3 login and try to create instance you should see only compute offerings from ROOT/dom1 in 3rd page.

**Comment by davidjumani** [comment]
@kricud Was able to reproduce it. It appears to be a backend issue. Will look into adding a fix

**Comment by nvazquez** [comment]
Closing as PR 5307 is merged
