### ISSUE TITLE
Null Pointer Exception while list hosts

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5291]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

Single server setup, KVM, Advanced Network, LocalStorage enabled for Zone

##### OS / ENVIRONMENT

Ubuntu 20.04.2
Kernel: 5.13.7

##### SUMMARY

I was able to set up an Advanced Zone. Launched SystemVMs and tried to add a host. CloudStack Agent service is running, but when I try to add the host I'm getting a Null Pointer Exception, see the [log](https://github.com/apache/cloudstack/files/6950862/out.log)

Storage pools [info](https://github.com/apache/cloudstack/files/6950870/pools.log)

##### STEPS TO REPRODUCE

~~~
cmk list hosts
~~~

##### EXPECTED RESULTS

~~~
Cluster hosts are listed or empty list with REST 200
~~~

##### ACTUAL RESULTS

~~~
🙈 Error: (HTTP 530, error code 9999) <nil>
~~~

**Comment by tampler** [comment]
I also checked the SQL entries in the 'Host' table. See below
![host](https://user-images.githubusercontent.com/2816743/128634678-a30d6343-5652-4a3e-9764-23c8d3ec5a3f.png)

**Comment by rhtyd** [comment]
@tampler have you disabled local storage on the hosts, is it enabled for your zone?

Log reference seen:
```
2021-08-08 16:25:58,908 DEBUG [c.c.a.q.QueryManagerImpl] (qtp2109798150-310:ctx-8d47711c ctx-34c8bea1) (logid:92e1b525) >>>Generating Response>>>
2021-08-08 16:25:58,924 ERROR [c.c.a.ApiServer] (qtp2109798150-310:ctx-8d47711c ctx-34c8bea1) (logid:92e1b525) unhandled exception executing api command: [Ljava.lang.String;@78127f28
java.lang.NullPointerException
	at com.cloud.storage.StorageManagerImpl.isLocalStorageActiveOnHost(StorageManagerImpl.java:412)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.jav
```

**Comment by tampler** [comment]
@rhtyd  Hello Rohit

I'm not sure if that was a case. I'm evaluating CloudStack now and set everything on a single server. YES, I'm using local storage on my ZONE and locally

I was blocked by this issue and fixed it by dropping and restoring MYSQL databases. Do you want me to try to reproduce this with some corner case test?

Things started to work after database reset, but this may be an issue for CloudStack testing and usability

Best,
Boris

**Comment by nvazquez** [comment]
Hi @tampler I've tested with the latest 4.15 branch and cannot reproduce your issue, can you please verify with these packages? https://download.cloudstack.org/testing/nightly/2021-08-09/debian/4.15/

**Comment by nvazquez** [comment]
Can you also provide the output of your `storage_pool_host_ref` table? Seems like the NPE is caused by a missing entry on this table

**Comment by tampler** [comment]
@nvazquez Hello! Unfortunately, I've dropped those databases and restored from an initial backup. That said, I can't provide any extra debug info, unless you provide me a specific test.

Perhaps, it's better to close this issue for now since I can't debug it anymore

**Comment by tampler** [comment]
Hello, @nvazquez 

I see this issue is still there in 4.16.0-Snapshot, which I built from today's master. I'm getting the following:
```
cmk> list storagepools
<empty>
cmk> list hosts
🙈 Error: (HTTP 530, error code 9999) <nil>

```
![host_npe](https://user-images.githubusercontent.com/2816743/129348962-8d57296e-5266-42ff-9ca5-0cfe9f429d50.png)

**Comment by nvazquez** [comment]
@weizhouapache can you please check if this is a regression?

**Comment by weizhouapache** [comment]
> h installation. In settings, I did:
> `system.vm.use.local.storage -> true`
> `ca.plugin.root.auth.strictness -> false`

@tampler 
could you provide the `storage_pool` table in database ?

**Comment by weizhouapache** [comment]
same as what @nvazquez have tested, I cannot reproduce the issue.

there are DB records below.
```
MariaDB [cloud]> select * from storage_pool;
+----+------------------------------------------------+--------------------------------------+------------+------+----------------+--------+------------+------------+----------------+--------------+-----------+---------------+---------------------+---------+-------------+--------+-----------------------+-------+------------+---------+---------------+--------+
| id | name                                           | uuid                                 | pool_type  | port | data_center_id | pod_id | cluster_id | used_bytes | capacity_bytes | host_address | user_info | path          | created             | removed | update_time | status | storage_provider_name | scope | hypervisor | managed | capacity_iops | parent |
+----+------------------------------------------------+--------------------------------------+------------+------+----------------+--------+------------+------------+----------------+--------------+-----------+---------------+---------------------+---------+-------------+--------+-----------------------+-------+------------+---------+---------------+--------+
|  1 | ref-trl-1594-k-M7-wei-zhou-kvm1-local-4fad9008 | 4fad9008-678d-41f5-936d-bccf7c008c89 | Filesystem |    0 |              1 |      1 |          1 |   58744832 |    84012326912 | 10.0.32.142  | NULL      | /localstorage | 2021-08-16 12:41:43 | NULL    | NULL        | Up     | DefaultPrimary        | HOST  | KVM        |       0 |          NULL |      0 |
+----+------------------------------------------------+--------------------------------------+------------+------+----------------+--------+------------+------------+----------------+--------------+-----------+---------------+---------------------+---------+-------------+--------+-----------------------+-------+------------+---------+---------------+--------+
1 row in set (0.00 sec)

MariaDB [cloud]> select * from storage_pool_host_ref;
+----+---------+---------+---------------------+--------------+---------------+
| id | host_id | pool_id | created             | last_updated | local_path    |
+----+---------+---------+---------------------+--------------+---------------+
|  1 |       1 |       1 | 2021-08-16 12:41:43 | NULL         | /localstorage |
+----+---------+---------+---------------------+--------------+---------------+
1 row in set (0.00 sec)
```
