### ISSUE TITLE
VPC Add network help information as separate icon

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5293]
##### ISSUE TYPE

 * Improvement Request
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### SUMMARY

VPC Add network help information as separate icon, not integrated into fields.
![Screenshot 2021-08-09 105217](https://user-images.githubusercontent.com/30048481/128674828-cfa48d18-6b3e-469d-b5c6-1af7fee38019.png)
Users on regular occasion instead of entering netmask in netmask field are entering cidr.
Move help text to separate help icon with full text explanation available.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by davidjumani** [comment]
Added a fix

**Comment by nvazquez** [comment]
Fixed by PR #5326
