### ISSUE TITLE
Basic Zone - change init sequence

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5302]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI, Zone
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

Single Server deployment
Basic Zone
LocalStorage enabled

##### OS / ENVIRONMENT

Ubuntu 20.04.2

##### SUMMARY

Creation of a Basic Zone after a clean CloudStack setup fails with the error: `TypeError: h.prefillContent.secondaryStorageProvider is undefined`

The host can't be added BEFORE secondary storage is created. GUI wizard asks to setup Secondary Storage AFTER host setup, which causes this problem

So, need to change the init sequence.Init Secondary Storage right after creating a Zone (when secondary storage is zone-wide) or after creating a Cluster (when secondary storage is cluster-wide)

##### STEPS TO REPRODUCE

Change init/create sequence for Basic Zone so that Secondary Storage is created BEFORE adding the host

![zone-secondary](https://user-images.githubusercontent.com/2816743/128930649-9c53d679-0027-49cd-9a26-98fc485d471d.png)

~~~

~~~

##### EXPECTED RESULTS

~~~
Basic Zone is created without errors
~~~

##### ACTUAL RESULTS

~~~
Error creating a Basic Zone

~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5303
