### ISSUE TITLE
Override Root Disk Size button does not work

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#5306]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1.0
~~~

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Override Root Disk Size button does not work

##### STEPS TO REPRODUCE

~~~
When selecting template for the creation of new instance Override Root Disk Size button does not work
Check attached video
https://drive.google.com/drive/folders/1MnE2VQk0WWTvEXQeYan7wueYacJutcrv?usp=sharing
~~~

##### EXPECTED RESULTS

~~~
Expected to button to move to on position
~~~

##### ACTUAL RESULTS

~~~
Button doesn't work
~~~

**Comment by nvazquez** [comment]
@AlexanderKgr which hypervisor are you using to test? Does it happen also for the default centos template?

**Comment by Pearl1594** [comment]
@AlexanderKgr cc @nvazquez  this has been fixed by https://github.com/apache/cloudstack/pull/5199/commits/8872b53556e0b15d48051a4fcc35e3c393caa55e?diff=split&w=1#diff-8008c55fcf5cea1128c96959a8e0602e2a6585d439666dc2f7556dc59e106de7L110-R110

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr which hypervisor are you using to test? Does it happen also for the default centos template?

i am using xcp-ng 8.2 and it is also happening with the default centos template

**Comment by davidjumani** [comment]
Verified, this has been fixed

**Comment by nvazquez** [comment]
Thanks @Pearl1594 @davidjumani, confirming the commit has been included in this PR https://github.com/apache/cloudstack/pull/5199 and fixes the issue
