### ISSUE TITLE
VMWare host do not receive commands to cleanup nics

### ISSUE THREAD

**Issue by GutoVeronezi** [apache/cloudstack#5308]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
VM, VMWare
~~~

##### CLOUDSTACK VERSION
~~~
4.15.0.1
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In the class `VirtualMachineManagerImpl.java`, the `nicExpungeCommands` is instantied here:
https://github.com/apache/cloudstack/blob/2a4c2c250696a154ccf8a7c8fff8604d893e9258/engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java#L576

There are 2 implementation for this method:
- `HypervisorGuruBase`, which returns `null`:
https://github.com/apache/cloudstack/blob/2a4c2c250696a154ccf8a7c8fff8604d893e9258/server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java#L293-L296

- `VMWareGuru`, which returns some commands:
https://github.com/apache/cloudstack/blob/2a4c2c250696a154ccf8a7c8fff8604d893e9258/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/guru/VMwareGuru.java#L342-L358

`nicExpungeCommands` is only used in the following block:
https://github.com/apache/cloudstack/blob/2a4c2c250696a154ccf8a7c8fff8604d893e9258/engine/orchestration/src/main/java/com/cloud/vm/VirtualMachineManagerImpl.java#L628-L652

However, only `HypervisorGuruBase` implements the method `finalizeExpunge`, which returns `null`:
https://github.com/apache/cloudstack/blob/2a4c2c250696a154ccf8a7c8fff8604d893e9258/server/src/main/java/com/cloud/hypervisor/HypervisorGuruBase.java#L288-L291

Therefore, the block where `nicExpungeCommands` is used is never called, which causes VMWare host not receiving cleanup nics' commands.

**Comment by GutoVeronezi** [comment]
@nvazquez could you explain more?

**Comment by nvazquez** [comment]
Thanks @GutoVeronezi. As I understand this is a leftover only for Vmware nics connected to lswtich. In this case, is needed to send `UnregisterNicCommand` to Vmware hosts to complete the cleanup

**Comment by weizhouapache** [comment]
for vmware, finalizeExpungeNics is executed before finalizeExpunge. it is not an issue imho.

**Comment by nvazquez** [comment]
@weizhouapache there is a corner please in which finalizaExpungeNics returns a list of commands but these commands are never sent to the hypervisor, please check #5449,
