### ISSUE TITLE
Can't remove an empty Zone - zombie storage volumes

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5313]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Storage, zone
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### CONFIGURATION

Basic Zone
KVM
LocalStorage for Guest/SystemVMs were enabled Globally and during Basic Zone setup

##### OS / ENVIRONMENT

Ubuntu 20.04.2

##### SUMMARY

Created a Basic Zone. Then decided to completely remove it, but that won't work due to: 
```
(localcloud) 🐱 > list zones
{
  "count": 1,
  "zone": [
    {
      "allocationstate": "Enabled",
      "dhcpprovider": "VirtualRouter",
      "dns1": "8.8.8.8",
      "id": "83bc4dda-449b-483c-8b42-2c652c1b92d6",
      "internaldns1": "193.x.x.x",
      "localstorageenabled": true,
      "name": "zone0",
      "networktype": "Basic",
      "resourcedetails": {
        "system.vm.use.local.storage": "true"
      },
      "securitygroupsenabled": true,
      "tags": [],
      "zonetoken": "4aea8564-8f4c-33d5-ab75-e39034e428b8"
    }
  ]
}
(localcloud) 🐱 > delete zone id=83bc4dda-449b-483c-8b42-2c652c1b92d6 
🙈 Error: (HTTP 530, error code 4250) The zone cannot be deleted because there are storage volumes in this zone.

```
I'd expect to be able to remove an empty zone, since all other primitives were removed too
![zone](https://user-images.githubusercontent.com/45828526/129382693-73b60650-2e34-46cf-95eb-3db3b7ecb18c.png)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
An empty Zone was removed
~~~

##### ACTUAL RESULTS

~~~
An empty Zone can't be removed
~~~

**Comment by nvazquez** [comment]
@tetra12 looks like there are still some volumes not removed in DB for the zone, can you please try to disable the zone first and remove system VMs (if any)? As your zone is enabled it will try to recreate system VMs and its volumes

**Comment by tetra12** [comment]
Closing as can't reproduce
