### ISSUE TITLE
Compressed Templates - fail to upload a bz2 file 

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5314]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management, Templates
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### CONFIGURATION

Basic Zone
KVM

##### OS / ENVIRONMENT

Ubuntu 20.04

##### SUMMARY

I wanna upload a compressed *.qcow2.bz2 template from my local http server.
```
bku@cloud:~/webserver$ file ubu-server.qcow2.bz2 
ubu-server.qcow2.bz2: bzip2 compressed data, block size = 900k
```
But when I try to upload it thru a web GUI, I'm getting the following:
`"status": "Failed to install: Template content is unsupported, or mismatch between selected format and template content. Found  : POSIX tar archive (GNU) (bzip2 compressed data, block size = 900k)"`

I selected KVM, QCOW2, Extractable, Public, HVM, Featured checkboxes

##### STEPS TO REPRODUCE

~~~
Upload a *qcow2.bz2 file
~~~

##### EXPECTED RESULTS

~~~
Successfully upload a *.qcow2.bz2 file
~~~

##### ACTUAL RESULTS

~~~
"status": "Failed to install: Template content is unsupported, or mismatch between selected format and template content. Found  : POSIX tar archive (GNU) (bzip2 compre
ssed data, block size = 900k)"
~~~

**Comment by rhtyd** [comment]
@tetra12 are you trying the browser based upload or registering the http url? If it is browser based upload can you try to uploading a tar.bz2 or use qemu-img to compact the qcow2 and upload it?

**Comment by tetra12** [comment]
Closing as can't reproduce
