### ISSUE TITLE
MS does not recreate SSVM after upgrade

### ISSUE THREAD

**Issue by gerolamo-ov** [apache/cloudstack#5330]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

advanced networking, kvm

##### OS / ENVIRONMENT

ubuntu 20.04

##### SUMMARY

After upgrading from 4.9 to 4.15.1, everything appeared to be ok until the last step in which we have to upgrade systemVMs and virtual routers.
Stopping and restarting SSVM and Console proxy VM worked (with VM based on 4.15.1 template) but SSVM seemd to have an intermittend "disconnected" state
So we tried to destroy the SSVM in order to recreate it, but, after deleting it, the SSVM was not automatically recreated.

No errors appears to be in error logs.

Is there a way to force SSVM to recreate?

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
SSVM recreated automatically
~~~

##### ACTUAL RESULTS

~~~
No SSVM recreated
~~~

**Comment by rhtyd** [comment]
Did you register the systemvm template for the specific version and wait till it was in ready state before your upgrade? Can you share management server logs?

Usually you need to read through the ms and kvm agent logs as to why ssvm is not being launched. Usual suspects are a corrupt or missing systemvm template or template not in ready state, storage issue (capacity, mounting issue or path/permissions).

**Comment by gerolamo-ov** [comment]
Hi,
according to this Wido's blog post:
https://blog.widodh.nl/2013/04/cloudstack-zone-x-is-is-not-ready-to-launch-console-proxy-yet/

Brief: there is a configuration in DB, not visible in UI: “secondary.storage.vm”

In our environment this was setted as pseudo random string.
Setting this value to "true" in database and restarting the MS, resolved the issue.

What is “secondary.storage.vm” intended for and why is this setting not visible in UI?

**Comment by shwstppr** [comment]
@gerolamo-ov from DB:
```
mysql> select * from configuration where name='secondary.storage.vm'\G
*************************** 1. row ***************************
     category: Hidden
     instance: DEFAULT
    component: management-server
         name: secondary.storage.vm
        value: true
  description: Deploys a VM per zone to manage secondary storage if true, otherwise secondary storage is mounted on management server
default_value: false
      updated: NULL
        scope: NULL
   is_dynamic: 0
```
Intention of this config can be seen from its description. I'm not sure why it is a hidden config. Although ACS do have some other hidden(not available in UI) configs as well and maybe the reason for them to be hidden is their very specific use-case.
