### ISSUE TITLE
[UI] Unable to add ESX/ESXi host from UI, Username / Password inputs are missing on Add Host dialog.

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#5332]
Unable to add ESX/ESXi host from UI, Username / Password inputs are missing on Add Host dialog.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### OS / ENVIRONMENT

CloudStack, with VMware hypervisor

##### SUMMARY

Unable to add ESX/ESXi host from UI.

![ACS_AddHost_VMware](https://user-images.githubusercontent.com/12028987/129894297-25791d6f-9052-45be-bbb8-0859dcaa728b.png)

##### STEPS TO REPRODUCE

- Go to Infrastructure -> Hosts
- Click of 'Add Host' (Select Cluster with 'VMware')
- Unable to specify username / password for the ESX/ESXi

##### EXPECTED RESULTS

Should able to add ESX/ESXi host from UI.

##### ACTUAL RESULTS

Unable to add ESX/ESXi host from UI. Fails with error: "Empty or null value provided for API arg: password"

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5337
