### ISSUE TITLE
Vmware: Snapshot are not removed from the primary storage after backup to secondary storage

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#5334]
Vmware: Snapshot are not removed from the primary storage after backup to secondary storage

Steps to reproduce:
- Create a VM and take its root disk's volume snapshot
- Monitor the snapshot operation in ACS and vSphere client
- Notice that worker VM is removed but its vmdk file is left in the worker VM's directory on primary storage

In code, we observe that between 4.15.0 and 4.15.1 there are changes in how volume snapshots are handled where after backup the disks are detached before destroying the worker VM leading to delete VM and its related files (vmx, logs etc) on the primary storage but not its vmdk.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

**Comment by nvazquez** [comment]
Closing as PR is merged
