### ISSUE TITLE
Public IP for system VM is unreachable

### ISSUE THREAD

**Issue by fengdoudm** [apache/cloudstack#5336]
Everything is well when i add advenced zone on the **CloudStack 4.15.1.0**, but public IP for system VM is unreachable.
Everything is well when i add advenced zone on the **CloudStack 4.13.1.0**, public IP for system VM is reachable.
I tried many times, still can't fix it.  Can everyone  help me, thanks.

I will redeploy the **CloudStack 4.15.1.0** tomorrow.

**Comment by weizhouapache** [comment]
@fengdoudm could you check if you register correct systemvm template ?
https://download.cloudstack.org/systemvm/

**Comment by rhtyd** [comment]
@fengdoudm did you add a VLAN on the public IP range, or other config? Please check or share details of your zone deployment.

**Comment by fengdoudm** [comment]
> @fengdoudm could you check if you register correct systemvm template ?
> https://download.cloudstack.org/systemvm/
Systemvm template is systemvmtemplate-4.15.1-kvm.qcow2.bz2 in the CloudStack 4.15.1.0

**Comment by fengdoudm** [comment]
> @fengdoudm did you add a VLAN on the public IP range, or other config? Please check or share details of your zone deployment.
The following were some information for system VM and public network.
![image](https://user-images.githubusercontent.com/8956444/130427932-93d3e04f-ad1d-4c15-b083-c05ca3551452.png)
![image](https://user-images.githubusercontent.com/8956444/130428117-7eed8dd0-efea-4e76-af43-9664f2f5a2d6.png)

**Comment by fengdoudm** [comment]
1. Add zone
![image](https://user-images.githubusercontent.com/8956444/130803681-37a319ae-29ed-426a-9913-13cb364de105.png)

2. Set up zone name
![image](https://user-images.githubusercontent.com/8956444/130803906-c0a04847-c341-4564-856d-59528611a246.png)

3. Set up physical network
![image](https://user-images.githubusercontent.com/8956444/130804196-6eba6a30-6e24-4f27-94ec-e9bf1974a55e.png)

4. Configure public traffic
![image](https://user-images.githubusercontent.com/8956444/130804528-4335bc09-3ed8-4b9e-8381-a96243f2fc40.png)

5. Configure Pod
![image](https://user-images.githubusercontent.com/8956444/130804725-f9ab40a0-170c-49df-a9c8-d2f629766edb.png)

6. Configure guest traffic
![image](https://user-images.githubusercontent.com/8956444/130806316-1b3b3d01-68d3-4646-bf36-3f059dac0865.png)

7. Configure cluster name
![image](https://user-images.githubusercontent.com/8956444/130805100-6e02106d-61b5-4d00-a9ae-4d01cf511e0a.png)

8. Add hosts for the cluster
![image](https://user-images.githubusercontent.com/8956444/130805350-8b1b969f-debb-4b4f-b96a-b682550951e4.png)

9. Add primary storage for the zone
![image](https://user-images.githubusercontent.com/8956444/130805646-376d5d29-3adf-47bb-b34e-70690b865e2e.png)

10. Add secondary storage for the zone
![image](https://user-images.githubusercontent.com/8956444/130805751-b1be59a9-aac4-4a7f-b043-823f0b80e11b.png)

11. Launch zone
![image](https://user-images.githubusercontent.com/8956444/130805872-348ea03a-5938-4977-8e2c-88c5489e9d2f.png)

**Comment by fengdoudm** [comment]
Because I can not access console from my pc




--
发自我的网易邮箱手机智能版



在 2021-08-27 16:26:58，dahn ***@***.***> 写道：


@fengdoudm could you check if you register correct systemvm template ?
https://download.cloudstack.org/systemvm/
Systemvm template is systemvmtemplate-4.15.1-kvm.qcow2.bz2 in the CloudStack 4.15.1.0

Here's a weird question, the system VM can connet to my PC, but my PC can't connect to the system VM.

silly side question @fengdoudm , why would you want to reach the systemvm from your PC?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weizhouapache** [comment]
@fengdoudm 
I think it is because the public ip (172.16.116.132) and private ip (172.16.116.145) are in same subnet.
it is not suggested.

you need to change the route table in cpvm manually.

**Comment by fengdoudm** [comment]
got It,I will try to change the private ip.thank you very much.



--
发自我的网易邮箱手机智能版



在 2021-09-09 19:36:11，"Wei Zhou" ***@***.***> 写道：


@fengdoudm
I think it is because the public ip (172.16.116.132) and private ip (172.16.116.145) are in same subnet.
it is not suggested.

you need to change the route table in cpvm manually.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
