### ISSUE TITLE
default.ui.page.size changed to 200 not working

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5338]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### STEPS TO REPRODUCE

~~~
Change default.ui.page.size to 200 restart cloudstack-management clear browser cache.
~~~

##### EXPECTED RESULTS

~~~
Default page size is set to 200
~~~

##### ACTUAL RESULTS

~~~
Default page size remines 20
~~~
![Screenshot 2021-08-19 114515](https://user-images.githubusercontent.com/30048481/130038266-9dfcf5f2-5842-4232-b739-d66098ae2e55.png)
![Screenshot 2021-08-19 114527](https://user-images.githubusercontent.com/30048481/130038281-56f8159f-56fd-4b9e-af79-9a4cac5dd7bd.png)
![Screenshot 2021-08-19 114556](https://user-images.githubusercontent.com/30048481/130038293-909028fc-5cb0-443e-a0af-53ef3d0fbc8f.png)

**Comment by rhtyd** [comment]
@kricud I think this is per UI/login session - the UI does not save this setting or query backend to know the default page size. Should we save in browser cache (browser local storage) cc @davidjumani @utchoang

**Comment by davidjumani** [comment]
Will look into it as part of https://github.com/apache/cloudstack/pull/5276

**Comment by kricud** [comment]
@rhtyd My plan was to change this value to 500 and have it as workaround for #5290 at expense of ACS CPU/RAM/IOPS. 
Its not doing what I expected from its description/appearance.

**Comment by davidjumani** [comment]
Added https://github.com/apache/cloudstack/pull/5276/commits/3858e15e407fe8d89e1a910a807446e7e3ab3912 to honour it

**Comment by rhtyd** [comment]
@davidjumani if you want to work on this for 4.15 - can you send a 4.15 specific PR with a specific scope (just UI only)?

**Comment by davidjumani** [comment]
Separated it into a different PR #5394

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5394
