### ISSUE TITLE
Unnecessary button 'Take VM volume snapshot' on a destroyed (but not expunged) VM

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#5340]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16 latest main
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

There is an unnecessary button 'Take VM volume snapshot' on a destroyed (but not expunged) VM.

##### STEPS TO REPRODUCE

~~~
1. Destroy a VM without expunging it.
2. Now try to 'Take VM volume snapshot' by clicking the button.
~~~

##### EXPECTED RESULTS

~~~
This button should not be there if the VM is destroyed.
~~~

##### ACTUAL RESULTS

~~~
The operation fails expectedly with a proper error message.
~~~

![image](https://user-images.githubusercontent.com/12384665/130057086-7aab506f-7388-4b23-8a49-5574ca7bcdba.png)
![image](https://user-images.githubusercontent.com/12384665/130057150-4c17a9e9-5124-46b6-8653-b8df301ff8c2.png)

**Comment by rhtyd** [comment]
Merged in https://github.com/apache/cloudstack/pull/5345
