### ISSUE TITLE
After adding a new project, the list is not automatically refreshed

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#5343]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16 latest main
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

After adding a new project, the list is not automatically refreshed

##### STEPS TO REPRODUCE

~~~
Go to Projects and create a new project.
~~~

##### EXPECTED RESULTS

~~~
The list should be auto-refreshed after a new object is added.
~~~

##### ACTUAL RESULTS

~~~
The list of projects on the pages is not auto-refreshed, you have to press the 'Refresh' button in order to see your new project.
~~~

![image](https://user-images.githubusercontent.com/12384665/130085889-0c07e850-1945-46e7-8e14-acf6d56626da.png)

![image](https://user-images.githubusercontent.com/12384665/130085690-158d7db7-7e6c-4ada-ad4d-7188a8137f0c.png)

![image](https://user-images.githubusercontent.com/12384665/130086287-4a64298a-9766-4abe-992b-365a35b9615d.png)

**Comment by utchoang** [comment]
@vladimirpetrov I have tested with version `4.15` and `main` but can't reproduce the error, can you reproduce the step by step error?

**Comment by vladimirpetrov** [comment]
Actually, you are right, @utchoang! I did a full browser refresh and now it's working properly. My bad - it must have been some old code leftovers. Closing this issue.
