### ISSUE TITLE
Add storage name to delete primary/secondary storage dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#5344]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The storage name is missing in the delete primary/secondary storage dialog and it's not really clear which one you're deleting.

##### STEPS TO REPRODUCE

~~~
Try to delete a primary or secondary storage.
~~~

##### EXPECTED RESULTS

~~~
It would be much clearer if we had the storage name explicitly in the delete dialog.
~~~

##### ACTUAL RESULTS

~~~
The storage name is missing in the delete primary/secondary storage dialog.
~~~

![image](https://user-images.githubusercontent.com/12384665/130106493-40930e46-28ea-45ca-aa87-21a6b42960a2.png)

![image](https://user-images.githubusercontent.com/12384665/130106564-41852208-62f6-4b1e-9be6-507c195e1a46.png)

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5359
