### ISSUE TITLE
Drop Agent dependency on qemu-kvm for Ubuntu

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5350]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Agent, Core
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### CONFIGURATION

Built the latest qemu version from source

##### OS / ENVIRONMENT

Ubuntu 20.04 and newer

##### SUMMARY

CS Agent requires `qemu-kvm` installation. However, newer versions of `qemu` have dropped dependency on `qemu-kvm` in favor of `qemu-system-x86`. 

If I build and install the latest `qemu` from source, I'm unable to install the CloudStack Agent due to  its dependency on `qemu-kvm`, which was dropped in recent releases of `qemu`.

Thus, I can't use the latest release of `qemu`, since trying to `apt install -y qemu-kvm` yields in the following error :
```
bku@ttx0:~/work/qemu/build$ sudo apt install -y qemu-kvm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'qemu-system-x86' instead of 'qemu-kvm'
qemu-system-x86 is already the newest version (1:5.2+dfsg-9ubuntu3.1).
qemu-system-x86 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 cloudstack-agent : Depends: qemu-kvm (>= 2.5)
                    Depends: ebtables but it is not going to be installed
                    Depends: vlan but it is not going to be installed
                    Depends: ipset but it is not going to be installed
                    Depends: python3-libvirt but it is not going to be installed
                    Depends: ethtool but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```

##### STEPS TO REPRODUCE

~~~
1. Clone qemu repository
2. Build and install qemu from master
3. Install a stock libvirt for Ubuntu
3. Validate qemu and virsh installation: `qemu-img --version` , `libvirtd --version`
4. Try to install CloudStack Agent on the node
5. Observe error installing the CS agent
~~~

##### EXPECTED RESULTS

~~~
Agent works with the latest qemu and libvirt
~~~

##### ACTUAL RESULTS

~~~
Fail to install CS Agent  on the node with the latest `qemu` is installed
~~~

**Comment by weizhouapache** [comment]
@rhtyd @DaanHoogland 
do we support non-stock qemu version on hypervisors ? 
do we support non-LTS ubuntu versions as hypervisors ? qemu-kvm is not installed in ubuntu 21.04

**Comment by tetra12** [comment]
That's what ppl say about `qemu-kvm` [here](https://linux.debian.user.narkive.com/yv4308hI/qemu-kvm-won-t-install-on-bullseye-installs-qemu-system-x86-instead)

**Comment by DaanHoogland** [comment]
@weizhouapache @tetra12 I'm not sure how we can insert this altered dependency but for sure we'll need a separate packaging for newer distributions. If we feel it serves a purpose we should support it, but it will cost us a lot of extra effort to maintain. 
Can we use a replace.property to insert the string 'qemu-kvm-x86' in the package?

**Comment by weizhouapache** [comment]
> @weizhouapache @tetra12 I'm not sure how we can insert this altered dependency but for sure we'll need a separate packaging for newer distributions. If we feel it serves a purpose we should support it, but it will cost us a lot of extra effort to maintain.
> Can we use a replace.property to insert the string 'qemu-kvm-x86' in the package?

Even if we remove the dependency so cloudstack-agent can be installed, we do not know if it works with the new qemu 5.2, nobody have tested it.
@tetra12 I suggest you to remove your self-build qemu 5.2 and install qemu from official apt repository on ubuntu 20.04, it works fine.

**Comment by rhtyd** [comment]
On 20.04 I don't see any issue @tetra12, were you testing a recent version of Ubuntu? I would prefer a platform-agnostic depdency otherwise we'll have to keep separate packaging configs for Ubuntu/aarch64 (for ex. RaspberryPi/arm64 platforms).

**Comment by weizhouapache** [comment]
> On 20.04 I don't see any issue @tetra12, were you testing a recent version of Ubuntu? I would prefer a platform-agnostic depdency otherwise we'll have to keep separate packaging configs for Ubuntu/aarch64 (for ex. RaspberryPi/arm64 platforms).

@rhtyd 
it looks he built qemu 5.2 from source, which does not have qemu-kvm package any more.

ps:
official qemu version in ubuntu 20.04 is  4.2, which works fine in cloudstack)
official qemu version n ubuntu 21.04 is  5.2, which does not contain qemu-kvm package. it is not LTS.

**Comment by tetra12** [comment]
@rhtyd @weizhouapache 

I need to customize QEMU and built a master from sources, which is 6.1.0-RC4 now.

`qemu-kvm` package was the wrapper over `qemu-kvm-x86` in older 4.x QEMU, which is shipped with Ubuntu 20.04. 
QEMU provides it, not OS. It has been removed starting from 5.x and Ubuntu 21.04, which ships 5.2, also doesn't ship `qemu-kvm`

**Comment by weizhouapache** [comment]
@tetra12 

can you try the following change in debian/control ?

https://github.com/apache/cloudstack/blob/main/debian/control#L25

    qemu-kvm (>= 2.5) | qemu-system-x86 (>=5.2)

**Comment by tetra12** [comment]
@weizhouapache 

If you do that change, ACS would fail to install on Ubuntu 18 and 20. Leaving that empty is a generic workaround, that will push users to install correct deps on the host before installing ACS

**Comment by weizhouapache** [comment]
> @weizhouapache
> 
> If you do that change, ACS would fail to install on Ubuntu 18 and 20. Leaving that empty is a generic workaround, that will push users to install correct deps on the host before installing ACS

@tetra12 
`qemu-kvm (>= 2.5) | qemu-system-x86 (>= 5.2)` means it is ok if one of  `qemu-kvm (>= 2.5)` and `qemu-system-x86 (>= 5.2)` is installed.

**Comment by gogast** [comment]
Issue also exists on Debian 11 .

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5755
