### ISSUE TITLE
Support Ubuntu 21.04

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5361]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Build flow
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### SUMMARY

Support CloudStack Management and Hypervisor build for Ubuntu 21.04

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Install ACS management and agent on 21.04 servers
~~~

##### ACTUAL RESULTS

~~~
The latest supported version is 20.04
~~~

**Comment by GabrielBrascher** [comment]
I would rather wait to support an LTS release. Ubuntu 21.04 is not LTS.
The next LTS will be the 22.04 according to ["The Ubuntu lifecycle and release cadence"](https://ubuntu.com/about/release-cycle).

**Comment by tetra12** [comment]
Hello @GabrielBrascher 

What you say makes sense from the support point of view. However, I'd follow official Ubuntu cadence in the following form:

1. Drop support for end-of-life packages, e.g Ubuntu 14 and 16. So that ACS supports only Ubuntu 18 and higher. I would recommend following the support cadence as in OpenNebula [here](https://docs.opennebula.io/6.0/installation_and_configuration/frontend_installation/opennebula_repository_configuration.html#repositories-ee), which supports Debian 9/10 and Ubuntu 18/21

2. Add a priority support for LTS, but still give customers a choice to install deps on non-LTS, such as 21.04. The main reason for me to choose 21.04 is the highly outdated version of Qemu, which I'm not able to customize. 
In my network, I need to customize `QEMU` and add the latest matching version of `libvirt`. Both are very rapidly developed projects and the package version in the 20.04 LTS is already highly outdated

**Comment by GabrielBrascher** [comment]
I understand your point. But from our side, it adds quite a lot of complexity to the releasing cycle (more OS versions to be considered when testing release candidates, as well as more packages to be built/managed). Additionally, users might be encouraged to use an Ubuntu release that, in theory, is not stable and soon will be dropped.

You can have updated packages from Libvirt/Qemu added into Ubuntu 20.04 via [this repo](https://launchpad.net/~jacob/+archive/ubuntu/virtualisation). It would give you `QEMU emulator version 5.0.0` and `libvirtd (libvirt) 6.6.0`.

PS: I do not take any responsibilities if something breaks :slightly_smiling_face:.

**Comment by tetra12** [comment]
Yeah, makes sense... Let other core members consider this point.

BTW, I'm using qemu version 6.1-rc4 and libvirt 7.7.0 :smile:

**Comment by rohityadavcloud** [comment]
We're closer to 22.04 in 4 months, project generally doesn't support and test releases against non-LTS releases of distros. Closing the PR on this remark, thanks.

**Comment by tetra12** [comment]
UPD: June 8 2022

Trying to install nighties for 4.17.0.0 on Ubuntu 22.04. `mgmt` works fine, but `kvm` fails immediately on start with:
```bash
Jun 09 11:23:26 kvm0 java[4409]: Unable to start agent: Unable to find update_host_passwd.sh
```
However, I clearly see that script on the install path but for some reason, agent complains on it. 
Should I open a new issues on that ?
