### ISSUE TITLE
Scale VM custom compute offering not working

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5391]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### STEPS TO REPRODUCE

~~~
Press on Scale VM select Custom Compute offering try to move sliders for CPU and RAM not working. 
Enter values by hand and press ok presents error.
~~~
![Screenshot 2021-08-31 094315](https://user-images.githubusercontent.com/30048481/131455496-f78aad6b-bcbb-44c5-8c36-670faad35339.png)
![Screenshot 2021-08-31 094333](https://user-images.githubusercontent.com/30048481/131455502-ad4df404-9fbc-48a6-8126-660159a91c67.png)

##### EXPECTED RESULTS

~~~
Scale VM select Custom Compute offering works
~~~

##### ACTUAL RESULTS

~~~
Scale VM select Custom Compute offering not working
~~~

**Comment by nvazquez** [comment]
Thanks @utchoang, closing as PR is merged
