### ISSUE TITLE
KVM: Fail to migrate VM with local root disk and datadisk attached

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#5407]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### CONFIGURATION

- KVM
- Root disk on Local storage
- DataDisk allocated on any shared storage (tested on NFS, RBD)

##### SUMMARY

When migrating a VM with root disk in local storage + datadisk (always shared) it fails.
There are two ways of performing such a migration via the [migrateVirtualMachineWithVolume](https://cloudstack.apache.org/api/apidocs-4.15/apis/migrateVirtualMachineWithVolume.html).
1.  `migrate virtualmachinewithvolume virtualmachineid=<VM_ID> hostid=<HOST_ID>`
2. `migrate virtualmachinewithvolume virtualmachineid=<VM_ID> hostid=<HOST_ID> migrateto[0].volume=<VOLUME_ID> migrateto[0].pool=<POOL_ID>`

In the first case, the execution flow has no mapped volumes; however, it assumes that all the volumes on the VM should be migrated and maps such migrations. Causing exception during migration as the data disk has the wrong map.

In the second scenario, CloudStack holds the provided map of `volume -> storages` but at the end, it turns out to try to migrate all the volumes ignoring the provided map.

##### STEPS TO REPRODUCE

~~~
Migrate a VM with at least 1 Datadisk and its Root disk allocated in local storage.
~~~

##### EXPECTED RESULTS

~~~
VM is live-migrated along with its Root disk to another host (& respective local storage pool) in the same cluster
~~~

##### ACTUAL RESULTS

~~~
Fails to migrate VM
~~~

**Comment by shwstppr** [comment]
@GabrielBrascher are these scenarios working fine on 4.15?

**Comment by GabrielBrascher** [comment]
@shwstppr I am testing and debugging it in 4.16. But, as far as I know, 4.15 (and 4.14) also present issues in such migrations.

**Comment by GabrielBrascher** [comment]
@shwstppr I have created PR #5410 addressing this issue. Can you please check it? Thanks!

**Comment by sureshanaparti** [comment]
Closing the issue, as the associated fix PR is merged.
