### ISSUE TITLE
Cannot select constrained or unconstrained offering on powered on VM

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5412]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### OS / ENVIRONMENT

VMware

##### STEPS TO REPRODUCE

~~~
In new and legacy UI Power on VM in Vmware environment and try to scale it .
CPU and Memory hot add is enabled.
~~~
![Screenshot 2021-09-07 134933](https://user-images.githubusercontent.com/30048481/132332643-200b6ed3-2414-4586-8c10-fd5c8c4fe751.png)

![Screenshot 2021-09-07 134814](https://user-images.githubusercontent.com/30048481/132332622-497e8800-41e2-4c4f-ad93-875335d32baa.png)

##### EXPECTED RESULTS

~~~
Scaling can be done with constrained and unconstrained offerings.
~~~

##### ACTUAL RESULTS

~~~
Scaling cant be done with constrained and unconstrained offerings.
~~~

**Comment by shwstppr** [comment]
Ignore the scale API output in my previous response. Forgot I've already stopped the VM.
Old UI had same behaviour as well,
![Screenshot from 2021-09-07 17-53-33](https://user-images.githubusercontent.com/153340/132343990-e3cffbb5-c7f9-4bda-98d6-7a7240945bd5.png)

**Comment by kricud** [comment]
In ACS version 4.11.3 custom commute is/was working as option for turned on VM.
If you entered values lower than existing configuration error was thrown.

As you can only increase not decrease cpu and ram.
