### ISSUE TITLE
Unable to register OVA template when properties are prepend with "ovf:" in the ovf file

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#5415]
When trying to register an OVA format template in VMware, template installation is failing.
The reason for that is a couple of properties inside the ovf file are prepended with "ovf:" Eg. Property, File, Item, Disk, etc.

The corresponding error in the cloud.log of SSVM is
2021-09-08 02:13:48,611 ERROR [storage.template.DownloadManagerImpl] (pool-1-thread-1:null) Template process exception
com.cloud.exception.InternalErrorException: getTemplateVirtualSize: Unable to parse OVF XML document /mnt/SecStorage/54efe74a-bb32-3f6e-9d91-22cfcb27a30b/template/tmpl/2/202 to get the virtual disk fe146945-66c1-3dd7-9e75-e508bd94b098.ova size due to java.lang.NullPointerException
        at com.cloud.storage.template.OVAProcessor.getTemplateVirtualSize(OVAProcessor.java:159)
        at com.cloud.storage.template.OVAProcessor.process(OVAProcessor.java:104)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Template
~~~

##### CLOUDSTACK VERSION

~~~
4.13, main
~~~

##### STEPS TO REPRODUCE

~~~
1. Register a OVA template having an OVF file which has some  properties prepended with "ovf:" Eg. Property, File, Item, Disk
~~~

##### EXPECTED RESULTS

~~~
Template installation should be successful and ready
~~~

##### ACTUAL RESULTS

~~~
Template installation is failing. We can check it under the zones section of the template.
~~~

**Comment by NuxRo** [comment]
@nvazquez  LGTM :+1:
