### ISSUE TITLE
Hide SSO Provider URL 

### ISSUE THREAD

**Issue by ngrosc** [apache/cloudstack#5418]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.x
~~~

##### CONFIGURATION

SSO active

##### OS / ENVIRONMENT

N/A

##### SUMMARY

As soon as SSO is active, the IDP URL is visible in the selector as item. it would be nice, to get an alias for it to mask it and also for a cleaner display

##### STEPS TO REPRODUCE

~~~
Configure SAML IDP that the SSO selector becomes visible on the login page
~~~

##### EXPECTED RESULTS

~~~
SAML IDP has option for an alias to display this instead of the url, i.e. saml2.idp.name. If not set, the url will be displayed as today
~~~

##### ACTUAL RESULTS

~~~
SAML IDP is listed as URL
~~~

**Comment by rhtyd** [comment]
In the configured xml, this can be fixed with the appropriate name - pl check, test if a file based idp Metadata can be used with custom name.

**Comment by nvazquez** [comment]
Thanks @rhtyd - @ngrosc does it fix the issue?

**Comment by ngrosc** [comment]
Hi Guys

Just tested it, and it's working like a charm.

Thanks Rohit for the hint!

Best Regards
Christian

Am Di., 14. Sept. 2021 um 05:59 Uhr schrieb Nicolas Vazquez <
***@***.***>:

**Comment by rhtyd** [comment]
@ngrosc Great, let's close this on your remark
