### ISSUE TITLE
Ability to see/manage Security Groups in UI

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#5436]
We might have a bug or regression, if zone has security groups enabled the UI doesn't show the SG tab under networks. However, we're able to deploy VMs against existing SGs. This needs testing/checking at least against 4.16/main.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SG, UI
~~~

**Comment by rhtyd** [comment]
cc @nvazquez @sureshanaparti @utchoang @weizhouapache

**Comment by weizhouapache** [comment]
@rhtyd 
it looks ok in my testing (4.16/main).
![Screenshot from 2021-09-13 08-40-30](https://user-images.githubusercontent.com/57355700/133035781-bfef13aa-9921-4a22-a65f-b32795cf86dc.png)

**Comment by rhtyd** [comment]
My bad, I think I got the wrong Trillian env. In an env with SG enabled for a zone, the tab was seen/shown.
