### ISSUE TITLE
Dashboard/project UI issues as user account role

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#5440]
All issues reproduced under user-account role (not admin!):

1. Deploy 2 Vms, volumes in a user account
2. Create a project under a user account -> the project tab doesn't refresh; next try to add an account (say admin) -> the account tab doesn't refreshes. Finally deploy 1 VM, volumes in that account.
3. Go to project dashboard, you'll see 1 VM; now switch to default view -> you'll see dashboard does not refresh/change

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15, 4.16/main
~~~

**Comment by rhtyd** [comment]
cc @Pearl1594 @shwstppr @davidjumani @nvazquez @sureshanaparti @weizhouapache

**Comment by nvazquez** [comment]
@davidjumani @utchoang I could reproduce the issues, simply clicking Compute -> Instances as a user and then Projects makes the projects list to not being refreshed, however I can see the notification at the top. Any idea on this issues?

**Comment by Pearl1594** [comment]
@rhtyd @nvazquez regarding step #2 i.e., On creation of a project - the project tab doesn't auto-refresh, I was able to reproduce the issue, but on clearing the cache - surprisingly things worked as it should i.e., Project tab auto refreshes on creation of a new project
