### ISSUE TITLE
Primate: remove blank spaces around item values

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#5444]
Hello,

Currently field names such as "Display Name", "ID" and so on are not surrounded by any blank spaces, however their values are surrounded by 1 blank space on each side.

When double clicking to select and copying the values, such as IDs etc, it becomes quite annoying having to spend time on removing them manually when pasting in other programs (say cloudmonkey).

Can this be adjusted to exclude those blank spaces? 

Cheers
![Selection_008](https://user-images.githubusercontent.com/2357012/133071495-b4d3b4d6-8db6-4c42-a40e-7f5cde6bc97a.jpg)

**Comment by nvazquez** [comment]
@NuxRo I tried on Chrome and the values do not have space, however I see a space at the end of the values using Firefox, in which browser did you see that behaviour?

Chrome:
![Screenshot from 2021-09-14 00-25-47](https://user-images.githubusercontent.com/5295080/133190075-563d3b47-2463-4683-9c71-a05b75b7ad2a.png)

Firefox:
![Screenshot from 2021-09-14 00-28-16](https://user-images.githubusercontent.com/5295080/133190339-fbba8dae-65ff-4430-92f8-23d78e3b37a3.png)

@utchoang @davidjumani any hint on this? Looks like different browsers may add those spaces for some style classes

**Comment by NuxRo** [comment]
@nvazquez you'd think mentioning the browser and version would be important.. Firefox 91 on Fedora.

I've now just tried Chromium and it doesn't prepend/append any spaces, however it does append a "new line", so something is definitely afoot here.

**Comment by rhtyd** [comment]
@NuxRo please get/test latest main, issue fixed in https://github.com/apache/cloudstack/pull/5450
