### ISSUE TITLE
Solution for multiple VLANs using cloudstack ?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#5462]
##### ISSUE TYPE
 * Solution

We're using CloudStack + KVM to build up our private virtulization environment, and we have **_the requirement that to use multiple VLANs for VM in one cluster via basic network mode_**.

1.    We have tried using bridge in KVM host but it could only support all VMs in 1 VLAN, and we'd like to know is that possible if using openvswitch in KVM host to support multiple VLANs in basic network mode? If yes what's the configuration when adding zone? Thank you.
(Not using advanced network just because the Windows OS VM need to join our AD servers outside Cloudstack platform and NAT is not working for such case as I know)

2.   If the first can not meet our needs, could you please give some advices ?

**Comment by weizhouapache** [comment]
@xuanyuanaosheng 

In basic zone, you can add multiple ip ranges to the network. This may not meet your requirement because all ip ranges use same vlan.

shared networks in advanced zone will solve your problem.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  Thanks for your reply.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache Could you please give some advices to us about **_multiple VLANs for VM in one cluster and join our AD servers outside Cloudstack platform via advanced zone ?_**

**Comment by weizhouapache** [comment]
@xuanyuanaosheng 
please read this page in cloudstack doc: https://docs.cloudstack.apache.org/en/latest/adminguide/networking.html

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  方便的话，加个微信可以么？

**Comment by nvazquez** [comment]
Hi @xuanyuanaosheng @weizhouapache can we close this issue?

**Comment by xuanyuanaosheng** [comment]
@weizhouapache @nvazquez  Thanks for your help. The problem has resolved, I will close this issue.
