### ISSUE TITLE
After installing 4.15.2.0 instances with uefi cannot boot for second time (xcp-ng 8.2)

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#5466]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CRITICAL - operation not possible
~~~

##### CLOUDSTACK VERSION
~~~
4.15.2.0
~~~

##### CONFIGURATION

Ubuntu server 18 with cloudstack 4.15.2.0
Hypervisor xcp-ng 8.2 with september security patch
Advanced networking

##### SUMMARY

Continuing from this issue
https://github.com/apache/cloudstack/issues/5204
Which is closed and this problem happening

After installation of 4.15.2.0, when creating a new instance there is an option in advanced setting for bios or uefi - legacy, secure (btw - why there is 2 options for uefi? on xen orchesra there are only bios and uefi)
When selecting bios everything is working perfect, even old vms from old templates which had issues with 4.15.1.0. You can shutdown, boot again, reboot, everything works as it should

When selectin uefi - both options (secure - legacy) the instance will boot without issue on the 1st boot. But if you shutdown the instance and try to boot it again there is issue. Without even touching something from settings. There is an error that 
"Unable to start a VM due to insufficient capacity"

![image](https://user-images.githubusercontent.com/25532758/133887703-873c0f8c-3dad-4183-b223-8be2c5fefbc5.png)

and in the logs of cloudstack management there is something strange 

![image](https://user-images.githubusercontent.com/25532758/133887746-8f6a4487-4443-4967-a502-6e41eacec685.png)

I have selected uefi and secure and haven't touched the settings. I can understand that it is trying to vm with bios boot option.

This happens even on old instances created with older versions of CS. Instance will work the 1st time booting but if you shut it down cannot boot anymore.

I think this is really critical.

##### STEPS TO REPRODUCE

~~~
1. Create new instance or boot an instance with option uefi.
2. shut it down.
3. Try to boot it and it won't boot anymore
~~~

##### EXPECTED RESULTS

~~~
The instance to boot as the first time.
I underline that i haven't touched anything in instance settings.
~~~

##### ACTUAL RESULTS

~~~
Instance cannot boot

~~~

**Comment by rhtyd** [comment]
@AlexanderKgr thanks for reporting, would have been nicer if we could test 4.15.2 RC1/RC2.

Let's try to get it right for 4.16 then, cc @shwstppr - can you work on a fix for 4.16?

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr thanks for reporting, would have been nicer if you could test 4.15.2 RC1/RC2 earlier. Until you've the fix you may disable xcpng8.2 hosts or explore a workaround.
> 
> Let's try to get it right for 4.16 then, cc @shwstppr - can you work on a fix for 4.16?

i will try to revert to 4.15.1. i have a db backup. luckily i have not upgraded my production site. next time i will try rc versions

**Comment by rhtyd** [comment]
Great to hear that @AlexanderKgr, just a tip - after your issue is fixed by a pull request you can help us test the fix in your test environments using snapshot/nightly builds from http://download.cloudstack.org/testing/nightly (however, note this doesn't honour DB upgrade paths), and definitely help us test release candidates (RCs) and vote in future.

**Comment by AlexanderKgr** [comment]
> Great to hear that @AlexanderKgr, just a tip - after your issue is fixed by a pull request you can help us test the fix in your test environments using snapshot/nightly builds from http://download.cloudstack.org/testing/nightly (however, note this doesn't honour DB upgrade paths), and definitely help us test release candidates (RCs) and vote in future.

i will help with the test. 
I have issue restoring db. have drop cloud db, run the initialization script, stopped management server and restore db with the dump i have before upgrade... management server boots as new...any help?

**Comment by shwstppr** [comment]
@AlexanderKgr once the PR #5469 gets merged you may test the next nightly

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr once the PR #5469 gets merged you may test the next nightly

build failed!

**Comment by nvazquez** [comment]
@AlexanderKgr the PR is still in progress, we'll let you know once it is merged so you can test the nightly build

**Comment by AlexanderKgr** [comment]
> @AlexanderKgr the PR is still in progress, we'll let you know once it is merged so you can test the nightly build

Merged?

**Comment by rhtyd** [comment]
@AlexanderKgr the PR has been merged now - wait for the build/testing folder with today's date (2021-09-27) or later at https://download.cloudstack.org/testing/nightly/

**Comment by AlexanderKgr** [comment]
installed and tried 28-9-21 version and everything works. 
thanks for fixing
@rhtyd 
@shwstppr

**Comment by AlexanderKgr** [comment]
tried to boot an old instance with uefi and still facing the same error.

![image](https://user-images.githubusercontent.com/25532758/135321626-d492aacf-373b-4952-9fc1-43cbe728cf86.png)

and from the logs of cs

![image](https://user-images.githubusercontent.com/25532758/135321731-8735f411-71fe-4454-93f7-40f6424e40c8.png)

@shwstppr what is wrong with my configuration?
 running on CloudStack 4.15.3.0-snapshot.20210929 

@rhtyd
