### ISSUE TITLE
Refactor GroupByExtension to improve test logic

### ISSUE THREAD

**Issue by wx930910** [apache/cloudstack#5479]
##### ISSUE TYPE

 * Improvement Request

##### SUMMARY

I noticed that there is a test class [GroupByExtension](https://github.com/apache/cloudstack/blob/bf6266188c89a5487383f216333ae10e878d2c10/framework/db/src/test/java/com/cloud/utils/db/GroupByTest.java#L103) extends production class [GroupBy](https://github.com/apache/cloudstack/blob/bf6266188c89a5487383f216333ae10e878d2c10/framework/db/src/main/java/com/cloud/utils/db/GroupBy.java#L26) to assist testing  [GroupBy.toSql(StringBuilder)](https://github.com/apache/cloudstack/blob/bf6266188c89a5487383f216333ae10e878d2c10/framework/db/src/main/java/com/cloud/utils/db/GroupBy.java#L26). This might not be the best priactice in unit testing and can be improved by leveraging mocking frameworks.

###### Current Implementation
 * `GroupByExtension` implements `GroupBy` and overrides methods to make `GroupBy.init(Builder)` do nothing.
 * In test case, the child test class is used to test `GroupBy.toSql(StringBuilder)`.
 
###### Proposed Implementation
 * Replace `GroupByExtension` with a mocking object created by Mockito.
 * Use method stub to control the behavior of `GroupBy.init(Builder)`.
 * Create a method to return the mocking object for reusing.

###### Motivation
 * Decouple test class `GroupByExtension` from production class `GroupBy`.
 * Remove the redundant test child class `GroupByExtension`.

##### More Thought
 * If we only use the spying object once, we can create it inside of the test case to make test logic more explict.

**Comment by DaanHoogland** [comment]
@blueorangutan package
