### ISSUE TITLE
Account and projectId can't be specified together

### ISSUE THREAD

**Issue by PPisz** [apache/cloudstack#5493]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

New UI

##### CLOUDSTACK VERSION

4.15.1
4.15.2

##### OS / ENVIRONMENT

CentOS 8 / KVM

##### SUMMARY

I have a project, a user in a project, VM. When the VM is turned off and I try to edit settings of VM, I get this message:

Request Failed (431)
Account and projectId can't be specified together

The changes to the settings are not saved, in the old client, this message does not appear, but the changes are also not saved.
There is no error message in the CS log.

##### STEPS TO REPRODUCE
Editing a VM in a project.

##### EXPECTED RESULTS

User should be able to edit VM settings, the settings should save correctly.

##### ACTUAL RESULTS

This bug did not exist in 4.15.0

**Comment by shwstppr** [comment]
@davidjumani does #5485 fix this in main?

**Comment by davidjumani** [comment]
@shwstppr Yes it should

**Comment by nvazquez** [comment]
Tested main, fixed by #5485
