### ISSUE TITLE
Normal users with granted permission on listconfigurations/updateconfiguration are able to list and update global configurations

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5494]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
master
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

as titile

##### STEPS TO REPRODUCE

~~~
1. create a role from Role 'User'
2. add listconfigurations and updateconfigurations to allow lists
3. create an account/user from the new role
4. list and update configuration by the user
~~~

##### EXPECTED RESULTS

~~~
user can only be able to list/update account settings
~~~

##### ACTUAL RESULTS

~~~
user is able to list/update account settings, domain settings, cluster settings, global settings, etc

~~~

**Comment by weizhouapache** [comment]
I have discussed with @Pearl1594 
It seems many apis have similar issue (not sure if it is a real issue).
some APIs have `authorized = {RoleType.Admin` in APICommand annotation, but many old APIs do not have it.

**Comment by rhtyd** [comment]
cc @nvazquez @sureshanaparti pl triage

**Comment by davidjumani** [comment]
I can add a fix to restrict users as well, as part of https://github.com/apache/cloudstack/pull/4339
