### ISSUE TITLE
Improvement request: scale vm with new service offering, despite of storage tags

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5512]
Currently we can only scale vm to new service offering which have all the tags of current service offering.

It would be good to have an option to support vm upgrade to new service offering which do not have all the tags.

##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
master/4.16
~~~

##### OS / ENVIRONMENT

N/A
##### SUMMARY

It was introduced by ba0503d000250e233701a71bd8e406e52b6ad110

https://github.com/apache/cloudstack/blob/ba0503d000250e233701a71bd8e406e52b6ad110/engine/orchestration/src/com/cloud/vm/VirtualMachineManagerImpl.java#L2911-L2917

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by slavkap** [comment]
@weizhouapache, it will be great if this limitation is removed. There is the same case when we migrate a volume to a different storage pool, which I guess according to the comments is needed only for VMware

>         // OfflineVmwareMigration: check storage tags on disk(offering)s in comparison to destination storage pool
>         // OfflineVmwareMigration: if no match return a proper error now
>         DiskOfferingVO diskOffering = _diskOfferingDao.findById(vol.getDiskOfferingId());
>         if (diskOffering == null) {
>             throw new CloudRuntimeException("volume '" + vol.getUuid() + "', has no diskoffering. Migration target cannot be checked.");
>         }
>         if (!doesTargetStorageSupportDiskOffering(destPool, diskOffering)) {
>             throw new CloudRuntimeException(String.format("Migration target pool [%s, tags:%s] has no matching tags for volume [%s, uuid:%s, tags:%s]", destPool.getName(),
>                     getStoragePoolTags(destPool), vol.getName(), vol.getUuid(), diskOffering.getTags()));
>         }

**Comment by sureshanaparti** [comment]
@weizhouapache @slavkap I think, this can be addressed properly after decoupling the service and disk offerings (done in the PR: https://github.com/apache/cloudstack/pull/5008).

**Comment by nvazquez** [comment]
@sureshanaparti @slavkap can this limitation be removed now? I see the PR mentioned is already merged

**Comment by sureshanaparti** [comment]
> @sureshanaparti @slavkap can this limitation be removed now? I see the PR mentioned is already merged

@nvazquez I think so, we have to check / confirm the current behavior in main as the service and disk offerings are decoupled. cc @harikrishna-patnala

**Comment by slavkap** [comment]
@nvazquez, I didn't have the chance to test it, but I will do it and let you know
