### ISSUE TITLE
ctrl modifier in console proxy won't turn off

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5550]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
console proxy
~~~

##### CLOUDSTACK VERSION

~~~
4.16-snapshot/main
~~~

##### CONFIGURATION

nested environment on vmware
MS: centos7
Hyp: vmware7.0

##### SUMMARY

after starting a command that lasts (i.e. `ping google`), on sending `ctrl-c`, the keyboard is no longer accessible. turning of the ctrl modifier in the browser window does not seem to work as typing `ls` clears the screen (as if `ctrl-l` is pressed)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
next command can be entered
~~~

##### ACTUAL RESULTS

~~~
no input is/seems to  accepted anymore.
~~~

**Comment by nvazquez** [comment]
@DaanHoogland I could not reproduce the issue, tested on user VMs setting deploy-as-is on/off and succeded in all scenarios:

![image](https://user-images.githubusercontent.com/5295080/136066113-b614a1a0-4a90-4084-92a7-a13df251d6f2.png)

**Comment by DaanHoogland** [comment]
Ok, this is a latency issue in firefox on fedora in gnome on xorg. not a cloudstack issue as far as I can tell, replacing 4.16 milestone for 4.17 and will close if needed later

**Comment by nvazquez** [comment]
@DaanHoogland is this still an issue or can be closed?

**Comment by DaanHoogland** [comment]
closing
