### ISSUE TITLE
Hide the 'Power State' column on host tables when Host HA is not enabled - UI

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#5555]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15+
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Hide the 'Power State' column on host tables when Host HA is not enabled

The ever-present column of **'big red dot and Disabled'** is not relevant and distracting when Host HA hasn't been enabled.

##### STEPS TO REPRODUCE

~~~
Log into UI as an admin - go to any view of hosts in the environment
~~~

##### EXPECTED RESULTS

~~~
'Power State' column should only be visible when Host HA is enabled

~~~

##### ACTUAL RESULTS

~~~
'Power State' column is visible regardless of whether Host HA is enabled

~~~

**Comment by utchoang** [comment]
@PaulAngus cc @shwstppr @rhtyd @davidjumani  I am wondering if Host Ha is the information of a resource in listHostMetrics? And will hide the Power State column based on this value?
![image](https://user-images.githubusercontent.com/13766648/136487469-123334ed-bf95-426f-ab99-742bc5131312.png)

**Comment by rhtyd** [comment]
Actually it should be disabled if oobm is not configured/enabled for any/all hosts, people can still use oobm feature without host HA. Alternatively, give option in config.json to override and say which columns you want to show or hide.

**Comment by nvazquez** [comment]
Hi @davidjumani can you please explore this issue?

**Comment by davidjumani** [comment]
If this has to be changed, hiding a column based on the value of a field is quite tricky and very specific as it is in a shared view (ListView).
Alternatively, it can be done in one of the following ways :

1. Show the column only in the metrics view (easy fix)
2. Allow the user to select the columns he wishes to see (could take some effort since this will be a global change but have a good payoff as it makes the UI more customizable)

**Comment by nvazquez** [comment]
I'm +1 with the second one - what do you think @PaulAngus @DaanHoogland @rohityadavcloud?

**Comment by GabrielBrascher** [comment]
I agree with @rohityadavcloud regarding the OOBM. If a host has Out-of-band enabled and configured, I see no reason in hiding it for Admins in case HA is not enabled.

I am +1 in the 2nd option raised by @davidjumani but it might be tricky to have it implemented.
