### ISSUE TITLE
OpenJDK17 + new dependency migration

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#5563]
OpenJDK 17 is the new LTS, CloudStack currently uses JDK11 whose support ends in about 2 yrs time.
https://endoflife.date/java

This is not an urgent task, nonetheless we need to upgrade JDK/JRE support to 17 in future; at least by end of 2022; along with major upgrade to some necessary dependencies to their latest major versions such as bouncycastle, spring, jetty, mysql-connector as well.

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Build system, JDK
~~~

**Comment by Damans227** [comment]
Hey @rohityadavcloud Let me know if I can help with the migration of OpenJDK to 17. I am guessing we will propose a roadmap or a plan to complete this migration. So if there is something which needs to be validated or some research to be done, let me know and I can spend some time on it.

**Comment by nvazquez** [comment]
Thanks @Damans227 @rohityadavcloud should we consider this task for 4.17?

**Comment by Damans227** [comment]
@nvazquez Not a problem.

**Comment by nvazquez** [comment]
Hi @Damans227 are you currently working on this?

**Comment by Damans227** [comment]
> Hi @Damans227 are you currently working on this?

Not yet. I am waiting on some pointers about where to start and what to look for. If you can suggest something in that regard, I can start working on it.

**Comment by rohityadavcloud** [comment]
I'm moving this to 4.18 given that 4.17 is really near and openjdk17 isn't shipped by default in many LTS distros yet. jdk11 continues to be a supported LTS until sep 2023 for active support https://endoflife.date/java

**Comment by Damans227** [comment]
Sounds good. Thx!

**Comment by rohityadavcloud** [comment]
LTS security support is until 2026 (was this a new column I missed); closing this. I'm sure we'll all be reminded for this when distros stop shipping JDK11.
