### ISSUE TITLE
Read-only column of Secondary storage list view is misleading

### ISSUE THREAD

**Issue by yadvr** [apache/cloudstack#5578]
The read-only param key is false but it shows as following in the UI:
![Screenshot from 2021-10-14 14-28-01](https://user-images.githubusercontent.com/95203/137285456-e543ed4e-b2dd-4be5-8047-408320006773.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.15.2
~~~

**Comment by rhtyd** [comment]
Ah great, closing then.
