### ISSUE TITLE
Can't specify cluster for VR with storage tags

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5581]
##### ISSUE TYPE
 * Bug Report

##### CLOUDSTACK VERSION
~~~
4.14.1
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 7.9 - Management server
XCP-NG 8.2 - hypervisor
2 Clusters with different SAN 1 Pod

##### SUMMARY
Can't specify cluster for VR with storage tags. 
When create new System Offering For Software Router and use storage tags VRs ignore it and start on cluster where they are created firrst. 
When create new System Offering For Software Router and use host tags VRs start on host from cluster where tag are presented. 

##### STEPS TO REPRODUCE
~~~
Create 1 zone with 2 clusters in 1 pod. Each cluster has its own SAN. Add tags on host and SAN.
Create 4 System Offering For Software Router:
1 SO with host tag A
1 SO with host tag B
1 SO with SAN tag SA
1 SO with SAN tag SB
Create network
Change VR's Compute Offering (or create Network Offering with one of created System Offering)
~~~

##### EXPECTED RESULTS
~~~
VR start on host with needed host tags or start in cluster which contains needed SAN
~~~

##### ACTUAL RESULTS
~~~
VR ignored SAN tags
Honored only host tags
~~~

**Comment by nvazquez** [comment]
Hi @edikevich - have you used the changeServiceForRouter API to change the service offering of your VR? I have tried stopping a VR, changing the offering by the API, start the VR and it succeeded on 4.16.0

**Comment by rohityadavcloud** [comment]
This is not how it works - you can however, change the system service offering for VR @edikevich or for specific network/VPC offering.
Pl re-open to discuss further, thanks for the report.
