### ISSUE TITLE
VPC effective public source ip address changes

### ISSUE THREAD

**Issue by adrianopaterlini** [apache/cloudstack#5589]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION
Advanced Zone

##### OS / ENVIRONMENT
ACS - Centos 8
Hypervisor - VMware 7.0.1.0

##### SUMMARY
When one network that belongs to a VPC goes down (shutdown), effective public src ip address changes (source-nat) to a different allocated ip address. Workaround: Reboot Virtual Router.

##### STEPS TO REPRODUCE
1. Login to the UI.
2. Create a VPC with two (2) networks (A and B)
3. Create at least one VM on each network (A and B)
4. Add e configure additional ip address for each VM
5.  Run #curl ifconfig.me (at VR console)
6. Stop all VMs using the network A
7. Wait until network shuts down (network.gc.wait)
8.  Run #curl ifconfig.me (at VR console)

##### EXPECTED RESULTS

External source ip should always be the same, i.e., the ip shown as source-nat in cloudstack should show always be returned in steps 5 and 8.

##### ACTUAL RESULTS

At step 8 a different ip address is shown as source ip.

**Comment by weizhouapache** [comment]
might be fixed by #5532

**Comment by adrianopaterlini** [comment]
We tested backporting 4.15.2 with PR #5532. Its working fine.
