### ISSUE TITLE
List projects API displaying limits for users

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#5606]
For users, the API response of the `listProjects` API includes the project limits even though the UI does not display the project limits.

##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.16/main
~~~

##### CONFIGURATION
Projects

##### OS / ENVIRONMENT
N/A

##### SUMMARY
We may want to remove the project limits for users on the list projects API response. This information is not displayed in the UI. Open for discussion

**Comment by DaanHoogland** [comment]
As there has been no counter, I'm closing this as undesirable.
