### ISSUE TITLE
Restart a vpc tier with cleanup should not cleanup the whole VPC

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5615]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR/network
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0.0-rc1
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

kvm

##### SUMMARY

ideally restart a vpc network will remove the guest nic and replug it in VPC VR.
but actually VPC VR is destroyed and a new VPC VR is created.

##### STEPS TO REPRODUCE

~~~
1. create vpc
2. create vpc tier
3. create vm in vpc tier
4. restart vpc tier with cleanup
~~~

##### EXPECTED RESULTS

~~~
guest nic is removed from vpc vr and replugged.
~~~

##### ACTUAL RESULTS

~~~
VPC VR is destroyed and a new VPC VR is created.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5873
