### ISSUE TITLE
Add Footer text option for login screen

### ISSUE THREAD

**Issue by PaulAngus** [apache/cloudstack#5622]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.1%+
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA
##### SUMMARY

The ability to add text (usually help related) on the login screen would be very useful.
By adding a Login Screen Footer Text (HTML) option would for instance point users where to get login help.
Or show a usage policy.

##### STEPS TO REPRODUCE

Go to the login screen

##### EXPECTED RESULTS

![image](https://user-images.githubusercontent.com/4810220/138664280-59e51743-3998-4d2f-a961-f87cbb0d1cb6.png)

##### ACTUAL RESULTS

~~~

~~~

**Comment by PaulAngus** [comment]
As one can use inline HTML to format the footer text in the main UI through the config.json file. ie

`  "footer": "<span style='color:red'><b>IMPORTANT TEXT</b></span></br>Other text",`

Then I'd think that doing the same on the login page would give as much flexibility as anyone would need. so only one 'placeholder' would do it.

People might not realize that this can be done in the main UI.  I'll add a note on it in the documentation if it's not already there.

**Comment by DaanHoogland** [comment]
> As one can use inline HTML in the main UI through the config.json file to add text formatting and new lines. ie
> 
> ` "footer": "<span style='color:red'><b>IMPORTANT TEXT</b></span></br>Other text",`
> 
> Then I'd think that doing the same on the login page would give as much flexibility as anyone would need. so only one 'placeholder' would do it.
> 
> People might not even realize that this can be done in the main UI. I'll add a note on it in the documentation if it's not already there.

no , i didn't. thanks @PaulAngus

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5628
