### ISSUE TITLE
[UI] feature request: deploy vm with param from previous page

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5639]
Examples:

Select a network -> "View Instances" -> "Add Instance' , the network is selected by default.
Select a Template -> "View Instances" -> "Add Instance' , the template is selected by default.

##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

**Comment by sureshanaparti** [comment]
Fixed in #5653
