### ISSUE TITLE
migrateSecondaryStorageData returns success on failure

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5654]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Secondary storage
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### SUMMARY

when migrating data away from a secondary storage success is reported even when not all templates, snapshots and volumes have been migrated away.

##### STEPS TO REPRODUCE

~~~
create an image store
add templates to the store.
create a second store that won't be able to hold all the templates
migrateSecondaryStorageData from the first to the second storage 
not all template will have been migrated but success will be returned
~~~

##### EXPECTED RESULTS

~~~
error result
~~~

##### ACTUAL RESULTS

~~~
success result
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5750
