### ISSUE TITLE
VMware: Migrate VR with additional Public IPs failed

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5669]
Steps to reproduce the issue

(1) create 2 public Ip ranges
(2) create an isolated network, and a vm
(3) acquire a public IP in new ip range (not same as Source NAT), create port forwarding rules to the vm. VR will have two public NICs (source NAT IP, and new public IP).
```
# esxcli network vm port list -w 178877 |grep Portgroup

   Portgroup: cloud.private.untagged.0.1-vSwitch0
   Portgroup: cloud.public.51.200.1-vSwitch1
   Portgroup: cloud.guest.1206.200.1-vSwitch1
   Portgroup: cloud.public.670.200.1-vSwitch1
```

(4) choose a destination host, remove the port group `cloud.public.670.200.1-vSwitch1` on it (this normally happens on vm migration across clusters while the port group does not exist on destination host).

```
# esxcli network vswitch standard portgroup remove -p cloud.public.670.200.1-vSwitch1 -v vSwitch1
```

(5) migrate VR  to destination host, failed with error
```
2021-11-08 08:58:41,867 DEBUG [c.c.a.t.Request] (DirectAgent-129:ctx-1ca672fa) (logid:36218135) Seq 1-1048212813270500266: Processing:  { Ans: , MgmtId: 32986087031327, via: 1(10.0.33.238), Ver: v1, Flags: 10, [{"com.cloud.agent.api.MigrateAnswer":{"result":"false","details":"MigrationCommand failed due to Exception: java.lang.RuntimeException
Message: Currently connected network interface 'Network adapter 5' uses network 'cloud.public.670.200.1-vSwitch1', which is not accessible.
","wait":"0","bypassHostMaintenance":"false"}}] }
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Vmware
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0.0-RC3
~~~

##### CONFIGURATION

vmware
basic networkking

##### SUMMARY

see title

##### STEPS TO REPRODUCE

~~~
see description
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment]
Fixed by https://github.com/apache/cloudstack/pull/5670
