### ISSUE TITLE
Can not copy template between two Basic zones with the cloudstack4.15.1

### ISSUE THREAD

**Issue by fengdoudm** [apache/cloudstack#5678]
**Version: cloudstack4.15.1
System: Centos7.9**

There were two basic zones named 'stage' and 'qa.
The network for 'stage': 172.16.116.0/24
The network for 'qa': 172.16.126.0/24
I can not copy template from 'stage' to 'qa'
There was some error with '**HTTP Server returned 403 (expected 200 OK)**'
I have no idea to solve it, the following were some information.

![image](https://user-images.githubusercontent.com/8956444/141279153-f9fb1bcb-4260-4927-82a7-1d9eec775bb5.png)
![image](https://user-images.githubusercontent.com/8956444/141279500-5d60a9db-8b5d-4317-948c-afabe0b417b5.png)

**Comment by fengdoudm** [comment]
I found there was a IP limit .
![image](https://user-images.githubusercontent.com/8956444/141444461-f0b36513-18ac-47f0-b21f-e06595e95348.png)

**Comment by nvazquez** [comment]
Hi @fengdoudm this looks like a configuration issue. Please check the management server logs for more detail on the issue and the connectivity between them

**Comment by DaanHoogland** [comment]
fixed in #7288
