### ISSUE TITLE
Can't create multiple port forwarding rules at once

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5688]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't add multiple port forwarding rules at once for 1 VM

##### STEPS TO REPRODUCE
~~~
Add first port forwarding rule and add it to VM
Try to add second rule to this VM
~~~
##### EXPECTED RESULTS
~~~
User can add both rules
~~~

##### ACTUAL RESULTS
~~~
After U add first rule U can't add second. Only switching between VM's allow U add second rule on VM which U want.
~~~

**Comment by weizhouapache** [comment]
@edikevich 
do you use vpc or isolated network ?
can you share some error logs ?

**Comment by edikevich** [comment]
Hi.
Have same problem with VPC and Isolated networks. After I add first rule I can't push "OK" button when create second rule.
I don't have any errors in management server logs.

**Comment by weizhouapache** [comment]
@edikevich 
I see, thanks. It seems to be a UI bug. 
If you refresh the page, you should be able to add port forwarding rule.

**Comment by edikevich** [comment]
Thx. Yes I found how to avoid it but when U create  more than 5 rules is realy annoyed:(

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5690
