### ISSUE TITLE
UI: Issue with Add Network to VM

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#5691]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1 (and above)
~~~

##### SUMMARY

When adding a NIC to a VM fails and a user re-attempts to add a NIC, the form appears to have the previously selected network. However, on submitting the form, the first network from the list of available networks is automatically selected, rather that the network that appears to be pre-populated on the form. Also, submitting the form with out selecting any network picks the first network from the list of available networks.

##### STEPS TO REPRODUCE

~~~
1. Create a VM
2. Try adding a NIC to the VM by selecting a network and providing an already allocated IP / providing an incorrect IP , such that it fails
3. Re-try adding a NIC to the network by opening the 'Add network to VM' form, observe that the previously selected network already appears to be prepopulated in the network field, and provide a desired IP from the network (if required) and submit the form
4. On checking API request, it is observed that the network id corresponds to the 1st network in the drop-down list and not the pre-selected network.

~~~

##### EXPECTED RESULTS

~~~
The VM gets added to the selected network
~~~

##### ACTUAL RESULTS

~~~
The VM is added to the 1st network from the drop-down.
~~~

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5693
