### ISSUE TITLE
Uploaded volumes use the first custom disk offering

### ISSUE THREAD

**Issue by alexandru-bagu** [apache/cloudstack#5696]
In a multi-zone setup where the zones are configured to use different storage types (shared vs local) the uploaded volume will not have assigned the first Custom disk offering available without considering zone.

Even if the zones in the setup use the same kind of storage only the disk offerings available for the selected zone in the upload form should be considered.

In my case my first zone is using local storage and if I want to upload a volume in the second zone which uses Shared storage I must first change the disk offering to the shared storage one otherwise I get an error that the zone does not support local storage (because I don't have any local storage pools configured).

**Comment by sureshanaparti** [comment]
Fixed in #5852
