### ISSUE TITLE
Hide shrink disk option on XCP-NG/Xenserver

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5698]
##### ISSUE TYPE
 * Bug Report?
 
##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone
PreSetup iscsi storage

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Shrink disk don't work on XCP-NG/Xenserver. Maybe better to hide this option?

##### STEPS TO REPRODUCE
~~~
Create VM. Stop VM. Go to Volumes. Try to resize volume with shrink option. Wait for "OK" message.
~~~

##### EXPECTED RESULTS
~~~
XCP-NG/Xenserver dont allow to shrink disks. In XOCE, XCP-NG Center we see error message when we try to shrink disk. In CS we should see error message too or don't see shink option.
~~~

##### ACTUAL RESULTS
~~~
Shrink option is presented in WebUI but after shrink volume nothing happends. Volume stayed in original size.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5829
