### ISSUE TITLE
UI: 4.16 cannot set correct traffic label

### ISSUE THREAD

**Issue by lijinlongpq** [apache/cloudstack#5705]
I installed cloudstack on Ubuntu 20.04 from DEB package repository. Tried to add a new zone, but somehow failed to set traffic label correctly with both basic network and advanced network. 

In my env, I got two networks, cloudbr0 & cloudbr1. When I set management network with label cloudbr0. The Guest network been setted with label cloudbr0 too. Same way, I set Guest network with lable cloudbr1, then management network also got label cloudbr1. Just cannot set individual label for each network. Tried with different browsers: Chrome, Edge & Firefox and all having same issue. 

Not sure whether it's a bug or I did something wrong.

Kindly help.

**Comment by utchoang** [comment]
@lijinlongpq Do you mean that when you did set a label for a network with name "cloudbr0" and then done with the next network, it shows "cloudbr0" in the input label for it right?

**Comment by lijinlongpq** [comment]
@utchoang Not only confusing, the fact is when I set a label with name "cloudbr0", the next network it shows "cloudbr0". And If I edit the second one with name "cloudbr1". Then I go back to check, the first one also shows name "cloudbr1". It looks like overwrite the first network setting which is not correct.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5714
