### ISSUE TITLE
Can't paste any value in Get Diagnostics Data

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5707]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't paste any value in Get Diagnostics Data:
![image](https://user-images.githubusercontent.com/42668237/142991251-8e365f79-efc9-4781-9d5d-38097fd40bd7.png)

##### STEPS TO REPRODUCE
~~~
Try to get Diagnostics Data from VM or System VM
~~~
##### EXPECTED RESULTS
~~~
Administrator can paster any available value, for example, iptable or all Diagnostics Data after click OK button
~~~

##### ACTUAL RESULTS
~~~
Administrator can't paster any available value. Only all Diagnostics Data after click OK button are presented.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5853
