### ISSUE TITLE
Error message after delete domain

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5709]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Error message after delete domain but it was deleted:

![image](https://user-images.githubusercontent.com/42668237/142993177-e1815200-4859-4106-8600-b4c75c1e404a.png)

##### STEPS TO REPRODUCE
~~~
Create new domain. Then delete it.
~~~
##### EXPECTED RESULTS
~~~
Domain was deleted without any errors.
~~~

##### ACTUAL RESULTS
~~~
Error message after delete domain but it was deleted
~~~

**Comment by sureshanaparti** [comment]
Verified the fix PR and merged. Closing this issue.
