### ISSUE TITLE
Problem enabling LDAPS.

### ISSUE THREAD

**Issue by correajl** [apache/cloudstack#5712]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Code, API.
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.15.2.0
~~~

##### CONFIGURATION

Using many domains. 
Trying to use LDAP server with TLS.
All certificates generated and tested.
Keystore configured and tested. 

##### OS / ENVIRONMENT

Ubuntu Server 20.04.3 LTS.
KVM.
cloudstack-management                4.15.2.0~focal

##### SUMMARY

Need to communicate management server with LDAP using TLS (LDAPS). Documentation says if ldap.truststore and ldap.truststore.password are configured it will switch working to LDAPS. It just happens when these parameters are configured globally but using API it is possible to configure them inside a domain. When configured inside a domain we have no effect. 

##### STEPS TO REPRODUCE

Try to configure ldap.truststore and ldap.truststore.password for a domain:

cmk -p user@myprofile update configuration name='ldap.truststore' value='/etc/cloudstack/management/cloud.jks' **domainid="e8b2ec00-21e2-430b-bd9b-a31c3d642bbf"** 
cmk -p user@myprofile update configuration name='ldap.truststore.password' value=PASSWORD **domainid="e8b2ec00-21e2-430b-bd9b-a31c3d642bbf"** 

##### EXPECTED RESULTS

~~~
LDAPS enabled and communication between management and LDAP servers using TLS. 
~~~

##### ACTUAL RESULTS

~~~
LDAPS is not enabled. 
LDAP server logs shows "initializing ldap with provider url: ldap://ldapserver.domain:636".
All queries trying to log in a user use ldap:// too, not ldaps://. 
~~~

If we configure ldap.truststore and ldap.truststore.password globally (not for a domain), so we can make LDAPS to work. 

~~~
cmk -p user@myprofile update configuration name='ldap.truststore' value='/etc/cloudstack/management/cloud.jks'
cmk -p user@myprofile update configuration name='ldap.truststore.password' value=PASSWORD
# Until here no domain was specified!
cmk -p user@myprofile add ldapconfiguration hostname=ldapserver.mydomain port=636 domainid="e8b2ec00-21e2-430b-bd9b-a31c3d642bbf"
cmk -p user@myprofile update configuration name='ldap.basedn' value='...............' domainid="e8b2ec00-21e2-430b-bd9b-a31c3d642bbf"

~~~
I think the code is looking for ldap.truststore and ldap.truststore.password only in global configuration. It would be interesting looking inside domain configurations too. So, each domain could have a different LDAP configuration.  As the API accepts the domainid= parameter to configure the truststore, I believe that the initial idea was this, but something is not working as well.

**Comment by DaanHoogland** [comment]
@correajl if i make a PR on 4.16 to fix this will you be able to test it? I seems like the fix is rather simple (but testing isn't) I'll try to add some unit tests later.

**Comment by DaanHoogland** [comment]
ping @correajl can you test #5816 ?

**Comment by sureshanaparti** [comment]
> ping @correajl can you test #5816 ?

Hi @correajl Can you help in testing the PR #5816. Thanks.

**Comment by correajl** [comment]
Yes, I'm going to test as soon as possible.

tks

- JLC

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5816
