### ISSUE TITLE
Can't chose VM for static NAT because only one page in VM chose dialog is presented.

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5715]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't chose VM for static NAT because only one page in VM chose dialog is presented. I think this problem is actual for other VM chose dialog.

##### STEPS TO REPRODUCE
~~~
Create many VM in one network. Try to enable static NAT for VM.
~~~
##### EXPECTED RESULTS
~~~
All pages in VM chose dialog are presented. U can chose VM from any page.
~~~

##### ACTUAL RESULTS
~~~
Only one page in VM chose dialog is presented. Search dialog can help avoid issue.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5849
