### ISSUE TITLE
Can't create S3 Secondary Storage in created zone

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5718]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Can't create S3 Secondary Storage after create zone. While U create zone S3 SS is presented
![image](https://user-images.githubusercontent.com/42668237/143389544-13086163-f039-4a87-8721-99ff3b2309ce.png)
![image](https://user-images.githubusercontent.com/42668237/143389750-6a026e19-5e80-411d-b54a-308f0d662d92.png)

##### STEPS TO REPRODUCE
~~~
Create Zone. Try to add second Secondary Storage with S3 provider.
~~~
##### EXPECTED RESULTS
~~~
Can create second SS with S3 provider
~~~

##### ACTUAL RESULTS
~~~
S3 provider is missing in chose dialog
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5726
