### ISSUE TITLE
Cannot scale VM with deleted template

### ISSUE THREAD

**Issue by alexandru-bagu** [apache/cloudstack#5719]
CS version 4.16.0

Error occurs here:
```
java.lang.NullPointerException
        at com.cloud.vm.UserVmManagerImpl.checkIfDynamicScalingCanBeEnabled(UserVmManagerImpl.java:4138)
```

**Comment by sureshanaparti** [comment]
Hi @alexandru-bagu Are you able to delete the template when a VM exists / using that template?

**Comment by harikrishna-patnala** [comment]
There is force delete option for templates @sureshanaparti. This looks like a genuine issue I could reproduce it.
