### ISSUE TITLE
Tags are displayed incorrectly or aren't displayed at all

### ISSUE THREAD

**Issue by edikevich** [apache/cloudstack#5727]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16.0
~~~

##### CONFIGURATION
XCP-NG 8.2
Advanced Zone

##### OS / ENVIRONMENT
Oracle Linux 8.4 - Management server, MYSQL 8.0.26
XCP-NG 8.2 - hypervisor

##### SUMMARY
Storage tags are displayed incorrectly:
![image](https://user-images.githubusercontent.com/42668237/143834351-270ff46d-024c-4136-8dcb-7d5934c3959c.png)

![image](https://user-images.githubusercontent.com/42668237/143834392-e3480f73-c4bf-4354-a749-fac26a10b738.png)

Host tags aren't displayed

![image](https://user-images.githubusercontent.com/42668237/143834698-d115cda4-e835-473d-a28a-3c1935f6a58e.png)

![image](https://user-images.githubusercontent.com/42668237/143834730-27364bf5-7150-4e18-91e0-efe1bca723e0.png)

##### STEPS TO REPRODUCE
~~~
Add tag to storage
~~~
##### EXPECTED RESULTS
~~~
Storage's tags are displayed correctly. Host's tags are displayed.
~~~

##### ACTUAL RESULTS
~~~
Storage tags are displayed incorrectly. Host tags aren't displayed.
~~~

**Comment by shwstppr** [comment]
@edikevich Tags in the info card of the UI is different from host, storage tags. Please see #5798 fixes the behaviour

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5798
