### ISSUE TITLE
Support VMware7 minor release

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#5728]
Support VMware 7.0u2, 7.0u3 in CloudStack. Currently with 4.15 onwards only Vmware 7.0u1 is supported.

##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2.0, 4.16.0.0
~~~

**Comment by rhtyd** [comment]
Note: it seems VMware ESXi 7.0u3 has some issues and was called off, but vCenter 7.0u3 is available out there.

**Comment by rohityadavcloud** [comment]
Closing this issue, we've a PR.
