### ISSUE TITLE
Exception while update vm with 'HA Enabled' checked

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5743]
steps to reproduce the issue

(1) create a vm from default compute offering 'Small Instance'
(2) stop vm
(3) update vm, check 'HA Enabled'

Got an exception:
```
2021-12-02 09:34:13,313 ERROR [c.c.a.ApiServer] (qtp1840903588-15:ctx-6d9864ce ctx-5d3387f4) (logid:ad4a7d0a) unhandled exception executing api command: [Ljava.lang.String;@4c4af26b
com.cloud.utils.exception.CloudRuntimeException: Failed to update VM, due to: Can't enable ha for the vm as it's created from the Service offering having HA disabled
	at org.apache.cloudstack.api.command.user.vm.UpdateVMCmd.execute(UpdateVMCmd.java:271)
```

two options
(1) fix it on UI 
(2) remove the restriction in API

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI/API
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Fixed in #5847
