### ISSUE TITLE
[Vmware][Deploy-as-is] DB exception when the template/appliance has empty default values

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#5747]
Cannot deploy VM from a template when:
- 'Read Settings from OVA' = true
- The template has one or more properties without a default value (null values)

Example (missing the `ovf:value` property):
```
<Property ovf:key="SCHProxyPort" ovf:type="string" ovf:userConfigurable="true">
        <Label>Smart Call Home HTTP Proxy port number</Label>
        <Description>HTTP proxy server port number (Defaults to port 80 if omitted.)</Description>
</Property>
```

Leads to:
![image](https://user-images.githubusercontent.com/5295080/144592239-4174efd3-3a01-4e23-ac62-98336f5ca0df.png)

##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
VMware
~~~

##### CLOUDSTACK VERSION
~~~
4.16 (main)
~~~

##### STEPS TO REPRODUCE
~~~
- Register a template missing default values for properties as described above using 'Read Settings from OVA' = true
- Deploy VM
~~~

##### EXPECTED RESULTS
~~~
Deployment succeeds
~~~

##### ACTUAL RESULTS
~~~
Exception (picture above)
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5748
