### ISSUE TITLE
The question about the cloudstack primary storage

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#5751]
Does cloudstack's cluster support two different types of primary storage like one is NFS, another is RBD?

**Comment by sureshanaparti** [comment]
@xuanyuanaosheng yes,  cloudstack's cluster supports different storage types. More details here: http://docs.cloudstack.apache.org/en/latest/adminguide/storage.html#primary-storage

It's better to ask questions in the dev mailing list "dev@cloudstack.apache.org".

**Comment by xuanyuanaosheng** [comment]
@sureshanaparti  Thanks for you reply. Could you please take a look at https://github.com/apache/cloudstack/issues/5741
