### ISSUE TITLE
UI: SSH key option should not be presented if not allowed/support

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#5765]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15
4.16
~~~

##### CONFIGURATION
- UI
- SSH API calls not allowed

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Dynamic role which does not allow for any of the 'SSH' API calls like: https://cloudstack.apache.org/api/apidocs-4.16/apis/listSSHKeyPairs.html

The user is however still prompted for SSH keypairs during instance deployment.

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/326786/145641788-2de56f7b-51e1-43f4-834e-843ea5186b55.png">

##### STEPS TO REPRODUCE
- Create a new Role which does not allow any of the 'ssh' API calls
- Deploy a new Instance
- The UI will still prompt SSH keypair options

##### EXPECTED RESULTS
The UI should not show the SSH keypair options during deployment.

The only option for users to get SSH keys into the Instance would be using the userdata for cloud-init.

##### ACTUAL RESULTS
The UI still shows the option for SSH keypairs while the user does not have the permissions for this.

**Comment by sureshanaparti** [comment]
Closing this issue as the fix PR got merged. @wido Please reopen if you still notice SSH key option when it is not allowed/supported for the user. Thanks.
