### ISSUE TITLE
UI: Rootdisksize is not shown as 'Disk Size' on VM deployment

### ISSUE THREAD

**Issue by wido** [apache/cloudstack#5777]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.15
4.16
~~~

##### CONFIGURATION
Rootdisk size set to for example 40GB for a disk offering

##### SUMMARY
The rootdisksize for a ServiceOffering is set to 40GB.

During deployment the UI however does not show the rootdisksize in the summary details of the VM.

This means that the user has no idea how large the root disk will be after deployment.

##### STEPS TO REPRODUCE
- Create a Service Offering with a fixed rootdisksize
- Select this Service Offering during deployment
- You will see the disk size is not modified

##### ACTUAL RESULTS
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/326786/146177729-a4de1761-f3df-4b69-8bf1-5034693a887e.png">

**Comment by sureshanaparti** [comment]
Hi @GabrielBrascher Are you working on the fix for this issue?

**Comment by GabrielBrascher** [comment]
@sureshanapart I have just opened a PR fixing it. Please, check it out at: #5796

**Comment by sureshanaparti** [comment]
> @sureshanaparti I have just opened a PR fixing it. Please, check it out at: #5796

thanks @GabrielBrascher , will check it.

**Comment by GabrielBrascher** [comment]
Closing this issue as the PR #5796 fixing it got merged.
