### ISSUE TITLE
Feat: Add Prometheus and Grafana monitoring support 

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#5778]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
API, UI, SDK go
~~~

##### CLOUDSTACK VERSION

~~~
4.17, 4.16
~~~

##### SUMMARY

Many users need to monitor Cloudstack management server resources, such as Disk, CPU, Bandwidth, Public IPs, etc.
This has already been implemented  [here](https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+Metrics+Exporter+for+Prometheus) and in #4173

It was also covered on CCC 2021 [here](https://www.youtube.com/watch?v=m8mYdWHoxLY&list=PLnIKk7GjgFlY7L4-pp3pAD_b5IVEFd_2b&index=7).

However, this feature is still not available for general use.  So need to make usable the already implemented feature

~~~
~~~

**Comment by weizhouapache** [comment]
@tampler 
what are missing in your opinion ?
afaik it just works.

**Comment by tampler** [comment]
hi @weizhouapache 

Are there any API methods to enable/disable/update/remote metrics? Are there GUI knobs? 
It just works from the SQL cmdline, which is why 99.99% of users NOT aware of it. Correct me if I'm wrong. Any links are highly welcome

**Comment by weizhouapache** [comment]
> 



> hi @weizhouapache
> 
> Are there any API methods to enable/disable/update/remove metrics? Are there GUI knobs? It just works from the SQL cmdline, which is why 99.99% of users are NOT aware of it. Correct me if I'm wrong. Any links are highly welcome

@tampler 
no API, no GUI.
you can get all metrics by cli `curl http://127.0.0.1:9595` if prometheus exporter is enabled in global setting.
you can also use the http url in grafana.

**Comment by nvazquez** [comment]
Hi @tampler afaik it is working. Can you please confirm if the issue is still valid after @weizhouapache's comment?

**Comment by tampler** [comment]
Yes, works for me. Thanks everybody !

**Comment by meisammaleki** [comment]
Hello
I have enabled Prometheus on ACS version 4.17.2 and now I can get the metrics on Prometheus, the question is, Is there any dashboard for these metrics? or I should use the queries on grafna?
