### ISSUE TITLE
UI: create network dialog digressed 

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5780]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16 and main
~~~

##### SUMMARY

When trying to create a new network the dialog is empty:

![image](https://user-images.githubusercontent.com/2486961/146195942-9e2fe809-571a-40ce-be2c-6b583f26a4b7.png)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Closing this as the fix PR is merged. @DaanHoogland Reopen the issue if you still notice it. Thanks.
