### ISSUE TITLE
Management server does not respect max.project.public.ips

### ISSUE THREAD

**Issue by KuasarCloud** [apache/cloudstack#5787]
ISSUE TYPE
Bug Report

COMPONENT NAME
PUBLIC IP

CLOUDSTACK VERSION
4.15.2.0

CONFIGURATION

SUMMARY
Configured the parameter with max.project.public.ips = 3 and restart the management server, but the user can acquire as many public ip as he wishes

STEPS TO REPRODUCE
Have advanced zone with and VPC deployed into a project
Restrict the variable in global configuration
Acquire multiples IP beyond the set limit

EXPECTED RESULTS
Restrict the number of IP set by the global configuration parameter max.project.public.ips

**Comment by nvazquez** [comment]
Hi @KuasarCloud, besides the global setting have you checked the project limits? The default value for 'Max. Public IPs' per project is 20 - can you try configuring the limits under Project -> Project -> Configure Limits -> Max. Public IPs (if not done already) and restart the management server?

**Comment by nvazquez** [comment]
@KuasarCloud I'm closing this issue per my comment above, if the issue persists please reopen it
