### ISSUE TITLE
CloudStack API does not allow to set domain for templates via "createTemplate" nor "updateTemplate"

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#5793]
##### ISSUE TYPE

 * Feature Idea ?

##### COMPONENT NAME

~~~
API
~~~

##### CONFIGURATION

~~~
N/A
~~~

##### OS / ENVIRONMENT

~~~
N/A
~~~

##### SUMMARY

In [registerTemplate](https://cloudstack.apache.org/api/apidocs-4.15/apis/registerTemplate.html) there is the possibility of choosing a domain id; however this is not possible when creating a template via [createTemplate](https://cloudstack.apache.org/api/apidocs-4.15/apis/createTemplate.html). Additionally, CloudStack does not offer support for updating templates domainid (see: [updateTemplate](https://cloudstack.apache.org/api/apidocs-4.15/apis/updateTemplate.html)).

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
N/A
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~

**Comment by nvazquez** [comment]
Hi @GabrielBrascher are you working or planning to work on this?

**Comment by rohityadavcloud** [comment]
The problem statement is to add a domainid parameter to the createTemplate API that is available only for root admin, like the domainid paramter for this API: https://cloudstack.apache.org/api/apidocs-4.18/apis/registerTemplate.html

When domainid is provided and if the caller is the root admin, the create template should create template for the specified domainid using a volume or a snapshot.

**Comment by GabrielBrascher** [comment]
Perfect @rohityadavcloud that was the idea indeed.
I'm not working on this, just wanted to discuss and check some options.
Considering this is an old "issue" raised, I can close for now, or we can leave it open if anyone want's to work/discuss in this context.
