### ISSUE TITLE
UI: Add network offering form not showing "System offering for router" for VPC and provider list is not getting updated on VPC toggle

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#5807]
I've observed 2 issues
1. When trying to create a VPC network offering, option to select "System offering for router" is missing. In case of normal networking offering it is showing.
2. When VPC toggle button turns on and off, supported providers list is updating dynamically, we had to start a new "Add network offering" form.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15, 4.16, main
~~~

##### STEPS TO REPRODUCE

~~~
1. Click "Add network offering"
2. Turn On VPC toggle button 
3. Select any supported services and provider as "VpcVirtualRouter", the "Select Offering for Router" drop down is missing. 
4. To see how it looks, start a fresh "Add network offering" form and select any service with provider as "Virtual Router", we can see the "Select Offering for Router" dropdown like below 
~~~
![image](https://user-images.githubusercontent.com/3348673/147317404-10bfa08f-4f2b-4190-b0ed-ad69ba9bd3c1.png)
~~~
1. Click "Add network offering"
2. Keep VPC toggle button off
3. Select DNS service and provider "Virtual Router"
4. Turn On VPC toggle button
5. Try to change the DNS provider to "VpcVirtualRouter", we could not do that. This is working fine in 4.15 but not in 4.16 and main.
~~~
![image](https://user-images.githubusercontent.com/3348673/147318418-813123b0-529c-4463-8257-5246166cdc4b.png)

##### EXPECTED RESULTS

~~~
1. Click "Add network offering"
2. Turn On VPC toggle button 
3. Select any supported services and provider as "VpcVirtualRouter", we should see the "Select Offering for Router" dropdown like below 
~~~
![image](https://user-images.githubusercontent.com/3348673/147317414-89273ca1-67ad-495b-b4fb-5156b73908a2.png)

~~~
1. Click "Add network offering"
2. Keep VPC toggle button off
3. Select DNS service and provider "Virtual Router"
4. Turn On VPC toggle button
5. Try to change the DNS provider to "VpcVirtualRouter", we should be able see updated list and select "VpcVirtualRouter"
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Hi @utchoang Is it possible for you to check this issue.

**Comment by shwstppr** [comment]
Apologies @utchoang (cc @sureshanaparti ) if you already started work on this. Created a draft PR. Please close it if you can with a better fix. Was getting some issue with making select element update on options change

**Comment by utchoang** [comment]
@shwstppr No problem, I haven't started this work either. I will review your PR.
