### ISSUE TITLE
VMware: upload template from local is not importing OVF properties

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#5808]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### SUMMARY

In the case of VMware, when we register a template from URL and turn on "Read VM settings from OVA" toggle then OVF properties from the template are imported into CloudStack. When we upload the same template from local and turn on "Read VM settings from OVA" toggle then OVF properties are not getting imported.

##### STEPS TO REPRODUCE

~~~
1. Click upload template Icon under Images > Templates
2. Select an OVA that has predefined OVF properties
3. Turn on the "Read VM settings from OVA" option 
~~~

##### EXPECTED RESULTS

~~~
OVF properties should have been successfully imported into CloudStack
~~~

##### ACTUAL RESULTS

~~~
OVF properties did not import into CloudStack
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5861
