### ISSUE TITLE
Load Balancer - Configure Sticky Policy

### ISSUE THREAD

**Issue by satishglondhe** [apache/cloudstack#5813]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI & API
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0.0 
~~~

##### OS / ENVIRONMENT

NA

##### SUMMARY

While configuring any type of Sticky Policy for a Load Balancer, the OK button is not working [it doesn't throw any error nor it gets submitted]  therefore not able to create any type of sticky policy. 

Also, we tried to execute the same using the API's but that is also not working. 

##### STEPS TO REPRODUCE

~~~
1. Create Load Balancer
2. In Load Balancer Details Table - Stickiness Column
3. Click on "Configure" button one popup will open with the Configure Sticky Policy form
4. Fill up all required data and click on "Ok" button.
~~~

##### EXPECTED RESULTS

~~~
It should submit the form and create stickiness policy for Load Balancer
~~~

##### ACTUAL RESULTS

~~~
Nothing will happen. Not showing error not submitting form
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5814
