### ISSUE TITLE
How to switch from management server :root@cloud-mgmt:~#    to nfs server :root@cloud-nfs:~#   in the same machine

### ISSUE THREAD

**Issue by lequocvieet** [apache/cloudstack#5821]
##### ISSUE TYPE
*Documentation report
http://docs.cloudstack.apache.org/en/latest/installguide/management-server/index.html#using-a-separage-nfs-server
##### COMPONENT NAME
Prepare separate NFS server 
##### CLOUDSTACK VERSION
4.16
##### OS / ENVIRONMENT
Ubuntu 20.04

##### SUMMARY
I am following documentation in preparing NFS server separate but I don't know how to switch from management server to NFS server in the terminal 
![image](https://user-images.githubusercontent.com/70306842/147909975-59eebbb9-7cbe-42bf-9c3e-f4d308a7925e.png)
This image said that "on the storage server" but I am on the management server, I don't know how to switch to another server or create another server in my terminal.

##### EXPECTED RESULTS
Does anyone know how to do this, I expect after config nfs is done in my machine has two servers: management server and nfs server separately. For example: :root@cloud-mgmt:#   and  root@cloud-nfs:#  
May I use SSH or something else?

**Comment by DaanHoogland** [comment]
@lequocvieet can you ask this question on the mailing list users@cloudstack.apache.org, please.

**Comment by rohityadavcloud** [comment]
Yes pl ask on the users ML, thanks.
