### ISSUE TITLE
"storage.max.volume.size" config needs fixing

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#5830]
There is a global config to control the size of the volume
![image](https://user-images.githubusercontent.com/3348673/148359893-7b71bc92-a8f3-4fb2-9732-6dac4299c181.png)

There are 2 issues with this config
1. This is marked as dynamic, but it is not, we need to restart the management server. This needs to either set the dynamic flag to false or fix the usage of the config.
2. In the case of root volume, when the root volume is first created this config is not considered, later if we try to resize the same root volume then the config is being considered.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Global Setting
~~~

##### CLOUDSTACK VERSION

~~~
4.16, main
~~~

##### STEPS TO REPRODUCE

~~~
1. set the config value of "storage.max.volume.size" to 2GB
2. create a VM with root disk size more than 3GB
3. Try to resize the root volume to some higher value 
~~~

##### EXPECTED RESULTS

~~~
Root volume with higher size should not be created.
~~~

##### ACTUAL RESULTS

~~~
Root volume is created with higher value and if we try to resize then operation failed with error stating the global setting.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5857
