### ISSUE TITLE
documentation instructs users to setup libvirt dangerously insecurely

### ISSUE THREAD

**Issue by pipo** [apache/cloudstack#5834]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~
Documentation
~~~

##### SUMMARY

The documentation at https://docs.cloudstack.apache.org/en/latest/installguide/hypervisor/kvm.html#install-and-configure-libvirt
instructs users to setup libvirt with TCP connections with no authentication enabled. This is an extremely dangerous setup. Anyone allowed to access libvirt, which in this case is at least all local (unprivileged) users may use libvirt to spawn privileged processes.

The documentation is also misleading because it claims that it's the only way for migrations to work. Libvirt supports migrations using all protocols and transports, it's just that the secure variants actually require a bit of setup.

Trading total insecurity for omitting a few setup steps is a very bad trade.

A suggested configuration is to use SSH keys for ssh transport or setup TLS client and server certificates. Both then don't require any more user interactions.

**Comment by pipo** [comment]
Libvirt was accidentally made aware of this problem in the following libvirt bug report: https://gitlab.com/libvirt/libvirt/-/issues/264#note_803220900

**Comment by berrange** [comment]
> This is an extremely dangerous setup

To be explicit, we consider a connection to privileged libvirtd to be equivalent to have a root shell. IOW, configuring libvirtd to listen on a TCP socket with no encryption and no authentication is equivalent to replacing SSH with RSH and setting an empty root password.

**Comment by rohityadavcloud** [comment]
@pipo, while the initial config may not look optimal, by default, when you add host in CloudStack (using root user + password or ssh-public key based auth) libvirtd is reconfigured with TLS certificates from CloudStack's CA framework with listening/ports reconfigured on port 16514 on localhost. When making connection, the cloudstack-agent process talks to libvirtd over TLS/16514 (both for local-kvm/libvirt operations and for live VM migration across hosts). It is assumed that admin will put some kind of firewall configuration in production env. The host security (CA framework) is discussed here: https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#security

Pl do suggest or raise a PR here if there's any specific config we're put in the installation section: https://github.com/apache/cloudstack-documentation

**Comment by berrange** [comment]
If it is going to be reconfigured with TLS, why is it needed to first configure it with TCP ?  Why not just leave it using the local UNIX socket only until TLS is ready to be configured, rather than introducing this period of time (however short) when the host security is wide open to any malicious entity.

**Comment by Hudratronium** [comment]
@rohityadavcloud 
Reading through this topic reminded me, that maybe some of the documentation might be a bit "outdated" in regards of the functionality of the installation scripts / scripts running during the add-on process of the hosts?
As far as i experienced in my configurations (Ubunutu 20.04 for Hosts, KVM) i didn't need to configure libvirt anymore prior the installation of the CS Agent / add on to CS-Cluster.  Same goes for apparmor. 
So this step might just be needed for "older" CS Versions as well as other or older host-os?

Another question - more out of interest is - when the inital configurtation of libvirt is taking place. While installing the CS Agent or while the add-on-process you described  above?
Depending on this, we could think of mark this steps as deprecated or just for "documentional purposes" and not part of the actual installation routine?

**Comment by rohityadavcloud** [comment]
@pipo thanks for the report, we can certainly improve the QIG docs; however, by default when KVM hosts are added, they libvirtd is secured by CloudStack CA certs; https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#security

**Comment by cfergeau** [comment]
https://docs.cloudstack.apache.org/en/latest/installguide/hypervisor/kvm.html#install-and-configure-libvirt and https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#securing-process seem to be contradicting each other?
The former mentions plain text migration, and accessing libvirt over tcp / port 16509 while the latter says:
> A secured host will only allow and initiate TLS enabled live VM migration. This requires libvirtd to listen on default port 16514, and the port to be allowed in the firewall rules.

**Comment by Hudratronium** [comment]
@cfergeau 
you stumbled over a "general" problem imho - that the documentation is kind of outdated in several parts. Especially in the areas of "installation guides". From my experience i didn't need to change any libvrit configuration files at all after installing the CS Agent. Same goes for the configuration of AppArmor and SELinux.
Some of the mentioned steps are performed now while installing the CS Agent on the host. Same goes for some other features that aren't "updated" in the current docs or not even mentioned.
