### ISSUE TITLE
Improve kvm vm snapshot

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5836]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

We have achieved
xenserver: volume snapshot and vm snapshot
vmware: volume snapshot and vm snapshot
KVM+NFS: volume snapshot and vm snapshot
kvm +ceph: Only support volume snapshots;

kvm+ceph primary storage, it is a very perfect combination.
But we currently do not support KVM+ceph vm snapshots, I think this is a very large feature loss;

Libvrit api does not support vm snapshot in raw format (it may be the biggest obstacle to achieving this function).

We can refer to the openstack processing method:
1. suspend the vm
2. use the agent to connect to the ceph api to directly create a snapshot of all the volumes on the vm
3. resume vm

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by nvazquez** [comment]
@slavkap can you confirm if the PR #3724 fixes this issue?

**Comment by slavkap** [comment]
Hi @nvazquez, yes, it follows the described steps, but we freeze the VM instead of suspending it. It should work and for other storages as well

**Comment by nvazquez** [comment]
Thanks @slavkap, adding it to the 4.17 milestone tentatively

**Comment by nvazquez** [comment]
Hi @div8cn - PR #3724 addresses this issue and is ready now, could you please test it?
