### ISSUE TITLE
confusing error message on successful deployment

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5888]
password message shows as error:
![image](https://user-images.githubusercontent.com/2486961/150749140-d8e5b67c-0fd3-48f4-be5e-02ba7fcf0125.png)

I am not sure how this changed, but it is a bit confusing to have an initial password being desplayed in an error message after a successful deployment and as success report .

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
head of 4.16.1 branch
~~~

##### STEPS TO REPRODUCE

~~~
deploy a VM from a password enabled template.
~~~

##### EXPECTED RESULTS

~~~
a success message (with a green check for instance)
~~~

##### ACTUAL RESULTS

~~~
an error message containing the password.
~~~

**Comment by sureshanaparti** [comment]
Fixed in #5889
