### ISSUE TITLE
Destroying SSVM reported to have failed, while it actually succeeded

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#5895]
while destroying a system VM (ssvm in this case) it is reported to have failed, while it actually succeeded,

![image](https://user-images.githubusercontent.com/2486961/150986144-11be44ee-6e04-4bb4-a521-720812e9c40b.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
@DaanHoogland some logs here might be helpful to check what is the issue.

**Comment by DaanHoogland** [comment]
yes, of course. I was to busy on other things to give this much attention. I don't think it has high severity hence I just left it here as is.

**Comment by sureshanaparti** [comment]
@DaanHoogland It seems MS couldn't find the host entry for secondary storage VM after expunging, and so it's returned as failed.

**Comment by sureshanaparti** [comment]
Fixed in #5908
