### ISSUE TITLE
Add Network :  Network Offering Drop down is not showing "Offering for Isolated networks with no Source Nat service "

### ISSUE THREAD

**Issue by jack99trade** [apache/cloudstack#5897]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
4.16

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
Centos7.9

##### SUMMARY
Not able to get list of Network Offerings (only Source-Nat service offering is displayed ) when I try to create Isolated Guest Network.
I am looking to create Guest isolated Network from "Isolated networks with no Source Nat service" offering.  (NOTE:  able to create the same using API)

##### STEPS TO REPRODUCE
Go-to:  Network > Guest Networks .  Add Network (Click)

![image](https://user-images.githubusercontent.com/98413115/151024228-b81b8a92-32f9-4016-9b5a-8af0187c7e20.png)

##### EXPECTED RESULTS

Add Network:  Network Offering Drop down shows "Offering for Isolated networks with no Source Nat service "

##### ACTUAL RESULTS

Add Network:  Network Offering Drop down is not showing "Offering for Isolated networks with no Source Nat service "

**Comment by weizhouapache** [comment]
@jack99trade @sureshanaparti 
This seems like a bug with UI. 
root admin and domain admin should be able to create networks without sourcenat , but normal users cannot (see #5844 )

**Comment by sureshanaparti** [comment]
agree @weizhouapache, if normal users can create isolated networks without source nat, then UI has to be updated to show the offerings without source nat (whatever the normal users are permitted).

**Comment by jack99trade** [comment]
> agree @weizhouapache, if normal users can create isolated networks without source nat, then UI has to be updated to show the network offerings without source nat (whatever the normal users are permitted).

@sureshanaparti  Yeap agree with you.  is it possible for me to enable this locally on my test setup? maybe change some files.  I'm not sure which file to change tho.

**Comment by sureshanaparti** [comment]
> > agree @weizhouapache, if normal users can create isolated networks without source nat, then UI has to be updated to show the network offerings without source nat (whatever the normal users are permitted).
> 
> @sureshanaparti Yeap agree with you. is it possible for me to enable this locally on my test setup? maybe change some files. I'm not sure which file to change tho.

May be, remove this line from code (then all offerings without source nat are shown) and access the UI.
https://github.com/apache/cloudstack/blob/982eef202ff98e484c4d562277371ca33e7661a2/ui/src/views/network/CreateIsolatedNetworkForm.vue#L347

**Comment by jack99trade** [comment]
> > > agree @weizhouapache, if normal users can create isolated networks without source nat, then UI has to be updated to show the network offerings without source nat (whatever the normal users are permitted).
> > 
> > 
> > @sureshanaparti Yeap agree with you. is it possible for me to enable this locally on my test setup? maybe change some files. I'm not sure which file to change tho.
> 
> May be, remove this line from code (then all offerings without source nat are shown) and access the UI.
> 
> https://github.com/apache/cloudstack/blob/982eef202ff98e484c4d562277371ca33e7661a2/ui/src/views/network/CreateIsolatedNetworkForm.vue#L347

@sureshanaparti thanks .. will try this

**Comment by sureshanaparti** [comment]
@jack99trade @utchoang As per the changes in PR #5844, normal users can only create isolated networks with source nat service, so UI should only show the network offerings with source nat for the normal users.

**Comment by jack99trade** [comment]
> @jack99trade @utchoang As per the changes in PR #5844, normal users can only create isolated networks with source nat service, so UI should only show the network offerings with source nat for the normal users. Admins should able to see network offerings without source nat as well.

@sureshanaparti  imho if admin has created a network offering and enabled it for users with irrespective of the services selected , should be enabled for user selection in dropdown while creating guest network,  it is not practical to make everyone Admin.

**Comment by sureshanaparti** [comment]
> > @jack99trade @utchoang As per the changes in PR #5844, normal users can only create isolated networks with source nat service, so UI should only show the network offerings with source nat for the normal users. Admins should able to see network offerings without source nat as well.
> 
> @sureshanaparti imho if admin has created a network offering and enabled it for users with irrespective of the services selected , should be enabled for user selection in dropdown while creating guest network, it is not practical to make everyone Admin.

Hi @jack99trade I'm not sure why it is not allowed for normal users. @weizhouapache Can you confirm the behavior and any reason why the isolated networks without source nat is not allowed for normal users?

**Comment by weizhouapache** [comment]
> @sureshanaparti imho if admin has created a network offering and enabled it for users with irrespective of the services selected , should be enabled for user selection in dropdown while creating guest network, it is not practical to make everyone Admin.

@sureshanaparti @jack99trade 
the changes were added more than 10 years ago , even before it was contributed to apache foundation.

https://github.com/apache/cloudstack/commit/7aab227b37ac47e0267894e42da4c4f3df48ddc9#diff-87cb51214e148f240e29cf09d67b62f57e7d897917a88b8ad84ef9988ca23a92R1807

as I understand it is why only isolated network with source nat can be created on UI (and also legacy UI)
to be honest, I have no idea they added the restriction. I do not see any problem.

@sureshanaparti can we remove the restriction ?

**Comment by sureshanaparti** [comment]
@weizhouapache May be, this has to be discussed with wider audience and take their opinions / feedback.

@GabrielBrascher @rohityadavcloud @DaanHoogland @svenvogel @nvazquez @NuxRo @andrijapanicsb and others, Please post you thoughts on this please. Thanks.

**Comment by DaanHoogland** [comment]
I don't see an issue, except maybe lack of functionality for a user. Why would a user want a network without sourcenat? what would they do in it? no access to internet from VMs they create in it...?
I have no issue with allowing it, you might want to have a network with only static nat maybe, but otherwise it would be completely useless.
@weizhouapache maybe the restriction was added before static nat was available?
..., bit of a strange situation.

**Comment by jack99trade** [comment]
> I don't see an issue, except maybe lack of functionality for a user. Why would a user want a network without sourcenat? what would they do in it? no access to internet from VMs they create in it...? I have no issue with allowing it, you might want to have a network with only static nat maybe, but otherwise it would be completely useless. @weizhouapache maybe the restriction was added before static nat was available? ..., bit of a strange situation.

hi @DaanHoogland ,   There are some scenarios where User just want IP connectivity between machines and all Machines default route is set to Internal Gateway(Firewall Instance with Public IP) and able to use Internet. These all machines are in Cluster and have multiple Nics  , if all use Source Nat based offering then lot of public ips and system vm routers are consumed.  if option is given to user to choose no-source nat based network the all this can be achieved with 1 public IP and and 1 system vm router.  Note: Currently users are able to create no-source Nat based network via API . they just don't get the option via GUI.

**Comment by sureshanaparti** [comment]
@jack99trade  As admins are allowed to create network without source nat, for now it would be good to fix the UI to show offerings without source nat for admin only. The users restriction for network without source nat can be addressed at later release (as a improvement if needed, based on the consensus).

**Comment by jack99trade** [comment]
> can

Hi @sureshanaparti  Since Users are already able to create Networks (With and Without Source Nat) using APIs.  Can we allow from GUI as well?  Or is there any Role which we can assign to User in RBAC, which shows them all offerings?

**Comment by jack99trade** [comment]
> @jack99trade As admins are allowed to create network without source nat, for now it would be good to fix the UI to show offerings without source nat for admin only. The users restriction for network without source nat can be addressed at later release (as a improvement if needed, based on the consensus).

Hi @sureshanaparti Since Users are already able to create Networks (With and Without Source Nat) using APIs. Would it be possible to enable the listing of all networks.  correct me if I am wrong , but if user is able to create the network using API , then if they see the offering listed then they should be able to create from GUI as well right away ?

**Comment by weizhouapache** [comment]
@jack99trade @sureshanaparti 

Discussed with Suresh, it should not be an issue to allow normal users to create isolated network without source nat.
I will test different account type and network type in 4.16.0.0 and make (java) code changes.

**Comment by sureshanaparti** [comment]
Fixed in #5904. @jack99trade If you still notice this issue after the fix, please reopen. Thanks.
