### ISSUE TITLE
Allow upload volume with custom size

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#5906]
User should able to specify custom size while uploading a volume.

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Volume
~~~

##### SUMMARY

Allow user to specify custom size while uploading, and resize the volume that is uploaded with the custom size (when the size specified is more than the uploaded volume size).

**Comment by DaanHoogland** [comment]
@sureshanaparti good feature, but do we scan for the current size first and set that as minimum? and how to hande the error situation?
anyway this is for 4.17, right?

**Comment by sureshanaparti** [comment]
> @sureshanaparti good feature, but do we scan for the current size first and set that as minimum? and how to hande the error situation?
> anyway this is for 4.17, right?

@DaanHoogland correct, the volume's current size would be the minimum size.

**Comment by nvazquez** [comment]
@sureshanaparti is there any work-in-progress PR for this issue?

**Comment by sureshanaparti** [comment]
> @sureshanaparti is there any work-in-progress PR for this issue?

no wip PR @nvazquez

**Comment by DaanHoogland** [comment]
closing as stale @sureshanaparti , please reopen or create a new when it becomes relevant again
