### ISSUE TITLE
Ajax-based VM console does not work on vmware 7

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#5919]
vmware 7 has been supported in cloudstack since 4.15.1.0 
The support was done by #4300 which contains a fix for novnc vm console issue for vmware 7

the old ajax-based vm console does not work.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM Console / CPVM
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### OS / ENVIRONMENT

vmware 7 as hypervisor

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@sureshanaparti @nvazquez 
just logged this issue here. Maybe it is not necessary to fix it.

**Comment by sureshanaparti** [comment]
> @sureshanaparti @nvazquez
> just logged this issue here. Maybe it is not necessary to fix it.

ok @weizhouapache

**Comment by nvazquez** [comment]
@borisstoyanov @vladimirpetrov I think we had a discussion about this when testing the VMware 7.0 support - should this be fixed?

**Comment by borisstoyanov** [comment]
@nvazquez @weizhouapache please help me understand, since some time we've moved to noVNC console and afaik the old console is not available any more, and it looks like VMware 7 is not working with the old console. If all of this I understood right, why should we be looking to fix this? Excuse me if I didn't get the issue you describe, but could you share reproductions steps if it's still requiring fix.

**Comment by weizhouapache** [comment]
> @nvazquez @weizhouapache please help me understand, since some time we've moved to noVNC console and afaik the old console is not available any more, and it looks like VMware 7 is not working with the old console. If all of this I understood right, why should we be looking to fix this? Excuse me if I didn't get the issue you describe, but could you share reproductions steps if it's still requiring fix.

@borisstoyanov 
Hi Bobby, novnc is default console, but old console is not removed yet 
You can try the following 2 steps
(1) update global setting 'novnc.console.default to 'false'
(2) open a vm console

it works on other hypersivors.

**Comment by vladimirpetrov** [comment]
I personally don't see a reason to support the old console anymore @nvazquez @weizhouapache.

**Comment by weizhouapache** [comment]
@vladimirpetrov @borisstoyanov @nvazquez 
since most of you think we do not need to support old console on vmware 7. let's close this issue.
