### ISSUE TITLE
UI: Filter menu UX improvements 

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#5926]
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### SUMMARY

- It would be a good enhancement to be able to resize the filter popup so one can see the full domain, zone or other resource names
- Another good improvement would be to display the list of resources alphabetically

![image](https://user-images.githubusercontent.com/10495417/152284900-9be1a37b-a363-45fc-ad81-1383a0b5347a.png)

**Comment by nvazquez** [comment]
Thanks @Pearl1594 - @davidjumani can you please work on this?

**Comment by utchoang** [comment]
@davidjumani I will solve this problem for you.
