### ISSUE TITLE
UI - Missing view Accounts button in domain view

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#5928]
##### ISSUE TYPE

 * Bug

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15.x
~~~

##### SUMMARY

View Accounts Button missing when selecting a domain. 
In the old UI there is an option to view accounts when you've selected a domain. In the New UI this option is missing.
This option is however visible when we traverse to the Domain view, from the Accounts list view.

In the domain View: No "view Accounts" button visible
![image](https://user-images.githubusercontent.com/10495417/152301598-ce801c2e-ae68-4ea9-8d0b-021f3442173c.png)

Traversing to the Domain, from the accounts list view , displays the button:
![image](https://user-images.githubusercontent.com/10495417/152301963-d7d97dc7-74c3-4ff2-a4a1-e1e119a11efe.png)

It would be a good improvement to have the view Accounts button visible on direct traversal to the Domain (Domain -> Specific Domain)

**Comment by sureshanaparti** [comment]
Fixed in #5929
