### ISSUE TITLE
UEFI/SECURE boot is not working with OVA templates

### ISSUE THREAD

**Issue by kricud** [apache/cloudstack#5932]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
ACS
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2.0
~~~

##### OS / ENVIRONMENT

ESXi 6.7 and Windows

##### STEPS TO REPRODUCE

**UEFI/SECURE works in general:**
Create new instance with UEFI/SECURE
![image](https://user-images.githubusercontent.com/30048481/152498235-7112ed7e-a24e-4f17-a917-300f85017a11.png)

Works us expected
![image](https://user-images.githubusercontent.com/30048481/152498260-a22f782d-f917-4929-a8a5-49ef75147de3.png)

**Problem with template prepared for UEFI/SECURE:**
Upload ova template that has been created to boot with UEFI/SECURE
![image](https://user-images.githubusercontent.com/30048481/152498321-1f12ff95-dc71-42b4-ace9-b9082cf25ff3.png)

Edit template settings to add support for UEFI/SECURE boot
![image](https://user-images.githubusercontent.com/30048481/152498374-18d6600f-4a57-496f-af6a-86af138f0bde.png)

Create instance from template
(Advanced settings are not used from template)
![image](https://user-images.githubusercontent.com/30048481/152498411-2be2c4c7-eee9-4ac2-b287-3bb63a840d0b.png)

Deployed instance contains settings for UEFI/SECURE
![image](https://user-images.githubusercontent.com/30048481/152498451-080d141c-1534-47f7-96fe-dea12ec8bd65.png)

Hypervisor settings are for BIOS – VM will not boot as its prepared for UEFI/SECURE boot.
![image](https://user-images.githubusercontent.com/30048481/152498488-053cbc55-9039-41dc-a0b1-f959a8f08441.png)

**Workaround is to “Read VM settings from OVA”**
With this approach end user cannot edit settings as they are controlled by OVA. I think that its correct behavior as “Read VM settings from OVA” where implemented for appliances that could contain some not standard things.
![image](https://user-images.githubusercontent.com/30048481/152498518-67ef14bd-e5fa-4ebf-8649-80ad9b8b256e.png)
![image](https://user-images.githubusercontent.com/30048481/152498521-f8953c05-fa84-4842-80e3-5c1bf6fa1cea.png)
![image](https://user-images.githubusercontent.com/30048481/152498530-037ee0bb-c89a-4b7f-8f34-d24770c2a8d8.png)

~~~

~~~

##### EXPECTED RESULTS

~~~
Instance created from template with UEFI/SECURE boots
~~~

##### ACTUAL RESULTS

~~~
Instance is not booting as its configured for BIOS/Legacy boot
~~~

**Comment by DaanHoogland** [comment]
@kricud this would be a regression as the initial UEFI support was not written with deploy as is in mind. Do you have no way to deploy the template at this time?

**Comment by kricud** [comment]
Workaround is to use “Read VM settings from OVA” it has its limitations in flexibility what can be initial configuration, important part is templet starts/boots and is not creating ticket in helpdesk.

**Comment by nvazquez** [comment]
Hi @kricud, from your images I see you have set BIOS on the VM deployment wizard, this would override the template settings. Have you tried deploying another VM from the same template but specifying UEFI on the VM deployment wizard as well?

**Comment by kricud** [comment]
Hi @nvazquez if I’m changing settings in Advanced Mode to UEFI/SECURE it works.
I have no way of telling to all my users that for this template you need to go and change settings in “Advanced Mode” to UEFI/SECURE from BIOS/LEGACY.

In process of creating Instance from template Advanced Mode settings are not impacted from template settings where UEFI/SECURE is defined.

**Comment by nvazquez** [comment]
Copy that, thanks @kricud. I agree it would be a good enhancement if the UI automatically detects the boot mode from the template settings

**Comment by nvazquez** [comment]
Hi @davidjumani can you please take a look at this issue? If the template has the UEFI setting then the VM deployment wizard should display it as the initial value of the advanced setting's boot type

**Comment by davidjumani** [comment]
Added the option to add UEFI as a details setting and infer it from the DeployVM form in https://github.com/apache/cloudstack/pull/5974
