### ISSUE TITLE
remove use of unsupported log4gv1

### ISSUE THREAD

**Issue by pjfanning** [apache/cloudstack#5941]
##### ISSUE TYPE

 * Improvement Request

https://github.com/apache/cloudstack/blob/main/pom.xml#L79

Log4jv1 has not been supported in many years and has multiple CVEs open against it. The ASF gets multiple daily queries/requests about log4j and most of them are expecting us to upgrade

* log4jv2 2.17.1 and above is one option
* reload4j is a fork of log4j that is maintained

**Comment by rohityadavcloud** [comment]
Thanks for the report, I've raised a PR to fix this issue. https://github.com/apache/cloudstack/pull/5878

**Comment by sureshanaparti** [comment]
Fixed in #5878
