### ISSUE TITLE
upgrade javascript dependencies with security issues

### ISSUE THREAD

**Issue by pjfanning** [apache/cloudstack#5950]
##### ISSUE TYPE

 * Bug Report

Have a look at the vulnerabilities in https://github.com/pjfanning/cloudstack/security/dependabot associated with package-lock.json

**Comment by rohityadavcloud** [comment]
That link gives a 404, maybe it's privately visible only @pjfanning ?

**Comment by pjfanning** [comment]
@rohityadavcloud these are the dependencies from that github page.

```
nanoid
Moderate severity


shelljs
High severity


follow-redirects
High severity


json-schema
Moderate severity


ansi-regex
Moderate severity


nth-check
Moderate severity


tmpl
Moderate severity


axios
High severity


ansi-html
High severity


path-parse
Moderate severity


tar
High severity


@npmcli/git
Moderate severity


normalize-url
High severity


color-string
Moderate severity


trim-newlines
High severity


glob-parent
High severity


ws
Moderate severity


dns-packet
High severity


browserslist
Moderate severity


postcss
Moderate severity


hosted-git-info
Moderate severity


ssri
High severity


url-parse
High severity


lodash
High severity


merge
High severity


is-svg
High severity


y18n
High severity


elliptic
Moderate severity


node-notifier
Moderate severity


ini
High severity


highlight.js
Moderate severity


object-path
High severity


node-forge
High severity


node-fetch
High severity


bl
High severity


yargs-parser
Moderate severity


dot-prop
High severity


prismjs
High severity

serialize-javascript
High severity
```

**Comment by pjfanning** [comment]
It's easy to get github to run dependabot analyses on your own github fork of apache/cloudstack - there is Security tab (between Wiki and Insights)

**Comment by davidjumani** [comment]
@pjfanning Let's check back on the dependencies when https://github.com/apache/cloudstack/pull/5151 is merged as it involves changing the vue library itself which could potentially fix some of the dependency vulnerabilities

**Comment by nvazquez** [comment]
PR #5151 got merged today - @davidjumani please advise if this issue is still valid after the vue upgrade

**Comment by pjfanning** [comment]
Thanks for working on #5151 - it does fix a lot of the dependabot highlighted issues. There are still a number of CVEs present though. One example is https://github.com/advisories/GHSA-hgjh-723h-mx2j

Would it be possible to use `npm audit fix` on the latest code to see if there any low-hanging fruit changes that can be made?

**Comment by davidjumani** [comment]
Can be fixed by https://github.com/apache/cloudstack/pull/6091

**Comment by nvazquez** [comment]
PR #6091 merged, @davidjumani can you please advise if there are more dependencies to update after the PR merged?

**Comment by pjfanning** [comment]
thanks for looking into this - dependabot is still recommending this - https://github.com/apache/cloudstack/blob/main/ui/package.json#L89 to update to 7.0.0 - due to https://github.com/advisories/GHSA-r8f7-9pfq-mjmv

**Comment by davidjumani** [comment]
@utchoang Can you please check if updating this will cause breaking changes? Thanks

**Comment by rohityadavcloud** [comment]
2cents - I think build dependencies can warning may be reviewed and ignored as the build depdencies aren't used to serve/run the webapp, we only use them to build a SPA (single page app) which is statically served by embedded Jetty. We don't use node-sass in prod.

**Comment by rohityadavcloud** [comment]
Addressed in https://github.com/apache/cloudstack/pull/6142 pl re-open if there's something we've missed. Thanks for the bug report @pjfanning
