### ISSUE TITLE
Missing "configuration Limits" option in multilevel domain scheme

### ISSUE THREAD

**Issue by luganofer** [apache/cloudstack#5973]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
At least in versions 4.15.2 and 4.16
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Given a multi-level domain scheme (a domain with one or more subdomains) from the new UI it is impossible to edit the configuration limits of the subdomains, using the admin domain user of the parent domain.
The same applies to the configuration limits on subdomain accounts.
From the old UI as well as from the APIs the configuration of limits on subdomains (using the domain admin user of the parent domain) works correctly.

##### STEPS TO REPRODUCE

~~~
1) Create a domain, an account for the domain created and a domain admin user for the account; all with the root admin user.

2) Login to the new UI using the domain and domain admin user created in the previous step.

3) Create a subdomain, an account for it and a user.

4) Attempt to modify the configuration limits on the subdomain created from the "Domains" menu and selecting the subdomain created in the previous step.

5) The "configuration limits" menu is not displayed to modify the quota of the subdomain resources.

~~~
![Screenshot_1](https://user-images.githubusercontent.com/17618230/153251276-4e1c8953-b5fb-4def-8557-fa9e46a21841.png)

##### EXPECTED RESULTS

~~~
The UI should show the "configuration limits" option in the created subdomain.
~~~

##### ACTUAL RESULTS

~~~
 The "configuration limits" option not displayed to modify the quota of the subdomain resources.
~~~

**Comment by nvazquez** [comment]
Hi @davidjumani can you please check this issue?

**Comment by nvazquez** [comment]
Thanks @davidjumani for the quick fix!
