### ISSUE TITLE
SG API Authorize Ingress/Egress Rule returns an empty response

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5979]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.0-Snapshot
~~~

##### CONFIGURATION

Advanced Zone with SG

##### OS / ENVIRONMENT

Ubuntu 21.10
4.16.1.0-Snapshot master

##### SUMMARY

Cloudstack server returns an empty response for both `authorizeSecurityGroupIngress` and `authorizeSecurityGroupEgress` methods. However, the job is done, rules are correctly added to desired SGs.

Details on those API methods are [here](https://cloudstack.apache.org/api/apidocs-4.16/apis/authorizeSecurityGroupIngress.html)

The issue with an empty response causes problems in upnstream APIs, since SG Rule ID is required.

I'm not sure how to reproduce this in Java, but I found this issue working with the Go API.
See screens attached in the next section

##### STEPS TO REPRODUCE

~~~
1. Setup an Adv Zone with SG enabled
2. Create an empty SG
3. Create an `authorizeSecurityGroupIngress` or `authorizeSecurityGroupEgress` API request
4. Use the following SG Rule settings:

Protocol = "tcp"
CidrList = {"10.1.2.2/30", "10.1.3.3/30"}
PortStart = 11111
PortEnd = 22222

5. Run API request
6. Notice that the rule was added, the code is `200`  but the response contains only the `JobID` field. All others are empty
~~~

##### EXPECTED RESULTS

~~~
The full response struct is returned as per spec here: https://cloudstack.apache.org/api/apidocs-4.16/apis/authorizeSecurityGroupIngress.html

The expected full struct is the following:

type AuthorizeSecurityGroupIngressResponse struct {
	Account           string `json:"account"`
	Cidr              string `json:"cidr"`
	Endport           int    `json:"endport"`
	Icmpcode          int    `json:"icmpcode"`
	Icmptype          int    `json:"icmptype"`
	JobID             string `json:"jobid"`
	Jobstatus         int    `json:"jobstatus"`
	Protocol          string `json:"protocol"`
	Ruleid            string `json:"ruleid"`
	Securitygroupname string `json:"securitygroupname"`
	Startport         int    `json:"startport"`
	Tags              []Tags `json:"tags"`
}
~~~

##### ACTUAL RESULTS

And the screenshot with an empty response from my debugger
![sg_resp](https://user-images.githubusercontent.com/45828526/153406502-4d2fb937-8862-4957-8363-3b67cd242561.png)

~~~
Resp is `200`, the job is done, but the resp structure contains only JobID
~~~

**Comment by sureshanaparti** [comment]
Hi @tetra12 The API requests _authorizeSecurityGroupIngress_ / _authorizeSecurityGroupEgress_ are async jobs, and would return jobid in the response. The job status/response can be requested using the API  _queryAsyncJobResult_ with that jobid as the parameter, which has the full response struct. I think, in case of Go API, it tracks for the job status in the background and sends the full response. Have you noticed API call _queryAsyncJobResult_ sent after the _authorizeSecurityGroupIngress_ / _authorizeSecurityGroupEgress_ API calls ?

**Comment by DaanHoogland** [comment]
I tested both in my local env and they do return an id when the job is done, please see @sureshanaparti's comment above, @tetra12 .

**Comment by nvazquez** [comment]
Closing this issue, please reopen if needed @tetra12
