### ISSUE TITLE
[KVM] Enable CloudStack to use multiple LOCAL storage pools

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#5987]
##### ISSUE TYPE

 * Improvement Request

Enable CloudStack to use multiple LOCAL storage pools that are (already configure and) available on KVM hosts.

At the moment, only the default /var/lib/libvirt/images/ storage pool is used - and if additional local storage pools are configured via virsh/libvirtd, those are NOT read by the ACS agent and can't be used (even manually adding those additional storage pools to DB, setting tags, and deploying a volume on those additional storage pools - does not work)

**Comment by weizhouapache** [comment]
this will be a nice feature !
