### ISSUE TITLE
Question - How to find out the active users on Cloudstack UI

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#5989]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
4.16
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

~~~
This is actually a question - not sure if there is a forum where I should paste it, but putting it on here for now. 

I have CloudStack 4.15 installed and various users connect via the portal or via the api. 
However, I do not know how to check how many users are currently on the portal. For example if I need to bring down the database for maintenance, (not clustered), I would like to know I am not stopping active users. I do send out messages for maintenance, but we need to do upgrade from old mysql 5 to 8.

How can I find out?

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by nvazquez** [comment]
Hi @nxsbi you can use the mailing lists for these questions as well. You can use the API to find out the active users or also query the database

From cmk:
````
list accounts state=enabled domainid=<DOMAINID>
list users state=enabled domainid=<DOMAINID>
````

Or DB query:
````
select * from account where state = 'enabled';
select * from user where state = 'enabled';
````

**Comment by nxsbi** [comment]
> Hi @nxsbi you can use the mailing lists for these questions as well. You can use the API to find out the active users or also query the database
> 
> From cmk:
> 
> ```
> list accounts state=enabled domainid=<DOMAINID>
> list users state=enabled domainid=<DOMAINID>
> ```
> 
> Or DB query:
> 
> ```
> select * from account where state = 'enabled';
> select * from user where state = 'enabled';
> ```
Thanks for the reply.  However this will just tell me at the system level how many users I have.

I want to know how many users are actively using the web UI (logged in or running api queries).

**Comment by nvazquez** [comment]
Sorry for the delay @nxsbi - I think there is no actual way to retrieve this information. However, you can query the events for user logins and their last login date to have an idea of the active users (however this approach may not be accurate):

````
select u.id as user_id, u.username, u.account_id, a.account_name, max(e.created) as last_login
from event e join user u on (e.user_id = u.id) join account a on (u.account_id = a.id)
where e.type = 'USER.LOGIN' GROUP BY e.user_id;
````

**Comment by DaanHoogland** [comment]
@nxsbi in #5588 there is an active connections output parameter added. Is this what you are looking for?

**Comment by nvazquez** [comment]
Closing for now - please reopen if needed @nxsbi
