### ISSUE TITLE
There is no secondary storage VM for secondary storage host SecondaryStorage

### ISSUE THREAD

**Issue by pam955** [apache/cloudstack#5991]
I have got "There is no secondary storage VM for secondary storage host SecondaryStorage" ERROR in cloudstack-management logs, 
and I cannot add the ISO images。

![image](https://user-images.githubusercontent.com/55932732/153820875-fc27cc54-d840-4ee1-866f-fbf21fdf7ac2.png)

I'm using cloudstack v4.16.0 version, by KVM as a hypvisior

**Comment by pam955** [comment]
please help me to fix it！

**Comment by Pearl1594** [comment]
@pam955 Based on the snippet of the logs shared, it seems that you don't have a secondary storage VM, i.e., in your console go to the systemVMs tabs under Infrastructure and there wouldn't be any systemvm listed. It seems that this is because you have no hypervisor host in a valid State. Please check the host state.

**Comment by pam955** [comment]
@Pearl1594
Thanks for your comment, I can see Vms  in "running" state in the  systemVMs tabs under Infrastructure。One vms showing "alter" , but I cannot see the details。
![Uploading systemvms.png…]()

**Comment by pam955** [comment]
![image](https://user-images.githubusercontent.com/55932732/153998707-6fb95c35-fe85-4965-9cb0-7b538b2a6355.png)

**Comment by Pearl1594** [comment]
@pam955 You can try destroying the SSVM and let it get re-created, or login to the SSVM (via console/ssh) and restart the cloud service (systemctl restart cloud). To identify why the SSVM has gone into alert state, you can check the logs in the Ssvm at `/var/log/cloud.log`

**Comment by pam955** [comment]
Thank you, the error is disapere after delete the Sys Vms 。
