### ISSUE TITLE
Failed to add host rhel 7

### ISSUE THREAD

**Issue by lijinlongpq** [apache/cloudstack#6004]
##### ISSUE TYPE
 Other

##### COMPONENT NAME

~~~
Zone
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION

Add zone with advanced networking

##### OS / ENVIRONMENT

Management Server: Ubuntu 20.04
Agent: Red Hat Enterprise Linux Server release 7.9

##### SUMMARY

Previously I had successfully setup cloudstack 4.15.0 with advanced networking in my lab. 

Now I try to setup in our office environment. Management server is a Ubuntu VM with version 4.15.2. Agent Server is a physical server with RHEL 7.9. 

But when I create the first zone, it's failed. Stopped at adding host. I have tried many days and many times. I have tried basic networking and advanced networking. All same. I will upload the logs. Please help, thanks

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by lijinlongpq** [comment]
[agent.log](https://github.com/apache/cloudstack/files/8091823/agent.log)
[management-server.log](https://github.com/apache/cloudstack/files/8091824/management-server.log)
![cloudstack-add-host-failed](https://user-images.githubusercontent.com/9441400/154561280-87be1e55-4485-47c5-936c-94b617dcc512.jpg)

**Comment by rohityadavcloud** [comment]
Hi @lijinlongpq I'm not sure what caused it, it appears the certficate import failed for some reason. We might need to look at those certificate and check if your CA certificate pair is correct in the first place, possible options are (a) re-deploy your env, esp drop current database and re-deploy your env, (b) if previous option is not possible then delete the entries from cloud.configuration table for name=ca.plugin.root.private.key and name=ca.plugin.root.public.key, then restart mgmt server and try again (ensure all other acs mgmt servers are stopped, and only started after the first is fully up with its UI/API accessible).

A workaround you can try (while we discuss the issue) is to set the auth strictness global setting to `false`, add the host, then go to Infrastructure -> hosts -> select host and click the button to provision certificate. Finally, set the auth global setting to `true` again.

**Comment by lijinlongpq** [comment]
> 

Thank you Rohit Yadav, I did re-deploy the env, a new VM. And yes, it's working now.
