### ISSUE TITLE
GSoC 2022 Idea: View Logs in the UI

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#6011]
## Background

As of now, when an admin encounters an issue or error in CloudStack, the maximum information they can immediately get is the API failure response which provides a reason for the failure. At times this might not be sufficinet to diagnose the error and would require the admin to investiage the CloudStack logs. This would require the admin or the sysadmin to log into the VM running CloudStack and either view or export the logs, and then dive into identifying the issue. This idea aims to eiliminate that step. 

The goal of this is to provide admins the ability to view the logs directly in the UI. This would make diagnosing failures and RCAs much quicker. 

## Requirement

Provide the ability display the logs in the UI

Add an API / WebSocket (and UI) support to :
- View the logs
- Live follow the logs (similar to 'tail -f')

This will require modifications in the :
- API Layer
- Service Layer

## Relevant Skills
- Java
- Vue.js (for UI) - minimal skills required

## Difficulty
Simple

## Duration
175 hours

## Potential Mentors
- David Jumani
- Any Developer from CS Community

## References
- https://github.com/shapeblue/hackerbook/
- https://cloudstack.apache.org/api/apidocs-4.16/

## Future Enhancements
- Colour code the logs for easier identification of log levels, etc

**Comment by Damans227** [comment]
Nice one!

**Comment by borisstoyanov** [comment]
@davidjumani good idea, can you please add more details to the idea. One conflict that could potentially appear is that not always Cloudstack root admins have access to logs or even ssh on the management server, so it could be a point of conflict. 

Can you also mark if this is a medium project 175hrrs or large one 350.

**Comment by davidjumani** [comment]
@borisstoyanov I agree that they might not have ssh access for obvious security reasons. But IMO, the admin (or at least root admin) has every right to view the logs since they do not disclose any information that the admin does not already know. This is no different than configuring the rsyslog to export the logs to a remote server

**Comment by sahilsaini110** [comment]
Hello, @borisstoyanov @davidjumani  I'm Sahil Saini. I'm an open-source enthusiast and an undergraduate student at IIT BHU. Cloud computing and networking are two topics I'm currently researching. I'm new to open source, but I'm looking forward to working with the cloud stack and exploring it further.

**I'd want to work on this issue and submit a proposal for the same. I have recently started exploring the cloud and cloud stack, therefore I'm looking forward for your help and valuable guidance.** 

I'm very inclined towards learning more about open source and cloud computing, and I believe, that cloud stack is the greatest place for me to start.

**Comment by borisstoyanov** [comment]
@sahilsaini110, you can reach me and David on the officual cloudstack slack.

**Comment by sahilsaini110** [comment]
@borisstoyanov Sorry for bothering you again, but I'm having difficulties finding/joining the cloudstack slack channel. Could you perhaps please send me a link or assist me with this?

**Comment by davidjumani** [comment]
Hi @sahilsaini110 Glad to see your interest! As Boris had mentioned, you can reach out to us on slack or send us an email, our email ids can be found on our GitHub profile

**Comment by davidjumani** [comment]
Hi @mehrdadmoradii Good to see your interest in opensource and this project. You can send me an email and we can discuss this further

**Comment by borisstoyanov** [comment]
@mehrdadmoradii @sahilsaini110 This week is the deadline to submit proposals into the GSoC platform, to secure your GSoC participation please submit the proposal by Fri.

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
