### ISSUE TITLE
Configure MTU size for KVM

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6014]
Introduce a new global setting that can be used to customize all MTU values the MTU interface (see libvirt XML - https://libvirt.org/formatnetwork.html#elementsConnect).

First of all we implemented a change for each single nic of a vm. We observed that this is not useful because Linux Bridges / OpenvSwitch with Libvirt always configures bridge network interface MTU
to use the lowest MTU of all ports (devices) on the bridge.

The only useful way to bypass this problem is to set the MTU to the same size for all VMs.

We introduced a global setting.
kvm.mtu.size Set the MTU for Libvirt and KVM (if not set the default MTU will be considered, Attention: If you use OVS the main bridge automatically is adjusted to the guest nic mtu)

if this is not set nothing will happen. after set a value it will be set for all virtual machines.

See https://github.com/apache/cloudstack/pull/3186

##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
KVM, VR
~~~

**Comment by shwstppr** [comment]
@rohityadavcloud @Pearl1594 will #6426 address this?

**Comment by rohityadavcloud** [comment]
This issue has been raised in response of closing an old PR https://github.com/apache/cloudstack/pull/3186 @DaanHoogland - logistics of the why/how of the implementation is not scope of this issue

**Comment by DaanHoogland** [comment]
ok, remark still stands

**Comment by rohityadavcloud** [comment]
Closing this, let's revisit this in future.
