### ISSUE TITLE
GSoC 2022: CloudStack Terraform Provider - Add datasources for the existing resources

### ISSUE THREAD

**Issue by harikrishna-patnala** [apache/cloudstack#6016]
## Background
Terraform is an Infrastructure as Code (IaC) software that provides a consistent CLI workflow to manage resources in
many cloud services. Cloudstack Terraform provider integrates with Cloudstack to aid in managing and automating the deployment of resources in cloudstack. We have recently made the first release of CloudStack Terraform Provider v0.4.0 https://github.com/apache/cloudstack-terraform-provider

## Requirement
Terraform defines a **datasource** as, "something that allows Terraform to use the information defined outside of Terraform, defined by another separate Terraform configuration, or modified by functions". Most resources offer data sources alongside their set of resource types. However, currently Cloudstack Terraform Provider only has one datasource for template. Hence, we propose an idea for students to get involved in enhancing the features of the Cloudstack Terraform Provider by adding support for datasources.

![image](https://user-images.githubusercontent.com/3348673/154947206-d110a18d-21cd-4f8b-981b-26970c1b2069.png)

If the students are enjoying the project, the scope can be extended to support adding further resources in Terraform such that the CloudStack Terraform Provider may become a de-facto tool for automating CloudStack deployments. 

The current set of resources Cloudstack terraform provider supports are:
https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs , where as its counterpart Ansible boasts of a more evolved list of resources - https://docs.ansible.com/ansible/latest/collections/ngine_io/cloudstack/index.html - mainly zones, clusters, accounts, domains, etc. It would be great if students interested want to go a step ahead and help add support for these too.

## Relevant Skills:
GoLang (basic)

## Difficulty:
Medium

## Potential Mentors:

Harikrishna Patnala
Pearl Dsilva

## Example and references
https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs : check **Resources** and **Data Sources** section under CloudStack Provider
Depends on CloudStack Go SDK - https://github.com/apache/cloudstack-go

**Comment by Damans227** [comment]
@harikrishna-patnala @Pearl1594 I am interested in submitting a proposal on this issue for GSOC2022. Taking a quick look at the `cloudstack-terraform-provider` repo, I can see there are 50 cloudstack resources available via terraform:

```
➜  cloudstack git:(main) ls -l | grep resource_cloudstack | wc -l
      50
```

As part of this project, how many data sources are we targeting from these 50 resources? And which ones should be done on a priority basis?  

cc: @borisstoyanov

**Comment by Pearl1594** [comment]
@Damans227 great to see that you are interested. In terms of the datasources, ideal practice is to have a datasource for the supported resources. However, on a priority basis, if we were to select datasources to be supported, we'd include:
```

1. volumes
2. instances
3. sshkeypair
4. zones
5. service offering
6. network offering
7. disk offering
```

If you are keen on further increasing support of resources - we can also look at adding the following resources:
```
user
account
domain
project
host
cluster
pod
zone
configuration
```

**Comment by Damans227** [comment]
> @Damans227 great to see that you are interested. In terms of the datasources, ideal practice is to have a datasource for the supported resources. However, on a priority basis, if we were to select datasources to be supported, we'd include:
> ```
> 
> 1. volumes
> 2. instances
> 3. sshkeypair
> 4. zones
> 5. service offering
> 6. network offering
> 7. disk offering
> ```
> 
> If you are keen on further increasing support of resources - we can also look at adding the following resources:
> ```
> user
> account
> domain
> project
> host
> cluster
> pod
> zone
> configuration
> ```

Ok, got it. I will start working on a draft of the design document for this issue. Thanks for your help. 

I will let you know if I have any further questions.

**Comment by borisstoyanov** [comment]
Hi @Damans227, great to see you have interest in this project as well. Please work with @harikrishna-patnala and possibly @Pearl1594 to file a submission 

@harikrishna-patnala I'd assume this could be a med or large project (175/350hrs), please work with the student and define the scope. We need to know what the size would be.

**Comment by Damans227** [comment]
> @Damans227 great to see that you are interested. In terms of the datasources, ideal practice is to have a datasource for the supported resources. However, on a priority basis, if we were to select datasources to be supported, we'd include:
> 
> ```
> 
> 1. volumes
> 2. instances
> 3. sshkeypair
> 4. zones
> 5. service offering
> 6. network offering
> 7. disk offering
> ```
> 
> If you are keen on further increasing support of resources - we can also look at adding the following resources:
> 
> ```
> user
> account
> domain
> project
> host
> cluster
> pod
> zone
> configuration
> ```

@Pearl1594 Hi! In the CloudStack API documentation, I see there are about 72 resources supported. Is this project going to include implementing data sources for all of them, or am I looking at the incorrect list of resources?

Maybe my perspective of looking at work involved in the project is broken, but I feel I could define a clear timeline for implementation if I know the exact number of resources to be worked on.

**Comment by Pearl1594** [comment]
@Damans227 you are right, the link you shared provides an entire list of resources and their associated APIs supported in CloudStack. However, for the scope of this project, we will focus on the list of resources already supported in Terraform - i.e., https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs (Resources Section) - and look at providing datasource support for those. As we move ahead in the project, if you wish to extended the project scope to provide support for additional essential resources we could add a tentative plan in the proposal for their support too - but that is subject to your interest. Some of the other resources that would be good to have include:
#### Users 
Account
Project
User
Domain

#### Infrastructure Components
Host
Cluster
Pod
Zone
Storage Pool (Primary Store) 
Image Store (secondary storage)

But as an initial step, we'll focus on just providing support for datasources for existing resources in Terraform provider.
Thanks!

**Comment by harikrishna-patnala** [comment]
Agree with @Pearl1594 let's first start with adding datasources for existing resources and then we can extend if we get time

**Comment by Pearl1594** [comment]
@Damans227 please note that Terraform depends on the CloudStack go SDK to interact with CloudStack. While most API support may be there, there could be a case where the go SDK may need to be extended to support certain operations.

**Comment by Damans227** [comment]
> @Damans227 you are right, the link you shared provides an entire list of resources and their associated APIs supported in CloudStack. However, for the scope of this project, we will focus on the list of resources already supported in Terraform - i.e., https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs (Resources Section) - and look at providing datasource support for those. As we move ahead in the project, if you wish to extended the project scope to provide support for additional essential resources we could add a tentative plan in the proposal for their support too - but that is subject to your interest. Some of the other resources that would be good to have include:
> #### Users 
> Account
> Project
> User
> Domain
> 
> #### Infrastructure Components
> Host
> Cluster
> Pod
> Zone
> Storage Pool (Primary Store) 
> Image Store (secondary storage)
> 
> But as an initial step, we'll focus on just providing support for datasources for existing resources in Terraform provider.
> Thanks!

Understood, and thanks for the explanation. This is very helpful. 

Please excuse my lack of familiarity with using CloudStack via Terraform 🙏

**Comment by Pearl1594** [comment]
That's perfectly fine @Damans227 , do reach out for any queries.

**Comment by Damans227** [comment]
Hi @Pearl1594 @harikrishna-patnala @borisstoyanov 

I have prepared an unofficial draft of the design document for my GSoC proposal. Ptal and provide any feedback or criticism of my approach to solve the problem. 

https://docs.google.com/document/d/1FYdYzcN8fFTDfq1NIhbTLU4DeJhc2HpU/edit?usp=sharing&ouid=109681619309347919886&rtpof=true&sd=true

Fyi, I have the document unlocked for adding the comments. Looking forward to hearing from you.

**Comment by harikrishna-patnala** [comment]
Thanks, @Damans227 for the draft, to me it looks constructive and the right approach. Let's hear from @Pearl1594 too.

**Comment by Damans227** [comment]
> Thanks, @Damans227 for the draft, to me it looks constructive and the right approach. Let's hear from @Pearl1594 too.

Sounds good, thanks!

**Comment by Pearl1594** [comment]
@Damans227 Brilliant work on the draft proposal! I've added a small comment which pertains to maybe considering adding tests for the datasources/resource. Thanks & great work!

**Comment by Damans227** [comment]
> @Damans227 Brilliant work on the draft proposal! I've added a small comment which pertains to maybe considering adding tests for the datasources/resource. Thanks & great work!

Thanks for all your feedback and answering the question in the draft. I've just read your comment and will incorporate the suggestions very shortly. I will keep you posted.

**Comment by Damans227** [comment]
Hi @Pearl1594 @harikrishna-patnala I have revised the draft of my design document based on the feedback I've received earlier, and it now looks pretty close to what I am planning to submit as an actual proposal for this project. Ptal when you get a chance, and share your feedback: 

https://docs.google.com/document/d/1FYdYzcN8fFTDfq1NIhbTLU4DeJhc2HpU/edit

I highly appreciate your guidance on this matter and look forward to hearing from you. 

Thanks!

**Comment by Pearl1594** [comment]
Hi @Damans227 I reviewed the proposal - really well written! Just added a small comment on adding some buffer time in the proposed timeline. All in all, a great job! Thanks!

**Comment by Damans227** [comment]
> Hi @Damans227 I reviewed the proposal - really well written! Just added a small comment on adding some buffer time in the proposed timeline. All in all, a great job! Thanks!

Just saw your comment. It's very insightful, and I completely agree with it. I think adding those items which you have suggested will make the draft comprehensive and even more clear. So, I will work on them and let you know when the draft is updated. 

Thanks for all your great feedback so far! 👍🏽

**Comment by Damans227** [comment]
Hi @Pearl1594 I have added implementation details for creating a new resource using CloudStack`Zone` as an example. It's titled as, _"Sample implementation steps to create a cloudtsack_zone resource"._ Also, I added a note in the `Proposal Timeline` section highlighting that some effort may go into optimizing existing resources in go-sdk. Ptal, and lemme know your feedback:

https://docs.google.com/document/d/1FYdYzcN8fFTDfq1NIhbTLU4DeJhc2HpU/edit?usp=sharing&ouid=109681619309347919886&rtpof=true&sd=true

As always, I appreciate all your feedback and help. Thanks!

**Comment by Pearl1594** [comment]
Looks good @Damans227 great work!

**Comment by Damans227** [comment]
> Looks good @Damans227 great work!

Many thanks for all your feedback and suggestions. Appreciate it!

**Comment by Damans227** [comment]
Hi @borisstoyanov My proposal for this project is complete and ready to go. 
Do we accept early submissions or should I wait until the contributor applications have officially begun, i.e., April 4th? (Just asking for the sake of being well informed, otherwise I am in no rush).

**Comment by Damans227** [comment]
Another question, I don't see this issue (and many other cloudstack issues) listed under the GSoC2022 ideas list published by [Apache](https://summerofcode.withgoogle.com/programs/2022/organizations/apache-software-foundation) on the GSoC website: 

https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2022+Ideas+list#GSoC2021Ideaslist-CloudStack

Can we still pursue this idea for GSoC2022 ?

**Comment by Pearl1594** [comment]
@Damans227 the list (https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2022+Ideas+list#GSoC2021Ideaslist-CloudStack) is yet to be updated.

**Comment by Damans227** [comment]
> @Damans227 the list (https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2022+Ideas+list#GSoC2021Ideaslist-CloudStack) is yet to be updated. 

Got it! Thanks for letting me know.

**Comment by Damans227** [comment]
@Pearl1594 @harikrishna-patnala @borisstoyanov Hi, I hope everyone doing well. I have successfully submitted my proposal for this project. PTAL, when you get a chance. Thanks!

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
