### ISSUE TITLE
GSoC 2022 Idea: Add the ability to Safely Shutdown / restart CloudStack

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#6021]
## Background

Shutting down / Restarting Cloudstack is a necessary step in upgrades, system maintenance, etc. As of now, there is no way to safely shutdown or restart CloudStack. It is directly terminated via systemd. Since this is the case, any asyncronous job or background task is abrubptly terminated and can fail. As of now, CloudStack maintains a list of asynchronous jobs wihtin it's database along with their status. 

This idea aims to provide a way to safely shutdown CloudStack. It involves two parts :
- Prevent new asynchronous jobs from being added to CloudStack when a safe shutdown is triggered
- Check the status of the async jobs and Shut down CloudStack when all the jobs have been completed

## Requirement

Provide the ability to safely shutdown CloudStack

Add API (and/or UI) support to :
- Trigger a safe shutdown
- (Optional) Support restarts
- (Optional) Support a forced shutdown when CloudStack will quit even if there are async jobs running

This will require modifications in the :
- API Layer
- Service Layer
- Minor DB changes if required

## Relevant Skills
- Java
- MySQL - Minimal / Basic knowledge
- Vue.js (for UI) - minimal skills required
- Some knowledge of CloudStack and its Job framework - Good to have

## Difficulty
Medium

## Duration
- Some Experience : 175 hours
- Newbie : 350 hours

## Potential Mentors
- David Jumani
- Any Developer from CS Community

## References
- https://github.com/shapeblue/hackerbook/
- https://cloudstack.apache.org/api/apidocs-4.16/

## Future Extensions
- Support restarts
- Support a forced shutdown when CloudStack will quit even if there are async jobs running

**Comment by Yashikaone** [comment]
Hello @davidjumani 
I'm Yashika Sarkar, an undergraduate student and I would like to work on building a solution to this issue therefore I want to put forth a proposal for this particular issue.
I am new to open source and I am particularly interested in contributing to this organisation for two major reasons, it'd be a great way to learn more about cloud computing and I have had more exposure to Java.
I am interested in learning more about cloud computing and I have tried to acquaint myself with the codebase of ACS.
So far,I have made a single contribution in this project.
I'm looking forward to your help and much needed guidance on discovering the credible path into the world of open source.
Thank you.

**Comment by borisstoyanov** [comment]
Hi @davidjumani, great idea! I think it'll contribute to smoother upgrades and maintenance of ACS environments. Can you please indicate if this is large (350hrs) or medium(175 - like last year) project. 

Hi @Yashikaone, great that you have interest! I'll be helping out with coordination of the GSoC projects this year, so if you have any questions reach out.
I think the window for proposal submissions is still not open yet, but there's nothing wrong to reach out express interest and work with the mentor, as you did. Please work with David to prepare a proposal and we'll take it further later on.

**Comment by Yashikaone** [comment]
Thank you for the information @borisstoyanov I'll reach out to you if I have any question.

**Comment by davidjumani** [comment]
@Yashikaone Great to see your interest! As Boris has mentioned, the window for submitting proposals is not yet open. However, you can reach out to us if you'd like to get a deeper understanding of CloudStack, the idea or work on a draft proposal until the window opens

**Comment by Yashikaone** [comment]
Thank you for the reply @davidjumani

**Comment by Yashikaone** [comment]
How do I reach out to you directly @davidjumani and @borisstoyanov ?

**Comment by davidjumani** [comment]
@Yashikaone You can send us an email, our email ids can be found on our GitHub profile

**Comment by Yashikaone** [comment]
Thank you @davidjumani

**Comment by borisstoyanov** [comment]
Hi @Yashikaone, 

This week is the last chance to submit you proposal for this idea, please take some time and do so if you want to secure your GSoC participation.

**Comment by Yashikaone** [comment]
Hello borisstoyanov 
Please excuse my late reply I was busy with my ongoing exams.
I'd like to inform you I have submitted the proposal 
Thank you for the reminder

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
