### ISSUE TITLE
KVM - Volumes are not disconnected from the host while migrate or stop a VM

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#6026]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM hypervisor
~~~

##### CLOUDSTACK VERSION

~~~
4.16 and newer
~~~

##### SUMMARY

When you migrate a Virtual machine to another host the volumes are still connected to the old one. Also, the situation is the same when you stop a virtual machine, the volumes are not disconnected.

Affected Storage drivers are - SolidFire, Linstor, StorPool and those using `IscsiAdmStorageAdaptor`

##### STEPS TO REPRODUCE

~~~
Stop a Virtual Machine - the attached volumes has to be disconnected from the host
Migrate a Virtual machine - the attached volumes has to be disconnected from the old host
~~~

##### EXPECTED RESULTS

~~~
all volumes have to be disconnected when you stop a VM or disconnected from the old host while migrating
~~~

##### ACTUAL RESULTS

~~~
The volumes are still connected on the host
~~~

**Comment by sureshanaparti** [comment]
Fixed in #6029
