### ISSUE TITLE
GSoC 2022 Idea: Report / Manage the VM jobs in CloudStack.

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#6030]
## Background

CloudStack allows users/operators to perform various operations on the Virtual Machines (VMs). When multiple operations are performed on a VM at the same time, these operations are maintained and sync-ed using the sync queues. Any long running job (eg. volume snapshot) of a VM keeps other jobs in waiting/pending state, and only be picked once the active job is finished. Currently, it is not possible for an operator to list the pending jobs on a VM, cancel or re-prioritise any job if needed.

## Requirement
Provision to admin/operator, to the list the pending jobs of a VM, cancel or re-prioritise a job if needed. Also, allow to clear all the pending jobs of a VM.

Add API (and/or UI) support to
- List the active jobs for a VM
- List all the pending jobs of a VM (in queue, by their order of execution)
- Re-prioritise a job from the pending jobs (if possible)
- Cancel any job from the pending jobs
- Clear all the pending jobs of a VM

## Relevant Skills
- Java, MySQL
- Vue.js (for UI)
- Some knowledge of CloudStack and its Job framework

## Difficulty
Medium

## Potential Mentors
- Suresh Kumar Anaparti
- Any Developer from CS Community

## Project Scope/Duration
Large / 350hrs (can be Medium / 175 hours - with reduced scope of API/UI work)

## References
- http://docs.cloudstack.apache.org/en/latest/adminguide/index.html#working-with-virtual-machines
- https://cwiki.apache.org/confluence/display/CLOUDSTACK/FS+-+VMSync+improvement
- https://cwiki.apache.org/confluence/display/CLOUDSTACK/Snapshot+throttling+FS
- https://cloudstack.apache.org/api/apidocs-4.16/
####  Jira Ticket
- https://issues.apache.org/jira/browse/CLOUDSTACK-10452

## Future Extensions
This can be extended for other resources (hosts, primary storage, network, etc).
[APIs should take resource type as a param for generic implementation]

**Comment by borisstoyanov** [comment]
Hi @sureshanaparti, thank you for submitting this idea, I like it. 

Please indicate if this is large (350hrs) or medium(175 - like last year) project.

**Comment by sureshanaparti** [comment]
Hi @damanBirSingh Thanks for your interest in this idea. You can reach out to us, for any guidance on CloudStack, the idea or the draft proposal.

**Comment by sureshanaparti** [comment]
> Hello Everyone,
> 
> I am Daman Bir Singh, an gradute student and I would like to put forth a proposal for this particular issue and work on building a solution. I have started going through the cloudstack hackerbook repo to get more idea about cloudstack project.
> 
> I am new to open source but have some experince working with java and am very interested to contributing more in open source projects. Looking forward to your help and much needed guidance to make meaningful contributions to the project.
> 
> Thanks & Regards Daman

@damanBirSingh Are you working/planning to submit a proposal for this idea? Let me know if you have any questions or need guidance. Please note, that the Proposal Deadline is 19-Apr-2022 (GSoC 2022 Timelines: https://summerofcode.withgoogle.com/programs/2022). Thanks.

**Comment by borisstoyanov** [comment]
@damanBirSingh I'd like to remind you that this week is the last chance to submit your proposal, please take the advantage to do so if you want to secure your GSoC2022 participation.

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
