### ISSUE TITLE
GSoC 2022 Idea: Keep track of VM's "last known state" and enforce it after an outage 

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#6033]
Hello,

An infrastructure outage can take out several or all VMs. In the aftermath it's not always possible to know which VMs were supposed to be ON or OFF, especially if HA is not enabled. People keep powered off VMs around all the time for many reasons.

I propose we add a feature where Cloudstack keeps track of the "last known state" of a VM and after an outage either enforce it (ie start the VM or leave it off) or at least show some information to the operator in the UI/API so they can do it themselves; perhaps make this behaviour configurable in the global settings.

Thanks

**Comment by borisstoyanov** [comment]
@NuxRo thanks, great idea. I know some hypervisors like VMware are syncing this state, so I'd assume this would be relevant to others? Can you elaborate a bit on the idea. Can you also put a size on the project medium 175hrs or large 350hrs, you might want to have a developer to do an assessment of the changes required to come up with this part. Also add in the perspective of space, storage, systemvms/router, hypervisors, user roles, networks etc.. to the idea.

**Comment by NuxRo** [comment]
2-3 months should be more than enough for this feature, @borisstoyanov

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
