### ISSUE TITLE
SSVM scaling issue

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#6038]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
SSVM
~~~

##### CLOUDSTACK VERSION

~~~
4.15.x
~~~

##### SUMMARY

When active cmds i.e., no of entries in cmd_exec_log table is 0 and the SSVM standby capacity - `secstorage.capacity.standby` is higher than the max sessions an SSVM can handle `secstorage.session.max`, then the no of SSVMs get scaled up. However, when there aren't any active commands, a logic is added to scale down the SSVMs. 

##### STEPS TO REPRODUCE

~~~
1. Set `secstorage.session.max` to 5
2. Set `secstorage.capacity.standby` to 10
3. Notice after 30s a new SSVM spawns up and in the next iteration it is cleaned up
~~~

##### EXPECTED RESULTS

~~~
number of SSVMs created should remain intact unless deleted
~~~

##### ACTUAL RESULTS

~~~
SSVMs scaled down based on no of active commands i.e., load
~~~

**Comment by sureshanaparti** [comment]
Fixed in #6042
