### ISSUE TITLE
GSoC 2022 Idea: More granularity on affinity/anti-affinity groups

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#6039]
Currently, defining an affinity or anti-affinity rule works only at hosts level. I would like to have more detail on the affinity group, extending it at different levels (cluster, pod, zone,..) and also within the same level, being able to add or remove resources from the group.

For hosts and storage pools, administrators can make use of host tags or storage tags to get a similar result. However, the extension of affinity/anti-affinity groups would make the administration easier.

Size of the project: Medium (~175hs)

**Comment by borisstoyanov** [comment]
@nvazquez thanks for the idea, can you indicate if it's either large or medium size project (175/350hrs)

**Comment by nvazquez** [comment]
Sorry forgot to reply @borisstoyanov - it is updated on the PR description: Size of the project: Medium (~175hs)

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
