### ISSUE TITLE
GSoC 2022 Idea: Instant Instance Deploy (using VM Definitions)

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#6043]
## Background

Currently, Deploy Instances/Virtual Machines(VMs) in Cloudstack requires to specify some offerings, template and other settings through the API (check the API here: https://cloudstack.apache.org/api/apidocs-4.16/apis/deployVirtualMachine.html) or the 'Instance Deployment Wizard' in the UI.

## Requirement
Provision to user/operator to quick deploy an instance using a VM definition/profile. The VM definition/profile would hold the details of the template, offerings (including any custom values - size, iops), ssh keypair, instance group, affinity group and other settings (boot type, dynamic scaling, userdata, keyboard language, etc) that are required, and the underlying definition/profile id can be used to launch an instance. At the minimum, the definition should hold all the mandatory details for deploying an instance. With this, only the VM definitions/profiles (and other important options, with the associated billing details) can be exposed to the users for VM deployment, instead of the offerings and other VM options.

Need to add new APIs (and/or UI) support for the VM definition/profile CRUD operations, and support for definition in the deployVirtualMachine API.

## Relevant Skills
- Java, MySQL
- Vue.js (for UI)
- Some knowledge of Virtualization and CloudStack

## Difficulty
Medium

## Potential Mentors
- Suresh Kumar Anaparti
- David Jumani

## Project Scope/Duration
Medium / 175 hours

## References
- http://docs.cloudstack.apache.org/en/latest/adminguide/index.html#working-with-virtual-machines
- https://cloudstack.apache.org/api/apidocs-4.16/apis/deployVirtualMachine.html
- https://cloudstack.apache.org/api/apidocs-4.16/
####  Jira Ticket
- https://issues.apache.org/jira/browse/CLOUDSTACK-10451

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.

**Comment by rohityadavcloud** [comment]
Additiona note - we now have user-data as a first class feature which can be used for this.
