### ISSUE TITLE
GSoC 2022 Idea: Edge Zones

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#6044]
## Background
Over recent years, Edge computing has been gaining popularity as it defines a model that brings compute and storage closer to
where they are consumed by the end-user. By being closer to the end-user a better experience can be provided with reduction on overall latency, lower bandwidth requirements, lower TCO, more flexible hardware/software model, while also ensuring security and reliability. To align ACS with this evolving cloud computing model we would like to propose an idea of supporting Edge Zones in CloudStack, which
can be also looked upon as a lightweight zone, with minimal resources.

## Requirement
Today, when a Zone is setup in CloudStack, it by default comes up with a secondary storage VM(SSVM) and a console proxy VM(CPVM). As part of this project, we would need to define a new zone type to decide the change in workflow required to ensure that a CPVM & SSVM isn't spawned up by default. Basic characteristics of an Edge zone include:
- no need for Secondary Storage
- no Secondary Storage VM
- no Console Proxy VM
- Local storage only as typically an edge device comprises of a single compute node (host)
- And supports L2 and Isolated networks.

A high-level view of an edge zone would look something like:
![Edge-zone-example](https://user-images.githubusercontent.com/10495417/155530992-8bdeee61-498b-4525-9a8f-93bb2b9548bb.png)

## Relevant Skills:
Java
MySQL
Vue.js (Basic)

## Difficulty
Medium

## Project Duration:
175 hours

## Potential Mentors
Alex Mattioli
Nicolas Vazquez
Pearl Dsilva

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
