### ISSUE TITLE
GSoC 2022 Idea: Autodetect IPs used inside the VM

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#6047]
With regards to IP info reporting, Cloudstack relies entirely on it's DHCP data bases and so on. When this is not available (L2 networks etc) no IP information is shown for a given VM.

I propose we introduce a mechanism for "IP autodetection" and try to discover the IPs used inside the machines by means of querying the hypervisors. For example with KVM/libvirt we can simply do something like this:

```
root@fedora35 ~]# virsh domifaddr win2k22 --source agent
 Name       MAC address          Protocol     Address
-------------------------------------------------------------------------------
 Ethernet   52:54:00:7b:23:6a    ipv4         192.168.0.68/24
 Loopback Pseudo-Interface 1                      ipv6         ::1/128
 -          -                    ipv4         127.0.0.1/8
```

The above command queries the qemu-guest-agent inside the Windows VM. The VM needs to have the qemu-guest-agent installed and running as well as the virtio serial drivers (easily done in this case with [virtio-win-guest-tools.exe](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.215-2/virtio-win-guest-tools.exe) ) as well as a guest-agent socket channel defined in libvirt.

Once we have this information we could display it in the UI/API as "Autodetected VM IPs" or something like that.

I imagine it's very similar for VMWare and XCP-ng.

Thank you

**Comment by NuxRo** [comment]
In terms of time, 2-3 months should be more than enough to develop this feature.

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
