### ISSUE TITLE
UX is deeply untested for normal user account

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6067]
We don't test the UI as normal user account, but as a root admin by default. This has manifested as tech debt or bugs over time. While there might not be any functional bugs in many cases, it leads to poor UX if the UI isn't tested/optimised for normal user accounts.

Steps to reproduce:
- Create and log in as a normal user account
- Deploy resources such as VM, volumes, networks, templates etc.
- Go through a VM deployment, setup fw/pf/network rules, add data disks etc.
- Add the same resources in a user project
- Now navigate through the project and see router-links lead to invalid views
- for example, execute a full test plan wrt https://github.com/apache/cloudstack-primate/blob/master/.github/ISSUE_TEMPLATE/test_full_plan.md

Common issues:
- Router links don't check if the user can actually go to a specific route (for ex. zone, offering etc.)
- Certain actions assume admin roles, this needs a thorough checking
- Dashboard isn't showing all information necessary (as seen in project resources or account resources)

##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

**Comment by nvazquez** [comment]
Partly covered by the manual testing performed on PR #5151, in progress
