### ISSUE TITLE
Adding cloudstack repository fails under Rocky Linux 8.5

### ISSUE THREAD

**Issue by ukedk** [apache/cloudstack#6073]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Centos 8 Repo

##### CLOUDSTACK VERSION

4.16

##### OS / ENVIRONMENT

Rocky Linux 8.5

##### SUMMARY

Following the documentation to add the cloudstack-epo fails:

Failed to download metadata for repo 'cloudstack': Checksum mismatch /var/cache/dnf/cloudstack-972dd32202bee359/repodata/e9d29c06626056b2e09e7712d6477873a470cf1abb59646e90805b2a3bc64a67-filelists.xml.gz

##### STEPS TO REPRODUCE

dnf update

~~~

~~~

##### EXPECTED RESULTS

adding repo  

[cloudstack]
name=cloudstack
baseurl=http://download.cloudstack.org/centos/$releasever/4.16/
enabled=1
gpgcheck=0

should work

##### ACTUAL RESULTS

Failed to download metadata for repo 'cloudstack': Checksum mismatch /var/cache/dnf/cloudstack-972dd32202bee359/repodata/e9d29c06626056b2e09e7712d6477873a470cf1abb59646e90805b2a3bc64a67-filelists.xml.gz

**Comment by davidjumani** [comment]
@ukedk Thanks for reporting the issue. The repodata was out of sync and it's been fixed
Can you try clearing the cache and trying again ?

**Comment by nvazquez** [comment]
Closing the issue as per @davidjumani's comment - if the issue persists please reopen it @ukedk
