### ISSUE TITLE
GSoC Idea 2022 - Bypass Secondary Storage (Direct Download) on VMware &/or XenServer

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#6082]
## Background
The default way of registering / downloading templates in CloudStack involves caching them on the secondary store and then during VM deployment, the template is copied to the primary store. However, from ACS version 4.11.1 onward, a feature was added for KVM hypervisor to enable direct download to primary store. This massively reduces the usage of secondary store and also quickens the entire VM deployment process, as there is no need to copy the template from secondary to primary store. 

## Requirement
We would like to propose an idea to extend this feature of direct download of templates onto primary store for other hypervisors - namely, VMware and XenServer. This would gravely benefit end-users to efficiently use the secondary storage and save overall time of VM deployment on the respective hypervisors

## Relevant Skills:
Java
MySQL
Vue.js

## Difficulty:
175 hours (Only VMware)
350 hours (VMware & XenServer)

## Potential Mentors:
Abhishek Kumar (@shwstppr )
Pearl Dsilva (@Pearl1594 )

## References
https://www.shapeblue.com/how-to-deploy-templates-without-using-secondary-storage-on-kvm/
https://www.shapeblue.com/cloudstack-feature-first-look-direct-download-agnostic-of-the-storage-provider/
https://cwiki.apache.org/confluence/display/CLOUDSTACK/Bypass+Secondary+Storage+%28Direct+Download%29+on+KVM
https://www.youtube.com/watch?v=SwepUTfGiKc

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
