### ISSUE TITLE
UEFI hosts capability not detected after upgrade

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#6087]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
INFRA
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### SUMMARY

If a host is added before 4.14 (where boot-into-bios feature was introduced) it seems that the capability of the host is not added after upgead. Cloudstack should be able to determine this via different strategies for different hypervisors. 

~~~
host.uefi.enable is missing from cloud.host_details table
~~~

**Comment by davidjumani** [comment]
Created a fix in #6139
