### ISSUE TITLE
UI: Add zone wizard missing provider for primary storage

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#6088]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.16, main
~~~

##### SUMMARY
When adding a primary storage through the Add zone wizard, the different storage providers are not displayed. This ends up on a non-successful zone creation which needs manual addition of the storage pools for different providers

![image](https://user-images.githubusercontent.com/5295080/157691647-4049165a-e1d6-4de8-ab18-95e9b64691fd.png)

##### STEPS TO REPRODUCE
~~~
Add zone
Complete the steps until Primary storage
Try registering for example NFS storage pool for a provider such as PowerFlex, SolidFire, etc
~~~

##### EXPECTED RESULTS
~~~
Add zone succeeds
~~~

##### ACTUAL RESULTS
~~~
Add zone fails, needs manual registration of storage pools
~~~

**Comment by rohityadavcloud** [comment]
@nvazquez would this be useful for 4.17.1.0 cc @utchoang @shwstppr ?
