### ISSUE TITLE
Smoke test failed on ubuntu 20.04

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6114]
see https://github.com/apache/cloudstack/pull/6031#issuecomment-1061431788

<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="box-sizing: border-box; font-weight: 600;">Trillian test result (tid-3520)</b><br style="box-sizing: border-box;">Environment: kvm-ubuntu20 (x2), Advanced Networking with Mgmt server u20<br style="box-sizing: border-box;">Total time taken: 36070 seconds<br style="box-sizing: border-box;">Marvin logs:<span> </span><a href="https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr6031-t3520-kvm-ubuntu20.zip" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr6031-t3520-kvm-ubuntu20.zip</a><br style="box-sizing: border-box;">Smoke tests completed. 91 look OK, 1 have errors<br style="box-sizing: border-box;">Only failed tests results shown below:</p>

Test | Result | Time (s) | Test File
-- | -- | -- | --
test_01_migrate_VM_and_root_volume | Error | 70.02 | test_vm_life_cycle.py
test_02_migrate_VM_with_two_data_disks | Error | 49.82 | test_vm_life_cycle.py

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by nvazquez** [comment]
Fixed on #6116
