### ISSUE TITLE
travis tests failed in 4.16/main

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6115]
as followup of #6113 

3 tests failed in travis tests, see https://github.com/apache/cloudstack/pull/6113/checks?check_run_id=5536689365

26430.5	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	passed
[ 26430.6](https://app.travis-ci.com/github/apache/cloudstack/jobs/563196176)	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	errored
[ 26430.7](https://app.travis-ci.com/github/apache/cloudstack/jobs/563196177)	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	passed
[ 26430.8](https://app.travis-ci.com/github/apache/cloudstack/jobs/563196178)	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	errored
[ 26430.9](https://app.travis-ci.com/github/apache/cloudstack/jobs/563196179)	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	errored
[ 26430.10](https://app.travis-ci.com/github/apache/cloudstack/jobs/563196180)	openjdk11	PATH=$HOME/.local/bin:$PATH	Linux	passed

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by Pearl1594** [comment]
I see the following 2 tests failing on quite a few PRs  on main - I'll have a look at them - 
- component/test_project_limits: test_04_publicip_per_project | Status : FAILED ===
- component/test_resource_limits:  test_01_publicip_per_domain | Status : FAILED ===
