### ISSUE TITLE
Router health check notification mail shows UUID of router, unable to locate via UI

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#6129]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1
~~~

##### SUMMARY

Router health check message sent via email show the UUID of the router VM, however, there are no way to filter router instance using UUID via UI.

Example
```
Health checks failed: 1 failing checks on router 89c5d650-4781-4a8e-9331-6b972815ba93

```
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
router name should be shown in the mail body or make UUID search available in UI.
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
A good feature request @levindecaro . For now use the API (cmk for instance) to search based on UUID.
