### ISSUE TITLE
Cloudstack XCP-NG and OVS GRE plugin

### ISSUE THREAD

**Issue by furyflash777** [apache/cloudstack#6179]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Network, OVS
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.0 
~~~

##### CONFIGURATION

advanced networking + OVS 

##### SUMMARY

I am trying to use guest network isolation based on open vswitch GRE.
According this guide https://docs.cloudstack.apache.org/en/latest/plugins/ovs-plugin.html

Zone, clusters, hosts, System VMs are created, but during VM creation I have an error

INFO [c.c.v.VirtualMachineManagerImpl] (Work-Job-Executor-14:ctx-8cff03b7 job-389/job-391 ctx-1ee828af) (logid:ba1a0383) Insufficient capacity
com.cloud.exception.InsufficientVirtualNetworkCapacityException: Unable to allocate vnet as a part of network Ntwk[232|Guest|8] implement Scope=interface com.cloud.dc.DataCenter; id=6

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Configure Zone with OVS GRE isolation and XCP-NG hypervisor 
~~~

##### ACTUAL RESULTS

VM is not started 

~~~

~~~

**Comment by weizhouapache** [comment]
@furyflash777 
this seems to be same as #6727 
the vxlan VNI range is not passed when you created the zone.

this is fixed by #7038

**Comment by weizhouapache** [comment]
@furyflash777 
do you still have this issue ?

**Comment by weizhouapache** [comment]
@furyflash777 
I am closing this issue. please feel free to reopen if you still have same issue
