### ISSUE TITLE
list routers issues by domain admin

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6191]
API `listRouters` is permitted to domain admin since the implementation of dynamic roles.

the file `engine/schema/src/main/resources/META-INF/db/create-default-role-api-mappings.sql` has the following sql
```
INSERT INTO `cloud`.`role_permissions` (`uuid`, `role_id`, `rule`, `permission`, `sort_order`) values (UUID(), 3, 'listRouters', 'ALLOW', 194) ON DUPLICATE KEY UPDATE rule=rule;
```
There are few issues on UI
(1) domain admin can list virtual routers of isolated networks , but get a 404 error when view the details of routers.
(2) the api response of listrouters does not have information of guest nic 
(3) domain admin cannot list virtual routers of shared networks (scope is Domain or Account).

First of all, do we need to add this role permission by default ?

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rohityadavcloud** [comment]
Hi @weizhouapache this sounds like a bug, have you checked git history - if git history confirms that listRouters shouldn'be allowed for domain domain - let's remove this at least from default/in-built roles in an upgrade path in 4.17.0.0. cc @nvazquez @Pearl1594

**Comment by rohityadavcloud** [comment]
If the listRouters is an allowed API historically, perhaps it was never meant to be supported in the UI? So, it's worth discussing how we fix the bug or do anything about it in the UI?

**Comment by weizhouapache** [comment]
> As a domain admin I would like to see the routers and the internal nics, I'm not sure if I would need to see all router attributes as domain admin.

@DaanHoogland 
different from your opinion, as a root admin I do not expect this informatoin to be visible for domain admin :-)

**Comment by DaanHoogland** [comment]
> > As a domain admin I would like to see the routers and the internal nics, I'm not sure if I would need to see all router attributes as domain admin.
> 
> @DaanHoogland 
> different from your opinion, as a root admin I do not expect this informatoin to be visible for domain admin :-)
> 
> 

Right, meaning it should be configurable, should it?
