### ISSUE TITLE
Bring in the JUnit Assume Feature to `CABackgroundTaskTest`

### ISSUE THREAD

**Issue by Codegass** [apache/cloudstack#6203]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
TEST
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
I would like to propose an idea of using Assume feature offered in JUnit 4&5 for some of the test cases in CloudStack. The Assume function is to replace Assertion in precondition checking. As [mentioned in the document](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html):

> Assume functions is a set of methods useful for stating assumptions about the conditions in which a test is meaningful. A failed assumption does not mean the code is broken, but that the test provides no useful information.

I notice that some test cases in CloudStack can benefit from the Assume feature. For example:

1. [testAutoRenewalEnabledWithExceptionsOnProvisioning](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L122)
2. [testAutoRenewalEnabledWithNoExceptionsOnProvisioning](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L111) 
3. [testAutoRenewalDisabled](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L134)

These cases are all from `CABackgroundTaskTest`. They all use the assert function to check the preconditions regarding `certMap.size()` in the test cases.

Take the test case, [`testAutoRenewalDisabled`](https://github.com/apache/cloudstack/blob/main/server/src/test/java/org/apache/cloudstack/ca/CABackgroundTaskTest.java#L136-L137), as an example. Right now this case is asserting `certMap.size() == 1` before the actual testing target(`task.runInContext()`) is executed.

```java
certMap.put(hostIp, expiredCertificate);
Assert.assertTrue(certMap.size() == 1);
```
Since the test case `testAutoRenewalDisabled` contains 2 assertions, it may fail due to 2 reasons:

* The functions related to the `certMap` have bugs.(Here is the `Assert.assertTrue(certMap.size() == 1)`)
* The function `task.runInContext()` have bugs.(What we actually want to check with this test)

Here I suggest replacing the `assertTrue` function with the `assumeThat` function, so when the precondition fails, JUnit can skip it instead of report a failurel.  This can help us to focus on failure that is raised by the target testing function.

##### Proposed changes

Before
```java
certMap.put(hostIp, expiredCertificate);
Assert.assertTrue(certMap.size() == 1);
```

After
```java
certMap.put(hostIp, expiredCertificate);
Assume.assumeThat(icertMap.size() == 1, is(true));
```

Please let me know if you think this proposal makes sense, If so I can submit a PR accordingly, If not, comments are appreciated.

**Comment by rohityadavcloud** [comment]
@Codegass could you propose a PR, or discuss further on dev@ mailing list https://cloudstack.apache.org/mailing-lists.html

**Comment by Codegass** [comment]
> @Codegass could you propose a PR, or discuss further on dev@ mailing list https://cloudstack.apache.org/mailing-lists.html

Thank you for the reply! I will soon propose a PR this weekend.
