### ISSUE TITLE
Provide project UUID in the user UI if not an admin

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#6231]
##### ISSUE TYPE
* Enhancement Request
 
##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
GA

##### CONFIGURATION
http://qa.cloudstack.cloud:8080

##### SUMMARY
In case a user is not an admin, how will he/she find out in the UI the project ID? maybe display aside the name in the View dropdown.

##### Workaround
Use Developer Tools (F12) in browser to sneak for the UUID in the dropdown either an API tool like Cloudmonkey.

**Comment by nvazquez** [comment]
Hi @synergiator sorry if I didn't understand properly, but as a user I am able to see a project's UUID by clicking on it (Projects -> click on the project -> See ID at the left) - can you explain further?

**Comment by synergiator** [comment]
never mind, need to double check. thx.

**Comment by rohityadavcloud** [comment]
Appears a non-issue, thanks for reporting @synergiator pl re-open if you're able to reproduce the issue.
