### ISSUE TITLE
Plugins for specific Domain or Accounts.

### ISSUE THREAD

**Issue by jack99trade** [apache/cloudstack#6249]
##### ISSUE TYPE
* Other

##### COMPONENT NAME
Plugins Configuration

##### CLOUDSTACK VERSION
4.16.1.0
##### CONFIGURATION

Is there any parameter I can add in config to show a  plugin for specific Account or Domain . 
e.g. ExamplePlugin is shown to Domain-1  users 
      ExamplePlugin1 is shown to Domain-2 users

###
{
   plugins: [
      {
         "name": "ExamplePlugin",
         "icon": "appstore",
         "path": "example.html"
      },
      {
         "name": "ExamplePlugin1",
         "icon": "appstore",
         "path": "https://cloudstack.apache.org/"
      }
   ]
###

##### OS / ENVIRONMENT
Centos7

**Comment by DaanHoogland** [comment]
No there isn't @jack99trade . At the moment features are just shown or hidden on the basis of access rights to APIs and in most cases being a root admin or not.

**Comment by jack99trade** [comment]
> No there isn't @jack99trade . At the moment features are just shown or hidden on the basis of access rights to APIs and in most cases being a root admin or not.

@DaanHoogland  Thanks for info.
