### ISSUE TITLE
User Account disable issue. 

### ISSUE THREAD

**Issue by jack99trade** [apache/cloudstack#6251]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME
User Management
##### CLOUDSTACK VERSION
4.16.1.0

##### CONFIGURATION

Cloudstack with Ldap integration (Windows AD)

##### OS / ENVIRONMENT
centos7
##### SUMMARY

whenever user enters bad password couple of times. its AD account is locked for 15 minutes and then its auto unlocked in AD.

on Cloudstack the users is disabled and keeps in disabled state.  

I am unable to find an option to turn off this feature on Cloudstack because Account policy is set by AD. please suggest which configuration i need to toggle to fix this.
######################

**Comment by nvazquez** [comment]
Hi @jack99trade I think that CloudStack behavior cannot be disabled, will need some investigation unless @DaanHoogland @rohityadavcloud @andrijapanicsb could you remember if its possible to disable that?

**Comment by weizhouapache** [comment]
@nvazquez @jack99trade 
you can update the global setting `incorrect.login.attempts.allowed` to a large value.

@nvazquez 
we could make changes to mark the value `0` as disabled in 4.17.0.0.

**Comment by nvazquez** [comment]
Many thanks @weizhouapache - I have created the fix #6254

**Comment by jack99trade** [comment]
> incorrect.login.attempts.allowed

@weizhouapache  thanks for this. i have updated my incorrect.login.attempts.allowed global value to higher side for now.

**Comment by nvazquez** [comment]
Fixed on #6254
