### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [apache/cloudstack#6259]
##### ISSUE TYPE

 * Other

##### SUMMARY

Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `plugins\user-authenticators\ldap\pom.xml`, `org.zapodot:embedded-ldap-junit` scope should be `test`  instead of `compile`.
- in `utils\pom.xml`, `commons-io:commons-io` scope should be `compile`  instead of `provided`.
- in `server\pom.xml`, `mysql:mysql-connector-java` scope should be `compile`  instead of `test`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6557
