### ISSUE TITLE
Does the cloudstack Primary Storage support the Shared-Block storage service?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6291]
Does the cloudstack Primary Storage support the Shared-Block storage service ?
 - https://www.zstack.io/help/en/product_manuals/maintenance_manual/v3/7.4.html#chapter-7-4-1-Shared-Block
 
If support, How to use it?

![image](https://user-images.githubusercontent.com/4197714/176598404-08a3511a-2a9a-4dab-ad4e-2981938b04be.png)

**Comment by rohityadavcloud** [comment]
Hi @xuanyuanaosheng no there is no support for shared-blockstorage in CloudStack. Please may discuss your ideas on dev@ or users@ mailing list https://cloudstack.apache.org/mailing-lists.html

**Comment by xuanyuanaosheng** [comment]
@rohityadavcloud  OK, Thanks
