### ISSUE TITLE
Does the cloudstack support the SAN Storage?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6292]
Does the cloudstack support the SAN Storage like : https://www.zstack.io/help/en/product_manuals/maintenance_manual/v3/7.6.html

**Comment by rohityadavcloud** [comment]
Hi @xuanyuanaosheng can you discuss/ask on the dev and users mailing list if you're not getting attention on Github issues as not all developers/users check Github often. https://cloudstack.apache.org/mailing-lists.html
