### ISSUE TITLE
Place VM's on the same network as the CloudStack-management server

### ISSUE THREAD

**Issue by CKrieger2020** [apache/cloudstack#6298]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

UI, IP

##### CLOUDSTACK VERSION

4.16.0.0

##### SUMMARY

I am trying to find a method of placing newly deployed VM's on the same network as my management server, but so far it only allows me to create guest VM's behind a NAT with a private IP address. I need to create multiple VM's hosting services that can be routed to an external DNS. My concern is that the NAT will make routing to these machines impossible.

I have tried changing the network offering on my guest network from "offering for isolated network with NAT service enabled" to "offering for isolated network with no NAT service enabled", but it gives me this error:

"can't upgrade from network offering edad787d-baa0-4ca8-a67b-bd288adc6d37 to 052cee24-272b-44f1-a4df-4b5da7a30744; check logs for more information"

I would choose this during network deployment, but I do not have the option to choose "offering for isolated network with no NAT service enabled" until after deployment. 

I would appreciate any advice you can give to help guide me from here as I am new to cloudstack

##### EXPECTED RESULTS

Place all deployed VM's on same IP range as the management console itself. 

##### ACTUAL RESULTS

Forced to deploy VM's behind NAT per default configuration

**Comment by DaanHoogland** [comment]
@CKrieger2020 this is certainly a new use case. After a quick read I think you might want to investigate going to IPv6.
Another possible way to go is to deploy in a shared network.

**Comment by nxsbi** [comment]
@CKrieger2020 - have you tried to create a new Network or create a L2 network (assuming your CS instance is on a separate L2 network than what is available in CS for users to choose from)
In my home lab I have been able to create instance using L2 which talks to my other computers on the home network.

**Comment by rohityadavcloud** [comment]
It's possible to do this by deploying VMs on a L2 network whose vlan is `vlan://untagged` essentially you'll be on the same network as your host/mgmt network.

**Comment by rohityadavcloud** [comment]
@CKrieger2020 can you check the above suggestion and re-open the issue to discuss more.
To discuss further questions, you can raise them on the users@ and/or dev@ ML https://cloudstack.apache.org/mailing-lists.html
