### ISSUE TITLE
unsupported configuration: VNC password is 22 characters long, only 8 permitted

### ISSUE THREAD

**Issue by Tragiv** [apache/cloudstack#6302]
##### ISSUE TYPE

 Other

##### COMPONENT NAME

~~~
system VM
~~~

##### CLOUDSTACK VERSION

~~~
  cloudstack-agent-4.15.2.0-1.el8.x86_64
  cloudstack-common-4.15.2.0-1.el8.x86_64
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

CentOS Stream release 8   KVM  host

##### SUMMARY

enable  zone ,
Agent log error
org.libvirt.LibvirtException: unsupported configuration: VNC password is 22 characters long, only 8 permitted

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
system VM  is start
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@Tragiv 
this issue should be fixed in upcoming 4.17.0.0 by #6244

**Comment by Tragiv** [comment]
thanks, I know

**Comment by weizhouapache** [comment]
This is caused by a libvirt change made in Dec 2021
https://gitlab.com/libvirt/libvirt/-/commit/27c1d06b5bd68bdce55efff0a50a15a30cb2a96b

for users who use 4.15/4.16 and have this issue, please downgrade libvirt.
