### ISSUE TITLE
Upgrade ant-design-vue to version 3.x

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#6342]
After upgrading to Vue3, have moved to ant-design-vue version 2.x. However it is now recommended to move to version 3.x:

https://www.antdv.com/docs/vue/migration-v3:

`
The 2.x version is a compatible version developed for compatibility with Vue 3. It does not bring many new features, and most of the API changes are only for better compatibility with Vue 3. The 3.x version has greatly improved performance, ease of use, and functions. After the 3.x version is stable, we will archive the 2.x version. It is recommended that you upgrade to the 3.x version as soon as possible. Although there are many changes, they are basically compatible. You can upgrade gradually according to the warnings given by the console.
`

##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
UI
~~~

**Comment by nvazquez** [comment]
Hi @utchoang since you have done a great work on the Vue3 PR can you please check this one?

**Comment by eliran-natan** [comment]
Is it possible to upgrade to from Vue 2 to Vue 3 while still using Antd 1.7.8? 
Thanks!

**Comment by utchoang** [comment]
@eliran-natan No, because Antd 1.7 only works with Vue 2. When I migrate from Vue 2 -> 3, I have to upgrade the Antd version from 1->2 (refer to https://github.com/apache/cloudstack/pull/5151)

**Comment by eliran-natan** [comment]
Thank you! So this means that Antd version 2 would work with Vue2? (So we could do the upgrade step by step: first upgrade antd while still working with Vue2, and later on upgrade to Vue3). 
Will it be the same for antd version 3? :)

**Comment by utchoang** [comment]
@eliran-natan If you want to use Antd version 2, you must use Vue 3. You can refer to https://2x.antdv.com/docs/vue/migration-v2

**Comment by eliran-natan** [comment]
@utchoang, so this means that there cannot be a step-by-step upgrade. 
We have to move to Vue3 and to Antd2 on the same go...do you agree? :)
- To update to Vue 3 I must have antd2
- To update to antd2 I must have Vue3

**Comment by rohityadavcloud** [comment]
We've already migrated to vue3, so it's about moving to andv2 now.
