### ISSUE TITLE
Drop embedded LDAP classes from runtime

### ISSUE THREAD

**Issue by mlsorensen** [apache/cloudstack#6346]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME

~~~
LDAP
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### SUMMARY
LDAP test cases use packages from `org.apache.directory.server` to create an embedded LDAP server for testing. These packages pull in ehcache 2.10.4, which embeds a version of Jetty and Jackson that have critical vulnerabilities. While this LDAP server and classes aren't used in a running CloudStack instance, we should avoid packaging these classes outside of the testing scope.

**Comment by DaanHoogland** [comment]
thanks for the notice @mlsorensen , these were supposed to become an embedded ldap, but as virtual attributes are not well supported in apache DS, that effort failed.
