### ISSUE TITLE
Juniper SRX plugin: Improperly parsed untagged VLAN when provisioning a guest network

### ISSUE THREAD

**Issue by vdombrovski** [apache/cloudstack#6381]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Juniper SRX plugin
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

This is a direct follow-up to the following issue: https://issues.apache.org/jira/browse/CLOUDSTACK-9996

Previously addressed by this commit:

https://github.com/apache/cloudstack/commit/a8c09f2a1980757eb7a9da4a178dc27da08df2ed

A similar issue arises whenever Cloudstack tries to provision a Guest network; The following check fails because of the equals instead of contains:

https://github.com/apache/cloudstack/blob/main/plugins/network-elements/juniper srx/src/main/java/com/cloud/network/resource/JuniperSrxResource.java#L703

##### STEPS TO REPRODUCE

~~~
1. Configure an SRX network element. Choose any interfaces, it doesn't matter for this issue
2. Provision a public IP range inside your public network; make sure that you don't specify any VLANs (so that it becomes vlan://untagged)
3. Create a network offering for isolated networks with the following providers:
- DNS,DHCP,UserData: VR
- Firewall,SourceNAT,StaticNAT,PortForwarding: Juniper SRX
4. Create a guest network that uses the above network offering.
5. Try to restart the guest network; this will force the initial SRX configuration.

If you manually update the VLAN inside cloud.vlan database to be "untagged" instead of "vlan://untagged"; the above steps achieve expected results.
~~~

##### EXPECTED RESULTS

~~~
The guest network restart completes successfully
~~~

##### ACTUAL RESULTS

~~~
The guest network restart fails. DEBUG logs show the following:

2022-05-11 14:06:44,472 ERROR [c.c.n.r.JuniperSrxResource] (DirectAgent-2:ctx-f5e76969) (logid:b540c9d9) com.cloud.utils.exception.ExecutionException: Could not parse public VLAN tag: vlan://untagged
~~~

**Comment by rohityadavcloud** [comment]
We don't have any SRX infra in the community CI/CD systems to verify/fix this, any pull request is welcome @vdombrovski

**Comment by DaanHoogland** [comment]
@vdombrovski As the iControl jar for juniper appliances is outdated we have removed the SRX plugin. If we reintroduce it we first need to find a replacement jar.

**Comment by vdombrovski** [comment]
@DaanHoogland sounds good, I saw your PR #7023. Are you planning to delete this from the official documentation for the upcoming release as well?

**Comment by DaanHoogland** [comment]
> Are you planning to delete this from the official documentation for the upcoming release as well?

good point didn't think of that.

**Comment by DaanHoogland** [comment]
created https://github.com/apache/cloudstack/issues/7690 for this

> > Are you planning to delete this from the official documentation for the upcoming release as well?
> 
> good point didn't think of that.

**Comment by vdombrovski** [comment]
Awesome, I'll close this issue, as it is no longer in scope.
