### ISSUE TITLE
Updating the rpfilter config value to 'false' in the upgrade path

### ISSUE THREAD

**Issue by soreana** [apache/cloudstack#6390]
As we discussed [here](https://github.com/apache/cloudstack/pull/6380#discussion_r872021311_) we need to update the `network.disable.rpfilter` and `consoleproxy.disable.rpfilter` config values to `false` in the upgrade path (either Upgrade class / schema file) when the value is not 'true'.

Check the following pull request for more information: https://github.com/apache/cloudstack/pull/6380

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6477
