### ISSUE TITLE
Please release 4.16/4.17 Docker images to the official Docker Hub account!

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#6396]
So far, there are working builds for 4.16.1/4.17-SNAPSHOT Docker images of the cloud stack simulator.

It would be great to make them available in the official Docker Hub account!

![image](https://user-images.githubusercontent.com/1834666/168970658-f5154245-1954-4a48-8ac4-d1023a5b998b.png)

In the meantime, build for 4.16.0/4.16.1 has been shared by one of the team members:
https://hub.docker.com/r/ustcweizhou/cloudstack-simulator/tags

**Comment by rohityadavcloud** [comment]
Thanks makes sense, we'll need to figure out how to do this and if this requires access from ASF. (we've never needed this as nobody has asked/required this and it would add an overhead to maintain/test/build/publish them)

**Comment by synergiator** [comment]
Hi Rohit, indeed I discussed this on the ML last year. I think an easy-access up to date cloudstack simulator could attract more newcomers to the community, but that's just a hypothesis. Good enough there is an online demo, as well.

**Comment by weizhouapache** [comment]
> Is it like microstack?

@xlmnxp 
I think `mbx` is the tool similar as `microstack`
https://github.com/shapeblue/mbx
You can use it to deploy cloudstack mgmt server and different hypervisors in a server.

**Comment by threedliteguy** [comment]
I tried the above docker image but it still requires an external NFS server, it seems. So when I get to the step of adding primary and secondary storage I do not have the root pwd or an NFS mount to point to to continue to be able to test uploading an iso and launching an instance of it.  A docker run script with port mappings (e.g. 5050) and persistence directory mapping parms would also be helpful to have.

**Comment by rohityadavcloud** [comment]
@weizhouapache did you explore something to this end, may be we can add a Github action to automate this? (to push for main branch and every 4.xx release/tag?)
