### ISSUE TITLE
bug: fail to download a template from https

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#6406]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Core, GUI, API
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.17.0.0-snapshot.20220325 
~~~

##### CONFIGURATION

Advanced network with VPC
KVM

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

I'm using a QCOW2 image template. When I install it from a `http` location, all works. When I setup my reverse proxy to use `https` (with support of `tls1.2` and `tls1.3`, I'm getting an error: `Received fatal alert: internal_error`

Log is here [management-server.log](https://github.com/apache/cloudstack/files/8749437/management-server.log)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Download and install template from `http` and `https`
~~~

##### ACTUAL RESULTS

~~~
Can download a template from `http` only
~~~

**Comment by nvazquez** [comment]
Hi @tampler can you upload the SSVM logs as well?

**Comment by nvazquez** [comment]
Also - does this mean you are running the code from main at 25/03? (CloudStack 4.17.0.0-snapshot.20220325). If that is the case please upgrade your packages to use the latest code (or 4.17 RC2 - https://download.cloudstack.org/testing/4.17.0.0-RC2/)

**Comment by tampler** [comment]
Hi @nvazquez 

Yes, I used a nightly build for 4.17 back then (Mar 25 2022) to setup a test env. Do you want me to try with the latest nightly for 4.17 or 4.16 ? :thinking:

**Comment by nvazquez** [comment]
@tampler thanks, latest nightly packages for 4.17 should be fine. You may also need the latest system VM template and recreate your system VMs

**Comment by nvazquez** [comment]
Sure - the packages include the system VM templates, that should work

**Comment by nvazquez** [comment]
Hi @tampler please confirm if the issue persists after rebuilding with the latest packages

**Comment by weizhouapache** [comment]
@tampler 
have you tested latest 4.17.0.0 RC3 ?

do you use self-signed certificate ?

**Comment by tampler** [comment]
Hi @weizhouapache 

1. Not yet tested. I'll be using the latest nightly. Sorry for the delay - our test env is being used and I need more time
2. No, I'm using and ext authority and set up ACS behind a reverse proxy

Best,
Boris

**Comment by tampler** [comment]
I was unable to install ACS nightly 4.17.0.0 as of Jun 3 2022 on `Ubuntu 22.04`. 
`cloudstack-setup-management` fails with this:
```bash
DEBUG:root:execute:uname -m
DEBUG:root:execute:hostname -f
DEBUG:root:execute:touch /var/run/cloudstack-management.pid
DEBUG:root:execute:chown cloud.cloud /var/run/cloudstack-management.pid
DEBUG:root:execute:hostname --fqdn
DEBUG:root:execute:mkdir -p /var/lib/cloudstack/
DEBUG:root:execute:chown cloud:cloud -R /var/lib/cloudstack/
DEBUG:root:execute:sudo /usr/sbin/service cloudstack-management status
DEBUG:root:execute:sudo /usr/sbin/service cloudstack-management stop
DEBUG:root:execute:sudo update-rc.d -f cloudstack-management remove
DEBUG:root:execute:sudo update-rc.d -f cloudstack-management defaults
DEBUG:root:Failed to execute:update-rc.d: error: unable to read /etc/init.d/cloudstack-management
DEBUG:root:execute:sudo /usr/sbin/service cloudstack-management status
DEBUG:root:Failed to execute:x cloudstack-management.service - CloudStack Management Server
     Loaded: loaded (/lib/systemd/system/cloudstack-management.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-06-03 12:41:01 UTC; 649ms ago
   Main PID: 116513 (code=exited, status=143)
        CPU: 19.150s

Jun 03 12:35:19 mgmt java[116513]: WARNING: An illegal reflective access operation has occurred
Jun 03 12:35:19 mgmt java[116513]: WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/usr/share/cloudstack-management/lib/cloudsta>
Jun 03 12:35:19 mgmt java[116513]: WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
Jun 03 12:35:19 mgmt java[116513]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jun 03 12:35:19 mgmt java[116513]: WARNING: All illegal access operations will be denied in a future release
Jun 03 12:41:01 mgmt systemd[1]: Stopping CloudStack Management Server...
``` 

Falling back to `4.16.2.0` to try this out

**Comment by weizhouapache** [comment]
> 

@tampler 
this error seems to be caused by db configuration.
the cloudstack-management service is running

**Comment by tampler** [comment]
@weizhouapache got a msg from you few days ago, which for some reason is NOT displayed in the issue history

> this error seems to be caused by db configuration.
> the cloudstack-management service is running

1. What makes you think so? :thinking: 
2. Why do I don't see issues with 4.16.2?

This time I'm setting up a standalone hardened MySQL server with pre-config. I created 2 users on my `mysql` host: `cloud@mgmt` and `root@mgmt`. I can access my MySQL server from the Mgmt server with the following:

```bash
mysql -u root -h mysql
mysql -u cloud -h mysql -p
```
This works fine for 4.16.2
Any ideas? :thinking:

**Comment by weizhouapache** [comment]
> @weizhouapache got a msg from you few days ago, which for some reason is NOT displayed in the issue history
> 
> > this error seems to be caused by db configuration.
> > the cloudstack-management service is running
> 
> 1. What makes you think so? 🤔
> 2. Why do I don't see issues with 4.16.2?
> 
> This time I'm setting up a standalone hardened MySQL server with pre-config. I created 2 users on my `mysql` host: `cloud@mgmt` and `root@mgmt`. I can access my MySQL server from the Mgmt server with the following:
> 
> ```shell
> mysql -u root -h mysql
> mysql -u cloud -h mysql -p
> ```
> 
> This works fine for 4.16.2 Any ideas? 🤔

@tampler 
I have removed the comment as I think it is wrong.

I have successfully deployed cloudstack 4.17.0.0 with ubuntu 22.04 as mgmt server and hypervisor in our lab.
It looks fine.

**Comment by harikrishna-patnala** [comment]
Ping @tampler, are you still seeing this issue?

**Comment by rohityadavcloud** [comment]
Hi @tampler we've reviewed and tested this issue and found to be a non-issue. Can you try with the most recently ACS release 4.17.0.0 deb packages repo such as http://packages.shapeblue.com/cloudstack/upstream/debian/4.17/ and try again? If you're able to reproduce this, pl re-open this issue. Thanks for submitting the bug report.

**Comment by tampler** [comment]
Hello everyone and thanks for helping on this. 

We cannot currently upgrade the ACS version and test the issue on the latest 4.17. I'll get back to this as soon as we upgrade
