### ISSUE TITLE
Broken SAML SSO plugin with malformed URL when authenticating against Google IdP

### ISSUE THREAD

**Issue by Luis-3M** [apache/cloudstack#6427]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
SAML SSO plugin
~~~

##### CLOUDSTACK VERSION
~~~
LATEST -> https://github.com/apache/cloudstack/blame/main/plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java#L153
~~~

##### CONFIGURATION
SAML SSO plugin activated.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Google's IdP URL already contains a query param, thus this line of code will create a malformed redirect URL.
https://github.com/apache/cloudstack/blame/main/plugins/user-authenticators/saml2/src/main/java/org/apache/cloudstack/saml/SAMLUtils.java#L153

Example of google's IdP URL: `https://accounts.google.com/o/saml2/idp?idpid=XXXXXXXXX`

##### STEPS TO REPRODUCE
- Enable and configure SAML SSO plugin2 using Google as the IdP.
- Access the UI and attempt to login via Single Sign-On

You should now face an Invalid Request error.

##### EXPECTED RESULTS
Users should be redirected to Google's login portal thus completing the authentication flow.

##### ACTUAL RESULTS
![Screenshot 2022-05-31 at 11 08 55](https://user-images.githubusercontent.com/26753403/171154930-8a54162c-6552-458f-9e53-0ea2bb28ddb3.png)

~~~
Malformed URL: 
https://accounts.google.com/o/saml2/idp?idpid=<ID>?SAMLRequest=<SAMLRequest>
~~~

~~~
Expected URL:
https://accounts.google.com/o/saml2/idp?idpid=<ID>&SAMLRequest=<SAMLRequest>
~~~

**Comment by Luis-3M** [comment]
Hi @rohityadavcloud ,
Relevant fields of our IdP Metadata are the following:

`<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://accounts.google.com/o/saml2/idp?idpid=XXXXXXX"/>`

`<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://accounts.google.com/o/saml2/idp?idpid=XXXXXXX"/>`

Cloudstack SAML plugin assumes that the SSO URL will not have a query param which is not the case for Google.

**Comment by neogismm** [comment]
Hi @Luis-3M, can you share the google SAML error code?

**Comment by Luis-3M** [comment]
Hi @neogismm,
Apologies for the late response.

Successful request
![saml_success](https://user-images.githubusercontent.com/26753403/173936642-7357d970-117f-46aa-bee8-5fac8876a8f7.png)

Unsuccessful request (due to a broken redirect URL)
![saml_failure](https://user-images.githubusercontent.com/26753403/173936665-b28e5c85-86ad-4116-8f27-a45d52e64db0.png)

We should append the SAML request query param using "?" or "&" for cases where the IdP URL does not contain/does contain query params, respectively.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6457
