### ISSUE TITLE
Fast Instance Group Selection

### ISSUE THREAD

**Issue by anrusakov** [apache/cloudstack#6428]
**Description**

Add Groups list to "Filter By" 
Or 
Add Groups list to "Serach"

**Types of changes**

- [ ]  Bug Report
- [ ]  Improvement Request
- [ ]  Enhancement Request
- [x] Feature Idea
- [ ]  Documentation Report
- [ ]  Other

Feature/Enhancement Scale or Bug Severity
Feature/Enhancement Scale
- [ ]  Major
- [x]  Minor

##### SUMMARY

It is very hard to Find VM or VMs on "Inststances" page in case i have 30+.

Groups is cool feature, but to find VM I have to go to "Instance Groups", find Group, and then press "View Instances".

It will be greate to add "Instance Groups" list to "Inststances" page - to "Filter By"  or to "Serach"

This feature will be useful for customer support as well.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6495
