### ISSUE TITLE
API: virtualmachine VPC information not returned

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#6452]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API
~~~

##### SUMMARY

Currently, it is possible to list instances filtered by VPC, yet the information returned by the API includes no VPC information. In the case of our Ansible Inventory plugin, this translates into having the ability to "filter" by VPC, but not to group by VPC. Grouping by VPC is very desirable because allows to target specific VPCs with automation playbooks.

##### HOW THE FEATURE WOULD BE USED

Once VPC information is returned with instance data, the Ansible Inventory Plugin will be able to run playbooks targeting an specific VPC.

**Comment by rvalle** [comment]
I am not sure of the best implementation, currently the virtualmachine information inclues a nic array with ip information and network information such as:

```
"networkid": "975331fe-1b24-4921-933e-26ccf00eb2a3",
"networkname": "frontend",
```
perhaps when the nic information could also include ```vpcid```,```vpcname``` when the network happens to belong to a VPC.

**Comment by nvazquez** [comment]
Fixed on #6461

**Comment by rvalle** [comment]
woow @nvazquez didn't expect this enhancement implemented so quickly! 
thanks!

**Comment by nvazquez** [comment]
Thanks @rvalle and @Pearl1594 for the quick fix. You can find it already on the 4.17 branch and also on main branch while 4.17.1/4.18 are not released
