### ISSUE TITLE
Unable to create VPC in latest version through the UI

### ISSUE THREAD

**Issue by ash-quinn** [apache/cloudstack#6453]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
- latest
~~~

##### CONFIGURATION

We currently have a single interface with two vlans, one is native on the trunk, the other is vlan 30. We have gone through the basic configuration of the cluster and everything
##### OS / ENVIRONMENT

AlmaLinux 8.5 on both machines

##### SUMMARY

 When we try to make a VPC it does not show the zone. We spent hours trying to configure the VpcVirtualRouter and finally after using the API got the provider enabled.

##### STEPS TO REPRODUCE

~~~
go through basic configuration and then try to make a VPC
~~~

##### EXPECTED RESULTS

~~~
the user interface shows our zone and we can select a vpc service offering
~~~

##### ACTUAL RESULTS

~~~
It does not show the zone
![image](https://user-images.githubusercontent.com/56168307/173495295-e103e44d-024e-45a7-9a36-d4492073ae3e.png)

~~~

**Comment by shwstppr** [comment]
@ash-quinn is your zone security group enabled?

**Comment by ash-quinn** [comment]
@shwstppr It is, yes!

**Comment by shwstppr** [comment]
@ash-quinn There always been a filter in UI to not list zones with security group,
https://github.com/apache/cloudstack/blob/4.13.0.0/ui/scripts/network.js#L5176
In main, https://github.com/apache/cloudstack/blob/main/ui/src/views/network/CreateVpc.vue#L161

Not sure if it is needed with the latest backend code. Will check and maybe create a PR to fix this

**Comment by shwstppr** [comment]
@ash-quinn checked the docs and code it seems isolated networks and VPCs aren't meant for zones with security groups as they only support shared network model.
Maybe this should be made a bit more clearer in the docs

**Comment by rohityadavcloud** [comment]
Addressed in documentation with https://github.com/apache/cloudstack-documentation/pull/278
