### ISSUE TITLE
Kubernetes cluster stuck in Stopping state

### ISSUE THREAD

**Issue by saffronjam** [apache/cloudstack#6456]
##### ISSUE TYPE
 * Bug Report
 
##### COMPONENT NAME
API

##### CLOUDSTACK VERSION
4.17.0  (cloud have occurred on 4.16.1)

##### CONFIGURATION
Single host running management server and database 

##### OS / ENVIRONMENT
Ubuntu 20.04

##### SUMMARY
When attempting to delete a Kubernetes cluster, it gets stuck in Stopping state.  
![cluster-stuck-in-stopping-state](https://user-images.githubusercontent.com/26722370/173568612-afc21b94-e32a-46fa-a9e4-62a7b363b932.png)

And every time a kubernetes-related API call is made, such as "deleteKubernetesCluster", error 530 appears
![error-530](https://user-images.githubusercontent.com/26722370/173568629-45b49c3a-fc6b-4419-acca-ceb2c9ac717a.png)

Investigating the cloudstack-management.service logs, there seem to be an unhandled null pointer exception when issuing some string operation (perhaps a toString() on a null reference). Looking into the source code, it appears to be the case. 
![error-logs](https://user-images.githubusercontent.com/26722370/173570426-a7c4b6fd-f0b1-41b3-9e5a-6ae69bccabd5.png)

##### STEPS TO REPRODUCE
Removing clusters was possible, but this time it appears as some reference was deleted in database, which nullified a field in a row in the table kubernetes_supported_version, or related table. Therefore, it would be hard to write steps to reproduce. 

##### EXPECTED RESULTS
Friendlier error message, recoverable state. How can such a field become null?

##### ACTUAL RESULTS
Kubernetes clusters stuck in stopping state, refuses to be deleted, prompting multiple error code 530 messages
(every delete operation is ignored since a cluster cannot be deleted while in the stopping state)

**Comment by Pearl1594** [comment]
@saffronjam is the Kubernetes binaries iso for the corresponding Kubernetes version available? Based on the NPE it appears that the iso for the Kubernetes version in question isn't available.

**Comment by saffronjam** [comment]
Thanks for the quick reply.

I think that was the case.

I resolved it by marking the entries in the database as removed.

You can close this issue :)
