### ISSUE TITLE
UI breaks with SAML authentication

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack#6459]
Greetings CloudStack devs. Congrats on your 4.17.0.0 release. I ran into a minor UI bug which I'll explain below.

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0.0
~~~

##### CONFIGURATION
Basic CloudStack with SAML/SSO authentication enabled

##### OS / ENVIRONMENT
N/A  (Rocky Linux 8.5)

##### SUMMARY
When logging in via SAML, after the SAML server redirects the client back to CloudStack, the UI fails to load any pages because a javascript exception is thrown. 

Attached is a gif showing what happens. 
![cloudstack4-17-sso-broken-list](https://user-images.githubusercontent.com/4450716/173693442-8cc18438-e500-4dee-81ae-8a2db587737e.gif)

The stack trace from the browser console is also given below. Note that '7a9f1bad-8de0-4fa7-8a64-a09dc845e3e3' is my user ID.

```
TypeError: Cannot read properties of undefined (reading '7a9f1bad-8de0-4fa7-8a64-a09dc845e3e3')
    at Proxy.fetchData (AutogenView.vue:830:34)
    at Proxy.created (AutogenView.vue:608:10)
    at dt (runtime-core.esm-bundler.js:155:36)
    at pt (runtime-core.esm-bundler.js:164:21)
    at br (runtime-core.esm-bundler.js:2965:5)
    at vr (runtime-core.esm-bundler.js:2867:9)
    at Ma (runtime-core.esm-bundler.js:7170:9)
    at _a (runtime-core.esm-bundler.js:7082:9)
    at Pa (runtime-core.esm-bundler.js:7012:11)
    at V (runtime-core.esm-bundler.js:4922:13)
```

The line at AutogenView.vue:830 is:
```
        if (!this.$store.getters.customColumns[this.$store.getters.userInfo.id]) {
```

The workaround currently is to do a full page refresh after logging in. After that is done, I can load all pages properly again. This issue does not affect local accounts, only SAML authenticated accounts.

Please let me know if there're anything I can debug on my end.

Thanks again.

##### STEPS TO REPRODUCE
~~~
1. Sign out
2. Sign in using SAML
3. Attempt to list VM instances
~~~

##### EXPECTED RESULTS
~~~
Expect the list to load properly
~~~

##### ACTUAL RESULTS
~~~
Lists doesn't load and there is an exception in the browser console.
~~~

**Comment by ngrosc** [comment]
Same here. It is not limited to instances but also to other items like volumes, networks.

**Comment by rohityadavcloud** [comment]
cc @nvazquez

**Comment by nvazquez** [comment]
Hi @utchoang, can you please check this issue?

**Comment by nvazquez** [comment]
Thanks for the fix @utchoang! @kohrar can you please test the PR #6462?

**Comment by kohrar** [comment]
Awesome! Thanks @utchoang for the quick fix. Using your PR, the issue is now fixed.
