### ISSUE TITLE
How To - Offsite Backup of VHD files 

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#6469]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

xcp-ng 7.4

##### OS / ENVIRONMENT

N/A

##### SUMMARY

This is not an issue per say, but a question. What is the best way to backup VHD files to an offsite backup for DR?  We are using xcp-ng 7.4 and Cloudstack 4.15. We do not have a second data center. I am thinking to map a NFS drive in Azure Blob storage and map that as a mount on a dedicated Linux server (on prem) and then use rsync to copy VHD files over. First time will take forever, but then incremental rsync should be quick. Will rsync work correctly for VHD backups like this? 

##### STEPS TO REPRODUCE

 

~~~
rsync files

~~~

##### EXPECTED RESULTS

~~~
in case of a disaster, the backed up version of rsync'd file can be used as a new VHD and create new VM based on that
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~

**Comment by nxsbi** [comment]
PS  - Note that the VM cannot be shutdown. So rsync will run while VM is running.

**Comment by nxsbi** [comment]
Still looking for advice here... Any suggestions are welcome

**Comment by rohityadavcloud** [comment]
Thanks for the questions @nxsbi I think it depends on the setup, you can use a backup solution (something like Veeam) or something bare-bone like scripts that say are run by cronjob that rsync your backups vhd files. Can you ask this on users or dev mailing list where you might get more reach to the community - https://cloudstack.apache.org/mailing-lists.html 

(closing as this is not an issue)
