### ISSUE TITLE
No input filed for IP address in UI when adding new Zone.

### ISSUE THREAD

**Issue by ccycv** [apache/cloudstack#6479]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### CONFIGURATION

~~~
NA
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu 20.04. 
~~~

##### STEPS TO REPRODUCE

~~~
Add new zone via UI
~~~

##### EXPECTED RESULTS

~~~
Allowing to add IP address with option to go back or forward
~~~

##### ACTUAL RESULTS

~~~
No input field available and no option to go back. It was tested multiple times via Chrome Browser.
~~~

![Screenshot 2022-06-21 093205](https://user-images.githubusercontent.com/23322009/174733484-c8c1c6fc-4432-4215-b6e1-e3ed78743e92.png)

**Comment by ccycv** [comment]
Update : Same issue in Firefox.

**Comment by utchoang** [comment]
@ccycv I tried with branch 4.17 but it works fine. Can you show me an image/video of the steps you performed the error? (If possible, show me the console in the browser's dev tool)

**Comment by slavkap** [comment]
@ccycv, is this an Advanced or Basic network configuration?

**Comment by ccycv** [comment]
> @ccycv, is this an Advanced or Basic network configuration?

I tested only in Advanced

**Comment by utchoang** [comment]
@ccycv can you show me the console in the browser's dev tool? (like this picture)
![image](https://user-images.githubusercontent.com/13766648/174742483-fef62a7c-6788-42b0-9c7d-b2e6f971fea6.png)

**Comment by ccycv** [comment]
> @ccycv can you show me the console in the browser's dev tool? (like this picture) ![image](https://github.com/assets/13766648/fef62a7c-6788-42b0-9c7d-b2e6f971fea6)

I do not see anything, only 1 failed load resources but this one was from the start.

![image](https://user-images.githubusercontent.com/23322009/174747692-7a2e010e-af0d-4fe7-bf56-0ec117f8139b.png)

**Comment by utchoang** [comment]
@ccycv According to your screenshot, I don't know why it's not showing, can you get the latest code from 4.17 and check if it has a different change?

**Comment by ccycv** [comment]
> @ccycv According to your screenshot, I don't know why it's not showing, can you get the latest code from 4.17 and check if it has a different change?

This is a fresh install with the packages from shapeblue. I also reinstalled and tested from a different PC/different network, same issue.

**Comment by utchoang** [comment]
@ccycv can you try the Cloudstack http://qa.cloudstack.cloud:8080/client/ with your browser and confirm again? I think this from the browser.

**Comment by ccycv** [comment]
> @ccycv can you try the Cloudstack http://qa.cloudstack.cloud:8080/client/ with your browser and confirm again? I think this from the browser.

![image](https://user-images.githubusercontent.com/23322009/174761792-f512d169-f2fe-4433-b4ee-9cab1ff00a55.png)

Not working even via your link. How can be this from my Browser? I tested in Chrome 102.0.5005.115 (Official Build) (64-bit), Firefox 101.0.1 (64-bit )and also used a different PC with Firefox 101.0.1 (64-bit) which in a different network..

I use advanced networking with Local Storage and at network I add a second physical network for Guest. ( with VMware), You should try in the same way to see if you can continue after you add the vCenter details.

**Comment by utchoang** [comment]
@ccycv This is on my chrome (same version as you). I think this may be due to vue-i18n's warning "Detected HTML". I'll create a PR to hidden it and you can test it and see if that works.
![image](https://user-images.githubusercontent.com/13766648/174763907-11086b62-81bf-4e2b-8c63-f5e555910ec8.png)

**Comment by utchoang** [comment]
@ccycv I have created a PR https://github.com/apache/cloudstack/pull/6480 containing the content I talk above, you can check it again with the URL: http://qa.cloudstack.cloud:8080/client/pr/6480 and confirm if it works?

**Comment by ccycv** [comment]
With this occasion I found a new bug, I also have upgraded setup to 4.16.1 from a previous version, where I already have the zone added. I wanted to try the same thing to see if I have the same issue, looks like here I have a different one.

When I insert the vSwitch name and hit ok, the vSwitch name is not saved.
![image](https://user-images.githubusercontent.com/23322009/174769230-63a5a905-10ea-4cc3-b618-c8d5fa399cc9.png)

If I edit again, show empty ( I can continue like this and no label is saved for Management and Public)

![image](https://user-images.githubusercontent.com/23322009/174769589-18b1fb9f-d8b2-4611-b9d9-d215c65431a2.png)

It is saved only for "Guest"

![image](https://user-images.githubusercontent.com/23322009/174769703-1cffb2af-2f06-41f9-aee4-cfd51af010ed.png)

![image](https://user-images.githubusercontent.com/23322009/174769769-a6a20514-820a-447d-b8c9-0bb75a5694e1.png)

If I add an additional Physical Network with traffic type "Guest" and try to continue  I get this error, because I do not have labels to the above traffic types where are not saved. Looks like the error is showing only in case you add a secondary physical network, otherwise is ignored.

![image](https://user-images.githubusercontent.com/23322009/174770390-a26887a9-0a75-4283-b288-448847c0e06c.png)





I also tested in Edge browser

**Comment by ccycv** [comment]
> @ccycv I have created a PR #6480 containing the content I talk above, you can check it again with the URL: http://qa.cloudstack.cloud:8080/client/pr/6480 and confirm if it works?

No, it is not working. I also tested in a incognito tab.

![image](https://user-images.githubusercontent.com/23322009/174772766-a6581d05-c16d-4680-9130-176af10418ac.png)

**Comment by ccycv** [comment]
> @ccycv I found the problem, and will add a fix now

Is there a way to fix on my side? I have installed from shapeblue repo.

**Comment by nvazquez** [comment]
Hi @ccycv I have tested the shapeblue packages but cannot hit this issue, tried on Chrome and Safari. Are you using the shapeblue ubuntu packages? Also, are you saying the vswitch issue is also present on 4.16.1?

**Comment by ccycv** [comment]
> Hi @ccycv I have tested the shapeblue packages but cannot hit this issue, tried on Chrome and Safari. Are you using the shapeblue ubuntu packages? Also, are you saying the vSwitch issue is also present on 4.16.1?

the above issue with "vSwitch labels" is in 4.16.1

I'm using the shapehost packages my setups:

4.16.1 is an old setup, where I have already few zone added from previous versions>
4.17.0 Is a new setup, no zones...

I think these issues occurs only when you create zones with VMware, in my case with advanced networking and local storage. ( 2x physical networks )

**Comment by nvazquez** [comment]
Thanks for the explanation @ccycv - I'm able to hit the issue only when selecting Vmware as hypervisor on the zone wizard, could not hit it previously as I was testing with KVM. I will also test PR #6480 to be included on 4.17.1.

For now can you consider using the API to create the zone as the first step and then continue adding elements through the UI? For example on cloudmonkey:
````
create zone name=<NAME> dns1=<DNS1> internaldns1=<DNS2> networktype=Advanced localstorageenabled=true
````

This will only create the DB entry for the zone and you can continue adding all the resources from the UI, after that you can enable the zone at the end

**Comment by ccycv** [comment]
> @ccycv I have fixed the errors you mentioned, can you test it again with http://qa.cloudstack.cloud:8080/client/pr/6480?

Now I can not continue from this step:

![image](https://user-images.githubusercontent.com/23322009/174953742-bd341f53-f43a-40fb-8dbf-486a08fb648b.png)

After I click on Next, nothing happens and I'm not able to click anymore, not even to edit or previous, already tested from 2 browsers.

**Comment by utchoang** [comment]
@ccycv can you try again to see does it working?

**Comment by ccycv** [comment]
> @ccycv can you try again to see does it working?

Now, I have labels added to all and I get this :

![174770390-a26887a9-0a75-4283-b288-448847c0e06c](https://user-images.githubusercontent.com/23322009/174987671-e9203aea-39ed-4408-9035-76e8960e11c6.png)


If I leave just 1 Physical network, I'm able to click next and finish the setup...

![image](https://user-images.githubusercontent.com/23322009/174987150-bd9abc27-57d6-440b-8926-f15814b546a5.png)

![image](https://user-images.githubusercontent.com/23322009/174987208-505e681e-7a68-4420-9909-617a35005b7a.png)

**Comment by ccycv** [comment]
A new UI issue:

I add the Cluster name, in my case, "MUB-001" after I hit ok I see the error and the Cluster name filed changed to host/dc/cluster.. 
![image](https://user-images.githubusercontent.com/23322009/174990826-70f48b42-63b2-492b-bdbb-e62c3d166a04.png)
 
 if I hit another OK, I see added again and again..

![image](https://user-images.githubusercontent.com/23322009/174991817-445ee111-df1f-4bf9-8881-a7ec549038df.png)

**Comment by utchoang** [comment]
@ccycv can you check it again?

**Comment by ccycv** [comment]
> @ccycv can you check it again?

Sorry, I forgot to mention that the above error is on my new setup 4.17

Did you asked me to check again for the error with labels or the last one from 4.17?

**Comment by utchoang** [comment]
@ccycv No, please check my fixed at PR https://github.com/apache/cloudstack/pull/6480

**Comment by ccycv** [comment]
> @ccycv No, please check my fixed at PR #6480 Each commit will be rebuilt, you can run the test using blueorangutan's build link

The issue is fixed. I can add 2 Physical networks and finish the setup.

**Comment by ccycv** [comment]
> This is on my setup 4.17
> 
> Update: Looks like is not a UI issue, I get the same error in cloudmonkey..
> 
> add cluster zoneid=f524ec82-6470-4ba1-b230-439c2c735f70 hypervisor=VMware clustertype=ExternalManaged podid=83dbcc41-ae70-436a-9bd9-c6dc4d977ede clustername="MUB-001" username="[administrator@vsphere.local](mailto:administrator@vsphere.local)" password="testaddcluster" url="http://vscsp06.test.host/"
> 
> Error: (HTTP 530, error code 9999) Index 0 out of bounds for length 0
> 
> A new UI issue:
> 
> I add the Cluster name, in my case, "MUB-001" after I hit ok I see the error and the Cluster name filed changed to host/dc/cluster.. ![image](https://user-images.githubusercontent.com/23322009/174990826-70f48b42-63b2-492b-bdbb-e62c3d166a04.png)
> 
> if I hit another OK, I see added again and again..
> 
> ![image](https://user-images.githubusercontent.com/23322009/174991817-445ee111-df1f-4bf9-8881-a7ec549038df.png)

I decided to stay with 4.16.1 for now,. In 4.16.1 I know the only way to add the cluster is via cloudmonkey and I must specify the full path in URL, otherwise I get the error "Unable to add the external cluster". (not sure if this is why I was not able to add in 4.17)

add cluster zoneid=b4444207-8bb1-4319-afc5-663e194deabf hypervisor=VMware clustertype=ExternalManaged podid=76da9fdd-e8ea-4959-b333-dc2c15506441 clustername="MUB-001" username="administrator@vsphere.local" password="testaddcluster" url="http://vscsp06.test.host/IN-001/MUB-001/"

**Comment by shwstppr** [comment]
@ccycv is it possible to share management server logs for the add cluster error on 4.17?

**Comment by ccycv** [comment]
> add cluster

I only have the error from 4.16.1. I reinstalled because I had to finish this setup.

"`clustername=MUB-001&clustertype=ExternalManaged&command=addClus
ter&hypervisor=VMware&podid=76da9fdd-e8ea-4959-b333-dc2c15506441&response=json&sessionkey=khGQCjV9v6BYC8AnRiXDgwY3k2A&url=http%3A%2F%2Fvscsp06.test.host%2F&username=administrator%40vsphere.l
ocal&zoneid=b4444207-8bb1-4319-afc5-663e194deabf
2022-06-22 10:50:52,399 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp515715487-14:ctx-e2db9f9f ctx-e72558d5) (logid:94f2861a) Discover host. dc: 1, pod: 1, cluster: 6, uri host: vscsp06.test.h
ost
2022-06-22 10:50:58,251 ERROR [c.c.h.v.VmwareServerDiscoverer] (qtp515715487-14:ctx-e2db9f9f ctx-e72558d5) (logid:94f2861a) Unable to find host or cluster based on url: /
com.cloud.exception.DiscoveryException: Unable to add the external cluster
        at org.apache.cloudstack.api.command.admin.cluster.AddClusterCmd.execute(AddClusterCmd.java:212)
2022-06-22 10:50:58,280 INFO  [c.c.a.ApiServer] (qtp515715487-14:ctx-e2db9f9f ctx-e72558d5) (logid:94f2861a) Unable to add the external cluster
`

I explained above how did I managed to add the cluster in 4.16.1.

**Comment by ccycv** [comment]
Update:

   Related to adding a cluster. I tried to add new zone to the same setup, ofc, I had the same issue via UI and then I tried to add via cloudmonkey but without success, here is why;
   
   `022-07-12 08:01:07,483 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Discover host. dc: 2, pod: 2, cluster: 36, uri host: vscsp06.test.host
2022-07-12 08:01:07,489 INFO  [c.c.n.NetworkModelImpl] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) More than one physical networks exist in zone id=2 with traffic type=Guest.
2022-07-12 08:01:07,507 INFO  [c.c.h.v.VmwareServerDiscoverer] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Detected private network label : vSwitch1,null,vmwaresvs
2022-07-12 08:01:07,507 DEBUG [c.c.h.v.r.VmwareContextFactory] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) initialize VmwareContext. url: https://vscsp06.test.host/sdk/vimService, username: administrator@vsphere.local, password: F****************
2022-07-12 08:01:07,654 INFO  [c.c.h.v.u.VmwareContext] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) New VmwareContext object, current outstanding count: 5
2022-07-12 08:01:07,683 INFO  [c.c.h.v.m.VmwareManagerImpl] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Preparing network on host com.cloud.hypervisor.vmware.util.VmwareContext@5ddfaaa2 for vSwitch1,null,vmwaresvs
2022-07-12 08:01:07,691 WARN  [c.c.h.v.VmwareServerDiscoverer] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Unable to connect to Vmware vSphere server. service address: vscsp06.test.host. java.lang.NumberFormatException: For input string: "null"
2022-07-12 08:01:07,691 INFO  [c.c.h.v.u.VmwareContext] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Disconnecting VMware session
2022-07-12 08:01:07,694 WARN  [c.c.r.ResourceManagerImpl] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Unable to find the server resources at http://vscsp06.test.host/HK-001/HKG-001/
2022-07-12 08:01:07,694 INFO  [c.c.u.e.CSExceptionErrorCode] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Could not find exception: com.cloud.exception.DiscoveryException in error code list for exceptions
2022-07-12 08:01:07,708 WARN  [o.a.c.a.c.a.c.AddClusterCmd] (qtp515715487-18:ctx-1158479d ctx-d5973879) (logid:d407e9a3) Exception:
com.cloud.exception.DiscoveryException: Unable to add the external cluster
        at com.cloud.resource.ResourceManagerImpl.discoverCluster(ResourceManagerImpl.java:585)
        at jdk.internal.reflect.GeneratedMethodAccessor785.invoke(Unknown Source)
`

"Detected private network label : vSwitch1,null,vmwaresvs"  here is the issue, not sure why, but the network labels where changed from vSwitch1 to "vSwitch1,null,vmwaresvs", after I corrected, I was able to add with success.

**Comment by mail2lawi** [comment]
Is it possible to re-open this? I'm facing the same issue on 4.17.2 running on Red Hat EL 8. I've tried multiple browsers with no success. The moment I click on 'Next' the UI freezes and I can't go forward or backwards. I have to restart the whole setup process again. 
So far I haven't managed to get past the page.

![add_zone](https://user-images.githubusercontent.com/29949457/214219495-0f8a95cc-5564-4e95-92c5-c79de4c85559.png)

**Comment by DaanHoogland** [comment]
@mail2lawi good mentioning it here, but let's stick to your new issue #7128 to handle this. No need to reopen this one.
