### ISSUE TITLE
Documentation needs instructions for adding a host using an SSH key

### ISSUE THREAD

**Issue by mrog** [apache/cloudstack#6498]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~
Adding a host
~~~

##### CLOUDSTACK VERSION

~~~
4.16
4.17
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

A feature was added in version 4.16 that allows the use of an SSH key instead of a password when adding a host.  See https://github.com/apache/cloudstack/pull/5684.  (Note that the SSH key path in the pull request description isn't quite correct.)

The instructions for adding a host don't explain how to use an SSH key.
https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
Here's a summary of the process that should be explained in the instructions.

- Copy the system key from /var/cloudstack/management/.ssh/id_rsa.pub on the management server, and add it to the /root/.ssh/authorized_keys file on the host.  (You may use ssh-copy-id for this step, if desired.)
- If you're creating a new zone, you must fill in the password field when providing information about the host.  Enter any string in the password field.  It doesn't have to be a real password.
- If you're adding a new host to an existing zone, choose the "System SSH Key" option.
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by mrog** [comment]
This is related to https://github.com/apache/cloudstack/issues/6499.

**Comment by rohityadavcloud** [comment]
cc @weizhouapache was this added?

**Comment by weizhouapache** [comment]
> cc @weizhouapache was this added?

@rohityadavcloud cloudstack doc is not updated. 

I see @harikrishna-patnala has self-assigned this. 
@harikrishna-patnala if you have any question, please let me know.

**Comment by harikrishna-patnala** [comment]
@weizhouapache "Add host" form is facilated to provide either using password or ssh keys but not the "Add Zone" Wizard. 

@utchoang has already created PR for this https://github.com/apache/cloudstack/pull/6525. I'll update the document accordingly.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack-documentation/pull/280
