### ISSUE TITLE
When creating a new zone, the host password field should not be required when an SSH key is being used

### ISSUE THREAD

**Issue by mrog** [apache/cloudstack#6499]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Zone creation
~~~

##### CLOUDSTACK VERSION

~~~
4.16
4.17
~~~

##### CONFIGURATION

Applies to both basic networking and advanced networking

##### OS / ENVIRONMENT

N/A

##### SUMMARY

A feature was added in version 4.16 that allows the use of an SSH key instead of a password when adding a host. See https://github.com/apache/cloudstack/pull/5684.

This is obvious when adding a host to an existing zone because there's a setting to use an SSH key instead of a password.  The UI doesn't show a setting like this when a new zone is being created.

##### STEPS TO REPRODUCE

~~~
Create a new zone, using either basic or advanced networking.
~~~

##### EXPECTED RESULTS

~~~
The UI should allow the user to select to use the system SSH key instead of a password, just it does when you're adding a new host to an existing zone.
~~~

##### ACTUAL RESULTS

~~~
When creating a new zone, the screen that asks for host information requires a password.  You can enter a garbage string in this field and it will use the SSH key, but that's not obvious to the user.
~~~

**Comment by mrog** [comment]
This is related to https://github.com/apache/cloudstack/issues/6498.

**Comment by rohityadavcloud** [comment]
cc @utchoang can you have a look at this, probably requires a new form?

**Comment by jdalais** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/21107174/177319500-2b4eeaf0-6c72-42a8-8d2f-47225c0bfbe6.png">

Am getting stuck on the above screen while trying to create zone; is that related?

**Comment by harikrishna-patnala** [comment]
I don't think it is related to this issue @jdalais, please check the developer tools for any errors or management server logs for anything suspicious.

**Comment by utchoang** [comment]
@jdalais Your issue is similar to https://github.com/apache/cloudstack/issues/6479 and has been fixed at PR https://github.com/apache/cloudstack/pull/6480

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6525
