### ISSUE TITLE
UI - Minor UI Issue - Failed "Resize volume" action is listed in notification list with a "Successfully resized volume" title

### ISSUE THREAD

**Issue by madodig** [apache/cloudstack#6501]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0
~~~

##### SUMMARY

If the instance disk size is fixed per the disk offering and one tries to resize the volume, the action fails. Pop-up notification shows the actual result and the cause of the failure, but in the notifications list it is titled as "Successfully resized volume".

##### STEPS TO REPRODUCE

[UI] Navigate to Storage / Volumes / Choose fixed size volume / Select "Resize volume" / Input the size, Submit
_OR_
[UI] Navigate to Storage / Volumes / Hover over fixed size volume's 3 dots / Select "Resize volume" / Input the size, Submit

##### EXPECTED RESULTS

The title of the notification message is consistent with the actual result and the pop-up notification.

##### ACTUAL RESULTS

When the action fails, notification pops up:

![image](https://user-images.githubusercontent.com/14966219/175834290-9c6b28c9-cec5-4d38-9aba-0c84c8d99a0a.png)

When the notifications list is chosen, the message is titled as "Successfully resized volume", although it has failed:

![image](https://user-images.githubusercontent.com/14966219/175834306-7ea12483-eeea-48ee-b1d7-7b6793d5c795.png)

**Comment by shwstppr** [comment]
Fixed with #6502 
@madodig please reopen if you still face the issue
