### ISSUE TITLE
package.sh error

### ISSUE THREAD

**Issue by jaspercloud** [apache/cloudstack#6515]
##### ISSUE TYPE

Bug Report

##### CLOUDSTACK VERSION

cloudstack-4.18.0.0

##### OS / ENVIRONMENT

export JAVA_HOME=/data/jdk-11.0.15
export M2=/data/apache-maven-3.0.5
export PATH=$JAVA_HOME/bin:$M2/bin:$PATH

##### SUMMARY

[root@dev-server packaging]# ./package.sh --distribution centos7
Packaging CloudStack...
version 4.18.0.0-SNAPSHOT
Preparing to package Apache CloudStack 4.18.0.0-SNAPSHOT
. preparing source tarball
. executing rpmbuild
RPMDIR /data/cloudstack/packaging/../dist/rpmbuild
error: Failed build dependencies:
        maven >= 3.0.0 is needed by cloudstack-4.18.0.0-SNAPSHOT.el7.x86_64
RPM Build Done

but, maven installed and set env.

**Comment by Pearl1594** [comment]
@jaspercloud can you verify the version of mvn:
1. check if mvn is installed, run: `which mvn`
```
$ which mvn
/usr/bin/mvn
```
2. check the version: `mvn -version`

```
$ mvn -version
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Listening for transport dt_socket at address: 8787
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.15, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-110-generic", arch: "amd64", family: "unix"
```

**Comment by rohityadavcloud** [comment]
@jaspercloud you can use these container images we use with BO/trillian to build packages - https://hub.docker.com/u/shapeblue or as Pearl suggested, ensure you've all the dependencies installed and using the right base distro to build pkgs (for ex. building rpm packages on Ubuntu may not work)

**Comment by weizhouapache** [comment]
@jaspercloud 
it looks you installed maven3 from a package (because the PATH is /data/apache-maven-3.0.5)
please install maven3 by `yum` and retry.

**Comment by nvazquez** [comment]
@jaspercloud I'm closing this issue as it seems resolved, in case the issue persists please reopen it
