### ISSUE TITLE
rdp debug

### ISSUE THREAD

**Issue by jaspercloud** [apache/cloudstack#6517]
(https://github.com/apache/cloudstack/blob/main/services/console-proxy/rdpconsole/src/test/doc/rdp.pfx)
windows10 is supported？

import windows10
CertUtil: -importPFX fail: 0x8007000d (WIN32: 13 ERROR_INVALID_DATA)

**Comment by rohityadavcloud** [comment]
Hi @jaspercloud sorry I couldn't understand the issue. If the question is whether CloudStack supports windows10 guest VMs - then yes.

**Comment by DaanHoogland** [comment]
@jaspercloud I am closing this issue. If you feel this is invalid please reopen or create a new one
