### ISSUE TITLE
CS 4.17 Zone icon does not render in Add Instance page (section 1)

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#6534]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

CentOS7 with 4.17
##### SUMMARY

I uploaded a new image for Zone - it shows correctly in most places. But on the Create VM page, it appears as blank with render size of 0:0 

##### STEPS TO REPRODUCE

~~~
Upload a PNG or JPG image for Zone from Infrastructure menu.
Go to Add Instance (as any user or admin) 

The icon next to the Zone appears as blank. 
Tested in Chrome and Firefox, also tested in Incognito mode

~~~

##### EXPECTED RESULTS

~~~
Icon Shows correctly

~~~

##### ACTUAL RESULTS

~~~
Icon does not appear next to the Zone in the section 1 (Select Deployment Infrastructure) in Add Instance 

![image](https://user-images.githubusercontent.com/71042351/177622790-d08016ad-dc15-49c7-8100-34781a16e6d1.png)

~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6543
