### ISSUE TITLE
Guest network permissions not working with projects

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6544]
When networks are shared with projects, in the project view (both UI and API) those networks aren't listed and therefore couldn't be used to deploy VM.

The feature isn't working as per https://docs.cloudstack.apache.org/en/4.17.0.0/adminguide/networking_and_traffic.html#guest-network-permissions

Please test and add support for allowing sharing of following types of networks with other accounts and projects:

- L2 networks not in Project
- Isolated networks not in Project
- Shared networks with scope is Account

Please add basic smoketests for this, both as admin and normal user accounts; across accounts and projects (where both the admin and normal user is an owner).

##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
API, Networks
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0
~~~

##### STEPS TO REPRODUCE

~~~

- creating a network "Net1", using offering "DefaultIsolatedNetworkOfferingWithSourceNatService"

- creating a project "Proj1"

- add permissions for network "Net1" to project "Proj1"

- switch to project "Proj1"

- (hit refresh/F5 as workaround for the empty resource list bug)

- list networks (empty)

- create a new instance, but networks is still empty

~~~

##### EXPECTED RESULTS

~~~
Networks should list the network permitted to the project (in project view and API)
~~~

##### ACTUAL RESULTS

~~~
The network wasn't list in the API or UI (even with the projectid=-1 param in API)
~~~

**Comment by shwstppr** [comment]
Fixed with [b62f59a](https://github.com/apache/cloudstack/commit/b62f59ac956f9d8188fe1678d6d20d0b56dd2c93)
