### ISSUE TITLE
Log files grow very large

### ISSUE THREAD

**Issue by mrog** [apache/cloudstack#6551]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Log files
~~~

##### CLOUDSTACK VERSION

~~~
4.14
4.16
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The CloudStack management and agent log files grow unbounded.  Under heavy use, they can quickly consume all available disk space.

##### STEPS TO REPRODUCE

~~~
- Install CloudStack and use it a lot.
- Examine contents of /var/log/cloudstack/.
~~~

##### EXPECTED RESULTS

~~~
The log files should be limited to a reasonable size.
~~~

##### ACTUAL RESULTS

~~~
The log files are large.
~~~

##### PROPOSED SOLUTIONS
Both of these changes would be helpful:
1. Explain in the installation guide how to modify the log4j settings to limit the log file sizes.  It would be useful to call out the XML file locations anyway to help users who want to make other logging changes.
2. In the log4j XML files (for both management and agent), change each TimeBasedRollingPolicy to a FixedWindowRollingPolicy with a MaxIndex value.  Then add a triggering policy with a MaxFileSize value.

**Comment by DaanHoogland** [comment]
@mrog are you making a PR for this?

**Comment by mrog** [comment]
I just made a PR.  https://github.com/apache/cloudstack/pull/6563

**Comment by harikrishna-patnala** [comment]
Closing this issue as the PR raised for this is also closed.
