### ISSUE TITLE
Install CloudStack From Source

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#6559]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
Source Code
##### CLOUDSTACK VERSION
4.17 main branch

##### CONFIGURATION
N/A otherwise

##### OS / ENVIRONMENT
Ubuntu 18.04
Apache Maven 3.6.0
Java version: 11.0.15,
nodejs v16.16.0
##### SUMMARY
I Compiled CloudStack From Source But At The Compile Stage i encountered  With an ERROR mentioned in the follow screenshot. Whats The Mean  cannot find symbol
##### STEPS TO REPRODUCE
mvn clean install -P systemvm,developer

![image](https://user-images.githubusercontent.com/104001728/179942018-e20cf990-9beb-4306-8d65-a741d659a3c9.png)

##### ACTUAL RESULTS
~~~
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cloud-plugin-storage-volume-storpool: Compilation failure: Compilation failure:
[ERROR] /root/cloudstack/plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolHelper.java:[188,21] error: cannot find symbol
[ERROR]   symbol:   method setConversionPattern(String)
[ERROR]   location: variable patternLayout of type PatternLayout
[ERROR] /root/cloudstack/plugins/storage/volume/storpool/src/main/java/org/apache/cloudstack/storage/datastore/util/StorPoolHelper.java:[193,23] error: incompatible types: RollingFileAppender cannot be converted to Appender
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cloud-plugin-storage-volume-storpool:
~~~

**Comment by rohityadavcloud** [comment]
Thanks for reporting @ahmadamirahmadi007 I rechecked to find my commit shared above had no effected, I had to cherry-pick them again on 4.17/main branches - I caused this while merging 4.17.0.1 to 4.17 branch somehow the commits got missing (had no effect on fwd-merging which is perhaps because I used the -X ours flag :( )
