### ISSUE TITLE
Create a zone wizard freeze after vCenter information screen

### ISSUE THREAD

**Issue by garavitov** [apache/cloudstack#6568]
ISSUE TYPE
Bug Report
COMPONENT NAME
UI

CLOUDSTACK VERSION
build 4.17.0.1

CONFIGURATION
Create Zone Wizard

OS / ENVIRONMENT
Ubuntu 20.04 LTS
Compute Nodes: Vmware Esxi

SUMMARY
Successfully installed the Apache CloudStack 4.17.0.1 from repository with no issues.
Can't configure a zone with VMware Hypervisor, the wizard freeze without error after the vCenter information screen with no errors and wit the only possibility is to click the close cross button.

STEPS TO REPRODUCE
Create a new zone wizard choosing Advanced Networkin and with VMware hypervisor.

![image](https://user-images.githubusercontent.com/87421502/180851097-cc6a9a4a-dfb8-4e82-8b10-4b7806fcfb43.png)

EXPECTED RESULTS
Complete Wizard

ACTUAL RESULTS
I am stuck on the wizard

**Comment by utchoang** [comment]
Same with issue https://github.com/apache/cloudstack/issues/6479 and has fixed in https://github.com/apache/cloudstack/pull/6480

**Comment by shwstppr** [comment]
@garavitov if possible you may test the latest nightly build from https://download.cloudstack.org/testing/nightly/. Issue should occur in that
