### ISSUE TITLE
Update localized Chinese language pack

### ISSUE THREAD

**Issue by luwei1970** [apache/cloudstack#6572]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
zh_CN.json
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### STEPS TO REPRODUCE

~~~
Direct coverage "/public/locales/zh_CN.json"
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@luwei1970 are you having the knowledge of Mandarin  to do this?

**Comment by shwstppr** [comment]
@luwei1970 can you please recreate your PR https://github.com/apache/cloudstack/pull/6573 using correct remote

**Comment by rohityadavcloud** [comment]
As others advised, @luwei1970 pl submit a new PR - we rely on contributors for language translations.

**Comment by rohityadavcloud** [comment]
@luwei1970 I looked at your old PR - looks like you're having issues with opening the Github PR, I've submitted your change on your behalf to assist you - can you review this https://github.com/apache/cloudstack/pull/6653
I'll close this issue instead
