### ISSUE TITLE
A model of readyforshutdown api 

### ISSUE THREAD

**Issue by Yashikaone** [apache/cloudstack#6611]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
To get the model api reviewed and rectify errors if any 
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@Yashikaone are you trying to propose a new feature here? It is not clear from the title, description.
