### ISSUE TITLE
Error while changing the compute offering on a vm

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#6627]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1 on CentOS 7
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When change the compute offering on a VM from the UI it fails with error "You cannot pass in a custom disk size to a non-custom disk offering.". This happens with every time you change the compute offering through the cloudstack web UI.
This seems to happens because it send via API the parameter "details[0].rootdisksize" which cause the issue.
A workaround we found is to write "null" in the disk size parameter when changing the compute offering

##### STEPS TO REPRODUCE

~~~
Change a compute offering through cloudstack web UI on a powered off vm
~~~

##### EXPECTED RESULTS

~~~
The compute offering is changed
~~~

##### ACTUAL RESULTS

~~~
error "You cannot pass in a custom disk size to a non-custom disk offering."
~~~

**Comment by shwstppr** [comment]
Fixed #6636 
Please re-open if the issue still persists

**Comment by vdombrovski** [comment]
The issue still persists it seems, can we reopen this please?

Referencing this file: https://github.com/shapeblue/cloudstack/blob/e00ced7a7d4d45d8bfa455599385238ebedf72f3/ui/src/views/compute/ScaleVM.vue

There seems to be a condition where **updateComputeOffering** triggers before **@update-disk-size="updateFieldValue"** which sets the rootdisksize once again. It would seem much better to handle the action on submit instead (for example, when rootdisksize=0)

Test that works:

- Scale -> Select offering on page 2 -> submit

Test that doesn't work:

- Scale -> Select offering on page 1 -> submit

Tested on Firefox (v.105) and Chrome (v.100)

**Comment by shwstppr** [comment]
@vdombrovski can you please share complete reproduction steps
