### ISSUE TITLE
Harvester HCI Compatibility 

### ISSUE THREAD

**Issue by RagingAdmin** [apache/cloudstack#6628]
https://harvesterhci.io/

This project is based on openSUSE Leap 15, which is a compatible hyoervisor with KVM.

Can Harvester HCI be compatible with CloudStack ?

**Comment by DaanHoogland** [comment]
It can be tried to be added, there will have to be some scripting done for it to work, probably, @RagingAdmin .

**Comment by rohityadavcloud** [comment]
@RagingAdmin it depends, if they're using libvirtd etc then it should be compatible. CloudStack already supports openSUSE Leap 15 as KVM host. Why don't you give it a spin and maybe report on users@ (and/or here)?

**Comment by rohityadavcloud** [comment]
Thanks for the question, as we've answered the question I'm closing this.
