### ISSUE TITLE
Add a permission for force stopping a vm

### ISSUE THREAD

**Issue by BartJM** [apache/cloudstack#6629]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
N/A
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We would like the ability to prevent users to use `forced=true` when calling the `stopVirtualMachine` API.

This is wanted to prevent a scenario where a vm is running twice due to an issued forced stop by a user. This occurs when a force stop is sent to a vm, but the agent cannot handle the stop command (disabled/alert/other). The force stop will just administratively set the vm down, while it is still running. when starting the vm again CS will start on another host since the original is in disabled/alert state.

##### STEPS TO REPRODUCE

- Start a vm on a host.
- Disable cloudstack-agent on the host
- Force stop the vm
- Start the vm
 
~~~

~~~

**Comment by rohityadavcloud** [comment]
Sounds like yet another global setting to tune the behaviour and something in the UI to detect this.

**Comment by Rubueno** [comment]
Thanks @abh1sar and @rohityadavcloud!
