### ISSUE TITLE
ui: tags related options not visible for public IP and maybe some other resources

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#6649]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

UI for adding, removing resource tags is not visible in the public IP view.
This could be an issue with some other resources as well which support resource tags
![Screenshot from 2022-08-17 13-34-07](https://user-images.githubusercontent.com/153340/185067468-7a62f49c-7f50-4071-a460-0e6bcc89d0cf.png)

##### STEPS TO REPRODUCE

~~~
1. Log in to UI
2. Go to details of a public IP
~~~

##### EXPECTED RESULTS

~~~
Tags related UI should be visible
~~~

##### ACTUAL RESULTS

~~~
Tags related UI is not visible
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6650
