### ISSUE TITLE
Compile from source code error

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#6669]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
:cloud-apidoc
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1
~~~

##### OS / ENVIRONMENT

Oracle Linux 8
Apache Maven 3.5.4 
java openjdk 11.0.16

##### SUMMARY

I build CloudStack from sources. And I got described errors. I have to use cloudstack 4.16.0.0 or 4.16.1.0 for my own reason

##### STEPS TO REPRODUCE

~~~
mvn -Psystemvm,developer clean package -rf :cloud-apidoc
~~~

##### EXPECTED RESULTS

~~~
Complited build
~~~

##### ACTUAL RESULTS

~~~
Error while compiling

[ERROR] Failed to execute goal on project cloud-apidoc: Could not resolve dependencies for project org.apache.cloudstack:cloud-apidoc:pom:4.16.1.0: The following artifacts could not be resolved: org.apache.cloudstack:cloud-server:jar:4.16.1.0, org.apache.cloudstack:cloud-client-ui:pom:4.16.1.0: Failure to find org.apache.cloudstack:cloud-server:jar:4.16.1.0 in https://repo.jenkins-ci.org/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of repo.jenkins-ci.org.releases has elapsed or updates are forced -> [Help 1]

~~~

**Comment by rohityadavcloud** [comment]
@top-secrett what's the output of:

```
$ python --version
$ python3 --version
```

If `python` is missing pl add an alias or symlink to python3.

And have you setup the build dependencies per https://github.com/shapeblue/hackerbook/blob/main/2-dev.md#setting-up-development-environment ?

**Comment by top-secrett** [comment]
@rohityadavcloud I did it
[root@cloudstack-4.16.1.0]# python --version
Python 3.6.8
[root@oracle cloudstack-4.16.1.0]# python3 --version
Python 3.6.8

**Comment by rohityadavcloud** [comment]
Are you able to build 4.17 or main branch @top-secrett? The error suggests something to do with dns resolution or repo access.

**Comment by top-secrett** [comment]
It seems like a problem with dependeses on RHEL8 based distros.
I biult it from source on CentOS7.
Thank you for help
