### ISSUE TITLE
Work with MySQL group replication

### ISSUE THREAD

**Issue by itsmdev** [apache/cloudstack#6670]
Error log:
```
2022-08-24 02:14:35,802 ERROR [c.c.u.d.Merovingian2] (main:null) (logid:) cleanupForServer:Exception:The table does not comply with the requirements by an external plugin.
2022-08-24 02:14:35,909 ERROR [c.c.u.d.Merovingian2] (main:null) (logid:) cleanupForServer:Exception:cleanupForServer:Exception:The table does not comply with the requirements by an external plugin.
```
seem caused by `op_lock` and `op_nwgrp_work` use `MEMORY` engine:

```
| def           | cloud              | op_lock                                              | MEMORY             |
| def           | cloud              | op_nwgrp_work                                        | MEMORY             |
+---------------+--------------------+------------------------------------------------------+--------------------+
```

any solution? 

in `./engine/schema/src/main/resources/META-INF/db/schema-490to4910.sql`:, engine will be set to innodb：
```
ALTER TABLE cloud.op_nwgrp_work ENGINE=INNODB;
```

So, can I use InnoDB from the start？

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

4.16.1.0

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rohityadavcloud** [comment]
@itsmdev thanks for reporting, I think they all should be INNODB unless there is any reason not to. Can you check latest main or 4.17 branch incase this is already fixed those cc @nvazquez if you remember we fixed them?

**Comment by itsmdev** [comment]
@rohityadavcloud 
https://github.com/apache/cloudstack/blob/c58118148e1a579efc1d59dba27f54463222c843/setup/db/create-schema.sql#L401
https://github.com/apache/cloudstack/blob/c58118148e1a579efc1d59dba27f54463222c843/setup/db/create-schema.sql#L1796

**Comment by DaanHoogland** [comment]
according to https://github.com/apache/cloudstack/blob/4.17/engine/schema/src/main/resources/META-INF/db/schema-490to4910.sql#L30-L31 this has long been changed and will be automatically be updated on every installation after 4.9

**Comment by DaanHoogland** [comment]
@itsmdev I am closing this issue. If you feel this is invalid please reopen or create a new one

**Comment by Revellski** [comment]
This can be replicated on new install, when bootstrapping with `cloudstack-setup-databases`.  I guess the script uses an older schema which is expected to be upgraded during the first run. However, CloudStack fails to start due to the error above.

**Comment by Demonium** [comment]
Hello,
I just had the same issue on version 4.20 after a fresh installation...
I have executed the lines below to correct the issue
`ALTER TABLE cloud.op_lock ENGINE=INNODB;
ALTER TABLE cloud.op_nwgrp_work ENGINE=INNODB;`

**Comment by DaanHoogland** [comment]
so there are two issues here that both would not lead to problems in isolation:
1. the default table type (ENGINE) should be set to innodb. this can be documented as a prerequisite setup for mysql
2. the addition of new tables shouls always speficify an engine. this is hard to enforce but a retroaction on existing tables can be done (i.e. a “bug”fix)
I suggest we do both. What do you think @weizhouapache @rohityadavcloud @vishesh92 others?

**Comment by Demonium** [comment]
Hello,
I have setup again cloudstack on a fresh database installation without setup innodb cluster and it's work perfectly at first time I don't know if it's relevant for you ?

**Comment by DaanHoogland** [comment]
thanks @Demonium , this is clearly an edge case. I am not sure about all the right conditions yet. One thing is the cluster bit, that seems to play a role. You are saying you are running a regular active/passive replication scheme?

**Comment by Demonium** [comment]
Hello @DaanHoogland ,
I'm not an expert just discovering the whole stuff but follow this tutorial https://severalnines.com/blog/mysql-innodb-cluster-80-complete-deployment-walk-through-part-one/
I think it's active but not sure....

**Comment by DaanHoogland** [comment]
closing this as it has a mix of different questions. please open a new discussion or , if you have reproduction schemes, a new issue per item.
