### ISSUE TITLE
Mulitple Bugs in GUI for newly introduced features in 4.17.0 / 4.17.0.1 after upgrading from 4.16.1

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#6677]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management GUI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### OS / ENVIRONMENT

Magement Server running Ubuntu 20.04
Browsers used: Firefox 103.2 / Chrome 104

##### SUMMARY

Varius GUI Bugs after upgradeing Managementserver from 4.16.1.
Findings till now:

- Wizzard for creating compute offerings

<img width="436" alt="offering_gui" src="https://user-images.githubusercontent.com/79725167/187182861-38da2ebf-c517-477c-be96-98074489a1d7.png">

- GUI "Live migration" 
<img width="227" alt="label_livemigration" src="https://user-images.githubusercontent.com/79725167/187183022-ec04b8b3-d115-4dd7-8869-87799aea2427.png">

-   Infrastucture - Summary
<img width="437" alt="label_menue" src="https://user-images.githubusercontent.com/79725167/187183137-d39ccba1-7733-4eff-ba2d-979b948babca.png">

-  New Menue "DB usage metrics"
<img width="1123" alt="label3" src="https://user-images.githubusercontent.com/79725167/187183503-6a77495b-1054-4eba-a307-ffbdbe45b4c3.png">

- Infrastructure "Virtual Routers" 
<img width="457" alt="label2" src="https://user-images.githubusercontent.com/79725167/187183333-ced7c1d2-96d2-454e-bc9f-9150ee512c3c.png">

##### STEPS TO REPRODUCE

~~~
Upgrade 4.16.1. to 4.17.0.1
~~~

##### EXPECTED RESULTS

~~~
GUI / Labels correctly displayed
~~~

##### ACTUAL RESULTS

~~~
See pictures
~~~

**Comment by shwstppr** [comment]
@Hudratronium these missing label texts seem to be related to the browser cache. I tested the upgrade and was facing the same but it goes away once you empty cache and hard reload. You may also test the same with an incognito tab

Before:
![Screenshot from 2022-08-30 11-41-15](https://user-images.githubusercontent.com/153340/187364542-fc68c1b8-bd55-4d94-87d0-bd1039d45a3e.png)

After:
![Screenshot from 2022-08-30 11-47-45](https://user-images.githubusercontent.com/153340/187364338-e35b2f4c-fd1b-47cf-834f-648f0e4f4888.png)


This [link](https://nira.com/chrome-clear-cache/#:~:text=Here's%20how%20to%20clear%20the,Windows%2C%20Linux%2C%20and%20Chromebooks.&text=Click%20Empty%20Cache%20and%20Hard,%2C%20and%20you're%20done.) helped me clearing cache on chrome

**Comment by Hudratronium** [comment]
Thank you for your help - that helped me a lot!
