### ISSUE TITLE
No permission to migrate volume, only root admin can migrate a volume

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#6701]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
ALL
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When a non-root user try to change the compute offering on a VM he faces the error: " No permission to migrate volume, only root admin can migrate a volume ".

##### STEPS TO REPRODUCE

~~~
Change the compute offering of a powered-off VM
~~~

##### EXPECTED RESULTS

~~~
The compute offering is changed.
~~~

##### ACTUAL RESULTS

~~~
Non-root user faces error " No permission to migrate volume, only root admin can migrate a volume "
~~~

**Comment by shwstppr** [comment]
@cdfgallo Thanks for reporting the issue.
The behaviour here needs to be discussed. My view, https://github.com/apache/cloudstack/pull/6704#issuecomment-1238056686
cc @harikrishna-patnala @NuxRo @alexandremattioli

**Comment by harikrishna-patnala** [comment]
I agree with your comment @shwstppr, usually migrate operations are not given to users, if at all user hits these kind of issues, they may need to contact admin. Others please chime in.

**Comment by cdfgallo** [comment]
I agree on the migration part, but a normal user should be allowed to change the compute offering on a VM if this doesn't lead to a volume migration.

**Comment by aarushisoni** [comment]
Hi my name is Aarushi Soni . I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.

**Comment by rohityadavcloud** [comment]
@cdfgallo does it work for you if you try changing the offering of the VM but untick the automatic migration option that says "Auto migrate volume to another storage pool if required":

<img width="1173" alt="Screenshot 2022-10-07 at 2 18 14 PM" src="https://user-images.githubusercontent.com/95203/194513111-d1e8c067-2d5d-4b45-a2a5-d65c71e86ebb.png">

**Comment by cdfgallo** [comment]
@rohityadavcloud nope, unfortunately this does not work too. Still receive same error from the UI.

**Comment by mik-allen** [comment]
This is a major bug for our company and is preventing us from upgrading to 4.17.1. If we were to upgrade from 4.16.1, we would be inundated with customer support requests to do what should be a basic operation- increase or decrease CPU/RAM.

@rohityadavcloud, I can also confirm that unticking 'auto migrate' does not help. Logging in as a root admin is the only way to scale successfully in our lab environment.

**Comment by rohityadavcloud** [comment]
Thanks @mik-allen for reporting, I'm able to consistently reproduce this as normal user account in a KVM env (I think this is hypervisor agnostic):

1. Deploy a VM using a small offering and stop it.
 
2. Scale the VM with the option to auto-migrate:
<img width="1116" alt="Screenshot 2022-10-11 at 3 45 10 PM" src="https://user-images.githubusercontent.com/95203/195064697-4aab16ea-46b6-44b1-bc97-c863f396036c.png">

3. The operation fails with permission to migrate issue:
<img width="1614" alt="Screenshot 2022-10-11 at 3 45 24 PM" src="https://user-images.githubusercontent.com/95203/195064876-d84c9df8-4679-4a2d-a496-f01313ce9bad.png">

4. This happens even when the auto-migration option in ScaleVM is selected.

The auto-migrate feature was introduced in case there's a service offering that has storage tags and offers something specific to the offering.

**Comment by soreana** [comment]
@rohityadavcloud @weizhouapache @shwstppr @harikrishna-patnala 
Any update on this? Is it in progress?
I'm willing to contribute if you need help.

**Comment by DaanHoogland** [comment]
@soreana are you working on this?

**Comment by soreana** [comment]
@DaanHoogland Not yet. I was waiting for the @shwstppr @harikrishna-patnala reply.

**Comment by DaanHoogland** [comment]
I know @harikrishna-patnala is busy on https://github.com/apache/cloudstack/pull/6704 so I think he is in the lead right now.

**Comment by soreana** [comment]
@DaanHoogland Cool 👍 
I will keep an eye on the https://github.com/apache/cloudstack/pull/6704 then :)

**Comment by rohityadavcloud** [comment]
any update on this @shwstppr @harikrishna-patnala @DaanHoogland ?

**Comment by vladimirpetrov** [comment]
LGTM based on manual testing.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6704
