### ISSUE TITLE
Router displaying error "Failed to start Conntrack Deamon"

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#6702]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### CONFIGURATION

- Hypervisor: KVM
- Advanced networking in use
- The VR is part of a HA-Setup for  a redundant VPC with following services availeable (custome service offering for VPC)
  - SourceNat
  - StaticNat
  - VPN
  - NetworkACL
  - PortForwarding

##### OS / ENVIRONMENT

N/A

##### SUMMARY

After upgradeing to CS 4.16.1 to 4.17.0.1 and patching / rebooting the virtual Routers, following message is displayed: 

<img width="642" alt="Anmerkung 2022-09-05 000526" src="https://user-images.githubusercontent.com/79725167/188488791-059d837f-976d-42a7-98cd-abbc728c2b6d.png">

The whole process as well the start of patching / rebooting was done via the WebGUI.
Followed the offical Upgrade Guide http://docs.cloudstack.apache.org/en/latest/upgrading/upgrade/upgrade-4.16.html

##### STEPS TO REPRODUCE

~~~
Upgrade to from CS 4.16.1 to 4.17.0.1, patch / reboot existing VR via WebGUI of the Mangement Server
~~~

##### EXPECTED RESULTS

~~~
No errors shown on VR after finished reboot
~~~

##### ACTUAL RESULTS

~~~
Errors shown on the GUI of the Virtual Router, that the Conntrack Daemon failed to start
~~~

**Comment by DaanHoogland** [comment]
@Hudratronium upgraded from where (via what) to 4.17.0.1?

**Comment by Hudratronium** [comment]
@DaanHoogland 
Sorry i missed to click 'save'.... instead i closed the window. I updated the inital comment. If further information are needed please let me know.

**Comment by DaanHoogland** [comment]
@Hudratronium I will replay this in a lab environment. Any extra's that might be particular to the failure? Hypervisor type, network type? (assuming kvm/isolated for now)

**Comment by Hudratronium** [comment]
@DaanHoogland 
Thanks for your effort - sometimes it is a bit hard to get a grip on what infos might be needed for this things.... sorry for that.
Regarding your questions:

- Hypervisor: KVM
- Advanced networking in use
- The VR is part of a HA-Setup for  a redundant VPC with following services availeable (custome service offering for VPC)
  - SourceNat
  - StaticNat
  - VPN
  - NetworkACL
  - PortForwarding

**Comment by DaanHoogland** [comment]
@Hudratronium I created a 4.16.1 env and a VPC with an offering of your specs. The message you descibe shows immediatly without any upgrade. The upgrade probably has nothing to do with the messages you see.

Is there any hampered functionality in the router?

**Comment by Hudratronium** [comment]
@DaanHoogland
Interesting, will have to clearify that interally since when this is present.... 

Nevertheless currently we haven't experienced any hampered functionality .
Healthchecks are running fine, no alerts or things we have seen in the logs.

**Comment by aarushisoni** [comment]
I want to contribute to this issue . Is this issue still open ? I am first time contributor . Please guide me through this process.

**Comment by aarushisoni** [comment]
I have a doubt regarding this issue . I am doing it for my college open
source project . I studies this link material that you provided can you
please guide me how to setup environment to solve this issue .

**Comment by rohityadavcloud** [comment]
Hi @aarushisoni unfortunately we can't offer a tutorial or mentoring programme for you. You can learn on your own [0] using the hackerbook self-study material which has chapters on how to get started with CloudStack and setup build/test environment; join the dev mailing list [1] and contribute to the project [2][3]. It may be worth picking one specific task, rather a large group to issues/tasks to begin with. I would advise to start to learn CloudStack as a user first before contributing as a developer.

[0] https://github.com/shapeblue/hackerbook
[1] https://cloudstack.apache.org/mailing-lists.html
[2] https://github.com/apache/cloudstack/blob/main/CONTRIBUTING.md
[3] https://cloudstack.apache.org/developers.html

**Comment by rohityadavcloud** [comment]
@Hudratronium this could be a non-issue and ignorable, do you have redundant routers on your VPC?

**Comment by Hudratronium** [comment]
@rohityadavcloud 
Yes, it's  redundant setup. Both routers displaying the same message.

**Comment by aarushisoni** [comment]
Hi is there any slack group for discussion?
I have windows is it compulsory to have ubuntu?

**Comment by rohityadavcloud** [comment]
@Hudratronium if those are redundant VPC VRs - it's expected and ignorable message if you don't have any VPC tiers that are implemented (i.e. VMs on the tiers or no tiers added).

**Comment by Hudratronium** [comment]
@rohityadavcloud 
The VPC has several Tiers as well as a bunch of VMs running 'inside'.
