### ISSUE TITLE
UI fix Theme text color not bind navTextColorPick

### ISSUE THREAD

**Issue by hooklee2000** [apache/cloudstack#6720]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME
UI Theme
~~~

~~~

##### CLOUDSTACK VERSION
4.17.0.0 and 4.17 branch

~~~

~~~

##### CONFIGURATION
UI

##### OS / ENVIRONMENT
CentOS 8

##### SUMMARY
UI choose Theme , text color not bind correctly to navTextColorPick.
click "reset to default" button, will display last choosed color.

### SOLUTION
~~~
vi ui/src/components/view/Setting.vue
 :73
change navBgColorPick to navTextColorPick
:257
add 
this.uiSettings = {}
~~~
![图片](https://user-images.githubusercontent.com/52850777/189287091-a73ef4a0-0f98-4517-b77c-e91f77ef62bc.png)

**Comment by shwstppr** [comment]
Fixed with #6271
