### ISSUE TITLE
OVA downloads into an error

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#6736]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
OVA download 
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1
~~~

##### CONFIGURATION

VMWare 6.7 
OVA: PI-VA-3.10.0.0.205.ova
https://software.cisco.com/download/home/286329246/type/284272932/release/3.10.0

##### SUMMARY

When downloading the OVA appliance results in error: "did not find a guest os with type rhel7_64guest" 

##### STEPS TO REPRODUCE

~~~
1. Register the template 
~~~

##### EXPECTED RESULTS

~~~
Register and upload the OVA should work fine
~~~
**Notes for testing: Please make sure to check both register and upload.**

**Comment by nvazquez** [comment]
@borisstoyanov is this template registered as deploy-as-is?

**Comment by DaanHoogland** [comment]
@borisstoyanov @nvazquez I created a fix which will allow the upload and registration.
now the following problem occurs:
![image](https://user-images.githubusercontent.com/2486961/191750022-763802fe-4862-4f48-b005-b5a0272f979d.png)
the compute offering is expected but will not give any selection posibilities.
is this some how expected, or can it be a problem with the template?

**Comment by DaanHoogland** [comment]
also the license agreement section is not containing a license agreement:
![image](https://user-images.githubusercontent.com/2486961/191750579-1cd607e9-12ef-4a79-b2fd-bf14a2832b5c.png)

**Comment by borisstoyanov** [comment]
I think you don't have a matching offering @DaanHoogland, check out the specs of the OVA at CISCO page, I think it requires some massive RAM etc..

**Comment by DaanHoogland** [comment]
yes, but than I would expect that as a message, couldn´t I? I'll adjust the test and rerun but doubt this is the only issue.

**Comment by DaanHoogland** [comment]
ok, @borisstoyanov I cannot reproduce the weir state above anymore, the template is in deployable state with the PR #6758 can you test it?
