### ISSUE TITLE
VM deletion can fail on volume access revocation if VM's last host is removed

### ISSUE THREAD

**Issue by mlsorensen** [apache/cloudstack#6739]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API, Storage
~~~

##### CLOUDSTACK VERSION
~~~
main
~~~

##### CONFIGURATION
PowerFlex, Datera storage

##### SUMMARY
If a VM is stopped, then the last host it was running on is removed from cloudstack, the VM can fail to delete. This is because deletion attempts to revoke host access to the VM's volumes and various storage plugins will throw errors if the provided host is null.

Looking through the storage plugin implementations, it looks like this would affect Datera and PowerFlex storage types only.

Generally this seems to be due to passing a null host object to the storage provider's revokeAccess() method. Looked into a holistic fix but there are several places where revokeAccess() can be invoked or could be invoked in the future. Additionally, a storage plugin could choose to handle a null host as a "revoke all" command.

##### STEPS TO REPRODUCE
1. Create VM with root on Datera or PowerFlex storage 
2. Start/stop the VM
3. remove the host the VM ran on from CloudStack
4. attempt to delete the VM

##### EXPECTED RESULTS
VM should be deleted

##### ACTUAL RESULTS
Error is thrown during deletion

**Comment by sharmadhiraj86** [comment]
Hey, I want to work on this issue, can you assign this issue to me please? @rohityadavcloud @mlsorensen

**Comment by mlsorensen** [comment]
@sharmadhiraj86 that would be great. I don't have access to assign.

Looking at the SolidFire implementation, they seem to not be affected.  I have a PowerFlex fix already that I've tested.

I do think it might be worth looking at everywhere that we call revokeAccess and figure out if we really do want to even call revoke if the host is null, but at a minimum making sure the managed storage plugins are handling it seems necessary to avoid further issues long term.

**Comment by rohityadavcloud** [comment]
Closing this as main reported issue fir powerflex has been fixed.
