### ISSUE TITLE
LDAP mapping leftover when subdomain is deleted

### ISSUE THREAD

**Issue by artem-sidorenko** [apache/cloudstack#6752]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
LDAP
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.1
~~~

##### SUMMARY

LDAP mapping is left in the DB when subdomain is removed

##### STEPS TO REPRODUCE

- Setup LDAP
- Create a subdomain
- Link some group or OU to the subdomain
- Remove subdomain
- check the table ldap_trust_map - mapping is still there

Similar to the https://github.com/apache/cloudstack/pull/4899

##### EXPECTED RESULTS

~~~
MariaDB [cloud]> select * from ldap_trust_map;
Empty set (0.01 sec)
~~~

##### ACTUAL RESULTS

~~~
MariaDB [cloud]> select * from ldap_trust_map;
+----+-----------+------+---------------------------------------------------+--------------+------------+
| id | domain_id | type | name                                              | account_type | account_id |
+----+-----------+------+---------------------------------------------------+--------------+------------+
|  6 |         6 | OU   | cn=users,cn=accounts,dc=test,dc=com |            0 |          0 |
+----+-----------+------+---------------------------------------------------+--------------+------------+
1 row in set (0.00 sec)
~~~

**Comment by xuanyuanaosheng** [comment]
I also meet this issue, Please help to handle this.

**Comment by DaanHoogland** [comment]
@artem-sidorenko @xuanyuanaosheng , can you add the same trust_map/configuration again?

**Comment by DaanHoogland** [comment]
@artem-sidorenko can you try #7915 ? it should fix your problem.
closing this provisionally, feel free to re-open
