### ISSUE TITLE
Root admin not allowed to deploy in a VPC belonging to account in a non-ROOT domain

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6754]
Root admin not allowed to deploy in a VPC belonging to account in a non-ROOT domain.

Steps to reproduce:
- Create a domain D1 under ROOT domain
- Create an account T1 in D1
- Login as T1 user, create a VPC, a VPC tier, and deploy a VM on it
- Logout, Login as a root admin
- Deploy a VM in the VPC tier (it won't show the tier in UI, nor allow in API) (however, root admin was found to be able to create a new VPC tier in the VPC owned by T1 user)

Error seen in API:

> deploy virtualmachine  serviceofferingid=1bcaaebd-a6c6-4363-949e-77d00502992f   templateid=711ee0f1-297f-41fe-9610-e2c93c00c0d2  zoneid=f992179a-4f24-4d22-9033-685b5af67214 networkids=b518afc5-0c2a-4a0b-a225-fcdee0b40f11  name=test123
🙈 Error: (HTTP 531, error code 4365) Unable to use network with id= b518afc5-0c2a-4a0b-a225-fcdee0b40f11, permission denied

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.16, 4.17
~~~

##### CONFIGURATION

Advance zone, KVM

**Comment by DaanHoogland** [comment]
@rohityadavcloud can you clarify:
Is the root admin able to deploy in the tier they created and not in the other?
Also (maybe as a point of discussion) do we feel that ROOT/admin should always be allowed to deploy (or do anything) in a subdomain? This one is a bit of a security discussion I´d say.

**Comment by rohityadavcloud** [comment]
Root admin in my test wasn't able to deploy VM in any of the tiers, even the (new vpc) tiers created by the root-admin for someone else's account. @DaanHoogland it may be worth checking this behaviour against an older version (4.11, 4.9 etc?) to establish if this is a historic limitation or a regression in newer releases.

**Comment by DaanHoogland** [comment]
@rohityadavcloud , I finally got around testing this on 4.14 and admin is not allowed to deploy on the user's VPC. I also created a second root admin account which also couldn´t deploy to the users vpc.

Do you want to convert this to a feature request?

**Comment by rohityadavcloud** [comment]
Thanks @DaanHoogland - sounds like this has been a historic limitation then and not a bug. Adding enhancement label to the issue. I think if it's a quick fix then let's do it, as while admin may not be (now) allowed to deploy VM, they're otherwise allowed to do many more operations (incl. acl configuration, stop/start/destroy VMs etc.)
