### ISSUE TITLE
VR： how can i recreate a new virtual route in cloudstack 4.11.2

### ISSUE THREAD

**Issue by yuanbosoft** [apache/cloudstack#6761]
##### ISSUE TYPE

 * Bug Report
 * Other

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

After drop virtual route ,all vms can not start , i regret!!!
 how can i recreate a new virtual route in cloudstack 4.11.2, basic network.

##### OS / ENVIRONMENT

centos7.4

##### STEPS TO REPRODUCE

~~~
After drop virtual route ,all vms can not start , i regret!!!
 how can i recreate a new virtual route in cloudstack 4.11.2
~~~

##### EXPECTED RESULTS

~~~
add a new vitual route 
~~~

##### ACTUAL RESULTS

~~~
![vr](https://user-images.githubusercontent.com/7006125/192091023-451c4ac7-3666-49ff-9f98-3c00cb8a51e5.png)


~~~

**Comment by weizhouapache** [comment]
@yuanbosoft 
you can restart the network or vpc with cleanup
it will create new virtual routers

**Comment by yuanbosoft** [comment]
when I restart the the defaultGuestNetwork:
1.the cloudstack web page will pop up: 
Resource [DataCenter:1] is unreachable: Can't find all necessary running routers!

2.The cloudstact-management log with pop up:
udstack.api.command.user.network.RestartNetworkCmd, cmdInfo: {"makeredundant":"false","cleanup":"true","response":"json","ctxUserId":"2","httpmethod":"GET","ctxStartEventId":"1609","id":"becd3a84-349d-4f67-a331-90641ee173a2","ctxDetails":"{\"interface com.cloud.network.Network\":\"becd3a84-349d-4f67-a331-90641ee173a2\"}","ctxAccountId":"2","uuid":"becd3a84-349d-4f67-a331-90641ee173a2","cmdEventType":"NETWORK.RESTART","_":"1664024563759"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 229335791363470, completeMsid: null, lastUpdated: null, lastPolled: null, created: null}
2022-09-24 21:08:25,498 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-15:ctx-dd738e64 job-2121 ctx-dab784b8) (logid:33626c0e) Restarting network 204...
2022-09-24 21:08:25,499 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-15:ctx-dd738e64 job-2121 ctx-dab784b8) (logid:33626c0e) Performing rolling restart of routers of network Ntwk[204|Guest|7]
2022-09-24 21:08:25,503 DEBUG [o.a.c.e.o.NetworkOrchestrator] (API-Job-Executor-15:ctx-dd738e64 job-2121 ctx-dab784b8) (logid:33626c0e) Asking VirtualRouter to implemenet Ntwk[204|Guest|7]
2022-09-24 21:08:25,508 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-15:ctx-dd738e64 job-2121) (logid:33626c0e) Unexpected exception while executing org.apache.cloudstack.api.command.user.network.RestartNetworkCmd
com.cloud.exception.ResourceUnavailableException: Resource [DataCenter:1] is unreachable: Can't find all necessary running routers!
        at com.cloud.network.element.VirtualRouterElement.implement(VirtualRouterElement.java:243)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.implementNetworkElements(NetworkOrchestrator.java:1203)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.rollingRestartRouters(NetworkOrchestrator.java:2948)
        at org.apache.cloudstack.engine.orchestration.NetworkOrchestrator.restartNetwork(NetworkOrchestrator.java:2853)
        at com.cloud.network.NetworkServiceImpl.restartNetwork(NetworkServiceImpl.java:1883)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy229.restartNetwork(Unknown Source)
        at org.apache.cloudstack.api.command.user.network.RestartNetworkCmd.execute(RestartNetworkCmd.java:99

**Comment by yuanbosoft** [comment]
pop up error as shown below:
![isuue](https://user-images.githubusercontent.com/7006125/192101036-c7107941-6437-43a4-bea5-864b793731cc.png)

**Comment by yuanbosoft** [comment]
cloudstack-sysvmadm -dlocalhost -u cloud -p...


mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.

Stopping and starting 1 secondary storage vm(s)...
Done stopping and starting secondary storage vm(s)

Stopping and starting 1 console proxy vm(s)...
Done stopping and starting console proxy vm(s) .
mysql: [Warning] Using a password on the command line interface can be insecure.

**Stopping and starting 0 running routing vm(s)...**

**Comment by weizhouapache** [comment]
@yuanbosoft 
4.11.2 is quite old and EOL
I would suggest you to upgrade to latest versions (4.17.0.1 or 4.16.1.1)

**Comment by rohityadavcloud** [comment]
@yuanbosoft try if you can restart the network or deploy a VM which in turn will deploy the VR.

**Comment by yuanbosoft** [comment]
> 

Oops,I had already tried  restart the network and deploy a VM ,then the cloudstack-management.log pop up 

"Unexpected exception while executing org.apache.cloudstack.api.command.user.network.RestartNetworkCmd
com.cloud.exception.ResourceUnavailableException: Resource [DataCenter:1] is unreachable: Can't find all necessary running routers!"

**Comment by slavkap** [comment]
@yuanbosoft, can you share the log when you try to deploy a new VM?

**Comment by weizhouapache** [comment]
@yuanbosoft 
what's the state of the current running vm ?
can you destroy it and restart the network ?

**Comment by slavkap** [comment]
@yuanbosoft, can you share what is the output of:
`SELECT * FROM cloud.ntwk_service_map where service="SourceNat" and provider="VirtualRouter" and network_id=204;`
and
`SELECT redundant FROM cloud.networks where id=204;`

**Comment by yuanbosoft** [comment]
> 

1.All about 20 vms are stoped；
2.I have already destroyed console vm and second vm yet, console  and second vms are all restart ,but VR not recreate automaticly

**Comment by yuanbosoft** [comment]
> 

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| cloud              |
| cloud_usage        |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
6 rows in set (0.01 sec)

mysql> SELECT * FROM cloud.ntwk_service_map where service="SourceNat" and provider="VirtualRouter" and network_id=204;
Empty set (0.00 sec)

mysql> SELECT redundant FROM cloud.networks where id=204;
+-----------+
| redundant |
+-----------+
|         1 |
+-----------+
1 row in set (0.00 sec)

mysql>

**Comment by yuanbosoft** [comment]
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| cloud              |
| cloud_usage        |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
6 rows in set (0.01 sec)

mysql> SELECT * FROM cloud.ntwk_service_map where service="SourceNat" and provider="VirtualRouter" and network_id=204;
Empty set (0.00 sec)

mysql> SELECT redundant FROM cloud.networks where id=204;
+-----------+
| redundant |
+-----------+
|         1 |
+-----------+
1 row in set (0.00 sec)

mysql>

**Comment by yuanbosoft** [comment]
mysql> SELECT * FROM cloud.networks where id=204;
+-----+---------------------+--------------------------------------+---------------------+--------------+-----------------------+-----------------+---------+------+------+---------------------+---------------------+----------------+---------------------------+-------+---------+-----------+------------+------+------+-----------+------------+----------+-------------------+----------------+------------+------------------+---------------------+---------+-------------------+--------+-------------+----------+--------------+-----------------+----------------+-------------+-----------+-------------+
| id  | name                | uuid                                 | display_text        | traffic_type | broadcast_domain_type | broadcast_uri   | gateway | cidr | mode | network_offering_id | physical_network_id | data_center_id | guru_name                 | state | related | domain_id | account_id | dns1 | dns2 | guru_data | set_fields | acl_type | network_domain    | reservation_id | guest_type | restart_required | created             | removed | specify_ip_ranges | vpc_id | ip6_gateway | ip6_cidr | network_cidr | display_network | network_acl_id | streched_l2 | redundant | external_id |
+-----+---------------------+--------------------------------------+---------------------+--------------+-----------------------+-----------------+---------+------+------+---------------------+---------------------+----------------+---------------------------+-------+---------+-----------+------------+------+------+-----------+------------+----------+-------------------+----------------+------------+------------------+---------------------+---------+-------------------+--------+-------------+----------+--------------+-----------------+----------------+-------------+-----------+-------------+
| 204 | defaultGuestNetwork | becd3a84-349d-4f67-a331-90641ee173a2 | defaultGuestNetwork | Guest        | Native                | vlan://untagged | NULL    | NULL | Dhcp |                   7 |                 200 |              1 | DirectPodBasedNetworkGuru | Setup |     204 |         1 |          1 | NULL | NULL | NULL      |          0 | Domain   | cs1cloud.internal | NULL           | Shared     |                0 | 2020-07-13 07:20:16 | NULL    |                 1 |   NULL | NULL        | NULL     | NULL         |               1 |           NULL |           0 |         1 | NULL        |
+-----+---------------------+--------------------------------------+---------------------+--------------+-----------------------+-----------------+---------+------+------+---------------------+---------------------+----------------+---------------------------+-------+---------+-----------+------------+------+------+-----------+------------+----------+-------------------+----------------+------------+------------------+---------------------+---------+-------------------+--------+-------------+----------+--------------+-----------------+----------------+-------------+-----------+-------------+
1 row in set (0.00 sec)

mysql>

**Comment by yuanbosoft** [comment]
mysql> SELECT * FROM cloud.ntwk_service_map where network_id=204;
+----+------------+----------+---------------+---------------------+
| id | network_id | service  | provider      | created             |
+----+------------+----------+---------------+---------------------+
|  1 |        204 | Dhcp     | VirtualRouter | 2020-07-13 07:20:16 |
|  2 |        204 | UserData | VirtualRouter | 2020-07-13 07:20:16 |
|  3 |        204 | Dns      | VirtualRouter | 2020-07-13 07:20:16 |
+----+------------+----------+---------------+---------------------+
3 rows in set (0.00 sec)

mysql>

**Comment by slavkap** [comment]
@yuanbosoft, I don't have any experinece with the redundant routers, probably @weizhouapache could help here. But according to the code if the redundant option is enabled for the network you should have network service `SourceNat` for the VirtualRouter provider. Or vice versa if the redundant option is disblaed (set to 0) you don't need the service `SourceNat`. In your case it fails because you don't have that service, and the redundancy for the router is enabled.

**Comment by yuanbosoft** [comment]
> redundancy for the router is enabled.

How can I disable the redundant routers via command or web UI?

**Comment by slavkap** [comment]
I couldn't find another API call than the [updateNetwork](https://cloudstack.apache.org/api/apidocs-4.11/apis/updateNetwork.html) with which you can change the network offering (for which the redundant option is disabled). Or with an update of the DB 
`update cloud.networks set redundant=0 where id=204;`

**Comment by yuanbosoft** [comment]
> I couldn't find another API call than the [updateNetwork](https://cloudstack.apache.org/api/apidocs-4.11/apis/updateNetwork.html) with which you can change the network offering (for which the redundant option is disabled). Or with an update of the DB `update cloud.networks set redundant=0 where id=204;`

Dear，many tkx, 
After exeucted above update sql, all vms launched ,many thanks again .

**Comment by DaanHoogland** [comment]
@yuanbosoft as per your last remark I am closing this. please reopen or create a new ticket if you think this in err.
