### ISSUE TITLE
ZipFile instances can kill management server with OutOfMemory crash

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6764]
This couldn't be confirmed or reproduced but is based on a high-level heap dump analysis from an env. Pl check wherein the code do we use ZipFile java/utils instances and are we properly closing them (using try-with-resource) or keeping some kind of mechanism so that these instances don't just always grow but get GC'd. In case this can't be produced or not such usage can be found/investigated, let's close this. 

##### ISSUE TYPE

 * Bug Report
 * 
##### COMPONENT NAME

~~~
Management Server
~~~

**Comment by rohityadavcloud** [comment]
One followup for this could be to introduce a section on JVM tuning on https://docs.cloudstack.apache.org/en/latest/adminguide/tuning.html (for ex. how to tune/increase the max. java heap for JVM cloudstack-management etc processes)

**Comment by DaanHoogland** [comment]
> One followup for this could be to introduce a section on JVM tuning on https://docs.cloudstack.apache.org/en/latest/adminguide/tuning.html (for ex. how to tune/increase the max. java heap for JVM cloudstack-management etc processes)

there is a section already but it actually still speaks of tomcat. I'll see about updating that.

**Comment by DaanHoogland** [comment]
@rohityadavcloud do you think https://github.com/apache/cloudstack-documentation/pull/288 is enough to close this?
