### ISSUE TITLE
Template Names Limited to 32 Characters: vm_template.name size is 255

### ISSUE THREAD

**Issue by damonb123** [apache/cloudstack#6766]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
TemplateManagerImpl.java

##### CLOUDSTACK VERSION
4.16.0, 4.17.0

##### SUMMARY
* File: ./server/src/main/java/com/cloud/template/TemplateManagerImpl.java:1751
* Method: public VMTemplateVO createPrivateTemplateRecord(CreateTemplateCmd cmd, Account templateOwner)
* Issue:
The template name is limited to 32 characters despite the field allowing 255.  This prevents the ability to use a more descriptive name for templates with environments that have many templates.

```java
String name = cmd.getTemplateName();
if ((name == null) || (name.length() > 32)) {
  throw new InvalidParameterValueException("Template name cannot be null and should be less than 32 characters");
}
```
Improvement request, change 32 to 255 allowing the full use of the field size and more descriptive names.

**Comment by damonb123** [comment]
Thank you for such a quick response.

**Comment by DaanHoogland** [comment]
np @damonb123 , will you be able to test the PR?
