### ISSUE TITLE
AutoSelect live migration fails with local storage

### ISSUE THREAD

**Issue by Rubueno** [apache/cloudstack#6773]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI, API
~~~

##### CLOUDSTACK VERSION
~~~
4.16.1
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When live migrating an instance and choosing "AutoSelect" it is not possible to live migrate an instance with local storage, while when selecting the destination host, it is possible to live migrate an instance with local storage.

##### STEPS TO REPRODUCE
~~~
- Spawn vm on local storage
- Live migrate instance in UI using "AutoSelect"
- Migration fails

CS calls migrateVirtualMachine instead of migrateVirtualMachineWithVolume
~~~

##### EXPECTED RESULTS
~~~
CloudStack to be smart enough to also live migrate instances with local storage when using "AutoSelect"
CS calls migrateVirtualMachineWithVolume instead of migrateVirtualMachine
~~~

##### ACTUAL RESULTS

- Error is returned:
```
Migration failed
Unsupported operation, VM uses Local storage, cannot migrate
```

**Comment by DaanHoogland** [comment]
@Rubueno what method are you using to migrate 
Also, can you test with 4.17? I cannot migrate without choosing a target there.

**Comment by Rubueno** [comment]
> @Rubueno what method are you using to migrate Also, can you test with 4.17? I cannot migrate without choosing a target there.

In this case I was using the UI to migrate. I cannot test with 4.17 yet due to internal release/update policies.

**Comment by shwstppr** [comment]
@Rubueno I don't think this is a bug but rather more of an enhancement. Currently, `migrateVirtualMachineWithVolume` doesn't support live VM migration without providing `hostid`. Therefore, to support this we need to,
- In the backend, refactor `migrateVirtualMachineWithVolume` API to support autoselect flag similar to `migrateVirtualMachine`
- In UI when `Auto-assign` is selected, it needs to list volumes to check if any of the volumes are on local storage and based on that call migrate API

**Comment by Rubueno** [comment]
I can agree marking this as an enhancement instead, although I would see it as a bug when the autoselect option is presented in the UI in cases when it is not supported.
