### ISSUE TITLE
Max size for custom disk offering is checked for disk creation but not for resizing

### ISSUE THREAD

**Issue by thierry-martinez** [apache/cloudstack#6774]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
server

##### CLOUDSTACK VERSION

All versions

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The maximum size for custom disk offering is checked for disk creation but not for resizing.
Users cannot create volumes larger than `CustomDiskOfferingMaxSize` but can resize their volumes afterwards to larger sizes up to the allowed quota.

In the code, `CustomDiskOfferingMaxSize` is checked in [`allocVolume`](https://github.com/apache/cloudstack/blob/8ab8fdc1db4fed4d906c69618980fda9ef710e6a/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L718) but not in [`resizeVolume`](https://github.com/apache/cloudstack/blob/8ab8fdc1db4fed4d906c69618980fda9ef710e6a/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L1020).

##### STEPS TO REPRODUCE
- Make sure that there is a custom disk offering
- Try to create a volume with a custom disk offering and a size larger than `CustomDiskOfferingMaxSize` but lower than other quotas.
- Try to resize a volume with a custom disk offering and a size larger than `CustomDiskOfferingMaxSize` but lower than other quotas.

##### EXPECTED RESULTS
Both creation and resizing should fail.

##### ACTUAL RESULTS
Disk creation fails but resizing succeeds.

**Comment by DaanHoogland** [comment]
fixed in #7073
