### ISSUE TITLE
CreateTagsCmd.java returns wrong EventType

### ISSUE THREAD

**Issue by damonb123** [apache/cloudstack#6777]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
CloudStack API
~~~

##### CLOUDSTACK VERSION
~~~
4.16.x, 4.17.0.1
~~~

##### SUMMARY
Create tags overrides getEnvtype() returns the wrong event type.

```java
    @Override
    public String getEventType() {
        return EventTypes.EVENT_RESOURCE_ICON_UPLOAD;
    }
``` 

Unless I am misunderstanding, it should be:

```java
    @Override
    public String getEventType() {
        return EventTypes.EVENT_TAGS_CREATE;
    }
```

**Comment by damonb123** [comment]
Thanks, for update.  I use the kafka events to perform task when certain tags are added.  My work around is capturing the UPLOAD.RESOURCE.ICON event.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6779
