### ISSUE TITLE
UI: Instances list not filterable by hostid

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack#6786]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0.1
~~~

##### CONFIGURATION
Standard install

##### OS / ENVIRONMENT
N/A

##### SUMMARY
On the 'Hosts' page, clicking on 'View Instances' brings the user to a table of instances (VMs). However, this table is not filtered by the host appropriately even though the URL includes a `hostid=xxxx`. Instead, the table shows all instances in CloudStack.

##### STEPS TO REPRODUCE
1. Go to Infrastructure -> Hosts
2. Select a host (For example: `hostA`)
3. Click on 'View Instances'
4. See that the Instances table contains all VMs in CloudStack (**not** filtered to show only `hostA`'s VMs). The URL should contain something like: `/client/#/vm?hostid=7b313bd8-81fe-4e57-bccb-90df970f6d67`. Note that `hostA`'s `hostid` is being passed in the URI but has no effect.

##### EXPECTED RESULTS
Expect the Instances table is filtered to show only `hostA`'s VMs.

##### ACTUAL RESULTS
Instances table is **not** filtered to show only `hostA`'s VMs.

##### Additional info
I think the `hostid` parameter isn't actually used by the view. I _think_ the table view is generated and filtered by this file/line:

https://github.com/apache/cloudstack/blob/c5262443595e4ed1bb9898654f3bed728331ffc0/ui/src/views/AutogenView.vue#L1524

I don't see hostid actually be used here.

**Comment by weizhouapache** [comment]
I confirm this issue exists in 4.18 as well

**Comment by shwstppr** [comment]
Problem is not with UI, `listVirtualMachinesMetrics` API (for some reason deprecated now) used for listing VMs in the VM view doesn't support podid, hostid, storageid, etc parameters cc @weizhouapache

**Comment by shwstppr** [comment]
Problem is not with the UI but with the `listVirtualMachinesMetrics` API. Currently, it does not support some of the params (hostid, podid, storageid, etc) as it extends DeployVMsCmd class. cc @weizhouapache 

I've created a draft PR to fix this https://github.com/apache/cloudstack/pull/6851

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6851
