### ISSUE TITLE
UI: Public IP Tab - Pagination dropdown unusable

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack#6787]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0.1
~~~

##### CONFIGURATION
Standard install

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The pagination dropdown on the physical network traffic type tab page is being hidden due to the overflow-y being set to scroll. As a result, the selections are being hidden inside a div rather than appearing in front.

See the following gif for a better idea of what I mean:
![overflow-y](https://user-images.githubusercontent.com/4450716/193160738-4bacf2fd-5b32-4b80-ab6e-554826a41808.gif)

##### STEPS TO REPRODUCE
This is happening only on traffic type tab pages. I'll use the public traffic network as an example.

I am currently using Microsoft Edge 105.0.1343.42.

1. Go to Infrastructure -> Zones -> zoneX -> Physical network -> public -> Traffic types
2. Scroll down to the bottom of the list and click on the page size dropdown

##### EXPECTED RESULTS
The dropdown menu should appear properly.

##### ACTUAL RESULTS
The dropdown menu is appearing within a scrollable div.

##### Additional information
I think this is being set here:
https://github.com/apache/cloudstack/blob/main/ui/src/views/infra/network/IpRangesTabPublic.vue#L94

I overrode the `overflow-y` value in the developer console to `none` and the dropdown renders properly.

There are lots of instances where `overflow-y: auto` is set elsewhere, but I see the same behavior only on the other infrastructure/network pages (ie. public, guest, management, storage).

**Comment by DaanHoogland** [comment]
@kohrar using firefox the dropdown open dropping up. so it is usable. Do you see a change to try another browser (to exclude environmental issues)?
