### ISSUE TITLE
config.json wrongly set to 640 after upgrade to 4.17.1

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#6796]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
cloudstack-management-4.17.1.0-1.el7.x86_64
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1
~~~

##### CONFIGURATION

kvm
SharedMountPoint (CephFS)

##### OS / ENVIRONMENT

CentOS Linux release 7.9.2009 (Core) 3.10.0-1160.45.1.el7.x86_64
libvirt-4.5.0-36.el7_9.5.x86_64
qemu-kvm-ev-2.12.0-44.1.el7_8.1.x86_64
qemu-img-ev-2.12.0-44.1.el7_8.1.x86_64
qemu-kvm-common-ev-2.12.0-44.1.el7_8.1.x86_64
libvirt-daemon-driver-qemu-4.5.0-36.el7_9.5.x86_64

##### SUMMARY

After run yum update cloudstack-management `/etc/cloudstack/management/config.json` perm set to 640, cause inaccessible from browser. should set to 644 instead.

##### STEPS TO REPRODUCE

~~~
yum update cloudstack-management
~~~

##### EXPECTED RESULTS

~~~
/etc/cloudstack/management/config.json should set to 644 instead of 640

-rw-r--r--  1 root cloud  16180 Oct  1 04:56 config.json
~~~

##### ACTUAL RESULTS

~~~
-rw-r-----  1 root cloud 16031 Oct 1 17:02 config.json
~~~

**Comment by levindecaro** [comment]
@DaanHoogland 

Thanks for your update, I'd try to reproduce that today but no luck. Last time, i got 403 on config.json when it is 0640, after set to 0644, it work immediately.

**Comment by DaanHoogland** [comment]
@levindecaro what user(-id) is running the server? and of what groups is it a member?

**Comment by levindecaro** [comment]
it is `cloud` uid:995, gid:993

**Comment by DaanHoogland** [comment]
should work (if the group with gid 993 is cloud!)

**Comment by DaanHoogland** [comment]
@levindecaro , I think your `ACTUAL RESULT` is expected. Is there anything we need to do on this ticket? Do you still see a problem?

**Comment by rohityadavcloud** [comment]
((I'm thinking why this issue as config.json is read publically by UI by anybody having access to the webserver (even with the chmod 600 fix, anybody can curl the static file patch at http://<mgmt IP>:8080/client/config.json); there shouldn't be anything required to guard/enforce that only root or cloud user can read it))

**Comment by levindecaro** [comment]
@DaanHoogland, i'm pretty sure i have to change config.json to 644 to make ACS accessible in the upgrade exercise, i have screen capture with forbidden error. Since i fixed that with 644, i cannot reproduce that with changing it back to 640. this is quite mystery to me. I'd like to close this, and observe this problem in next version. Thank you.

**Comment by DaanHoogland** [comment]
thanks @levindecaro , let us kmnow what you find.
