### ISSUE TITLE
Force-stop VM succeed but VM is still running on host if cloudstack-agent is stopped

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6798]
Steps to reproduce the issue

on KVM

- create a vm and start it
- stop cloudstack-agent
- force-stop the VM
- VM is stopped but it is still running on kvm host

This seems incorrect to me. but devs/users may have different opinion.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

server

~~~

##### CLOUDSTACK VERSION

~~~

4.18

~~~

##### OS / ENVIRONMENT

kvm

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@weizhouapache I did merge some kvm related commits. did you verify this on 4.17?

**Comment by weizhouapache** [comment]
@DaanHoogland
I got the same result on a 4.17.1.0 env

**Comment by DaanHoogland** [comment]
Ok, not a regression, but still a major bug.

**Comment by Rubueno** [comment]
Just my 2 cents: does stopVirtualMachine with force=true not always behave this way? The caller must know the VM is stopped before calling it: https://cloudstack.apache.org/api/apidocs-4.17/apis/stopVirtualMachine.html

**Comment by Hudratronium** [comment]
> Force  stop the VM (vm is marked as Stopped even when command fails to be send  to the backend, otherwise a force poweroff is attempted).  The caller  knows the VM is stopped.

Guess the 'interesting' part is, that there is no further feedback what actually happend while calling the function. In the end that could lead to some nasty situations...
As a 'user' i would expect that, like @weizhouapache descriped it, the VM will be stopped on the host by any means and / or verified that it is stopped. If this isn't possible, cause the agent isn't up or not reachable, i would expect this to throw a 'error'. 
I can see why such a function (override of a VM status in DB to be able to deploy it on another host if it is lost) might be usefull. But the overall nameing of the function makes me expect something different then the description in the API docs.

**Comment by Rubueno** [comment]
Indeed. My team has opened https://github.com/apache/cloudstack/issues/6629 to prevent regular users from using this parameter.

**Comment by SakshiT25** [comment]
Hi, I'm interested in working on this issue. Kindly guide me for the further steps.

**Comment by DaanHoogland** [comment]
> Indeed. My team has opened #6629 to prevent regular users from using this parameter.

@Rubueno your request makes sense, and maybe this option should be named `forceMark`, `markDeleted` or just `mark`. It is forcing the marking as deleted in the DB and doesn´t force anything on the backend.

**Comment by DaanHoogland** [comment]
@SakshiT25 are you picking this up?

**Comment by DaanHoogland** [comment]
definition of force stop is being discussed here!

**Comment by rohityadavcloud** [comment]
I think this is by design, we also have a force remove host; we leave upto the admin what they're trying to do - perhaps warn the admin/user what force stop does (in case of KVM)?

**Comment by weizhouapache** [comment]
this is an expected behaviour

according to #7866 made by @DaanHoogland , Force-stop VM means `Force stop the VM (vm is marked as Stopped even when command fails to be send to the backend, otherwise a force poweroff is attempted). To be used if the caller knows the VM is stopped and should be marked as such.`
