### ISSUE TITLE
How to configure a management server cluster?

### ISSUE THREAD

**Issue by 1450793561** [apache/cloudstack#6813]
How to configure a management server cluster?What configuration items need to be modified?

I modified the following configuration to open the current node port 8080 no page

```
cluster.node.IP=10.10.10.100
cluster.servlet.port=9090
region.id=2

# CloudStack database settings
db.cloud.username=cloud
db.cloud.password=cloud
db.cloud.host=10.10.10.99
db.cloud.driver=jdbc:mysql
db.cloud.port=3306
db.cloud.name=cloud
```

**Comment by weizhouapache** [comment]
@1450793561 
the file can be generated by command `cloudstack-setup-databases` on management server.
see http://docs.cloudstack.apache.org/en/latest/installguide/management-server/#install-the-database-on-the-management-server-node

**Comment by 1450793561** [comment]
> @1450793561 the file can be generated by command `cloudstack-setup-databases` on management server. see http://docs.cloudstack.apache.org/en/latest/installguide/management-server/#install-the-database-on-the-management-server-node
Do you mean that the following initialization command should be executed on the standby server?

cloudstack-setup-databases cloud:@localhost [ --deploy-as=root: | --schema-only ] -e -m -k -i

**Comment by 1450793561** [comment]
@weizhouapache 
Do you mean that the following initialization command should be executed on the standby server?

cloudstack-setup-databases cloud:@localhost [ --deploy-as=root: | --schema-only ] -e -m -k -i

**Comment by weizhouapache** [comment]
> @weizhouapache Do you mean that the following initialization command should be executed on the standby server?If you run the database from the standby machine again and you reinitialize it, all the data in mysql is initialized
> 
> cloudstack-setup-databases cloud:@localhost [ --deploy-as=root: | --schema-only ] -e -m -k -i

@1450793561 
if you run the command without ` --deploy-as=root:`, it will just generate the db.properties on the server.
database will not be touched.

this is very useful for extra management servers.

**Comment by 1450793561** [comment]
thanks,is over done.
