### ISSUE TITLE
Clean up mounted NFS mount points used in current session

### ISSUE THREAD

**Issue by 1450793561** [apache/cloudstack#6814]
After the service restarts, an Error message is displayed in the log .The page won't open

2022-10-08 17:11:31,623 DEBUG [C.c.U.c.dencryptionutil] (main:null) (logid:) Error while decrypting: true
2022-10-08 17:11:31,625 INFO [o.a.c.s.NfsMountManager] (main:null) (logid:) Clean up mounted NFS mount points used in current session"

**Comment by nvazquez** [comment]
Hi @1450793561 can you share the full management server logs after restarting the service?

**Comment by 1450793561** [comment]
@nvazquez 

I have restarted the manager server several times, but occasionally this error will be reported. When I restart the Manager server again, no error will be reported.
Does this error have something to do with my use of independent nfs server? Please check the official document to see that this should be uninstalled before adding zone

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- the official document -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
If you are using a separate NFS server, perform this step. If you are using the Management Server as the NFS server,  you MUST NOT perform this step.
When the script has finished, unmount secondary storage and remove the created directory.
umount /mnt/secondary
rmdir /mnt/secondary

**Comment by nvazquez** [comment]
Thanks @1450793561 the problem in this case comes from `2022-10-11 17:30:33,439 ERROR [c.c.c.ClusterManagerImpl] (main:null) (logid:) Detected that another management node with the same IP 10.10.10.5 is already running, please check your cluster configuration`, can you please share the output of `select * from mshost`? It seems like there are duplicate entries affecting the startup

**Comment by 1450793561** [comment]
@nvazquez 

![微信图片_20221013143226](https://user-images.githubusercontent.com/31468018/195519720-cf6fa521-8c14-4906-9c78-ee5b3ad5e3bc.png)

![微信图片_20221013143234](https://user-images.githubusercontent.com/31468018/195519787-ab768e0b-9df9-410b-9a3c-27518ebd8437.png)

**Comment by nvazquez** [comment]
@1450793561 looks like the state column is Down for the mshost record, that may cause the issue. Do you see the state flipping between Up and Down on each service restart?

**Comment by 1450793561** [comment]
@nvazquez Up and Down  Where to see?

**Comment by weizhouapache** [comment]
@1450793561 
the `state` column in `mshost` table

can you share the result of "ip a" on management server ?

**Comment by 1450793561** [comment]
@weizhouapache 

the  mshost  not see chanage
the result of "ip a"

```
[root@WT-ARCHERY-10-5 ~]#ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:e6:85:80:6f:48 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.5/24 brd 10.10.10.255 scope global dynamic eth0
       valid_lft 76220sec preferred_lft 76220sec
[root@WT-ARCHERY-10-5 ~]#
```

**Comment by weizhouapache** [comment]
@1450793561 
is your management server running well now ?

**Comment by 1450793561** [comment]
@weizhouapache Now it is normal. After 3 times of restart, this error will not be reported

**Comment by weizhouapache** [comment]
this is normally the last log when management server is stopped.
