### ISSUE TITLE
Failed to upload the ssl certificate. Procedure，version 4.17.1

### ISSUE THREAD

**Issue by 1450793561** [apache/cloudstack#6815]
upload the ssl certificate 530 error，

![微信图片_20221009162026](https://user-images.githubusercontent.com/31468018/194745958-d6194e55-aa55-4e66-8ec7-b898b7ce7aad.png)

log info following
![微信图片_20221009162326](https://user-images.githubusercontent.com/31468018/194746032-1e70684d-daf2-4c65-877f-73f324079d8b.png)

**Comment by nvazquez** [comment]
Hi @1450793561 can you try the same operation via API using cloudmonkey for example?

**Comment by weizhouapache** [comment]
@1450793561 
it looks you uploaded a ssl certificate for a user. ( it looks like an issue anyway)

if you want to upload ssl ceritificares for SSVM and CPVM, please navigate to Infrastrcture -> Summary -> SSL Certificates, a dialog will pop up like below
![image](https://user-images.githubusercontent.com/57355700/194816202-086081f0-b3c0-422f-b73b-cd38fa6621f9.png)

**Comment by 1450793561** [comment]
@weizhouapache thanks，i find this， Infrastrcture -> Summary -> SSL Certificates

**Comment by 1450793561** [comment]
@weizhouapache in 4.17 version，to register an iso image, do I have to upload ssl ceritificares for SSVM and CPVM?

**Comment by weizhouapache** [comment]
> @weizhouapache in 4.17 version，to register an iso image, do I have to upload ssl ceritificares for SSVM and CPVM?

@1450793561 
if you register template or iso from a URL, ssl certificate is not required.

if you upload template or iso from local machine, ssl certificate is required. you need to configure other settings as well.
please refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

**Comment by 1450793561** [comment]
Now I'm just uploading iso from the url with the error message below.
"Connection refused (Connection refused)"
"secstorage.allowed.internal.sites" this parameter has been modified 10.10.0.0/16,but still this mistake
![微信图片_20221011145037](https://user-images.githubusercontent.com/31468018/195016435-a0e7c8f3-3c24-4aa7-980a-662d34755903.png)

**Comment by weizhouapache** [comment]
@1450793561 
two questions 
1. is your webserver in the network 10.10.0.0/16 ?
2. Have you restarted mgmt server and SSVM after your change ?

**Comment by 1450793561** [comment]
@weizhouapache 
In version 4.15, after modify the parameter "secstorage. Charges of.internal. Sites," from the url registration iso is no problem.

 In version 4.17, after modify the parameter "secstorage. Charges of.internal. Sites," from the url registration iso has the problem

**Comment by weizhouapache** [comment]
> @weizhouapache In version 4.15, after modify the parameter "secstorage. Charges of.internal. Sites," from the url registration iso is no problem.
> 
> In version 4.17, after modify the parameter "secstorage. Charges of.internal. Sites," from the url registration iso has the problem

@1450793561 
that's a bit strange.
can you answer my previous questions ?

**Comment by 1450793561** [comment]
@nvazquez 
It's weird, me to

1.firsh question is yes
2.sercord question is yes，restarted mgmt server after my change

**Comment by weizhouapache** [comment]
> @nvazquez It's weird, me to
> 
> 1.firsh question is yes 2.sercord question is yes，restarted mgmt server after my change

@1450793561 
I notice you have closed the issue. is the issue fixed ?
