### ISSUE TITLE
How to configer advanced  zones with version 4.13.1

### ISSUE THREAD

**Issue by austinuMyaccount** [apache/cloudstack#6816]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.13.1.0
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

vmware CentOS 7 

##### STEPS TO REPRODUCE

how to create a useful  advanced zone ,that mean to be how to design an advanced networking.

~~~

~~~

##### EXPECTED RESULTS

~~
for example, physical machine has an static ip 192.168.1.123, there is a vmware in the machine, and there is a manager server vm and a agent server vm, manager's ip is 172.168.0.123, agent's ip is 10.2.3.4, how to configer networking so that client can use physical machine chorme visit cloudstack system. 
~~~

**Comment by austinuMyaccount** [comment]
i sure it's follow the issue template

**Comment by austinuMyaccount** [comment]
> Thanks for opening your first issue here! Be sure to follow the issue template!

i sure it's follow the issue template!

**Comment by nvazquez** [comment]
@austinuMyaccount I'm closing this one in favour of #6818
