### ISSUE TITLE
How to configer advanced zones with cloudstack version 4.13.1, vmware 16

### ISSUE THREAD

**Issue by austinuMyaccount** [apache/cloudstack#6818]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI,Networking
~~~

##### CLOUDSTACK VERSION

~~~
4.13.1.0
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

vmware 16 CentOS 7

##### SUMMARY

how to create a useful advanced zone ,that mean to be how to design an advanced networking.
##### STEPS TO REPRODUCE

~~~
how to create a useful advanced zone ,that mean to be how to design an advanced networking.
~~~

##### EXPECTED RESULTS

~~~
for example, physical machine has an static ip 192.168.1.123, there is a vmware in the machine,
 and there is a manager server vm and a agent server vm, manager's ip is 172.168.0.123,
 agent's ip is 10.2.3.4, how to configer networking so that client can use physical machine chorme visit cloudstack system.
~~~

##### ACTUAL RESULTS

~~~
i can use advanced zones to build complicated networking and working well.
~~~

**Comment by rohityadavcloud** [comment]
Thanks for the question, unless there is a bug you've hit you may refer to the admin guide on https://docs.cloudstack.apache.org/en/latest/adminguide/index.html how to configure and use advance zones with vmware. (we don't support vmware 16, perhaps you mean 6.x?)
