### ISSUE TITLE
Unable to list all Public IP Addresses from account with ROOT ADMIN role

### ISSUE THREAD

**Issue by zap51** [apache/cloudstack#6821]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.0
~~~

##### CONFIGURATION

~~~
KVM with Advanced Networking
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu Server 20.04 LTS on both Management and Hosts
~~~
##### SUMMARY

We have several zones with Public IP Addresses. 
Listing all Public IP Addresses on both WebUI and API produces 

~~~
Comparison method violates its general contract!
~~~

On WebUI

![image](https://user-images.githubusercontent.com/45934027/195062345-60a83c37-2d0d-4f95-b855-d4d126c0b134.png)

On API

![image](https://user-images.githubusercontent.com/45934027/195063546-4c84b9fd-a34d-4011-8a10-4662bfb1bb5b.png)

This is happening on Accounts with ROOT ADMIN privileges. Normal users / users with little number of Public IP Addresses are able to list the addresses normally.

##### STEPS TO REPRODUCE

~~~
1. Navigate to Network -> Public IP Addresses
~~~

##### EXPECTED RESULTS

~~~
API or WebUI should list all Public IP Addresses.
~~~

##### ACTUAL RESULTS

~~~
"Comparison method violates its general contract!" is the error message and doesn't list Public IP Addresses
~~~

**Comment by rohityadavcloud** [comment]
@zap51 does it fix if you add `-Djava.util.Arrays.useLegacyMergeSort=true` in the JAVA_OPTS on /etc/default/cloudstack-management and restart mgmt server?

**Comment by zap51** [comment]
@rohityadavcloud Thanks, I'd updated this on one of the our management servers, I'm now able to list Public IP Addresses. But, as soon as I toggle "Projects" button on WebUI, it throws "undefined" when navigated to 4th page with pagesize 20.

![image](https://user-images.githubusercontent.com/45934027/195076838-b22d8fda-8480-4bda-a2f2-e5cf37b6364a.png)

Similarly, on the API with Projects, throws

![image](https://user-images.githubusercontent.com/45934027/195076720-e2d98659-cd36-4618-8fce-e6a472ad60a6.png)

Regards

**Comment by weizhouapache** [comment]
> @rohityadavcloud Thanks, I'd updated this on one of the our management servers, I'm now able to list Public IP Addresses. But, as soon as I toggle "Projects" button on WebUI, it throws "undefined" when navigated to 4th page with pagesize 20.
> 
> ![image](https://user-images.githubusercontent.com/45934027/195076838-b22d8fda-8480-4bda-a2f2-e5cf37b6364a.png)
> 
> Similarly, on the API with Projects, throws
> 
> ![image](https://user-images.githubusercontent.com/45934027/195076720-e2d98659-cd36-4618-8fce-e6a472ad60a6.png)
> 
> Regards

any error in management servef log ?

**Comment by zap51** [comment]
> 

Here's the log on `/var/log/cloudstack/management/management-server.log`

```
2022-10-11 11:37:30,462 ERROR [c.c.a.ApiServer] (qtp169663597-336:ctx-24a2aca1 ctx-482def32 ctx-66700007) (logid:48e02052) unhandled exception executing api command: [Ljava.lang.String;@1b620cc0
java.lang.NullPointerException
	at com.cloud.api.ApiResponseHelper.populateOwner(ApiResponseHelper.java:2630)
	at com.cloud.api.ApiResponseHelper.createIPAddressResponse(ApiResponseHelper.java:875)
	at org.apache.cloudstack.api.command.user.address.ListPublicIpAddressesCmd.execute(ListPublicIpAddressesCmd.java:198)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:772)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:596)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:321)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:134)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:131)
	at com.cloud.api.ApiServlet.doGet(ApiServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-11 11:37:30,468 DEBUG [c.c.a.ApiServlet] (qtp169663597-336:ctx-24a2aca1 ctx-482def32 ctx-66700007) (logid:48e02052) ===END===
```

And at `/var/log/cloudstack/management/apilog.log`

```INFO  [a.c.c.a.ApiServlet] (qtp169663597-333:ctx-6acb5316 ctx-7c4e6ad3 ctx-0c473dd9) (logid:00d64382) (userId=1352 accountId=1922 sessionId=null) <--redacted--> -- GET apiKey=XXX&command=listPublicIpAddresses&listall=true&projectid=-1&response=json&signature=mRUs0hDwp0OBGrsvrrMM3gAaUks%3D 530 null```

Regards

**Comment by zap51** [comment]
@weizhouapache 

Here's the output of the query. Some information is redacted FYI.

> select * from user_ip_address join projects on user_ip_address.account_id=projects.project_account_id where projects.removed is not null;

```
+------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
| id   | uuid                                 | account_id | domain_id | public_ip_address | data_center_id | source_nat | allocated           | vlan_db_id | one_to_one_nat | vm_id | state     | mac_address | source_network_id | network_id | physical_network_id | is_system | vpc_id | dnat_vmip | is_portable | display | removed | created | rule_state | forsystemvms | id  | name | uuid                                 | display_text          | project_account_id | domain_id | created             | removed             | state    |
+------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
| 1463 | 26527c7b-a846-4654-bd6d-8ae89c31ce40 |       1265 |       962 | x.x.x.x           |              7 |          1 | 2022-09-19 05:12:31 |          7 |              0 |  NULL | Allocated |         379 |               219 |       NULL |                 211 |         0 |    248 | NULL      |           0 |       1 | NULL    | NULL    | NULL       |            0 | 299 | NULL | 1cdf779b-23d8-40c4-be80-e69d8b24c95f | user-name-6536279     |               1265 |       962 | 2022-09-16 08:38:03 | 2022-09-21 12:53:24 | Disabled |
| 1499 | 9e4b3356-e0ae-4c5b-9edb-9ab576b757e4 |       1265 |       962 | x.x.x.x           |              7 |          1 | 2022-09-16 08:52:16 |          7 |              0 |  NULL | Allocated |         391 |               219 |       NULL |                 211 |         0 |    230 | NULL      |           0 |       1 | NULL    | NULL    | NULL       |            0 | 299 | NULL | 1cdf779b-23d8-40c4-be80-e69d8b24c95f | user-name-6536279     |               1265 |       962 | 2022-09-16 08:38:03 | 2022-09-21 12:53:24 | Disabled |
+------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
```

Thanks

**Comment by weizhouapache** [comment]
> @weizhouapache
> 
> Here's the output of the query. Some information is redacted FYI.
> 
> > select * from user_ip_address join projects on user_ip_address.account_id=projects.project_account_id where projects.removed is not null;
> 
> ```
> +------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
> | id   | uuid                                 | account_id | domain_id | public_ip_address | data_center_id | source_nat | allocated           | vlan_db_id | one_to_one_nat | vm_id | state     | mac_address | source_network_id | network_id | physical_network_id | is_system | vpc_id | dnat_vmip | is_portable | display | removed | created | rule_state | forsystemvms | id  | name | uuid                                 | display_text          | project_account_id | domain_id | created             | removed             | state    |
> +------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
> | 1463 | 26527c7b-a846-4654-bd6d-8ae89c31ce40 |       1265 |       962 | x.x.x.x           |              7 |          1 | 2022-09-19 05:12:31 |          7 |              0 |  NULL | Allocated |         379 |               219 |       NULL |                 211 |         0 |    248 | NULL      |           0 |       1 | NULL    | NULL    | NULL       |            0 | 299 | NULL | 1cdf779b-23d8-40c4-be80-e69d8b24c95f | user-name-6536279     |               1265 |       962 | 2022-09-16 08:38:03 | 2022-09-21 12:53:24 | Disabled |
> | 1499 | 9e4b3356-e0ae-4c5b-9edb-9ab576b757e4 |       1265 |       962 | x.x.x.x           |              7 |          1 | 2022-09-16 08:52:16 |          7 |              0 |  NULL | Allocated |         391 |               219 |       NULL |                 211 |         0 |    230 | NULL      |           0 |       1 | NULL    | NULL    | NULL       |            0 | 299 | NULL | 1cdf779b-23d8-40c4-be80-e69d8b24c95f | user-name-6536279     |               1265 |       962 | 2022-09-16 08:38:03 | 2022-09-21 12:53:24 | Disabled |
> +------+--------------------------------------+------------+-----------+-------------------+----------------+------------+---------------------+------------+----------------+-------+-----------+-------------+-------------------+------------+---------------------+-----------+--------+-----------+-------------+---------+---------+---------+------------+--------------+-----+------+--------------------------------------+-----------------------+--------------------+-----------+---------------------+---------------------+----------+
> ```
> 
> Thanks

the two ips are used by vpcs (ids are 248, 230) as source nat IP in a deleted project (id=299). it should not happen.

if the vpcs have been removed as well, a workaround is, update the ip to free state by manual db changes (please backup your database/table).

update user_ip_address set account_id=NULL,domain_id=NULL,source_nat=0,allocated=NULL,one_to_one_nat=0,vm_id=NULL,state='Free',vpc_id=NULL,network_id=NULL,dnat_vmip=NULL where id=1463;
update user_ip_address set account_id=NULL,domain_id=NULL,source_nat=0,allocated=NULL,one_to_one_nat=0,vm_id=NULL,state='Free',vpc_id=NULL,network_id=NULL,dnat_vmip=NULL where id=1499;

**Comment by weizhouapache** [comment]
> 299

@zap51 
in this case, you should not execute the queries I mentioned in previous comment.

you can try to restore the project and account to normal state.

update projects set removed=NULL where id=299;
update account set removed=NULL where id=1265;

**Comment by zap51** [comment]
> > 299
> 
> @zap51 in this case, you should not execute the queries I mentioned in previous comment.
> 
> you can try to restore the project and account to normal state.
> 
> update projects set removed=NULL where id=299; update account set removed=NULL where id=1265;

Thanks,
    I tried the set of queries. Now I see I'm able to get into the details of the domain, however not visible on the WebUI though. I'm trying to clean up the entire domain and releasing all resources under it, but no success. I also see that the account has `cleanup_needed=1`

```
select * from account where id=1265;
+------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
| id   | account_name                      | uuid                                 | type | role_id | domain_id | state   | created             | removed             | cleanup_needed | network_domain | default_zone_id | default |
+------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
| 1265 | PrjAcct-xxxxxx-xxxxxx-6536279-962 | f64a31eb-10db-40a7-a276-6f4e730c2859 |    5 |    NULL |       962 | enabled | 2022-09-16 08:38:03 | NULL                |              1 | NULL           |            NULL |       0 |
+------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
```

Please suggest to remove all the resources under these domain and hopefully the account.

Thanks

**Comment by zap51** [comment]
> > > 299
> > 
> > 
> > @zap51 in this case, you should not execute the queries I mentioned in previous comment.
> > you can try to restore the project and account to normal state.
> > update projects set removed=NULL where id=299; update account set removed=NULL where id=1265;
> 
> Thanks @weizhouapache, I tried the set of queries. Now I see I'm able to get into the details of the domain, however not visible on the WebUI though. I'm trying to clean up the entire domain and releasing all resources under it, but no success. I also see that the account has `cleanup_needed=1`
> 
> ```
> select * from account where id=1265;
> +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> | id   | account_name                      | uuid                                 | type | role_id | domain_id | state   | created             | removed             | cleanup_needed | network_domain | default_zone_id | default |
> +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> | 1265 | PrjAcct-xxxxxx-xxxxxx-6536279-962 | f64a31eb-10db-40a7-a276-6f4e730c2859 |    5 |    NULL |       962 | enabled | 2022-09-16 08:38:03 | NULL                |              1 | NULL           |            NULL |       0 |
> +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> ```
> 
> Please suggest to remove all the resources under this domain and hopefully the account.
> 
> Thanks

@weizhouapache Please suggest a method to clean up the resources under this account. Thank you!

**Comment by weizhouapache** [comment]
> > > > 299
> > > 
> > > 
> > > @zap51 in this case, you should not execute the queries I mentioned in previous comment.
> > > you can try to restore the project and account to normal state.
> > > update projects set removed=NULL where id=299; update account set removed=NULL where id=1265;
> > 
> > 
> > Thanks @weizhouapache, I tried the set of queries. Now I see I'm able to get into the details of the domain, however not visible on the WebUI though. I'm trying to clean up the entire domain and releasing all resources under it, but no success. I also see that the account has `cleanup_needed=1`
> > ```
> > select * from account where id=1265;
> > +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> > | id   | account_name                      | uuid                                 | type | role_id | domain_id | state   | created             | removed             | cleanup_needed | network_domain | default_zone_id | default |
> > +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> > | 1265 | PrjAcct-xxxxxx-xxxxxx-6536279-962 | f64a31eb-10db-40a7-a276-6f4e730c2859 |    5 |    NULL |       962 | enabled | 2022-09-16 08:38:03 | NULL                |              1 | NULL           |            NULL |       0 |
> > +------+-----------------------------------+--------------------------------------+------+---------+-----------+---------+---------------------+---------------------+----------------+----------------+-----------------+---------+
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please suggest to remove all the resources under this domain and hopefully the account.
> > Thanks
> 
> @weizhouapache Please suggest a method to clean up the resources under this account. Thank you!

@zap51 
I do not the exact state of your project, network, etc.
do you need the project ? if not, just update the `removed` field in the table above, cloudstack will try to clean the project in backend.

update account set removed=now() where id=1265;

**Comment by zap51** [comment]
> 962

@weizhouapache Had tried the above, but the resources are not released till now. Please suggest.

`cleanup_needed` is still `1` in the database.

Thanks

**Comment by weizhouapache** [comment]
@zap51 
what resources need to be cleaned ?

**Comment by zap51** [comment]
> @zap51 
> what resources need to be cleaned ?
> 
@weizhouapache 
The VPC that is holding 1 public IP address.

**Comment by weizhouapache** [comment]
> > @zap51
> > what resources need to be cleaned ?
> 
> @weizhouapache The VPC that is holding 1 public IP address.

that's the only resource to be cleaned ? if yes, you can run the sql I mentioned before
`update user_ip_address set account_id=NULL,domain_id=NULL,source_nat=0,allocated=NULL,one_to_one_nat=0,vm_id=NULL,state='Free',vpc_id=NULL,network_id=NULL,dnat_vmip=NULL where id=xxx; `

**Comment by zap51** [comment]
@weizhouapache @rohityadavcloud Thank you for your support. I've done the VR, VPC and VPC Isolated Network cleanup and able to list all Public IP Address without any issues. I'm closing this issue now.
