### ISSUE TITLE
public.ip.addresses of guestnetwork conflicts with an existing address

### ISSUE THREAD

**Issue by 1450793561** [apache/cloudstack#6823]
The address assigned to the guestnetwork conflicts with an existing address.
following pic

![微信图片_20221012133940](https://user-images.githubusercontent.com/31468018/195259720-15fa2701-a51a-47f8-b32e-328126264f1c.png)

**Comment by weizhouapache** [comment]
What do these ips have conflict with ?

Anyway, these ips are added by you , when you create the zone.

**Comment by 1450793561** [comment]
@weizhouapache 
These ip addresses conflict with other existing server ip addresses. Before cloudstack is built, there are many servers, such as 10.10.10.98 in the screenshot. I can ping this address, but guestnetwork still considers this address to be assignable

I know that when creating a zone, you need to fill in the guest network range. I fill in 10.10.10.10-10.10.10.200

 In other words, when you create a guest network, the specified IP address range cannot conflict with the existing IP address range

**Comment by weizhouapache** [comment]
> @weizhouapache These ip addresses conflict with other existing server ip addresses. Before cloudstack is built, there are many servers, such as 10.10.10.98 in the screenshot. I can ping this address, but guestnetwork still considers this address to be assignable
> 
> I know that when creating a zone, you need to fill in the guest network range. I fill in 10.10.10.10-10.10.10.200
> 
> In other words, when you create a guest network, the specified IP address range cannot conflict with the existing IP address range

@1450793561 

right. when you create the zone, you should make sure that the ips do not have conflict

- host ips
- pod start/end ips (used by cloudstack system vms)
- public ips
- guest network ips

**Comment by 1450793561** [comment]
What you said above is clear, but now my question is whether the scope of guest network can include existing ip?

Please see the screenshot below. The ip address assigned to the virtual machine is 10.10.10.68, but 10.10.10.68 already exists on this network segment


![微信图片_20221013111408](https://user-images.githubusercontent.com/31468018/195491080-ae5522a1-6f30-49ef-8b9b-e4e540303522.png)

![微信图片_20221013111421](https://user-images.githubusercontent.com/31468018/195491096-16013d51-da4b-43b0-aa96-7bbe2fcda2bc.png)

**Comment by weizhouapache** [comment]
> @weizhouapache What you said above is clear, but now my question is whether the scope of guest network can include existing ip?
> 
> Please see the screenshot below. The ip address assigned to the virtual machine is 10.10.10.68, but 10.10.10.68 already exists on this network segment
> 
> ![微信图片_20221013111408](https://user-images.githubusercontent.com/31468018/195491080-ae5522a1-6f30-49ef-8b9b-e4e540303522.png)
> 
> ![微信图片_20221013111421](https://user-images.githubusercontent.com/31468018/195491096-16013d51-da4b-43b0-aa96-7bbe2fcda2bc.png)

@1450793561 
is the vm on the network ? if yes, this s expected behavior.

when you create a vm on a Shared network, management server will choose an IP in the network Ip range and assign IP to the VM.

**Comment by 1450793561** [comment]
@weizhouapache 
For example, the ip address of manager server is 10.10.10.68, and the range of guest network configured during zone createion is 10.10.10.50-10.10.10.100. Is it possible that I assigned ip 10.10.10.68 when I created the vm

**Comment by 1450793561** [comment]
ip conflicts are not checked

**Comment by weizhouapache** [comment]
> @weizhouapache For example, the ip address of manager server is 10.10.10.68, and the range of guest network configured during zone createion is 10.10.10.50-10.10.10.100. Is it possible that I assigned ip 10.10.10.68 when I created the vm.
> 
> What is the policy for assigning ip addresses? Random assignment from guest network range? Does it not judge that the ip address already exists in the network segment

@1450793561 
if the vmip is specified when you create the vm, mgmt server will check if the vmip is available and assign to vm if ip is free.
if vmip is not specified, mgmt server will choose a random IP.

mgmt server checks the vlan and guest IP ranges, but does not check if the guest IPs have conflict with IPs for other use (management server, hosts, etc).

you should have a better network plan. it is the first and important step to build an environment.

**Comment by 1450793561** [comment]
### if vmip is not specified, mgmt server will choose a random IP

**Comment by 1450793561** [comment]
>  if vmip is not specified, mgmt server will choose a random IP.

### The above is just an example to say that manager server is 10.10.10.68.may be zhe ip 10.10.10.68 is another service that is already running,In this case, the ip that's assigned to the vm could also be this, right?

**Comment by weizhouapache** [comment]
> > if vmip is not specified, mgmt server will choose a random IP.
> > @weizhouapache
> 
> ### The above is just an example to say that manager server is 10.10.10.68.may be zhe ip 10.10.10.68 is another service that is already running,In this case, the ip that's assigned to the vm could also be this, right?

of course. if you add network with 10.10.10.50-10.10.10.100, the ip 10.10.10.68 might be assigned to a vm.
if you add another network with same vlan and ip range to cloudstack, it will fail. cloudstack has the check.
if you use an Ip in guest ip range for other use, it is out of cloudstack's control. this should be avoided.
once again, you should have a better network plan.
