### ISSUE TITLE
The System VMs Agent state is not Up after upgrade to CloudStack 4.17.1.0

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6826]
#### ISSUE TYPE

 * Other

#### COMPONENT NAME
* System VMs

##### CLOUDSTACK VERSION
* CloudStack 4.17.1.0

##### OS / ENVIRONMENT
```
# rpm -qa | grep cloudstack
cloudstack-management-4.17.1.0-1.el7.x86_64
cloudstack-common-4.17.1.0-1.el7.x86_64

# rpm -qa | grep cloudstack
cloudstack-agent-4.17.1.0-shapeblue0.el8.x86_64
cloudstack-common-4.17.1.0-shapeblue0.el8.x86_64

# cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="8.3"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.3"
```

##### SUMMARY
The System VMs Agent state is not Up after upgrade from 4.15.2.0 to CloudStack 4.17.1.0

##### STEPS TO REPRODUCE
we using the doc as below:
[upgrade the cloudstack ](http://docs.cloudstack.apache.org/en/latest/upgrading/upgrade/upgrade-4.15.html)

##### EXPECTED RESULTS
The  System VMs Agent state is OK.

##### ACTUAL RESULTS
The  System VMs Agent state is not OK.
![image](https://user-images.githubusercontent.com/4197714/195544169-2e3ea120-1beb-4530-ab36-2290d7a72bc5.png)

---
There is no valid log error message in the log file.
```
2022-10-13 00:01:50,636 DEBUG [kvm.resource.LibvirtComputingResource] (UgentTask-5:null) (logid:) Execution is successful.
2022-10-13 00:01:50,637 DEBUG [kvm.resource.LibvirtConnection] (UgentTask-5:null) (logid:) Looking for libvirtd connection at: qemu:///system
2022-10-13 00:01:50,648 DEBUG [cloud.agent.Agent] (UgentTask-5:null) (logid:) Sending ping: Seq 32-380:  { Cmd , MgmtId: -1, via: 32, Ver: v1, Flags: 11, [{"com.cloud.agent.api.PingRoutingWithNwGroupsCommand":{"newGroupStates":{"i-2-26018-VM":["26018","2"],"i-2-26020-VM":["26020","2"],"i-2-25943-VM":["25943","4"],"i-2-25969-VM":["25969","2"],"i-2-25950-VM":["25950","2"],"i-2-25937-VM":["25937","4"],"i-2-26008-VM":["26008","2"],"i-2-25931-VM":["25931","5"],"i-2-26007-VM":["26007","2"],"i-2-26005-VM":["26005","5"],"i-2-25959-VM":["25959","2"],"i-2-25948-VM":["25948","3"],"i-2-26012-VM":["26012","2"],"i-2-26017-VM":["26017","2"]},"_hostVmStateReport":{"i-2-26018-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"r-25932-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26020-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25943-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25969-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25950-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25937-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"r-25938-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26008-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"s-26559-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25931-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26007-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26005-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25959-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-25948-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26012-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"v-26560-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"},"i-2-26017-VM":{"state":"PowerOn","host":"whdckvm007.cn.prod"}},"_gatewayAccessible":"true","_vnetAccessible":"true","hostType":"Routing","hostId":"32","wait":"0","bypassHostMaintenance":"false"}}] }
2022-10-13 00:01:50,913 DEBUG [cloud.agent.Agent] (Agent-Handler-1:null) (logid:) Received response: Seq 32-380:  { Ans: , MgmtId: 345052215515, via: 32, Ver: v1, Flags: 100010, [{"com.cloud.agent.api.PingAnswer":{"_command":{"hostType":"Routing","hostId":"32","wait":"0","bypassHostMaintenance":"false"},"result":"true","wait":"0","bypassHostMaintenance":"false"}}] }
2022-10-13 00:02:23,580 DEBUG [cloud.agent.Agent] (agentRequest-Handler-1:null) (logid:d574e7cf) Processing command: com.cloud.agent.api.GetHostStatsCommand
2022-10-13 00:02:27,142 DEBUG [cloud.agent.Agent] (agentRequest-Handler-2:null) (logid:621fd576) Processing command: com.cloud.agent.api.GetStorageStatsCommand
2022-10-13 00:02:27,142 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-2:null) (logid:621fd576) Trying to fetch storage pool b4fb50ca-79f2-46ba-bd1b-092f9bd14d4e from libvirt
2022-10-13 00:02:27,142 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-2:null) (logid:621fd576) Looking for libvirtd connection at: qemu:///system
2022-10-13 00:02:27,158 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-2:null) (logid:621fd576) Asking libvirt to refresh storage pool b4fb50ca-79f2-46ba-bd1b-092f9bd14d4e
2022-10-13 00:02:27,160 DEBUG [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-2:null) (logid:621fd576) Successfully refreshed pool b4fb50ca-79f2-46ba-bd1b-092f9bd14d4e Capacity: (49.98 GB) 53660876800 Used: (10.98 GB) 11788746752 Available: (39.00 GB) 41872130048
2022-10-13 00:02:27,244 DEBUG [cloud.agent.Agent] (agentRequest-Handler-4:null) (logid:621fd576) Processing command: com.cloud.agent.api.GetStorageStatsCommand
2022-10-13 00:02:27,244 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-4:null) (logid:621fd576) Trying to fetch storage pool 0edb0e58-6b90-3bee-8e7b-13007b0f7bf9 from libvirt
2022-10-13 00:02:27,244 DEBUG [kvm.resource.LibvirtConnection] (agentRequest-Handler-4:null) (logid:621fd576) Looking for libvirtd connection at: qemu:///system

```

 I have test all the connection:

The cloudstack manager node ip: 10.25.2.173

The agent host node ip: 10.26.246.10

The KVM vm instance IP:
- 10.26.18.78 (VLAN1)
- 10.26.15.68 (VLAN2)
![image](https://user-images.githubusercontent.com/4197714/195549225-37744e68-b0e2-4e52-890f-6acaeb1dd61b.png)

The virtual routes ip: 
-  r-25938-VM: 10.26.18.31 (VLAN1)
-  r-25932-VM: 10.26.15.31 (VLAN2)
![image](https://user-images.githubusercontent.com/4197714/195544950-a237d38b-da95-45bd-b98a-cbe0e86f4c3d.png)

The system vm ip:
- s-26559-VM
- v-26560-VM
![image](https://user-images.githubusercontent.com/4197714/195547539-27e1089d-f7d6-4289-b468-d44ee6fb9e75.png)

The system vm can ping all the ip address:

The Second Storage VM: s-26559-VM
![image](https://user-images.githubusercontent.com/4197714/195548716-5baf434f-7ed6-4763-b605-21e5e5207dec.png)

The console proxy VM: v-26560-VM
![image](https://user-images.githubusercontent.com/4197714/195552153-f9531a44-c9d4-4796-b4dc-75b3761d72a3.png)

The virtual route can also ping all the ip:

![image](https://user-images.githubusercontent.com/4197714/195554278-1d5d3062-dfb0-4dff-8c00-8cfef243f5d1.png)

The manager node can ping all the address:

![image](https://user-images.githubusercontent.com/4197714/195550536-16673d4c-328e-4b7e-937a-84606d1c02c4.png)

But I don't know why the System VMs Agent state is not Up,  Can you give some suggestions on how to troubleshoot this problem?  If you need more information, please ask.

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng ,
first one question; you mention you used the upgrade guide from 4.15.x, but your rpm output above show only 4.17.0.1 and 4.17.1.0. Which upgrade did you perform?
Then about the issue. If all features function ok, I don´t think the state display is a problem. You can destroy and systemvm that doesn´t show a good status and wait for a new one to come up again. That should remove the problem. If some functionality is not working that would also be the first course of action.

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland 
we upgrade CloudStack from version 4.15.2.0 to  4.17.1.0 .

@slavkap 
The status of the secondary storage of the problematic cluster:
The second storage is using nfs:
![image](https://user-images.githubusercontent.com/4197714/196322766-4edcdd79-9d69-4a9f-888c-5913a943f6a8.png)

```
[root@10.26.246.10 image]# pwd
/image
[root@10.26.246.10 image]# ls
snapshots  template  volumes
[root@10.26.246.10 image]# ifconfig | grep inet
        inet 169.254.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::ecde:53ff:fecb:df73  prefixlen 64  scopeid 0x20<link>
        inet 10.26.246.10  netmask 255.255.255.0  broadcast 10.26.246.255
        inet6 fe80::bc35:98ff:fe7a:d06a  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::9c75:d0ff:fed5:53ed  prefixlen 64  scopeid 0x20<link>
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
[root@10.26.246.10 image]# tree ./*
./snapshots
./template
└── tmpl
    ├── 1
    │   ├── 3
    │   │   ├── 68d8aa03-dbce-4335-b2fa-4812a4ca65dc.qcow2
    │   │   └── template.properties
    │   └── 4
    │       └── template.properties
    └── 2
        ├── 232
        │   └── template.properties
        ├── 247
        │   ├── 247-2-d800137d-4247-3e93-a3cb-915ba60c921e.iso
        │   └── template.properties
        └── 248
            ├── 4b1ec60e-f0d3-3307-a321-a13152959117.qcow2
            └── template.properties
./volumes

8 directories, 8 files

```

And the directory of the storage system virtual machine is empty:
![image](https://user-images.githubusercontent.com/4197714/196324038-98fc468c-316a-42a8-af2e-5606af73b4c4.png)


------

The status of the secondary storage of our another normal cluster:
```
[root@10.26.246.7 image]# pwd
/image
[root@10.26.246.7 image]# ls
snapshots  template  volumes
[root@10.26.246.7 image]# ifconfig | grep inet
        inet6 fe80::9edc:71ff:feca:93b0  prefixlen 64  scopeid 0x20<link>
        inet 10.26.246.7  netmask 255.255.255.0  broadcast 10.26.246.255
        inet6 fe80::9edc:71ff:feca:93b0  prefixlen 64  scopeid 0x20<link>
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
[root@10.26.246.7 image]# tree ./*
./snapshots
./template
└── tmpl
    ├── 1
    │   ├── 253
    │   │   ├── 253-1-59fef5e9-6616-3704-acf0-a0a5838dd1ae.iso
    │   │   └── template.properties
    │   ├── 255
    │   │   ├── 255-1-d3e4c0b7-81af-3dc1-96ea-010a16b78c24.iso
    │   │   └── template.properties
    │   ├── 3
    │   │   ├── dea9fed0-a166-45f3-b4d9-39edc1744ff6.qcow2
    │   │   └── template.properties
    │   └── 4
    │       ├── 02fc4431-c4b4-3407-bff6-50d367eb9ee8.qcow2
    │       └── template.properties
    └── 2
        ├── 247
        │   ├── 247-2-d800137d-4247-3e93-a3cb-915ba60c921e.iso
        │   └── template.properties
        ├── 248
        │   ├── 58a5fd71-e52e-3de0-9046-ba6a44df69ea.qcow2
        │   └── template.properties
        └── 257
            ├── 68b2c597-f9c5-3d2c-94be-fe7205e94ce2.qcow2
            └── template.properties
./volumes

10 directories, 14 files
```
And the directory of the storage system virtual machine is empty:
![image](https://user-images.githubusercontent.com/4197714/196325040-b2e5b1dc-ed54-4517-a909-fbe89c9d88be.png)

**Comment by weizhouapache** [comment]
> snapshots  template  volumes

@xuanyuanaosheng 
can you share the content of `/etc/cloudstack-release` in systemvm ?

When you upgrade cloudstack-management using official packages, a new systemvm template will be registered automatically.
Please check if there is a new systemvm template for 4.17.1.0 and it has been downloaded to all secondary storages.

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland @weizhouapache @slavkap 
The systemvm version is 4.16.1.
```
root@s-26640-VM:~# cat /etc/cloudstack-release 
Cloudstack Release 4.16.1 Mon 31 Jan 2022 10:02:56 AM UTC

----------------------------------------------------------------------------
root@v-26641-VM:~# cat /etc/cloudstack-release 
Cloudstack Release 4.16.1 Mon 31 Jan 2022 10:02:56 AM UTC

```
![image](https://user-images.githubusercontent.com/4197714/196375787-0a03557b-f9f4-49f2-949e-9a3f3ce73418.png)


I have do as below steps in cloudstack management node:
1.  download: systemvmtemplate-4.17.0-kvm.qcow2.bz2
2.  mount second storage node to management node: 
``` 
mount 10.26.246.10:/image /image
```
3.  /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /image -f systemvmtemplate-4.17.0-kvm.qcow2.bz2 -h kvm -F

But I think it is failed.  How to upgrade the systemvm template manually?

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland @weizhouapache @slavkap Any idears?

**Comment by weizhouapache** [comment]
> @DaanHoogland @weizhouapache @slavkap The systemvm version is 4.16.1.
> 
> ```
> root@s-26640-VM:~# cat /etc/cloudstack-release 
> Cloudstack Release 4.16.1 Mon 31 Jan 2022 10:02:56 AM UTC
> 
> ----------------------------------------------------------------------------
> root@v-26641-VM:~# cat /etc/cloudstack-release 
> Cloudstack Release 4.16.1 Mon 31 Jan 2022 10:02:56 AM UTC
> ```
> 
> ![image](https://user-images.githubusercontent.com/4197714/196375787-0a03557b-f9f4-49f2-949e-9a3f3ce73418.png)
> 
> The cloudstack management node version:
> 
> ```
> # rpm -qa | grep cloudstack
> cloudstack-management-4.17.1.0-1.el7.x86_64
> cloudstack-common-4.17.1.0-1.el7.x86_64
> ```
> 
> I have do as below steps in cloudstack management node:
> 
> 1. download: systemvmtemplate-4.17.0-kvm.qcow2.bz2
> 2. mount second storage node to management node:
> 
> ```
> mount 10.26.246.10:/image /image
> ```
> 
> 3. /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /image -f systemvmtemplate-4.17.0-kvm.qcow2.bz2 -h kvm -F
> 
> But I think it is failed. How to upgrade the systemvm template manually?

@xuanyuanaosheng 
the script downloads the template to secondary storage and overwrite the last systemvm template.
but the references of the template on primary storage pools are not updated, which are save in `template_spool_ref` table
as a workaround, you can remove the records from `template_spool_ref` table (delete from template_spool_ref where template_id=xxxxxx). Please backup your database before the change.
After that, cloudstack will copy the systemvm template from secondary storage to primary storage pools when new systemvms/vrs are created.

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland @weizhouapache @slavkap

The Second storage config is `nfs://10.26.246.10/image`
```
# tree ./*
./tmpl
├── 1
│   ├── 3
│   │   ├── afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
│   │   └── template.properties
│   └── 4
│       └── template.properties
└── 2
    ├── 232
    │   └── template.properties
    ├── 247
    │   ├── 247-2-d800137d-4247-3e93-a3cb-915ba60c921e.iso
    │   └── template.properties
    └── 248
        ├── 4b1ec60e-f0d3-3307-a321-a13152959117.qcow2
        └── template.properties

7 directories, 8 files


# cat tmpl/1/3/template.properties 
filename=afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
description=SystemVM Template
hvm=false
size=453181440
qcow2=true
id=3
public=true
qcow2.filename=afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
uniquename=routing-3
qcow2.virtualsize=4194304000
virtualsize=4194304000
qcow2.size=453181440
```

The path is `afd37f36-3775-49b7-bd1e-1af1c52cfe1c`

and the mysql `template_spool_ref` related to primary storage is `c3098158-93e3-40b1-a3e4-882c0f2a47b5` and `dea9fed0-a166-45f3-b4d9-39edc1744ff6`

I delete the record using:
```
# DELETE from template_spool_ref WHERE local_path = 'c3098158-93e3-40b1-a3e4-882c0f2a47b5';
# DELETE from template_spool_ref WHERE local_path = 'dea9fed0-a166-45f3-b4d9-39edc1744ff6';
```
 I delete record in `template_spool_ref`  and delete the systemvm in cloudstack web ui.

But when the new systemvms started. 

![image](https://user-images.githubusercontent.com/4197714/197473741-be9edb1b-e343-4dbe-8c32-c94ce2551d59.png)

There is no  copy the systemvm template from secondary storage to primary storage pools when new systemvms/vrs are created.

**Comment by weizhouapache** [comment]
> @DaanHoogland @weizhouapache @slavkap
> 
> The Second storage config is `nfs://10.26.246.10/image`
> 
> ```
> # tree ./*
> ./tmpl
> ├── 1
> │   ├── 3
> │   │   ├── afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
> │   │   └── template.properties
> │   └── 4
> │       └── template.properties
> └── 2
>     ├── 232
>     │   └── template.properties
>     ├── 247
>     │   ├── 247-2-d800137d-4247-3e93-a3cb-915ba60c921e.iso
>     │   └── template.properties
>     └── 248
>         ├── 4b1ec60e-f0d3-3307-a321-a13152959117.qcow2
>         └── template.properties
> 
> 7 directories, 8 files
> 
> 
> # cat tmpl/1/3/template.properties 
> filename=afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
> description=SystemVM Template
> hvm=false
> size=453181440
> qcow2=true
> id=3
> public=true
> qcow2.filename=afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2
> uniquename=routing-3
> qcow2.virtualsize=4194304000
> virtualsize=4194304000
> qcow2.size=453181440
> ```
> 
> The path is `afd37f36-3775-49b7-bd1e-1af1c52cfe1c`
> 
> and the mysql `template_spool_ref` related to primary storage is `c3098158-93e3-40b1-a3e4-882c0f2a47b5` and `dea9fed0-a166-45f3-b4d9-39edc1744ff6`
> 
> I delete the record using:
> 
> ```
> # DELETE from template_spool_ref WHERE local_path = 'c3098158-93e3-40b1-a3e4-882c0f2a47b5';
> # DELETE from template_spool_ref WHERE local_path = 'dea9fed0-a166-45f3-b4d9-39edc1744ff6';
> ```
> 
> I delete record in `template_spool_ref` and delete the systemvm in cloudstack web ui.
> 
> But when the new systemvms restarted. there is no new records in mysql
> 
> ![image](https://user-images.githubusercontent.com/4197714/197473741-be9edb1b-e343-4dbe-8c32-c94ce2551d59.png)
> 
> and the system vm version is still:
> 
> ```
> root@s-27372-VM:/usr/local/cloud# cat /etc/cloudstack-release 
> Cloudstack Release 4.16.1 Mon 31 Jan 2022 10:02:56 AM UTC
> root@s-27372-VM:/usr/local/cloud# ls /usr/local/cloud/
> root@s-27372-VM:/usr/local/cloud# 
> root@s-27372-VM:/usr/local/cloud# df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            640M     0  640M   0% /dev
> tmpfs           262M  468K  262M   1% /run
> /dev/vda6       3.2G  1.3G  2.0G  40% /
> tmpfs           655M     0  655M   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> /dev/vda1       366M   45M  322M  13% /boot
> tmpfs           131M     0  131M   0% /run/user/0
> ```
> 
> There is no copy the systemvm template from secondary storage to primary storage pools when new systemvms/vrs are created.


@xuanyuanaosheng 
can you check if the vm_template_id of the vm_instance is 3 ?

select vm_template_id from vm_instance where id=27372;

**Comment by xuanyuanaosheng** [comment]
@weizhouapache The sql result is
![image](https://user-images.githubusercontent.com/4197714/197485472-dc7bd4b5-668a-43ef-a8e0-aac242123678.png)

**Comment by weizhouapache** [comment]
> @weizhouapache The sql result is ![image](https://user-images.githubusercontent.com/4197714/197485472-dc7bd4b5-668a-43ef-a8e0-aac242123678.png)

and more ?

select pool_id from volumes where instance_id=27372;
select * from template_spool_ref where template_id=3 and pool_id in (select pool_id from volumes where instance_id=27372);

**Comment by xuanyuanaosheng** [comment]
@weizhouapache 

![image](https://user-images.githubusercontent.com/4197714/197487826-26b57acb-e445-48d3-b841-649e5102accb.png)

The result is empty:
![image](https://user-images.githubusercontent.com/4197714/197487987-d9f8d00f-f0ce-4273-b7ac-72cf0856177f.png)

**Comment by xuanyuanaosheng** [comment]
@weizhouapache I restart the cloudstack-agent server and find some new info:

please search `afd37f36-3775-49b7-bd1e-1af1c52cfe1c` and `s-27557-VM`

![image](https://user-images.githubusercontent.com/4197714/197490658-e53b7057-9adf-49ab-89ac-b04ad0b179ff.png)

[management-server.log](https://github.com/apache/cloudstack/files/9850420/management-server.log)

**Comment by weizhouapache** [comment]
> @weizhouapache I restart the cloudstack-agent server and has been restarted repeatedly. I find some new info:
> 
> ![image](https://user-images.githubusercontent.com/4197714/197494838-49e61449-de8f-4133-b421-3004c5179e89.png)
> 
> please search `afd37f36-3775-49b7-bd1e-1af1c52cfe1c` and `s-27557-VM` key word
> 
> ![image](https://user-images.githubusercontent.com/4197714/197490658-e53b7057-9adf-49ab-89ac-b04ad0b179ff.png)
> 
> [management-server.log](https://github.com/apache/cloudstack/files/9850420/management-server.log)
> 
> I find logs in cloudstack ：
> 
> ```
> 2022-10-24 17:14:06,876 INFO  [c.c.v.VirtualMachineManagerImpl] (secstorage-1:ctx-d8dfa196) (logid:78bc21f1) allocating virtual machine from template:afd37f36-3775-49b7-bd1e-1af1c52cfe1c with
>  hostname:s-27557-VM and 3 networks
> ```

the file name on secondary storage is `c3098158-93e3-40b1-a3e4-882c0f2a47b5.qcow2` in database, but actual file name is `afd37f36-3775-49b7-bd1e-1af1c52cfe1c.qcow2`

select * from template_store_ref where template_id=3;

you may need to update `install_path` in the table.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache 
![image](https://user-images.githubusercontent.com/4197714/197496191-247f0b60-3034-4ed1-96b8-e2b31284c864.png)

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland @weizhouapache @slavkap
It has worked as expected.
![image](https://user-images.githubusercontent.com/4197714/197499811-b3af8849-c06c-4dd4-977e-9cdd3a420333.png)

Thank you, and I will close this issue.

I think a new featue: Cloud you please add a button to update the system vm template manually ?

**Comment by weizhouapache** [comment]
> 

@xuanyuanaosheng 
I think the cloudstack release note has descibred how to register the new systemvm template.
(cloud-install-sys-tmplt is not recommended for existing platforms).
from 4.17, the systemvm templates have been bundled with the cloudstack-management package so users do not need to register new systemvm template. If needed, new systemvm template can still be registered
- register template
- change template type to SYSTEM
- update router.template.xx in global setting to the new template

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  OK, Thanks
