### ISSUE TITLE
travis job 9 start showing intermetted failures recently

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#6830]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Testing, CI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~
submit or update a PR
~~~

##### EXPECTED RESULTS

~~~
all travis jobs pass successful
~~~

##### ACTUAL RESULTS

~~~
travis job 9 fails
~~~

**Comment by weizhouapache** [comment]
I noticed this issue few years ago.
sometimes travis works, sometimes not with error
```
=== TestName: test_02_deploy_vm_anti_affinity_group_fail_on_not_enough_hosts | Status : SUCCESS ===
=== TestName: test_02_deploy_vm_anti_affinity_group_fail_on_not_enough_hosts | Status : EXCEPTION ===
```

I have no idea why the test is executed twice. The second time we got the exception.

**Comment by rohityadavcloud** [comment]
Closing this/moving to https://github.com/apache/cloudstack/issues/7021
