### ISSUE TITLE
Please display System VMs's Template version like Virtual routers

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6831]
##### ISSUE TYPE

 * Improvement Request

![image](https://user-images.githubusercontent.com/4197714/196155321-839a2793-8b00-4311-b1ca-fd9651eeee35.png)

**Comment by Anish7575** [comment]
Hi, I would like to work on this issue. Can someone guide me how to approach this ?

**Comment by DaanHoogland** [comment]
@Anish7575 , The UI needs adapting to include this information from the output of the API `list systemvms`. If you are not familiar with what I am saying, you'll have to go through [the hackerbook](https://github.com/shapeblue/hackerbook) first.

**Comment by weizhouapache** [comment]
this requires not only the api response and UI changes, but also some java code changes to get the template version from system vms.
a bit difficult for new developers.

**Comment by rohityadavcloud** [comment]
The systemvms are limited in number versus the number of VRs etc you can in a zone. Currently the systemvm versions are listed on the resource view but on in the tabular view, I think we can simply show the agent version in the list view and in the resource view one can see the template already.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9011
