### ISSUE TITLE
VR reply packets - interface mismatch (VPC load balancer)

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6834]
This is similar as #6615 but different

Steps to reproduce the issue

- Advanced networking with at least 2 public ranges
- Create a VPC, VPC tier and a VM
- Acquire a public IP in different public range as VPC Source NAT IP
- Create Load balancer rule and add the VM to the load balancer rule (port 22)

ssh to the VM using public IP from another server (for example mgmt server)

The request and reply packets go through different interface

request (through eth3 /LB Public IP)
![image](https://user-images.githubusercontent.com/57355700/196378832-0c5c459b-4982-45ba-a123-ecc2a7a13f53.png)

reply (through eth1 / Source NAT)
![image](https://user-images.githubusercontent.com/57355700/196378881-fcfa5015-b058-42ac-93cb-d16fce111dcf.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.0
4.18
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@weizhouapache I tested with 4.17.1.0:
![image](https://user-images.githubusercontent.com/2486961/196748022-e12e93a1-192f-4acc-bcd0-4ccf452b9847.png)

**Comment by weizhouapache** [comment]
> @weizhouapache I tested with 4.17.1.0: ![image](https://user-images.githubusercontent.com/2486961/196748022-e12e93a1-192f-4acc-bcd0-4ccf452b9847.png)

@DaanHoogland 
did you ssh from the VR to the VM ?

**Comment by DaanHoogland** [comment]
> @DaanHoogland did you ssh from the VR to the VM ?

no, from home to the vm

**Comment by DaanHoogland** [comment]
@weizhouapache , reproduced and possible fix created.
