### ISSUE TITLE
Virtual Routers system vm is no starting

### ISSUE THREAD

**Issue by canghai908** [apache/cloudstack#6842]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
Virtual Routers vm is no starting 

##### CLOUDSTACK VERSION
OS:centos 7.9
cloudstack:4.17.0

##### OS / ENVIRONMENT
CEPH 15.6
cloudstack:4.17.0
libvirt-4.5.0-36.el7_9.5.x86_64

##### SUMMARY
![image](https://user-images.githubusercontent.com/1450994/197340546-01534baf-9c16-4781-8738-39d32d26f65d.png)

##### STEPS TO REPRODUCE
When I remote the kvm hypervisor,thg virtual routers system vm is no starting.
system vm up ok
![image](https://user-images.githubusercontent.com/1450994/197340762-52ce200e-90d9-4052-ab0b-70623d7c624a.png)
virtual routers system vm is hang
![image](https://user-images.githubusercontent.com/1450994/197340785-4ceac3e7-a6e3-47b2-a6d0-900358572201.png)
connect to vnc
![image](https://user-images.githubusercontent.com/1450994/197340793-e80f4444-f6e7-411e-8893-248c73f501ff.png)

**Comment by weizhouapache** [comment]
@canghai908 
are the systemvms running on same ceph storage pool ?

**Comment by canghai908** [comment]
yes， the systemvms running on same ceph storage pool。

Wei Zhou ***@***.***> 于2022年10月23日周日 17:13写道：

**Comment by weizhouapache** [comment]
@canghai908
- check if cloudstack-agent and management have all been upgrade to same version (4.17.0)
- create a new network and check again ?

**Comment by canghai908** [comment]
@weizhouapache cloudstack-agent and management are  same version (4.17.0).Now I update  cloudstack agent and management  to 4.17.1.0 the virtual routers system is work ok,but my some vm is hang like this.I don't know if it's cloudstack's problem or ceph's problem in the morning。

**Comment by canghai908** [comment]
@weizhouapache My problem solved！The problem is due to ceph's locks。look this article 
 https://www.cnblogs.com/zphj1987/p/14155644.html

**Comment by weizhouapache** [comment]
> @weizhouapache My problem solved！The problem is due to ceph's locks。look this article https://www.cnblogs.com/zphj1987/p/14155644.html I would like to know if cloudstack needs the exclusive-lock feature of rbd, and if not, can I disable this feature to avoid this problem from happening。

@canghai908 good ! 
thanks for update and sharing

for your question, maybe @wido can help.

**Comment by wido** [comment]
> > @weizhouapache My problem solved！The problem is due to ceph's locks。look this article https://www.cnblogs.com/zphj1987/p/14155644.html I would like to know if cloudstack needs the exclusive-lock feature of rbd, and if not, can I disable this feature to avoid this problem from happening。
> 
> @canghai908 good ! thanks for update and sharing
> 
> for your question, maybe @wido can help.

We should not want to disable exclusive-locking as this is an important feature of Ceph to prevent data corruption.

Who is holding the lock @canghai908 ? Why is another client locking this image on Ceph?

**Comment by canghai908** [comment]
@wido the vm images on ceph.The image is locke by cloudstack computer node
![image](https://user-images.githubusercontent.com/1450994/197531433-2db42140-af4f-4209-be21-9291485c947b.png)
The reason for the lockup is due to network issues and unexpected restart of the vm hypervisor machine. 
I rm the image lock
![image](https://user-images.githubusercontent.com/1450994/197532147-3a4b6160-f4bc-4385-8b06-80993e30c4c5.png)
The virtual machine starts normally
![image](https://user-images.githubusercontent.com/1450994/197532447-bc1f0c79-1668-439b-b45f-780116f93a88.png)

**Comment by wido** [comment]
Was the VM running on that compute node before? Did it crash?

the exclusive lock should timeout after a couple of minutes after which you can start the VM on a different host.

**Comment by wido** [comment]
> @wido
> 
> > Was the VM running on that compute node before? Did it crash?
> > yes.VM running on that compute node,the node is crash and the ceph cluster network also has a problem.
> > In my case the lock was not timeout. After manual remove lock it was fine. Excuse me, where is the timeout time of the lock configured?

How long did you wait? And was the other node really down?

Because the exclusive lock should be handed over to another node if the old one goes down. If that doesn't happen Ceph blocks because there is a potential data corruption risk.

**Comment by canghai908** [comment]
@wido 

> How long did you wait? And was the other node really down?

wait for 12 hours。other node really down by unexpected。

**Comment by wido** [comment]
> @wido
> 
> > How long did you wait? And was the other node really down?
> 
> wait for 12 hours。other node really down by unexpected。

That is odd, the exclusive lock should timeout and be handed over to the other client.

If that doesn't work something is wrong, but disabling exclusive locks should not be done.

That said, this seems like a Ceph issue and not a CloudStack issue.

**Comment by canghai908** [comment]
@wido Thank you!I will check the ceph cluster.
