### ISSUE TITLE
Create Template For Mikrotik With Cloud-Init Password Enable Feture

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#6847]
##### ISSUE TYPE

 * Question
 * Feature Idea

##### COMPONENT NAME
Create Template With CloudStack And Cloud-init
##### CLOUDSTACK VERSION

CloudStack 4.17.1.0

##### OS / ENVIRONMENT
ACS Distro" ubuntu 20
##### SUMMARY
I'm going to create a Mikrotik template in Cloudstack and I want to use CloudInit to set the parameters I need.
I did this via a script to configure the hostname with this command in mikrotik
 " /system/identity/set name=[:put ([/tool fetch url=http://data-server./latest/meta-data/local-hostname as-value output=user]->"data")]"
My question is, where does cloudstack store the automatically generated password like Hostname?
I could not find the saved cloud-init metadata files about password.
I'm going to take it and set it for the user via a script on my mikrotik template.

##### EXPECTED RESULTS
Find the cloud stack production password for the VM
##### ACTUAL RESULTS
i dont know wher is it

**Comment by DaanHoogland** [comment]
@ahmadamirahmadi007 the password is sent to the password server for the VM. That would be running in the VR for it's network. It is than exposed to the VM via a service. It is not stored in the DB. after it is returned through the API, CloudStack forgets all about it.

**Comment by ahmadamirahmadi007** [comment]
tnx

**Comment by weizhouapache** [comment]
@ahmadamirahmadi007 
fyi, you can put this script https://github.com/apache/cloudstack/blob/main/setup/bindir/cloud-set-guest-sshkey-password-userdata-configdrive.in in your template and make it auto-start.
It can get the VM password and VM userdata which are stored in CloudStack VR or ConfigDrive ISO.
