### ISSUE TITLE
VM memory usage is 99.9x% on XenServer/XCP-ng

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#6848]
The VM memory usage is always 99.9x% on XenServer or XCP-ng

![image](https://user-images.githubusercontent.com/57355700/197729083-4337019c-4722-43f4-a8bc-531aa4d3ca4c.png)

The actual VM usage is not

![image](https://user-images.githubusercontent.com/57355700/197729355-9bf10c71-ab14-44ef-8491-88e283049c04.png)

Tested with
- XenServer 8.1
- XCP-ng 8.2
- CentOS 7 vm
- CentOS 8 vm

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM
~~~

##### CLOUDSTACK VERSION

~~~
4.17
4.18
~~~

##### SUMMARY

XenServer 8.1 
XCP-ng 8.2

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
anyone has the same issue ?

**Comment by edikevich** [comment]
@weizhouapache Hi. I had same issue at previous job. We had XCP-NG 8.2. All VMs had 99% memory usage. VM were with and with out xen-tools

**Comment by weizhouapache** [comment]
> edikevich

@edikevich thanks for your reply.

Have you checked the value on XCP-ng Center or XenCenter ? I'd like to know it is an issue with cloudstack or xenserver/xcp-ng.

**Comment by edikevich** [comment]
@weizhouapache Sorry not now. I changed job) BUT! I remember that the values in XCP-ng Center ​​were correct. 
I think this is CS issue.

**Comment by rohityadavcloud** [comment]
Closing this as the PR is merged, thanks @weizhouapache (re-open if there's something else pending).
