### ISSUE TITLE
Exported metrics have a domain instead of the full path

### ISSUE THREAD

**Issue by vdombrovski** [apache/cloudstack#6859]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API / metrology
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.0
~~~

##### OS / ENVIRONMENT

Irrelevant

##### SUMMARY

Prometheus metrics are grouped by domain, however the domain name provided isn't the full path. This leads to some duplicate labels whenever your domain names aren't unique

##### STEPS TO REPRODUCE

1. Create a domain /ROOT/CUSTOMER_A/CLOUD
2. Create a domain /ROOT/CUSTOMER_B/CLOUD
3. Enabled prometheus metrics inside UI configuration and restart management
4. Gather Prometheus metrics (here demonstrated using curl): `curl "http://127.0.0.1:9595/metrics"`

##### EXPECTED RESULTS

Either a full path or the parent is reported

~~~
cloudstack_domain_resource_count{domain="CLOUD", path="/ROOT/CUSTOMER_A/CLOUD", type="cpu"} 0
cloudstack_domain_resource_count{domain="CLOUD", path="/ROOT/CUSTOMER_B/CLOUD", type="cpu"} 0
~~~

##### ACTUAL RESULTS

~~~
cloudstack_domain_resource_count{domain="CLOUD", type="cpu"} 0
cloudstack_domain_resource_count{domain="CLOUD", type="cpu"} 0
~~~

**Comment by vdombrovski** [comment]
Looks like changing domain.getName() into domain.getPath() should be sufficient to get the proper domain names:

https://github.com/apache/cloudstack/blob/4e2f461b3154c35c92dff71442cffacf240a903e/plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterImpl.java#L371

**Comment by DaanHoogland** [comment]
no, not as far I I can see. we can skip it if there isn´t a simple fix.

**Comment by vdombrovski** [comment]
I've detailed the proposed fix above. I'd like to know if it is OK having this breaking change to be more accurate on the reported labels, or whether it's better to add another "path" label to the existing metric without changing the name label.

**Comment by DaanHoogland** [comment]
To tell you the truth @vdombrovski , I don´t know how this is used and whether it would break anything. It seems alright to me, but in my experience even changing log messages can break things (like monitorring systems)

**Comment by vdombrovski** [comment]
I've issued a fix in the above PR, please let me know if this change looks OK.
