### ISSUE TITLE
Guest Network - Dedicated VXLAN Range

### ISSUE THREAD

**Issue by remipcomaite** [apache/cloudstack#6871]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API, UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0, 4.17.1
~~~

##### CONFIGURATION
Advanced Networking

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I can't add a dedicated VXLAN range

##### STEPS TO REPRODUCE
 * Edit the guest physical network from the UI interface
 * Add a dedicated VLAN/VNI range

![image](https://user-images.githubusercontent.com/114096594/200093597-686e46eb-9da4-4b53-a048-a57d206d0668.png)

##### EXPECTED RESULTS
A new dedicated VXLAN range

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/114096594/200093475-59b279e9-a793-4640-9212-00008e5900c0.png)

**Comment by DaanHoogland** [comment]
thanks @remipcomaite , not sure if this is possible with the API. Could you try that? If so it is a UI feature to implement.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7215
