### ISSUE TITLE
listVirtualMachinesMetrics doesn't filter VMs by Host ID

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6886]
listVirtualMachinesMetrics with listall=true and hostid param returns all the VMs and doesn't return VMs by provided host ID. However, listVirtualMachines works.

Found via UI in env with more than 1 host. As root admin go to Infra -> hosts -> select a host -> see instances on this host.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.10
~~~

**Comment by rohityadavcloud** [comment]
cc @rahulbcn27

**Comment by shwstppr** [comment]
@rohityadavcloud is this same as https://github.com/apache/cloudstack/issues/6756?

**Comment by rohityadavcloud** [comment]
Not entirely sure @shwstppr - this is about the list API response; list API not filtering based on provided API param

**Comment by rohityadavcloud** [comment]
Closing as addressed by @shwstppr in his PR https://github.com/apache/cloudstack/pull/6851

**Comment by DaanHoogland** [comment]
@rohityadavcloud #6851 is not merged yet. should this be closed?
