### ISSUE TITLE
Slow mysql query encountered when browsing the Network Tab

### ISSUE THREAD

**Issue by s-seitz** [apache/cloudstack#6888]
When using a broader IP Range (e.g multiple /16), a particular query is getting slow:

~~~
SELECT COUNT(user_ip_address.public_ip_address) FROM user_ip_address  INNER JOIN vlan ON user_ip_address.vlan_db_id=vlan.id WHERE user_ip_address.data_center_id  = 1 AND  (vlan.vlan_type = 'DirectAttached' );
~~~

##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
API, Mysql Backend
-->

##### CLOUDSTACK VERSION
4.17.1.0

##### CONFIGURATION
Advanced Networking, VLAN isolation

##### OS / ENVIRONMENT
Ubuntu 22.04 LTS

##### SUMMARY
When using a broader IP Range (e.g multiple /16), a particular query is getting slow:

~~~
SELECT COUNT(user_ip_address.public_ip_address) FROM user_ip_address  INNER JOIN vlan ON user_ip_address.vlan_db_id=vlan.id WHERE vlan.vlan_type = 'DirectAttached' AND user_ip_address.data_center_id  = 1  AND user_ip_address.state != 'Free'  AND user_ip_address.removed IS NULL;
~~~

This could be resolved by adding a (missing) key:
```
ALTER TABLE `user_ip_address` ADD KEY `fk_user_ip_address__state` (`state`);
```

##### STEPS TO REPRODUCE
Having a few /16 IPv4 Ranges assigned,
Enable mysql slowlog with a timeout of e.g. 2 seconds, and watch it happen.

##### EXPECTED RESULTS
Having the result faster.

##### ACTUAL RESULTS
Waiting for the result for about 2 seconds. (At least for my setup)

**Comment by rohityadavcloud** [comment]
Is this critical/blocker issue @DaanHoogland ?

**Comment by DaanHoogland** [comment]
@rohityadavcloud , for anybody using /16 nets it is a blocker and I don´t know a workaround. I would say it is critical. Any reason it would not be?

**Comment by DaanHoogland** [comment]
@s-seitz I am assuming you tested this to resolve your issue?
If not please try with PR #7028
