### ISSUE TITLE
Hosts marked unavailable due to different CPU frequencies using host capabilities

### ISSUE THREAD

**Issue by MejdiB** [apache/cloudstack#6914]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME
~~~
Agent
~~~

##### CLOUDSTACK VERSION
~~~
4.17.1
~~~

##### CONFIGURATION
Cloudstack 4.17.1 Environment Advanced Zone with Security Groups. One Computing Cluster consists of AMD EPYC CPUs based on Rome Architecture

##### OS / ENVIRONMENT
RHEL 8 is used for cloudstack management servers and hosts.

##### SUMMARY
With version 4.17, Cloudstack seems to derive the cpu frequency from `virsh capabilites` (https://github.com/apache/cloudstack/issues/6680). With the new update, we experience strange behavior across our CPU hosts based on AMD EPYC Rome CPUs. A lot of hosts are marked "unavailable", due to differences in the CPU frequency:

Example output Host A:
~~~
  <host>
    <uuid>948dfa00-7553-11eb-8000-ac1f6b365290</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>EPYC-Rome</model>
      <vendor>AMD</vendor>
      <microcode version='137367629'/>
      <counter name='tsc' frequency='2800000000'/>
      <topology sockets='1' dies='1' cores='24' threads='2'/>
~~~

Example output Host B (not available for VMs):
~~~
  <host>
    <uuid>34d92400-753e-11eb-8000-ac1f6b3675d4</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>EPYC-Rome</model>
      <vendor>AMD</vendor>
      <microcode version='137367629'/>
      <counter name='tsc' **frequency='2799999000'/**>
      <topology sockets='1' dies='1' cores='24' threads='2'/>
~~~

Starting a VM on Host B would result in the following error:
~~~
2022-11-17 16:33:06,369 INFO  [utils.linux.KVMHostInfo] (Agent-Handler-1:null) (logid:) Fetching CPU speed from "host capabilities"
2022-11-17 16:33:06,375 INFO  [utils.linux.KVMHostInfo] (Agent-Handler-1:null) (logid:) Retrieved value [2799999000] from "host capabilities". This corresponds to a CPU speed of [2799] MHz.
~~~

lscpu, however, displays the value of 2800 MHz on all hosts:
~~~
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
BIOS Vendor ID:      Advanced Micro Devices, Inc.
CPU family:          23
Model:               49
Model name:          AMD EPYC 7402 24-Core Processor
BIOS Model name:     AMD EPYC 7402 24-Core Processor                
Stepping:            0
CPU MHz:             3345.701
CPU max MHz:         2800,0000
CPU min MHz:         1500,0000
BogoMIPS:            5600.24
Virtualization:      AMD-V
L1d cache:           32K
~~~

**Comment by weizhouapache** [comment]
@MejdiB what's the cpu speed of the vm ? 2800 ?

**Comment by MejdiB** [comment]
@weizhouapache Yes, since ACS 4.15.1 we worked with a Compute Offering with 2800 MHz.

**Comment by weizhouapache** [comment]
> @weizhouapache Yes, since ACS 4.15.1 we worked with a Compute Offering with 2800 MHz.

@MejdiB 
as a workaround, can you add `host.cpu.manual.speed.mhz=2800` in the agent.properties and restart cloudstack-agent ?

**Comment by MejdiB** [comment]
@weizhouapache It worked indeed, the hosts are marked as available again. I have migraated one VM to a host and it also worked. Thanks for the workaround!
