### ISSUE TITLE
Failed to start kvm VRVM correctly

### ISSUE THREAD

**Issue by hooklee2000** [apache/cloudstack#6915]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME
 VR

##### CLOUDSTACK VERSION
main,4.18-vm-autoscaling

##### CONFIGURATION
advanced networking,

##### OS / ENVIRONMENT
CentOS7

##### SUMMARY
  We tested current [4.18-vm-autoscaling](https://github.com/apache/cloudstack/tree/4.18-vm-autoscaling) branch 4.18.0.0-SNAPSHOT  on 2022-11-17. Using kvm systemtemplate4.17.0 which modified cloudstack-release to 4.18.0，we found VR vm disappeared in ui.
  Using ssh connected the VR vm under agent host, it had console proxy java process, so acted as CPVM wrongly.

##### STEPS TO REPRODUCE
  We pulled  [4.18-vm-autoscaling](https://github.com/apache/cloudstack/tree/4.18-vm-autoscaling) branch on 2022-09-26, it worked well. Then we pulled on 2022-11-17, it failed cause VR cannot start.
  system vms
![图片](https://user-images.githubusercontent.com/52850777/202640290-e2104023-8b3e-4fd9-ba31-dd1ad7517c92.png)
  virtual router vms
![图片](https://user-images.githubusercontent.com/52850777/202640452-39324ae7-6a48-4d32-a3ec-99691003ae15.png)
view console, url is http://10.2.40.59/resource/noVNC/vnc.html?autoconnect=true&port=8080&token=F6IDkA3EnAfclsOgXqbytvUsEbKgC2jAWuP6ybG5HyqNgyR2fAwSFn9BbsCjgC28jQTR5O5v84f-T18N5Xmj-_otcsNv3I7sYLl9dN7HbM5LeVbxzaoG19e4DjEcVklBnN7_QclFRuV7NE-X9cp0YYLd9w6eWdQEjGKPvc4CxJaPqcZDn53gXVIUuj2-l7aTK7Wf4bnMnJ41oLNP39kqCaHiwJXskke7ciEcpIWzIJr3GXSGcfD67N5NOAXto0efGs2ZOKcpjkcw2B6cLj0_tepUNDdjehBq7TSHIjgWFu788xVA0Km2jY7HZbChqZ39icAfeNhL2SfVglKWg9BORTidPb51sYufJrbsv8V_MhfcMICUFZq-q5yPCtiLZTQpox_o65J5v-ed7r6Ft_rJbC3XbTwOv4P8nfNI_UZkCMfM41rLOyZRNBjhkFijXCHi7H9TX7v-93vsQq0cbK6Quw.
  Correctly it may be http://10.2.8.13:8080/client/console?cmd=access&vm=7545d234-0464-401b-a283-09c8d8b3f725
register iso timeout
![图片](https://user-images.githubusercontent.com/52850777/202640766-8ca83450-fa86-4ad8-a1bc-c8a40541ad9d.png)

   We also tested main branch  pulled on 2022-11-17, it had the same problem. How ever, Using virsh list  it had not vrvm, it only  had cpvm and  ssvm.
  4.18-vm-autoscaling had vrvm,but vrvm had cpvm java process.
  We tested all with a fresh installation.
By the way, using mysql 8, we must disable mysql's validate_password :

set global validate_password.policy=0;
set global validate_password.length=1;

otherwise cloudstack-setup-database printed error :
We apologize for below error:

cloudstack-setup-database  cloud:xxxxxx@127.0.0.1 --deploy-as=root:xxxxxx
***************************************************************
Encountering an error when executing mysql script
----------------------------------------------------------------------
table:
/usr/share/cloudstack-management/setup/create-database.sql

Error:
b"mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n"

Sql parameters:
{'user': 'root', 'passwd': 'xxxxxx', 'port': 3306, 'host': '127.0.0.1'}
----------------------------------------------------------------------
            
***************************************************************
Please run:

    cloudstack-setup-databases -h

for full help

##### EXPECTED RESULTS
starting vrvm correctly.

##### ACTUAL RESULTS
Failed to start vrvm or acted as CPVM wrongly.

**Comment by DaanHoogland** [comment]
@weizhouapache can you have a look?

**Comment by hooklee2000** [comment]
We tesed main branch [a63b2ab](https://github.com/apache/cloudstack/commit/a63b2aba7aa3948f78d280a356c550c6638a137b), view console and register iso all worked well. we  found we used http not https to register iso, cloudstack default need https.
Howerver , it has not virtual router under client ui and virsh list.

**Comment by weizhouapache** [comment]
@hooklee2000 
thanks for your update
