### ISSUE TITLE
The cloudstack version 4.17.1.0 Second storage only has S3 

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6920]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
- UI
- Second Storage

##### CLOUDSTACK VERSION

cloudstack version 4.17.1.0

##### SUMMARY
The second storage can only has s3

##### EXPECTED RESULTS
![image](https://user-images.githubusercontent.com/4197714/203682965-cedad215-dfb9-4dd0-bf4f-b38f99dd0f6e.png)

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/4197714/203682671-0ddf1139-7460-4754-b590-2398561d9e88.png)

**Comment by hooklee2000** [comment]
We used kvm, it worded well. Which provider ( kvm, vmware,xen...) did you choose?

**Comment by xuanyuanaosheng** [comment]
@hooklee2000   We also use kvm.

**Comment by xuanyuanaosheng** [comment]
@hooklee2000  

I reset the environment using
## cloudstack 测试环境重置步骤：
```
# systemctl stop cloudstack-management.service

# cloudstack-setup-databases cloud:password@localhost --deploy-as=root:12345

# cloudstack-setup-management

# systemctl start cloudstack-management.service

# systemctl status cloudstack-management.service
```

**Comment by xuanyuanaosheng** [comment]
I  will close this issue
