### ISSUE TITLE
VMs using strict host affinity cannot be started

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#6933]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When all VMs using the same strict host affinity group are stopped, they cannot be started anymore.

##### STEPS TO REPRODUCE

~~~
1. Create a new strict host affinity group
2. Deploy two VMs which use this affinity group
3. Stop both VMs
4. Try to start any of the VMs
~~~

##### EXPECTED RESULTS

~~~
The VMs should start normally.
~~~

##### ACTUAL RESULTS

~~~
The VMs cannot be started anymore. 
~~~

**Comment by vladimirpetrov** [comment]
LGTM based on manual testing.

**Comment by vladimirpetrov** [comment]
Reopening since #6936 is still not closed.

**Comment by DaanHoogland** [comment]
guess it is closed now @vladimirpetrov ?
