### ISSUE TITLE
Xcp-ng 8.2.1 - issues reverting to vm snapshot

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#6941]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Vm restore
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.0
~~~

##### CONFIGURATION

Advanced Networking

##### OS / ENVIRONMENT

Ubuntu server 20.04

##### SUMMARY

When trying to restore a "disk" vm snapshot and vm is poweroff i have the following message

![0-02-05-e01893be44079cb86b45ad152a3b507ff7dd27d7b995f9416b0a92e0ac7e4cc4_e6fab0de0573277d](https://user-images.githubusercontent.com/25532758/205231554-aac2a21f-acda-4df4-b1e8-4348d7d644cd.jpg)

and from the cs logs

![0-02-05-2156f986e60bfd407fb9a5fa9d2a803e9804c45d28d1722b88f23f0e39f7362d_d8f125d0384ac741](https://user-images.githubusercontent.com/25532758/205231631-559c91b8-3a11-4f0f-a0bb-4ed9e0f3e9a1.jpg)

When trying to restore a "disk" vm and the vm is powered off from console i have the following message

![0-02-05-783b345223258c4eee84888d8861429b1f552fa233536ac90152e9141ab0359d_45cd3ca2ad89b7cb](https://user-images.githubusercontent.com/25532758/205231770-a153346f-3089-400d-b985-6adc75e66518.jpg)

Which is normal is some consideration

##### STEPS TO REPRODUCE

~~~
Create a vm, take a disk snapshot and try to restore.
You will have the error i describe
~~~

##### EXPECTED RESULTS

~~~
Restore vm to snapshot
~~~

##### ACTUAL RESULTS

~~~
Error messages
~~~

**Comment by DaanHoogland** [comment]
@AlexanderKgr you can revert a disk to a disk snapshot and a vm to a vm snapshot. It seems you are trying to revert a vm to a disk snapshot. Is that correct?
Also you are describing in both examples restoring a powered off vm to a disk snapshot .
Am I misunderstanding your scenarios?

**Comment by AlexanderKgr** [comment]
Anyone?

**Comment by DaanHoogland** [comment]
@AlexanderKgr it might help to ask on the [users mailing list](mailto:users@cloudstack.apache.org)

**Comment by weizhouapache** [comment]
@AlexanderKgr 
guest os mappings for 'Ubuntu 20.04 LTS" are missing for xenserver and vmware.
please update the template guest os type to "Ubuntu 18.04 LTS" and retry.
I will create a fix

**Comment by weizhouapache** [comment]
the os mappings were added in #4672, but it was broken by #5911
fix: #7095

**Comment by MartinEmrich** [comment]
I experienced this with ACS 4.18.1 and XCP-ng as a hypervisor.

````
(i-39-6822-VM_VS_20231020072617) Revert VM: i-39-6822-VM to snapshot: i-39-6822-VM_VS_20231020072617 failed due to Hypervisor com.cloud.hypervisor.xenserver.resource.XenServer650Resource doesn't support guest OS type Debian GNU/Linux 12 (64-bit). you can choose 'Other install media' to run it as HVM
````

The message is IMHO wrong, the VM with Debian 12 worked fine before.

Could you reopen the issue? Or shall I create a new one?

**Comment by weizhouapache** [comment]
@MartinEmrich 
please create a new issue and link to this. thanks

**Comment by MartinEmrich** [comment]
@weizhouapache done: https://github.com/apache/cloudstack/issues/8123
