### ISSUE TITLE
WebUI: Unable to create new account / user when the domain count is larger than 500

### ISSUE THREAD

**Issue by zap51** [apache/cloudstack#6945]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
WebUI
~~~

##### CLOUDSTACK VERSION

~~~
4.16, 4.17
~~~

##### CONFIGURATION

~~~
Advanced Networking
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu 20.04 LTS on both Management and Hypervisors
~~~

##### SUMMARY

~~~
WebUI and API doesn't list the appropriate domain to select the "Domain" when creating the account on the account creation wizard.
~~~

##### STEPS TO REPRODUCE

~~~
From WebUI:

1. Make sure the number of domains present are 501 or more.
2. Create a domain named "test-domain-0011", assume the domain count after the creation is "502".
3. In our case, the number of domains are `560`.
4. Go to the "Add Account" and fill the required information.
5. In the "Domain", search for "test-domain-0011", it doesn't get listed.

From API:

1. Once the "test-domain-0011" is created from the UI, list using
`$ cmk list domains listall=true`

lists only first 500 entries.
~~~

##### EXPECTED RESULTS

~~~
1. WebUI should additionally perform "pagesize=-1" when doing the ListDomains API. 
2. This is not the current behaviour now. ListDomains API doesn't specify "pagesize=-1" or any relevant ones.
~~~

##### ACTUAL RESULTS

~~~
1. WebUI doesn't list the domain "test-domain-0011" when searched in the "Add Account" wizard.
2. API is the only approach now.
~~~

**Comment by zap51** [comment]
Update:
    It's applied everywhere where ListDomains API is used by the WebUI. I've tested with the creation of Network Offering, which fails to find the domain.

**Comment by zap51** [comment]
@DaanHoogland Is there a way we can fix this in the release 4.16.1.0 itself? Because we're unable to perform anything that includes ListDomains API on the WebUI. Please suggest.

**Comment by shwstppr** [comment]
@zap51 you increase global setting, `default.page.size`
It must be set to 500 currently.
Maybe we need to improve the UI/UX in such cases when a large number of resources are returned.

**Comment by zap51** [comment]
Thank you very much @shwstppr. Wondering how I forgot this global configuration option. Shall I go ahead and close this issue?

**Comment by DaanHoogland** [comment]
@zap51 you can close if you feel it is adequately handled. If not, please add a description of how functionality should be changed. (hope @shwstppr's pointer indeed fixed it for you)

**Comment by zap51** [comment]
Yes, that fixed it for me. Thanks @shwstppr and @DaanHoogland. Closing this issue.
