### ISSUE TITLE
Cross-account VPC network

### ISSUE THREAD

**Issue by elShiaLabeouf** [apache/cloudstack#6950]
Hi! 

I couldn't find forums or discord channels related to Cloudstack, so I'm posting my quick question here.

I'm a new Cloudstack user, trying out VPC network concept following a [leaseweb guide](https://kb.leaseweb.com/products/elastic-compute/managing-apache-cloudstack-network) and bumped into an issue: 

Am I correct that If a user creates a VPC network, a user in another account can’t use it or see it when provisioning a VM ?

**Comment by weizhouapache** [comment]
@elShiaLabeouf 
You can add network permissions for the other accounts.
Please refer to https://www.shapeblue.com/manage-network-permission/

**Comment by DaanHoogland** [comment]
@elShiaLabeouf other than posting here you can ask questions on the [mail list](mailto:users@cloudstack.apache.org)

**Comment by weizhouapache** [comment]
currently cloudstack does not support share VPC or VPC tiers to another accounts.
(only isolated/L2 networks and account-scope shared networks can be shared to other accounts in same domain)

This is a new feature.

**Comment by rohityadavcloud** [comment]
@elShiaLabeouf you're right, VPCs are owned by accounts. If you require the VPC to be created/used between various accounts you can create such VPCs in projects to which one or more accounts have access to. In newer ACS 4.18+ releases, there is a network permission feature (I'm not sure if it's for VPC but certainly for isolated networks), wherein an account can share their network to other account(s).

Hope this helps. If you've further questions, pl discuss them on our users@ mailing list. https://cloudstack.apache.org/mailing-lists.html thanks.
