### ISSUE TITLE
import a VM only adds 1st NIC

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#6951]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM ingestion
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1
~~~

##### CONFIGURATION

VMware

##### SUMMARY

When importing an unmanaged VM it only adds the first NIC, if the VM has more than one it will end up only with one in CloudStack

##### STEPS TO REPRODUCE

~~~
1. Create a VM with 3 networks
2. Unmanage the VM
3. Import the VM with auto networking selection
~~~

##### EXPECTED RESULTS

~~~
all 3 nics are configured 
~~~

##### ACTUAL RESULTS

~~~
just 1. 
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6953

**Comment by rohityadavcloud** [comment]
@borisstoyanov I realised just after merging this hasn't been manually tested by you or @vladimirpetrov but I see testing from @shwstppr, pl re-open if this should require another round of testing 🙏
