### ISSUE TITLE
Make git-pr script run with python3

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6955]
The git-pr script requires python2, we need to migrate it to be compatible with either both py2/py3 or just py3.
https://github.com/apache/cloudstack/blob/main/tools/git/git-pr

**Comment by rohityadavcloud** [comment]
cc @DaanHoogland

**Comment by DaanHoogland** [comment]
ah, I'd been looking at this as well, thanks for reminding @rohityadavcloud : #6961

**Comment by rohityadavcloud** [comment]
Thanks @DaanHoogland

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6961
