### ISSUE TITLE
Please add an IP format verification function

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#6958]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
* VPN
* UI

##### CLOUDSTACK VERSION
CloudStack 4.17.1.0 

##### SUMMARY
If the configuration `remote.access.vpn.client.iprange` is set not right the cloudstack web UI will crash.  The cloudstack web UI  will be crashed when restart cloudstack-management.

This problem is only be solved by modifying the database.

##### STEPS TO REPRODUCE

1.  Set the remote.access.vpn.client.iprange to : `10.64.94..1 - 10.64.95.250` , The IP format is not right.

![image](https://user-images.githubusercontent.com/4197714/206346360-6fab04ff-5dc5-4e70-8580-0e6ffeebf82f.png)

2,  Restart the cloudstack-management

**Comment by soreana** [comment]
@xuanyuanaosheng thanks for raising this issue.
Unfortunately, a global setting value validation is not supported in the Cloudstack, you can set anything there.

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng , are you sure you can not resolve the situation without DB change? i.e. calling the API [update configuration](https://cloudstack.apache.org/api/apidocs-4.17/apis/updateConfiguration.html )

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland Yes,  This problem is only be solved by modifying the database.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7415
