### ISSUE TITLE
UI Bug: IP assignment in deploying a VM

### ISSUE THREAD

**Issue by soreana** [apache/cloudstack#6974]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
Main, 4.17, 4.17.2
~~~

##### SUMMARY

When you set a name for a VM in deployment tab, the custom IP address will be removed. For more info checkout the following gif.

https://user-images.githubusercontent.com/9499410/207056253-702ddb63-c1f5-485b-9cdf-b57fb298ec54.mov

##### STEPS TO REPRODUCE

~~~
1. Try to deploy a virtual machine.
2. Add a custom IP in the box.
3. Assign a name to the VM.
4. The IP is removed.
5. Input the IP again and deploy the VM
6. VM deployed with a different IP
~~~

##### EXPECTED RESULTS

~~~
Appropriate IP assigned to the VM
~~~

##### ACTUAL RESULTS

~~~
Cloudstack pick the first free IP in the range and assign it to the VM.
~~~

**Comment by DaanHoogland** [comment]
@soreana are you working on a fix for this?

**Comment by soreana** [comment]
@DaanHoogland Not actively, I'm not good at VueJS, I appreciate any help :)
