### ISSUE TITLE
F5 network plugin not included in 4.17 release

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6976]
While cutting 4.17.2.0 RC1, I found that F5 network plugin isn't included in the source build (to fix/bump the version). It appears this was incorrectly removed from the community releases due to this: https://github.com/apache/cloudstack/pull/5993/files the build system no longer has rules to add the f5 network plugin either via client/pom.xml or plugins/pom.xml. This plugin therefore also doesn't participate in the maven build process. This is embarrassing if anybody still uses this and we've removed it from CloudStack 4.17 release without any due process.

cc @DaanHoogland @nvazquez

**Comment by DaanHoogland** [comment]
Think we should deprecate it effective immediately. There is no-one supporting f5 and no-one asking about it either.
