### ISSUE TITLE
Volumes fail to detach on VMware VM imported in CloudStack which has space in its name

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6992]
When VM has space in its name, volume fail to attach/detach to such VMware VMs imported in CloudStack.
Exception like following is seen:
```
java.io.IOException: Server returned HTTP response code: 400 for URL: https://10.0.33.178/folder/space test/space test_30.vmdk?dcPath=Trillian&dsName=fd54f3559fe43f60b8694fe4ccac777f
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
```

The temporary workaround is to unmanage the imported VMware VM in CloudStack, rename the VM on vCenter (remove space in its name and also in the name of the folder/vmdk file) and re-import the VM in CloudStack. VMware KB on renaming VM: https://kb.vmware.com/s/article/1029513

Also consider the case for vMotion/migration of such VMs (with spaces) (ref an old discussion: https://communities.vmware.com/t5/VI-VMware-ESX-3-5-Discussions/Storage-VMotion-How-to-cope-with-spaces-in-VM-name/td-p/725955)

**Comment by DaanHoogland** [comment]
fixed by #6989
