### ISSUE TITLE
Root volume of system vms is being listed

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#6993]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API/UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 [main]
~~~

##### EXPECTED RESULTS

~~~
Volumes of system VMs/routers should not be listed to admin/user in Volumes tab
~~~

##### ACTUAL RESULTS

~~~
they are
~~~
![Screenshot 2022-12-15 at 10 34 21](https://user-images.githubusercontent.com/13551960/207811692-854d094c-c0c1-4f44-a2ec-4e55d17c223c.png)

**Comment by DaanHoogland** [comment]
@borisstoyanov I agree these should not be listed to normal users, but why not to admin users?

**Comment by borisstoyanov** [comment]
was this an improvement introduced by someone? if not it should be a regression?

**Comment by DaanHoogland** [comment]
are they shown to normal users, than yes. If not then I would call it an accidental improvement, if not planned.

**Comment by weizhouapache** [comment]
@borisstoyanov @DaanHoogland 
I just checked this issue, it is caused by some changes in #6491 

I will add a filter on UI

**Comment by DaanHoogland** [comment]
@weizhouapache will you filter it for everybody or only for normal users?
It seems valid to see it as an admin, to me.

**Comment by weizhouapache** [comment]
@DaanHoogland 
only root admin can list systemvm volumes.

I will add a filter only for root admins, which has two options:
- User: list only users' volumes. This is default
- All: list all volumes (users' volumes and systemvm volumes)

What do you think ?

**Comment by DaanHoogland** [comment]
sounds good, but should resource/domain admins not also be able to see those, or at least VR volumes)

**Comment by weizhouapache** [comment]
> sounds good, but should resource/domain admins not also be able to see those, or at least VR volumes)

@DaanHoogland 
The api parameter introduced in #6491 can only be used by root admin.

```
    @Parameter(name = ApiConstants.LIST_SYSTEM_VMS, type = CommandType.BOOLEAN, description = "list system VMs; only ROOT admin is eligible to pass this parameter", since = "4.18",
            authorized = { RoleType.Admin })
    private Boolean listSystemVms;
```

let's keep the same behaviour.
