### ISSUE TITLE
Deploy VM form doesn't handle the IP passed for NIC correctly

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#6997]
In the deploy VM form in 4.17.1, when IP is passed for a network it doesn't accept the right IP ending with 0.

When IP 10.97.22.80 or 10.97.22.90 is passed:

For example:
<img width="717" alt="Screenshot 2022-12-16 at 6 34 44 PM" src="https://user-images.githubusercontent.com/95203/208106510-a55ca158-6091-4bd4-86f6-d7e307dc624e.png">

The UI instead passes 10.97.22.8 or 10.97.22.9 by stripping the ending '0':

<img width="864" alt="Screenshot 2022-12-16 at 6 37 26 PM" src="https://user-images.githubusercontent.com/95203/208106618-ae127f8f-4bde-4e82-962a-994dd48f8a7b.png">

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1
~~~

**Comment by shwstppr** [comment]
@rohityadavcloud this should fix the issue https://github.com/apache/cloudstack/pull/6994

**Comment by DaanHoogland** [comment]
@rohityadavcloud can you see if @shwstppr is correct, please?

**Comment by vladimirpetrov** [comment]
LGTM, tested manually with isolated and shared networks with the latest 4.18 nightly build.
