### ISSUE TITLE
The 'LSI Logic Parallel' controller is not supported on Windows 10 

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7004]
The 'LSI Logic Parallel' controller' not supported on Windows 10 and may causes problems if we use it. https://kb.vmware.com/s/article/2004740

Please check if that's the case and should we need to update the guest OS mappings for Windows 10 on Vmware.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
4.16, VMware ESXi, 7.0.3
~~~

**Comment by DaanHoogland** [comment]
@rohityadavcloud can you describe a scenario in which this poses a problem, please?
Also I see three lsilogic adapters in our code:
```
public interface ScsiDiskControllerType {
    String LSILOGIC_PARALLEL = "lsilogic";
    String LSILOGIC_SAS = "lsilogicsas";
    String LSILOGIC_SAS_1068 = "lsisas1068";
    String BUSLOGIC = "buslogic";
    String VMWARE_PARAVIRTUAL = "pvscsi";
    String VIRTUAL_SCSI = "VirtualSCSI";
}
```
Are all three a problem or one specific type?

**Comment by rohityadavcloud** [comment]
I think the osdefault controller for Windows10 should be something it can work out of the box on VMware (I'm guessing the user who reported this to me suggests they can't use lsi logic parallel with Windows 10).

**Comment by weizhouapache** [comment]
@rohityadavcloud @DaanHoogland 
As I understand from https://kb.vmware.com/s/article/2004740, the problem is quite similar as windows vm on kvm.

on kvm, virtio driver is not installed by default in windows vm, users have to create vm with IDE disk, install virtio driver , update the guest os type to "Windows PV" and then stop/start the windows vm 

This is more likely a document issue, not source code.
We could improve the admin guide https://docs.cloudstack.apache.org/en/latest/adminguide/templates.html

**Comment by weizhouapache** [comment]
user needs to upgrade to 4.16.1.0 and above which includes #5910

**Comment by shwstppr** [comment]
@weizhouapache cc @rohityadavcloud do we still need documentation changes for this or the mentioned PR https://github.com/apache/cloudstack/pull/5910 fixes this?

**Comment by rohityadavcloud** [comment]
Yes thanks @shwstppr doc PR is all we need. Unless you think this can be address automatically in the code.

**Comment by shwstppr** [comment]
@rohityadavcloud  I've created a documentation PR, https://github.com/apache/cloudstack-documentation/pull/314

Though I tested the deployment of a VM with Windows 10 as guest OS and osdefault as controllers in ACS. In vCenter it seems to be using LSI Logic SAS
![Screenshot from 2023-05-10 13-58-05](https://github.com/apache/cloudstack/assets/153340/1220c0e4-5495-4124-99a6-0d63f786c4ce)

**Comment by rohityadavcloud** [comment]
Closing as doc PR was created/merged https://github.com/apache/cloudstack-documentation/pull/314
