### ISSUE TITLE
Github Actions Optimisations

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7010]
Followup from https://github.com/apache/cloudstack/pull/6956

Suggestions, optimisations to consider and implement:
- Reduce no. of jobs, for ex. run more component tests in a group (as github actions timeout is 6hrs), overall less runners
- Check for PR diff/changes and only run component tests if required (for example when java changes, or run tests by changes type)
- Run/skip UI tests if not UI change; or only run UI tests if UI changes only
- Explore pipeline and artifact upload/download, passing across jobs

Example pipeline can be:
Check type of changes, do we need to build UI or java code -> Do mvn -Dnoredist -Dsimulator build with unit tests -> if it passes -> run smoketests (2-4 runners) and integration tests (2-4 runners)

**Comment by DaanHoogland** [comment]
@rohityadavcloud, I don't agree with the "Reduce no. of jobs" part. I'd rather increase the number of jobs into smaller parts and have them be done quicker. It hardly matters for the total resources consumed, especially if we put the build in a separate job in a pipeline.

**Comment by rohityadavcloud** [comment]
I'm ideally in favour of not reducing the no. of jobs, however there's an Apache org level max. number of runners; for each PR this currently kicks 20+ runners concurrently.

**Comment by DaanHoogland** [comment]
I'll discuss this on the next builds meeting. I wonder if runners vs cpu load is an issue for github
