### ISSUE TITLE
Unable to migrate UEFI instances with XCP-NG

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7019]
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.17.2.0 
~~~

##### CONFIGURATION
~~~
Cloudsatck advanced zone without security groups, xcp-ng 8.2.1
~~~

##### OS / ENVIRONMENT
~~~
Cloudsatck on Oracle Linux 8 
~~~

##### SUMMARY
~~~
Unable to migrate UEFI instances with XCP-NG. But it is possible directly via XCP-NG 
~~~

##### STEPS TO REPRODUCE
~~~
Create UEFI inctance, try "Migrate instance to another host"
~~~

##### ACTUAL RESULTS

~~~
There is no available hosts to migrate instance
~~~

![8VRDsZSgEkeOueU](https://user-images.githubusercontent.com/92435079/209282743-29230b02-7c9e-40d6-8051-2da4baee1da7.png)

**Comment by slavkap** [comment]
@top-secrett, can you try to migrate the VM via CLI? I've seen that there are some limitations in the UI for cases that are implemented and work in CS

**Comment by top-secrett** [comment]
> @top-secrett, can you try to migrate the VM via CLI? I've seen that there are some limitations in the UI for cases that are implemented and work in CS

Can you help with it? I didn't work with CS CLI before

**Comment by slavkap** [comment]
You can follow the steps to install and setup the CLI from [cmk](https://github.com/apache/cloudstack-cloudmonkey/wiki/Getting-Started)

**Comment by shwstppr** [comment]
@slavkap cc @top-secrett when you say it could be a UI issue, does `findHostsForMigration` API return any host in this case for the VM?

**Comment by top-secrett** [comment]
@slavkap @shwstppr BIOS instances can migrate, problem with UIEFI
![photo_2022-12-23_14-32-18](https://user-images.githubusercontent.com/92435079/209329228-ba9ba797-dc4c-42c3-aae6-09a6eaa7e41c.jpg)

**Comment by top-secrett** [comment]
@slavkap @shwstppr today I've tryed to migrate UEFI instance via Cloudmonkey and it allows to migrate. There is no migrate function for UEFI only in CS UI

**Comment by shwstppr** [comment]
@top-secrett from what I understand it seems findHostsForMigration API which is used in UI to list the suitable hosts is not working correctly when the VM is using UEFI. I'll check that and update the issue accordingly
