### ISSUE TITLE
Fix Github Actions Simulator CI Failures

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7021]
After moving Github Actions, we found two runners consistently failing with, failures seen in tests:
test_acl_sharednetwork (for example https://github.com/apache/cloudstack/actions/runs/3764630739/jobs/6399260045)
test_tags (https://github.com/apache/cloudstack/actions/runs/3764630739/jobs/6399260616)

**Comment by DaanHoogland** [comment]
test_acl_sharednetwork should be fixed in #7033

**Comment by weizhouapache** [comment]
All are good now!
