### ISSUE TITLE
UI favicon and title of login page editable via config.json

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#7055]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2.0
~~~

##### SUMMARY

I would be nice to be able to change favicon of the UI and the title of the login page via config.json.
You are unable to change the favicon via config.json. It looks hard coded and points to cloud.ico.
You can edit the titles of the UI after login via appTitle, but this will not change the title of the login page. It looks like it is hard coded in index.html.

**Comment by abhinavs1920** [comment]
Please assign me this issue

**Comment by DaanHoogland** [comment]
go ahead @abhinavs1920, but please let us know if you abandon it.

**Comment by Harshitsoni2000** [comment]
Hi @DaanHoogland, is this issue still open? I am interested in working on this issue, and have created a PR for this as well.

**Comment by Harshitsoni2000** [comment]
Hi @DaanHoogland,
have created a PR - https://github.com/apache/cloudstack/pull/7418

**Comment by abhinavs1920** [comment]
I think Harshit has solved the issue already.

**Comment by rohityadavcloud** [comment]
PR has been merged https://github.com/apache/cloudstack/pull/7418 closing this
