### ISSUE TITLE
UI user icon not using primary-color setting

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#7056]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2.0
~~~

##### SUMMARY

After login into UI the top right user icon does not use @primary-color from theme section of config.json

**Comment by rahulbcn27** [comment]
I am working on it .

**Comment by rahulbcn27** [comment]
@sbrueseke  I could not reproduce this on main or 4.18 . Is this bug specific to 4.17.2.0?

**Comment by sbrueseke** [comment]
> @sbrueseke I could not reproduce this on main or 4.18 . Is this bug specific to 4.17.2.0?

I am not able to install 4.18 at the moment, so I cannot test it on this version.

This is how the html code looks like on 4.17.2:
`<span class="user-menu-avatar avatar ant-avatar ant-avatar-sm ant-avatar-circle" style="background-color: rgb(24, 144, 255); color: white;" data-v-46ea8cbc=""><span class="ant-avatar-string" style="transform: scale(1) translateX(-50%);">SB</span></span>`

It looks like background-color in styles is not beeing changed by the theme.
Can you maybe double-check the code on 4.18?

**Comment by sbrueseke** [comment]
@rahulbcn27 I updated our test installation to 4.18.0.0 and it looks like this issue is still present. 
I am talking about the small avatar icon at the top of the right corner:
![avatar](https://user-images.githubusercontent.com/23243455/226657545-8d90f028-5cd7-4652-9972-775d18456045.PNG)

html source code show that style tag has an attribute background-color which is set to the default value and not to the primary-color value. Can you please check this an verify it? Thank you!
