### ISSUE TITLE
VMs without uuid are not listing in the list virtual machines api call when ids parameter used.

### ISSUE THREAD

**Issue by soreana** [apache/cloudstack#7074]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### SUMMARY

Some of our old VMs data were missing in our dashboards. After digging that a little bit further we noticed a strange behaviour in the CloudStack 4.17. We have old VMs in our data center which don't have an UUID. Their uuid's field in DB is a long value. For simplicity I will call this vm `NO-UUID` from now on.

When I call `list virtualmachines` with `id` of `NO-UUID` it returns the correct VM. But when I pass `NO-UUID`'s id in the `ids` it returns nothing. Check the following cmk outputs for more info.

The issue exists with the remaining listing as well.

##### EXPECTED RESULTS

list virtualmachines returns the same results when it called with `id` or `ids`.

~~~
(local)  > list virtualmachines ids=11289 listall=true filter=id
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "11289"
    }
  ]
}
(local)  > list virtualmachines id=11289 listall=true filter=id
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "11289"
    }
  ]
}
(local)  >
~~~

##### ACTUAL RESULTS

list virtualmachines returns nothing with `ids` but it returns the vm with `id`.

~~~
(local)  > list virtualmachines ids=11289 listall=true filter=id
(local)  > list virtualmachines id=11289 listall=true filter=id
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "11289"
    }
  ]
}
(local)  >
~~~

**Comment by weizhouapache** [comment]
@soreana 
`ids` support only uuid. 

it is not a good idea to use long value `id`. You'd better use uuid instead of id.

**Comment by weizhouapache** [comment]
> @weizhouapache Unfortunately they don't have an `uuid`. See the following db output.
> 
> ```
> mysql> select id,uuid from user_vm_view where id = 11289 limit 1;
> +-------+-------+
> | id    | uuid  |
> +-------+-------+
> | 11289 | 11289 |
> +-------+-------+
> 1 row in set (0.01 sec)
> ```

@soreana 
hmm, it looks the vm was created more than 10 years ago (before cloudstack 4.1.0).
engine/schema/src/main/resources/META-INF/db/schema-40to410.sql:UPDATE `cloud`.`vm_instance` set uuid=id WHERE uuid is NULL;

I think it is ok to regenerate uuid.

**Comment by soreana** [comment]
@weizhouapache Thanks a lot.

I will update the uuid. I will close the ticket after confirming the expected behaviour.

**Comment by soreana** [comment]
@weizhouapache 

We followed the following procedure, which solved our issue.

0. Create a database backup
1. Get the VMs data in a (id, uuid, account_id, display_name) format
    1.1 generate a file containing all the failed VMs.
        select id,uuid,account_id, display_name from vm_instance where id = uuid and removed is null INTO OUTFILE '/tmp/incorrect_uuid.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' ;
2. Generate a uuid for each row in a (id, old_uuid, new_uuid, account_id, display_name) format
    2.1 Check if the uuid is unique
    2.2 If not unique generate a new one
3. Generate a sql file to update  CloudStack DB and other application that were dependent on the UUID of the VM.

**Comment by weizhouapache** [comment]
@soreana 
good you have solved the issue.

actually it can be done by a simple sql

`UPDATE vm_instance SET uuid=UUID() WHERE uuid=CAST(id AS CHAR);`

you can trust that uuid is unique.

**Comment by soreana** [comment]
@weizhouapache

That is cool, I didn't know that, thanks 👍
