### ISSUE TITLE
Every guest network has 1 ip that unknown allocated in first range

### ISSUE THREAD

**Issue by troke12** [apache/cloudstack#7079]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Network
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### CONFIGURATION

We have multiple guest network that has been linked with every physical network
- 172.16.200.1-172.16.200.50 on Guest Network A (Physical Network A)
- 172.16.500.1-172.16.500.50 on Guest Network B (Physical Network B)

Then we have 2 VM that has been finish setup with both guest network

Here the current configuration about our VM
- VM 1 has : 
  - 172.16.200.35 Guest Network A
  - 172.16.500.35 Guest Network B
- VM 2 has : 
  - 172.16.200.36 Guest Network A
  - 172.16.500.36 Guest Network B
 

##### SUMMARY

Then on that every ranges we check that : 
- 172.16.200.1 is Allocated
- 172.16.500.1 is Allocated

Both ip is reply when trying to ping but i cannot find which VM running with that

**Comment by weizhouapache** [comment]
@troke12 
Each (Shared) guest network which support dhcp/dns/userdata, has a virtual router which acts as the dhcp/dns/userdata server.
You can go to "Infrastructure" -> "Virtual routers" to get the details of the virtual routers.
