### ISSUE TITLE
Github Actions fail due to Error:  Java heap space

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7085]
```
Error:  Java heap space -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
```

I'm not sure how to address or fix this, so logging this for now.

This is seen when we do mvn builds, and esp for sonar/jacoco builds. Perhaps using a more aggresive/default GC could help?

**Comment by DaanHoogland** [comment]
Hvae you seen any special circumstances? like big diffs or new dirs/projects. is it more on 4.17 than 4.18 or vice versa?

**Comment by rohityadavcloud** [comment]
Not seen anymore, we should keep an eye.
