### ISSUE TITLE
Primate UI is missing core count for VM instances

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#7105]
It seems like at some point along the way we lost the core/cpu count in the Primate UI.
Currently only the combined GHz are displayed which is not very informative, see screenshot.

It'd be nice to have this fixed in time for 4.18.

Thanks

![Selection_052](https://user-images.githubusercontent.com/2357012/213135597-fcd6be01-a1ad-44cb-acab-1056e695e7a9.jpg)

**Comment by DaanHoogland** [comment]
fixed in #7106
