### ISSUE TITLE
Allow to rename a project, not just its description string

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#7107]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
UI/API
~~~

##### CLOUDSTACK VERSION

~~~
some upstream release in future
~~~

##### SUMMARY

Currently, it's only possible to change the description of a project entity. There is also "project name" which seems to be hardcoded as string reference in the database model. Would be good if it would be a the human-readable label which is interchangeable: per UI and per API.
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rahulbcn27** [comment]
I am working on it.

**Comment by rahulbcn27** [comment]
https://github.com/apache/cloudstack/pull/7149

@rohityadavcloud Please review.
