### ISSUE TITLE
Latest main can't create networks

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7110]
See cc @weizhouapache @DaanHoogland  (possible via API though)
<img width="948" alt="Screenshot 2023-01-18 at 8 07 41 PM" src="https://user-images.githubusercontent.com/95203/213199775-bbe6fac5-2f3b-4903-a426-0251021ee870.png">

**Comment by weizhouapache** [comment]
@rohityadavcloud 
what's the error ?
The network "Test" has been created, right ?

**Comment by rohityadavcloud** [comment]
There is no create network button @weizhouapache on this page (even for root admin user)

**Comment by weizhouapache** [comment]
@rohityadavcloud 
ah, got it. it works in my local env
let me create a new env and check

**Comment by weizhouapache** [comment]
@rohityadavcloud 
I cannot reproduce the issue in a fresh environment.

what's the type of the zone ?
what's the last commit ?
do you use nodejs development mode (e.g. by 'npm start') ?

**Comment by rohityadavcloud** [comment]
Thanks @weizhouapache let me rebuild an email and confirm the same.

**Comment by rohityadavcloud** [comment]
Can't reproduce with latest main, closing.
