### ISSUE TITLE
Plugin development

### ISSUE THREAD

**Issue by vinokumark** [apache/cloudstack#7121]
Hi Team,

Any one provide the clear document to develop the custom plugin and UI with example.

Below document not clear for development and there is no "/client/tomcatconf/componentContext.xml.in." on plugin directory branch 4.11.2.

http://docs.cloudstack.apache.org/en/latest/developersguide/plugins.html

![image](https://user-images.githubusercontent.com/31273923/214011097-b1533092-3cee-4d65-aa42-16f03c46716d.png)

**Comment by DaanHoogland** [comment]
@vinokumark there are the [docs](http://docs.cloudstack.apache.org/en/latest/developersguide/plugins.html) and there are the examples from the repository. If you feel the docs need improvement, pleasse feel free to [submit a PR](https://github.com/apache/cloudstack-documentation/compare). At the moment [a big plugin is being evaluated for Tungsten Fabric](https://github.com/apache/cloudstack/pull/7065). Maybe that can give some inspiration.

**Comment by rohityadavcloud** [comment]
Thanks @vinokumark you're right the docs are wrong and refer to legacy UI, you may refer to https://github.com/shapeblue/hackerbook and https://github.com/apache/cloudstack/tree/main/ui/docs

**Comment by soreana** [comment]
@rohityadavcloud @vinokumark @DaanHoogland Is this still relevant?

**Comment by weizhouapache** [comment]
> @rohityadavcloud @vinokumark @DaanHoogland Is this still relevant?

@soreana yes

**Comment by vishesh92** [comment]
Stale docs have been removed in https://github.com/apache/cloudstack-documentation/pull/404

To check the UI customization and development related docs, check:
* https://docs.cloudstack.apache.org/en/latest/adminguide/ui.html#basic-ui-customization
* https://github.com/apache/cloudstack/tree/main/ui#readme
* https://github.com/apache/cloudstack/tree/main/ui/docs
