### ISSUE TITLE
Documentation: Missing information regarding deploying UEFI 'enabled' hosts

### ISSUE THREAD

**Issue by Hudratronium** [apache/cloudstack#7126]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

As of know the CS documentation currently only has minimal information regarding the configuration of UEFI / Secureboot capable hosts and the overall integration into an CS infrastructure.
Beside the information in the docs the only offical source of information is a wiki entry ( https://cwiki.apache.org/confluence/display/CLOUDSTACK/Enable+UEFI+booting+for+Instance ) .
The infos given in the wiki are still up to date as it has been modified at 10/2019.
As far as i have seen, there have been some changes fixes and enhancements regarding this feature during the last releases of CS. 
For example the discovery of UEFI-capable hosts ( https://lists.apache.org/thread/dqyxsfggbjppqznj16y9v1rvqhw1mp0b ). 
Also the additional needed steps to enable UEFI/secure boot functionality (OVMF-package) arent't documented in official sources.

With Windows Server 2022 we have a major OS which is actively checking secure boot / needing it to match some security baselines.
The same goes for several certifications and stuff when you are using CS in more security sensitive environments - even without Windows based systems at all. 

I like to request to update and enhance the documentation with the needed information - especially about
- deployment of UEFI-enabled hosts
-  implications for deploying legacy / BIOS-VMs in such environments.

The problem is that currently, at least I as a 'provider' of a CS infrastructure, can't find the information / process-diagrams ... to enhance the documentation with further information. 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by Jw9394** [comment]
i have the same issue like you and i am wondering how to run my VM on "q35" not the "pc-i440fx-6.2" one

**Comment by rohityadavcloud** [comment]
Raised a doc PR here - https://github.com/apache/cloudstack-documentation/pull/407 not sure what additional information we want to add here.
