### ISSUE TITLE
Extend Import-Export Instances to the KVM Hypervisor

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#7127]
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
API, UI, Instances
~~~

##### SUMMARY
The Import-Export functionality is only allowed for the Vmware hypervisor. The functionality is developed within a VM ingestion framework that allows the extension to other hypervisors. The Import-Export functionality consists on few APIs and the UI to interact with them:

- listUnmanagedInstances: Lists unmanaged virtual machines (not existing in CloudStack but existing on the hypervisor side)
- importUnmanagedInstance: Import an unmanaged VM into CloudStack (this implies populating the database with the corresponding data)
- unmanageVirtualMachine: Make CloudStack forget a VM but do not remove it on the hypervisor side

The complexity on KVM should be parsing the existing XML domains into different resources and map them in CloudStack to populate the database correctly.

**Comment by itsayushpandey** [comment]
Hi @nvazquez , I am interested in working on this project and have been spending time on hackerbook (https://github.com/shapeblue/hackerbook) to make sure I understand some details before committing to the project. As extensive as it is, it took time, and based on my understanding I was able to submit a proposal on GSoc portal. I was wondering if you had any feedback or further guidance I can incorporate into the proposal. Thank you so much for your time!

**Comment by nvazquez** [comment]
Hi @itsayushpandey can you share a link to the proposal on Google docs? You can send it to my email nvazquez@apache.org

**Comment by itsayushpandey** [comment]
Hi @nvazquez thank you for your prompt reply. I've shared the proposal over email.

**Comment by rohityadavcloud** [comment]
I think as a first step once you've read basic CloudStack [dev training](https://github.com/shapeblue/hackerbook/blob/main/2-dev.md), you'll need to figure out code in the KVM hypervisor plugin which perhaps currently doesn't allow unmanaged VMs to run on KVM host (i.e. VMs not managed by CloudStack I think aren't allowed to run on KVM hosts currently - I could be wrong). You can use [mbx](https://github.com/shapeblue/mbx/tree/main) for local dev setup etc. as well.

**Comment by itsayushpandey** [comment]
> I think as a first step once you've read basic CloudStack [dev training](https://github.com/shapeblue/hackerbook/blob/main/2-dev.md), you'll need to figure out code in the KVM hypervisor plugin which perhaps currently doesn't allow unmanaged VMs to run on KVM host (i.e. VMs not managed by CloudStack I think aren't allowed to run on KVM hosts currently - I could be wrong). You can use [mbx](https://github.com/shapeblue/mbx/tree/main) for local dev setup etc. as well.
> 
> Once this is done (which might take most of your initial training/getting up to speed time), following the advise Nicolas has proposed should be easier to implement.

Hi @rohityadavcloud thank you for the pointers! 
To verify whether cloudstack allows unmanaged VM's to run on a KVM host I performed the following steps :

1.  Extended unmanaged VM's support to KVM by implementing PrepareUnmanageVMInstanceCommand in KVM plugin in pull request #7712 
2. Started a new VM in cloudstack on KVM 
3.  Executed unmangeVirtualMachine API to unmanage the previously added virtual machine in step 2.
4. Verified that the virtual machine is still running on the KVM host but not presenting cloudstack management server database.

Do you think this will suffice to test the corner case that you mentioned ?
Please let me know if you have any other advice for validating the support for unmanage VM's existence in cloudstack + KVM setup.

**Comment by borisstoyanov** [comment]
I think we can close this once we get a doc PR. agree @nvazquez ?

**Comment by weizhouapache** [comment]
can this be closed in favor of #7976 ?
cc @shwstppr

**Comment by shwstppr** [comment]
Closing this with #7976 being merged. @nvazquez please reopen if we need anything more.
