### ISSUE TITLE
UI unresponsive at the public network step when adding new zone

### ISSUE THREAD

**Issue by mail2lawi** [apache/cloudstack#7128]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### CONFIGURATION

Hypervisor - KVM

##### OS / ENVIRONMENT

RHEL 8.7

##### SUMMARY

During initial setup after logging into Cloudstack for the first time, at the 3rd step (Network), under 'Public traffic', the UI freezes on clicking 'Next'. 

I am using cloudstack built from source for Centos8.

#6479 looks similar but somehow I am still getting the error on 4.17.2

##### STEPS TO REPRODUCE

~~~
Follow the normal steps for setting up a zone. 

Set DNS as appropriate

Select KVM as hypervisor

Leave the default values on the Physical network page

Under public network, enter your IP ranges as appropriate.

However, the page freezes with or without input on the page. All needed to get the page frozen is to click 'Next' button. 
After that you can't proceed or go back and you can't even use the textboxes.
~~~

##### EXPECTED RESULTS

~~~
I should be taken to the next page once I enter the public network details and click Next. Or if values are missing, there should be an error which I can correct and proceed
~~~

##### ACTUAL RESULTS

~~~
On clicking Next the page became non-responsive. I checked the logs and didn't say anything I could use to resolve the issue. 
I've tried with 2 browsers - Microsoft Edge running on Ubuntu and Firefox also running on Ubuntu. Both behaved the same.

Attached is the image of the page where the UI becomes unresponsive on clicking Next, with or without network values



~~~
![add_zone](https://user-images.githubusercontent.com/29949457/214231968-52cd6336-261f-44c9-b9cb-0ff2b4cc32d9.png)

**Comment by weizhouapache** [comment]
@mail2lawi 
it works well in my testing (I use Chrome). can you try with Chrome ?

can you open the console of your browser to see if there is any error ?

**Comment by mail2lawi** [comment]
I was missing a step. You have to click 'Add' first before clicking 'Next'.  Ideally that shouldn't be a reason for all controls to be locked but at least now I can get past the page.

**Comment by DaanHoogland** [comment]
That is a valid point @mail2lawi . Maybe, if it is reproducable, it is worth an issue?
