### ISSUE TITLE
Advanced Zone with SG: Security Groups not shown in Create Instance UI (Project View)

### ISSUE THREAD

**Issue by MejdiB** [apache/cloudstack#7135]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### CONFIGURATION

Cloudstack 4.17.2 environment Advanced Zone with Security Groups. Default View and Projects are used in this setup.

##### OS / ENVIRONMENT

RHEL 8 is used for cloudstack management servers and hosts.

##### SUMMARY

When creating an instance in the Default View, users can see their Security Groups from which they can choose when initially creating a VM. In The Projects View, the list of Security Groups are not shown in the Create Instance UI.

**Comment by DaanHoogland** [comment]
fixed in #7164

**Comment by MejdiB** [comment]
@DaanHoogland Ok, I will close this issue then
