### ISSUE TITLE
Pass the addresses of all image stores to the SSVM 

### ISSUE THREAD

**Issue by GutoVeronezi** [apache/cloudstack#7162]
Following the discussion in https://github.com/apache/cloudstack/pull/6900#discussion_r1091781970, the idea is to pass to the SSVM the addresses of all image stores it has access.

##### ISSUE TYPE
 * Improvement Request

**Comment by weizhouapache** [comment]
thanks @GutoVeronezi

**Comment by weizhouapache** [comment]
fixed via #7410 
thanks @shwstppr
