### ISSUE TITLE
UI - SQL error when searching/filtering on accountuser page

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack#7165]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
Tested on
* 4.17.2.0
* 4.17.0.1

##### CONFIGURATION
Standard install.

##### OS / ENVIRONMENT
Rocky Linux 8

##### SUMMARY
I am getting the following error message in the web console when trying to search for a specific user account.

```
Request failed. (530)
Caught: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT user_view.id, user_view.uuid, user_view.username, user_view.password, user_view.firstname, user_view.lastname, user_view.email, user_view.state, user_view.api_key, user_view.secret_key, user_view.created, user_view.removed, user_view.timezone, user_view.registration_token, user_view.is_registered, user_view.incorrect_login_attempts, user_view.account_id, user_view.account_uuid, user_view.account_name, user_view.account_type, user_view.account_role_id, user_view.domain_id, user_view.domain_uuid, user_view.domain_name, user_view.domain_path, user_view.job_id, user_view.job_uuid, user_view.job_status, user_view.default, user_view.source FROM user_view WHERE user_view.account_type != 5 AND user_view.id != 1 AND (user_view.username LIKE x'257573657225' OR user_view.firstname LIKE x'257573657225' OR user_view.lastname LIKE x'257573657225' OR user_view.email LIKE x'257573657225' OR user_view.state LIKE x'257573657225' OR user_view.account_name LIKE x'257573657225' OR user_view.account_type LIKE ** NOT SPECIFIED ** ) AND user_view.removed IS NULL ORDER BY user_view.id ASC LIMIT 0, 50
```

The page I am trying to search on is the `/#/accountuser` page.

##### STEPS TO REPRODUCE
1. Log in to CloudStack UI
2. Click on 'Accounts'
3. Click on any account
4. Click on 'View Users'
5. On the user list page (i.e. the /#/accountuser page, eg. https://cloudstack.example.com/client/#/accountuser), use the search box at the top right of the user table.
6. The 'Request failed' error appears.

##### EXPECTED RESULTS
The user table should be filtered by the search.

##### ACTUAL RESULTS
A '500 Internal Server Error.' page is displayed.

**Comment by DaanHoogland** [comment]
addressed in #7169
