### ISSUE TITLE
UI background colour of warning makes it illegible 

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7167]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

when selecting a default ACL for a VPC tier, the warning about the ACL is not legible due to its colours.
![image](https://user-images.githubusercontent.com/2486961/216576463-0529a071-8ab8-4924-909c-b06b515b1368.png)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
tested this in the tungsten UI PR #7166 , it seems to be specific to that code. I can not reproduce in main atm.

**Comment by rohityadavcloud** [comment]
@DaanHoogland we found this to be a build bug (if you build UI again, you may not consistently get this issue), which we hope is fixed via the Ant Design 3 upgrade by @davidjumani . Pl keep an eye if you hit this again and create new issue.
