### ISSUE TITLE
SolidFire: VM restart with data disk from the Solidfire Storage failure

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#7172]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
storage, VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.17+, maybe earlier versions as well
~~~

##### CONFIGURATION

Advanced zone with VMware as hypervisor

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When one or more data disk which are provisioned with solidfire are attached to a VM, stop-start for the VM fails with a disk path issue from the hypervisor.
From the logs and code investigation it appears CloudStack revokes access for the volume with Solidfire plugin while stopping the VM but it is not granting the access again on the start of the VM

##### STEPS TO REPRODUCE

~~~
- Deploy a VM
- Attach a solidfire data disk
- Stop the VM
- Start the VM, observe failure
~~~

##### EXPECTED RESULTS

~~~
VM is started successfully
~~~

##### ACTUAL RESULTS

~~~
VM start fails with error,

Invalid configuration for device '2'. Device: VirtualDisk. Provided backing file is not accessible from host.
~~~

**Comment by rohityadavcloud** [comment]
I've tested the fixes and raised - https://github.com/apache/cloudstack/pull/7761
cc @shwstppr
