### ISSUE TITLE
Full test Plan for UI Admin user

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7184]
Note: for User role test exclude after Account/User feature, for DomainAdmin role exclude after Infrastructure (except for Offerings)

Common

- [X] Project selector
- [X] Language selector
- [X] Notifications / clear notifications
- [X] Paginations
- [X] Profile
- [X] Help
- [X] Logout
- [X] Context-sensitive help

Dashboard

- [X] Fetch latest (only on Admin dashboard)
- [X] View hosts in alert state
- [X] View alerts
- [X] View events

Compute > Instances

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links
- [X]    Filter by
- [X]    Create new instance

Compute > Kubernetes

This requires configuring and setting up CKS: http://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-service.html

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links
- [X]    Filter by
- [X]    Add Kubernetes cluster
- [X]    Start/stop a Kubernetes cluster
- [X]    Scale Kubernetes cluster
- [X]    Upgrade Kubernetes cluster
- [X]    Delete Kubernetes cluster

Compute > Instances > selected instance

- [X]    View console
- [X]    Reboot instance
- [X]    Update instance
- [X]    Start/Stop instance
- [X]    Reinstall instance
- [X]   Take snapshot
- [X]    Assign VM to backup offering
- [X]    Attach ISO
- [X]    Scale VM
- [X]    Migrate instance to another host
- [X]    Change affinity
- [X]    Change service offering
- [X]    Reset Instance Password
- [X]    Assign Instance to Another Account (VM must be stopped)
- [X]    Network adapters
- [X]    Add network to VM
- [X]    Set default NIC
- [X]    Add/delete secondary IP address
- [X]    Delete VM network
- [X]    Settings
- [X]    Add setting
- [X]    Update setting
- [X]    Delete setting
- [X]    Add / delete comment
- [X]    Add / delete tags
- [X]    Links

Compute > Instance groups

- [X]    Search
- [X]    Sort
- [X]    Links
- [X]    New instance group

Compute > Instance groups > selected instance group

- [X]   Links
- [X]   Update instance group
- [X]   Delete instance group

Compute > SSH Key Pairs

- [X]    Search
- [X]    Sorting
- [X]    Links
- [X]    New SSH key pair

Compute > SSH Key Pairs > selected SSH key pair

- [X]    Links
- [X]    Delete SSH key pair

Compute > Affinity Groups

- [X]    Search
- [X]    Sort
- [X]    Links
- [X]    New affinity group

Compute > Affinity Groups > selected affinity group

- [X]    Links
- [X]    Delete affinity group

Storage > Volumes

- [X]    Basic earch
- [X]    Extended search
- [X]    Sort
- [X]    Links
- [X]    Create volume
- [X]    Upload local volume
- [X]    Upload volume from URL

Storage > Volumes > selected volume

- [X]    Detach volume
- [X]    Take snapshot
- [X]    Recurring snapshot
- [X]    Resize volume
- [X]    Migrate volume
- [X]    Download volume
- [X]    Delete volume
- [X]    Links
- [X]    Add/delete tags

Storage > Snapshots

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links

Storage > Snapshots > selected snapshot

- [X]    Links
- [X]    Add/delete tags
- [X]    Create template
- [X]    Create volume
- [X]    Revert snapshot
- [X]    Delete snapshot

Storage > VM Snapshots

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links

Storage > VM Snapshots > selected snapshot

- [X]    Links
- [X]    Add/delete tags
- [X]    Revert VM snapshot
- [X]    Delete VM snapshot

Network > Guest networks

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links
- [X]    Add network

Network > Guest networks > selected network

- [X]    Links
- [X]    Add/delete tags
- [X]    Update network
- [X]    Restart network
- [X]    Delete network
- [X]    Acquire new IP (only for isolated networks)
- [X]    Replace ACL list(only for VPC isolated networks)
- [X]    Delete public IP address (only for isolated networks)
- [X]    Add/delete egress rule (only for isolated networks)

**Network > VPC **

- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Links
- [X]    Add VPC

Network > VPC > selected VPC

- [X]    Links
- [X]    Update VPC
- [X]    Restart VPC
- [X]    Delete VPC
- [X]    Networks
- [X]    - Links
- [X]    - Paginations
- [X]    - Add network
- [X]    - Add internal LB
- [X]    Public IP addresses
- [X]   - Links
- [X]    - Pagination
- [X]    - Select tier
- [X]    - Acquire new IP
- [X]    - Delete IP address
- [X]    Network ACL Lists
- [X]    - Links
- [X]    - Pagination
- [X]    - Add network ACL list
- [X]    Private Gateways
- [X]    - Links
- [X]    - Pagination
- [X]    - Add private gateway
- [X]    VPN Gateway
- [X]   - Links
- [X]    VPN Connections
- [X]    - Links
- [X]   - Pagination
- [X]    - Create Site-to-site VPN connection
- [X]    Virtual routers
- [X]    - Links
- [X]    Add/delete tags

Network > Security groups

- [X]    Search
- [X]    Sort
- [X]    Links
- [X]    Add security group

Network > Security groups > selected security group

- [X]    Links
- [X]    Add/delete tags
- [X]    Add ingress rule by CIDR
- [X]    Add ingress rule by Account
- [X]    Ingress rule - add/delete tags
- [X]    Ingress rule - delete
- [X]    Add egress rule by CIDR
- [X]    Add egress rule by Account
- [X]    Egress rule - add/delete tags
- [X]    Egress rule - delete
- [X]    Ingress/egress rules pagination

Network > Public IP Addresses

- [X]    Search
- [X]    Sort
- [X]    Links
- [X]    Acquire new IP

Network > Public IP Addresses > selected IP address

- [X]    Links
- [X]    Add/delete tags
- [X]    Enable/Disable static NAT
- [X]    Release IP
- [X]    Firewall - add rule
- [X]    Firewall rule - add/delete tags
- [X]    Firewall rule - delete
- [X]    VPN - Enable/Disable VPN
- [X]    VPN - Manage VPN Users

Network > VPN Users

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add VPN user

Network > VPN Users > selected VPN user

- [X]    Links
- [X]    Delete VPN User

Network > VPN Customer Gateway

- [X]    Links
- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Add VPN Customer Gateway

Network > VPN Customer Gateway > selected gateway

- [X]    Links
- [X]    Edit VPN Customer Gateway
- [X]    Delete VPN Customer Gateway
- [X]    Add/delete tags - Xen do they support it ?

Images > Templates

- [X]    Links
- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Change order (move to the top/bottom, move one row up/down)
- [X]    Register template
- [X]    Upload local template

Images > Templates > selected template

- [X]    Links
- [X]    Add/delete tags
- [X]    Edit template
- [X]    Copy template
- [X]    Update template permissions
- [X]    Delete template
- [X]    Download template
- [X]    Zones pagination
- [X]    Settings - add/edit/remove setting

Images > ISOs

- [X]    Links
- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Change order (move to the top/bottom, move one row up/down)
- [X]    Register ISO
- [X]    Upload local ISO

Images > ISOs > selected ISO

- [X]    Links
- [X]    Add/delete tags
- [X]    Edit ISO
- [X]    Download ISO
- [X]    Update ISO permissions
- [X]    Copy ISO
- [X]    Delete ISO
- [X]    Zones - pagination

Images > Kubernetes ISOs

- [X]    Links
- [X]    Basic search
- [X]    Sort
- [X]    Refresh
- [X]    Pagination
- [X]    Enable/Disable
- [X]    Add Kubernetes Version

Projects

- [X]    Links
- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Switch to project
- [X]    New project

Projects > selected project

- [X]    Links
- [X]    Add/delete tags
- [X]    Edit project
- [X]   Suspend/Activate project
- [X]    Add account to project
- [X]    Accounts - Make account project owner
- [X]    Accounts - Remove account from project
- [X]    Delete project
- [X]    Accounts - pagination
- [X]    Resources - edit

Events

- [X]    Links
- [X]    Basic search
- [X]    Extended search
- [X]    Sort
- [X]    Archive event
- [X]    Delete event

Events > selected event

- [X]    Links
- [X]    Archive event
- [X]    View event timeline
- [X]    Delete event

Users

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add user

Accounts

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add account
- [X]    Add LDAP account

Accounts > selected account

- [X]    Links
- [X]    Update account
- [X]    Update resource count
- [X]    Disable/enable account
- [X]    Lock/unlock account
- [X]    Add certificate
- [X]    Delete account
- [X]    Settings

Users > selected user

- [X]    Links
- [X]    Edit user
- [X]    Change password
- [X]    Generate keys
- [X]    Disable/enable user
- [X]    Delete user
- [X]    Copy API Key
- [X]    Copy Secret Key

Domains

- [X]    Search
- [X]    Expand/collapse
- [X]    Add/delete note
- [X]    Add domain
- [X]    Edit domain
- [X]    Delete domain
- [X]    Update resource count
- [X]    Link domain to LDAP Group/OU
- [X]    Settings

Roles

- [X]    Links
- [X]    Search
- [X]    Sort
- [x]    Create role

Roles > selected role

- [X]    Edit role
- [X]    Delete role
- [X]    Rules - add new rule
- [X]    Rules - modify rule
- [X]    Rules - delete rule
- [X]    Rules - change rules order

Infrastructure > Summary

- [X]    Links
- [X]    Setup SSL certificate

Infrastructure > Zones

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Pagination
- [X]    Add zone

Infrastructure > Zones > selected zone

- [X]    Links
- [X]    Edit zone
- [X]    Enable/disable zone
- [X]    Enable/disable out-of-band management
- [X]    Enable HA (disable?)
- [X]    Add VMWare datacenter
- [X]    Delete zone
- [X]    Settings - edit

Infrastructure > Pods

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add Pod

Infrastructure > Pods > selected Pod

- [X]    Links
- [X]    Dedicate/Release Pod
- [X]    Edit Pod
- [X]    Disable/enable Pod
- [X]    Delete Pod

Infrastructure > Clusters

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add Cluster

Infrastructure > Clusters > selected cluster

- [X]    Links
- [X]    Dedicate/Release cluster
- [X]    Enable/disable cluster
- [X]    Manage/unmanage cluster
- [X]    Enable/disable out-of-band management
- [X]    Enable/disable HA
- [X]   Configure HA
- [X]    Delete cluster
- [X]    Settings - edit

Infrastructure > Hosts

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add host

Infrastructure > Hosts > selected host

- [X]    Links
- [X]    Add/delete notes
- [x]    Dedicate/release host
- [X]    Edit host
- [X]    Force reconnect
- [X]    Disable/enable host
- [X]    Enable/cancel maintenance mode
- [X]    Enable/disable out-of-band management
- [X]    Enable/disale HA
- [X]    Delete host (only if disabled)

Infrastructure > Primary Storage

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add Primary storage

Infrastructure > Primary Storage > selected primary storage

- [X]    Links
- [X]    Edit primary storage
- [X]    Enable/cancel maintenance mode
- [X]    Delete primary storage
- [X]    Settings - edit

Infrastructure > Secondary Storage

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add Secondary storage

Infrastructure > Secondary Storage > selected secondary storage

- [X]    Links
- [X]    Delete secondary storage
- [X]    Settings - edit

Infrastructure > System VMs

- [X]    Links
- [X]    Search
- [X]    Sort

Infrastructure > System VMs > selected system VM

- [X]    Links
- [X]    View console
- [X]   Start/Stop system VM
- [X]    Reboot system VM
- [X]    Change service offering
- [X]    Migrate system VM
- [X]    Run diagnostics
- [X]    Get diagnostics data
- [X]    Destroy system VM

Infrastructure > Virtual routers

- [X]    Links
- [X]    Search
- [X]    Sort

Infrastructure > Virtual routers > selected virtual router

- [X]    Links
- [X]    View console (running)
- [X]    Start/Stop router
- [X]    Reboot router
- [X]    Change service offering
- [X]    Migrate router (running)
- [X]    Run diagnostics (running)
- [X]    Get diagnostics data
- [X]    Destroy router

Infrastructure > Internal LB VMs

- [X]    Links
- [X]    Search
- [X]    Sort

Infrastructure > Internal LB VMs > selected internal LB VM

- [X]    Links
- [X]    View console
- [X]    Stop router
- [X]    Migrate router

Infrastructure > CPU Sockets

- [X]    Search Not supported or even needed
- [X]    Sort

Infrastructure > Management servers

- [X]    Links
- [X]    Search Not supported via backend
- [X]    Sort

Infrastructure > Management servers > selected management server

Infrastructure > Alerts

- [X]    Links
- [X]    Search
- [X]    Sort

Infrastructure > Alerts > selected alert

- [X]    Archive alert
- [X]    Delete alert

Service Offerings > Compute offerings

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Add offering

Service Offerings > Compute offerings > selected offering

- [X]    Links
- [X]    Edit offering
- [X]    Update offering access
- [X]    Delete offering

Service Offerings > System offerings

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Change order (move to the top/bottom, move one row up/down)
- [X]    Add offering

Service Offerings > System offerings > selected offering

- [X]    Edit offering
- [X]    Delete offering

Service Offerings > Disk offerings

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Change order (move to the top/bottom, move one row up/down)
- [X]    Add offering

Service Offerings > Disk offerings > selected offering

- [X]    Links
- [X]    Edit offering
- [X]    Update offering access
- [X]    Delete offering

Service Offerings > Network offerings

- [X]   Links
- [X]    Search
- [X]    Sort
- [X]    Change order (move to the top/bottom, move one row up/down)
- [X]    Add offering

Service Offerings > Network offerings > selected offering

- [X]    Edit offering
- [X]    Enable/Disable offering
- [X]    Update offering access
- [X]    Delete offering

Service Offerings > VPC offerings

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Change order
- [X]    Add offering

Offerings > VPC offerings > selected offering

- [X]    Links
- [X]    Add / delete tags
- [X]    Edit offering
- [X]    Enable/Disable offering
- [X]    Update offering access
- [X]    Delete offering

Configuration > Global settings

- [X]    Links
- [X]    Search
- [X]    Sort
- [X]    Edit value

Configuration > LDAP Configuration

- [X]    Links
- [X]    Search
- [X]    Sort Not supported via backend
- [X]    Configure LDAP

Configuration > LDAP Configuration > selected LDAP configuration

- [X]  remove LDAP

Configuration > Hypervisor capabilities

- [X]    Data
- [X]    Search
- [X]    Sort

Tools 

- [X] Comments
- [X] Import-Export instances

**Comment by kiranchavala** [comment]
Environmnet: 4.17.2 and 4.18 nightly builds

Bugs found when testing the UI for the admin user

| Date       | Github Issue | Description                                                       | Status                | Reporter     | Assignees |
|------------|--------------|-------------------------------------------------------------------|-----------------------|--------------|-----------|
| 10/2/2023  | #7189        | Context senstive help icon is not displayed for some tabs         | In progress           | kiranchavala |           |
| 13//2/2023 | #7202        | host anti-affinity and host affinity is not working               | In progress           | kiranchavala |           |
| 13//2/2023 | #7204        | Unable to select a default (host) option during the vm deployment | Closed fixed in #7256 | kiranchavala |           |
| 20/2/2023  | #7266        | Internal LB rules are not displayed                               | In progress           | kiranchavala |           |



Enhancement issues logged 
| Date       | Github Issue | Description                                                                                     | Status      | Reporter     | Assignees |
|------------|--------------|-------------------------------------------------------------------------------------------------|-------------|--------------|-----------|
| 10/2/2023  | #7189        | List alerts page should have a filter drop down                                                 | In progress | kiranchavala |           |
| 13//2/2023 | #7216        | Ability to select account and user in the drop down when adding to the project                  | In progress | kiranchavala |           |
| 14//2/2023 | #7204        | Ability to view Archived events                                                                 | In progress | kiranchavala |           |
| 14//2/2023 | #7218        | Filter option is missing for the following tabs in the UI                                       | In progress | kiranchavala |           |
| 17/2/2023  | #7246        | Assign a static-nat label to the public-ip address                                              | In progress | kiranchavala |           |
| 17/2/2023  | #7247        | Assign a network name coloumn in the Guest Vlan page                                            | In progress | kiranchavala |           |
| 17/2/2023  | #7248        | Create a vpn users tab                                                                          | In progress | kiranchavala |           |
| 17/2/2023  | #7249        | Create a Site-to-site VPN Connections tab                                                       | In progress | kiranchavala |           |
| 17/2/2023  | #7250        | Enabling site to site vpn connection before enabling VPN Gateway doesn't throw an error message | In progress | kiranchavala |           |
| 17/2/2023  | #7251        | Events tab is missing for the following sections                                                | In progress | kiranchavala |           |
| 22/02/2023 | #7278        | Unable to order the ISO/templates in the UI                                                     | In progress | kiranchavala |           |

**Comment by borisstoyanov** [comment]
Thanks @kiranchavala ! If you're done with the effort I think it's safe to close the issue. 
great results btw!
