### ISSUE TITLE
Context-senstive help icon  is not displayed for the following tabs

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7189]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly

~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When the admin users clicks over the following feilds, the context senstive help icon is not displayed

1. Network > Guest networks
2. Network > VPN Customer Gateway
3. Network > Guest VLAN
4. Infrastructure > Zones
5. Infrastructure > Pods
6. Infrastructure > Clusters
7. Infrastructure > Hosts
8. Infrastructure > Internal LB
9. Infrastructure > Management servers
10. Configuration > Global Settings
11. Configuration > LDAP Configuration
12. Configuration > Hypervisor capabilities

##### STEPS TO REPRODUCE
~~~
Click on the following feilds in the UI, the context senstive help icon is not displayed

1. Network > Guest networks
2. Network > Guest VLAN
3. Infrastructure > Zones
4. Infrastructure > Pods
5. Infrastructure > Clusters
6. Infrastructure > Hosts
7. Infrastructure > Internal LB
8. Infrastructure > Management servers
9. Configuration > Global Settings
10. Configuration > LDAP Configuration
11. Configuration > Hypervisor capabilities

~~~

##### EXPECTED RESULTS

~~~
The context senstive help icon should be displayed and the user should be redirected to the appropriate help pages in the documentation

1. Network > Guest networks

http://docs.cloudstack.apache.org/en/latest/adminguide/networking_and_traffic.html#adding-an-additional-guest-network

2. Network > Guest VLAN

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/network_setup.html#vlan-allocation-example

3. Infrastructure > Zones

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/concepts.html#about-zones

4. Infrastructure > Pods

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/concepts.html#about-pods


5. Infrastructure > Clusters

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/concepts.html#about-clusters

6. Infrastructure > Hosts

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/concepts.html#about-hosts


7. Infrastructure > Internal LB

http://docs.cloudstack.apache.org/en/latest/adminguide/networking_and_traffic.html#about-virtual-private-clouds

or 

http://docs.cloudstack.apache.org/en/latest/adminguide/networking_and_traffic.html#creating-an-internal-lb-rule


8. Infrastructure > Management servers

http://docs.cloudstack.apache.org/en/latest/conceptsandterminology/concepts.html#management-server-overview

9. Configuration > Global Settings

http://docs.cloudstack.apache.org/en/latest/adminguide/index.html#tuning


10. Configuration > LDAP Configuration

http://docs.cloudstack.apache.org/en/latest/adminguide/accounts.html#using-an-ldap-server-for-user-authentication

11. Configuration > Hypervisor capabilities

http://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html?highlight=Hypervisor%20capabilities#hypervisor-capabilities


~~~

##### ACTUAL RESULTS

~~~
The context-sensitive help icon is not displayed and the user should be redirected to the appropriate help pages in the documentation
~~~

Screenshots
![working-context](https://user-images.githubusercontent.com/1401014/218034911-25f2c829-5c8b-4ca7-bb96-aa14b0f42cbc.png)
![not-working-context](https://user-images.githubusercontent.com/1401014/218034940-1898ff76-afab-4be0-8323-1f1c46b28e18.png)

**Comment by kiranchavala** [comment]
Tested on older release 4.17.2 release and observed the same issue

**Comment by davidjumani** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7306

**Comment by shwstppr** [comment]
@kiranchavala can you please check if this is fixed now as suggested by @davidjumani

**Comment by kiranchavala** [comment]
@shwstppr The issue is fixed , closing it , 

Just checked on 4.19 release

Currently the context help is not available for the following items

Network > VNF appliance
Network > VPN Users
Network > VPN customer gateway
Network > Tungsten Fabric


will create a separate issue or a PR for those

**Comment by DaanHoogland** [comment]
@kiranchavala @shwstppr was this implemented? (no PR is linked)

**Comment by kiranchavala** [comment]
@DaanHoogland  fixed in https://github.com/apache/cloudstack/pull/7306
