### ISSUE TITLE
Unable to upload ISO nor templates from local

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#7191]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When you try to upload a ISO or a template using Cloudstack UI function "Upload from local" you receive error: Upload Failed
Failed to upload ISO. - Error: Request failed with status code 502

##### STEPS TO REPRODUCE

Open the page Images/ISO and upload an ISO from local.

##### EXPECTED RESULTS

~~~
The ISO is uploaded
~~~

##### ACTUAL RESULTS

~~~
We receive error 502.

From the logs we can see the following:
2023-02-09 20:16:32,104 WARN  [c.c.a.AlertManagerImpl] (Upload-Monitor-1:ctx-a90ee4fd) (logid:e8671b09) alertType=[28] dataCenterId=[2] podId=[null] clusterId=[null] message=[Template 29d91b99-6d23-4c77-b4a8-f06238109302 failed to upload. Error details: file receive failed or connection closed prematurely.].

Looks like it doesn't read correctly the podId and clusterId parameters.
~~~

**Comment by DaanHoogland** [comment]
@cdfgallo do you see more errors before this or do you see any errors in the log on the ssvm?

**Comment by borisstoyanov** [comment]
@cdfgallo can you try rebuilding the SSVM and upload again? 

are you able to download a snapshot? 

are you using a proxy, cause this is bad gateway error, also from your report I don't see how did you came to the conclusion it cannot reaad podId or clusterId?

**Comment by cdfgallo** [comment]
@DaanHoogland I attach here the "complete" log of the operation from the SSVM, unfortunatelly no, no other errors.

[ssvm-log.txt](https://github.com/apache/cloudstack/files/10706125/ssvm-log.txt)

**Comment by cdfgallo** [comment]
@borisstoyanov 
I'm not using any proxy.
I'm able to download any template from the ssvm (not sure how I can download a snapshot).
The error refer to "java.lang.NumberFormatException: null" while it's expecting an integer value but receiving the value "null", that's why I'm pointing at that.

**Comment by borisstoyanov** [comment]
@cdfgallo when you create a snapshot of a volume you have the option to download it, it's the same process as uploading but in the other direction, can you try that. 

Also can you destroy your SSVM and wait until the new one is up and try again to upload. Maybe also share an image of the upload form in the UI before clicking upload.

**Comment by DaanHoogland** [comment]
The NPE is in this line:
```
        long defaultMaxSecondaryStorageInGB = cmd.getDefaultMaxSecondaryStorageInGB();
```
so it has nothing to do with the Pod or cluster. It is an implicit conversion failing. What is your value for "max.account.secondary.storage"? This is the setting propagated to that command.

**Comment by cdfgallo** [comment]
@borisstoyanov I tried to rebuild the ssvm but I receive the same error. Also it's a bit strange that the agent is still the same as 4.17.0.1 when the template is of version 4.17.2
![image](https://user-images.githubusercontent.com/110984295/218069371-34d79094-405d-47db-a5de-8e1abd0c6dac.png)
Here the screen you requested
![gui-upload](https://user-images.githubusercontent.com/110984295/218071195-655523fd-1567-43fc-aeac-362941245980.png)


@DaanHoogland the value of max.account.secondary.storage is 5000

**Comment by cdfgallo** [comment]
@borisstoyanov I can't find the option to download the snapshot. I can revert it to a template and download it, I can revert to a volume, revert vm to snapshot or delete it.

**Comment by DaanHoogland** [comment]
> @borisstoyanov I tried to rebuild the ssvm but I receive the same error. Also it's a bit strange that the agent is still the same as 4.17.0.1 when the template is of version 4.17.2

do you mean the agent on the host or in the ssvm?

![image](https://user-images.githubusercontent.com/2486961/218073087-c6af24a7-bae4-4ca5-96a9-0b87c68ba7d1.png)

or

![image](https://user-images.githubusercontent.com/2486961/218073405-5ce360d7-9a99-491e-b96e-4162bad30b45.png)


> 
> @DaanHoogland the value of max.account.secondary.storage is 5000

Ok, that value should have been propagated. the value default value is 400 but in itself is this value is no issue.

**Comment by DaanHoogland** [comment]
please check what template you have and destroy the ssvm to be recreated
the version you show is indeed not good

**Comment by cdfgallo** [comment]
After updating the agent correctly on the ssvm I got no more issues. Strangely the agent wasn't updating at first.
Thank you @DaanHoogland @borisstoyanov for your support!
