### ISSUE TITLE
List alerts page should have a filter drop down 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7193]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Infrastructure>Alerts

List alerts page should have a filter drop-down similar to List Events page 

It would be easy for the admin to filter by alert types  and other feilds

The api supports it 

https://cloudstack.apache.org/api/apidocs-4.17/apis/listAlerts.html

The different  alert types are 

MEMORY = 0,
CPU = 1, 
STORAGE = 2,
STORAGE_ALLOCATED = 3,
PUBLIC_IP = 4, 
PRIVATE_IP = 5, 
SECONDARY_STORAGE = 6,
HOST = 7, 
USERVM = 8, 
DOMAIN_ROUTER = 9, 
CONSOLE_PROXY = 10, 
ROUTING = 11: lost connection to default route (to the gateway),
STORAGE_MISC = 12, 
USAGE_SERVER = 13, 
MANAGMENT_NODE = 14, 
DOMAIN_ROUTER_MIGRATE = 15,
CONSOLE_PROXY_MIGRATE = 16,
USERVM_MIGRATE = 17,
VLAN = 18, 
SSVM = 19, 
USAGE_SERVER_RESULT = 20,
STORAGE_DELETE = 21, 
UPDATE_RESOURCE_COUNT = 22, 
USAGE_SANITY_RESULT = 23,
DIRECT_ATTACHED_PUBLIC_IP = 24,
LOCAL_STORAGE = 25,
RESOURCE_LIMIT_EXCEEDED = 26, 
SYNC = 27, 
UPLOAD_FAILED = 28, 
OOBM_AUTH_ERROR = 29

##### STEPS TO REPRODUCE
~~~

Events >  Filter icon near the search bar

Infrastructure >Alerts


Screenshot attached

~~~

##### EXPECTED RESULTS

~~~
N/A
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~
![filter-events](https://user-images.githubusercontent.com/1401014/218080498-84382d99-1234-454f-bf02-a6b599fe1bab.png)

![filter-alerts](https://user-images.githubusercontent.com/1401014/218080513-d1a02133-94c6-4720-9d8d-2b074d054ecb.png)

**Comment by kiranchavala** [comment]
@borisstoyanov please add the tag Component:ui and type:enhancement

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/8630
