### ISSUE TITLE
Provide an option for affinity group  when deploying vm in the UI 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7203]
##### ISSUE TYPE

 * Enhacement/Improvement Request

##### COMPONENT NAME

~~~
component:ui
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly


~~~

##### SUMMARY

Provide an option for affinity group  when deploying vm in the UI 

It will be helpful to have a affinity group [test-box] optional when deploying a vm  for the User
![affinity](https://user-images.githubusercontent.com/1401014/218455149-17020918-c842-416f-94f5-704701e8abe7.png)

 
https://cloudstack.apache.org/api/apidocs-4.17/apis/deployVirtualMachine.html

The deployVirtual Machine api call containes the affinity group ids 

##### STEPS TO REPRODUCE
~~~
N/A


~~~

##### EXPECTED RESULTS

~~~
N/A
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~

**Comment by kiranchavala** [comment]
@borisstoyanov please add the tag Component:ui and type:enhancement

**Comment by weizhouapache** [comment]
@kiranchavala 
you can find it in the "Advanced mode" section

**Comment by kiranchavala** [comment]
Thanks @weizhouapache  closing the issue
