### ISSUE TITLE
Ability to view Archived events

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7217]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Ability to view Archived events

This is a minor ui enhancement request but good to have for the admin users for quick search of archived events

Admin user may want to view the Archived events from the UI

Currently, there is no way to view the archived events

https://cloudstack.apache.org/api/apidocs-4.17/apis/listEvents.html

The only way is from the Database, there is an archived field in the event table 

It will be good to have this feature in case the admin wants to view the archived events
![archive-events](https://user-images.githubusercontent.com/1401014/218741700-bd2d8505-0077-41a1-bb98-c98e9f9d2ee5.png)

**Comment by kiranchavala** [comment]
@borisstoyanov  could you please add the labels

Componet:UI

Componet:api

type:enhancement

type:improvement

**Comment by rohityadavcloud** [comment]
cc @shwstppr could this be something that may be backported to 4.18 branch for 4.18.1.0 ?

**Comment by shwstppr** [comment]
@rohityadavcloud this functionality is based on a new param `archived` in the listEvents API therefore I targeted it for main rather than 4.18
