### ISSUE TITLE
~/.ssh/id_rsa.cloud on KVM host is missing

### ISSUE THREAD

**Issue by MilanHofmann** [apache/cloudstack#7232]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Host
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

ubuntu jammy jellyfish on ec2 metal instance.

##### SUMMARY

There has no key been generated to log into system vms from the host.

##### STEPS TO REPRODUCE

Set up zone + host on ec2 bare metal instance with advanced networking.
I enabled pubkey authentification AFTER the installation.

~~~

~~~

##### EXPECTED RESULTS

~~~
Have a ~/.ssh/id_rsa.cloud - key.
~~~

##### ACTUAL RESULTS

~~~
It's missing.
~~~

**Comment by weizhouapache** [comment]
@MilanHofmann 
Have you found the root cause ?

**Comment by MilanHofmann** [comment]
@weizhouapache 
yes it was quite stupid:
On an ec2 instance cloudstack creates the pubkey still in the /root/.shh/ directory, even though it logged in with another username.
I was actually using that username as well and hit ~/.ssh/id_rsa.cloud, which led to the result that the /ubuntu/.shh/ directory was empty.

**Comment by weizhouapache** [comment]
> @weizhouapache yes it was quite stupid: On an ec2 instance cloudstack creates the pubkey still in the /root/.shh/ directory, even though it logged in with another username. I was actually using that username as well and hit ~/.ssh/id_rsa.cloud, which led to the result that the /ubuntu/.shh/ directory was empty.

ah ok. it makes sense.
thanks for the info @MilanHofmann
