### ISSUE TITLE
Assign a network name column in the Guest Vlan page

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7247]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Assign a network name column in the Guest Vlan page

Have the network name as a  column in this page ( Network > Guest Vlan) 

Currently to identify the mapping between guestvlan and networks

User has to click on the Vlan id > Guestnetworks > 

It will be easy for the admin user to identify the relation with the networks if its on the main page of guest vlan 

https://cloudstack.apache.org/api/apidocs-4.17/apis/listGuestVlans.html
![guestvlan1](https://user-images.githubusercontent.com/1401014/219572965-9c47404d-f148-4b5d-b0cc-cc9a0bf89d16.png)

![guestvlan2](https://user-images.githubusercontent.com/1401014/219572975-b1f06fbf-de9e-401a-b7b3-b49e9dcb7e82.png)

**Comment by weizhouapache** [comment]
the only problem is, the guest vlan might be used by multiple networks (for example 1 isolated network and 2 user-shared networks)
