### ISSUE TITLE
Create a vpn users tab 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7248]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Create a vpn users tab 

It will be nice if the vpn users details can be found under Network 

Network > vpn users 

Currently to manage or create vpn users and end users has to perform the following steps 

Network > Guest Networks > Public Ip Address > Source Nat IP > VPN > Manage VPN users

or 

Vpc network> Public Ip Address > VPN> Manage VPN users

https://cloudstack.apache.org/api/apidocs-4.17/apis/listVpnUsers.html

![VPN users](https://user-images.githubusercontent.com/1401014/219573115-3b191db8-8f3f-4407-bfd1-4d450865736f.png)

![VPN users2](https://user-images.githubus
![VPN users3](https://user-images.githubusercontent.com/1401014/219573803-41d3aaea-8e59-4525-945c-5998cc5e1aa1.png)
ercontent.com/1401014/219573796-3b988b90-c11d-4801-b9d1-06547200d250.png)

**Comment by shwstppr** [comment]
Fixed with #7277
