### ISSUE TITLE
Create a Site-to-site VPN Connections tab 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7249]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Create a Site-to-site VPN Connections tab 

It will be nice list the site to site vpn connections details  under Network 

It will good feature for the admin user to list all the vpn connection with the required filters

Network > Site to site vpn connections 

Currently to manage VPN connections end users has to perform the following steps 

Network > VPC > VPN connection > 

https://cloudstack.apache.org/api/apidocs-4.17/apis/listVpnConnections.html
![site to site vpn2](https://user-images.githubusercontent.com/1401014/219573453-6b82cbe8-f168-48d7-a5c9-39184830f822.png)

![site to site vpn](https://user-images.githubusercontent.com/1401014/219573460-93fce672-294e-4445-870c-65aed0c2c06c.png)

**Comment by DaanHoogland** [comment]
fixed in 9066
