### ISSUE TITLE
Events tab is missing for the following sections

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7251]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Componet:UI
Componet:api
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
4.17.2

~~~

##### SUMMARY

Events tab is missing for the following sections

Instance > SSH key pairs

Instance > Affinity groups

Storage > Snapshots
Storage > VMSnapshots

Network > Public Ip Address 
Network > VPN customer gateway
Network > Guest VLAN

Infrastructure>Cluster

Infrastructure>HOST

Service offerings >Compute offering

Service offerings >System offering

Service offerings >Disk offering

Service offerings >VPC offering

https://cloudstack.apache.org/api/apidocs-4.17/apis/listEventTypes.html

Example
![event](https://user-images.githubusercontent.com/1401014/219587971-2d7607d7-d3f9-4fe5-9e34-1226b0dfd3df.png)

**Comment by kiranchavala** [comment]
@borisstoyanov Could you please add the required labels

**Comment by rohityadavcloud** [comment]
@kiranchavala this is a new request, event tab may not be available or applicable for all these places. For example a VM starting on a network could be logged as an event in the VM's event tab (not network tab). Currently events have 1:1 mapping so we may be limited by that.

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/8630
