### ISSUE TITLE
is it possible to add gpu to vm?

### ISSUE THREAD

**Issue by hirayamanawari** [apache/cloudstack#7262]
I using cloudstack 4.17.2

I have poweredge R730XD as kvm host with Quadro RTX 5000 that I want to add to my VM

is it possible to have my VM use this GPU? if it is what are the steps that I need to do?

I'm new to cloudstack.

**Comment by weizhouapache** [comment]
@hirayamanawari 
there were some discussion in mailing list
https://markmail.org/message/yyirwcyhcyd4xvmk

**Comment by rohityadavcloud** [comment]
Hi @hirayamanawari I think your question has been answered so I'm closing this. We've some option via API to have gpu passthrough for KVM and XenServer/XCP-ng may support some models.

For any further queries, you may ask on our users@ mailing list https://cloudstack.apache.org/mailing-lists.html
