### ISSUE TITLE
No el8/el9 in the name of 4.18.0.0-RC1 packages

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#7263]
centos7/el7 looks ok

`cloudstack-agent-4.18.0.0-1.el7.x86_64.rpm`

el8

`cloudstack-agent-4.18.0.0-1.x86_64.rpm`

el9

`cloudstack-agent-4.18.0.0-1.x86_64.rpm`

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Packaging
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0-RC1
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@weizhouapache is this a serious issue, to any extend?

**Comment by rohityadavcloud** [comment]
this is expected and not an issue @weizhouapache not an issue as the same pkgs are inter-operable b/w EL8, EL9 and SUSE.

**Comment by weizhouapache** [comment]
closing as per @rohityadavcloud 's comment
