### ISSUE TITLE
The Public IP addresses can not display the VM name

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7271]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
- UI

##### CLOUDSTACK VERSION
CloudStack 4.17.2.0 

![image](https://user-images.githubusercontent.com/4197714/220319681-b66b6a6c-6333-461f-874a-4630211db563.png)

**Comment by weizhouapache** [comment]
Network name is empty -> public ip is used by VPC or system vms
VM name -> public IP is not used as Static NAT.

**Comment by kiranchavala** [comment]
Hi @xuanyuanaosheng 

The vm name will be displayed only if the public ip address is having static nat 

https://cloudstack.apache.org/api/apidocs-4.17/apis/listPublicIpAddresses.html

![public-ip](https://user-images.githubusercontent.com/1401014/220327107-1ba6d26d-a66f-40cc-86d7-6a5c354e802c.png)

**Comment by xuanyuanaosheng** [comment]
@weizhouapache @kiranchavala 
Yes, as you said. may be this sould be a  Enhancement Request.
 
I mean the VM name can display the  system vms's name or just add a type note or add a hyperlink.
![image](https://user-images.githubusercontent.com/4197714/220510516-42563aea-04c6-40af-80c4-8190398621f5.png)
![image](https://user-images.githubusercontent.com/4197714/220511060-bf2e8e0d-c9be-4b91-94b6-7c90a95b42d1.png)


![image](https://user-images.githubusercontent.com/4197714/220511184-6bfd0d98-3168-46bf-ae4c-776b7403e164.png)
![image](https://user-images.githubusercontent.com/4197714/220511252-7637141e-58fe-4d61-8cbe-dab4bd0bdaf5.png)

So we can known this IP is used by cloudstack system or user.
