### ISSUE TITLE
Clearing DNS entry and saving zone does not persist changes if empty

### ISSUE THREAD

**Issue by damonb123** [apache/cloudstack#7273]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.1.0
~~~

##### STEPS TO REPRODUCE
Open zone that has DNS entries.  In test example, the goal was to remove DNS2 entry and leave DNS1.
Click OK after clearing one of the DNS fields entry.
Should get a green check mark dialog "Edit Zone - [zone name]".  Indicating a successful update.
Refresh zone, value is still present in field, and in database.

##### EXPECTED RESULTS
~~~
Expected the cleared entries were saved to the database.
Possibly even a dialog message saying all VR's in zone needed to be restarted along with all VM's to pick up changes.
Possibly a dialog offering to bounce them?
~~~

##### ACTUAL RESULTS
~~~
DNS fields still had data in them.
~~~

**Comment by kiranchavala** [comment]
Yes its a UI bug 

The actual API is working fine 

https://cloudstack.apache.org/api/apidocs-4.17/apis/updateZone.html
