### ISSUE TITLE
Full test plan for the normal user and domain admin user

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7283]
Note: for User role test exclude after Account/User feature, for DomainAdmin role exclude after Infrastructure (except for Offerings)

Common

- [X] Project selector
- [X] Language selector
- [X] Notifications / clear notifications
- [X] Paginations
- [X] Profile
- [X] Help
- [X] Logout
- [X] Context-sensitive help

Dashboard

- [X] Fetch latest (only on Admin dashboard)
- [X] View hosts in alert state
- [X] View alerts
- [X] View events

Compute > Instances

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links
- [X] Filter by
- [X] Create new instance

Compute > Kubernetes
This requires configuring and setting up CKS: http://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-service.html

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links
- [X] Filter by
- [X] Add Kubernetes cluster
- [X] Start/stop a Kubernetes cluster
- [X] Scale Kubernetes cluster
- [X] Upgrade Kubernetes cluster
- [X] Delete Kubernetes cluster

Compute > Instances > selected instance

- [X] View console
- [X] Reboot instance
- [X] Update instance
- [X] Start/Stop instance
- [X] Reinstall instance
- [X] Take snapshot
- [X] Assign VM to backup offering
- [X] Attach ISO
- [X] Scale VM
- [X] Migrate instance to another host
- [X] Change affinity
- [X] Change service offering
- [X] Reset Instance Password
- [X] Assign Instance to Another Account (VM must be stopped)
- [X] Network adapters
- [X] - Add network to VM
- [X] - Set default NIC
- [X] - Add/delete secondary IP address
- [X] - Delete VM network
- [X] Settings
- [X] - Add setting
- [X] - Update setting
- [X] - Delete setting
- [X] Add / delete comment
- [X] Add / delete tags
- [X] Links

Compute > Instance groups

- [X] Search
- [X] Sort
- [X] Links
- [X] New instance group
 

Compute > Instance groups > selected instance group

- [X] Links
- [X] Update instance group
- [X] Delete instance group

Compute > SSH Key Pairs

- [X] Search
- [X] Sorting
- [X] Links
- [X] New SSH key pair

Compute > SSH Key Pairs > selected SSH key pair

- [X] Links
- [X] Delete SSH key pair

Compute > Affinity Groups

- [X] Search
- [X] Sort
- [X] Links
- [X] New affinity group

Compute > Affinity Groups > selected affinity group

- [X] Links
- [X] Delete affinity group

Storage > Volumes

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links
- [X] Create volume
- [X] Upload local volume
- [X] Upload volume from URL

Storage > Volumes > selected volume

- [X] Detach volume
- [X] Take a snapshot
- [X] Recurring snapshot
- [X] Resize volume
- [X] Migrate volume
- [X] Download volume
- [X] Delete volume
- [X] Links
- [X] Add/delete tags

Storage > Snapshots

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links

Storage > Snapshots > selected snapshot

- [X] Links
- [X] Add/delete tags
- [X] Create template
- [X] Create volume
- [X] Revert snapshot
- [X] Delete snapshot

Storage > VM Snapshots

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links

Storage > VM Snapshots > selected snapshot

- [X] Links
- [X] Add/delete tags
- [X] Revert VM snapshot
- [X] Delete VM snapshot

Storage > Backups

Network > Guest networks

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links
- [X] Add network

Network > Guest networks > selected network

- [X] Links
- [X] Add/delete tags
- [X] Update network
- [X] Restart network
- [X] Delete network
- [X] Acquire new IP (only for isolated networks)
- [X] Replace ACL list(only for VPC isolated networks)
- [X] Delete public IP address (only for isolated networks)
- [X] Add/delete egress rule (only for isolated networks)

**Network > VPC **

- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Links
- [X] Add VPC

Network > VPC > selected VPC

- [X] Links
- [X] Update VPC
- [X] Restart VPC
- [X] Delete VPC
- [X] Networks
- [X] - Links
- [X] - Paginations
- [X] - Add network
- [X] - Add internal LB
- [X] Public IP addresses
- [X] - Links
- [X] - Pagination
- [X] - Select tier
- [X] - Acquire new IP
- [X] - Delete IP address
- [X] Network ACL Lists
- [X] - Links
- [X] - Pagination
- [X] - Add network ACL list
- [X] Private Gateways
- [X] - Links
- [X] - Pagination
- [X] - Add private gateway
- [X] VPN Gateway
- [X] - Links
- [X] VPN Connections
- [X] - Links
- [X] - Pagination
- [X] - Create Site-to-site VPN connection
- [X] Virtual routers
- [X] - Links
- [X] - Add/delete tags

Network > Security groups

- [X] Search
- [X] Sort
- [X] Links
- [X] Add security group

Network > Security groups > selected security group

- [X] Links
- [X] Add/delete tags
- [X] Add ingress rule by CIDR
- [X] Add ingress rule by Account
- [X] Ingress rule - add/delete tags
- [X] Ingress rule - delete
- [X] Add egress rule by CIDR
- [X] Add egress rule by Account
- [X] Egress rule - add/delete tags
- [X] Egress rule - delete
- [X] Ingress/egress rules pagination

Network > Public IP Addresses

- [X] Search
- [X] Sort
- [X] Links
- [X] Acquire new IP

Network > Public IP Addresses > selected IP address

- [X] Links
- [X] Add/delete tags
- [X] Enable/Disable static NAT
- [X] Release IP
- [X] Firewall - add rule
- [X] Firewall rule - add/delete tags
- [X] Firewall rule - delete
- [X] VPN - Enable/Disable VPN
- [X] VPN - Manage VPN Users

Network > VPN Users

- [X] Links
- [X] Search
- [X] Sort
- [X] Add VPN user

Network > VPN Users > selected VPN user

- [X] Links
- [X] Delete VPN User

Network > VPN Customer Gateway

- [X] Links
- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Add VPN Customer Gateway

Network > VPN Customer Gateway > selected gateway

- [X] Links
- [X] Edit VPN Customer Gateway
- [X] Delete VPN Customer Gateway
- [X] Add/delete tags

Images > Templates

- [X] Links
- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Change order (move to the top/bottom, move one row up/down)
- [X] Register template
- [X] Upload local template

Images > Templates > selected template

- [X] Links
- [X] Add/delete tags
- [X] Edit template
- [X] Copy template
- [X] Update template permissions
- [X] Delete template
- [X] Download Template
- [X] Zones pagination
- [X] Settings - add/edit/remove setting

Images > ISOs

- [X] Links
- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Change order (move to the top/bottom, move one row up/down)
- [X] Register ISO
- [X] Upload local ISO

Images > ISOs > selected ISO

- [X] Links
- [X] Add/delete tags
- [X] Edit ISO
- [X] Download ISO
- [X] Update ISO permissions
- [X] Copy ISO
- [X] Delete ISO
- [X] Zones - pagination

Images > Kubernetes ISOs

- [X] Links
- [X] Basic search
- [X] Sort
- [X] Refresh
- [X] Pagination
- [X] Enable/Disable
- [X] Add Kubernetes Version

Projects

- [X] Links
- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Switch to project
- [X] New project
- [X] Project invitations

Projects > selected project

- [X] Links
- [X] Add/delete tags
- [X] Edit project
- [X] Suspend/Activate project
- [X] Add account to project
- [X] Accounts - Make account project owner
- [X] Accounts - Remove account from project
- [X] Delete project
- [X] Accounts - pagination
- [X] Resources - edit

Events

- [X] Links
- [X] Basic search
- [X] Extended search
- [X] Sort
- [X] Archive event
- [X] Delete event

Events > selected event

- [X] Links
- [X] Archive event
- [X] View event timeline
- [X]  Delete event

Users

- [X] Links
- [X] Search
- [X] Sort
- [X] Add user

Accounts

- [X] Links
- [X] Search
- [X] Sort
- [X] Add account

Accounts > selected account

- [X] Links
- [X] Update account
- [X] Update resource count
- [X] Disable/enable account
- [X] Lock/unlock account
- [X] Add certificate
- [X] Delete account
- [X] Settings

Users > selected user

- [X] Links
- [X] Edit user
- [X] Change password
- [X] Generate keys
- [X] Disable/enable user
- [X] Delete user
- [X] Copy API Key
- [X] Copy Secret Key

Domains

- [X] Search
- [X] Expand/collapse
- [X] Add/delete note
- [X] Add domain
- [X] Edit domain
- [X] Delete domain
- [X] Update resource count
- [X] Settings

Offerings > Compute offerings

- [X] Links
- [X] Search
- [X] Sort
- [X] Add offering

Offerings > Compute offerings > selected offering

- [X] Links
- [X] Edit offering
- [X] Update offering access
- [X] Delete offering

Offerings > Disk offerings
 
- [X] Links
- [X] Search
- [X] Sort
- [X] Change order (move to the top/bottom, move one row up/down)
- [X] Add offering

Offerings > Disk offerings > selected offering

- [X] Links
- [X] Edit offering
- [X] Update offering access
- [X] Delete offering

Tools

- [X] comments

**Comment by kiranchavala** [comment]
Did not find any major UI issue with User and domain admin ( Role) account

**Comment by kiranchavala** [comment]
@borisstoyanov please add the tag testing

**Comment by borisstoyanov** [comment]
Thanks @kiranchavala ! If you're done with the effort I think it's safe to close the issue
