### ISSUE TITLE
How to achieve connectivity between different VPCs under the same zone in CloudStack?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7294]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME
VR, VPN, UI

##### CLOUDSTACK VERSION
CloudStack 4.17.2.0

**Comment by kiranchavala** [comment]
Hi @xuanyuanaosheng 

you need to setup site to site vpc

Please to refer to this blog 

https://www.shapeblue.com/vpc-to-vpc-vpn-configuration-in-cloudstack/

http://docs.cloudstack.apache.org/en/latest/adminguide/networking/site_to_site_vpn.html?highlight=site%20to%20site%20vpc

**Comment by xuanyuanaosheng** [comment]
@kiranchavala  Thanks for your help.

Another question, What are the use cases of the Private Gateway in VPC?  Please give some example?

![image](https://user-images.githubusercontent.com/4197714/221778091-f9bf97b7-7323-4be0-8d2d-2f4c4166d803.png)

![image](https://user-images.githubusercontent.com/4197714/221778174-16114ac0-75a2-409a-92a9-2720eec68b54.png)

**Comment by kiranchavala** [comment]
@xuanyuanaosheng you can refer the youtube video 

https://youtu.be/XQwqqcPWDbE?t=2400

timestamp 40:00 to 45:00

**Comment by xuanyuanaosheng** [comment]
@kiranchavala  I will do some test on this.  If the test is successful, I will upload relevant screenshots of the testing process to the **issue.**
 
I also need to test another issue https://github.com/apache/cloudstack/issues/7295, I'm not sure if the solutions to these two issue are consistent. But as far as I understand, connectivity between different VPCs under the same zone in CloudStack should not require site-to-site VPN, while connectivity between different VPCs under different zones should require site-to-site VPN.

**Comment by xuanyuanaosheng** [comment]
1.  This can connect them via a private gateway or through a vpn. of course you'll need to have your underlaty in order to allow for the connectivity
2.  private gateways in same zone should work.
3.  https://www.youtube.com/watch?v=VwNPTEcyhMY
4.  https://blog.remibergsma.com/2017/01/19/inter-vpc-connectivity-made-easy-in-cosmic-5-3/
5.  Configuring connectivity between CloudStack hosted VPCs can be done by either using private gateways – which has to be configured by CloudStack root administrators to use dedicated network segments

![image](https://user-images.githubusercontent.com/4197714/225549332-113544f4-af19-4026-a3ed-452af5bf2699.png)


The Zone name is Tesra,  The goal is **achieve connectivity between VPC-103 and VPC-104  using VPC Private gateway under the Tesra zone.**

The VPC-103 info:
-  CIDR: 10.26.28.0/22
-  Public IP addresses:10.26.20.63 (source-nat)
-  Virtual routers: r-78-VM | Running | 10.26.20.63 | 4.17.2
-  Have two tier: VLAN-1128 (CIDR:10.26.28.0/24) and VLAN-1129 (CIDR: 10.26.29.0/24)
-  Have two VM in order to test: 10.26.28.73 and 10.26.29.94,They can ping each other.

The VPC-104 info:
-  CIDR: 10.26.32.0/22
-  Public IP addresses:10.26.20.67 (source-nat)
-  Virtual routers: r-77-VM | Running | 10.26.20.67 | 4.17.2
-  Have two tier: VLAN-1132 (CIDR:10.26.32.0/24) and VLAN-1133 (CIDR: 10.26.33.0/24)
-  Have two VM in order to test: 10.26.32.114 and 10.26.33.231, They can ping each other.

---

Use VLAN id that is not in Guest vlan range (1121-1130), like 1141



The below is VLAN-1128 (CIDR:10.26.28.0/24)  <==> VLAN-1132 (CIDR:10.26.32.0/24)

The VPC-103 config:
![image](https://user-images.githubusercontent.com/4197714/225553553-01292510-361c-4e2d-b039-9cd45bc05146.png)

![image](https://user-images.githubusercontent.com/4197714/225553779-58cbede9-d6b4-454a-8d7f-217d3620f7bb.png)

![image](https://user-images.githubusercontent.com/4197714/225553841-30073b08-ef4f-42eb-8b9d-3bca6721d4f4.png)

The VPC-104 config:

![image](https://user-images.githubusercontent.com/4197714/225554191-8471ce5e-8404-4fef-bb4c-e8838462c65e.png)

![image](https://user-images.githubusercontent.com/4197714/225554267-3d8319be-433a-4c83-a62c-0d3425de8e69.png)

![image](https://user-images.githubusercontent.com/4197714/225554359-61b19f2e-f9d9-45f0-98a3-dc576c4d96d2.png)
