### ISSUE TITLE
How to achieve connectivity between different VPCs under different zones in CloudStack?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7295]
##### ISSUE TYPE
 * Documentation Report

##### COMPONENT NAME
VR, VPN, UI

##### CLOUDSTACK VERSION
CloudStack 4.17.2.0

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng , of the top of my head: you can connect them via a private gateway or through a vpn. of course you'll need to have your underlaty in order to allow for the connectivity. I think people have tris in the wild allready but I would not know what the most common solution is.

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland   Thanks for  your reply, I will do some test on thses issue.

**Comment by weizhouapache** [comment]
@xuanyuanaosheng 
private gateways in same zone should work. I have used it many times before.
Do not forget to add static routes.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  OK, Thanks,  I will do some test on this.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  [DaanHoogland](https://github.com/DaanHoogland) @kiranchavala

The example:

The Zone name is Tesra,  The goal is **achieve connectivity between VPC-103 and VPC-104  using VPC Private gateway under the Tesra zone.**

The VPC-103 info:
-  CIDR: 10.26.28.0/22
-  Public IP addresses:10.26.20.63 (source-nat)
-  Virtual routers: r-78-VM | Running | 10.26.20.63 | 4.17.2
-  Have two tier: VLAN-1128 (CIDR:10.26.28.0/24) and VLAN-1129 (CIDR: 10.26.29.0/24)
-  Have two VM in order to test: 10.26.28.73 and 10.26.29.94,They can ping each other.

The VPC-104 info:
-  CIDR: 10.26.32.0/22
-  Public IP addresses:10.26.20.67 (source-nat)
-  Virtual routers: r-77-VM | Running | 10.26.20.67 | 4.17.2
-  Have two tier: VLAN-1132 (CIDR:10.26.32.0/24) and VLAN-1133 (CIDR: 10.26.33.0/24)
-  Have two VM in order to test: 10.26.32.114 and 10.26.33.231, They can ping each other.

How to 

![image](https://user-images.githubusercontent.com/4197714/222101530-ab54d4d1-f81f-40eb-a846-8baa7a18b9a8.png)

**Comment by xuanyuanaosheng** [comment]
https://www.youtube.com/watch?v=VwNPTEcyhMY

**Comment by rohityadavcloud** [comment]
@xuanyuanaosheng as you've figured, the two popular ways are site-to-site VPN between two VPCs, or using private gateways and static routes. If you've already figured this out, could you raise a PR to https://github.com/apache/cloudstack-documentation if you want to add any documentation, thanks.
