### ISSUE TITLE
ISO Upload failed - cannot get rid/delete of failed entry

### ISSUE THREAD

**Issue by rongage** [apache/cloudstack#7301]
If you have a failed upload of an ISO (or presumably a template as well), the failed iso upload does not delete itself from the iso view and you cannot delete it.

![image](https://user-images.githubusercontent.com/48737316/222212915-dff68da7-551f-4496-8309-64c92d10fd19.png)

##### ISSUE TYPE
Bug report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Upload an ISO *BEFORE* you have done the SSL approval trick.  Upload fails due to network error (bad error message) and then the ISO entry in the ISO display remains and cannot be deleted from the UI.  

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

Either failed ISO entry is auto-removed when the upload fails
-or-
Offer a method to remove the failed ISO from the ISO display
~~~

~~~

##### ACTUAL RESULTS

UI thinks that the upload is proceeding (see attached error message above) when it clearly isn't.

~~~

~~~

**Comment by kiranchavala** [comment]
Hi @rongage 

The failed uploaded template/iso will be automatically removed  after 60 min 

This is controlled by the  Configuration> Global settings > "Upload operation timeout" > The default value is set to 60 min

**Comment by DaanHoogland** [comment]
@rongage are you satisfied with the answer?
I am closing the issue. If you feel that is invalid, please reopen or create a new issue
