### ISSUE TITLE
ENHANCEMENT REQUEST (KVM)(Kubernetes): Resize compute offering for kubernetes clusters in a stopped state

### ISSUE THREAD

**Issue by aron-ac** [apache/cloudstack#7303]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.17.1 +
~~~

##### CONFIGURATION

KVM hypervisors

##### OS / ENVIRONMENT

n/a

##### SUMMARY

Scaling compute offerings for underlaying KVM based VMs for k8s clusters when they are in a stopped state. You can resize KVM VMs in cloudstack in a stopped state, it would be ideal to allow resizing of machines for kubernetes clusters as well (KVM)

##### STEPS TO REPRODUCE

~~~
1. Stop a running KVM kubernetes cluster (API or UI)
2. 'Scale' compute offering for VMs in that cluster (API or UI)
3. Start KVM kubernetes cluster with the new compute offering (API or UI)
~~~

##### EXPECTED RESULTS

~~~
Change compute offering for KVM based kubernetes clusters in a stopped state
~~~

##### ACTUAL RESULTS

~~~
Live scale of compute offering size in kubernetes is not supported for KVM (so we should enable it for stopped state)
~~~

**Comment by shwstppr** [comment]
Improvement added in https://github.com/apache/cloudstack/pull/7475. This issue can be closed once confirmed
