### ISSUE TITLE
Console Proxy Url Websocket failed

### ISSUE THREAD

**Issue by troke12** [apache/cloudstack#7317]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Console Proxy
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1.1
~~~

### in Global Settings
<img width="849" alt="Screenshot 2023-03-07 at 11 48 50 AM" src="https://user-images.githubusercontent.com/10250068/223323712-5d33c1fa-982d-4db0-b748-e03289cd2534.png">

### This is our current topology
![Console_proxy drawio (3)](https://user-images.githubusercontent.com/10250068/223323113-efb37bc3-3b30-466c-b6dd-2052d9922dde.png)

### Error websocket
<img width="1680" alt="Screenshot 2023-03-07 at 11 52 04 AM" src="https://user-images.githubusercontent.com/10250068/223324314-d6a68a3f-77f1-4234-adef-ae424cc82283.png">

**Comment by Kirembu** [comment]
This is also affecting me. 
The error I'm getting on the Proxy is 404 "/websockify" Not found

I can't seem to get where that endpoint should be or if there is a problem with the console proxy system vm.
Any luck with this issue @troke12 ?

**Comment by troke12** [comment]
> This is also affecting me. 
> The error I'm getting on the Proxy is 404 "/websockify" Not found
> 
> CLOUDSTACK VERSION
> 
> `4.17.2.0` 
> 
> I can't seem to get where that endpoint should be or if there is a problem with the console proxy system vm.
> Any luck with this issue @troke12 ?

Until now, still same issue

But I think from your issue it's needed to enable websocket by webserver ?

**Comment by Kirembu** [comment]
> > This is also affecting me.
> > The error I'm getting on the Proxy is 404 "/websockify" Not found
> > CLOUDSTACK VERSION
> > `4.17.2.0`
> > I can't seem to get where that endpoint should be or if there is a problem with the console proxy system vm.
> > Any luck with this issue @troke12 ?
> 
> Until now, still same issue
> 
> But I think from your issue it's needed to enable websocket by webserver ?

Thank for the response...
I don't think that's the issue:

I'm using Nginx to proxy the console url and I have added the required web socket configs:
Example:

```
    location /websockify {
      proxy_pass http://172.16.7.12;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      # Don't disconnect if inactive.
      proxy_read_timeout 600s;
      # Disable caching of VNC stream.
      proxy_buffering off;
    }
```


But I'm still getting this message:

> 404 Not Found
> No context found for request

I'm proxying the request to the Console proxy IP Address: [172.16.7.12]

No context found for request

**Comment by troke12** [comment]
Is that any solution that for noVNC configuration that not start with that parameter?

**Comment by weizhouapache** [comment]
> > Hi @troke12, did you check the CPVM logs when trying to display a VM console? If possible can you set DEBUG level on it and share it? The file should be on /var/log/cloud.log
> 
> Hi @nvazquez
> 
> Right now i have same problem with @Kirembu
> 
> The `/websockify` it's not found because they are not running under domain and it is must be using port, the cloudstack management when we click the button "View Console" is directly start with parameter `port=8080`
> 
> for example `https://mydomain.com/resource/noVNC/vnc.html?autoconnect=true&port=8080&token=xxxxxxxx`
> 
> I'm already setting in nginx like this
> 
> ```
> location /websockify {
> proxy_pass http://172.16.25.37:8080/websockify;
> proxy_http_version 1.1;
> }
> ```
> 
> But if we tried to remove the parameter `&port=8080` it's works well

@troke12 
can you upload ssl certiticate in cloudstack as well ?
please refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

**Comment by troke12** [comment]
> @troke12 can you upload ssl certiticate in cloudstack as well ? please refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

I though it was not from SSL, because i tried to directly open the console in browser and theres is no problem with the SSL, but the main problem it's from noVNC 

This is when i tried to open with the parameter `port=8080`

![image](https://user-images.githubusercontent.com/10250068/228267851-31611b40-3170-499a-8c95-d4fb1f1e3baa.png)

This is when i open **without** parameter `port=8080` and worked as well without port and the ssl also works fine

![image](https://user-images.githubusercontent.com/10250068/228269650-3456642c-0943-41a0-9531-f504bee4963b.png)

So i think it's the problem with the route the console proxy

![image](https://user-images.githubusercontent.com/10250068/228271524-b403934b-95a3-4c00-927a-19628038a401.png)

when i trace inside console proxy VM, there are 2 ports that i've been focused,

- 8080 it's for the websockify endpoint and authentication (?)
- 80 it's for the noVNC server 

is that correct?

**Comment by weizhouapache** [comment]
> > @troke12 can you upload ssl certiticate in cloudstack as well ? please refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/
> 
> I though it was not from SSL, because i tried to directly open the console in browser and theres is no problem with the SSL, but the main problem it's from noVNC
> 
> This is when i tried to open with the parameter `port=8080` as default
> 
> ![image](https://user-images.githubusercontent.com/10250068/228267851-31611b40-3170-499a-8c95-d4fb1f1e3baa.png)
> 
> This is when i open **without** parameter `port=8080` and worked as well without port and the ssl also works fine
> 
> ![image](https://user-images.githubusercontent.com/10250068/228269650-3456642c-0943-41a0-9531-f504bee4963b.png)
> 
> So i think it's the problem with the route the console proxy
> 
> ![image](https://user-images.githubusercontent.com/10250068/228271524-b403934b-95a3-4c00-927a-19628038a401.png)
> 
> when i trace inside console proxy VM, there are 2 ports that i've been focused,
> 
> * 8080 it's for the websockify endpoint and authentication (?)
> * 80 it's for the noVNC server
> 
> is that correct?

@troke12 
As far as I know, yes websickify port is 8080 if http or 8443 if https.
can you test with port=8443 instead of port=8080 ?

**Comment by troke12** [comment]
> @troke12 As far as I know, yes websickify port is 8080 if http or 8443 if https. can you test with port=8443 instead of port=8080 ?

@weizhouapache 

Already tried to upload my certificates that i got from cloudflare using cloudmonkey
`cloudmonkey upload customcertificates id=1 certificates='XXXXXXXXX' privatekey='AAAAAAAAA' domainsuffix='*.mydomain.com'`

it is successfully uploaded to cloudstack management, both SSVM and CPVM automatically restarted but i check CPVM and ssh on it, i check that theres no port running 8443, i tried to destroy the CPVM only but still no services running port 8443

<img width="727" alt="Screenshot 2023-03-29 at 9 52 00 AM" src="https://user-images.githubusercontent.com/10250068/228414272-f738421d-2128-46f1-a672-a3cfba1b241b.png">

**Comment by weizhouapache** [comment]
@troke12 

I think you need to make few changes. my suggestions are

###### 1. upgrade cloudstack

###### 2. upload SSL certificates in cloudstack, and change global settings
- consoleproxy.sslEnabled = true
- consoleproxy.url.domain = "your domain name"
- restart mgmt server and recreate CPVM

###### 3. update nginx config
- :443 to https://xxx/  ( you already did)
- :8443/websockify to https://xxx:8443/websockify (configured as ssl port)

**Comment by troke12** [comment]
> @troke12
> 
> I think you need to make few changes. my suggestions are
> 
> ###### 1. upgrade cloudstack
> ###### 2. upload SSL certificates in cloudstack, and change global settings
> * consoleproxy.sslEnabled = true
> * consoleproxy.url.domain = "your domain name"
> * restart mgmt server and recreate CPVM
> 
> ###### 3. update nginx config
> * :443 to https://xxx/  ( you already did)
> * :8443/websockify to https://xxx:8443/websockify (configured as ssl port)

@weizhouapache 

for me the final solution is **upgrade**

for solution point no. 2 already configured as well and I've explained it in the description on this issue and still not working.

for solution point no. 3 literally will not working because `/websockify` are not running for 8443 port, websockify only run 8080 and it's only for http, i found that inside the code of cloudstack in different branch ver 4.16 and 4.18 for vncserver websockify 8443 only in ver 4.18 version of cloudstack, for version 4.17 it's also don't have that (for @Kirembu i think this is your problem). So that's why the final solution it's upgrade to 4.18

**Comment by weizhouapache** [comment]
> > @troke12
> > I think you need to make few changes. my suggestions are
> > ###### 1. upgrade cloudstack
> > ###### 2. upload SSL certificates in cloudstack, and change global settings
> > 
> > * consoleproxy.sslEnabled = true
> > * consoleproxy.url.domain = "your domain name"
> > * restart mgmt server and recreate CPVM
> > 
> > ###### 3. update nginx config
> > 
> > * :443 to https://xxx/  ( you already did)
> > * :8443/websockify to https://xxx:8443/websockify (configured as ssl port)
> 
> @weizhouapache
> 
> for me the final solution is **upgrade**
> 
> for solution point no. 2 already configured as well and I've explained it in the description on this issue and still not working.
> 
> for solution point no. 3 literally will not working because `/websockify` are not running for 8443 port even we setup the nginx configuration to 8080 for masking it's really not working, 8080 it's only for http, i found that inside the code of cloudstack in different branch ver 4.16 and 4.18 for vncserver websockify 8443 only in ver 4.18 version of cloudstack, for version 4.17 it's also don't have that (for @Kirembu i think this is your problem). So that's why the final solution it's upgrade to 4.18

@troke12 
sorry I thought you are running with cloudstack 4.18 or 4.17. the ports are diferent in 4.16.

can you share your nginx setting ?

**Comment by troke12** [comment]
> @troke12 sorry I thought you are running with cloudstack 4.18 or 4.17. the ports are diferent in 4.16.
> 
> can you share your nginx setting ?

here my setting

```nginx
server {
        listen 80;
        listen [::]:80;
        server_name console.mydomain.id;
        return 301 https://$server_name$request_uri;

}
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name console.mydomain.id;

        #Certificate pathes
        ssl_certificate /etc/letsencrypt/live/npm-1/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/npm-1/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;

        client_max_body_size 3584K;

        location / {
                proxy_pass http://172.16.25.31;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
}

server {
        listen 8080 ssl;
        listen [::]:8080 ssl;
        server_name console.mydomain.id;

        #Certificate pathes
        ssl_certificate /etc/letsencrypt/live/npm-1/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/npm-1/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;

        client_max_body_size 3584K;

        location /pop {
               add_header Content-Type text/plain;
               return 200 'gangnam style!';
        }

        location / {
                proxy_pass http://172.16.25.31;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
}
```

for listen 8080 is not working, but if i try to setting to the 8443 is working `https://console.mydomain.id:8443/pop`

**Comment by weizhouapache** [comment]
@troke12 
1. You must upload SSL certificate, and restart mgmt server/CPVM.
2. update the 443 part to the following (the setting for websocket is not needed)
```
        location / {
                proxy_pass https://172.16.25.31;
        }
```
3. update the 8080 part  to
```
        location /websockify {
                proxy_pass https://172.16.25.31/websockify;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
```

**Comment by troke12** [comment]
> @troke12
> 
> 1. You must upload SSL certificate, and restart mgmt server/CPVM.
> 2. update the 443 part to the following (the setting for websocket is not needed)
> 
> ```
>         location / {
>                 proxy_pass https://172.16.25.31;
>         }
> ```
> 
> 3. update the 8080 part  to
> 
> ```
>         location /websockify {
>                 proxy_pass https://172.16.25.31:8080/websockify;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>         }
> ```

1. I'm already upload the certificates using cloudmonkey (you can see [my comment](#issuecomment-1487874061) before)
2. I know this, when we tried to restart CPVM while the global config ssl is true, i must configured the proxy_pass for 443 to `https` scheme, It's worked well fine
3. But only port 8080 that cannot listen when i setting to `https` scheme inside nginx, tried to check the port 8080 from nginx it's not used by nginx, but still not working

**Comment by weizhouapache** [comment]
> 3. But only port 8080 that cannot listen when i setting to `https` scheme inside nginx, tried to check the port 8080 from nginx it's not used by nginx, but still not working

@troke12 
Have you tried my suggestion in previous comment ?
Do not use "location /"

**Comment by troke12** [comment]
> 
> > 3. But only port 8080 that cannot listen when i setting to `https` scheme inside nginx, tried to check the port 8080 from nginx it's not used by nginx, but still not working
> 
> @troke12 
> Have you tried my suggestion in previous comment ?
> Do not use "location /"

Yes, I only set to /websockify, but still not working

**Comment by weizhouapache** [comment]
> > > 3. But only port 8080 that cannot listen when i setting to `https` scheme inside nginx, tried to check the port 8080 from nginx it's not used by nginx, but still not working
> > 
> > 
> > @troke12
> > Have you tried my suggestion in previous comment ?
> > Do not use "location /"
> 
> Yes, I only set to /websockify, but still not working

@troke12 
can you share the nginx setting ?
I was able to access the console in my testing

**Comment by troke12** [comment]
> > > > 3. But only port 8080 that cannot listen when i setting to `https` scheme inside nginx, tried to check the port 8080 from nginx it's not used by nginx, but still not working
> > > 
> > > 
> > > @troke12
> > > Have you tried my suggestion in previous comment ?
> > > Do not use "location /"
> > 
> > 
> > Yes, I only set to /websockify, but still not working
> 
> @troke12 can you share the nginx setting ? I was able to access the console in my testing

sure, here the settings

```nginx
server {
        listen 80;
        listen [::]:80;
        server_name console.mydomain.id;
        return 301 https://$server_name$request_uri;

}
server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name console.mydomain.id;

        #Certificate pathes
        ssl_certificate /etc/letsencrypt/live/npm-7/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/npm-7/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;

        client_max_body_size 3584K;

        location / {
                proxy_pass https://172.16.25.31;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
}
server {
        listen 8080 ssl;
        listen [::]:8080 ssl;
        server_name console.mydomain.id;

        #Certificate pathes
        ssl_certificate /etc/letsencrypt/live/npm-7/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/npm-7/privkey.pem;

        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;

        client_max_body_size 3584K;

        location /pop {
               add_header Content-Type text/plain;
               return 200 'gangnam style!';
        }

        location /websockify {
                proxy_pass https://172.16.25.31:8080;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
        }
}
```

**Comment by weizhouapache** [comment]
> proxy_pass https://172.16.25.31:8080;

this should be 

proxy_pass https://172.16.25.31:8080/websockify;

**Comment by troke12** [comment]
> > proxy_pass https://172.16.25.31:8080;
> 
> this should be
> 
> proxy_pass https://172.16.25.31:8080/websockify;

already do that before (https://github.com/apache/cloudstack/issues/7317#issuecomment-1486647897 both https or http and still not working)

**Comment by weizhouapache** [comment]
> > > proxy_pass https://172.16.25.31:8080;
> > 
> > 
> > this should be
> > proxy_pass https://172.16.25.31:8080/websockify;
> 
> already do that before ([#7317 (comment)](https://github.com/apache/cloudstack/issues/7317#issuecomment-1486647897) both https or http and still not working)

@troke12 
my nginx conf has more lines than yours. It works. 
If you need, I can share with you by email.

**Comment by troke12** [comment]
sure, my email it's ***@***.***    On Wednesday, April 5, 2023 at 01:14:02 PM GMT+7, Wei Zhou ***@***.***> wrote:  
 
 





proxy_pass https://172.16.25.31:8080;


this should be
proxy_pass https://172.16.25.31:8080/websockify;


already do that before (#7317 (comment) both https or http and still not working)


@troke12
my nginx conf has more lines than yours. It works.
If you need, I can share with you by email.

**Comment by troke12** [comment]
> > > > proxy_pass https://172.16.25.31:8080;
> > > 
> > > 
> > > this should be
> > > proxy_pass https://172.16.25.31:8080/websockify;
> > 
> > 
> > already do that before ([#7317 (comment)](https://github.com/apache/cloudstack/issues/7317#issuecomment-1486647897) both https or http and still not working)
> 
> @troke12 my nginx conf has more lines than yours. It works. If you need, I can share with you by email.

sure, my email was on my profile github page

**Comment by weizhouapache** [comment]
@troke12 
I am closing this issue. if you still have the problem, please feel free to reopen

**Comment by AxelPanda** [comment]
@weizhouapache Hello, I have just the same problem as troke12, could you please share your nginx conf file? Thanks.

**Comment by troke12** [comment]
> sorry @AxelPanda @herdiansah571 I do not use the nginx config for now.
> 
> @troke12 Have you configured nginx to support MGMT servers and CPVM/SSVM ? If so, can you share the config files ? thanks

i'm already configured with nginx but it's fixed after upgrading, i can reshare the config nginx that you give me before to adjust by as they needed

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 8080 ssl http2;

    server_name                 *.[domain.com](http://domain.com/)

    access_log                  off;
    error_log                   /dev/null   crit;

    ssl_certificate             /root/SSLcerts/main.crt;
    ssl_certificate_key         /root/SSLcerts/private.key;
    ssl_dhparam                 /etc/nginx/dhparam.pem;

    ssl_session_timeout         5m;
    ssl_session_cache           shared:SSL:10m;
    ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers                 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4';
    ssl_prefer_server_ciphers   on;

    ssl_stapling                on;
    ssl_stapling_verify         on;

    add_header                  Strict-Transport-Security max-age=63072000;

    resolver                    8.8.4.4 8.8.8.8 valid=300s;
    resolver_timeout            10s;

    location /websockify {
        proxy_pass https://10.0.57.121:8080/websockify;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
    }
}


server {
    listen                      443 ssl http2;

    server_name                 *.[domain.com](http://domain.com/)

    access_log                  off;
    error_log                   /dev/null   crit;

    ssl_certificate             /root/SSLcerts/main.crt;
    ssl_certificate_key         /root/SSLcerts/private.key;
    ssl_dhparam                 /etc/nginx/dhparam.pem;

    ssl_session_timeout         5m;
    ssl_session_cache           shared:SSL:10m;
    ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers                 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4';
    ssl_prefer_server_ciphers   on;

    ssl_stapling                on;
    ssl_stapling_verify         on;

    add_header                  Strict-Transport-Security max-age=63072000;

    resolver                    8.8.4.4 8.8.8.8 valid=300s;
    resolver_timeout            10s;

    location / {
        client_max_body_size 0;
        client_body_buffer_size 8k;

        proxy_cache off;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
        proxy_request_buffering off;
        proxy_redirect off;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_set_header X-signature $http_x_signature;
        proxy_set_header X-metadata $http_x_metadata;
        proxy_set_header X-expires $http_x_expires;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' ', Content-Type, origin, authorization, accept, client-security-token, x-signature, x-metadata, x-expires';

        set $uuid         "$1";
        proxy_pass https://10.0.57.121/;
    }
}
```
