### ISSUE TITLE
SystemVM's are in running state but agent status is down

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7318]
SystemVM's agent down

##### ISSUE TYPE

 * Other

##### COMPONENT NAME

SystemVM

##### CLOUDSTACK VERSION

4.17

##### CONFIGURATION

Used Advance network in KVM

##### OS / ENVIRONMENT

Management ,NFS on same server - Centos
KVM on another server -Centos

##### SUMMARY

Systemvm are showing as running and I can see on kvm it is in running state. But agent status is down and also in management log secondary storage vm is not up. 
On KVM I can able to get the console using virsh console <systemvm id> it will ask for login user and password. 
But on cloudstack ui agent is down and I can't able to upload any iso as secondary storage is not up till now

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by Noelantogerorge** [comment]
I am new to cloudstack so sorry for the unwanted questions... I haven't give the tag for physcial network and I have added only one physical network. Is that the issue tha systemvm agaent not working?

**Comment by DaanHoogland** [comment]
> I am new to cloudstack so sorry for the unwanted questions... I haven't give the tag for physcial network and I have added only one physical network. Is that the issue tha systemvm agaent not working?

No @Noelantogerorge , having just one physical network should be possible but the chances are it is your network setup. There is a check-ssvm.sh script on the ssvm. run that to see more information .  https://cwiki.apache.org/confluence/display/CLOUDSTACK/SSVM%2C+templates%2C+Secondary+storage+troubleshooting

**Comment by Noelantogerorge** [comment]
@DaanHoogland Thank you for your response.. 
I think there is some networking issue or network miss configuration happed. Please find the log below

root@s-5-VM:/usr/local/cloud/systemvm# sh ssvm-check.sh
================================================
First DNS server is  8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
92 bytes from 10.60.0.199: Destination Host Unreachable
92 bytes from 10.60.0.199: Destination Host Unreachable
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
WARNING: cannot ping DNS server
route follows
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.60.0.1       0.0.0.0         UG    0      0        0 eth2
8.8.8.8         10.60.0.191     255.255.255.255 UGH   0      0        0 eth1
10.60.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth1
10.60.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth2
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 eth0
================================================
ERROR: DNS not resolving cloudstack.apache.org
resolv.conf follows
nameserver 8.8.8.8
nameserver 8.8.8.8

**Comment by kiwiflyer** [comment]
@Noelantogerorge 

Take a look in your zone configuration and see if you specified 8.8.8.8 as your "Internal DNS 1". If so, remove it and only specify 8.8.8.8 as your external dns and the static route should be removed once you restart the SSVM. 

You can find that under Infrastructure / Zones / The Name of Your Zone.

Look at the "Details" tab and click the Edit button on the top right of the screen.

**Comment by Noelantogerorge** [comment]
@kiwiflyer 
Thank you....
I had tried removing "Internal DNS 1" but even after clearing the value same 8.8.8.8 is coming back when we press ok button. I think "Internal DNS 1" is a mandatory filed so just tried with my gateway ip and it accept it. On my enviornment there is no internal dns server we use goolge dns.. Do i need to configure a dns server internaly?

Also my concern is that on pinging kvm host from ssvm it is getting reply whereas it is not getting reply if I ping to our gateway IP.

**Comment by weizhouapache** [comment]
@Noelantogerorge 
you can log into the systemvms using " virsh console". the username is "admin" and password is "password".

The agent not in Up state is normally because the system vms cannot connect to management server.
you can log into the system vms, and check if the management server is reachable.
please upload /var/log/cloud.log in system vms if possible.

**Comment by Noelantogerorge** [comment]
Hi,
I was able to login to ssvm using the ssh key. Please find the log attached. Also I have attached my network configuration in cloudstack UI for your referrence..
[cloud.log](https://github.com/apache/cloudstack/files/10919246/cloud.log)
[network_conf.pdf](https://github.com/apache/cloudstack/files/10919286/network_conf.pdf)

**Comment by weizhouapache** [comment]
> Hi, I was able to login to ssvm using the ssh key. Please find the log attached. Also I have attached my network configuration in cloudstack UI for your referrence.. [cloud.log](https://github.com/apache/cloudstack/files/10919246/cloud.log) [network_conf.pdf](https://github.com/apache/cloudstack/files/10919286/network_conf.pdf)

@Noelantogerorge 
as you may have noticed, the system vm cannot connect to the management server (10.60.0.120:8250)

can you ping the kvm host ip (also in 10.60.0.0/24 ?) in system vm ?

**Comment by Noelantogerorge** [comment]
Yes, i can able to ping kvm host.

**Comment by weizhouapache** [comment]
> Yes, i can able to ping kvm host.

@Noelantogerorge
OK. so it seems like the packets from the system vm are not forwarded to management server.

Please check the firewall on the kvm host.

**Comment by Noelantogerorge** [comment]
I had disabled selinux and firewalld on kvm.

**Comment by weizhouapache** [comment]
> I had disabled selinux and firewalld on kvm.

@Noelantogerorge 
can you share more details on the host ?

ip a
ip route
brctl show

**Comment by Noelantogerorge** [comment]
Please find the attached details..

**Comment by Noelantogerorge** [comment]
[brctl_show.txt](https://github.com/apache/cloudstack/files/10921961/brctl_show.txt)
[ip_route.txt](https://github.com/apache/cloudstack/files/10921962/ip_route.txt)
[ip_a.txt](https://github.com/apache/cloudstack/files/10921963/ip_a.txt)

**Comment by weizhouapache** [comment]
> firewalld

@Noelantogerorge 
They look ok.

can you share the output of `iptables-save` and `cat /proc/sys/net/ipv4/conf/cloudbr0/forwarding` ?

**Comment by Noelantogerorge** [comment]
please find the output below
[root@kvmhost2 ~]# iptables-save
# Generated by iptables-save v1.4.21 on Wed Mar  8 21:29:54 2023
*filter
:INPUT ACCEPT [30008:243105400]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [56264:285763585]
-A INPUT -p tcp -m tcp --dport 49152:49216 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5900:6100 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 16514 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 16509 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1798 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Wed Mar  8 21:29:54 2023
[root@kvmhost2 ~]# cat /proc/sys/net/ipv4/conf/cloudbr0/forwarding
1
[root@kvmhost2 ~]# cat /proc/sys/net/ipv4/ip_forward
1

[root@kvmhost2 ~]# service firewalld status
Redirecting to /bin/systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Mar 03 05:00:39 kvmhost2 systemd[1]: Starting firewalld - dynamic firewall daemon...
Mar 03 05:00:42 kvmhost2 systemd[1]: Started firewalld - dynamic firewall daemon.
Mar 03 05:00:42 kvmhost2 firewalld[894]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Mar 08 06:20:49 kvmhost2 systemd[1]: Stopping firewalld - dynamic firewall daemon...
Mar 08 06:20:50 kvmhost2 systemd[1]: Stopped firewalld - dynamic firewall daemon.

**Comment by weizhouapache** [comment]
@Noelantogerorge 
all looks ok.

can you confirm
- ping works, from systemvm to kvm host (10.60.0.121)
- ping does not work, from system vm to management server (10.60.0.120)
- ping does not work, from system vm to other ips (10.60.0.1, 10.60.0.191, 8.8.8.8, etc)

can you also share the output of the commands in the system vm ?
- ip a
- ip route


by the way, do you use virtual instance or physical server as kvm host?

**Comment by Noelantogerorge** [comment]
Please find my updates below

- ping works, from systemvm to kvm host (10.60.0.121) - **yes it works** 
- ping does not work, from system vm to management server (10.60.0.120) - **yes ping does not work**
- ping does not work, from system vm to other ips (10.60.0.1, 10.60.0.191, 8.8.8.8, etc) - **yes ping does not work**

From SystemVM

root@s-9-VM:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0e:00:a9:fe:7e:e8 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 169.254.126.232/16 brd 169.254.255.255 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 1e:00:3d:00:00:10 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    altname ens4
    inet 10.60.0.210/24 brd 10.60.0.255 scope global eth1
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 1e:00:d4:00:00:1b brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 10.60.0.190/24 brd 10.60.0.255 scope global eth2
       valid_lft forever preferred_lft forever

root@s-9-VM:~# ip route
default via 10.60.0.1 dev eth2 
8.8.8.8 via 10.60.0.1 dev eth1 
10.60.0.0/24 dev eth1 proto kernel scope link src 10.60.0.210 
10.60.0.0/24 dev eth2 proto kernel scope link src 10.60.0.190 
169.254.0.0/16 dev eth0 proto kernel scope link src 169.254.126.232 

I use virtual instance as KVM host..

**Comment by Noelantogerorge** [comment]
Please find my updates below

   - ping works, from systemvm to kvm host (10.60.0.121) - *yes it works*
   - ping does not work, from system vm to management server (10.60.0.120)
   - *yes ping does not work*
   - ping does not work, from system vm to other ips (10.60.0.1,
   10.60.0.191, 8.8.8.8, etc) - *yes ping does not work*

From SystemVM

***@***.***:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group
default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state
UP group default qlen 1000
link/ether 0e:00:a9:fe:7e:e8 brd ff:ff:ff:ff:ff:ff
altname enp0s3
altname ens3
inet 169.254.126.232/16 brd 169.254.255.255 scope global eth0
valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state
UP group default qlen 1000
link/ether 1e:00:3d:00:00:10 brd ff:ff:ff:ff:ff:ff
altname enp0s4
altname ens4
inet 10.60.0.210/24 brd 10.60.0.255 scope global eth1
valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state
UP group default qlen 1000
link/ether 1e:00:d4:00:00:1b brd ff:ff:ff:ff:ff:ff
altname enp0s5
altname ens5
inet 10.60.0.190/24 brd 10.60.0.255 scope global eth2
valid_lft forever preferred_lft forever

***@***.***:~# ip route
default via 10.60.0.1 dev eth2
8.8.8.8 via 10.60.0.1 dev eth1
10.60.0.0/24 dev eth1 proto kernel scope link src 10.60.0.210
10.60.0.0/24 dev eth2 proto kernel scope link src 10.60.0.190
169.254.0.0/16 dev eth0 proto kernel scope link src 169.254.126.232

I use virtual instance as KVM host..

With Regards,
Nixon Varghese,

*"*Ability is of little account without opportunity.*."*

**Comment by Noelantogerorge** [comment]
Please advise where have we gone wrong?

With Regards,
Nixon Varghese,

*"*Ability is of little account without opportunity.*."*

**Comment by weizhouapache** [comment]
@Noelantogerorge 
 can you ping the system vm ips (10.60.0.210 and 10.60.0.190) from the kvm host and management server ?

**Comment by weizhouapache** [comment]
@Noelantogerorge 
you can also use tcpdump to investigate where the packet is dropped.

**Comment by Noelantogerorge** [comment]
Thank you all for supporting me for identifying the issue. 
Fixed the Issue.. It was some configuration issue on KVM host.. Rebuilt the same reslove the issue. Sorry as I am new to cloudstack I could't able to identify where have I gone wrong..
Thank you so much

**Comment by weizhouapache** [comment]
> A quick doubt is it possible to add 1 more NIC to a guest VM which should have a public IP. Example my server is having 2 NIC eth0 to local lan and eth1 to my public IP. How can I bring the same network concept on cloudstack.. I have bring up a guest VM on isolated network and i can see eth0 is having lan IP of my guest vm cidr. Now I need to add 1 more NIC with my public ip address.

@Noelantogerorge 
you can create a shared network with public ips, and add the vm to the network.

**Comment by Noelantogerorge** [comment]
> > Thank you all for supporting me for identifying the issue. Fixed the Issue.. It was some configuration issue on KVM host.. Rebuilt the same reslove the issue. Sorry as I am new to cloudstack I could't able to identify where have I gone wrong.. Thank you so much
> 
> @Noelantogerorge good you have fixed it.
> 
> can you share more details which could help other users ?

Step where I had gone wrong is that when configuring I had installed KVM packages from virtualization repo and then I installed cloudstack agent and do the necesary configuration as per documentation. I belive that might some lib files to cause some configuration issue with cloudstack agent.
On second installation I just do the necessary firewall and host settings and install cloudstack agent. As kvm is part of cloudstack agent it installed correctly with all necessary lib files and it worked without any issue.

**Comment by weizhouapache** [comment]
> > > Thank you all for supporting me for identifying the issue. Fixed the Issue.. It was some configuration issue on KVM host.. Rebuilt the same reslove the issue. Sorry as I am new to cloudstack I could't able to identify where have I gone wrong.. Thank you so much
> > 
> > 
> > @Noelantogerorge good you have fixed it.
> > can you share more details which could help other users ?
> 
> Step where I had gone wrong is that when configuring I had installed KVM packages from virtualization repo and then I installed cloudstack agent and do the necesary configuration as per documentation. I belive that might some lib files to cause some configuration issue with cloudstack agent. On second installation I just do the necessary firewall and host settings and install cloudstack agent. As kvm is part of cloudstack agent it installed correctly with all necessary lib files and it worked without any issue.

@Noelantogerorge 
thanks for the sharing.
which cloudstack version do you use ? what's the OS version and qemu versions (in 1st and 2nd installation) ?

**Comment by Noelantogerorge** [comment]
> > A quick doubt is it possible to add 1 more NIC to a guest VM which should have a public IP. Example my server is having 2 NIC eth0 to local lan and eth1 to my public IP. How can I bring the same network concept on cloudstack.. I have bring up a guest VM on isolated network and i can see eth0 is having lan IP of my guest vm cidr. Now I need to add 1 more NIC with my public ip address.
> 
> @Noelantogerorge you can create a shared network with public ips, and add the vm to the network.

@weizhouapache Thank you for the advice. I tried to create it but it is showing below error
"The IP range with tag: vlan://untagged in zone Zone-1 has overlapped with the subnet. Please specify a different gateway/netmask." 
As I am testing this on lan network I had given public ip address when creating Zone is same lan network.

**Comment by weizhouapache** [comment]
> > > A quick doubt is it possible to add 1 more NIC to a guest VM which should have a public IP. Example my server is having 2 NIC eth0 to local lan and eth1 to my public IP. How can I bring the same network concept on cloudstack.. I have bring up a guest VM on isolated network and i can see eth0 is having lan IP of my guest vm cidr. Now I need to add 1 more NIC with my public ip address.
> > 
> > 
> > @Noelantogerorge you can create a shared network with public ips, and add the vm to the network.
> 
> @weizhouapache Thank you for the advice. I tried to create it but it is showing below error "The IP range with tag: vlan://untagged in zone Zone-1 has overlapped with the subnet. Please specify a different gateway/netmask." As I am testing this on lan network I had given public ip address when creating Zone is same lan network.

It looks you have created another network (probably management network ?) with vlan://untagged.
please make sure there is no overlap
