### ISSUE TITLE
Create storage pool fails when no hosts have been added yet

### ISSUE THREAD

**Issue by vdombrovski** [apache/cloudstack#7322]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2 (also affects older versions)
~~~

##### CONFIGURATION

1 Advanced Zone
1 POD
1 Cluster
Zero hosts added

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Adding a primary storage (of type Ceph in this case) fails with the following error when no hosts have been added yet

```
com.cloud.utils.exception.CloudRuntimeException: Failed to create storage pool as it is not accessible to hosts.
```

##### STEPS TO REPRODUCE

Start with a clean install of the manager, add a Zone,Pod,Cluster then try adding Primary Storage

~~~
# Using cmk
cmk create storagepool name=CEPH-CHI url="rbd://cloudstack:[CEPH_AUTH]@ceph:6789/cloudstack" zoneid=[ZONE_ID] provider=DefaultPrimary scope=zone hypervisor=KVM
~~~

##### EXPECTED RESULTS

The storage pool gets created

##### ACTUAL RESULTS

~~~
Failed to add data store: Failed to create storage pool as it is not accessible to hosts.
com.cloud.utils.exception.CloudRuntimeException: Failed to create storage pool as it is not accessible to hosts.
        at org.apache.cloudstack.storage.datastore.lifecycle.CloudStackPrimaryDataStoreLifeCycleImpl.attachZone(CloudStackPrimaryDataStoreLifeCycleImpl.java:492)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:826)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:237)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
       [...]
~~~

Looking here: https://github.com/apache/cloudstack/blob/main/plugins/storage/volume/default/src/main/java/org/apache/cloudstack/storage/datastore/lifecycle/CloudStackPrimaryDataStoreLifeCycleImpl.java#L470

The command returns all hosts that are enabled and up, then connects it to the shared pool in our case. However, when the list is empty, then `if (poolHosts.isEmpty()) ` condition gets triggered, failing the creation.

As this connection is done anyway when adding a new host, I don't see why one couldn't add a new primary storage without having any hosts during deployment.

**Note:** we are deploying Cloudstack using Ansible, so we're not following the order provider by the UI wizard.

**Comment by weizhouapache** [comment]
@vdombrovski 
As you can see in the code and log, when create a primary storage pool, cloudstack will verify if the pool is accessible on kvm hosts. It makes sense to me. Otherwise there is no validation on the pools.

Assume we add multiple pools without validation but there is an issue with one of the pools. When we add a host, the host will not work, as virsh/libvirt commands on pools will be stuck.

**Comment by weizhouapache** [comment]
@vdombrovski 
I am closing this ticket. if you think it is a valid bug, please free feel to reopen or create a new issue.
