### ISSUE TITLE
Event results in unwanted error log

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7324]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

The following appears in the event log, while no errors seem to occur:
~~~
(non-prod) 🐵 > list events id=11792702-7314-49a9-9e95-fb57e6981499
{
  "count": 1,
  "event": [
    {
      "account": "system",
      "created": "2023-03-07T16:00:07-0300",
      "description": "Error while creating entity for allocating snapshot",
      "domain": "ROOT",
      "domainid": "8141c7d0-69b1-11eb-af2b-00505681f744",
      "id": "11792702-7314-49a9-9e95-fb57e6981499",
      "level": "ERROR",
      "state": "Created",
      "type": "SNAPSHOT.CREATE",
      "username": "system"
    }
  ]
}
~~~
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
no error event
~~~

##### ACTUAL RESULTS

~~~
an event that alerts the user to an error that never happened.
~~~

**Comment by shwstppr** [comment]
I'm not able to reproduce this. *allocating snapshot* is published by VolumeApiServiceImpl.allocSnapshot (called by CreateSnapshotCmd.create()). If API command's create fails with the exception it shouldn't have called execute() method.

We need more logs to analyze this. From my tests and code investigation on 4.18 branch I don't see this happening

**Comment by DaanHoogland** [comment]
I have no clue how to continue further on this. It seems it is a one time one environement fluke. I suppose we should close this untill we have more data.
