### ISSUE TITLE
Does CloudStack support the High-Availability Virtual IP Address using Keepalived?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7331]
![image](https://user-images.githubusercontent.com/4197714/224647672-962bd068-7a1f-4c5a-a014-b21119118613.png)

If supported, and how to use it?

like below:
Two ECS instances are based on HaVip and use Keepalived to form a highly available private network service. Other instances within the VPC can access this service through the private network using the HaVip address as the service address. When the primary ECS instance fails, the standby ECS instance automatically invokes its takeover program to take over the service of the primary ECS instance, achieving business high availability.

![image](https://user-images.githubusercontent.com/4197714/224648362-3925f1ad-b0fd-48ea-be75-fe3255416960.png)

**Comment by weizhouapache** [comment]
@xuanyuanaosheng 
cloudstack supports redundant virtual routers for isolated network and vpcs, as virtual routers are the most important component of  isolated network and vpcs.
The feature is implemented by keepalived, and primary/backup VRs have the VIP (which is the gateway of isolated network or vpc tier). 
However, this does not support user vms as the OS is fully managed by users. You need to configure keepalived inside your user vms.

You could consider the load balancer feature in cloudstack. There is also a VPC feature named internal Load balancer.

**Comment by xuanyuanaosheng** [comment]
@weizhouapache  Thanks.

**Comment by weizhouapache** [comment]
closing thsi ticket

@xuanyuanaosheng 
please feel free to reopen if you have more question.
