### ISSUE TITLE
Failover of RADOS monitor when intergrate Cloudstack with CEPH RBD

### ISSUE THREAD

**Issue by tuanhoangth1603** [apache/cloudstack#7334]
Hello, 
When integrating CEPH RBD as the primary storage for Cloudstack, we can only input one IP address of the node running the monitor service into the 'RADOS monitor' field, while typically, CEPH cluster has at least 3 monitor nodes. It seems that there is no HA capability if this monitor node stops working.

When I turn off the monitor service:

- The running VMs still function normally and can be rebooted.
- However, if VM stopped, it cannot start again, and the agent reports an error of not finding the domain in Virsh.
- Also, I cannot create new VMs
So, is there any way to achieve HA by inputting multiple IP addresses of RADOS monitor nodes? Will this issue be considered for resolution in the future?

**Comment by weizhouapache** [comment]
Hi @tuanhoangth1603 
this issue has been fixed by #6792 
You can test 4.18.0.0-RC3 which includes the fix.

**Comment by tuanhoangth1603** [comment]
Thanks so much !
