### ISSUE TITLE
keyboard setting in noVNC not functional when using vmware7

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7335]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Console/noVNC
~~~

##### CLOUDSTACK VERSION

~~~
4.17
4.18
~~~

##### SUMMARY

When using vmware 7 and noVNC japanese (and probably all non US) keyboards do not work.

##### STEPS TO REPRODUCE

~~~
log in with language set to a non US/english setting (i.e. japanese)
open a console
~~~

##### EXPECTED RESULTS

~~~
keyboard takes locale input
~~~

##### ACTUAL RESULTS

~~~
keyboard behaves as US/intl
~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7694
