### ISSUE TITLE
Templates become Inactive after restarting

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#7342]
See screenshots below

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Template
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

1. register a template with invalid url

![image](https://user-images.githubusercontent.com/57355700/225308426-3bd67593-16c9-42d4-8c38-3c3d89d4789e.png)

2. restart mgmt server
![image](https://user-images.githubusercontent.com/57355700/225308757-5d56fba4-9026-4a68-813a-150cdba736e4.png)

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@weizhouapache I'm not able to reproduce this on 4.18 env with KVM hypervisor. Even after restarting MS it shows template status as `HTTP Server returned 404 (expected 200 OK)`

**Comment by weizhouapache** [comment]
@shwstppr 
I just tested again on 4.18.0.0

1. register template with cross-zones
![image](https://user-images.githubusercontent.com/57355700/234050705-131b3659-3b5b-4d87-93f3-510e20d34b76.png)


2. template is not downloaded
![image](https://user-images.githubusercontent.com/57355700/234050803-eebd410e-6b8c-47b5-bb92-37244ed8d469.png)


3. restart mgmt server
![image](https://user-images.githubusercontent.com/57355700/234051120-39443437-02ba-4450-a12d-b33102a9e57d.png)
