### ISSUE TITLE
Cannot delete image store with active templates backup!

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7347]
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.17.2.0 update from 4.16.0.0 verson by verison
~~~

##### CONFIGURATION

~~~
Advanced zone
~~~
##### OS / ENVIRONMENT

~~~
Oracle Linux 8
~~~

##### SUMMARY

I added new zone, tested it and want to delete it. I've removed almost all from zone, but forgot about templates. And now I cant delete secodary storage. 

##### STEPS TO REPRODUCE

~~~
1. Create zone
2. Download any templates
3. Delete all elements from zone without templates
4. try to delete secondary storage 
~~~

##### EXPECTED RESULTS

~~~
Secondary storage is deleted
~~~

##### ACTUAL RESULTS

~~~
Secondary storage is not deleted
~~~

**Comment by top-secrett** [comment]
Can I just delete all records about this templates in DB?

**Comment by top-secrett** [comment]
it helped me
~~~
update image_store set removed="2023-03-16 18:14:00" where id=3;
~~~

**Comment by DaanHoogland** [comment]
@top-secrett did you mark the templates as removed (see template_store_ref and vm_template)?

**Comment by top-secrett** [comment]
@DaanHoogland 
It didn't help. I marked records of system templates like removed by example of another records in tables
update vm_template set state="Inactive" where id=7;
update vm_template set state="Inactive" where id=8;
update vm_template set removed="2023-03-16 12:39:09" where id=7;
update vm_template set removed="2023-03-16 12:39:09" where id=8;
update template_zone_ref set removed="2023-03-16 12:39:09" where zone_id=4;
update template_store_ref set state="Destroyed" where template_id=8;
update template_store_ref set destroyed="1" where template_id=8;

**Comment by shwstppr** [comment]
@top-secrett can you please share order of steps you followed while trying to delete your zone?

**Comment by top-secrett** [comment]
@shwstppr I can't provide exacltly the same steps. 
I disabled the zone, deleted all VMs and system VMs, hosts, cluster, pod then primary storage. Tried to delete secondary storage and got error: 
"2023-03-16 17:25:18,016 INFO  [c.c.a.ApiServer] (qtp1278254413-749:ctx-f77a0409 ctx-568e7caf) (logid:876adab3) Cannot delete image store with active templates backup!"
After that I tried to delete templates and got errors, but after CS reboot, templates dissapiared.

Only this helped:
~~~
update image_store set removed="2023-03-16 18:14:00" where id=3;
~~~

**Comment by shwstppr** [comment]
@top-secrett thank you for the update. The error is shown when there are still templates available for the secondary store(and its zone). I feel this is the expected behaviour. Operator must delete all active templates for the zone first which can be done using UI or API,
```
list templates zoneid=<ZONE_ID> templatefilter=all listall=true filter=id,name
delete template zoneid=<ZONE_ID> id=<TEMPLATE_ID>
```
If you faced an error while deleting or if after deleting all templates for the zone you were still unable to remove the secondary store then there could be a bug. We may need logs or reproduction steps for that.

**Comment by top-secrett** [comment]
@shwstppr Please, tell me what should I grep in my logs?

**Comment by shwstppr** [comment]
@top-secrett would need logs for the time when you tried deleting templates using UI or API and it failed. You may have to search in logs for the relevant error for deleteTemplate API and then can grep the job specific logs using job id.

In case you didn't try deleting those active templates then this is not an issue.

**Comment by top-secrett** [comment]
@shwstppr Ok. I am not able to reproduce it again. Let's close issue
