### ISSUE TITLE
Cloudstack 4.18 ubuntu packages

### ISSUE THREAD

**Issue by furyflash777** [apache/cloudstack#7353]
Hello.
Cloudstack 4.18 packages are not available in any ubuntu repository after release. 

Could you please add 4.18 packages to http://download.cloudstack.org/ubuntu/dists/focal/

**Comment by wido** [comment]
We are aware of this. I have been trying to build the packages, but I have run into some issues with Python 2 and 3 in the newer Ubuntu versions.

@rohityadavcloud Do you maybe have an idea to get these build?

**Comment by kiranchavala** [comment]
Hi @wido 

Please refer to this PR  #7269 by @weizhouapache 

And also #7315 if you want to build via docker

**Comment by wido** [comment]
I have been checking for 20.04, but that failed me as well. At the moment I am time constraint and I will do this asap.

**Comment by DaanHoogland** [comment]
@furyflash777 can you try again? (cc @wido )

**Comment by weizhouapache** [comment]
packages have been built and uploaded to http://download.cloudstack.org/ubuntu/dists/

thanks @wido @DaanHoogland
