### ISSUE TITLE
api call listRoles name filter not working as expected

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#7362]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### SUMMARY

When using parameter name with api call listRoles it lists all roles which have the value of name in the actual name instead of the roles with the exact value of name. Parameter keyword should be used to filter when wanting to find all roles where the value is part of the name.

##### STEPS TO REPRODUCE

~~~
Create a new role with name "New Domain Admin".
Do the following api call: /client/api/?command=listRoles&name=Domain%20Admin&response=json
~~~

##### EXPECTED RESULTS

~~~
You should only get 1 result back. The result should be the default "Domain Admin" role.
~~~

##### ACTUAL RESULTS

~~~
You get 2 results back. The default "Domain Admin" and the new created "New Domain Admin".
~~~

**Comment by kiranchavala** [comment]
Able to reproduce the issue 

(scmk) 🐱 > list roles  name=Domain Admin response=json
{
  "count": 2,
  "role": [
    {
      "description": "Default domain admin role",
      "id": "2acbd609-cdea-11ed-b8aa-1e000a0003b1",
      "isdefault": true,
      "name": "Domain Admin",
      "type": "DomainAdmin"
    },
    {
      "description": "New Domain Admin",
      "id": "ae9b8992-e5f2-45a5-8adb-26c1bd0209aa",
      "isdefault": false,
      "name": "New Domain Admin",
      "type": "DomainAdmin"
    }
  ]
}

**Comment by nvazquez** [comment]
Hi @sbrueseke @kiranchavala, I was checking the name paramenter behaviour on listVirtualMachines and it does not retrieve the exact VM name when I set it. For example, check this:

````
(localcloud) 🐱 > list virtualmachines name=test filter=id,name
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "096fc02b-fe71-41e8-bc81-412d2e31b70d",
      "name": "TestVM"
    }
  ]
}
````

That makes me wonder if this is a bug or not, what do you think?

**Comment by harikrishna-patnala** [comment]
@nvazquez listVMs was fixed later. It is listing with exact name, I've checked the code as well.

(localcloud) 🐱 > list virtualmachines name=TestVM filter=id,name
{
  "count": 1,
  "virtualmachine": [
    {
      "id": "f4ff60b2-d17a-46af-bb16-caa8d2221dd5",
      "name": "TestVM"
    }
  ]
}
(localcloud) 🐱 > list virtualmachines name=Test filter=id,name
(localcloud) 🐱 > 
(localcloud) 🐱 > 
(localcloud) 🐱 > list virtualmachines name=test filter=id,name
(localcloud) 🐱 >

**Comment by harikrishna-patnala** [comment]
I've created a new PR to fix roles search (in UI as well). Along with that I've fixed other scenarios where keyword is already there, I made the name to be exact search https://github.com/apache/cloudstack/pull/7384

**Comment by nvazquez** [comment]
Thanks @harikrishna-patnala, I was not using the latest version on my test env, have verified on 4.18 and is fixed as you mentioned (https://github.com/apache/cloudstack/pull/6032)

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7384
