### ISSUE TITLE
how can we migrate vm from proxmox to cloudstack??

### ISSUE THREAD

**Issue by Kwakye-Emmanuel** [apache/cloudstack#7371]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@Kwakye-Emmanuel is this to be extended with more information? are you writing that howto?
the ticket is very unclear like this and will probably not get a follow-up unless it is from you.

**Comment by rohityadavcloud** [comment]
cc @andrijapanicsb @alexandremattioli

**Comment by andrijapanicsb** [comment]
cc on what :)

**Comment by leolage** [comment]
Hi, I can show you how to transfer a qcow image of a virtual machine to the Cloudstack storage. I have previously accomplished this by creating a virtual machine on Cloudstack and then replacing the disk file of the VM with the qcow image copied from Proxmox.

**Comment by Kwakye-Emmanuel** [comment]
ok, please show me

**Comment by rohityadavcloud** [comment]
@Kwakye-Emmanuel 4.19 has a KVM ingestion feature using which you can import a qcow2 file of a stopped proxmox based VM and get it imported to a CloudStack+KVM env. For further questions that aren't bug report but questions on how-to, kindly ask on the users mailing list or Github actions.
