### ISSUE TITLE
Secondary NIC for public network in Instance

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7376]
I need my Instance to have 1 NIC for public network. 

##### ISSUE TYPE

 * Other

##### COMPONENT NAME

UI

~~~

##### CLOUDSTACK VERSION
<!--
New line separated list of affected versions, commit ID for issues on main branch.
-->

4.17.2

~~~

##### CONFIGURATION

Advance Networking

##### OS / ENVIRONMENT

Management server on Ubuntu 
KVM on Ubuntu

##### SUMMARY

I am trying to add secondary NIC for a instance. I need to have public IP on that interfaces. While trying to create a shared network with my public IP details it is showing CIDR overlap with Zone. I had given same public IP while creating the Zone where it ask for public IP. 
How can I have 2 interface like LAN and PUBLIC for my instance

~~~

**Comment by kiranchavala** [comment]
Hi @Noelantogerorge 

AFAIK

The zone's physical network public range should not overlap with shared network cidr.

You should give a separate cidr when creating a shared network 

Zone  network

Infrastructure>zone>Physical network

![zone-physical-network](https://user-images.githubusercontent.com/1401014/228525180-cd6a29b7-dcd1-4837-b626-653cd25c3925.png)


Shared network 

![Screenshot](https://user-images.githubusercontent.com/1401014/228525566-95ad0317-c168-4be2-91c2-eed557b14351.png)

**Comment by Noelantogerorge** [comment]
@kiranchavala 
Thank you for the response..
I have public network on 134.x.x.x and privent network on 192.168.x.x
On creating zone I had provided 134.x.x.x as my public network and 192.168.x.x as my pod IP.
I should provide pubilc network itself for Zone right.
Then cloudstack will not allow to create shared network with public network..

**Comment by kiranchavala** [comment]
@Noelantogerorge the public network 134.x.x.x  which you have provided during the zone creation is used by the systemvms , routers (vpc,isolated  networks)

It's not possible for the VM to have a second nic/interface with a public ip  of (134.x.x.x,)

If you want the VM to acquire a public ip (134.x.x.x)  you need to create a isolated 

![Screenshot1](https://user-images.githubusercontent.com/1401014/228738230-90315397-39d0-4c2d-8186-eecc5a167b05.png)

Enable static nat , portforwarding,firewall rules

![Screenshot2](https://user-images.githubusercontent.com/1401014/228738236-ae2fec5d-cd63-4272-9d2f-cb4738449a5c.png)

---------------------


If you are creating a shared network, and you want the vm to get a public ip  on the nic , you have to aquire a different public range say 189.xxx. 


Please refer to the documenation 

http://docs.cloudstack.apache.org/en/latest/adminguide/index.html#managing-networks-and-traffic

**Comment by Noelantogerorge** [comment]
I had divided my public network 134.x.x.x to small subnets and make the kvm host interface as truck port so I can get all subnet on kvm and create the zone on 1 subnet and a shared network on next subnet. I was able to spin up a instance with LAN nic and WAN nic
