### ISSUE TITLE
Display Only the Advanced Zones when creating a "AutoScale Vm groups".

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7409]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

component:UI

##### SUMMARY

Display Only the Advanced Zones when creating a "AutoScale Vm groups".

Currently, the autoscaling feature is only supported in Advanced zone as it requires LB support and only isolated network and vpc support LB.

The admin user should not be able to create an Autoscale vm Group in a basic zone.

We can add a filter to show any Advance/Core zones

-------------
Steps to reproduce the issue

1. Create a basic zone  

2. Create a autoscale vm group 

Compute > Autoscale vm group > New Autoscale Vm group

[Screencast from 06-04-23 02:34:29 PM IST.webm](https://user-images.githubusercontent.com/1401014/230331272-40e55544-3371-4cca-9802-2815fd720a76.webm)

##### EXPECTED RESULTS

The admin user should not be able to create a Autoscale vm Group in a basic zone.

##### ACTUAL RESULTS

The admin user is having the option to  create a Autoscale vm Group in a basic zone.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7411
