### ISSUE TITLE
Remove the option of Edit tags insecurity group (Ingress rules/Egress rules)

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7412]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

component:UI

##### SUMMARY

Remove the option to Edit tags a security group (Ingress rules/Egress rules)

Steps to reproduce the issue

1. Create a basic zone

2. Network >Security Group> Select any Security  Group > Ingress rule /Egress rule 

3. Click on Action item (edit tags)

4. End user will be unable to add any tag as there is no supporting api call 

[Screencast from 06-04-23 03:21:24 PM IST.webm](https://user-images.githubusercontent.com/1401014/230342291-91b90617-28c4-4749-9d97-7f5016440e02.webm)

The backend api call doesn't support tags

https://cloudstack.apache.org/api/apidocs-4.18/apis/authorizeSecurityGroupEgress.html

https://cloudstack.apache.org/api/apidocs-4.18/apis/authorizeSecurityGroupIngress.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/revokeSecurityGroupEgress.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/revokeSecurityGroupIngress.html

##### EXPECTED RESULTS

No option should be provided in the UI to edit security group ingress/Egrees rules

##### ACTUAL RESULTS

Option is provided in the UI to edit security group ingress/Egrees rules

**Comment by shwstppr** [comment]
@kiranchavala It is supposed to use `createTags` API but the form doesn't seem to work properly at the moment. Will add a fix

**Comment by weizhouapache** [comment]
fixed by #7424
