### ISSUE TITLE
Unable to import instance from VMware to CS

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7420]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

~~~
advanced networking, vmware zone
~~~

##### OS / ENVIRONMENT

OracleLinux 8, vSphere Client version 6.7.0.54000

##### SUMMARY

Error "Please enter a valid value.: CPU (in MHz)" when import VM from VMware,

##### STEPS TO REPRODUCE

1. In VMware Vsphere create, clone or restore VM by Veeam. Connect it to existing guest network
2. Find VM in CS "Import-Export instances" section.
3. Select it and push "Import Instance"
4. Fill required fields, choose right compute offering
5. Push "OK" button

##### EXPECTED RESULTS

~~~
VM is imported to CS
~~~

##### ACTUAL RESULTS

~~~
Get error "Please enter a valid value.: CPU (in MHz)"
~~~

![image](https://user-images.githubusercontent.com/92435079/230897635-e0ea755b-2cbb-43f6-b8fd-fc0bffc8e704.png)
![image](https://user-images.githubusercontent.com/92435079/230897977-2e9ed25e-b94e-4ddb-bda6-7e0195172793.png)

**Comment by shwstppr** [comment]
@top-secrett can you please check if import works fine when using a fixed compute offering or an unconstrained offering?

**Comment by top-secrett** [comment]
@shwstppr It works only with a fixed compute offering, with an unconstrained offering I got the same error.
Thank you

**Comment by shwstppr** [comment]
@top-secrett thanks will have a look

**Comment by weizhouapache** [comment]
fixed by https://github.com/apache/cloudstack/pull/7423
