### ISSUE TITLE
listVirtualMachinesUsageHistory API date filter dosen't work 

### ISSUE THREAD

**Issue by nimabm** [apache/cloudstack#7422]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### OS / ENVIRONMENT

Ubuntu 20.04

##### SUMMARY
listVirtualMachinesUsageHistory API with start date variable doesn't return enough record, that's just return 2 latest record.

##### STEPS TO REPRODUCE

~~~
call URL like this : 
http://localhost:8080/client/api?apiKey=Mzd8BAOkjGPQvSPHeeuB6mwYZGKVG5FVj-QtwCLw46n0q34h9VbFQ53KfrgilHK5Gbpe0x3oGxpLTqdHGv_7GQ&command=listVirtualMachinesUsageHistory&id=52100d05-9855-4b27-adae-d02fe5923f70&response=json&startdate=2023-04-10&signature=wFfxO19SBWhfDofal42EXXYmwqE%3D
~~~

##### EXPECTED RESULTS

~~~
I expect this URL to return data with all of record from start date 
~~~

##### ACTUAL RESULTS

~~~
{"listvirtualmachinesusagehistoryresponse":{"count":1,"virtualmachine":[{"id":"51100d05-9855-4b27-adae-d02fe5923f70","name":"i-192-755-VM","stats":[{"timestamp":"2023-04-10T17:40:23+0330","cpuused":"2.29%","diskioread":0,"diskiowrite":0,"diskiopstotal":0,"diskkbsread":0,"diskkbswrite":0,"memoryintfreekbs":736080,"memorykbs":1048576,"memorytargetkbs":1048576,"networkkbsread":12,"networkkbswrite":0,"networkread":"0.01 MiB","networkwrite":"0.00 MiB"}]}]}}
~~~

**Comment by shwstppr** [comment]
@nimabm have you tried providing startdate with the required format?

From docs,

```
startdate start date to filter stats.Use format "yyyy-MM-dd hh:mm:ss"
```

**Comment by GutoVeronezi** [comment]
Hello @nimabm 

Could you provide the values of the global configurations `vm.stats.max.retention.time` and `vm.stats.interval`?

**Comment by nimabm** [comment]
> Hello @nimabm
> 
> Could you provide the values of the global configurations `vm.stats.max.retention.time` and `vm.stats.interval`?

thanks ,I define "vm.stats.max.retention.time" parameter value and issue has been fixed
