### ISSUE TITLE
Not able to change compute offering in a Kubernetes cluster when using KVM VMs

### ISSUE THREAD

**Issue by saffronjam** [apache/cloudstack#7454]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Kubernetes
~~~

##### CLOUDSTACK VERSION
~~~
4.18
~~~

##### CONFIGURATION
Default, following guides provided by CloudStack

##### OS / ENVIRONMENT
Ubuntu 22.04

KVM hypervisor

##### SUMMARY
Changing compute offering when scaling Kubernetes cluster results in error saying that it is not support.

".. on KVM is not supported!"

I expect to be able to change the compute offering after the cluster is created.
For a use case such as: increasing the RAM since a heavy app requires it.

##### STEPS TO REPRODUCE
~~~
- create a Kubernetes cluster on KVM VMs
- scale the cluster with a different compute offering
~~~

##### EXPECTED RESULTS
~~~
I expect to be able to change compute offering for a Kubernetes cluster
~~~

##### ACTUAL RESULTS
~~~
Error popup saying that it is not supported on KVM.
~~~

Error in code:
https://github.dev/apache/cloudstack/blob/2ac1b7e9599b048d3490577b0823752fc7a740d7/plugins/integrations/kubernetes-service/src/main/java/com/cloud/kubernetes/cluster/actionworkers/KubernetesClusterScaleWorker.java#L240

**Comment by saffronjam** [comment]
Adding on to this, I presume this has to do with the "running" part.

Error message:
``` ... cluster with running VMs on hypervisor ... ```

However, if I would stop the Kubernetes cluster, then I don't have any option to scale it. So:

1. Cluster is in Running state -> Can't scale with new compute offering because the virtual machines are running
2. Cluster is NOT in Running state -> Can't scale with new compute offering because there is no option apart from "Start cluster" and "Delete cluster"

**Comment by kiranchavala** [comment]
Hi @saffronjam 

I was able to reproduce the issue 

![Scaling-k8s](https://user-images.githubusercontent.com/1401014/233919262-bcce1ec0-3731-45c6-a75c-025b8f4335a0.png)



Currently scaling of running vms is only supported on vmware and xenserver

http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html?highlight=scaling#cpu-and-memory-scaling-for-running-vms

It could be a limitation on the kvm side 

http://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html?highlight=scaling#cpu-and-memory-scaling-for-running-vms



Can you follow these steps

1. Stop the Kubernetes cluster , the vm's associated with kubernetes cluster will also be in stopped state

2. Now go to instance > stopped vm of the k8s cluster > scale the vm 

or  Execute the api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/scaleVirtualMachine.html

3. Start the Kubernetes cluster

**Comment by saffronjam** [comment]
I tried the approach suggested above, and the nodes appears to have been scaled.
However, I noticed that the cluster configuration is no longer synchronized with the nodes. The cluster still says it is using the old configuration. 

Since I thought that this would cause broken scaling (new nodes would get the old offering), I reverted the changes.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7475
