### ISSUE TITLE
TF: Tungsten Fabric needs a Public IP per service, ACS UI allows to try to place more than 1 service per public IP.

### ISSUE THREAD

**Issue by alexandremattioli** [apache/cloudstack#7459]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI (maybe API as well)
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

KVM on Centos 7 , Tungsten Fabric

##### SUMMARY

In a normal isolated network a user can add multiple services with the same public IP (sourceNAT, Port Forwarding, etc...).
With the Tungsten Fabric Plugin that's not possible (no conserve mode equivalent). But the UI doesn't stop an end user from trying (and getting errors)

##### STEPS TO REPRODUCE

~~~
Add isolated network, go to the source nat public IP, try to add a service (e.g. port forwarding).
~~~

##### EXPECTED RESULTS

~~~
UI shouldn't allow to place more than 1 service per public IP
~~~

##### ACTUAL RESULTS

~~~
UI allows to attempt to place more than 1 service per public IP. Action fails without proper explanation
~~~

**Comment by weizhouapache** [comment]
fixed by #7511
