### ISSUE TITLE
NoVNC cannot be accessed through a browser

### ISSUE THREAD

**Issue by Python-IBM** [apache/cloudstack#7481]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
UI

##### CLOUDSTACK VERSION
Cloudstack 4.18.0.0

##### CONFIGURATION
basic network

##### OS / ENVIRONMENT
Linux Centos 7.9

##### SUMMARY
After I created the host using the basic network, I tried to open the console page of the system KVM and redirected to the h5 page of Novnc. However, I was unable to access it properly.

##### STEPS TO REPRODUCE
1. System KVM Information
![image](https://user-images.githubusercontent.com/33851767/235070666-592ace8b-b70e-40c2-ace4-bca590c8ebfc.png)

2. Physical network information
![image](https://user-images.githubusercontent.com/33851767/235071199-003f82bc-9049-4f08-a402-060e23017b0d.png)

3. Click on the console on the KVM page
![image](https://user-images.githubusercontent.com/33851767/235070763-d62f892b-9e3d-4aef-b7c0-4e0276a981d1.png)

![image](https://user-images.githubusercontent.com/33851767/235070818-a414b1c5-f1f1-4cea-afdb-94904f2f5c83.png)

4. NoVNC has been loading for a long time without displaying the console
![image](https://user-images.githubusercontent.com/33851767/235071057-781e65f7-ecba-434c-b0a8-4352cead42f3.png)

##### EXPECTED RESULTS
I hope to access the H5 page of the console normally through NoVNC and be able to log in and operate the KVM virtual machine

##### ACTUAL RESULTS
NoVNC cannot be accessed through a browser

**Comment by Python-IBM** [comment]
> 
I have re edited the issue content according to the template requirements. Please help me identify any issues.

**Comment by Python-IBM** [comment]
> 
I have re edited the issue content according to the template requirements. Please help me identify any issues.


> Thanks for opening your first issue here! Be sure to follow the issue template!

I have re edited the issue content according to the template requirements. Please help me identify any issues.

**Comment by Python-IBM** [comment]
> Thanks for opening your first issue here! Be sure to follow the issue template!

I have re edited the issue content according to the template requirements. Please help me identify any issues.

**Comment by weizhouapache** [comment]
@Python-IBM 
the agent of system vms are not Up. It seems they (in 192.168.21.0/24) cannot connect to the management server (in 192.168.100.0/24)

please check your network configuration if the gateways and routes are configured correctly.

**Comment by toneskoturw** [comment]
When I upgraded to 4.18, I encountered the same problem as you. I manually shutdown the ConsoleProxy VM, and the VM automatically restarted, problem solved. (restarting the CPVM did not solve the problem). hope it help.

但是我认为楼主的问题应该是楼上指出的，进入CPVM ping一下通不通。

Here is the logs I found:

tail management log: 
Could not send allow session command to CPVM: Resource [Host:3] is unreachable: Host 3: Host with specified id is not in the right state: Disconnected

ssh -i ~/.ssh/id_rsa.cloud -p 3922 root@169.254.127.152
tail /var/log/messages
iptables-restore v1.8.7 (nf_tables): invalid port/service `${VNCPORT}' specified

**Comment by Python-IBM** [comment]
> @Python-IBM the agent of system vms are not Up. It seems they (in 192.168.21.0/24) cannot connect to the management server (in 192.168.100.0/24)
> 
> please check your network configuration if the gateways and routes are configured correctly.
Ok, let me check,thanks!
