### ISSUE TITLE
[cleanup] unused code in file PropertiesStorage.java

### ISSUE THREAD

**Issue by nikam14** [apache/cloudstack#7487]
##### ISSUE TYPE

 
 * Improvement Request
 * Enhancement Request

##### SUMMARY

location: agent/src/main/java/com/cloud/agent/dao/impl/PropertiesStorage.java
line no - 122, 128, 146
screnshots-
![1](https://user-images.githubusercontent.com/55378196/235640804-13cd33fb-2f23-4839-a22f-27ce34330f1a.PNG)
![2](https://user-images.githubusercontent.com/55378196/235640852-6d507880-61e6-4c7f-8f11-0bf5799d658b.PNG)
![3](https://user-images.githubusercontent.com/55378196/235640882-baddc0d3-f494-44da-95c4-e80f4977191f.PNG)

There are some methods which are declared but do not have any working.
these methods can be removed.

##### EXPECTED RESULTS

~~~
can remove that code
~~~

**Comment by rohityadavcloud** [comment]
Thanks for the issue @nikam14 you're welcome to submit a PR to cleanup. Code specific changes need not always require an issue, you can directly raise a PR instead.
