### ISSUE TITLE
Unable to find management port group Management Network while migrating instances

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7491]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

Advanced networking
VMware cluster
vSphere Client version 6.7.0.54000

##### OS / ENVIRONMENT

OracleLinux 8

##### SUMMARY

After reboot vSphere Client and whole VMware infrastructure we got an error while migration instances. Before reboot all worked fine.
Error:
MigrateCommand failed due to [Exception: java.lang.Exception Message: Unable to find management port group Management Network ].
Management port group "Management Network" present in VMware: 
![image](https://user-images.githubusercontent.com/92435079/235911727-75625d5a-52ca-44ae-a281-bc09c0bd2482.png)

Full log:
[ManagementNetworkError.txt](https://github.com/apache/cloudstack/files/11382232/ManagementNetworkError.txt)

##### EXPECTED RESULTS

~~~
Migration successful
~~~

##### ACTUAL RESULTS

~~~
Migration failed
~~~

**Comment by kiranchavala** [comment]
@top-secrett 

Could you please try to unmanage /Manage the cluster and then try to migrate a vm 

![unmange](https://user-images.githubusercontent.com/1401014/236741640-d2b3a24d-c540-4b05-9826-db00247793d5.png)

**Comment by rohityadavcloud** [comment]
@top-secrett did you restart cloudstack management server as well after the VMware infra was rebooted?

**Comment by top-secrett** [comment]
@kiranchavala @rohityadavcloud I restarted CS management server and tryed to unmanage/manage clusters, but i get the same error

**Comment by top-secrett** [comment]
@rohityadavcloud  @kiranchavala hello guys. Any suggestions to resolve problem?

**Comment by rohityadavcloud** [comment]
Sorry I missed your message @top-secrett - you can simply try to create the port-group manually on the destination host. Ideally you can create a distributed vswitch and migrate all your guest network/port groups to the dvswitch.

**Comment by top-secrett** [comment]
@rohityadavcloud We are already using distributed vswitch with port group "Management Network"

**Comment by rohityadavcloud** [comment]
@top-secrett if this is an env where all the old svs were migrated to dvs, then you'll need to create the management network portgroup in the migrated DVS and in CloudStack enable the global setting `vmware.use.dvswitch`. You may also read https://www.shapeblue.com/cloudstack-vmware-environment-migration-from-vswitch-to-dvswitch/

I'm not sure if the docs website suggests these, this could be a docs issue - cc @DaanHoogland @weizhouapache

**Comment by top-secrett** [comment]
@rohityadavcloud should we use VLAN in "vmwarenetworklabel" zone parameter with dvs?
![image](https://github.com/apache/cloudstack/assets/92435079/48b6bcae-2595-4e9c-b054-fa28dfc8bdc0)

**Comment by DaanHoogland** [comment]
@top-secrett did you get any new information on this? is it still a problem?

**Comment by top-secrett** [comment]
@DaanHoogland It is still a problem. In 2 old clusters we can't migrate VMs. We added a new pod in existing zone and there is no problem

**Comment by harikrishna-patnala** [comment]
@top-secrett can you check the following details for your particular host from the managed object browser. You will need to first find the host in the path. (https://<vcenterIP>/mob   then click on "Service Content" then "rootFolder" then "chilldEntity" then "hostFolder" then "childEntity" then "host" here you can moid of the host)

Management server is trying to query https://<vCenterIP>/mob/?moid=host-1009&doPath=config.virtualNicManagerInfo.netConfig  and in that it is searching for value of nicType with "management" 

![image](https://github.com/apache/cloudstack/assets/3348673/79980b6c-72f4-4d7d-a363-2caf8cdad7e4)

The corresponding entry from vCenter I can see it here

![image](https://github.com/apache/cloudstack/assets/3348673/e3832bcf-4478-4c03-b060-46c65b1e39ad)

Can you check if can list the similar details for your host.

**Comment by top-secrett** [comment]
@harikrishna-patnala 
![image](https://github.com/apache/cloudstack/assets/92435079/10b170e9-a5d0-48e7-b705-8c70634542b4)
![image](https://github.com/apache/cloudstack/assets/92435079/1cc56012-e60b-4e59-ba00-f0dcbc3b532b)

**Comment by JoaoJandre** [comment]
This issue seems like a environmental issue, not a bug; thus, I'll be removing it from the 4.18.2.0 milestone. 
@SadiJr you have some experience with VMware, could you take a look at this?

**Comment by SadiJr** [comment]
@top-secrett could you please provide a little more information:

1. The migration fails between some specific hosts, or between any hosts? Also, are you only experiencing errors in the migration process?
2. Could you please review if your global configuration `vmware.management.portgroup` has the correct value? Please also check if there is a typo, or maybe a blank space at the start or the end of the configuration.
3. Could you please check, in every ESXi host, in `Networking` -> `VMkernel NICs` if the name of the `Management Network` is correct?

**Comment by top-secrett** [comment]
@SadiJr Hello. Sorry for delay. 
1. I have 3 clusters in a one vSphereClient. Migration fails among all hosts in cluster-183_185-1 and cluster-183_185-2, but works in cluster-185. I found migrations errors only, everyting works fine except that.
![image](https://github.com/apache/cloudstack/assets/92435079/d461b4a3-a97d-4935-8ab8-8f3e5f6b4a6e)
![image](https://github.com/apache/cloudstack/assets/92435079/9466f500-c6b9-442f-8513-6800221550ac)
2. There is no any additional spaces or symbols
![image](https://github.com/apache/cloudstack/assets/92435079/69530b76-bb62-4dd4-bdb8-d638010aabf5)
3. All hosts from 3 clusters connected to the same network  
![image](https://github.com/apache/cloudstack/assets/92435079/354e7a13-d886-4e74-b56a-854b1ecaeca9)

**Comment by top-secrett** [comment]
I don't know what happened, but migration is working now.
