### ISSUE TITLE
Guest Networks not visible in cloudstack 4.18 while creating VMs

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#7497]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Guest Networks not visible in cloudstack 4.18 while creating VMs
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
While creating advanced zone not allowing to skip VLAN/VNI range. After adding a range not allowing to create guest VLAN for any VLAN in that range and what ever  guest subnet we create not visible in UI while creating Compute instance. 

Ex - 
VLAN/VNI range I set to 1-5 VLAN Ids. So it's not allowing to create any guest subnet with VLAN ID 1-5 . After creating subnet with VLAN ID 6 subnet is not visible during VM creation . Where it's a new setup and we have only ROOT domain.  

##### EXPECTED RESULTS
Guest VLAN/Subnet should be visible during VM creation for selection. 

~~~

**Comment by kiranchavala** [comment]
@yashi4engg 

Specifying the guest vlan's is only available during zone creation

![guestvlan](https://user-images.githubusercontent.com/1401014/236740585-d6379f1c-e80b-4ea3-b515-aeeaaf42aa90.png)

If you want to add more guest vlans to a zone , you can try updating it from the UI or via the api call 

![guestvlan2](https://user-images.githubusercontent.com/1401014/236740691-95e0714f-2cef-4c5b-a4e5-1fbfb14d1d31.png)


Also you can view the available vlan from this tab

![guestvlan3](https://user-images.githubusercontent.com/1401014/236740766-b058fbcc-fe89-4f7f-836b-44b396777b55.png)


Whenever a create a isolated network , a random vlan from the avaible guest vlans will be allocated to the network 

If you want a specific vlan associated then you can use the api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/createNetwork.html

https://cloudstack.apache.org/api/apidocs-4.18/apis/updatePhysicalNetwork.html

**Comment by yashi4engg** [comment]
thanks for the update ..let me try that
