### ISSUE TITLE
Unable to execute updateNetworkOffering api call when availability=Required is passed

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7510]
##### ISSUE TYPE

 * Improvement/Enhancement request

##### COMPONENT NAME

~~~

Component: UI, API

~~~

##### CLOUDSTACK VERSION

~~~
4.18 


~~~

##### SUMMARY

Unable to execute updateNetworkOffering api call when availability=Required is passed

Steps to reproduce the issue 

Case 1
--------

1. Log in as admin user 

2. Create some network offerings, make sure to select guest type as isolated and source nat in supported services

Let's say you have created a network offering 1

3. Edit the network offering (network offering 1) and change the availability to true

Screenshot

<img width="775" alt="Screenshot 2023-05-10 at 3 42 37 PM" src="https://github.com/apache/cloudstack/assets/1401014/067f511b-845c-4d01-bbe7-420273c2c2f4">

4. Exception 

"System already has network offering id=10 (DefaultIsolatedNetworkOfferingWithSourceNatService) with availability Required"

Expected behavior 
-----------
Ideally admin user should be allowed to set multiple network offerings with source nat as availability required 

At any given point only 1 network offering can be set with availability as required 

Case 2
--------
1. Login as admin user 

2. Create some network offerings, make sure to select guest type as isolated and  do not select source nat in supported services

Let's say you have created network offering 2

3. Edit the network offering (network offering 2) and change the availability to true

4. Exception 

"Availability can be Required only for networkOfferings of type Isolated and with SourceNat enabled"

Expected behavior 
-----------
Ideally, other network offerings can  also be set with availability required, there could be a use case for a normal user to access of network offerings which doesn't contain source nat as a supported service

Currently, available network offerings are 

(DefaultIsolatedNetworkOfferingForVpcNetworksWithInternalLB)
(DefaultSharedNetscalerEIPandELBNetworkOffering)
(DefaultL2NetworkOfferingVlan)
(DefaultSharedNetworkOfferingWithSGService)
(DefaultSharedNetworkOffering)
(DefaultIsolatedNetworkOfferingForVpcNetworksNoLB)
(DefaultIsolatedNetworkOfferingForVpcNetworks)
(DefaultL2NetworkOffering)
(DefaultTungstenSharedNetworkOfferingWithSGService)
(DefaultL2NetworkOfferingConfigDriveVlan)
(DefaultIsolatedNetworkOffering)
(DefaultL2NetworkOfferingConfigDrive)
(DefaultNetworkOfferingforKubernetesService)
(DefaultIsolatedNetworkOfferingWithSourceNatService)
(QuickCloudNoServices)

**Comment by shwstppr** [comment]
@weizhouapache does it make sense to add what you mentioned to the param description? Will help showing info text in UI form for the param. We may also update the error string in the backend

**Comment by weizhouapache** [comment]
> @weizhouapache does it make sense to add what you mentioned to the param description? Will help showing info text in UI form for the param. We may also update the error string in the backend

@shwstppr 
as I remember, networkofferingid is required in the API/UI.
the availability only has impact when cloudstack create a default network for accounts in service layer.
For example, when move a vm to another account but the account does not have any network.

**Comment by DaanHoogland** [comment]
fixed by #7545
