### ISSUE TITLE
cloudstack 4.18 VM ha not working 

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#7520]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
cloudstack 4.18 VM ha not working . We have configured host HA as well and compute offering have VM HA enabled. But VMs not migrating if i power off Hypervisor .

**Comment by weizhouapache** [comment]
@yashi4engg 
can you provide more information ?
os distribution, os version, storage, etc

**Comment by yashi4engg** [comment]
OS - OEL9.1 , Stoarge - Ceph rbd (ceph-quincy) 

Guest VMs running on OS OEL7.9

**Comment by DaanHoogland** [comment]
@yashi4engg I am closing this issue. If you feel this is invalid please reopen or create a new one.
The Host HA issue you opened should be the only issue. VM HA will not activate on (possible) host down.
