### ISSUE TITLE
Offline VM migration in VMware with disk detach causes VM snapshots issues

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7525]
VM snapshot fails with the following steps:

1. Migration of offline virtual machines between clusters
2. Disk attach to that VM
3. Disk detach
4. Disk deletion
5. Obtaining VM snapshot

There is still an issue with the detach volume operation. CloudStack does not send DetachCommand to the vCenter during step 3 and in vCenter the VM continues to show the detached disk.

Ref:
https://github.com/apache/cloudstack/blob/main/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L2781-L2790

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.11, 4.18+
~~~

**Comment by rohityadavcloud** [comment]
Ref: the attach case was fixed in https://github.com/apache/cloudstack/pull/5371

**Comment by DaanHoogland** [comment]
fixed in #7526
