### ISSUE TITLE
mem.overprovisioning not working as expected. 

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#7529]
Mem.overprovisiing value set to 5 . 

mem.overprovisioning.factor -- set to 5 
vm.min.memory.equals.memory.divided.by.mem.overprovisioning.factor - set to true 

But still unable to create VMs more then actual Memory on hypervisor. 
Even if can create more then that it not reflecting on VM and ..vm dumpxml shows assign memory devided by total assigned/over provisioning ratio. 

We want over provisioning to work in a way where if we login to guest should show actual assigned value and we should be able to create VMs with value more than actual available memory similar like VMWare. 

Please guide through global setting tuning if any to make it work ... 

For example ..My hyp have actual mem ory 126GB ...So when i create a VM with 96GB where overprovisioing set to 10 ...VM shows memory in free-g output only 9GB.

**Comment by rajujith** [comment]
@yashi4engg  This looks like a bug to me, CloudStack shouldn't set a lower value for the memory configs in the KVM instead it should use auto ballooning. CC @harikrishna-patnala

**Comment by rohityadavcloud** [comment]
Need review/testing, was KVM ballooning feature on? cc @DaanHoogland @rajujith

**Comment by yashi4engg** [comment]
KVM balloning feature on at Host side but concern here is if we use mem.overprovisioing its not showing assigned memory at VM side and its shows only assigned mem/overprovisioing-ratio .

**Comment by rajujith** [comment]
@yashi4engg  the 'memory unit' in the domain definition should not be changed based on the over provisioning ratio but cloudstack does that currently.

**Comment by rohityadavcloud** [comment]
@yashi4engg do you have memory balloon feature disabled; if you're using KVM do you have `vm.memballoon.disable` set to true or false (or not defined) in your agent.properties?

**Comment by yashi4engg** [comment]
@rohityadavcloud  - we are not using vm.memballoon.disable either true pr false in agent.properties.I think default its true for KVM hosts. But currently for over provisioning to work we are using "host.overcommit.mem.mb" in agent.properties . 

This working but its making confusion when managing load and checking actual memory uses on UI . So we want mem overprovisioning should work in a way where its shoudl show complete aloocated memory on VM side using free command but actually it can use mem.ballooning and over provisioning .

**Comment by rohityadavcloud** [comment]
I've raised a doc PR to explain how it works - pl refer to that https://github.com/apache/cloudstack-documentation/pull/337 in addition to that, we've had a bugfix to improve this - https://github.com/apache/cloudstack/pull/7810

Please re-open ticket with comments, if this work isn't acceptable with suggestions to what do you expect.

**Comment by yashi4engg** [comment]
@rohityadavcloud - I tried to follow that but after that seems baloonning not working and host is not reclaiming free memory and keep on showing memory as used what VM had used max at any point ..
ex - VM used 90% of Mem at a particular point So host not able to release that memory even after one day if current use on VM is less then 10% of aloocated Mem. 


I used below settings :- 
# cat /etc/default/qemu-kvm 
KSM_ENABLED=AUTO

agent.properties file - 
vm.memballoon.disable=false
vm.memballoon.stats.period=0

Also disabled below one from global setting for cluster :- 
mem.overprovisioning.factor - 2
vm.min.memory.equals.memory.divided.by.mem.overprovisioning.factor - false

**Comment by yashi4engg** [comment]
@rohityadavcloud and team  -- Please reopen issue as given solution not working as expected.

**Comment by DaanHoogland** [comment]
@yashi4engg you can not reopen yourself?

**Comment by weizhouapache** [comment]
@rohityadavcloud @DaanHoogland 
any ideas ?

**Comment by DaanHoogland** [comment]
I'll have another shot at reproducing this

**Comment by weizhouapache** [comment]
> @rohityadavcloud - I tried to follow that but after that seems baloonning not working and host is not reclaiming free memory and keep on showing memory as used what VM had used max at any point .. ex - VM used 90% of Mem at a particular point So host not able to release that memory even after one day if current use on VM is less then 10% of aloocated Mem.
> 
> I used below settings :-
> 
> # cat /etc/default/qemu-kvm
> KSM_ENABLED=AUTO
> 
> agent.properties file - vm.memballoon.disable=false vm.memballoon.stats.period=0
> 
> Also disabled below one from global setting for cluster :- mem.overprovisioning.factor - 2 vm.min.memory.equals.memory.divided.by.mem.overprovisioning.factor - false

@yashi4engg @DaanHoogland 
I will test this scenario.

**Comment by weizhouapache** [comment]
@yashi4engg 
I am able to reproduce the issue.
However, I think it is not a bug. As far as I know, qemu/kvm does NOT automatically reclaim unused memory from guest VMs, unless you reduce the memory of guest VMs.

Here are the steps I did
- created 4 VMs with 1GiB memory
- check memory usage of kvm host, it increased around 1.5GiB
- run memory tests to use 512MB memory in each VM
- check memory usage of kvm host, it increased around 1.8GiB
- stop the memory tests, and wait for a hour
- check memory usage of kvm host, it did not change
- reduce the memory of guest VMs to 512MiB
- check memory usage of kvm host, it decreased around 1.2GiB
- increase the memory of guest VMs to 1GiB
- check memory usage of kvm host, it did not change

Some commands
- check memory usage of kvm host: `free -mh`
- memory tests inside vm: `head -c 512m /dev/zero | tail`
- reduce memory of guest VMs on host : `virsh setmem <vm-name> 524288`
- check memory of guest VMs on host: `virsh dommemstat <vm-name>`

**Comment by weizhouapache** [comment]
@DaanHoogland @yashi4engg 
mark it as a minor issue

**Comment by yashi4engg** [comment]
@DaanHoogland  - But its not a Prod use case where its not possbile to reduce and increase memory of VM frequently ...Memory Ballooning should work so free memory should auto relaesed to allocate for other VM if uses increase on another VM .. See below use case - 

1 - We are using Memory overprovisoining
2 - ex- we have deployed 20 VM totale actual memory 128GB and allocated is 200GB due to overporivisoining 
3 - 4-5 at any point uses their max memory example 80GB and after few minuted memory uses on tjose again reduced .
4 - Here whats happening even if actual uses is less but still Host showing Memeory uses high and impacting other VMs if they need some memeory for their uses.

**Comment by weizhouapache** [comment]
> 3 - 4-5 at any point uses their max memory example 80GB and after few minuted memory uses on tjose again reduced .

@yashi4engg 
from what I have tested, the output of `virsh dommemstat` on kvm host is consistent with the `free` command inside vm.
The problem is, how to automatically reclaim allocated but unused memory from guest VMs. You might ask qemu/kvm if it is possible.
(a script to monitor memory usage and reduce/increase memory should work)

btw: from my experience, it is a bad practise to use memory overprovisioning in kvm production environments.

**Comment by weizhouapache** [comment]
> Memory Ballooning should work so free memory should auto relaesed to allocate for other VM if uses increase on another VM 
@yashi4engg 
I think this is out of our scope. do you have other issues ? if not, I am going to close this issue.

**Comment by rohityadavcloud** [comment]
Hi @yashi4engg I've reviewed the comments and supporting data, this isn't a CloudStack bug. Overprovisioning shouldn't be confused with memory ballooning feature or dynamic reclaming. KSM enabled in an env will try to reduce memory consumption, but it's been clearly stated in kvm/libvirt docs that memory ballooning may not be dynamic. Agree with Wei's comments, you shouldn't use memory over provisioning in KVM env if you're not observing gains. The cons of using memory overprovisioning could end up crashing your guest VMs (or host).

**Comment by bhouse-nexthop** [comment]
See #11932
