### ISSUE TITLE
Cloudstack 4.18 HTTP 503 Error on Ubuntu 22.04

### ISSUE THREAD

**Issue by hpepper** [apache/cloudstack#7533]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

Web access fails

##### CLOUDSTACK VERSION

* cloudstack-management: 4.18.0.0

##### OS / ENVIRONMENT

* OS: Ubuntu 22.04.2 LTS
* mysqld --version: /usr/sbin/mysqld  Ver 8.0.33-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

##### SUMMARY

Did a new installation of cloudstack on a new minimal Ubuntu installation.
Following the instructions in [4.18.0.0 installation](http://docs.cloudstack.apache.org/en/4.18.0.0/installguide/index.html#general-installation)

<h2>HTTP ERROR 503 Service Unavailable</h2>

URI: | /client/
-- | --
503
Service Unavailable
-

##

* minimal install of Ubuntu 22.04
* Install cloudstack as per the manuel, except for the iptables part

~~~
May 13 15:36:51 cloudstack java[6754]: INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.>
May 13 15:36:51 cloudstack java[6754]: INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.>
May 13 15:36:51 cloudstack java[6754]: INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.>
May 13 15:36:51 cloudstack java[6754]: INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.>
May 13 15:36:51 cloudstack java[6754]: WARNING: An illegal reflective access operation has occurred
May 13 15:36:51 cloudstack java[6754]: WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/usr/share/cloudstack-management/lib/cloudstack-4.18.0.0.jar) to method java.lang.ClassLoader.>
May 13 15:36:51 cloudstack java[6754]: WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
May 13 15:36:51 cloudstack java[6754]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
May 13 15:36:51 cloudstack java[6754]: WARNING: All illegal access operations will be denied in a future release
May 13 15:36:52 cloudstack java[6754]: INFO  [c.c.u.d.T.Transaction] (main:null) (logid:) Is Data Base High Availiability enabled? Ans : false
May 13 15:36:56 cloudstack java[6754]: ERROR [c.c.u.d.Merovingian2] (main:null) (logid:) Unable to get a new db connection
May 13 15:36:56 cloudstack java[6754]: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
May 13 15:36:56 cloudstack java[6754]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
May 13 15:36:56 cloudstack java[6754]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
May 13 15:36:56 cloudstack java[6754]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
~~~

##### EXPECTED RESULTS

Getting access to the Cloudstack web UI.

##### ACTUAL RESULTS

~~~
<h2>HTTP ERROR 503 Service Unavailable</h2>


URI: | /client/
-- | --
503
Service Unavailable
-
~~~

~~~
systemctl status cloudstack-management
● cloudstack-management.service - CloudStack Management Server
     Loaded: loaded (/lib/systemd/system/cloudstack-management.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-05-13 23:45:02 UTC; 1h 4min ago
   Main PID: 881 (java)
      Tasks: 37 (limit: 4571)
     Memory: 1.1G
        CPU: 50.660s
     CGroup: /system.slice/cloudstack-management.service
             └─881 /usr/bin/java -Djava.security.properties=/etc/cloudstack/management/java.security.ciphers -Djava.awt.headless=true -Dcom.sun.management.jmxremote=false -Xmx2G -XX:+UseParallelGC -XX:MaxGCPaus>

May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.server.Server.start(Server.java:423)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.server.Server.doStart(Server.java:387)
May 13 23:45:23 cloudstack java[881]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
May 13 23:45:23 cloudstack java[881]:         at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:192)
May 13 23:45:23 cloudstack java[881]:         at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:107)
May 13 23:45:23 cloudstack java[881]: INFO  [o.a.c.s.NfsMountManager] (main:null) (logid:) Clean up mounted NFS mount points used in current session.
~~~

~~~
sudo grep -i -E 'error|exception' /var/log/cloudstack/management/management-server.log
[sudo] password for cadm: 
2023-05-13 23:45:23,725 ERROR [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Failed to configure ClusterManagerImpl
javax.naming.ConfigurationException: cluster node IP should be valid local address where the server is running, please check your configuration
~~~

Any suggestions on how I can troubleshoot this?

**Comment by kiranchavala** [comment]
@hpepper could you please check if you able to connect to the database from the management server

# mysql -h <dbserver ip> -p

also could you please cross check the db.properties file if the credentials are correct 

cat /etc/cloudstack/management/db.properties

**Comment by kiranchavala** [comment]
@hpepper can i close the issue if its resolved ?

**Comment by hpepper** [comment]
@kiranchavala Thank you for your help.
`mysql -u cloud -p  -h localhost -P 3306 -D cloud` works.

I am unable to verify that the password in the db.properties is correct, since I haven't found a way to decode the encrypted password.
The decryption command ends with "Operation not possible (Bad input or parameters)"

`java -cp /usr/share/java/jasypt-1.9.3.jar  org.jasypt.intf.cli.JasyptPBEStringDecryptionCLI password=password algorithm=PBEWITHHMACSHA1ANDAES_128 input=j5oaiHBv5RB8MOxQekM/b/AMWxgOCmgB91X/ObBpyA0lr57z7ecrcVGZN0LtcFan ivGeneratorClassName=org.jasypt.iv.RandomIvGenerator`

**Comment by hpepper** [comment]
@weizhouapache Thanks
The cluster info in the /etc/cloudstack/management/db.properties file is:
```
cluster.node.IP=127.0.1.1
cluster.servlet.port=9090
region.id=1
```

**Comment by hpepper** [comment]
Is there a version of Cloudstack and a version of fedora or ubuntu that verified to work together?

(I have come across some suggestions that the java DB interface be manually updated, but I'd prefer, using std components, if possible)

**Comment by weizhouapache** [comment]
> Is there a version of Cloudstack and a version of fedora or ubuntu that verified to work together?
> 
> (I have come across some suggestions that the java DB interface be manually updated, but I'd prefer, using std components, if possible)

For each cloudstack release, it has been verified to work with most Ubuntu LTS version.

@hpepper can you change cluster.node.IP to 127.0.0.1 ?

**Comment by hpepper** [comment]
@weizhouapache thank you :-) that worked.
(my brain apparently filtered out the 1. ( wonder where I introduced that, I'll run a new installation to ensure I can repeat this)

**Comment by GiantFrog** [comment]
For what it's worth, I also had a 127.0.1.1 which didn't work on a brand new OS install of Ubuntu 23.10
127.0.0.1 works! I don't think it's you, it must have come that way somehow...

**Comment by tomorrrow666** [comment]
HTTP ERROR 503 Service Unavailable
The operating system is Ubuntu 22.04, and the MySQL version is 8.0.41-0ubuntu0.22.04.1.

idrl@management1:~$ sudo tail -F /var/log/cloudstack/management/management-server.log
[sudo] idrl 的密码： 
2025-02-08 09:16:06,769 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Module Hierarchy:         redfish
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-framework-config-system-context.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-server-system-context.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-core-system-context.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-framework-db-system-context.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-engine-schema-system-checkers-context.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-framework-config-system-context-inheritable.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-core-system-context-inheritable.xml]
2025-02-08 09:16:06,770 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/system/spring-contrail-system-context-inheritable.xml]
2025-02-08 09:16:06,771 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [system] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.18.2.5.jar!/META-INF/cloudstack/bootstrap/spring-bootstrap-context-inheritable.xml]
