### ISSUE TITLE
Not able fetch Account propertys  via API call

### ISSUE THREAD

**Issue by happyalexkg** [apache/cloudstack#7534]
Good afternoon, I am unable to get some values when calling API - ListUsers

Here is my API call:
  /client/api?accounttype=0&apiKey=api_key&command=listUsers&name=murzik2&response=json&signature=sign

But it's always return empty response.

but if you use admin instead of murzik2, all information about this account is provided

CloudStack 4.17.02

so my question is it possible to get AccountID via API Call, if i have only AccountName ?
Thx

**Comment by weizhouapache** [comment]
@happyalexkg 
You need to pass the domainid which can be fetched by listDomains api.

**Comment by happyalexkg** [comment]
Thank you very much ... BIG thx
