### ISSUE TITLE
incorrect weave yaml url in docs

### ISSUE THREAD

**Issue by ugenk** [apache/cloudstack#7540]
##### ISSUE TYPE
 * Documentation Report

##### COMPONENT NAME
kubernetes

##### CLOUDSTACK VERSION
latest

##### SUMMARY

In the documentation: https://docs.cloudstack.apache.org/en/latest/plugins/cloudstack-kubernetes-service.html#kubernetes-supported-versions
there is an example of generation k8s iso with create-kubernetes-binaries-iso.sh

In example there is a link "https://cloud.weave.works/k8s/net?k8s-version=1.12.5" but it is unaccessible
Looks like it should be replaced with https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

**Comment by shwstppr** [comment]
Added PR to update the documentation here, https://github.com/apache/cloudstack-documentation/pull/317
Also, tested the cluster deployment for the iso built using the command added in the example

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack-documentation/pull/317
