### ISSUE TITLE
Language translation files are cached after upgrade

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7546]
Post upgrading packages, the translation files such as `en.json` are cached in the browser. Somehow hard refresh doesn't work on them. If the UI can find a clever way to call them or ensure that they arne't cached by the browser.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

**Comment by DaanHoogland** [comment]
@rohityadavcloud , according to internet (stackoverflow) you need to up the version in `package.json` to automatically load the new files. I think we can do that (allign it a bit with the cloudstack release for instance.

**Comment by rohityadavcloud** [comment]
Ah, thanks @DaanHoogland I suppose we can use the UI version same as ACS version - cc @weizhouapache ?

**Comment by rohityadavcloud** [comment]
Raised a PR - https://github.com/apache/cloudstack/pull/7894 @DaanHoogland cc all - but that needs manual (upgrade) testing

**Comment by Pearl1594** [comment]
@rohityadavcloud what is the side effect of this - do you mean that since the translation files are getting cached, on changing the language, it doesn't reflect in the UI?

**Comment by rohityadavcloud** [comment]
@Pearl1594 say you upgrade from 4.17 -> 4.18; any new feature that introduced say a UI translation key such as `message.action.xyz.abc` will show up as-is, since the translation file (en.json say) is cached in browser for 4.17. Only if somebody clears cache or open UI in incognito etc will be able to see the string for `message.action.xyz.abc` which got added in 4.18 (not in 4.17).

**Comment by weizhouapache** [comment]
fixed by #7894
