### ISSUE TITLE
All templates from different zones and hypervisors are availible for reinstall VM

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7560]
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

Two anvanced zones:
- xcp-ng
- VMware

##### SUMMARY

We have two zones with different hypervisors, but templates from all zones are available for each other when reinstall VM
![image](https://github.com/apache/cloudstack/assets/92435079/3d85c132-3299-47af-af35-390a108b34aa)
![image](https://github.com/apache/cloudstack/assets/92435079/29ef1658-8f81-42b8-b018-4298f68cfe6c)
![image](https://github.com/apache/cloudstack/assets/92435079/f85df94d-ba71-46a5-8d7a-710c277a2096)
![image](https://github.com/apache/cloudstack/assets/92435079/5569f606-a121-4f09-b95f-cd281b8411f3)

**Comment by kiranchavala** [comment]
@DaanHoogland  this looks like  a bug as the  listTemplates api call is not passing the zone id when a user tries to restore a vm (https://cloudstack.apache.org/api/apidocs-4.18/apis/restoreVirtualMachine.html)

I think we should list only templates that are active in the zone and also based on the vm zone id 

I have tried this with a normal user account and it lists all the templates

https://cloudstack.apache.org/api/apidocs-4.18/apis/listTemplates.html

http://<>:8080/client/api/?listall=true&templatefilter=executable&showicon=true&command=listTemplates&response=json

**Comment by DaanHoogland** [comment]
@top-secrett if you can please test #7739?

**Comment by top-secrett** [comment]
@DaanHoogland sorry, but I don't know how to test it

**Comment by DaanHoogland** [comment]
> @DaanHoogland sorry, but I don't know how to test it

ok, we'll have to wait till someone else does then

**Comment by zap51** [comment]
@DaanHoogland I tested, LGTM. Template present in different zones are no longer shown during reinstall.

**Comment by DaanHoogland** [comment]
fixed in #7739
