### ISSUE TITLE
Cannot Ping to 8.8.8.8 after created a vm in cloudstack

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7565]
Guys, i cann't ping to public after created a vm in cloudstack. i can ping to local gateway ip but not to internet. any suggestion? cloudstack version is 4.18.0.0.

**Comment by kiranchavala** [comment]
Hi @thorzinaung 

what is the zone type you have created is it basic or advanced ?

What type of network you have created, is it isolated network, shared network ?

If it's  isolated network, could you check if you have allowed the egress rules

http://docs.cloudstack.apache.org/en/latest/adminguide/networking/ip_forwarding_and_firewalling.html?highlight=egress#egress-firewall-rules-in-an-advanced-zone

<img width="1142" alt="Screenshot 2023-05-29 at 9 24 07 AM" src="https://github.com/apache/cloudstack/assets/1401014/3f2952a4-2d61-4d4d-9514-2578ca432f2e">

**Comment by thorzinaung** [comment]
> Hi @thorzinaung
> 
> what is the zone type you have created is it basic or advanced ?
> 
> What type of network you have created, is it isolated network, shared network ?
> 
> If it's isolated network, could you check if you have allowed the egress rules
> 
> http://docs.cloudstack.apache.org/en/latest/adminguide/networking/ip_forwarding_and_firewalling.html?highlight=egress#egress-firewall-rules-in-an-advanced-zone
> 
> <img alt="Screenshot 2023-05-29 at 9 24 07 AM" width="1142" src="https://user-images.githubusercontent.com/1401014/241628973-3f2952a4-2d61-4d4d-9514-2578ca432f2e.png

@kiranchavala Thank you bhai for your support. now it's working. Really appreciate. Thank you very much. i have deny egress rule before.

**Comment by kiranchavala** [comment]
issue resolved
