### ISSUE TITLE
Import Unamanged VM fails due to no matching network found

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#7578]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2.0
~~~

##### CONFIGURATION

advanced networing

##### SUMMARY

When I try to import an unmanaged VM from a VMware cluster already present in Cloudstack, despite the fact that I have a corresponding L2 network available in the cluster, I can't import the VM via GUI as I can't select any network.
If I try to press OK button error "Request failed. Please select a network for NIC: Network adapter 1" appears.
If I import the VM via API importUnmanagedInstance it works just fine even without selecting any network.

##### STEPS TO REPRODUCE

~~~
In Import-Export instances tool try to import a VM with a tagged VSS. It doesn't show any matching network in CS.
~~~

##### EXPECTED RESULTS

~~~
The corresponding network with same L2 tag can be selected and the import can be completed.
~~~

##### ACTUAL RESULTS

~~~
No network are shown and the import cannot be completed.
~~~

**Comment by shwstppr** [comment]
@cdfgallo can you please share what you get in network/nics section in import form in the UI?

**Comment by cdfgallo** [comment]
@shwstppr this is how it looks in the UI
![Screenshot 2023-06-01 140241](https://github.com/apache/cloudstack/assets/110984295/4cb98871-ac98-41fe-b65a-d2d85e42c6b8)

**Comment by shwstppr** [comment]
@cdfgallo I tried to reproduce this but can't. For me, UI matches NIC to the correct network. Can you please share details of your network, like cmk output for listNetwork API

**Comment by mwaag** [comment]
Hi,
i experienced the same issue just now and found this issue by google-search.

We are working with projects as billable units and vmware only as hypervisor. I unmanaged one VM from project x and are trying to import this unmanaged vm into project y using the ui and do not see any "matching networks" either. 
Trying to finalize this action results in the same errormessage.

Here are our network-details:
[Source-Network (pastebin)](https://pastebin.com/CjaLN9EU)

[Networks of Destination-Project (pastebin)](https://pastebin.com/4T4hKeBa)

In my opinion the network 'atim-services-network' in the destination-project should match. Can you see, why this is not the case?

**Comment by mwaag** [comment]
This shows the result, when trying to import the VM with cloudmonkey:

import unmanagedinstance clusterid=55b7ee5e-22db-494c-93c0-3b46cacd0624 name=i-97-174834-VM serviceofferingid=c233ef58-24c0-4d05-882e-8345e279e844 displayname=webost-imported projectid=4a2d488d-7b11-486a-8ab0-7b6111ceb704 templateid=fe1b6a83-8c8d-462a-86e0-88614b688745
{
  "accountid": "36c623ce-74f7-491c-b8a8-e0eb3af6d3e2",
  "cmd": "org.apache.cloudstack.api.command.admin.vm.ImportUnmanagedInstanceCmd",
  "completed": "2023-06-13T11:52:32+0200",
  "created": "2023-06-13T11:52:22+0200",
  "jobid": "81af23c1-d70b-49d1-bc3f-760d2d8c1539",
  "jobprocstatus": 0,
  "jobresult": {
    "errorcode": 530,
    "errortext": "Suitable network for nic(ID: Network adapter 1) not found during VM import"
  },
  "jobresultcode": 530,
  "jobresulttype": "object",
  "jobstatus": 2,
  "userid": "e63be6d6-cf03-4be5-b45d-8bf42da7369a"
}

How does the parameters nicipaddresslist and nicnetworklist work? Can you give an example, please?

**Comment by cdfgallo** [comment]
Hi @shwstppr, yes my L2 networks are in setup state.
Thank you!

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/7628
