### ISSUE TITLE
UI: searching for template with . (dot) in it's name - doesn't return any results

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#7590]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API/UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1 tested
~~~

##### CONFIGURATION

Template is registered with name "vCenter 6.7"
##### OS / ENVIRONMENT

Searching to "vCenter 6" - gives resulted
Searching for "vCenter 6.7" - returns zero results from API
details (40sec recording): https://somup.com/c01h2raAeG

**Comment by DaanHoogland** [comment]
@andrijapanicsb , as searching for "vCenter 6" gives "vCenter 6.7" as a result, I think the "issue" is '.' having a special meaning
If so, did you try searching for  "vCenter 6\.7" or "vCenter 6?7"?

**Comment by andrijapanicsb** [comment]
Alright, I did some more digging:

Template details:
**Name**: vCenter 67u3 (no dot in the name)
**Description**: vCenter 6.7u3 (has dot in the name, don't ask me why 🤷‍♂️ )
![image](https://github.com/apache/cloudstack/assets/45762285/cda807fd-a9d0-43a7-8b46-401719e624ee)


The problem is the discrepancy of what we SHOW in the "images/template" list of templates vs. list of templates in the New Instance Wizard:

- When you go to Images/Templates - and search for the image, you are SEARCHING by name (not description) and you get template's NAMES (not descriptions, which I think makes sense)

![image](https://github.com/apache/cloudstack/assets/45762285/e870118c-21cf-4b83-89a0-6642e7ad2516)


- When you search for templates in the new Instance Wizard, it seems that the DESCRIPTION is showed, not the NAME - and this might need fixing.
![image](https://github.com/apache/cloudstack/assets/45762285/6d469892-41aa-4271-a6e5-fa2af32118a1)
(I've here searched by the NAME of the template (vCenter 67u3) and I got resulted vCenter 6.7u3 (with the dot, which is DESCRIPTION value)

**Comment by DaanHoogland** [comment]
shouldn't this be a keyword search that would match both name and desceription @andrijapanicsb ?

**Comment by andrijapanicsb** [comment]
Since for some silly reason we have 2 fields for the same thing - I would say "yes', but that then, removes unique results. so I guess another opinion is needed.

**Comment by weizhouapache** [comment]
from the code, only check template name by keyword
```
        // other criteria

        if (keyword != null) {
            sc.addAnd("name", SearchCriteria.Op.LIKE, "%" + keyword + "%");
        } else if (name != null) {
            sc.addAnd("name", SearchCriteria.Op.EQ, name);
        }

        SearchCriteria.Op op = isIso ? Op.EQ : Op.NEQ;
        sc.addAnd("format", op, "ISO");

        if (!hyperType.equals(HypervisorType.None)) {
            sc.addAnd("hypervisorType", SearchCriteria.Op.EQ, hyperType);
        }
```

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9215
