### ISSUE TITLE
Fix smoke tests for kubernetes cluster

### ISSUE THREAD

**Issue by vishesh92** [apache/cloudstack#7604]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME

~~~
CKS
~~~

##### SUMMARY
Currently smoke tests for CKS are flaky. It might be worth adding the kuberentes to base.lib and revisit the smoke tests.

Sample test runs:
https://github.com/apache/cloudstack/pull/7548#issuecomment-1563664511

**Comment by weizhouapache** [comment]
@vishesh92 @DaanHoogland 
the failure with PR #7587 (test_08_upgrade_kubernetes_ha_cluster) has been fixed by #7118 in cloudstack 4.18
you can ignore it.

**Comment by weizhouapache** [comment]
> > @vishesh92 @DaanHoogland the failure with PR #7587 (test_08_upgrade_kubernetes_ha_cluster) has been fixed by #7118 in cloudstack 4.18 you can ignore it.
> 
> Let's leave this open to address the lack of base entruy for k8s clusters (low prio)

@DaanHoogland ok.

btw, I have removed the link https://github.com/apache/cloudstack/pull/7587#issuecomment-1579514314
 from description. cc @vishesh92

**Comment by weizhouapache** [comment]
moved to 4.18.2.0

**Comment by weizhouapache** [comment]
this should be fixed via #8297  and #8402
