### ISSUE TITLE
UI: Add Persistent ACS appearance under user profile

### ISSUE THREAD

**Issue by MejdiB** [apache/cloudstack#7619]
##### ISSUE TYPE
 * Improvement Request
 * Feature Idea

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17.2
~~~

##### SUMMARY

I propose a feature idea to move the dark mode option (sidebar palette) to the user profile as a preference/appearance setting. Web applications such as GitHub and others offer such a setting and make this persistent. Maybe it would be possible to link the appearance to the system theme.

**Comment by shwstppr** [comment]
Moving it out of 4.19.0.0 milestone

**Comment by JoaoJandre** [comment]
Hey @MejdiB, can you check if #8942 covers your use case?

**Comment by MejdiB** [comment]
@JoaoJandre I think this is done in #8942 . Thank you very much.
