### ISSUE TITLE
VM status is not getting changed when shutdown is triggered from VM

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7635]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

UI

~~~

##### CLOUDSTACK VERSION
<!--
New line separated list of affected versions, commit ID for issues on main branch.
-->

4.18.0.0

~~~

##### CONFIGURATION

Advance networking

##### OS / ENVIRONMENT

All on Ubuntu 22.04

##### SUMMARY

If we triger a shutdown from VM instace it get shutdown and when checking console of that VM it is not connecting. But I can see my VM instance on cloudstack is still running. If I go for a stop instance option in cloudstack then it will show stopped status. 
Is it a issue that has to fix or some thing I have to configure on my VM to change this behaviour

##### STEPS TO REPRODUCE

Just bring up a VM on cloustack and login to VM using console. Trigger a power off and wait for a while so that your console get disconnected. Once it is disconnected check the status of that VM in instance 

##### EXPECTED RESULTS

Status should become stopped

##### ACTUAL RESULTS

It is still showing Running status

**Comment by Noelantogerorge** [comment]
@DaanHoogland Thank you for your reply
I just login to KVM host and check the status of VM it is not running
Actions Done

- log in to VM instalnce through console and trigger shutdown
- VM shutdown and console shows no fail to connect to server/token expires
- checked the status of VM on KVM and it is not running
- Checked the status on cloudstack it is still in running state

**Comment by Noelantogerorge** [comment]
@DaanHoogland  Thanks for the reply
I just checked my KVM host and VM is not in running status It is still showing running in cloudstack
when I futher dig on it I can see that on triggering a shutdown from VM console it is getting power off and on cloudstack status is running where as on KVM host VM is not showing in running status. After some time it automatically get started on KVM and I can get console also.

**Comment by DaanHoogland** [comment]
@Noelantogerorge I'll investigate how this is supposed to work on KVM (when out-of-bounds things happen te a VM) I don't know by head. In general I think a VM shouldn't be managed out of bounds.
So the scenario is:
- the VM-OS is shutdown from within the VM
- KVM marks it as stopped automatically
- nothing happens in ACS
is that correct?

**Comment by Noelantogerorge** [comment]
@DaanHoogland yes thats our scenario

**Comment by soreana** [comment]
@Noelantogerorge Is the high availability turned on? You can confirm that by checking the global setting `force.ha` value and the `Offering HA` value in the system offering.

**Comment by Noelantogerorge** [comment]
@soreana Yes, HA is true from my offerings

**Comment by soreana** [comment]
> @soreana Yes, HA is true from my offerings

In that case when a VM turns off, CloudStack will start it after `kvm.ha.recover.wait.period` passed. Its default value is 10 minutes. So if something goes wrong for your VM and it turned off, CloudStack will start it after the 10 minutes. Can you please follow these steps and see if it fixes your issue?

1. Create a new service offering (make sure that the `Offering HA` is turned off).
2. Make sure that the `force.ha` global setting is set to `false`.
3. Restart management server if necessary.
4. Turn off the VM and switch its service offering.
5. Shutdown the vm from inside.
6. Check if CloudStack start it again.

**Comment by Noelantogerorge** [comment]
@soreana 
I had tested this and now VM status moved to stopped after some time of VM shutdown 
Steps done
1. verified global setting Force ha (force.ha) is disable
2. created new compute offering with HA disable
3. Shutdown VM and change the compute offering  to newly created one
4. started VM
5. login to console and trigged power off
6. VM powered off and console disconnected
7. checked on KVM and VM is not showing in running status
8. wait for about 5min to get stopped status on cloudstack

So HA on compute offering is nothing but if VM is stooped cloudstack will automattically bring that UP after a time period? I thought HA helps VM to move from 1 KVM to another when KVM get disconnected.

**Comment by soreana** [comment]
@Noelantogerorge
I believe that the Wei's comment answered your question. Let us know if you need any further assistance and we would be more than happy to help.

**Comment by weizhouapache** [comment]
@Noelantogerorge 
can you test again and wait for a bit longer time for VM state to be updated ?

**Comment by Noelantogerorge** [comment]
@weizhouapache @soreana Thanks for the support.. I was had enabled ha in my offerings so cloudstack is trying to bring the VM up when I triggered a shutdown inside the VM So status is still in running in UI. As per @soreana comment I tried to changing the offering without HA and tried then cloudstack UI change the status to stopped. 
Got clear understanding with @weizhouapache comment. 
Thank you for the support....

**Comment by WowYouCanReallyDance** [comment]
> @Noelantogerorge I believe that the Wei's comment answered your question. Let us know if you need any further assistance and we would be more than happy to help.

Thanks first, I think the VM state should changed on the VMs list table immediately while it gets shutdown. What do you think about this?   Or, there's some settings control of this?

**Comment by WowYouCanReallyDance** [comment]
crying…… no one help me
