### ISSUE TITLE
The "Virtual routers"  can not work as expect

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7639]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
* Virtual routers

##### CLOUDSTACK VERSION
CloudStack 4.17.2.0

##### CONFIGURATION
-  advanced networking, having  two hosts name is _**kvm001**_ and _**kvm002**_
-  Create a VPC name is **_test_**, the details info is 

![image](https://github.com/apache/cloudstack/assets/4197714/a8a41cd2-d730-4100-a976-55e73400a9d3)

- The instances in VPC  
   java001 ( 10.65.13.57 )   on host kvm001
   java002 ( 10.65.13.135 )  on host kvm002

  php001 ( 10.65.14.69 ) on host kvm001
  php002 ( 10.65.14.15 ) on host kvm002
   
![image](https://github.com/apache/cloudstack/assets/4197714/72951914-263b-409a-8413-254fa5e90f7b)

- The instance connection problem:
  java001 can ping php001, but can not ping java002 and php002. 
  
![image](https://github.com/apache/cloudstack/assets/4197714/609002f2-c4aa-44ca-bf62-6efddc286572)

   The vm can only ping the vm on same hosts.

##### OS / ENVIRONMENT
OS:  oracle linux 8

##### EXPECTED RESULTS
The  "Virtual routers"  works fine.

The similar issue:
1.    https://github.com/apache/cloudstack/issues/6702
2.    https://github.com/apache/cloudstack/issues/5138

##### ACTUAL RESULTS
The error 

1.  Router displaying error 
```
"Failed to start Conntrack Deamon"
```
2.  The alerts description: 
```
More than one redundant virtual router is in PRIMARY state! Router r-30765-VM and router r-30764-VM
```

Please see the picture:

![image](https://github.com/apache/cloudstack/assets/4197714/c17e3072-8559-4960-92b6-53361b57780c)

![image](https://github.com/apache/cloudstack/assets/4197714/65cedc6d-22a3-4504-a87a-6b6c8ff2bb9e)

![image](https://github.com/apache/cloudstack/assets/4197714/3b7d20e5-82ee-4f3c-a3e8-6fee6187447a)

I have restart the VPC, It can not work.
I have restart the Virtual routers, It also can not work.

How to repair this problem ?

**Comment by rajujith** [comment]
@xuanyuanaosheng  could you check the following: 

1. KVM traffic labelling is correct and the VM, VR guest interfaces are under the expected bridge
2. Tier VLANs are allowed on the switch ports of the KVM host
3. Do they work fine if you migrate all VMs to a single host?

**Comment by xuanyuanaosheng** [comment]
Done, I will close this issue.

Thanks @rajujith
