### ISSUE TITLE
UI issue, running notification shifting top-bottom

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#7640]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### SUMMARY

When having a in-progress task in the notification drop down, the tasks is shifting top to bottom with any other items in the menu. 

Checkout the gif: 

![notifications-shifting](https://github.com/apache/cloudstack/assets/13551960/2baa878b-e8c8-49b9-996b-7387230f4167)

**Comment by borisstoyanov** [comment]
Correct @DaanHoogland , not sure about the origin though..

**Comment by shwstppr** [comment]
@borisstoyanov this may be fixed by #7609

**Comment by borisstoyanov** [comment]
> @borisstoyanov this may be fixed by #7609

will test it out, thanks!

**Comment by weizhouapache** [comment]
fixed by #7609
