### ISSUE TITLE
[Enhancement]change the return type from null to empty object in [FakeDhcpSnooper.java]

### ISSUE THREAD

**Issue by nikam14** [apache/cloudstack#7646]
##### ISSUE TYPE

 * Enhancement Request

##### SUMMARY

location - agent/src/main/java/com/cloud/agent/dhcp/FakeDhcpSnooper.java
line - 146
Null is a reference that does not point to any object. Returning an empty object can help to improve the readability and maintainability of code.

##### EXPECTED RESULTS

add this line.
Screenshot - 
![1](https://github.com/apache/cloudstack/assets/55378196/817f236c-c96a-4c22-9a5c-fcb891bf2721)
and this 
![2](https://github.com/apache/cloudstack/assets/55378196/35a01bcd-c18c-41d7-a606-7e2f129c01d7)

##### ACTUAL RESULTS

Screenshot - 
![prev](https://github.com/apache/cloudstack/assets/55378196/8fee4200-6283-4193-ae36-991091f1b9b5)

**Comment by DaanHoogland** [comment]
@nikam14 why don't you enter a PR and have the tests run on this. You are welcome to do so. No idea what the side effects will be.

**Comment by soreana** [comment]
Hey @nikam14 

Thanks for raising this issue. In CloudStack codes `null` has a different meaning from the emptyMap and most of the time it is used to determining if the value is missing or for error handling. I don't know what is the purpose of the `FakeDhcpSnooper.java` class, but I think that this null value is there for a reason.

**Comment by weizhouapache** [comment]
I do not know what exactly the issue the original code causes.

**Comment by nikam14** [comment]
@DaanHoogland  @soreana  @weizhouapache thank you for your suggestions . just wanted to improve the code . and open for better solution.

**Comment by DaanHoogland** [comment]
well, @nikam14 if you think this is good, please submit a PR, we can review and test that.

**Comment by nikam14** [comment]
Sure , I can make the pr.
