### ISSUE TITLE
Unable to create a CKS cluster if the network offering contains userdata :ConfigDrive

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7647]
##### ISSUE TYPE

 * Bug report

##### COMPONENT NAME

~~~

Component: cks, kubernetes

~~~

##### CLOUDSTACK VERSION

~~~
4.18 

~~~

##### SUMMARY

Unable to create a CKS cluster if the network offering contains userdata :Config

Steps to reporoduce the issue 

1. Create a network offering with userdata: config drive as supported services

2. Create an isolated network with network offering in step 1

3. Create CKS cluster 

Expected behaviour 
-----------
The CKS cluster should get created

Actual behaviour 
---------
The CKS cluster is not getting created, the cluster creation fails 

The reason could be due to systemvm template not supporting  ConfigDrive as data source

**Comment by kiranchavala** [comment]
Exception message on the control node

<img width="765" alt="Screenshot 2023-06-19 at 12 09 58 PM" src="https://github.com/apache/cloudstack/assets/1401014/290f07e4-15d6-4d7b-8947-a93ceac6ceb7">

**Comment by weizhouapache** [comment]
moved to 4.18.2.0

**Comment by weizhouapache** [comment]
moved to 4.20.0.0 as this requires new systemvm template

cc @DaanHoogland @sureshanaparti
