### ISSUE TITLE
Virtual Router Failing Health Check Due To Missing Entries in /etc/hosts

### ISSUE THREAD

**Issue by whitetiger264** [apache/cloudstack#7653]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 But have noticed the issue in previous versions already.
~~~

##### CONFIGURATION
I have a very basic private cloud setup with Advanced Networking. No funny additional load balancers, VPCs etc just a basic set-up. 

##### OS / ENVIRONMENT
Cloudstack Management Server Runs On AlmaLinux 8
and KVM hosts also on Almalinux 8

##### SUMMARY
After creating a new VM with a custom name, such as "Example-VM", terminating the VM and Recreating it again using the same name again, causing the virtual router to stop updating the `/etc/host` entries and causing failed health checks. And now, it's to a point where when I create new VMs I MUST always manually enter entires into the Virtual Routers `/etc/hosts/` file it now no longer enters it automatically. 

I have tried rebooting the router and nothing, I want to try patching it and possibly destroying it so its re-created again. This will most likely solve it, but no one wants to do that in production. 

##### STEPS TO REPRODUCE
Create a few VMs with a custom name. Destroy it (expunge also) and recreate VM again using the SAME name, repeat this step three or four times. Following the same VM name, resources, host etc. Automatically assign IPs to VM. 

##### EXPECTED RESULTS
The virtual router should always update entries accordingly in the `/etc/hosts` file.

**Comment by weizhouapache** [comment]
Hi @whitetiger264 
I guess the two VMs have the same name but different IPs, right ?

**Comment by whitetiger264** [comment]
> Hi @whitetiger264 I guess the two VMs have the same name but different IPs, right ?

No, the VM is literally destroyed. And re-created again. So two instances of the same name, but different IPs do not exist at the same time.

**Comment by weizhouapache** [comment]
> > Hi @whitetiger264 I guess the two VMs have the same name but different IPs, right ?
> 
> No, the VM is literally destroyed. And re-created again. So two instances of the same name, but different IPs do not exist at the same time.
> 
> EDIT: Actually, yes also. When recreating it, since IPs are automatically assigned, the second time or third time its created it will most likely have a new IP yes but the same name as before. But the instances do not exist simultaneously.

@whitetiger264 
sorry for the confusion. The two VMs I meant are (1) deleted VM and (2) new VM after recreation.
now clear.

one more question, do you use isolated network, shared network or vpc ?

**Comment by whitetiger264** [comment]
> > > Hi @whitetiger264 I guess the two VMs have the same name but different IPs, right ?
> > 
> > 
> > No, the VM is literally destroyed. And re-created again. So two instances of the same name, but different IPs do not exist at the same time.
> > EDIT: Actually, yes also. When recreating it, since IPs are automatically assigned, the second time or third time its created it will most likely have a new IP yes but the same name as before. But the instances do not exist simultaneously.
> 
> @whitetiger264 sorry for the confusion. The two VMs I meant are (1) deleted VM and (2) new VM after recreation. now clear.
> 
> one more question, do you use isolated network, shared network or vpc ?

The network is set to use `DefaultSharedNetworkOffering` as the network offering, so yes shared network. a V
ERY basic setup I have :).

**Comment by DaanHoogland** [comment]
@whitetiger264 I created an environment  with an advanced zone with only a shared network and recreated the same VM three times. Every time I got the entry in /etc/hosts on the router. Is there any more information you can give?

**Comment by whitetiger264** [comment]
> @whitetiger264 I created an environment with an advanced zone with only a shared network and recreated the same VM three times. Every time I got the entry in /etc/hosts on the router. Is there any more information you can give?

Hmmm the VMs are all created on local storage on the KVM host so the NFS storage locations are not in play in this case. I am not really sure what else to share. The virtual router and VMs that are created are all on the same KVM host. 

Attached is a screenshot of the virtual router. Please feel free to ask me all details you still need. 

![image](https://github.com/apache/cloudstack/assets/16236376/56deb62a-07cb-4e94-852b-8a52a8d61bf0)

**Comment by weizhouapache** [comment]
> @whitetiger264 I created an environment with an advanced zone with only a shared network and recreated the same VM three times. Every time I got the entry in /etc/hosts on the router. Is there any more information you can give?

got same results as @DaanHoogland 
when vm is created, the entry is added to /etc/hosts
when vm is expunged, the entry is removed

**Comment by weizhouapache** [comment]
> Is there perhaps a certain log that can be traced that logs the process of entries being added to the `/etc/hosts` file? That would be the only way I would be able to provide the actual error being triggered.

@whitetiger264 
you can check /var/log/cloud.log if there are some errors

when vm is deleted, there should be logs like
```
2023-06-20 15:10:25,590 INFO     Attempting to delete entries from dnsmasq.leases file for VMs which are not on dhcphosts file
2023-06-20 15:10:25,590 INFO     dhcp_release $(ip route get 10.0.100.105 | grep eth | head -1 | awk '{print $3}') 10.0.100.105 1e:00:83:00:00:2d
2023-06-20 15:10:25,590 INFO     Executing: dhcp_release $(ip route get 10.0.100.105 | grep eth | head -1 | awk '{print $3}') 10.0.100.105 1e:00:83:00:00:2d
2023-06-20 15:10:25,609 INFO     Deleted 1 entries from dnsmasq.leases file
2023-06-20 15:10:25,609 INFO     Wrote edited file /etc/hosts
2023-06-20 15:10:25,609 INFO     Updated file in-cache configuration
2023-06-20 15:10:25,609 INFO     Updated hosts file
```


when vm is created
```
2023-06-20 15:10:59,634 INFO     update_config.py :: Processing incoming file => vm_dhcp_entry.json.75a5c3d8-7f85-4160-aa0b-047d3c253aaf
2023-06-20 15:10:59,635 INFO     Processing JSON file vm_dhcp_entry.json.75a5c3d8-7f85-4160-aa0b-047d3c253aaf
2023-06-20 15:10:59,635 INFO     Continuing with the processing of file '/var/cache/cloud/vm_dhcp_entry.json.75a5c3d8-7f85-4160-aa0b-047d3c253aaf'
2023-06-20 15:10:59,636 INFO     Command of type dhcpentry received
...
2023-06-20 15:10:59,744 INFO     Attempting to delete entries from dnsmasq.leases file for VMs which are not on dhcphosts file
2023-06-20 15:10:59,745 INFO     Deleted 0 entries from dnsmasq.leases file
2023-06-20 15:10:59,745 INFO     Wrote edited file /etc/hosts
2023-06-20 15:10:59,745 INFO     Updated file in-cache configuration
2023-06-20 15:10:59,746 INFO     Updated hosts file
...

```

**Comment by weizhouapache** [comment]
> @weizhouapache and @DaanHoogland Thank you, the logs are not really confirming anything for me. However, I made a video of me showing you the error to replicate it while grabbing a copy of what the log outputs. In this case, it fails to write new and recently created VMs entries to `/etc/hosts/` when terminating the VM, it seems to update perfectly fine and remove the entry. But for some reason, it's specifically failing to write an entry for new and other existing VMs that have been recently created.
> 
> You can view the video and get the log files here: https://privnote.com/UPggnDRK#Ycx61RQ0p PS This link will self-destruct within 50 mins

@whitetiger264 
just want to confirm
- which cloudstack version do you use ?
- was the cloudstack created from the correct template ?
- how many guest IP ranges in the shared network ?
- are the IPs in cloudstack VR correct ? (share "ip a" if possible)

I noticed some errors like `Command 'dhcp_release $(ip route get xxx ' returned non-zero exit status 1` which I never saw  before

**Comment by whitetiger264** [comment]
> > @weizhouapache and @DaanHoogland Thank you, the logs are not really confirming anything for me. However, I made a video of me showing you the error to replicate it while grabbing a copy of what the log outputs. In this case, it fails to write new and recently created VMs entries to `/etc/hosts/` when terminating the VM, it seems to update perfectly fine and remove the entry. But for some reason, it's specifically failing to write an entry for new and other existing VMs that have been recently created.
> > You can view the video and get the log files here: https://privnote.com/UPggnDRK#Ycx61RQ0p PS This link will self-destruct within 50 mins
> 
> @whitetiger264 just want to confirm
> 
> * which cloudstack version do you use ?
> * was the cloudstack created from the correct template ?
> * how many guest IP ranges in the shared network ?
> * are the IPs in cloudstack VR correct ? (share "ip a" if possible)
> 
> I noticed some errors like `Command 'dhcp_release $(ip route get xxx ' returned non-zero exit status 1` which I never saw before

1. I use version 4.18 but as mentioned I saw or noticed this with previous versions such as 4.17
2. I am not sure I understand this question, I created CloudStack from this source http://download.cloudstack.org/centos/$releasever/4.18/ and I used the correct System templated for 4.18 too by following the official upgrade documentation. 
3. I have one Guest Network called `public network` and in this network, I have:
 - 2 x /29 public ranges
 - 3 x /28 public ranges
 So 5 different ranges in total. Of which I currently have 18 VMs utilising from these ranges, fully publicly accessible. I also noticed now that my VirtualRouter also gets its Guest public IP from one of these ranges. 
 4. I believe so, though not 100% sure, I am new to Cloudstack and I followed documentation when I did the installation. I ssh into my VR now and ran `ip a` as requested:
 
 ```
 root@r-128-VM:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 1e:00:e9:00:00:4c brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 197.189.xxx.xxx/29 brd 197.189.xxx.xxx scope global eth0
       valid_lft forever preferred_lft forever
    inet 129.232.xxx.xxx/28 brd 129.232.xxx.xxx scope global eth0
       valid_lft forever preferred_lft forever
    inet 41.72.xxx.xxx/28 brd 41.72.xxx.xxx scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0e:00:a9:fe:7e:67 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    altname ens4
    inet 169.254.126.103/16 brd 169.254.255.255 scope global eth1
       valid_lft forever preferred_lft forever
root@r-128-VM:~# 
````

**Comment by weizhouapache** [comment]
> > > @weizhouapache and @DaanHoogland Thank you, the logs are not really confirming anything for me. However, I made a video of me showing you the error to replicate it while grabbing a copy of what the log outputs. In this case, it fails to write new and recently created VMs entries to `/etc/hosts/` when terminating the VM, it seems to update perfectly fine and remove the entry. But for some reason, it's specifically failing to write an entry for new and other existing VMs that have been recently created.
> > > You can view the video and get the log files here: https://privnote.com/UPggnDRK#Ycx61RQ0p PS This link will self-destruct within 50 mins
> > 
> > 
> > @whitetiger264 just want to confirm
> > 
> > * which cloudstack version do you use ?
> > * was the cloudstack created from the correct template ?
> > * how many guest IP ranges in the shared network ?
> > * are the IPs in cloudstack VR correct ? (share "ip a" if possible)
> > 
> > I noticed some errors like `Command 'dhcp_release $(ip route get xxx ' returned non-zero exit status 1` which I never saw before
> 
> 1. I use version 4.18 but as mentioned I saw or noticed this with previous versions such as 4.17
> 2. I am not sure I understand this question, I created CloudStack from this source http://download.cloudstack.org/centos/$releasever/4.18/ and I used the correct System templated for 4.18 too by following the official upgrade documentation.
> 3. I have one Guest Network called `public network` and in this network, I have:
> 
> * 2 x /29 public ranges
> * 3 x /28 public ranges
>   So 5 different ranges in total. Of which I currently have 18 VMs utilising from these ranges, fully publicly accessible. I also noticed now that my VirtualRouter also gets its Guest public IP from one of these ranges.
> 
> 4. I believe so, though not 100% sure, I am new to Cloudstack and I followed documentation when I did the installation. I ssh into my VR now and ran `ip a` as requested:
> 
> ```
> root@r-128-VM:~# ip a
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>    inet 127.0.0.1/8 scope host lo
>       valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>    link/ether 1e:00:e9:00:00:4c brd ff:ff:ff:ff:ff:ff
>    altname enp0s3
>    altname ens3
>    inet 197.189.xxx.xxx/29 brd 197.189.xxx.xxx scope global eth0
>       valid_lft forever preferred_lft forever
>    inet 129.232.xxx.xxx/28 brd 129.232.xxx.xxx scope global eth0
>       valid_lft forever preferred_lft forever
>    inet 41.72.xxx.xxx/28 brd 41.72.xxx.xxx scope global eth0
>       valid_lft forever preferred_lft forever
> 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
>    link/ether 0e:00:a9:fe:7e:67 brd ff:ff:ff:ff:ff:ff
>    altname enp0s4
>    altname ens4
>    inet 169.254.126.103/16 brd 169.254.255.255 scope global eth1
>       valid_lft forever preferred_lft forever
> root@r-128-VM:~# 
> ```

@whitetiger264 
I would suggest you to create a shared network for each IP range. it will make configuration more simple.

back to your issue, eth0 has only 3 public IPs attached. maybe there is no VMs on the other 2 IP ranges. can you please double-check ?

**Comment by whitetiger264** [comment]
> > > > @weizhouapache and @DaanHoogland Thank you, the logs are not really confirming anything for me. However, I made a video of me showing you the error to replicate it while grabbing a copy of what the log outputs. In this case, it fails to write new and recently created VMs entries to `/etc/hosts/` when terminating the VM, it seems to update perfectly fine and remove the entry. But for some reason, it's specifically failing to write an entry for new and other existing VMs that have been recently created.
> > > > You can view the video and get the log files here: https://privnote.com/UPggnDRK#Ycx61RQ0p PS This link will self-destruct within 50 mins
> > > 
> > > 
> > > @whitetiger264 just want to confirm
> > > 
> > > * which cloudstack version do you use ?
> > > * was the cloudstack created from the correct template ?
> > > * how many guest IP ranges in the shared network ?
> > > * are the IPs in cloudstack VR correct ? (share "ip a" if possible)
> > > 
> > > I noticed some errors like `Command 'dhcp_release $(ip route get xxx ' returned non-zero exit status 1` which I never saw before
> > 
> > 
> > 
> > 1. I use version 4.18 but as mentioned I saw or noticed this with previous versions such as 4.17
> > 2. I am not sure I understand this question, I created CloudStack from this source http://download.cloudstack.org/centos/$releasever/4.18/ and I used the correct System templated for 4.18 too by following the official upgrade documentation.
> > 3. I have one Guest Network called `public network` and in this network, I have:
> > 
> > 
> > * 2 x /29 public ranges
> > * 3 x /28 public ranges
> >   So 5 different ranges in total. Of which I currently have 18 VMs utilising from these ranges, fully publicly accessible. I also noticed now that my VirtualRouter also gets its Guest public IP from one of these ranges.
> > 
> > 
> > 4. I believe so, though not 100% sure, I am new to Cloudstack and I followed documentation when I did the installation. I ssh into my VR now and ran `ip a` as requested:
> > 
> > ```
> > root@r-128-VM:~# ip a
> > 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
> >    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
> >    inet 127.0.0.1/8 scope host lo
> >       valid_lft forever preferred_lft forever
> > 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
> >    link/ether 1e:00:e9:00:00:4c brd ff:ff:ff:ff:ff:ff
> >    altname enp0s3
> >    altname ens3
> >    inet 197.189.xxx.xxx/29 brd 197.189.xxx.xxx scope global eth0
> >       valid_lft forever preferred_lft forever
> >    inet 129.232.xxx.xxx/28 brd 129.232.xxx.xxx scope global eth0
> >       valid_lft forever preferred_lft forever
> >    inet 41.72.xxx.xxx/28 brd 41.72.xxx.xxx scope global eth0
> >       valid_lft forever preferred_lft forever
> > 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
> >    link/ether 0e:00:a9:fe:7e:67 brd ff:ff:ff:ff:ff:ff
> >    altname enp0s4
> >    altname ens4
> >    inet 169.254.126.103/16 brd 169.254.255.255 scope global eth1
> >       valid_lft forever preferred_lft forever
> > root@r-128-VM:~# 
> > ```
> 
> @whitetiger264 I would suggest you to create a shared network for each IP range. it will make configuration more simple.
> 
> back to your issue, eth0 has only 3 public IPs attached. maybe there is no VMs on the other 2 IP ranges. can you please double-check ?

Thank you for the tip, I will surely look into this. 

As for the issue, yes I can 100% confirm the other two ranges are "Free" and have zero VMs.

**Comment by whitetiger264** [comment]
Hello

As a temporary solution, I patched the VR, and now I am no longer getting the error when creating new VMs. But I am fairly certain if I replicate the steps it will happen again.

**Comment by DaanHoogland** [comment]
> Hello
> 
> As a temporary solution, I patched the VR, and now I am no longer getting the error when creating new VMs. But I am fairly certain if I replicate the steps it will happen again.

what did you do to patch it?

**Comment by whitetiger264** [comment]
> > Hello
> > As a temporary solution, I patched the VR, and now I am no longer getting the error when creating new VMs. But I am fairly certain if I replicate the steps it will happen again.
> 
> what did you do to patch it?

I did it via UI. The "Patch system VM" button:

![image](https://github.com/apache/cloudstack/assets/16236376/751752d9-cdce-4313-9c8e-0d619c5ad7f3)

**Comment by weizhouapache** [comment]
I was not able to reproduce the issue even if there are multiple IP ranges in the shared network.

@whitetiger264 
can you check if the cloudstack packages are installed with same version on management server and kvm hosts ?

**Comment by whitetiger264** [comment]
> I was not able to reproduce the issue even if there are multiple IP ranges in the shared network.
> 
> @whitetiger264 can you check if the cloudstack packages are installed with same version on management server and kvm hosts ?

Management Host:

```
root@hostname ~ $ rpm -q cloudstack-management
cloudstack-management-4.18.0.0-1.x86_64
root@hostname ~ $ 
```

KVM Host:

```
root@hostname ~ $ rpm -q cloudstack-agent
cloudstack-agent-4.18.0.0-1.x86_64
root@hostname ~ $ 
```

**Comment by whitetiger264** [comment]
> Hello
> 
> As a temporary solution, I patched the VR, and now I am no longer getting the error when creating new VMs. But I am fairly certain if I replicate the steps it will happen again.

I talked too soon. Created a new VM now and didn't even delete and re-create it and again it's broken. So yeah, no idea what's actually causing this behaviour. If I delete my VR will it take the VMs down? And will be re-create a new one automatically?

**Comment by DaanHoogland** [comment]
> > Hello
> > As a temporary solution, I patched the VR, and now I am no longer getting the error when creating new VMs. But I am fairly certain if I replicate the steps it will happen again.
> 
> I talked too soon. Created a new VM now and didn't even delete and re-create it and again it's broken. So yeah, no idea what's actually causing this behaviour. If I delete my VR will it take the VMs down? And will be re-create a new one automatically?

You can restart network with cleanup, @whitetiger264 . That will destroy the router and rebuild a new one.

**Comment by DaanHoogland** [comment]
yes

**Comment by weizhouapache** [comment]
> I assume that will temporarily take VMs down from being publicly accessible, yes? Just want to confirm so that I can schedule this first with the clients.


@whitetiger264  
No worries. the cloudstack VR of shared network is not the gateway.

**Comment by whitetiger264** [comment]
Sooo, I did a clean network restart and it seems to be stuck in this phase. its been over 10 minutes now:

![image](https://github.com/apache/cloudstack/assets/16236376/5026c587-5e7f-4a40-be5e-02f2c97cf0a7)

**Comment by whitetiger264** [comment]
> Sooo, I did a clean network restart and it seems to be stuck in this phase. its been over 10 minutes now:
> 
> ![image](https://user-images.githubusercontent.com/16236376/247593532-5026c587-5e7f-4a40-be5e-02f2c97cf0a7.png)

Here's the log entry for when I started the Network restart using the "Clean Up" option: https://privnote.com/y2tpiOTp#Y6aIQWPnj

Looks like I am screwed now.

**Comment by whitetiger264** [comment]
The logs show zero errors, as far as I can see. I restarted cloud stack and then saw in alerts the following:

- Unable to restart r-172-VM which was running on hostname: hostname(id:44), availability zone: ZONE NAME, pod: POD NAME
- Unable to fence off host: 44
- VM state sync alert

I now also see two VRs for the same network: 
![image](https://github.com/apache/cloudstack/assets/16236376/63180d78-df21-43ed-bf8b-bdf093b38b52)

**Comment by whitetiger264** [comment]
Some Voodoo is happening with my instance. I stopped the additional VR after rebooting CS Management. Then proceeded to destroy it. Rebooted CS again, did a network restart with clean up again on the old existing VR, and this time it completed successfully. I now have a new VR and everything in `/etc/hosts` is showing. 

Going to create a few new VMs and see what happens and update here again. Will try to document my steps this time so I can see what exactly causes this behaviour.

**Comment by DaanHoogland** [comment]
good to read it is fixed @whitetiger264 , sorry we weren't there during you panic.

**Comment by whitetiger264** [comment]
Closing this because I can now no longer replicate it. Will open new case if it happens again.

**Comment by weizhouapache** [comment]
> Closing this because I can now no longer replicate it. Will open new case if it happens again.

Good, thanks for the update

**Comment by weizhouapache** [comment]
it looks same as #8761
