### ISSUE TITLE
Volume view of system VMs gives a 404

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7662]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 
~~~

##### SUMMARY

When browsing to the volume of a system VM an error page apears. The code is 404 as if the page doesn't exist. Either

- the link should be disabled,
- the error should be in the 500 range (server error) or
- the retrieval of ssvm volumes should be implemented

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7772
