### ISSUE TITLE
Site2Site IPSEC VPN doesn't send traffic between VPC and VMware Edge Gateway 

### ISSUE THREAD

**Issue by furyflash777** [apache/cloudstack#7668]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPN
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### OS / ENVIRONMENT

XCP-NG 8.2.1

##### SUMMARY

Site2Site IPSEC VPN doesn't send traffic between VPC and VMware Edge Gateway.

IPSEC connection established successfully

from External Site I can ping internal VPC router ip and alias ip. VM behind VPC  is not reachable . 
form VPC Site I can't ping anything on the External Site. Internet resources are working. 

ACL rules for inernal network "allow all".

i see icmp request on the eth1 (public) vpc router interface, but no reply.  

11:46:00.655692 eth1  In  IP 10.21.52.11 > 10.21.92.41: ICMP echo request, id 3, seq 1100, length 40

Site2Site VPN between 2 VPC is working well with the same configuration. 

##### STEPS TO REPRODUCE

~~~

Create Site2Site VPN between VPC and VMware Edge GW. Configure ACL and Edge Gateway Firewall. 
Try to ping resources. 

Configuration example 

IKE policy
aes256-sha256;modp4096
IKE lifetime (second)
28800
IKE version
ikev2
ESP policy
aes256-sha256
ESP lifetime (second)
3600
Dead peer detection
true
Split connections
true
Force UDP encapsulation of ESP packets
false


~~~

##### EXPECTED RESULTS

~~~
Traffic goes between resources in VPN.  
~~~

##### ACTUAL RESULTS

~~~
Resources are not available in VPN.  
~~~

**Comment by rajujith** [comment]
@furyflash777  could you run 'ipsec status' on the virtual router and verify the expected IPSec connection is established?

**Comment by furyflash777** [comment]
Destroy/Create vpc router VMs help me.
