### ISSUE TITLE
Ceph Primary Storage: Unsupported slash character by parser

### ISSUE THREAD

**Issue by vdombrovski** [apache/cloudstack#7673]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Utils
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Current parser doesn't properly interpret a rbd:// URI with a secret containing a slash "/" character.

##### STEPS TO REPRODUCE

I've added a testcase that fails here to reproduce: https://github.com/apache/cloudstack/pull/7671

##### EXPECTED RESULTS

Unit test passes

##### ACTUAL RESULTS

Unit test fails (also silently fails on a real setup because the URL is incorrect)

**Comment by weizhouapache** [comment]
fixed by #7708
