### ISSUE TITLE
unable to create template from Root Volume Disk

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7674]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
![Screenshot from 2023-06-22 15-12-04](https://github.com/apache/cloudstack/assets/122773216/94bf0023-0e05-4785-92da-7eb7e45e8887)

~~~

**Comment by weizhouapache** [comment]
this duplicates #7675
