### ISSUE TITLE
unable to create template from Root Volume Disk

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7675]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management-server-component
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

Template

##### OS / ENVIRONMENT

RHEL 9, VMWare

##### SUMMARY

I just created template from windows 10 root volume and it's working fine but when i create from Linux it's not working and show like below screenshot. Can anyone suggest me.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### A
![Screenshot from 2023-06-22 15-12-04](https://github.com/apache/cloudstack/assets/122773216/b5eeac15-ab15-4e27-be82-bb89ec9eee54)
CTUAL RESULTS

~~~

~~~

**Comment by kiranchavala** [comment]
@thorzinaung please share the complete management server log

**Comment by thorzinaung** [comment]
@kiranchavala hi, here is the mgmt server log
[management-server.zip](https://github.com/apache/cloudstack/files/11833084/management-server.zip)

**Comment by kiranchavala** [comment]
@thorzinaung please check if the vm has any iso attached, 

Please detach the iso and then try to create a template from volume again

**Comment by weizhouapache** [comment]
@kiranchavala 
I am curious why create template fails when vm has attached ISO . is it a bug ?

cc @DaanHoogland

**Comment by kiranchavala** [comment]
@weizhouapache @DaanHoogland the error is coming from vcenter , the create template from volume will fail if there is a iso attached 

https://pricklytech.wordpress.com/2021/02/13/vmware-vsphere-deploy-ovf-errorvim-fault-filenotfound/
