### ISSUE TITLE
project description should be optional

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7676]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

the project description should default to the project name;
![image](https://github.com/apache/cloudstack/assets/2486961/adb340c7-ff6b-4331-95f4-64b9bd3758e7)

see also #6855 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
description is optional
~~~

##### ACTUAL RESULTS

~~~
description is required
~~~

**Comment by shwstppr** [comment]
@DaanHoogland this has been changed in #7180. Is this still relevant?

**Comment by DaanHoogland** [comment]
> @DaanHoogland this has been changed in #7180. Is this still relevant?

thanks no, slipped through the cracks
