### ISSUE TITLE
template description should be optional

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7679]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI/API
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

the template description should default to the template name;
![image](https://github.com/apache/cloudstack/assets/2486961/a94a89c4-52d6-4322-be04-a6062b0c514b)
see also #6855
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
description is optional
~~~

##### ACTUAL RESULTS

~~~
description is required
~~~

**Comment by shwstppr** [comment]
@DaanHoogland this has been changed in https://github.com/apache/cloudstack/pull/7180. Is this still relevant?

![Screenshot from 2023-10-11 16-10-00](https://github.com/apache/cloudstack/assets/153340/4325cb18-8312-45f0-a4b6-d57b9fc408c6)
