### ISSUE TITLE
Kubernetes support for versions 1.25.0 and 1.26.0 in Advanced Zone with SG

### ISSUE THREAD

**Issue by Arceoavs** [apache/cloudstack#7680]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
kubernetes
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### CONFIGURATION

- Advanced Zone with SG
- Non-HA kubernetes cluster

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Support for Kubernetes Versions 1.25.0 and 1.26.0 is not working. The latest version of kubernetes that can be started with the officially published ISOs is 1.24.0. Despite the wording on the [documentation](NOTE: From ACS 4.16 onwards, Kubernetes versions >= 1.20.x are only supported (https://endoflife.date/kubernetes).): "From ACS 4.16 onwards, Kubernetes versions >= 1.20.x are only supported (https://endoflife.date/kubernetes)."

##### STEPS TO REPRODUCE

1. Add the kubernetes ISO for version >1.24.0 from http://download.cloudstack.org/cks/ to cloudstack as a new kubernetes version under Images/Kubernetes ISOs
2. Create a kubernetes cluster using the UI

##### EXPECTED RESULTS

The kubernetes cluster is created. 

##### ACTUAL RESULTS

The form on the UI stays on screen and shows the loading status. For more than an hour. Reloading the page stops the creation process. 

![image](https://github.com/apache/cloudstack/assets/16841883/2365e8dd-2c24-4e6c-b1a2-77618eb8aa11)

**Comment by weizhouapache** [comment]
@Arceoavs 
any error in management server log ?

can you try with cloudstack 4.18.0.0 ?

**Comment by weizhouapache** [comment]
I have created a PR #7685 to run integration test with 1.25.0/1.26.0
let's wait for the test results

**Comment by weizhouapache** [comment]
this issue might be similiar as #7734

**Comment by weizhouapache** [comment]
@Arceoavs 
I have manually tested latest kubernetes 1.27.3 (in advanced zone), it works well
the integration test #7685 proves that k8s 1.25 and 1.26 work as well.

can you retest it and upload management server logs ?

**Comment by weizhouapache** [comment]
@Arceoavs 
I am able to manually create a k8s cluster (1.26.0) in an advanced zone with security group.

The issue you mentioned looks like an issue with browser cache. Can you hard refresh the page or use incognito mode ?

**Comment by weizhouapache** [comment]
closing this issue

@Arceoavs 
If you still have same issue, please reopen the issue.
Please also try with cloudmonkey
