### ISSUE TITLE
ACS why doesn't it uninstall the iso automatically?

### ISSUE THREAD

**Issue by mm8m6m7m** [apache/cloudstack#7688]
After installing the operating system, why doesn't it uninstall the iso automatically?
Do you have to manually uninstall the ISO every time?
![image](https://github.com/apache/cloudstack/assets/20329685/ed978266-6a16-4f2a-96a6-3419c5d2ef16)

**Comment by DaanHoogland** [comment]
It was designed this was @mm8m6m7m , I don't know why. Maybe, because some VMs run their OS from ISO and don't install it on disk?
I think you only have to detach the iso one time, it wouldn't reattach it every time.

**Comment by mm8m6m7m** [comment]
You can refer to the need for vmwarestation to automatically reboot and automatically uninstall the iso after installing the system using the iso.

**Comment by DaanHoogland** [comment]
Sounds like you want an extra feature to detach any ISO on the first shut-down. This is not generally applicable to any VM booted from ISO, so it must be an option.

**Comment by mm8m6m7m** [comment]
I remember that openstack also implements automatic uninstallation of the installation ISO？

**Comment by rajujith** [comment]
@mm8m6m7m  It could be useful to have this improvement. Like @DaanHoogland  mentioned it should be only optional.

**Comment by mm8m6m7m** [comment]
I just hope that the official ACS can achieve this function, everyone help must top ah.

**Comment by rohityadavcloud** [comment]
This is by design, there is no way for orchestration layer to know if an iso should be ejected or not. Some OS installers require the OS to be manually ejected.
