### ISSUE TITLE
Got issue when create BackUp offering

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7702]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
management-server-component
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### OS / ENVIRONMENT

RHEL 8/ VMWare

##### SUMMARY

when i create backup offering it's show like below screenshot. i don't know what is the error.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~
![backupoffering](https://github.com/apache/cloudstack/assets/122773216/d9a883f3-2709-46aa-b988-5da8ae000912)

~~~

**Comment by kiranchavala** [comment]
@thorzinaung 

You need to enable veeam integration with cloudstack inorder to use the backup offerings 

http://docs.cloudstack.apache.org/en/latest/adminguide/veeam_plugin.html?highlight=veeam

**Comment by rohityadavcloud** [comment]
As the documentation is advised, closing. Please re-open if you hit any operation issue.
