### ISSUE TITLE
CloudStack doesnot automatically start after system reboot

### ISSUE THREAD

**Issue by Atiqul-Islam** [apache/cloudstack#7710]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
Cloudstack Management Server get into a bad state after system restart.
~~~

##### CLOUDSTACK VERSION
~~~
4.17.2
~~~

##### CONFIGURATION
~~~
CloudStack with Isolated Network
~~~

##### OS / ENVIRONMENT
~~~
Ubuntu Server 22.04
~~~

##### SUMMARY
~~~~
Restarting the bare metal machine puts cloudstack in a bad state. 
Restarting the management server service seems to resolve the issue.
Is there any  way to ensure that restarting the bare metal will bring up the Management Server in the last known state before the restart.
~~~~

##### STEPS TO REPRODUCE
~~~
Install CloudStack 4.17.2 on Ubuntu Server 22.04
Reboot the bare metal system
~~~

##### EXPECTED RESULTS
~~~
I expect CloudStack to automatically come up in the state it was when the system was rebooted.
~~~

##### ACTUAL RESULTS
~~~
Management Server ends up in a bad state.
Restarting the management server via the command `sudo systemctl restart cloudstack-management-server` resolves the issue.
~~~

**Comment by zap51** [comment]
@Atiqul-Islam I've not been able to reproduce this issue. Would you try checking,
1. `# systemctl is-enabled cloudstack-management`
2. `# systemctl status cloudstack-management`

Inspect for errors in the configuration as well. 

Thanks

**Comment by shwstppr** [comment]
Hi @Atiqul-Islam were you able to check the status of the service as suggested in the above comments?

**Comment by rohityadavcloud** [comment]
Closing as stale. @Atiqul-Islam the solution is https://github.com/apache/cloudstack/issues/7710#issuecomment-1646743861
