### ISSUE TITLE
Please provide a sql scripts to force clear all the related resource of a zone when a zone was decomission

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#7715]
##### ISSUE TYPE
 * Other

some zone has been decomission,  some resource can not delete because the system vm can not start.

could you please provide a sql scripts to force clear all the related resource of a zone?

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng which resources do you mean?
also please see #7630 , it fixes some of what you describe and might contain clues to what you need.

**Comment by rajujith** [comment]
@xuanyuanaosheng  if you want to remove the resources of all the zones you could run the `cloudstack-setup-databases `again but this won't delete any resources at the hypervisors.

**Comment by xuanyuanaosheng** [comment]
@rajujith I just want to delete the resources related to one zone.
---
@DaanHoogland  
The resources  include the volumes, Primary storage, Secondary storage, Template. and the physical network etc.

In some reason, the hosts and the Storage can not work again, this cause the System VMs can not started and the  so I can not delete the resource in this zone.

like:

I can not delete the template using `Force delete`

![image](https://github.com/apache/cloudstack/assets/4197714/5d69abc8-6be0-47aa-ba93-cc34b36cc16e)

so I can not delete the Secondary storage

![image](https://github.com/apache/cloudstack/assets/4197714/e3ae3d6d-2af7-49bd-a608-c8f969e87648)

I can not delete the volumes
![image](https://github.com/apache/cloudstack/assets/4197714/e8279808-96df-4a2a-99c4-04edcdaf67f1)

so I can not delete the Primary storage

![image](https://github.com/apache/cloudstack/assets/4197714/8bd61040-17ed-4ef0-a529-92b083e50ea0)

so I can not delete the cluster, pod and zone.

Please provide a  sql scripts to force delete these resources.

**Comment by rajujith** [comment]
@xuanyuanaosheng  unfortunately there is no ready to use script delete a specific zone and associated resources to the best of my knowledge.

**Comment by xuanyuanaosheng** [comment]
@rajujith  It is sad to hear about that

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng ,

- You have a decommisioned zone (is it disabled?
- I think it is not removed, because you indicate you want to remove the physical network and a zone cannot be removed with physical networks. Is that correct?
- the volumes and Templates you want to remove can not be removed because there is no SSVM. Are these still attached to VMs?

Please specify what action you are taking and what you would expect from it. I have removed zones for the ticket I mentioned without problems but maybe there is a sequence of events, or an extra item in the zone that prevents it for you.

**Comment by xuanyuanaosheng** [comment]
@DaanHoogland 

- Yes, The zone is disabled.

![image](https://github.com/apache/cloudstack/assets/4197714/aa812336-fb31-43b6-8dc7-37598b7c1f27)

- Yes， the zone has physical network.

![image](https://github.com/apache/cloudstack/assets/4197714/a18f5fd6-7752-4d02-932f-a7f416dc61ba)


- The instances have been deleted and the Volumes are not attached to VMs.

![image](https://github.com/apache/cloudstack/assets/4197714/146539c4-ec97-4466-b717-6cfd70aa78ac)

---
##### STEPS TO REPRODUCE

 -  Create a zone has all the resource and work fine.
 -  Delete the Hosts  in this zone.
 -  Don't readd the hosts. In this situation, how to delete all the remain resources in this zone?

I

**Comment by DaanHoogland** [comment]
@xuanyuanaosheng it does not sound as the right order to go about it. But as a reparation method you could try and find the right SQLs to delete the remnance. Make sure you backup your DB before trying anything.

You should start at tables like `template_store_ref`, `volume_store_ref`, `snapshot_store_ref` and `template_spool_ref`, and work in two directions.
For IPs I think it would not be so hard as the table `user_ip_address` has a field for zone. This one is also the table the fix I referred in https://github.com/apache/cloudstack/issues/7715#issuecomment-1619699345 is for.

hope this helps

**Comment by xuanyuanaosheng** [comment]
I will close this issue
