### ISSUE TITLE
testClient has hypervisortype kvm when running on vmware

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7717]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
marvin
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

When running test_vm_deployment_planner.py on vmware, `test_01_deploy_vm_on_specific_host` fails with an exception because the template to deploy a VM, cannot be found. debugging found that the template for KVM is being looked for and this fails.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
> @DaanHoogland did you test on an environment with multiple zones ?

yes, but this was mute and could do with 3rd party testing. I did only run the tests on the default zone. I am not sure how and even if we can use smoke tests on more than the first zone in an env.

**Comment by weizhouapache** [comment]
> > @DaanHoogland did you test on an environment with multiple zones ?
> 
> yes, but this was mute and could do with 3rd party testing. I did only run the tests on the default zone. I am not sure how and even if we can use smoke tests on more than the first zone in an env.

@DaanHoogland 
I think we never run smoke tests on multiple zones, right ?
would you like to keep #7718 open and push more fixes to the same PR, or merge #7718 asap ?

**Comment by DaanHoogland** [comment]
> > > @DaanHoogland did you test on an environment with multiple zones ?
> > 
> > 
> > yes, but this was mute and could do with 3rd party testing. I did only run the tests on the default zone. I am not sure how and even if we can use smoke tests on more than the first zone in an env.
> 
> @DaanHoogland I think we never run smoke tests on multiple zones, right ? would you like to keep #7718 open and push more fixes to the same PR, or merge #7718 asap ?

I have no more fixes atm, several fixes I planned for it are already merged in other PRs. The major issue left now is qemu not supporting live-migration atm. Not sure if we should deal with that in the env or in the test code.
no asap, but we can merge.
