### ISSUE TITLE
zone installation wizard traffic types

### ISSUE THREAD

**Issue by msteini** [apache/cloudstack#7721]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

advanced networking

##### SUMMARY

when adding a second physical network during adding a new zone via ui you get the following error code, even when all required traffic types are set:

"Error in configuration! All required traffic types should be added and with multiple physical networks each network should have a label."

![Network_Wizard](https://github.com/apache/cloudstack/assets/121959761/1d54af10-6421-4fa8-b654-f16ea8315ad9)
![Network_Wizard_Error](https://github.com/apache/cloudstack/assets/121959761/109a642e-a0b4-4d66-b1f8-34efd73cf081)

A possible workaround is to edit each Traffic type and add a label manually.

##### STEPS TO REPRODUCE

1. Add a new Zone: Infrastructure -> Zones -> Add zone
2. Choose Zone type "Core"
3. Choose Core zone type "Advanced"
4. Fill Zone details
5. Under Network add physical network and configure types
6. Click Next -> Error appears

~~~

~~~

##### EXPECTED RESULTS

~~~
UI should use name of traffic type as default label.
~~~

##### ACTUAL RESULTS

~~~
UI is not able to proceed.
~~~

**Comment by DaanHoogland** [comment]
@msteini , I don't think the name of the traffic type are the correct labels. In addition to that the labels are hypervisor type specific and depend a bit on the choices you make configuring your NICs.

**Comment by msteini** [comment]
@DaanHoogland, thanks for looking in to that. I totally understand your point, but if i do not configure a second physical network i can proceed without setting any label. Which label is there set? 
Thanks.

**Comment by msteini** [comment]
@DaanHoogland thanks for your answers. I will close this issue.
