### ISSUE TITLE
Unable to create BackUP offering

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7725]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
API, Management-Server-Component
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0..0
~~~

##### OS / ENVIRONMENT

RHEL8/VMware
![backupofferingerror](https://github.com/apache/cloudstack/assets/122773216/94d7a4c4-f4b2-4728-a909-1168828e4ba2)

##### SUMMARY

When i create backup offering, it's not working and shows up like this.
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
![backupofferingerror](https://github.com/apache/cloudstack/assets/122773216/2fac7bee-55f5-44f2-a186-2ac5e52f2511)

~~~

**Comment by DaanHoogland** [comment]
@thorzinaung is the backup provider working out of bounds?

**Comment by kiranchavala** [comment]
@thorzinaung  could you please let me  know the steps you followed when enabling backup offerings 



Have you followed the steps properly? 

http://docs.cloudstack.apache.org/en/latest/adminguide/veeam_plugin.html?highlight=veeam

**Comment by thorzinaung** [comment]
@kiranchavala @DaanHoogland  as per your mentioned. i did all the step. now it's not showing error but i can't see external ID. I quite dont understand what is that mean and i still cant create backup offering. pls see attached file.
![RRRR](https://github.com/apache/cloudstack/assets/122773216/0385bf38-18cb-4219-b0c7-f27296f5c290)

**Comment by thorzinaung** [comment]
@kiranchavala bhai, now i got backup offering but still i quite don't understand of it's concepts. Where my backup will save when i choose my instance to backup. i can see bakup in my backup option but still can't find where it's saved backup file located. Could you please guide me or refer me a link that i can clearly read about backup in cloudstack. thank you bhai.
![BackUp1](https://github.com/apache/cloudstack/assets/122773216/e5e00ea3-cdce-4b8c-920d-bd0f3f1490b7)

**Comment by thorzinaung** [comment]
When i restore, it's show like that. @kiranchavala  @DaanHoogland Could you pls guide me?
![error](https://github.com/apache/cloudstack/assets/122773216/55e69f51-e5a1-4687-83de-0699f4c37a5a)

**Comment by DaanHoogland** [comment]
@thorzinaung , I do not have a Veeam setup, so I cannot. But if you have any logging or stack traces I can try and find a problem.

**Comment by thorzinaung** [comment]
@DaanHoogland brother, sorry for late reply. i have stopped for deploying with vmware now. i am trying to do with KVM base. Could you pls refer me or suggest me to read about cloudstack with KVM. because im new to KVM and i don't know about architecture with KVM. Sorry for inconvenient brother. Could you pls answer if you're ok. I really appreciate it.

**Comment by DaanHoogland** [comment]
@thorzinaung there is a kvm b&r plugin and I understand there is a second in the making. About KVM itself; this should be clear in the [docs](http://docs.cloudstack.apache.org/en/latest/)

**Comment by rohityadavcloud** [comment]
This is configuration related question and not really a bug, please discuss on Github Discussions or on the mailing list. Thank you.
