### ISSUE TITLE
UI forgets project context on refresh

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7736]
1. Create a project
2. Switch to that project in UI, the nav bar goes dark
3. Refresh site (Ctrl+R, or cmd+R)
4. The UI context and dark nav bar is gone

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

**Comment by weizhouapache** [comment]
fixed by #7893
