### ISSUE TITLE
Systemvm agent state isn't up

### ISSUE THREAD

**Issue by HtainL** [apache/cloudstack#7737]
##### ISSUE TYPE
 
 * Other

##### COMPONENT NAME

~~~
systemvm agent state isn't up
~~~

##### CLOUDSTACK VERSION

~~~
4.16
~~~

##### OS / ENVIRONMENT
 rhel 8.5/ vmware 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
When i downgrade from CS4.18 to CS 4.16.1.1 And, systemvm and console vm agent isn't up. 
~~~
![System VMs - CloudStack -](https://github.com/apache/cloudstack/assets/134905472/0fd8f647-3657-4c50-8f9a-96
![System VMs - CloudStack -](https://github.com/apache/cloudstack/assets/134905472/288234d9-ec5d-4af2-9750-722d6e8bc48f)
9e13173080)

**Comment by DaanHoogland** [comment]
@HtainL , did you downgrade the DB and the packages and check if the old SVM template is still on the storage?

**Comment by HtainL** [comment]
issued was closed. 
1) delete systemvm and console vm 
2) Then, systemvm auto create and agent was up
