### ISSUE TITLE
Cloudstack Multiple Management

### ISSUE THREAD

**Issue by Hossein4185** [apache/cloudstack#7738]
##### ISSUE TYPE
question

##### CLOUDSTACK VERSION
cloudstack 4.17.2

##### SUMMARY
When using the Cloudstack Multiple Management, can i use several types of Linux at the same time in The one cluster, such as Ubuntu 18.04 and CentOs7?

**Comment by DaanHoogland** [comment]
@Hossein4185  , AFAIK this is possible but not usual, so you might encounter problems unknown. 
Take not that for compute clusters this is definitely not supported.

**Comment by Hossein4185** [comment]
thank you.
