### ISSUE TITLE
default value localhost does not work as endpoint.url for kubernetes

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#7745]
Hi,

Version `4.18`

The default value in `endpoint.url` does not allow the creation of kubernetes cluster, the solution is to change it to a public IP; for example for my case `http://192.168.122.10:8080/client/api` (instead of `http://localhost:8080/client/api`)
![2023-07-18_01-00](https://github.com/apache/cloudstack/assets/2527234/ee2b8f11-d9c4-48fb-8d48-05104bb54da8)

**Comment by rohityadavcloud** [comment]
@abdelouahabb CloudStack may not automatically know what IP/endpoint or domain you've configured so yes you're right you need to configure the accessible URL (that's accessible by the k8s cluster).
Feel free to raise a PR to improve the settings description.

Thanks for the issue. Closing as it's a question, and you've figured how to change it.
