### ISSUE TITLE
UI: support utf-8 string in user data

### ISSUE THREAD

**Issue by hooklee2000** [apache/cloudstack#7748]
##### ISSUE TYPE

  Improvement Request

##### COMPONENT NAME
 UI,

##### CLOUDSTACK VERSION
4.18.0.0

##### CONFIGURATION
 basic network, advanced networking

##### OS / ENVIRONMENT
CentOS 7.9

##### STEPS TO REPRODUCE
1、register user data input user data :
```yaml
#cloud-config
bootcmd:
  - echo hello中文 > /tmp/test.txt
```
2、raised error:
RegisterUserData.vue 195
Method：handleSubmit (e)  params.userdata = encodeURIComponent(btoa(this.sanitizeReverse(values.userdata)))；

btoa only support ascii， it can'nt support chinese string such as 中文

##### EXPECTED RESULTS
I checked cloud-init issue https://github.com/canonical/cloud-init/issues/3271， supporting UTF-8  is to be fixed in cloud-init in version 19.2-53，CentOS 7.9 uses cloud-init v19.4.
Maybe we can support utf-8 string in user data

**Comment by rohityadavcloud** [comment]
@harikrishna-patnala cc @shwstppr @DaanHoogland - don't we support utf8 characters? Or is it a limitation of our API?

**Comment by shwstppr** [comment]
@rohityadavcloud this seems to be a UI only issue. May need a change

**Comment by weizhouapache** [comment]
fixed by #7749
