### ISSUE TITLE
Domains doesn't list in the UI Search filter if the count is greater than 500

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7753]
**ISSUE TYPE**

 * BUG

**COMPONENT NAME**

UI

**CLOUDSTACK VERSION**

Cloudstack 4.18

**SUMMARY**

Domains doesn't list in the UI Search filter if the count is greater than 500

**Steps to reproduce the issue** 

1. Create about 510 domains

2. Go To compute >instance > Search filter

3. Try to search domains greater than 

Screenshot attached

![Screenshot 2023-07-19 at 1 14 33 PM](https://github.com/apache/cloudstack/assets/1401014/d2068086-df07-48e6-ae9d-1b4a03161795)

There is no issue with the listdomains api call, it works properly when pagesize is passed 

https://cloudstack.apache.org/api/apidocs-4.18/apis/listDomains.html

The maximum pagesize is 500 

(cmk)  > list domains filter=name,state,path, pagesize=501 page=1
🙈 Error: (HTTP 431, error code 4350) Page size can't exceed max allowed page size value: 500

(cmk)  > list domains filter=name,state,path, pagesize=500 page=2
{
  "count": 521,
  "domain": [

**Actual behavior** 

Cloudstack ui doesn't display the domains > 500 in the search filter

**Expected behavior** 

Cloudstack ui should display the domains > 500 in the search filter

**Comment by kiranchavala** [comment]
The list domain api response returns all the domain but cloud stack UI is not showing the domains greater than pagesize 500


![Screenshot 2023-07-19 at 1 25 42 PM](https://github.com/apache/cloudstack/assets/1401014/2237562d-29ce-46a5-902e-b3bdaedf263f)


May be need to look into the "SearchView.vue" in the code base

**Comment by DaanHoogland** [comment]
fixed by #7766, but has 7780 as a follow-up
