### ISSUE TITLE
VMs not rebalancing based on CPU/Mem Uses 

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#7755]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
VMs not auto balancing b/w hypervisors based on Mem/Cpu uses of hypervisors Even we configured VM HA in templates. 
If any of hypervisors reached to capacity on uses VMs running on hyp getting rebooted instead of rebalancing before hypervisor uses reaching threshold.

Ex - At time of VM creation Mem uses 60% but due to overprovisoning at certain point Memory uses reached to 100% on Hypervisor and VMs got rebooted .. As per standard behavior VMs should migrated to another hypervisor at any threshold like 80% uses of actual Mem. 

##### EXPECTED RESULTS
<  VMs should auto balance in cluster b/w hypervisors based on load >

~~~

~~~

**Comment by rajujith** [comment]
@yashi4engg  CloudStack doesn't provide the auto load balancing of VMs yet. If you are using VMware ESXi you can enable DRS in the ESXi cluster.

**Comment by yashi4engg** [comment]
@rajujith  - We are planning to introduce that feature in future or any similar setting like ESXi you suggest for KVM Hypervisors.
