### ISSUE TITLE
Provide an option to update role of an account from the UI 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7756]
ISSUE TYPE

 * Enhancement Request/Improvement Request

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack 4.18

SUMMARY

Provide an option to update role of an account from the UI 

Currently to update role of account is only possible from the api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/updateAccount.html

The ui only provides the option to update the name and network domain.

It would be helpfull for the admin user to update the role of an account directly from the UI ( A dropdown of various roles available in the system) 

Screenshot attached

 
![Update Role](https://github.com/apache/cloudstack/assets/1401014/19613495-d562-468c-a9bb-d5bada5da312)

**Comment by rohityadavcloud** [comment]
PR - https://github.com/apache/cloudstack/pull/9012

**Comment by DaanHoogland** [comment]
fixed in #9012
