### ISSUE TITLE
ssvm not setting default gateway to eth2 -  acs 4.18.0

### ISSUE THREAD

**Issue by Chih80** [apache/cloudstack#7800]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
ssvm
~~~

~~~

##### CLOUDSTACK VERSION
4.18

~~~

~~~

##### CONFIGURATION
Advanced networking

##### OS / ENVIRONMENT
ubuntu 20.04

##### SUMMARY

ssvm default gateway although listed correctly in the gui details, upon checking  netstat 0.0.0.0/0 is not pointing to it and not set for eth2.

##### STEPS TO REPRODUCE
create or destroy ssvm

~~~

~~~

##### EXPECTED RESULTS

default gateway set to eth2.
~~~ 

~~~

##### ACTUAL RESULTS

default gateway not set to eth2.

~~~

~~~

**Comment by Chih80** [comment]
CPVM showing the correct default gateway to eth2 conf. SSVM missing the default gateway for eth2 conf.

**Comment by weizhouapache** [comment]
@Chih80 
CPVM and SSVM are configured like it for many years.

 is there any problem caused by it in your environment ?

**Comment by Chih80** [comment]
I don't believe so. Triple check all the network settings, everything is correct. The detail on the gui shows the correct default gateway, but within ssvm, it is not set to eth2.

current - 0.0.0.0/0 -> x.x.x.x eth1

supposed to be - 0.0.0.0/0 -> x.x.x.x eth2. 

why it is not setting to eth2?

**Comment by weizhouapache** [comment]
> @weizhouapache I don't believe so. Triple check all the network settings, everything is correct. The detail on the gui shows the correct default gateway, but within ssvm, it is not set to eth2.
> 
> current - 0.0.0.0/0 -> x.x.x.x eth1
> 
> supposed to be - 0.0.0.0/0 -> x.x.x.x eth2.
> 
> why it is not setting to eth2?

@Chih80 
I checked the system vms in some of my testing environments. The default gateway of both CPVM and SSVM are both set to eth2. 

can you share the value of the global setting `secstorage.allowed.internal.sites` ?

**Comment by Chih80** [comment]
@weizhouapache Yea, my CPVM has the correct settings but not SSVM.

secstorage.allowed.internal.sites, I have 0.0.0.0/0.

**Comment by Chih80** [comment]
it turned out to be the 0.0.0.0/0 that was added, once removed the default gateway is set properly for eth2 in ssvm. Thank You @weizhouapache

**Comment by weizhouapache** [comment]
> it turned out to be the 0.0.0.0/0 that was added, once removed the default gateway is set properly for eth2 in ssvm. Thank You @weizhouapache

good it is resolved
