### ISSUE TITLE
Database Restore Error

### ISSUE THREAD

**Issue by Hossein4185** [apache/cloudstack#7819]
##### ISSUE TYPE
Error

##### CLOUDSTACK VERSION
4.13.1

##### OS / ENVIRONMENT
ubuntu 22

##### SUMMARY
I want to Restore The Cloud database Dump an get Error
ERROR 1005 (HY000) at line 4170: Can't create table cloud.mshost_status (errno: 150 "Foreign key constraint is incorrectly formed")

Iam use mariadb 10.6

**Comment by DaanHoogland** [comment]
@Hossein4185 , I am not sure if this is the right location for the best help on mysql/mariadb issues, but maybe you can try the following:
- check that the DB you try to restore in does not contain any remnance of newer versions of the DB? (mshost_status was introduced in 4.17)
- see if the dump you try to restore is complete? i.e. see the definition of the foreign key the complaint is about.

**Comment by Hossein4185** [comment]
Resolve the problem.
One question I had was this. cloudstack 4.13.1 Is it compatible with MariaDB 10.6?

**Comment by DaanHoogland** [comment]
> Resolve the problem. One question I had was this. cloudstack 4.13.1 Is it compatible with MariaDB 10.6?

I do not know of any version problems, so I think yes it is.

**Comment by Hossein4185** [comment]
thank you so much
