### ISSUE TITLE
Stopped VM with local storage and data disk created/attached fails if created on a different host

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7834]
This is where all disks are local storage. Create a VM with root disk on host A, stop the VM and create a disk and attach it to the VM and chances are sometimes it gets created on host B (local storage); however on attach it fails with error as data disk is on local storage of host B.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Local storage, VM/volume
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

Adv zone

**Comment by weizhouapache** [comment]
@rohityadavcloud 
what's the hypervisor and OS ?

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7886
