### ISSUE TITLE
UI bug: internal "refresh" of the UI can cause a wrong VM to be deleted

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#7840]
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### CONFIGURATION

No special configuration needed.

##### OS / ENVIRONMENT

NA

##### SUMMARY

Start VM deployment process and leave the VM being deployed (it takes 5+ seconds)
Go immediately and list e.g. single VPC details (chose VPC and click on it), wait for a bit until the previous API call (to deploy VM) is completed, and the current view (a specific VPC view) will be replaced with the VM view (the VM which you have deployed).
This is not critical.

**However, a user searching for VM (many results, so all API calls in background take time to complete), then quickly clicking the VM, clicking the delete button - can result in user deleting the wrong VM - see the video demonstraion here: https://screenpal.com/watch/c0j6j7VkPJC**

**DUE TO THIS, I MARK IT AS CRITICAL.**

##### STEPS TO REPRODUCE

See the Summary above, see the video.
Beside fixing the "refresh of UI after previous API call completion" general problem - it's critical to reproduce the deletion bug issue, to be able to confirm it is fixed later and not rely on general fix and hope it fixes the deletion issue.
I assume that introducing additional latency (Chrome can do this in Developer Tools) will help make sure that API calls takes long time to complete, so it should be doable to reproduce the issue (I'm still working on reproducing the deletion bug)

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
I don't think an issue due to a user *quickly* clicking around is critical.

**Comment by weizhouapache** [comment]
fixed by #7846
