### ISSUE TITLE
Hide delete button for templates that are in "Installing template" state

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#7865]
##### ISSUE TYPE

 * Bug Report
 
![image](https://github.com/apache/cloudstack/assets/45762285/fde184e1-8cdf-4e21-8987-9b4a873e443a)

ACS 4.18.1-snapshot

Allows to press the delete button, but then gives error to try with other templates which are not "installing", etc.

Hide the button/gray-put (whatever we do in other such cases)

**Comment by nvazquez** [comment]
Hi guys, I have created PR: https://github.com/apache/cloudstack/pull/7882 can you please review?

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/7882
