### ISSUE TITLE
Management Server HA

### ISSUE THREAD

**Issue by HtainL** [apache/cloudstack#7885]
##### ISSUE TYPE
 Other
 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
etc
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### OS / ENVIRONMENT
Ubuntu 22.04

##### SUMMARY
 Ubuntu server was installed kvm and in kvm i create cloudstack management, sql, nfs, dns server. I want to get HA of all this kvm vm when one of my ubuntu server was failed. I configured with pacemaker, corosync and pcs and i shutdown my server but it not automatically migrate and run to another server. 

Storage server mount on /var/lib/libvirt/images and /etc/libvirt/qemu. Both servers can access cs.xml and cs.qcow2.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS
 

~~~

~~~

**Comment by rajujith** [comment]
Hi @HtainL  what are you trying appears to be outside Cloudstack, not a feature of Cloudstack itself. Cloudstack can work fine even if one of the management servers goes down. For DB HA you could try the DB HA feature within Cloudstack but it seems to have some issues. Another option is using a Galera Cluster.

**Comment by rohityadavcloud** [comment]
This is outside the scope of CloudStack; we already support HA by having a cluster of mgmt server and by design we allow multiple mgmt servers that can take over resources management (vms, hosts etc) when the owner mgmt server is Down.
