### ISSUE TITLE
GUI -  search instance always give the first VM name and GUI is very slow 

### ISSUE THREAD

**Issue by dseralathan** [apache/cloudstack#7910]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

Categorize the issue - UI

##### CLOUDSTACK VERSION
CloudStack 4.18.0.0

##### OS / ENVIRONMENT
KVM with OEL9

##### SUMMARY
in GUI - when  search instance with particular instance name always give the first VM name in the dashboard 
 GUI is very slow

##### STEPS TO REPRODUCE
GUI- Compute-Instances - search tab - give instance name 

##### EXPECTED RESULTS
search should give the exact VM(instance) name 

##### ACTUAL RESULTS
searching one VM gives the  other VM name ( the first VM in list ) 
~~~

**Comment by dseralathan** [comment]
Added point : When working on one instance the gUI goes to that first VM in list

**Comment by rohityadavcloud** [comment]
@dseralathan can you share your ACS and MySQL server versions?

The search results matches with VMs matching/containing the substring, CloudStack keyword search isn't exact. Are other VMs in your search result having the keyword in their names (or displayname)?

**Comment by rohityadavcloud** [comment]
@dseralathan does it help improve the response time (slowness of UI) if you add the following in the URL:

http://<your cloudstack domain or ip>:8080/client/#/vm?details=min
http://<your cloudstack domain or ip>:8080/client/#/vm?details=servoff,tmpl,nics

compared to:
http://<your cloudstack domain or ip>:8080/client/#/vm

**Comment by weizhouapache** [comment]
@dseralathan 
this should be improved by #7911 
can you test it ? you can run UI locally following https://github.com/apache/cloudstack/tree/main/ui#development

**Comment by DaanHoogland** [comment]
@dseralathan closing this as fixed by #7911. please reopen or open a new one as you see fit if needed.

**Comment by rohityadavcloud** [comment]
Sorry opening this @DaanHoogland need to hear from @dseralathan thanks

**Comment by dseralathan** [comment]
Thanks weizhouapache and DaanHoogland

**Comment by DaanHoogland** [comment]
> Thanks weizhouapache and DaanHoogland

@dseralathan , does it help (see @rohityadavcloud 's questions at https://github.com/apache/cloudstack/issues/7910#issuecomment-1692834533 and https://github.com/apache/cloudstack/issues/7910#issuecomment-1692899856) I.e. can we close this issue?

**Comment by rohityadavcloud** [comment]
Thanks @dseralathan I'm assuming this is acceptable for you, if not pl re-open or raise another issue with more details and steps to reproducing the issue.

**Comment by dseralathan** [comment]
the VM search give exact VM and is not changing to the first VM in list after we exclude state,IP in field

**Comment by rohityadavcloud** [comment]
We're potentially still seeing this, so re-opening this with the note on investigation - sometimes the table/column could have multiple indexes - when the query choose between 2 or more indexes the wrong one, it could take time for the query to complete. I would investigate if in the case of listVirtualMachines and lisVirtualMachinesMetrics API what queries pick what columns or what indexes the optimiser may choose to run the query. The explain query (https://dev.mysql.com/doc/refman/8.0/en/using-explain.html) can help us know which indexes are in the path of search/optimisation - fixing the index could make the query go faster. 

cc @andrijapanicsb @borisstoyanov @vishesh92 @harikrishna-patnala @shwstppr @DaanHoogland

**Comment by rohityadavcloud** [comment]
Likely also addressed by https://github.com/apache/cloudstack/pull/9198
@dseralathan can you try to test it in your env if possible?

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9198 pl re-reopen if you still have issues, thanks.

**Comment by rohityadavcloud** [comment]
Additionally fixed in https://github.com/apache/cloudstack/pull/9177
To make the listing faster, the new global setting will need to be set to false.
