### ISSUE TITLE
Kubernetes cluster not scaling down once it gone to alert state

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7928]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Kubernetes UI

##### CLOUDSTACK VERSION

4.18
##### CONFIGURATION

Advance Networking

##### OS / ENVIRONMENT

All runnig on Ubuntu 22.04

##### SUMMARY

My kubernetes cluster was configured for autoscale and when I deployed some 40 pods on the cluster it when to Alert state due to some resources. So I removed all pods from the cluster and restarted the cluster. Now cluster state is in Running status but all new nodes it spinned up is still running and scale down is not triggered. 

##### STEPS TO REPRODUCE

Expected scale down has to be triggered and cluster should move to old state

**Comment by weizhouapache** [comment]
@Noelantogerorge 
I think this is same as #7920 , right ? cc @shwstppr

**Comment by Noelantogerorge** [comment]
@weizhouapache 
Yes it is same... I will close this and followup on #7920

**Comment by weizhouapache** [comment]
> @weizhouapache Yes it is same... I will close this and followup on #7920

cool.
btw thanks for the details in description
