### ISSUE TITLE
User role unable to expunge a VM

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7936]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

UI

##### CLOUDSTACK VERSION

4.18

##### CONFIGURATION

Advance networking

##### OS / ENVIRONMENT

All on Ubuntu 22.04

##### SUMMARY

A user with role USER is unable to expunge VM created by same user. 

##### STEPS TO REPRODUCE

Created an account user and add role as USER. Then create a new VM under that user
after creation go for delete option and VM will get destroyed but VM root volume will be shown on Storage -> Volume.
Only admin user can expunge that volume.

##### EXPECTED RESULTS

User should have full permission to create and delete Volume and VM's. If a user creates a VM and delete that its corresponding root volume should expunge..

##### ACTUAL RESULTS

Root volume remains and admin user has to login to and delete that vm. As VM is only going for destroyed state

**Comment by Noelantogerorge** [comment]
Please find some screen shots for more clarifications
![image](https://github.com/apache/cloudstack/assets/126588356/34f6b19f-c1a7-4b91-9509-b485e5d51274)
![image](https://github.com/apache/cloudstack/assets/126588356/0f30f767-3503-4df3-927c-ada684ce28f4)
![volume_delete](https://github.com/apache/cloudstack/assets/126588356/b72cd300-2ec2-4c7a-b3c0-a16e7239d02d)

**Comment by rohityadavcloud** [comment]
Hi @Noelantogerorge thanks for the issue, do you have these global settings enabled:
- allow.user.expunge.recover.vm
- allow.user.expunge.recover.volume

**Comment by Noelantogerorge** [comment]
Hi @rohityadavcloud 
Thanks for the swift reply.
I had allow.user.expunge.recover.volume enabled but allow.user.expunge.recover.vm was not enabled. Enabling that too solved my issue..
Just a small clarification.
I had created 2 shared network (public1 and public2) in Admin user. Is it possible to block all shared network on user role and also show only particular shared network on user role.
Now user role is able to view all shared network and also assign same to instance.
My requirement was like one department should not have shared network so their VM's should only have Isolated network and another department should able to view one of my shared network called public1 so their vm's should have a public IP. 
It would be helpful if you can share me which role should be denied and which should be allowed to get this done....

**Comment by DaanHoogland** [comment]
> I had created 2 shared network (public1 and public2) in Admin user. Is it possible to block all shared network on user role and also show only particular shared network on user role.
> Now user role is able to view all shared network and also assign same to instance.
> My requirement was like one department should not have shared network so their VM's should only have Isolated network and another department should able to view one of my shared network called public1 so their vm's should have a public IP.
> It would be helpful if you can share me which role should be denied and which should be allowed to get this done....

@Noelantogerorge , I think you would want to create domains and create the accounts in those domains. Maybe that solves your use-case.
