### ISSUE TITLE
Default Domain Admin role not working after migration

### ISSUE THREAD

**Issue by MartinEmrich** [apache/cloudstack#7946]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Mangement Server
~~~

##### CLOUDSTACK VERSION
~~~
4.18.0
~~~

##### OS / ENVIRONMENT
CentOS 7 / MariaDB 10.6

##### SUMMARY
After migrating to dynamic roles with `migrate-dynamicroles.py` and upgrading from 4.11 to 4.18, domain admins can no longer log in or use the API.

##### STEPS TO REPRODUCE
* Use and migrate an Apache Cloudstack installation since 2013 until at 4.11.2.0.
* Migrate to dynamic roles with `/usr/share/cloudstack-common/scripts/util/migrate-dynamicroles.py -H localhost -b cloud -u cloud -p xxxx -D` and moving command.properties out of the way

##### EXPECTED RESULTS
~~~
Domain account users to continue to work as before.
~~~

##### ACTUAL RESULTS
Top level root admin works fine.

But domain admin or other users do not:

Logging in to the UI gets stuck at "Discovering features...".

using the API results in messages like
```
2023-09-06 09:43:41,659 DEBUG [c.c.a.ApiServlet] (qtp1444635922-1285:ctx-d0c978ae) (logid:bff1f438) ===START===  10.12.0.248 -- GET  name=cdskl-shared&command=listServiceOfferings&apiKey=XXXX
2023-09-06 09:43:41,664 DEBUG [c.c.a.ApiServer] (qtp1444635922-1285:ctx-d0c978ae ctx-eefbdbcf) (logid:bff1f438) CIDRs from which account 'Account [{"accountName":"admin","id":39,"uuid":"813308c2-8405-46c3-aa09-0e6bbd90e3b1"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2023-09-06 09:43:41,666 DEBUG [c.c.a.ApiServer] (qtp1444635922-1285:ctx-d0c978ae ctx-eefbdbcf) (logid:bff1f438) The API [listServiceOfferings] does not exist or is not available for the account Account [{"accountName":"admin","id":39,"uuid":"813308c2-8405-46c3-aa09-0e6bbd90e3b1"}].
2023-09-06 09:43:41,667 DEBUG [c.c.a.ApiServlet] (qtp1444635922-1285:ctx-d0c978ae ctx-eefbdbcf) (logid:bff1f438) ===END===  10.12.0.248 -- GET  name=cdskl-shared&command=listServiceOfferings&apiKey=XXXX
````

##### Additional info

The UI does not allow me to add permissions to the default roles. But by adding a specific permission to the database manually makes that API function work for domain admins, e.g.:
```
INSERT INTO `cloud`.`role_permissions` (`uuid`, `role_id`, `rule`, `permission`, `description`) VALUES ('8890d77e-c77a-4df1-a5f6-6af1dd52ac0c ', 3, 'listVirtualMachines', 'ALLOW', 'Test');
```

Reading the migration Python script source code, using "-D" for "use default rules" does only enable the dynamic rule checker option, but does `sys.exit(0)` directly after that. It does *not* insert any default rules into the database.

I suspect that this might work for a fresh installation, where the installation process might fill the role_permissions table with what is necessary, but that is missing here.

**Comment by MartinEmrich** [comment]
Luckily, wildcards do work, so this is a workaround:

```
INSERT INTO `role_permissions` (`id`, `uuid`, `role_id`, `rule`, `permission`, `description`, `sort_order`) VALUES (971, '8890d77e-4c07-11ee-bcb6-7eaeea291d34', 3, '*', 'ALLOW', 'Workaround', 0);
```

But I am not sure if this gives more permissions than "Domain Admin" should normally have. As this is an internal single-tenant installation, there's no risk for now.

**Comment by DaanHoogland** [comment]
@MartinEmrich , one clarification please; you upgraded to 4.18 and then ran the `migrate-dynamicroles.py` script? Or did you run it on a 4.11.2 environment?

**Comment by MartinEmrich** [comment]
I ran the script before the upgrade (with the `-D` option, as I never edited my command.properties), but also multiple times after the upgrade in an attempt to get it to work.

**Comment by DaanHoogland** [comment]
ok, I'll try to reproduce in a lab env

**Comment by DaanHoogland** [comment]
Not sure if I reproduced your issue @MartinEmrich , but on installing a 4.11 env, `dynamic.apichecker.enabled` is `true` by default. When I set it to `false` login fails even as root-admin. setting it back to `true` login succeeds again. Can you check that?

**Comment by MartinEmrich** [comment]
@DaanHoogland Sorry, this is an internal production system, and the update to 4.18 is now >2 weeks ago, so restoring a backup to try again is not an option.

But that installation ist reeeeally old... Skimming thorugh my mail archive, it could possibly have started with ACS 4.5.2 or even older, and then upgraded to 4.6.0, 4.6.1, 4.7.0,  4.7.1, 4.8.0, 4.9.2.0,  4.11.2.0 and now finally 4.18.
Here and there, I had do use my own pre-release builds to get blocking bug fixes early, that might even have caused more database inconsistencies (even now, I have to run a homegrown 4.18.1.0 prerelease to get a bugfix early).

I guess the dynamic roles mode expects some database entries that a fresh 4.11.2.0 (and 4.18.0) installation provide, but which never happened during our eventful upgrade history.

If there is no readily apparent fix possible, I would totally understand if you would close this as "can't reproduce"... I just wonder what I should put into the database to get the "official out-of-the-box configuration".

**Comment by DaanHoogland** [comment]
I can give you a dump of the role and role permission tables of a stock lab environment, but other than that, yes, I think closing is the most expedient course of action ;)

**Comment by MartinEmrich** [comment]
If you already have one at hand, that would be great... Saves me from setting up a fresh VM.

Sounds like a plan!

**Comment by DaanHoogland** [comment]
[role.zip](https://github.com/apache/cloudstack/files/12723996/role.zip)
here you go. A bit inconvenient maybe for the uuids, (and the 'bla'-role) but easy to manipulate if you wish.
closing the issue.
