### ISSUE TITLE
cks: k8s cluster on vpc tier #7479 is fixed but still same error

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7950]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

UI

##### CLOUDSTACK VERSION

4.18

##### CONFIGURATION

Advance networking

##### OS / ENVIRONMENT

All on Ubuntu 22.04

##### SUMMARY

I am trying to craete a kubernetes cluster on VPC network. Main reason is that my kubernetes cluster pods should communicate with another datacenter VM's. So I had setup a VPC network and added site-to-site VPN to that VPC network. On trying to create a cluster it shows "does not support firewall that is required for Kubernetes cluster". When checking on git I can see Kubernetes Clusters cannot be deployed in VPCs #6723 ticket and it is closed with cks: k8s cluster on vpc tier #7479.

##### EXPECTED RESULTS

It should get created

##### ACTUAL RESULTS

It shows below error 
"Network ID: 580097a5-a2f9-4f8c-95c7-c77c10e2d9c4 does not support firewall that is required for Kubernetes cluster"

**Comment by shwstppr** [comment]
@Noelantogerorge did you try 4.18.1 RC or nightly build or build from source?

**Comment by Noelantogerorge** [comment]
@shwstppr No had taken from office repo as per the documentation. I haven't gone to build from source

**Comment by shwstppr** [comment]
@Noelantogerorge the PR was merged into the 4.18 branch. Changes are not available in the 4.18.0 release. Therefore, to test the changes you need to
- use a recent 4.18 nightly build
- use 4.18.1 RC build
- build 4.18 branch from source
- wait for 4.18.1 release

**Comment by weizhouapache** [comment]
+1 with @shwstppr said

@Noelantogerorge 
you can test the 4.18.1.0-RC3
https://download.cloudstack.org/testing/4.18.1.0-RC20230907T0850/

**Comment by aron-ac** [comment]
CKS still does not deploy into VPC in versions 4.18.1 or 4.19.1 - is there documentation on getting this to work? @shwstppr

**Comment by shwstppr** [comment]
@aron-ac what version are you using? Please share the error. Maybe open a new issue.
For documentation, as far as I remember there shouldn't be any extra steps.

**Comment by CodeBleu** [comment]
> [@aron-ac](https://github.com/aron-ac) what version are you using? Please share the error. Maybe open a new issue. For documentation, as far as I remember there shouldn't be any extra steps.

@shwstppr These are the errors:

CS version: `4.19.1.1`

- Failed to setup Kubernetes cluster : test-cmk, unable to setup network rules
- Public IP with ID: 1d7b55b9-afe4-4365-9131-7a22eb67029a linked to the Kubernetes cluster: test-cmk is not usable (Also, I found this [PR](https://github.com/apache/cloudstack/pull/9079) that should resolve this issue I believe)

**Comment by winterhazel** [comment]
@aron-ac @CodeBleu it seems that the error you're facing was fixed on 4.20.0+, but the fix was not backported to 4.19.x. You can try upgrading to 4.20, or waiting until a next 4.19 minor fixes it.

**Comment by CodeBleu** [comment]
> [@aron-ac](https://github.com/aron-ac) [@CodeBleu](https://github.com/CodeBleu) it seems that the error you're facing was fixed on 4.20.0+, but the fix was not backported to 4.19.x. You can try upgrading to 4.20, or waiting until a next 4.19 minor fixes it.

Please seem my comment here.
https://github.com/apache/cloudstack/pull/9079#discussion_r1958929330
