### ISSUE TITLE
Provide a copy option from the UI to copy the password of a vm 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#7960]
ISSUE TYPE

    Improvement request

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack 4.18

SUMMARY

Provide a copy option from the UI to copy the password of a vm 

Steps to reproduce the issue

1. Register a password-enabled template 

2. Deploy a vm 

![Password field](https://github.com/apache/cloudstack/assets/1401014/50f42d45-024a-4c2e-8e51-53dc241c23b1)

Currently, Cloudstack Ui supports copy options on many fields in the ui  (like instance uuid, template uuid)

![copy id ](https://github.com/apache/cloudstack/assets/1401014/d40a872a-c33d-4257-99c2-0ceee77bebb4)

It will be useful to the end-user to copy the password of a vm

**Comment by weizhouapache** [comment]
the password is sensitive data, it is displayed only once on the UI (in the notification area)

**Comment by kiranchavala** [comment]
@weizhouapache, 

I do not want the password field to be displayed permanently, It's fine to display it only once, 

Just an easy way to copy the value from the notification area with only one click instead copy the entire value

**Comment by weizhouapache** [comment]
> @weizhouapache,
> 
> I do not want the password field to be displayed permanently, It's fine to display it only once,
> 
> Just an easy way to copy the value from the notification area with only one click instead copy the entire value

@kiranchavala 
I can copy only the password
![image](https://github.com/apache/cloudstack/assets/57355700/7e008198-1e62-453d-82dc-8329c2967a5f)

I use Chrome btw.

**Comment by kiranchavala** [comment]
@weizhouapache just a minor thing like  provided a copy button for the password so that it can easily copied to a clipboard


![copy-password](https://github.com/apache/cloudstack/assets/1401014/bc3c73a3-72a6-4501-be58-65884019ac96)
![copy-password2](https://github.com/apache/cloudstack/assets/1401014/1a836d30-1cb3-404d-8772-a629ed120fcd)
![copy-password3](https://github.com/apache/cloudstack/assets/1401014/1b976720-52bb-4079-9b42-58a2522dbc66)

**Comment by weizhouapache** [comment]
@kiranchavala 
I got your point. These information are saved into cloudstack database, we can get them via cloudstack APIs.
but vm password is not ...

**Comment by shwstppr** [comment]
@kiranchavala @weizhouapache this might require some tweaking the notification UI element to show a button or hacker click. I can have a go at it

**Comment by weizhouapache** [comment]
> @kiranchavala @weizhouapache this might require some tweaking the notification UI element to show a button or hacker click. I can have a go at it

cool, thanks @shwstppr

**Comment by GutoVeronezi** [comment]
Good point, @kiranchavala, it will improve the UX.

Thanks for the willingness, @shwstppr.
