### ISSUE TITLE
Kubernetes cluster LB dosen't support UDP port 

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#7969]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Kubernetes UI

##### CLOUDSTACK VERSION

4.18

##### CONFIGURATION

Advance networking

##### OS / ENVIRONMENT

All on ubuntu 22.04

##### SUMMARY

When trying to create a LB in kubernetes cluster with UDP port it fails. 

##### STEPS TO REPRODUCE

Should be able to loadbalance UDP port also...

##### ACTUAL RESULTS

Getting error like LB service cannot support this rule

![image](https://github.com/apache/cloudstack/assets/126588356/0a759dd1-d09c-44ef-8d38-13cb30651908)

**Comment by rajujith** [comment]
@Noelantogerorge  this is possibly due to the known limitation where HAproxy doesn't support UDP. https://github.com/apache/cloudstack/pull/4501
