### ISSUE TITLE
4.18.1 cannot access snapshot in GUI

### ISSUE THREAD

**Issue by Chih80** [apache/cloudstack#7994]
After updating from 4.18.0 to 4.18.1, All admin accounts are unable to access and list snapshots in the gui.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
UI - snapshot
~~~

~~~

##### CLOUDSTACK VERSION
4.18.1

~~~

~~~

##### CONFIGURATION
advance networking

##### OS / ENVIRONMENT
management server/secondary/mysql on ubuntu 22.04

##### SUMMARY

when trying to access snapshot in the gui, nothing gets display other than a red X at top of page.

##### STEPS TO REPRODUCE
UI, click storage -> snapshots

~~~

~~~

##### EXPECTED RESULTS

list snapshots
~~~

~~~

##### ACTUAL RESULTS

noting gets listed but an error symbol.

From the mgm log:
2023-09-24 02:31:41,015 ERROR [c.c.a.ApiServer] (qtp9190301-17:ctx-929f6bb9 ctx-afcecb42) (logid:f3a11c73) unhandled exception executing api command: [Ljava.lang.String;@6a2520b5
java.lang.NullPointerException

~~~

~~~
![Screenshot 2023-09-24 001337](https://github.com/apache/cloudstack/assets/141194587/c6efd911-c646-449c-a647-67d219741ee4)

**Comment by DaanHoogland** [comment]
I can reproduce your issue @Chih80 , I'll have a look for a fix.

**Comment by DaanHoogland** [comment]
@Chih80 , can you look in the database if the snapshots still exist? In my case they dissapeared. I created a new snapshot and this show as expected.

**Comment by Chih80** [comment]
yes the snapshots still exist. In my case for what ever reason, their were two accounts with the same name when I checked mysql db. One being user and one being admin, that user account was never made with the admin role so how that came up in the db is a mystery. The UI only show the correct user account. I updated the user account with the admin role to user role and a min later, everything started working. Admins and users with admin roles can not access the snapshots in the UI. The only thing is, now I still have 2 user accounts with the same name.

**Comment by DaanHoogland** [comment]
So both accounts are in the same domain @Chih80 ? if so, a workaround would be renaming one.

You can use for instance cloudmonkey for that.  see https://cloudstack.apache.org/api/apidocs-4.18/apis/updateAccount.html

**Comment by DaanHoogland** [comment]
@Chih80 is this still an issue for you, or can we close?

**Comment by rohityadavcloud** [comment]
Hi @Chih80 it appears you're hitting some bug, could you check and share the management server logs. For example, you can set the page size to 1 in the URL and try to go through the page -> you'll hit some API for some snapshot where the NPE is happening - chances are something in the DB is wrong for the specific snapshot.

**Comment by Chih80** [comment]
This issue was resolve. After checking the db, I saw that a single user was also assign as admin, basically one account set as a user and also an admin. I have no idea how that happened. After manually deleting the admin assignment to the account, I was able to access snapshots.

**Comment by Chih80** [comment]
This issue was resolve. After checking the db, I saw that a single user was also assign as admin, basically one account set as a user and also an admin. I have no idea how that happened. After manually deleting the admin assignment to the account, I was able to access snapshots.
