### ISSUE TITLE
[UI] Vmware deploy-as-is instances are not receiving the properties values

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#7998]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.17, 4.18
~~~

##### CONFIGURATION
Register a VMware vApp template selecting the option 'Read settings from OVA'. Deploy VM and input property values

##### OS / ENVIRONMENT
Vmware vApps containing properties

##### SUMMARY
vApp properties values are not passed to the deployVirtualMachine API after the Vue3 upgrade on: https://github.com/apache/cloudstack/pull/5151

##### STEPS TO REPRODUCE
~~~
- Register a vApp template containing vApp properties on CloudStack, selecting the 'Read setting from OVA' option
- On the Deploy Instance wizard, select the template and complete the values for the vApp properties
- Deploy VM 
~~~

##### EXPECTED RESULTS
~~~
The deployVirtualMachine API includes the properties set
~~~

![image](https://github.com/apache/cloudstack/assets/5295080/bb62e1b0-6021-4ef6-8a63-f3966c1d61db)

##### ACTUAL RESULTS
~~~
The properties parameter is not set for the deployVirtualMachine API
~~~

![image](https://github.com/apache/cloudstack/assets/5295080/edec9a08-a997-4527-939f-6c0ffc016336)

**Comment by shwstppr** [comment]
Fixed by #8072
