### ISSUE TITLE
Make the number of characters for the randomly generated vm pasword configurable.

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8010]
**ISSUE TYPE**

* Improvement request

**COMPONENT NAME**

Compnent: Management server

**CLOUDSTACK VERSION**

Cloudstack version 4.18

**SUMMARY**

Make the number of characters for the randomly generated vm pasword configurable.

Currently, by default  Cloudstack generates a random 6 character password

Can we have a global setting to specify the number of characters required for the randomly generated vm password

Similar to the global settings related to user password specifications

Having more characters may also increase the security or make it align with the organization policies

**Steps to reproduce the issue**

1. Register a password-enabled template

2. Deploy a virtual machine 

3. The random password generated is always of 6 characters 

Screenshot

By default, 6 characters are generated for a vm

<img width="1152" alt="Screenshot 2023-09-26 at 5 54 23 PM" src="https://github.com/apache/cloudstack/assets/1401014/cde46a0d-eead-47b3-aef3-4caa65003efb">

<img width="1115" alt="Screenshot 2023-09-27 at 2 47 43 PM" src="https://github.com/apache/cloudstack/assets/1401014/5b9cd041-3b3a-449c-8ee3-51d6f6c2851a">

**Expected behavior**

Admin user should be able to configure the number of characters for the randomly generated vm password

**Actual behavior**

Currently admin user is not able to configure the number of character for the randomly generated vm password

**Comment by GutoVeronezi** [comment]
@kiranchavala, we already have the configuration `vm.password.length`; could you try it?

**Comment by isupersky** [comment]
@kiranchavala Can you please elaborate more on the requirements.

**Comment by sureshanaparti** [comment]
@kiranchavala The length of randomly generated vm password can be controlled through _vm.password.length_ config, any other requirement here?

**Comment by kiranchavala** [comment]
Thanks @sureshanaparti @GutoVeronezi  global setting "vm.password.length"  solves the issue 

But I wanted the vmpassword configuration to be more granular similar  to user/account password global setting configuration 

Will close the issue as there is similar PR #6861 open
