### ISSUE TITLE
Kubernetes ISO

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#8013]
ISSUE TYPE
My Issue

COMPONENT NAME
Kubernetes ISO

CLOUDSTACK VERSION
4.17.2.0 Stable Latest Version

CONFIGURATION
Adding ISO

OS / ENVIRONMENT
Ubuntu 20.04

SUMMARY
I Uploading kubernetes ISO Image with 2 Following methods:
1- Download From http://download.cloudstack.org/cks/ "1.27.3"
2- Creating That With create-kubernetes-binaries-iso.sh script 
but in both cases instead Of "Ready" State Both Of Them Stuck in "Allocated" State 

STEPS TO REPRODUCE

EXPECTED RESULTS
I want its state be Ready for Creating cluster in Compute TAB

ACTUAL RESULTS
it stay in Allocated State and i cant use it

**Comment by DaanHoogland** [comment]
@ahmadamirahmadi007 , can you try `http://download.cloudstack.org/cks/setup-1.27.3.iso` as url?

**Comment by ahmadamirahmadi007** [comment]
Thank you all. my problem is solved.
