### ISSUE TITLE
Cloudstack Debug logs throwing the IPMI admin username and password in plaintext on the cloudstack-management logs

### ISSUE THREAD

**Issue by nsaikrishna15** [apache/cloudstack#8014]
Cloudstack Debug logs throwing the IPMI admin username and password in plaintext on the cloudstack-management logs. seems like a bug. 

we are using 4.17.2 cloudstack version.

**Comment by harikrishna-patnala** [comment]
@nsaikrishna15 can you please share me the masked snippet of the logs where it is logging the username and password.

**Comment by sureshanaparti** [comment]
Hi @nsaikrishna15 Is it the same issue as this one - https://github.com/apache/cloudstack/issues/8526, can you share the log snippet. Thanks.

**Comment by DaanHoogland** [comment]
fixed by #9126
