### ISSUE TITLE
Cloudstack vm-snapshot is pausing the vm in the kvm. how to avoid this?

### ISSUE THREAD

**Issue by nsaikrishna15** [apache/cloudstack#8015]
Cloudstack vm-snapshot is pausing the vm in the kvm. how to avoid this? even if we not enable the memory snapshot option still it is pausing. is there any alternative for this so that we dont need to pause the vm. 

And how does the volume backup work? if we have multiple volumes for the vm's how to take backup and how to restore ?

**Comment by DaanHoogland** [comment]
@nsaikrishna15 , I think this is a libvirt limitation and we'll have to live with for now?

**Comment by rajujith** [comment]
@nsaikrishna15  this issue could be avoided if you use 'qemu-kvm-ev' RPMs on the KVM.

**Comment by nsaikrishna15** [comment]
Got to know that it's a limitation from KVM s We stopped relying on the vm snapshots and using storage level snapshots for the backup and restore. Thanks for the suggestions will try the new versions in next cycles.

**Comment by rohityadavcloud** [comment]
Worth exploring some options cc @sureshanaparti @DaanHoogland @weizhouapache

**Comment by nsaikrishna15** [comment]
Will upgrade the clusters and check it.
