### ISSUE TITLE
Stablise 4.19/main branch Github Actions and smoketests

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#8016]
Recently several Github Actions based simulator/smoketests are failing and smoketests (test matrix) need to be stablised for main branch. Without this it would be difficult to know if failures are due to the PR or due to issues in main or the CI/CD system.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
main/4.19, CI/CD
~~~

**Comment by harikrishna-patnala** [comment]
Recent results seems to be fine, but 1 or 2 test failures especially in test_kubernetes_clusters.py. Previous failures are mainly due to capacity.

I'm checking those failures in test_kubernetes_clusters.py (test_08_upgrade_kubernetes_ha_cluster)

**Comment by rohityadavcloud** [comment]
Happening again, jfyi @shwstppr @harikrishna-patnala @DaanHoogland

**Comment by shwstppr** [comment]
Other than intermittent k8s test failures, I'm also seeing codecov failures in Simulator CI run in different PRs,
https://github.com/apache/cloudstack/actions/runs/6559838081/job/17816236724?pr=8116

Do we need any changes for this? @vishesh92 @rohityadavcloud @harikrishna-patnala @DaanHoogland 
https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

**Comment by DaanHoogland** [comment]
> Other than intermittent k8s test failures, I'm also seeing codecov failures in Simulator CI run in different PRs, https://github.com/apache/cloudstack/actions/runs/6559838081/job/17816236724?pr=8116
> 
> Do we need any changes for this? @vishesh92 @rohityadavcloud @harikrishna-patnala @DaanHoogland https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

By the looks of this comment it seems to be another api rate limiting issue.  If we already use a codecov upload token there is nothing more we can do. (will have to check that)
