### ISSUE TITLE
Missing event after ha restart of VM

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#8021]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### SUMMARY

When using a ha enabled offering and a VM was restarted because of this, no entry is showing in events.

##### STEPS TO REPRODUCE

~~~
1) Create a VM with ha enabled offering
2) Destroy the VM on the hypervisor (in KVM via virsh destroy <id>)
3) Wait until CS is restarting the VM
4) Take a look at Events tab of VM and/or Events Tab of main menu
~~~

##### EXPECTED RESULTS

~~~
A new entry should be added to the events history because of ha restart
~~~

##### ACTUAL RESULTS

~~~
No entry is made to the events history
~~~

**Comment by sureshanaparti** [comment]
Fixed in #9202
