### ISSUE TITLE
Issue with upgrading Oracle Linux host

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#8026]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Core
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### OS / ENVIRONMENT

Master server OS: CentOS 7
Cluster hosts OS: Oracle Linux 8.8

##### SUMMARY

In a cluster composed of only Oracle Linux 8.8 servers, when upgrading the agent on host from version 4.17.2.0 to version 4.18.0.0 the agent keep disconnecting from master server with error:
2023-09-30 11:57:15,462 DEBUG [c.c.a.m.AgentManagerImpl] (AgentConnectTaskPool-341:ctx-ad1cb9b6) (logid:ab135acf) Failed to handle host connection: 
java.lang.IllegalArgumentException: Can't add host: 192.168.9.61 with hostOS: Oracle Linux Server into a cluster,in which there are Red hosts added

There seems to be an issue with some scripts that now is reading "too much" from the OS version
I'll attach also logs from the agent and libvirt

##### STEPS TO REPRODUCE

~~~
Upgrade a Oracle Linux host in a cluster from version 4.17.2.0 to version 4.180.0.0
~~~

##### EXPECTED RESULTS

~~~
The agent works without any issue.
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by cdfgallo** [comment]
[agent.log](https://github.com/apache/cloudstack/files/12774868/agent.log)
[libvirt.log](https://github.com/apache/cloudstack/files/12774869/libvirt.log)

**Comment by DaanHoogland** [comment]
@cdfgallo two questions:
1. your output says `to version 4.180.0.0` is that a c&p error? there is an extra `0` in there.
2. can you try 4.18.1 ? #7616 is fixed and seems the same issue you are having.

**Comment by cdfgallo** [comment]
@DaanHoogland my answers:
1. that's a typo, my bad. The version is 4.18.0.0
2. my issue looks different from the #7616 . In Oracle Linux the new "first word" with the new agent is Oracle, while with version 4.17.2 was Red

**Comment by DaanHoogland** [comment]
> 2\. my issue looks different from the #7616 . In Oracle Linux the new "first word" with the new agent is Oracle, while with version 4.17.2 was Red

ok, but then I think the solution for you is to set the Host OS to "Oracle Linux" for your hosts. I have no idea why it would be starting with "Red". 

can you probide the contents of `/etc/redhat-release` of one of the failing hosts here?

**Comment by cdfgallo** [comment]
> ok, but then I think the solution for you is to set the Host OS to "Oracle Linux" for your hosts. I have no idea why it would be starting with "Red".

How can I do this in CS?

> 
> can you probide the contents of `/etc/redhat-release` of one of the failing hosts here?

of course. It's "Red Hat Enterprise Linux release 8.8"

**Comment by cdfgallo** [comment]
> > > ok, but then I think the solution for you is to set the Host OS to "Oracle Linux" for your hosts. I have no idea why it would be starting with "Red".
> > 
> > 
> > How can I do this in CS?
> 
> not, you need to either upgrade to 4.18.1 or hack the DB.

You mean on the host_detail table?


> 
> This means that the hosts should be "Red Hat Enterprise Linux" (not "Oracle ...")

But when I upgrade the agent to version 4.18.0.0 I get the error "Can't add host: 192.168.9.61 with hostOS: Oracle Linux Server into a cluster,in which there are Red hosts added". Is there something changed from version 4.17.2?

**Comment by DaanHoogland** [comment]
> > not, you need to either upgrade to 4.18.1 or hack the DB.
> 
> You mean on the host_detail table?

yes, the detail with name Host.OS

> > This means that the hosts should be "Red Hat Enterprise Linux" (not "Oracle ...")
> 
> But when I upgrade the agent to version 4.18.0.0 I get the error "Can't add host: 192.168.9.61 with hostOS: Oracle Linux Server into a cluster,in which there are Red hosts added". Is there something changed from version 4.17.2?

Do they exist with detail { name: "Host.OS", value: "Red" } in the cluster you are trying to add the hosts to now?

the string is gotten from the file `/etc/redhat-release`, and this has not changed. What has changed is that it now gets the full string before the word "reelase".

**Comment by cdfgallo** [comment]
> > > not, you need to either upgrade to 4.18.1 or hack the DB.
> > 
> > 
> > You mean on the host_detail table?
> 
> yes, the detail with name Host.OS
> 
> > > This means that the hosts should be "Red Hat Enterprise Linux" (not "Oracle ...")
> > 
> > 
> > But when I upgrade the agent to version 4.18.0.0 I get the error "Can't add host: 192.168.9.61 with hostOS: Oracle Linux Server into a cluster,in which there are Red hosts added". Is there something changed from version 4.17.2?
> 
> Do they exist with detail { name: "Host.OS", value: "Red" } in the cluster you are trying to add the hosts to now?
> 
> the string is gotten from the file `/etc/redhat-release`, and this has not changed. What has changed is that it now gets the full string before the word "release".

Yes, indeed. They are present with "Host.id" = "Red".
Until we will proceed with the update to version 4.18.1.0, do you think that using the agent for version 4.17.2 on these hosts can cause any issue?

**Comment by DaanHoogland** [comment]
> > Do they exist with detail { name: "Host.OS", value: "Red" } in the cluster you are trying to add the hosts to now?
> > the string is gotten from the file `/etc/redhat-release`, and this has not changed. What has changed is that it now gets the full string before the word "release".
> 
> Yes, indeed. They are present with "Host.id" = "Red". Until we will proceed with the update to version 4.18.1.0, do you think that using the agent for version 4.17.2 on these hosts can cause any issue?

It may not, but especially in new functionality it may. So if you encounter any problems you may update the entries named "Host.OS" in the host details to the full string preceding the work 'release' in the file '/etc/redhat-release' .

All that said, I would strongly advice upgrading to 4.18.1. This is a fix release with no new functionality.

**Comment by mlsorensen** [comment]
Here is the previous report: https://github.com/apache/cloudstack/issues/7742

I think it was mentioned that there should be an upgrade process documented to workaround?

**Comment by cdfgallo** [comment]
> @cdfgallo can you try ACS 4.18.1.0 ? Are there any other hosts that are no exactly the same Linux EL8 distro/build? A workaround is to set the Host.OS of the first non-removed host in the cluster same as the Host.OS it detects for the host you're trying to add.

We will upgrade to 4.18.1 and I hope this will get sorted out.
Thank you!
