### ISSUE TITLE
ISO.CREATE event is not present for Kubernetes ISO registration 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8043]
**ISSUE TYPE**

Bug report

**COMPONENT NAME**

Component: UI

**CLOUDSTACK VERSION**

Cloudstack version 4.18

**SUMMARY**

ISO.CREATE event is not present for Kubernetes ISO registration 

**Steps to reproduce the issue**

Register a kubernetes iso

1. Navigate to 

Image> Kubernetes ISO > Add Kubernetes Iso
 
![Screenshot 2023-10-05 at 11 16 15 AM](https://github.com/apache/cloudstack/assets/1401014/d0fe4f42-4dbf-41c9-ba18-022e12a956d0)

2. Navigate to 

Image > ISo's > Events

![Screenshot 2023-10-05 at 11 22 00 AM](https://github.com/apache/cloudstack/assets/1401014/8d973547-f2b6-4580-9ece-6d585f868b91)

**The iso create event is present in the event section only**

![Screenshot 2023-10-05 at 11 14 35 AM](https://github.com/apache/cloudstack/assets/1401014/d789d74c-66c3-432c-ba5c-eeab1f2029be)

**Expected behavior**

ISO.CREATE event should be present for the kubernetes iso 

**Actual behavior**

ISO.CREATE event should be present for the kubernetes iso

**Comment by rohityadavcloud** [comment]
Is there an event under the actual ISO @kiranchavala ?

**Comment by kiranchavala** [comment]
@rohityadavcloud there is a event present  for normal iso's 
![Screenshot 2023-10-31 at 5 54 31 PM](https://github.com/apache/cloudstack/assets/1401014/5f4a8b42-6fc7-49e8-a842-e217d00f6e89)

**Comment by shwstppr** [comment]
@kiranchavala @rohityadavcloud Current design allows only one resource to be linked with an event. Here the actual ISO is linked as with any ISO registration. Also, currently, we do not have any events for KUBERNETES as such so would it be a better idea to add new event types?

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9070
