### ISSUE TITLE
Vm deployment wizard should mention "My iso's

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8051]
ISSUE TYPE

* Bug/Improvement request

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18

**SUMMARY**

Vm deployment wizard should mention "My iso's

**Steps to reproduce the issue**

1. Register a ISo 

2. Launch a vm deployment wizard

3. Select ISO tab

The Tab should contain "My ISo's currently its displaying "My templates"

![Myiso's](https://github.com/apache/cloudstack/assets/1401014/eb07f04f-05fd-4958-a283-f636ca2b3762)

**Expected behavior**

The form should contain "My ISo's"

**Actual behavior**

The form is saying "My Templates"

**Comment by DaanHoogland** [comment]
fixed by #8075
