### ISSUE TITLE
Have a primary /secondary storage filter  for Storage and Image tab sections

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8053]
ISSUE TYPE

* Improvement request

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18

**SUMMARY**

Have a primary /secondary storage filter  for Storage and Image tab sections

**Steps to reproduce the issue**

1. Create a template, ISO , volume , Snapshpts 
  

We could add a filter for the following views of Template,ISO , Volumes, Snapshots

So that admin can easily filter out them based on the Storages

![Volumes](https://github.com/apache/cloudstack/assets/1401014/0ab40fb1-9454-49fa-a501-c0b3e25ecb1e)

![snapshots](https://github.com/apache/cloudstack/assets/1401014/e0c6b905-e449-4c67-8837-93df9fa04a39)
![Templates](https://github.com/apache/cloudstack/assets/1401014/c835b885-3883-4c0e-ac6a-975c519dda60)
![ISo](https://github.com/apache/cloudstack/assets/1401014/b1684c45-7a22-4563-85f9-d3d35e1c5141)

Also the NEW PR #7949 improved the api responses 

https://github.com/apache/cloudstack/pull/7949

The volumes, Snapshots, templates /Iso can be easily filtered out based on their storages  and also the api responses 

https://cloudstack.apache.org/api/apidocs-4.18/apis/listVolumes.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listSnapshots.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listTemplates.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listIsos.html

**Expected behavior**

End user should be to filter out the resources based on the primary and secondary storages 

**Actual behavior**

End user is not able to filter out the resources based on the primary and secondary storages

**Comment by shwstppr** [comment]
Only root admin will be able to use such filters. Is this already added in #7949 @kiranchavala @vishesh92?

**Comment by kiranchavala** [comment]
@shwstppr Yes, it is already present in 7949 we can close this issue

**Comment by shwstppr** [comment]
Addressed by #7949
