### ISSUE TITLE
Storage capacity check does not consider the VM snapshot of DATADISK

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8054]
as title

steps to reproduce the issue
1. create vm with root and data disk
2. check storage pool usage
3. create vm snapshot
4. check storage pool usage again

expected: both root and data disk size are considered
actual: only root disk size is considered

it seems to be caused by the line `        sc.setParameters("vType", Volume.Type.ROOT.toString());` in code
```
@Override
    public long getVMSnapshotSizeByPool(long poolId) {
        SearchCriteria<SumCount> sc = TotalVMSnapshotSizeByPoolSearch.create();
        sc.setParameters("poolId", poolId);
        sc.setParameters("state", State.Destroy);
        sc.setParameters("vType", Volume.Type.ROOT.toString());
        List<SumCount> results = customSearch(sc, null);
        if (results != null) {
            return results.get(0).sum;
        } else {
            return 0;
        }
    }
```

https://github.com/apache/cloudstack/blob/e333f2705aa39007683fca83edac704410e72ca1/engine/schema/src/main/java/com/cloud/storage/dao/VolumeDaoImpl.java#L664
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
fixed in 8101
