### ISSUE TITLE
Events tab  is missing from the following pages 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8063]
ISSUE TYPE

* Bug/Improvement request

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18

**SUMMARY**

The events tab is missing from the following pages 

**Roles Related events can be added** 

CMK> list eventtypes  filter=name | grep ROLE
      "name": "ROLE.CREATE"
      "name": "ROLE.UPDATE"
      "name": "ROLE.DELETE"
      "name": "ROLE.IMPORT"
      "name": "ROLE.PERMISSION.CREATE"
      "name": "ROLE.PERMISSION.UPDATE"
      "name": "ROLE.PERMISSION.DELETE"
      
![Roles_events](https://github.com/apache/cloudstack/assets/1401014/b092db9c-736c-4c50-a152-1e74f4430182)

**Project roles-related events are not generated in the event tab of project**

CMK> list eventtypes  filter=name | grep PROJECT
      "name": "PROJECT.ROLE.CREATE"
      "name": "PROJECT.ROLE.UPDATE"
      "name": "PROJECT.ROLE.DELETE"
      "name": "PROJECT.ROLE.PERMISSION.CREATE"
      "name": "PROJECT.ROLE.PERMISSION.UPDATE"
      "name": "PROJECT.ROLE.PERMISSION.DELETE"
      
      
![projectrole1](https://github.com/apache/cloudstack/assets/1401014/91b62f44-08ad-44d7-a7de-c8ac09fdba92)

      
![Projectrole2](https://github.com/apache/cloudstack/assets/1401014/bfdb7abd-47a7-44c1-8274-21b965abf4af)

**Infrastructure > Clusters**

CMK > list eventtypes  filter=name | grep CLUSTER
      "name": "CLUSTER.ROLLING.MAINTENANCE"
      
CLUSTER.CREATE and CLUSTER.DELETE can be added to the events      
      
![Cluster](https://github.com/apache/cloudstack/assets/1401014/d8bdf59c-8a57-4782-b774-f61d23dc0423)

**Infrastructure > Hosts**

CMK> list eventtypes  filter=name | grep HOST
      "name": "HOST.RECONNECT"
      "name": "HOST.DECLARE.DEGRADED"
      "name": "HOST.CANCEL.DEGRADED"
      "name": "HOST.OOBM.ENABLE"
      "name": "HOST.OOBM.DISABLE"
      "name": "HOST.OOBM.CONFIGURE"
      "name": "HOST.OOBM.ACTION"
      "name": "HOST.OOBM.CHANGEPASSWORD"
      "name": "HOST.OOBM.POWERSTATE.TRANSITION"
      "name": "HOST.RESERVATION.RELEASE"
      "name": "HOST.ROLLING.MAINTENANCE"

![Host](https://github.com/apache/cloudstack/assets/1401014/3187f29b-9be5-4240-ab2d-115ea39dc688)

**Infrastructure > InternalLB**

![InternalLb](https://github.com/apache/cloudstack/assets/1401014/728ed4eb-0c8e-4966-9bec-70d23412265d)

(CMK) list eventtypes  filter=name | grep INTERNAL
      "name": "INTERNALLBVM.START"
      "name": "INTERNALLBVM.STOP"

**Service offerings > Compute offerings >** 

(CMK) 🐱 > list eventtypes  filter=name | grep SERVICE

      "name": "SERVICE.OFFERING.CREATE"
      "name": "SERVICE.OFFERING.EDIT"
      "name": "SERVICE.OFFERING.DELETE"
      
![compute offerings](https://github.com/apache/cloudstack/assets/1401014/54619199-faa8-44d6-85f4-462a529b8108)

**Service offerings > Disk offerings >** 

CMK> list eventtypes  filter=name | grep DISK
         "name": "DISK.OFFERING.CREATE"
      "name": "DISK.OFFERING.EDIT"
      "name": "DISK.OFFERING.DELETE"
      
![Diskofferings](https://github.com/apache/cloudstack/assets/1401014/bd3bd844-bac9-4759-bd78-661457a496c6)

**Service offerings > Network Offerings >**

(CMK) > list eventtypes  filter=name | grep NETWORK

      "name": "NETWORK.OFFERING.CREATE"
      "name": "NETWORK.OFFERING.ASSIGN"
      "name": "NETWORK.OFFERING.EDIT"
      "name": "NETWORK.OFFERING.REMOVE"
      "name": "NETWORK.OFFERING.DELETE"
      
![network offerings](https://github.com/apache/cloudstack/assets/1401014/089428f7-e295-4106-9a16-66b0a8c0c077)

      
**Service offerings > Vpc Offerings >** 

CMK> list eventtypes  filter=name | grep VPC
      "name": "VPC.OFFERING.CREATE"
      "name": "VPC.OFFERING.UPDATE"
      "name": "VPC.OFFERING.DELETE"
      
![VPCofferings](https://github.com/apache/cloudstack/assets/1401014/d32124cb-4930-4d68-ad5a-b9b8e88cc082)

**Comment by shwstppr** [comment]
@kiranchavala are these in addition to https://github.com/apache/cloudstack/issues/7251?

**Comment by kiranchavala** [comment]
@shwstppr yes, except for the service offerings section  they are in addition to #7251

I had forgotten that I had created it earlier 

Do you want me to close the issue and it to #7251
