### ISSUE TITLE
Filter icon is missing from the service offerings

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8064]
ISSUE TYPE

* Bug/Improvement request

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18

**SUMMARY**

The filter icon  is missing from the service offerings

We can add a filter tab with the following paramters 

Name,Zone.Domain,Account,State,Tags ,type

![filter-compute](https://github.com/apache/cloudstack/assets/1401014/e597b608-a405-4fb7-8a9d-d9ab38ce24b9)
![filter-disk](https://github.com/apache/cloudstack/assets/1401014/5b9fbdbc-233b-4429-b9b3-4f256e1d6d5d)
![filter-network](https://github.com/apache/cloudstack/assets/1401014/27ed02a4-9fb4-4bf1-bf0a-7d225e55d90f)
![filter-system](https://github.com/apache/cloudstack/assets/1401014/69b5dfa5-a706-44ec-a66b-68f690f1af03)
![filter-vpc](https://github.com/apache/cloudstack/assets/1401014/9d6e0462-5d4a-4e31-851c-fff0706d6340)

The necessary api calls for the filter are 

https://cloudstack.apache.org/api/apidocs-4.18/apis/listServiceOfferings.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listDiskOfferings.html
https://cloudstack.apache.org/api/apidocs-4.18/apis/listNetworkOfferings.html

**Comment by harikrishna-patnala** [comment]
This was fixed in all the offering pages with the PR https://github.com/apache/cloudstack/pull/9068 in 4.19.1 release

![Screenshot 2024-08-19 at 5 59 18 PM](https://github.com/user-attachments/assets/2161f62b-95d1-41fa-9872-c2e33c1e551a)
