### ISSUE TITLE
The physical size for volumes is always shown as zero, when metrics is enabled

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8073]
ISSUE TYPE

* Bug

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18.1, 4.19

**SUMMARY**

The physical size for volumes is always shown as zero, when metrics is enabled

**Steps to reproduce the issue**

1. Create a 4.18.1 or 4.19 Cloudstack env

2. Create some root and data volumes

3. Enable the metric option 

Screenshots 

**In 4.18**

The physical size is correctly shown

![volume-metrics-4 18](https://github.com/apache/cloudstack/assets/1401014/0be353ba-be07-476a-9cdc-91f4c38832be)

**In 4.18.1**

The physical size is always zero

![volume-metrics-4 18 1](https://github.com/apache/cloudstack/assets/1401014/83979bac-b461-4a3d-99a3-14f57e7a8200)

**Expected behavior**

The correct physical size of the volume should be displayed 

**Actual behavior**

The physical size of the volume is shown as zero

**Comment by shwstppr** [comment]
Fixed by #8119
