### ISSUE TITLE
UI: only the previous vm/template setting is present in the dropdown when add a new setting

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8074]
When add a setting to a template or vm, if try to add another setting, only the previous setting is present in the dropdown

This is a very common UI bug, for example when add settings to template

![image](https://github.com/apache/cloudstack/assets/57355700/3d297a41-0dcc-4e6f-902a-f4bfceb1e1f7)

for add setting to vm

![image](https://github.com/apache/cloudstack/assets/57355700/bfddfc8f-e685-40f7-b553-2328cc91b4ba)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@weizhouapache dropdown is just for suggestion, user can still add a new custom setting
https://github.com/apache/cloudstack/assets/153340/e4ad7b70-d14c-4c30-8253-4144821f5bdf

**Comment by DaanHoogland** [comment]
I think this is not a bug, but we could reconsider how this suggestion is choosen and whether more options should be given.

**Comment by weizhouapache** [comment]
thanks @shwstppr for the video. yes, it works

@DaanHoogland 
my expectation is, when I add a setting (key/value) and click the key field again, it should list all suggestions (not only the previous key). Based on it, I think it is a minor UI bug.

**Comment by DaanHoogland** [comment]
> when I add a setting (key/value) and click the key field again, it should list all suggestions (not only the previous key).

makes sense
