### ISSUE TITLE
Creating Volume Snapshot from VM Snapshot can fail on KVM with Local/NFS Storage

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#8078]
Creating Volume Snapshot from VM Snapshot can fail on KVM with Local/NFS Storage:

1. Enable global setting to have vmsnapshot use storage, also enable snapshot feature for KVM
2. Create/take VM snapshot of a VM with root and data disk attached and qemu-guest-agent installed
3. Now go to the VM snapshot, and create (volume) snapshot from the VM Snapshot which may fail

This issue needs reproduction and may be closed if it's found to work. In my test env, I had a local storage enabled adv KVM zone that used Ubuntu 22.04 LTS/KVM hosts.

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
KVM, VM Snapshots
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

**Comment by rohityadavcloud** [comment]
In my env this is consistently failing:
```
Failed to create snapshot due to an internal error creating snapshot from vm snapshot8
```

**Comment by rohityadavcloud** [comment]
cc @shwstppr - I'm not sure if this is a severe issue though, may be done even in 4.19.1

**Comment by rohityadavcloud** [comment]
cc @GutoVeronezi @slavkap if you know of a easy/quick fix to assist on this issue. Thanks.

**Comment by slavkap** [comment]
Hey @rohityadavcloud, probably this is not the perfect fix. The snapshot will be created only on secondary storage. The VM snapshots without memory are volume snapshots. That's why there is no need to copy the data twice on primary storage.

**Comment by rohityadavcloud** [comment]
Thanks @slavkap I agree, they may be copied to secondary storage directly. Creating volume snapshot from disk-only VM snapshot may still be useful to create backups or create templates from such volume-snapshots.

**Comment by shwstppr** [comment]
@rohityadavcloud @slavkap do we need anything more here or can it be closed?
