### ISSUE TITLE
Bulk deletion of templates  from multiple zones is not working

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8083]
ISSUE TYPE

* Bug

**COMPONENT NAME**

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18.1

**SUMMARY**

Bulk deletion of templates from multiple zones is not working

**Steps to reproduce the issue**

1. Create 2 zones Cloudstack environment

2. Register a template/ISO in alll zone 

3. Select  the Bulk delete template  option and select both the zone

The template gets deleted in only one zone 

<img width="1168" alt="Screenshot 2023-10-12 at 4 20 30 PM" src="https://github.com/apache/cloudstack/assets/1401014/30a0904a-90e7-4857-92ea-2104958e4aeb">

https://cloudstack.apache.org/api/apidocs-4.18/apis/deleteTemplate.html

Only one zone id is getting passed in the api call 

http://10.0.34.201:8080/client/api/?id=6897f3b3-9030-45c7-bebe-216e1c799393&forced=true&zoneid=90085d02-1fa4-4511-838f-c431ee7e2b27&command=deleteTemplate&response=json

The issue is not observed for the bulk deletion of  ISO's 

**Expected behavior**

The template should get deleted in both the zones

**Actual behavior**

The template should is getting deleted in a single zone

**Comment by shwstppr** [comment]
Fixed by #8118
