### ISSUE TITLE
add domain path to all entities

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8086]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

as agreed in https://github.com/apache/cloudstack/pull/7386#issuecomment-1759616648, we need to make the enhancement by @pierrelefevre more generic.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
localcloud) 🐱 > list networks filter=name,type,domainpath
{
  "count": 2,
  "network": [
    {
      "domainpath": "ROOT",
      "name": "bla",
      "type": "Isolated"
    },
    {
      "domainpath": "ROOT",
      "name": "sla",
      "type": "Shared"
    }
  ]
}
~~~

##### ACTUAL RESULTS

~~~
localcloud) 🐱 > list networks filter=name,type,domainpath
{
  "count": 2,
  "network": [
    {
      "name": "bla",
      "type": "Isolated"
    },
    {
      "domainpath": "ROOT",
      "name": "sla",
      "type": "Shared"
    }
  ]
}
~~~

**Comment by rohityadavcloud** [comment]
@DaanHoogland is the fix required that we always send the domain path for all networks? Concern - could it slow down listing networks at scale?

**Comment by DaanHoogland** [comment]
> @DaanHoogland is the fix required that we always send the domain path for all networks? Concern - could it slow down listing networks at scale?

@rohityadavcloud , we could think of making this an option on the call, if it really is a performance hog. I have not considdered that, just the automation consequence as described by the refenced [PR (comment)](https://github.com/apache/cloudstack/pull/7386#issuecomment-1759616648) and the original issue #7363. I am not sure but I think the issue was with automation using terraform.

**Comment by rohityadavcloud** [comment]
Thanks @DaanHoogland let me figure out and raise a PR. (related - the list networks API right now, works by listing all networks and then return a page out of it - pagination isn't implemented in it properly; likely @abh1sar 's PR may fix it)
