### ISSUE TITLE
label for copy password missing

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8092]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

![image](https://github.com/apache/cloudstack/assets/2486961/00742e2a-867b-43e8-8199-8d449c43f390)

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by harikrishna-patnala** [comment]
I can see the label @DaanHoogland both on VM creation and reset password. May be cache issue in your env!

![image](https://github.com/apache/cloudstack/assets/3348673/7e2ba27e-6e65-43d2-aec5-3686be063ea0)

**Comment by DaanHoogland** [comment]
not reproduced
