### ISSUE TITLE
can't login to management ui 

### ISSUE THREAD

**Issue by digitalgust** [apache/cloudstack#8130]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

management : centos 7.9

##### SUMMARY

can not login to gui, loading forever.
browser is chome 114.
open browser dev console ,get the error message:
vue-router.esm-bundler.js:3302 SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at a (util.js:5:17)
    at e.get (webStorage.js:20:27)
    at permission.js:57:45
    at vue-router.esm-bundler.js:1934:35
    at new Promise (<anonymous>)
    at vue-router.esm-bundler.js:1908:18
    at vue-router.esm-bundler.js:3416:65
VM3430:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at a (util.js:5:17)
    at e.get (webStorage.js:20:27)
    at Object.install (bootstrap.js:57:54)
    at Object.use (runtime-core.esm-bundler.js:3808:28)
    at main.js:70:8

##### STEPS TO REPRODUCE

~~~
before the issue occurred, the management server (and mysql) disk is full ,but i don't determine the disk full is the cause of login problem. 
~~~

##### EXPECTED RESULTS

~~~

login form , show the user and password field.
~~~

##### ACTUAL RESULTS

~~~

loading forever.
~~~

**Comment by weizhouapache** [comment]
@digitalgust 
can you please fix the disk issue, and then restart management server ? 
If it does not work, reinstall the packages and retry.

**Comment by digitalgust** [comment]
disk issue fixed already, and attemp to upgrade centos to latest and restore to old version (the management is a vm in esxi), and restore db data to a month ago , but all fail to login.

i am trying to revert to a snapshot that 2 years ago,it's running.but db data is old too . 
now trying to upgrade cloudstack and restore dbdata to latest.

**Comment by digitalgust** [comment]
i found the problem that 's disk full .
close the issue.
