### ISSUE TITLE
Bug: IPv6 CIDR for a VPC Subnet

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#8146]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Core
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0-SNAPSHOT-20231025-090535
~~~

##### SUMMARY

Can't create IPv6 subnet for a VPC4 CIDR. 
IPv6 CIDR and gateway are correct since both are derived from a CIDR calculator

##### STEPS TO REPRODUCE

~~~
// using DefaultIsolatedNetworkOfferingWithSourceNatService
cmk create network name=net-ipv6 vpcid=3907a884-a131-410d-9465-53cf947f7c0b ip6cidr=2001:db8:0:0:4000::/66 ip6gateway=2001:db8::4000:0:0:1 zoneid=bfd6f45b-de72-49a3-a523-a801162e3951 networkofferingid=77b348d6-dafc-427e-ba36-88e2034deaa2
~~~

##### EXPECTED RESULTS

~~~
IPv6 subnet is created
~~~

##### ACTUAL RESULTS

~~~
🙈 Error: (HTTP 431, error code 4350) The cidr size of IPv6 network must be 64 bits!
~~~

**Comment by weizhouapache** [comment]
@tampler 
CloudStack VRs configure SLAAC for IPv6, the cidr must be /64, as mentioned in the error message.

what you passed `ip6cidr=2001:db8:0:0:4000::/66` is not supported.

**Comment by tampler** [comment]
@weizhouapache  Hello Wei
This breaks VPC logic. `/64` CIDR6 should have been assigned to VPC6, which is NOT yet supported AFAIS :roll_eyes: 

How do I build subnets from a SLAAC IPv6 with only one fixed CIDR? I do receive `/64` range from my provider, but how do you expect me to split it on subnets? :thinking: 
I took my CIDR6 from a subnet calculator:
```sh
Full Range 2001:db8::/64
Subnet 0 2001:db8::/66
Subnet 1 2001:db8:0:0:4000::/66
Subnet 2 2001:db8:0:0:8000::/66
Subnet 3 2001:db8:0:0:c000::/66
```

**Comment by weizhouapache** [comment]
> @weizhouapache Hello Wei This breaks VPC logic. `/64` CIDR6 should have been assigned to VPC6, which is NOT yet supported AFAIS 🙄
> 
> How do I build subnets from a SLAAC IPv6 with only one fixed CIDR? I do receive `/64` range from my provider, but how do you expect me to split it on subnets? 🤔 I took my CIDR6 from a subnet calculator:
> 
> ```shell
> Full Range 2001:db8::/64
> Subnet 0 2001:db8::/66
> Subnet 1 2001:db8:0:0:4000::/66
> Subnet 2 2001:db8:0:0:8000::/66
> Subnet 3 2001:db8:0:0:c000::/66
> ```

@tampler 
You may request a larger IPv6 subnet for use. IPv6 addresses are very cheap.
To use IPv6 subnets, refer to https://docs.cloudstack.apache.org/en/latest/plugins/ipv6.html#isolated-network-and-vpc-tier

smaller subnets like /66 are not supported. They will not be supported in the future either.

**Comment by tampler** [comment]
@weizhouapache Thanks for clearing this out! Buying a larger IPv6 range is definitely not a problem.
Another issue I discovered is that I'm still unable to create a IPv6 network for VPC. Here's what I have:

```sh
  CIDR4: 10.0.0.64/26                                                           
  Gate4: 10.0.0.65
  NetMask4: 255.255.255.192
  CIDR6: 2001:db8:0:1::/64 
  Gate6: 2001:db8:0:1::1    
  NetMask6: ffff:ffff:ffff:ffff::   
```
Error: `CloudStack API error 431 (CSExceptionErrorCode: 4350): Can only support create IPv6 network with a
dvance shared network!`

So I can't create IPv6 subnet within VPC, right ? :roll_eyes:

**Comment by weizhouapache** [comment]
> @weizhouapache Thanks for clearing this out! Buying a larger IPv6 range is definitely not a problem. Another issue I discovered is that I'm still unable to create a IPv6 network for VPC. Here's what I have:
> 
> ```shell
>   CIDR4: 10.0.0.64/26                                                           
>   Gate4: 10.0.0.65
>   NetMask4: 255.255.255.192
>   CIDR6: 2001:db8:0:1::/64 
>   Gate6: 2001:db8:0:1::1    
>   NetMask6: ffff:ffff:ffff:ffff::   
> ```
> 
> Error: `CloudStack API error 431 (CSExceptionErrorCode: 4350): Can only support create IPv6 network with a dvance shared network!`
> 
> So I can't create IPv6 subnet within VPC, right ? 🙄

@tampler 
you may refer to the link https://docs.cloudstack.apache.org/en/latest/plugins/ipv6.html#isolated-network-and-vpc-tier

```
Here’s the sequence of events when IPv6 is used:

The administrator sets global configuration - ipv6.offering.enabled to true.
The administrator adds a public IPv6 range in an advanced zone.
The administrator adds an IPv6 prefix for guest traffic type for the zone.
The administrator creates a network or VPC offering with IPv4 + IPv6 (Dual stack) support.
The user deploys an isolated network with the IPv6 supported network offering. For VPC, user creates a VPC with IPv6 supported VPC offering and then deploys a network tier with IPv6 supported network offering.
CloudStack assigns a SLAAC based public IPv6 address to the network from the public IPv6 range of the zone. It also assigns an IPv6 subnet to the network from the guest IPv6 prefix for the zone. See [SLAAC](https://datatracker.ietf.org/doc/html/rfc4862)for more information.
The user deploys a guest VM in the network. The VM is assigned a SLAAC based IPv6 address from the guest IPv6 subnet of the network.
```
also
```
Once a public IPv6 address and guest subnet are assigned to the network or the network is successfully, the operator must update routing in the upstream router. For this, CloudStack returns the gateway and subnet for the network with listNetworks API response.
```

Another option for you is, create a shared network with the IPv6 address (and dummy IPv4 range), and then attach the VMs in VPC to the shared network.

**Comment by tampler** [comment]
@weizhouapache  Interesting idea :thinking: 
1. Adding a link to a shared network from an instance from a private VPC subnet introduces a huge security flaw and smth you can't do in AWS. So you won't wanna do that in ACS for production use
2. Currently I'm working with simulator, which doesn't offer VPC enabled IPv6. I opened #8148 to fix this out. 

Well, my initial issue is solved, so I'm closing this issue. Thanks for helping me out!
