### ISSUE TITLE
Add IPv6 netmask parameter to subnets

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#8155]
##### ISSUE TYPE

 * Improvement Request
 * Feature Idea
##### COMPONENT NAME

~~~
Core, API
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0-SNAPSHOT-20231025-090535
~~~

##### SUMMARY

IPv6 support was added to subnets. According to [docs](https://cloudstack.apache.org/api/apidocs-4.18/apis/createNetwork.html), there's no way to config IPv6 netmask. However, BOTH v4 and v6 masks need to be configured

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
Both IPv4 and IPv6 masks are allowed to set. Both need to be named properly, like `netmask4` and `netmask6`
~~~

##### ACTUAL RESULTS

~~~
IPv4 mask only with `netmask` parameter
~~~

**Comment by weizhouapache** [comment]
You can use ip6cidr

**Comment by tampler** [comment]
Of course I can. Same I could have had only IPv4 cidr. I noticed this discrepancy during API config for v6 networks.
Why having different APIs for v4 and v6?

**Comment by tampler** [comment]
I also suggest to standardize naming, e.g:
ip4cidr vs ip6cidr
gate4 vs gate6
netmask4 vs netmask6
ip4start, ip4ned vs ip6start, ip6end

**Comment by DaanHoogland** [comment]
> I also suggest to standardize naming, e.g: `ip4cidr` vs `ip6cidr` `gate4` vs `gate6` `netmask4` vs `netmask6` `ip4start`, `ip4end` vs `ip6start`, `ip6end` `dns4` vs `dns6`

for backwards compatibility I'd keep the designartors without number to be aliases of the -4 names.

**Comment by weizhouapache** [comment]
@tampler 
I am not sure if you still need the parameter.

In my opinion, unlike Ipv4 netmask, almost every ipv6 user uses Ipv6 prefix/cidr (not ipv6 netmask which is too complicated).

**Comment by tampler** [comment]
Hello @weizhouapache 

This seems to be like a stole issue. We may close it for now as a low priority at least. I'll reopen this should I require this again and badly :point_up:
