### ISSUE TITLE
Enhancement Request: Custom Control and Worker Node sizes

### ISSUE THREAD

**Issue by aron-ac** [apache/cloudstack#8159]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
Cloudstack Kubernetes Provider
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### SUMMARY

Currently in the cloudstack kubernetes provider you are only able to select one compute offering that dictates the size for both the control nodes and worker nodes. This results in an over provisioned control plane. Typically the control plane for a kubernetes cluster does not have the same compute requirements as the worker nodes.

Suggest that for the kubernetes provider we can define two compute offerings for the cluster, one for control nodes and one for worker nodes. 

##### STEPS TO REPRODUCE

When creating a new Kubernetes cluster allow user to select a compute package for the control nodes and a compute offering for the worker nodes. (UI and API)

~~~
n/a
~~~

##### EXPECTED RESULTS

~~~
n/a
~~~

##### ACTUAL RESULTS

~~~
n/a
~~~

**Comment by kiranchavala** [comment]
existing enhancement request already present #7916

**Comment by weizhouapache** [comment]
thanks @kiranchavala 

@aron-ac Please keep eye on #7916
