### ISSUE TITLE
Restarting management server causes multiple entries for the same node

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#8174]
Restart management server several times, even if there's only one mgmt server, it causes several entries in the cloud.mshost table and in the API:

<img width="943" alt="Screenshot 2023-11-01 at 11 17 34 PM" src="https://github.com/apache/cloudstack/assets/95203/fc86f846-562b-4f4e-8212-ec43968d3479">

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Mgmt server
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

Adv zone KVM env with Ubuntu 22.04

**Comment by weizhouapache** [comment]
@rohityadavcloud 
can you share the entries in database table `mshost` ?

**Comment by weizhouapache** [comment]
If a new record each time when management server is restarted, it might be because the management server id is calculated from a random mac address.

https://github.com/apache/cloudstack/blob/78213da82860761e174d5876afe857977f3889b3/utils/src/main/java/com/cloud/utils/net/MacAddress.java#L145

may need to verify all the commands before the line in same class

**Comment by weizhouapache** [comment]
looks  same as #8516

**Comment by poddm** [comment]
> If a new record each time when management server is restarted, it might be because the management server id is calculated from a random mac address.
> 
> https://github.com/apache/cloudstack/blob/78213da82860761e174d5876afe857977f3889b3/utils/src/main/java/com/cloud/utils/net/MacAddress.java#L145
> 
> may need to verify all the commands before the line in same class

What is the use case for this logic?  Why not just use the servers FQDN?

**Comment by weizhouapache** [comment]
> > If a new record each time when management server is restarted, it might be because the management server id is calculated from a random mac address.
> > https://github.com/apache/cloudstack/blob/78213da82860761e174d5876afe857977f3889b3/utils/src/main/java/com/cloud/utils/net/MacAddress.java#L145
> > 
> > may need to verify all the commands before the line in same class
> 
> What is the use case for this logic? Why not just use the servers FQDN?

@poddm 
Actually it does.
It gets the local address at first. If it does not, then fall back to the process above.
If the issue still exists, please share more information like
- hostname
- hostname -f
- /etc/hosts

**Comment by rohityadavcloud** [comment]
This happens on a server which is used both as management server and KVM hosts (and docker host), the number of interfaces keep on changing over time and the current code is flaky to be deterministic about which interface to pick. I've addressed this at: https://github.com/apache/cloudstack/pull/8968/commits/fb82e352bf4cd9306421effdd91bdc6e9387df5f

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/8988
