### ISSUE TITLE
Isolated network is shutdown even when there are running VMs on it

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8200]
in some cases, the isolated network is shutdown even when there running VMs on it. due to it
- the VR is stopped
- the vlan is released

As a workaround, to avoid the issue, user has to update the network to persistent, t

update network_offerings set is_persistent = 1 where traffic_type='Guest' and guest_type='Isolated';    

The issue is that, the nics_count in op_networks table is changed to 0, which is wrong sometimes.
We should add check on running/migrating/stopping VMs as well, before shutting down an isolated network, which is similar as
https://github.com/apache/cloudstack/blob/3d7281d4516e4a73a4a30921b9fe58a987fcb038/server/src/main/java/com/cloud/network/NetworkModelImpl.java#L2564-L2567

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by zap51** [comment]
I thought of reporting this as we've been affected multiple times on v4.16.1.0 as well.

**Comment by shwstppr** [comment]
@weizhouapache can you please provide some reproduction steps to verify the PR?

**Comment by weizhouapache** [comment]
> @weizhouapache can you please provide some reproduction steps to verify the PR?

@shwstppr 
To simulate the wrong value of nics_count, update the op_networks.nics_count for an isolated network to 0, then wait for the GC..

**Comment by shwstppr** [comment]
Linked PR is merged https://github.com/apache/cloudstack/pull/8204
Closing this
