### ISSUE TITLE
It is possible to restrict unauthorized access or block access to public IPs on SSVM?

### ISSUE THREAD

**Issue by IgaoWolf** [apache/cloudstack#8208]
Hello everyone,
I have a question that has been bothering me in recent days. I wanted to know if there is any way to restrict access to the public IPs of the SSVM in a manner that doesn't disrupt their operation.

**Comment by DaanHoogland** [comment]
@IgaoWolf , this sounds like you want tu put a firewall in front of the cloudstack installation. If I understand you correctly, there is no way to do that from within.
