### ISSUE TITLE
In an SG zone a VM can't be connected to an L2 network only

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#8217]
Hello,

While checking PR #8022 I realised in an SG zone a VM cannot be connected only in an L2 network, making the 8022 feature less useful than it could have been.
So what happens is that in an SG zone, once #8022 is out we can't have a clean "North - VNF - South/VM" setup, as Cloudstack mandates the VM in the South will need to be connected in at least another Shared SG network.

IMHO we should allow a VM to be connected only to an L2 network in a SG zone.

UI wise this is the error I am getting.

![Selection_574](https://github.com/apache/cloudstack/assets/2357012/24cc5c9d-ce27-4155-b40d-fc4478bd0403)

cc @weizhouapache @alexandremattioli

**Comment by weizhouapache** [comment]
@NuxRo 
sorry I just recall that this issue should has been fixed by #8122

**Comment by weizhouapache** [comment]
fixed by #8122
