### ISSUE TITLE
Doubt - Unable to Access VM Created through running Apache CloudStack Docker Image

### ISSUE THREAD

**Issue by aerial-ace1** [apache/cloudstack#8226]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
Not sure. But it is the version of the current docker image
~~~

##### CONFIGURATION

~~~
N/A
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu 22.04.3 LTS
Docker version 20.10.24, build 297e128
~~~

##### SUMMARY

~~~
When I try to open a console for any VM, it never opens up and I am not able to ssh into the VM either as port 22 is closed
~~~

##### STEPS TO REPRODUCE

~~~
So I pull the container and run it using the commands given in the Docker Hub 
~~~
[Docker Hub Site](https://hub.docker.com/r/apache/cloudstack-simulator)
```sh
docker pull apache/cloudstack-simulator
docker run --name cloudstack-simulator -p 8080:5050 -d apache/cloudstack-simulator
```
~~~
Then I deploy a datacenter of a basic zone using the given command
~~~
```sh
docker exec -it cloudstack-simulator python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/basic.cfg
```
Then go and make a compute instance using this datacenter deployment

##### EXPECTED RESULTS

~~~
I expect to be able to use the console and shell of the VM
~~~

##### ACTUAL RESULTS

![image](https://github.com/apache/cloudstack/assets/96421655/57b6aa76-a93d-43ec-845d-c09fe5c9c632)
~~~
First things first, the console proxy doesn't have a agent up state.
~~~
![image](https://github.com/apache/cloudstack/assets/96421655/751e515e-1d28-4474-9c02-3bee3c14565d)
~~~
This is the VM
~~~
![image](https://github.com/apache/cloudstack/assets/96421655/0cea6b72-16c6-4278-b79d-440a8e4484f2)
~~~
The console is unresponsive
~~~
![image](https://github.com/apache/cloudstack/assets/96421655/045d471d-31af-49e9-bbe8-b0d1b903e698)
~~~
I am able to ping the IP from my local machine(by exec-ing into the Docker Container also but screenshot not included)
~~~

**Comment by shwstppr** [comment]
@aerial-ace1 you are running a simulator environment and it just simulates resources in CloudStack. To deploy and access actual VMs and other resources please refer to the quick installation guide in Cloudstack documentation, https://docs.cloudstack.apache.org/en/latest/installguide/index.html
