### ISSUE TITLE
NoVNC work only for VM running on the same host as cpvm

### ISSUE THREAD

**Issue by 0sorkon** [apache/cloudstack#8242]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
SystemVM, CPVM
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

N/A 

##### OS / ENVIRONMENT

Ubuntu 22.04.3 LTS
cloudstack-common 4.18.1.0-shapeblue0
cloudstack-agent 4.18.1.0-shapeblue0
libvirt-* 8.0.0-1ubuntu7.7
qemu-* 1:6.2+dfsg-2ubuntu6.15

##### SUMMARY

NoVNC work only for VM running on the same host as cpvm. If vm running on the different host, browser show "Connection..." and after some period of time: "Failed to connect. Tocken expired". In browser console: Failed when connecting:
 Connection closed (code: 1001, reason: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms)`
No specific log entries. Neither in host logs no cpvm

Also migration betwen host not working. VM stuck at Migrating state. Only logs with some errors on reciver host:
~~~
Nov 16 16:21:30 cloud java[44764]: libvirt: QEMU Driver error : Domain not found: no domain with matching name 'i-2-109-VM'
Nov 16 16:21:30 cloud java[44764]: INFO  [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:) (logid:f234eb22) No existing libvirtd connection found. Opening a new one
Nov 16 16:21:30 cloud libvirtd[44082]: Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory
Nov 16 16:21:30 cloud libvirtd[44082]: End of file while reading data: Input/output error
Nov 16 16:21:30 cloud java[44764]: libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/virtlxcd-sock': No such file or directory
Nov 16 16:21:30 cloud java[44764]: WARN  [kvm.resource.LibvirtConnection] (agentRequest-Handler-3:) (logid:f234eb22) Can not find a connection for Instance i-2-109-VM. Assuming the default connection.
~~~
Last week everything was working, however at some unspecified point, it suddenly stopped working 

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
novnc works
migration work
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by 0sorkon** [comment]
This issue can be closed. The problem was an incorrect mtu value on the management interface on both compute nodes. Its strange but dont related to cloudstack itself

**Comment by weizhouapache** [comment]
do you use nested virtualization environment ? @0sorkon

**Comment by 0sorkon** [comment]
No, i don't. But because of some environment specifics my management interfaces is gre tunnels. And for some strange reason the mtu on them became 8962 which caused the problem.

**Comment by weizhouapache** [comment]
> No, i don't. But because of some environment specifics my management interfaces is gre tunnels. And for some strange reason the mtu on them became 8962 which caused the problem.

@0sorkon 
got it, thanks for the information
