### ISSUE TITLE
Cloudstack VM Password reset via GUI

### ISSUE THREAD

**Issue by wekesa254** [apache/cloudstack#8262]
Hi, 
Am currently running Cloudstack 4.18.0.0 
I have managed to create a template from the existing VM. My challenge is I don't have the option to reset the password from Cloudstack GUI. 
Kindly advise on what I might be missing out. Thank you. 
![Screenshot from 2023-11-23 18-36-46](https://github.com/apache/cloudstack/assets/42968567/7e82c0da-30ca-486b-b96a-f70a35fe0db8)

**Comment by weizhouapache** [comment]
You need to stop the vm

**Comment by wekesa254** [comment]
VM is in stop state

**Comment by weizhouapache** [comment]
Is password enabled for the template?

**Comment by wekesa254** [comment]
No

**Comment by weizhouapache** [comment]
Please update the template to password-enabled and retry

**Comment by wekesa254** [comment]
Ok

**Comment by rohityadavcloud** [comment]
One pre-requisite is that the VM/template must also have CloudStack compatible password-reset script or tooling.

**Comment by weizhouapache** [comment]
+1 with @rohityadavcloud 

@wekesa254 do you still have the issue ? if not, can you/we close this ticket ?

**Comment by DaanHoogland** [comment]
@wekesa254 can we close the issue?

**Comment by rohityadavcloud** [comment]
Closing on the remark as the original question was answered and advised on requirement that password reset script must be installed in template to leverage the feature. Modern best practice is to use cloud-init + ssh keys.
