### ISSUE TITLE
Vmstats records are not deleted as expected

### ISSUE THREAD

**Issue by havengit** [apache/cloudstack#8266]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.18.0.0
kvm

2 management servers with galera mariadb cluster
~~~

##### SUMMARY

When accessing the instance list, it takes about 3 minutes for a return, but other pages request return soon. The database has a lot of read IO. Check that the database is executing Creating sort index.

I find the vm_stats table has 1270000 records,From 4.17 the vm_stat is retained persistently. Setting in globe  "Vm stats max retention time " is 720 min default ,but there some record was not deleted 。
https://github.com/apache/cloudstack/pull/5984
![image](https://github.com/apache/cloudstack/assets/20832243/4759d7a5-cb61-4e6b-8822-54cbc29bc689)

A temporary solution is to truncate the vm_stats table.

##### STEPS TO REPRODUCE

~~~
No steps required to reproduce
~~~

##### EXPECTED RESULTS

~~~
Records are cleared normally, or collection of vmstat is allowed to be turned off
~~~

##### ACTUAL RESULTS

~~~
Some records was not deleted
~~~

**Comment by havengit** [comment]
After some testing, this problem has been solved. This shouldn't be a bug. The global parameters need some optimization.
default allocation:
Vm stats interval 60s
Vm stats max retention time 720min
Modified configuration
Vm stats interval 300s
Vm stats max retention time 60min

There are about 200+ running VMs in our environment. If calculated according to the default parameters, it will be retained
200*720=144000, after optimization: 200*60=12000

It may be that our database performance is insufficient and the amount of records is too large to complete the deletion operation as expected. There will be more and more records.

It is recommended to optimize the setting value.

**Comment by DaanHoogland** [comment]
@havengit Do you mean to close this ticket or is still work to be done?

**Comment by weizhouapache** [comment]
> It may be that our database performance is insufficient and the amount of records is too large to complete the deletion operation as expected. There will be more and more records.

if so, this needs to be fixed

**Comment by havengit** [comment]
> @havengit Do you mean to close this ticket or is still work to be done?

This problem will occur when there are a large number of running VMs. I've confirmed that adjusting the global settings resolves the issue. No more work needed. It is recommended to modify the default value。

**Comment by weizhouapache** [comment]
persistent vm stats were introduced by PR #5984 in CloudStack 4.17.0.0
There might be heavy I/O if there are many vms or the vm stats interval is small (it writes the vm stats in database).

for vm network/disk statistics, the default interval was set to 300 seconds.
but for some new settings, the default interval is set to 60 seconds. It is good to have the statistics every minute, but we need to consider some large environments.

We need to review the global settings and probably change the default value of some settings.

```
mysql> select name,value,default_value from configuration where name like "%interval%";
+--------------------------------------------------------+--------+---------------+
| name                                                   | value  | default_value |
+--------------------------------------------------------+--------+---------------+
| account.cleanup.interval                               | 60     | 86400         |
| alert.purge.interval                                   | 86400  | 86400         |
| api.throttling.interval                                | 1      | 1             |
| autoscale.stats.interval                               | 60     | 60            |
| backup.framework.sync.interval                         | 300    | 300           |
| backup.retry.interval                                  | 300    | 300           |
| cluster.heartbeat.interval                             | 1500   | 1500          |
| console.session.cleanup.interval                       | 180    | 180           |
| consoleproxy.capacityscan.interval                     | 30000  | 30000         |
| database.server.stats.interval                         | 60     | 60            |
| diagnostics.data.gc.interval                           | 86400  | 86400         |
| direct.agent.scan.interval                             | 90     | 90            |
| direct.download.certificate.background.task.interval   | 0      | 0             |
| direct.network.stats.interval                          | 86400  | 86400         |
| drs.automatic.interval                                 | 60     | 60            |
| drs.plan.expire.interval                               | 30     | 30            |
| event.purge.interval                                   | 86400  | 86400         |
| expunge.interval                                       | 60     | 86400         |
| external.network.stats.interval                        | 300    | 300           |
| externaldhcp.vmip.retrieval.interval                   | 180    | 180           |
| extract.url.cleanup.interval                           | 300    | 7200          |
| extract.url.expiration.interval                        | 14400  | 14400         |
| healthcheck.update.interval                            | 600    | 600           |
| host.stats.interval                                    | 60000  | 60000         |
| indirect.agent.lb.check.interval                       | 0      | 0             |
| interval.baremetal.securitygroup.agent.echo            | 10     | 10            |
| investigate.retry.interval                             | 60     | 60            |
| kvm.ha.activity.check.interval                         | 8      | 60            |
| kvm.rolling.maintenance.ping.interval                  | 10     | 10            |
| management.server.stats.interval                       | 60     | 60            |
| migrate.retry.interval                                 | 120    | 120           |
| network.gc.interval                                    | 600    | 600           |
| network.ipv6.prefix.subnet.cleanup.interval            | 1800   | 1800          |
| network.loadbalancer.basiczone.elb.gc.interval.minutes | 30     | 30            |
| network.securitygroups.work.cleanup.interval           | 120    | 120           |
| outofbandmanagement.background.task.execution.interval | 4      | 4             |
| ovm3.heartbeat.interval                                | 10     | 1             |
| ping.interval                                          | 20     | 60            |
| resourcecount.check.interval                           | 300    | 300           |
| restart.retry.interval                                 | 600    | 600           |
| router.alerts.check.interval                           | 300    | 1800          |
| router.check.interval                                  | 30     | 30            |
| router.health.checks.advanced.interval                 | 10     | 10            |
| router.health.checks.basic.interval                    | 3      | 3             |
| router.health.checks.config.refresh.interval           | 10     | 10            |
| router.health.checks.results.fetch.interval            | 10     | 10            |
| router.redundant.vrrp.interval                         | 1      | 1             |
| router.stats.interval                                  | 300    | 300           |
| secstorage.capacityscan.interval                       | 30000  | 30000         |
| snapshot.poll.interval                                 | 300    | 300           |
| stop.retry.interval                                    | 600    | 600           |
| storage.cache.replacement.interval                     | 86400  | 86400         |
| storage.cache.replacement.lru.interval                 | 30     | 30            |
| storage.cleanup.interval                               | 10800  | 86400         |
| storage.stats.interval                                 | 60000  | 60000         |
| storpool.storage.stats.interval                        | 3600   | 3600          |
| storpool.volumes.stats.interval                        | 3600   | 3600          |
| sync.interval                                          | 60     | 60            |
| ucs.sync.blade.interval                                | 3600   | 3600          |
| upload.monitoring.interval                             | 60     | 60            |
| usage.sanity.check.interval                            | NULL   | NULL          |
| vm.disk.stats.interval                                 | 0      | 0             |
| vm.disk.stats.interval.min                             | 300    | 300           |
| vm.job.check.interval                                  | 3000   | 3000          |
| vm.job.report.interval                                 | 60     | 60            |
| vm.network.stats.interval                              | 0      | 0             |
| vm.network.stats.interval.min                          | 300    | 300           |
| vm.op.cancel.interval                                  | 3600   | 3600          |
| vm.op.cleanup.interval                                 | 1200   | 86400         |
| vm.op.wait.interval                                    | 60     | 120           |
| vm.stats.interval                                      | 60000  | 60000         |
| vm.tranisition.wait.interval                           | 300    | 3600          |
| vmscheduler.jobs.expire.interval                       | 30     | 30            |
| vmsnapshot.expire.interval                             | -1     | -1            |
| volume.stats.interval                                  | 600000 | 600000        |
| vpc.cleanup.interval                                   | 1200   | 3600          |
| xenserver.heartbeat.interval                           | 60     | 60            |
+--------------------------------------------------------+--------+---------------+
77 rows in set (0.00 sec)
```

**Comment by DaanHoogland** [comment]
not sure if any do, but even though they mean kind of the reverse some of these might matter as well:
|name|value|default_value|
|----|-----|-------------|
|alert.smtp.connectiontimeout|30000|30000|
|alert.smtp.timeout|30000|30000|
|backup.plugin.networker.request.timeout|300|300|
|backup.plugin.veeam.request.timeout|300|300|
|backup.plugin.veeam.restore.timeout|600|600|
|baremetal.provision.done.notification.timeout|1800|1800|
|cloud.kubernetes.cluster.scale.timeout|3600|3600|
|cloud.kubernetes.cluster.start.timeout|3600|3600|
|cloud.kubernetes.cluster.upgrade.timeout|3600|3600|
|cloudian.api.request.timeout|5|5|
|cluster.message.timeout.seconds|300|300|
|consoleproxy.session.timeout|300000|300000|
|diagnostics.data.retrieval.timeout|1800|1800|
|direct.download.connect.timeout|5000|5000|
|direct.download.connection.request.timeout|5000|5000|
|direct.download.socket.timeout|5000|5000|
|kvm.ha.activity.check.timeout|60|60|
|kvm.ha.fence.timeout|60|60|
|kvm.ha.health.check.timeout|10|10|
|kvm.ha.recover.timeout|60|60|
|kvm.rolling.maintenance.stage.timeout|1800|1800|
|kvm.rolling.maintenance.wait.maintenance.timeout|1800|1800|
|ldap.read.timeout|1000|1000|
|ncc.command.timeout|600000|600000|
|network.lock.timeout|600|600|
|network.securitygroups.work.lock.timeout|300|300|
|outofbandmanagement.action.timeout|60|60|
|ovm3.heartbeat.timeout|180|120|
|ping.timeout|2.0|2.5|
|project.invite.timeout|86400|86400|
|quota.activationrule.timeout|2000|2000|
|quota.usage.smtp.connection.timeout|60|60|
|router.aggregation.command.each.timeout|600|600|
|saml2.timeout|1800|1800|
|stats.timeout|60000|60000|
|storage.pool.client.timeout|60|60|
|timeout.baremetal.securitygroup.agent.echo|3600|3600|
|upload.operation.timeout|60|60|
|vm.job.lock.timeout|1800|1800|
|vm.job.timeout|600000|600000|
|vmware.hung.wokervm.timeout|7200|7200|
|vmware.nic.hotplug.wait.timeout|15000|15000|
|vmware.package.ova.timeout|3600|3600|
|vmware.vcenter.session.timeout|1200|1200|
|xen.heartbeat.timeout|180|120|
|xenserver.heartbeat.timeout|120|120|

I think that's it (famous last words)

**Comment by weizhouapache** [comment]
yes @DaanHoogland 
the timeout settings are important, they have impacts on some long-running tasks, for example snapshots.

Back to this issue, I think we could at least review
- interval of stats , which determine how frequent stats are written to database
- retention time of stats, which determine how frequent stats are cleaned up and how many records are kept.

**Comment by DaanHoogland** [comment]
I was looking at the timeouts to see if any can be related. I did a coure filtering of the list;
`vm.job.lock.timeout`
`vm.job.timeout` and most importantly
`stats.timeout` may be of influence.

Of course you are right that the *intervals* are of more significance.
