### ISSUE TITLE
documentation for flexible tags

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8283]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~
tagging
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### SUMMARY

the feature added by PR #7489 needs documentation

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by JoaoJandre** [comment]
Created the PR here https://github.com/apache/cloudstack-documentation/pull/365
