### ISSUE TITLE
Unable to change public IP address of system VM in zone with security label enabled

### ISSUE THREAD

**Issue by jhondoue** [apache/cloudstack#8288]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Physical network public traffic management
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### OS / ENVIRONMENT

~~~
almalinux 8.3
~~~
##### PROBLEM

~~~
 "system VM" radio button and perform an IP range update to select the public IP address range used by the system VM in the physical network public traffic management user interface, I get "Error 431 forSystemVms is not available for this IP" range with vlan type: DirectAttached" is returned.
~~~
##### STEPS TO REPRODUCE

~~~
Adding and updating public IP ranges from the physical network settings UI for zones with advanced networking and security labels enabled
~~~

##### EXPECTED RESULTS

~~~
Change public IP of system VM
~~~

##### ACTUAL RESULTS

~~~
This issue could not be reproduced in zones with security labels disabled. Since it is not possible to specify the public IP used by the system VM, Cloud Stack automatically gives the system VM a public IP with a smaller VLAN ID value.
This becomes a big problem when you want to change the public IP address of your system VM for some reason.
~~~

**Comment by DaanHoogland** [comment]
I am not sure I understand your report completely yet @jhondoue , but it sounds like an enhancement request to me. I am not sure if systemvm ip ranges are fully implemented for security groups yet. (hope I understood your report right)

**Comment by jhondoue** [comment]
@DaanHoogland 
Thank you reply
What I have described is an issue where changing the public IP address given to system VMs fails.

Due to error 431, I was unable to smoothly change the public IP addresses of the console proxy and secondary storage, so I had no choice but to temporarily delete all VLANs and was able to achieve my goal.
It's possible that my steps were wrong somehow. .
![2023-12-02_23-30-48](https://github.com/apache/cloudstack/assets/152584081/1e6a4a0c-c518-49d7-bab1-142cd9b6c084)
![2023-12-02_23-31-07](https://github.com/apache/cloudstack/assets/152584081/7b36e434-36c9-46ac-80a1-b567e618020c)

**Comment by weizhouapache** [comment]
@jhondoue 
the public IPs are actually the IPs in shared network, different as the public IPs in advanced zone without security groups.
therefore you cannot dedicate IP ranges to system vms.

**Comment by DaanHoogland** [comment]
@jhondoue , can you live with @weizhouapache ´s comment? anything to add?

**Comment by rohityadavcloud** [comment]
Closing this as stale and by design.
