### ISSUE TITLE
CKS cluster with HA enabled has port forwarding rules to one control VM

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8295]
with PR #7479, we are able to create CKS cluster on vpc tier, that's great !

Different from the settings on CKS on isolated networks, only port forwarding rules are configured in new public IP in VPC.
We might need to create load balancer rules for kubernetes api servers (port 6443). otherwise, if the control VM is down, the CKS cluster will not work.
see screenshot
![image](https://github.com/apache/cloudstack/assets/57355700/b02dfb49-ef56-4055-bd04-9661b349a0c1)

For your information, below are the port forwarding rules and load balancer rules for isolated networks
![image](https://github.com/apache/cloudstack/assets/57355700/d645188d-e69a-459f-920b-48e9c8c9b679)
and
![image](https://github.com/apache/cloudstack/assets/57355700/cde26633-2dcf-46f5-8774-3c3a34ccf2d8)

We should also consider the scenario that network offering does not support conserve mode.  In that case,  public ip cannot be used for multiple purposes,  we should use load balancing to replace port forwarding rules for the management ports 2222/2223... 

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
CKS
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
so on VPCs we need to create an extra ip when we create a CKS cluster, do we?

**Comment by weizhouapache** [comment]
> so on VPCs we need to create an extra ip when we create a CKS cluster, do we?

yes, that is done in PR #7479

**Comment by weizhouapache** [comment]
fixed in 4.20.0 by #7919
