### ISSUE TITLE
[Question] signatureVersion and expires params in /client/console request

### ISSUE THREAD

**Issue by OlegChuev** [apache/cloudstack#8299]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Console
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### SUMMARY

I'm trying to implement access to the VM Console without entering CloudStack itself. I was able to implement it using the following approach: [link to the CloudStack developer documentation](https://docs.cloudstack.apache.org/en/latest/developersguide/dev.html#how-to-sign-an-api-call-with-python).

An example of my request query is as follows:
`/client/console?apikey=XXXXXX&cmd=access&vm=YYYYYY&signature=ZZZZ`

Now, I'm attempting to add signatureVersion and expires parameters, as per the link above, to the request to add an additional layer of security. However, it seems that it doesn't work at all. It appears that `server/src/main/java/com/cloud/servlet/ConsoleProxyServlet.java` lacks the required functionality. What are your thoughts on adding it somewhere in the nearest future?

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@OlegChuev , I fuess you are on your own for now. Your description sounds like this is a reasonable request and it should work though.

**Comment by nvazquez** [comment]
Hi @OlegChuev, as far as I know that endpoint may be deprecated. Have you tried a query to `/client/api?command=createConsoleEndpoint....`? This is an API command and should support the parameters you are trying to use

**Comment by rohityadavcloud** [comment]
Hi @OlegChuev as @nvazquez has advised, the current best practice is to us the `createConsoleEndpoint` API to obtain information to get the correct URL. Closing on this remark. If this isn't acceptable for you, kindly reopen the ticket with further inputs for our better understanding.
