### ISSUE TITLE
Console proxy iptables: invalid port/service `${VNCPORT}' specified

### ISSUE THREAD

**Issue by salfers** [apache/cloudstack#8303]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
System VM: Console Proxy
~~~

##### CLOUDSTACK VERSION
~~~
systemvm-kvm-4.18.1
~~~

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY

When checking the syslog on a console proxy it is apparent that the firewall configuration fails:

```
Dec  5 08:41:14 systemvm postinit.sh[2244]: iptables-restore v1.8.7 (nf_tables): invalid port/service `${VNCPORT}' specified
Dec  5 08:41:14 systemvm postinit.sh[2244]: Error occurred at line: 38
Dec  5 08:41:14 systemvm postinit.sh[2244]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

##### STEPS TO REPRODUCE

On a CloudStack 4.18 installation, ssh into the console proxy and view `/var/log/messages`.

##### ADDITIONAL CONTEXT

When checking `/etc/iptables/rules.v4` you can see that the port was substituted incorrectly:
```
[...]
-A INPUT -i eth1 -p tcp -m state --state NEW -m tcp --dport 8001 -j ACCEPT
-A INPUT -i eth2 -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -i eth2 -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -i eth2 -p tcp -m state --state NEW -m tcp --dport ${VNCPORT} -j ACCEPT
COMMIT
```
Consequently no firewall ends up being configured on the CPVM.

The bug was introduced in this commit: https://github.com/apache/cloudstack/commit/b2fbe7bb12156f8efb065c8e423a1970310879fa#diff-0b886ce9aa1fea73688602c0cfade52a5162e40b27944c3d7948a59c98e78e8d

**Comment by DaanHoogland** [comment]
Thanks for the detailed report @salfers .

**Comment by DaanHoogland** [comment]
@salfers can you review #8369 (won't make it in 4.19 but may be in the next release)

**Comment by salfers** [comment]
The changes in your pull request look correct to me. :+1:

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/8369
