### ISSUE TITLE
VPC: Public IP cannot be used by multiple services

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8313]
Steps to reproduce the issue
- create a vpn, a tier and a vm
- acquire a public IP
- create port forwarding rule to the vm
- create load balancer rule via cmk/cloudmonkey

Expected:
all good

Actual result:
```
(localcloud) 🐱 > create loadbalancerrule publicipid=712e9718-7ca7-4866-a930-516919098201 publicport=80 privateport=80 algorithm=roundrobin name=http
🙈 Error: (HTTP 530, error code 4250) Failed to create load balancer rule: http
```
the error logs show
```
2023-12-06 11:04:11,098 WARN  [c.c.n.l.LoadBalancingRulesManagerImpl] (qtp249034932-13:ctx-a267cf2c ctx-045bb55f ctx-fcc51a3c) (logid:e9fde666) Failed to create load balancer due to
java.security.InvalidParameterException: The IP 10.0.53.125 is already used as PortForwarding rather than Lb
        at com.cloud.network.NetworkModelImpl.canIpUsedForNonConserveService(NetworkModelImpl.java:422)
        at com.cloud.network.NetworkModelImpl.checkIpForService(NetworkModelImpl.java:1621)
```

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.18/4.19
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
this has been addressed in #8309

**Comment by alexandremattioli** [comment]
Adding to that, a VPC's sourceNAT IP cannot be used for other services.

**Comment by DaanHoogland** [comment]
I marked it as 4.19 as the PR, but I think it is a bit tight to get this in.
