### ISSUE TITLE
UI add icons to host for declareHostAsDegraded and cancelHostAsDegraded

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#8318]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### SUMMARY

When a host is in state 'Alert' or 'Disconnected' you are able to degrade a host via api call [declareHostAsDegraded](https://cloudstack.apache.org/api/apidocs-4.18/apis/declareHostAsDegraded.html). It would be nice to have this action as an icon (button) on the host page in the UI. To get a host out of degraded state it would be nice to have an icon (button) using api call [cancelHostAsDegraded](https://cloudstack.apache.org/api/apidocs-4.18/apis/cancelHostAsDegraded.html).

More info on those api calls: [API-call to declare host as Degraded](https://github.com/apache/cloudstack/pull/4111)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
Fixed with #8327
