### ISSUE TITLE
Unable to upload ISO Files 

### ISSUE THREAD

**Issue by tamoorahmedntu** [apache/cloudstack#8331]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
secondarystoragevm
secondarystorage
secstorage.ssl.cert.domain = cloudstorage.mydomainname
Using SSL 
~~~
##### CLOUDSTACK VERSION
~~~
CloudStack 4.18.1.0 
~~~
##### OS / ENVIRONMENT
~~~
Ubuntu 22.04.1 LTS
~~~

##### SUMMARY
Proper SSL being used not self signed 
Able to SSH to SSVM and CPSVM

Unable to upload ISO or templates;
when uploading I get the error message in the browser console 
![image](https://github.com/apache/cloudstack/assets/55551210/09fc624d-9388-426f-adcf-7e483a76c7ab)
![image](https://github.com/apache/cloudstack/assets/55551210/a4cc38db-8a08-4fde-8d33-da077af847ce)

Management Cloud Stack Log 
says unable to reach host
unable to reach cloudstorage.mydomainname
management has firewall turned off 

NFS on Management 
NFS is running and mounted and working 

SSVM 
/usr/local/cloud/systemvm/ssvm-check.sh
![image](https://github.com/apache/cloudstack/assets/55551210/77b956a8-d9e1-4ddc-80bd-bec39eb5bfab)
SSVM  firewall turned off 
![image](https://github.com/apache/cloudstack/assets/55551210/585dee59-3a77-4a02-aa6f-38a215a9b92e)
IP Address NOT pingable 
Private IP address Pingable 

##### STEPS TO REPRODUCE
images  > ISOs > Upload ISO from local

##### EXPECTED RESULTS
To be able to upload ISO successfully 

##### ACTUAL RESULTS

Management Cloud Stack Log 
says unable to reach host
unable to reach cloudstorage.mydomainname
management has firewall turned off 

NFS on Management 
NFS is running and mounted and working 

SSVM 
/usr/local/cloud/systemvm/ssvm-check.sh
![image](https://github.com/apache/cloudstack/assets/55551210/77b956a8-d9e1-4ddc-80bd-bec39eb5bfab)
SSVM  firewall turned off 
![image](https://github.com/apache/cloudstack/assets/55551210/585dee59-3a77-4a02-aa6f-38a215a9b92e)
IP Address NOT pingable 
Private IP address Pingable 

Console Proxy
Working fine with Private IP Address

**Comment by rajujith** [comment]
@tamoorahmedntu 

Are you able to connect to port 443 on cloudstorage.mydomainname? 
Does this hostname resolve correctly to the SSVM's public IP?

You could compare you configuration against the recommended steps for enabling SSL/TLS for system VMs in cloudstack: 

https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

**Comment by tamoorahmedntu** [comment]
Nothing comes up on 443
Not public but yes private


________________________________

**Comment by tamoorahmedntu** [comment]
I went through everything again and made sure, all the net plan reflect cloud stack instructions and made sure the traffic labels are correct and made sure all the network IPs are correct, after a reboot things started to work
