### ISSUE TITLE
noVNC -Websocket issue after upgrading from 4.17 to 4.18

### ISSUE THREAD

**Issue by shulemmosko** [apache/cloudstack#8332]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

Console Proxy

##### CLOUDSTACK VERSION

Management 4.18.1.0
SystemVM 4.18.1.0
Agents 4.17.2.0

##### CONFIGURATION

I have one console proxy systemvm,  using SSL.

##### OS / ENVIRONMENT

Ubuntu Focal 20.04

##### SUMMARY

After upgrading cloudstack management the console proxy stopped working, I can get to the noVNC gray background page but after trying to connect im getting a red banner "failed to connect to server"

![image](https://github.com/apache/cloudstack/assets/78984653/2ec8c869-9c26-4846-a480-8db31ca14e18)

The interesting part is that when logging in to the console proxy via ssh port 8443 that the websocket is trying to use is not allowed in iptables.

![image](https://github.com/apache/cloudstack/assets/78984653/93f6ab33-08bb-4807-b321-e1c56f6a11a5)

I tried changing the port in the vnc URL to port=8080 but then im getting the following in the browser console.

![image](https://github.com/apache/cloudstack/assets/78984653/f5ed1522-2cf5-4406-a88c-1d76017790de)

##### STEPS TO REPRODUCE

upgrading management server to 4.18.1.0

##### EXPECTED RESULTS

noVNC to work properly.

**Comment by rajujith** [comment]
@shulemmosko  have you recreated the consoleproxy vm after the upgrade?

**Comment by shulemmosko** [comment]
@rajujith yes of course, multiple times.

**Comment by shulemmosko** [comment]
@rajujith @weizhouapache 

Here you can see that the consoleproxy VM is not listening on port 8443.

![image](https://github.com/apache/cloudstack/assets/78984653/959ab065-fb2f-4e7d-abb7-a433fabebfec)

And here is the systemVM config.

![image](https://github.com/apache/cloudstack/assets/78984653/2d2712cf-80a3-4b8e-8de3-2b3206ec5b67)

the URL is pointing to the public IP of the consoleproxy VM.

Thanks for your help!!

**Comment by weizhouapache** [comment]
@shulemmosko 
have you upgraded the systemvm template and cloudstack-agent on kvm hosts ?

**Comment by weizhouapache** [comment]
> The cloudstack agents i tried upgrading but it would not connect to the management server see issue #8310 so I had to downgrade them to 4.17.2

that explains. The cloudstack-agent version must be same as cloustack-management
