### ISSUE TITLE
question about virtual router apache cloudstack

### ISSUE THREAD

**Issue by herdiansah571** [apache/cloudstack#8335]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Virtual Router
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### STEPS TO REPRODUCE

~~~
Hello,

I want to ask question about virtual router.
I have 2 kvm hypervisors, the first kvm hypervisor hostname is kvm-1 and the second kvm hypervisor hostname is kvm-2.
then I create a vpc virtual router on kvm-1, then I create an instance on kvm-1, if I ping the instance on kvm-1 the network is reachable.
then I created an instance on kvm-2. but if I ping the instance on kvm-2 it is unreachable
I want to ask, does the VPC virtual router only support 1 kvm hypervisor? and the second hypervisor, namely kvm-2, can't connect to the virtual router?

Please help to provide an explanation. and how can the VPC virtual router assign an IP address to the instance on KVM-2?

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by herdiansah571** [comment]
Hello @weizhouapache 

you mean configure ports as trunk mode or hybrid mode on physical switch ? 
or configure ports as trunk mode or hybrid mode on apache cloudstack server ? 
can you share an example configuration ?

Thanks.....

**Comment by rajujith** [comment]
@herdiansah571 
An example based on Cisco catalyst series for the hypervisor switch port:
```
interface GIgabitEthernet 1/0/5
switchport trunk encapsulation dot1q
switchport mode trunk
switchport trunk native vlan 100
switchport trunk allowed 101-200
```

**Comment by herdiansah571** [comment]
Hello @rajujith 

How about If I use openvswitch ? so I install openvswitch on each hypervsors (kvm-1 & kvm-2).
If I  install openvswitch on each hypervsors (kvm-1 & kvm-2), can  the VPC virtual router assign an IP address to the instance on KVM-2?
