### ISSUE TITLE
 System and Builtin templates must be cross zone

### ISSUE THREAD

**Issue by Tbaugus44** [apache/cloudstack#8340]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI-System Templates
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0 
~~~

##### CONFIGURATION

Advanced Networked Zone.
##### OS / ENVIRONMENT

The management server is running on a separate vm than its mySQL db. both are running Ubuntu 22.04.03 LTS, KVM Hypervisor. 

##### SUMMARY

We can not switch a template to be used as a system template. we get the error "System and Builtin templates must be cross zone". We are unable to find what we need to enable for this to work.

##### STEPS TO REPRODUCE

Go to Images>Templates. Selected an uploaded template and change the template type to system
![image](https://github.com/apache/cloudstack/assets/148808916/de05b75e-a336-44a9-9fa0-612224c3da19)

~~~

~~~

##### EXPECTED RESULTS

~~~
I expected the template to be changed to a system template
~~~

##### ACTUAL RESULTS

~~~
we get the error System and Builtin templates must be cross zone
~~~

**Comment by weizhouapache** [comment]
You can re-register the template for all zones

**Comment by Tbaugus44** [comment]
how would you do that? this is a template we uploaded from here http://packages.shapeblue.com/systemvmtemplate/4.18/

**Comment by rajujith** [comment]
@Tbaugus44  You need to register the template again using the 'register template from URL'. In the form select all zones, and template type 'SYSTEM'.

**Comment by Tbaugus44** [comment]
@rajujith thank you. i see what you mean. I have only found .bz2 template files from Shapeblue and cloudstack. do you know where i could point to an already unzipped file

**Comment by weizhouapache** [comment]
> @rajujith thank you. i see what you mean. I have only found .bz2 template files from Shapeblue and cloudstack. do you know where i could point to an already unzipped file

@Tbaugus44 
you should be able to register the systemvm template file ends with .bz2
