### ISSUE TITLE
create L2 network offering with userdata Problem

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#8345]
##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME
API,UI

##### CLOUDSTACK VERSION
4.17.2.0

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
U20.4 LTS

##### SUMMARY
I Create Network Offering For L2 Network With "UserData Enable Option" But After Create I can Not See And Use It During Create and Add Guest L2 Network In Network Offering Section. 
i Tested it in 4.18.1 and everything is Ok there.

##### STEPS TO REPRODUCE
service offering > network offering > add > L2 > With Follow Option
 Enable Userdata Radio B
 public 
all zone 
enable

##### EXPECTED RESULTS
i can view of use of that L2 network offering During Creating L2 Network

##### ACTUAL RESULTS
i can not use my L2 Network Offering With Userdata Enable

**Comment by weizhouapache** [comment]
> Tested it in 4.18.1 and everything is Ok there.

4.18.1 ?

**Comment by ahmadamirahmadi007** [comment]
yes but my problem is on 4.17.2

**Comment by weizhouapache** [comment]
@ahmadamirahmadi007 
can you share some screenshots ?
I cannot reproduce the issue

**Comment by ahmadamirahmadi007** [comment]
![L2Offering](https://github.com/apache/cloudstack/assets/104001728/164564b8-c6ee-4ced-a7cc-487bd523f033)
![AddNetwork](https://github.com/apache/cloudstack/assets/104001728/5b2116e1-a3b7-41c1-b461-138000571821)

i dont have L2NetworkOfferin In Creating L2 Network
@weizhouapache

**Comment by weizhouapache** [comment]
@ahmadamirahmadi007 
I am still not able the reproduce the issue
can you list network offerings by cmk/cloudmonkey ?
```
list networkofferings guestiptype=L2 filter=id,name
```

**Comment by ahmadamirahmadi007** [comment]
{
  "count": 12,
  "networkoffering": [
    {
      "id": "dec01899-d15d-4fc5-b804-dc16d1268175",
      "name": "DefaultL2NetworkOffering"
    },
    {
      "id": "af22a591-5cc1-4042-afec-9a406cafd40f",
      "name": "DefaultL2NetworkOfferingVlan"
    },
    {
      "id": "2ef7d725-0ecc-4eb2-ae0d-855fba90eb65",
      "name": "DefaultL2NetworkOfferingConfigDrive"
    },
    {
      "id": "c6204e9f-ef76-402f-badb-b43cb8952127",
      "name": "DefaultL2NetworkOfferingConfigDriveVlan"
    },
    {
      "id": "7ac8aaa4-cadd-4129-8796-4134fb4b7ab4",
      "name": "Test1L2"
    },
    {
      "id": "0677e3b3-85ef-412d-a0c3-2c0a0968b89b",
      "name": "SW-250M"
    },
    {
      "id": "22b3e75a-4f99-469f-8008-cbd364075c80",
      "name": "SW-2500M"
    },
    {
      "id": "107138e1-5809-41ec-9f96-c9d58d34a6a2",
      "name": "TEST-L2-cloudinit"
    },
    {
      "id": "e9994c5f-0451-454d-b350-3da36eb5c04f",
      "name": "SW-250M-cv"
    },
    {
      "id": "fc06a795-0f21-41ba-a1f0-e9a1a9fba5a7",
      "name": "SW-250M-c"
    },
    {
      "id": "dc4e35a2-9c29-4ad0-a7c2-58ff71c82ad7",
      "name": "SW-250M-cccc"
    },
    {
      "id": "ecfbf039-25bf-4515-83ed-4cf923ba26de",
      "name": "L2NetworkOffering"
    }
  ]
}

i L2NetworkOffering was built by me. but I can't use it to build a L2 network.

**Comment by weizhouapache** [comment]
> i L2NetworkOffering was built by me. but I can't use it to build a L2 network.

can you share the details of the offering ?
```
list networkofferings guestiptype=L2 id=ecfbf039-25bf-4515-83ed-4cf923ba26de
```

**Comment by ahmadamirahmadi007** [comment]
{
  "count": 1,
  "networkoffering": [
    {
      "availability": "Optional",
      "conservemode": true,
      "created": "2023-12-13T09:44:40+0330",
      "displaytext": "L2NetworkOffering",
      "egressdefaultpolicy": true,
      "forvpc": false,
      "guestiptype": "L2",
      "hasannotations": false,
      "id": "ecfbf039-25bf-4515-83ed-4cf923ba26de",
      "internetprotocol": "IPv4",
      "isdefault": false,
      "ispersistent": false,
      "name": "L2NetworkOffering",
      "networkrate": 200,
      "service": [
        {
          "name": "UserData",
          "provider": [
            {
              "name": "ConfigDrive"
            }
          ]
        }
      ],
      "serviceofferingid": "c1b39187-597f-4c1e-a2e9-8eb616abbe1e",
      "specifyipranges": false,
      "specifyvlan": true,
      "state": "Enabled",
      "supportspublicaccess": false,
      "supportsstrechedl2subnet": false,
      "traffictype": "Guest"
    }
  ]
}

**Comment by weizhouapache** [comment]
> { "count": 1, "networkoffering": [ { "availability": "Optional", "conservemode": true, "created": "2023-12-13T09:44:40+0330", "displaytext": "L2NetworkOffering", "egressdefaultpolicy": true, "forvpc": false, "guestiptype": "L2", "hasannotations": false, "id": "ecfbf039-25bf-4515-83ed-4cf923ba26de", "internetprotocol": "IPv4", "isdefault": false, "ispersistent": false, "name": "L2NetworkOffering", "networkrate": 200, "service": [ { "name": "UserData", "provider": [ { "name": "ConfigDrive" } ] } ], "serviceofferingid": "c1b39187-597f-4c1e-a2e9-8eb616abbe1e", "specifyipranges": false, "specifyvlan": true, "state": "Enabled", "supportspublicaccess": false, "supportsstrechedl2subnet": false, "traffictype": "Guest" } ] }

looks good.

do you have multiple zones ?

**Comment by ahmadamirahmadi007** [comment]
no just one

**Comment by weizhouapache** [comment]
can you create a L2 network with the offering via cmk ?

**Comment by ahmadamirahmadi007** [comment]
/snap/bin/cmk  create network displaytext=MyNetwork name=MyNetwork networkofferingid=ecfbf039-25bf-4515-83ed-4cf923ba26de zoneid=e02cb5c3-f987-443f-ab1a-0799b0c83f80
🙈 Error: (HTTP 530, error code 4390) Provider ConfigDrive is either not enabled or doesn't support service UserData in physical network id=201

**Comment by weizhouapache** [comment]
> /snap/bin/cmk create network displaytext=MyNetwork name=MyNetwork networkofferingid=ecfbf039-25bf-4515-83ed-4cf923ba26de zoneid=e02cb5c3-f987-443f-ab1a-0799b0c83f80 🙈 Error: (HTTP 530, error code 4390) Provider ConfigDrive is either not enabled or doesn't support service UserData in physical network id=201

@ahmadamirahmadi007 
can you go the zone -> physical networks -> select the guest physical networks -> Network service providers -> ConfigDrive -> Enable provider ?

**Comment by ahmadamirahmadi007** [comment]
![image](https://github.com/apache/cloudstack/assets/104001728/137eccf2-3fb1-4f1f-9851-746e5209aaa2)

no thats disable

**Comment by weizhouapache** [comment]
> @ahmadamirahmadi007
> can you go the zone -> physical networks -> select the guest physical networks -> Network service providers -> ConfigDrive -> Enable provider ?

@ahmadamirahmadi007
can you go the zone -> physical networks -> select the guest physical networks -> Network service providers -> ConfigDrive -> Enable provider ?

**Comment by ahmadamirahmadi007** [comment]
.Thank you very very much. my problem solved.
