### ISSUE TITLE
 Creation of large files with vmdk format in secondary storage-CloudStack 4.17.2.0

### ISSUE THREAD

**Issue by yeganehmehr** [apache/cloudstack#8348]
##### ISSUE TYPE

 * Bug Report

 * Other

##### COMPONENT NAME
 UI
##### CLOUDSTACK VERSION
CloudStack 4.17.2.0
##### CONFIGURATION
advanced networking
##### OS / ENVIRONMENT
scst :CentOS release 6.10 (Final)

##### SUMMARY
In the path, subfiles with a large volume have been created, whose names do not exist in any of the Cloudstack database tables.
Can these files be deleted?
Because the disk consumption of this partition has greatly increased.

/storage/volumes/

[root@SCST01 23f81482c9674916bb5061df06eb244d]# ls -lha
total 83G
drwxr-xr-x 2 root root 4.0K Dec 11 10:06 .
drwxr-xr-x 9 root root 4.0K Dec 11 11:27 ..
-rw-r--r-- 1 root root  83G Dec 11 01:13 23f81482c9674916bb5061df06eb244d-disk0.vmdk

##### STEPS TO REPRODUCE
[root@SCST01 ~]# df -hT
Filesystem           Type   Size  Used Avail Use% Mounted on
/dev/sdb1            ext4   1.5T  1.3T  128G  91% /storage

##### EXPECTED RESULTS
Recently, 500 GB disk was added to the server, but it used all the volume

**Comment by rajujith** [comment]
@yeganehmehr  I assuming this storage you are referring here is the primary storage? you could find the volume in the DB using: 

`select * from volumes where path='23f81482c9674916bb5061df06eb244d'\G`

**Comment by yeganehmehr** [comment]
@rajujith 

this storage is secondary storage 

MariaDB [cloud]> select * from volumes where path='23f81482c9674916bb5061df06eb244d'\G
Empty set (0.054 sec)

**Comment by yeganehmehr** [comment]
@rajujith 
  and  again start use  my disk 
/dev/sdb1            ext4   2.0T  1.6T  271G  86% /storage

**Comment by rajujith** [comment]
@yeganehmehr  volumes in the secondary storage information can be found in table "volume_store_ref"

**Comment by DaanHoogland** [comment]
@yeganehmehr take care when considdering storage used by vmware. It can create snapshots of volumes in use without knowledge of cloudstack. If you do not know what you are doing, deleting those may lead to data loss.

**Comment by rohityadavcloud** [comment]
I think the question has been answered; these files can be related to data disks, snapshots or linked entities. Unless you know what they are and are absolutely sure you shouldn't delete them. Via vCenter one can check if those files are related to the VM somehow and only take a call to delete them. One solution could be to migrate the VM off a datastore, double check the VM has no volume or VM snapshots, VM in vCenter has no snapshots and then remove delete the remaining files in the folder (but not ideal).
