### ISSUE TITLE
ConsoleProxy: Fail to Access VM via port forwarding

### ISSUE THREAD

**Issue by tampler** [apache/cloudstack#8349]
##### ISSUE TYPE

 * Networking
 * Debug
 * Documentation Report

##### COMPONENT NAME

~~~
Core, Network, Debug, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### CONFIGURATION

Advanced zone with VPC
![Network setup](https://github.com/apache/cloudstack/assets/2816743/ffca5078-d50e-4e25-9aac-9f481ddf8eba)

![Forward setup](https://github.com/apache/cloudstack/assets/2816743/83c99601-637a-452b-b20a-0aff28a9061d)

![System VM](https://github.com/apache/cloudstack/assets/2816743/c21f3f2c-16eb-4547-82f0-6103bfd16950)

![Virtual Router](https://github.com/apache/cloudstack/assets/2816743/9c422456-8bd3-4a0e-bad4-2fd026289fa9)

![Access Error](https://github.com/apache/cloudstack/assets/2816743/27b90654-8f73-4b81-82e2-8f3d22a20247)

Bridge config
```sh
    br1:
      interfaces: [enp1s0f1]
      addresses: [192.168.1.4/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
          on-link: true
      nameservers:
        addresses:
          - xxx.yyy.93.93
          - xxx.yyy.92.92
```

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

Using an external `router` device to route traffic in ACS. CloudStack is running on the private network `192.168.1.0/24` with Source NAT enabled.
Hypervisor is using only `one` bridge `br1` to route all traffic types in the `192.168.1.0/24` network.

```
> cat ./agent.properties
private.network.device=br1
guest.network.device=br1
public.network.device=br1
```
I was able to successfully config VPC and a private subnet and launch `Alpine Linux` VM. Now I need to route traffic into it to proceed with my VM

##### STEPS TO REPRODUCE

~~~
1. Install ACS 4.19.0.0 with an Advanced Zone
2. Create a VPC and a subnet
3. Launch `Alpine Linux` VM in the private subnet
4. Click on `Console Proxy` to allow VNC screen
5. Enable port forwarding to console proxy: `ssh -L 2220:<remote public IP>:<80>
6. Check VNC connection:

> curl http://localhost:2220/resource/noVNC/vnc.html\?autoconnect\=true\&port\=8080\&token\=MSY5R/tXOxtp7MKoxOTiZJTG1cwTmWhzj3JVqvwmy1aBBGYLS04sfwYGGX70Yh6w8JT1EBqr7ZavvYLnIeK4CJsmDrhoCn1EHAKhR1U/XZ2cIcT7mKjzw9wkcQIi3YAQXhmqRFPJ41EskEdcBE40+qouQYchsrG397c7HEyzg+t2ITknryu5IJNMEY3QfrkMmkN5ag2H/0t+d19cRI1jUNbOAGdchYFbExR2d2xqkwtvCn8awehXwC3xsuPxPk+y/5Ec+AArtMKW5P8uqPsBJ2xmzaJ+PfmgT+niDDuz8XmRBOKCOYnyC31CDf2JXMOpX4S56F0duIjDUDhYKR0y8ETQ4rs1LsEJPglWvz+Md4dareUMzjqbeYvnOTiEmYjmXkERTQi/O6l5cyJN0tyDgeIvQRI6PHWmq7UaULsyj2UDHPFQO1qJEn+UTXGW3lvMqQCbtb/NwGlfWFvwhoS/4w44ewd5N/oLFN6PsSnNMmmPPdXxlwK3Ut++9XpvyhIzvdqyX5OuH5gUNCxWxwzZKsPdqA\=\=
curl: (7) Failed to connect to localhost port 2220 after 0 ms: Connection refused

~~~

##### EXPECTED RESULTS

~~~
Login via Console Proxy to my VM
~~~

##### ACTUAL RESULTS

~~~
Error in connection establishment: net::ERR_CONNECTION_REFUSED
~~~

**Comment by tampler** [comment]
@weizhouapache 
Hello Wei. Why do you think so :roll_eyes: ? As the issue states, I can't connect Console Proxy to a working VM. Is `Console Proxy` a part of ACS package? Or NO? Thus this is a setup/config/debug/documentation issue.

Any clues? :eyes:  Let me know if you know more info about my setup

**Comment by weizhouapache** [comment]
> @weizhouapache Hello Wei. Why do you think so 🙄 ? As the issue states, I can't connect Console Proxy to a working VM. Is `Console Proxy` a part of ACS package? Or NO? Thus this is a setup/config/debug/documentation issue.
> 
> Any clues? 👀 Let me know if you need more info about my setup

@tampler 
does your  cpvm have a public IP ? if not, can you configure a public IP ?
can you access the vm console on cloudstack UI ? If yes, then this is not a cloudstack issue.

the port forwarding to CPVM is not in the scope of cloudstack functionalities.

**Comment by rajujith** [comment]
@tampler  JFYI "Netscaler VPX and MPX versions 9.3, 10.1e and 10.5 (not tested to work fine for last many CloudStack releases)" 
http://docs.cloudstack.apache.org/en/4.18.1.0/releasenotes/compat.html

**Comment by tampler** [comment]
@rajujith This issue boils down to the use case of ACS.
1. Modern large scale deployments won't allow ACS to be a front facing infrastructure unit. ACS will be hidden behind hardware (NetScaler, F5, Nicara) or software Edge/Application load balancers. 
2. IPv4 is a scarce resource and its price only keeps growing. It's expensive to get a formidable range here in Russia and virtually impossible to buy own.
3. In my case, I have ALB in front of ACS and use a subdomain routing to access it, e.g `acs.example.com/ui -> cloudstack.ip.local:8080/client` 
4. In my case, I have ALB in front of ACS and use RFC 1918 for all ACS ranges, including `public`. 
That's why `CPVM` link looks like this: `http://192.168.1.21/resource/noVNC/vnc.html?autoconnect=true&port=8080&token=oW2Df...` which can't connect to an application VM in a `vpc subnet`

My network map looks like below. I imaging similar setup to be used in most modern deployments with limited IPv4 range, server and cloud resources
![netmap](https://github.com/apache/cloudstack/assets/2816743/6866d7ac-f1c2-4932-8261-73c279f0b290)

**Comment by Anxbbq** [comment]
> @rajujith This issue boils down to the use case of ACS.
> 
> 1. Modern large scale deployments won't allow ACS to be a front facing infrastructure unit. ACS will be hidden behind hardware (NetScaler, F5, Nicara) or software Edge/Application load balancers.
> 2. IPv4 is a scarce resource and its price only keeps growing. It's expensive to get a formidable range here in Russia and virtually impossible to buy own.
> 3. In my case, I have ALB in front of ACS and use a subdomain routing to access it, e.g `acs.example.com/ui -> cloudstack.ip.local:8080/client`
> 4. In my case, I have ALB in front of ACS and use RFC 1918 for all ACS ranges, including `public`.
>    That's why `CPVM` link looks like this: `http://192.168.1.21/resource/noVNC/vnc.html?autoconnect=true&port=8080&token=oW2Df...` which can't connect to an application VM in a `vpc subnet`
> 
> My network map looks like below. I imagine a similar setup to be used in most modern deployments with limited IPv4 range, server and cloud resources ![netmap](https://private-user-images.githubusercontent.com/2816743/290516545-6866d7ac-f1c2-4932-8261-73c279f0b290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzQxOTcsIm5iZiI6MTcwMjYzMzg5NywicGF0aCI6Ii8yODE2NzQzLzI5MDUxNjU0NS02ODY2ZDdhYy1mMWMyLTQ5MzItODI2MS03M2MyNzlmMGIyOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDk1MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU5OTE1MmFkNzBlMmFiOTI2MDA2OWJiYjEwMGFhN2ZlZjEwNjA2ZWUyY2I2OTljM2FiMjZmMTkyNmIzNzI2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wYs3TfNyjWQ5jf00UnVdWBMnXgvuX3KaPpKf_W01yDs)

I deployed cloudstack on a remote machine, and allocated private IP to the vms, and i cant access the vm console through UI on my own computer. Now I have solved this using nginx to proxy noVnc and websocket in consoleProxy.

**1**，change the port of management-server to 8088（anyone else except 8080，because the websocket in CPVM use this port as default）
**2**, config the nginx （server part） like，

`


    server {
        listen 8080;
        server_name  acs.example.com;

        location /websockify {
                proxy_pass http://192.168.xxx.xxx:8080/websockify;  # IP address of  Console Proxy
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;
                proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
                proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
                proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
        }
    }
       server {
        listen       80;
        server_name  acs.example.com;
        root         /usr/share/nginx/html;

        location / {
                proxy_pass http://192.168.xxx.xxx;  # IP of Console Proxy 
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }
    }


`

**3**, edit /etc/hosts, add this,
`10.122.xxx.xxx (the public ip of the machine where the management server deployed)   asc.example.com`

**4**, if use another computer to access the vm console，make sure it can access the machine which cloudstack deployed,
then add `10.122.xxx.xxx   asc.example.com` to the computer's hosts mapping file.

**5** set the Globle param "consoleproxy.url.domain"= acs.example.com


if the configuration is correct, we can access the vm console.

**Comment by weizhouapache** [comment]
@tampler 
can you try @Anxbbq 's configuration and close this issue if it works ?

**Comment by tampler** [comment]
@weizhouapache  Sure will do! brb soon to this :+1:

**Comment by tampler** [comment]
Worked for me! Thanks for sharing your solution @Anxbbq
