### ISSUE TITLE
Kubernetes VM don't have internet connection

### ISSUE THREAD

**Issue by raihanjp** [apache/cloudstack#8351]
##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME
~~~
CloudStack Kubernetes Provider
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1
~~~

##### OS / ENVIRONMENT
Ubuntu 22.04

##### SUMMARY
Can't pull any image

Failed to pull image "registry.k8s.io/metrics-server/metrics-server:v0.6.4": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/metrics-server/metrics-server:v0.6.4": failed to resolve reference "registry.k8s.io/metrics-server/metrics-server:v0.6.4": failed to do request: Head "https://registry.k8s.io/v2/metrics-server/metrics-server/manifests/v0.6.4": dial tcp: lookup registry.k8s.io on 8.8.8.8:53: read udp 10.1.1.231:39706->8.8.8.8:53: i/o timeout

Ping from control node
cloud@skripsi-control-18c618bc8bd:$ ping -c 1 google.com
ping: unknown host
cloud@skripsi-control-18c618bc8bd:$ ping -c 1 registry.k8s.io
ping: unknown host

##### STEPS TO REPRODUCE
Fresh kubernetes cluster installation
Kubernetes version: https://download.cloudstack.org/testing/cks/setup-1.27.8.iso
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

##### EXPECTED RESULTS
~~~
metrics-server-5d875656f5-flz97                       1/1     Running 
~~~

##### ACTUAL RESULTS
~~~
metrics-server-5d875656f5-flz97                       0/1     ImagePullBackOff
~~~

**Comment by weizhouapache** [comment]
@raihanjp 

which type of zone (basic/advanced/advanced with security group) and network (isolated, vpc tier, shared) do you use ?

can you run the same ping commands from CloudStack virtual router of the network ?

**Comment by raihanjp** [comment]
@weizhouapache 
-I'm using advanced zone and DefaultNetworkOfferingforKubernetesService which is isolated. 

-Still can't ping when i ran the same ping commands on the virtual router of the network

**Comment by raihanjp** [comment]
I installed cloudstack exactly following this tutorial https://rohityadav.cloud/blog/cloudstack-kvm/ adapt with my network configuration

**Comment by weizhouapache** [comment]
> @weizhouapache -I'm using advanced zone and DefaultNetworkOfferingforKubernetesService which is isolated.
> 
> -Still can't ping when i ran the same ping commands on the virtual router of the network

@raihanjp 
what's the default egress policy ? is there any egress rules ?
can you ping the gateway of public IPs in the virtual router ?

**Comment by raihanjp** [comment]
@weizhouapache 
- The default egress policy is **allow** and there's no any egress rules
- I can't ping the gateway of the public IP, but i can ping 8.8.8.8
![Screenshot 2023-12-13 150003](https://github.com/apache/cloudstack/assets/70987108/08b7bd78-ada5-4f71-9e79-c1d987d7ab14)

![Screenshot 2023-12-13 150108](https://github.com/apache/cloudstack/assets/70987108/85a8f355-6cf9-48cd-9c23-5d86f34877f6)

![Screenshot 2023-12-13 150203](https://github.com/apache/cloudstack/assets/70987108/fea50bf7-798a-42db-b18e-0df223e4ce4f)

**Comment by weizhouapache** [comment]
> @weizhouapache
> 
> * The default egress policy is **allow** and there's no any egress rules
> * I can't ping the gateway of the public IP, but i can ping 8.8.8.8

@raihanjp 
all looks good.
now the problem is, you can ping 8.8.8.8, but not for google.com, right ?

**Comment by raihanjp** [comment]
@weizhouapache 
Yes i can't ping google.com or registry.k8s.io or any domain. I want to troubleshoot this because i tought it will solve the problem i'm facing that is failed to pull image

**Comment by weizhouapache** [comment]
> @weizhouapache Yes i can't ping google.com or registry.k8s.io or any domain. I want to troubleshoot this because i tought it will solve the problem i'm facing that is failed to pull image

It looks like a DNS issue
Do you use 8.8.8.8 as the dns server ?

**Comment by raihanjp** [comment]
Yes, i use 8.8.8.8 as the dns server
![Screenshot 2023-12-13 154618](https://github.com/apache/cloudstack/assets/70987108/883b0c74-415a-425c-bc86-1598ff07ead4)

**Comment by raihanjp** [comment]
if my systemvm can ping google.com and registry.k8s.io, the problem must be on the kubernetes cluster creation process right? or  do you think there could be a misconfiguration on the apache cloudstack installation?

**Comment by weizhouapache** [comment]
> if my systemvm can ping google.com and registry.k8s.io, the problem must be on the kubernetes cluster creation process right? or do you think there could be a misconfiguration on the apache cloudstack installation?

ping/dns should work in the CloudStack virtual router (it is not in the scope of CKS configuration)

can you run more commands in the VR ?
```
cat /etc/resolv.conf
nslookup google.com
```

**Comment by raihanjp** [comment]
the resolv.conf only have this and nslookup can't ping google.com
~~
nameserver 8.8.8.8
~~
i added 
~~
nameserver 192.168.10.1
~~
finally the VR can ping and nslookup google.com, but the VR itself is not pingable and it can't ping it's own ip address. and the kubernetes still can't pull the image, i've tried with other image and it still has the same error. (s-1-vm = system VM & r-11-VM = VR)

Does this ip route on the system vm and the VR matter? the VR name changed from the last image i post after i reboot the VR
![Screenshot 2023-12-13 172027](https://github.com/apache/cloudstack/assets/70987108/0ae68ca6-6efb-4286-a04a-c12c9cd441af)
![Screenshot 2023-12-13 172045](https://github.com/apache/cloudstack/assets/70987108/73554c08-fdc7-47d3-b138-4ed1084b1724)

**Comment by weizhouapache** [comment]
@raihanjp 
you can add `192.168.10.1` as a dns server in the zone setting.

when you add nameserver in /etc/resolv.conf manually , please restart dnsmasq service in VR and retry.

**Comment by raihanjp** [comment]
- do you mean this by adding the dns server in the zone setting? And should the use.external.dns in the global setting set to "true"?
- i've restart dnsmasq service in VR, i just noticed if i reboot the VR, the config on resolv.conf is back to default only "nameserver 8.8.8.8"
![Screenshot 2023-12-13 193506](https://github.com/apache/cloudstack/assets/70987108/af43cbe6-2da4-4874-a148-9bd1baf8295a)

**Comment by weizhouapache** [comment]
> * do you mean this by adding the dns server in the zone setting? And should the use.external.dns in the global setting set to "true"?
> * i've restart dnsmasq service in VR, i just noticed if i reboot the VR, the config on resolv.conf is back to default only "nameserver 8.8.8.8"

@raihanjp 
for existing networks, you can update the DNS1 and DNS2 in the networt details.

Did it work after you added nameserver and restarted dnsmasq ?

**Comment by raihanjp** [comment]
@weizhouapache
after adding the nameserver and restart dnsmasq it just work when pinging google.com from the VR, but the kubernetes vm still can't ping google.com. the configuration of the resolv.conf revert to the default too thats "nameserver 8.8.8.8" only, if the VR is rebooted. 

Currently i'm reinstalling my ubuntu (including cloudstack management), because previously I had successfully used a Kubernetes cluster without problems, but something happened that caused the server to have to be factory reset. I'll get back to you with the update. Thankyou so muchweizhou

**Comment by raihanjp** [comment]
@weizhouapache 
hello, i'm here to update the progress. so last night i reinstall ubuntu and cloudstack management, last night the problem is still the same, i rerun the same process to reproduce the problem. I try creating the k8s cluster using this ISO https://download.cloudstack.org/testing/cks/, i tried both 1.27.8 and 1.28.4 and faced the same problem, the k8s node can't ping google.com and the VR can't ping google.com too, i didn't change any settings at all, so i turned off the server last night. this morning when i turned on the server i didn't face any problem and i didn't change any settings. Now i can ping google.com from my VR and VM, and my VM can already pull any image. I really don't know where the problem is. Thank you very much for your help

**Comment by weizhouapache** [comment]
> @weizhouapache hello, i'm here to update the progress. so last night i reinstall ubuntu and cloudstack management, last night the problem is still the same, i rerun the same process to reproduce the problem. I try creating the k8s cluster using this ISO https://download.cloudstack.org/testing/cks/, i tried both 1.27.8 and 1.28.4 and faced the same problem, the k8s node can't ping google.com and the VR can't ping google.com too, i didn't change any settings at all, so i turned off the server last night. this morning when i turned on the server i didn't face any problem and i didn't change any settings. Now i can ping google.com from my VR and VM, and my VM can already pull any image. I really don't know where the problem is. Thank you very much for your help

@raihanjp 
some changes might be applied after rebooting
For example, when you update the DNS setting of the network, you need to restart the VR to make the config effective.

**Comment by raihanjp** [comment]
@weizhouapache 
Here to update again. I kept facing the same issue when creating a new k8s cluster. I've solved the issue that works everytime for me. Before, the guest network only use DNS1 = 8.8.8.8

To solve the issue, i add the dns on the guest network so it use DNS 1=1.1.1.1 and DNS 2=8.8.8.8
