### ISSUE TITLE
Cannot create primary on StorPool

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#8352]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Primary storage plugin
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### SUMMARY

Creating primary storage on StorPool is impossible because the URL needed is not valid. I checked that a few storage plugins could be affected as well (according to the code), like SolidFire, Nexenta and Cloudbyte (Elastisitor). 
The issue is caused by this change [PR 6699](https://github.com/apache/cloudstack/pull/6699/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R783)

I could fix it for StorPool but I think there is a need to be tested for those Storage drives mentioned above and to deliver a general fix.

##### STEPS TO REPRODUCE

create primary storage from UI/CLI

##### EXPECTED RESULTS

~~~
successfully created a storage pool
~~~

##### ACTUAL RESULTS

~~~
SP_API_HTTP=10.2.23.1:81;SP_AUTH_TOKEN=4343423;SP_TEMPLATE=ssd2 is not a valid uri
~~~

**Comment by weizhouapache** [comment]
this looks like a blocker issue

should we revert the commit ? @shwstppr @DaanHoogland @slavkap @rohityadavcloud

**Comment by shwstppr** [comment]
@weizhouapache I feel let's do some code investigation before we go about the revert
@slavkap is it possible for you to highlight the specific code from the PR that is causing the issue?

**Comment by slavkap** [comment]
@shwstppr, it fails [here](https://github.com/apache/cloudstack/pull/6699/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R899) when trying to create URI from the URL string

>     public static UriInfo getUriInfo(String url) {
>         try {
>             if (url == null) {
>                 return new UriInfo();
>             }
>             if (url.startsWith("rbd://")) {
>                 return getRbdUrlInfo(url);
>             }
>             URI uri = new URI(UriUtils.encodeURIComponent(url));
>             return new UriInfo(uri.getScheme(), uri.getHost(), uri.getPath(), uri.getUserInfo(), uri.getPort());
>         } catch (URISyntaxException e) {
>             throw new CloudRuntimeException(url + " is not a valid uri");
>         }
>     }

**Comment by weizhouapache** [comment]
> @shwstppr, it fails [here](https://github.com/apache/cloudstack/pull/6699/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R899) when trying to create URI from the URL string
> 
> > ```
> > public static UriInfo getUriInfo(String url) {
> >     try {
> >         if (url == null) {
> >             return new UriInfo();
> >         }
> >         if (url.startsWith("rbd://")) {
> >             return getRbdUrlInfo(url);
> >         }
> >         URI uri = new URI(UriUtils.encodeURIComponent(url));
> >         return new UriInfo(uri.getScheme(), uri.getHost(), uri.getPath(), uri.getUserInfo(), uri.getPort());
> >     } catch (URISyntaxException e) {
> >         throw new CloudRuntimeException(url + " is not a valid uri");
> >     }
> > }
> > ```

@slavkap 
this code block already exists in 4.18.1.0 #6792 #7708
did you face any problem in 4.18.1.0 ? If not, I think there is no issue with this code block.

The problem might be caused by the value passed `cmd.getUrl()`

**Comment by slavkap** [comment]
@weizhouapache, there is no issue with this code snippet. The problem is that it is invoked now for each storage plugin, and not all use a valid URL. Before this PR [this part of code](https://github.com/apache/cloudstack/pull/6699/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R897) had been used only by the Default primary storage .

According to this article [SolidFire CloudStack](https://www.shapeblue.com/solidfire-with-cloudstack/#Adding_SolidFire_1_1-based_Primary_Storage-3) the URL that should be provided is not valid also and I think the SolidFire's users will have the same problem

**Comment by shwstppr** [comment]
@slavkap @weizhouapache I understand the problem is how we are creating params for initializing DataStoreLifeCycle. Some storage providers do not use a valid URL which we are trying to check in the PR change. I guess we can try to fix the `extractUriParamsAsMap` method. Let me try to draft a PR. It will be great if you guys can help review/test

**Comment by shwstppr** [comment]
@slavkap @weizhouapache I've created #8353. Let me know if the changes in it make sense
