### ISSUE TITLE
Cloudstack virtual machines can't communicate with virtual routers when they are on different hosts

### ISSUE THREAD

**Issue by herdiansah571** [apache/cloudstack#8360]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### STEPS TO REPRODUCE

~~~
I'm using Cloudstack 4.18.1.0  on a Ubuntu 22.04.3 LTS set of hosts, and I have a problem on my setup.

I have two hosts running. When a virtual router is created on host 1 and a virtual machine using that virtual router is created on host 2, I have no connectivity at all on the virtual machine. I can't ping to the virtual router from the virtual machine.


When both virtual router and virtual machine are created on the same host, everything works!

Maybe those packages are being filtered somehow? I have no clue on how to proceed. Both hosts can communicate directly outside the virtualization.
~~~

##### EXPECTED RESULTS

~~~
virtual machine can ping virtual router from different hosts
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by akkidarkhq** [comment]
i am  stucked at the same issue. my router is in host 1. 

![Screenshot 2023-12-20 102830](https://github.com/apache/cloudstack/assets/100999421/d5a36565-a684-4742-8253-e47c8fe6aeb8)

![Screenshot 2023-12-20 102855](https://github.com/apache/cloudstack/assets/100999421/c39f4192-7d3c-4c5c-b529-a4608556821d)

**Comment by DaanHoogland** [comment]
@herdiansah571 @akkidarkhq I tested this in a nested lab environment; 1 MS, 2 Hosts, all ubuntu22. It works as expected. I think there must be extra conditions in your environments that prevent this from functioning properly. Can you try to add more clues?

**Comment by weizhouapache** [comment]
this is a typical issue for new users.  same issue as #8335
you need to configure the switch ports on your physical switches.

you can get more information on google. search by keyword "Configuring VLAN Trunks"

**Comment by herdiansah571** [comment]
Hello @weizhouapache 

Currently Cloudstack virtual machines can communicate with virtual routers when they are on different hosts after configure VLAN Trunks on physical switch port. thank you for provide me an explanation

**Comment by weizhouapache** [comment]
thanks for the update @herdiansah571
