### ISSUE TITLE
Add all accounts/projects when managing templates/ISO

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#8361]
##### ISSUE TYPE

Enhancement Request

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

No relevant informations.

##### SUMMARY

It would be really useful to have the possibility to add all accounts/projects when we manage the "Update template permissions" of a ISO/Templates especially when you have a lot of accounts/projects in your environment.
Also it would be nice to have a list of the permission added in the UI.

##### STEPS TO REPRODUCE

~~~
The feature would allow to select all accounts/projects when managing permissions of a ISO/Template
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
This is not actually possible.
~~~

**Comment by DaanHoogland** [comment]
@cdfgallo that would be like making the template public. Is that enough functionality for you, or is there a nich use-case I am missing?

**Comment by cdfgallo** [comment]
@DaanHoogland I would say that is really similar except for the fact that, if a domain admin set a template/ISO as public, every user in the platform (even if not in the same domain!) which have the permission to see images, can see (but not use) it.
This would help clients to easily share images and keeping their "privacy".

**Comment by weizhouapache** [comment]
@cdfgallo 
there is a global/domain setting which restricts public template to be accessible by the domain only.
see #4774 
the config `share.public.templates.with.other.domains` is set to `true` by default. you can set to `false` for specific domains.

**Comment by cdfgallo** [comment]
> @cdfgallo there is a global/domain setting which restricts public template to be accessible by the domain only. see #4774 the config `share.public.templates.with.other.domains` is set to `true` by default. you can set to `false` for specific domains.

@weizhouapache Thant's what I was looking for, thank you very much! :)
I'm closing this fr as we already have what we need.
