### ISSUE TITLE
KVM: add new action `inject-nmi`

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8368]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
KVM
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### CONFIGURATION

KVM hypervisors

##### SUMMARY

add new action `inject-nmi`

see https://github.com/apache/cloudstack/pull/8282#issuecomment-1855522438

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
fixed by #8282
