### ISSUE TITLE
Port forwarding rules gets the same public port when creating port forwarding rules with CloudStack's API

### ISSUE THREAD

**Issue by saffronjam** [apache/cloudstack#8386]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API for Virtual Router Port forwarding rules
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1
~~~

##### CONFIGURATION
Isolated network Source NAT with redundant router

![image](https://github.com/apache/cloudstack/assets/26722370/50980a6e-1631-4e19-ac32-77bb65ddfb39)

##### OS / ENVIRONMENT
Ubuntu 22.04

My client is the Go client for CloudStack's API

##### SUMMARY
Using the API I was able to create, what I think, is a race-condition for port forwarding rules that is not handled by the API. Two port forwarding rules ended up with the same public port, even though I should have received an error such as:

"The range specified, 2502-2502, conflicts with ... ". 

![image](https://github.com/apache/cloudstack/assets/26722370/b00601bc-7f4e-4ad9-98cc-3b7a3c71d322)

##### STEPS TO REPRODUCE
~~~
Using the API create 2 port forwarding rules with same public port (for 2 different VMs in my case).
~~~

##### EXPECTED RESULTS
~~~
Conflict error, that I can handle in my client using the CloudStack API.
~~~

##### ACTUAL RESULTS
~~~
Two port forwarding rules created, with the same public port, for different VMs. Only one of them works of course.
~~~

**Comment by DaanHoogland** [comment]
@saffronjam do you have a script for this (code fragment?) and do you have a work around to get you going?

**Comment by saffronjam** [comment]
Hi Daan,
Sorry about the delay. Right now, I am unable to replicate this, and it could have been caused by some bad state in the router maybe? I will reopen this issue if I am able to reliably replicate the issue.

As a solution on our side though, we added a Mongo database layer between, with a unique index, to ensure the port forwarding rules are unique. 

You can probably close this issue for now.
