### ISSUE TITLE
Resize Root Disk | compute offering with Disk offering strictness > true

### ISSUE THREAD

**Issue by midhunpjos** [apache/cloudstack#8400]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
Compute Offerings
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

ACS 4.18.1 Hypervisor XCP-ng

##### OS / ENVIRONMENT

ACS 4.18.1 on Ubuntu Hypervisor XCP-ng

##### SUMMARY

Resizing Root Disk after VM deployment is possible after VM deployed with compute offering with Disk offering strictness as true

##### STEPS TO REPRODUCE

~~~
Create Compute Offering
set root disk size 
enable Disk offering strictness
~~~

##### EXPECTED RESULTS

~~~
Once the VM is deployed We should not be able to change ROOT volume size
~~~

##### ACTUAL RESULTS

~~~
Select Root Disk,
Select resize volume and update to higher value
Root Disk is getting upgraded to new size

~~~

**Comment by rajujith** [comment]
@midhunpjos  this property on compute offering is expected to restrict the resize volume? it is expected only to restrict changing the disk offering right? I haven't tried it myself though. 

> diskofferingstrictness
> 	True/False to indicate the strictness of the disk offering association with the compute offering. When set to true, override of disk offering is not allowed when VM is deployed and change disk offering is not allowed for the ROOT disk after the VM is deployed

**Comment by midhunpjos** [comment]
> @midhunpjos this property on compute offering is expected to restrict the resize volume? it is expected only to restrict changing the disk offering right? I haven't tried it myself though.
> 
> > diskofferingstrictness
> > True/False to indicate the strictness of the disk offering association with the compute offering. When set to true, override of disk offering is not allowed when VM is deployed and change disk offering is not allowed for the ROOT disk after the VM is deployed

@rajujith But resizing a disk almost approximates to change offering. 
Can this be considered as an enhancement?

**Comment by rajujith** [comment]
@midhunpjos  You are looking for way to restrict volume resizing?

**Comment by midhunpjos** [comment]
> @midhunpjos You are looking for way to restrict volume resizing?

Yes. Exactly. Its better to restrict the resizing too. right ?

**Comment by sureshanaparti** [comment]
@midhunpjos @rajujith Volume resize restriction check is there when disk size strictness is enabled, but not for disk offering strictness. I think, you have to enable the disk size strictness for the disk offering associated to the compute/service offering.

https://github.com/apache/cloudstack/blob/ab808995ffe76a2a308d91bbc761693538cfa0dd/server/src/main/java/com/cloud/storage/VolumeApiServiceImpl.java#L1116-L1119

**Comment by midhunpjos** [comment]
thanks @sureshanaparti for the comments. This will solve my concern..

**Comment by DaanHoogland** [comment]
closing according to submitter comment.
