### ISSUE TITLE
Can Cloudstack attach/detach disks to Windows VMs immediately like VMware?

### ISSUE THREAD

**Issue by tuanhoangth1603** [apache/cloudstack#8403]
I have tried attaching a new disk on Linux, and the Linux VM immediately recognizes the new disk. 
However, with Windows Server 2022 Standard, the new disk is not recognized. 
- I have tried accessing Disk Management to rescan, press F5 -> Unsuccessful. 
- I have also attempted to restart the VM by logging in and using the OS restart function, but it was unsuccessful. 
Therefore, I have to access the portal, click the shutdown VM button, and then start the VM for the new disk to be recognized.

I wonder if I missed something such as windows template,... and I hope you can assist me. 
I have searched for other topics or issues related to this but couldn't find any. If there is an issue addressing this, please mention it.
Thank you!

**Comment by weizhouapache** [comment]
is virtio driver installed?

**Comment by tuanhoangth1603** [comment]
Hi,
Do I need to install all features of the virtio driver?
![image](https://github.com/apache/cloudstack/assets/38004836/7eb27486-d788-4146-ace9-bf9499fa51d9)

**Comment by weizhouapache** [comment]
`Viostor` is for disk

I suggest to install `Network` as well, and change OS type to "Windows PV" then you will have better disk/network performce

**Comment by tuanhoangth1603** [comment]
Thanks for your instruction.
Can you explain more about the change OS type to "Windows PV". Where I can make the change ?

**Comment by weizhouapache** [comment]
> Thanks for your instruction. Can you explain more about the change OS type to "Windows PV". Where I can make the change ?

@tuanhoangth1603 
- go to vm details page
- edit vm, change the OS type of template  to "Windows PV"
- stop vm and start it
(if the template has virtio installed, you can change the OS type of template. otherwise, only change the vm which has virtio drivers)

**Comment by tuanhoangth1603** [comment]
@weizhouapache thank you.

Can Viostor automatically extend the OS volume on Windows? I have tried creating a template as follows:

1. Create a Windows Server 2019 VM.
2. Install Cloud Instance Manager to manage passwords.
3. Install Virtio drivers as per your instructions.
4. Power off the VM and proceed to create a template from the volume.
Afterward, I create a new VM using the recently created template with a larger volume size. However, Windows does not automatically extend the volume as it does in OpenStack.

I would greatly appreciate your assistance.
Best regards.

**Comment by tuanhoangth1603** [comment]
@weizhouapache please help me about 

> @weizhouapache thank you.
> 
> Can Viostor automatically extend the OS volume on Windows? I have tried creating a template as follows:
> 
> 1. Create a Windows Server 2019 VM.
> 2. Install Cloud Instance Manager to manage passwords.
> 3. Install Virtio drivers as per your instructions.
> 4. Power off the VM and proceed to create a template from the volume.
>    Afterward, I create a new VM using the recently created template with a larger volume size. However, Windows does not automatically extend the volume as it does in OpenStack.
> 
> I would greatly appreciate your assistance. Best regards.

@weizhouapache please help me about this case. Thank you so much!

**Comment by weizhouapache** [comment]
> 4\. Afterward, I create a new VM using the recently created template with a larger volume size. However, Windows does not automatically extend the volume as it does in OpenStack.

@tuanhoangth1603 
cloudstack only resizes the physical size of volume. (I believe it is same in openstack)
you can use powershell script to auto detect and resize partitions in windows vm.

**Comment by tuanhoangth1603** [comment]
> > 4. Afterward, I create a new VM using the recently created template with a larger volume size. However, Windows does not automatically extend the volume as it does in OpenStack.
> 
> @tuanhoangth1603 cloudstack only resizes the physical size of volume. (I believe it is same in openstack) you can use powershell script to auto detect and resize partitions in windows vm.

Openstack user Cloud-init to auto extend the OS volume on Windows. 
It seems like our CloudStack does not currently work with cloud-init. Should we consider adding this to the development milestone ?

**Comment by weizhouapache** [comment]
> > > 4. Afterward, I create a new VM using the recently created template with a larger volume size. However, Windows does not automatically extend the volume as it does in OpenStack.
> > 
> > 
> > @tuanhoangth1603 cloudstack only resizes the physical size of volume. (I believe it is same in openstack) you can use powershell script to auto detect and resize partitions in windows vm.
> 
> Openstack uses Cloud-init to auto extend the OS volume on Windows. It seems like our CloudStack does not currently work with cloud-init. Should we consider adding this to the development milestone ?

@tuanhoangth1603 
changes need to be made in cloud-init or cloudbase-init project, and also the template, but not cloudstack

**Comment by tuanhoangth1603** [comment]
Thank you very much for your enthusiastic support.
