### ISSUE TITLE
Force User to Host

### ISSUE THREAD

**Issue by omurozlu** [apache/cloudstack#8404]
force user to host
I integrated cloudstack 4.18 and VMware vcenter
How can I enable the user to create an instance on a specific host?

I did not see anything like this in the admin panel.

**Comment by rajujith** [comment]
@omurozlu  Go to the host details in the UI for a selected host and click on dedicate host to an account or domain. The user/s in the account instances will be explicitly deployed to this host.

**Comment by DaanHoogland** [comment]
@omurozlu , I am closing this as answered. Please reopen or create a new ticket if you have remaining issues.
