### ISSUE TITLE
Cloudstack should not allow to create resources with same name

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8416]
ISSUE TYPE

Enhancement/Improvement request

COMPONENT NAME

Component: UI/API/

CLOUDSTACK VERSION

Cloudstack version 4.18

SUMMARY

Cloudstack should not allow to create resources with same name

Currently, Cloudstack doesn't allow to creation of  the following resources with the same name

vm name,  ssh key pairs, User-data, affinity groups, Instance groups, projects, accounts, Domains , users , Roles , Vpn users.

For example, for vm-name it throws the following exception

![same-name](https://github.com/apache/cloudstack/assets/1401014/90336746-4637-4470-bf88-a66f48ecf4a8)

**But Cloudstack allows the creation of the following resources with the same name**

**volume, snapshot, template/Iso, Networks, VPC,  Service offerings, Kubernetes cluster**

To maintain consistency across we should not allow to create the resources if there are already  active resources with the same name

It will help the admin/user to manage the resources better

Expected behaviour

Cloudstack should validate the resource name before creating them.
It should check if any existing active resources are present before creating them. 

If they are present , cloudstack should throw a popup

**Comment by DaanHoogland** [comment]
@kiranchavala I think it shsouldn't be a problem to have resources with the same name. In some cases it is even harmful if we cannot; If users cannot see each others resources they should not get a hint that the other have a resource by a name by refusing it. There can always also be users that see both.
In addition to the security implications of not allowing it, we'll also have a backwards compatability issue if we refuse it.

**Comment by DaanHoogland** [comment]
@kiranchavala is my explanation to your satisfaction? Can we close this issue?

**Comment by kiranchavala** [comment]
@DaanHoogland  thanks for looking into it, I agree it could cause backward compatability issue .

we can close the issue
