### ISSUE TITLE
The Project toggle should be present for Userdata

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8421]
ISSUE TYPE

Enhancement/Improvement request /UI 

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18

SUMMARY

The Project toggle should be present for Userdata

Navigate to 

Compute > User Data > 

![user-data](https://github.com/apache/cloudstack/assets/1401014/c535b467-f329-4b19-8184-b3088ebadb36)

The project toggle button is present for all the resources and UI sections., we should extend it for user data also

For example

![existing project toogle button](https://github.com/apache/cloudstack/assets/1401014/4bb0de17-6734-48e7-83d8-4033fa9421ae)

**Comment by sureshanaparti** [comment]
@kiranchavala this is fixed with #8656 (in 4.19.1), please verify. thanks.

**Comment by kiranchavala** [comment]
Thanks @sureshanaparti , closing the issue
