### ISSUE TITLE
The Project toggle should be present for Buckets

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8422]
ISSUE TYPE

Enhancement/Improvement request /UI 

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.19 RC 1

SUMMARY

The Project toggle should be present for Buckets

Navigate to 

Storage > Buckets > 

![buckets](https://github.com/apache/cloudstack/assets/1401014/940ff6a2-e207-473c-af16-d11656a96f77)

The project toggle button is present for all the resources and UI sections., we should extend it for buckets  also

**Comment by DaanHoogland** [comment]
related to #8421

**Comment by sureshanaparti** [comment]
Closing this, as the fix PR got merged.
