### ISSUE TITLE
Updating the secondary storage to readonly or readwrite doesn't show in the UI (Access)

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8441]
ISSUE TYPE

Enhancement/Improvement Request/ BUG

COMPONENT NAME

Component: API/ UI

CLOUDSTACK VERSION

Cloudstack version 4.18, 

SUMMARY

Updating the secondary storage to read-only or read-write doesn't  show in the UI (Access)

**Steps to reproduce the issue** 

1. Navigate To Infrastructure > Secondary Storage 
2. Click on particular Secondary storage make it readonly.

Also, there is no event generated for this action 

Screenshots

![Screenshot 2024-01-04 at 3 20 40 PM](https://github.com/apache/cloudstack/assets/1401014/20d2778f-fc5f-4f1b-a0e1-022b879ee8e1)

![Screenshot 2024-01-04 at 3 21 06 PM](https://github.com/apache/cloudstack/assets/1401014/8688f885-882e-4d06-8090-649bd09e5c12)

**Bug part**

3. Navigate Back To Infrastructure > Secondary Storage, there is no Data under Access Column

![Access](https://github.com/apache/cloudstack/assets/1401014/4af052e0-cb2d-4019-b2bd-c0272418401d)

Backend api call
https://cloudstack.apache.org/api/apidocs-4.18/apis/updateImageStore.html

Expected behaviour 

For an Admin user,  Cloudstack should show whether the storage is in ready only or ready write status in the UI.

The respective event should also be populated

**Comment by shwstppr** [comment]
@kiranchavala cc @Pearl1594 did #8467 fixed the issue?
