### ISSUE TITLE
Provide option of disabling the vpn users 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8443]
ISSUE TYPE

Enhancement/Improvement Request

COMPONENT NAME

Component: API/ UI

CLOUDSTACK VERSION

Cloudstack version 4.18, 

SUMMARY

Provide option of disabling the vpn users 

Steps to reproduce the issue 

1. Navigate to Network > VPN Users

2. Create a vpn user

3. There is no option to disable the vpn user 

![Screenshot 2024-01-04 at 5 10 16 PM](https://github.com/apache/cloudstack/assets/1401014/d92da520-14f8-4bc4-ab09-d74c2812d9b9)

The only option present is to remove it 

It would be great if Cloudstack could follow the similar behavior of normal users of cloudstack 

![Screenshot 2024-01-04 at 5 11 20 PM](https://github.com/apache/cloudstack/assets/1401014/f11465b0-ff2b-4006-9466-4617671ef44d)

Currently, there is only removevpnuser api call 

https://cloudstack.apache.org/api/apidocs-4.18/apis/removeVpnUser.html

Expected behavior 

Cloudstack can have a disableVPNuser api call similar to 

https://cloudstack.apache.org/api/apidocs-4.18/apis/disableUser.html

**Comment by DaanHoogland** [comment]
@kiranchavala I do not see the practical use of this. If you don't need it delete it if you need it keep it. VPN users are extarnal entities in principle, and they don't own anything in the system. There is no use for keeping them around.

**Comment by kiranchavala** [comment]
Thanks @DaanHoogland closing the issue
