### ISSUE TITLE
System vm's volumes should be expunged when a primary storage is set in Maintenance Mode

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8450]
ISSUE TYPE

Enhancement/Improvement Request

COMPONENT NAME

Component: 

CLOUDSTACK VERSION

Cloudstack version 4.18, 

SUMMARY

System vm's volumes should be expunged when a primary storage is set in Maintenance Mode

Currently, the system vm volumes are set in destroyed state  and have to wait till the storage cleanup thread  runs which is 24hrs by default

Unless the systemvm's volumes are removed the primary storage can't be removed

Steps to reproduce the behavior

Example

1. Create a cloudstack enviroment with 2 Primary storages (cluster wide and zone wide) 

2. Launch a vm with root disk and data disk ( Both disks are allocated in the cluster wide primary storage)

3. Put the cluster wide storage in Maintainence Mode

5. On putting the Cluster wide storage in Maintainence Mode.

The vm goes into stopped state

6. The system vm volumes  are recreated in the Zone wide storage 

7. The system vm volumes associated with the cluster wide storage are marked in the destroyed state

Screenshots

![Screenshot 2024-01-03 at 12 02 41 PM](https://github.com/apache/cloudstack/assets/1401014/f7bd4617-d922-4229-bcc6-34e82764e7ff)

![Screenshot 2024-01-03 at 12 02 32 PM](https://github.com/apache/cloudstack/assets/1401014/5ebd1236-d0e1-48b8-a0a9-32464925ac7b)

8. Admin user who wants to remove the Cluster wide storage cannot do so unless the system vm volumes are expunged and marked as removed and it depends on the global settings paramters

storage.cleanup.interval
storage.cleanup.delay
storage.cleanup.enabled

9. This doesn't affect the vm disk as they are recreated in another active primary storage

Expected behaviour

Cloudstack should expunge the systemvm volumes instead of marking them destroyed.

As systemvm volumes genrally doesn't contain important  data.

Or we could have pop up  option asking the user if they want to expunge the systemvm volumes immediately when they put a primary storage in Maintenance mode ( some sort of configurable value)

**Comment by DaanHoogland** [comment]
@kiranchavala can I interpret this as a bug actually? volumes on a storage in maintenance are marked as destroyed. I would expect them to be either migrated or expunged indeed. This might even be an operator decision.

Enhancement or bug, I think it can go into 4.18.2, can it (cc @rajujith ) ? or is it too much of a paradigm shift for a minor version?

**Comment by rajujith** [comment]
@DaanHoogland @kiranchavala  This can be considered an improvement. On enabling maintenance on the primary storage allow optional expunge of systemVM volumes?. I am assuming it is not common to delete the primary storage in maintenance before the storage cleanup thread has run subsequently which is by default in 24 hours.

**Comment by DaanHoogland** [comment]
So what is the functionality we want here @kiranchavala @rajujith ?

I would not want an automatic expunge of all volumes on going into maintenance as the reason for the maintenance might not be removing the store from the system.

**Comment by JoaoJandre** [comment]
> @kiranchavala can I interpret this as a bug actually? volumes on a storage in maintenance are marked as destroyed. I would expect them to be either migrated or expunged indeed. This might even be an operator decision.
> 
> Enhancement or bug, I think it can go into 4.18.2, can it (cc @rajujith ) ? or is it too much of a paradigm shift for a minor version?

I think that this could go into 4.18.2, it seems like a bug to me. I cannot see a case where keeping system VMs' volumes on destroyed state would be beneficial in this situation.

**Comment by kiranchavala** [comment]
@DaanHoogland 

I would also prefer the automatic expunge of only the system VM volumes when primary storage is kept in maintenance mode.

**Comment by DaanHoogland** [comment]
fixed by #9197
