### ISSUE TITLE
When running a Windows Server 2022 virtual machine on a QEMU/KVM Host, CloudStack Instance Metrics always indicates 100% memory utilization, whereas the Windows Task Manager->Performance reports only 9% usage

### ISSUE THREAD

**Issue by shaerul** [apache/cloudstack#8453]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
CloudStack Instance Metrics (Memory)
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

Windows Server 2022 Instance on QEMU/KVM Host

##### OS / ENVIRONMENT

QEMU/KVM Installed on Ubuntu 20.04 LTS Host

##### SUMMARY

I've set up a Windows Server 2022 on a QEMU/KVM host running Ubuntu 20.04 LTS. Since the initial setup, CloudStack's Instance Metrics consistently display 100% memory utilization, contrary to the Windows Task Manager, which consistently shows only 9%. Despite installing "virtio-win-guest-tools" from "virtio-win-0.1.240.iso" on the Windows Server 2022 VM, the issue persists.

Interestingly, instances created from Ubuntu, CentOS, and Alpine Linux exhibit accurate metrics, reflecting proper allocation and usage.

Could you provide assistance in resolving this bug or problem?

<img width="955" alt="windows-mem-bug" src="https://github.com/apache/cloudstack/assets/5109336/92129c9e-245d-4bcd-acce-3984beef060b">
<img width="890" alt="windows-mem-bug-1" src="https://github.com/apache/cloudstack/assets/5109336/5a693069-e4c2-4e14-bf73-6135ec26a5e3">

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@shaerul 
Which os type do you use? 
You can try with "Windows PV"

**Comment by shaerul** [comment]
> @shaerul Which os type do you use? You can try with "Windows PV"

I am using Windows Server 2022 and installed Latest virtio-win-guest-tools from virtio-win-0.1.240.iso

**Comment by weizhouapache** [comment]
> > @shaerul Which os type do you use? You can try with "Windows PV"
> 
> I am using Windows Server 2022 and installed Latest virtio-win-guest-tools from virtio-win-0.1.240.iso
> 

What are the disk and network types  in device manager? 

If they are not virtio devices,  change os type and retry

**Comment by shaerul** [comment]
> > > @shaerul Which os type do you use? You can try with "Windows PV"
> > 
> > 
> > I am using Windows Server 2022 and installed Latest virtio-win-guest-tools from virtio-win-0.1.240.iso
> 
> What are the disk and network types in device manager?
> 
> If they are not virtio devices, change os type and retry

I have created a new Instance with virtio nicAdapter and virtio rootDiskController. Also updated Windows Server 2022 but no improvement at all.

<img width="945" alt="virtio-root-nic" src="https://github.com/apache/cloudstack/assets/5109336/4b95489d-5bd3-465b-951c-6ee6e95d1c22">
<img width="768" alt="diskcontrollers" src="https://github.com/apache/cloudstack/assets/5109336/a935b8b2-7450-42d3-be9f-12408e475a42">
<img width="769" alt="SystemDevices" src="https://github.com/apache/cloudstack/assets/5109336/d74ec945-8b1f-4e5d-84b1-ddbac402a18d">

**Comment by weizhouapache** [comment]
@shaerul 
Can you check the xml definition of the Windows vm if virtio memory balloon is enabled?

**Comment by shaerul** [comment]
> @shaerul Can you check the xml definition of the Windows vm if virtio memory balloon is enabled?

It appears to be present,

    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>

I have attached herewith the entire dumpxml for your convenience. Thanks.

[i-2-121-VM.txt](https://github.com/apache/cloudstack/files/13851469/i-2-121-VM.txt)

**Comment by weizhouapache** [comment]
> > @shaerul Can you check the xml definition of the Windows vm if virtio memory balloon is enabled?
> 
> It appears to be present,
> 
>     <memballoon model='virtio'>
>       <alias name='balloon0'/>
>       <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
>     </memballoon>
> 
> I have attached herewith the entire dumpxml for your convenience. Thanks.
> 
> [i-2-121-VM.txt](https://github.com/apache/cloudstack/files/13851469/i-2-121-VM.txt)
> 
> 
>   

Can you add the following line to agent.properties,  restart cloudstack-agent, and  stop/start vm? 

vm.memballoon.stats.period=5

**Comment by shaerul** [comment]
> > > @shaerul Can you check the xml definition of the Windows vm if virtio memory balloon is enabled?
> > 
> > 
> > It appears to be present,
> > ```
> > <memballoon model='virtio'>
> >   <alias name='balloon0'/>
> >   <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
> > </memballoon>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have attached herewith the entire dumpxml for your convenience. Thanks.
> > [i-2-121-VM.txt](https://github.com/apache/cloudstack/files/13851469/i-2-121-VM.txt)
> 
> Can you add the following line to agent.properties, restart cloudstack-agent, and stop/start vm?
> 
> vm.memballoon.stats.period=5

This function performed like a enchanting charm. I'm now obtaining the accurate outcome. Thaks a lot.

Should I add this line to all of my KVM hosts' agent.properties, restart cloudstack-agent, and stop/start Windows VMs?

<img width="272" alt="solved-memory-metrics-for-windows-server-2022" src="https://github.com/apache/cloudstack/assets/5109336/67485b1f-65ba-4edc-a754-d823d20e1355">

**Comment by weizhouapache** [comment]
> This function performed like a enchanting charm. I'm now obtaining the accurate outcome. Thanks a lot.
> 
> Should I add this line to all of my KVM hosts' agent.properties, restart cloudstack-agent, and stop/start Windows VMs?

yes @shaerul 

I have faced the issue in the past that Windows VM was frozen after live migration if memory ballooning is enabled. Not sure if the issue still exists with recent kvm/libvirt. Please test it fully if you want to enable it in your production.

**Comment by shaerul** [comment]
> > This function performed like a enchanting charm. I'm now obtaining the accurate outcome. Thanks a lot.
> > Should I add this line to all of my KVM hosts' agent.properties, restart cloudstack-agent, and stop/start Windows VMs?
> 
> yes @shaerul
> 
> I have faced the issue in the past that Windows VM was frozen after live migration if memory ballooning is enabled. Not sure if the issue still exists with recent kvm/libvirt. Please test it fully if you want to enable it in your production.

After the key-value entry in agent.properties of all KVM hosts I have tested live migration in 5 hosts respectively across two clusters. Everything worked seamlessly. No frozen VMs, malfunctioning or memory metrics problem.

**Comment by shaerul** [comment]
This has been resolved and I am closing this issue with thanks to @weizhouapache
