### ISSUE TITLE
Recommended CSP for Cloudstack

### ISSUE THREAD

**Issue by ngrosc** [apache/cloudstack#8457]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
API & UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.+
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Recommended CSP settings for cloudstack

##### STEPS TO REPRODUCE

~~~
Are there some recommendations for a proper CSP configuration, that works with Cloudstack and that is compliant with "CSP best practices"?
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
Not sure if anybody looked at this before @ngrosc . Do you have any input so far?

**Comment by rohityadavcloud** [comment]
@ngrosc you may find this useful - https://bitworks.software/2018-08-23-cloudstack-global-variables-atlas-system.html however most admins should experiment and tune through the variety of global settings they want. There's usually not a default "default" that might work for everyone.
