### ISSUE TITLE
Without any configuration in the vpc network, instances in different layers can actually communicate with each other! ! !

### ISSUE THREAD

**Issue by ifup-ens192** [apache/cloudstack#8459]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC network
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.18.1
~~~

##### CONFIGURATION

~~~
advanced networking
~~~

##### OS / ENVIRONMENT

~~~
CentOS 7.9
~~~

##### SUMMARY

Under the newly created VPC network, even without any configuration. Instances located in different layers can still communicate with each other at will.

##### STEPS TO REPRODUCE

The following is my entire operation process. First, create a new vpc network.
![image](https://github.com/apache/cloudstack/assets/128039494/f48f2bee-1bb0-4d98-8b80-4a7f17732dc2)

Use default network scheme and default ACL rules

![image](https://github.com/apache/cloudstack/assets/128039494/264935b6-7f80-4f97-9624-28c696a405ac)

The same goes for the other one

![image](https://github.com/apache/cloudstack/assets/128039494/7027150e-4ae9-4a80-ba6c-3f85b4c1d9d9)

This is the network plan I just checked. This is the network plan that comes with acs. I have not made any modifications.

![image](https://github.com/apache/cloudstack/assets/128039494/846ffdaf-9164-490f-92b1-7bfa9de72ba6)

Next I use the vpc network I just created to create two instances

![image](https://github.com/apache/cloudstack/assets/128039494/0b270b22-0a94-44c5-91d3-7936f4523fd8)
![image](https://github.com/apache/cloudstack/assets/128039494/534ef8b7-1908-4a81-a873-2c61cce02bcb)

##### EXPECTED RESULTS

As expected, the two instances should not be able to ping each other, but the actual situation is the opposite.

##### ACTUAL RESULTS

Enter the instance from the console and ping the IP addresses of the two machines.

![image](https://github.com/apache/cloudstack/assets/128039494/7871fbf6-9c0f-480d-b52a-ca006070fcb3)
![image](https://github.com/apache/cloudstack/assets/128039494/2173df2b-73e7-4c12-b215-2801538031d7)

Finally, attach a screenshot of the virtual router. Its status is normal.

![image](https://github.com/apache/cloudstack/assets/128039494/86dc6b60-6896-4207-b791-56ba1c268bc1)

**Comment by ifup-ens192** [comment]
![image](https://github.com/apache/cloudstack/assets/128039494/b62cbd90-ab84-423a-91fd-21082894b8c3)

**Comment by weizhouapache** [comment]
@ifup-ens192 
you can create a network ACL and assign to the vpc tiers

`default_allow` allows all incoming/outoging traffic from/to other vpc tiers , and also public internet if there are static nat/lb/pf.
