### ISSUE TITLE
Import instances from VMware into a KVM cluster fails

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8473]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM import
~~~

##### CLOUDSTACK VERSION

~~~
cloudstack-management-4.19.0.0-SNAPSHOT.20240109
~~~

##### OS / ENVIRONMENT

Rocky 8 KVM

##### SUMMARY

After the virt-v2v has converted the VMware VM, management server fails the VM import operation into KVM with the below error:

```
2024-01-09 07:32:18,036 ERROR [o.a.c.v.UnmanagedVMsManagerImpl] (API-Job-Executor-3:ctx-5f472c22 job-56 ctx-71211ae9) (logid:d2274e91) Error importing VM: Unable to look up template by id 202
com.cloud.exception.InvalidParameterValueException: Unable to look up template by id 202
        at com.cloud.vm.UserVmManagerImpl.commitUserVm(UserVmManagerImpl.java:4478)
        at com.cloud.vm.UserVmManagerImpl.importVM(UserVmManagerImpl.java:8230)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```
##### STEPS TO REPRODUCE

~~~
1. Add an existing VMware DC with VMs to a zone with KVM cluster.
2. Import an unamanaged instance from VMware to KVM.
~~~

**Comment by shwstppr** [comment]
Marking this for 4.19.0 milestone as it is a bug with one of the major new features.
This seems similar to https://github.com/apache/cloudstack/issues/8432
I guess we need to either remove https://github.com/apache/cloudstack/blob/main/server/src/main/java/org/apache/cloudstack/vm/UnmanagedVMsManagerImpl.java#L1114-L1116 or refactor the check to prevent further issues.

@nvazquez

**Comment by DaanHoogland** [comment]
@nvazquez , might this be the same issue as https://github.com/apache/cloudstack/pull/8433#issuecomment-1878475879 , not being able to add a VM due to root disk size being to small?
