### ISSUE TITLE
Managed VMware instances are listed as unmanaged for Import instances from VMware into a KVM cluster

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8474]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM import
~~~

##### CLOUDSTACK VERSION

~~~
cloudstack-management-4.19.0.0-SNAPSHOT.20240109
~~~

##### SUMMARY

UI lists the managed VMware instances under the unmanaged tab in UI for Import instances from VMware into a KVM cluster.

![Screenshot 2024-01-09 at 2 30 23 PM](https://github.com/apache/cloudstack/assets/5229147/13c9b656-61c5-4dd5-ad90-8e08fe30dcf4)

##### STEPS TO REPRODUCE

~~~
1. Add an existing VMware DC with VMs to a zone with KVM cluster.
2. Click on [Import-Export Instances], select action 'Migrate existing instances to KVM'
~~~

**Comment by shwstppr** [comment]
Did some investigation for this. This seems to be an API issue and not just UI. `listVmwareDcVms` seems to be returning all VMs in the VMware DC and not filtering managed instances.
Marking it for 4.19.0 milestone for now

**Comment by shwstppr** [comment]
@nvazquez we may need some fix here

**Comment by DaanHoogland** [comment]
@rajujith @shwstppr , I actually think this issue is not a bug. Whether instances from vmware can be imported into KVM has no relevance to whether these are already managed as vmware instances.

**Comment by rajujith** [comment]
> @rajujith @shwstppr , I actually think this issue is not a bug. Whether instances from vmware can be imported into KVM has no relevance to whether these are already managed as vmware instances.

Its incorrect to list the 'managed' the instances under the name 'unmanaged'

**Comment by borisstoyanov** [comment]
is this really a bug? I think this is an expected behaviour since the tool multifunctions as both import and migrate instances either in or out of cloudstack.

**Comment by DaanHoogland** [comment]
@nvazquez , maybe "candidate instances" or some other "candidat ..."?

**Comment by shwstppr** [comment]
> Hi guys, sorry I was delaying my response on this issue to gather more comments, but I'm also in line with it not being a bug. Perhaps @rajujith you suggest to rename the table name from 'Unmanaged' to another to avoid confusion?

Instances look fine to me
![Screenshot from 2024-01-10 16-54-53](https://github.com/apache/cloudstack/assets/153340/88820021-513a-4532-a10c-0b9647d2c201)

**Comment by rajujith** [comment]
> > Hi guys, sorry I was delaying my response on this issue to gather more comments, but I'm also in line with it not being a bug. Perhaps @rajujith you suggest to rename the table name from 'Unmanaged' to another to avoid confusion?
> 
> Instances look fine to me 

Yes renaming is fine.
