### ISSUE TITLE
Cloudstack 4.18.1.0 local storage volume snapshot changed

### ISSUE THREAD

**Issue by kaizouk** [apache/cloudstack#8477]
Hi,

It seems that volume snapshot changed into primary storage instead of secondary storage.

Is there somewhere option to change this (back) to secondary storage? I havent find option in global settings .

There is only option to copy snapshot from primary to secondary. Is only way to mount secondary to primary suitable (saving primary storage disk space)? (this is a dirty trick)

Regards
Mikko

##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by GutoVeronezi** [comment]
@kaizouk, if you are using KVM, refer to the following workflow to understand how volume snapshots work on ACS:
![image](https://github.com/apache/cloudstack/assets/38945620/32a68509-9a88-4276-ac06-290e4bd19a29)

Please, check if the global setting `snapshot.backup.to.secondary` is set as `true`.

**Comment by kaizouk** [comment]
ok, I didnt notice that fortunately if snapshot.backup.to.secondary = true then the volume snapshot will be removed from primary storage when backup into secondary is done (so this is move actually in the end). But there is no option anymore to take volume snapshot straight to the secondary as it was before? I have to consider then this dirty trick what i mentioned.

**Comment by GutoVeronezi** [comment]
> ok, I didnt notice that fortunately if snapshot.backup.to.secondary = true then the volume snapshot will be removed from primary storage when backup into secondary is done (so this is move actually in the end). But there is no option anymore to take volume snapshot straight to the secondary as it was before? I have to consider then this dirty trick what i mentioned.

Actually, ACS always stored the volume snapshot on the primary storage first and then copied it to the secondary storage :smile:. The catch is that, before 4.17, ACS was taking a full VM snapshot and saving it internally in the root disk (which is in the primary storage); then, it would extract the snapshot to the secondary storage. Following there is the previous workflow:

![image](https://github.com/apache/cloudstack/assets/38945620/62257297-44ff-4d50-9851-290949bcc18b)

You can also check issue #5124 for reference.

**Comment by kaizouk** [comment]
Many Thx  GutoVeronezi . I wondering why I didnt notice this kind of catch before. This is indeed true what you wrote! I close this now!

In return I can tell you that there is some important thing with 4.18.1.0 KVM cloudstack agent. With Ubuntu 18.04 LTS you have to ie symlink /bin/hostname ->/usr/bin/hostname that agent works!  I didnt find this info from anywhere.

**Comment by weizhouapache** [comment]
> Many Thx GutoVeronezi . I wondering why I didnt notice this kind of catch before. This is indeed true what you wrote! I close this now!
> 
> In return I can tell you that there is some important thing with 4.18.1.0 KVM cloudstack agent. With Ubuntu 18.04 LTS you have to ie symlink /bin/hostname ->/usr/bin/hostname that agent works! I didnt find this info from anywhere.

@kaizouk 
this could fix the issue  [#8310 ](https://github.com/apache/cloudstack/issues/8310#issuecomment-1853469097)
