### ISSUE TITLE
KVM: add the template UUID info in the domain XML

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#8478]
This could be used when you want to import an unmanaged VM and the user doesn't remember from which template the VM was created. It could be added as an `entry` in the `sysinfo` tag:
current state:
```
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Apache Software Foundation</entry>
      <entry name='product'>CloudStack KVM Hypervisor</entry>
      <entry name='uuid'>9f9d39da-e243-473a-b21d-3e31ea2d1cb1</entry>
    </system>
  </sysinfo>
```

with the template UUID
```
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Apache Software Foundation</entry>
      <entry name='product'>CloudStack KVM Hypervisor</entry>
      <entry name='uuid'>9f9d39da-e243-473a-b21d-3e31ea2d1cb1</entry>
     <entry name='template'>[UUID]</entry>
    </system>
  </sysinfo>
```

This will be in case the template isn't deleted from CS

##### ISSUE TYPE
 * Improvement Request
 * Enhancement Request

##### CLOUDSTACK VERSION

~~~
4.19.1.0 or 4.20
~~~

**Comment by weizhouapache** [comment]
@slavkap 
there was a feature request to add more information to the vm metadata on kvm
https://github.com/apache/cloudstack/issues/6695

**Comment by slavkap** [comment]
thanks @weizhouapache, I will close

**Comment by DaanHoogland** [comment]
@slavkap , I don't see template uuid mentioned in that feature request so  you might want to add a comment there.

**Comment by slavkap** [comment]
yes, I will add it as a comment
