### ISSUE TITLE
Please let me know how to request a full snap shot when proceeding with the snap shot.

### ISSUE THREAD

**Issue by tjkim980702** [apache/cloudstack#8493]
**Please let me know how to request a full snapshot when proceeding with the snapshot.**

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Hi @tjkim980702 , What is the underlying hypervisor used? I think, except XenServer, for other hypervisors, the full snapshot is taken.

**Comment by rohityadavcloud** [comment]
Hi @tjkim980702 there isn't any details provided for us to investigate the issue any further - for this reason I'm closing this for now. However, kindly re-open the issue if you've any further details for us.
