### ISSUE TITLE
Event state  is incorrect when Maintenance mode is Enabled/Cancelled on a Primary storage

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8495]
ISSUE TYPE

Bug

COMPONENT NAME

Component: API/ UI

CLOUDSTACK VERSION

Cloudstack version 4.18, 

SUMMARY

Event is incorrectly displayed when Maintenance mode is Enabled/Cancelled on a Primary storage

Steps to reproduce the issue 

1. Navigate to Infrastructure > Primary storage

2. Select a primary storage and enable maintenance mode  

3. The event generated for maintenance is in Scheduled state 

4. Cancel the maintenance mode on the primary storage 

5. The event generated for maintenance is in Scheduled state 

![enable-maintainence mode](https://github.com/apache/cloudstack/assets/1401014/446bad7b-3304-48a6-b9ec-0a34945104ac)

![eventmainteance ](https://github.com/apache/cloudstack/assets/1401014/68ebc72e-48a3-4bb9-9207-fe90033ff514)

![eventmaintainece2](https://github.com/apache/cloudstack/assets/1401014/f65c2444-acb5-4398-8023-645526b18e01)

```
*************************** 213. row ***************************
           id: 213
         uuid: 7816d935-2586-45d1-b98b-53e3bccc31fe
         type: MAINT.PREPARE.PS
        state: Scheduled
  description: preparing storage pool: 1 for maintenance
      user_id: 2
   account_id: 2
    domain_id: 1
  resource_id: 1
resource_type: StoragePool
      created: 2024-01-11 05:17:55
        level: INFO
     start_id: 0
   parameters: NULL
     archived: 0
      display: 1


*************************** 214. row ***************************
           id: 214
         uuid: 63683a5d-dda2-44d2-aa25-86b03f8a1de0
         type: MAINT.CANCEL.PS
        state: Scheduled
  description: canceling maintenance for primary storage pool: 1
      user_id: 2
   account_id: 2
    domain_id: 1
  resource_id: 1
resource_type: StoragePool
      created: 2024-01-11 05:24:11
        level: INFO
     start_id: 0
   parameters: NULL
     archived: 0
      display: 1
```

Expected behavior 

The state of the event should be completed

**Comment by shwstppr** [comment]
Fixed with #9056
