### ISSUE TITLE
Ui  improvements to OAuth Configuration

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8501]
ISSUE TYPE

Enhancement/Improvement Request

COMPONENT NAME

Component: API/ UI

CLOUDSTACK VERSION

Cloudstack version 4.19 rc 1, 

SUMMARY

Ui  improvements to OAuth Configuration

Issue 1: Disable oAuth icon should be visible on top menu bar

Steps to reproduce the issue 

1. Navigate to configutation  > Ouath Configuration

Screenshot

![disable1](https://github.com/apache/cloudstack/assets/1401014/22da51ff-d7d9-4d9b-8961-d82542ec6e6c)

The disable action of account/ user in present in the top menu bar 

![disable user](https://github.com/apache/cloudstack/assets/1401014/2b999a4a-4e2a-4e40-a994-547692e15d5b)

![disable account](https://github.com/apache/cloudstack/assets/1401014/71a3a144-99aa-4f88-99b3-87b720fdff1a)

Current behavior 

End user has to edit the OAuth configuration and disable the configuration , which can be a little tedious

![disable2](https://github.com/apache/cloudstack/assets/1401014/7ac42e71-a006-42a5-a425-633ecd9fdc19)

----
Issue2 : Extra Space is getting  adding in the UI  form of Oauth

Steps to reproduce the issue 

1.  Navigate to configutation  > OAuth Configuration.

2. Create a OAuth Configuration.

3. Copy and paste the client id, secret key and redirect URI

A extra space is getting added 

![Screenshot 2024-01-12 at 5 33 23 PM](https://github.com/apache/cloudstack/assets/1401014/31273bfa-7b5c-4f25-a52b-fc91038d3ec4)

End user has to make sure there is no space after they paste the credentials

**Comment by DaanHoogland** [comment]
@kiranchavala these are two issues, can you create separate issues for those, please? (personally I would refuse the second one as a user responsibility)

**Comment by kiranchavala** [comment]
@DaanHoogland 

 @harikrishna-patnala requested to log both issues under the same ticket.
 
 
 CC @harikrishna-patnala  could you please take this up when you are free, not a big priority as of now

**Comment by abh1sar** [comment]
Confirmed with Kiran that Issue 2 might not be a valid issue. So will provide the fix for Issue 1 only.

**Comment by DaanHoogland** [comment]
fixed in #9242
