### ISSUE TITLE
Improve test_cluster_drs.py for VMware

### ISSUE THREAD

**Issue by shwstppr** [apache/cloudstack#8507]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
Test
~~~

##### CLOUDSTACK VERSION

~~~
main/4.19
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

NA

##### SUMMARY

Improve test_cluster_drs.py for VMware
`test_02_balanced_drs_algorithm` intermittently fails for VMware due to higher memory usage for system VMs as highlighted in https://github.com/apache/cloudstack/pull/7344#issuecomment-1891377003

**Comment by shwstppr** [comment]
@vishesh92 do we need any work on this? I'm not seeing failures recently

**Comment by sureshanaparti** [comment]
Fixed in #8508
