### ISSUE TITLE
UI instance edit does not show ha setting correctly

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#8510]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### SUMMARY

When editing the instance settings via UI the value of haenable will always shown as disabled, even if the state is true.
Api call listVirtualMachinesMetrics is providing the correct value, it looks like UI is just not using this value to disable or enalbe the button in the edit popup.

##### STEPS TO REPRODUCE

1) create an instance using a compute offering with ha enable true
2) in UI go to Compute ->Instances and click on the instance.
3) take a look at the Details and HA enabled. It shows true
![cs41810_instance_details](https://github.com/apache/cloudstack/assets/23243455/47f513b5-7287-408b-95b8-0cf1c76e60c6)

4) click on edit icon to open the popup to edit the instance
![cs41810_instance_edit](https://github.com/apache/cloudstack/assets/23243455/0dc1bc43-49ef-4360-96fe-fc21cdff8a2d)

HA enabled will always shown as disabled.

~~~

~~~

##### EXPECTED RESULTS

~~~
UI edit instance popup will show correct value of haenable.
~~~

##### ACTUAL RESULTS

~~~
UI edit instancen popup will always show haenable as disabled.
~~~

**Comment by weizhouapache** [comment]
fixed by #9049
