### ISSUE TITLE
Show Domain filter in the UI for Users

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8522]
ISSUE TYPE

Enhancement/Improvement Request

COMPONENT NAME

Component: API/ UI

CLOUDSTACK VERSION

Cloudstack version 4.18 

SUMMARY

Show Domain filter in the UI for Users view

Steps to reproduce the issue 

1. Navigate to Accounts > Click on a particular Account > View users

2. There is no domain filter available in this view 

<img width="1144" alt="Screenshot 2024-01-17 at 11 53 42 AM" src="https://github.com/apache/cloudstack/assets/1401014/24e0f20b-069b-4c48-98af-1032e4cc5e97">

3. The domain filter is available in Accounts 

![listaccount](https://github.com/apache/cloudstack/assets/1401014/294c6f22-6300-485a-be80-623cadeb7bdf)

It would be great if we could extend the behavior to the  users view also as the listuser api call supports domain as the response 

As the list user supports the listing of the domain , this should be easy to implement

https://cloudstack.apache.org/api/apidocs-4.18/apis/listUsers.html

<img width="551" alt="Screenshot 2024-01-17 at 12 03 35 PM" src="https://github.com/apache/cloudstack/assets/1401014/13ade4d5-f49d-4e33-8b36-c3643c3963f9">

Expected behavior 

It would be handy for the Admin  user to  identify the domain the user belongs to

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/8630
