### ISSUE TITLE
Cannot Delete Root admin account 

### ISSUE THREAD

**Issue by Tbaugus44** [apache/cloudstack#8531]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### OS / ENVIRONMENT

Ubuntu 22.04 KVM

##### SUMMARY

I cannot delete a root admin user. 

##### STEPS TO REPRODUCE

![user_](https://github.com/apache/cloudstack/assets/148808916/3b57f7e7-9a44-4698-8107-88d8e79f6682)

~~~

~~~

##### EXPECTED RESULTS

~~~
to be able to delete a user
~~~

##### ACTUAL RESULTS

~~~
i couldn't delete a user 
~~~

**Comment by DaanHoogland** [comment]
@Tbaugus44 you are right, please use an API tool to do this, like cmk.

**Comment by Tbaugus44** [comment]
could you provide an example of this ?

**Comment by Tbaugus44** [comment]
im getting this error when running the cmk list users username=scadmin filter=id

Two factor authentication 2FA is enabled but not verified, please verify 2FA using validateUserTwoFactorAuthenticationCode API before calling other APIs. Existing session is invalidated.

**Comment by DaanHoogland** [comment]
> im getting this error when running the cmk list users username=scadmin filter=id
> 
> Two factor authentication 2FA is enabled but not verified, please verify 2FA using validateUserTwoFactorAuthenticationCode API before calling other APIs. Existing session is invalidated.

well, it seems to trivial to be true but the message actually tells you what to do; do a call to validateUserTwoFactorAuthenticationCode before you proceed.

**Comment by Tbaugus44** [comment]
this has been solved thank you for your help. this article helped set up cloudmonkey.

https://kb.leaseweb.com/products/elastic-compute/managing-apache-cloudstack-api-and-automation
