### ISSUE TITLE
Showing advanced settings of service offerings

### ISSUE THREAD

**Issue by wverleger** [apache/cloudstack#8537]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1
~~~

##### SUMMARY

One can't see the settings of service offerings on the details page.
For example settings set for "compute offerings":

![cs_offerings](https://github.com/apache/cloudstack/assets/121959384/8ede46d5-81f4-4c9d-a4dc-f756796edfb4)

##### STEPS TO REPRODUCE

~~~
Create a compute offering with custom settings. Go to detail page.
~~~

##### EXPECTED RESULTS

~~~
See what kind of settings were used to create the offering.
~~~

##### ACTUAL RESULTS

~~~
No information about creation settings.
~~~

**Comment by DaanHoogland** [comment]
@wverleger , you are right, these are not currently supported by either the list API or the UI.

**Comment by sbrueseke** [comment]
@DaanHoogland api call listServiceOfferings replies with serviceofferingdetails array, which contains maxcpunumber, mincpunumber, minmemory and maxmemory when query a custom offering.

**Comment by DaanHoogland** [comment]
> @DaanHoogland api call listServiceOfferings replies with serviceofferingdetails array, which contains maxcpunumber, mincpunumber, minmemory and maxmemory when query a custom offering.

you are right, I missed that the first time I looked :face_with_head_bandage:
