### ISSUE TITLE
Linstor storage provider details are not displayed when Custom Protocol is selected during primary storage creation

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8550]
ISSUE TYPE

Bug

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.18 

SUMMARY

Linstor storage provider details are not displayed when Custom Protocol is selected

Steps to reproduce the issue 

1. Navigate to Infrastructure > Primary Storage >

2. Add primary storage

3. Select the Protocol as Linstor > Cloudstack displays the Server and Resource groups

screenshot

<img width="624" alt="linstor-custom2" src="https://github.com/apache/cloudstack/assets/1401014/30899375-30c2-428d-b276-b3768c7c0922">

<img width="533" alt="Screenshot 2024-01-23 at 12 58 33 PM" src="https://github.com/apache/cloudstack/assets/1401014/e648d591-4ecf-4f73-acaf-b333e00bcc7b">

4. Select the Protocol as Custom and Provider as Linstor

There is no details of the Server or and Resource group present in the form

Screenshot

<img width="611" alt="linstor-custom" src="https://github.com/apache/cloudstack/assets/1401014/3b0e7cd5-3c41-4277-948b-eccef58f5eb0">

<img width="527" alt="Screenshot 2024-01-23 at 12 58 43 PM" src="https://github.com/apache/cloudstack/assets/1401014/6bf407bc-fa50-46c4-a898-b14b0f6cc6f8">

Expected behaviour 

There should be the details of the Server or and Resource group present when the protocol is custom and Provider as Linstor

For example for Powerflex, we display it correctly

<img width="523" alt="Powerflex" src="https://github.com/apache/cloudstack/assets/1401014/cd5c4a63-eeaa-42c7-a537-9ec8aba466f5">

**Comment by DaanHoogland** [comment]
@rp- are you aware of this? (any resolution on this?)

**Comment by rp-** [comment]
Yes, I think I know this.
I'll try to get this patched

**Comment by sureshanaparti** [comment]
> Yes, I think I know this. I'll try to get this patched

Hi @rp- Can you patch, and create a the PR for this (targeted to 4.19 branch)?

**Comment by sureshanaparti** [comment]
@kiranchavala Closing this, as fix PR got merged.
