### ISSUE TITLE
VMware/KVM migration to KVM - the OS type is not set (CentOS 4.5 32bit, by default). VM settings also empty

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#8551]
ACS 4.19.0.0 (RC2):

New ACS Feature from 4.19: 
**Migrating a VMware VM to KVM** - the end resulting VM has OS type set to "CentOS 4.5 32bit" - since the form doesn't provide a way to choose the OS type during the conversion (nor do we, as it seems?, check for the OS type in the migration process)

The same is true for the feature: Importing KVM from QCOW2 on a shared/local storage feature - there is no way to choose the OS typd

![image](https://github.com/apache/cloudstack/assets/45762285/07e88161-6719-400b-ade6-86c35639797e)

If we don't have time to fix this for 4.19, then, at the bare minimum, we should be updating documentation to state the needed next steps after the VM is imported (and before powering it for the first time). In some cases, VM settings/details also need to be set (if the migrated VM is for example EUFI-enabled)

cc @shwstppr @DaanHoogland @weizhouapache @rohityadavcloud

**Comment by nvazquez** [comment]
We have added a note about the default import template and its guest OS type on: https://github.com/apache/cloudstack-documentation/pull/377

**Comment by DaanHoogland** [comment]
@nvazquez , is this all we do about this (i.e. can we close this ticket?)

**Comment by andrijapanicsb** [comment]
I'm fine if we keep it for future migration improvement

**Comment by andrijapanicsb** [comment]
Improvement to come in future releases
