### ISSUE TITLE
cloudstack-ui RPM package has bad permissions

### ISSUE THREAD

**Issue by kohrar** [apache/cloudstack#8558]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Rocky Linux 8

##### SUMMARY
The cloudstack-ui RPM package appears to have restrictive permissions which disallows the 'cloud' user from reading asset files.

This is likely a bad umask set during the build/package process.

##### STEPS TO REPRODUCE
~~~
# cd /tmp
# wget http://download.cloudstack.org/centos/8/4.18/cloudstack-ui-4.18.1.0-1.x86_64.rpm
# mkdir ui ; cd ui
# rpm2cpio ../cloudstack-ui-4.18.1.0-1.x86_64.rpm | cpio -idmv
# ls -al usr/share/cloudstack-ui/
total 524
drwxr-xr-x 6 root root    166 Jan 23 11:09 .
drwxr-xr-x 4 root root     38 Jan 23 11:09 ..
drw-r--r-- 2 root root    175 Jan 23 11:09 assets
-rw-r--r-- 1 root root  14318 Sep 14 07:47 cloud.ico
-rw-r--r-- 1 root root 456512 Sep 14 07:47 color.less
lrwxrwxrwx 1 root root     30 Sep 14 07:47 config.json -> /etc/cloudstack/ui/config.json
drw-r--r-- 2 root root   8192 Jan 23 11:09 css
-rw-r--r-- 1 root root   1228 Sep 14 07:47 error.html
-rw-r--r-- 1 root root   1220 Sep 14 07:47 example.html
-rw-r--r-- 1 root root  18181 Sep 14 07:47 index.html
drw-r--r-- 2 root root  16384 Jan 23 11:09 js
drw-r--r-- 2 root root    309 Jan 23 11:09 locales
~~~

Notice that the directories here (assets, css, js, locales) are not world executable.

##### EXPECTED RESULTS
Directories should be world executable. Otherwise, the 'cloud' user that cloudstack-management runs as will be unable to read resources in sub-directories, resulting in a 404 error.

##### WORKAROUND
Running `chmod o+x` on these directories fixes the 404 errors.

**Comment by kohrar** [comment]
A follow and related question -- I installed cloudstack-ui and set `webapp.dir=/usr/share/cloudstack-ui` in the `server.properties` config file, but this breaks requests to the API because cloudstack-ui doesn't include [the WEB-INF/web.xml file](https://github.com/apache/cloudstack/blob/main/client/src/main/webapp/WEB-INF/web.xml). It works after I add that file in and restart cloudstack-management.

Is this by design or an oversight? Would the expected behavior be to install the cloudstack-ui package and have everything 'just work' or am I using this package wrong?

Thanks in advance.

**Comment by DaanHoogland** [comment]
@kohrar I am not completely sure about your problem but it sounds like unintended. Would you have a fix to add to the packaging?

**Comment by kohrar** [comment]
@DaanHoogland It looks like the spec file for the UI package has a couple issues. I've made a PR to address the issues I encountered here. Thanks!

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/8568
