### ISSUE TITLE
max connection problem on haproxy acs 4.17.2

### ISSUE THREAD

**Issue by meisammaleki** [apache/cloudstack#8571]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
Network isolated

##### CLOUDSTACK VERSION
4.17.2

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY

max connection default value in haproxy.conf doesn't change after updating global option value

##### STEPS TO REPRODUCE
I have changed the default value for this global setting "network.loadbalancer.haproxy.max.conn" to 16384 and then restarted the management server without any problem. then I created a new isolated network and activated loadblacer on an instance, but the default value in haproxy.conf doesn't change :

network.loadbalancer.haproxy.max.conn | Load Balancer(haproxy) maximum number of concurrent connections(global max) | Network  16384

##### EXPECTED RESULTS
global
        log 127.0.0.1:3914 local0 warning
        maxconn **16384**
        maxpipes 1024
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon
##### ACTUAL RESULTS
global
        log 127.0.0.1:3914 local0 warning
        maxconn **4096**
        maxpipes 1024
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon

**Comment by DaanHoogland** [comment]
@meisammaleki , can you test this in newer version, like 4.18.1?

**Comment by weizhouapache** [comment]
@meisammaleki 
Do you use the default network offerings ?
if not, may be useful to check the `concurrent_connections` of the network offering

**Comment by rajujith** [comment]
@meisammaleki  based on my tests the configuration works fine: 

root@r-6-VM:~# cat /etc/haproxy/haproxy.cfg
global
	log 127.0.0.1:3914   local0 warning
	maxconn 16000

**Comment by weizhouapache** [comment]
> @meisammaleki
> Do you use the default network offerings ?
> if not, may be useful to check the `concurrent_connections` of the network offering

@meisammaleki 
can you please check ?

**Comment by meisammaleki** [comment]
Hello
I use the custom network offering and I have changed concurrent_connections on db in network_offerings table on database
tnx

**Comment by weizhouapache** [comment]
> Hello
> I use the custom network offering and I have changed concurrent_connections on db in network_offerings table on database
> tnx
> 

Does it work? @meisammaleki

**Comment by DaanHoogland** [comment]
@meisammaleki , I am closing this, please reopen or create a new issue if you feel there is still a problem.
