### ISSUE TITLE
Cloudstack agent host auto sleep

### ISSUE THREAD

**Issue by tuanhoangth1603** [apache/cloudstack#8573]
I created this issue with the purpose of sharing with the CloudStack community an issue I encountered the last recent day. The situation is as follows:

I installed CloudStack agent version 4.17.2.0 on physical servers using Ubuntu 20.04 minimal OS.
After installation, I did not restart the server but left it as is for usage.
Recently, due to a power outage at the data center, my servers were rebooted.
When the servers came online, I accessed the console via iDrac and noticed that the OS had switched from minimal to a UI. I began to suspect something was amiss.
After about 5 minutes, these agent servers automatically shutdown. I was genuinely concerned about this.
I reopened the server and try to checked the logs before the shutdown, discovering that the 'sleep' service caused this issue.
The specific log excerpt is as follows.

So, I have two points to share:
1. Does the installation of the cloudstack-agent package include the GUI package of Ubuntu?
2. If point 1 is correct, I suggest adding a notice to the installation instructions that states:
"After installing cloudstack-agent, it is necessary to run the command: ```systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target``` to disable sleep mode."
This is also how I resolved my issue. However, it can be time-consuming for those who haven't encountered a similar situation before.
Hope this is helpful for everyone.

```
Jan 28 21:41:17 host132 ModemManager[1512]: <info>  [sleep-monitor] system is about to suspend
Jan 28 21:41:17 host132 NetworkManager[1459]: <info>  [1706452877.5634] manager: sleep: sleep requested (sleeping: no  enabled: yes)
Jan 28 21:41:17 host132 NetworkManager[1459]: <info>  [1706452877.5640] manager: NetworkManager state is now ASLEEP
Jan 28 21:41:17 host132 gnome-shell[1737]: Screen lock is locked down, not locking
Jan 28 21:41:17 host132 systemd[1]: Reached target Sleep.
Jan 28 21:41:17 host132 systemd[1]: Starting Record successful boot for GRUB...
Jan 28 21:41:17 host132 systemd[1]: Starting Suspend...
Jan 28 21:41:17 host132 systemd-sleep[13889]: Suspending system...
Jan 28 21:41:17 host132 systemd[1]: grub-common.service: Succeeded.
Jan 28 21:41:17 host132 systemd[1]: Finished Record successful boot for GRUB.
Jan 28 21:41:17 host132 kernel: [ 1518.374020] PM: suspend entry (s2idle)
Jan 28 21:41:17 host132 systemd[1]: Starting GRUB failed boot detection...
Jan 28 21:41:17 host132 systemd[1]: grub-initrd-fallback.service: Succeeded.
Jan 28 21:41:17 host132 systemd[1]: Finished GRUB failed boot detection.
```

**Comment by weizhouapache** [comment]
> 1. Does the installation of the cloudstack-agent package include the GUI package of Ubuntu?

@tuanhoangth1603 
I do not think so.
you can check `/var/log/dpkg.log` when gnome/kde,etc and cloudstack-agent was installed.

**Comment by tuanhoangth1603** [comment]
> > 1. Does the installation of the cloudstack-agent package include the GUI package of Ubuntu?
> 
> @tuanhoangth1603 I do not think so. you can check `/var/log/dpkg.log` when gnome/kde,etc and cloudstack-agent was installed.

Thanks @weizhouapache, it is my mistake. GNOME has been installed when I installed collectd.
