### ISSUE TITLE
Resetting a VM password doesn't work. (Password created while first VM setup does work)

### ISSUE THREAD

**Issue by dataCobra** [apache/cloudstack#8584]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Cloudstack UI
~~~

##### CLOUDSTACK VERSION
~~~
4.18.1.0 (Release version)
~~~

##### CONFIGURATION
Using `AlmaLinux-9-GenericCloud-latest.x86_64.qcow2` for a template and enabled `password` feature.
(This also is true for the Ubuntu 22.04 LTS cloud image and the debian 12 cloud image.)

##### SUMMARY
When using the `password` feature for a template the initial setup of the password while building the VM works, but using the `reset password` button afterwards does not change the password.

The password is still the initial password created by cloudstack on VM creation.

##### STEPS TO REPRODUCE
1. Create a template with an image that uses cloud-init
2. Set the `password` feature for the template
3. Create a VM with the template
4. Try the inital setup password (does work)
5. Stop the VM
6. Click on `reset password`
7. Start the VM
8. Try the new password (doesn't work)
9. Try the initial password (does work)

##### EXPECTED RESULTS

~~~
The button `reset password` does indeed reset the password for the VM as displayed.
~~~

##### ACTUAL RESULTS
~~~
The button `reset password` does not change the password and the initial password from creation does still work.
~~~

**Comment by weizhouapache** [comment]
@dataCobra 
have you put the cloudstack script for password in the vm ?

Please refer to https://docs.cloudstack.apache.org/en/latest/adminguide/templates/_password.html
You probably need to put the file in different folder, depends on the Linux OS.

you can also try other script in this folder: https://github.com/apache/cloudstack/tree/main/setup/bindir

**Comment by dataCobra** [comment]
@weizhouapache 
No I didn't add the script to the vm.

So password resetting is only possible with modifying the images to include the script?

I'll try that.

**Comment by weizhouapache** [comment]
> @weizhouapache No I didn't add the script to the vm.
> 
> So password resetting is only possible with modifying the images to include the script?

yes.

> 
> I'll try that.

**Comment by dataCobra** [comment]
Does work as explained.

Thank you for the help. I'll close this know.
