### ISSUE TITLE
Usage is not idem potent while in some cases it can be

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8587]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Usage server
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1 
~~~

##### SUMMARY

When for some reason events remain marked unprocessed, but intermediate records allready exist, the usage job could could just ignore that and keep running

##### STEPS TO REPRODUCE

~~~
mark an event as unprocessed
~~~

##### EXPECTED RESULTS

~~~
usage job sees the intermediat record and continues running
~~~

##### ACTUAL RESULTS

~~~
and exception is thrown the unprocessed event is not marked as processed and next run will try and fail in the same way.
~~~

**Comment by vishesh92** [comment]
This is already fixed in #8726. I forgot to link the PR with this issue.
