### ISSUE TITLE
Add host failure with Cannot find the server resources at http://[ip]

### ISSUE THREAD

**Issue by SuperXiaoxiong** [apache/cloudstack#8594]
##### ISSUE TYPE

 Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### OS / ENVIRONMENT

centos7.9 hyperv

##### SUMMARY

Add Host , there cause an error Cannot find the server resources at http://[ip]
It's should be ssh connect , why use the  http connect 

I debug the code , found It exec 
```
com.cloud.hypervisor.hyperv.discoverer.HypervServerDiscoverer#Map
 resource.configure(agentIp, params);
ReadyCommand ping = new ReadyCommand();
Answer pingAns = resource.executeRequest(ping);
```

the 
```
 com.cloud.hypervisor.hyperv.resource.HypervDirectConnectResource#executeRequest

make http request
```

##### STEPS TO REPRODUCE

~~~
as above 
~~~

##### EXPECTED RESULTS

~~~
as above
~~~

##### ACTUAL RESULTS

~~~
as above
~~~

**Comment by weizhouapache** [comment]
is hyperv still supported ? 
cc @DaanHoogland @rohityadavcloud

**Comment by rajujith** [comment]
@SuperXiaoxiong  could you clarify whether you are using CentOS7.9 as KVM or hyper-v ? By any chance you created the cluster with wrong hypervisor type?

**Comment by SuperXiaoxiong** [comment]
Sorry for mismatch KVM and hyper-v
