### ISSUE TITLE
Whether nested virtualization possible with KVM hosts?

### ISSUE THREAD

**Issue by naseemvk** [apache/cloudstack#8596]
Hi Team

I am using cloudstack version 4.17.2.0

I want to know whether nested virtualization is possible if we are using using KVM hosts.

**Comment by weizhouapache** [comment]
@naseemvk 
just to clarify, you want to the VMs to support nested virtualization ?

**Comment by naseemvk** [comment]
Yes I want VMs to support nested virtualization 

Exact requirement is I want to run Hyper V on Windows Server 2019 VM

My host processor is AMD EPYC

Just for clarification
Whether I need to follow below steps since my host is already showing as nested virtualization enabled 

Create the following file: /etc/modprobe.d/kvm-nested.conf and add the following details to the file: options kvm-intel nested=1

**Comment by weizhouapache** [comment]
> Yes I want VMs to support nested virtualization
> 
> Exact requirement is I want to run Hyper V on Windows Server 2019 VM
> 
> My host processor is AMD EPYC
> 
> Just for clarification Whether I need to follow below steps since my host is already showing as nested virtualization enabled
> 
> ![image](https://private-user-images.githubusercontent.com/48643957/301866248-eeef208e-232c-47b4-9747-8ba483cbbf0f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODUxOTIsIm5iZiI6MTcwNjg4NDg5MiwicGF0aCI6Ii80ODY0Mzk1Ny8zMDE4NjYyNDgtZWVlZjIwOGUtMjMyYy00N2I0LTk3NDctOGJhNDgzY2JiZjBmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNDQxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2U5YzU3MjM1MmI5YTI0ZjU0NGMwY2E3NzJjZWY5ZjgyZWUzNzkyNWM3NTYwZjQ3ZDI2NTkzMjMwNTk1MDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wMNXxxvXq1SZ4DlNYMfOfj-7Vth40EBsmdgfXN8IuIc)
> 
> _Create the following file: /etc/modprobe.d/kvm-nested.conf and add the following details to the file: options kvm-amd nested=1_

it looks good. nested is already enabled on the kvm host.

now you need to add a cpu flag to the vms. please refer to https://docs.cloudstack.apache.org/en/latest/installguide/hypervisor/kvm.html#configure-cpu-model-for-kvm-guest-optional

since the processor is AMD, you can try with a cpu feature "svm" ("vmx" is for intel processors)

**Comment by naseemvk** [comment]
I followed the same but didn't do the below step

_* Encode the text to be passed, as: '%3Ccpu%20mode%3D%27host-model%27%20check%3D%27partial%27%2F%3E'
* Stop and update the virtual machine, passing the encoded text as the extraconfig parameter: update virtualmachine extraconfig="%3Ccpu%20mode%3D%27host-model%27%20check%3D%27partial%27%2F%3E" id=<VM_UUID>_

Now when I checked inside my Hyper V server VM it is showing like this

![image](https://github.com/apache/cloudstack/assets/48643957/77a08c81-15f0-4619-b556-c8667869bb3e)


agent.properties file content

#####

cluster=2
pod=2
resource=com.cloud.hypervisor.kvm.resource.LibvirtComputingResource
private.network.device=cloudbr0
domr.scripts.dir=scripts/network/domr/kvm
guest.cpu.mode=host-model
router.aggregation.command.each.timeout=600
guest.network.device=cloudbr1
keystore.passphrase=kmusdfrqCccYx5sfvy9YIsdfsdf
hypervisor.type=kvm
port=8250
zone=2
public.network.device=cloudbr1
local.storage.uuid=5afdsfce-3cb3-4985-ab1d-06esdfdf80cd
host=192.168.0.200@static
guid=2casdasd63-d67d-32d3-83eb-8adasdasdd8
LibvirtComputingResource.id=9201
workers=5
iscsi.session.cleanup.enabled=false
vm.migrate.wait=3600
guest.cpu.features=svm

#####

*** Super thanks for all your response and support ***

**Comment by weizhouapache** [comment]
> I followed the same but didn't do the below step
> 
> _* Encode the text to be passed, as: '%3Ccpu%20mode%3D%27host-model%27%20check%3D%27partial%27%2F%3E'
> * Stop and update the virtual machine, passing the encoded text as the extraconfig parameter: update virtualmachine extraconfig="%3Ccpu%20mode%3D%27host-model%27%20check%3D%27partial%27%2F%3E" id=<VM_UUID>_
> 
> Now when I checked inside my Hyper V server VM it is showing like this
> 
> ![image](https://github.com/apache/cloudstack/assets/48643957/77a08c81-15f0-4619-b556-c8667869bb3e)
> 
> 
> agent.properties file content
> 
> #####
> 
> cluster=2
> pod=2
> resource=com.cloud.hypervisor.kvm.resource.LibvirtComputingResource
> private.network.device=cloudbr0
> domr.scripts.dir=scripts/network/domr/kvm
> guest.cpu.mode=host-model
> router.aggregation.command.each.timeout=600
> guest.network.device=cloudbr1
> keystore.passphrase=kmusdfrqCccYx5sfvy9YIsdfsdf
> hypervisor.type=kvm
> port=8250
> zone=2
> public.network.device=cloudbr1
> local.storage.uuid=5afdsfce-3cb3-4985-ab1d-06esdfdf80cd
> host=192.168.0.200@static
> guid=2casdasd63-d67d-32d3-83eb-8adasdasdd8
> LibvirtComputingResource.id=9201
> workers=5
> iscsi.session.cleanup.enabled=false
> vm.migrate.wait=3600
> guest.cpu.features=svm
> 
> #####
> 
> *** Super thanks for all your response and support ***

@naseemvk 
You are welcome. Can we close this issue?

**Comment by naseemvk** [comment]
Sorry @weizhouapache if my previous message caused any confusion. 

What I intended to convey is **NESTED VIRTUALIZATION IS NOT WORKING**

Kindly let me know if anything further needs to be done. If anything I am missed.

So please keep this thread open. If we can achieve the results, it would be helpful for many others as well.

**Comment by weizhouapache** [comment]
> Sorry @weizhouapache if my previous message caused any confusion. 
> 
> What I intended to convey is **NESTED VIRTUALIZATION IS NOT WORKING**
> 
> After installing Hyper-V on my VM, it fails to boot after the restart. 
> 
> Kindly let me know if anything further needs to be done. If anything I have missed.
> 
> So please keep this thread open. If we can achieve the results, it would be helpful for many others as well.
> 
> 

@naseemvk 
I did not use hyper-V before. As I remember, this should work if you use other hypervisors, e.g kvm or VMware.
I suggest you to ask Microsoft for help. Maybe hyper-V has other requirements which are unknown to us.

**Comment by naseemvk** [comment]
Okay. after instaling Hyper-V in server 2019 VM, the VM fails to boot. 

Also we tested in a Ubuntu VM by enabling KVM. When we run a VM(L2) in that the nested VM fails at booting

**Comment by weizhouapache** [comment]
In the case of ubuntu22, what's the error in cloudstack mgmt and agent when you start a VM on it?

**Comment by rohityadavcloud** [comment]
Yes @naseemvk you'll need to set `guest.cpu.mode=host-passthrough` in /etc/cloudstack/agent/agent.properties in case of the KVM host. Kindly use our users mailing list or Github discussions if you've further questions that aren't bug reports.
