### ISSUE TITLE
Option "network selection" from import tool not selecting the right option

### ISSUE THREAD

**Issue by LuizFelipeCibulski** [apache/cloudstack#8612]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When trying to import an unmanaged instance it's necessary to change the network guest for the instance to be at the right environment network. 
But when selecting the appropiate network and click on import, Cloudstack returns an error saying "Unale to use network with id = ID, permission denied", the problem is, even thoug I wrotte the correct network name Cloudstack will use the last network created. 
To solve this, I just deleted and created the network guest, making the network the first option on the selection menu.

##### STEPS TO REPRODUCE

1- Open the Import-Export instances
2- Select a Unmanaged instances
3- After inform all the data from the vm, on the "Network selection" section change the network for a different on the same vlan:
3.1- The default option:
![1option](https://github.com/apache/cloudstack/assets/78325665/3b9e55fe-aca3-4db1-8f09-e52ecc2ccf20)
3.2- The select option:
![selectoptin](https://github.com/apache/cloudstack/assets/78325665/276add9b-e272-4968-bbd3-c3ab8a46b950)
4- The error:
![error](https://github.com/apache/cloudstack/assets/78325665/c2c645f0-0fb4-408c-afe0-57f5380eb43a)
5- The confirmation that the id was from the 1 option that appers on the selection menu:
![confirmation](https://github.com/apache/cloudstack/assets/78325665/90a4545e-ab3c-4776-be49-552a0bc9fb31)
6- The ID of the corret network guest:
![thecorret](https://github.com/apache/cloudstack/assets/78325665/c06df694-d5ed-411c-a848-05d6a8148e92)

##### EXPECTED RESULTS

~~~
The network guest selected is used to import the vm.
~~~

##### ACTUAL RESULTS

~~~
The fisrt option on the selection menu is used every time.
~~~

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9194
