### ISSUE TITLE
Hovering button in VM view shows "label.copy.consoleurl" instead of correct text.

### ISSUE THREAD

**Issue by dataCobra** [apache/cloudstack#8617]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### SUMMARY

As stated in the title the button does not show text but "label.copy.consoleurl".
![image](https://github.com/apache/cloudstack/assets/42339846/fb2caf4b-68ce-4c06-b830-38d5c0cfe5fe)

##### STEPS TO REPRODUCE

~~~
Hover over the button and it shows "label.copy.consoleurl".
~~~

##### EXPECTED RESULTS

~~~
Hover over the button and it shows the correct text.
~~~

##### ACTUAL RESULTS

~~~
Hover over the button and it shows "label.copy.consoleurl".
~~~

**Comment by vishesh92** [comment]
@dataCobra It's working as expected for me. Can you share more details about your environment?

![image](https://github.com/apache/cloudstack/assets/8760112/6f3007d1-ff1d-46cf-bbc6-76d671503a33)

**Comment by weizhouapache** [comment]
> @dataCobra It's working as expected for me. Can you share more details about your environment?
> 
> ![image](https://github.com/apache/cloudstack/assets/8760112/6f3007d1-ff1d-46cf-bbc6-76d671503a33)
> 

If the environment was upgraded recently, clean the browser cache or try with incognito mode

**Comment by dataCobra** [comment]
Thank you for the hint with the browser cache.

This fixed the issue for me.

Didn't know that this could be caused because of the cache.
