### ISSUE TITLE
Delete and Edit button for Guest IP ranges not visible in UI

### ISSUE THREAD

**Issue by ccycv** [apache/cloudstack#8623]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

~~~
Advanced Networking 
~~~

##### OS / ENVIRONMENT

~~~
CentOS 7
~~~

##### STEPS TO REPRODUCE

~~~
Check the Guest IP range for any network, type shared.

~~~
![image](https://github.com/apache/cloudstack/assets/23322009/a8232024-54fd-4b6f-9478-0280fceedf56)

##### EXPECTED RESULTS

~~~
The option to edit/delete
~~~

##### ACTUAL RESULTS

~~~
Not visible 
~~~

**Comment by DaanHoogland** [comment]
Are you meaning to get an UI interface to updateVlanIpRange? (not sure what API applies from your image)

**Comment by ccycv** [comment]
@DaanHoogland  the edit and delete buttons are missing, please see the screenshots from 4.18.x

![image](https://github.com/apache/cloudstack/assets/23322009/a9ecfa1a-5078-4ca7-b440-62ebcddd67e2)

**Comment by DaanHoogland** [comment]
ah, thanks, regression :(

**Comment by DaanHoogland** [comment]
did you by any change test with head of 4.18 (i.e. 4.18.2.0-SNAPSHOT)?

**Comment by ccycv** [comment]
> did you by any change test with head of 4.18 (i.e. 4.18.2.0-SNAPSHOT)?

No.

**Comment by DaanHoogland** [comment]
got around testing it in 4.18 head (i.e. 4.18.2 to come) and no issue there
![image](https://github.com/apache/cloudstack/assets/2486961/28d354bc-5554-4844-8997-54ec791fb886)

**Comment by weizhouapache** [comment]
@DaanHoogland 
sounds like a regression in 4.19
I checked some 4.19 environments, the buttons are not visible.

> got around testing it in 4.18 head (i.e. 4.18.2 to come) and no issue there ![image](https://private-user-images.githubusercontent.com/2486961/303995462-28d354bc-5554-4844-8997-54ec791fb886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjYyNzIsIm5iZiI6MTcwNzcyNTk3MiwicGF0aCI6Ii8yNDg2OTYxLzMwMzk5NTQ2Mi0yOGQzNTRiYy01NTU0LTQ4NDQtODk5Ny01NGVjNzkxZmI4ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMDgxOTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTM2YTJlNzA0ODE0NWZlODg1ZTU2YzM0ODg1MTExY2Y5MDk3MTY1MDJhMjU5ZDZjZjg0N2ZiNjhkOGYyZjM4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LObCB5kpH_up2NCy8dNruoA3DqFjRP5p7jVRDe7Lg2I)

**Comment by sureshanaparti** [comment]
Closing this, as the fix PR got merged.
