### ISSUE TITLE
Improve the list volume api to show only the encrypted volumes

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8635]
ISSUE TYPE

Improvement request

COMPONENT NAME

Component: Api

CLOUDSTACK VERSION

Cloudstack version 4.18 4.19

SUMMARY

List volume api should show the encrypted volumes 

Steps to reproduce the issue

1. Create service offering and disk offering  with encrypt option enabled.

Screenshot
![Screenshot 2024-02-09 at 10 41 58 AM](https://github.com/apache/cloudstack/assets/1401014/da0163fd-9385-4482-8a05-9e3f789ca632)

2. Launch a vm with service offering and disk offering

3. Go volumes view (storage > volumes) , there is no way to identify if the volume is encrypted or not 

![volumencrypt2](https://github.com/apache/cloudstack/assets/1401014/142bc746-b822-4de2-9f7c-ceb99bc257ca)

![volumencrypt](https://github.com/apache/cloudstack/assets/1401014/b2639f8f-5e68-4c2d-a7d5-72aa521ce22d)

4. Also the listVolumes doesn't list only the encrypted volumes 

https://cloudstack.apache.org/api/apidocs-4.19/apis/listVolumes.html

It would be handy feature for the admins and users to list only the encyrpted volumes 

Example 

list volume encrypted=true

**Comment by DaanHoogland** [comment]
@kiranchavala did you check if this is possible with the API?

**Comment by kiranchavala** [comment]
@DaanHoogland  it's not possible via api call the the list volumes doesn't have the "encrypted" option 

So i would like to have the encrypted option added

**Comment by kiranchavala** [comment]
@DaanHoogland 

Also, can we list volumes by serviceofferingid


Currently, we are able to list volumes by only disk offering  id


https://cloudstack.apache.org/api/apidocs-4.19/apis/listVolumes.html


Do you want me to create a separate enchancment request for this ?

**Comment by DaanHoogland** [comment]
yes please, it might be a different technical discussion. For now, for both of them my implementation plans are not so neat hacks and the solution might be different.

**Comment by sureshanaparti** [comment]
Merged enhancement PR. Encrypted volumes can be listed using `list volumes isencrypted=true`.
