### ISSUE TITLE
List volume api should have the parameter service offering id 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8646]
ISSUE TYPE

Improvement request

COMPONENT NAME

Component: Api

CLOUDSTACK VERSION

Cloudstack version 4.18 4.19

SUMMARY

List volume api should have the option of service offering id 

Steps to reproduce the issue

1. Create a service offering 

2. Launch a vm with service offering 

3. Currently if I want to list the root disk volumes  of the vm created from the service offering 

There is no way list them

https://cloudstack.apache.org/api/apidocs-4.19/apis/listVolumes.html

It would be handy feature for the admins and user to have a servicofferingid parameter as they could list all the volumes associated with the service offering id 

Example 

list volume <serviceoffering id>

This is could be similar to listVirtualMachine with serviceofferingid parameter

https://cloudstack.apache.org/api/apidocs-4.19/apis/listVirtualMachines.html

Root disk details, no way to identify the service offering

![Screenshot 2024-02-13 at 3 42 04 PM](https://github.com/apache/cloudstack/assets/1401014/681c7a49-2879-4ec7-8d73-f059d316259c)

Data disk details 

![data disk details](https://github.com/apache/cloudstack/assets/1401014/0eed5012-76a1-4ec6-9c29-0fe5945bebe6)

**Comment by sureshanaparti** [comment]
@kiranchavala Closing this, as the fix PR got merged.
