### ISSUE TITLE
MinIO Bucket created in CloudStack 4.19 - How to connect via external client? 

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#8651]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Storage - Bucket
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

Two problems/(Maybe clarification needed) - I am testing out the new release 4.19. I connected it to a locally hosted MinIO instance. 
Problem 1: I noticed that each user can only see their own bucket - this is good. However, I am unable to browse the bucket via external application like CyberDuck (or Python). I cannot find any documentation around how to use the CloudStack URL/IP to do the bucket browsing either. I know I can browse the MinIO instance URL and bucket directly, but since the user access is not managed by MinIO, there is no practical way to enable browsing for a Cloudstack user. 
Problem 2: If I want to share the link to an uploaded file, when I click on the file name in Bucket browser in Cloudstack, I can get a link. However, this link is to the MinIO server, and not using the CLoudstack server. Keep in mind that my cloudstack user does not have any Key/Secret for MinIO, they only have Cloudstack API/Key

##### STEPS TO REPRODUCE

~~~
Link MinIO to Cloudstack. 
Create new CloudStack user. 
Login as the new cloudstack user
Create bucket as this user. Upload a file. 
create API KEY/Secret

Try to browse in app like CyberDuck using the Cloudstack URL with the new API key/secret - fails

~~~

##### EXPECTED RESULTS

~~~
User is able to brwse the bucket in Cyberduck
~~~

##### ACTUAL RESULTS

~~~
Cannot browse the bucket - Perhaps this uses a special port and not 8080? 

![image](https://github.com/apache/cloudstack/assets/71042351/b2a8ed10-e916-4a85-80aa-3f4f21614f32)

PROBLEM 1: - Cannot figure out how to browse bucket via external tool or path (without referencing the MinIO actual path)

![image](https://github.com/apache/cloudstack/assets/71042351/e105121c-f215-4d50-8a84-283654d7f63e)

PROBLEM2: When you click on a file in the cloudstack bucket browser, it allows you to see a URL and a presigned URL. 
However, these point to the MinIO IP - not using the Cloudstack IP. MinIO is not internet facing - I want to interface using cloudstack as the bucket is secured via cloudstack not MinIO. 


~~~

**Comment by nxsbi** [comment]
Hopefully its just a matter of using a correct Port number. 
Goal would be to programmatically connect to the bucket so using the internal MinIO address would not work. Even if MinIO was exposed to internet, the user does not have a MinIO API Key/Secret. They created the bucket using CloudStack and CS was using the admin access Key/Secret

**Comment by nxsbi** [comment]
Never Mind - Found the API/Secret -- I went to the BUcket name in Cloudstack, and under detail, I can see the URL, API Key and Secret.
This solved Problem 1

Problem 2  - Is there any way to use the Cloudstack URL (I could setup a DNS entry and Port Forwarding rule in firewall) - But want to know if there is any better way? 

I

**Comment by vishesh92** [comment]
@nxsbi Regarding Problem 2, CloudStack only creates and manages buckets on the Object Storage. It doesn't have any idea about the contents of buckets as of now. The Bucket browser makes requests directly to the object store (minio server) to lists the files and do other operations.
If you setup port forwarding & DNS entry, make sure that you use the same values when you create the Object Storage. Otherwise, the link bucket browser generates would still point to the minio server.

**Comment by nxsbi** [comment]
Thanks @vishesh92 
Closing this issue
