### ISSUE TITLE
Web UI: incorrect sorting of colums with numerical values

### ISSUE THREAD

**Issue by boubouX** [apache/cloudstack#8663]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### SUMMARY

The sorting functionality for columns containing numerical values, such as metrics, is currently incorrect and renders the feature ineffective.

##### STEPS TO REPRODUCE

~~~
Use sorting on Web UI
~~~

##### EXPECTED RESULTS

Sorting based on value
~~~
 Sorting of columns representing numerical value should be based on value.
~~~

##### ACTUAL RESULTS

~~~
The sorting of columns appears to be uniformly based on ASCII values, disregarding the numerical nature of the data within the columns.
~~~

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9247
