### ISSUE TITLE
auto start all VMs on a host using local storage after reboot

### ISSUE THREAD

**Issue by Forevery1** [apache/cloudstack#8687]
I need this feature, what should I do?

**Comment by weizhouapache** [comment]
> I need this feature, what should I do?

Is the service offering HA-enabled ?

**Comment by Forevery1** [comment]
> > I need this feature, what should I do?
> 
> Is the service offering HA-enabled ?

I am single-node deployed, the rest is default，ha should not be enabled

**Comment by weizhouapache** [comment]
> > > I need this feature, what should I do?
> > 
> > 
> > Is the service offering HA-enabled ?
> 
> I am single-node deployed, the rest is default，ha should not be enabled

If you have write access to the database, you can update the `ha_enabled` field in the tables `service_offering` and `vm_instance`  if needed.

**Comment by Forevery1** [comment]
> > > > I need this feature, what should I do?
> > > 
> > > 
> > > Is the service offering HA-enabled ?
> > 
> > I am single-node deployed, the rest is default，ha should not be enabled
> 
> If you have write access to the database, you can update the `ha_enabled` field in the tables `service_offering` and `vm_instance`  if needed.

This just doesn't work when using local storage, just update the ha_enable field in the database, right?

**Comment by Forevery1** [comment]
> 
> > > 
> > > If you have write access to the database, you can update the `ha_enabled` field to 1 in the tables `service_offering` and `vm_instance`  if needed.
> > 
> > This just doesn't work when using local storage, just update the ha_enable field in the database, right?
> 
> @Forevery1 
> I have not tested it yet. You can have a try. 
> If it does not work, you can create an issue with more details

Thank you😀

**Comment by pcfriek1987** [comment]
I was looking for this too and was actually a little confused that it can't be done yet. As it looks like almost everyone can do it (plain KVM, proxmox, esxi, openstack).

Does that option actually work to enable HA with local storage? Then I might try it too.

**Comment by weizhouapache** [comment]
> I was looking for this too and was actually a little confused that it can't be done yet. As it looks like almost everyone can do it (plain KVM, proxmox, esxi, openstack).
> 
> Does that option actually work to enable HA with local storage? Then I might try it too.

@pcfriek1987 
I think what you need is unrelated to host HA, but a new feature like this
![image](https://github.com/apache/cloudstack/assets/57355700/3b9ff1f6-d498-4637-ad0e-e8b94774160b)

right ?

**Comment by pcfriek1987** [comment]
> > I was looking for this too and was actually a little confused that it can't be done yet. As it looks like almost everyone can do it (plain KVM, proxmox, esxi, openstack).
> > Does that option actually work to enable HA with local storage? Then I might try it too.
> 
> @pcfriek1987 I think what you need is unrelated to host HA, but a new feature like this ![image](https://private-user-images.githubusercontent.com/57355700/309235675-3b9ff1f6-d498-4637-ad0e-e8b94774160b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTA5NTUsIm5iZiI6MTcwOTI5MDY1NSwicGF0aCI6Ii81NzM1NTcwMC8zMDkyMzU2NzUtM2I5ZmYxZjYtZDQ5OC00NjM3LWFkMGUtZThiOTQ3NzQxNjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwNTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYzliZTRhYjA3OWU2NTY5YzM0ZWRhYzQwMDUwNzhiN2Q1MGRmYjMzNTc0YTAzNzY1MjQ1ZWIwYTRjZjhlOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1G8bysQI-xIzyTwQu5caxtWNvxwTPkuaz5dKqYjtYcg)
> 
> right ?

I need exactly that indeed :) or is that already possible in some way?

**Comment by Forevery1** [comment]
> > I was looking for this too and was actually a little confused that it can't be done yet. As it looks like almost everyone can do it (plain KVM, proxmox, esxi, openstack).
> > 
> > Does that option actually work to enable HA with local storage? Then I might try it too.
> 
> @pcfriek1987 
> I think what you need is unrelated to host HA, but a new feature like this
> ![image](https://github.com/apache/cloudstack/assets/57355700/3b9ff1f6-d498-4637-ad0e-e8b94774160b)
> 
> right ?

Yes, that's the feature

**Comment by eddiewang** [comment]
i would also like to see this feature implemented!

**Comment by Indrasura20** [comment]
I would very much love this feature as well! I think this basic KVM feature should have been added years ago.
