### ISSUE TITLE
Certificate ownership verification failed for client

### ISSUE THREAD

**Issue by yeganehmehr** [apache/cloudstack#8707]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME
CLOUDSTACK VERSION

##### CLOUDSTACK VERSION
CloudStack 4.17.2.0

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT
CentOS Linux release 7.8.2003 (Core)
##### SUMMARY
when i creat vm get thie error
2024-02-26 13:43:02,058 ERROR [o.a.c.c.p.RootCACustomTrustManager] (pool-59459-thread-1:null) (logid:) Certificate ownership verification failed for client: X.X.X.X
2024-02-26 13:43:02,060 ERROR [c.c.u.n.Link] (AgentManager-SSLHandshakeHandler-4:null) (logid:) SSL error caught during wrap data: Certificate ownership verification failed for client: X.X.X.X

**Comment by DaanHoogland** [comment]
@yeganehmehr is this a clean installation?

**Comment by yeganehmehr** [comment]
No.we update to cloudstack  4.17.2

**Comment by DaanHoogland** [comment]
@yeganehmehr , you could
- set auth strictness (ca.plugin.root.auth.strictness) setting to false,
- restart kvm agent;

if you want secure connections you can then
- re-provision certificates.
- set the auth strictness back to true
- and finally restart cloudstack-agent

let us know how you fare

**Comment by rohityadavcloud** [comment]
Usually post-upgrade, systemvms and routers must be upgraded/re-created. For KVM agents, if there was an issue Daan's advised can be followed to apply the workaround.

Closing as the question has been answered.
