### ISSUE TITLE
Two backups appear in the UI interface

### ISSUE THREAD

**Issue by mm8m6m7m** [apache/cloudstack#8710]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~
![image](https://github.com/apache/cloudstack/assets/20329685/4a81474f-93a8-4644-b0e7-14d132b8f626)

Two backups appear in the UI interface

**Comment by weizhouapache** [comment]
this has been fixed by #8678
