### ISSUE TITLE
Assign instance to another account

### ISSUE THREAD

**Issue by yeganehmehr** [apache/cloudstack#8715]
##### ISSUE TYPE

 * Bug Report
 * Other
##### COMPONENT NAME
 UI, etc.
##### CLOUDSTACK VERSION

CloudStack 4.17.2.0

##### CONFIGURATION
advanced networking

##### OS / ENVIRONMENT

CentOS Linux release 7.9.2009 (Core)

##### SUMMARY

We wanted the feature of Assign instance to another account
but when we turn off the source machine after selecting the correct account type and domain, we still do not see the target account.

What features should be considered for the source and destination accounts

##### ACTUAL RESULTS
Changing the account and moving anywhere was not done

**Comment by sureshanaparti** [comment]
Hi @yeganehmehr Did you notice any error in the management server log during the assignment?

You can specify target domain and account to change instance ownership. The target account should be in Enabled state, and with in the resource limits. Assignment might fail if any network rues configured on the instance, or snapshots exists for the volumes of the instance.

**Comment by yeganehmehr** [comment]
Hi @sureshanaparti The resource and network conditions are completely the same and we don't get any error when we want to check the log. The problem is that we have a whmcs domain through which customer service accounts are created, and the problem is that when we move the accounts, it doesn't show that domain. Only those that were created before the update are displayed

**Comment by sureshanaparti** [comment]
@yeganehmehr Have you tried with api / cmk.

Check API details here: https://cloudstack.apache.org/api/apidocs-4.17/apis/assignVirtualMachine.html

**Comment by rohityadavcloud** [comment]
You need to do this as a root admin, then you'd be able to see the accounts; or use the API (such as cmk CLI) to run the API.

Since the question has been answered, I'm closing this. If you hit a CloudStack issue, pl re-open the issue or log a new one. Thanks.
