### ISSUE TITLE
Cannot link minio as object storage for cloudstack

### ISSUE THREAD

**Issue by anhtt96VN** [apache/cloudstack#8722]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Cannot link minio as object storage for cloudstack
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

I using basic network

##### OS / ENVIRONMENT

CloudStack Management  OS: Ubuntu 20.04.6 LTS
CloudStack Database OS: Ubuntu 20.04.6 LTS
Minio Server using Docker: https://min.io/docs/minio/container/index.html

```
mkdir -p ~/minio/data

docker run \
   -p 9000:9000 \
   -p 9001:9001 \
   --name minio \
   -v ~/minio/data:/data \
   -e "MINIO_ROOT_USER=ROOTNAME" \
   -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
   quay.io/minio/minio server /data --console-address ":9001"
   ```
##### SUMMARY

I tried adding minio to cloudstack but it didn't work.  
My minio IP is: 10.110.252.45:9001  
I tried adding with:

1.  [http://10.110.252.45:9100](http://10.110.252.45:9100/)
2.  10.110.252.45:9100
3.  10.110.252.45  
   All show errors as shown in the picture
  
![image](https://github.com/apache/cloudstack/assets/95908257/1c6ee466-140a-455f-9dac-3104d00eb573)
![image](https://github.com/apache/cloudstack/assets/95908257/f9f5f007-153f-4bd5-8eee-deb429d8fcc3)

##### STEPS TO REPRODUCE

~~~
It happened when I added minio to the cluster

**Comment by omurozlu** [comment]
http://10.110.252.45:9000/ try ?

**Comment by anhtt96VN** [comment]
@omurozlu yes I tried it and it still fails

**Comment by anhtt96VN** [comment]
@omurozlu I have added it according to your instructions. Thank you for the enthusiastic support from the team
