### ISSUE TITLE
[UI] Storage menu not showing even with API permissions

### ISSUE THREAD

**Issue by BryanMLima** [apache/cloudstack#8730]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
Main
~~~

##### SUMMARY
As reported in https://github.com/apache/cloudstack/pull/8713#issuecomment-1969866705, the `Storage` submenu in the sidebar is not displayed to users when they do not have permission to the API `listVolumesMetrics`. However, roles can have permissions to other APIs, such as `listBackups` and `listSnapshots`, in which case the submenu should be displayed. This scenario is probably not exclusive to the `Storage` menu.

##### STEPS TO REPRODUCE
Create a role with permission to allow the APIs `listBackups` and `listSnapshots` and deny the API `listVolumesMetrics`. The UI dashboard will not show the `Storage` menu in the sidebar.

##### EXPECTED RESULTS
The UI should show the `Storage` submenu alongside with its own `Backups` and `Snapshots` submenus.

##### ACTUAL RESULTS
The submenu `Storage` is not displayed, even though the role has permission to list snapshots and backups.

**Comment by BryanMLima** [comment]
@DaanHoogland @winterhazel @sureshanaparti, I am probably overthinking this scenario, however, the `permission` property in the JS component (`storage.js`) works like an AND operator. Maybe it could function like an OR operator as well; what do you guys think?

**Comment by DaanHoogland** [comment]
> @DaanHoogland @winterhazel @sureshanaparti, I am probably overthinking this scenario, however, the `permission` property in the JS component (`storage.js`) works like an AND operator. Maybe it could function like an OR operator as well; what do you guys think?

This was exactly my thought when I learned of it @BryanMLima . Let's try.

**Comment by winterhazel** [comment]
Hey everyone,

I've implemented @BryanMLima's idea in #8978. The filtering still works as an AND operator for routes that correspond to a page; however, I have changed so that routes corresponding to sections get shown if the user has access to any of its pages.

**Comment by BryanMLima** [comment]
Closing this as this was addressed in PR #8978.
