### ISSUE TITLE
Unable to create a instance on hyper-v host

### ISSUE THREAD

**Issue by kedupuganti-kub** [apache/cloudstack#8738]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

Hyper-v
~~~

~~~

##### CLOUDSTACK VERSION

4.19

~~~

~~~

##### SUMMARY
Hyperv installed  and cloudstack agent installed in hyper-v and it is attached to cloudstack managment successfully. I have created Primary storage as SMB and secondary as SMB. All the componets are got attached and it is in green. 

I am trying to  create one instance with ubunutu 22 and windows server 2019  in hyperv through cloudstack but i'm getting the below error " Hypervisor Hyperv does not support rootdisksize override"

Can any one help us on this. 

##### STEPS TO REPRODUCE

I am trying to  create one instance with ubunutu 22 and windows server 2019  in hyperv through cloudstack but i'm getting the below error " Hypervisor Hyperv does not support rootdisksize override"

~~~

~~~

##### EXPECTED RESULTS

Hyper-v instance creating thorugh cloudstack 
~~~

~~~

##### ACTUAL RESULTS

Hyperv installed  and cloudstack agent installed in hyper-v and it is attached to cloudstack managment successfully. I have created Primary storage as SMB and secondary as SMB. All the componets are got attached and it is in green. 

I am trying to  create one instance with ubunutu 22 and windows server 2019  in hyperv through cloudstack but i'm getting the below error " Hypervisor Hyperv does not support rootdisksize override"
~~~

~~~

**Comment by DaanHoogland** [comment]
@kedupuganti-kub I am not sure if there are active hyperv users at the moment. There are no hyperv maintainers. We'll try to help of course. First thing to check: Are the systemvms up and running?

**Comment by weizhouapache** [comment]
this seems to be caused by #7692 

https://github.com/apache/cloudstack/blob/9a73a2f9e1433103373e7bd9da8b5feef4479feb/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L665-L671

as @DaanHoogland said, the plugin is not well-maintained.

**Comment by kedupuganti-kub** [comment]
I have tried to  https://github.com/apache/cloudstack/pull/7692 tried in this way

 but  the problem here  the  error which i am getting is  22 port  on hyperv and saying that "kvm is not installed in the host" as i am looking for the hyperv integration. 

Could you please help me i need to deliver this to client with hyperv

**Comment by DaanHoogland** [comment]
@kedupuganti-kub are your systemvms up and connected?

**Comment by kedupuganti-kub** [comment]
No Daan no systemvms  is not running. But agent is started in the hyperv and it is added to cluster.  

I have another KVM cluster in that it is running.
