### ISSUE TITLE
haproxy misconfiguration after restarting VPC with cleanup

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8745]
Steps to reproduce the issue

- Create 1 VPC
- create 2 VPC tiers, and a VM on each VPC tier
- acquire 2 public IPs
- create LB rules to the VM in each tier

The VR has correct haproxy configuration
![image](https://github.com/apache/cloudstack/assets/57355700/802a0469-cc35-4454-8bf1-0b6ece44c5cb)

- restart VPC with cleanup

The new VR has haproxy configuration for LBs of only 1 tier
![image](https://github.com/apache/cloudstack/assets/57355700/6b09c4f0-da52-4203-9d2b-8f2d58f65bfe)

health check failing
![image](https://github.com/apache/cloudstack/assets/57355700/7fbdbb10-7ee7-4638-bc82-ded7708b4af4)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.18/4.19
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
just reviewed both solutions (@JoaoJandre ) and both seem to do the job
#8881 does it by overloading the call to create the LB commands
#8765 does it by checking which list to load from the DB

If I understand correctly this creates the list multiple times in #8765, while in #8881 it is created only once. I see no problem with either code but I think Wei has a point and we should go with the overloading solution.

Note that this is purely from a code analysis point of view. I have not had time to test either yet but have started building the envs to check them.

**Comment by DaanHoogland** [comment]
@JoaoJandre both tested and checked /etc/haproxy/haproxy.cfg to be exactly the same as before restart. (cc @weizhouapache @SadiJr )

**Comment by JoaoJandre** [comment]
> @JoaoJandre both tested and checked /etc/haproxy/haproxy.cfg to be exactly the same as before restart. (cc @weizhouapache @SadiJr )
> 
> less work then I thought.

@DaanHoogland I've also just finished testing both solutions. Both fix #8745. However, #8765 does indeed produce more commands than necessary, while #8881 will only send one command for all LBs. Thus I think we should go with #8881.

**Comment by JoaoJandre** [comment]
Fixed by #8881
