### ISSUE TITLE
Host evacuation after KVM Host failed

### ISSUE THREAD

**Issue by Psyma** [apache/cloudstack#8749]
I want to try the High Availability cloudstack 4.19

Ubuntu 22.04 -> Management server & 2 KVM Host

KVM Host has instances with Host-HA enabled (OOBM is disabled because host hardware is not supported with power management) when I shutdown this host the instances didn't evacuate to available host

Host State is "Disconnected"
Host Resource state is "Enabled"

**Comment by rajujith** [comment]
@Psyma  can you check whether the instances are HA enabled? you can check the instance details. If not enabled you can select the HA on compute offering.

**Comment by Psyma** [comment]
![Screenshot from 2024-03-06 17-59-21](https://github.com/apache/cloudstack/assets/59403530/850e4cce-0972-4584-b375-135db686e0ae)
![Screenshot from 2024-03-06 17-59-35](https://github.com/apache/cloudstack/assets/59403530/4fec8297-0f77-4ced-b350-9bb56e751c84)
![Screenshot from 2024-03-06 17-59-44](https://github.com/apache/cloudstack/assets/59403530/a0999405-c52b-48c0-aea0-0aa8132b4621)
![Screenshot from 2024-03-06 18-00-03](https://github.com/apache/cloudstack/assets/59403530/65eb1275-757b-4011-ba62-ad7c96008d8b)

**Comment by rohityadavcloud** [comment]
@Psyma host HA and VM HA are different features; if your physical hosts don't have oobm feature then host HA can't be used as designed and it can cause unknown consequences. You can still have VM HA without host HA for shared primary storage such as NFS primary storage.
