### ISSUE TITLE
Restart VM fail when attached an unbootable ISO file.

### ISSUE THREAD

**Issue by digitalgust** [apache/cloudstack#8754]
"After upgrading to CloudStack 4.19.0, I restarted some VMs and found that a few of them failed to restart successfully. The logs reported an error indicating the inability to start the VM instance, without providing further details. After some investigation, I discovered that these VMs were attached with an ISO that did not have boot functionality enabled. The 'bootable' property of this ISO was marked as false. Upon dettched this ISO, the VMs restarted normally. I believe there should be a TIPS added when attach an ISO, indicating that attaching an ISO without boot functionality may cause VM restart failure."

##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME
UI
~~~

~~~

##### CLOUDSTACK VERSION
4.19

~~~

~~~

**Comment by digitalgust** [comment]
Just I retry attach an unbootable ISO to a vm USING UI, then reboot vm from UI too, and  the vm reboot normally, retry 3times all fine.

So i suspect may be the problem is cause by secondary storage, then I reopen log of that day,  
```
 2024-03-07 00:01:18,103 DEBUG [c.c.a.t.Request] (AgentManager-Handler-7:null) (logid:) Seq 65-5109896727205250449: Processing:  { Ans: , MgmtId: 522407
74720, via: 65, Ver: v1, Flags: 10, [{"com.cloud.agent.api.Answer":{"result":"false","details":"com.cloud.utils.exception.CloudRuntimeException: Failed
 to get root directory from secondary storage URL [nfs://sec.csdomain/data/secondary], using NFS version [null], due to [Unable to mount 192.168.100.20
:/data/secondary at /mnt/SecStorage/c4d3ac9b-62c2-347f-a328-3e9b03850a19 due to mount.nfs: requested NFS version or transport protocol is not supported
].
Caused by: com.cloud.utils.exception.CloudRuntimeException: Unable to mount 192.168.100.20:/data/secondary at /mnt/SecStorage/c4d3ac9b-62c2-347f-a328-3
e9b03850a19 due to mount.nfs: requested NFS version or transport protocol is not supported

```

  I checked the logs of that day and found  number of errors. It was indeed because of a failure in the secondary storage. The secondary storage system may have been interrupted due to the upgrade of cloudstack. I don't know why I ignored this error at that time. It may be because when CS reports an error, two errors will be threw in the log. The second error does not have a detail error reason. I think I may have overlooked the first error message at that time. After I canceled the ISO mounted on the VM, the VM started normally. I tried several times later. If I attached the ISO, the VM could not start. If I detached the ISO, the VM could start normally. This made me mistakenly think that the problem was caused by the unbootable ISO. 

   Therefore, the conclusion is: the error I reported does not actually exist. It was caused by the failure of my secondary storage at that time, which led to the failure of VM startup. At that time, I did not find the real reason for the failure of VM startup.

   I 'm sorry .

**Comment by shwstppr** [comment]
@digitalgust I'm closing the issue based on your remark. Please re-open or create a new issue if are facing an issue with the secondary store
