### ISSUE TITLE
Redfish configuration failed ACS v4.19.0

### ISSUE THREAD

**Issue by psyma** [apache/cloudstack#8764]
Failed to execute HTTP GET request retry attempt 2/2 [URL: https://192.168.1.85/redfish/v1/Systems/] due to exception javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

then I tried this commands

openssl s_client -servername [redfish IP] -connect [Redfish IP]:5000 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'>/tmp/redfish.crt

keytool -import -alias [Redfish IP] -keystore /path-to-java/lib/security/cacerts -file /tmp/redfish.crt

(node185) Failed to execute HTTP GET request retry attempt 2/2 [URL: https://192.168.1.85/redfish/v1/Systems/] due to exception javax.net.ssl.SSLPeerUnverifiedException: Certificate for <192.168.1.85> doesn't match any of the subject alternative names: []

**Comment by rohityadavcloud** [comment]
I don't have a redfish compliant server to check/test, cc @GabrielBrascher @wido - can you review and advise?

**Comment by wido** [comment]
@psyma Take a look at: https://docs.cloudstack.apache.org/en/latest/adminguide/hosts.html#out-of-band-management

Have you tried the *redfish.ignore.ssl* to turn it off and on?

As it's not a valid certificate you probably have these issues. Have you tried without SSL (just to see if this works)

**Comment by psyma** [comment]
@rohityadavcloud @wido Thanks for the attention.

We disregard using the redfish instead we use IPMI.
