### ISSUE TITLE
apache cloudstack docker deployment

### ISSUE THREAD

**Issue by Gunseerat** [apache/cloudstack#8769]
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
deployment of cloudstack-simulator in dockers

##### CLOUDSTACK VERSION
latest 4.19

##### CONFIGURATION
in relevance to creating a host on cloudstack-simulator

##### OS / ENVIRONMENT
docker on ubuntu

##### SUMMARY
please help me in creating a zone, further creating a host in dockers. If it is a straight-forward normal deployment then the values of mount partitions and all other things are known. But, in case of docker deployment, how to check where mounting is done to add primary and secondary partitions while assigning clusters and hosts in a zone. I haven't found any clear tutorial or help so far.

##### STEPS TO REPRODUCE
ubuntu virtual machine is running dockers
further cloudstack-simulator is running inside a container in this virtual machine.

##### EXPECTED RESULTS
should be able to create an advanced zone

##### ACTUAL RESULTS
few details are missing.

**Comment by kiranchavala** [comment]
@Gunseerat 

https://github.com/apache/cloudstack/blob/main/tools/docker/README.md


have you executed the following command?

Advanced zone
docker exec -it simulator python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/advanced.cfg

**Comment by Gunseerat** [comment]
Hi Kiran,
I tried but are there any pre-requisites that need to be installed inside ubuntu VM to run this command because it did not work directly.

**Comment by weizhouapache** [comment]
> Hi Kiran, I tried but are there any pre-requisites that need to be installed inside ubuntu VM to run this command because it did not work directly. This file is not found, does this need any other software to be added ? /root/tools/marvin/marvin/deployDataCenter.py

@Gunseerat 
do you use the official docker image ?
https://hub.docker.com/r/apache/cloudstack-simulator

**Comment by Gunseerat** [comment]
> > Hi Kiran, I tried but are there any pre-requisites that need to be installed inside ubuntu VM to run this command because it did not work directly. This file is not found, does this need any other software to be added ? /root/tools/marvin/marvin/deployDataCenter.py
> 
> @Gunseerat do you use the official docker image ? https://hub.docker.com/r/apache/cloudstack-simulator

Yes, anyhow I tried the following within container and it has resolved the issue.
Thank you so much for helping!
