### ISSUE TITLE
UI: Missing button remove vmware datacenter

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8773]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### SUMMARY

The 'remove vmware datacenter' button on the zone having a vmware datacenter is missing in 4.19. API works fine.

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/8781
