### ISSUE TITLE
Guest has not initialized the display (yet). When UEFI is enabled.

### ISSUE THREAD

**Issue by ahmedali6** [apache/cloudstack#8784]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### OS / ENVIRONMENT

OS:

```bash 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

uefi.properties:

```
guest.nvram.template.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS.fd
guest.loader.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
guest.nvram.path=/var/lib/libvirt/qemu/nvram/
guest.loader.legacy=/usr/share/OVMF/OVMF_CODE.secboot.fd
```

```
-> ls /usr/share/OVMF/
OVMF_CODE_4M.fd     OVMF_CODE_4M.secboot.fd   OVMF_CODE.fd     OVMF_CODE.secboot.fd  OVMF_VARS_4M.ms.fd        OVMF_VARS.fd
OVMF_CODE_4M.ms.fd  OVMF_CODE_4M.snakeoil.fd  OVMF_CODE.ms.fd  OVMF_VARS_4M.fd       OVMF_VARS_4M.snakeoil.fd  OVMF_VARS.ms.fd
```

Host:

![image](https://github.com/apache/cloudstack/assets/87921765/c3efe0b7-c0df-4235-ba93-7d3c48ddb08a)

##### SUMMARY

When deploying any VM with UEFI enable I keep getting this message:

```
Guest has not initialized the display (yet).
```

##### STEPS TO REPRODUCE

~~~
Deploy a VM with UEFI enabled.
~~~

##### EXPECTED RESULTS

~~~
The VM should boot successfully.
~~~

##### ACTUAL RESULTS

~~~
The VM does not boot.
~~~
![image](https://github.com/apache/cloudstack/assets/87921765/1c2fa65a-106e-4cf3-bbac-6fe65529c70f)

**Comment by ahmedali6** [comment]
@kiranchavala Yes I did that. Here is the VM settings:

![image](https://github.com/apache/cloudstack/assets/87921765/df3a8d67-b7b6-48ca-8f5e-8a95a668b06d)

**Comment by weizhouapache** [comment]
@ahmedali6 
the uefi.properties is misconfigured
```
guest.nvram.template.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
```
it should be set to `OVMF_VARS.xxx.fd`, not `OVMF_CODE.secboot.fd`

**Comment by ahmedali6** [comment]
@weizhouapache
Do you know which one should I put? there is multiple ones starting with OVMF_VARS

```
-> ls /usr/share/OVMF/
OVMF_CODE_4M.fd     OVMF_CODE_4M.secboot.fd   OVMF_CODE.fd     OVMF_CODE.secboot.fd  OVMF_VARS_4M.ms.fd        OVMF_VARS.fd
OVMF_CODE_4M.ms.fd  OVMF_CODE_4M.snakeoil.fd  OVMF_CODE.ms.fd  OVMF_VARS_4M.fd       OVMF_VARS_4M.snakeoil.fd  OVMF_VARS.ms.fd
```

**Comment by weizhouapache** [comment]
> @weizhouapache Do you know which one should I put? there is multiple ones starting with OVMF_VARS
> 
> ```
> -> ls /usr/share/OVMF/
> OVMF_CODE_4M.fd     OVMF_CODE_4M.secboot.fd   OVMF_CODE.fd     OVMF_CODE.secboot.fd  OVMF_VARS_4M.ms.fd        OVMF_VARS.fd
> OVMF_CODE_4M.ms.fd  OVMF_CODE_4M.snakeoil.fd  OVMF_CODE.ms.fd  OVMF_VARS_4M.fd       OVMF_VARS_4M.snakeoil.fd  OVMF_VARS.ms.fd
> ```

@ahmedali6 
you can use `OVMF_VARS.ms.fd` or `OVMF_VARS_4M.ms.fd`

**Comment by ahmedali6** [comment]
@weizhouapache 

I tried both of them and restarted the agent but still not working. Maybe worth knowing that even when I set UEFI to LEGACY I have the same issue.

**Comment by ahmedali6** [comment]
This is how the uefi.properties looks now:

```
guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS.fd
guest.loader.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
guest.nvram.path=/var/lib/libvirt/qemu/nvram/
guest.loader.legacy=/usr/share/OVMF/OVMF_CODE.secboot.fd
```

**Comment by weizhouapache** [comment]
> This is how the uefi.properties looks now:
> 
> ```
> guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
> guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS.fd
> guest.loader.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
> guest.nvram.path=/var/lib/libvirt/qemu/nvram/
> guest.loader.legacy=/usr/share/OVMF/OVMF_CODE.secboot.fd
> ```

try with the following, it worked for me
```
guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS_4M.fd
guest.nvram.path=/var/lib/libvirt/qemu/nvram/
guest.loader.secure=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd
guest.loader.legacy=/usr/share/OVMF/OVMF_CODE_4M.fd
```

**Comment by ahmedali6** [comment]
@weizhouapache 

The VM now works! Thank you.

**Comment by tdtmusic2** [comment]
> > This is how the uefi.properties looks now:
> > ```
> > guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
> > guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS.fd
> > guest.loader.secure=/usr/share/OVMF/OVMF_CODE.secboot.fd
> > guest.nvram.path=/var/lib/libvirt/qemu/nvram/
> > guest.loader.legacy=/usr/share/OVMF/OVMF_CODE.secboot.fd
> > ```
> 
> try with the following, it worked for me
> 
> ```
> guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
> guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS_4M.fd
> guest.nvram.path=/var/lib/libvirt/qemu/nvram/
> guest.loader.secure=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd
> guest.loader.legacy=/usr/share/OVMF/OVMF_CODE_4M.fd
> ```

Hi Wei. In my case there is no OVMF_VARS-4M.ms.fd file in that location, only the files bellow. Also the nvram folder is empty, don't know if something is supposed to be there. The edk2-ovmf package is installed.

`OVMF_CODE.secboot.fd  OVMF_VARS.fd  OVMF_VARS.secboot.fd  UefiShell.iso`

**Comment by dtorressn** [comment]
Thank you all. The following `/etc/cloudstack/agent/uefi.properties` works on Ubuntu 24.04 LTS too.
```
guest.nvram.template.secure=/usr/share/OVMF/OVMF_VARS_4M.ms.fd
guest.nvram.template.legacy=/usr/share/OVMF/OVMF_VARS_4M.fd
guest.nvram.path=/var/lib/libvirt/qemu/nvram/
guest.loader.secure=/usr/share/OVMF/OVMF_CODE_4M.secboot.fd
guest.loader.legacy=/usr/share/OVMF/OVMF_CODE_4M.fd
```
