### ISSUE TITLE
UI: Job is cancelled as it has been blocking others for too long

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#8797]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

Advanced Networking
KVM
SharedMountPoint

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

After upgrade to 4.19, UI report `Unable to serialize: Job is cancelled as it has been blocking others for too long` frequently for each operation, such as start VM, stop VM, taking snapshot..etc

##### STEPS TO REPRODUCE

Just perform random VM operation, 1/3 chance will get this error message, however the operation are  executed successfully no wonder it is real success or error.

##### EXPECTED RESULTS

Should report correct state of the job, and job queue and tasks timeout should respect the ACS timeout configurations.

##### ACTUAL RESULTS

Random error message regardless the actual task status.

~~~
Unable to serialize: Job is cancelled as it has been blocking others for too long
~~~

**Comment by levindecaro** [comment]
suspecting this issue is related to time sync between two management server, the problem significantly reduced after time correction.

**Comment by DaanHoogland** [comment]
> suspecting this issue is related to time sync between two management server, the problem significantly reduced after time correction.

So we can close this issue?

**Comment by levindecaro** [comment]
@DaanHoogland yes, i dont have further input on this issue at this moment.
