### ISSUE TITLE
Unable to build Marvin

### ISSUE THREAD

**Issue by rp-** [apache/cloudstack#8799]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
TEST-TOOL
~~~

##### CLOUDSTACK VERSION

~~~
main branch
~~~

##### OS / ENVIRONMENT

ArchLinux

##### SUMMARY

Marvin fails to build

##### STEPS TO REPRODUCE

~~~
rp@frami /tmp » git clone https://github.com/apache/cloudstack.git
Cloning into 'cloudstack'...
remote: Enumerating objects: 799392, done.
remote: Counting objects: 100% (592/592), done.
remote: Compressing objects: 100% (417/417), done.
remote: Total 799392 (delta 107), reused 442 (delta 60), pack-reused 798800
Receiving objects: 100% (799392/799392), 572.64 MiB | 19.77 MiB/s, done.
Resolving deltas: 100% (480675/480675), done.
rp@frami /tmp » cd cloudstack 
rp@frami /tmp/cloudstack ±main » export JAVA_HOME=/usr/lib/jvm/java-11-openjdk                                                                                                                                   1 ↵
rp@frami /tmp/cloudstack ±main » mvn -P developer -pl :cloud-marvin           
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< org.apache.cloudstack:cloud-marvin >-----------------
[INFO] Building Apache CloudStack marvin 4.20.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] The POM for org.apache.cloudstack:cloud-apidoc:pom:4.20.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.485 s
[INFO] Finished at: 2024-03-19T09:10:59+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-marvin: Could not resolve dependencies for project org.apache.cloudstack:cloud-marvin:pom:4.20.0.0-SNAPSHOT: org.apache.cloudstack:cloud-apidoc:pom:4.20.0.0-SNAPSHOT was not found in https://repo.jenkins-ci.org/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo.jenkins-ci.org.public has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
~~~

##### EXPECTED RESULTS

~~~
Marin successfully built
~~~

##### ACTUAL RESULTS

~~~
[ERROR] Failed to execute goal on project cloud-marvin: Could not resolve dependencies for project org.apache.cloudstack:cloud-marvin:pom:4.20.0.0-SNAPSHOT: org.apache.cloudstack:cloud-apidoc:pom:4.20.0.0-SNAPSHOT was not found in https://repo.jenkins-ci.org/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo.jenkins-ci.org.public has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
~~~

**Comment by weizhouapache** [comment]
> ```
> [INFO] Apache CloudStack Plugin - Stratosphere SSP ........ SUCCESS [  4.379 s]
> [INFO] Apache CloudStack Plugin - Network Brocade VCS ..... SUCCESS [  7.096 s]
> [INFO] Apache CloudStack Plugin - Network VXLAN ........... SUCCESS [  4.194 s]
> [INFO] Apache CloudStack Plugin - NSX Network ............. FAILURE [ 16.137 s]
> [INFO] Apache CloudStack Plugin - Power Management Driver ipmitool SKIPPED
> [INFO] Apache CloudStack Plugin - Power Management Driver nested-cloudstack SKIPPED
> [INFO] Apache CloudStack Plugin - Power Management Driver Redfish SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Image default provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Image S3 provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Image sample provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Image Swift provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume CloudByte Provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume Datera Provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume Nexenta Provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume sample provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume Linstor provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume StorPool provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume Adaptive Base Provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume - Pure Flash Array SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Volume - HPE Primera SKIPPED
> [INFO] Apache CloudStack Plugin - MinIO object storage provider SKIPPED
> [INFO] Apache CloudStack Plugin - Simulator object storage provider SKIPPED
> [INFO] Apache CloudStack Plugin - Storage Allocator Random  SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator LDAP . SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator MD5 .. SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator OAuth2 SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator PBKDF2-SHA-256 SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator Plain Text SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator SAML2  SKIPPED
> [INFO] Apache CloudStack Plugin - User Authenticator SHA256 Salted SKIPPED
> [INFO] Apache CloudStack Plugin - User Two Factor Authenticator TOTP SKIPPED
> [INFO] Apache CloudStack Plugin - User Two Factor Authenticator Static Pin SKIPPED
> [INFO] Apache CloudStack Framework - Spring Module ........ SKIPPED
> [INFO] Apache CloudStack Secondary Storage Controller ..... SKIPPED
> [INFO] Apache CloudStack Console Proxy .................... SKIPPED
> [INFO] Apache CloudStack Console Proxy - RDP Client ....... SKIPPED
> [INFO] Apache CloudStack Console Proxy - Server ........... SKIPPED
> [INFO] Apache CloudStack System VM ........................ SKIPPED
> [INFO] Apache CloudStack Client UI ........................ SKIPPED
> [INFO] Apache CloudStack Framework - QuickCloud ........... SKIPPED
> [INFO] Apache CloudStack Test ............................. SKIPPED
> [INFO] Apache CloudStack Developer Mode ................... SKIPPED
> [INFO] Apache CloudStack Developer Tools .................. SKIPPED
> [INFO] Apache CloudStack apidocs .......................... SKIPPED
> [INFO] Apache CloudStack marvin ........................... SKIPPED
> [INFO] Apache CloudStack DevCloud4 ........................ SKIPPED
> [INFO] Apache CloudStack DevCloud-KVM ..................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  10:23 min
> [INFO] Finished at: 2024-03-19T10:37:02+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project cloud-plugin-network-nsx: Could not resolve dependencies for project org.apache.cloudstack:cloud-plugin-network-nsx:jar:4.20.0.0-SNAPSHOT: The following artifacts could not be resolved: com.vmware:nsx-java-sdk:jar:4.1.0.2.0, com.vmware:nsx-gpm-java-sdk:jar:4.1.0.2.0, com.vmware:nsx-policy-java-sdk:jar:4.1.0.2.0, com.vmware.vapi:vapi-authentication:jar:2.40.0, com.vmware.vapi:vapi-runtime:jar:2.40.0: Could not find artifact com.vmware:nsx-java-sdk:jar:4.1.0.2.0 in repo.jenkins-ci.org.releases (https://repo.jenkins-ci.org/releases/) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :cloud-plugin-network-nsx
> ```

@rp- 
can you try #8772 ?

**Comment by rp-** [comment]
@weizhouapache 
After that it worked and now also
`mvn -P developer -pl :cloud-marvin`
works.

**Comment by weizhouapache** [comment]
> But the question for me is, isn't Marvin just a python tool/package? What has it todo with apidoc? or why is apidoc failing in the beginning.

@rp- 
the marvin module automatically generates the python files for CloudStack APIs. 
the list of CloudStack APIs is generated by apidoc module which has dependencies on cloud-server and cloud-client-ui, so you need to compile the whole project at first.

**Comment by rp-** [comment]
Then this should maybe added to the Marvin wiki page

**Comment by rp-** [comment]
added full build info to the wiki
