### ISSUE TITLE
UI: After wrong pass/login, the UI does not load any more

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#8803]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

Try logging in with a wrong password - the auth attempt never fails, the UI will continue to load forever... and if you close the tab/window, and open the same UI login page - it never opens up - see the recording below:

https://somup.com/cZeq0ZCX3O

**Comment by vishesh92** [comment]
This is a duplicate of https://github.com/apache/cloudstack/issues/8662 and PR for the fix is https://github.com/apache/cloudstack/pull/8671

**Comment by andrijapanicsb** [comment]
Excellent, thx @vishesh92 !

**Comment by DaanHoogland** [comment]
closing as duplicate of #8662
