### ISSUE TITLE
UI: Dashboard shows incorrect count of virtual routers

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8804]
ISSUE TYPE

BUG 

Component Name

UI

CLOUDSTACK VERSION

Cloudstack version 4.19 

SUMMARY

UI: Dashboard shows incorrect count of virtual routers

Steps to reproduce the issue

1. Create a Project 

2. Change into project view and launch a vpc network  and make sure the virtual router is running

3. Change back to default view , Launch a isolated network , make sure the router is running for the network

4. Click on Dashboard, you will see the count of virtual routers will be 1. The virtual routers associated with a project are not shown

<img width="620" alt="Screenshot 2024-03-20 at 10 13 57 AM" src="https://github.com/apache/cloudstack/assets/1401014/8dac07f4-8a27-4bab-ac74-652909758843">

Cloudstack is executing the following api here

https://cloudstack.apache.org/api/apidocs-4.19/apis/listRouters.html

5. The issue is not observed if the user clicks on  Infrastructure > Summary

<img width="1372" alt="Screenshot 2024-03-20 at 10 10 33 AM" src="https://github.com/apache/cloudstack/assets/1401014/cce61fce-4f57-45dc-9f16-c9403da1088f">

Cloudstack is executing the following api here

https://cloudstack.apache.org/api/apidocs-4.19/apis/listInfrastructure.html

Actual Behaviour

Admin user should  is not seeing the correct count of virtual routers

Expected Behaviour

Admin user should see the correct the count of virtual routers

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/8807
