### ISSUE TITLE
KVM Host-HA using CEPH RBD

### ISSUE THREAD

**Issue by Psyma** [apache/cloudstack#8805]
I was able to use KVM Host-HA using NFS as primary storage it works great.

If I use CEPH RBD as primary storage KVM Host-HA is not working.

Does it mean KVM Host-HA only works with NFS ?

**Comment by weizhouapache** [comment]
> I was able to use KVM Host-HA using NFS as primary storage it works great.
> 
> If I use CEPH RBD as primary storage KVM Host-HA is not working.
> 
> Does it mean KVM Host-HA only works with NFS ?

it is also supported for storpool storage. #8045

There is a PR to support ceph storage. #5862 , it is not merged yet.

**Comment by Psyma** [comment]
@weizhouapache Thank you
