### ISSUE TITLE
Disable Service offerings

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8817]
##### ISSUE TYPE

 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
UI,API
~~~

##### SUMMARY

It would be useful to enable and disable compute, disk offerings. It is available in network offering. As an operator I may want to disallow further allocation of resources using a certain offering anymore.

**Comment by rajujith** [comment]
Workaround available now: `update service_offering set state='Inactive' where uuid='65ffaa0c-2b79-410e-aa90-8464112a0d8c';`

**Comment by vishesh92** [comment]
@rajujith If the service offering is compute only, you will also need to update the state of disk offering to Inactive.

 As of now Delete service offering command, sets the state to Inactive for the service offering and associated disk offering and not actually delete from the database. You can just execute delete service offering command to hide the service offerings.

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/8821
