### ISSUE TITLE
Update custom plugins documentation 

### ISSUE THREAD

**Issue by furyflash777** [apache/cloudstack#8830]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### OS / ENVIRONMENT

Javascript/HTML 

##### SUMMARY

I am trying to create custom page (plugin). 
I added 

  "plugins": [
          {
      "name": "ExamplePlugin",
      "icon": "appstore",
      "path": "myplugin.html"
    },
    {
      "name": "ExamplePlugin1",
      "icon": "fire",
      "path": "https://example.com"
    }
  ],

Simple javascript functions are working well. 
But I can't adopt examples from https://docs.cloudstack.apache.org/en/latest/developersguide/plugins.html
to this new one.

Could you please provide example for apiCall 'listVirtualMachines' for simple html script. 
Where can I find javascript cloudstack libs guide?

sorry I am not familiar with javascript  

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
There are some examples to be found under <project>/ui/src/views/auth/Login.vue

Documentation needs constant improvement and might indeed be outdated. If you have any suggestions for updating it, please share.

**Comment by rohityadavcloud** [comment]
The UI development docs are here:
https://github.com/apache/cloudstack/tree/main/ui#readme
https://github.com/apache/cloudstack/tree/main/ui/docs

Raise doc PR to address the cleanup of old UI/plugin docs https://github.com/apache/cloudstack-documentation/pull/404
