### ISSUE TITLE
Improve Useability of ACL Rules for Large Scale Projects (or long term maintanence)

### ISSUE THREAD

**Issue by btzq** [apache/cloudstack#8841]
##### ISSUE TYPE

 * Improvement Request
 
##### COMPONENT NAME

~~~
Improvement Request (UI, Functionality)
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

As an admin, I find creating and manaing ACL Rules to be painful at the moment. 

Here are a few ideas id like to propose to improve the useability for long term, and large scale projects.

**1. Display ACL Rules in the form of a excel like table** 
- Currently the UI for ACL Rules is in a 2x4 Column
- It makes it hard to scan and read. 
- Also, depending on the input, the columns can be hidden/shown. Which makes it even harder to read as every rule can have a different arrangement. 

**2. Allow users to import ACL from a CSV File**
- As an admin, id like the ability to plan my ACL lists offline first in an excel.
- Once ive finalised my list, i would like to be able to import it to cloudstack via CSV
- This would greatly help my workflow (i can also keep the excel as a backup)

**3. Allow users to Search ACL Rule**
- In large scale projects like ours, we have around 20-40 ACL Rules.
- As the rules increase, its hard to read and identify. 
- Supporting search ACL Rule would help. 

**4. Display Tags in the UI for each ACL Rule**
- Tags are supported in the GUI, but they are not displayed. 
- If tags are shown in the UI, it makes it easier to scan

**5. Support ability to Filter by Tags**
- This is self explanatory, makes managing ACL rules easier for large lists. 

**6. Allow user to create an ACL Rule for Multiple Ports**
- I remember reading somewhere that the logic is supported (Eg. Terraform Provider Docs)
- But the UI doesnt seem to support it. 
- This will help greatly reduce the number of rules we create. 

**7. Export ACL List is missing some data**
- For example, 'Ports' are not available in the exported CSV when exported. 
- There may be others that are missing from the CSV output too. 

**8. Support ACL on Public IP**
- Good to have, adds more security

**9. Support Destination CIDR**
- Good to have, adds more security
- Reduces number of ACL Rules required

**10. Option to set ACL Rule to be the very bottom by default**
- At the very end of our ACL Rule, we usually have a 'Deny All'
- But when i use API or Terraform to create ACL Rules, the arrangement and sequence (including the rule number) gets all messed up. 
- Would be great if we could have a parameter and function in the UI to make the rule fix itself at the bottom of the list.

I know its a long list. Thank you for reading!

##### STEPS TO REPRODUCE

~~~
Experiencing this issue cause our projects are getting bigger and bigger.
~~~

##### EXPECTED RESULTS

~~~
Better experience using ACL Rules
~~~

##### ACTUAL RESULTS

~~~
Challenging to use ACL rules for large scale projects.
~~~

**Comment by btzq** [comment]
Created! Will close this ticket.

**Comment by DaanHoogland** [comment]
thanks @btzq , much appreciated.
