### ISSUE TITLE
Fix error message on deletion of default system service offerings

### ISSUE THREAD

**Issue by vishesh92** [apache/cloudstack#8882]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
System service offerings
~~~

##### CLOUDSTACK VERSION

~~~
all
~~~

##### SUMMARY

On deleting a default system service offering, an error with text "Default service offerings cannot be deleted" is shown which can be confusing to the end user.

##### STEPS TO REPRODUCE

Delete any default system service offering.

##### EXPECTED RESULTS

~~~
A better error message as to why I can't delete the default system service offerings.
~~~

##### ACTUAL RESULTS

~~~
Got an error message saying "Default service offerings cannot be deleted"
~~~

![image](https://github.com/apache/cloudstack/assets/8760112/5e2d2211-9fc9-4f6a-a987-ca7688792a4f)

cc: @DaanHoogland

**Comment by DaanHoogland** [comment]
fixed in #8883
