### ISSUE TITLE
CKS Cluster goes into alert state when a node is expunged

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#8902]
ISSUE TYPE

Improvement request/BUG

COMPONENT NAME

Component: CKS

CLOUDSTACK VERSION

Cloudstack version 4.18 4.19

SUMMARY

CKS Cluster goes into an alert state when a vm part of the cluster is  destoryed/expunged

Steps to reproduce the issue

1. Create a cks cluster with a worker size let's say 2
2. Wait till cks cluster is in running state
3.  Expunge one of the worker node vm
4. The cks cluster goes into alert state

Expected behaviour 

Cloudstack should throw an error popup message when user tries to delete a vm which is part of a cks cluster.

"Expunge is not allowed as its part of a cks cluster."

This could be the same behaviour when we try to delete a vpc which has active tier in it 

Actual behaviour 

Currently, Cloudstack allows to deletion a vm which is part of a cks cluster

**Comment by DaanHoogland** [comment]
fixed in 9057
