### ISSUE TITLE
Refine SMBIOS info for KVM or Others

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#8912]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
KVM
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Current provided smbios information is altered by ACS when spinning up the instance, some third party software is relying on the "product" entity from dmidecode output to determine what is the underlying hypervisor, as the result, they are not compatible with CloudStack because they want a single "KVM" product name where should be ordinary. 
 
Example code from ACS
```
guestDef.append("<entry name='product'>CloudStack " + _type.toString() + " Hypervisor</entry>\n");
```

Shall we use `vendor` instead of `product`, and just inherit the `product` information come from the kvm package.?

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by levindecaro** [comment]
Just cross checked with cloud-init, it is require this metadata to do initialization, seems no solution.

**Comment by DaanHoogland** [comment]
@levindecaro , I am a bit confused about what you are asking here. 

Do you want "KVM" as an answer for your query to "product" ?

**Comment by kiranchavala** [comment]
@levindecaro 

Currently the following information is exported as metadata by cloudstack 

Do you want a hypervisor field exported as a metadata ?



```
For metadata type, use one of the following:

    service-offering. A description of the instances service offering

    availability-zone. The Zone name

    local-ipv4. The guest IP of the instance

    local-hostname. The hostname of the instance

    public-ipv4. The first public IP for the router.

    public-hostname. This is the same as public-ipv4

    instance-id. The instance name of the instance

```


Ref :
http://docs.cloudstack.apache.org/en/4.19.0.0/adminguide/virtual_machines/user-data.html

**Comment by NuxRo** [comment]
> Just cross checked with cloud-init, it is require this metadata to do initialization, seems no solution.

You could instruct cloud-init it's running on CloudStack by means of config file.

**Comment by levindecaro** [comment]
@kiranchavala @NuxRo @DaanHoogland 

Yes, I'm interested in exploring whether there's a method to override or find a workaround for the system information provided by ACS KVM deployment. Over the years, I've encountered several instances where certain Virtual Appliance distributors such as Dell and HPE utilize the output of dmidecode for their VM deployment. They specifically look for matches such as "Red Hat," "Ubuntu," "KVM," or "VMware" in the output to initiate their kickstart processes. It's frustrating to find that our KVM setup might be misinterpreted due to these SMBIOS details. Therefore, I'm inquiring about the possibility of bypassing this information modification. Upon researching, I've discovered that cloud-init also relies on this system information for its operations. Consequently, I currently find myself needing to adjust the XML configuration post ACS deployment.
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Apache Software Foundation</entry>
      <entry name='product'>CloudStack KVM Hypervisor</entry>
      <entry name='uuid'>b45bc7cf-d544-4172-8aba-22eee31d98d5</entry>
    </system>
  </sysinfo>

**Comment by weizhouapache** [comment]
@levindecaro 
I did a quick test on the changes on VM XML definition
```
-      <entry name='product'>CloudStack KVM Hypervisor</entry>
+      <entry name='vendor'>CloudStack KVM Hypervisor</entry>
```

what I found are
- `virsh dumpxml` shows there is no `vendor` after the change

```
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>Apache Software Foundation</entry>
      <entry name='uuid'>4d37861f-9be8-472b-af8e-8e896b9ed4b7</entry>
    </system>
  </sysinfo>
```

- `dmidecode` command shows the product name is changed to `KVM` instead of `CloudStack KVM Hypervisor`

```
 Handle 0x0100, DMI type 1, 27 bytes
 System Information
 	Manufacturer: Apache Software Foundation
-	Product Name: CloudStack KVM Hypervisor
+	Product Name: KVM
 	Version: RHEL 7.6.0 PC (i440FX + PIIX, 1996)
 	Serial Number: Not Specified
 	UUID: 4D37861F-9BE8-472B-AF8E-8E896B9ED4B7
```

As I know, this will break the datasource check on CloudStack in cloud-init, which checks the product name in `dmidecode` output.

```
dscheck_CloudStack() {
    is_container && return ${DS_NOT_FOUND}
    dmi_product_name_matches "CloudStack*" && return $DS_FOUND
    return $DS_NOT_FOUND
}
```
https://github.com/canonical/cloud-init/blob/5d587ecd0dfd952ad17caa123de9d954c3ceb07d/tools/ds-identify#L786-L790
of course you can skip ds-identify by
```
echo "policy: enabled" >  /etc/cloud/ds-identify.cfg
```

**Comment by levindecaro** [comment]
@weizhouapache 

Thanks for confirming this, so i don't have option to workaround it either remove the "product" from LibvirtVMDef break cloud-init or skip ds-identify breaks all existing template.

Is is possible to make a toggle switch that disable smbios modification or for higher flexibility, a override hook like `extraconfig`  which override specific xml tag?

**Comment by weizhouapache** [comment]
@levindecaro 

extraconfig seems to work

I added a new section in vm xml,
```
   </resource>
   <sysinfo type='smbios'>
     <system>
+      <entry name='manufacturer'>Apache</entry>
+      <entry name='product'>CloudStack</entry>
+    </system>
+  </sysinfo>
+  <sysinfo type='smbios'>
+    <system>
       <entry name='manufacturer'>Apache Software Foundation</entry>
       <entry name='product'>CloudStack KVM Hypervisor</entry>
       <entry name='uuid'>4d37861f-9be8-472b-af8e-8e896b9ed4b7</entry>
```

The `dmidecode` shows the product has been changed to
```
System Information
        Manufacturer: Apache
        Product Name: CloudStack
```

**Comment by levindecaro** [comment]
@weizhouapache 

Oh.. right, it works, thanks for your time.
