### ISSUE TITLE
VSAN Storage Policy Question

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#8914]
##### ISSUE TYPE

 * Other: Question About VSAN Storage Policy

##### CLOUDSTACK VERSION
4.17.2

##### OS / ENVIRONMENT
ESXi Cluster 

##### SUMMARY
I create a VSAN Storage Policy In vCenter But I noticed that after choosing VSAN Storage Policy In Creating Disk Offering. CloudStack Only Uses it For DATADISK. 
is there any way to use it for ROOTDISK?

##### STEPS TO REPRODUCE
Create Disk Offering With Specific VSAN Storage Policy

##### EXPECTED RESULTS
I Need My VSAN Storage Policy Sets On ROOTDISK

##### ACTUAL RESULTS
CloudSack Use my vsan storage policy just on DATADISK

**Comment by harikrishna-patnala** [comment]
If you have created the storage policy after the zone is created in CloudStack you can import the new policies using importVsphereStoragePolicies or updateZone APIs.

**Comment by ahmadamirahmadi007** [comment]
i can fetch all storage policy in cloudstack but when i create vm from that disk offering, policy just apply to DATADISK not to ROOTDISK. i mean when i check vm setting on vcenter the datadisk is only configure with that specific vsan policy and rootdisk policy stay on default storage policy. 
![image](https://github.com/apache/cloudstack/assets/104001728/6f1d7f7c-1351-4dec-b45f-590a763604cf)

**Comment by harikrishna-patnala** [comment]
@ahmadamirahmadi007 You need to select the storage policy on the compute offering inorder to get it applied to the root disk. If it is set only on disk offering that it will be applied only on data disk.

1. create a new compute offering with selected storage policy
2. create vm with that compute offering 

You will be able see the policy applied on the root disk as well

**Comment by ahmadamirahmadi007** [comment]
I did exactly that. The result has not changed. @harikrishna-patnala

**Comment by harikrishna-patnala** [comment]
@ahmadamirahmadi007 let me quickly test this and get back to you.

**Comment by harikrishna-patnala** [comment]
@ahmadamirahmadi007 it was working fine in my case. Following are the steps that I've followed
1. Created a storage tag on the datastore on vCenter
2. Created a new storage policy named "tag"
3. Imported the storage policies into CloudStack and created a new service/compute offering with it
![image](https://github.com/apache/cloudstack/assets/3348673/88772b67-43a2-4846-94e3-f10ee235450a)

4. Created a new Instance using that compute offering.
5. VM's root volume is created on the tagged storage and I can see the policy configured on the VM on vCenter
![image](https://github.com/apache/cloudstack/assets/3348673/4e8ee75e-4e6a-495c-9581-a82a15f4a2d4)

**Comment by ahmadamirahmadi007** [comment]
could you please tell me about steps of creating policy in vcenter . i do follow steps for creating my vsan policy:
1- vm storage policy 
2- enable rules for vsan storage
3- choose my vsan option
and with that i can see my policy in cloud stack
![Untitled](https://github.com/apache/cloudstack/assets/104001728/70df50ef-f88c-44aa-b9ac-20b0968c8b1a)
i dont create any tag for that in vcenter @harikrishna-patnala

**Comment by harikrishna-patnala** [comment]
@ahmadamirahmadi007 I just used tag as an example, it should work for other types of policies also.

May I know how you have created the compute offering. Did you select disk offering for the root volume while creating the compute offering ? I mean the below

![image](https://github.com/apache/cloudstack/assets/3348673/3ea06d6f-c1de-4106-809a-9b0e3b11c280)

**Comment by harikrishna-patnala** [comment]
I could reproduce this issue when I created the compute offering like I mentioned above. It was working fine when there is no disk offering associated to the compute offering.

@ahmadamirahmadi007 Can you please confirm if it is the same case for you.

**Comment by ahmadamirahmadi007** [comment]
yes. i created my compute offering like you exactly. root disk does not get my compute offering with specific storage policy but the data disk choose correct policy.
![diskoffer](https://github.com/apache/cloudstack/assets/104001728/da347543-d3ce-4c86-8425-f4e57467b511)
![compute](https://github.com/apache/cloudstack/assets/104001728/2389f204-259c-4257-a833-8039ef25fe2f)
![disks](https://github.com/apache/cloudstack/assets/104001728/f42fff87-f891-4d54-8a44-01ce484cb9e2)

**Comment by harikrishna-patnala** [comment]
thanks for confirming @ahmadamirahmadi007 

So to conclude, VSAN storage policy is not getting applied to the root disk when a disk offering is associated with the compute offering.

Steps to reproduce the issue

1. Create a disk offering with a storage policy selected
2. Create a compute offering and associate the above created disk offering in that compute offering
3. Create an instance using the above compute offering
4. Expectation is that the storage policy selected in the disk offering should be applied on the root disk, but it is not happening.

@ahmadamirahmadi007 As a workaround, you can try creating a compute offering without associating a disk offering to it and select the storage policy in the compute offering itself.

**Comment by ahmadamirahmadi007** [comment]
Thank you for taking the time for me. @harikrishna-patnala

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9203 pl re-open if it needs further discussion, thanks for reporting the issue.
