### ISSUE TITLE
AMD Mi300x - Launch end of April 2024

### ISSUE THREAD

**Issue by Dominic46515** [apache/cloudstack#8920]
AMD is launching their cost effective GPU in the market by end of April 2024 , currently it is not compatible with Apache Cloud Stack , due to huge demand in the market for GPU's this will become a potential requirement that cloud stack users would be looking for 

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by btzq** [comment]
+1 on this. 

Would be great if cloudstack can support any GPU, irregardless of brand.

**Comment by rohityadavcloud** [comment]
Thanks for the suggestion. We may be looking into a first-class GPU feature that's agnostic of build/model, as testing/supporting every other model isn't possible but any pull requests are welcome.

For now this isn't a bug, we'll need to close it.

**Comment by Dominic46515** [comment]
We are looking for Apache cloudstack developers , let me know if any feasiblity From: Rohit Yadav ***@***.***>Date: Tuesday, 30 April 2024 at 20:38To: apache/cloudstack ***@***.***>Cc: Dominic46515 ***@***.***>, Author ***@***.***>Subject: Re: [apache/cloudstack] AMD Mi300x - Launch end of April 2024 (Issue #8920)Thanks for the suggestion. We may be looking into a first-class GPU feature that's agnostic of build/model, as testing/supporting every other model isn't possible but any pull requests are welcome.For now this isn't a bug, we'll need to close it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by rohityadavcloud** [comment]
@Dominic46515 I don't have your email to advise further, could you drop me an email: rohit.yadav AT shapeblue.com
