### ISSUE TITLE
Routes are not ensured when connect to VM console via WebSocket

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8921]
When connect to vm console via tunnel or directly, the routes are ensured. 

https://github.com/apache/cloudstack/blob/45daa1ce591a43442c30cc6ec9a70124440063eb/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java#L291-L297

https://github.com/apache/cloudstack/blob/45daa1ce591a43442c30cc6ec9a70124440063eb/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java#L301-L302

However, when connect to console via websocket url, router are not ensured

https://github.com/apache/cloudstack/blob/45daa1ce591a43442c30cc6ec9a70124440063eb/services/console-proxy/server/src/main/java/com/cloud/consoleproxy/ConsoleProxyNoVncClient.java#L287-L288

The issue only impacts the VMs on the ESXi 7 hosts in a different subnet than the subnet in which CPVM was created.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19/4.20
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
fixed in #8922
