### ISSUE TITLE
Qemu agent is not installed after importing from VMware

### ISSUE THREAD

**Issue by ahmedali6** [apache/cloudstack#8926]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

When importing an Ubuntu VM from VMware to ACS the qemu-agent is not automatically installed on the VM although according to this release notes from [virt-v2v](https://www.libguestfs.org/virt-v2v-release-notes-2.2.1.html) it should automatically install the qemu-agent

##### STEPS TO REPRODUCE

~~~
Migrate an Ubuntu machine from VMware to ACS

~~~

##### EXPECTED RESULTS

~~~
qemu-agent should be installed automatically in the VM
~~~

##### ACTUAL RESULTS

~~~
No qemu-agent was found
~~~

**Comment by DaanHoogland** [comment]
@ahmedali6 , this is not a cloudstack issue, check your guest os and virt-v2v versions. see [the third note in this paragraph of the docs on this subject](https://docs.cloudstack.apache.org/en/latest/adminguide/virtual_machines.html#converting-and-importing-a-vmware-vm)

**Comment by ahmedali6** [comment]
@DaanHoogland Thank you for the fast reply. It was my mistake I had an old version virt-v2v installed.
