### ISSUE TITLE
Template is not Ready if there are multiple zones

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8928]
There are two zones in the environment: KVM and VMware

When register a template for all zones, it is stuck at the following status

![image](https://github.com/apache/cloudstack/assets/57355700/325f22f5-72b7-4eaa-ae6e-7c417631929a)

or

![image](https://github.com/apache/cloudstack/assets/57355700/4714e554-1b99-469c-9960-ba252bf33f71)

or

![image](https://github.com/apache/cloudstack/assets/57355700/020e9d6e-354e-4699-b7fe-deb610e08e54)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API/storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19/4.20
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@weizhouapache should we close this as #8933 is merged?

**Comment by weizhouapache** [comment]
> @weizhouapache should we close this as #8933 is merged?

yes @shwstppr

**Comment by sureshanaparti** [comment]
@weizhouapache Closing this, as advised.
