### ISSUE TITLE
Failed to restore backup from veeam

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#8939]
a CloudStack user has faced an issue that failed to restore backup from veeam

The management-server.log shows
```
Failed to import VM ... with hypervisor [type: VMware] due to: [Invalid string format].
```

This issue is found when use PreSetup as primary storage.

The feature has been tested ok on NFS storage.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Fixed in #9256
