### ISSUE TITLE
error handling when creating a CKS cluster with no enabled zone

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#8962]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI, CKS, Security Groups
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### SUMMARY

When a user tries to create a CKS cluster and no zone is enabled a unclear error message is shown. see https://github.com/apache/cloudstack/pull/8489#issuecomment-2069121983

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by kiranchavala** [comment]
Closing the issue as the pr is merged
