### ISSUE TITLE
SNMP doesn't work

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#8969]
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### OS / ENVIRONMENT

Oracle Linux 8

I tryed to configure SNMP as in the docs: http://docs.cloudstack.apache.org/en/4.19.0.0/adminguide/management.html#snmp-alert-details
My config /etc/cloudstack/management/log4j-cloud.xml
![image](https://github.com/apache/cloudstack/assets/92435079/2d1dbae1-90ed-4db5-9481-e06e68fd758c)
After restrart cloudstack-management nothing happend

**Comment by rohityadavcloud** [comment]
This is really a log4j configuration issue @top-secrett could you refer to what's support by log4j ?
