### ISSUE TITLE
Cannot add a tag to an existing Compute offering

### ISSUE THREAD

**Issue by 0sorkon** [apache/cloudstack#8971]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
~~~
API
~~~
##### CLOUDSTACK VERSION

~~~
4.18.1.0
~~~

##### SUMMARY
Cannot add a storage tag to an existing Compute offering with enabled "Compute only disk offering". When I try to add it via GUI, I get an error Request failed. (502)
```Request failed with status code 502```
![image](https://github.com/apache/cloudstack/assets/3714094/bf53fa5b-cb97-493f-8ab7-df83fd7c75bc)
At the same time in the management server logs: 
```There are active volumes using the disk offering ... Please first add the new tags to the mentioned storage pools before adding them to the disk offering```
However, there is already a tag in Primary storage
![image](https://github.com/apache/cloudstack/assets/3714094/af2138d8-cf90-4372-be97-28f26f0c7ebe)
Translated with DeepL.com (free version)

##### STEPS TO REPRODUCE
* add tag to storage
* try to add atg to compute offering
##### EXPECTED RESULTS
The tag is successfully added. volumes are created according to the tag in the compute offering.
##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
> There are active volumes using the disk offering ... Please first add the new tags to the mentioned storage pools before adding them to the disk offering

Can you check if this is true, @0sorkon . Probably there is some pool with no tags or not containing this tag. The code:
```
                    if (CollectionUtils.isEmpty(tagsOnPool) || !tagsOnPool.containsAll(listOfTags)) {
...
                        throw new InvalidParameterValueException(String.format("There are active volumes using the disk offering %s, and the pool %s doesn't have the new tags. " +
                                "The following volumes are using the mentioned disk offering %s. Please first add the new tags to the mentioned storage pools before adding them" +
                                " to the disk offering.", diskOfferingInfo, poolInfo, listOfVolumesNamesAndUuid));
                    }
```
is added in 4.19 (PR #6269) and would give more info if you had it running. Maybe it helps you identify the problem..?

**Comment by 0sorkon** [comment]
If I understand this correctly, a change in this behaviour is planned in 4.19. If so, what is the best way for me to make sure that some offerings are created on one storage pool and others on another, that they do not mix with each other and that this process can be controlled?

**Comment by DaanHoogland** [comment]
No @0sorkon , it is the output in case something is wrong that is improved.

I think you need to
1. identify all volumes that use the offering
2. check where these are stored
3. check the tags on those stores

The error message is ligit as far as I can see. But so is your expectation! I can not tell what is "in the way", but I think there is some volume stored somewhere that would require the tag as well if added on the offering.

**Comment by 0sorkon** [comment]
Resolved by tagging ALL primary storage

**Comment by DaanHoogland** [comment]
> Resolved by tagging ALL primary storage

that does not seem like the ideal solution. Did you check to see if any volume using this offering was located on any of the other primary stores, @0sorkon ?
