### ISSUE TITLE
When deploying node to Kubernetes it times out

### ISSUE THREAD

**Issue by PaX101** [apache/cloudstack#8975]
When deploying a node on Kubernetes in Cloudstack 4.19.0.0 it times out when it tries to list the VM's:

`Error syncing load balancer: failed to ensure load balancer: error retrieving list of hosts: Get https://my.url.com/client/api?apiKey=myapikeyhere&command=listVirtualMachines&listall=true&response=json&signature=mysignature: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

![Kub](https://github.com/apache/cloudstack/assets/4069927/1e8cf594-da68-45cf-a4e7-22ed30cec9ff)

When i try and load the page myself if takes around 5-10 minutes to load the VM list similar to the bug in 4.18 when trying to list VM's. If i change the command to: listVirtualMachinesMetrics in my broswer it loads instantly.

**Comment by rohityadavcloud** [comment]
@PaX101 yes because you're listing the listVirtualMachinesMetrics API which by default returns VM stats (which slows down the API request). If you don't need all the details, you can pass details=min to the API response (or specific details you'd expect).

If you're not able to control this API request, one way to address this could be to change the default behaviour that's change-able via global setting.

**Comment by rohityadavcloud** [comment]
@PaX101 I've proposed a PR here which might help your case - https://github.com/apache/cloudstack/pull/8985
Can you try to disable `vm.stats.increment.metrics` global setting in your environment and see if it helps speed you listVIrtualMachines API calls?

**Comment by weizhouapache** [comment]
> @PaX101 yes because you're listing the listVirtualMachinesMetrics API which by default returns VM stats (which slows down the API request). If you don't need all the details, you can pass details=min to the API response (or specific details you'd expect).
> 
> If you're not able to control this API request, one way to address this could be to change the default behaviour that's change-able via global setting.

good idea to list virtualmachine with details parameters
I created a PR to address it in ccm: https://github.com/apache/cloudstack-kubernetes-provider/pull/60

**Comment by rohityadavcloud** [comment]
Additionally fixed in https://github.com/apache/cloudstack/pull/9177
To make the listing faster, the new global setting will need to be set to false.
