### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by fmcwebs** [apache/cloudstack#8991]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
OS Support
~~~

##### CLOUDSTACK VERSION

~~~
4.18 / 4.19
~~~

##### OS / ENVIRONMENT

Ubuntu 24.04

##### SUMMARY

It will be great to add support for Ubuntu 24.04 to the hosts.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
+1

Do we consider it in 4.19.1?

@sureshanaparti @rohityadavcloud @DaanHoogland

**Comment by DaanHoogland** [comment]
Any idea about the work involved @weizhouapache ?

**Comment by weizhouapache** [comment]
> Any idea about the work involved @weizhouapache ?

the support for ubuntu 24.04 as guest OS is quite simple, just 1-2 line of code changes

the support for ubuntu 24.04 as mgmt and kvm host should be very similar as what we have done for ubuntu 22.04, etc
- build templates
- update trillian
- update jenkins
- fix smoke test failures ,etc

**Comment by rohityadavcloud** [comment]
I've tested the support with ACS 4.19 and it works for me out of the box, Ubuntu 24.04 as KVM host, mgmt server, usage server, NFS server and MySQL server host. It's just a matter of validating that.

**Comment by weizhouapache** [comment]
> I've tested the support with ACS 4.19 and it works for me out of the box, Ubuntu 24.04 as KVM host, mgmt server, usage server, NFS server and MySQL server host. It's just a matter of validating that.

great news, thanks @rohityadavcloud

**Comment by andrijapanicsb** [comment]
Sounds great, we need the newer Ubuntu for those virt-v2v stuff and in general.
