### ISSUE TITLE
System VM / Agent on KVM host does not support NFSv3 on Secondary Storage

### ISSUE THREAD

**Issue by Jayd603** [apache/cloudstack#8996]
On the host system (Ubuntu 22.04.4, latest libvirt, cloudstack etc.), NFS connects fine and can write.

Agent log shows this:
2024-04-26 16:43:33,585 ERROR [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-3:null) (logid:2032a2aa) org.libvirt.LibvirtException: internal error: Child process (/usr/bin/mount -o nodev,nosuid,noexec 192.168.22.50:/mnt/SSDStorage1/Cloudstack/template/tmpl/1/3 /mnt/a3313f14-20d0-3952-a7e1-571f5aa1654a) unexpected exit status 32: mount.nfs: Protocol not supported

I set secstorage.nfs.version in the cloudstack UI and restarted the agent with no effect

Update: according to #4482 - I can use nfs://my-nfs-server/exports/ps01?nfsvers=3 if I edit the database, just trying to find where in the db secondary storage is set up to try it

Changing the nfsver in the url did not seem to solve anything.

Update: I notice that it is attempting to mount a path that does not exist on the storage server, when I try to mount that path I get the protocol not supported error, I"m going to manually create the directories as it requests them and see what happens

Update 2: OK, now it's making a little more sense, it's connecting with NFS it seems, there is NO template there, this is probably because of the install error from not initially being able to connect to secondary storage on creation of the zone and the installer allowing me to continue despite no usable secondary storage, this may end up being related to my other bug report in which case i will close this one

**Comment by weizhouapache** [comment]
Update /etc/nfsmount.conf to set the NFS version to 4.0 and retry

**Comment by Jayd603** [comment]
> Update /etc/nfsmount.conf to set the NFS version to 4.0 and retry

Thanks but the server I am using actually only supports nfsv3 due to legacy clients making use of it.

**Comment by weizhouapache** [comment]
> > Update /etc/nfsmount.conf to set the NFS version to 4.0 and retry
> 
> Thanks but the storage server I am using actually only supports nfsv3 due to legacy clients making use of it. I can use iscsi or another nfs server BUT i'd like to use nfsv3 on this one server preferably.
> 
> Also do you mean on the host system? because that file doesn't exist in ubuntu and the KVM host system can mount fine when I mount from command line using the same mount command in the logs.

@Jayd603 
I noticed you have some update, what's the current status ?

**Comment by Jayd603** [comment]
This bug is probably related to the first bug I submitted, ie, the zone set up let me configure secondary storage that it could not actually make use of and no errors were shown.  Since then I fixed secondary storage, manaully deleted the old storage and am still debugging other issues.  

> > > Update /etc/nfsmount.conf to set the NFS version to 4.0 and retry
> > 
> > 
> > Thanks but the storage server I am using actually only supports nfsv3 due to legacy clients making use of it. I can use iscsi or another nfs server BUT i'd like to use nfsv3 on this one server preferably.
> > Also do you mean on the host system? because that file doesn't exist in ubuntu and the KVM host system can mount fine when I mount from command line using the same mount command in the logs.
> 
> @Jayd603 I noticed you have some update, what's the current status ?
