### ISSUE TITLE
(VirtualRouter) Provider is not ready, cannot Enable the provider, please configure the provider first

### ISSUE THREAD

**Issue by Luskan777** [apache/cloudstack#8997]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VirtualRouter
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### OS / ENVIRONMENT : Ubuntu 22.04.4 LTS (Management Server) and CentOS 7 (Agent)
Network: advanced networking
Physical Network: 
  - cloudbr0: management and storage traffic
  - cloudbr1: Public and Guest Traffic

##### STEPS TO REPRODUCE

~~~
When you try to activate the VirtualRouter provider in  Zone -> Physical Network -> Network Service Provider
~~~

##### EXPECTED RESULTS

~~~
Successfully activate the VirtualRouter provider
~~~

##### ACTUAL RESULTS

~~~
(VirtualRouter) Provider is not ready, cannot Enable the provider, please configure the provider first
~~~

![image](https://github.com/apache/cloudstack/assets/71342479/c147a4c8-ee8b-4f65-b21f-9b465c4609e4)

**Comment by kiranchavala** [comment]
@Luskan777 

Could you please try the following API calls.

Please provide the management server logs if any of the API calls fails


# List network service providers for the given physical network

$ list networkserviceproviders physicalnetworkid=<physical_network_id>

# For a specific Network Service Provider list the virtual router element - to get the id

$ list virtualrouterelements nspid=<nsp_uuid_from_above>

# enable the virtual router element

$ configure virtualrouterelement id=<element_uuid_from_above> enabled=true

or 

$ update networkserviceprovider id=<uuid_of_nsp> state=Enabled

**Comment by Luskan777** [comment]
HI @kiranchavala , thank you very much for your answer

  As it was an environment that was not yet in production, I reinstalled the management server, after reinstalling it I was able to activate the Vritual Router provider as expected
