### ISSUE TITLE
VMs not loading kvm and kvm-intel module at boot once if useing custom cpu

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#9005]
##### ISSUE TYPE

VMs not loading kvm and kvm-intel module at boot once we use custom cpu as below - 
guest.cpu.model=SandyBridge
guest.cpu.mode=custom

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
we are using below config in agent.properties - 
guest.cpu.model=SandyBridge
guest.cpu.mode=custom

we need kvm module to be loaded on vm so that we can use below properties in our automation :- 

"ansible_virtualization_type": "kvm", 

If we use guest.cpu.mode=host-model it come by default. 

##### EXPECTED RESULTS
kvm module should be present after vm reboot and must be install as part of VM creation. 

~~~

~~~

**Comment by weizhouapache** [comment]
@yashi4engg 
you need to add the following to agent.properties
```
guest.cpu.features=vmx
```

**Comment by rohityadavcloud** [comment]
Resolved as closed, question has been answered. Pl re-open if you're still stuck or log a new issue. Thanks.
