### ISSUE TITLE
When i am trying to add OVS combinations with providers it's saying this(Provider Ovs doesn't support services combination: [PortForwarding, StaticNat])

### ISSUE THREAD

**Issue by everdata-root** [apache/cloudstack#9009]
Provider Ovs doesn't support services combination: [PortForwarding, StaticNat]

Can we resolve this ?
it would be great if i get support regarding this

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
@everdata-root 
do you use a new network offering ?

create a new network offerintg with `Connectivity` capability and retry ?

**Comment by everdata-root** [comment]
I do, creating a new one with connectivity(required done)
Can this be resolved on any other basis, or it might have something else or dependency.
I found somewhere on google that you can update services provider to resolve this, can this be done or it may cause of this

**Comment by weizhouapache** [comment]
> I do, creating a new one with connectivity(required done) 

still fail with the new network offering ? @everdata-root

**Comment by DaanHoogland** [comment]
@everdata-root can you provide us with more data to work on?

- what offering do you have configured? (please give us the full definition)
- what kind of topology do you have? (hosts including os versions and by extention hypervisortype)
- what action are you performing when this error occurs?
- is this environment new or does it already contain resources?
- etc..

**Comment by everdata-root** [comment]
>Adding Network offering with the isolate guest type, supported services(static nat, portforwarding),conserve zone and public method
>Topology using - isolated network
>I am just googling and finding if it has another method to be done and there is something which can fulfil this requirement 
this is absolutely a new environment.

**Comment by DaanHoogland** [comment]
so,
what action are you performing when this error occurs?
(like deploying a VM / creating a network / configuring - or adding a host?

**Comment by DaanHoogland** [comment]
closing this, please reopen if you have more information (or create a new ticket)
