### ISSUE TITLE
add `encryptionformat` to volume reponse for admins

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9014]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API/UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

On requests like listVolumes or updateVolume the output should include encryption format (at least for admins)
see the discussion in https://github.com/apache/cloudstack/pull/8643#issuecomment-2085073967
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
> to be consistent with volume table, maybe better to use `encryptformat` ?

thanks, updated

**Comment by kiranchavala** [comment]
Closing the issue as the pr is merged
