### ISSUE TITLE
admin should be allowed to elevate user from role `User` to `Domain Admin`

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9015]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI / API
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

as noticed in https://github.com/apache/cloudstack/pull/9012#issuecomment-2085425939

When an admin want to grant domain admin rights to a user with role user:
![image](https://github.com/apache/cloudstack/assets/2486961/81a873f8-e8e3-48eb-882e-bbe22d089a24)
This is true in ROOT, where it maybe should fail but with a better message. In a subdomain this would be a perfectly acceptable action.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
@DaanHoogland question: why can't we allow escalating a normal user to domain admin in ROOT domain?

**Comment by DaanHoogland** [comment]
> @DaanHoogland question: why can't we allow escalating a normal user to domain admin in ROOT domain?

We can, but you can argue that a domain admin in ROOT doesn't mean to much. I am mixing talking about a technical defect and desired/expected functionality a bit, sorry.

Keeping to the subject at hand; root admin should be able to elevate anybodies rights/role.

BTW, I will do extra tests on this to see whether this works on other levels.

**Comment by shwstppr** [comment]
I drafted PR https://github.com/apache/cloudstack/pull/9173 with an attempt to simplify the checks for a role change. It allows ROOT admin to change role in all conditions except one. Will check if it can cause any regressions or unexpected behaviour

**Comment by DaanHoogland** [comment]
fixed in #9173
