### ISSUE TITLE
Search Bar at Autoscale Instance Group Page is not working

### ISSUE THREAD

**Issue by btzq** [apache/cloudstack#9042]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Autoscale Group
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

1. Open Autoscale Instance Group Page (View list of ASG Groups)
2. Use search bar on the top right corner

Result is that the page refreshes, but the ASG groups are not filtered accordingly based on the search criteria.

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
Result is that the page refreshes, but the ASG groups are not filtered accordingly based on the search criteria.
~~~

##### ACTUAL RESULTS

~~~
Search bar should work accordingly
~~~

**Comment by shwstppr** [comment]
Fixed with #9046
