### ISSUE TITLE
Empty resources in dashboard

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#9045]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

One our customer account (can't really say if it happened after the upgrade but I don't believe so) is unable to see his resources assigned in the dashboard in the UI.
As you can see from the screenshot the account has assigned resources, as VMs, volumes and so on.
From all other pages we can see no issues and he's able to manage every resource assigned to him.
Actually, this is the only account with this issue on our infrastructure.

##### STEPS TO REPRODUCE

~~~
Don't know how to reproduce this.
~~~

##### EXPECTED RESULTS

~~~
The user show be able to see the resource assigned to him in the dashboard
~~~

##### ACTUAL RESULTS

~~~
Empty dashboard for this user
~~~

**Comment by cdfgallo** [comment]
![3_user](https://github.com/apache/cloudstack/assets/110984295/c73ea66e-7a04-4af5-b4ae-7b7d180a489d)
![4_account_resources](https://github.com/apache/cloudstack/assets/110984295/07b24f8d-3c49-4dd1-b5c8-aa75355842bc)
![1_resources_home](https://github.com/apache/cloudstack/assets/110984295/a1ca21d2-a976-4e7f-8586-1c52c18b77e7)
![2_instances](https://github.com/apache/cloudstack/assets/110984295/cf311a89-5a4c-44a7-9520-ecac34c70148)

**Comment by DaanHoogland** [comment]
@cdfgallo
- Did you see and exceptions in the logs?
- Do you remember when the user could last see their resources?

as the user still has limits it seems the links are there so it should be possible to repair.

**Comment by rohityadavcloud** [comment]
@cdfgallo can you open this account in a browser with dev tools, share with us if you see any errors on the devtools/JS console?

**Comment by cdfgallo** [comment]
Hi @DaanHoogland not in the management logs when the user login. Unfortunately no.

@rohityadavcloud we just completed this test with our client and I'm posting the errors received.

**Comment by cdfgallo** [comment]
![error-devt2](https://github.com/apache/cloudstack/assets/110984295/97b665de-38fa-4245-9107-f9d6c31d8529)
![error-devt](https://github.com/apache/cloudstack/assets/110984295/fe86162f-2cd7-4e18-9d9b-180ab066dcdc)

**Comment by cdfgallo** [comment]
![image](https://github.com/apache/cloudstack/assets/110984295/9c2bd795-bbf0-4420-b70d-6b3c38623c01)
![image](https://github.com/apache/cloudstack/assets/110984295/cc3519cc-fed6-4576-b123-04b584c9518f)

**Comment by shwstppr** [comment]
@cdfgallo can you please share the full resolution image or share the error? Not sure but for me above-shared images are showing in 512x239px and are not readable

**Comment by shwstppr** [comment]
@cdfgallo I assume you've already tried a different browser or used an incognito window. Please try if not already. I was able to partially reproduce the behaviour by corrupting cached project value

**Comment by cdfgallo** [comment]
@shwstppr yes I confirm that we already tried different browsers and using incognito mode. Unfortunately the issue persists.

**Comment by cdfgallo** [comment]
@rohityadavcloud @shwstppr 
I've been able to reproduce the issue just accessing our infrastructure with an account with domain administrator privilege using external saml2 authentication. 
I saw the same errors posted up here in devtools and no error logs in the management server.
Looking at the database I can't see nothing strange on the account.
Thank you,
Fabio

**Comment by shwstppr** [comment]
Thanks @cdfgallo. I guess then this is the same issue as https://github.com/apache/cloudstack/issues/8950
cc @rohityadavcloud 
I'll try to spend some time next week to look into a possible fix. However, I'm not sure right now about setting up SAML authentication for a DomainAdmin role.

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9097
Tested on https://qa.cloudstack.cloud/simulator/ using SAML using `rick`

@cdfgallo please test latest 4.19 branch and re-open if you still reproduce this error
