### ISSUE TITLE
Msty.app Cloudstack does not see LmStudio models due to path issue

### ISSUE THREAD

**Issue by papyr** [apache/cloudstack#9075]
##### ISSUE TYPE

 * Improvement Request

##### Msty.app
Since each downloaded ollama model in the LM studio download sits in its own subfolder (has its its own per model path), and Msty only have one setting for all models is unable to find the LM studio/Ollma downloaded models.

 **Can you please all us to configure the path per model, and add discovery of models from the LM studio/Ollama paths** `C:\Users\usename\.cache\lm-studio\models` + _Sub_ `modelSubfolder`

Or option two is to use LLM bridge here on github

**Comment by rohityadavcloud** [comment]
Shouldn't this issue be logged somewhere else @papyr ? This doesn’t appear anywhere related to Apache CloudStack.

**Comment by rohityadavcloud** [comment]
Closing this, @papyr as we've not heard from you and this clearly doesn't seem like any CloudStack related issue.
