### ISSUE TITLE
ConfigDrive In L2 Networking Does not offer password In Reinstalling VM

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#9095]
ISSUE TYPE
Bug Report
Improvement Request

COMPONENT NAME
API

CLOUDSTACK VERSION
4.17.2.0

CONFIGURATION
advanced networking

OS / ENVIRONMENT
U20.4 LTS

SUMMARY
I Create Network Offering For L2 Network With "UserData Enable Option". 
I Used ConfigDrive Option In Cloud-init But In New Creation Of VM instance Cloudstack In Mount Drive Presented to me password File But after reinstalling, I don't have that file anymore.

STEPS TO REPRODUC

EXPECTED RESULTS
i want to  use password file that cloudstack Mount for me. in Reinstalling VM
![image](https://github.com/apache/cloudstack/assets/104001728/7e5b4a6b-dd6c-4367-b2d8-b9cbd04c6d0b)

ACTUAL RESULTS
i dont see password file 
![image](https://github.com/apache/cloudstack/assets/104001728/0b184704-f65e-472d-bf25-9bcc84489a55)

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9113
