### ISSUE TITLE
VPC link present under Create Menu when account has no permission

### ISSUE THREAD

**Issue by scottsignal** [apache/cloudstack#9099]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 22.04
Single-node Management Server
MySQL 5.7

##### SUMMARY

When setting all permissions for VPC networks to deny, the link to create a VPC is still present under create menu.   I have attached a screenshot.
![image](https://github.com/apache/cloudstack/assets/113709190/e3a15868-d352-4f6f-a674-24b9e169cb53)
##### STEPS TO REPRODUCE

Set all permissions on role for VPC to deny.  This was tested on both Domain Admins and User roles types.  The link to create a VPC is still present under create menu and if you click on the link it brings up a 404-error page since user has no permissions to VPC networks.  The link on the left nav does disappear as expected.

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
VPC link not be present in the create dropdown when user has no permission to do anything with VPC networks.
~~~

##### ACTUAL RESULTS

~~~
VPC link is present in the create dropdown when user has no permission to do anything with VPC networks.
~~~

**Comment by shwstppr** [comment]
Fixed with #9104
