### ISSUE TITLE
test_events_resource fails in unrelated changes

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9122]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
integration tests
~~~

##### CLOUDSTACK VERSION

~~~
main
~~~

##### SUMMARY

i.e.
https://github.com/apache/cloudstack/pull/9088#issuecomment-2126901516

and many more

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by weizhouapache** [comment]
oh, I thought it has been fixed by #9032

**Comment by shwstppr** [comment]
@DaanHoogland needs to repackage

**Comment by shwstppr** [comment]
@DaanHoogland not seeing this in the latest health check PRs test runs. Though there are some other test failures but not sure if they are intermittent or not.

**Comment by DaanHoogland** [comment]
ok, maybe we can close, I noticed several in a day (after I merged #9032) will reopen if applicable.
