### ISSUE TITLE
Add limit configuration for number of projects per domain/account and add UI function for configuring limits

### ISSUE THREAD

**Issue by MejdiB** [apache/cloudstack#9127]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
UI, API
~~~

##### CLOUDSTACK VERSION
~~~
4.18.x and newer
~~~

##### SUMMARY
Currently, admins can set various global configuration options for resource limits such as "max.account.cpus", "max.account.memory", "max.domain.cpus", "max.domain.memory" etc. However, there is no option for limiting total number of projects for a domain or account like "max.account.projects" and "max.domain.projects". Furthermore, an input field on the UI for the Configure Limits view for a particular domain or account is missing. As a workaround it can be configured using Cloudmonkey: 

```
(localcloud) 🐱 > update resourcelimit
domainid=37ff2485-cc1e-11ee-a4eb-1e00db000197 account=ACSUser
resourcetype=5 max=3
{
  "resourcelimit": {
    "account": "ACSUser",
    "domain": "ROOT",
    "domainid": "37ff2485-cc1e-11ee-a4eb-1e00db000197",
    "max": 3,
    "resourcetype": "5",
    "resourcetypename": "project"
  }
}
```

**Comment by my-code-AL** [comment]
I'll look into this

**Comment by charlesweng** [comment]
What would be the recommended default maximum you would be looking for?

**Comment by my-code-AL** [comment]
@MejdiB . I'm also curious why you selected "5" for the project resource type. I don't see this as a listed option for the API constants.

**Comment by MejdiB** [comment]
@my-code-AL This is just an example for a workaround using Cloudmonkey, as this is not available on the UI on the Configure Limits view. "max.account.projects" and "max.domain.projects" are not yet implemented as constants in Cloudstack. At least I don't see them in the global configuration options.

**Comment by MejdiB** [comment]
@charlesweng I am not looking for any specific default value. Instead, why not setting this as configuration options just like "max.account.cpu" or "max.account.memory"?

**Comment by DaanHoogland** [comment]
@MejdiB , projects can be per domain but not per account as these are a type of shared account. cc @my-code-AL

**Comment by DaanHoogland** [comment]
thanks @MejdiB @my-code-AL , I still want to have the functional discussion if projects should be limited per account or domain, but I like your functionality none-the-less.

**Comment by MejdiB** [comment]
@DaanHoogland @my-code-AL It happens that users have created multiple projects to evade the default resource limits for accounts or projects, e.g. Project x part 1, project x part 2 etc. since there is no project limit per default. For this reason, I had to set the project limit for accounts using Cloudmonkey (as described in my example). This was the original motivation behind this issue.
