### ISSUE TITLE
ui for listVolumes by isEncrypted

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9130]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

see https://github.com/apache/cloudstack/pull/8643#issuecomment-2129386421

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment]
backend change is still pending
