### ISSUE TITLE
Make schema migrations are idempotent

### ISSUE THREAD

**Issue by vishesh92** [apache/cloudstack#9170]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Schema migrations

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Ensure that migrations are idempotent. Sometimes, there are some schema changes which are already applied in the database. This causes issues during upgrade. Especially if someone is maintaining a private fork.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@vishesh92 , do you mean "updates" (or schema changes) instead of "migrations"?

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9171 @shwstppr @vishesh92 in case some changes are needed, pl review and re-open to advise them, thank for the issue and the PR.
