### ISSUE TITLE
Users have the permission to create featured templates

### ISSUE THREAD

**Issue by TadiosAbebe** [apache/cloudstack#9241]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Template
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

A new cloudstack deployment with advanced networking, kvm for compute, nfs for secondary storage, ceph for primary storage

##### OS / ENVIRONMENT

ubuntu server 22.04 for all servers, kvm, management and storage

##### SUMMARY

On the cloudstack documentation, it specifies that `Only an administrator can make a Template Featured.`, that holds true for the most part, in a way that for users with User and Domain admin role the featured checkbox when registering a template or ISO isn't visible. But when users with the above roles try to create a template from an existing volume they are given the permission to make the template a featured one.

##### STEPS TO REPRODUCE

~~~
1. Create an instance with a root disk
2. Stop the instance and navigate to it's volume
3. Click on create template from volume button
4. Here whether you are a root admin, domain admin, or user you will see the featured option and you are able to set the template as featured
~~~

##### EXPECTED RESULTS

~~~
for users with the User role the featured option should not be visible and the user shouldn't have the permission to set a template featured
~~~

##### ACTUAL RESULTS

~~~
users with the User role can set the featured option, and it will allow them to create a featured template that is 
~~~

**Comment by DaanHoogland** [comment]
fixed in #9253
