### ISSUE TITLE
Search filter does not work for domain/account

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#9274]
see screenshot

Issue 1: the list of account is not updated when domain is changed. All accounts are listed
![image](https://github.com/apache/cloudstack/assets/57355700/877af312-5de7-4bcf-a08b-5433ae51dfa4)

Issue 2: got an exception when search by account
![image](https://github.com/apache/cloudstack/assets/57355700/ac01a10a-7bf5-4fef-8333-429dd7f8a95d)

the account name should be passed instead of account uuid

looks like related to #9068

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19/main
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
Fixed in #9345
