### ISSUE TITLE
UI: Issues related to Externally managed kuberntes cluster

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9291]
ISSUE TYPE

Bug
Enhancement
Improvement request

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.19.0

SUMMARY

Populate information related to externally managed kubernetes cluster

This is related to the feature in capc

https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/pull/350

Steps to reproduce  the issue 

1. Launch a CAPC enabled kubernetes cluster by following the steps 

https://cluster-api-cloudstack.sigs.k8s.io/development/building.html

2. Navigate to compute> kubernetes > select the eternally 
 
![capc](https://github.com/apache/cloudstack/assets/1401014/314a3482-372f-4c32-88f4-ce365f7ee6f0)

3. The information related to firewall, portforwarding, Loadbalancing are not displayed for a external managed k8s cluster 

![network-info-extern-capc](https://github.com/apache/cloudstack/assets/1401014/f685c522-9a70-4204-91a2-6e9302f1e2e7)

Actual Behaviour 

The size (worker node count)   of the k8s cluster is displayed incorrectly 

There is no CPU and Memory information available 

The kubernetes version is not available 

The firewall, portforwarding, Loadbalancing rules is not shown

Expected behaviour 

The size (worker node count)  of the k8s cluster should be  displayed  

The CPU and Memory should be displayed

The kubernetes version should be displayed

The firewall, portforwarding, Loadbalancing rules is not shown

**Comment by weizhouapache** [comment]
IMHO, since the cks cluster is externally managed, if we set these values, it will take extra effort to get the values synced

**Comment by DaanHoogland** [comment]
@weizhouapache , I read you comment as, "we should not try to show them". That would mean this issue is about removing the fields from the UI, agree?

**Comment by weizhouapache** [comment]
> The size (worker node count) of the k8s cluster should be displayed
> 
> The CPU and Memory should be displayed
> 
> The kubernetes version should be displayed
> 
> The firewall, portforwarding, Loadbalancing rules is not shown

@DaanHoogland yes, but some columns might be difficult to hide in the list view, as there might be mixed CKS type (ExternalManaged/CloudManaged) in an environment.

> The size (worker node count) of the k8s cluster should be displayed

yes, they should be displayed correctly

> The CPU and Memory should be displayed

for ExternalManaged cluster, `N/A` is fine with me

> The kubernetes version should be displayed

for ExternalManaged cluster, `N/A` is fine with me

> The firewall, portforwarding, Loadbalancing rules is not shown

for ExternalManaged cluster, the rules could be displayed, but not updatable

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9434
