### ISSUE TITLE
UI: Remove the delete action item for cks nodes

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9293]
ISSUE TYPE

Improvement issue

COMPONENT NAME

Component: UI

CLOUDSTACK VERSION

Cloudstack version 4.19.0

SUMMARY

Remove the delete action item for  kubernetes nodes inside a cks cluster

Steps to reproduce  the issue 

1. Create cks cluster and navigate inside the cks cluster

![Remove the delete action item](https://github.com/apache/cloudstack/assets/1401014/d844047f-f485-4e5f-b500-bf0a88b91166)

Currently, we are throwing a exception whenever a user tries to delete the kubernetes node based on this

https://github.com/apache/cloudstack/pull/9057

In my opinion its better not to show the delete icon , when the operation is expected to fail, 

End user should be only allowed to delete the cks cluster from the UI 

Expected behaviour 

Remove the delete action item for the cks nodes

**Comment by Pearl1594** [comment]
@kiranchavala I believe the PR #9057 prevents deletion of the CKS nodes using the destroyVirtualMachine API from the instances tab. These delete icons basically translate to `scaleKubernetesCluster` which effectively scales down a specific node in the CKS cluster

**Comment by DaanHoogland** [comment]
@Pearl1594 , you are saying it is solved in #9057 ?

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9434
