### ISSUE TITLE
Storage pools are not mounted when the host is in maintenance mode  or comes out of maintenance mode 

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9295]
ISSUE TYPE

Bug

COMPONENT NAME

Component: storage,kvm

CLOUDSTACK VERSION

Cloudstack version 4.19.0, 4.18 
KVM

SUMMARY

Storage pools are not mounted when the host is in maintenance mode or comes out of maintenance mode 

Steps to reproduce  the issue 

Test case scenario 1

1. Have Cluster C1 with host H1 and cluster C2 with host H2
2. Have only one cluster wide storage pool P1 attached to C1
3. Put H2 on maintenance
4. Add a zone wide storage pool P2.
5. Take H2 out of maintenance
6. Deploy a VM in H2. it will fail as P2 is not mounted on H2.

Test case scenario 2

1. Add zone wide pool P2 when both hosts are not in maintenance.
2. Disable Pool P2.
3. Reboot H2
4. P2 won't be mounted on H2 as it is disabled.
5. VM deployment on H2 fails as it is not able to find any pool
 

**Actual Behaviour** 

Cloudstack is not mounting the storage pool when the host is maintenance mode or comes out of maintenance mode

**Expected behaviour** 

Cloudstack should mounting the storage pool when the host is maintenance mode or comes out of maintenance mode

**Comment by abh1sar** [comment]
Just found out there is a setting for adding disabled storage pools during reboot which will avoid TestCase2: mount.disabled.storage.pool

**Comment by sureshanaparti** [comment]
Fixed in #9301
