### ISSUE TITLE
VM stuck in Expunging state after VM Destroy 

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#9297]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When a VM is destroyed in UI, the vm_instance table still shows state = Expunging

##### STEPS TO REPRODUCE

~~~
Go to UI, Destroy a VM (my example had 1 root disk only).  Select to Expunge immediately. Root disk is deleted, and volume is set as Expunged. However the vm_instance table state stays as Expunging. 

NOTE - I had originally installed CS version 4.14, which upgraded to 4.16 and then 4.17 and now 4.19. I see VMs going back historically few years which still show as expunging. 

~~~

##### EXPECTED RESULTS

~~~
vm_instance state should change to Destroyed or Expunged ( can someone explain whats the difference?)
~~~

##### ACTUAL RESULTS

~~~
vm_instance state shows as Expunging
~~~

**Comment by sureshanaparti** [comment]
VM state would be Expunging after it is removed, which is expected.

**Comment by nxsbi** [comment]
It sure is confusing to call it "Expunging" which indicates something is still in progress versus "Expunged" indicating the process is complete. Hopefully this can be updated in future version? 

Additional confusion is caused because for virtual routers it calls it "Destroyed" when you delete it (or when you reboot router and ask to cleanup).
