### ISSUE TITLE
Backups tab appearing twice in the UI

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9311]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

Have the backup framework enabled i.e backup.framework.enabled=true

##### SUMMARY

On listing the storage pane on the left the backup tab is listed twice. 

![Screenshot 2024-06-28 at 2 46 59 PM](https://github.com/apache/cloudstack/assets/5229147/fc70604a-eb43-4765-b12f-e932a3c1b225)

**Comment by rohityadavcloud** [comment]
Fixed in 4.19 branch; checked against latest https://qa.cloudstack.cloud/simulator/#/backup cc @sureshanaparti

**Comment by DaanHoogland** [comment]
@rajujith can you check and close?

**Comment by rajujith** [comment]
It is fixed @rohityadavcloud @DaanHoogland .
