### ISSUE TITLE
unable to delete k8s cluster when we add k8s cluster network with a instance and removed it

### ISSUE THREAD

**Issue by Noelantogerorge** [apache/cloudstack#9331]
##### ISSUE TYPE
<!Pick one below and delete the rest.
 * Bug Report

##### COMPONENT NAME

UI

##### CLOUDSTACK VERSION

4.19.0

##### CONFIGURATION

Advanced Networking

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY
<!-- Explain the problem/feature briefly.

I had set up a Kubernetes cluster and connected its network interface to a virtual machine instance. My service was operating on an instance, and I needed to connect to a pod that was running on a Kubernetes cluster directly. I deleted the nic from VM instance after checking connectivity, however when I tried to delete the Kubernetes cluster, I received the following error.

 Network: The Kubernetes cluster's ncs-test network is used by instances of ncs-test that are not a member of the Kubernetes cluster.
 
My virtual machine (VM) is visible in the instance list on the virtual router page, but that nic is not displayed on the VM nic page.
 I've included screenshots of the identical

![image](https://github.com/apache/cloudstack/assets/126588356/b9526c3b-63c2-4046-b8e5-f13b6749f77d)
![image](https://github.com/apache/cloudstack/assets/126588356/3f4d57c8-fbf3-4d2e-9ed2-a8e0c987d153)

Is there a way to remove it?

**Comment by shwstppr** [comment]
@Noelantogerorge can you please share the error you're facing and steps to reproduce.
From what I understand from title,
 - Create a k8s cluster
 - Added a VM to its network
 - Destroyed the VM
 - Tried deleting the cluster.
 
 The VM that is added and deleted should be expunged and not in Destroyed state for ACS to delete the k8s cluster.

**Comment by Noelantogerorge** [comment]
@shwstppr 

Thank you...

Steps to reproduce

- Create a k8s cluster
- Create a VM instance on Add instance page show network as k8s network
- Once VM is up, add another nic as primary and remove this network nic (k8s network)
- Try deleteing k8s cluster

We got below error
Network: The Kubernetes cluster's ncs-test network is used by instances of ncs-test that are not a member of the Kubernetes cluster.

**Comment by shwstppr** [comment]
Thanks @Noelantogerorge for sharing the steps. I was able to reproduce the issue. I've created a fix for it.
The only workaround I was able to find was to delete that additional VM instance (you may take a snapshot and deploy a new VM using it)

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9339
