### ISSUE TITLE
Listing backups fails when an instance is expunged without deleting its backups

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9341]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API,UI 
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### CONFIGURATION

Dell Networker as B&R provider
##### OS / ENVIRONMENT

ACS with Dell Networker as B&R provider for KVM 
##### SUMMARY

Listing backups fails in UI and API when you delete an instance with backups then listing backups for all backups fails. 

##### STEPS TO REPRODUCE

~~~
1. Create backups in two instances i1 and i2 for example.
2. Expunge the instance i1 
3. List the backups.
~~~

##### EXPECTED RESULTS

~~~
Listing backups shouldn't break when an instance having a backup is expunged. 
Backups for an instance should be listed even after an instance is expunged so that it can be recovered. 
~~~

##### ACTUAL RESULTS

~~~
Listing backups breaks on expunging an instance with backup. 
~~~

![Screenshot 2024-07-05 at 2 33 33 PM](https://github.com/apache/cloudstack/assets/5229147/4dc5da75-f2e6-491c-8d8e-d62bfddbce3b)

![Screenshot 2024-07-05 at 2 48 47 PM](https://github.com/apache/cloudstack/assets/5229147/518bf244-ff08-4a64-9cfe-d6a64e06c80c)

A workaround is to delete the backup records of the expunged instance, but its not a ideal one.

**Comment by vishesh92** [comment]
Fixed in https://github.com/apache/cloudstack/pull/9392
