### ISSUE TITLE
Created date not displayed in UI for backups

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9343]
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### OS / ENVIRONMENT

ACS with B&R provider enabled

##### SUMMARY

On listing the backups of instance the created date is not displayed in the UI. 

##### STEPS TO REPRODUCE

~~~
1. Create a backup of an instance.
2. List the backups of the instance 
~~~

<img width="827" alt="Screenshot 2024-07-05 at 3 06 38 PM" src="https://github.com/apache/cloudstack/assets/5229147/a1405b4e-24d9-49a0-9dce-6e2cf9b19a4b">

**Comment by sureshanaparti** [comment]
@hsato03 @rajujith Fix merged to 4.19 as well, will be available in 4.19.1.
