### ISSUE TITLE
Copy console UI button does not work

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#9368]
The copy console (copy icon) button in the resource view card on left side of a VM does not work.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19/4.19.1 RC1
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by vladimirpetrov** [comment]
I'm not able to reproduce this on 3 different upgraded environments @rohityadavcloud

**Comment by DaanHoogland** [comment]
> I'm not able to reproduce this on 3 different upgraded environments @rohityadavcloud

I tried just one, but no issue

**Comment by harikrishna-patnala** [comment]
I've tried too, its not working **Safari** browser, others are working fine

**Comment by rohityadavcloud** [comment]
Addressed also in https://github.com/apache/cloudstack/pull/9381
