### ISSUE TITLE
CloudStack tab/app title not loaded in the browser

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#9375]
The CloudStack UI loaded in a browser tab shows undefined app title with 4.19.1 RC1: Tested with Safari & Chrome

<img width="284" alt="Screenshot 2024-07-12 at 11 34 32 AM" src="https://github.com/user-attachments/assets/a70a6365-4931-49b0-ae68-5ecc873ef532">

<img width="407" alt="Screenshot 2024-07-12 at 11 34 36 AM" src="https://github.com/user-attachments/assets/65ab7a21-5ffe-457a-afd3-3a73b8c18ec8">

However, after login the title gets fixed.

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1 RC1
~~~

**Comment by DaanHoogland** [comment]
@rohityadavcloud : 
![image](https://github.com/user-attachments/assets/ab06deb9-414a-4483-befb-baa55be901a6)
I think some environmental issue must be at play

**Comment by rohityadavcloud** [comment]
Closing this https://github.com/apache/cloudstack/pull/7418/files @DaanHoogland 
yes in my env the `loginPageTitle` wasn't define - as it was an upgraded env (not a freshly installed). Thanks for checking.
