### ISSUE TITLE
remove offering button should not be shown if the action is not  allowed

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9393]
##### ISSUE TYPE

 * Improvement Request
 
##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### SUMMARY

as described in https://github.com/apache/cloudstack/pull/9391#issuecomment-2228126972  remove backup offering should only be shown if remove backup offering is allowed.  (i.e. not for dummy offering or any other that might disallow it.)

see also 
![image](https://github.com/user-attachments/assets/3c426193-6da1-4594-9d9e-d29bada2713b)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by abh1sar** [comment]
@DaanHoogland in the given example in https://github.com/apache/cloudstack/pull/9391#issuecomment-2228126972, the backup offering could be deleted using the 'force' option.
So, I think the remove offering button should still be shown. The error only gives the warning that using the 'force' option will delete all the backups.
Please let me know your thoughts

**Comment by DaanHoogland** [comment]
> @DaanHoogland in the given example in [#9391 (comment)](https://github.com/apache/cloudstack/pull/9391#issuecomment-2228126972), the backup offering could be deleted using the 'force' option. So, I think the remove offering button should still be shown. The error only gives the warning that using the 'force' option will delete all the backups. Please let me know your thoughts

So you are saying we should not implement this at all, right @abh1sar ? If the functionality is consistant, I am fine with keeping it, but it seemed odd to me at the time (close at will)
