### ISSUE TITLE
Cannot edit shared guest network domain

### ISSUE THREAD

**Issue by Hector-Work** [apache/cloudstack#9405]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### CONFIGURATION

Shared guest network with advanced networking

##### SUMMARY

According to the [documentation](https://docs.cloudstack.apache.org/en/latest/adminguide/networking_and_traffic.html#editing-restarting-and-removing-a-guest-network), it is possible to edit the network domain of a guest network after is has been created. However, when editing the network on my instance, there is no network domain field.

I also tried editing an isolated network on the same instance and that does have a network domain field when editing.

##### STEPS TO REPRODUCE

~~~
Create shared guest network with a network domain.
Edit the network.
~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@Hector-Work , It is not supported to change the networkdomain for shared networks. If you try with the API you get an http error 431: "NetworkOffering and domain suffix upgrade can be performed for Isolated networks only".

**Comment by Hector-Work** [comment]
Thanks for your reply @DaanHoogland. What is the reason behind this?

**Comment by DaanHoogland** [comment]
@Hector-Work , I am not completely sure, the code that prevents this is more then ten years old, but IIRC, a shared network is shared so updating a domain suffix for all users would be kind of rude. I see no technical impediment. Maybe a DB hack could be done? (I didn't just write that text right now!)

**Comment by Hector-Work** [comment]
Thanks @DaanHoogland, I see where you're coming from, though I would argue that having to create a new network with the correct network domain and then migrate all user instances on to it (with the associated downtime and reconfiguration) is also kind of rude!

I will try your suggested (or not) unofficial method :)

**Comment by DaanHoogland** [comment]
You are absolutely right @Hector-Work and I think I would be rude not to consider this a valid feature request. I am thinking implementing a setting that will allow changing if set to true (default false) I really do not see any reason not to but am being conservative.

**Comment by Hector-Work** [comment]
Thanks @DaanHoogland. I have been able to make the change directly through the database for now, so as a workaround it is doable.

**Comment by DaanHoogland** [comment]
@JoaoJandre #9585 is ready to merge, can we include it in 4.20?

**Comment by JoaoJandre** [comment]
> @JoaoJandre #9585 is ready to merge, can we include it in 4.20?

As this was a simple feature block that only required a few changes, we can include it.
