### ISSUE TITLE
UI: guest network options greyed out

### ISSUE THREAD

**Issue by poddm** [apache/cloudstack#9413]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.1
~~~

##### SUMMARY

After upgrading to 4.19.0.1 (from 4.18).  The following UI components are greyed out and no longer accessible to non-admin users.
- update network
- restart network
- delete network

##### STEPS TO REPRODUCE

~~~
As a non Admin user, create and then view a guest network in the UI.  Options are greyed out.
~~~

##### EXPECTED RESULTS

~~~
Pre 4.19 users had the ability to manage a guest network.
~~~

##### ACTUAL RESULTS

~~~
see screenshot.
~~~
![Screenshot 2024-07-17 at 4 33 42 PM](https://github.com/user-attachments/assets/ab257a5b-dece-4565-b3e5-59b4da17d19c)

**Comment by poddm** [comment]
I believe the issue is related to these UI changes.
- https://github.com/apache/cloudstack/pull/7434/files#diff-cd0d475eaf2cb0977840c06248dcf621d5203a63092c0160f7ad3d8277cd627b

```javascript
disabled: (record, user) => { return (record.account !== user.userInfo.account && !['Admin', 'DomainAdmin'].includes(user.userInfo.roletype)) },
```

**Comment by weizhouapache** [comment]
it works for me
![image](https://github.com/user-attachments/assets/99f271da-2ee0-4873-a0d2-3ca224a04d23)

**Comment by rohityadavcloud** [comment]
@poddm can you check for your account role permissions, are those APIs (action) unavailable for your logged in user?

**Comment by poddm** [comment]
I double checked the account role and project permissions.  The user is granted `allow` to these APIs updateNetwork, listNetworks and deleteNetwork.

Additionally, I am able to use `CMK` to update and delete these networks which doesn't align to the UI being greyed out.

**Comment by poddm** [comment]
@weizhouapache, can you share the API response for listnetworks?  I don't see the `account` field returned on my instance.

**Comment by weizhouapache** [comment]
> @weizhouapache, can you share the API response for listnetworks?  I don't see the `account` field returned on my instance.

@poddm 
The account is not returned in project networks. Instead of it, projectid and project name are returned.

I am able to reproduce the issue when click a network in project view.

**Comment by rohityadavcloud** [comment]
@poddm can you check in a different browser or in incognito mode? It appears you're likely in a project, and projects can have their own project level roles types & permissions - can you check if that's the case?
