### ISSUE TITLE
Some java classes use "java.security.InvalidParameterException" which should be "com.cloud.exception.InvalidParameterValueException"

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#9436]
just for cleanup 

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~
4.20
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by sureshanaparti** [comment]
good catch @weizhouapache , updated to proper exception here: https://github.com/apache/cloudstack/pull/9455
