### ISSUE TITLE
Whole snapshot chain is lost when the latest snapshot is deleted

### ISSUE THREAD

**Issue by JoaoJandre** [apache/cloudstack#9446]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
4.19.1
4.19.2
main
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Env with XenServer

##### SUMMARY
When deleting a snapshot on XenServer, all of its parents will be erased, causing data loss. 

##### STEPS TO REPRODUCE

~~~
1. Create a VM
2. Take a volume snapshot (S1).
3. Access the VM and write some data, for example with: dd if=/dev/zero of=test bs=1M count=1000
4. Use sync to make sure data is written to disk
5. Take a second volume snapshot (S2).
6. Delete the last volume snapshot (S2).
~~~

##### EXPECTED RESULTS

~~~
Only the last volume snapshot (S2) is deleted.
~~~

##### ACTUAL RESULTS

~~~
On the UI, only the last volume snapshot (S2) is deleted. However, actually, the whole snapshot chain is deleted (S2 AND S1). This can be verified directly on storage or through the snapshot_store_ref table. Any operation with the deleted snapshot (S1) will fail.
~~~

**Comment by rohityadavcloud** [comment]
@JoaoJandre do you know if this was a regression in 4.19(.1) or did it happen also with earlier versions?

**Comment by JoaoJandre** [comment]
@rohityadavcloud this regression was introduced in 4.19.0.0 (#7873)
