### ISSUE TITLE
Button and Menus display label references, not the label text

### ISSUE THREAD

**Issue by d834256** [apache/cloudstack#9454]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0
~~~

##### CONFIGURATION

Installed from packages as per the install document at https://docs.cloudstack.apache.org/en/latest/installguide/management-server/index.html

##### OS / ENVIRONMENT

Redhat 9.3, plow, x64

##### SUMMARY

Incorrect button and menu labels.

##### STEPS TO REPRODUCE

Install cloudstack from RHEL9 repo as per install guide.

~~~

~~~

##### EXPECTED RESULTS

~~~
The actual text for the labels should be appearing not the reference to the label.


~~~

##### ACTUAL RESULTS

The button labels and some of the menu items look like they're not populating correctly. I tried a separate install using Ubuntu and I found the same behaviour. Problems are indicated by names like label.object.storage, label.create, label.vnf.applicances etc. 

![Untitled](https://github.com/user-attachments/assets/cb6c52f2-64e6-48c4-9e85-385fec968b5e)
![Screenshot 2024-07-26 101927](https://github.com/user-attachments/assets/3b01171a-6655-411d-bedc-0d6bc43bde7c)
![Screenshot 2024-07-26 102515](https://github.com/user-attachments/assets/bac042f3-5995-4860-92e1-9d369ce60feb)
![Screenshot 2024-07-26 102531](https://github.com/user-attachments/assets/85886be6-c843-40a7-8cea-b5e63923b0d7)

~~~

~~~

**Comment by shwstppr** [comment]
@d834256 is this an upgraded environment? Have you tried logging in after clearing browser cache/incognito tab?

**Comment by d834256** [comment]
> @d834256 is this an upgraded environment? Have you tried logging in after clearing browser cache/incognito tab?

To answer your question - they're fresh installs from ISO and updates applied. 

Though, I have been testing previous versions. Taking your advice I tried using a separate browser (sorry, should have tried this first) and the labels display correctly so it is a caching issue. Thank you!

**Comment by rohityadavcloud** [comment]
Closing on your remarks.
