### ISSUE TITLE
Incorrect log statement for Deployment planner

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9497]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Log
~~~

##### CLOUDSTACK VERSION

~~~
4.19.x
Mostly all versions
~~~

##### SUMMARY

CloudStack logs 'DeploymentPlanner allocation algorithm: null' for instance deployment async jobs although the correct deployment planner is used as per 'vm.deployment.planner'. 

##### STEPS TO REPRODUCE

~~~
1. Deploy an instance
2. Check the logs for the job
~~~

##### EXPECTED RESULTS

~~~
Logging should print the correct deployment planner
~~~

##### ACTUAL RESULTS

~~~
It always logs 'null' for deployment planner
~~~

Example: 

`2024-08-07 07:33:13,456 DEBUG [c.c.d.DeploymentPlanningManagerImpl] (API-Job-Executor-1:ctx-fcfd4f0d job-96 ctx-e5e1c26a) (logid:849ff926) DeploymentPlanner allocation algorithm: null
`

**Comment by weizhouapache** [comment]
the line has been removed in 4.20/main by #7214 
it is no longer an issue with 4.20/main
