### ISSUE TITLE
cloudstack-agent-4.19.1.0  run error  ，Unable to find the guid 

### ISSUE THREAD

**Issue by JustUse** [apache/cloudstack#9514]
[root@cloudstack ~]# /usr/bin/java -Djava.io.tmpdir=/usr/share/cloudstack-agent/tmp -Xms256m -Xmx2048m -cp /usr/share/cloudstack-agent/lib/*:/usr/share/cloudstack-agent/plugins/*:/etc/cloudstack/agent:/usr/share/cloudstack-common/scripts com.cloud.agent.AgentShell
log4j:WARN No appenders could be found for logger (com.cloud.agent.AgentShell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INFO  [cloud.agent.AgentShell] (main:) (logid:) Agent started
INFO  [cloud.agent.AgentShell] (main:) (logid:) Implementation Version is 4.19.1.0
INFO  [cloud.agent.AgentShell] (main:) (logid:) agent.properties found at /etc/cloudstack/agent/agent.properties
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Unable to find the guid

[root@cloudstack ~]# cat  /etc/cloudstack/agent/agent.properties | grep -v '#'
guid=
resource=com.cloud.hypervisor.kvm.resource.LibvirtComputingResource
workers=5
host=localhost
port=8250
cluster=default
pod=default
zone=default
local.storage.uuid=
domr.scripts.dir=scripts/network/domr/kvm
hypervisor.type=kvm
iscsi.session.cleanup.enabled=false
[root@cloudstack ~]# 

how can i resolve this problem？thank you very much ！！

**Comment by DaanHoogland** [comment]
@JustUse , the text "Unable to find the guid" occurs only in exceptions that should be logged more extensively to see the stacktrace. Could you edit the log4j.xml file to up the loglevel, please?

Did you start the agent with that command or use the initscript (or add it in cloudstack first)?

**Comment by JustUse** [comment]
> @JustUse , the text "Unable to find the guid" occurs only in exceptions that should be logged more extensively to see the stacktrace. Could you edit the log4j.xml file to up the loglevel, please?
> 
> Did you start the agent with that command or use the initscript (or add it in cloudstack first)?

hi，i found that when  running cloudstack-agent.service and failed in two seconds. is it need to initscript ?  how can i initscript  this?

**Comment by JustUse** [comment]
> @JustUse , the text "Unable to find the guid" occurs only in exceptions that should be logged more extensively to see the stacktrace. Could you edit the log4j.xml file to up the loglevel, please?
> 
> Did you start the agent with that command or use the initscript (or add it in cloudstack first)?

`sed -i 's/INFO/DEBUG/g' /etc/cloudstack/agent/log4j-cloud.xml`
[(https://cwiki.apache.org/confluence/display/CLOUDSTACK/KVM+agent+debug)]

**Comment by DaanHoogland** [comment]
@JustUse the field 
```
guid=
```
should have a value in the agent properties file. Did you add the host to cloudstack?

I am not sure, but I think  you can make one up and start it.
