### ISSUE TITLE
listServiceOfferings does not show custom offering of running instance

### ISSUE THREAD

**Issue by sbrueseke** [apache/cloudstack#9519]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.1
~~~

##### CONFIGURATION

enable.dynamic.scale.vm enabled

##### SUMMARY

I want to scale a running instance using a custom service offering on a kvm host via UI. This worked in earlier versions, at least in 4.19.0.1. It is not working in 4.19.1.1. Root cause is that listServiceOfferings does not show the custom offering for a running vm. UI will prompt: "It's not possible to scale up Instances that utilize KVM hypervisor with a fixed compute offering." because of this.

api call scaleVirtualMachine is able to scale the running instance.

##### STEPS TO REPRODUCE

~~~
1. enable enable.dynamic.scale.vm in global settings
2. Create a custom offering with dynamic scale enabled
3. Start an instance using this offering
4. Click the scale icon and pop-up with prompt will appear
~~~

##### EXPECTED RESULTS

~~~
Custom service offering will be shown in pop-up after clicking on scale icon
~~~

##### ACTUAL RESULTS
![scalepopup](https://github.com/user-attachments/assets/d0aca1c8-7af7-45cb-926c-8750b79f8b04)

**Comment by rp-** [comment]
Is this maybe related to #9894

**Comment by sbrueseke** [comment]
> Is this maybe related to #9894

yes, looks like this is the root cause of it.

**Comment by DaanHoogland** [comment]
As #9894 is merged, can you check if your issue is gone @sbrueseke ? (and close this issue?)
