### ISSUE TITLE
[linstor] Fail to revert or delete instance snapshot in case of migrated volumes

### ISSUE THREAD

**Issue by wornet-mwo** [apache/cloudstack#9522]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0
~~~

##### CONFIGURATION

linstor storage with LVM as backend is used, a second storage is required to reproduce.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Volumes in ACS are created using a path in linstor. That path differs if the volume is not initially created on linstor. However the volume uuid is used for vm snapshot deletions and reverts.

##### STEPS TO REPRODUCE

* create an instance outside the linstor storage
* migrate the instance to linstor
* create an instance snapshot
* try to delete or revert the snapshot
* get an error including stacktrace in the management log stating the ResourceGroup named after the volume uuid is missing

##### EXPECTED RESULTS

* The instance snapshot should be either reverted or deleted depending on the action

##### ACTUAL RESULTS

See steps to reproduce.

##### additional notes
This is a issue for a pull request which is already in preparation.

**Comment by DaanHoogland** [comment]
fixed by 9528
