### ISSUE TITLE
Template Upload from local depends (wrongly) on the routes being added for internal sites

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#9530]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1 tested, haven't reproduced/tested it in newer versions (but somewhat sure it's still there)
~~~

##### CONFIGURATION

- Ensure a wrong value/unreachable network CIDR is set as "secstorage.allowed.internal.sites" e.g. set a value "10.16.30.16/24" (wrong CIDR notation btw). 
- When uploading templates from local, SSVM will fetch the data from the browser, then it will try (for whatever reason/bug) to create routes towards the CIDR defined in the "secstorage.allowed.internal.sites" - but the OS will fail to add such route due to the combination of a wrong CIDR value in the global setting (and perhaps Pod management network gateway)
- This result with the error below in the SSVM log, after which the template is left/stuck in the NotUploaded state:

`2024-08-12 07:11:45,428 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-4-1:null) [id: 0xb5b790d0] CLOSE()
2024-08-12 07:11:45,430 INFO  [handler.logging.LoggingHandler] (nioEventLoopGroup-4-1:null) [id: 0xb5b790d0] UNREGISTERED
2024-08-12 07:11:45,435 INFO  [storage.resource.NfsSecondaryStorageResource] (Thread-4:null) shutting down post upload server
2024-08-12 07:11:53,237 WARN  [storage.resource.NfsSecondaryStorageResource] (agentRequest-Handler-4:null) Error in configuring route to internal ip err=Error: Invalid prefix for given prefix length.`

Routes should not be added during Upload from Local - they are/should be added when downloading a template from a URL (ideally, routes should be added during starting of the SSVM, but I guess that is not the topic now)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rohityadavcloud** [comment]
Fixed by https://github.com/apache/cloudstack/pull/9567
