### ISSUE TITLE
adding KVM primary disk for a host is not possible from UI

### ISSUE THREAD

**Issue by dredknight** [apache/cloudstack#9533]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### CONFIGURATION

Cloudstack with KVM hypervisors.

##### OS / ENVIRONMENT

NA

##### SUMMARY

When trying to add new primary storage from UI with a host scope, the user cannot select the desired host. The UI shows only 1 available host and that is the host from the first cluster in the zone, disregarding the Cluster field filter.

##### STEPS TO REPRODUCE

~~~
Go to  UI -> Infrastructure -> Primary storage -> Select "Add Primary Storage"
Chose:
- Scope: Host
- Cluster: Select a cluster with KVM host
- Host: Try to select proper host from the cluster.
~~~

##### EXPECTED RESULTS

~~~
The UI to present hosts from the selected cluster.
~~~

##### ACTUAL RESULTS

~~~
The UI is presenting host from the first cluster in the zone disregarding the cluster filed filter.
~~~

**Comment by rajujith** [comment]
@dredknight  If you are trying to add local storage as primary storage, you can enable 'Enable local storage for User Instances' and then try using the CMK or API to add the storage. Make sure to use compute and disk offerings with local storage type.  I do see there is an issue filtering the host in UI.

**Comment by dredknight** [comment]
Thank you @rajujith!
