### ISSUE TITLE
Dynamic scaling improvement for VMware

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#9555]
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.19
~~~

##### CONFIGURATION

Instance with dynamic scaling enabled. 

##### SUMMARY

Currently, dynamic scaling enabled instances get created at the vCenter with CPU and Memory hot add enabled but there is no user-friendly way to manage the limits. Some values get applied on the instances on vCenter and beyond that scale-up won't work.
It would be good to manage this better either by taking the limit value from the user to allowing the value to the updated through Cloudstack per instance.

**Comment by harikrishna-patnala** [comment]
@rajujith I'm keeping the notes below based on our discussion privately. If you agree for this, we can close the issue.

The "Limit" value is not related to the dynamic scaling or hot add feature. It is a setting for memory on a VM allows you to specify the maximum amount of memory that the VM can use, regardless of the amount of memory that has been allocated to the VM. If the utilization crosses the limit, then it will be swapped with disk.

The maximum value which anyone can dynamically scale the VM is 16times of the memory when the VM is started. This is given from the VMware documentation. https://knowledge.broadcom.com/external/article/343190/cannot-hot-add-more-than-3gb-to-linux-64.html

So setting limit value will not have any effect on the hot add limit.

For CS to provide a way to configure this limit I think it will degrade the VMs performance later at some point. If multiple VMs on the same host are configured with "Unlimited" memory limits and high memory allocations, this can lead to resource contention. If the host does not have enough physical memory to satisfy the needs of all VMs, some VMs might experience performance degradation or may need to swap memory to disk.
