### ISSUE TITLE
Autoscale Source Based Sticky Session Doesnt Always Work

### ISSUE THREAD

**Issue by btzq** [apache/cloudstack#9583]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Virtual Router
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.1
~~~

##### SUMMARY

Note, this bug is intermittent, because we only encounter this issue on and off. But often enough to know it is a bug.

We have 50 AutoscaleGroups within a single VR, and a good portion of them require Source Based Sticky Session. 

But on and off, the SourceBased Sticky Session doesnt work unless the VMs under Autoscale Group are all deleted, and started up again. 

##### STEPS TO REPRODUCE

~~~
- Create Autoscale Group, with multiple VMs, and no Sticky Session
- Ensure Autoscale Group is still enabled, and VMs are running.
- Disable Autoscale Group (but do not delete VMs)
- Change Load Balance Rule Sticky Session to -> Sourcebased
- Turn on Autoscale Group

The result, is that the SourceBased Sticky Session does not work. 

For us, to overcome the issue, we had to:

- Disable Autoscale Group
- Delete All VMs (Results in downtime)
- Enable Autoscale Group and let is recreate all the VMs

Only then, the SourceBased StickySession works.
~~~

##### EXPECTED RESULTS

~~~
To be able to change Sticky Session without having to destroy all VMs
~~~

##### ACTUAL RESULTS

~~~
Unable to change Sticky Session if it is SourceBased
~~~

**Comment by DaanHoogland** [comment]
fixed in #9822
