### ISSUE TITLE
Repeated "Network domain" field in "Add Network" form

### ISSUE THREAD

**Issue by msinhore** [apache/cloudstack#9603]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### OS / ENVIRONMENT

Any

##### SUMMARY

When adding a new isolated network, there are repeated Network domain fields for Isolated networks. 
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
One field for "Network domain"
~~~

##### ACTUAL RESULTS

![image](https://github.com/user-attachments/assets/ab51245c-514b-4970-8eed-68b5240314df)

**Comment by DaanHoogland** [comment]
@msinhore , can you check main? I think this was fixed.

**Comment by BryanMLima** [comment]
Hey @DaanHoogland @msinhore, this was fixed in this PR https://github.com/apache/cloudstack/pull/8919#issuecomment-2072426719, though, it will only be available in version 4.20.

**Comment by DaanHoogland** [comment]
fixed in #897

**Comment by SviridoffA** [comment]
Hello everyone! Is this fix planned for 4.19.3? It seems to be missing in 4.19.2.

**Comment by DaanHoogland** [comment]
> Hello everyone! Is this fix planned for 4.19.3? It seems to be missing in 4.19.2.

no @SviridoffA , it is in 4.20

**Comment by SviridoffA** [comment]
@DaanHoogland 
Got it… thanks for the answer.

**Comment by DaanHoogland** [comment]
> [@DaanHoogland](https://github.com/DaanHoogland) Got it… thanks for the answer.

to be clear, you are free to backport and submit a PR. it is just not planned at the moment. For now a 4.20.1 is planned (but it is already in 4.20.0)
