### ISSUE TITLE
Cannot add Rocky8 KVM host

### ISSUE THREAD

**Issue by Jonlli** [apache/cloudstack#9620]
When adding to the last step, it prompts that the server resources on the IP cannot be found.
Centos7.9 working well. 
Who can tell me why? The official documentation says it supports Rocky8, but why can't it be added to the host

**Comment by weizhouapache** [comment]
@Jonlli 
It does support rocky8 and 9.

Have you configured linux bridges manually ?

**Comment by Jonlli** [comment]
yeah ,  bridges working

I checked all the configurations, the compute nodes, and the bridge configurations are working fine, but I still can't drop the compute node to join the control end

**Comment by Jonlli** [comment]
I reinstalled the bridge mode of centos7, and it can join the control node normally.

**Comment by Jonlli** [comment]
we have solved it. you can close the ticket

**Comment by DaanHoogland** [comment]
@Jonlli can you descrivbe what the issue was, for others to learn?

**Comment by weizhouapache** [comment]
> @Jonlli can you descrivbe what the issue was, for others to learn?

this could be the same issue in the mailing list
https://lists.apache.org/thread/xqp3db72phhrmhgt0kvpx8yzt7rr13v8

as suggested by @NuxRo 
```
Add the following to /etc/libvirt/libvirt.conf :
remote_mode="legacy"

Then restart services.
```
