### ISSUE TITLE
UI: Unable to create a domain when networkdomain is mentioned and cleared

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9623]
ISSUE TYPE

BUG 

Component Name

UI

CLOUDSTACK VERSION

Cloudstack version 4.19

SUMMARY

UI: Unable to create a domain when networkdomain is mentioned and cleared

Steps to reproduce the issue

1.  Navigate to Domains  > Create domain >  mention network domain

![Screenshot 2024-09-02 at 3 54 43 PM](https://github.com/user-attachments/assets/a211dbe1-c327-4a8e-bf38-c06ce75bae39)

2. Clear the network domain field 

![Screenshot 2024-09-02 at 3 55 49 PM](https://github.com/user-attachments/assets/3c8b3480-5ae5-47e8-a761-dd1ab85ddee7)

3. Create the domain 

Exception 

![Screenshot 2024-09-02 at 3 47 00 PM](https://github.com/user-attachments/assets/d074efdb-cc2c-4762-b714-b8362f195e2c)

4. Exception error message  431

![Screenshot 2024-09-02 at 3 52 58 PM](https://github.com/user-attachments/assets/7b5c3f09-6ab9-48e7-9583-e851ce8ed0e6)

![Screenshot 2024-09-02 at 3 53 14 PM](https://github.com/user-attachments/assets/6f8f96d4-759a-448d-995e-c5f1339be003)

Actual Behaviour

The domain is not created 

Expected Behaviour

The domain should get created  when the networkdomain is cleared 

There is no issue with the API Call

**Comment by DaanHoogland** [comment]
fixed in #9637
