### ISSUE TITLE
instance start dialog does not react to ctrl-enter

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#9668]
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by JoaoJandre** [comment]
Fixed in #9743
