### ISSUE TITLE
List userdata with name or keyword not list anything

### ISSUE THREAD

**Issue by tanganellilore** [apache/cloudstack#9686]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 22.04 for cloudstack
KVM on Rocky linux

##### SUMMARY

If I use `listUserData` api for list all userdata everything works well, but if I use keyword or name to fitler data, i receive a empty list.
IAlso on UI the table is empty.

##### STEPS TO REPRODUCE

~~~
Call the `listUserData` with `keyword` or `name` param
~~~

##### EXPECTED RESULTS

~~~
Showed userdata filetr by keyworkd or name
~~~

##### ACTUAL RESULTS

~~~
Empty list
~~~

**Comment by weizhouapache** [comment]
fixed by #9751
