### ISSUE TITLE
dhcp-range not added in dnsmasq for multiple ip ranges for the guest physical network

### ISSUE THREAD

**Issue by vishesh92** [apache/cloudstack#9687]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

at least 4.18+
~~~

~~~

##### CONFIGURATION

Basic Zone with 2 different IP ranges for Guest Physical network.

##### SUMMARY

When 2 ip ranges are added for a guest physical network for a basic zone, the dnsmasq.conf on the VR has only 1 entry for dhcp-range which results in dhcp requests getting ignored if the VM's IP is in the second IP range.

##### EXPECTED RESULTS

~~~
dhcp-range in the dnsmasq.conf should have the same number of entries as the the number of ip ranges in the physical network.
~~~

##### ACTUAL RESULTS

~~~

dhcp-range in the dnsmasq.conf have only 1 ip range irrespective of number of IP ranges in the guest physical network.
~~~

**Comment by weizhouapache** [comment]
@vishesh92 
have you tested with 4.19.1.0 or later ?

**Comment by vishesh92** [comment]
> @vishesh92 have you tested with 4.19.1.0 or later ?

Yes. I tested with 4.18.1.1 & 4.19.1.1.

**Comment by vishesh92** [comment]
I debugged it a little more with help from @weizhouapache . Looks like this is the duplicate of https://github.com/apache/cloudstack/issues/8158

The extra dhcp-range options are set in `/etc/dnsmasq.d/cloud.conf`. For 4.18, only 1 entry is added irrespective of the number of ip ranges added in the physical network. But for 4.19, the number of entries are equivalent to the number of ip ranges added for the physical network.
