### ISSUE TITLE
Management server state not Down after management service stop [in main]

### ISSUE THREAD

**Issue by sureshanaparti** [apache/cloudstack#9722]
Management server state not Down after management service stop [in main], also noticed some components are not stopped during service stop. 

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Manager Components: ClusterManagerImpl, ClusterServiceServletAdapter, etc
~~~

##### CLOUDSTACK VERSION

~~~
4.20.0.0-SNAPSHOT
~~~

##### OS / ENVIRONMENT

MS OL8 + KVM OL8, Advanced Networking.

##### SUMMARY

Management server state not Down after management service stop [in main], also noticed some components are not stopped during service stop. 

Manager Components: ClusterManagerImpl, ClusterServiceServletAdapter, etc are not stopped. Didn't notice the below logs after stop.

```
stopping bean ClusterManagerImpl
stopping bean ClusterServiceServletAdapter
```

From 4.20.0.0-SNAPSHOT (Mgmt2 service stopped) =>

<img width="1262" alt="MgmtServers_4 20 0 0-SNAPSHOT" src="https://github.com/user-attachments/assets/9b2a3de5-a4e7-404a-bbc3-a6127d97052d">

```
sureshanaparti$ cat 4.20.0.0-SNAPSHOT_StoppingBeansCheck.txt | wc -l
    546
```

[4.20.0.0-SNAPSHOT_StoppingBeansCheck.txt](https://github.com/user-attachments/files/17102577/4.20.0.0-SNAPSHOT_StoppingBeansCheck.txt)

From 4.19.1.1 env (Mgmt2 service stopped) =>

<img width="1266" alt="MgmtServers_4 19 1 1" src="https://github.com/user-attachments/assets/b6e4a19f-fa93-43ca-9881-244590a41120">

```
sureshanaparti$ cat 4.19.1.1_StoppingBeansCheck.txt | wc -l
    636
```

[4.19.1.1_StoppingBeansCheck.txt](https://github.com/user-attachments/files/17102588/4.19.1.1_StoppingBeansCheck.txt)

##### STEPS TO REPRODUCE

- Created env with latest main / 4.20.0.0-SNAPSHOT
- Stop the management service from MS  host (`service cloudstack-management stop`) - Notice that management server state is still Up after service is stopped (check in DB - `SELECT id, name, msid, runid, service_ip, service_port, state, last_update, removed FROM cloud.mshost`).

##### EXPECTED RESULTS

~~~
MS state should be in Down state after management service stopped (and all manager components should be stopped for graceful service stop).
~~~

##### ACTUAL RESULTS

~~~
MS state is in Up state after management service stopped (and few manager components are not stopped).
~~~

**Comment by sureshanaparti** [comment]
@JoaoJandre @DaanHoogland I've noticed this issue in my testing, seems to be a critical one, maybe blocker if the management server state is considered during communication in multi-MS/clustered env.

**Comment by weizhouapache** [comment]
I remember we have noticed some other issues regarding the management server
- stopping management server takes 1 minute which is mucher longer than before (found by @DaanHoogland ?)
- OOM killer on cloudstack-management service (might it be related to this issue ? @sureshanaparti )

**Comment by sureshanaparti** [comment]
@weizhouapache this is not related to OOM killer, some components in the spring modules are not invoking stop during service stop. I could root cause the issue, working on the fix.

**Comment by weizhouapache** [comment]
> @weizhouapache this is not related to OOM killer, some components in the spring modules are not invoking stop during service stop. I could root cause the issue, working on the fix.

thanks @sureshanaparti 
I never faced the OOM killer issue in envs with only 1 mgmt server. 
Maybe it is also related to the multiple mgmt serverss
