### ISSUE TITLE
Ubuntu missing dependency libvirt-daemon-driver-storage-rbd

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#9797]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### OS / ENVIRONMENT
~~~
Ubuntu 22.04
~~~

##### SUMMARY

~~~
The cloudstack-agent deb file doesn't pull  libvirt-daemon-driver-storage-rbd as a dependency 
(although it does pull librados etc).
In envs with CEPH this leads to failing to connect to the storage pool
despite manual rbd commands working on the hypervisor.
~~~
##### STEPS TO REPRODUCE

~~~
apt install cloudstack-agent
~~~

##### EXPECTED RESULTS

~~~
apt pulls in libvirt-daemon-driver-storage-rbd as a dependency
~~~

##### ACTUAL RESULTS

~~~
Cloudstack couldn't start a VM on CEPH
~~~

**Comment by kiranchavala** [comment]
@NuxRo Yes encountered the same issue today 

Also, should the documentation be updated to include the following commands?

```
# ceph config set mon auth_expose_insecure_global_id_reclaim false

# ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false

# ceph config set mon auth_allow_insecure_global_id_reclaim false
```


https://github.com/apache/cloudstack/issues/5741#issuecomment-990669423

https://docs.cloudstack.apache.org/en/4.19.1.1/installguide/configuration.html

**Comment by weizhouapache** [comment]
> @NuxRo Yes encountered the same issue today
> 
> Also, should the documentation be updated to include the following commands?
> 
> ```
> # ceph config set mon auth_expose_insecure_global_id_reclaim false
> 
> # ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false
> 
> # ceph config set mon auth_allow_insecure_global_id_reclaim false
> ```
> 
> [#5741 (comment)](https://github.com/apache/cloudstack/issues/5741#issuecomment-990669423)
> 
> https://docs.cloudstack.apache.org/en/4.19.1.1/installguide/configuration.html

we could add a section in the doc for ceph storage

**Comment by NuxRo** [comment]
@weizhouapache @kiranchavala witnessed a few ceph client installs lately and none required those settings (Ubuntu 22.04), no idea honestly.. up to you.

**Comment by weizhouapache** [comment]
> @weizhouapache @kiranchavala witnessed a few ceph client installs lately and none required those settings (Ubuntu 22.04), no idea honestly.. up to you.

those settings are on ceph mgrs, not  ceph clients.

it is not a cloudstack issue
probably it is enough to add a `Note` in the doc
