### ISSUE TITLE
Cloudstack shouldn't allow to change a user's password if the user is of saml and ldap  from cloudstack

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9933]
ISSUE TYPE

Bug/Improvement request

COMPONENT NAME

Component: Improvement, UI,Bug

CLOUDSTACK VERSION

Cloudstack version 4.19.1.x

SUMMARY

Cloudstack shouldn't allow to change a user's password if the user is of saml and ldap  from cloudstack

Steps to reproduce the issue

1.  Have a cloudstack environment with Ldap and saml enabled 

2.  Make sure the ldap user and saml users are imported with a user role

3. Navigate to a ldap user /saml user , or login as a ldap/user. there is an option to change the password 

  
![Screenshot 2024-11-15 at 1 26 06 PM](https://github.com/user-attachments/assets/8126390a-8b61-423f-a438-aa7954d72a7f)

![Screenshot 2024-11-15 at 1 27 48 PM](https://github.com/user-attachments/assets/27c329e1-21fd-408a-9d0d-c386306592e3)

Previously Cloudstack  didn't allow to change the password of ldap or a small account 

![Screenshot 2024-11-15 at 1 32 39 PM](https://github.com/user-attachments/assets/d70f2c26-bfc8-4700-aba6-a84e4e5eb372)

Expected behaviour 

The update user API call shouldn't allow to change the password for ldap/saml user

https://cloudstack.apache.org/api/apidocs-4.19/apis/updateUser.html

Cloudstack shouldn't allow to change a user's password if the user is of saml and ldap  from cloudstack

Cloudstack should throw an exception message to contact the administrator

**Comment by DaanHoogland** [comment]
fixed in #9999
