### ISSUE TITLE
Cloudstack Management Upgrade

### ISSUE THREAD

**Issue by kenneth0595** [apache/cloudstack#9935]
ISSUE TYPE
Can't Upgrade Cloudstak

VERSION
From Cloudstack version 4.19.1.2 To 4.19.1.3

HYPERVISOR 
CentOS 7

REPO
[apache-cloudstack]
name=Apache CloudStack
baseurl=http://download.cloudstack.org/centos/$releasever/4.19/
enabled=1
gpgcheck=0

UPGRADE OUTPUT
# yum upgrade cloudstack-management
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: d2lzkl7pfhq30w.cloudfront.net
No packages marked for update

**Comment by weizhouapache** [comment]
the URL should be https://download.cloudstack.org/centos7/4.19/
