### ISSUE TITLE
ISO Uploading from local Not Ready

### ISSUE THREAD

**Issue by bwcxyk** [apache/cloudstack#9945]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI and possibly management server
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.3
~~~

##### CONFIGURATION

basic network

##### OS / ENVIRONMENT

Ubuntu 22.04

##### SUMMARY

Uploaded successfully but Not Ready

##### STEPS TO REPRODUCE

~~~
navigate to Images -> ISOs
Upload lSO from local
Use CentOS-7-x86_64-Minimal-2009.iso image

Problems with certificates when uploading.
Resolved with reference to https://github.com/apache/cloudstack/issues/8175#issuecomment-1794291710
Uploaded successfully, But ISO Not Ready
~~~

##### EXPECTED RESULTS

~~~
ISO Ready
~~~

##### ACTUAL RESULTS

~~~
ISO Not Ready
~~~

![image](https://github.com/user-attachments/assets/780ed505-dd21-4f07-9894-467b8435326b)
![image](https://github.com/user-attachments/assets/066eb3a3-9986-4501-b297-459540723f64)
![image](https://github.com/user-attachments/assets/ffc74f77-e273-4a92-8f7f-17fee488fe46)

**Comment by DaanHoogland** [comment]
@bwcxyk , have you checked the registration status in the iso-details?
I see you have another ISO registered. Was that one registered from URL or also from local?

**Comment by bwcxyk** [comment]
> @bwcxyk , have you checked the registration status in the iso-details? I see you have another ISO registered. Was that one registered from URL or also from local?

From URL, Iso-details how to view

**Comment by DaanHoogland** [comment]
> > @bwcxyk , have you checked the registration status in the iso-details? I see you have another ISO registered. Was that one registered from URL or also from local?
> 
> From URL, Iso-details how to view

from the ISO list click on the ISO you need and than click on Zones

**Comment by bwcxyk** [comment]
I redeployed it and it worked, maybe it was a virtualisation nesting issue
