### ISSUE TITLE
When adding a zone and selecting LXC type for the Hypervisor, the host cannot be added

### ISSUE THREAD

**Issue by maic** [apache/cloudstack#9972]
When adding a zone and selecting LXC type for the Hypervisor, the host cannot be added; The following is the specific error log information of the setup. log

OS ：ubuntu20.04.6

cloudstack version：4.18.0.0

<img width="667" alt="1732599885537" src="https://github.com/user-attachments/assets/bb3a2f17-50a4-45c6-9abf-52c3b28fa64a">

DEBUG:root:execute:uname -r
DEBUG:root:execute:uname -m
DEBUG:root:execute:hostname -f
DEBUG:root:execute:kvm-ok
DEBUG:root:execute:awk '/MemTotal/ { printf "%.3f \n", $2/1024 }' /proc/meminfo
DEBUG:root:execute:ip a | grep "^\w" | grep -iv "^lo" | wc -l
DEBUG:root:execute:service apparmor status
DEBUG:root:execute:apparmor_status |grep libvirt
DEBUG:root:execute:ln -s /etc/apparmor.d/usr.sbin.libvirtd /etc/apparmor.d/disable/
DEBUG:root:execute:ln -s /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper /etc/apparmor.d/disable/
DEBUG:root:execute:apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
DEBUG:root:execute:apparmor_parser -R /etc/apparmor.d/usr.lib.libvirt.virt-aa-helper
DEBUG:root:cloudbr0 is not a network device, is it down?
DEBUG:root:execute:sudo /usr/sbin/service network-manager status
DEBUG:root:Failed to execute:Unit network-manager.service could not be found.
DEBUG:root:execute:route -n|awk '/^0.0.0.0/ {print $2,$8}'
DEBUG:root:list index out of range
  File "/usr/lib/python3/dist-packages/cloudutils/serviceConfig.py", line 38, in configuration
    result = self.config()
  File "/usr/lib/python3/dist-packages/cloudutils/serviceConfig.py", line 211, in config
    super(networkConfigUbuntu, self).cfgNetwork()
  File "/usr/lib/python3/dist-packages/cloudutils/serviceConfig.py", line 108, in cfgNetwork
    device = self.netcfg.getDefaultNetwork()
  File "/usr/lib/python3/dist-packages/cloudutils/networkConfig.py", line 51, in getDefaultNetwork
    dev = result[1]

DEBUG:root:execute:sudo update-rc.d -f apparmor remove
DEBUG:root:execute:sudo update-rc.d -f apparmor defaults
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start
DEBUG:root:execute:sudo /usr/sbin/service apparmor status
DEBUG:root:execute:sudo /usr/sbin/service apparmor start

**Comment by weizhouapache** [comment]
@maic 
I think LXC is not used widely for now.  can you try KVM instead ?

The issue seems to be because you have not configured `cloudbr0` bridge

**Comment by maic** [comment]
KVM usage has always been normal, now we need to use LXC
