### ISSUE TITLE
Stored user data not selected when clicking its row in VM deployment form

### ISSUE THREAD

**Issue by winterhazel** [apache/cloudstack#9990]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
Tested on 4.20.0.0, probably on 4.19 as well
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In the VM deployment form, if a user tries to select a stored user data by clicking its corresponding row (outside the radio button), the user data does not get selected. Instead, the user has to click on the radio button. For other similar listings, clicking outside the radio button works.

##### STEPS TO REPRODUCE

~~~
1. Create a stored user data
2. Open the VM deployment form
3. Try to select a stored user data by clicking its row (not the radio button)
~~~

##### EXPECTED RESULTS

~~~
Stored user data gets selected
~~~

##### ACTUAL RESULTS

~~~
Stored user data does not get selected
~~~

**Comment by DaanHoogland** [comment]
@bernardodemarco as you self assigned, will you address this on the 4.20 branch or in main/21?

**Comment by bernardodemarco** [comment]
Closing this ticket since it was fixed by https://github.com/apache/cloudstack/pull/10016.
